### ISSUE TITLE
Installing latest version of react-storybook does not use webpack 2

### ISSUE THREAD

**Issue by ankurp** [storybooks/storybook#1002]
I installed the latest version of storybook using the following command `npm install @kadira/storybook@2.35.3` and when I examine the package.json of this package it does not use webpack 2. Do others also see this issue as when I look at the package.json of master I do see the dependency is set to webpack 2 https://github.com/storybooks/storybook/blob/master/packages/react-storybook/package.json#L62

**Comment by wardpeet** [comment]
Master is not the latest npm package, you can try installing through the master branch

**Comment by ankurp** [comment]
How can I install from master branch. This is a mono repo right with multiple packages?

**Comment by ndelangen** [comment]
Hey @ankurp thanks for the interest! It can be a little daunting and complex at first, we're working hard on getting a alpha release out asap.

If you don't feel like waiting you can clone the repo, bootstrap and then `npm link`. It's described [here](https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#testing-against-master). Let me know if you need further help. You can also ask on slack!  
Sorry if the documentation for this is still fairly limited.. We do appreciate the feedback!
