### ISSUE TITLE
Remove tracking

### ISSUE THREAD

**Issue by phillipj** [storybooks/storybook#1003]
Hi,

first of all fantastic project, I'm really enjoying it 👍 

I got curious as to why tracking was needed, so I tried to visit the URL displayed when I start storybook:

```bash
➜ npm run storybook

> clearing-ui@0.1.0 storybook /my/cra/project
> start-storybook -p 9009 -s public

@kadira/storybook v2.35.3

=> Loading static files from: /my/cra/project/public .
=> Using default webpack setup based on "Create React App".
=> Loading custom webpack config (full-control mode).

React Storybook started on => http://localhost:9009/

 We will collect some anonymous usage stats of how you use storybook.
 See why?: https://getstorybook.io/tracking
```

But https://getstorybook.io/tracking ends in a 404 page sadly 😞 

I'm more than willing to open a PR fixing it, if I only knew the correctly URL?

**Comment by tmeasday** [comment]
I'm not sure we have control of the reporting end point (we should figure that out @ndelangen?), but I think that URL went here: https://stats.getstorybook.io/

I guess we should update it to that in the meantime.

**Comment by ndelangen** [comment]
If someone wants to create a PR completely removing the tracking, I'm happy to merge that.

We'll gain insights by asking users.

**Comment by phillipj** [comment]
Thought I'd help out removing the tracking related code, but it doesn't seem to be included in the v3 source.

Therefore closing this as it's not a concern anymore.

Oh and thanks for your work getting v3 out, great work! 👍

**Comment by ndelangen** [comment]
Correct I already removed it, thanks for checking and closing issues 👍
