### ISSUE TITLE
Add option to disable Uglify.

### ISSUE THREAD

**Issue by hearnden** [storybooks/storybook#1005]
Uglify can't parse ES6 syntax, and the feature request to support ES6 syntax in Uglify is >3 years old (https://github.com/mishoo/UglifyJS2/issues/448).  For projects that feed ES6 source into Storybook (e.g., as output from `tsc` targetting ES6), Uglify gets in the way.

A configuration option to disable Uglify in Storybook's webpack config was suggested here: https://github.com/storybooks/storybook/issues/788#issuecomment-294299492, and would be a great help!

**Comment by ndelangen** [comment]
We can switch to babili plugin. I think that would solve both issues

**Comment by thuringia** [comment]
@ndelangen I created a PR for this, however, I did not create any configurability for the minifier.

**Comment by tesla3327** [comment]
I am running into this issue as well. Right now our workaround is to remove the UglifyJS plugin manually through "full-control" mode, which is a bit of an ugly hack.

Hopefully this can be merged soon?

**Comment by bigfish** [comment]
This will be in 3.2.0, right? Looking forward to that :)

**Comment by ndelangen** [comment]
@bigfish this is not a change about the be released with `3.2.0`, if you want to remove Uglify, you'll need to do so using webpack full control mode.

**Comment by bcomnes** [comment]
+1000 on this.  Would very much rather pass a single flag to turn things off than adopt full-control mode.

**Comment by ndelangen** [comment]
I will give this on my high priority list to work on after the 3.3 release. 

Related:
https://github.com/storybooks/storybook/issues/1570#issuecomment-345896597

**Comment by bcomnes** [comment]
Following up here, I dont recall the details, but updating some of our dependencies fixed the issues I was having that caused me to want to turn it off.

**Comment by Hypnosphi** [comment]
We actually use ES6-aware uglify since #2530
