### ISSUE TITLE
`yarn.lock` should not be listed in `.gitignore`

### ISSUE THREAD

**Issue by theinterned** [storybooks/storybook#1009]
I noticed that the yarn lock file is ignored. Is this on purpose? 

https://github.com/yarnpkg/yarn/issues/1583

**Comment by ndelangen** [comment]
It is, `yarn + lerna = trouble` for us right now.

You're free to use yarn to install in root, but lerna should be using npm.

We're caching `node_modules` in travis CI, so builds are already relatively fast, yarn is not that much faster in this case to warrant the issues when combining with lerna at this point.
