### ISSUE TITLE
Autoload all /.story.js$/

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#1013]
Instead of having consumers require every story file, we can do a glob-pattern match and auto-load.

This is consistent with how tools like jest work.

**Comment by aaronmcadam** [comment]
Another common idiom I see is `*.stories.js`, but I'd be happy if we agree on a single naming scheme.

**Comment by dikarel** [comment]
IMO it should be able to load any of:
`*.stories.js`, `*.story.js`, `story.js`, `stories.js`

**Comment by pierrecholhot** [comment]
I would rather have an addon that auto loads all my stories when instructed rather than have this behaviour applied by default

**Comment by danielduan** [comment]
I think the `*.jsx` extension should be added as well.

**Comment by UsulPro** [comment]
If we talk about add this pattern to "getstorybook" as default, I think It's great. It allows people to start writing stories just after adding storybook to their project but also lefts flexibility of manual customization

**Comment by danielduan** [comment]
I'm gonna toss it into the cli.

**Comment by ndelangen** [comment]
@danielduan that sounds great! 

In #1209 I'd also like the visit the idea of configuring this in a config, much like how you set a `testPattern` for jest.

**Comment by Hypnosphi** [comment]
Works in `3.3.0-alpha.4`

**Comment by JulienMalige** [comment]
Is there any reason for react-native not to be affected by this change ?
