### ISSUE TITLE
Possibility to add and addon to the list

### ISSUE THREAD

**Issue by wcastand** [storybooks/storybook#1014]
Hi, I did an addon for storybook and i would like to know if there is a possibility to add it to your list of addons ?
[storybook-addon-jsx](https://github.com/Kilix/storybook-addon-jsx)

If it's okay, i can make a PR to update the readme.

**Comment by shilman** [comment]
@wcastand awesome! here is a list of community addons. Please feel free to send a PR: 

https://github.com/storybooks/storybooks.github.io/blob/source/pages/docs/react-storybook/addons/addon-gallery/index.md

**Comment by wcastand** [comment]
Thanks, i made a PR. I close this issue then :)
