### ISSUE TITLE
Restore storybook-addon-links

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1016]
## What happened

1. We consolidated all packages into the monorepo
2. We marked all of the original package repos as deprecated
3. https://github.com/storybooks/storybook-addon-links did not get transitioned to the monorepo
4. I read a stale PR and assessed that `addon-links` was deprecated
5. I started to remove `addon-links` from the docs and from the code, e.g. https://github.com/storybooks/storybook/issues/1015

However, now as far as I can tell, the only problem was that addon-links was not properly ported to the monorepo.

## What needs to happen
- [x] addon-links ported to monorepo and tested
- [x] documentation updated to refer to addon-links as a standalone package
- [x] "built-in" `actions` and `linkTo` API should be deprecated (with 3.0?)

**Comment by mnmtanish** [comment]
Version 3.0 is a good time to remove actions and linkTo APIs from core. But let's add a warning log in when using these APIs and make sure it continues to work for now. It'll be no longer supported from v3.0 and we can remove it completely at a later version. What do you think?

**Comment by ndelangen** [comment]
I should merge `https://github.com/storybooks/storybook-addon-links` into the monorepo?
