### ISSUE TITLE
Deprecate addon-links and addon-actions as "built-in addons"

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1017]
## why

Built-in addons are confusing and are only there for backwards compatibility. For example, they generate confusion like this #1016, and multiple cases in the documentation etc.

Currently there are three types of addons:
- "built-in addons" (actions, links)
- "core addons" that are part of the storybooks monorepo but are not included by default (notes, info, etc.)
- "community addons" which are maintained in separate repos by community members

## what
I propose we:
- [x] remove actions and links as built-in
- [x] update the docs
 - [x] make the actions/links addons like normal "core addons"
 - [x] add migration instructions

Alternatively:
- [x] wrap the "built-in" versions with deprecation warnings
- [x] remove them in the 4.0 release (#1028 = followup)

Old-style code will break, but since we are doing a major version bump that's to be expected and we can add it to the migration guide.

**Comment by ndelangen** [comment]
I think removing them in 3.0.0 is do-able tbh.

**Comment by arunoda** [comment]
Okay. This looks great.
