### ISSUE TITLE
Webpack config not respected during static build when using `config-dir`

### ISSUE THREAD

**Issue by kirkstrobeck** [storybooks/storybook#1018]
**Given:**

- Storybook folder is at `/storybook`
- CLI command is `build-storybook --config-dir storybook --output-dir tmp/storybook --static-dir static`
- There is a custom webpack at `storybook/webpack.config.js` that functions as expected when running `start-storybook --config-dir storybook --port 6006 --static-dir static`
- Storybook version is `2.35.3`

**Expected:**

Static build to use custom webpack

**Actual:**

Static build does not use custom webpack

**Comment by tmeasday** [comment]
Hi @kirkstrobeck - would it be possible to create a simple reproduction, as outlined here: https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#reproductions ?

Much appreciated

**Comment by kirkstrobeck** [comment]
I’m closing this for now until I find out more, the issue seems to be a bit more far reaching. Bottom line, our static build looks quite different from the served version.
