### ISSUE TITLE
css loading issues (yes, I know, again)

### ISSUE THREAD

**Issue by zeroasterisk** [storybooks/storybook#1027]
Sorry, I suspect you're sick of these issues, especially since they are likely not the fault of storybook... 

If you take a look at this simple example:
https://zeroasterisk.github.io/react-eltoro-ui-budget

I loaded CSS from CDN via `head.html` (because that's what always works for me)

but 1 CSS file didn't exist on a CDN, so I had to import it, and I couldn't get it to work...

https://github.com/zeroasterisk/react-eltoro-ui-budget/blob/master/src/stories/index.js#L5-L10
```
// this isn't importing - getting funky errors
// import 'react-widgets/dist/css/react-widgets.css';
//   getting:
//   ERROR in ./~/css-loader!./~/raw-loader!./~/react-widgets/dist/css/react-widgets.css
//    Module build failed: Unknown word (1:1)
//    > 1 | module.exports = ".rw-btn,.rw-input{color:inherit;font:inherit;margin:0}
```

Here's the webpack config, user override:
https://github.com/zeroasterisk/react-eltoro-ui-budget/blob/master/.storybook/user/modify_webpack_config.js

----

any advice?  I've read through your docs several times and no luck.

**Comment by shilman** [comment]
@zeroasterisk where is react-widgets set up? I don't see it as a dependency in package.json.

**Comment by zeroasterisk** [comment]
@shilman for some reason, I thought `npm i --save-peer react-widgets` would work... oh well, I fixed...

**Comment by shilman** [comment]
Glad to hear you got it working! Closing for now 😄

**Comment by zeroasterisk** [comment]
@shilman sorry, sadly that wasn't a resolution, only something missing from my example. The original problem remains, but now you can recreate it easier.
