### ISSUE TITLE
Allow custom `test` function for storyshots

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#1034]
Currently, storyshots does two things: (a) it sets up a Jest test for each story, and (b) it defines the body of that test to be a vanilla snapshot test.

However, there are different things you may want to do in step (b), for instance:
 - Simply render the story, and ensure it doesn't throw an exception (https://github.com/storybooks/storybook/pull/917, https://github.com/storybooks/storybook/issues/547, https://github.com/storybooks/storybook/issues/1032)
 - Shallow render the story, and snapshot it (https://github.com/storybooks/storybook/issues/995)
 - Pass options to the rendering, especially `createNodeMock` (https://github.com/storybooks/storybook/issues/876, https://github.com/storybooks/storybook/issues/881, https://github.com/storybooks/storyshots/pull/98)

This issue proposes allowing configuring the body of the test (although keeping the current as the default). First proposed here: https://github.com/storybooks/storybook/pull/917#issue-222724618

There is a question of how to best implement this. The simplest thing is simply an option to `initStoryshots`:

```js
initStoryshots({
  test(story) {
    // make assertions (doesn't return anything).
  }
});
```

@theinterned made a suggestion around lifecycle methods [here](https://github.com/storybooks/storyshots/pull/98#issuecomment-299253374) -- can you provide a bit more detail about how that might be used?

In terms of implementing the use cases above, I would suggest we export "test bodies" that do the standard things from storyshots. So you could do

```js
import initStoryshots, { shallowSnapshot } from 'storyshots';

initStoryshots({ test: shallowSnapshot });
```

**Comment by tmeasday** [comment]
I implemented my suggestion in #1035, but we can do something else still.

**Comment by rogovdm** [comment]
>>> There is a question of how to best implement this.

@tmeasday maybe extract step b into an own package? And storyshots addon can be used on top of it. Other addons can be build too (like #1032 or else)

**Comment by tmeasday** [comment]
@rogovdm do you mean to extract [this file](https://github.com/storybooks/storybook/pull/1035/files#diff-172bbaff55905ef69d7ac0af4ed9871b) into its own package?

**Comment by ndelangen** [comment]
Is this done @tmeasday

**Comment by tmeasday** [comment]
Yes, that is what I meant by the `merge` label @ndelangen

**Comment by tmeasday** [comment]
Released with v3!
