### ISSUE TITLE
We need to open source our logo, and other art

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#1036]
We should add a new repo providing our source and good quality material for people to use.

For example if someone wants to promote storybook, there's almost no material.

I'm hoping @arunoda still has the source material for the logo.

This does not mean the material's copyright changes, it still belongs to kadira legally, though we're looking into giving it to the public domain possibly.

**Comment by arunoda** [comment]
Here's the [dropbox folder](https://www.dropbox.com/sh/5owqt5qcfhwle28/AAARaGMEXGbMMtpLPlGZ1MIDa?dl=0) for the logo.
It's has the original Sketch file.

**Comment by UsulPro** [comment]
Can we modify these logos or create derivatives based on them?
For example, use it to create `storybook-addon` badge?

**Comment by arunoda** [comment]
@UsulPro sure no problem.

**Comment by ndelangen** [comment]
Done
