### ISSUE TITLE
Detect and support Gatsby projects by getstorybook

### ISSUE THREAD

**Issue by UsulPro** [storybooks/storybook#1040]
As mentioned in https://github.com/gatsbyjs/gatsby/issues/633, we have successful experience of using Storybook with Gatsby. An example of such integration is @shilman's excellent work on updating our documentation website - https://github.com/storybooks/storybooks.github.io

At this moment getstorybook autodetects and has templates for following project types:
- React
- React-Native
- CRA projects
- Meteor projects

We can support Gatsby projects as well and create separated [template](https://github.com/storybooks/storybook/tree/master/packages/getstorybook/generators) based on our experience. For that we need to add Gatsby projects detection [here](https://github.com/storybooks/storybook/blob/master/packages/getstorybook/lib/detect.js).

**Comment by ndelangen** [comment]
We better make it Gatsby 1.0 compatible! I think this would be great!

**Comment by barbush** [comment]
Why is storybook support only in Typescript starter? Storybook support needs to be in the normal version
