### ISSUE TITLE
Custom head

### ISSUE THREAD

**Issue by kirkstrobeck** [storybooks/storybook#1041]
Would like the ability to add head.js instead of just [head.html](https://github.com/storybooks/storybooks.github.io/blob/source/pages/docs/react-storybook/configurations/add-custom-head-tags/index.md) so I can haz dynamic stuff.

**Comment by ndelangen** [comment]
I need more information to understand what it is you're requesting.

`head.html` can contain `<script>`s. 
Or do you need server side middleware?

Or would you rather have us require a module in which you can return html to use as head?

**Comment by kirkstrobeck** [comment]
> Or would you rather have us require a module in which you can return html to use as head?

That one! 😀

**Comment by ndelangen** [comment]
Would you be interested in creating a PR @kirkstrobeck ?

**Comment by ndelangen** [comment]
Will consider this for #1209
