### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ajhyndman** [storybooks/storybook#1042]
As a result of #996, the README seems to be out of date.  Multiple links toward the bottom of the document point to incorrect folders.  I'm not sure how much else I can trust.  As a wannabe user, I'd like to know how storybook works now!

**Comment by shilman** [comment]
Thanks @ajhyndman ! Submitted a quick fix to get things back in order.

**Comment by UsulPro** [comment]
fixed in #1043

**Comment by ajhyndman** [comment]
Awesome! 🎉
