### ISSUE TITLE
npm i -g @storybook/cli not working

### ISSUE THREAD

**Issue by knottronix** [storybooks/storybook#1045]
Hi there, Sorry if this is something I am doing wrong, I am reasonably new to NPM, however running the install instructions "npm i -g @storybook/cli" fails on both windows and mac.

sudo npm i -g @storybook/cli
Password:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "i" "-g" "@storybook/cli"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! Cannot read property 'path' of null

Windows says @storybook/cli is not in the NPM registry. 

I assume CLI is a command line package utility? That then finds and installs storybook from git hub? Anyway, any help greatly appreciated!

**Comment by UsulPro** [comment]
Hi @knottronix 

we're in the big process of releasing Storybook v3 now.
and this package didn't published yet

you can use this instead:

https://github.com/storybooks/getstorybook

it depricated but it's the last published version at this moment

**Comment by knottronix** [comment]
Many thanks Oleg.

Does the deprecated version work with React Native?

Thanks again for the quick response.

Cheers,

Andrew

**Comment by UsulPro** [comment]
Andrew, I didn't try it personally, but yes, it has a template for react native.

I will close this issue. Feel free to reopen this if any questions still left or open a new one related react-native

**Comment by knottronix** [comment]
Many thanks!
