### ISSUE TITLE
Sequence of props

### ISSUE THREAD

**Issue by khankuan** [storybooks/storybook#1048]
Hi, thanks for building the project. I'm wondering if there are support or addons to
1) manage a sequence of props
2) helpers to manage a demo with state <- should i simply write a demo component?

Cheers!

**Comment by ndelangen** [comment]
Can you explain what you mean with "a sequence of props"?

So helper elements we usually call `decorators`. And it's really common to write some to get a component to render in a specific way.

What sort of state are we talking about?

🍻 !

**Comment by khankuan** [comment]
Hi, here is what I meant as an example: 
```
story.sequence({
  title: 'User doing an action'
}, [{
  title: 'Initial',
  update: () => ({
    name: 'John',
    actions: ['Add as friend', 'Message'],
    onActionClick: story.handler('onActionClick')
  })
}, {
  title: 'Card becomes expanded (after 1 sec)',
  update: async function(props) {
    await delay(1000)
    props.expanded = true
  }
}, {
  title: 'User clicks on Message action',
  update: (props, ref) => {
    const message = ref.props.actions[1]
    ref.handleActionClick(message)
  }
}])
```
I thought it would be nice to be able to update props to allow for state changes in stories. I'm also wondering how are people writing stories that require state change currently, do they do it by created a demo component that encapsulate the state?

references
https://github.com/khankuan/react-catalog/blob/master/docs/src/UserCard/UserCard.story.jsx#L23
https://khankuan.github.io/react-catalog/#/All/UserCard/User%20doing%20an%20action

Cheers!

**Comment by ndelangen** [comment]
I'm looking at your examples, and I do not see anything related to storybook... Am I going mad and or blind ?

This `story.sequence`, is not a part of storybook `¯\_(ツ)_/¯`

I'm not sure what to do about this, I can't support another similar product. I hope you find the answers you are looking for. Let me know if I have indeed gone mad, and it's actually storybook we're looking at in your examples! 💙

**Comment by khankuan** [comment]
Hi, you've misunderstood. I wanted to know how do everyone deal with prop changes in their stories. The example above is not part of react storybook, but a library that is similar. In the example, i have a story that has multiple steps (each step has its own props). I wonder what others are doing if they have stories where there are prop changes. 

Cheers.

**Comment by ndelangen** [comment]
Sorry for the misunderstanding.

Props only change when changed by an outside, so in storybook terms that would be a decorator.

A decorator would be a stateful component changing the props on the component in the story.

In storybook we use addons to supply storybook with decorators. 

An good example of such addon is [addon knobs](https://github.com/storybooks/storybook/tree/master/addons/knobs)

Is this what you are looking for?

**Comment by khankuan** [comment]
Hi, thanks. Knobs are great, but not exactly what I'm looking for. In knobs, the viewer adjust the props accordingly. What I'm looking for is a pre-setup sequence of props that the viewer can walk through, step by step without having to know which knob to turn to achieve the full ux flow for a story. For example, there could be a story that showcases the ux flow for a user inputing a value into a TextField:
```
// step 1
props = { value: null, placeholder: 'Type something' }
// step 2: user enters an invalid input
props = { value: 'test', placeholder: 'Type something', errorText: 'Username is already taken' }
// step 3: user corrects the input
props = { value: 'test123', placeholder: 'Type something', successText: 'Username is valid' }
```
Thanks for the tip on decorators. I'll look into it further.

Cheers

**Comment by ndelangen** [comment]
Ah I think I get it now,

Yeah what you'd want to do is have a list of props and send them to a component over time.
That's a excellent responsibility for a decorator.

You could start by just writing a component that will take a list of objects and a component and a interval. At each interval it should pick and object from the list and use it as props for the component.

Let me know if you need help getting that working?

We could create a fancy addon for it even with a time-bar?

**Comment by khankuan** [comment]
I like the interval and time-bar idea. Any thoughts on how it would hook up with storyshots? In the library above, I had each step taken as a snapshot in test generation.

**Comment by sht5** [comment]
@khankuan adding my solution
```

import React, {Component} from 'react';
import PropTypes from 'prop-types';

class ChangingPropsSimulator extends Component {
    
    constructor(props) {
        super(props);
        this.state = {
            propsObjIndex: 0
        }
        const {propsArray} = props;
        setInterval((() => {
            this.setState({
                propsObjIndex: (this.state.propsObjIndex + 1) % propsArray.length
            });
        }).bind(this), 5000)
    }
    
    render() {
        const {propsArray, Component} = this.props;
        const currentProps = propsArray[this.state.propsObjIndex];
        return (
            <Component {...currentProps}/>
        );
    }
};

ChangingPropsSimulator.propTypes = {
    Component: PropTypes.node.isRequired,
    propsArray: PropTypes.array.isRequired
}

export default ChangingPropsSimulator
```

@ndelangen would this be beneficial to docs? maybe i can make a pull request if so.
