### ISSUE TITLE
[3.0.0alpha] build-storybook no longer supports relative paths

### ISSUE THREAD

**Issue by ajhyndman** [storybooks/storybook#1052]
It looks like the build-storybook executable is passing a relative path as-is to Webpack 2 as an output location.  Webpack 2 seems to require that this be resolved to an absolute path:

https://webpack.js.org/configuration/output/#output-publicpath

I'd like to see the same relative output pathname supported via command line.  Nobody wants an absolute path committed in the `package.json` of their project.  I'm hoping this can be resolved programatically inside the webpack config reconciliation?

```
$ build-storybook -c local_modules/storybook/ -o ./docs/storybook 
@storybook/react v3.0.0-alpha.0

=> Loading custom webpack config (extending mode).
Building storybook ...
/Users/work/Projects/mathspace-1/node_modules/webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./docs/storybook" is not an absolute path!
```

**Comment by chrvadala** [comment]
Same problem. A possible workaround is:
`"build-storybook": "build-storybook -s public -o ${PWD}/prova"`

**Comment by unutoiul** [comment]
how this is is solved? as I still can't have an absolute path in my storybook project.?

**Comment by ndelangen** [comment]
@unutoiul Please explain what's you're trying to do, from what I understand in your comment you're trying to do the opposite of the OP.

Here's the fix implemented, by the @ajhyndman himself. (:bow:)
https://github.com/storybooks/storybook/pull/1058/files

Please understand we're just humans here, not mind readers.
If you want your problem to get fixed, the best approach is to be kind and informative.
Cheers! 🍻

**Comment by unutoiul** [comment]
Hi,

I'm trying to have absolute path when I import files:

example:

import Test from 'shared-components/components/test/test';

instead of 

import Test from './../components/test/test';

Thanks,
Lucas

**Comment by ndelangen** [comment]
`'shared-components/components/test/test'`
Is not an absolute path, that's a reference to an npm package called `shared-components`.

If you want to have some special resolver logic, you need to configure webpack to do so.
https://webpack.js.org/configuration/resolve/
https://storybook.js.org/configurations/custom-webpack-config/
