### ISSUE TITLE
How to make custom webpack.config for ReactNativeWeb project for different platforms

### ISSUE THREAD

**Issue by code-by** [storybooks/storybook#1054]
I have React Native project and make them to be work in browser using React Native Web
For some React components I made different files for different platforms, like this
index.ios.js
index.android.js
index.web.js

When I make storybook webpack config with
```
  resolve: {
    alias: {
      'react-native': 'react-native-web',
    },
    extensions: ['.js', '.jsx', '.web.js'],
  },

```

I got errrors like this:
```
ERROR in multi manager
Module not found: Error: Cannot resolve 'file' or 'directory' /home/user/prj/RNWApp/node_modules/@kadira/storybook/dist/server/config/polyfills.js in /home/user/prj/RNWApp
 @ multi manager
```

How I need resolve them in Storybook webpack.config.js ?

**Comment by shilman** [comment]
Try taking a look at this example from @Gongreg : 

https://github.com/wix/react-native-storybook-example

Does it solve your problem?

**Comment by code-by** [comment]
@shilman My problem that was I don't add empty extension ('') into resolve - extensions in storybook custom webpack.config.js, cause I previously removed it in project webpack.config.js after upgrading to webpack 2 (http://stackoverflow.com/questions/42068939/webpack-2-cannot-resolve-empty-extensions)

**Comment by Gongreg** [comment]
So problem solved? :)
