### ISSUE TITLE
Cannot npm install v3.0.0-alpha.0

### ISSUE THREAD

**Issue by delijah** [storybooks/storybook#1055]
When i type the following into my console...

`npm install https://github.com/storybooks/storybook.git#v3.0.0-alpha.0`

...i get the following error...

```
npm ERR! addLocal Could not install /var/folders/lk/9kgdct616xd3nv8w93dfbj1c0000gn/T/npm-35127-e969619c/git-cache-7ba39d26/bf7db99e6d5843ad3c787d42c58ba22e23cb1b06
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/storybooks/storybook.git#v3.0.0-alpha.0"
npm ERR! node v7.6.0
npm ERR! npm  v4.2.0

npm ERR! No version provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/delijah/.npm/_logs/2017-05-18T09_02_35_376Z-debug.log
```

**Comment by shilman** [comment]
@ndelangen @aaronmcadam will Lerna support installing from a `git` URL?

@delijah Does installing from `npm` work? E.g. https://github.com/storybooks/storybook#getting-started

**Comment by ndelangen** [comment]
You will install the root package, which we do not publish and is meaningless.

npm installing this git repo will not help you in any way. You need to install from npm.

run:
```
npm view @storybook/react` to view all releases pushed to npm, and take your pick.
```

or just install last alpha release like so:
```sh
npm i @storybook/react@alpha
```

**Comment by delijah** [comment]
Ok, thank you.
