### ISSUE TITLE
No compatible version found: @storybook/react@^2.21.0

### ISSUE THREAD

**Issue by anorudes** [storybooks/storybook#1056]
I'm trying to add, but I get the following error after getstorybook

**Comment by shilman** [comment]
Can you please share more information about your setup and the error you are getting? Thanks!

**Comment by danielduan** [comment]
@anorudes check your `package.json`. The package should be named `"@storybook/react": "3.0.0-alpha.0"`, you might have the wrong version.

**Comment by anorudes** [comment]
Getstorybook installed the wrong version of the package. I myself before this removed it from package.json. However, after the launch getstorybook, it still tries to install this version.
