### ISSUE TITLE
Unable to start 1.11.0

### ISSUE THREAD

**Issue by LFDM** [storybooks/storybook#106]
This is an issue of `react-split-pane` in fact, but I am still posting it here, as most people will probably run into this through `react-storybook`.

When I try to run storybook, webpack's throwing this exception:

```
ERROR in ./~/@kadira/react-split-pane/index.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign" specified in "/home/lfdm/code/si/praisemanager/frontend/node_modules/@kadira/react-split-pane/package.json" at 1, attempted to resolve relative to "/home/lfdm/code/si/praisemanager/frontend/node_modules/@kadira/react-split-pane"
```

**Comment by arunoda** [comment]
That's weird. I'm not getting this error? Are you using NPM v3?
Is there anyway, I can reproduce this?

**Comment by LFDM** [comment]
I am on npm 3.3.6, yeah.

Would love to have more info, but don't really know why this would happen myself. I'll do further digging too and check back when I find anything

**Comment by arunoda** [comment]
Could you try removing all the NPM modules and try re-installing again?

**Comment by LFDM** [comment]
Did that - it's of no help.

I think the issue is that `react-split-pane` is not transpiled. When `storybook` requires it know, it goes through the webpack build processes the consumer specifies in his storybook configuration. This might not have access to this `transform-object-assign` plugin (and it shouldn't, as it's an implementation detail of `react-split-pane`).

Does this make sense?

**Comment by arunoda** [comment]
I will take a look at that and try to make it traspile correctly or not.
