### ISSUE TITLE
Builging 3.0.0-alpha.0 with Webpack 2.5.1 does not use absolute path for output dir

### ISSUE THREAD

**Issue by paazmaya** [storybooks/storybook#1060]
After initial setup for Webpack React project, the command `npm run build-storybook`, getting the error:

```
configuration.output.path: The provided value "./storybook-static/" is not an absolute path!
```

Could be solved possibly by `path.resolve()` or similar, as the command with absolute output path seems to make this working, `npm run build-storybook -- --output-dir /absolutely/right/is/it`.

Need more info?

**Comment by shilman** [comment]
Thanks @paazmaya for testing out the alpha! I believe this is a duplicate to #1052 , which has been fixed and should be released soon. Please reopen if you think it's a separate issue!

**Comment by paazmaya** [comment]
Thank you!

Seems like there was a suggested workaround, so I will be using

```
build-storybook --output-dir ${PWD}/storybook-static
```

until a new alpha comes out.

Happy to try out!
