### ISSUE TITLE
[3.0.0-alpha.0] build-storybook wants absolute path

### ISSUE THREAD

**Issue by jupl** [storybooks/storybook#1067]
When running `build-storybook -o story` I get an error from Webpack mentioning that the value `configuration.output.path` (`story`) is not an absolute path. Currently I need to run the task like `build-storybook -o $PWD/story` which is not cross-platform friendly.

**Comment by ajhyndman** [comment]
Should be fixed in current master: #1052

What's the plan for publishing alpha releases?

**Comment by ndelangen** [comment]
I can do another release, sure!

**Comment by shilman** [comment]
Closing this as a duplicate to #1052. Let's follow up there!
