### ISSUE TITLE
Not seeing stories show up in react native project. But works in reactjs

### ISSUE THREAD

**Issue by Jonovono** [storybooks/storybook#1068]
I just installed running `getstorybook` in a new react native project I created with `react-native init TestApp`. And then run `npm run storybook`. The page loads but nothing shows. However, if I run it in a new reactjs project it works. Is this expected? Is there additional steps for react native not listed in the readme?

Thanks!

**Comment by matt-oakes** [comment]
#1099 is likely the cause of the issue (check the browser console and see if it mentions `react-dom`). If so, run `npm install --save-dev react-dom@^15.5.4` and rerun `npm run storybook`.

**Comment by tmeasday** [comment]
@Jonovono can you tell me a little more about what you are seeing? What steps did you follow?

**Comment by tmeasday** [comment]
Going to close this as hopefully it was the issue that @matt-oakes mentioned and solved! @Jonovono do let us know if not and we'll reopen.
