### ISSUE TITLE
How to use custom fonts?

### ISSUE THREAD

**Issue by code-by** [storybooks/storybook#1070]
I have React Native project that I make to work for web too using React Native Web.
The project use custom fonts, ex. OpenSans.
How do I need to link fonts in the project to use in web storybook also?
Or I need specify it in the project itself?
Thank you

**Comment by ndelangen** [comment]
I'm not sure how you add custom fonts to react-native itself. So maybe you can educate me a little on how that looks in code?

Sounds to me all you need to do is define the font face family somewhere.
1 place where you can do that is in the `head.html` file which storybook will load/inject if provided.

https://github.com/necolas/react-native-web/issues/190

**Comment by code-by** [comment]
@ndelangen
I add and use fonts this way:
```
const MyStyles = StyleSheet.create({
  textInput: {
   fontFamily: 'opensans_light',
  }
} 
```
And fonts itself is in `/android/app/src/main/assets/`

**Comment by ndelangen** [comment]
perhaps @z4o4z can help you with this?

**Comment by z4o4z** [comment]
@code-by I think you should specify it in the project itself.

**Comment by jamesleech** [comment]
for anyone else that ends up here looking for a solution.
It isn't great but it works.

src/App.js

```export const loadAllAssests = [
  Asset.loadAsync([
    require('../assets/images/logo.png'),
  ]),
  Font.loadAsync({
    ...Icon.Ionicons.font, // This is the font that we are using for our tab bar
    black: require('../assets/fonts/CircularStd-Black.ttf'),
    bold: require('../assets/fonts/CircularStd-Bold.ttf'),
  }),
];

export default class App extends React.Component<Props, State> {
  state = {
    isLoadingComplete: false,
  };

  loadResourcesAsync = async () => Promise.all(loadAllAssests);

  ...
}```

storybook/index.js
```import { loadAllAssests } from '../src';
...

Promise.all(loadAllAssests).then(() => {
  console.log('loadResourcesAsync done'); // this is quick enough that it works.
});

// import stories
configure(() => {
  loadStories();
}, module);

// Refer to https://github.com/storybooks/storybook/tree/master/app/react-native#start-command-parameters
// To find allowed options for getStorybookUI
const StorybookUIRoot = getStorybookUI({});

export default StorybookUIRoot;```

**Comment by iMadooc** [comment]
Like in @z4o4z comment.
I used the method provided in this link [add-custom-head-tags](https://storybook.js.org/configurations/add-custom-head-tags)

And then just add `font-family` under `<script>...</script>`.
It works like charm :)

**Comment by iampava** [comment]
Just posted this comment inside a different issue but which seems similar: https://github.com/storybookjs/storybook/issues/7335#issuecomment-631994613 Might help :)

**Comment by axelhildingson** [comment]
This simple solution is to just add a load state before you render the Storybook component 
`
import AppLoading from 'expo-app-loading'

const LoadStoryBook = () => {
  const StorybookUIRoot = getStorybookUI({
    asyncStorage: null,
  })
  const [loading, setLoading] = useState(true)
  useEffect(() => {
    const fetchPreLoadedData = () => {
      return Promise.all([loadFonts]).then(() => setLoading(false))
    }
    fetchPreLoadedData()
  }, [])
  if (loading) return <AppLoading />
  return <StorybookUIRoot />
}
export default LoadStoryBook
`

**Comment by ehrenmurdick** [comment]
Virtually no one is actually reading the issue! They're asking about React **Native** _not_ web!

**Comment by jonniebigodes** [comment]
Despite being a bit outdated the [Intro to Storybook](https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/) tutorial has some instructions on how you can load custom fonts.

**Comment by dannyhw** [comment]
Someone linked me this issue asking about fonts so I thought I'd leave an update. 

Fonts for expo have a few more options now, best thing is to check the expo docs directly. Basically you just include fonts the same as any other react native app, so if not using expo you can follow any other trusted guide to adding fonts.

https://docs.expo.dev/guides/using-custom-fonts/

For react native web I recommend using addon-react-native-web rather than using the on device UI. With this approach you can use the static files configuration since its using the reactjs storybook setup. For example:`staticDirs: [{from: '../fonts', to: 'fonts'}],`

**Comment by blwinters** [comment]
It's not clear to me how `staticDirs` can be leveraged for this, but here is how I got custom fonts working. I have a bare React Native project and I'm using `@storybook/addon-react-native-web` to get Storybook running in the browser ([as is now recommended](https://levelup.gitconnected.com/introducing-react-native-web-storybook-3c56d48a6508) by @dannyhw). 

I created the following `FontLoader` component, which wraps around my app's provider tree. So for Storybook, I added the loader to the global decorators in `.storybook/preview.js`. (And to be clear, I don't have any special `webpack.config.js`, it seems like that might be needed for standard React Storybook.)

```
// FontLoader.tsx
import React, { PropsWithChildren, useCallback } from 'react'
import { View } from 'react-native'
import { useFonts } from 'expo-font'
import { theme, fontName } from '@theme'

interface Props extends PropsWithChildren {
  onFontsLoaded?: () => void // callback for displaying the splash screen once background view has loaded
}

export const FontLoader = ({ onFontsLoaded, children }: Props) => {
  const [fontsLoaded] = useFonts({
    [fontName]: require('../../assets/fonts/Inter-Regular.otf'),
    'inter-italic': require('../../assets/fonts/Inter-Italic.otf'),
    'inter-light': require('../../assets/fonts/Inter-Light.otf'),
    'inter-medium': require('../../assets/fonts/Inter-Medium.otf'),
    'inter-bold': require('../../assets/fonts/Inter-Bold.otf'),
    'inter-black': require('../../assets/fonts/Inter-Black.otf'),
  })

  const onLayoutRootView = useCallback(async () => {
    if (fontsLoaded) {
      onFontsLoaded?.()
    }
  }, [fontsLoaded, onFontsLoaded])

  if (!fontsLoaded) {
    return null
  }

  return (
    <View onLayout={onLayoutRootView} style={{ flex: 1, backgroundColor: theme.colors.$background }}>
      {children}
    </View>
  )
}
```

```
// .storybook/preview.js
import React from 'react'

import { FontLoader } from '../src/utils/FontLoader'
import { ThemeProvider } from '../src/theme'

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}

export const decorators = [
  Story => (
    <FontLoader>
      <ThemeProvider>
        <Story />
      </ThemeProvider>
    </FontLoader>
  ),
]
```

**Comment by dannyhw** [comment]
@blwinters about static dirs:

To use static assets (like fonts) for react-native-web or even just react you can use static dirs like the following.

Lets say I want to add fonts in the folder `fonts/`

I add this to my `main.js`

```
staticDirs: [{from: '../fonts', to: 'fonts'}],
```

I add a `preview-head.html` file to `.storybook` and in here I add a style tag where I load the fonts into css.

.storybook/preview-head.html:
```
<style>
    @font-face {
        font-family: Roboto;
        src: url('fonts/Roboto-Bold.ttf');
        font-weight: bold;
    }
</style>
```

Then in the component I can just use the font like `style={{fontFamily: 'Roboto'}}` or however you like.

this example code comes from https://github.com/dannyhw/sb-rn-fonts/tree/patch-1

**Comment by blwinters** [comment]
@dannyhw Thank you for that explanation, I figured there must be something like this. However, I wasn't able to get it to work. I tried it in my project with no luck, then I cloned the example project that you linked and also there I saw a serif font instead of Roboto (screenshot attached). Seems like the `preview-head.html` isn't getting picked up by Storybook or something. Any ideas?

<img width="663" alt="Screen Shot 2022-09-02 at 1 31 29 PM" src="https://user-images.githubusercontent.com/4462923/188208093-c438ec2f-27c0-491a-8602-c76cf44f043d.png">

**Comment by dannyhw** [comment]
@blwinters you need to be on the patch-1 branch that I linked

**Comment by blwinters** [comment]
@dannyhw Ah, my mistake, yes that's working. I already had that correctly on my project, but looking at the differences between our projects I figured it must be because I had pinned my storybook packages to 6.3.x, due to the limitations of `@storybook/react-native`. Once I matched my packages to yours (which updates them to 6.5.x), I started seeing the custom fonts correctly. I'm fine with letting go of Storybook RN for now, the web interface is better anyway and this simplifies my config.

**Comment by daibergm** [comment]
> @blwinters about static dirs:
> 
> To use static assets (like fonts) for react-native-web or even just react you can use static dirs like the following.
> 
> Lets say I want to add fonts in the folder `fonts/`
> 
> I add this to my `main.js`
> 
> ```
> staticDirs: [{from: '../fonts', to: 'fonts'}],
> ```
> 
> I add a `preview-head.html` file to `.storybook` and in here I add a style tag where I load the fonts into css.
> 
> .storybook/preview-head.html:
> 
> ```
> <style>
>     @font-face {
>         font-family: Roboto;
>         src: url('fonts/Roboto-Bold.ttf');
>         font-weight: bold;
>     }
> </style>
> ```
> 
> Then in the component I can just use the font like `style={{fontFamily: 'Roboto'}}` or however you like.
> 
> this example code comes from https://github.com/dannyhw/sb-rn-fonts/tree/patch-1

Perfect!, it's work for me
