### ISSUE TITLE
Storybook CLI should to be updated for 3.0.0

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1077]
## why 
`getstorybook` =>

<img width="653" alt="testosterone_ _node_ _node____nvm_versions_node_v6_10_2_bin_getstorybook_ _178x43" src="https://cloud.githubusercontent.com/assets/488689/26274517/e917daba-3d8e-11e7-9c54-aff524d71d6d.png">

## what
- [ ] update all dependencies in `@storybook/cli` appropriately
- [ ] what do we want to do about new releases .. this should get updated automagically? (maybe separate issue)

**Comment by ndelangen** [comment]
CLI needs major work, but I think I can fix this.
