### ISSUE TITLE
Filter box should work on story levels too

### ISSUE THREAD

**Issue by bcowgill** [storybooks/storybook#109]
> Edit: original title: Filter box does nothing.

I tried the simple instructions for testing a Button as shown here: https://github.com/kadirahq/react-storybook

and it works, but I don't see the Filter box doing anything.

**Comment by arunoda** [comment]
Filterbox only filter the top level menu (Which you defined with `storiesOf()` API.

**Comment by timkindberg** [comment]
So maybe this issue should rename to "Filter box should work on story levels too"

**Comment by arunoda** [comment]
@timkindberg Goog idea.

**Comment by ndelangen** [comment]
I think this is a clearly bug, probably easily fixable !
