### ISSUE TITLE
docgen does not detect React.createClass components

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#1096]
I've been struggling to get `react-docgen` working with the current default configs. Storybooks has a few features recently merged into `addon-info` to automatically generate documentation for description, prop-types, and more. We could potentially automatically generate configs for Knobs as well.

The issue seems to inside the Kadira babel plugin `babel-plugin-react-docgen`. When stepping through what's happening during babel compile, I found out it never reaches the part that runs `react-docgen`.
1. Half the components get rejected because they're stateless components. Some are incorrectly identified, some are correct that they are stateless, however I still think there is value in getting docgen description and prop info for stateless components.
https://github.com/kadirahq/babel-plugin-react-docgen/blob/master/src/index.js#L25
2. All of the components will fail the parent path node name test which seems to always point to a render function and thus fail because they don't have a name. The name is used to find the generated info later on.
https://github.com/kadirahq/babel-plugin-react-docgen/blob/master/src/index.js#L29
3. All of the components will fail to be detected as exported.
https://github.com/kadirahq/babel-plugin-react-docgen/blob/master/src/index.js#L34

My guess is that we need to update the plugin to support the new version of babel we're using.

Example of a component that would be identified as stateless, without parent node name, and not exported:
```
const React = require('react');
const { PropTypes } = React;

const stylesheet = {};

/**
 * Component for displaying a container that resembles the original CSS environment for different themes
 */

const ComponentWrapper = React.createClass({
  propTypes: {
    /**
     * Theme to display
     */
    theme: PropTypes.string
  },

  getDefaultProps() {
    return {
      theme: 'damask'
    };
  },

  render() {
    return (
      <div className={ stylesheet[this.props.theme] }>
        <div className={ stylesheet.container }>
          { this.props.children }
        </div>
      </div>
    );
  }
});

module.exports = ComponentWrapper;
```

Since my component class names are the same as the filenames, I've been able to get it to work by changing the `index.js` in `babel-plugin-react-docgen` to:
```
      'FunctionDeclaration|FunctionExpression|ArrowFunctionExpression': function FunctionDeclarationFunctionExpressionArrowFunctionExpression(path, state) {

        console.log('babel-plugin-react-docgen 2');
        console.log(path.hub.file.opts.basename);
        // if (!(0, _isStatelessComponent2.default)(path)) {
        //   console.log('stateless');
        //   return;
        // }
        // if (!path.parentPath.node.id) {
        //   console.log('no parent');
        //   console.log(path.parentPath.node);
        //   return;
        // }
        // var className = path.parentPath.node.id.name;
        var className = path.hub.file.opts.basename;

        // if (!isExported(path, className, t)) {
        //   console.log('not exported');
        //   return;
        // }
        console.log('generating');
        injectReactDocgenInfo(className, path, state, this.file.code, t);
      }
```

I think we should try to bring the babel plugin under our umbrella org and maintain it since it does bring a lot of improvements to addon-info.

Thoughts?

**Comment by ndelangen** [comment]
I have asked @arunoda to transfer control of the repo, so we can work on it.

Second option is to look to alternatives: https://www.npmjs.com/package/babel-plugin-doc-gen

**Comment by ndelangen** [comment]
Thanks for all this investigative work @danielduan !!!

**Comment by danielduan** [comment]
That other package seems to be work in progress and hasn't been worked on for a few months. It's probably better to bring the original plugin in-house and update it.

It seems a bit misleading to name it `babel-plugin-react-docgen` since it only looks for a specific type of React file. Maybe something like `babel-plugin-storybook-docgen` seems more fitting. Alternatively, we could build other options into the plugin such that it could be used outside of the Storybook use case.

**Comment by ndelangen** [comment]
@danielduan The repo has been moved over. https://github.com/storybooks/babel-plugin-react-docgen 

If you can make a PR there I can publish it, I think

**Comment by wildeyes** [comment]
I'm encountring this in version 2.35.3, 
```
Module build failed: TypeError: The plugin ["...\\node_modules\\babel-plugin-react-docgen\\lib\\index.js",{"DOC_GEN_COLLECTION_NAME":"STORYBOOK_REACT_CLASSES"}] didn't export a Plugin instance
```

**Comment by danielduan** [comment]
@wildeyes I've never encountered that before. I think the confusing thing is that there's two ways to use the plugin.

If you want the docgen info on the React class and all in one global collection:
```
{
  "plugins":[
    ["babel-plugin-react-docgen", { "DOC_GEN_COLLECTION_NAME": "MY_REACT_DOCS"}]
  ]
}
```

If you just want the docgen info on the react class:
```
{
  "plugins": ["react-docgen"]
}
```

Make sure you're using the right one?

**Comment by wildeyes** [comment]
I actually don't have that plugin in my plugins list.

**Comment by danielduan** [comment]
@wildeyes it is automatically injected by storybooks when it reads from your custom `.babelrc` if you have one. If not, it reads from the default one and then injects it.

Either way, I'm not sure why it's happening and it definitely shouldn't. Can you try upgrading your project to `3.0.0-alpha.4` and see if this issue still exists?

**Comment by danielduan** [comment]
I'm gonna mark this for 3.0.1 release. Currently, stateless components and class style React components do work so I don't think the fix for this plugin should hold up the release for Storybook.

**Comment by Stupidism** [comment]
Also, to support description for stateless components: please update react-docgen to at least 
https://github.com/reactjs/react-docgen/releases/tag/v2.11.0

**Comment by danielduan** [comment]
It was originally on 2.12 already and I've upgraded it to 2.16 so we're good. @stupidism

**Comment by Stupidism** [comment]
@danielduan Sorry, I wrote description in the wrong place. It's working.

**Comment by ndelangen** [comment]
This is resolved? 🎈

**Comment by Gongreg** [comment]
@danielduan There is already a solution for automatic knob generation: https://github.com/lucasconstantino/storybook-addon-smart-knobs . :)

**Comment by Stupidism** [comment]
I think this should be done in this plugin?
https://github.com/storybooks/babel-plugin-react-docgen/issues/28
