### ISSUE TITLE
extract default webpack and publish as package

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#1098]
We see people using our webpack config by including it, and we even document it.
`@storybook/react/dist/server/config/webpack.config`

But reaching deep into a package is a bad practice, because it's fragile, and makes it harder for us to refactor.

We should publish the default webpack config as it's own package.

**Comment by heinzmuller** [comment]
Just a thought, but what about having it as a named export?

`import { webpackConfig } from "@storybook/react"`

**Comment by ndelangen** [comment]
yeah valid point, that's an option too!

**Comment by ndelangen** [comment]
Care to make this into a PR @heinzmuller ?

**Comment by ndelangen** [comment]
We found a better solution where the default is passed as a parameter in full control mode.
