### ISSUE TITLE
Logo refresh proposal

### ISSUE THREAD

**Issue by SachaG** [storybooks/storybook#1100]
I was talking with @shilman about improving the Storybook(s) homepage and I think one of the first step would be refreshing the logo. I like the overall concept, but I think the execution could be even better with a few tweaks, like using a different font for example. 

Here's the current logo:

![https://d3vv6lp55qjaqc.cloudfront.net/items/3x0Q1514411z3l1O2a1Q/storybooks-old.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=e0d32032](https://d3vv6lp55qjaqc.cloudfront.net/items/3x0Q1514411z3l1O2a1Q/storybooks-old.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=e0d32032)

And here's my proposal:

![https://d3vv6lp55qjaqc.cloudfront.net/items/051r060k3n011Q2e1v0G/storybooks-new.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=8dde02e4](https://d3vv6lp55qjaqc.cloudfront.net/items/051r060k3n011Q2e1v0G/storybooks-new.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=8dde02e4)

I softened the colors a bit, and set the name in [Filmotype Major](http://www.myfonts.com/fonts/filmotype/major/) to fit in with the children's book theme. 

(The softer colors probably look a bit weak when directly compared with the current logo, but I think in context on the homepage it would work well)

**Comment by SachaG** [comment]
Monochromatic version:

![https://d3vv6lp55qjaqc.cloudfront.net/items/2Y312N1G0n3P0H3U2v17/storybooks-mono.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=f3fb9276](https://d3vv6lp55qjaqc.cloudfront.net/items/2Y312N1G0n3P0H3U2v17/storybooks-mono.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=f3fb9276)

**Comment by SachaG** [comment]
Other versions:

![https://d3vv6lp55qjaqc.cloudfront.net/items/372B3d2L0e13133D3e2Q/Screen%20Shot%202017-05-23%20at%2010.36.46.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=9376303a](https://d3vv6lp55qjaqc.cloudfront.net/items/372B3d2L0e13133D3e2Q/Screen%20Shot%202017-05-23%20at%2010.36.46.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=9376303a)

**Comment by dburles** [comment]
Looks wonderful! though, Storybook or Storybooks?

**Comment by shilman** [comment]
@SachaG @dburles sorry for the confusion, it's my fault. It should be `Storybook`.
- We are `storybook` in all places except for our github org which is `storybooks`
- @ndelangen is reaching out to Github to try to get us `storybook`

**Comment by shilman** [comment]
@SachaG can we do your proposal minus the trailing `s`?

Currently the assets are in https://github.com/storybooks/storybooks.github.io in the `design` directory. Would be great to also have SVGs for the new design (in addition to PNGs?)

**Comment by shilman** [comment]
Here's the updated proposal? Any objections?

<img width="1096" alt="storybooks-new_svg" src="https://cloud.githubusercontent.com/assets/488689/26436507/43e4da96-415a-11e7-8750-d9c00d5cf545.png">

**Comment by dburles** [comment]
Just to be picky I wouldn't mind seeing how it looks in uppercase like the old logo (but with the new font)

**Comment by shilman** [comment]
OOOH @SachaG one thing!! We're not going to change the capitalization of the project, so the logo should either be `STORYBOOK` as @dburles suggests, or `Storybook` with a lowercase `B`. 😅

**Comment by SachaG** [comment]
![https://d3vv6lp55qjaqc.cloudfront.net/items/1I0b1v0P3Y3F2p1d3U2N/Screen%20Shot%202017-05-25%20at%2015.43.02.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=05bc11dd](https://d3vv6lp55qjaqc.cloudfront.net/items/1I0b1v0P3Y3F2p1d3U2N/Screen%20Shot%202017-05-25%20at%2015.43.02.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=05bc11dd)

**Comment by dburles** [comment]
looks good @SachaG would be cool to see it in drop-caps like the original

**Comment by shilman** [comment]
@dburles you are one tough customer 😁

**Comment by dburles** [comment]
haha i was just thinking that 😂

**Comment by SachaG** [comment]
![https://d3vv6lp55qjaqc.cloudfront.net/items/073J352F2K2Z2H3A0019/Screen%20Shot%202017-05-25%20at%2015.58.12.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=57b68dec](https://d3vv6lp55qjaqc.cloudfront.net/items/073J352F2K2Z2H3A0019/Screen%20Shot%202017-05-25%20at%2015.58.12.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=57b68dec)

**Comment by dburles** [comment]
yep that's awesome!

**Comment by shilman** [comment]
Awesome!!! Personally I prefer the Storybook logo. STORYBOOK is also fine but i don’t want the B to be larger because people will starting writing it as StoryBook and we already have enough confusion with Storybook vs Storybooks. (I heard somebody call it storyboard on twitter). So anything we can do to minimize that confusion is worth it.

**Comment by SachaG** [comment]
I get that Storybook vs Storybooks is a problem, but I don't see why "StoryBook" would be one? It doesn't make a difference in URLs or command line or anywhere people would need to type out the name?

**Comment by shilman** [comment]
Are you proposing we change it to StoryBook everywhere in the docs also?

**Comment by SachaG** [comment]
Here's a version with stronger colors to match the original pink:

![https://d3vv6lp55qjaqc.cloudfront.net/items/2W080D1I452l0d0Q2c2v/Screen%20Shot%202017-05-26%20at%2010.27.50.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=9c68547c](https://d3vv6lp55qjaqc.cloudfront.net/items/2W080D1I452l0d0Q2c2v/Screen%20Shot%202017-05-26%20at%2010.27.50.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=9c68547c)

I personally prefer more muted colors since they fit more with the "children's book" theme (printed colors aren't as flashy as onscreen ones), but I tend to like more muted colors in general so that's just my personal taste. It doesn't make a huge difference anyway. 

> Are you proposing we change it to StoryBook everywhere in the docs also?

No, I would just suggest keeping the original logo's slightly larger B for improved readability, but no need to change it anywhere. The name can still be "Storybook".

**Comment by dburles** [comment]
Hey @SachaG can you post the muted drop-caps version above but with the B reduced in size?

**Comment by SachaG** [comment]
@dburles sorry I don't get it, so you want the B to be the same size as everything else? In that case it'd be the same as https://github.com/storybooks/storybook/issues/1100#issuecomment-303936372 ?

**Comment by shilman** [comment]
@SachaG If the logo says StoryBook then people are going to write it as StoryBook. If that's what we want then we should just change the name. If not, then we should have a logo that's consistent with the name, either `Storybook` or `S[TORYBOOK]` where TORYBOOK is drop caps (slightly smaller than then the initial S (@dburles' suggestion, as I understand it).

**Comment by SachaG** [comment]
Oh ok, I got confused because "TORYBOOK" was already smaller in all previous versions (but not by much). Do you want me to accentuate the difference? 

And the B in the original logo was bigger, so has people calling it "StoryBook" been a problem so far? I just like how the bigger B looks visually. But again it's just nitpicking, I'm fine either way if we can reach a consensus among all parties involved :)

**Comment by shilman** [comment]
As I mentioned, I've seen Storybook, Storybooks, StoryBook, storyboard, etc. People will mangle it even if we're consistent on our side. But if WE'RE inconsistent, it will only magnify the problem (assuming one agrees that it's a problem).

In summary, from my side:

TYPE: I prefer `Storybook` to `S[TORYBOOK]`, but am fine both ways. `StoryBook` doesn't work for me, and I feel pretty strongly about it, though maybe I'm the only one.

COLOR: I prefer a bolder color scheme, but agree that having a great logo and making the rest of our assets match is the right way of thinking about it (and not the other way around). So ideally we dial up the saturation a little bit from the original proposal, but maybe not all the way back up. The lime green and red in the last proposal are hard on the eyes, though I love the bold pink. I'll defer to your judgment.

**Comment by SachaG** [comment]
OK, so here's a proposal with the lowercase logo, and in-between colors (stronger than my first version but not as strong as the original pink). What do you all think?

![https://d3vv6lp55qjaqc.cloudfront.net/items/1j1O2t0V0W3o2z183j2K/Screen%20Shot%202017-05-26%20at%2013.33.12.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=faa6d1ec](https://d3vv6lp55qjaqc.cloudfront.net/items/1j1O2t0V0W3o2z183j2K/Screen%20Shot%202017-05-26%20at%2013.33.12.png?X-CloudApp-Visitor-Id=d40749865873d7b5ab32c80852150f74&v=faa6d1ec)

**Comment by ndelangen** [comment]
I think we have a winner 🆒

**Comment by shilman** [comment]
I love this @sachag. Thanks so much for being accommodating on this. 100% on board. 😻😻😻

**Comment by dburles** [comment]
I agree! thanks @SachaG !

**Comment by SachaG** [comment]
@shilman maybe we could write a blog post about the logo design process for the Storybook blog? I feel like it could make for a cool case study?

**Comment by shilman** [comment]
@SachaG new logo is getting a lot of love.  Great work and thanks for your patience and flexibility on this!

**Comment by shilman** [comment]
@SachaG I missed your comment above about the blog post. Great idea--let me know how I can help!

**Comment by AgaAgnieszkaBorcz** [comment]
Hello. What license is your logo falling under? Can be used commercially? For example stickers?>>> thank you

**Comment by shilman** [comment]
cc @domyen

**Comment by domyen** [comment]
I made the new logo. The source is under the MIT license just like the rest of the code. So I think it's fine if you want to make stickers/merch. 

That said, I have a similar opinion of @keithamus [here](https://github.com/chaijs/chai/issues/1233#issuecomment-464046033). Good luck!

**Comment by SachaG** [comment]
I made the old logo (can't wait to see the new one!) and I agree with @domyen

**Comment by AgaAgnieszkaBorcz** [comment]
Great thank you Guys!

**Comment by ndelangen** [comment]
@AgaAgnieszkaBorcz
If you can show me a PR you made that got merged, I'll send you a bunch of stickers personally!

**Comment by ghengeveld** [comment]
I updated the above thread to replace inline images and links with raw URLs. Hopefully that'll get those images out of the Google search index. We don't want to see those old logos in any more slide decks. Here's the proper one:

![storybook-logo-2400w](https://user-images.githubusercontent.com/321738/110119676-6b276680-7dbc-11eb-974c-f891f4c29928.png)

And white variant (for dark backgrounds):

![storybook-logo-2400w-white](https://user-images.githubusercontent.com/321738/110119702-75e1fb80-7dbc-11eb-9ccc-862726f220cd.png)

I'll update the [brand](https://github.com/storybookjs/brand) repository with some new assets as well.
