### ISSUE TITLE
Proposal - Storybook api to add components without plugins sidebar

### ISSUE THREAD

**Issue by tuchk4** [storybooks/storybook#1103]
Add  `page` api (or with similar name) to show components without plugins sidebar. 

```
storiesOf('Welcome', module)
  .page('to Storybook', () => <Welcome showApp={linkTo('Button')} />);
```

For example at our storybook we have pages with all icons and theme colors and plugins sidebar in this case is useless and takes space.

![image](https://cloud.githubusercontent.com/assets/5140611/26346098/cd313384-3fad-11e7-948a-72b6448b9eab.png)

---

Another case - we developed components lib and want to publish it to open source and all examples and docs will be in storybook. Customs themes and *page* api will allow us to make docs and examples as useful as possible.

**Comment by shilman** [comment]
Awesome! I know @UsulPro has done some work with theming. I think there are actually two separate issues here:

1. Ability to theme
2. Ability to add pages
 - or alternatively stories with options to disable the plugins panel
 - or optionally a more configurable panel/docking framework for the UI
 - or the idea of being able to display a bunch of stories on the same page
 - or some combination of the above 😄 
Can we divide it into two separate issues? Or do you think these two features are tied together somehow?

**Comment by tuchk4** [comment]
Completely agree that there are two separate issues. 

But this is up to you. 
- I can close this issue and create two separate issues
- Or implement features in different PRs but link to them to one Issue.

**Comment by shilman** [comment]
@tuchk4 how about you just edit this issue to make it about the pages API and open up a new issue about theming? thanks!

**Comment by tuchk4** [comment]
@shilman done

**Comment by UsulPro** [comment]
@shilman @tuchk4 
I started some works for adding theming to storybook indeed! I was near to submit first PR, but we started to switch to the monorepo and decided to wait untill it will settle down.
I think theming it's a hole bunch of features and related things. So there a lot of work.
I can share my PR as "it is" if you want to start asap, but I could join to this work only in a few weeks.
what do you think @tuchk4 ?

**Comment by UsulPro** [comment]
We have options addon https://github.com/storybooks/storybook/tree/master/addons/options
and there is an option `showDownPanel: false`. You can use it globally or locally for each separated story.

Doesn't it the same as your offered API?

**Comment by shilman** [comment]
@UsulPro I think the idea is that `stories` would automatically show the addons bar, and `pages` would automatically hide the addons bar.

**Comment by shilman** [comment]
@tuchk4 you could do this in an addon very easily. If you look at the source of the `options` addon, it just does this on the preview side:

```js
import addons from '@storybook/addons';
import { EVENT_ID } from '../shared';
export function setOptions(options) {
  const channel = addons.getChannel();
  channel.emit(EVENT_ID, { options });
}
```

And on the addon side:
```js
    const channel = addons.getChannel();
    channel.on(EVENT_ID, data => {
      api.setOptions(data.options);
    });
```

So you could write a simple addon that dynamically set the options to show or hide the panel depending on which story was selected, either by piggybacking on the options addon, or just doing something similar.

**Comment by tuchk4** [comment]
@shilman It's time to publish new addon :)

**Comment by UsulPro** [comment]
> dynamically set the options to show or hide the panel depending on which story was selected

**Comment by UsulPro** [comment]
> dynamically set the options to show or hide the panel depending on which story was selected

Sorry if I miss something, but look at this stories:

```js
storiesOf('Material-UI', module)
    .add('Components', () => {
        setOptions({
            name: 'storybook-addon material-ui',
            url: 'https://github.com/sm-react/storybook-addon-material-ui',
            goFullScreen: false,
            downPanelInRight: false,
        });
        return <Components />;
    })
    .add('Card', () => (
      <Card />
    ));

```

Here I set options directly from the story:
```js
.add('Components', () => {
        setOptions({
            name: 'storybook-addon material-ui',
            url: 'https://github.com/sm-react/storybook-addon-material-ui',
            goFullScreen: false,
            downPanelInRight: false,
        });
        return <Components />;
    })
```

and it changes dynamically. You can check out this [demo](https://sm-react.github.io/react-theming/?theme-ind=0&theme-sidebar=false&theme-full=false&knob-Title=Welcome%20to%20React-Theming&knob-Subtitle=Storybook%20Boilerplate%20Project&knob-Label1=Hello%20Button&knob-Label2=Hello%20Button&selectedKind=Material-UI&selectedStory=Components&full=0&down=1&left=1&panelRight=0&downPanel=sm%2Fstorybook-addon-material-ui%2Fmaterial-panel)

Notice how the Title changes depending on what storyKind is selected. It's possible to add own options for each `.add()` and it will work dynamically.

I don't mind creating a separate addon of course :)
But it's enough to just put this option inside the page function like this:

```js
export default {
  page(storyName, getStory) {
     setOptions({
            downPanelInRight: false,
        });
    this.add(storyName, getStory);
  }
}

```

And then add this to `StoriesOf` by `setAddon(pages);`

Really sorry if I did not catch something in this idea

**Comment by shilman** [comment]
LOL @UsulPro even simpler! 👍

**Comment by shilman** [comment]
I think @UsulPro's solution would work like a charm. Going to close this for now @tuchk4. Please feel free to re-open in case we missed something!
