### ISSUE TITLE
"An error occured while installing dependencies"

### ISSUE THREAD

**Issue by wildeyes** [storybooks/storybook#1105]
![image](https://cloud.githubusercontent.com/assets/1652108/26355842/cf667766-3fd2-11e7-9eba-c8000905845e.png)

**Comment by shilman** [comment]
@wildeyes looks like we've got a problem!
- which version of getstorybook are you running?
- can you tell us more about your project? is there a public repo somewhere, or a reliable way to reproduce?
if you let us know we can try to help you figure it out.

**Comment by wildeyes** [comment]
3.0.0-alpha.0, what do you need to know? it's not a public repo, sadly :)

**Comment by shilman** [comment]
@wildeyes was the repo generated using some boilerplate, or can you share your `package.json` file here? without more information it is hard to assess the problem.

also, perhaps try upgrading to 3.0.0-alpha.4, though honestly i don't think there is much difference in getstorybook between the two versions..

**Comment by wildeyes** [comment]
Are there some console.logs I can place somewhere in storybook's code? what could trip storybook in the package.json?

storybook did generate a few files before it sigfaulted

**Comment by shilman** [comment]
sure. the first thing that's weird is that it detected your project as react native when it's react. that's in `lib/cli/lib/detect.js` so you should figure out what's going there, and def let us know if it's a storybook bug.

as for the dependency error, that's in `lib/cli/lib/helpers.js` at the bottom. not sure how to debug that one, but perhaps you can change the `stdio` settings and see what it prints out?

hope that helps!

**Comment by wildeyes** [comment]
@shilman I removed the react-native part, I had react-native dependencies in package.json (who knew). will try to debug it and see

**Comment by shilman** [comment]
@wildeyes it looks like the problem you're seeing is due to a bug in windows `getstorybook`,  https://github.com/storybooks/getstorybook/issues/28. this bug was fixed earlier (https://github.com/storybooks/getstorybook/pull/26) but didn't get moved over properly when we did our 3.0 repository restructure.

We're working on it now.

**Comment by shilman** [comment]
@wildeyes The windows fix has been applied to the latest alpha `alpha.5`. Can you try upgrading and let me know if it works for you?

**Comment by wildeyes** [comment]
Looks like it's fixed now, thanks! though I still somehow need to reproduce @yarnpkg/yarn#3481 to get storybook to work :(

**Comment by shilman** [comment]
@wildeyes good luck! let us know if you run into any more problems and thanks so much for catching this windows issue during our alpha test!

**Comment by wildeyes** [comment]
You should mention in the README that this is alpha quality for windows. I am very determined on getting storybook to work, but other developers won't be as forgiving, you should let people know what they're getting into, otherwise they'll just have a bad (misplaced) impression of storybook!

**Comment by quanquanmiaomiao** [comment]
I have the same problem,but i don't know how to salve

**Comment by shilman** [comment]
@wildeyes it's an alpha release, so it shouldn't be a surprise that it's "alpha-quality" on all platforms 😜 

We'll do a better job on Windows support once @UsulPro gets back in action (he's in the middle of a big family move, but aims to be back on the scene in mid June).

Nevertheless thanks for your patience and determination. You just helped the release improve for everybody. 🙇

**Comment by shilman** [comment]
@quanquanmiaomiao This appears to be a problem with your network connection? Are you able to navigate to `https://yarnpkg.com` in a browser when you're getting these network errors?

**Comment by wildeyes** [comment]
"@wildeyes it's an alpha release, so it shouldn't be a surprise that it's "alpha-quality" on all platforms 😜"

I know, but that should be visible. I didn't know that when I tried it out. I would have been more patient if I knew.

**Comment by shilman** [comment]
@wildeyes Great point. We'll do a better job during the next release. This was a massive structural change for Storybook, and hopefully the coming releases will be a lot smoother. Thanks again for your contribution!
