### ISSUE TITLE
Proposal - Storybook custom themes 

### ISSUE THREAD

**Issue by tuchk4** [storybooks/storybook#1107]
Would be great to customize storybook theme (light theme, dark theme, custom theme etc.)

Splitted from #1103

> we developed components lib and want to publish it to open source and all examples and docs will be in storybook. Customs themes and *page* api will allow us to make docs and examples as useful as possible.

**Comment by shilman** [comment]
Thanks @tuchk4 !! I hope it will be easier to discuss each point separately 😄

**Comment by UsulPro** [comment]
Related issue: #428

**Comment by shilman** [comment]
Good catch again @UsulPro. Let's continue the discussion over at #428. Closing this for now! 👍
