### ISSUE TITLE
Don't use randomly generated IDs in actions

### ISSUE THREAD

**Issue by marcfallows** [storybooks/storybook#1109]
In our storybooks we use [seedrandom](https://github.com/davidbau/seedrandom) to seed `Math.random` because we use them for visual regression. That means that the randomly generated IDs can result in duplicate keys:

Randomly generated id: https://github.com/storybooks/storybook/blob/master/addons/actions/src/preview.js#L16

Use of the ID in a key: https://github.com/storybooks/storybook/blob/master/addons/actions/src/components/ActionLogger/index.js#L22

And we all know how React feels about duplicated keys... 😞 

Could a uuid be used instead?

**Comment by shilman** [comment]
@marcfallows Seems reasonable to me! Wanna make a quick PR?

**Comment by marcfallows** [comment]
Happy to raise a PR. Do you have a preference:
 - Using [node-uuid](https://github.com/kelektiv/node-uuid) to generate a uuid
 - Keeping it simple and have a runtime counter

**Comment by ndelangen** [comment]
`uuid` please 👍

**Comment by marcfallows** [comment]
Sorry for the delay, finally make a PR for this: https://github.com/storybooks/storybook/pull/1347
