### ISSUE TITLE
Error while building storybook into static files

### ISSUE THREAD

**Issue by epicallan** [storybooks/storybook#1110]
I am using @storybook/react version 3.0.0-alpha.0 and I used getstorybook for my initial setup. 
When I run ```npm run build-storybook``` I get a webpack error that tells me that my output location is not absolute path and hence its invalid for use
<details>
> build-storybook -c .storybook -o .out

@storybook/react v3.0.0-alpha.0

=> Loading custom .babelrc
=> Using default webpack setup based on "Create React App".
Building storybook ...
/Users/allan/apps/dh-next/node_modules/webpack/lib/webpack.js:19
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value ".out" is not an absolute path!
</details>

**Comment by shilman** [comment]
@epicallan Thanks for testing out the alpha! I think this was fixed in alpha.2 or 3. Can you upgrade to the latest alpha and try again?

**Comment by epicallan** [comment]
Thanks @shilman and could you please upload the latest alpha whenever you get a chance.

**Comment by shilman** [comment]
@epicallan the latest alpha is already on npm. run `npm i @storybook/x@alpha --save` to update your library, where `x` is whatever library you're using.

**Comment by epicallan** [comment]
@shilman I am not sure whether I am missing something obvious. Running say ``` npm i @storybook/5@alpha --save``` for installing the 5th alpha did not work and even when i search on npm the latest release there is the first alpha.0 which is not the latest alpha.
<img width="531" alt="screen shot 2017-05-25 at 08 29 21" src="https://cloud.githubusercontent.com/assets/6281527/26437260/a770aac6-4124-11e7-941a-7b64193a2593.png">

**Comment by shilman** [comment]
@epicallan how about `npm i @storybook/react@alpha --save`?

**Comment by epicallan** [comment]
@shilman that worked it installed alpha 4. Thanks.

**Comment by shilman** [comment]
Great! Closing this now but feel free to reopen or post more q's as you have them.
