### ISSUE TITLE
documentation mentions deprecated 'actions' and 'linkTo' addons as part of core

### ISSUE THREAD

**Issue by gabor** [storybooks/storybook#1113]
the documentation says that this addon can be used without installing it.
but if you use it like `import { action } from '@storybook/addon-actions'` then `eslint` does not like it because it triggers the [import/no-extraneous-dependencies]( https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md ) warning (we are using a module that is not mentioned in `package.json`).

i can fix this by explicitly adding the package to `package.json`, but i wonder what is the recommended approach here.

**Comment by shilman** [comment]
@gabor which version of storybook are you using? we are in the process of deprecating the "use the addon with out installing it", so it should still work but will get phased out in 4.0.

**Comment by ndelangen** [comment]
ESlint is correct, you should list it as a dependency. If you can link us to the docs we'll change it.

We already have a PR upgrading the docs to `3.0.0`. here: https://github.com/storybooks/storybooks.github.io/pull/54
Care to review it @gabor ? ♥️

**Comment by gabor** [comment]
thank you for the info... the docs-page is https://github.com/storybooks/storybook/blob/master/addons/actions/README.md, contains the `You can use this addon without installing it manually.` text.

about the mentioned pull-request, i see it's about the documentation-site... on that site, at https://storybooks.js.org/docs/react-storybook/addons/addon-gallery/ again mentions that `These addons ship with Storybook by default. You can use them right away.`. i did not see this file getting changed in the mentioned pull-request.

**Comment by ndelangen** [comment]
We will need to update the docs!, thanks for checking. PR is very much welcome btw 🙏

**Comment by ndelangen** [comment]
Fixed!
