### ISSUE TITLE
 Warning: A Component: React.createClass is deprecated and will be removed in version 16 because of @storybook/addon-info

### ISSUE THREAD

**Issue by chakravarthysm** [storybooks/storybook#1114]
https://github.com/christianalfoni/markdown-to-react-components repo is deprecated, it has been moved to new repo - https://github.com/cerebral/marksy ,

markdown-to-react-components still uses React.createClass in one of its files which is deprecated in React 15, I'm getting warning in console as - 

`warning.js:36 Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

As storybook/addon-info uses markdown-to-react-components ^0.2.1 version, please use https://www.npmjs.com/package/marksy which may fix it.

**Comment by ranneyd** [comment]
The module causing the error (https://github.com/christianalfoni/markdown-to-react-components) is marked as DEPRECATED in its readme. They recommend migrating to marksy (https://github.com/cerebral/marksy). Using a deprecated package is bad

**Comment by Jeff-Duke** [comment]
Is this still available or was it resolved in https://github.com/storybooks/storybook/pull/1188 ?

**Comment by shilman** [comment]
@Jeff-Duke I think it's been fixed with the upgrade to `marksy`. Closing!
