### ISSUE TITLE
Getstorybook CRNA support

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1115]
## why
Currently `getstorybook` requires a few extra steps to get working with `create-react-native-app` (aka CRNA). They are documented (excellently) here:

https://medium.com/@inyono/using-react-native-storybook-with-create-react-native-app-471e531bb128

## what
Proposal for streamlining the setup process:
- [x] Simplify as much as possible:
  - [x] Consolidate `storybook/index.ios.js` and `storybook/index.android.js` into `index.js`
  - [x] Detect CRNA app and print out additional (minimal) manual step 
- [ ] Update docs: discuss why manual step and why manual step is necessary
  - [x] `react-native/README.md`
  - [ ] `react-native/docs`
  - [ ] https://storybooks.js.org

Props to @orta and @tmeasday for helping figure this out and for @inyono for the awesome post.

**Comment by inyono** [comment]
That would be so awesome :) Btw: https://github.com/serlo-org/serlo-abc has an updated version of the blog post that e.g. picks the real app entry on build. Feel free to ask if you need input or want help from me.

**Comment by ndelangen** [comment]
Is this done?
