### ISSUE TITLE
How to npm install v3.0.0-alpha

### ISSUE THREAD

**Issue by andrewcashmore** [storybooks/storybook#1116]
How can we consume v3.0.0-alpha using `npm install`?

**Comment by andrewcashmore** [comment]
I'm assuming this is because you guys are using Lerna and have a build process but wasn't sure

**Comment by ndelangen** [comment]
`npm i @storybook/react@alpha --save-dev` will install the latest npm published alpha release of storybook for react.

Replace react with any other package we maintain 👍

**Comment by andrewcashmore** [comment]
Thank you! 😄
