### ISSUE TITLE
storybook.js.org domain

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1118]
## why
consistent branding: as much as possible, singular `storybook` or `storybookjs` worst case.

## what
Move `storybooks.js.org` => `storybook.js.org`
- [x] update js.org DNS https://github.com/js-org/dns.js.org/pull/1262
- [x] migrate docs from `storybooks/storybooks.github.io` to `storybooks/storybook/docs`
- [x] upgrade docs build/deploy/travis scripts etc.
- [x] update all references in github/docs/etc.
- [x] update all external references e.g. `twitter`, `youtube`, `medium`, `opencollective`
- [x] set up redirect from old domain to new @shilman *ready for merge*

**Comment by ndelangen** [comment]
@shilman Ready to go!
