### ISSUE TITLE
Double render when first enter web-app

### ISSUE THREAD

**Issue by Stupidism** [storybooks/storybook#1120]
This may cause confusions for components cares about render times.
I found this bug in my own demo [project](https://stupidism.github.io/stupid-rc-starter/?selectedKind=RenderCounter&selectedStory=single-level).

## how to reproduce
Click the link above first.
If I enter homepage first and then come to component page, they are rendered once.

![image](https://cloud.githubusercontent.com/assets/5801015/26419437/a487b65c-4074-11e7-88b2-9d2f8253d98d.png)

But if I refresh in component page(or enter component page directly), they are rendered twice.

![image](https://cloud.githubusercontent.com/assets/5801015/26419411/84a3adbe-4074-11e7-933c-d04e7a092aa5.png)

## expected
Components should only be rendered once in both situations above

**Comment by Stupidism** [comment]
@shilman I think this happens because the url is updated after first render?

**Comment by shilman** [comment]
@Stupidism Hmm that could be it. Mind testing it out—I'd do it myself but your demo project seems to be offline. If you're right, it shouldn't happen when you navigate directly to the final URL. Please let me know what you find, and if it's due to the redirect then I'd say this isn't actually a bug.

**Comment by Stupidism** [comment]
@shilman Sorry, the above [link](https://stupidism.github.io/stupid-rc-starter/?selectedKind=RenderCounter&selectedStory=single-level) is updated now.

**Comment by shilman** [comment]
Hmm it looks like the double-render happens even when the URL is not updated?

**Comment by Stupidism** [comment]
@shilman Also, it renders twice when HMR

**Comment by Stupidism** [comment]
@shilman It always calls the render function twice.
