### ISSUE TITLE
Link to external site would navigate preview iframe with no way to reset

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#1122]
For a story that has a link to an external site, if the user clicks and navigates to the site, there's no way to return the preview iframe back except to refresh the page.

Story:
```
<a href="https://www.google.com">Click here to be banished forever!</a>
or 
<a href="/somewhere/far/far/away">Click here to get lost!</a>
```

Discovered this bug while playing with Lonely Planet's Storybook:
https://github.com/lonelyplanet/backpack-ui

I think we can fix it by detecting the location of the iframe when navigating to a new story and reload the entire iframe if it's in the wrong place.

**Comment by blairanderson** [comment]
I am having this problem as well.

**Comment by ndelangen** [comment]
https://github.com/storybooks/storybook/issues/7#issuecomment-313653199

I don't think we should touch this behavior tbh. It's the web. You made an `<a>` without a target.. This is what happens.

But having said that.. You could easily wrap a decorator or addon to `preventDefault()` that.

**Comment by Hypnosphi** [comment]
#1650 solves this while respecting usual browser behaviour
