### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybook#1126]
Currently here's the [LICENSE](https://github.com/storybooks/storybook/blob/master/LICENSE)

Basically, the copyright goes to a company which is no longer maintaining the project.
So, I think it's better to move this to some other party which has no financial or other bad agendas in  mind.

So guys, tell us what we can do about this.

While this is going on, I (kadira.io) will hold the copyright and I promise **NOT TO DO** anything evil.

**Comment by arunoda** [comment]
May be [JS foundation ](https://js.foundation/)or something.

**Comment by shilman** [comment]
@arunoda we started an open collective at:

https://opencollective.com/storybook

@ndelangen and I will consult with those folks to see whether the collective can hold the copyright somehow. If not, I think something JS foundation could be a good option also.

**Comment by arunoda** [comment]
@shilman that's good. But handing over the copyright to a fund raising company seems not like a good idea. (May be they don't have any evil agendas, but there could be something)

**Comment by shilman** [comment]
@arunoda agree we would want to understand the implications 100% before doing anything. just read through the opencollective docs and it's actually pretty unclear what's going on here. clearly "opencollective" itself is a for-profit entity, but i have no idea about the legal status of the collectives themselves. will consult my lawyer. fortunately we've raised exactly $0 so far so it doesn't matter what the status is yet. 😬

**Comment by ndelangen** [comment]
copen collective is not the place, the [JS foundation](https://js.foundation/) sounds like the right place to me

**Comment by shilman** [comment]
Ok, agreed. Sounds like there are separate discussions to have about the opencollective, but independent of this LICENSE issue. My bad.

**Comment by paulmolluzzo** [comment]
What about [Creative Commons](https://creativecommons.org)? ([wiki](https://en.m.wikipedia.org/wiki/Creative_Commons))

Specifically I'm referring to their [Attribution 4.0 license](https://creativecommons.org/licenses/by/4.0/), which is super open like MIT. IANAL, but I think it's nearly the same as MIT in that anyone can use the software for any purpose, but can't hold the author liable for any bad things. Moving forward Kadira wouldn't really have to do anything I don't think, including exist as a business.

Another option might be [releasing to public domain](https://creativecommons.org/publicdomain/). In this case Kadira is sort of "setting it free". Again IANAL, but I think this is sort of like "Here you go World, do whatever you want I'm gone".

Anyone more family with this can correct anything I've said. This is not something I'm familiar with, I'm just googling. 😀

**Comment by danielduan** [comment]
Let's keep the MIT license.

Many companies allow blanket usage of MIT and BSD but require special approvals for CC.

**Comment by ndelangen** [comment]
@arunoda Would you be if I would just remove the kadira part from the LICENCE?

**Comment by arunoda** [comment]
@ndelangen I'm fine with that.
But who'll hold the copyright then?
Do it wisely.

**Comment by paulmolluzzo** [comment]
@arunoda is there a reason you don't want to hold the copyright yourself not as Kadira but as an individual? Seems simple enough. 😀

**Comment by danielduan** [comment]
@ndelangen let's give the copyright to JS Foundation. We may have to go through some application process https://github.com/JSFoundation/TAC/blob/master/Project-Lifecycle.md#applying-to-join
