### ISSUE TITLE
DEPRECATED repo cleanup

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1133]
## why
After moving to the monorepo, we deprecated all the source repos. However the way we did it makes it look like the packages are no longer supported (in search, etc.):

![screen shot 2017-05-25 at 9 58 13 am](https://cloud.githubusercontent.com/assets/488689/26496336/67f63180-426a-11e7-965b-82d8fba647d2.png)

## what 
- [x] change title to `REPO/PACKAGE MOVED ...`
- [x] replace entire contents of README.md with short explanation

```
This contents of this repo was moved to the [Storybook monorepo](https://github.com/storybooks/storybook/) and the NPM package name has been changed.

- The old name of the package was: **OLD_PACKAGE**
- The new name of the package is: **@storybook/PACKAGE**
- The location of the code is: https://github.com/storybooks/storybook/tree/master/PATH

The repo you're looking at now is out of date and no longer maintained.
```

**Comment by shilman** [comment]
DONE!

**Comment by eddiemonge** [comment]
What was the point of the mono-repo? Makes its harder to track changes to the add-ons
