### ISSUE TITLE
New tagline

### ISSUE THREAD

**Issue by SachaG** [storybooks/storybook#1136]
"The UI Development Environment you'll [heart] to use" isn't very descriptive. Also, that heart icon randomly disappears for me sometimes so I just see an empty box. 

How about: 

> The UI component explorer, for React & React Native

> Build & maintain your own component libraries, for React & React Native

> Component-driven development doesn't have to be a fairy tale anymore (j/k)

**Comment by ndelangen** [comment]
If the heart is buggy we could try and replace it with an image with an alt attribute?

I quite like the slogan is it is, and doesn't name a UI toolkit in particular. 

Which is good because there are other UI libs out there, and we want to support some of them in the future: https://github.com/storybooks/storybook/blob/master/ROADMAP.md

**Comment by tmeasday** [comment]
I'm not religious about it, but we've been using "Component Explorer" to refer to the category that Storybook lives in. I prefer it to "Component Development Environment" for two reasons:

1. Less words is better
2. CDE implies a more restricted use case; I think we want Storybook to also be useful for other things like styleguides and documentation etc in the future

**Comment by ndelangen** [comment]
I changed the heart icon into an emoji.

I think storybook is much more then a components explorer, surely it's at the core of what storybook does, but it can do much more, and I want to slogan to reflect that.

Storybook will soon no longer be tied to react, so slogan should be framework agnostic.

I think I'll close this for now. Thanks for the suggestion!

**Comment by tmeasday** [comment]
I'd argue that "Component Development Environment" is more restricted in meaning than "Component Explorer". The former implies the development process of building a component, whereas to me the second allows other things like more static use cases.

**Comment by shilman** [comment]
@tmeasday I'd argue the opposite. To me explorer suggests browsing. I know it can be interpreted in other ways, but that's the way I'd interpret it. Development, to me, suggests build, test, document, etc. But that may just be me.

**Comment by tmeasday** [comment]
🤷‍♀️
