### ISSUE TITLE
Improve @storybook/* visibility on NPM

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1138]
## why

Currently when people search for e.g. `react storybook` on NPM, a lot of other results show up. `@storybook/*` should show up at the top. Search is powered by npms.io:

<img width="844" alt="npms" src="https://cloud.githubusercontent.com/assets/488689/26519299/3d6ab7fe-4302-11e7-8f71-385b78181f50.png">

This will clear up over time automatically, but we should accelerate it.

- Full list of ranking signals here: https://npms.io/about
- Analysis (?) for `@storybook/react`: https://api.npms.io/v2/package/%40storybook%2Freact

## what
- [x] Close a bunch of issues to improve the "active issues" / "total issues" number
- [ ] Improve our test coverage (team hackathon???)
- [ ] Get @arunoda or @mnmtanish to deprecate the `@kadira/*` packages after 3.0 release stabilizes

**Comment by ndelangen** [comment]
You bring up an issue stating we should bring our total issues down?

**Comment by UsulPro** [comment]
At this moment `@storybook/react` has 23,000 downloads per week on npm vs 61,000 of `@kadira/storybook`

`getstorybook` still has 1,787  downloads per week. it's already less than `@storybook/cli` but still meaningful

> This will clear up over time automatically, but we should accelerate it.

Possible step could be to involve `getstorybook` users to shift to `@Storybook` packages. Here is a proposal: storybooks/getstorybook#30

**Comment by Hypnosphi** [comment]
Does anyone really use anything other than web search (i.e. Google) to find stuff?

**Comment by ndelangen** [comment]
Either way, the correct packages (ours) show up first now.

**Comment by sodoku** [comment]
People who try to use npx will still download the old version. `npx getstorybook` will resolve to the deprecated version as the name matches.

**Comment by Hypnosphi** [comment]
Npx allows specifying package name:
```
npx getstorybook -p @storybook/cli
```

**Comment by sodoku** [comment]
@Hypnosphi thanks, I know. But unless you are aware that you have to do this to not get an outdated version, you would probably try to do `npx getstorybook` first. At least that's what I did and it took me a while until I realized that I was using an old version that is deprecated.

What do you think of printing a warning when you run the deprecated version?

**Comment by Hypnosphi** [comment]
I think we can even make it throw. @ndelangen WDYT?
