### ISSUE TITLE
less-loader in @kadira\storybook

### ISSUE THREAD

**Issue by leonidax** [storybooks/storybook#1150]
Hi, I was able to successfully use less-loader along with storybook but I had to modify the package.json under node_modules\@kadira\storybook, maybe less loader could be added by default in the storybook package.json.

There is more information about this issue in the following ticket [#691](https://github.com/storybooks/storybook/issues/691)

**Comment by shilman** [comment]
@leonidax you shouldn't need to modify the package. Instead you can just customize webpack:

https://storybook.js.org/configurations/custom-webpack-config/#extend-mode

Please give that a try and let me know if it works for you!

**Comment by leonidax** [comment]
Thanks for the quick answer.

I'm a bit puzzled, I cleaned the project to try to reproduce the problem and now I don't get it.

Seems to be working fine now, this is my wepback.config.js under .storybook

```
var genDefaultConfig = require('@kadira/storybook/dist/server/config/defaults/webpack.config.js');
const path = require('path');

module.exports = function (config, env) {

  var config = genDefaultConfig(config, env);

  config.module.loaders.push({
      test: /\.tsx?$/,
      exclude: /node_modules/,
      include: [/stories/, /components/],
      loader: "awesome-typescript-loader"
  })
  
  config.module.loaders.push({
      test: /\.less$/,
      exclude: /node_modules/,
      loaders: [ "style", "css", "less" ] 
  })

  config.resolve.extensions.push(".tsx");
  config.resolve.extensions.push(".ts");
  config.resolve.extensions.push(".css");
  config.resolve.extensions.push(".less");

  return config;
};
```

**Comment by shilman** [comment]
Glad to hear it! Closing this issue for now then.

**Comment by ndelangen** [comment]
Thanks for the suggestion!

Storybook will not include less support because if we would, we'd get a sass-request pretty quickly, and then a styles one, and then a modular-css one. 

And since all of em are incompatible with each other, we can only choose one. 
Can't be auto-detected either.

So it has to be an deliberate choice of a user to inject the <cssPreprocessor>-loader into webpack.

**Comment by leonidax** [comment]
True thanks :)
