### ISSUE TITLE
Using Storybook in a project with Wix's react-native-navigation?

### ISSUE THREAD

**Issue by gianko** [storybooks/storybook#1151]
I can't get it working... has someone tried it?

**Comment by Gongreg** [comment]
It does work :)

Give me few minutes for an example.

**Comment by SuttJ** [comment]
This doesn't seem to be working for me. When installing React-Native-Navigation to your project, it requires you to do stuff in Xcode:
![screen shot 2017-06-17 at 12 12 38 am](https://user-images.githubusercontent.com/29441327/27250027-2279868c-52f2-11e7-83af-a725278cca5c.png)

But my react app was a create-react-app so there's no xcode project to open. Did you follow those instructions above by going into Xcode?

**Comment by Gongreg** [comment]
Yes, I don't know if RNN supports CRNA. I'll quickly ask around.

**Comment by Gongreg** [comment]
@SuttJ so RNN doesn't support CRNA.

**Comment by SuttJ** [comment]
Alright. I appreciate you taking the time to find out, thanks!
On Jun 19, 2017, at 7:27 AM, Gytis Vinclovas <notifications@github.com<mailto:notifications@github.com>> wrote:


@SuttJ<https://github.com/suttj> so RNN doesn't support CRNA.

**Comment by Charlynux** [comment]
Take me some times to understand why Storybook stops on splash screen...

Just in case, I create a repository with correct configuration.
https://github.com/Charlynux/nativestorybook

**Comment by malcolm-kee** [comment]
Thanks @Charlynux for the sample.

For reference for anyone stumble upon this, I'm able to setup with the following changes on `storybook.js`:

```
import React, { Component } from "react";
import { AppRegistry } from "react-native";
import { Navigation } from "react-native-navigation";
import { getStorybookUI, configure } from "@storybook/react-native";

// import stories
configure(() => {
  require("./stories");
}, module);

// This assumes that storybook is running on the same host as your RN packager,
// to set manually use, e.g. host: 'localhost' option
const StorybookUIRoot = getStorybookUI({ port: 7007, onDeviceUI: true });

// react-native hot module loader must take in a Class - https://github.com/facebook/react-native/issues/10991
// https://github.com/storybooks/storybook/issues/2081
// eslint-disable-next-line react/prefer-stateless-function
class StorybookUIHMRRoot extends Component {
  render() {
    return <StorybookUIRoot />;
  }
}

Navigation.registerComponent("storybook.UI", () => StorybookUIHMRRoot);
Navigation.startSingleScreenApp({
  screen: {
    screen: "storybook.UI",
    title: "Storybook"
  }
});

export default StorybookUIHMRRoot;
```

**Comment by nenti** [comment]
With RNN@v2

```js
const StorybookUI = getStorybookUI({ port: 7007, onDeviceUI: true })
Navigation.registerComponent('storybook.UI', () => StorybookUI)
Navigation.events().registerAppLaunchedListener(async () => {
  await Navigation.setRoot({
    root: {
      component: {
        name: 'storybook.UI',
      },
    },
  })
})

export default StorybookUI
```

**Comment by kdawgwilk** [comment]
This still seems to blow up when adding the StorybookUI as another tab in RNN app rather than a single screen app
