### ISSUE TITLE
add a new option for breakIntoNewLines

### ISSUE THREAD

**Issue by Stupidism** [storybooks/storybook#1152]
[addons/info/src/components/Props.js#L27](https://github.com/storybooks/storybook/blob/master/addons/info/src/components/Props.js#L27)

I want an option to control this magic number `3` or force to `break into new lines`

**Comment by ndelangen** [comment]
Sounds good to me, PR is welcome!

**Comment by Stupidism** [comment]
How to get options inside `Props` component?
