### ISSUE TITLE
Addon panel is not positioned properly in vertical mode in safari

### ISSUE THREAD

**Issue by zillding** [storybooks/storybook#1169]
![screen shot 2017-05-31 at 10 09 29 pm](https://cloud.githubusercontent.com/assets/2175447/26636013/04134b70-464e-11e7-93eb-98a59a62d15d.png)

This seems to be something related to the flexbox styling.

safari v10.1.1
storybook v3.0.0

**Comment by tmeasday** [comment]
Confirmed.
