### ISSUE TITLE
Question: Loading stories from individual component folders?

### ISSUE THREAD

**Issue by reggi** [storybooks/storybook#1171]
I'm interested in editing my `config.js` to abide by a different storybook structure.

* /components
  * /SearchBox
    * /index.js
    * /story.js

Where each storybook story for a given component lives in the same folder with the component itself.

```js
import { configure } from '@kadira/storybook'

const req = require.context('./stories', true, /.stories.js$/)

function loadStories () {
  req.keys().forEach((filename) => req(filename))
}

configure(loadStories, module)
```
I think this would be a useful config to document for others as well.

**Comment by shilman** [comment]
@reggi like this?

https://storybook.js.org/basics/writing-stories/#loading-stories-dynamically

**Comment by reggi** [comment]
Thanks!

**Comment by alistair-hmh** [comment]
What if our components are in multiples node module folders? Eg:

```js
import { configure } from '@storybook/react';

const req = require.context("@my-lib/src/", true, /.stories.js$/);
const req2 = require.context("@your-lib/src/", true, /.stories.js$/);

configure(() => {
	req.keys().forEach(filename => req(filename));
}, module);
```

**Comment by zlw11063** [comment]
> What if our components are in multiples node module folders? Eg:
> 
> ```js
> import { configure } from '@storybook/react';
> 
> const req = require.context("@my-lib/src/", true, /.stories.js$/);
> const req2 = require.context("@your-lib/src/", true, /.stories.js$/);
> 
> // How can I require stories from req2?
> configure(() => {
> 	req.keys().forEach(filename => req(filename));
> }, module);
> ```

I would also like to know the right way to do this.

**Comment by alistair-hmh** [comment]
@zlw11063 - I found this kind of thing to work ok...

```js
import { configure } from '@storybook/react';

const reqs = [
    '@my-lib/src',
    '@your-lib/src'
].map(lib => require.context(lib, true, /.stories.js$/));

configure(() => {
    reqs.forEach(req => req.keys().forEach(filename => req(filename));
}, module);
``

**Comment by wbern** [comment]
@alistair-hmh don't you get webpack compile errors when using that?

**Comment by markolofsen** [comment]
**My variant:**

```
const req1 = require.context('../stories', true, /\.stories\.js$/);
const req2 = require.context('../widgets', true, /\.story\.js$/);
const libs = [req1, req2];

configure(() => libs.forEach(req => req.keys().forEach(f => req(f))), module);
```

**Comment by elewin** [comment]
Just pass them in as an array:

```
configure([
  require.context('../src/components', true, /\.stories\.js$/),
  require.context('../lib', true, /\.stories\.js$/)
], module);
```

https://storybook.js.org/docs/basics/writing-stories/#loading-stories-dynamically
