### ISSUE TITLE
Search on documentation

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#1177]
See https://github.com/storybooks/storybooks.github.io/issues/46

> Finding something in the documentation is hard right now.
> 
> We need to create something that will allow users to type in a query and we'll display a list of page / segments.

We should add a proper search to the homepage & header.

**Comment by tmeasday** [comment]
We should ask the algolia folks to setup docsearch for us

**Comment by tmeasday** [comment]
https://community.algolia.com/docsearch/

**Comment by ndelangen** [comment]
I submitted a request, cool suggestion!

**Comment by tmeasday** [comment]
LMK if you need help setting it up, I've done it before a few times ;)
