### ISSUE TITLE
Feature: Grouping like components with sidebar sections

### ISSUE THREAD

**Issue by reggi** [storybooks/storybook#1178]
Im interested in a way to group different components together based on different functionality or location in the app. A great example of a sidebar menu that does this is `GraphiQL`. You can see how when you click a section you have a full menu of new items and you can go back and forth. 

![jun-01-2017 11-49-44](https://cloud.githubusercontent.com/assets/296798/26688437/9afa95da-46c0-11e7-9e9b-2a55bef200ac.gif)

> Example scenario: Let's say you have a bunch of `form` components `Input`, `Select`, `Checkbox`, and then you have a bunch of `shape` components like `Circle`, `Square`, and `Triangle`. This idea would allow you to specify in the story file or perhaps in the folder structure, which component goes where. Allowing all the `shape` components to live together and all the `form`components all together.

Alternatively, a way to even group / order them with titles / header could help solve this issue as well.

**Comment by shilman** [comment]
@reggi the current workaround is to name your stories like "prefix.storyname" and then search for "prefix." in the search bar. obviously this is a hack, but it's something that's available today.

There are a couple other issues open that are related:
- Story categories https://github.com/storybooks/storybook/issues/458
- Substories/hierarchy https://github.com/storybooks/storybook/issues/151

If you think your idea can fit into one of those, perhaps we can close this and continue the conversation there? I think there is a group of people interested in working on this, though I'm not sure of the current status. @UsulPro ?

**Comment by ndelangen** [comment]
#1356 #1387 #1401 #1427 #151 
About to get released with `3.2.0`

**Comment by abnerlee** [comment]
@ndelangen I searched the doc, but I cannot find how to do this in your doc, so which doc should I refer to?

**Comment by ndelangen** [comment]
This issue is 2 years old, I lack the exact context of your question @abnerlee.

Can you elaborate what you're asking?

**Comment by Fr33maan** [comment]
`export default { title: 'Components.Button' }` Will create a category Components and place your Button story inside this category. Clean

**Comment by shilman** [comment]
@Fr33maan `Components/Button` in 6.0
