### ISSUE TITLE
update slow-start docs to use storybook 3.0

### ISSUE THREAD

**Issue by devdoomari** [storybooks/storybook#1180]
the doc says "do npm install --dev @kadira/storybook", 
but it seems that @kadira/storybook only goes up to version 2.

After fiddling with storybook-cli, I found the correct package to be `@storybook/react`

what do you think about updating that part of the doc?

**Comment by shilman** [comment]
@devdoomari that's definitely a bug, thanks for pointing it out! care to update the doc and issue a pull request? I can help you get it merged.

**Comment by devdoomari** [comment]
@shilman
but is @storybook/react the correct package for all use cases?
just to be sure - I might be wrong, and I'm not keen on doing a disservice by misinforming others.

**Comment by shilman** [comment]
@devdoomari it's the primary use case. At any rate, please give it a try and I'll review it thoroughly before merging the changes. Thanks so much!

**Comment by devdoomari** [comment]
@shilman

sorry I took so long to reply - but it seems that the docs have updated
so...closing! Thanks for your comments :)
