### ISSUE TITLE
Knobs Addon: use CodeMirror (or other editor) for object knobs

### ISSUE THREAD

**Issue by kohlmannj** [storybooks/storybook#1187]
Implement [CodeMirror](https://github.com/codemirror/codemirror) or another (lighter-weight?) code editor for the `object` knob. This will allow the user to focus on the data they're inputting, rather than manually formatting a JSON object literal.

Related: #1186

**Comment by z4o4z** [comment]
@kohlmannj It is really good idea, I'll try to do it!)
