### ISSUE TITLE
@storybook/addon-comments v3.0.0 falls with error

### ISSUE THREAD

**Issue by dangreen** [storybooks/storybook#1190]
```
VM9775 manager.bundle.js:94268 Uncaught TypeError: Cannot read property 'persister' of null
    at Container.init (VM9775 manager.bundle.js:94268)
    at Container.componentDidMount (VM9775 manager.bundle.js:94243)
    at VM7843 manager.bundle.js:28100
    at measureLifeCyclePerf (VM7843 manager.bundle.js:27910)
    at VM7843 manager.bundle.js:28099
    at CallbackQueue.notifyAll (VM7843 manager.bundle.js:11842)
    at ReactReconcileTransaction.close (VM7843 manager.bundle.js:32993)
    at ReactReconcileTransaction.closeAll (VM7843 manager.bundle.js:5946)
    at ReactReconcileTransaction.perform (VM7843 manager.bundle.js:5893)
    at batchedMountComponentIntoNode (VM7843 manager.bundle.js:12750)
```

**Comment by dangreen** [comment]
also
```
VM9775 manager.bundle.js:93970 Uncaught TypeError: Cannot read property 'persister' of null
    at DataStore._loadUsers (VM9775 manager.bundle.js:93970)
    at VM9775 manager.bundle.js:93917
```

**Comment by tmeasday** [comment]
Hi @dangreen, thanks for reporting this. I just confirmed this with both the `test-cra` app and a vanilla CRA app.

The issue is the lack of a database package. See https://github.com/storybooks/storybook/pull/1145.

I'm not totally sure how it worked before, or how to best move forward @ndelangen, but at the least we should indicate this problem on the comments addon for now.

**Comment by tmeasday** [comment]
@ndelangen -- what are your thoughts here?

**Comment by shilman** [comment]
@tmeasday @ndelangen let's get rid of comments in 3.2! 👍

**Comment by tmeasday** [comment]
@ndelangen confirmed to me he agrees we should remove it! If anyone objects, now would be a good time :)

**Comment by ndelangen** [comment]
Remove it, we will rebuild something like it when the time comes.

**Comment by jakiestfu** [comment]
I'm interested in this comments addon. Was the consensus to _not_ work on this for the time being? What needs to be done?

**Comment by ndelangen** [comment]
@jakiestfu I don't think we want to write custom connectors for all sorts of databases or chat apis... I'm not 100% sure on this, but it's how I feel about it now.

Of course I wouldn't stop anyone from writing such a thing, though we'd have to argue to add it to the core repo or not.

I'm not sure there's consensus about it, I'm personally a little divided on the issue, to be honest.

I have mentioned in the past that I think a good minimal viable solution would be to embed a system like https://disqus.com/ into an panel, what are your thoughts on that?
