### ISSUE TITLE
React Native Preview sets up channel only at render-time

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#1191]
See this code: https://github.com/storybooks/storybook/blob/cli-upgrade-mode/app/react-native/src/preview/index.js#L55-L72

The idea is that you pass in the `hostname` and `port` in the `getStorybookUI` call, and we can't create the channel until we know them. What is less clear is why the channel is only created at render time (i.e. in the callback) rather than immediately.

This causes issues with addons that expect the channel to be available immediately, i.e. the `options` addon (See https://github.com/storybooks/storybook/issues/815).

@ajwhite - @shilman and I recalled you were looking at this. Do you have any thoughts on that code? Any reason not to at least move it to the outside of the anonymous closure?

**Comment by shilman** [comment]
cc @mnmtanish we are proposing changes to code that you originally wrote, and we are trying to understand the implications. insights / suggestions welcome!

**Comment by tmeasday** [comment]
Note that the error message is show in storyshots at test time (I guess because the preview is *never* rendered).

```
 PASS  __tests__/storyshots.js (12.928s)
  ● Console
    console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
      Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
Error: Failed to find addon channel. This may be due to https://github.com/storybooks/storybook/issues/1192.
    at setOptions (/home/travis/build/storybooks/storybook/examples/react-native-vanilla/node_modules/@storybook/addon-options/dist/preview/index.js:28:11)
    at Timeout._onTimeout (/home/travis/build/storybooks/storybook/examples/react-native-vanilla/storybook/storybook.js:15:29)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

**Comment by tmeasday** [comment]
Hmm, maybe we should just make this change @shilman ;)
