### ISSUE TITLE
Options addon must be configured *after* the preview has rendered in React Native

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#1192]
As the addon channel is not created until render time in React Native (see https://github.com/storybooks/storybook/issues/1191), we cannot call `setOptions` until after that has happened. In practice, this currently means in a `setTimeout` block:

```js
const StorybookUI = getStorybookUI({ ... });
setTimeout(() => setOptions({ ... }), 1000);
```

### Reproduction
https://github.com/storybooks/storybook/issues/815#issuecomment-305822940

**Comment by samkelleher** [comment]
I'm just using regular web based react and I'm getting this error after a simple 3.0.0 > 3.1.6 upgrade.  Neither knobs or options addons I'm using work. It seems to be related to the missing addons channel which is not passed.
```
Failed prop type: The prop `channel` is marked as required in `WrapStory`, but its value is `null`.
    in WrapStory
```

This ultimatily results in an exception on the line `this.props.channel.removeListener('addon:knobs:knobChange', this.knobChanged);` as `channel` is null.

```
render.js:65 TypeError: Cannot read property 'removeListener' of null
    at WrapStory.componentWillUnmount (WrapStory.js:76)
    at ReactCompositeComponent.js:408
```

**Comment by Gongreg** [comment]
@tmeasday, this commit broke rn for me.

Both provider and manager breaks.

```
  this.channel = addons.getChannel();

    const secured = options.secured;
    const websocketType = secured ? 'wss' : 'ws';
    let url = `${websocketType}://${domain}`;
    if (options.manualId) {
      const pairedId = uuid();

      this.pairedId = pairedId;
      url += `/pairedId=${this.pairedId}`;
    }

    if (!this.channel) {
      this.channel = createChannel({ url });
      addons.setChannel(this.channel);

      this.channel.emit('channelCreated', { pairedId: this.pairedId });
    }
```
It had a check for channel before, now you simply throw up.
So we need to either add try catch around these lines, or revert the change.

**Comment by slorber** [comment]
Hi,

I'm not using RN but i got the error pointing to this issue after upgrading, is it normal?

**Comment by tmeasday** [comment]
@slorber -- sorry i missed this. I think this error can sometimes happen if your `node_modules` gets messed up and you have two versions of `@storybook/addons`, too.

**Comment by tmeasday** [comment]
We should see if https://github.com/storybooks/storybook/pull/2711 can be used to resolve this.

**Comment by slorber** [comment]
Will check next time I work on my storybook, haven't updated it for a while

**Comment by FredyC** [comment]
@tmeasday So is there some viable solution/workaround as of now? The #2711 have been merged, but I am not sure how that can be used actually.

**Comment by tmeasday** [comment]
@FredyC -- the workaround of calling from a timeout should still work.

I believe it turned out #2711 was an event from the manager side when the channel was created -- a similar change would be needed on the preview side to solve this issue (if I remember right). If someone is game to give it a go, it would be great! I think most of the core team doesn't use RN and is a little afraid to touch it, unfortunately.

**Comment by FredyC** [comment]
Actually, I just updated all packages yesterday and suddenly it seems to be working without any change. I guess some other change might have fixed?

    "@storybook/addon-actions": "^3.3.15",
    "@storybook/addon-links": "^3.3.15",
    "@storybook/react-native": "^3.3.15",

**Comment by danielduan** [comment]
can we verify that this has been fixed and close this ticket? @FredyC @tmeasday?

**Comment by FredyC** [comment]
Well, it seems more like a random issue. Even with those updated packages, I have seen that error time to time so I ended up with the timeout workaround which seems to be working so far, but it would be nice to have a proper solution for that.

**Comment by Gongreg** [comment]
@FredyC, hey. You are correct that this is a random issue. And the fix shouldn't be difficult. I would like to say that we can add the event to fix this issue (I would personally do it), but I have already failed multiple times to finish the functionality I am currently working on. If nobody will take this issue I will fix it, but I can't guarantee when I will do it. Sorry for that.

**Comment by tmeasday** [comment]
@danielduan as far as I know this remains an issue. I have not quite been brave enough to touch RN (which i don't use personally day-to-day) to try and resolve it, but I suspect it wouldn't be very hard to fix.

**Comment by xeroxoid** [comment]
Any news on this? Keep randomly getting it all day long today.

**Comment by Gongreg** [comment]
Hey, sorry for no bringing up no information, this issue was buried deep.

#3903 will solve this issue.
The channel will be created as soon as you call getStorybookUI instead of in middle of react render.

So you will be able to call:

```
const UI = getStorybookUI({...});

setOptions({...})
```
and you won't have to use any timeouts.

**Comment by Gongreg** [comment]
The #3903 was merged into the master. In Storybook v4 this issue is solved.
