### ISSUE TITLE
CLI support for next.js

### ISSUE THREAD

**Issue by rpersaud** [storybooks/storybook#1193]
getstorybook on an empty (pages/index.js) nextjs project yields :

  • Detecting project type. ✖
     Cannot read property 'react-native-scripts' of undefined

**Comment by shilman** [comment]
I think this is just a bug. Have issued a PR (#1195) to address the problem. I believe `getstorybook` will do the right thing in the fallback state and no special support is needed for `next.js`.

**Comment by shilman** [comment]
@rpersaud oops, closed this prematurely. i released the fix for this yesterday. would you mind upgrading `@storybook/cli` and trying again to verify the fix? it would help me a lot! 🙇

**Comment by rpersaud** [comment]
@shilman Yup, just upgraded and tried it - getstorybook now works! Good job!
