### ISSUE TITLE
README images are broken on npm

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1196]
## why

Relatively-linked images broken on https://www.npmjs.com/

<img width="598" alt="_storybook_addon-actions" src="https://cloud.githubusercontent.com/assets/488689/26785874/99861c9c-4a58-11e7-8801-e6f2cf2b4bca.png">

## what

Update github repository URL to `https://github.com/...` for all packages. See discussion in https://github.com/SamVerschueren/listr/pull/61

**Comment by xavcz** [comment]
Once published, it should be OK! 👌
