### ISSUE TITLE
Feature Change Proposal for Info Addon (move info button to story nav buttons)

### ISSUE THREAD

**Issue by smiket** [storybooks/storybook#1198]
Hi,

The info button on the top right corner can overlay actual component ui:

![image](https://cloud.githubusercontent.com/assets/679925/26788475/44c27174-49db-11e7-8b91-1f8daaaa2598.png)

I wonder if there could be a little info icon to the right of each story in the navbar instead:

![image](https://cloud.githubusercontent.com/assets/679925/26788524/77e2d4d6-49db-11e7-9722-9bc2c899144d.png)

Just thought I'd send a usability suggestion along.
Awesome tool :)

Thanks,
Steve

**Comment by ndelangen** [comment]
#1147 The entire info bit will be rendered in a panel instead
