### ISSUE TITLE
Generated React Native files do not work with storybook in a vanilla app.

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#1200]
I was putting together a RN app for https://github.com/storybooks/storybook/issues/1012, and ran into. I followed the following steps:

```
npm install -g react-native @storybook/cli
cd examples
react-native init ReactNativeVanilla

cd ReactNativeVanilla
# test that RN works :+1:
react-native run-ios

getstorybook
yarn run storybook
# storybook server/UI runs on port 7007

# run the app again, should see stories
react-native run-ios
```

At this stage I should see stories in the simulator, ie, something like
<img width="487" alt="screenshot 2017-06-06 12 43 42" src="https://cloud.githubusercontent.com/assets/132554/26811525/cf44e19e-4ab5-11e7-8874-bfc8ffab01af.png">

However, what I see is the standard starting app:
<img width="487" alt="screenshot 2017-06-06 12 44 55" src="https://cloud.githubusercontent.com/assets/132554/26811551/f50e38da-4ab5-11e7-8b95-b0fef0101cdf.png">

And no stories show in the UI.

I believe the problem was introduced by https://github.com/storybooks/storybook/commit/3e2673b96297a948fa11ed040b61b81686385a94, which means that `getstorybook` creates `storybook/index.js` rather than `storybook/index.[ios|android].js`. Changing the filename myself and restarting things fix the issue.

I can't find documentation but I think the core problem is in setting `--projectRoot=[configDir,projectDir]` here https://github.com/storybooks/storybook/blob/master/app/react-native/src/bin/storybook-start.js#L49, the RN packager will look for and `index.ios.js` in `configDir` (i.e. `./storybook`), and failing that, revert to the the `projectDir`.

**Comment by tmeasday** [comment]
This issue should be labelled `merged` but that label is gone, not sure why (@shilman?)

**Comment by shilman** [comment]
@tmeasday No idea what happened to `merged`?

**Comment by shilman** [comment]
This went out last week. Follow up issue: #1277
