### ISSUE TITLE
Empty main pane on Firefox Nightly

### ISSUE THREAD

**Issue by pascalduez** [storybooks/storybook#1210]
Greetings,

the main content pane is now showing in Firefox Nightly `55.0a1 (2017-06-05)`, while being properly rendered in the current stable version.

No error, nor any kind of useful log so far. 
Will try to debug later.

The Navigation pane is fine.
Probably just a CSS issue since the DOM content is present.

**Comment by pascalduez** [comment]
Just gave it another try, seems to be resolved with latest storybook version and Nightly version:

`58.0a1 (2017-09-30) (64-bit)` with either `layout.css.servo.enabled` true or false.

**Comment by Hypnosphi** [comment]
Feel free to reopen once it shows up again
