### ISSUE TITLE
React Native preview: use local ip address instead of localhost

### ISSUE THREAD

**Issue by slorber** [storybooks/storybook#1222]
As discussed with @shilman on Slack, for a CRNA/storybook newcomer, the situation can be confusing:
- The storybook points by default to localhost:7007
- Most CRNA users will tend to run on the phone, not emulator, and the phone can't reach the PC on localhost, leading to storybook not working when following the hello world tutorial (btw this "host" should rather be in hello world readme)

It's better to automatically detect the url if possible, because localhost will only work on emulator. For me if I want to work on the phone (with Expo) it should use

Before:

```
const StorybookUI = getStorybookUI({ port: 7007, host: 'localhost' });
```

After:

```
const StorybookUI = getStorybookUI({ port: 7007});
```

norbert said we could use react-script for that (not sure how)

> react-script is a package on npm used by create-react-app which does a lot of cool stuff including detecting the user’s local IP in a cross-platform way

**Comment by tmeasday** [comment]
Hey, I updated the title, as this issue applies as well to the general RN case (although simulator use is more common there I guess).

**Comment by slorber** [comment]
Found something useful on a blog post:

```
import { NativeModules } from 'react-native';
const { hostname } = url.parse(NativeModules.SourceCode.scriptURL);
```

https://medium.com/@inyono/using-react-native-storybook-with-create-react-native-app-471e531bb128

**Comment by shilman** [comment]
@slorber looks like a slam dunk! 🥇  mind putting together a quick PR for that?

**Comment by slorber** [comment]
I'll try very soon :)

**Comment by slorber** [comment]
The code above probably works but unfortunatly it's node code and it's not going to work in a browser app obviously. The host to target has to be defined at build time. 

Need https://github.com/react-community/create-react-native-app/issues/256 to be resolved first or find another way

**Comment by slorber** [comment]
Hmm no I'm sorry it works fine!

**Comment by slorber** [comment]
Just a question before: should we load the url lib or create a very simple function to parse domain 

like this (supposed to work in all browsers)

```
var tmp        = document.createElement ('a');
tmp.href   = "http://www.example.com/12xy45";
return tmp.hostname;
```

**Comment by shilman** [comment]
good question. i think it's fine to use this? https://www.npmjs.com/package/url
