### ISSUE TITLE
Centered addon: Invisible portions of overflowing components are inaccessible

### ISSUE THREAD

**Issue by su-narthur** [storybooks/storybook#1225]
When using the Centered addon, portions of a component which overflow the preview window are inaccessible.

Adding `overflow: scroll;` to the wrapper Centered creates allows for accessing the bottom inaccessible portion, but not the top inaccessible portion due to [this issue with flexbox](https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container).

Adding `margin: auto;` to an inner wrapper immediately inside the one Centered now creates seems to fix the issue without affecting the centering of components which completely fit. See [this explanation of the fix](https://stackoverflow.com/a/33455342/937377) and [this demo](https://jsfiddle.net/narthur/c9fovL3k/).

I blindly edited the addon's `src/index.js` file and came up with the following, though I'm new to the js development world and so didn't know how to compile it in order to test the fix:

```js
import React from 'react';

const style = {
  position: 'fixed',
  top: 0,
  left: 0,
  bottom: 0,
  right: 0,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  overflow: 'auto',
};

const innerStyle = {
  margin: 'auto',
}

export default function(storyFn) {
    return <div style={style}><div style={innerStyle}>{storyFn()}</div></div>;
}
```

Can this fix be added to the addon?

**Comment by ndelangen** [comment]
Do you see an opportunity to open a PR to fix this @su-narthur ?

**Comment by su-narthur** [comment]
@ndelangen Absolutely, this would be better as a PR. I hesitated, since I didn't know how to test my fix. Go for it anyway?

**Comment by ndelangen** [comment]
Go for it, I can help you test if you'd like. 

My schedule for tomorrow will only allow me to be available after 17:30 CEST though.

**Comment by su-narthur** [comment]
@ndelangen Ok, I've created a PR. What's next?

**Comment by ndelangen** [comment]
Thank you! I'll review and test it! 👍

**Comment by ndelangen** [comment]
Merged!

**Comment by casvil** [comment]
overflow-x does not work. I'll propose a PR

**Comment by kevinsar** [comment]
@casvil I can confirm that I am still seeing this bug in storybook 5.x.x, did you happen to come up with a fix?

**Comment by casvil** [comment]
hey @kevinsar , it was merged in https://github.com/storybookjs/storybook/pull/6361 but removed later in https://github.com/storybookjs/storybook/pull/6862. Sad
