### ISSUE TITLE
Not scrolling in full screen mode on iOS

### ISSUE THREAD

**Issue by plumbblake** [storybooks/storybook#1227]
The iframe is not scrolling on iOS. this could be fixed by setting its parent to `overflow: auto` and `-webkit-overflow-scrolling: touch`

potentially modifying the following object in `/lib/ui/src/modules/ui/components/layout/index.js` as seen below. 

```
const fullScreenPreviewStyle = {
  position: 'fixed',
  left: '0px',
  right: '0px',
  top: '0px',
  zIndex: 1,
  backgroundColor: '#FFF',
  height: '100%',
  width: '100%',
  border: 0,
  margin: 0,
  padding: 0,
  overflow: 'auto',
  webkitOverflowScrolling: 'touch',
};

**Comment by tmeasday** [comment]
Hi @plumbblake -- am I correct in saying this is *not* React Native, but a vanilla React storybook viewed on iOS?

**Comment by plumbblake** [comment]
@tmeasday That is correct.

**Comment by ArtanisAce** [comment]
Hi guys, would like to start contributing, so this might be a good first pick. Can I take it? :)

**Comment by Sandstedt** [comment]
This is still an issue, but not just in fullscreen mode, but also in the default viewing mode.

A quick and dirty fix is to att a file called manager-head.html in the .storybook folder and put this dirty css in it:

```
<style>
  /* Make the iframe scroll on iOS */

  .Pane.horizontal.Pane1>div>div+div {
    overflow: auto;
    -webkit-overflow-scrolling: touch;
  }
</style>
```
