### ISSUE TITLE
Documentation deployment inconsistent with package deployment

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1231]
why
===

- Documentation goes live as soon as its merged to `master`
- Packages go live as soon as somebody manually releases them (@shilman has been doing it about once a week so far)

This causes the documentation to be temporarily out of sync, and problems like this which is bad for users: https://github.com/storybooks/storybook/pull/1230

what
===

Either:
- [ ] Make documentation fixes part of the release process (somehow)
- [ ] Automate releases so that they happen as soon as a PR is merged

**Comment by tmeasday** [comment]
Unless we want to go all CD, I would recommend a `vNEXT` branch on the docs that is the "base" branch for PRs etc, and merge to master on release.

If we want to get really fancy we could do what we did for Meteor and have a deploy per release and a vNEXT deploy (http://docs.meteor.com/vNEXT/) but that's probably way over the top ;)

**Comment by shilman** [comment]
@tmeasday Chatted with @ndelangen in Slack and he proposed that we only deploy docs alongside `lerna publish`. This makes sense to me.

**Comment by ndelangen** [comment]
My goal is to go fully CD!

But right now that's just not going to work. 
- Test coverage is too low.
- There are no integration tests.
- There are no flow tests.
- Most addons are no tested at all.

I figured updating docs continuously already wouldn't be such a big deal. I was wrong, it's causing people to be confused when upgrading.

So yes, for right now I suggest to stop auto-deploying docs, and deploy manually (scripted) when performing a release.

**Comment by tmeasday** [comment]
Having a `deploy` branch or merging PRs to a different branch will have that effect btw.

**Comment by tmeasday** [comment]
I think this solves it: https://github.com/storybooks/storybook/issues/1357

**Comment by ndelangen** [comment]
Yes, We talked about this on slack:

- Docs should be deployed to separated instances per release.
- We will introduce a dropdown for selecting a release
- A deployed instance will do a periodic back-end call to something like `https://storybook.js.org/versions.json` to get the latest list of versions to display in the dropdown.
