### ISSUE TITLE
npm install --save prop-types causes severe problems with CRNA storybook

### ISSUE THREAD

**Issue by kdenz** [storybooks/storybook#1234]
I'm not sure if `npm install` of other packages will cause the same problem, I haven't tested that, but `npm install --save prop-types` to an out-of-the-box CRNA storybook app on RN 44, leads to loads of `npm run storybook`  errors like `Error: Can't resolve 'react' in '/Users/kmac/Desktop/storybook/react-native-multi-level-select/node_modules/react-modal/lib/components'` 

And in the end I had to remove `prop-types` and `@storybook/react-native` then rerun `getstorybook` for it to work again

**Comment by shilman** [comment]
Thanks @kdenz I'll check it out and see (1) whether I can reproduce the problem, and (2) whether I can make sense of what's going! It'll be a couple days though, so if anybody else wants to jump in here, go right ahead!

**Comment by danielduan** [comment]
If this is still a problem on the latest versions, please reopen. The cli should now install `prop-types` by default.
https://github.com/storybooks/storybook/blob/master/lib/cli/generators/REACT_NATIVE/index.js#L45
