### ISSUE TITLE
Mobile storybook view

### ISSUE THREAD

**Issue by necolas** [storybooks/storybook#124]
It would be great if we could view the storybook UI on a mobile device, especially when building mobile apps. At the moment the UI is missing meta tags for viewport scaling, and the nav / component menu has no mobile view (could probably be the standard hamburger + drawer pattern initially).

**Comment by arunoda** [comment]
Yes. This contains two issues actually.
We discuss about viewport resizing and mobile device previews here: https://github.com/kadirahq/react-storybook/pull/17

Also, it's great to have a mobile theme for Storybook itself. So, that's why I marked this as a feature.
If you can work on this, we are more than happy :)

**Comment by kevinSuttle** [comment]
Related: I like how this was done, with grabbers to resize. http://styleguide.devbproto.com/styleguide/

**Comment by arunoda** [comment]
Now we support full screen mode with the keyboard shortcuts. See: https://github.com/kadirahq/react-storybook/pull/17#issuecomment-217112876

This is not directly related to mobile view BTW.
Anyway, we need to have a mobile UI as well.

**Comment by udiedrichsen** [comment]
It would be great if you could make in the "keyboard shortcuts" dialog the shortcut description
clickable. I think that should be easy to implement.

With that feature we could use your great storybook on a smartphone 💯

**Comment by tmaly1980** [comment]
What would be required to make a standalone storybook app on an independent mobile device? Something like NativeBase's Kitchen Sink app with the drawer to list the stories. If it's not in the works, maybe there's some sort of direction on how to add a menu that can control the stories? Would anything else be needed to make it possible to disconnect the phone and still switch to other stories?

**Comment by danielduan** [comment]
#1740 solves part of this problem by changing the iframe size.

**Comment by denkristoffer** [comment]
I'm just commenting to avoid the bot closing this issue. Sorry about that.

**Comment by ndelangen** [comment]
No worries @denkristoffer thanks perfectly fine to do, I hear @UsulPro is back and might invest some time on this again. 🙇  (after 3.3)

**Comment by denzenin** [comment]
@necolas Hi Nicolas, I have faced the same issue. I need to test some components on mobile device. Maybe you have found some simple workaround for that?

**Comment by Hypnosphi** [comment]
@denzenin currently the best you can do is to append `full=1` to a story URL — this will turn on fullscreen preview mode

**Comment by denzenin** [comment]
@Hypnosphi thanks for the info

**Comment by denzenin** [comment]
https://github.com/storybooks/storybook/pull/3337

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.3`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.3)
