### ISSUE TITLE
Info Addon emits prop-type warning in 3.1.2

### ISSUE THREAD

**Issue by pierrecholhot** [storybooks/storybook#1247]
Using Storybook 3.1.2 and `@storybook/addon-info` 3.1.2 I get the following warning in some decorated components:

> Warning: Failed prop type: Invalid prop `node.type` of type `function` supplied to `Props`, expected `object`.
>     in Props (created by Node)
>     in Node (created by Story)
>     in pre (created by Pre)
>     in Pre (created by Story)
>     in div (created by Story)
>     in div (created by Story)
>     in div (created by Story)
>     in div (created by Story)
>     in div (created by Story)
>     in Story
>     in MuiThemeProvider (created by Theme)
>     in Theme

I believe this commit (c9ee900031549d3ff197fec4312b5300475030b4) fixes _or is related to_ the issue.

This should be noted somewhere for reference.

**Comment by danielduan** [comment]
If this is still a problem on later versions, please reopen this issue.
