### ISSUE TITLE
Remove margin in FullScreen for large components (100vh space)

### ISSUE THREAD

**Issue by MykolaGolubyev** [storybooks/storybook#1255]
Hello,
Do you think margin around a component can be removed in full screen mode?
Use case: testing {height: 100vh} components.

If this idea sounds good, I will try to look into it.

**Comment by kohlmannj** [comment]
@MykolaGolubyev I've added some basic `body` styles to `preview-head.html` to work around this:

```html
<style type="text/css">
  body {
    margin: 0;
    padding: 0;
  }
</style>
```

The bigger question, of course, is if something like this should be the default for the preview iframe.

**Comment by danielduan** [comment]
We have any `reset.css` sort of thing implemented for the Storybook iframe so the margin is probably your browser's default style getting rendered.

I don't think we should be overriding default browser behavior because that's helpful for catching browser specific bugs/behaviors. If you'd like to change your specific usage, @kohlmannj's solution is the best way to go.

**Comment by ndelangen** [comment]
I agree with @danielduan, this is exactly why the `preview-head.html` option is there.

Another option would be to expand the `addon-viewport` with some additional functionality:
setting padding/margin and possible also centering...

**Comment by joseneto-fixeads** [comment]
The storybook iframe (#storybook-preview-iframe) has a default margin (the chrome puts 8px margin on iframe). Components with 100vh broken, with a scrollbar :(

**Comment by Hypnosphi** [comment]
@joseneto-fixeads did you try to add `preview-head.html` file? https://storybook.js.org/configurations/add-custom-head-tags/

**Comment by joseneto-fixeads** [comment]
@Hypnosphi , Thanks! this solved the problem. I read already about this file, but I don't find him. I don't know the file must be created. Thanks!!!!

**Comment by jackblackCH** [comment]
How about a decorator for stories? `myStory.addDecorator(withBorderless);`

**Comment by jackblackCH** [comment]
A simple and still customizable plugin like solution via a decorator. We inject a style tag that overrides the body class in the iframe.

1. Add file to `.storybook/addons/no-border.js` -> `export default story => `<style>.sb-show-main{margin: 0}</style>${story()}`

2. In the story
```
import { storiesOf } from '@storybook/html'; // or react
import noBorder from '<path_back_to_root>.storybook/addons/no-border';

storiesOf('MyStory', module)
  .addDecorator(noBorder)
...
```

**Comment by Obiwarn** [comment]
Does not seem to work in SB 6 anymore?

**Comment by shilman** [comment]
try `layout: 'fullscreen'` story parameter

**Comment by inodino** [comment]
@Obiwarn Doesn't work for me either with SB 6..

**Comment by chidioguejiofor** [comment]
The issue is that there seem to be inline styles in the storybook by default. Not sure how to remove these


<img width="840" alt="Screenshot 2020-10-06 at 9 44 54 AM" src="https://user-images.githubusercontent.com/38565349/95179534-a6dfe500-07b8-11eb-880f-47af2c1fc252.png">

**Comment by Obiwarn** [comment]
find the solution here:

https://github.com/storybookjs/storybook/issues/12109

**Comment by chidioguejiofor** [comment]
Thanks a lot, @Obiwarn . Solves the problem well.

**Comment by mrajewski** [comment]
> try `layout: 'fullscreen'` story parameter

work like a charm
