### ISSUE TITLE
Creating standalone storybook app?

### ISSUE THREAD

**Issue by tmaly1980** [storybooks/storybook#1257]
It would be awesome to be able to create a demoable storybook on an independent mobile device, something that can be packaged and tested out on a real phone without needing to control screens via a web browser/USB connection. If the storybook had a drawer like NativeBase's Kitchen Sink app, this could be shown and shared within a larger team beyond just the developers. Sketch and InVision's Craft apps can create interactive mockups on a real device.... I'd love to use Storybook in a similar fashion further down the design/development pipeline.

If something like this isn't ready relatively quickly, how could I go about creating something like this myself? I'm looking to develop an launch an app in the next month, and it would be nice to use Storybook as part of the design/testing process.

**Comment by shilman** [comment]
@orta @ajwhite care to chime in here?
