### ISSUE TITLE
Info Addon: globally customize default values

### ISSUE THREAD

**Issue by kohlmannj** [storybooks/storybook#1261]
My usage of the info addon is such that I'd prefer that the story's source code is _never_ truncated. Therefore, it'd be great if there were a way to set [the default options](https://github.com/storybooks/storybook/blob/master/addons/info/src/index.js#L7) globally, rather than on a per-story basis, perhaps like this:

```jsx
// in config.js
import InfoAddon from '@storybook/addon-info';

setAddon(InfoAddon({
  maxPropsIntoLine: Infinity,
  maxPropObjectKeys: Infinity,
  maxPropArrayLength: Infinity,
  maxPropStringLength: Infinity,
});
```

**Comment by danielduan** [comment]
It's been added.
https://github.com/storybooks/storybook/tree/master/addons/info#global-options
