### ISSUE TITLE
Feature: Support Vue

### ISSUE THREAD

**Issue by hzoo** [storybooks/storybook#1262]
Talking with @ndelangen about storybook also supporting rendering Vue components; seems like it is a viable solution instead forking or building a separate tool. I believe there has been interest in supporting it from others and the team but no one actively working on this? 

> https://github.com/storybooks/storybook/blob/master/ROADMAP.md#supporting-other-frameworks-and-libraries

Some notes:
- Rendering is done in: https://github.com/storybooks/storybook/blob/master/app/react/src/client/preview/render.js
- There are a few UI elements in storybook itself written with react but maybe we can just leave those in?
- Might be easy to support the JSX way of writing a vue component, but most of vue is in `.vue` files so need to figure out how to load those files? Or maybe just use https://github.com/vuejs/babel-plugin-transform-vue-jsx to write the stories themselves but it would support .vue if that's easier (maybe weird to do that)? 

> For more in-depth info/discussion we can also discuss in https://storybooks-slackin.herokuapp.com

**Comment by gustojs** [comment]
I think optimally it would be best to show both React and Vue components together, especially for companies working with multiple stacks.

**Comment by TheLarkInn** [comment]
The vue-template-compiler has a great API that could be leveraged to take a .vue file and get back render functions.

https://github.com/vuejs/vue/blob/dev/packages/vue-template-compiler/README.md#compilercompiletofunctionstemplate

**Comment by kazupon** [comment]
I'm insterested in vue component supporting at the storybook.

As @TheLarkInn mentioned about it, Vue.js is publishing the `vue-template-compiler` has some API, We can get `render` function with API from template. However, before we are processing about it, we need to extract (parse) the vue component from `.vue` files.

There's something which I'm worrying about how to render the Vue and React component. 🤔

**Comment by zephraph** [comment]
I really like the idea of supporting other frameworks. I'd likely approach this more generically though by providing an API that frameworks could hook into. That way framework specific approaches could be isolated out, tested separately, and it gives the community a platform to build off of for other frameworks.

**Comment by ndelangen** [comment]
I got webpack to build succesful with a vue file with the vue loader.
https://github.com/storybooks/storybook/pull/1267

**Comment by ndelangen** [comment]
I need help getting it to actually render

**Comment by kazupon** [comment]
Hi @ndelangen
I want to help vue supporting as collaborator of storybook.
I had started implementing now.
https://github.com/kazupon/storybook/commits/add-app-vue

**Comment by alexandrebodin** [comment]
An alpha was juste released guys !

- getstorybook command => @storybook/cli 3.2.0-alpha.0 
- runtime => @storybook/vue 3.0.0-alpha.3 
- addon notes => @storybook/addon-notes 3.2.0-alpha.0
- addon knobs => @storybook/addon-knobs 3.2.0-alpha.0

Bug report and Feedbacks are very much welcome !!

**Comment by nblackburn** [comment]
I think this is a great idea as the name doesn't allude to it being exclusive to React so support for other frameworks would be great.

**Comment by shilman** [comment]
I've released an updated alpha of @alexandrebodin / @kazupon / @ndelangen 's wonderful  `@storybook/vue` along with some other pre-release features such as story hierarchies. Please try it out and give feedback to help us get this ready for a broader release:

https://gist.github.com/shilman/947a3d1d4cfdf5c3a8bb06d3d4eb84cf

cc @hzoo @gustojs @nblackburn @thelarkinn

**Comment by shilman** [comment]
@ndelangen @alexandrebodin @kazupon  Currently there's a problem with `getstorybook` for Vue. See these instructions for details:

https://gist.github.com/shilman/947a3d1d4cfdf5c3a8bb06d3d4eb84cf#vue-support-1262

Any ideas?

**Comment by andreiglingeanu** [comment]
Wow! This looks so awesome!

**Comment by alexandrebodin** [comment]
@shilman  

I just published `3.2.0-alpha.6`which works with getstorybook now.

**Comment by ndelangen** [comment]
We will be making an announcement tomorrow 🥁
