### ISSUE TITLE
Commands on landing page

### ISSUE THREAD

**Issue by tmaly1980** [storybooks/storybook#1270]
The landing page on localhost:7007 says to run `npm run <platform>`, when it should be `react-native run-<platform>` . There may be some installs that add a "run" script to package.json, but mine (ignite) does not.

**Comment by shilman** [comment]
Thanks @tmaly1980 this is a typo. I fixed it earlier, but it looks like the fix go undone in a later release. I fixed it again in https://github.com/storybooks/storybook/pull/1259 but I'll leave this open to make sure it gets into our next release.

**Comment by tmeasday** [comment]
Fixed in 3.1.6!
