### ISSUE TITLE
`getstorybook` cannot determine the app name for RN projects

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1277]
## why

`getstorybook` needs the project name to properly configure the RN entry files, but it fails silently: 

https://github.com/storybooks/storybook/blob/67d6af3670e93364590a9a9423442cc6ebc0eb12/lib/cli/generators/REACT_NATIVE/index.js#L13

When it fails, storybook does not properly inject itself into the AppRegistry, and when the user runs the app, no stories appear on the device.

## what
- [x] improve the heuristic for determining project name
- [x] give a big warning if it cannot determine project name so that it is less confusing and the user can set it by hand

**Comment by tmeasday** [comment]
Confirmed

**Comment by shilman** [comment]
Fixed and released: https://github.com/storybooks/storybook/releases/tag/v3.1.4

**Comment by eric-burel** [comment]
Hi, how are we supposed to set the name? I just began using React Native this week, with CRNA so I am using the very last version. `package.json` and `app.json` both have a `name` property.
