### ISSUE TITLE
Resolve local module linking in example apps

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#1286]
With the switch to npm@5, the way that the `test-cra` and `react-native-vanilla` apps were linked (via `file://` links) changed from "installs" to symlinks, similarly to lerna's behavior. See https://github.com/npm/npm/pull/15900 for more info.

To start with, this sort of removes the point of `test-cra` as it behaves the same as `cra-storybook|kitchen-sink`.

However, there are [some problems](https://github.com/storybooks/storybook/pull/1259#issuecomment-308614044) with symlinking our local dependencies that the `file://` links solved. In particular:

1. Jest ends up executing modules multiple times (https://github.com/facebook/jest/issues/3830), leading to issues of [this form](https://travis-ci.org/storybooks/storybook/builds/241926871#L812), or [this form](https://travis-ci.org/storybooks/storybook/builds/244451361#L698).

2. RN cannot resolve over symlinks (https://github.com/facebook/react-native/issues/637) making our example apps non-functional, and mostly pointless.

I'm not sure if/when the above issues will be solved, so we may want to consider other solutions to the problem. Here are some things that we can investigate:

A. Only supporting npm<5 for development.

B. Following the recommended fallback of `npm pack`-ing our packages and creating `file://` links to the `.tar.gz` (or using a tool like https://www.npmjs.com/package/install-local to do that).

C. Investigating yarn's support for workspaces -https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-workspaces-install-phase-1.md

I would appreciate thoughts on all this from anyone with experience with this kind of thing.

**Comment by shilman** [comment]
@tmeasday Thanks so much for investigating this. I don't have great ideas on how to move forward. In the short term, I am sidelining my RN-related example app changes and pushing forward with the react-only stuff. What a colossal pain in the ... neck.

**Comment by tmeasday** [comment]
Note that we have gone with technique B. in #1332, but I'll leave this open for a longer-term solution.

**Comment by tmeasday** [comment]
I think this problem is mostly OK now.

**Comment by Hypnosphi** [comment]
Not really. When testing RN, you have to do `yarn bootstrap --reset --core --reactnative` after each change in packages

**Comment by Hypnosphi** [comment]
@danielduan does the bot ignore mentions from PRs? This issue had one 3 days ago

**Comment by dangreenisrael** [comment]
@tmeasday I was working on implementing a new logger in RN, but the process of building and testing with the example was indeed a nightmare. I have some stuff I was working (haul and workspaces) for the RN example over the weekend, but probably won't have time to get to until the new year. I can push my (broken) code if you would like to take a look and/or a crack at it.

**Comment by tmeasday** [comment]
Oh! My bad, sorry!

**Comment by tmeasday** [comment]
And @dangreenisrael may as well post any information / branches to this issue as you can, hopefully someone can figure it out!
