### ISSUE TITLE
Toggle downPanel by default?

### ISSUE THREAD

**Issue by blairanderson** [storybooks/storybook#1295]
I would like to have the downPanel toggled by default. I'm hiding the actions because they are not useful for me at the moment.

**Comment by shilman** [comment]
@blairanderson this should do the trick: https://github.com/storybooks/storybook/tree/master/addons/options

**Comment by blairanderson** [comment]
@shilman exactly! 

FYI for people googling: https://github.com/storybooks/storybook/tree/master/addons/options#getting-started
