### ISSUE TITLE
addon: info - truncating props? how to update and change?

### ISSUE THREAD

**Issue by blairanderson** [storybooks/storybook#1299]
If i use the info addon: https://github.com/storybooks/storybook/tree/master/addons/info

sometimes props are truncated. How can i change that?

**Comment by blairanderson** [comment]
I will add to documentation after finding the information.

**Comment by shilman** [comment]
@blairanderson take a look at this PR: https://github.com/storybooks/storybook/pull/1157

**Comment by Stupidism** [comment]
Here is my config for this problem
```
// config.js
import infoAddon, { setDefaults } from '@storybook/addon-info';


// addon-info
setDefaults({
  inline: true,
  maxPropsIntoLine: 1,
  maxPropObjectKeys: 10,
  maxPropArrayLength: 10,
  maxPropStringLength: 100,
});
setAddon(infoAddon);
```
