### ISSUE TITLE
[addon-info] How to specify new-line in description

### ISSUE THREAD

**Issue by Stupidism** [storybooks/storybook#1311]
Here is code and snapshot.
```
RenderCounter.propTypes = {
  /**
   * Initial count for RenderCounter.
   */
  initialCount: T.number,
  /**
   * (props[, next]) => (...args) => {...}
   * get full props of inner onRerender can get \n
   * if next is specified, inner onRerender will not be called until next is called
   */
  onRerender: T.func,
};
```

![image](https://user-images.githubusercontent.com/5801015/27256727-2f70893a-5374-11e7-842d-a7ed46db6c86.png)

**Comment by shilman** [comment]
@Stupidism is this a question or just a useful example for anybody who's trying to do this? Thanks!

**Comment by Stupidism** [comment]
Question. As you can see the description of onRerender should be displayed in three lines.

**Comment by Li0liQ** [comment]
There is no way to do that at the moment.
See https://github.com/storybooks/storybook/blob/master/addons/info/src/components/Story.js#L251 - description is added as a text node in markup.

**Comment by bmv437** [comment]
Any way to make it support markdown? 
Similar to
https://github.com/storybooks/storybook/blob/master/addons/info/src/components/Story.js#L222

**Comment by dangreenisrael** [comment]
@Stupidism would this PR solve your problem https://github.com/storybooks/storybook/pull/2053

@bmv437 I think having it support markdown would be problematic because the content is being rendered into a `<td>` which would be less than ideal with things like h*. However, I do think that supporting markdown in notes would make a lot of sense.

**Comment by Stupidism** [comment]
@dangreenisrael I think so. Thank you very much!
