### ISSUE TITLE
[addon-info]: Story does not pass down props into root div

### ISSUE THREAD

**Issue by Stupidism** [storybooks/storybook#1312]
I tried to add some stylesheet for Story

`return React.cloneElement(element, { className: 'root' });` is not working.

```

  .addDecorator((getStory) => {
    const element = getStory();
    if (element.type === Story) {
      // return React.cloneElement(element, { className: 'root' });
      return <div className="root">{element}</div>;
    }
    return element;
  });
```

**Comment by shilman** [comment]
@Stupidism can you give a little more context for what you're trying to do? Is it part of a repo? Thanks!

**Comment by Stupidism** [comment]
I wanted to override some stylesheet of the `Story` component of `addon-info`. Because it's not very proper now. for example #1310. But className prop is ignored by this `Story` component. By convention unknown props should be passed down to root div.

Problem is now I need to wrap another div on the component, which would cause some problem for other decorators.
