### ISSUE TITLE
How to override existing webpack plugins

### ISSUE THREAD

**Issue by Stupidism** [storybooks/storybook#1314]
I'm trying to serialize function in documentation.
I have a function 
```
  const handler = (props, next) => (count) => {
    if (Math.random() < possibility) {
      next();
      log('hit', possibility, props, count);
    } else {
      log('miss', possibility, props, count);
    }
  };
```
And I used `handler.toString()` to print it out:
![image](https://user-images.githubusercontent.com/5801015/27257950-1aef8cc8-53a0-11e7-9394-cf9a46dc3d33.png)

It's pretty good. But after uglify:
![image](https://user-images.githubusercontent.com/5801015/27257953-381ffe36-53a0-11e7-9d78-c705189d3338.png)

So I'm thinking If I can override the uglifyPlugin and turn off compress.

**Comment by Stupidism** [comment]
I also trying to find a solution from uglifyJS: https://github.com/mishoo/UglifyJS2/issues/2118

**Comment by ndelangen** [comment]
Here you go:
Webpack full control mode: https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode

**Comment by ndelangen** [comment]
Please re-open if you feel this doesn't solve your problem 👍
