### ISSUE TITLE
Warning: Failed prop type: Invalid prop `knob.value` of type `boolean` supplied to `BooleanType`, expected `string`.

### ISSUE THREAD

**Issue by Stupidism** [storybooks/storybook#1316]
```
Warning: Failed prop type: Invalid prop `knob.value` of type `boolean` supplied to `BooleanType`, expected `string`.
    in BooleanType (created by PropField)
    in PropField (created by propForm)
    in form (created by propForm)
    in propForm (created by Panel)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by DownPanel)
    in div (created by DownPanel)
    in div (created by DownPanel)
    in div (created by DownPanel)
    in DownPanel (created by Container(DownPanel))
    in Container(DownPanel) (created by Layout)
    in div (created by Layout)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by Layout)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by Layout)
    in div (created by Layout)
    in Layout (created by Container(Layout))
    in Container(Layout)
    in div
```

**Comment by alexandrebodin** [comment]
Will be fixed in the next release

**Comment by brycedorn** [comment]
@alexandrebodin any ETA on next release?

**Comment by shilman** [comment]
@alexandrebodin FYI our convention is to not close issues until the feature/fix has actually been released so I'm reopening this. 👍

**Comment by Stupidism** [comment]
Add `close #1316` in the commit. When it's merged into main branch. This issue will be closed automatically

**Comment by shilman** [comment]
@Stupidism our convention is to close when we actually issue release, which is not necessarily when things get merged to` master` so until we change our convention please don't do this. Thanks for the suggestion though! cc @tmeasday @ndelangen

**Comment by tmeasday** [comment]
The idea is to avoid people opening duplicate issues for bugs that have already been fixed (but not released). As GH doesn't surface closed issues very obviously, it's better to leave them open until release.

**Comment by shilman** [comment]
released in v3.1.5. closing.

**Comment by joefraley** [comment]
i'm seeing this same problem @storybook/addon-knobs@5.1.0-alpha.12

https://github.com/storybooks/storybook/pull/6242/files#diff-1ef64f4620ba27403ef22d0b335bc8afR12 shows what i mean

**Comment by jephjohnson** [comment]
Same Issue

**Comment by shilman** [comment]
@jephjohnson which version?
