### ISSUE TITLE
Knob DateType breaks storybook ui

### ISSUE THREAD

**Issue by alexandrebodin** [storybooks/storybook#1318]
## How to reproduce

on `master` run

```
yarn install
yarn bootstrap
cd examples/cra-kitchen-sink
yarn storybook
```

Then go to the Button wtih knobs story and then try to use cmd + shift + d

**Comment by tmeasday** [comment]
Hey @alexandrebodin -- have you confirmed this happens with real apps (i.e. not ones using `npm link`, like `cra-kitchen-sink`)?

See my comments here: https://github.com/storybooks/storybook/pull/1345#issuecomment-310557623
