### ISSUE TITLE
babelHelpers is not defined.

### ISSUE THREAD

**Issue by alejandronanez** [storybooks/storybook#1320]
Hello there, I created a React component library using Rollup/styled components and when I try to run story book I got this error:

<img width="1090" alt="screen shot 2017-06-19 at 1 43 30 pm" src="https://user-images.githubusercontent.com/464978/27300456-6a88bcc2-54f5-11e7-8b3e-28e1181d5e56.png">

```shell
babelHelpers is not defined
ReferenceError: babelHelpers is not defined
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:41768:58)
    at Object.defineProperty.value (http://localhost:9001/static/preview.bundle.js:42381:30)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:660:30)
    at fn (http://localhost:9001/static/preview.bundle.js:86:20)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:42395:70)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:42414:30)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:660:30)
    at fn (http://localhost:9001/static/preview.bundle.js:86:20)
    at loadStories (http://localhost:9001/static/preview.bundle.js:40294:2)
    at ConfigApi._renderMain (http://localhost:9001/static/preview.bundle.js:40760:20
```
I'm using master branch https://github.com/react-medellin/components/tree/master for this and regular global installation for story book.

Any ideas why is this happening?

Thanks!!!

**Comment by shilman** [comment]
@alejandronanez can you give more info about how you did the install, or better yet share a repo?

**Comment by alejandronanez** [comment]
Hello @shilman,
You can check what I've done in here: https://github.com/react-medellin/components/tree/storybook if you have time you can `yarn && yarn storybook` and then open `localhost:9001`

**Comment by shilman** [comment]
I played around with it and it works if I remove "external-helpers" from the `.babelrc`. Hope that helps! Closing for now.

**Comment by alejandronanez** [comment]
Hmmm `external-helpers` is needed by my library (I'm using rollup) will dig into it and see what's going on! If I find a good solution I'll post it here in case anyone has a similar problem.

**Comment by shilman** [comment]
Good luck! Let us know how it works out!

**Comment by emartini** [comment]
@alejandronanez, you can remove `external-helpers` from your `.babelrc` file and enable it back only on your `rollup.config.js` using the [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel)

```js
import babel from 'rollup-plugin-babel';
export default {
  // ...
  plugins: [
    babel({
      exclude: 'node_modules/**',
      plugins: ['external-helpers']
    }),
  ]
}
```

**Comment by alejandronanez** [comment]
Hey Esteban! Will try that! Thanks!!!!

**Comment by alejandronanez** [comment]
Just tried this, worked like charm! Thanks!

**Comment by Tomekmularczyk** [comment]
Isn't the working configuration missing...

```js
import babel from 'rollup-plugin-babel';
export default {
  // ...
  plugins: [
    babel({
      exclude: 'node_modules/**',
      plugins: ['external-helpers'],
      externalHelpers: true,  // ...this field ???
    }),
  ]
}
```

**Comment by wilomgfx** [comment]
@Tomekmularczyk 
No `externalHelpers` is not supported

from the [readme](https://github.com/rollup/rollup-plugin-babel#usage)

> All options are as per the Babel documentation, except the following:
**options.externalHelpers**: a boolean value indicating whether to bundle in the Babel helpers

**Comment by MrJadaml** [comment]
For future googlers -Setting format to ES module in _rollup.config.js_ was the fix for me: `output.format: 'es'`

Rollup docs:
>an ES module bundle, suitable for use in other people's **libraries** and applications, that imports the external dependency.
