### ISSUE TITLE
Storyshots is intended only to be used with storybook

### ISSUE THREAD

**Issue by kurumkan** [storybooks/storybook#1324]
Here is my test file code:

    import React from 'react';
    import { mount } from 'enzyme';
    import renderer from 'react-test-renderer';
    import initStoryshots from '@storybook/addon-storyshots';
    
    import IconCell from './';
    initStoryshots();
    test('iconcell', () => {
        expect(renderer.create(<IconCell size="normal" type="pause" />).toJSON()).toMatchSnapshot();
    });

jest configs has this: 

    "moduleFileExtensions": [
      "json",
      "js",
      "jsx"
    ],

but it throws:

     storyshots is intended only to be used with storybook 
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/index.js:106:11)

**Comment by ndelangen** [comment]
Is `@storybook/react` a dependency listed in your `package.json`?

**Comment by kurumkan** [comment]
Hi there, I followed the instructions from [here](https://www.npmjs.com/package/@storybook/react)
But the answer to your question - no, there is no such entry @storybook/react in my package json.

**Comment by tmeasday** [comment]
Hey @kurumkan -- did something go wrong when you ran `getstorybook`? It should have added that entry for you. 

Maybe storyshots' error message could be better here?

**Comment by ndelangen** [comment]
Duplicate: https://github.com/storybooks/storybook/issues/1323

I think both have been answered? Please let us know if you need further help?
