### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by vijaybritto** [storybooks/storybook#1325]
I'm trying to install locally and i get the following error from npm.
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "i" "@storybook/cli"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /Users/vijay_britto/.npm/defined/1.0.0
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/vijay_britto/.npm/defined/1.0.0'
npm ERR!  { Error: EACCES: permission denied, mkdir '/Users/vijay_britto/.npm/defined/1.0.0'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/vijay_britto/.npm/defined/1.0.0',
npm ERR!   parent: 'detective' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vijay_britto/.npm/_logs/2017-06-20T10_25_26_884Z-debug.log`

Is this a known bug or am I missing something obvious?

**Comment by vijaybritto** [comment]
Fixed it after resetting permissions for that folder using `chown`

**Comment by paradox42** [comment]
@vijaybritto Mind to share your process of identify and fixing ? Appreciated.

**Comment by paradox42** [comment]
@vijaybritto  Thanks man, that's what I was looking for
