### ISSUE TITLE
Storyshots should warn if it finds no stories

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#1330]
Instead we see something like: https://travis-ci.org/storybooks/storybook/builds/244451361#L698

> Test suite failed to run
> Your test suite must contain at least one test.

Which I guess implies it, but we could be explicit about it.

**Comment by ArtanisAce** [comment]
Hi! Would like to take this as first contribution, and then keep jumping to more complex stuff :)

**Comment by tmeasday** [comment]
Awesome @artanisace. Let me know how I can help

**Comment by Hypnosphi** [comment]
Should be fixed in `3.3-alpha`
