### ISSUE TITLE
Does not render in IE11

### ISSUE THREAD

**Issue by chrisdhanaraj** [storybooks/storybook#1352]
Hey guys, just piping it with a new IE11 bug. Installing storybook on-top of create-react-app (or any existing React application) does not work in IE11. The side pane (with the iframe) does not render.

![image](https://user-images.githubusercontent.com/1266014/27499961-c9dfc0ba-582b-11e7-81c5-89a4d7141880.png)

**Comment by UsulPro** [comment]
confirm!
no console output, DOM nodes are all present, possible style problem?

**Comment by chrisdhanaraj** [comment]
Yeah, all the DOM nodes are present but trying to wade it in there to make it visible has been pretty futile over here

**Comment by samkelleher** [comment]
It looks like a CSS issue? with the classes `SplitPane vertical` which wraps the middle view. `Pane2` has no height and is what wraps the view, hence it doesn't appear.

**Comment by UsulPro** [comment]
Looks like it´s more [react-split-pane](https://github.com/tomkp/react-split-pane) issue. There is a demo page http://react-split-pane.surge.sh/ and it also doesn´t work in IE.

**Comment by UsulPro** [comment]
https://github.com/tomkp/react-split-pane/issues/207

**Comment by psimyn** [comment]
This looks fixed since react-split-panel version `0.1.64`

<img width="645" alt="screen shot 2017-07-10 at 2 05 22 pm copy" src="https://user-images.githubusercontent.com/1731922/28002476-ddda461c-6578-11e7-91d6-36d58b76943d.png">

**Comment by TrevorEyre** [comment]
I agree with @psimyn, it looks like this is fixed. Tested in IE 11 on Windows 8.1. @ndelangen, I think this issue can be closed.

![screen shot 2017-08-03 at 10 53 59 am](https://user-images.githubusercontent.com/6662070/28933405-2c3a6ea8-783a-11e7-97ab-e3f472ca4ad9.png)
