### ISSUE TITLE
Refactor `StoryStore` to be a separate package

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#1354]
So we can reuse it between the various app layers. It doesn't make sense to duplicate the `.storiesOf()` logic, and if we factor it out it's likely it can be used for other purposes.

**Comment by danielduan** [comment]
Is this still relevant? I feel like if we're gonna extract it as a package that we might as well refactor the thing and use redux or mobx.

**Comment by tmeasday** [comment]
Yes this is done in the form of `@storybook/core` 👍
