### ISSUE TITLE
Package @storybook/react doesn't exist

### ISSUE THREAD

**Issue by pedroabreu** [storybooks/storybook#1361]
I'm trying to use storybook in my project and I'm running into this issue when running `getstorybook`

```
 getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "Webpack React" app(node:83449) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Package `@storybook/react` doesn't exist
(node:83449) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've tried following the quick start guide by installing `npm install -g @storybook/cli` and the slow guide where I get this error

```
npm i --save-dev @storybook/react

npm ERR! code E404
npm ERR! 404 Not Found: @storybook/react@latest

npm ERR! A complete log of this run can be found in:
```

It's weird that I can't find any issue related to this. I'm running latest react

```
"react": "^15.6.1",
"react-addons-css-transition-group": "^15.6.0",
"react-addons-shallow-compare": "^15.6.0",
"react-addons-test-utils": "^15.6.0",
```

**Comment by shilman** [comment]
@pedroabreu what happens when you type:

```
npm view @storybook/react
```

**Comment by pedroabreu** [comment]
```
npm ERR! code E404
npm ERR! 404 no such package available : @storybook/react
npm ERR! 404
npm ERR! 404  '@storybook/react' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by shilman** [comment]
@pedroabreu how about
```
npm config ls 
```

**Comment by pedroabreu** [comment]
I've found that the issue is related to sinopia, seems that it doesn't play well with packages with `@`. If I start a new project from scratch it installs fine...

Sorry for wasting your time

**Comment by shilman** [comment]
No worries. Good luck! Closing this then 👍

**Comment by pedroabreu** [comment]
I'll just leave this here for people that might run into the same issue as me.

My issue was that I'm doing my package management through sinopia and because there's a know issue with parsing scoped packages (like @storybook), all calls to npmjs register will return a 404.

Way to fix this is to set a rule in your .npmrc to register npmjs instead of 

```
@storybook:registry=https://registry.npmjs.org/
```

It's not a full fix, since the ultimate goal would be to have this package cached in sinopia but it's a quick workaround

**Comment by swellingt0n** [comment]
@shilman I am having the same problem when using Nexus as a proxy for the npm registry. 
```
npm view @storybook/react
```
outputs

```
npm ERR!     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=proxyy)</h1>
npm ERR!     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=proxy)</p>
```
