### ISSUE TITLE
[Build Error] Latest webpack config is using old webpack 1 schema again !?

### ISSUE THREAD

**Issue by BerndWessels** [storybooks/storybook#1362]
Hi
"@ kadira/storybook": "2.35.3"

is using the old webpack 1 config again - see here `node_modules\@kadira\storybook\dist\server\config.js`:

```js
exports.default = function (configType, baseConfig, configDir) {
  var config = baseConfig;

  var babelConfig = (0, _babel_config2.default)(configDir);
  config.module.loaders[0].query = babelConfig;
```

As you can see it uses `module.loaders` rather than `module.rules`.

I can't tell exactly at which version of storybook that bug was introduced but it is now breaking all my builds.

**Comment by shilman** [comment]
@berndwessels `@kadira/storybook` is version 2.5.3. you want `@storybook/react` which is 3.x and uses webpack2

**Comment by BerndWessels** [comment]
Thank you.
