### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#1364]
Following up on the [documented release process](https://github.com/storybooks/storybook/pull/1348), we should fully automate package  releases, in concert with [Versioned Documentation](https://github.com/storybooks/storybook/issues/1357).

In line with the above, we should do the following:

1. Merge bugfixes / documentation improvements / etc directly to `master`. This should:
  - Run CI, obviously
  - If CI passes, publish a new PATCH version of changed packages via `lerna` on the CI server.
  - Update the x.y documentation in place.
  - Add an entry to the changelog

2. Merge new features to the `release/x.y` branch. This should:
  - Run CI, again.
  - If CI passes, publish a new `x.y-canary` release of changed packages, via `lerna`
  - Update the `x.y` preview documentation in place (or create it if this is the first commit to the branch).
  - Add an entry to the changelog

3. Run minor releases via merging `release/x.y` to `master`. This should:
 - I guess run CI, just to be sure ;)
 - Publish `x.y` versions for real, via `lerna`
 - Change the `x.y` documentation to be the latest, update all `<x.y` documentations to point to it and list it in their menus. Update `x.y-1` documentation to be "out-of-date".
 - Update the changelog with a release date, etc.

I think we can do all of that fairly easily, most of the pieces are in place now. It'll be fun!

**Comment by danielduan** [comment]
I think batched updates would be beneficial. Instead of every change merged to master, we can set to release patch updates twice a week.

**Comment by danielduan** [comment]
I'm gonna close this issue since the current process seems to work more or less. We can reopen this if needed.
