### ISSUE TITLE
Using different port for the packager (instead of the default 8081).

### ISSUE THREAD

**Issue by romshiri** [storybooks/storybook#1367]
It's not possible to run both React Native and Storybook packagers simultaneity as they both use port 8081 for running the packager.

I'd like to change the port Storybook packager runs on. 
The command "npm run storybook -p <port>" just change the port of the served HTML page.

**Comment by Gongreg** [comment]
Hey @romshiri,
Right now there is no way to do it.

But it can be quite easily implemented:

inside app/react-native/src/bin/storybook-start.js there are lines:

```
let cliCommand = 'node node_modules/react-native/local-cli/cli.js start';
if (program.haul) {
  cliCommand = `node node_modules/.bin/haul start --config ${program.haul} --platform all`;
}
```

We could add another command option for packager port.
If it was:
```
let cliCommand = 'node node_modules/react-native/local-cli/cli.js start --port=${YOUR PORT}';
```
It would work :).

If you want you could easily contribute on this thing. Or maybe I will have some free time tomorrow to do this.

**Comment by SaraChicaD** [comment]
i'm having this same problem :'(

**Comment by ndelangen** [comment]
Sounds like something we could very easily do @Gongreg ?
