### ISSUE TITLE
[addon-info] Story source incorrect when using static class properties

### ISSUE THREAD

**Issue by jonambas** [storybooks/storybook#1377]
Example component:
```
const Section = ({ children }) => <div>{ children }</div>;

class Panel extends Component {
  static Section = Section;

  render() {
    return <div>{ this.props.children }</div>;
  }
};
```

The story:
```
storiesOf('Test', module)
  .addWithInfo(
    'with some info',
    () => <Panel><Panel.Section>Hey</Panel.Section></Panel>
  );
```

Rendered info: 
![screen shot 2017-06-28 at 11 01 50 am](https://user-images.githubusercontent.com/3903325/27644335-40aa034a-5bf1-11e7-9023-3dd709c18f6e.png)

As you can see, `<Section />` should be `<Panel.Section />`. I'm working on a pretty large component lib that uses these 'nested' components pretty frequently, would be nice to find a fix 😢

**Comment by shilman** [comment]
@jonambas try: 

```
const Section = ({ children }) => <div>{ children }</div>;
Section.displayName = 'Panel.Section';
...
```

**Comment by jonambas** [comment]
@shilman 👍  Thanks, that did it

**Comment by shilman** [comment]
Great, closing for now!
