### ISSUE TITLE
Using getstorybook on Storybook 2.x repo

### ISSUE THREAD

**Issue by UsulPro** [storybooks/storybook#1378]
The most convenient way to migrate from Storybook 2.x to Storybook 3.x is to run `getstorybook` as it mention in our MIGRATION.md
It works fine but there are some issues left. Fixing them we could make migration process even more comfortable for users.

### How to reproduce

```sh
git clone https://github.com/sm-react/storybook-adk.git -b storybook_2.x
cd storybook-adk/
git checkout -b migration_test
npm i @storybook/cli -g
getstorybook
npm start

```

It´ll throw errors which should be solved manually. So the issues are:

- [ ] Doesn´t insert caret (^) in package.json. e.g.:

```json
"@storybook/addon-knobs": "3.1.6",
"@storybook/react": "3.1.7",
```

expected:

```json
"@storybook/addon-knobs": "^3.1.6",
"@storybook/react": "^3.1.7",
```

- [ ] Left `"@kadira/storybook": "^2.33.1"` in `peerDependencies`

expected:

change to the latest `@storybook/react` package

- [ ] Left `"@kadira/storybook-addons": "^1.6.1"` in `dependencies`

- [ ] Left `"@kadira/react-storybook-addon-info": "^3.3.0"`

- [ ] Left `"@kadira/storyshots": "^2.1.0"`

- [ ] Creates `import infoAddon from '@storybook/react-addon-info';` instead of `@storybook/addon-info`

- [ ] Doesn't procces `*.jsx` files

**Comment by janusch** [comment]
Hey,
there is a slight confusion about the addon-info package.
I just ran the latest getstorybook command and it rewrote the `addon-info` imports to: 
`import infoAddon from '@storybook/react-addon-info';`
whereas the package states that it has moved to `import infoAddon from '@storybook/addon-info';`
See: https://github.com/storybooks/react-storybook-addon-info 

Is this the correct package? `import infoAddon from '@storybook/addon-info';`

Thank you in advance for clarification!

**Comment by UsulPro** [comment]
@janusch the right name of this package is `@storybook/addon-info`
See: https://github.com/storybooks/storybook/tree/master/addons/info

**Comment by janusch** [comment]
thanks a lot for the reply!
