### ISSUE TITLE
How to configure both React Native and Webpack support?

### ISSUE THREAD

**Issue by MasahiroMorita** [storybooks/storybook#1382]
I'm developing an app that runs on React Native and Web, based on [this idea](http://jkaufman.io/react-web-native-codesharing/).

How can I setup storybook?
I run `getstorybook`, but it only configure for Webpack.

**Comment by ericwooley** [comment]
You can use https://github.com/ericwooley/react-nativeish for an example, which is loosely based off of https://github.com/grabcode/react-native-web-starter

As of 3.16 there is haul support, which you might have a significantly easier time dealing with.

**Comment by ndelangen** [comment]
Thanks for answering @ericwooley!

@MasahiroMorita I think this is answered? Let us know if there's more info you need!
