### ISSUE TITLE
Storybook (with addon-info) + Styled Components

### ISSUE THREAD

**Issue by michaltaberski** [storybooks/storybook#1384]
Hey,

I am using storybook (with info addon) at web React app. At the same app I am using styled components (https://www.styled-components.com/).

Here is simple case how I am doing this:

__LayoutHeader.js__
```javascript
import styled from 'styled-components';

const LayoutHeader = styled.div`
  color: #fff;
  background-color: #000;
`;

export default LayoutHeader;
```

__LayoutHeader.story.js__
```javascript
import { storiesOf } from '@storybook/react';
import React from 'react';

import LayoutHeader from './LayoutHeader';

storiesOf('LayoutHeader', module)
.addWithInfo('with text', () => (
  <LayoutHeader>Simple text</LayoutHeader>
));
```

The problem is the storybook info output looks like this:

![download](https://user-images.githubusercontent.com/202033/27685337-0a7bd84c-5cce-11e7-9c87-7a9f1b9f874f.png)

Can I somehow process the story so it renders story content as `<LayoutHeader />` instead of `<styled.div />`?

**Comment by michaltaberski** [comment]
I am sorry, my question was too hasty.

The solution is:

```javascript
import styled from 'styled-components';

const LayoutHeader = styled.div`
  color: #fff;
  background-color: #000;
`;

LayoutHeader.displayName = 'LayoutHeader';
export default LayoutHeader;
```

**Comment by UsulPro** [comment]
@michaltaberski Thank you for sharing your case!
Perhaps it'd be useful for someone!
I guess we can close it.
