### ISSUE TITLE
[Suggestion] Support chapters add-on

### ISSUE THREAD

**Issue by xareelee** [storybooks/storybook#1395]
I found a nice add-on, [storybook-chapters](https://github.com/sm-react/storybook-chapters), which allows you to group stories into a chapter. Unfortunately, it did not support react-native now. 

I think this add-on should be a built-in add-on in the storybook.

**Comment by ndelangen** [comment]
Good news! We're going to release `3.2.0` pretty soon, which will come with hierarchy support without introducing any new api's.

I'm not sure if storybook-chapters is something @UsulPro wants to keep maintaining after this. We'll have to ask him. Oleg is in the Storybook Team, so if there's something specific needed to support he can add it. If it's especially complicated (which it should not be) we should discuss it at a roadmap meeting.

Thanks for the suggestion! We understand the need for more organisation within stories in storybook. It's coming soon!
