### ISSUE TITLE
Can't use storyshots command in terminal

### ISSUE THREAD

**Issue by xareelee** [storybooks/storybook#1396]
Following https://storybook.js.org/testing/structural-testing/#using-storyshots to add the script and run it:

```
yarn run test-storybook
```

but it shows `command not found`:

```
yarn run v0.22.0
$ storyshots 
sh: storyshots: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```

**Comment by ndelangen** [comment]
Have you added the script to package.json?
Then, add the following NPM script into your package.json:

```json
{
  "scripts": {
    "test-storybook": "storyshots"
  }
}
```

**Comment by xareelee** [comment]
@ndelangen YES, definitely. 😃 

```
yarn run v0.22.0
$ storyshots 
sh: storyshots: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```

The second line indicates what the command the script executes. The command not found is `storyshots` not `test-storybook`.

Do I need to install `test-storybook` globally?

**Comment by ndelangen** [comment]
You should run `npm run storyshots` which in turn will run `storyshots` but within a npm 'context' causing the command exposed in `./node_modules/.bin/` to be available.

Is this what you're doing?

@tmeasday Are the docs correct here?

**Comment by tmeasday** [comment]
@ndelangen I am surprised to see this in the docs, as far as I am aware, storyshots does not ship with any `bin` scripts: https://github.com/storybooks/storybook/blob/master/addons/storyshots/package.json

I'm not sure what's going on there. I suppose we should get rid of that.

**Comment by xareelee** [comment]
@ndelangen 

The command `yarn run storyshots` equals to `npm run storyshots`. They just find and execute the `script` in the `package.json`. 

The issue is there is no such command `storyshots` in the `node_modules/.bin/` for cli.

**Comment by shilman** [comment]
@xareelee the documentation is wrong. i've fixed it here: https://github.com/storybooks/storybook/pull/1421

@ndelangen @tmeasday your review appreciated

**Comment by ndelangen** [comment]
LGTM, @shilman 

Does this fix your problem @xareelee ? If not feel free to reopen!
