### ISSUE TITLE
support dynamic imports (from Meteor apps)

### ISSUE THREAD

**Issue by zeroasterisk** [storybooks/storybook#1399]
I've just upgraded to Storybook 3 (w/ webpack 2)

I was hoping that since webpack supports dynamic imports, it would start working with Meteor which now supports dynamic imports...  but so far, not.

maybe there is some config I should adjust?

could we allow it to work somehow?

```
ERROR in ./imports/modules/Internationalization/components/IntlMessage.js
Module parse failed: /Users/alan/Code/myapp/portalV2/webapp/node_modules/@kadira/storybook/node_modules/babel-loader/lib/index.js?{"presets":["es2015","es2016","react","stage-1"],"plugins":["babel-root-slash-import",["/Users/alan/Code/myapp/portalV2/webapp/node_modules/babel-plugin-react-docgen/lib/index.js",{"DOC_GEN_COLLECTION_NAME":"STORYBOOK_REACT_CLASSES"}]],"babelrc":false}!/Users/alan/Code/myapp/portalV2/webapp/imports/modules/Internationalization/components/IntlMessage.js Unexpected token (27:11)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (27:11)
```

**Comment by UsulPro** [comment]
@zeroasterisk 
`Module parse failed: /Users/alan/Code/myapp/portalV2/webapp/node_modules/@kadira/storybook`
Are you sure you switched all package names to `@storybook`?

**Comment by zeroasterisk** [comment]
You're correct, I think it got partially migrated. I'll re-open if I needed to.
