### ISSUE TITLE
Remove relative position style

### ISSUE THREAD

**Issue by andrezzoid** [storybooks/storybook#1403]
Hey guys,
first of all, great work on Storybook!

I'm using `react-virtualized` to display data in a table and their `<AutoSizer>` component to figure out the table's width and height. But it doesn't seem to work properly because of a `position: relative` Storybook adds to the top div. Is there a way to remove it?

Thanks in advance.

![screenshot from 2017-07-03 11 37 24](https://user-images.githubusercontent.com/1095016/27789348-32e15cf8-5fe4-11e7-951d-fdc6ba1466bc.png)

**Comment by ndelangen** [comment]
Hey you self closed this? Did you get an answer elsewhere? Or did you find a solution to the problem? Care to share?

**Comment by andrezzoid** [comment]
@ndelangen still haven't figured this out but I've actually realized it was the `<AutoSizer>` component itself who added the styles. Thanks anyway :smile:
