### ISSUE TITLE
Cannot find module 'react-test-renderer' from 'test-bodies.js' when running tests

### ISSUE THREAD

**Issue by wallslide** [storybooks/storybook#1409]
![image](https://user-images.githubusercontent.com/917069/27860202-82585948-61b6-11e7-8f4e-fa471dcbe9b9.png)

I have `@storybook/react` `3.1.7` installed. My project is based on `creact-react-app`. I setup storyshots based on the instructions here:
https://github.com/storybooks/storybook/tree/master/addons/storyshots

First I added `@storybook/addon-storyshots` (version `3.1.7` was installed), then I created `Storyshots.test.js` as instructed, and ran `yarn run test`.  My storybook config folder is the default one. 

I'm running it in a docker container whose base is the `node:7.9` docker image.

**Comment by wallslide** [comment]
Fixed this by just explicitly adding the `react-test-renderer` package to my dev dependencies.

**Comment by oximer** [comment]
I'm having the same error, even after adding react-test-renderer

**Comment by techieshark** [comment]
Adding to the comment from @wallslide above -

According to [these docs]( https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-core#configure-jest-for-react), 

> StoryShots addon for React is dependent on react-test-renderer, but doesn't install it, so you need to install it separately.

```
npm install --save-dev react-test-renderer
```

(If using Angular or Vue you'll need another package; see the docs I link to.)

**Comment by Senja20** [comment]
the command `npm install --save-dev react-test-renderer` worked for me (thanks @techieshark ), but I had to use `--legacy-peer-deps` at the end. Also, I was working using typescript therefore I had to install types for react-test-renderer using the following command `npm i --save-dev @types/react-test-renderer`. 

Commands: 
- `npm install --save-dev react-test-renderer --legacy-peer-deps`
- `npm i --save-dev @types/react-test-renderer` (if ts)

**Comment by ghermaico135** [comment]
when I install this => npm install --save-dev react-test-renderer --legacy-peer-deps  the testing works.
Thank you!!
