### ISSUE TITLE
Is there a way to gulpify running storybook or build-storybook without the npm command?

### ISSUE THREAD

**Issue by dilizarov** [storybooks/storybook#1416]
I love this tool, but for business reasons we need it running via gulp commands and we can't use `gulp shell` or any of those that allow us to simply run terminal commands. Any recommended way to make this work?

**Comment by ndelangen** [comment]
Can you run a webserver like express? If so that's an opening.

**Comment by ndelangen** [comment]
another opening would be a child_process in node?

**Comment by dilizarov** [comment]
Essentially, we have our own build tools at the company. I'm perfectly fine running whatever storybook has running when we start up storybook in the `npm run storybook` way. The dilemma is that I'm not allowed to run `npm run` with our build tools. I noticed that `start-storybook` runs the `dist/server/index.js` file for instance. If there is a way in gulp to latch onto that and get things started up... would be fantastic.

**Comment by ndelangen** [comment]
Is something blocking your technically from doing that? \
Or are you prohibited from configuring something like that?

If you are prohibited from running `npm run` or `gulp shell` I'm assuming you're also prohibited from running a custom gulp pipe? or gulpFn?
https://www.npmjs.com/package/gulp-fn
https://stackoverflow.com/questions/27923523/how-can-i-write-a-simple-gulp-pipe-function

If you can run a pipe, you can run a node script.

I'm afraid there isn't much we can do here.. It sounds to me that what you want is perfectly possible to do, but you are just not allowed to do it..
