### ISSUE TITLE
Update React Native peerDependency

### ISSUE THREAD

**Issue by Rovack** [storybooks/storybook#1418]
It's been 2 months since React Native 0.44 was released, and they just now released stable version 0.46.
However, [storybook/react-native's peerDependencies](https://github.com/storybooks/storybook/blob/v3.2.0-alpha.5/app/react-native/package.json#L75) to this day remain `"react-native": "0.27.0 - 0.43.x"`.

I don't know if there's anything that would actually prevent this module from working with React Native 0.45 or 0.46, but at the very least I've personally used it with 0.44.0, and it seems to work fine (granted, I can't be sure I've covered _all_ cases).

Of course, this is only a peerDependency, and theoretically it shouldn't stop anyone from using Storybook with a newer version of React Native, but unfortunately that's not the case for any project still relying on shrinkwrap.
As it stands, shrinkwrap refuses to update as long as a peerDependency is unmet (see [here](https://github.com/npm/npm/issues/10836) and [here](https://github.com/npm/npm/issues/12909)), and [it doesn't look like that's about to change anytime soon](https://github.com/npm/npm/issues/13335).

So, 2 months later, it might at least make sense to try updating the peerDependency to something like "0.27.0 - 0.44.x".

**Comment by ericwooley** [comment]
It could probably be set too `^0.27.0`

Not sure why they did it the way they did.

**Comment by ajwhite** [comment]
Prereleases are treated specially by semver and an explicit range or `>=` is required to satisfy these types of matches.

See an example here:

<img width="317" alt="screen shot 2017-07-05 at 5 37 31 pm" src="https://user-images.githubusercontent.com/656630/27886122-b9c82baa-61a8-11e7-8163-d123ef51e8c9.png">

**Comment by Rovack** [comment]
Which makes sense, considering "minor" changes in pre-release often _are_ breaking (they certainly are in React Native).
However, in this specific case, it doesn't seem like anything pertinent to storybook broke between React Native 0.43 and 0.44, so it might be time to just update the range.

**Comment by smooJitter** [comment]
Nope, it does not work work .45.1

**Comment by rmevans9** [comment]
@smooJitter what are you not seeing work in 0.45.1? I have it working perfectly fine in 0.46.4

**Comment by ajwhite** [comment]
I think we can close this issue with #1424 having merged.

There are some dependency issues as of `3.2.0` outlined in https://github.com/storybooks/storybook/issues/1553, but that should be something we can provide a backward compatible solution for without needing to set a minimum dependency version.
