### ISSUE TITLE
sh: start-storybook: command not found

### ISSUE THREAD

**Issue by wahengchang** [storybooks/storybook#1426]
I was followed the instruction from the official website:
```
$ npm i -g @storybook/cli
$ cd my-react-app
$ getstorybook
```

sh: start-storybook: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! dashboard@0.0.0 storybook: `start-storybook -p 6006`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the dashboard@0.0.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peterchang/.npm/_logs/2017-07-07T09_10_13_275Z-debug.log

![image](https://user-images.githubusercontent.com/5538753/27951394-5d6442b4-6337-11e7-9226-4a529a22f308.png)

**Comment by wahengchang** [comment]
Fix
```
$ npm i --save-dev @storybook/react
$ npm run storybook
```

**Comment by ndelangen** [comment]
For some reason `@storybook/react` wasn't added to your project dependencies?

That's a bug in our CLI, I think there's already an issue for it:
https://github.com/storybooks/storybook/issues/1378

Actually our CLI needs an overhaul:
https://github.com/storybooks/storybook/issues/1108

**Comment by UsulPro** [comment]
looks like we discuss the same issue here: #311
