### ISSUE TITLE
Story is called twice instead of once.

### ISSUE THREAD

**Issue by michaltaberski** [storybooks/storybook#1428]
Hi,

I have following problem / question. Why this simple story is called twice? __(Check image below)__

![sample](https://user-images.githubusercontent.com/202033/27962106-22c4cc4c-6331-11e7-8b7a-f9da088884d2.png)

**Comment by michaltaberski** [comment]
Coud I ask any of you if you have also called the story twice each time or if it's just an issue of my setup?

**Comment by pascalduez** [comment]
Hi,

I also noticed this while debugging a component. Did not investigate further though.

**Comment by michaltaberski** [comment]
Thanks for info @pascalduez,
@ndelangen would you consider this issue as a bug, or there is a reason behind this?

**Comment by shilman** [comment]
I think this is a known bug, but thanks for the simple repro. Closing it as a duplicate to #707 . Feel free to re-open if you think it's a separate issue.
