### ISSUE TITLE
UI-issue with hierarchical view in release/3.2

### ISSUE THREAD

**Issue by nutgaard** [storybooks/storybook#1429]
## Current behaviour
With long names it prefers to push the document-icon and storyname onto a new line before breaking the storyname. If there's not enough room on the next line it breaks the storyname as expected. ![image](https://user-images.githubusercontent.com/1413417/27961883-78a26c6a-6330-11e7-99ee-c199bc10c4e0.png)

## Wanted/Expected behaviour
I would expect the opposite behaviour, e.g. start by breaking text and if its no longer possible pop it onto a new line (or just overflow). 

**Storybook-version**: 3.2.0-alpha.7

**Comment by igor-dv** [comment]
I'll look into it. Thanks.

**Comment by igor-dv** [comment]
@nutgaard 
BTW, do you think breaking the words is a good solution ? 
Inspiring from the editor we all use and love (I think all of them do this):

![image](https://user-images.githubusercontent.com/7867954/27968342-4fb3319e-634f-11e7-8ce3-ee7a234914d2.png)

WDYT ?

**Comment by igor-dv** [comment]
Here is the fix as you suggested.
![storybook_hierarchy_react-treebeard-width](https://user-images.githubusercontent.com/7867954/27970426-714dfbc4-6357-11e7-99e5-c3503d972180.gif)

But IMO the better way is to support horizontal scrolling starting from some minimum width.

**Comment by nutgaard** [comment]
I think both approaches are viable. 
But its probably easier to get the "overflow: hidden"-solution to work consistently, and paired with a horizontal scrollbar it solves the issue imho. 

Anyway huge 👍 for the quick response. :1st_place_medal:

**Comment by igor-dv** [comment]
Will be fixed with #1427
