### ISSUE TITLE
Fix bootstrap command for alpha releases

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1433]
## why

`npm run bootstrap` runs `lerna` to set up the proper package dependencies for local development. After running it, for example, `examples/cra-kitchen-sink` should use the freshly built `@storybook/*` packages on your local machine.

However, when we do alpha releases, our version naming convention differs from `semver` and `lerna` uses packages from the `npm` package server instead. So we need to constantly update the version of packages used in `cra-kitchen-sink`, partially defeating the value of `lerna`.

For example, here is the current `package.json` in the `release/3.2` branch:

```
  "devDependencies": {
    "@storybook/addon-actions": "^3.0.0",
    "@storybook/addon-centered": "^3.0.0",
    "@storybook/addon-events": "^3.0.0",
    "@storybook/addon-knobs": "3.2.0-alpha.7",
    "@storybook/addon-info": "^3.0.0",
    "@storybook/addon-links": "3.2.0-alpha.5",
    "@storybook/addon-notes": "3.2.0-alpha.5",
    "@storybook/addon-options": "3.2.0-alpha.5",
    "@storybook/addon-storyshots": "3.2.0-alpha",
    "@storybook/addons": "^3.0.0",
    "@storybook/react": "3.2.0-alpha.7",
    "react-scripts": "1.0.1"
  },
```

## what

Long-term:
- [ ] upgrade Lerna as soon as @ndelangen 's fix gets released (please upvote!!!!): https://github.com/lerna/lerna/pull/908

Short-term:
- [ ] be diligent about updating the `package.json` files in the `release/3.2` branch

**Comment by jhurley23** [comment]
Lerna have just announced [Release 2.0](https://github.com/lerna/lerna/blob/master/CHANGELOG.md) which may address this issue.
They've improved --canary functionality: https://github.com/lerna/lerna/pull/904

**Comment by pksunkara** [comment]
@shilman Are you still encountering this on release/3.4 branch?

**Comment by shilman** [comment]
Nope, it looks like it's been fixed across the board. Closing this. Yay!
