### ISSUE TITLE
Open translations on docs

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#1444]
I'm thinking about using the same docs-translations strategy https://github.com/yarnpkg/website uses.

**Comment by adoyle-h** [comment]
Great! I'm willing to translate the website into Chinese. I will do it when the i18n framework get ready.

**Comment by ndelangen** [comment]
@adoyle-h I'll keep you informed about the process, I think especially for Storybook for Vue, a chinese translation will be welcomed by the users!
