### ISSUE TITLE
ModuleNotFoundError in Imported Components

### ISSUE THREAD

**Issue by bbrinx** [storybooks/storybook#1451]
While importing the component works, it returns a ModuleNotFound error in the imported component. Outside of Storybook the component works perfectly. 

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'echarts-for-react/lib/core'
```

I don't know if this error is related:

```
Parsed request is a module using description file: [path]
Field 'browser' doesn't contain a valid alias configuration
```

**Comment by jlyman** [comment]
@bbrinx did you end up finding a resolution to this? Even if it was just a configuration error, I'd appreciate any pointers as I'm experiencing the same issue.

**Comment by eminaz** [comment]
@bbrinx Is this issue resolved? I also have this error
