### ISSUE TITLE
i m having this prolem while installing http-server-g...

### ISSUE THREAD

**Issue by aadirngr** [storybooks/storybook#1458]
C:\Users\user>npm install http-server-g
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "http-server-g"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/http-server-g
npm ERR! 404
npm ERR! 404  'http-server-g' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log

C:\Users\user>

**Comment by danielduan** [comment]
it should be `npm install http-server -g` with the space before `-g`. Not entirely storybook related, but hope that helps.
