### ISSUE TITLE
Running storybooks on now.sh fails

### ISSUE THREAD

**Issue by hlandao** [storybooks/storybook#1459]
Running storybooks on now.sh fails because Now does not allow to modify the filesystem in runtime
```
Module build failed: Error: EACCES: permission denied, mkdir '/home/nowuser/src/node_modules/.cache/react-storybook'
```

Is there a way to change Webpack in such way that filesystem modifications aren't required ?

* in our scenario we deploy storybooks on every pull-request, building static version takes too long and makes it useless.

Thanks!

**Comment by joefraley** [comment]
This can't be quite right because Zeit allows you to run build scripts that write to disk. Something else must be going on here...

**Comment by tuckerconnelly** [comment]
I got around this by doing:

`npm i serve`

```json
{
  "scripts": {
    "build": "rm -rf .out && build-storybook -c .storybook -o .out",
    "start": "cd .out && serve -p 9001"
  }
}
```

**Comment by danielduan** [comment]
If the workaround isn't sufficient, please reopen this. PRs are always welcomed!

**Comment by lek-tin** [comment]
Solved the problem by adding `sudo` to the `story` command

`"storybook": "sudo start-storybook -p 6006"`
