### ISSUE TITLE
v3.1.6 bottom panel won't resize on node6

### ISSUE THREAD

**Issue by panosvoudouris** [storybooks/storybook#1465]
With v3.1.6, when trying to resize the bottom panel (where addons appear) on node 6 the panel will jump between either a nearly collapsed height or almost full screen. It is not possible to resize it in-between. Works fine with node 8.

To replicate you'll need to clear node_modules and `npm i` with node 6, then try to run it.

**Comment by shilman** [comment]
@panosvoudouris FYI this is reproducible in the `examples/cra-kitchen-sink` example. I think somebody upgraded `react-split-pane` recently and I bet it's related to that.

**Comment by UsulPro** [comment]
Thanks for reporting it! I faced the same issue with node 7. Really ugly behavior!

**Comment by arahansen** [comment]
looks like I'm seeing this issue on node 8.

@panosvoudouris do you have steps on how you resolved this issue for node 8.x?

**Comment by panosvoudouris** [comment]
@arahansen I have not noticed this with node 8, worked fine for me there. However I've been deleting node_modules and rerunning `npm install` when switching node versions. Maybe that's the problem?

**Comment by nickdandakis** [comment]
This _was_ broken for me with Node 8. Seems fine after clearing `node_modules/`, deleting `package-lock.json` and re-running `npm install`.

Node v8.1.2
react-split-pane v0.1.65
@storybook/react v3.1.9
