### ISSUE TITLE
@storybook/react/addons is not transpiled and fails on uglifyjs

### ISSUE THREAD

**Issue by vvo** [storybooks/storybook#1480]
```sh
> cat addons.js 
import deprecate from 'util-deprecate';
import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';

deprecate(
  () => {},
  '@storybook/react/addons is deprecated. See https://storybook.js.org/addons/using-addons/'
)();
```

```
> tree -L 2
.
├── LICENSE
├── README.md
├── addons.js
├── demo.js
├── dist
│   ├── client
│   ├── demo
│   └── server
└── package.json

4 directories, 5 files
```

I understand this has been deprecated but I think there should be a dist/addons or the addons.js should be transpiled. This is causing me failures.

**Comment by shilman** [comment]
@vvo this is a bug. `prepublish.js` goes through and transpiles everything in `src` but `addons.js` is at the top level, so it should be written in old-style JS. Please feel free to submit a PR, or I can take care of it later.

**Comment by danielduan** [comment]
I believe this has been fixed?
