### ISSUE TITLE
HMR(Hot module replacement) not working when stories are not in src folder

### ISSUE THREAD

**Issue by rvenugopal** [storybooks/storybook#1483]
Hi

My project structure looks like the following.  I am able to get storybook working however, Webpack dev server HMR only works when I make changes to the 'src' folder.  When I make changes to the stories themselves, the changes are not picked up.  

```
├── .storybook        # Storybook configuration files
├── src                     # Source files
├── test                    # Automated tests 
├── stories               # Storybook stories in this folder

```
My config.js looks like the following
```
import { configure } from '@storybook/react';

const req = require.context('../stories', true, /story\.js$/)

function loadStories() {
  req.keys().forEach(req)
}

configure(loadStories, module);
```

Thanks
-Rv

**Comment by apvilkko** [comment]
I have the same issue. Hot reload is detected on index.js and other "root" components of the app but not on UI components nor their stories. UI components and stories are in the same folder, e.g. Button/index.js and Button/stories.js.

This makes storybook unusable for me currently.

**Comment by danielduan** [comment]
You guys are more than welcome to submit a PR to fix this.
