### ISSUE TITLE
Old version of enhanced-resolve and memory-fs

### ISSUE THREAD

**Issue by Travellerme** [storybooks/storybook#1490]
If I want to use alias for webpack config - I'm not able to do it, because I get such error from "memory-fs" library: Cannot read property 'replace' of undefined
This issue was solved here https://github.com/webpack/memory-fs/issues/12
But inside your library I see that you still use old versions:
`dependencies:
...
enhanced-resolve "~0.9.0"
...
`
0.9.0 Version of "enhanced-resolve" is using old version of 'memory-fs' too

`dependencies:
...
memory-fs "^0.2.0"
...
`

Is this possible to update dependencies ?

**Comment by SpaceK33z** [comment]
We now use the latest versions of webpack,

```
    "webpack": "^2.5.1 || ^3.0.0",
    "webpack-dev-middleware": "^1.10.2",
    "webpack-hot-middleware": "^2.18.0"
```

So this shouldn't be an issue anymore. Feel free to re-open if it still is.
