### ISSUE TITLE
Slack group?

### ISSUE THREAD

**Issue by mikewheaton** [storybooks/storybook#1491]
The footer of the [Storybook website](https://storybook.js.org/) contains a link to https://storybooks-slackin.herokuapp.com/, but it looks like there's nothing at that address. Has the Slack group been moved, or is it no longer available?

I'm brand new to Storybook but would be happy to submit a PR updating the [Footer component](https://github.com/storybooks/storybook/blob/master/docs/components/Footer/index.js) either way. 😄

**Comment by ndelangen** [comment]
It appears the heroku container was stopped by heroku..
Ow well, https://now-examples-slackin-nqnzoygycp.now.sh/

**Comment by mikewheaton** [comment]
Is the URL you posted a good replacement? I can open a PR to update that URL.

**Comment by ndelangen** [comment]
Yes it's a fine replacement I think, 
if you find any places where we still link to the herokuapp a PR to change them would be great!

**Comment by ndelangen** [comment]
I'll close this issue, I've edited the readme already, thanks for reporting!
