### ISSUE TITLE
Bug preview-head.html

### ISSUE THREAD

**Issue by kivohin** [storybooks/storybook#1496]
Hi there :)

I am trying to inject some custom fonts with Typekit into the iframe, so I am following these instructions: https://storybook.js.org/configurations/add-custom-head-tags/

So I created a `preview-head.html` file, but it never gets injected when running the local server. I was before on version `3.1.7`, I updated to `3.1.9` to see if any luck but didn't work. Also I tried to use the deprecated `head.html` but no luck.

Is there some known issue at the moment with `preview-head.html`? Or do I need to inject it myself with Webpack?

Thanks!

**Comment by shilman** [comment]
@kivohin am not aware of any known issues with this. Can you provide a repro? I'm going to update the `examples/cra-kitchen-sink` to include a working example.

**Comment by kivohin** [comment]
Thanks for your answer @shilman. I realized the scripts are actually being injected, so everything is good on your side 👍🏼 Keep up the great work 🌈
