### ISSUE TITLE
3.2-alpha: HMR broken

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1506]
## why

Expanding on @UsulPro 's [comment](https://github.com/storybooks/storybook/pull/1383#issuecomment-316526470). Do the following in branch `release/3.2` vs. `master` (3.1.x):
```
yarn bootstrap
cd examples/cra-kitchen-sink
yarn storybook
```
Then select one of the Button stories (not the Welcome story).
In a separate window, edit the you're looking at (e.g. change the button text).

Expected behavior (3.1.x):
- The button text will update.

Actual behavior (3.2-alpha):
- The page will reload and the Welcome story will show.

Note: when switching between branches, you may need to clean out your node_modules. You can do this by running:
```
git clean -fdx
```
This deletes all files that are not part of the git repo, so be careful if you have files lying around!

## what

- [ ] diagnose the problem
- [ ] fix it! 😁

**Comment by igor-dv** [comment]
Until now it was optional.. 
Don't we want this kind of checking ?

![image](https://user-images.githubusercontent.com/7867954/28490479-a77b103c-6ee3-11e7-8bec-7dc4603bc54c.png)

**Comment by ndelangen** [comment]
It should remain optional

**Comment by igor-dv** [comment]
Not providing the module breaks the HMR. But it should remain optional.. I am confused :confused:

**Comment by shilman** [comment]
@ndelangen @igor-dv  why optional? And if we want to keep it optional, can we at least print out a warning? Seems like a lot of people are getting bit by this, including us in our sample code!

**Comment by ndelangen** [comment]
Right, so a single warning into the terminal and console sound fair to me, yes!

> Not providing the module breaks the HMR. But it should remain optional.. I am confused :confused: 

Providing the module enables HMR. If you don't provide the module HMR is not enabled, for whatever reason the users is choosing to.
Now if a lot of users are missing this, a reminder-warning is definitely in order.

**Comment by ndelangen** [comment]
Is this something you want to do @igor-dv ?

**Comment by igor-dv** [comment]
Yeah, I'll do it by the end of the week

**Comment by ndelangen** [comment]
Cool, will close this then, will be released soon!
