### ISSUE TITLE
disable logging to stdout

### ISSUE THREAD

**Issue by jonathanong** [storybooks/storybook#1513]
i find this console log very annoying https://github.com/storybooks/storybook/blob/9b80a992cfcbece11227f815893173bf7b7a8ee7/app/react/src/server/babel_config.js#L24

can we add a way to disable it? i personally use https://www.npmjs.com/package/debug to gate logs at will. i know i'm using a custom babelrc because i added it manually!

**Comment by jonathanong** [comment]
note that i only care about this when i use snapshot testing. jest is no fun when tests print to stdout

**Comment by ndelangen** [comment]
I will slowly move over the codebase to use `npmlog`;

Should be easy to mock that with jest and filter out all the logging!

Any help with this would be appreciated!

**Comment by dangreenisrael** [comment]
Is this still something that is wanted? @ndelangen

**Comment by ndelangen** [comment]
Yes, moving all our logging to `npmlog` sounds like a good idea to me. it will allow setting a custom logging level for users, so they can get detail for debugging or production like levels with only catastrophic errors.

Would love to hear @Hypnosphi thoughts on this. 👍

**Comment by Hypnosphi** [comment]
I love the idea

**Comment by dangreenisrael** [comment]
I may have some time later this week that I could use to start digging into this. `3.3` or `master`?

**Comment by dangreenisrael** [comment]
@Hypnosphi

**Comment by ndelangen** [comment]
base off of `3.3` but I don't expect it to get merged before release, because that's close now.
