### ISSUE TITLE
Can't find utility function on Absolut path

### ISSUE THREAD

**Issue by wellyal** [storybooks/storybook#1518]
I have added a new resolve path on my webpack config

```modules: ['node_modules', 'src', ...```

On my Input component I reference a utility function for its absolut path like this.

```
import { capitalizeFirstLetter } from 'utils/capitalizeFirstLetter' 
```

The component itself works great but when I run storybook I get this error message:

```
in ./src/components/atoms/Input/Input.js
Module not found: Error: Can't resolve 'utils/capitalizeFirstLetter'
```

**Comment by ndelangen** [comment]
I presume you have a custom webpack config for storybook and have added it there as well?

Perhaps you need to provide full paths, that sounds like a good idea anyway. You can use the `path` module to get the full path:

```js
const path = require('path');

const modulePaths = [path.resolve('./node_modules'), path.resolve('./src')];
```

**Comment by ndelangen** [comment]
PS. I personally prefer to use a babel plugin over a webpack resolve:
https://github.com/jagrem/babel-resolve-relative-module

**Comment by wellyal** [comment]
@ndelangen thanks for you help. Still newbe with storybook. I didn't realize I had to create a custom webpack config for storybook. But (of course) makes all sense. Thanks again.

**Comment by ndelangen** [comment]
You're very welcome! Our support channel on slack is also a great way to get community support ⭐️
