### ISSUE TITLE
Tests are failing locally

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#1521]
With this setup:
```
$ git clone https://github.com/storybooks/storybook.git
$ cd storybook
$ yarn
$ yarn bootstrap
```

if you run `yarn test`, it just fails to start:
```
$ yarn test
yarn test v0.27.5
$ jest --projects ./ ./examples/react-native-vanilla

error Command failed with exit code 1.
```

`yarn jest` works, but one test is failing: 
```
Summary of all failing tests
 FAIL  examples/cra-kitchen-sink/src/storyshots.test.js
  ● Storyshots › Button › with knobs

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -10,11 +10,11 @@
       <p>
         My name is Storyteller, I'm 70 years old, and my favorite fruit is apple.
       </p>
       <p>
         My birthday is:
    -    2017-1-20
    +    1/20/2017
       </p>
       <p>
         My wallet contains: $
         12.50
       </p>
```

I believe the second issue is connected with usage of [toLocaleDateString](https://github.com/storybooks/storybook/blob/master/examples/cra-kitchen-sink/src/stories/index.js#L81)

**Comment by shilman** [comment]
Thanks @Hypnosphi !

For first one, you need to run `yarn bootstrap:react-native-vanilla` beforehand.

Second one is a nice catch. It sounds like there is a problem with our test setup where it is locale-dependent... Wanna take a crack at that?

**Comment by dcu-sharepoint** [comment]
@shilman My name is Carlos and would like to contribute as I think this app has great promise. the thing is I don't know how to start and I'm a newbie with these technologies including GITHUB/GIT but got to start somewhere.
