### ISSUE TITLE
[3.2.0-alpha.10] react-native project isn't working with the latest version of storybook

### ISSUE THREAD

**Issue by rmevans9** [storybooks/storybook#1532]
Hello!

To start I want to just say I love storybook and it is great for my workflow in developing components.

I was especially excited to see the nesting of stories PR land in 3.2.0. I gave it a shot on my project to see how it looked and to my dismay when I open the browser to the storybook page it actually locks up and ends up crashing the browser tab. I haven't tried debugging past looking at the console yet. Here is what I found:

![screen shot 2017-07-27 at 8 50 31 am](https://user-images.githubusercontent.com/14151327/28671009-2988526a-72a9-11e7-9554-df7f5404f710.png)

This error gets repeated......... a lot.

![screen shot 2017-07-27 at 8 50 46 am](https://user-images.githubusercontent.com/14151327/28671019-31f078a6-72a9-11e7-89fe-c3fb9db6daed.png)

I thought it might be my use of storybook so I created a brand new React Native project and added storybook. pre-3.2.0-alphas it worked fine as soon as I upgraded it the same errors that I was getting on my actual project started occurring.

I know I am not providing a ton of information around what might be going on so I am hoping someone can take my example repo (https://github.com/rmevans9/storybook-rn-sadness) and see if they can pinpoint the issue. That repo is a brand new project with `@storybook/react-native` at 3.2.0-alpha.10 installed.

Any ideas of how to resolve would be greatly appreciated.

**Comment by shilman** [comment]
@rmevans9 Thank you for the bug report and the repo. I can reproduce the problem on my machine and am looking into it now.

**Comment by shilman** [comment]
We've identified the problem in the hierarchy UI's interaction with react16 and are fixing it now. (Your project works fine with the stable version of Storybook, FYI)

**Comment by rmevans9** [comment]
@shilman yes, I am working just fine in the stable version in both my real project and this one. I just didn't want to see the bug causing this problem to hit stable so I just wanted to give the alpha a shot.

Thanks for tracking dow the issue!

**Comment by shilman** [comment]
Yeah we truly appreciate the bug report. We are about to release 3.2.0 and it's great to be able to fix this before that goes out. 🙇

**Comment by shilman** [comment]
@rmevans9 `@storybook/react-native@3.2.0-alpha.11` is live and fixes the problem 💥

**Comment by rmevans9** [comment]
It works in my real project! 🍾  Thanks for the quick turn around on the fix!

**Comment by igor-dv** [comment]
:+1:
