### ISSUE TITLE
Firing an action with the info addon is slower than molasses

### ISSUE THREAD

**Issue by levithomason** [storybooks/storybook#1535]
### What is this?

A button with `onClick={action('onClick')}`.  Two identical stories except the first is added with `.add()` the second with `.addWithInfo()`.

### What I'm doing
😄 Clicking the button several times in the `add()` story.  The actions are logged immediately.

😞 Clicking the button once in the `addWithInfo()` story.  The UI freezes for several seconds before the action is logged.

### Demo

![http://g.recordit.co/QNxUJm0trG.gif](http://g.recordit.co/QNxUJm0trG.gif)

>In all fairness, it is [probably slightly faster than molasses](https://youtu.be/7KEwIePdinQ?t=21s), depending.

**Comment by shilman** [comment]
In v4 we will deprecate the `addWithInfo` API and rename it to `addWithMolasses`. 😭 

In all seriousness, we're making a bunch of changes to the info addon (e.g. #1147) so let's see how things shake out with that. cc @UsulPro
