### ISSUE TITLE
"Stateless function components cannot be given refs" warnings with React@next

### ISSUE THREAD

**Issue by ConneXNL** [storybooks/storybook#1539]
I am using the react@next branch with the initial fiber support.

Upon loading the storybook I get 2 warnings:

```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Container(LeftPanel)`.
    in LeftPanel (created by Container(LeftPanel))
    in Container(LeftPanel) (created by Layout)

and 

Check the render method of `Container(ShortcutsHelp)`.
    in ShortcutsHelp (created by Container(ShortcutsHelp))
    in Container(ShortcutsHelp)
```

Things seem to work normally though.

**Comment by ndelangen** [comment]
Anyone who wants to pick this one? 

I feel it should be an easy one to get started contributing to storybook, so send me a message if you want to give this a go and want my help!

**Comment by oriSomething** [comment]
@ndelangen I think I'll try to pick this

**Comment by Hypnosphi** [comment]
Ok, so #1551 fixes the symptoms, but the origin of the problem is `react-komposer` adding refs to children [just for tests](https://github.com/arunoda/react-komposer/blob/master/src/tests/compose.js#L79). I will send them a PR, but unfortunately the repo looks [abandoned](https://github.com/arunoda/react-komposer/issues/127#issuecomment-286835563), so we should probably switch to [recompose](https://github.com/acdlite/recompose).

**Comment by ndelangen** [comment]
@Hypnosphi That sounds like the best course of action indeed! Will switching to recompose be easy you think?

**Comment by Hypnosphi** [comment]
Well, I haven't really digged into it, we should check that it provides the needed features. It may turn out that transferring react-komposer will be a better option (if that's OK for @arunoda)

**Comment by UsulPro** [comment]
if somebody is going to connect with @arunoda please ask about https://github.com/arunoda/podda as  well!

**Comment by Hypnosphi** [comment]
@ndelangen we can achieve the current behaviour using recompose's  [`mapPropsStream`](https://github.com/acdlite/recompose/blob/master/docs/API.md#mappropsstream) and some lite-weight observable stream library (I'd suggest [xstream](https://github.com/staltz/xstream)).

**Comment by danielduan** [comment]
React 16 should be fully supported now. Closing.

**Comment by Hypnosphi** [comment]
This issue is not about React 16 support
https://github.com/storybooks/storybook/issues/1539#issuecomment-321414193

**Comment by geocine** [comment]
This issue still persists. I am using the following versions

```
{
    "@storybook/addon-actions": "^4.0.0-alpha.8",
    "@storybook/addon-links": "^4.0.0-alpha.8",
    "@storybook/addon-notes": "^4.0.0-alpha.8",
    "@storybook/addon-options": "^3.4.6",
    "@storybook/addons": "^4.0.0-alpha.8",
    "@storybook/angular": "^4.0.0-alpha.8",
    "babel-core": "^6.26.3",
    "react": "^16.4.0",
    "react-dom": "^16.4.0"
}
```

I am getting the following errors:

```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Container(Layout)`.
    in Layout (created by Container(Layout))
    in Container(Layout)
    in div

Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Container(AddonPanel)`.
    in AddonPanel (created by Container(AddonPanel))
    in Container(AddonPanel) (created by addonPanel)
    in addonPanel (created by Layout)
    in div (created by Styled(div))
    in Styled(div) (created by Layout)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by Layout)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by Layout)
    in Layout (created by Layout)
    in div (created by Styled(div))
    in Styled(div) (created by Layout)
    in ThemeProvider (created by Layout)
    in Layout (created by Container(Layout))
    in Container(Layout)
    in div
```

**Comment by tysonmatanich** [comment]
@Hypnosphi Hoping it can get merged soon.
