### ISSUE TITLE
Storybook with TypeScript based application

### ISSUE THREAD

**Issue by sergeyzwezdin** [storybooks/storybook#1541]
I've created [typescript based](https://github.com/wmonk/create-react-app-typescript) React app (with `create-react-app`) and added storybook there (by using `getstroybook` CLI command).

I've [added](https://github.com/sergeyzwezdin/storybook-with-ts/blob/master/.storybook/webpack.config.js) `webpack.config.js` to define `ts-loader` to transpile my TypeScript code.

I've placed whole code here - https://github.com/sergeyzwezdin/storybook-with-ts

The problem is storybook building takes around 15 seconds with just single story. If I make the same for my real project it takes more than 20 seconds which is quite slow.

I guess this is because of both `babel-loader` and `ts-loader` build `node_modules` folder (I can see this process at console). Any way to avoid building `node_modules`.

P.S. I'm migrating application from `@kadira/storybook` to `@storybook/react`. With `@kadira/storybook` it worked much faster for me with the same codebase.

**Comment by KaySackey** [comment]
You don't have to double up on babel-loader and ts-loader. ts-loader can load javascript for you, and you're transpiling the Typescript down to ES5/commonjs modules anyways. 

I'm not seeing anything that should make this so slow, exclude: /node_modules/ should already be excluding your node_modules.

**Comment by RWOverdijk** [comment]
Why did you remove the repository?
