### ISSUE TITLE
lib/ui/example doesn't work with node < 8

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#1542]
That's because of trailing comma in function call: https://github.com/storybooks/storybook/blob/master/lib/ui/example/server.js#L12

We should either remove the comma until Node 8 becomes LTS in October, or add a note to readme

**Comment by ndelangen** [comment]
Trailing comma in function call is invalid, removal would be fine!

**Comment by ndelangen** [comment]
eslint should actually remove such things.. I guess somehow this got ignored because of a `.eslintignore` or some rules in the file itself?

**Comment by Hypnosphi** [comment]
Well it's valid since ES2017, so I think it's totally ok to used in babel-transpiled files

**Comment by Hypnosphi** [comment]
But yes, `**/example/**` is `.eslintignore`d for some reason

**Comment by ndelangen** [comment]
I can tell you the reason, those examples are marked for deletion.

'Lib/ui' may be excepted from this. I'm not quite sure yet.

The idea is to see the entire repo as 1 development environment, not every individual package have its own. This is still an ongoing process of improvement. We cut out what bothers us and have alternatives for. Parts that haven't been touched or discussed or reached consensus about remain.

Please share your thought and discuss.

I personally like using the example/car-kitchen-sink for development.

**Comment by Hypnosphi** [comment]
Closed with #1543
