### ISSUE TITLE
Adding/removing stories do not automatically update in React Native (3.2)

### ISSUE THREAD

**Issue by ajwhite** [storybooks/storybook#1547]
Story lists (on device, and on web) no longer automatically add or remove stories as they are added or removed in the codebase. It currently requires a full refresh of the web and device to observe these changes.

**Comment by shilman** [comment]
@ajwhite I am seeing this bug in `examples/react-native-vanilla` on `master` and also on @rmevans9 's branch. However, I am also running a CRNA side project with the latest `alpha` (which should be equivalent to `master`) and it's updating fine.

**Comment by rmevans9** [comment]
After speaking with @shilman about this and taking a quick look at it here are my findings on this issue which could make it a non-issue:

React Native has Hot Module Reloading built into it. If you have it on the components of the app reload when a story is added and the menus (both on web and OnDeviceUI) update accordingly. If you have it off the app doesn't reload the stories and thus the story doesn't propagate to the menus. 

CRNA uses Expo under the covers which I am fairly certain has a HMR type setup that is baked in during development which means when you update a story the RN app reloads the needed components and the stories appear in the menus. 

I believe this is a non-issue as any sane RN dev that is working on adding stories should have HMR on.

**Comment by shilman** [comment]
Agree with @rmevans9 and closing. And here's a screenshot for anybody who runs across this issue:

<img width="372" alt="glass" src="https://user-images.githubusercontent.com/488689/28757696-8ee87356-753d-11e7-8ef4-caf16c293a78.png">

**Comment by rmevans9** [comment]
@shilman Either that or the "Enable Hot Reloading" below will do. Personally I use "Enable Hot Reloading" because it updates the component in place without reloading the entire bundle. "Enable Live Reload" will reload the entire app bundle.
