### ISSUE TITLE
Changelogs

### ISSUE THREAD

**Issue by eddiemonge** [storybooks/storybook#1557]
Since this is now a mono-repo, changelogs are even more criticial to see whats been done in an add-on.

addons-actions is now at version 3.2.0 but the changelog only goes  up to 1.x. Please either update the changelog file or remove it. Or better yet, **split the add-ons back into separate repos but still under the storybook org**

**Comment by ndelangen** [comment]
Hey @eddiemonge,
There's a changelog in a subproject? Well that'd be legacy content. I guess we could remove it, it's probably no use to anyone anymore..

The monorepo is helping us tremendously in our development, it's not changing. Thanks for the suggestion though, I understand it's not quite the industry standard.

**Comment by danielduan** [comment]
I'll get rid of the individual changelogs.
