### ISSUE TITLE
Storyshots. Ability to skip some stories

### ISSUE THREAD

**Issue by tirli** [storybooks/storybook#1578]
Is it possible to skip several stories for storyshots?
I've read issues according to this in the old repo, but it doesn't help.

Tha main reason I need it is [not working findDomNode in react-test-renderer](https://github.com/facebook/react/issues/7371). I need to use it in one of my components, but its story fails all tests for me :(

**Comment by igor-dv** [comment]
There is a `storyKindRegex` option that may help you: 
https://github.com/storybooks/storybook/tree/master/addons/storyshots#storykindregex

**Comment by tirli** [comment]
@igor-dv 
Oh, I missed it. Thanks

**Comment by jaywick** [comment]
> There is a `storyKindRegex` option that may help you:
> https://github.com/storybooks/storybook/tree/master/addons/storyshots#storykindregex

FYI the URL is now https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-core#storykindregex
