### ISSUE TITLE
[addon/knobs] JSX Support

### ISSUE THREAD

**Issue by thomaskuntzz** [storybooks/storybook#1580]
It would be great if the knobs add-on had the ability to input simple JSX (`img` tags, etc.).

For instance: I have a coponent. One of its attributes is an object containing JSX, in this case an `img` tag. I'd like to be able to modify the `img` tag from the Knobs panel in Storybook. However, it seems that in order to do so, I'd need to have a function similar to for instance [object](https://github.com/storybooks/storybook/tree/master/addons/knobs#object) but that allows to pass JSX.

**Comment by ndelangen** [comment]
Can you elaborate?

**Comment by thomaskuntzz** [comment]
I updated the issue description 😉

**Comment by Hypnosphi** [comment]
The simplest use case is a component that expects children

**Comment by Hypnosphi** [comment]
I think I'll add babel parsing to object knob
