### ISSUE TITLE
Storybook crashes when using Addon Knobs (evaluating this.props.channel.on)

### ISSUE THREAD

**Issue by DaniyarJakupov** [storybooks/storybook#1586]
**Version**
App bootstrapped with create-react-native-app. 
```
"react-native": "0.46.1",
"@storybook/addon-knobs": "^3.2.0",
"@storybook/react-native": "3.2.3",
```
**Reproduction**
When I add withKnobs decorator to the story, storybook crashes with this error:

<img width="374" alt="screen shot 2017-08-03 at 17 04 20" src="https://user-images.githubusercontent.com/17025967/28928826-954d65c4-786e-11e7-8cb5-ef10576498e4.png">

<img width="864" alt="screen shot 2017-08-03 at 17 09 36" src="https://user-images.githubusercontent.com/17025967/28928834-9a386264-786e-11e7-82dd-e54e459d54d0.png">

As soon as I remove `.addDecorator(withKnobs)` everything is working fine
Index.js
```
import React from 'react';
import { Text } from 'react-native';

import { storiesOf } from '@storybook/react-native';
import { action } from '@storybook/addon-actions';
import { linkTo } from '@storybook/addon-links';
import { withKnobs, text, boolean, number, select } from '@storybook/addon-knobs';

import Button from './Button';
import CenterView from './CenterView';
import Welcome from './Welcome';
import Label from './Label';

storiesOf('Welcome', module).add('to Storybook', () => <Welcome showApp={linkTo('Button')} />);

storiesOf('Label', module)
  .addDecorator(getStory =>
    <CenterView>
      {getStory()}
    </CenterView>
  )
  .addDecorator(withKnobs)
  .add('vertical', () =>
    <Label
      onPress={action('clicked-text')}
      title={text('Title', 'Place')}
      population={number('Population', 8)}
      secondary={boolean('Secondary', false)}
    />
  );

```

**Comment by rkichenama** [comment]
I am not sure why, but when I `npm i -D react-inspector` everything got fixed.

**Comment by Gongreg** [comment]
@DaniyarJakupov, I found the issue, I am working on pr to fix it. I should be able to fix it today.

**Comment by kwelch** [comment]
Same for me, but installing react-inspector has not fixed the issue.

**Comment by DaniyarJakupov** [comment]
Just downgrade to "3.1.9" version. That should do the trick. At least it worked for me

**Comment by Gongreg** [comment]
@DaniyarJakupov, @kwelch the pr is still not merged. So yes, for now switch to older version. I'll notify you when pr is merged.

**Comment by aloifolia** [comment]
I ran into a similar issue with Storybook and React Native:
![image](https://user-images.githubusercontent.com/1295054/31220603-32efa70a-a9c1-11e7-8f90-46c5d1cdb122.png)

```javascript
const stories = storiesOf('AppointmentEntry', module)
  .add('crash', () => {
    const foo = Knobs.text('42');
    return <Text>{foo}</Text>;
  });
  
stories.addDecorator(Knobs.withKnobs);

```

Which version would you recommend to use? I

**Comment by Gongreg** [comment]
@aloifolia, hey, did you try adding decorator before stories? It looks like knobs are trying to emit events even though the decorator is not created yet.

**Comment by masm** [comment]
This is still an issue for me with version 3.2.13
