### ISSUE TITLE
Warnings about missing `selectedKind` and `selectedStory`

### ISSUE THREAD

**Issue by edoroshenko** [storybooks/storybook#1588]
Steps to reproduce:
1. Go through installation guide (https://storybook.js.org/basics/slow-start-guide/)
2. Open `http://localhost:9001/` (without query string!)
3. Open console

Result:
<img width="503" alt="screen shot 2017-08-03 at 21 30 48" src="https://user-images.githubusercontent.com/1292187/28939904-2772ce02-7893-11e7-8ef9-f15a7bbdac3a.png">

Expected result: clean console.

Additional information:
These warnings don't break the app, but add some extra noise, that sometimes confuses.
Apparently the problem is here: https://github.com/storybooks/storybook/blob/a9944e1533de79ce4a1a2fd8d2b25aa450998147/app/react/src/client/preview/init.js#L7
Probably it's not a good idea to run `init` function before stories had been added, or if it's an acceptable case, then `selectedKind` and `selectedStory` props of `Stories` component should become optional.

**Comment by bellomimarc** [comment]
I have the same issue.
Prev version (no issues) : 3.1.7 
Actualy version (with issue): 3.2.3

**Comment by Hypnosphi** [comment]
Looks like we jus should select the first story of the first kind by default. Feel free to file a PR

**Comment by kaiyoma** [comment]
Yup, seeing this error too in Storybook 3.2.3. Also seeing an error about the `prop-types` package:

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

**Comment by danielsneijers** [comment]
Is the issue still open? I'd like to take a shot at this one.

**Comment by kaiyoma** [comment]
I just ran into it this weekend after upgrading to the newest Storybook (and doing a clean install), so I believe it's still an issue.

**Comment by danielsneijers** [comment]
Cool, I'll check it out and try to make fix
