### ISSUE TITLE
'getstorybook' yields: 'Unable to get local issuer certificate'

### ISSUE THREAD

**Issue by kbherbert** [storybooks/storybook#1589]
Super stoked about Vue support! We are running through the setup on an internal repo that is inside a corporate firewall. Typically, when I install npm modules, I have to use the `strict-ssl=false` setting in my `.npmrc` to get around this error.

When running `getstorybook` within my Vue repo, I consistently get the following error:

```
C:\repo>getstorybook

 getstorybook - the simplest way to add a storybook to your project.

  Detecting project type. √
  Adding storybook support to your "Vue" app(node:34692) UnhandledPromiseRejecti
onWarning: Unhandled promise rejection (rejection id: 1): RequestError: unable t
o get local issuer certificate
```

I assume this command is trying to download other packages. I really only need to run this command once to do the initial setup. Any ideas where/what files to modify to work around this issue? Is there an HTTPS or SSL setting?

**os**: Windows 8
**npm**: 3.10.10
**node**: 6.9.5

Thanks!

**Comment by ndelangen** [comment]
All packages we download are on the public npm registry.

Some packages use a namespace (`@storybook`), maybe this is causing you some issues, if you're using a proxy.

see: https://github.com/storybooks/storybook/issues/235
> If so, can you try the default registry.
> 
> ```
> npm set registry https://registry.npmjs.org/
> ```
