### ISSUE TITLE
Can't setup in existing Vue project

### ISSUE THREAD

**Issue by mauzepeda** [storybooks/storybook#1596]
I followed the instructions as specified (run get storybook). I get the following errors (related to dependencies it seems).
[error.log.zip](https://github.com/storybooks/storybook/files/1201280/error.log.zip)

**Comment by ndelangen** [comment]
It seems the project type was undetected, this means the storybook CLI was unable to determine what to add.

Try setup/add storybook manually (it's not that hard!)
I have an example here:
https://github.com/ndelangen/storybook-vue-example

You need to:
- add the dependencies 
- add the `.storybook` folder.
- add stories

I hope this helps you.

**Comment by mauzepeda** [comment]
nom install wasn't working, yarn install did the job (+manual setup).
