### ISSUE TITLE
`getstorybook` package should warn that it's deprecated

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#1604]
And suggest to install `@storybook/cli`

**Comment by ndelangen** [comment]
Yeah, I'm talking with @mnmtanish and @arunoda about getting access to those packages, so we can deprecate all the old packages.

**Comment by UsulPro** [comment]
@ndelangen if you want to update `getstorybook` package, I have access to it on npm

**Comment by ndelangen** [comment]
Yes please!

**Comment by Hypnosphi** [comment]
@UsulPro did you do that?

**Comment by ndelangen** [comment]
Doesn't look like it's been done yet..
<img width="556" alt="screen shot 2017-11-02 at 23 30 20" src="https://user-images.githubusercontent.com/3070389/32353466-da1e727a-c025-11e7-8587-023898378404.png">

**Comment by ndelangen** [comment]
I still do not have access to that package, so I can't do it. @mnmtanish Are you able to help here? 🙇

**Comment by UsulPro** [comment]
Yes, I did:
![image](https://user-images.githubusercontent.com/14885189/34042052-ec41de54-e1ab-11e7-9b4e-348a4176e125.png)

![image](https://user-images.githubusercontent.com/14885189/34042215-a3b72f94-e1ac-11e7-9841-e2e2d2a559d7.png)

**Comment by UsulPro** [comment]
sure!
