### ISSUE TITLE
Tree animations perform poorly when knobs are present

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#1606]
It's easy to reproduce if you move the 'with knobs' story on the top of the 'Button' group in `examples/cra-kitchen-sink/src/stories/index.js`:

<details><summary>gif</summary>
<img src="https://user-images.githubusercontent.com/6651625/29007386-e937c8ca-7b0a-11e7-9d1e-bc0769a0e318.gif">
</details>

I'm not really sure, should we fix it on the side of knobs, tree, or both

**Comment by kohlmannj** [comment]
Writing a "+1" on this issue:

We're seeing unusable levels of sluggishness in a large Storybook (~30 components, 40+ stories), with multiple stories that use knobs. It's bad enough that I reverted back to the v3.1.x versions of `@storybook/react` and related dependencies.

 I will attempt to investigate and further diagnose the underlying cause as time permits.

**Comment by kohlmannj** [comment]
Writing a "+1" on this issue:

We're seeing unusable levels of sluggishness in a large Storybook (~30 components, 40+ stories), with multiple stories that use knobs, after upgrading to v3.2.x. It's bad enough that I reverted back to the v3.1.x versions of `@storybook/react` and related dependencies.

 I will attempt to investigate and further diagnose the underlying cause as time permits.

**Comment by ratheo** [comment]
We're also seeing very slow rendering. Especially the encoding and decoding of knobs for the url is taking up a lot of time.  It would be nice if it could be disabled.

**Comment by igor-dv** [comment]
You can change the `sidebarAnimations` to false with the options-addon. It will disable the tree animations.

**Comment by Hypnosphi** [comment]
In my case, removing global `withKnobs` decorator helped a lot

**Comment by lmenus** [comment]
Did anyone else experience delayed knob state updates? Let's say I have a text knob and as I type, every 2 or 3 characters it will backtrack by 1. Makes it very frustrating to use. I am only trying to determine if this is because of knobs right now.
