### ISSUE TITLE
build-storybook: Improve file deletion

### ISSUE THREAD

**Issue by srph** [storybooks/storybook#1608]
I found out that `build-storybook` appends `static` to the folder name, so:

```
build-storybook -c storybook -o storybook/static
```

Spouts everything to `storybook/static/static`. I just wanted to put everything storybook related inside the `storybook` directory, so I assumed that:

```
build-storybook -c storybook -o storybook
```

Would just make a `static` folder on the `storybook` folder.

But instead, it deleted everything and spouted an error: `Create a storybook config file in "storybook/config.js`.

I accidentally got all of my uncommitted code deleted :(.

## Suggestion

Delete only the files inside the `static` folder.

**Comment by ndelangen** [comment]
> https://opensourcecontributo.rs/user/ndelangen

AW SH🛑T, sorry man, I hope you didn't lose too much work.

**Comment by srph** [comment]
Nah it's fine. If anybody wants to pick this up, let us know. I'm interested to fix this soon, but I think I have a feeling that this upcoming week might be busy.

**Comment by Hypnosphi** [comment]
So, to be clear, do you want to have storybook's `index.html`, `iframe.html`, and `favicon.ico` in the same directory as the configs?

**Comment by Hypnosphi** [comment]
At the same time, I'm not sure that we should clear anything automatically. Webpack doesn't, so why should we?

**Comment by srph** [comment]
No, just that it puts things inside the `<output>/static` folder but at the same time deletes everything inside the `<output>` folder.

**Comment by Hypnosphi** [comment]
> the static folder (which it automatically appends)

Looks like we need this extra folder for webpack output

**Comment by srph** [comment]
Thank you, @Hypnosphi 🤜 🤛
