### ISSUE TITLE
Add multiple project roots to react-native CLI

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1609]
## why

So you can add components from from source that is located outside of your example app. E.g. 

https://github.com/storybooks/react-native-elements/tree/master/example

Currently you have to either copy the components into your app (which sucks) or reference them from the library (which sucks less, but means you need to link ... which RN doesn't support? or deploy to NPM).

## what

Add `--project-roots` option to the CLI here:

https://github.com/storybooks/storybook/blob/f3b063614188f20c2a36b84880c75bc4f3b80182/app/react-native/src/bin/storybook-start.js#L44

**Comment by danielduan** [comment]
fixed by https://github.com/storybooks/storybook/pull/1865
