### ISSUE TITLE
Markdown linting configuration is broken

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#1610]
## why

When I try to check in markdown changes, the linter automatically "fixes" the markdown with changes like this:

<img width="826" alt="storybooks_storybook" src="https://user-images.githubusercontent.com/488689/29036574-d9fe332c-7b54-11e7-8527-a550b89563f3.png">

This breaks the docs site, as you can see here:

https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel

1. FAQ is no longer in the side menu
2. FAQ title/heading is messed up

## what

Update linting settings or remove auto-linting for markdown

**Comment by Hypnosphi** [comment]
We have disabled the autofix for .md files
