### ISSUE TITLE
React-native device menu looks bad when RTL

### ISSUE THREAD

**Issue by alonbardavid** [storybooks/storybook#1611]
![screenshot_20170807-232805](https://user-images.githubusercontent.com/4058321/29044458-3dd124ae-7bc8-11e7-9439-704f767fa6e2.png)

When the android device is set to RTL (such as with hebrew), the menu that shows up on device when using React-native storybook obscures the content by default and when click on the header, instead of hiding it, it just docks it to the left.

I'm using:
@storybook/react-native : 3.2.3
haul: 1.0.0-beta.4
react-native: 0.46.4
With a real android device (samsung galaxy A7)

**Comment by shilman** [comment]
@ajwhite is this related to your backwards-compatible menu change?
