### ISSUE TITLE
Setting showLeftPanel does nothing without showDownPanel

### ISSUE THREAD

**Issue by KaySackey** [storybooks/storybook#1614]
If showLeftPanel is true, the left panel isn't shown unless showDownPanel is true.

I'd suggest merging these two into a single option like `panelLocation: "left" | "right" | "none"`

**Comment by Hypnosphi** [comment]
That's how storybook UI looks with
```
{
  showLeftPanel: true,
  showDownPanel: false,
}
```
<img width="1434" alt="screen shot 2017-08-08 at 12 42 24" src="https://user-images.githubusercontent.com/6651625/29066197-28b839f8-7c37-11e7-91ab-72a97bcad782.png">

Left panel (the one with navigation) is shown

Honestly, I find this naming (`showLeftPanel`, `showDownPanel`, and especially `downPanelInRight`, which is called "Action Logger position" in the shortcuts help) really confusing. I believe we should rename those to `showNavigationPanel`, `showAddonsPanel`, and `addonsPanelPosition`, respectively.

**Comment by danielduan** [comment]
definitely support the renaming of those.

**Comment by Hypnosphi** [comment]
Fixed with #1689

**Comment by shilman** [comment]
@Hypnosphi by convention we mark the issue as `merged` when the PR gets merged, and close the issue only once the code is actually released. See:

https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#closing-issues

**Comment by Hypnosphi** [comment]
Ok, so I shouldn't use the "Fixes #N" magic as I did before?

**Comment by shilman** [comment]
yeah i think we want the issues to only show up as fixed when end users can actually install the fix from NPM 👍

**Comment by shilman** [comment]
Fixed in 3.2.6 https://github.com/storybooks/storybook/releases/tag/v3.2.6
