### ISSUE TITLE
storyshots: decorators are part of the snapshots

### ISSUE THREAD

**Issue by testerez** [storybooks/storybook#1620]
When testing with storyshots, the decorators added with `addDecorator` are repeated in every snapshots. It would be great if the snapshots contain only the stories.
Is there any way to do it?

**Comment by coreylight** [comment]
I have a branch intended to fix this, but Github is crashing every time I try to make a PR 😕
https://github.com/coreylight/storybook/tree/no-decorators-in-storyshots

**Comment by UsulPro** [comment]
@coreylight Did you try to update your fork?
If still no success I can create a branch in storybook repo

**Comment by coreylight** [comment]
@UsulPro How should I update it? It looks like the diff is just massive. I based the branch on `release/3.3` due to this particular functionality being affected by wanting to use a snapshot per story, and not 1 big snapshot.

**Comment by UsulPro** [comment]
@coreylight is it #1849?
Could you add a description to this PR or close it if something wrong?
