### ISSUE TITLE
Resizing the preview iframe

### ISSUE THREAD

**Issue by seniorquico** [storybooks/storybook#1624]
Is there an available method to style or resize the preview iframe?

I would like to preview my components at various "screen sizes" to test some responsive CSS rulesets. Right now, I have to go fullscreen and resize the browser or enable the device mode using Chrome/Safari devtools. I could see making the testing workflow for a scenario like this much easier if the navigation menu could remain visible and the preview iframe just changed in size.

I tried out the third-party addon [storybook-host](https://github.com/philcockfield/storybook-host), but it creates/styles a div inside the preview iframe, skipping the responsive CSS rulesets.

**Comment by Hypnosphi** [comment]
<details><summary>Have you tried this?</summary>
<img src="https://user-images.githubusercontent.com/6651625/29102832-70eccf12-7cc4-11e7-80f3-a9e7722e8efe.gif">
</details>

**Comment by seniorquico** [comment]
@Hypnosphi Did you intend to include a link or reference?

**Comment by UsulPro** [comment]
@seniorquico It's default behavior of Storybook UI

**Comment by Hypnosphi** [comment]
@seniorquico please click on "Have you tried this?" above

**Comment by seniorquico** [comment]
@Hypnosphi Weird, the expanding block doesn't work on Chrome 60 on my Win10 touch device. Got it on my phone.

Yes. I can resize the pane manually and observe the responsive changes. That's what I've doing up to now. Having to test at multiple viewport sizes, I found the select menu with pre-defined options in the device mode of Chrome/Safari devtools much easier than manually resizing. However, that approach only works if I go into fullscreen.

What I was hoping to find was a mechanism to pre-define viewport sizes to quickly switch and test the responsive CSS rulesets. storybook-host was the closest I could find, but it fails to work for my scenario as it decorates the content of the iframe.

Having continued my Google search and digging just a bit around the code, I think I've approached the conclusion that this isn't currently achievable. But, would it be possible to create an addon that optionally applies margin around the iframe element from the manager app side?

On a related side note, [Sizzy](https://sizzy.co/) looks like an interesting tool. I had some issues with scroll bars appearing unnecessarily, and it still suffers the same fullscreen limitation as testing with device mode in Chrome/Safari devtools.

**Comment by ndelangen** [comment]
We have a topic on our roadmap to create tooling inside storybook (via addons) that mimic Sizzy's behavior, and make it easy to send links to real mobile devices to view the selected story in a variety of screen-sizes etc.

If you would want to work with us to create it 🙇 that'd be awesome!

**Comment by saponifi3d** [comment]
@ndelangen I recently ran into this issue as well, and created a quick addon to help solve the problem.

![viewport](https://user-images.githubusercontent.com/1569818/29285410-431ea466-80e3-11e7-8dc1-430a73785dc4.gif)

if you guys are interested, i'd love to cleaning up the action area, add more mobile sizes (maybe a handle to make responsive), and contrib back to the storybook addons :D

**Comment by seniorquico** [comment]
@saponifi3d That looks awesome! Please let me know if there's anyway I can help toward an effort to release your addon to the community.

@ndelangen Sending "fullscreen" links to a mobile device also sounds like an awesome feature. Are there any requirements or use cases drawn up? I'm definitely willing to help contribute.

**Comment by ndelangen** [comment]
@seniorquico Come join us on Slack so we can communicate efficiently on what, when and how we're planning to add the feature. 

Full disclosure: there hasn't been any work put into this except the description on our [Roadmap](https://github.com/storybooks/storybook/blob/master/ROADMAP.md)
