### ISSUE TITLE
Unable to install because package doesn't have certificate

### ISSUE THREAD

**Issue by vhflat** [storybooks/storybook#1630]
When trying to run `npm install @storybook/cli` I get the following error. 
I could set strict-ssl = false, but I can't really do that beacuse its not safe. 

> npm info using npm@4.1.2
npm info using node@v7.7.4
npm verb request uri https://registry.npmjs.org/@storybook%2fcli
npm verb request no auth needed
npm info attempt registry request try #1 at 12:37:05
npm verb request id 6bd6d99e44b72a3e
npm verb etag W/"597f3b21-91e1"
npm verb lastModified Mon, 31 Jul 2017 14:13:53 GMT
npm http request GET https://registry.npmjs.org/@storybook%2fcli
npm info retry will retry, error on last attempt: Error: unable to get local issuer certificate

Do you not have a proper certificate or am I doing something wrong?

**Comment by danielduan** [comment]
This sounds like something is wrong with your npm config or npm's certificate expired. Either that, or you're working behind a corporate proxy firewall and somehow they're stripping the ssl certificate.

Do installing other packages work for you?

**Comment by Hypnosphi** [comment]
Namely, other scoped packages, e. g. `@angular/common`

**Comment by vhflat** [comment]
Yup, the bug was in the corporate firewall.

**Comment by danielduan** [comment]
Thanks for reporting back. I'm gonna close this issue.
