### ISSUE TITLE
[addon-info] story source misleading without curly braces

### ISSUE THREAD

**Issue by jonambas** [storybooks/storybook#1633]
This is a very minor issue, but can be anoying when trying to copy/paste source.

Example source
<img width="980" alt="screen shot 2017-08-09 at 10 52 48 am" src="https://user-images.githubusercontent.com/3903325/29128204-28179b78-7cf1-11e7-95fe-d296d0272038.png">

Prop values should be surrounded with `{ }` eg: `<Tabs selected={0} />`

**Comment by UsulPro** [comment]
@jonambas Thanks for reporting this issue!
Do you want to help us to solve this?

**Comment by UsulPro** [comment]
btw here is a discussion about "Story Source" improvement #1602

**Comment by sabarnix** [comment]
@jonambas how did you manage to add linebreak between the attributes?
