### ISSUE TITLE
Global decorators in config.js are removed after hot module reload

### ISSUE THREAD

**Issue by clementoriol** [storybooks/storybook#1637]
Using the following package versions : 
```
"@storybook/addon-actions": "^3.2.0",
"@storybook/addon-info": "^3.2.0",
"@storybook/addon-knobs": "^3.2.0",
"@storybook/addon-options": "^3.2.3",
"@storybook/react": "3.2.3",
```

After adding global decorators in the config.js (before the configure function), the decorators work as expected (addon-info is here, addon-knobs works, etc.), but as soon as I save one of my file (a story for exemple), Storybook hot-reloads and the decorators are gone. Knobs doesn't work anymore, my custom decorator for wrapping the Preview component are gone, etc.

I tried removing decorators one by one with no success. The issues looks fairly consistent on any kind of Decorator.

I manage to find a workaround for now, downgrading my packages to these versions : 
```
"@storybook/addon-actions": "^3.1.6",
"@storybook/addon-info": "^3.2.0",
"@storybook/addon-knobs": "^3.1.6",
"@storybook/addon-options": "^3.1.6",
"@storybook/react": "^3.1.6",
```

And it now works as expected.

I can't provide a simple repo reproducing the error right now, but I believe it must be easily reproducible (I encountered the same bug  on two projets with very different configurations).

Let me now if you can't reproduce it, and I'll make one.
Thank you !

**Comment by ntucker** [comment]
There are two other reports of this in the original issue whose PR merge created this bug: https://github.com/storybooks/storybook/issues/877#issuecomment-320321789

**Comment by deehuey** [comment]
Any updates?

**Comment by ndelangen** [comment]
@clementoriol it would be super useful for anyone picking up this issue if there's a ready to go reproduction repo to clone. So it would help out tremendously if you could set that up? 🙇 

Switching from 3.2 to 3.1 solved the issue for you? damn, so we introduced this bug recently. Sorry about that.

**Comment by ntucker** [comment]
@ndelangen FYI the bug is added here: https://github.com/storybooks/storybook/commit/8a48f80d78d7dcfc9d8e32b4ea68d26bca1fa189

**Comment by crtvhd** [comment]
We're having the same issue with applying a global decorator which disappears after hmr:

```es6
// Custom decorator providing IntlProvider
const CustomIntlProvider = (storyFn) => (
  <IntlProvider locale="en">
    { storyFn() }
  </IntlProvider>
);

addDecorator(CustomIntlProvider);
```

(We know there's [storybook-addon-intl](https://github.com/truffls/storybook-addon-intl) however it seems to introduce much more errors in our storybook so we decided to provide [react-intl](https://github.com/yahoo/react-intl) manually)

Yet, adding the same decorator manually inside a story works just fine and does not break on hmr.

```es6
import { IntlProvider } from 'react-intl';
import { storiesOf } from '@storybook/react';

import Component from '../component';

const CustomIntlProvider = (storyFn) => (
  <IntlProvider locale="en">
    { storyFn() }
  </IntlProvider>
);

storiesOf('Component', module)
.addDecorator(CustomIntlProvider)
.add('Component', () => <Component />);
```

/cc @diablourbano

**Comment by ntucker** [comment]
@ndelangen I don't know why this https://github.com/storybooks/storybook/commit/8a48f80d78d7dcfc9d8e32b4ea68d26bca1fa189 was added. All it does is break HMR. HMR will run modules again while maintaining state so it just throws and exception. PR is to revert this buggy commit.

**Comment by igor-dv** [comment]
I think we are facing the same issue. I'll try to look into it ASAP.

**Comment by ndelangen** [comment]
Thank you @igor-dv 🙇

**Comment by igor-dv** [comment]
Let's make some order. 

1. #1481 was about to fix some wrong behavior in Storyshots regarding the global decorators (#877, #879) I still can't relate what was the problem, can someone elaborate it ? (cc @tmeasday)
2. This PR was about **not** to update global decorators after stories were loaded. 
3. Since in a regular work HMR causes global decorators to be cleaned and re-added again (IMO it's OK, because we **do** want to add global decorators on the fly) - it introduced a bug in which these decorators are cleaned but NOT re-added. 

IMO we need to revert this change and fix the storyshots problem in a proper way.

**Comment by tmeasday** [comment]
The idea of #1481 was to help people who put their global decorators *after* their story modules are required, like: https://github.com/ktj/storybook-rp/blob/master/.storybook/config.js#L6-L20

Looking at it closer, the reason the above code breaks in SS is that storyshots does this totally zany thing to emulate `require.context` (a webpack thing): https://github.com/storybooks/storybook/blob/master/addons/storyshots/src/require_context.js

Honestly, I think it's just mis-implemented, maybe there is something I am missing.

We should revert the PR and fix the require context thing.

**Comment by igor-dv** [comment]
Maybe it's far from being discussed (and a wrong place), but what if `configure`, will take `loadDecorators` function, like it takes `loadStories`.. And in general, may be it's better to limit the API to some life-cycle

**Comment by theKashey** [comment]
Still an issue :(

**Comment by wintercounter** [comment]
Why is this closed?

**Comment by shilman** [comment]
@wintercounter are you still seeing this? If so, what version?

**Comment by wintercounter** [comment]
Latest. I'm having a custom ApolloProvider as:
```jsx
addDecorator(storyFn => <ApolloProvider client={client}>{storyFn()}</ApolloProvider>)
```

**Comment by shilman** [comment]
@wintercounter `5.1.9`? Just verifying since I've been touching that code in `5.2.0-beta.x` and want to make sure it wasn't those changes that caused a regression. Thanks.

**Comment by wintercounter** [comment]
Yes, it `5.1.9`.

**Comment by heleg** [comment]
Still actual for version `5.2.6`

**Comment by wintercounter** [comment]
We still have this issue btw on 5.2.6. SInce we develop in Storybook in the first place, it makes the process really painful.

**Comment by heleg** [comment]
@wintercounter Do you require your decorators from another file?

I had this problem until I removed `require` and started to use `addDecorator` directly in my `config.js`

**Comment by wintercounter** [comment]
No, i have it in my setup:

```js
// Storybook setup file
import { addDecorator } from '@storybook/react'
import { ApolloProvider } from 'react-apollo'
import { ApolloClient } from 'apollo-client'
import { ApolloLink } from 'apollo-link'
import { InMemoryCache } from 'apollo-cache-inmemory'

const cache = new InMemoryCache()

const client = new ApolloClient({
    link,
    cache
})

addDecorator(storyFn => <ApolloProvider client={client}>{storyFn()}</ApolloProvider>)
```

**Comment by shilman** [comment]
@wintercounter do you have a repro repo I can look at?

**Comment by raphaelboukara** [comment]
## To reproduce:
Open a new shell and:
```sh
nvm use 10
git clone https://github.com/raphaelboukara/storybug.git
cd storybug
npm i
npm run storybook
```
![image](https://user-images.githubusercontent.com/6442236/71577662-baf60800-2afd-11ea-9fd3-6d6d1d450798.png)

go to `src/Button/index.js`.
add some changes. (for instance add "hi!" before text)
![image](https://user-images.githubusercontent.com/6442236/71577744-ff81a380-2afd-11ea-8635-4e8d4ff7fe04.png)

The global decorator disappear.

**Comment by shilman** [comment]
@raphaelboukara global decorators should be applied in `config.js`. if you move the global decorator in your example, HMR works as expected.

**Comment by peterp** [comment]
`config.js` doesn't seem to be documented.

**Comment by tmeasday** [comment]
@peterp it is now `.storybook/preview.js`
