### ISSUE TITLE
VueJS Webpack Template Compatibility

### ISSUE THREAD

**Issue by philipithomas** [storybooks/storybook#1648]
I just spent the better part of a day getting Storybook to work with our VueJS codebase, which is based on the [VueJS Webpack Template](https://github.com/vuejs-templates/webpack). 

The hardest part was getting the webpack configurations to work. Loaders seemed to keep causing issues for many different kinds of files. We use some features beyond the base template such as custom font loading, importing fontawesome, and a [single global variables.scss file](https://github.com/vuejs/vue-loader/issues/328). 

What I basically ended up doing was merging the Storybook config with the `build/webpack.base.conf.js`, while selectively importing some features from `build/webpack.dev.conf.js`. 

This part of the `build/webpack.dev.conf.js` caused issues, and I'm not sure why:

```js
new webpack.DefinePlugin({
      'process.env': config.dev.env
}),
```

So, here is the `.storybook/webpack.config.js` that worked for me:

```js
// load the default config generator.
const devConfig = require('../build/webpack.base.conf.js');
const path = require('path');
var utils = require('../build/utils');
var merge = require('webpack-merge');
var webpack = require('webpack')
var config = require('../config');
var FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')

// Export a function. Accept the base config as the only param.
module.exports = (storybookBaseConfig, configType) => {
  devConfig.entry = storybookBaseConfig.entry;
  devConfig.output = storybookBaseConfig.output;

  devConfig.module.rules.push(storybookBaseConfig.module.rules[0]);
    
  return merge(devConfig, {
    module: {
      rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap })
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new webpack.NoEmitOnErrorsPlugin(),
      new FriendlyErrorsPlugin(),
    ]
  })
};
```

What's my goal with opening a Github issue? The Vue Webpack Template is fairly standard in the Vue community. I think that we could work to improve my hack into a "best practices" 
Storybook webpack configuration for users of VueJS Webpack Template. 

If this issue isn't actionable - feel free to close it, and people who want to see my solution can find it through search.

**Comment by kazupon** [comment]
I'm contributing to make storybook available for vue users coommunity. However, My time is limited due to hard to work and Vue.js core team.

I hope your contributing. 👍

**Comment by ndelangen** [comment]
@philipithomas We'd be happy to change the default webpack config to accommodate users of the vue webpack template. Would you be interested in helping us and make a PR?
