### ISSUE TITLE
Make storybooks more impartial

### ISSUE THREAD

**Issue by miljan-aleksic** [storybooks/storybook#1654]
I love the initiative to support other frameworks, and in that line of work, I would like to see less about react/vue and more about the storybooks as a whole. For example:

- The repo description is about React, only.
- The storybooks source code, even if react based, should not have react namespaces in the result. There are data named as `data-reactroot` which when using Vue lead to believe you are using the wrong version.
- The docs and site are about React 99%, even the Vue part is referencing at some point react instead of Vue.
- FW specific addons should be moved to a different section.

I am sure you are aware of this and working toward a transition, which takes time, but seems there are some easy task that could be done already. Like updating the repo description and docs.

I can definitely help about this if required.

**Comment by Hypnosphi** [comment]
> There are data named as `data-reactroot` which when using Vue lead to believe you are using the wrong version.

Can you please elaborate? `data-reactroot` is attached and used by React DOM, not by Storybook app itself.

Anyway, feel free to contribute!

**Comment by miljan-aleksic** [comment]
Ok, I don't know react works, we can skip that one :)

**Comment by ndelangen** [comment]
Definitely something we're working on. It's a continues process of improving the codebase.

I think for the most part the points made in the OP have been addressed, If you have specific places you can point us to to improve: please let us know!
