### ISSUE TITLE
Storybook react-native not working on Android. Another process using port 8081

### ISSUE THREAD

**Issue by TakeoffAndroid** [storybooks/storybook#1656]
<img width="455" alt="screen shot 2017-08-14 at 1 15 28 pm" src="https://user-images.githubusercontent.com/11768239/29268865-61a4feca-810c-11e7-9b28-e41b246acf07.png">

**Comment by TakeoffAndroid** [comment]
I did all the possible ways. I changed the port from 8081 to 8088, but after changing the port issue again reflecting on port 8088

**Comment by philipithomas** [comment]
You might have storybook or another app already running and using that port. Did you try rebooting? 

You can find the app running with netstat or lsof ([see here](https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac)).

**Comment by TakeoffAndroid** [comment]
Yes. I tried rebooting, resetting, changing port and adb reverse too. None
worked.

**Comment by Hypnosphi** [comment]
So what's the output of `lsof -i :8081` in your case?

**Comment by TakeoffAndroid** [comment]
It was showing npm process running. Then i took the PID and execited kill
-9 PID command.

**Comment by Hypnosphi** [comment]
And what does the same command return right after the kill?

**Comment by TakeoffAndroid** [comment]
It is not showing up anything. Just an empty response.

On Aug 15, 2017 1:04 AM, "Filipp Riabchun" <notifications@github.com> wrote:

And what does the same command return right after the kill?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/storybooks/storybook/issues/1656#issuecomment-322286903>,
or mute the thread

**Comment by Hypnosphi** [comment]
Can you please create a temporary GitHub repo with your setup, so that we could reproduce your issue?
