### ISSUE TITLE
Start Guide for React/ Vue links are broken

### ISSUE THREAD

**Issue by msankhala** [storybooks/storybook#1660]
Route for these two links does not exists.

https://storybook.js.org/basics/slow-start-react
https://storybook.js.org/basics/slow-start-vue

On this page https://storybook.js.org/basics/quick-start-guide/ when click on these two links it show this error

```
Edit this page

NOT FOUND ⚓️
You just hit a route that doesn’t exist… the sadness. We’re working on improving this page, sorry.

Go to the main page

```

**Comment by Hypnosphi** [comment]
It's already fixed with #1629, but not yet deployed for some reason. @ndelangen how do we deploy the website?

**Comment by ndelangen** [comment]
I'll do it

**Comment by ndelangen** [comment]
done!
