### ISSUE TITLE
PropTypes are missing in info panel in static build

### ISSUE THREAD

**Issue by iernie** [storybooks/storybook#1661]
Couldn't find this issue anywhere so I am reporting it here.

It seems that when using the info-addon, the proptypes to a components works when you run storybook locally, but all proptypes are defaulted to type `node` in a static build of storybook.

The required field is also reset to `no` in a static build. Default seems to work though.

Here is a picture of it running locally
![live](https://user-images.githubusercontent.com/196950/29315692-d0528b18-81c4-11e7-858d-169ee14406e7.PNG)

And here is how it looks once it's built static
![static](https://user-images.githubusercontent.com/196950/29315709-e3ec7616-81c4-11e7-966f-ef7f213e285f.PNG)

Versions are
* `@storybook/react` v3.2.4
* `@storybook/addon-info` v3.2.4

**Comment by danielduan** [comment]
I think I know what's happening here. On prod, PropTypes get stripped out because it's not necessary in the traditional prod environment sense. Also, the `babel-plugin-react-docgen` doesn't run.

**Comment by DanielJRutledge** [comment]
Am also facing this issue with static builds of storybook. Any suggested workarounds until a fix is put in?

**Comment by danielduan** [comment]
There's really no workaround unfortunately. I don't think you can use a custom `.babelrc` for static builds.

I'll fix it when I get a chance.

**Comment by DanielJRutledge** [comment]
A custom ```.babelrc``` would only be employed on non-static builds?

**Comment by danielduan** [comment]
@DanielJRutledge unfortunately, yes. I think I'm gonna add it into the prod babel config for now and refactor the function that takes the custom babelrc later.

**Comment by danielduan** [comment]
Think this issue has been fixed when we refactored the server code to the core package.
