### ISSUE TITLE
(0, _typeof4.default) is not a function

### ISSUE THREAD

**Issue by blargity** [storybooks/storybook#1665]
I'm trying to set up Storybook for our react native application. We're using `async` / `await`.

When I run `yarn run storybook` I get:
![screen shot 2017-08-16 at 10 45 50 pm](https://user-images.githubusercontent.com/1531750/29363871-ef1adb20-82d4-11e7-9dd0-b431ee87e7b0.png)

I think this is related to babel not being configured with `"plugins": ["transform-async-to-generator"]` so I tried setting that explicitly in a `.babelrc` in `<project>/storybook` but it didn't seem to have any effect. I also tried using `babel-preset-react-native-stage-0` and it didn't have any effect either.

How can I use `async` / `await` with react native storybook? I can't seem to find any examples.

Details:
```
"@storybook/react-native": "^3.2.4",
"react-native": "0.44.0",
"react-dom": "16.0.0-alpha.6",
```

The repo I'm working on is open source, so here's a reproduction branch: https://github.com/blargity/kitsu-mobile/tree/storybook

I'd love any help anyone can provide!

**Comment by ndelangen** [comment]
I will add the plugin to the babel config

**Comment by blargity** [comment]
Is there a way for me to configure Storybook to use a different babel config in the meantime? I couldn't seem to get it to work even with adding a `.babelrc` in the `storybook` directory that running `getstorybook` created for me.

**Comment by ndelangen** [comment]
@blargity adding a `.babelrc` in the storybook config folder should work..

I've never used this myself, though.

I feel like we need to revamp how we configure things #1209 
How nextjs is configured I like a lot.

**Comment by ndelangen** [comment]
Regarding this specific issue, please recheck after next release. I think @shilman is working on it at the moment. Please re-open if it's not working.
