### ISSUE TITLE
addons-info missing typescript declarations

### ISSUE THREAD

**Issue by tko** [storybooks/storybook#1669]
While type definitions for many of the addons (knobs, links, notes, options, actions) seem to exist in DefinitelyTyped repository, there's none for `addons-info`.

**Comment by danielduan** [comment]
You're more than welcome to submit a PR and add them

**Comment by mkornblum** [comment]
I just opened one on DefinitelyTyped here - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20538

It wasn't 100% clear to me if I should have opened it on this repo or that one, but I went with the other once since that is where the other addon type definitions live.

**Comment by mkornblum** [comment]
Looks like they merged it already, hope they are helpful for you!

**Comment by andrespch** [comment]
hey @mkornblum  did you manage to get the propTypes descriptions working properly with TypeScript? it won't show the types for me, and will only show the propTypes section if I add defaultProps. I define my props like this 

```interface ActionButtonProps extends React.Props<ActionButton> {
  text?: string;
  onTap?(): void;
  disabled?: boolean;
}
```
