### ISSUE TITLE
How to set <body> classes?

### ISSUE THREAD

**Issue by code-by** [storybooks/storybook#1672]
Hello!
Is there way to set `<body>` (inside `<iframe>`) class(es)? (except using `finddomnode`)
Thank you

**Comment by danielduan** [comment]
What are you trying to insert? You should generally be using stories to insert components and add decorators to them if you want the components to be wrapped in something.

Extremely hacky way: you can target the nodes onload with a script in the header
https://storybook.js.org/configurations/add-custom-head-tags/

**Comment by code-by** [comment]
For example, one have css with 
```
body.someClass {
  background-color: 'green';
}
body.anotherClass {...}
....
```

so for storybook it is need to reassign body class(es) for another(s) div(s).

**Comment by ndelangen** [comment]
Write a wrapper component / decorator that sets the classes for you.

Alternatively you could write an addon so you can change the class from a panel for example.

**Comment by matthewharwood** [comment]
@ndelangen How do you set wrapper decorators with angular story books... I'm totally unable to do so.

**Comment by LiranBri** [comment]
you can add file *config.js* to *.storybook* dir with something likes this:
```javascript
import { configure } from '@storybook/react'

function loadStories () {
  document.body.className += ' ' + 'hasHover'
}

configure(loadStories, module)

```

**Comment by ndelangen** [comment]
That will work, mind that config.js CAN be MHR, and so the code may execute multiple times.
Another way wuld be to do this in an addon, which rejects HMR or in `preview-head.html`.

**Comment by ndelangen** [comment]
```js

storiesOf('name', module)
  .addDecorator(story => {
    document.body.classList.add('hasHover');
    return story();
  })
  .add('other name', () => {
    // ..
  });
```

Something like that might work, as a decorator.
But please consider that this will add a class to the body every time the story is rendered, and never cleans-up.. pretty bad.

Decorators are to change the story before they render, wrap them, extract data etc.

For permanent things side effects you're way better off using preview-head.html right now.

**Comment by vidal7** [comment]
Creating a file named preview-head.html in your config directory containing this seems to have worked out for me.

> <script>setTimeout(function () { document.body.classList.add("yourClass"); }, 0);</script>
