### ISSUE TITLE
Knobs: allow opting out of persisting values in URL

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#1680]
Ideally it would be a per-knob option. In fact, maybe having this on object knob could be enough

**Comment by danielduan** [comment]
I think the knobs in the URL looks really messy. I'd love to have an input in the panel to generate the copy and paste url, and perhaps save the actual knobs data in the local storage or cookie.

**Comment by SuperOl3g** [comment]
Yep, with encoded Russian symbols it looks  awful)
`http://localhost:3001/?knob-%D0%A2%D0%B5%D0%BA%D1%81%D1%82=%D0%97%D0%B0%20%D0%BE%D0%B1%D0%B5%D0%B4.%20%D0%A1%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE%21&selectedKind=a.Balloon&selectedStory=%D0%91%D0%B5%D0%B7%20%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs`
