### ISSUE TITLE
Add option to specify path where all files from static directories will be outputted

### ISSUE THREAD

**Issue by BjornMelgaard** [storybooks/storybook#1685]
Right now I have nextjs project, with images in `/static/images` folder, and Im using it in components like this

`<img src="/static/images/logo.png" alt="logo" />`
Problem is when I starting storybook with `"storybook": "start-storybook -p 6006 -c app/.storybook -s static",` the logo cant be found, for storybook proper path to image is now `"/images/logo.png"`

**Comment by jonespen** [comment]
Had the exact same issue, added the file  `middleware.js` to `./storybook` with this content: 
```js
/* eslint-env node */
const express = require('express')
const path = require('path')

module.exports = router => {
  router.use('/static', express.static(path.join(__dirname, '..', 'static')))
}
```

Hope it helps!

Inspired by https://github.com/storybooks/storybook/issues/714

**Comment by BjornMelgaard** [comment]
Thanks @jonespen :+1:

**Comment by Hypnosphi** [comment]
@ndelangen is this middleware feature documented anyhow?

**Comment by ndelangen** [comment]
I'm afraid it's not @Hypnosphi 

Thing to know about it is: it doesn't work when building a static version of storybook.

**Comment by aviramga** [comment]
@ndelangen @jonespen Im having the exact same issue but with build-storybook. Im also using nextjs. How can I solve this?

Thanks!

**Comment by Hypnosphi** [comment]
See https://github.com/storybooks/storybook/issues/714#issuecomment-365263374

**Comment by Hypnosphi** [comment]
Duplicates #714
