### ISSUE TITLE
[Suggestion] add bookshelf feature to classify books/stories

### ISSUE THREAD

**Issue by xareelee** [storybooks/storybook#1688]
I have categories for different purposes: 

* `Component`: display a UI element for reusability
* `Scene`: display a whole UI page for a scene
* `App`: display the whole app with full functionalities just like `react-native start`
* and more... for testing specific functionalities with UI

My current stories are like this:

<img width="257" alt="screen shot 2017-08-19 at 10 09 12" src="https://user-images.githubusercontent.com/804308/29482597-b2947ad2-84c6-11e7-8a5a-cb499afa12f2.png">

```
* [API] REST API
* [Scene] AdDialog
* [Comp] BannerButton
* [Comp] BannerView
```

I want to make stories to be classified in categories

```
* API
    * REST API
* App
    * new start
    * logged-in user
* Components
    * BannerButton
    * BannerView
    * ...
* Scenes
    * AdDialog
    * ....
```

using the following code

```js
// original story: accept a string for the story name
storiesOf('[Scene] AdDialog', module)

// with category: accept an array for the category and story names
storiesOf(['Scene', 'AdDialog'], module)
```

**Comment by tmeasday** [comment]
Hi @xareelee -- you can use the new Story Heirarchy feature to achieve this I think? https://medium.com/storybookjs/announcing-storybook-3-2-e00918a1764c

Try `storiesOf('Scene / AdDialog', module)` etc

**Comment by xareelee** [comment]
Thanks for the info. I did not notice this new feature. It works after upgrading to 3.2.
