### ISSUE TITLE
Options set via addon should not override URL params

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#1690]
1. Run `yarn start` in repo root
2. Toggle actions panel with `⌘ ⇧ D`
3. Reload the page

Expected: Actions panel stays hidden
Actual: It is hidden for a moment, and then shows up

**Comment by UsulPro** [comment]
@Hypnosphi it happens because we use `setOptions` in `config.js` to setup initial state.
If you remove `setOptions` it'll behave as you describe

**Comment by Hypnosphi** [comment]
My point is that query params should have higher priority when present

**Comment by UsulPro** [comment]
I see but `setOptions` can be used per story to setup appearance accordingly to selected story. It'll stop working if we change the priority

**Comment by Hypnosphi** [comment]
Well, if I reload the page, I stay on the same story. Links to other stories can be adjusted according to their specific `setOptions`

**Comment by UsulPro** [comment]
So you offer to detect where it runs: inside a story or not? And depending on that change `setOptions` behavior?

**Comment by Hypnosphi** [comment]
I'd suggest roughly that:
1) explicit URL param have precedence when defining current view
2) hiding/showing a panel changes the current page URL
3) URL params in links to other stories are formed in this manner:
    a) If the story has set the corresponding option via local `setOptions`, use that
    b) Otherwise, use the current value

**Comment by Hypnosphi** [comment]
By the way, how do you use `setOptions` per story? Can't find that in docs

**Comment by UsulPro** [comment]
this way: 
https://github.com/storybooks/storybook/blob/master/examples/cra-kitchen-sink/src/stories/index.js#L83

or even like this:
https://github.com/storybooks/storybook/blob/master/examples/cra-kitchen-sink/src/stories/index.js#L70

so in this cases URL could be formed twice:
1. when you select a story in stories panel
2. when this story trigger `setOptions` and it updates query params

**Comment by Hypnosphi** [comment]
Oh, so it's inside story render

**Comment by Hypnosphi** [comment]
Fill fix it as part of https://github.com/storybooks/storybook/issues/2313
