### ISSUE TITLE
Unknown option: base.cacheDirectory

### ISSUE THREAD

**Issue by satazor** [storybooks/storybook#1709]
I was trying the new `3.2.6-alpha.0` release but it has an error when used with `storyshots` because of https://github.com/storybooks/storybook/blame/master/app/react/src/server/config/babel.js#L6 which was recently added.

We must omit that in https://github.com/storybooks/storybook/blob/master/addons/storyshots/src/index.js#L41 and probably other places.

//cc @ndelangen

**Comment by ndelangen** [comment]
How do I test this?

**Comment by ndelangen** [comment]
Can you help me determine if this change fixes the problem?

**Comment by satazor** [comment]
Yep I will test it right now.

**Comment by satazor** [comment]
@ndelangen is does work, but shouldn't you apply the same fix to the react app?

**Comment by ndelangen** [comment]
Thanks for validating! 

> @ndelangen is does work, but shouldn't you apply the same fix to the react app?
It was already there..

**Comment by satazor** [comment]
@ndelangen Could we have a patch release with the fix? I'm kind of blocked because I need the newest version because of https://github.com/storybooks/storybook/pull/1554 available in `3.2.6` but at the same time I can't use it because of this bug.

**Comment by shilman** [comment]
@satazor https://github.com/storybooks/storybook/releases/tag/v3.2.7 👍
