### ISSUE TITLE
Cannot toggle search box when it has focus

### ISSUE THREAD

**Issue by tesla3327** [storybooks/storybook#1717]
When you toggle the search box on, it gets focus automatically. However, if the search box has focus you cannot use the same key commands to toggle it off. You must first click elsewhere to give focus the rest of the app, and then the key command will work again.

This is frustrating because it is unexpected behaviour and requires an extra mouse click (or tab to shift the focus).

**Comment by igor-dv** [comment]
Doesn't the `Esc` key work for you ?

**Comment by tesla3327** [comment]
The `Esc` key does not work for me.

Even if it did, it doesn't solve the issue that this is unexpected behaviour. Any IDE or editor or Spotlight on OS X do not require you to change focus before you can actually toggle the search box off again.

**Comment by Hypnosphi** [comment]
Which version of `@storybook/react` do you use?

**Comment by danielduan** [comment]
Just tested this to be working on Chrome in the `cra-kitchen-sink` on master. Clicking outside or hitting escape will close the search box. I'm gonna consider this as expected behavior and close the ticket.

Please reopen if you still can't close the search box on the latest version of Storybook.
