### ISSUE TITLE
Syntax error import statement on storyshots

### ISSUE THREAD

**Issue by satazor** [storybooks/storybook#1720]
Version 3.2.6 & 3.2.7 both contain a change on the babel presets. More specifically,
it was added `babel-preset-env` and removed `babel-preset-es2015` and `babel-preset-es2016`.

The issue is that the `modules` option was set to false but this causes issues when integrating with Jest. It must be NOT set if `process.env.NODE_ENV` is `test`. CRA does the same here: https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/index.js#L73

**Comment by shilman** [comment]
Released in 3.2.8, closing. Please re-open if there's more to do here!

**Comment by satazor** [comment]
It's working nicely now. Thanks!
