### ISSUE TITLE
getstorybook custom package manager setting

### ISSUE THREAD

**Issue by vjpr** [storybooks/storybook#1728]
- I want to use `pnpm` to install packages.
- I would also like a way to disable the installation step.

**Comment by ndelangen** [comment]
Yeah this sounds do-able. However going to be honest, our CLI does really need a complete overhaul, but it's low on the priority list.

**Comment by ndelangen** [comment]
We'd love help with this, so if anyone reads this and like writing CLIs please post here or come talk to us on slack. 👍

**Comment by ndelangen** [comment]
Will happen at some point as part of https://github.com/storybooks/storybook/issues/1108

**Comment by vjpr** [comment]
It would actually be a very small change here:

https://github.com/storybooks/storybook/blob/4c050d23801ba38e70f514d3fd27e63b6693dc40/lib/cli/lib/helpers.js#L150-L154

**Comment by ndelangen** [comment]
I'd welcome this in a PR!

**Comment by Hypnosphi** [comment]
> a way to disable the installation step

This is actually possible:

```
getstorybook --skip-install
```
