### ISSUE TITLE
`babel-plugin-transform-regenerator` and `babel-plugin-transform-runtime` missing from `app/react/package.json`

### ISSUE THREAD

**Issue by vjpr** [storybooks/storybook#1729]
I assume in the other projects (app/vue) too.

**Comment by valscion** [comment]
Seems like this was introduced by #1668? https://github.com/storybooks/storybook/pull/1668/files#r133578294

**Comment by valscion** [comment]
Here is a reproduction repository for this issue, created with `create-react-app` and just running `getstorybook`:

https://github.com/valscion/storybook-repro-1729

**Comment by Hypnosphi** [comment]
@valscion Please create a PR as soon as you do that =)

**Comment by valscion** [comment]
PR to fix this issue is here: https://github.com/storybooks/storybook/pull/1848
