### ISSUE TITLE
No custom babel config option for static builds

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#1731]
There's no way to add a custom `.babelrc` to static prod builds. Discovered during https://github.com/storybooks/storybook/issues/1661

It might be helpful to be on feature parity with dev builds for this one.

**Comment by cramatt** [comment]
Is this issue still open in 3.x.x ? I seem to be getting errors related to this... 

Does anyone have a workaround?

**Comment by danielduan** [comment]
Definitely still an issue. If you'd like to open a PR for this, please do. @cramatt

**Comment by danielduan** [comment]
I think this has been fixed in the core refactor. Going to close this, please open a new ticket if this is still an issue.
