### ISSUE TITLE
npm test gives setupFiles option was not found Validation error

### ISSUE THREAD

**Issue by arpankotecha** [storybooks/storybook#1734]
I'm running:
mac osx 10.12.5
npm 5.3

Followed the following instructions:
```
git clone https://github.com/storybooks/storybook.git
cd storybook
npm install
npm run bootstrap -- --core
```

Ran 
`
npm test
`

I get the following errors:
```
> storybook@3.0.0 test /Users/arpankotecha/src/react/storybook
> jest --projects ./ ./examples/react-native-vanilla

● Validation Error:

  Module <rootDir>/node_modules/react-native/jest/setup.js in the setupFiles option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

npm ERR! Test failed.  See above for more details.
```

Do I need to do anything before I can run tests?

**Comment by Hypnosphi** [comment]
You need to bootstrap RN-vanilla as well: `npm run bootstrap -- --core --react-native-vanilla`

@ndelangen I believe we should add that either to `CONTRIBUTING.md` or to `pretest` script

**Comment by ndelangen** [comment]
Yes that would resolve the issue indeed.

@arpankotecha In order to run all unit tests (including the ones for react-native) you have to have bootstrapped the react-native part of the codebase too!

Sorry our documentation is a bit lacking here, I'm working on improving this.

**Comment by CLL80** [comment]
For anyone having an issue with the ``unknown option `--react-native-vanilla'`` error, it seems the `--react-native-vanilla` flag has been changed to `--reactnative`.

**Comment by Hypnosphi** [comment]
Thanks @CLL80, I've edited the original comment
