### ISSUE TITLE
Can't get props for addon-info when using decorator (higher order component) on my component

### ISSUE THREAD

**Issue by michalg42** [storybooks/storybook#1735]
Hello

I wanted to use addon-info to get props in stories, but I got something like this in PropTypes section:
"withTheme(withStyles(Avatar))" Component
No propTypes defined!
Well, that's obvious for me why it's like this, but I would like to get props for Avatar, not its HOC. I couldn't find how to do it in readme, neither in issues.
How can I achieve this?

**Comment by Hypnosphi** [comment]
Are those HOCs your own, or are they taken from some library like recompose? If the former, you may want to extend the output with static methods from input:
```
function withSomething(ComposedComponent) {
  const Component = ...
  return Object.assign(Component, ComposedComponent)
}
```

**Comment by michalg42** [comment]
Unfortunately for me they are from libraries, in my case these are react-intl and material-ui (v1).

**Comment by UsulPro** [comment]
@michalg42 There two ways to get props in your case.

1. You can simply add everything you need into `propTables` option like this:

```js
withInfo({
      text: 'doc string about my component',
      propTables: [Avatar],
    })
```

2. You can separate your component from HOC. It means you can add High Order Components via `addDecorator` and then apply `withInfo` to your `<Avatar>` and add it as a story. I guess it's more "Storybook" way.

If you're using Material-UI library you might try to use this Storybook addon:
https://github.com/react-theming/storybook-addon-material-ui
It does exactly what I described in the second point: wraps your own components via decorator

**Comment by loliver** [comment]
I'm getting an issue when manually specifying `propTables` where the prop descriptions aren't passed through. The tables themselves are correct, just no comments are being parsed.

**Comment by yaminyaylo** [comment]
@loliver I have the same issue with components that have linked a style sheet (`export default withStyles(styles)(NavigationMenu)`) and then manually adding to propTables.

Maybe you have a solution to resolve this?

**Comment by baktiaditya** [comment]
@loliver me too :(
is there any luck getting the description in a wrapped component?

**Comment by loliver** [comment]
I wasn't able to find anything further, we've decided to stop using this addon for any documentation going forwards as it doesn't quite do what we need unfortunately.

**Comment by seveibar** [comment]
I may have a solution to this,

Instead of...
```javascript
class MyComponent extends Component<*,*> {
// ...
}

export default withStyles(styles)(MyComponent)
```

Do this...
```javascript
const StyledReactComponent = withStyles(styles)(Component)

class MyComponent extends StyledReactComponent<Props, State> {

}
export default MyComponent
```

Seems to be working so far for me.

**Comment by zhukmj** [comment]
Here is a workaround I used in my project

```js
// ...
const Button = (props) => {
   return (
    <button}>Click me</button>
  );
};

Button.propTypes = {
  primary: PropTypes.bool,
  secondary: PropTypes.bool,
};

export const ButtonComponent = Button;
export default withStyles(styles)(Button);
```

And now my story will look like

```js
// ...
import Button, { ButtonComponent } from '../src/Button';

storiesOf('Button', module)
  .add('Simple', withInfo({
    text: 'Simple button description',
    source: false,
    propTables: [ButtonComponent], // display propTable for Button component
    propTablesExclude: [Button], // do not display propTable for HOC
  })(() => <Button primary>Primary Button</Button>));
```

**Comment by spencerdcarlson** [comment]
Another solution is to add the propTypes after the HOC

```
// ...
const Button = (props) => {
   return (
    <button}>Click me</button>
  );
};

const HOC = withStyles(styles)(Button);

HOC.propTypes = {
  primary: PropTypes.bool,
  secondary: PropTypes.bool,
};

export default HOC;
```

**Comment by PolGuixe** [comment]
I have tried @zhukmj and as I am using Flow, it just works partially and is not able to get all the information.

![screen shot 2018-08-14 at 18 48 58](https://user-images.githubusercontent.com/6626225/44105688-bbce975c-9ff2-11e8-90ab-b9b4dcd6c8b6.png)

**Comment by eddiemonge** [comment]
I think this issue should still be opened, especially as CSSinJS becomes more popular

**Comment by Itrulia** [comment]
Yeah I think the same, using `styled-compoents` will result in

```
<Styled(styled.button) onClick={clicked}>
  Button
</Styled(styled.button)>
```

**Comment by mlnor27** [comment]
Hi everyone !
I encountered the same issue using the memo optimization HOC for functional component. Do we still have any news on this ?

**Comment by mlnor27** [comment]
> Another solution is to add the propTypes after the HOC
> 
> ```
> // ...
> const Button = (props) => {
>    return (
>     <button}>Click me</button>
>   );
> };
> 
> const HOC = withStyles(styles)(Button);
> 
> HOC.propTypes = {
>   primary: PropTypes.bool,
>   secondary: PropTypes.bool,
> };
> 
> export default HOC;
> ```

Props end up not being passed at all :/
