### ISSUE TITLE
Props order

### ISSUE THREAD

**Issue by RomainGoncalves** [storybooks/storybook#1737]
Hi there, 

sorry quick question. Is there a set order for the props display in the table?
They seem to be totally random yet fixed. Every refresh yields the same order, but I can't find how to organise them properly.

Thanks for any clue

**Comment by danielduan** [comment]
They are ordered based on how they are listed inside your react component.

**Comment by ndelangen** [comment]
Please re-open if the answer doesn't work or you've found a bug ♥️

**Comment by RomainGoncalves** [comment]
Ok I see that I need to upgrade to at least 3.2.7. I'm at 3.2.4 right now. 

Thanks
