### ISSUE TITLE
@storybook/react-native is not installed when using getstorybook

### ISSUE THREAD

**Issue by mymachine8** [storybooks/storybook#1738]
I followed the below steps,

1. npm -g i @storybook/cli
2. went to the project directory and ran getstorybook
3. now when I try to do, npm run storybook it is throwing me an error 
> storybook start -p 7007 
>sh: storybook: command not found

version: 
<img width="550" alt="screen shot 2017-08-25 at 5 08 49 pm" src="https://user-images.githubusercontent.com/7432847/29712560-1eb936f8-89b8-11e7-8c7a-cdd914b085ea.png">
storybook/cli@3.2.8

**Comment by danielduan** [comment]
try using `yarn run storybook`.

My guess is, you're probably running an older npm version. older versions of npm don't support executing a bin from the local node_modules install.

**Comment by mymachine8** [comment]
manually installing, `npm install --save @storybook/react-native` fixed my issue. Some how this library is not added in my package.json when I ran ` getstorybook`

**Comment by danielduan** [comment]
Think this is a bug. Looks like `@storybook/react-native` isn't added during `getstorybook`.

https://github.com/storybooks/storybook/blame/master/lib/cli/generators/REACT_NATIVE/index.js#L12

**Comment by ndelangen** [comment]
@mymachine8 Do you think you could open a PR for this? It would help a lot of people out actually!

**Comment by shilman** [comment]
I fixed this and released it in [v3.2.9](https://github.com/storybooks/storybook/releases/tag/v3.2.9). Sorry for the hassle!
