### ISSUE TITLE
Specific deep link options

### ISSUE THREAD

**Issue by vgpena** [storybooks/storybook#1739]
My project team has been using Storybook to, among other things, share dev progress with designers and project managers. Being able to send each other URLs deep linked to stories has been really useful.

It would be great to expand this utility to create per-story buttons that copy specific URLs to the clipboard:
- fullscreen deep link (handy for project managers to quickly review)
- hide components list, but show knobs panel (handy for devs/designers to confirm specific behavior)

To riff off of #1680, having knobs in the URL is handy for calling attention to specific states, but a button for "current story with default knobs" would also be handy for checking the base state.

**Comment by shilman** [comment]
@vgpena I think there are a couple different aspects to this issue:
1. functionality to be able to link to a particular state
2. UI for how to do that

Disregarding the UI for a minute, I believe the functionality you're asking for already exists, but may not be easy to find. You can click on the "CMD" button in the upper left corner to see the keyboard shortcuts:

<img width="674" alt="storybook" src="https://user-images.githubusercontent.com/488689/29739451-e8418306-89f2-11e7-8ef2-059c96c54c98.png">

Then you can toggle the confusingly-named "left" and "down" panels as needed (which will be made less confusing in https://github.com/storybooks/storybook/pull/1692). This will also change the URL accordingly.

By jumping through these hoops, I think you can get all the functionality you want. Can you confirm this?

Back to the UI, there have also been attempts to add UI for setting these options (PR here: https://github.com/storybooks/storybook/pull/981, demo here: https://usulpro.github.io/storybook-ui/)

This can obviously use some design work, but I'm curious how close this all gets to satisfying your use case. Feedback welcome!

**Comment by UsulPro** [comment]
My two cents to this:
Knobs panel has "Reset" button which sets all knobs to the default values and changes the URL appropriately. Isn't it same as you asking for
> "current story with default knobs"

**Comment by Hypnosphi** [comment]
> Knobs panel has "Reset" button

Let’s make it a link (using `RoutedLink` from `@storybook/components`)

**Comment by morgs32** [comment]
@Hypnosphi What's this you speak of? Is there any documentation of RoutedLink

**Comment by Hypnosphi** [comment]
It's an internal component, used in menu, for example. Basically, it's a native html link with changed behaviour on plain left click

**Comment by morgs32** [comment]
Is there any way to reset knobs from within the iframe? From within a decorator for example?
