### ISSUE TITLE
linkTo another story error

### ISSUE THREAD

**Issue by darul75** [storybooks/storybook#174]
Hi guys,

I try to figure out what can produce that error when clicking a button with a specific handler to switch to another named story:

`page_bus.js?147f:40 Uncaught Error: dataId is not supplied via queryString`

```
const props = {
    handleSignIn: function() {
      linkTo('Tab', 'empty');
    }
  }
};

storiesOf('Login', module)
  .add('empty', () => (
    <Login {...props} />
));
```

**Comment by darul75** [comment]
well, it was due to my handler

```
const props = {
  handlers: {
    handleSignIn: function() {
      action('login');
    }
};
```

instead of

```
const props = {
  handlers: {
    handleSignIn: handleSignIn: action('login')
  }
};
```

**Comment by arunoda** [comment]
@darul75 Try this:

```
const props = {
    handleSignIn: linkTo('Tab', 'empty'),
  }
};
```

Then it'll work.

**Comment by darul75** [comment]
ok fine, thx

**Comment by darul75** [comment]
Hi,

I have tried but result is still the same

<img width="1158" alt="capture d ecran 2016-05-09 a 21 07 27" src="https://cloud.githubusercontent.com/assets/2134003/15124830/247aa37c-162a-11e6-9189-1c7254d76853.png">

linkTo is giving error and action dump to console but trigger same error

**Comment by arunoda** [comment]
Okay. I'll have look at them do a fix if we can ASAP.

**Comment by arunoda** [comment]
This seems not like a linkTo issue. But something else, if there anyway you can provide a repo where we can reproduce this issue.

**Comment by darul75** [comment]
first thanks for giving feedback quickly, I need to extract and reproduce the case in a small repo as I am not allowed to share it with you.

**Comment by RajnishDashora** [comment]
+1

**Comment by necolas** [comment]
We're having the same issue after updating from 1.x to 2.3.0

**Comment by arunoda** [comment]
@necolas Interesting.
I'll do a test and see what's going on here.
May be we'll remove `HtmlWebpackPlugin` if it exists. Since it has no effect when used with storybook.

**Comment by necolas** [comment]
I think this was just a case of my mistake :)

**Comment by Ne-Ne** [comment]
I am getting the same issues when using it with setState in react:

### Problem
This is just a quick example, a button is clicked. `isLoading` a boolean state for react component overlay. Complete `1500` millisecond delay then it should fire `linkTo()` however it does not work...

```
handleContinueButton = () => {
    this.setState(
      {
        isLoading: true,
      },
      () => {
        setTimeout(() => {
          this.setState(
            {
              isLoading: false,
            },
            () => linkTo('section_1', 'section_1_2')
          );
        }, 1500);
      }
    );
  };
```

### Button origin
```
<Button onClick={this.handleContinueButton} fluid primary size="large" content="Continue" />
```

Any ideas?

**Comment by ndelangen** [comment]
`linkTo('section_1', 'section_1_2')` returns a function that when called, will navigate.

`linkTo('section_1', 'section_1_2')()` will navigate.
