### ISSUE TITLE
Vuejs: the stories are executed twice

### ISSUE THREAD

**Issue by miljan-aleksic** [storybooks/storybook#1742]
Hi, I detected my components are executed twice, at least when using Vuejs (didn't try with React). I am testing with latest 3.2.8 version. To reproduce just create a simple story like this:

```
<script>
export default {
  created () {
    console.log('should execute once')
  }
}
</script>
````

The component above should be inited once, but is done so twice. Can anyone try and confirm this issue?

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

I could not reproduce it.
Could you provide the reproduction repo please?

**Comment by miljan-aleksic** [comment]
Hi @kazupon!

Nothing extra in my configuration, I used the CLI and added the created method. I did notice that this happen only on first init, so only when refreshing the browser page manually, it doesn't happen when switching to another story.

Anyway, here is the test repo https://github.com/miljan-aleksic/test-storybook. Switch to MyButton story, refresh the page and check the console.log. Tested with Chrome.

**Comment by kazupon** [comment]
@miljan-aleksic 
Thank you for your feedback!

I checked it. it's bug.
I'll try to fix it later.

**Comment by mikemahony** [comment]
Call me crazy but this seems to have regressed? I just ran the above steps to reproduce (from the fix #1983), this time on `6.2.0-alpha.8` (`next`), and I'm getting `call created hook` twice per storybook page load... 

https://user-images.githubusercontent.com/1740063/102585807-e03ca700-40bd-11eb-8f27-d052c298e52e.mov

**Comment by jowilhnson** [comment]
Changing props via the Controls add-on seems to be triggering multiple updates as well.

**Comment by mikemahony** [comment]
Hi @kazupon and @miljan-aleksic, would you please consider re-opening this issue for us?  Thank you in advance!

**Comment by donotlb** [comment]
I encountered the same problem, and i found that the story will be called twice if the args of story function is present.

```js
export const MyStory1 = (args) => ({ ... }) // => story will be called twice

export const MyStory2 = () => ({ ... })     // => story will be called once
```

storybook version (@storybook/vue): 6.0.26

**Comment by bl-nkd-v** [comment]
Bumping this, seeing the same behavior in 2023
