### ISSUE TITLE
Do a proper full test of CLI in CI

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#1746]
We've had some regressions in the @storybook/cli package lately.

This is a clear signal we need proper tests that cover this behavior.

I would love for someone with great testing skills to add a script that properly tests the CLI.

I envision we have some basic fixtures of possible projects. Much like how [lerna has fixtures for their commands](https://github.com/lerna/lerna/tree/master/test/fixtures)
And then we run the CLI on it, and expect the output to match a snapshot.

**Comment by ndelangen** [comment]
Looking for someone who wants to pick this up!

**Comment by Hypnosphi** [comment]
In case of CRA/CRNA templates, we should also check that things work with current version of the boilerplate (see your [concern](https://github.com/storybooks/storybook/pull/1647#issuecomment-324149958)). In that case we can't use snapshots as they will change because of external reasons

**Comment by Hypnosphi** [comment]
Alternatively, we could add `create-react[-native]-app` as `devDependencies` and run them before each test on CI. Whenever those packages update, we'll get a PR from greenkeeper bot

**Comment by ndelangen** [comment]
I like that idea @Hypnosphi

**Comment by Hypnosphi** [comment]
I'm not sure though that greenkeeper can track non-root package.json

**Comment by Hypnosphi** [comment]
Unfortunately, not: https://github.com/greenkeeperio/greenkeeper/issues/139
So maybe we should consider alternatives

**Comment by ndelangen** [comment]
Greenkeeper may not be able to help us there, but it's not like we're without hope.

We can can implement our own helpers to stay up to date.

**Comment by Hypnosphi** [comment]
Or we can just use current versions, but make cli build non-required

**Comment by Hypnosphi** [comment]
Fixed with #1767
