### ISSUE TITLE
Some components seem to trigger an infinite loop in render function in Vue

### ISSUE THREAD

**Issue by mattrothenberg** [storybooks/storybook#1747]
Hey, thanks for building such an awesome project! Stoked that we Vue.js developers can finally take advantage of it.

I ran into the following issue when trying to use the `knobs` addon.

Assuming I have a template marked up thusly:

```
<div>{{username}}</div>
```
And a Vue component with a `computed` property marked up thusly:
```
username () {
  return text('Username', 'mattrothenberg')
},
```

My console inevitably blows up with the following error.
![screen shot 2017-08-27 at 10 53 18 am](https://user-images.githubusercontent.com/5148596/29750901-f79687f6-8b15-11e7-8bc1-82814c3ed90b.png)

The documentation around Vue.js + Storybook is pretty sparse. Is this the right pattern to be following?

**Comment by ndelangen** [comment]
I have seen this happen, but I haven't been able to pinpoint why or how this happens.

If someone could help debug this?

🤗

**Comment by mattrothenberg** [comment]
@ndelangen I'll put together a sample repository :)

**Comment by mattrothenberg** [comment]
@ndelangen https://github.com/mattrothenberg/storybook-test

As it turns out, I wasn't totally accurate in my initial diagnosis of the problem. I only started seeing the infinite loop error after pulling in a particular component from my favorite Vue UI library, [Element UI](http://element.eleme.io/#/en-US/component/select).

It appears that simply adding this particular component to the `template` causes the error.

```
<el-select v-model="value" placeholder="Select">
  <el-option
    v-for="item in options"
    :key="item.value"
    :label="item.label"
    :value="item.value">
  </el-option>
</el-select>
```
[Test Repository](https://github.com/mattrothenberg/storybook-test)

[Video demonstrating the error](https://streamable.com/m8crb)

Let me know if that helps!

**Comment by rndmerle** [comment]
Same issue with md-menu component of vue-material library.

**Comment by rndmerle** [comment]
Are you sure you don't still have a `addDecorator(withKnobs)` in config.js ?
Because I've that kind of loop with md-menu component from vue-material lib, but it's totaly linked to the inclusion of the knobs decorator.

**Comment by mattrothenberg** [comment]
@rndmerle You're right, removing that `addDecorator` "resolves" the issue I articulated.

**Comment by ndelangen** [comment]
I know @kazupon added some code to make addDecorator work for vue?

What could cause an infinite render in Vue?

**Comment by mattrothenberg** [comment]
Any call to `vm.$forceUpdate()` poses the risk of funny business
