### ISSUE TITLE
specify storybook path

### ISSUE THREAD

**Issue by xareelee** [storybooks/storybook#1748]
I have multiple React Native apps in one monorepo:

```
monorepo/
 |-- package.json
 |-- apps/
      |-- FirstReactNativeApp/
      |     |-- storybook
      |-- SecondReactNativeApp/
      |     |-- storybook
```

when I use `yarn storybook`, it search and use the scripts in my `package.json`:

```json
{
  "scripts": {
    "storybook": "storybook start -p 7007",
  }
}
```

but it shows errors in my console:

```
Scanning 1106 folders for symlinks in {path_to_root_project}/node_modules (19ms)

React Native Storybook started on => http://localhost:7007/

Scanning 1106 folders for symlinks in {path_to_root_project}/node_modules (25ms)

ENOENT: no such file or directory, stat '{path_to_root_project}/storybook'

webpack built 9c91edb89274e4fcca8d in 2967ms
```

How can I specify the path to the `storybook/` folder I want to pack and launch?

For example:

```
// for first app
storybook start -p 7007 --folder apps/FirstReactNativeApp/storybook

// for second app
storybook start -p 7007 --folder apps/SecondReactNativeApp/storybook
```

**Comment by danielduan** [comment]
you can set your `package.json` in `apps/FirstReactNativeApp` to do `storybook start -p 7007`. same with the other app.

then in your root `package.json`, you can have something like
```
scripts: {
  start-storybook-a: 'cd apps/FirstReactNativeApp && yarn storybook',
  ...
}
```

**Comment by xareelee** [comment]
I use [lerna](https://github.com/lerna/lerna) for monorepo. I install `storybook` in the root `package.json` for all projects, not app's `package.json`.

```
monorepo/
 |-- package.json                    ## add storybook devDependency here
 |-- apps/
      |-- FirstReactNativeApp/
      |     |-- package.json
      |     |-- storybook
      |-- SecondReactNativeApp/
      |     |-- package.json
      |     |-- storybook
```

When I ran `yarn storybook` to execute the npm script `storybook start -p 7007` under an app project, it doesn't find the storybook command in the `node_modules` of that app project.

**Comment by danielduan** [comment]
You should be using lerna to start storybook then:
https://github.com/lerna/lerna#run

`lerna run --scope FirstReactNativeApp storybook` or whatever you have your different apps named
