### ISSUE TITLE
Addons require `react` peer dependencies for Vue Storybook

### ISSUE THREAD

**Issue by sky790312** [storybooks/storybook#1751]
I use vue with stoyrbook and want to add more addons like centered, noted..etc.
I follow the step to install:
https://www.npmjs.com/package/@storybook/vue
Then I get default addons 'actions' and 'links' and example.
But when I want to install other addons, It fails without react dependency

```
yarn add @storybook/addon-centered --dev
yarn add v0.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "react@*".
error An unexpected error occurred, please open a bug report with the information provided in "/project path/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

https://github.com/storybooks/storybook/blob/afeebe035814193a9d970b6b613236b08eda2519/addons/centered/README.md

How to resolve the dependency's problem?

**Comment by danielduan** [comment]
You can install the react package in the root directory of your project where `@storybook/vue` is installed.

I wonder if we should also include that in the documentation and cli to automatically install `react` for the other platforms as well.

**Comment by Hypnosphi** [comment]
Why do addons even have a peerDependency on react?

**Comment by Hypnosphi** [comment]
Related: https://github.com/yarnpkg/yarn/issues/2688

**Comment by Hypnosphi** [comment]
@sky790312 By the way, looks like you're using an outdated version of yarn. Unmet peer dep should be just a warning, not an error

**Comment by Hypnosphi** [comment]
> but maybe we should change it to peer and add React as a direct devDpendency of the app in CLI (because it will be used from app package)

Actually it isn't used in stories code, so it should be left as is.
