### ISSUE TITLE
Add Atlassian to Homepage examples

### ISSUE THREAD

**Issue by nk8** [storybooks/storybook#1757]
Atlassian's AtlasKit is the best implementation of Storybook I've seen yet. It definitely deserves to be added to the homepage, maybe under "Used by these fine folks"

https://atlaskit.atlassian.com/components

**Comment by danielduan** [comment]
I don't think it's storybook under the hood. Looks like a custom framework they built with some design cues from Storybook and other similar projects.

**Comment by nk8** [comment]
Hmm... any idea why they have the Storybook link and versioning dropdown at the top right? Maybe they are exporting to Storybook?

Thanks for the clarification @danielduan.

![atlas](https://user-images.githubusercontent.com/1020686/29794289-3fac271c-8bfc-11e7-8912-0472c82fb527.PNG)

**Comment by danielduan** [comment]
Oh I completely missed that! Yeah that linked page from the versions is definitely Storybook, but not the AtlasKit part with the blue styling.
