### ISSUE TITLE
nuxtjs support/setup?

### ISSUE THREAD

**Issue by uptownhr** [storybooks/storybook#1759]
Anyone have experience getting storybook to work on a nuxtjs project? https://github.com/nuxt-community/modules/issues/127

**Comment by danielduan** [comment]
Take a look at the vue.js project and see if you can get it working. I don't know that anyone's tried it yet. Please report back on your progress.

**Comment by uptownhr** [comment]
will do!

**Comment by husayt** [comment]
https://davidwalsh.name/storybook-nuxt

**Comment by sobolevn** [comment]
https://github.com/howdy39/nuxt-storybook-element-boilerplate
