### ISSUE TITLE
addon-info: Component.__docgenInfo not defined.

### ISSUE THREAD

**Issue by konsumer** [storybooks/storybook#1762]
I can't get the "description" field to show up in the PropType table in my project. I worked on #1030 with @bigassdragon and we had it working when all was done.

I tried with both methods to add info, and `.__docgenInfo` is undefined in both.

I did this in my config.js:
```js
import { configure, setAddon } from '@storybook/react'
import infoAddon from '@storybook/addon-info'

setAddon(infoAddon)

window.STORYBOOK_REACT_CLASSES = {}

function loadStories () {
  require('../src/stories')
}

configure(loadStories, module)
```

and made stories that looked like this:
```js
import React from 'react'

import { storiesOf } from '@storybook/react'
import { withInfo } from '@storybook/addon-info'

import Docs from './Docs'

storiesOf('Docs', module)
  .add('withInfo', withInfo('Heading here')(() => (<Docs name='David' />)))
  .addWithInfo('addWithInfo', 'Heading here', () => (<Docs name='David' />))
```

and `Docs.js` looks like this:
```js
import React from 'react'
import PropTypes from 'prop-types'

/** A dumb component that says "hello" */
export const Docs = ({name}) => (<div>Hello {name}</div>)

Docs.propTypes = {
  /** the name of the person to say "hello" to */
  name: PropTypes.string
}

Docs.defaultProps = {
  name: 'World'
}

export default Docs
```

I tried `class Docs extends React.Component` style, too.

Still no "description" field in either story:
<img width="569" alt="screen shot 2017-08-28 at 5 37 06 pm" src="https://user-images.githubusercontent.com/83857/29799288-94329c2e-8c17-11e7-9a26-fbe444097c35.png">

<img width="565" alt="screen shot 2017-08-28 at 5 41 47 pm" src="https://user-images.githubusercontent.com/83857/29799402-37a23f68-8c18-11e7-988b-daa513108199.png">

steps to reproduce:

```
npm i -g create-react-app @storybook/cli
create-react-app demo
cd demo
getstorybook
npm i -D @storybook/addon-info
```

Then I made changes, above.

**Comment by konsumer** [comment]
I am pretty sure this is caused by react-docgen not being setup like it used to be. If I manually add my own `__docgenInfo`, it displays correctly:

```js
Docs.__docgenInfo = {
  'description': 'A dumb component that says "hello"',
  'methods': [],
  'props': {
    'name': {
      'type': {
        'name': 'string'
      },
      'required': false,
      'description': 'the name of the person to say "hello" to',
      'defaultValue': {
        'value': "'World'",
        'computed': false
      }
    }
  }
}
```
<img width="641" alt="screen shot 2017-08-29 at 12 30 26 am" src="https://user-images.githubusercontent.com/83857/29809513-4dc93588-8c51-11e7-9bfe-c5a6d94f293a.png">

**Comment by ndelangen** [comment]
@danielduan Did this change recently?

**Comment by konsumer** [comment]
Honestly, I haven't really looked at it since it was working when I worked on it with @bigassdragon. I think it could be related to the move from @kadira to @storybook, but I'm not sure. If I look at the webpack config (in a custom config function) I don't see any of the react-docgen stuff I might expect, but I don't know what it used to look like.

**Comment by danielduan** [comment]
You actually don't need `window.STORYBOOK_REACT_CLASSES = {}` in your `config.js`. It got moved inside the package at some point.

I'm guessing that might have cleared the docgen info.

**Comment by konsumer** [comment]
I tried it without, too.

**Comment by danielduan** [comment]
If you're using a custom webpack config, make sure that you're importing the storybook defaults as well. We've changed a good amount of the Webpack between v2 and now, you might not need a custom webpack file unless you're adding additional loaders.

The webpack config gets read here:
https://github.com/storybooks/storybook/blob/master/app/react/src/server/config.js
And the babel config then gets injected with docgen here:
https://github.com/storybooks/storybook/blob/master/app/react/src/server/babel_config.js

**Comment by konsumer** [comment]
No custom config (although I did try it with one.) [Here](https://github.com/konsumer/storybook_issue_1762) is a project that demonstrates the issue. As I said, it's pretty much just a plain cerate-react-app with getstorybook.

**Comment by danielduan** [comment]
`export const Docs = ({name}) => (<div>Hello {name}</div>)` doesn't work unfortunately.

If you delete `export`, it should be okay. It's a bug in https://github.com/storybooks/babel-plugin-react-docgen/issues/33

**Comment by konsumer** [comment]
Yep, that fixed it. Thanks for the help! It's a bit frustrating though, because I like to export the Component (for unit-testing and storybook) and export the react-redux-wrapped version (for actual use in my application.) I generally do it like this:


```js
import React from 'react'
import { connect } from 'react-connect'

import PropTypes from 'prop-types'

/** A dumb component that says "hello" */
const Docs = ({name}) => (<div>Hello {name}</div>)

Docs.propTypes = {
  /** the name of the person to say "hello" to */
  name: PropTypes.string
}

Docs.defaultProps = {
  name: 'World'
}

export const mapStateToProps = state =>({})

export default connect(mapStateToProps)(Docs)
```
I'll take a look and submit a PR over at babel-plugin-react-docgen. Thanks again!

**Comment by danielduan** [comment]
Yeah, you can export it after as a workaround

Something like
```
export default Docs
export { Docs }
```

**Comment by konsumer** [comment]
Thanks!

**Comment by konsumer** [comment]
I made a [PR to change the behavior of the resolver](https://github.com/reactjs/react-docgen/pull/214#issuecomment-326797972) but as @danez pointed out, the resolver [is actually configurable](https://github.com/reactjs/react-docgen#cli), and there are a few built in (maybe `findAllComponentDefinitions ` does what I want?) I propose that we that as the default, instead. I like the idea of the default storybook doc-resolver grabbing all the exported stuff, but then using it's own "this is what this story is about" resolution to pick out the right doc object to actually show. I will do some experimentation with this and come back with a PR, if people like this idea.

**Comment by danielduan** [comment]
Think it's a good idea, let's keep the conversation in the other issue for the babel plugin.
