### ISSUE TITLE
ModuleBuildError Unknown plugin

### ISSUE THREAD

**Issue by wojciech-bilicki** [storybooks/storybook#1765]
Tried to use storybook with webpack configuration. No good.

` [ ModuleBuildError: Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/mac/Development/MarvelApp/node_modules/react-inspector"`

`ModuleBuildError: Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/mac/Development/MarvelApp/node_modules/react-modal"`

`ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "/Users/mac/Development/MarvelApp/node_modules/react-treebeard/.babelrc"`

So on and so forth.

_.storybook/.babelrc_

`{
  "extends": "../.babelrc"
}`

_.storybook/webkack.config.js_

```
require('babel-register');

const config = require('../webpack.config.js');

module.exports = {
  plugins: config.plugins.filter(plugin =>
    ['DefinePlugin', 'ProvidePlugin', 'ExtractTextPlugin'].includes(
      plugin.constructor.name
    )
  ),
  devtool: 'source-map',
  resolve: config.resolve,
  module: {
    loaders: config.module.loaders,
    rules: config.module.rules
  }
};
```

**Comment by danielduan** [comment]
in your custom `.babelrc` file, you might have to list `require.resolve('babel-preset-es2015')` instead of just `'es2015'`

**Comment by wojciech-bilicki** [comment]
Ok, what actually helped was adding "es2015" to the .babelrc in a root directory. and running:
`npm install --save-dev babel-preset-es2015`

Storybook is great :)
