### ISSUE TITLE
Notes Typo on Examples

### ISSUE THREAD

**Issue by Ethaan** [storybooks/storybook#1766]
So after looking at this for a while, seems like there is a typo on the [VueJS Examples (atleast)](https://github.com/storybooks/storybook/blob/master/examples/vue-kitchen-sink/src/stories/index.js), with the Notes stories.

one note example for the `html` is being written like.

`withNotes({ notes: 'note' })` using `notes` as parameter instead of `text`, this break things, is this intended or something from older versions? (been using Storybook for like 3 days), wanna checkout before making a PR to correct this.

**Comment by Hypnosphi** [comment]
Yeah, definitely a bug. Please replace it with `withNotes('note')` and find other wrong usages, if any
