### ISSUE TITLE
Add proper typescript webpack setup in readme

### ISSUE THREAD

**Issue by GeeWee** [storybooks/storybook#1778]
The current webpack typescript setup in the [readme:](https://storybook.js.org/configurations/custom-webpack-config/) is off. First off, it doesn't import path, and thus doesn't even run.

Secondly, it fails miserably, if the files in the '/stories/' folder is typescript, as it'sn ot listed in the include param.
A webpack config that works looks something like this:

```javascript
// load the default config generator.
const genDefaultConfig = require('@storybook/react/dist/server/config/defaults/webpack.config.js');
const path = require('path');

module.exports = (baseConfig, env) => {
	const config = genDefaultConfig(baseConfig, env);
	
	// Extend it as you need.
	
	// For example, add typescript loader:
	config.module.rules.push({
		test: /\.(ts|tsx)$/,
		include: [
			path.resolve(__dirname, '../src'),
			path.resolve(__dirname, '../stories'),
			],
		loader: require.resolve('awesome-typescript-loader'),
	});
	config.resolve.extensions.push('.ts', '.tsx');
	
	return config;
};

```

**Comment by danielduan** [comment]
Would you mind creating a PR for the documentation?

https://github.com/storybooks/storybook/blob/master/docs/pages/configurations/custom-webpack-config/index.md

**Comment by matt-erhart** [comment]
I hadn't even considered the docs were wrong until spending a bunch of time on this. Let's get this fixed asap. I can pr later if need be.

**Comment by GeeWee** [comment]
It'd be awesome if you did this - I've had it on my to do list for a while but I've been crazy busy

**Comment by danielduan** [comment]
closing this in favor of #3270
