### ISSUE TITLE
After resizing scroll focus is lost in Chrome.

### ISSUE THREAD

**Issue by mascardoso** [storybooks/storybook#1779]
When resizing the area through the grabber of the right panel or bottom panel the scroll in Chrome is lost and I'm unable to scroll down. Seems like a focus issue.

**Comment by Hypnosphi** [comment]
Related: https://github.com/tomkp/react-split-pane/issues/30#issuecomment-278782399

**Comment by Hypnosphi** [comment]
Fixed in `3.3.0-alpha.3`

**Comment by joe-strummer** [comment]
Just a little workaround for anyone not upgrading to the alpha yet.

If scrolling has frozen due to using the resize grabber in the middle, resizing the actual browser window will unfreeze it. I've been resizing the browser to test responsive design, which works fine.
