### ISSUE TITLE
"Error: Cannot read property 'state' of undefined"

### ISSUE THREAD

**Issue by kevinSuttle** [storybooks/storybook#178]
No errors in Webpack, none in React, none in the console. I can only surmise that Storybook doesn't like some data it's getting.

**Comment by arunoda** [comment]
Can I get more info about this? When this is happening? Any way I can test this out?

**Comment by kevinSuttle** [comment]
The example: 

![no idea](http://img1.rnkr-static.com/user_node_img/50013/1000240969/870/doing-science-photo-u1.jpg)

**Comment by arunoda** [comment]
Now this is fixed right? :)

**Comment by kevinSuttle** [comment]
Yeah totally.

**Comment by kevinSuttle** [comment]
Well, maybe. Not sure if this is Webpack, or Storybook. Error only appears in the Storybook UI, but nowhere else. 

<img width="1437" alt="screen shot 2016-05-11 at 1 38 05 pm" src="https://cloud.githubusercontent.com/assets/95672/15190408/b8e1e49a-177d-11e6-8473-f07567d8e915.png">

**Comment by kevinSuttle** [comment]
I feel like the URL has something to do with it.

**Comment by arunoda** [comment]
We had source maps supports in the error message. That package seems to give some weird errors on FF. So, we removed it.
We'll try to add it back in after they've fixed the issue.
Then we can easily find out the root cause of the error.

**Comment by kevinSuttle** [comment]
Thanks, I'm all of a sudden seeing this issue almost every time I refresh now. :/

**Comment by kevinSuttle** [comment]
Here's how I fix this locally: comment out the first story, let the browser refresh, uncomment, let the browser refresh. Works consistently.

**Comment by arunoda** [comment]
Can I have a sample repo for this issue. Then I can debug the issue.

**Comment by kevinSuttle** [comment]
_[Sent privately]_

**Comment by arunoda** [comment]
Working on this.

**Comment by ndelangen** [comment]
Please provide a reproduction path if you still experience this issue 👍
