### ISSUE TITLE
Storybook index.js isn't finding one of it's required modules 

### ISSUE THREAD

**Issue by klairetan** [storybooks/storybook#1784]
When I try to start my Meteor app, `@kadira/storybook/dist/client/index.js` throws an error because of 

`var _preview = require('./preview');`

and prints the error 

```
W20170901-15:47:28.108(-7)? (STDERR) Error: Cannot find module './preview'
W20170901-15:47:28.109(-7)? (STDERR)     at makeMissingError (packages/modules-runtime.js:221:12)
W20170901-15:47:28.111(-7)? (STDERR)     at require (packages/modules-runtime.js:231:19)
W20170901-15:47:28.111(-7)? (STDERR)     at meteorInstall.node_modules.@kadira.storybook.dist.client.index.js (packages/modules.js:800:16)
W20170901-15:47:28.114(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170901-15:47:28.115(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
```
?

I didn't see this in the past issues, and I was wondering if anyone might know what's causing this? The folder exists within `@kadira/storybook/dist/client/`.

**Comment by Hypnosphi** [comment]
`@kadira/storybook` is deprecated. Please upgrade to new packages:

```
npm install --global `@storybook/cli`
// run inside your project dir
getstorybook
```

Node 8 comes with a built-in `npx` module which allows to run packages without installing them globally, so you might want to use it instead:
```
npx -p @storybook/cli getstorybook
```

Please let us know if the problem still persists after upgrading

**Comment by klairetan** [comment]
Hello! Thanks for the suggestion! Unfortunately, I tried and the issue is still occurring. Storybook ran with the sample button/welcome files though once I inserted my component and added the Meteor-imports plugin, this error began popping up. But I'm not sure how those would interfere with the internal module/file imports in Storybook?

**Comment by klairetan** [comment]
Thanks for the instructions! Unfortunately, I updated to @storybook, and I'm getting a similar though slightly different error where `@storybook.addon-actions.dist.index.js` isn't able to find `./manager`. Any ideas?

**Comment by klairetan** [comment]
So i think it was a meteorInstall issue, and I was able to run the app once I added the node_modules in my packages.json to Dependencies and not just devDependencies.
