### ISSUE TITLE
doc on custom webpack - module.rules should be used instead of module.loaders

### ISSUE THREAD

**Issue by devdoomari** [storybooks/storybook#1785]
I just upgraded some old project, and my webpack loaders were mysteriously ignored.
Spent a few hours on this, and it seems that storybook's custom webpack config only looks at module.rules instead of module.loaders.

Should I update the docs to point this out?
Also, would it be nice to add some warnings (or throw exceptions), or do you think storybook should silently merge module.loaders into module.rules?

**Comment by Ethaan** [comment]
I might say i have the same issue for my `stylus` loader in the past, spend like 2hrs (no kidding) until i take a close look into the [SASS example ](https://storybook.js.org/configurations/custom-webpack-config/#extend-mode) for the extend-mode and then i see they where doing `storybookBaseConfig.module.rules.push` and everything just works normally, a good warning could be great here

**Comment by danielduan** [comment]
We'd love a PR to update the documentation for it 👍

**Comment by Hypnosphi** [comment]
Just note that those are breaking changes in webpack, not in storybook itself: https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules

**Comment by danielduan** [comment]
I misread the issue. Thought there was an issue in the documentation. It looks to be correct and uses `rules` instead of `loaders`.

https://storybook.js.org/configurations/custom-webpack-config/

Closing issue since this is a webpack, not storybook. Please reopen if there's still an issue.
