### ISSUE TITLE
🚨 unable to clone from github ( possible repository corruption on the remote side )

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#1786]
There seems to be a problem with our repository that prevents you from cloning it.

It would appear to be an issue on the remote (GitHub), so I've submitted a support-request via email:

![screen shot 2017-09-02 at 12 25 11](https://user-images.githubusercontent.com/3070389/29994846-f5c4a73c-8fd9-11e7-8b7d-4809b23ace01.png)

If you have a working clone locally, you can probably continue work (but not push).

if you do not yet have a working clone you can opt to wait until the problem is resolved, or if you're impatient, you can opt to download as a ZIP:
<img width="591" alt="screen shot 2017-09-02 at 12 29 42" src="https://user-images.githubusercontent.com/3070389/29994855-73f8c750-8fda-11e7-8e5c-f36ce4b86248.png">

**Please for the time be careful with work, make sure you have backup of important work.**

**Comment by Hypnosphi** [comment]
I believe it's fixed
