### ISSUE TITLE
Cannot find module 'libnpx/package.json'

### ISSUE THREAD

**Issue by mjhamm75** [storybooks/storybook#1798]
I am running the current version of storybook
`"@storybook/react": "^3.2.8",`
with React 16
`"react": "^16.0.0-beta.5",`
`"react-dom": "^16.0.0-beta.5",`
And RR4
`"react-router": "^4.1.2",`
 `"react-router-dom": "^4.1.2",`

Here is the full error I get when I try to start storybook
```> npx start-storybook -p 9900 -c .storybook

@storybook/react v3.2.8

=> Loading custom .babelrc
Cannot find module 'libnpx/package.json'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lcrf-fe@2.0.0-alpha.0 storybook: `npx start-storybook -p 9900 -c .storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lcrf-fe@2.0.0-alpha.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mjhamm75/.npm/_logs/2017-09-05T21_38_49_679Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lcrf-fe@2.0.0-alpha.0 sb: `npm run storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lcrf-fe@2.0.0-alpha.0 sb script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mjhamm75/.npm/_logs/2017-09-05T21_38_49_702Z-debug.log
```

My app runs outside of storybook.  When I use React 15 with RR3, then I can run storybook without an issue.

I did an `npm install libnpx`, which then lead to the same message, but with a different lib that was missing, which was `npm`.  As I tried to install the missing modules, I just kept getting more missing modules.

**Comment by ndelangen** [comment]
Sounds like something went wrong during npm install, we have no dependency on libnpx anywhere AFAICS.

I have no idea where to start with this one. 😞

**Comment by mjhamm75** [comment]
I was trying to stay up to date and use npx, which is where the dependency
for libnpx comes from.  I removed all references/uses of npx and I am back
up and running.  This was not a storybook issue.  Sorry for the bother.
