### ISSUE TITLE
How to connect storybook to external database?

### ISSUE THREAD

**Issue by husayt** [storybooks/storybook#1805]
We have an external database which we store information for our internal stroybook addon. We would like to use storybook's own getDatabase mechanism to store there and connect to our database via setDatabase. This way all addons will be using the same database.

Is this currently supported?

**Comment by ndelangen** [comment]
The database stuff from Storybook 2 is currently 'on hold' for Storybook 3.

Persistence of settings and data will become a topic in the future and then we will revisit this.
We're not sure if the storybook database apis will remain in the future. 
Currently we've left them in, but to our knowledge nothing is using them.

If you want to connect your stories/components to an outside datasource, you'll have to write an addon or decorator:
https://storybook.js.org/addons/writing-addons/#docs-content

I hope this helps.
