### ISSUE TITLE
A linkTo which generates textual links?

### ISSUE THREAD

**Issue by pelotom** [storybooks/storybook#1808]
For components that require textual `href` props, it would be nice to be able to inject links that lead to other stories, a la `linkTo`. Is there a `linkToPath` or something that could generate a path instead of a callback?

**Comment by Hypnosphi** [comment]
I think we should use `RoutedLink` from `@storybook/components` in links addon, plus export a function returning hrefs

**Comment by pelotom** [comment]
That would be awesome!

**Comment by pelotom** [comment]
This was resolved by #1829.
