### ISSUE TITLE
Change ReactDOM container target

### ISSUE THREAD

**Issue by tomasfrancisco** [storybooks/storybook#1812]
I was trying to setup the `storybook` on an existing React project, and I notice that `storybook` is expecting the `container` for `ReactDOM`
```
ReactDOM.render(
  element,
  container,
  [callback]
)
```
to be `id='root'` instead of something else. Actually on the existing application that I have, it was using `id='app'` and then I was forced to change it to `id='root'`.
So I want to ask if is there any way to change it for the `storybook`  accordingly to each project instead of changing it on the existing project?

**Comment by Hypnosphi** [comment]
Storybook is built as a separate React app, so it shouldn‘t interfere with your application setup.

How does your storybook setup look like?

**Comment by tomasfrancisco** [comment]
Hmm I was sure that I was getting an error complaining that somehow the storybook was expecting `root` on my applications, and then I changed it and it started working. Today I moved back to my original id and it works. Well... It's working, don't know what I did differently. 

Closing the issue since it's not an issue anymore. Thanks for your time @Hypnosphi .
