### ISSUE TITLE
Setting knob values via URL does not work with iframe.html

### ISSUE THREAD

**Issue by darkartur** [storybooks/storybook#1813]
We are using backstopJS for css regression testing via iframe.html

And we want to cover some specific knobs combination but we can't specify knobs values without GUI

**Comment by Hypnosphi** [comment]
Well, there are no knobs in iframe. You can try index.html in fullscreen mode (full=1)

**Comment by darkartur** [comment]
@Hypnosphi thank you for your answer!

I guess solution that you suggest uses iframe tag. Iframe works badly in PhantomJS why not apply knobs via Iframe? I can make PR if u allow

**Comment by Hypnosphi** [comment]
You‘re welcome to give try (please base on `release/3.3` branch)

**Comment by Hypnosphi** [comment]
Please note that PhantomJS project has an unclear future: https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE

Latest release is more then year and a half ago

**Comment by darkartur** [comment]
@Hypnosphi Thank you for your advice. Phantom works nice in full screen mode, I guess there is no issue with iframes. But today I've found nice project https://loki.js.org/ and it is using iframe.html https://loki.js.org/ so I think this issue is still actual cuz I'm going to implement knobs testing there

**Comment by evexoio** [comment]
@darkartur any updates on this?

**Comment by rndmerle** [comment]
Afaik, in SB 4, setting knobs from the URL is no longer supported even from index.html.

**Comment by darkartur** [comment]
> Afaik, in SB 4, setting knobs from the URL is no longer supported even from index.html.

I'm sad to hear that

**Comment by Hypnosphi** [comment]
You can read the query parameters directly from current URL and use them as prop values or even as default knob values
