### ISSUE TITLE
Collapse certain panels by default?

### ISSUE THREAD

**Issue by brandondurham** [storybooks/storybook#1817]
Is it currently possible to include but collapse certain panels by default?

**Comment by ndelangen** [comment]
You can pick which panel you want open by default (globally) by importing them in the order you want to show them in `addons.js`.

**Comment by brandondurham** [comment]
Sorry… I’m referring to the _down panel_ and _left panel_. I would love to have to _down panel_ included but collapsed (⌘ ⇧ D) by default.

Possible?

**Comment by shilman** [comment]
@brandondurham yes, you can do this using `@storybook/addon-options`:

```
setOptions({
  showDownPanel: false,
})
```

https://www.npmjs.com/package/@storybook/addon-options

**Comment by brandondurham** [comment]
I’m an idiot. I have that installed and tried this setting, but for reason thought it removed it altogether.

Thanks for taking the time.
