### ISSUE TITLE
[storyshots] better document `test: snapshotWithOptions(...)` for mocking refs

### ISSUE THREAD

**Issue by tvald** [storybooks/storybook#1820]
It took quite a bit of searching and code diving through multiple frameworks to resolve callemall/material-ui#7710.

It would be helpful to explicitly mention in the README that it's necessary to mock refs and also link to [the example](https://github.com/storybooks/storybook/blob/master/examples/cra-kitchen-sink/src/storyshots.test.js) buried within the kitchen sink test.

Concise example:
```
initStoryshots({
  ...
  test: snapshotWithOptions({
    createNodeMock: () => ({ /* provide whatever DOM APIs you need here */ }),
  }),
})
```

Documentation:
[README.md#test](https://github.com/storybooks/storybook/blob/master/addons/storyshots/README.md#test)
[README.md#snapshotwithoptions](https://github.com/storybooks/storybook/blob/master/addons/storyshots/README.md#snapshotwithoptionsoptions)
[React ref mocking](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing) (`createNodeMock()`)

Related issues: #876, #886

**Comment by danielduan** [comment]
@tvald you are more than welcome to open a pull request to add these. We would very much appreciate it.

**Comment by javidjamae** [comment]
I created a PR for this: #2869
