### ISSUE TITLE
how do you enable withKnobs as a global?

### ISSUE THREAD

**Issue by fourcolors** [storybooks/storybook#1821]
I can't seem to get this to work globally?

**Comment by igor-dv** [comment]
Do you have these files configured:

`config.js`

```js
import { addDecorator } from '@storybook/react';
import { withKnobs } from '@storybook/addon-knobs';

addDecorator(withKnobs);
```

`addons.js`
```js
import '@storybook/addon-knobs/register'
```

**Comment by coreylight** [comment]
Not working for me either, I see the knobs pane but nothing in it. Have the `config.js` and `addons.js` as noted.

**Comment by igor-dv** [comment]
Can you please share an example of the story file where you want to use knobs ?

**Comment by coreylight** [comment]
Pretty simple stuff:
```jsx
import React from 'react';
import { storiesOf } from '@storybook/react';

import Avatar from './index';

const stories = storiesOf('Avatar', module);

stories.add('coreylight@gmail.com', () => {
  return <Avatar email="coreylight@gmail.com" />;
});
```

**Comment by coreylight** [comment]
Perhaps I'm assuming that the decorator will simply enable all component props as knobs? If this isn't true, is it something that can be accomplished?

**Comment by igor-dv** [comment]
There is a smart knobs addon that does this: https://github.com/storybooks/addon-smart-knobs
Otherwise you need to define each property separately: https://github.com/storybooks/storybook/tree/master/addons/knobs

**Comment by coreylight** [comment]
Great! Thanks @igor-dv, I'll look into it.
