### ISSUE TITLE
storybook-preview-iframe does not appear in Firefox Mobile v8.3 (5826)

### ISSUE THREAD

**Issue by joetidee** [storybooks/storybook#1822]
The storybook-preview-iframe simply does not appear when Storybook is viewed in Firefox mobile v8.3 (5826). I have to select 'Request Desktop Site' from Firefox setting in order for Storybook to work correctly.

**Comment by danielduan** [comment]
Can you attach a screenshot?

**Comment by joetidee** [comment]
![img_0001 1](https://user-images.githubusercontent.com/8842431/30491370-fa101ba4-9a34-11e7-9927-688a9fb9dbca.png)

**Comment by danielduan** [comment]
Definitely looks like a bug. If you'd like to look into it and submit a PR, you are more than welcome to. I personally don't have an iPad but I'm sure someone around here does.
