### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by Zevgart** [storybooks/storybook#1823]
I have a problem with brackets. I can install extension to brackets but I can't use it. I open  developer tools but i don't understand this problem. Console show me this all the time.

Uncaught SyntaxError: Unexpected token < file:///C:/Users/:1

**Comment by Zevgart** [comment]
![untitled](https://user-images.githubusercontent.com/22613740/30223430-1c91a748-94cb-11e7-859c-ec7b5cb9d92c.png)

**Comment by UsulPro** [comment]
@Zevgart Looks like you have a problem with some `brackets` extension on Windows OS. Are you sure it's related to the Storybook project? As I know we don't have any brackets extensions yet.

If you need help with running Storybook on Windows with Brackets feel free to connect with me in our slack, possible we can figure out it together
