### ISSUE TITLE
No LiveReload on completely fresh CRNA + storybook.

### ISSUE THREAD

**Issue by deehuey** [storybooks/storybook#1838]
Hey there, I've followed a guide to set up a brand new CRNA and storybook environment.

After running `getstorybook` in a fresh CRNA, and changing the App.js to

`export default from './storybook'`

I can see that my app is running, and i can view the emoji / "Hello Button" buttons, and see the actions and all, but if I change the button text to "Hello Buttonnnnnnnn" I'll see the "Hot loading..." notification on my phone, but it won't actually update until I toggle from one story, and then back to the story I'm on. (Meaning it's half working, but I don't see changes until rerendering)

Current package.json

```
  "devDependencies": {
    "react-native-scripts": "1.3.1",
    "jest-expo": "~20.0.0",
    "react-test-renderer": "16.0.0-alpha.12",
    "@storybook/react-native": "^3.2.8",
    "@storybook/addon-actions": "^3.2.6",
    "@storybook/addon-links": "^3.2.6",
    "react-dom": "16.0.0-alpha.12",
    "prop-types": "^15.5.10"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch",
    "storybook": "storybook start -p 7007"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "expo": "^20.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.0"
  }
```

The livereloading _was_ working on the CRNA app itself.

**Comment by danielduan** [comment]
I think I've came across this at one point as well. Can anyone else reproduce this on the latest or `3.3-alpha`?

**Comment by danielduan** [comment]
fixed https://github.com/storybooks/storybook/pull/2194
for existing projects, you'll need to replace the root storybook app with a react-native class component instead of a functional stateless component 

https://github.com/storybooks/storybook/issues/2081
