### ISSUE TITLE
Can storybook display the sample code for the component?

### ISSUE THREAD

**Issue by benweizhu** [storybooks/storybook#1843]
Hi storybook team,

I am wondering whether storybook support show the sample code on the storybook site for the component that display on page?

Like I write a Button component, and I want to show developers how to use the component?

```
import Button from '/components/Button';

<Button>This is a button.</Button>
```

**Comment by igor-dv** [comment]
One of the options is to use `addon-info`

https://github.com/storybooks/storybook/tree/master/addons/info

**Comment by benweizhu** [comment]
@igor-dv Thanks a lot, it works.

**Comment by Thamizhvaanan** [comment]
Can storybook display the sample html code for the component????

**Comment by imakou** [comment]
Want to know if storybook can display HTML code +1

**Comment by joe4mg** [comment]
Try the storysource addon

**Comment by blemaire** [comment]
> One of the options is to use `addon-info`
> 
> https://github.com/storybooks/storybook/tree/master/addons/info

`addon-info` is only compatible with react though, we use Angular here so can't use it 😢

**Comment by shilman** [comment]
@blemaire check out https://github.com/storybooks/storybook/tree/master/addons/storysource

**Comment by blemaire** [comment]
We have this setup but there is a lot of noise being displayed (still better than nothing to be fair)

**Comment by shilman** [comment]
@blemaire Will be fixing this as part of Storybook Docs: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a

**Comment by blemaire** [comment]
I saw this medium post a little while and have been dying for this to come out.
I've got a couple of side projects going at the moment but when the time is right, I'd like to get onboard (if you need extra fingertips)

**Comment by shilman** [comment]
@blemaire Please join the `#docs-mode` channel [on our Discord](https://discord.gg/UUt2PJb) for docs-related chatter. Would love to have you involved!

**Comment by blemaire** [comment]
@shilman already in there 😄 @Agaurooh#4198

**Comment by JBusch** [comment]
it is not possible to show the component and template  for angular right now, is it? am i missing something?

**Comment by bowiechang** [comment]
anyone had any chance with sourceon addon to render html/twig snippets? Seems like the only addons that displays code snippets.

**Comment by SBSB007** [comment]
Hi, I want to show my component .html/.ts code snippet in my storybook , I am using angular for my project. can anybody help here?
Thanks

**Comment by mgameover** [comment]
Hi guys,
@JBusch, @SBSB007 , If you are using Storybook v6 and `storysource` plugin you can specify `source` parameter for your story:
```ts
{
    storySource: {
        source : `
@Component({
    selector: 'my-component',
    template: '<p>This is a sample</p>',
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MyComponent  {
}`
    },
}
```
Result:
![screen](https://user-images.githubusercontent.com/62712576/109682870-69536e00-7b44-11eb-99ef-8312aa4318e5.png)

But that's more workaround the a proper solution. 
If you've found anything, please share. I'd rather prefer to display components source code than stories.
Thanks

**Comment by geometricpanda** [comment]
so i handled this in `preview.js`:

```js
addParameters({
    docs: {
        transformSource: (src, storyContext) => {
            try {
                const {template} = storyContext.storyFn(storyContext);
                return template;
            } catch (e) {
                return null;
            }
        }
    }
})
```

Limitations: This won't interpolate any `@Input` props.
And if there's any real problem, it's suppressing the Error and returning null - which usually is an issue, except thanks to how the `<Source>` block has been built where that's ok
https://github.com/storybookjs/storybook/blob/master/addons/docs/src/blocks/Source.tsx#L83
