### ISSUE TITLE
Static build works, but 'npm run storybook' gets 404 on manager.bundle.js

### ISSUE THREAD

**Issue by joakimgrr** [storybooks/storybook#1847]
Hi,

I have a react / webpack project to which i added storybook. I tried the automatic and manual installation and for both i get 404 on manager.bundle.js when running 'npm run storybook'. I opened the index.html inside the static build and that works just fine.

I installed storybook to a blank project and it seemed to work fine, so it seems that there is something conflicting possibly, but i cant figure what it could be, since that is the only error i'm getting.

Is there any known issues that might cause 404 on the bundle?

**Comment by danielduan** [comment]
do you have a custom webpack config? there needs to be an entry point specified or it will 404.

**Comment by speyburn** [comment]
@danielduan i don't have a custom config (i assume this would mean that i would have a webpack.config file in the .storybook folder)
