### ISSUE TITLE
Deprecate storybook old repos

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#1850]
I think these old repos should be moved to storybook-eol:
- https://github.com/storybooks/storybook-database-local
- https://github.com/storybooks/storybook-channel-firebase
- https://github.com/storybooks/storybook-database
- https://github.com/storybooks/storybook-channel-pagebus
- https://github.com/storybooks/storybook-addon-devel

We can have a discussion on whether react-cdk should be deprecated as well:
- https://github.com/storybooks/react-cdk

I don't think users lose much by going to cra + storybook instead of react-cdk. We can migrate some of the code into our CLI so it generates some boilerplates as well if desired.

**Comment by ndelangen** [comment]
I've added you as an owner to the storybook-eol organisation! :+1:

**Comment by danielduan** [comment]
alright, I'll move them.

**Comment by UsulPro** [comment]
I'd offer to not move react-cdk untill we can provide any better solution instead.

As for me `react-cdk` = `empty folder` + `getstorybook`

**Comment by danielduan** [comment]
@UsulPro would you feel comfortable putting a DEPRECATED label on the repo? I feel like it's misleading to users if we're not going to provide ongoing support for it.
