### ISSUE TITLE
Typescript bindings for storyshots

### ISSUE THREAD

**Issue by xogeny** [storybooks/storybook#1852]
Am I correct in understanding that as of 3.2, the addons type definitions should be located in
`@types/storybook__addon-${ADDON}` and that no such set of type definitions currently
exists for `@types/storybook__addon-storyshots`?

I have a [sample repository](https://github.com/xogeny/typescript-storyshots) and a [Medium article](https://medium.com/@mtiller/storybook-react-typescript-and-jest-c9059ea06fa7) that try to walk people through using TypeScript + Jest + Storybook + Storyshots.  But the [as has been pointed out to me](https://github.com/xogeny/typescript-storyshots/issues/1), the tests will work, but you'll get compiler errors (without such definitions) when trying to compile the code or run `storybook` with it.

I'd be happy to collaborate with whoever is responsible for maintaining the TypeScript definitions
to try and put together something reasonable so that using TypeScript works seamlessly.

**Comment by dantesolis** [comment]
hey guys, I'm having the same problem. Where Is it possible to submit a PR for those `TypeScript` defs.Thanks

**Comment by xogeny** [comment]
@dantesolis I would start here:

http://definitelytyped.org/guides/contributing.html

**Comment by bradleyayers** [comment]
I've written some types for storyshots and have published them at https://www.npmjs.com/package/@types/storybook__addon-storyshots.

**Comment by mortyccp** [comment]
If my project use vue this type definition will cause problem. Because of `import { StoryObject } from '@storybook/react';`

**Comment by igor-dv** [comment]
We are working on to bring in house typings
