### ISSUE TITLE
Packaging an addon

### ISSUE THREAD

**Issue by konsumer** [storybooks/storybook#1853]
I made a nice addon that shows you the QR code of the current story you are on (for mobile web testing) and I can't figure out how to package it.

This works fine when I import it in my project, in addons.js:

```js
import React from 'react'
import addons from '@storybook/addons'

const externalUrl = process.env.STORYBOOK_URL || window.location.origin

addons.register('local_qr', api => {
  class QRPanel extends React.Component {
    constructor (props) {
      super(props)
      this.state = {url: ''}
      this.handleUrl = this.handleUrl.bind(this)
    }

    componentDidMount () {
      api.onStory(this.handleUrl)
    }

    handleUrl (kind, story) {
      const url = `${externalUr}/iframe.html?selectedKind=${encodeURIComponent(kind)}&selectedStory=${encodeURIComponent(story)}`
      this.setState({url})
    }

    render () {
      return (
        <div>
          <img
            height={200}
            width={200}
            src={'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl=' + encodeURIComponent(this.state.url)}
          />
          <div>{this.state.url}</div>
        </div>
      )
    }
  }

  addons.addPanel('local_qr/panel', {
    title: 'QR Code',
    render: () => <QRPanel />
  })
})
```

But when I put it in it's own project and link to it via `file:///` url in package.json in another project, it doesn't seem to be registering (the QR panel isn't created, and things inside `addons.register` aren't called. A `console.log` in the top of my register file is called, however, so I know it's loading.

**Comment by konsumer** [comment]
[Here](https://github.com/konsumer/storybook-qr) is the packaged project.

**Comment by konsumer** [comment]
Here it is, running in another project (when imported directly in addons.js):

<img width="643" alt="screen shot 2017-09-15 at 5 48 12 pm" src="https://user-images.githubusercontent.com/83857/30507783-229e44ca-9a3e-11e7-8b2c-db7cfa4e9376.png">

**Comment by sigurbjorngudjonsson** [comment]
I'm having the exact same issue. Is there anything missing from the documentation?

**Comment by UsulPro** [comment]
@konsumer @sigurbjorngudjonsson when you import side package from npm or your local folder it should be transpilled to ES5. Usually, we do it via babel otherwise, it will be included in the bundle but can't be processed.
Are you sure you importing transpilled packages?
You can check out examples of our own addons in https://github.com/storybooks/storybook/tree/master/addons as well

If you have any further questions they're very welcomed in our [![Storybook Slack](https://now-examples-slackin-nqnzoygycp.now.sh/badge.svg)](https://now-examples-slackin-nqnzoygycp.now.sh/) where we have special channel `addons` dedicated to addon creation.

**Comment by konsumer** [comment]
@UsulPro yeh, I'm importing the babelified plugin. It's not registering at all, as in it doesn't throw an error or anything (as it would if the issue was that it neede to be transpiled) , just no QR panel. I have looked at the example addons, and mine is pretty similar (although maybe a bit simpler) and as I said does work fine if I include the same file, directly in another project, it's just when I try to package it up for others.

**Comment by UsulPro** [comment]
@konsumer 
didn't you notice that when you install your addon as a dependency you have missed `./index.js` in your package? to solve this you need to remove it from your `.gitignore` file or add separate `.npmignore` to your project. It happens because npm uses `.gitignire` instead of `.npmignore` when you don't provide the last directly.

**Comment by konsumer** [comment]
This is just local, it hasn't been published. Although, I will do it differently, and in my opinion a better way: have a gitignore that ignores index, the a npmignore which is identical but does not ignore it. That is what I typically do for [my other npm published projects](https://www.npmjs.com/~konsumer). Once published, I will definitely do that. But I am just trying to test the packaged addon locally. I am following the directions to use `file://` url instead of `npm link` (which is how I would normally do this.) I `prebublish` before testing (which generates the index), and it doesn't get included for some reason.

**Comment by konsumer** [comment]
But to be clear: `.npmignore` (or in the case where there is only `.gitignore`) only affects publishing. It tells `npm publish` which files to leave out, not what files should be ignored on a local import.

**Comment by konsumer** [comment]
and also, as a relevant sidenote, the file does get included (validated with a console.log at the top-level) it's just not registering (validated by no console.log in the register function.)

**Comment by konsumer** [comment]
a full example of validation:

```js
import React from 'react'
import addons from '@storybook/addons'

// this gets called
console.log('HI FROM TOP OF FILE')

const externalUrl = process.env.STORYBOOK_URL || window.location.origin

addons.register('local_qr', api => {
  // this never gets called
  console.log('HI FROM INSIDE REGISTER')
  class QRPanel extends React.Component {
    constructor (props) {
      super(props)
      this.state = {url: ''}
      this.handleUrl = this.handleUrl.bind(this)
    }

    componentDidMount () {
      api.onStory(this.handleUrl)
    }

    handleUrl (kind, story) {
      const url = `${externalUr}/iframe.html?selectedKind=${encodeURIComponent(kind)}&selectedStory=${encodeURIComponent(story)}`
      this.setState({url})
    }

    render () {
      return (
        <div>
          <img
            height={200}
            width={200}
            src={'https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl=' + encodeURIComponent(this.state.url)}
          />
          <div>{this.state.url}</div>
        </div>
      )
    }
  }

  addons.addPanel('local_qr/panel', {
    title: 'QR Code',
    render: () => <QRPanel />
  })
})
```

**Comment by UsulPro** [comment]
@konsumer it doesn't matter if you publish to npm or keep it in your local folder.
Let's say you have a folder `storybook-qr` with your addon and folder `app` with your main project when you want to use this addon.
As I understand you do the steps like this:
```sh
cd app
npm i ../storybook-qr --save-dev
npm run storybook
```

`npm i ../storybook-qr --save-dev` will add to your package.json dependency like this:
`"storybook-qr": "file:///home/path-to-addon/storybook-qr"` **and** install your addon  into `app/node_modules/storybook-qr`. while installing it will:

1. transpille it (because you have `prepublish` script)

2. filter all files from .npmignore (or from .gitignore if you don't have .npmignore)

You can always investigate what really you have by checking out your `app/node_modules/storybook-qr`

And to make it work you just need to have your `index.js` in this folder. I reproduced this steps on my machine and the only issue is related to that ignored file. After fixing it everything works fine!

proof:

![image](https://user-images.githubusercontent.com/14885189/30771367-0367189a-a04f-11e7-92e9-4c1b962b66aa.png)

**Comment by konsumer** [comment]
First of all, it does matter if you publish to npm or keep it in your local folder (that's just how npm works.) `.npmignore` is only to limit what files get sent to npm servers. You're missing the part that it is actually requiring it (as verified by the console.logs) and it's just not being registered. Your own tests confirm this, as you didn't mess with npmignore/gitignore, and somehow got it to work. To assuage your feelings that it must somehow be the gitignore/npmignore thing that is doing it though, I made an npmignore that is identical to gitgnore, except for the index.js line, as I would if I were publishing this. Did you do something else to get it to work?

[Here](https://asciinema.org/a/xSKnm3HwXd7duCHK8O2jAK7ka) is me doing what you suggest, start to finish, in a fresh project. It just doesn't work for me:

<img width="1227" alt="screen shot 2017-09-23 at 9 37 03 am" src="https://user-images.githubusercontent.com/83857/30775097-ca340ff8-a042-11e7-9a72-a37f88dfc91a.png">

Here is the above `console.log`s added:

<img width="1571" alt="screen shot 2017-09-23 at 9 39 43 am" src="https://user-images.githubusercontent.com/83857/30775141-2cccecd4-a043-11e7-88ea-9567523e1571.png">

Note the `HI FROM TOP OF FILE`, but no `HI FROM INSIDE REGISTER` and still no QR panel.

**Comment by konsumer** [comment]
If I copy the file into `.storybook/addons` and import it directly (not packaged), it works fine:

<img width="1867" alt="screen shot 2017-09-23 at 9 51 55 am" src="https://user-images.githubusercontent.com/83857/30775251-e840fb44-a044-11e7-81a8-5bdd0e84ab7d.png">

**Comment by konsumer** [comment]
I just published it on npm, and it worked fine, so I my point is the instructions for local development need a change, as they don't work as-is.

**Comment by UsulPro** [comment]
@konsumer how do you think is it enough to mention that after adding this line to `package.json` it's necessary to run `npm i` for this folder?
And that it's necessary to do it every time after you make changes in addon folder

(that's why I think it's not the best way to develop addons)

**Comment by konsumer** [comment]
That didn't do it for me. As I said the only way to make it work packaged, for me, was to actually publish it publicly, on npm.  In general, I use `npm link` for this sort of stuff, but that seems to have the same issues. Maybe if we got to the root of why the standard workflow doesn't work, then we could update the docs with proper `npm link` directions, and it would probably also fix the local file url thing, if people prefer that workflow.

**Comment by UsulPro** [comment]
@konsumer I tried your addon on my machine locally and everything worked fine (except the gitignore issue)

Maybe it will be useful to left the steps I did to run it (and maybe you can follow them from scratch as well):

```sh
git clone https://github.com/konsumer/storybook-qr.git
cd storybook-qr
npm i
cd ..
create-react-app test
cd test
getstorybook
npm i ../storybook-qr --save-dev
# add to addons.js line: import 'storybook-qr/register'; 
npm run storybook
```

**Comment by konsumer** [comment]
[Here](https://asciinema.org/a/pYJ02SK9DsYyehTtiD01xlSDZ) is me doing that. Here is the result (no QR panel):
<img width="1069" alt="screen shot 2017-09-23 at 2 24 28 pm" src="https://user-images.githubusercontent.com/83857/30777235-ed592ff4-a06a-11e7-8f0a-2347828ead36.png">

**Comment by konsumer** [comment]
Also, again, not sure what you mean by "the gitignore issue" as that was addressed above (even though it's actually not an issue.) As I said, this is actually published on npm and working fine in that context, just not locally, with any of the procedures you have described, or the procedure that is described in the documentation.

**Comment by konsumer** [comment]
It may not be clear, also, those "Here" statements above are actual links to screencasts of me trying what you are suggesting.  You can watch me do it.  I believe it works on your system, but it doesn't on mine, or  for @sigurbjorngudjonsson.

**Comment by sigurbjorngudjonsson** [comment]
If I remove `node_modules` from the custom addon folder and then switch over to a project where the addon is a file dependency and update the packages (`yarn` or `npm install`) then I'm able to use the addon with a local file reference in `package.json`.

Can it be the case that if the `node_modules` folder is not removed it uses a separate instance of the AddonStore from it's own `node_modules` where as the project using the addon has it's own as well?

I've declared that `"@storybook/addons": "^3.2.6"` is a peerDependency of the addon.

Has this anything to do with how the [AddonStore](https://github.com/storybooks/storybook/blob/master/lib/addons/src/index.js) is exported?

**Comment by cramatt** [comment]
Im seeing this issue too. It seems like there are 2 instances of `@storybook/addons`, and my addon is being registered with the second, which never gets initialized? Logs show the file is loaded, but the register callback never fires...
