### ISSUE TITLE
[addon-info] Why need break word for string prop ?

### ISSUE THREAD

**Issue by DimaRGB** [storybooks/storybook#1860]
Why need this wordBreak style for `string` prop ?
https://github.com/storybooks/storybook/blob/master/addons/info/src/components/PropVal.js#L28

it's ugly http://joxi.ru/V2V3w7EF0a8zMA

Thanks for cool addon.

**Comment by danielduan** [comment]
Is this a suggestion to remove the word break? It looks like if you have a really long word that gets displayed inside the prop table, it wouldn't break correctly. German words come to mind with something like this.

**Comment by DimaRGB** [comment]
Ok, but why that description don't have?

**Comment by danielduan** [comment]
Good question, I don't have an answer to that. If you'd like to open a PR to fix the prop table styles, please do! @DimaRGB
