### ISSUE TITLE
[addon-info] add custom Story

### ISSUE THREAD

**Issue by bratva** [storybooks/storybook#1863]
Hello.

I wrap my component in a helper, like this
```
<Wrap isMobile>
  <Button text="test"/>
</Wrap>
```
When i use addon-info like decorator or with `withInfo` i haved "Story Source" for both components.  But i want Source only for button.

I suggest add option`story` for addon. (custom Story component)
```(jsx)
import React from 'react';
import {Story} from '@storybook/addon-info';

class MyStory extends Story {
  _renderStory() {
    return (
      <Wrap isMobile>
       {this.props.children}
      </Wrap>
    );
  }
}

// in stories
withInfo({text: 'test', story: MyStory})(() => (
  <Button
     text="test"
  />
))
```

**Comment by UsulPro** [comment]
Hi, Pavel!
Storybook offers a bit another way to create stories. The idea is to put your needed isolated component to the story and wrap it with addons. If your component can't work without being wrapped into some other components you can use decorators.
Given that, your case might look like this:

```js
storiesOf('App', module)
  .addDecorator(storyFn => (<Wrap isMobile>{storyFn()}</Wrap>))
  .add('button', withInfo()(() => <Button text="test" />))
```

**Comment by UsulPro** [comment]
Yes, I know this addon-info behavior is confusing. That's why we started the work of removing addon-info to the preview side (#1501). After we finish that, stories will not be mutated by the addon

**Comment by bratva** [comment]
Thank.  I will wait
