### ISSUE TITLE
vue cli with getstorybook - sample "MyButton.vue" addon-action can't work

### ISSUE THREAD

**Issue by sky790312** [storybooks/storybook#1866]
I have used vue cli to generate my project and init storybook by "getstorybook".
I found the basic sample MyButton.vue has no react with click event to show in action log.
I have searched the vue way to use addon-action in stroybook example but can't work.

**Comment by Hypnosphi** [comment]
which project template do you use when running vue cli?

**Comment by Hypnosphi** [comment]
It can look like this:

```
import { storiesOf } from '@storybook/vue';
import { action } from '@storybook/addon-actions';

import MyButton from './MyButton';

storiesOf('Button', module)
  .add('With action', () => ({
    template: '<my-button :handle-click="log">Click me to log the action</my-button>',
    methods: {
      log: action('log1'),
    },
  }))
```

**Comment by sky790312** [comment]
I believe the project generate by vue-cli and init "getstorybook" which's add-action log has no react with the sample MyButton by click.. the sample use @click and methods, here you use prop $emit vue way. Neither can't work.

**Comment by Hypnosphi** [comment]
Can you please upload your project to github as a repo?

**Comment by sky790312** [comment]
sure, https://github.com/sky790312/storybook-test
it's just set up by vue-cli and getstorybook

**Comment by ederchrono** [comment]
Seems like Vue events are not working, to make the action work you need to send it as a prop and execute it inside the component :/

**Comment by Hypnosphi** [comment]
Looks like `MyButton.vue` lacked `$emit`: https://github.com/sky790312/storybook-test/pull/1. I will add that fix to #1867

**Comment by sky790312** [comment]
got it! there will be a little confuse to use @click and $emit together for vue developer, just a remind.

**Comment by Hypnosphi** [comment]
Why? https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events

**Comment by sky790312** [comment]
Sorry, forget that.
I mean..I see :handle-click="action" (<- it's prop) In some sample code.
It should use @handleClick="action" to $emit back parent element.

**Comment by Hypnosphi** [comment]
Code with `:handle-click` assumes that `MyButton` declares the corresponding prop, I just took that from `examples/vue-kitchen-sink`

**Comment by sky790312** [comment]
Yes, I think it should be
@handleClick="action"
then in parent method 'action' trigger the addon-action

**Comment by Hypnosphi** [comment]
You mean that child should `$emit('handleclick')` instead of `$emit('click')`? But it's just a matter of naming, isn't it?

**Comment by Hypnosphi** [comment]
**Alternatively**, you can use a prop, like this: https://github.com/storybooks/storybook/blob/master/examples/vue-kitchen-sink/src/stories/Button.vue

**Comment by sky790312** [comment]
I think we are discussing different things, the issue is clearify now. 
never mind.  Sorry for my poor expression. lol

**Comment by Hypnosphi** [comment]
Looks like this is relolved
