### ISSUE TITLE
Stencil / web components?

### ISSUE THREAD

**Issue by tycho01** [storybooks/storybook#1870]
So Ionic has recently put out an impressive [HNPWA](https://hnpwa.com/) ([here](https://github.com/ionic-team/ionic-stencil-hn-app)) based on their [Stencil](https://github.com/ionic-team/stencil), a "Compiler for Web Components" ([site](https://stenciljs.com/)).
This made me wonder: can `storybook` be used with web components? Would it require something specific to this Stencil to be used with it?

**Comment by ndelangen** [comment]
Interesting, yeah looks like that could work!

**Comment by ndelangen** [comment]
Hey @tycho01,

Check this out:
https://github.com/storybooks/storybook/pull/2225

This will actually support regular webcomponents just fine, I'm pretty sure ;)

It's unreleased for right now, but it's coming!

**Comment by leonrodenburg** [comment]
I looked at the code of #2225 again, and the current rendering code of Storybook for Polymer does not actually depend on Polymer. It just renders plain web components and would also work for Stencil / Skate JS / ... (fill in any other web components compliant framework). @ndelangen Maybe we should try to keep Storybook for Polymer framework-agnostic and rename it to Storybook for Web Components in the future?

Once the support for web components is added I can help set up example projects for Stencil or any other frameworks.

**Comment by ndelangen** [comment]
Yes, if we can keep #2225 working the way it does now, we could actually rename it to Storybook for WebComponents! 🎉

**Comment by franktopel** [comment]
Please re-open this ticket and let us know what has been done on this very promising issue!

**Comment by tonai** [comment]
For information I have made the test of integrating stencil and here is the comment that describe the process : https://github.com/storybooks/storybook/pull/2225#issuecomment-385005765

It can perhaps helps other stencil projects even if @storybook/polymer is not completely compatible now due to the polyfill that polymer uses and that cannot be removed from storybook.

**Comment by igor-dv** [comment]
@tonai, check this #3497, maybe it will help you to progress

**Comment by tonai** [comment]
Thanks @igor-dv, it indeed helps me because I was trying the v3 of storybook.
Upgrading to v4.0.0-alpha4 solved the polyfill problem.
