### ISSUE TITLE
Trying to run getstorybook shows uninformative error

### ISSUE THREAD

**Issue by rjbergerud** [storybooks/storybook#1874]
I run `getstorybook` and it prints the following error

```     Unexpected token } in JSON at position 2878 ```

I have no file named JSON in my project.  This is an error with my project, but it would be helpful if `getstorybook` would print out a more informative message/stacktrace.

**Comment by danielduan** [comment]
check your `package.json`?

**Comment by rjbergerud** [comment]
Yeah, it was there.

**Comment by danielduan** [comment]
If you have a link to your repo, we can probably take a look at it for you. It sounds like you have an extra `}` somewhere.

**Comment by rjbergerud** [comment]
@danielduan thanks, I found it ;)
