### ISSUE TITLE
Doesn't work with React Native

### ISSUE THREAD

**Issue by iosdev-republicofapps** [storybooks/storybook#1875]
Hi,

Thanks for making this available, it looks awesome and I'm eager to use it!  :-)

I create a react native app with create-react-native-app. The app works fine.  I followed your instructions at https://github.com/storybooks/storybook/tree/master/app/react-native#create-react-native-app-crna but when I try to preview on device, I get:
```
TransformError: /Users/joel/src/react/my-chat/node_modules/react-inspector/lib/index.js: Couldn't find preset "es2015" relative to directory "/Users/joel/src/react/my-chat/node_modules/react-inspector"

ABI20_0_0RCTFatal
-[ABI20_0_0RCTBatchedBridge stopLoadingWithError:]
__34-[ABI20_0_0RCTBatchedBridge start]_block_invoke_2
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

```

Any ideas?

Thanks!

**Comment by Rovack** [comment]
This seems to be the same issue reported in https://github.com/storybooks/storybook/issues/1831.

**Comment by danielduan** [comment]
I'm gonna close this because it's a duplicate as mentioned ^.
