### ISSUE TITLE
Remove drop shadow in Addon-Info

### ISSUE THREAD

**Issue by t2** [storybooks/storybook#1877]
The addon-info inline styling is very strange. Header and prop types are split into separate shadowed containers. Is this on purpose?

Example: https://cl.ly/0h0W0g0T1p1b

**Comment by ItsJonQ** [comment]
I noticed this as well. I couldn't override it via the `styles` config. I had to abandon it :(

**Comment by t2** [comment]
@ItsJonQ Me as well. Moved over to Styleguidist. Maybe someone will clean this up a bit.

**Comment by ItsJonQ** [comment]
@t2 Oo! Thanks for the recommendation. I'll seriously consider this option! My needs have grown from needing a simple playground to something more of a styleguide.

Thanks!

**Comment by danielduan** [comment]
We would love a PR for that if you any of you have time to give a try at fixing it.

**Comment by Hypnosphi** [comment]
I believe #1501 fixes that

**Comment by danielduan** [comment]
@Hypnosphi #1501 wouldn't fix this, but it would eliminate this problem because it won't be inline anymore.

**Comment by SuperOl3g** [comment]
@danielduan In common case we can just add `style` properties for each element of components.  But it's very inflexible solution. For example, now I want to add a light-gray background for each odd row in PropTable.
Inline styles can't do this, **we need the power of CSS**! ⚡️

AFAIU from #1576 you are planning to separate visual part from logic.
Did you think about [CSS modules](https://github.com/css-modules/css-modules), [styled components](https://github.com/styled-components/styled-components), [styletron](https://github.com/rtsao/styletron) or another CSS-in-JS solution with the possibility of theming?

**Comment by Hypnosphi** [comment]
@SuperOl3g We actually use [glamorous](https://glamorous.rocks/)

**Comment by SuperOl3g** [comment]
#428

**Comment by SuperOl3g** [comment]
@Hypnosphi Hmm, [it's](https://glamorous.rocks/advanced#theming) kind of theming but very limited. With this solution, we can theme the only what we preset to theming, it also doesn't give the possibility to overwrite any styles  :<

**Comment by SuperOl3g** [comment]
Hope #428 will solve not only the problem of theming of the core but also theming of add-ons too.

**Comment by danielduan** [comment]
I think if you're looking for an inline style guide type react tool, perhaps you should take a look at react-styleguidist: https://react-styleguidist.js.org/

I'd hate for you to leave Storybook but I think it might suit your use case better. You will lose out on Storybook's ecosystem of addons though.

**Comment by Hypnosphi** [comment]
> very very limited

It's actually the same as in styled-components which you have brought up

> we can theme the only what we preset to theming
In my view, it's actually a good thing. Anyway, we could just do something like this for all the components:

```
const Title = glamorous.h1({
  fontSize: '10px'
}, ({theme}) => ({
  color: theme.main.color,
  ...theme.Title
}))
```
Here, `theme.Title` will override everything

**Comment by SuperOl3g** [comment]
@Hypnosphi, sounds good! Look forward when it will be released)

**Comment by Hypnosphi** [comment]
@SuperOl3g you can actually bring that moment closer! Just clone the `release/3.3` branch, pick some component from `lib/ui/modules/ui/components`, and move it to `lib/components` replacing inline styles with glamorous stuff. Join us in slack once you have any questions: https://now-examples-slackin-nqnzoygycp.now.sh/

**Comment by SuperOl3g** [comment]
@Hypnosphi, ok, if I have some time, I will migrate some code

**Comment by SuperOl3g** [comment]
@Hypnosphi, I'm not very good at `glamorous` so maybe you know how to add theme styles only for `:nth-child(odd)` via `glamorous`?)

**Comment by Hypnosphi** [comment]
Like this:
```
{
  ':nth-child(odd)' {
    /* your styles */
  }
}
```

What do you want to use it for, by the way?
