### ISSUE TITLE
addon-info throws contrast accessibility issues for all stories

### ISSUE THREAD

**Issue by camsloanftc** [storybooks/storybook#1878]
The contrast ratio for the addon-info  "show info" button is inaccessible, and thus when used side-by-side with [storybooks-addon-a11y](https://github.com/storybooks/storybook-addon-a11y), I now receive an error on every single story.

<img width="1125" alt="screen shot 2017-09-21 at 1 35 49 pm" src="https://user-images.githubusercontent.com/16295659/30709917-d69d1842-9ed1-11e7-97de-f30096c27026.png">

**Comment by camsloanftc** [comment]
darkening the background of the button to this hex color would become AA and AAA compliant: `#155884`

**Comment by Hypnosphi** [comment]
@camsloanftc `#155884` looks OK to me, feel free to submit a PR with corresponding change

**Comment by UsulPro** [comment]
possible better to wait when we move it to the panel: no such buttons at all!

**Comment by camsloanftc** [comment]
If it is all being moved to the panel, then even better!
