### ISSUE TITLE
[3.3.0-alpha.0] addinfo throws prettyPropType error

### ISSUE THREAD

**Issue by eddiemonge** [storybooks/storybook#1880]
After upgrading to 3.3.0-alpha.0, I get the following message:

```
warning.js:35 Warning: Failed prop type: Invalid prop `propType` of type `string` supplied to `PrettyPropType`, expected `object`.
    in PrettyPropType (created by PropTable)
    in PropTable (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in Story
```

Seems to come from my `.storybook/config.js` file:

```
import { withInfo } from '@storybook/addon-info'

addDecorator((story, context) => withInfo({})(story)(context))
```

**Comment by danielduan** [comment]
I haven't seen the info addon documented or used like this as a decorator. I'm wondering if that's supported or not..

**Comment by eddiemonge** [comment]
That seems to fix it. The usage seems to have changed. That should make it a breaking change though

**Comment by shilman** [comment]
@eddiemonge please double check but i think `addDecorator((story, context) => withInfo({ text: 'string here' })(story)(context))` should also work. i think the issue in your code above is that you are passing in neither a string nor an object with a `text` field of type string. also, i don't think the usage has changed (other than the 3.2 change of `.addWithInfo` being deprecated (still supported, but will i'm hoping we drop it in 4.0). please lmk if that all makes sense 😬

**Comment by eddiemonge** [comment]
Changed it to 
```
addDecorator((story, context) => withInfo(
  'Global Components'
)(story)(context))
```
and it still throws the warning. Part of the problem is the debug output is not helpful. It doesn't give line numbers or anything useful. 

```
in PrettyPropType (created by PropTable)
          in PropTable (created by Story)
          in div (created by Story)
```
doesn't provide any context

**Comment by shilman** [comment]
@eddiemonge curious whether you've tried this in 3.2.11? it's also very possible that something broke in the 3.3 branch. if so, i can def look into it.

**Comment by eddiemonge** [comment]
`@storybook/react@3.2.11` no warning.

**Comment by eddiemonge** [comment]
Still an issue in 3.3.0-alpha.3

**Comment by danielduan** [comment]
this will probably be a part of https://github.com/storybooks/storybook/issues/2196 since it shows up in our jest tests.

**Comment by danielduan** [comment]
Think this has been fixed.
