### ISSUE TITLE
addon-info causes a 'TypeError: "paddingLeft" is read-only' error on React 16

### ISSUE THREAD

**Issue by jl-mindius** [storybooks/storybook#1890]
We just changed our project's structure to share code between web and React Native, which currently means using React 16.0.0-alpha.12 (due to RN version 0.47). This cased the error in the title to appear in the component view where we use the info addon. Upgrading to 16.0.0-rc.3 doesn't make a difference, but downgrading to 15.6.1 removes it.
```
The above error occurred in the <Node> component:
    in Node (created by Story)
    in pre (created by Pre)
    in Pre (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in Story
    in ThemeProvider
    in Router (created by BrowserRouter)
    in BrowserRouter

Consider adding an error boundary to your tree to customize error handling behavior.
You can learn more about error boundaries at https://fb.me/react-error-boundaries.

---

Node@http://localhost:9001/static/preview.bundle.js:67621:4
updateFunctionalComponent@http://localhost:9001/static/preview.bundle.js:37933:22
beginWork@http://localhost:9001/static/preview.bundle.js:38338:16
performUnitOfWork@http://localhost:9001/static/preview.bundle.js:40310:16
workLoop@http://localhost:9001/static/preview.bundle.js:40419:28
callCallback@http://localhost:9001/static/preview.bundle.js:29008:9
invokeGuardedCallbackDev@http://localhost:9001/static/preview.bundle.js:29047:7
invokeGuardedCallback@http://localhost:9001/static/preview.bundle.js:28904:5
performWork@http://localhost:9001/static/preview.bundle.js:40537:7
scheduleUpdateImpl@http://localhost:9001/static/preview.bundle.js:40922:19
scheduleUpdate@http://localhost:9001/static/preview.bundle.js:40861:12
scheduleTopLevelUpdate@http://localhost:9001/static/preview.bundle.js:41134:5
updateContainer@http://localhost:9001/static/preview.bundle.js:41164:7
renderSubtreeIntoContainer@http://localhost:9001/static/preview.bundle.js:44860:5
render@http://localhost:9001/static/preview.bundle.js:44881:12
renderMain@http://localhost:9001/static/preview.bundle.js:63978:3
renderPreview@http://localhost:9001/static/preview.bundle.js:63992:12
renderUI@http://localhost:9001/static/preview.bundle.js:53514:6
dispatch@http://localhost:9001/static/preview.bundle.js:53703:7
_renderMain@http://localhost:9001/static/preview.bundle.js:63790:7
render@http://localhost:9001/static/preview.bundle.js:63808:11
configure@http://localhost:9001/static/preview.bundle.js:63833:9
```
Like it says, the error comes from the Node component, specifically where left padding is added to `containerStyle`. Disabling that line removes the error.
```
function Node(props) {
  [...]
  var leftPad = {
    paddingLeft: 3 + (depth + 1) * 15,
    paddingRight: 3
  };
  // Error at below line
  (0, _assign2.default)(containerStyle, leftPad);
  [...]
```
Said line in the source: https://github.com/storybooks/storybook/blob/72186a4f32cd3ee6496d1dd89b7175948eed6c39/addons/info/src/components/Node.js#L61

**Comment by bmv437** [comment]
Yea, I've seen this too. It has to do with ReactFiber freezing the props to a component with `.preventExtensions()`

https://github.com/facebook/react/blob/11a1543b9ececd1fe8dbaf45df1e3ed3de5a8d9f/src/renderers/shared/fiber/ReactFiber.js#L53

The line above could be replaced with 
`const containerStyleCopy = Object.assign({}, containerStyle, leftPad)`

**Comment by danielduan** [comment]
The info addon doesn't work with react-native to my knowledge.

**Comment by bmv437** [comment]
I'm having the same issue with just normal react v16.0.0-rc.3
Was going to post an issue but I saw this one.

**Comment by danielduan** [comment]
@bmv437 please open a PR if you have a chance and add that line in. We'd really appreciate it!

**Comment by bmv437** [comment]
Opened a PR with the fix. Thanks @danielduan!

**Comment by jl-mindius** [comment]
Awesome, thanks guys!

To be clear, we're not using Storybook with React Native yet, but the shared root requires us using React 16 for the web app.
