### ISSUE TITLE
Help to debug "Accessing nonexistent addons channel" error that appears with 3.2.10

### ISSUE THREAD

**Issue by mthuret** [storybooks/storybook#1892]
Hi there, 

We use storybook along argos-ci to perform some visual regression testing. Since the release of 3.2.10, our build break with this error: Accessing nonexistent addons channel. 

I have a hard time understanding what is the change causing this. We were using 3.2.6 for the addons lib and the warning was already here. 

Here is the code that glue storybook with argos: https://github.com/algolia/react-instantsearch/blob/master/test/regressions/tests.js

I read some stuff about mocking the channel like storyshots does, I tried to mimic it but without any luck.

Does someone has any ideas?

**Comment by ndelangen** [comment]
Hey @mthuret,

Please check if all the addons you're using are updated and are using the same version of `@storybook/addons`.

**Comment by gvaldambrini** [comment]
@ndelangen I'm having the same issue. Not sure if it is related to this problem but in my case (the storybook-router development) the addon versions within the example app (cra-kitchen-sink) and within my addon are the same. What surprised me is that if I use the storybook-router version from npm (instead of the linked one) everything works fine. I can of course provide the code if it might help.

**Comment by mthuret** [comment]
@ndelangen yes that was it because we're using renovate for updating our deps. I group the update and everyting is now fine. I'm closing this.

 @gvaldambrini feel free to reopen this one or a new one if you have more details on your issue.

**Comment by StipJey** [comment]
I have this problem after update to 3.1.12

**Comment by jcreamer898** [comment]
The only 3 addons I'm using are these, and I'm getting the same error... 

![](http://d.pr/i/brWGTD+)

**Comment by colinswilliams** [comment]
Had this happening for me too, all dependencies were at 3.2.13, so I looked into the each dependency and saw that they were relying on `@storybook/addons`, which wasn't a part of my package.json. So for me, doing an `npm install -D @storybook/addons` resolved the issue.

**Comment by ndelangen** [comment]
@colinswilliams That should not be necessary to add as a dependency.. If you remove it now, it should continue to work.

If you have this problem, first thing to try is to remove `node_modules` and re-install. I my experience this solves the problem 99% of the time.

**Comment by ndelangen** [comment]
@colinswilliams Are you using a lockfile?

**Comment by colinswilliams** [comment]
Ooph! Good call, forgot about. Wound up deleting node_modules, and deleted the package.lock, removed @storybook/addons from package.json, and it worked. I'm assuming that when we added knobs later in the project, the lockfile referenced different versions of addons, giving us the error.

**Comment by ndelangen** [comment]
The joy of lockfiles ey? 😒 

I'm happy this resolved the problem.

**Comment by TroySchmidt** [comment]
Did something happen with v3.2.15?  I tried deleting ```package-lock.json```, deleting ```node_modules```, and installing ```@storybook/addons``` and nothing is getting rid of this danged non existent channels error.

**Comment by owcc** [comment]
reinstall all dependencies and keep all addons with same version(3.2.15), still not work,:(
<img width="315" alt="screen shot 2017-11-11 at 1 39 41 pm" src="https://user-images.githubusercontent.com/5770548/32686750-eac77ee0-c670-11e7-84ab-470485fca64d.png">

**Comment by webholics** [comment]
I have the same issue currently

**Comment by petekp** [comment]
Ran into this as well. Removing `node_modules` and `package-lock.json`, then re-running `npm install` worked for me.

**Comment by gscottolson** [comment]
I just fought with this same issue for the past few hours. Luckily, I had success with @petekp’s solution.

**Comment by Hypnosphi** [comment]
See https://github.com/storybooks/storybook/issues/1981#issuecomment-345193670

**Comment by TroySchmidt** [comment]
Played with deleting files, reinstalling, etc and made the local version work. But the CI build with VSTS using a custom agent that builds with fresh versions of the files using npm.cmd it results in no add-ons panel every time.

**Comment by ndelangen** [comment]
@TroySchmidt I'm real sorry you're experiencing these issues, We're working hard resolving the issue, but it's a non-trivial problem to solve.

@Hypnosphi has proposed a solution that involves moving the dependency of the @storybook/addons package to a peerDependency.

**Comment by TroySchmidt** [comment]
@Hypnosphi @ndelangen update on using alpha.4 it is back to building locally with the panels showing.  But now I am getting a undefined error in KnobManager when it is trying to ```_this.channel.emit('addon:knobs:setKnobs',...```

The actions panel is working properly.

**Comment by g-verma** [comment]
if still you facing the same issue , try this showAddonPanel: false, in config.js
