### ISSUE TITLE
Add documentation for which addons support react-native

### ISSUE THREAD

**Issue by notgiorgi** [storybooks/storybook#1895]
Add documentation for which addons support react-native

**Comment by danielduan** [comment]
We'd love a PR for it if you have some time. I think most of the addon readmes have something regarding which projects they support or don't support. It's probably a matter of gathering them in one place and trying some out.

I know for a fact the info addon isn't supported in react-native.

**Comment by notgiorgi** [comment]
> gathering them in one place and trying some out.

the [addon gallery](https://storybook.js.org/addons/addon-gallery/) would be the best fit I think.

**Comment by danielduan** [comment]
Yeah I can see some filter for that list for react, react-native, vue, and angular.

**Comment by notgiorgi** [comment]
Even simple badges after the name would be enough

**Comment by danielduan** [comment]
Documented in https://github.com/storybooks/storybook/blob/master/ADDONS_SUPPORT.md
