### ISSUE TITLE
Possibility to group knobs in the panel

### ISSUE THREAD

**Issue by Aylata** [storybooks/storybook#1896]
Hello!

Is it possible to group knobs when they are shown in the panel? I use "chapters" add-on to enable using different components in one story. Each component has its own knobs. At the moment there is a long-long-long list of all knobs and it's very hard to navigate and find something that you need. So is there any chance to group those knobs in a way I need it?

Thank you!

**Comment by danielduan** [comment]
I don't think that's something on the roadmap, but if you think you have a solution for it, feel free to open a PR.

**Comment by wildeyes** [comment]
Does anybody have any pointers on where to look to get this started? this feature is quite important for me, I'm thinking of implementing it.

**Comment by danielduan** [comment]
@wildeyes the code for knobs is under `addons/knobs`. `CONTRIBUTE.md` should have some tips on how to get your dev environment set up.
