### ISSUE TITLE
Windows 10 won't run getstorybook - EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by kkollman** [storybooks/storybook#1897]
Hi there,

I have a big issue when trying to run `getstorybook` - installer throws error and stops the whole process.

Message I get is:

 ```
• Detecting project type. ✓
 • Adding storybook support to your "React" app. ✓
 • Preparing to install dependencies. ✓

yarn install v1.1.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'D:\\kamil\\App\\node_modules\\farmhash\\build\\Release\\farmhash-legacy.node'".
info If you think this is a bug, please open a bug report with the information provided in "D:\\kamill\\App\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

 • Installing dependencies. ✖

     An error occurred while installing dependencies.
```

Could someone please let me know how to handle this one? It's driving me crazy.

**Comment by marchdoe** [comment]
@kkollman - what version of node are you running?

**Comment by yourikopecky** [comment]
@kkollman When I have this "EPERM: operation not permitted, unlink [...]" issue on windows it's because:
-When Atom (or any IDE using the project) is open
-When I use Atom Beta (open or not), the fix for this one is to use the stable release of Atom
-When my local server is running

So maybe it's not a problem with storybook.

**Comment by UsulPro** [comment]
@kkollman 
try to run `npm i` after that. Do you still have the same error?

**Comment by kkollman** [comment]
@marchdoe node v6.11.0
@yourikopecky I've tried with local server and atom off - no difference :(
@UsulPro when I try to `npm i` it correctly throws _no json_ error - did I understand something wrong? Shouldn't it be just a zip file that is opened?

**Comment by danielduan** [comment]
Try running your terminal in admin mode.
