### ISSUE TITLE
Accessibility developer tools don't work

### ISSUE THREAD

**Issue by dweldon** [storybooks/storybook#1899]
I've found that the [Chrome Accessibility Developer Tools](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en) don't work when browsing stories. I'm using storybook with Vue components (unsure if that's related). The accessibility properties of components were available when I used Vue Play (which also uses iframes) in the past, but after the switch to storybook the properties are never available.

**Comment by nblackburn** [comment]
I am seeing the same, it's a shame as it helps to be able to see them and the state of components.

**Comment by Hypnosphi** [comment]
I tried it on our [example app](https://github.com/storybooks/storybook/tree/master/examples/vue-kitchen-sink). Is this how it should work, or am I missing something?
<img width="1440" alt="screen shot 2017-09-28 at 01 30 22" src="https://user-images.githubusercontent.com/6651625/30941153-c615b8e2-a3ec-11e7-928f-9b73b4f5e4e2.png">

**Comment by dweldon** [comment]
@Hypnosphi That image looks correct... I just downloaded the source for `vue-kitchen-sink` but I can't get it to build. I'm getting a lot of `Module build failed: ReferenceError: Unknown plugin "transform-runtime"` errors.

**Comment by Hypnosphi** [comment]
You can run it this way:
```
git clone https://github.com/storybooks/storybook.git
cd storybook
yarn
yarn bootstrap --core
cd examples/vue-kitchen-sink
yarn storybook
```

**Comment by dweldon** [comment]
Thanks for the directions - I was able to get the build working but I still can't get the accessibility tools to work for anything inside of the `iframe` (including the button). I can see the accessibility properties of the `iframe` itself and everything above. For reference I'm on Chromium 61.0.3163.79 on Linux.

I wonder if I'm supposed to have to tell the plugin to look inside the `iframe` or something... though I've never had to do that before. Weird.

**Comment by dweldon** [comment]
I'm going to close this, as some combination of build environment and/or package upgrades has magically fixed this for me.
