### ISSUE TITLE
How to set up React Native Storybook with alternate dist directory (e.g. with TypeScript)?

### ISSUE THREAD

**Issue by lukecwilliams** [storybooks/storybook#1902]
The default installation instructions create a ./storybook directory, but in our case we need all source to be in `src` for TypeScript.  We compile to `dist`.

Moving storybook directory to src and compiling it doesn't appear to work.  We can get the server running with `-c dist/storybook`, but then the app runs normally - not showing any storybook content.

How can we get the storybook app to run with `react-native run-ios` when it's in the `./dist/storybook` directory?

**Comment by lukecwilliams** [comment]
I can get storybook running by conditionally changing this line

    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"dist/index.ios" fallbackResource:nil];

To

    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"storybook/index.ios" fallbackResource:nil];

Is that really the intended way to use this library though?  It seems like "no" because that requires modifying this file every time we want to look at storybook items.

**Comment by lukecwilliams** [comment]
Summarized questions on this topic:

1. How to set custom directory for storybooks index.ios.js entry point
2. How to transpile .ts files somewhere besides ./dist, so that they're not included in the production deployment bundle

**Comment by roblafeve** [comment]
I've been struggling with this for the last few days.

**Comment by lukecwilliams** [comment]
@roblafeve So far I don't have a better answer for (1) above - I just have to modify jsBundleURLForBundleRoot.

For (2):

- I'm just moving storybook files to ./src/storybook, and compiling to ./dist/storybook.
- Modified package.json scripts with
    "storybook": "storybook start -p 7007 -c dist/storybook"
- I'll have to remember to delete the ./dist/storybook directory prior to production deployment

I was unable to get output to multiple directories with multiple tsconfig.json files in different folders, though [comments elsewhere](https://stackoverflow.com/questions/29908200/tsconfig-how-to-set-correct-compiler-output-location-for-multiple-directories) seemed to indicate this is possible.

I'd still really like to know how to get storybook to find my index.ios.js file when it's in a custom subdirectory!

**Comment by lukecwilliams** [comment]
Side note, if anyone can explain what this `module` keyword is doing I'd be very appreciative.

    storiesOf('Welcome', module)

**Comment by Hypnosphi** [comment]
@lukecwilliams it's used for dealing with HMR

**Comment by lukecwilliams** [comment]
@Hypnosphi Ok - thanks for the info!

Just need to know how to get the storybook packager to recognize `./dist/storybook/index.ios.js` without manually modifying AppDelegate.m.

**Comment by lukecwilliams** [comment]
@Hypnosphi Do you know where this `module` keyword is from?  I don't understand why it's available and useful, is it like a `this` pointer for JS modules?

Very hard to find info searching the word "module".

**Comment by Hypnosphi** [comment]
It's rather a global variable than a keyword. It's not a part of JS standard, but it's used by webpack (it basically took it from node.js)

**Comment by lukecwilliams** [comment]
@Hypnosphi Ok, interesting - thanks.  I'm unclear where it comes from in RN without Webpack but I take it it's polyfilled somehow.

**Comment by Hypnosphi** [comment]
The stories files are indeed processed by webpack (`@storybook/react-native` depends on it)

**Comment by lukecwilliams** [comment]
That's helpful, thank you!
