### ISSUE TITLE
Add Vue play example like storybook-addon-jsx

### ISSUE THREAD

**Issue by lee-chase** [storybooks/storybook#1907]
Based on the activity I'd say storybook is a better long-term solution than vue-play, but without example source storybook does not fulfil the basic needs. Is anyone working on this?

**Comment by ndelangen** [comment]
Have you seen this:
https://github.com/storybooks/storybook/tree/release/3.3/examples/vue-kitchen-sink

Or this:
https://github.com/ndelangen/storybook-vue-example

Or are you looking for an example using JSX? I haven't seen it yet!

**Comment by lee-chase** [comment]
I'm working with Vue and noted that the JSX storybook plugin shows the markup/jsx required to create the story.

vue-play also has this feature.

However, unless my freshly installed/tested version of Storybook is broken, I do not see the markup/vue required to create the story.

**Comment by kazupon** [comment]
Unfortunately, we can not support JSX for Vue Components, due to Storybook is based on React architecture. 😞  
when we use [babel-preset-vue](https://github.com/vuejs/babel-preset-vue) in Storybook, occure conflicting.

**Comment by kazupon** [comment]
sorry, never mind.
We can support JSX syntax for Storybook of Vue.

**Comment by lee-chase** [comment]
Can you show Vue syntax?

**Comment by kazupon** [comment]
You can check it at [here](https://github.com/storybooks/storybook/pull/1993)

**Comment by kazupon** [comment]
close (merged #1993)

**Comment by ndelangen** [comment]
Awesome @kazupon !!!
