### ISSUE TITLE
Module build failed: SyntaxError

### ISSUE THREAD

**Issue by achtan** [storybooks/storybook#191]
hi, I'm getting this error:
https://www.dropbox.com/s/ist4p2vljk1d25y/Screenshot%202016-05-11%2016.01.07.png?dl=0

my package.json is:

```
....
  "devDependencies": {
    "@kadira/storybook": "^1.25.0",
    "babel-cli": "6.x.x",
    "babel-core": "6.x.x",
    "babel-eslint": "4.x.x",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-runtime": "6.x.x",
    "babel-polyfill": "6.x.x",
    "babel-preset-es2015": "6.x.x",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-2": "6.x.x",
    "babel-register": "^6.8.0",
    "chai": "3.x.x",
    "eslint": "1.7.x",
    "eslint-plugin-babel": "2.x.x",
    "mocha": "2.x.x",
    "nodemon": "1.7.x",
    "webpack": "^1.9.11",
    "webpack-dev-middleware": "^1.2.0",
    "webpack-hot-middleware": "^2.9.1"
  },
  "dependencies": {
    "babel-runtime": "6.x.x",
    "react": "^15.0.2",
    "react-dom": "^15.0.2"
  }
```

any idea how to fix it?

**Comment by arunoda** [comment]
Try updating storybook to the latest version. We had some issue, which removes the first preset in the babel config.

I think that's the issue here.

**Comment by achtan** [comment]
i have a latest version of SB `"@kadira/storybook": "^1.25.0",`
here is the rebo https://github.com/achtan/mo-admin-theme
it's a mix of https://github.com/kadirahq/npm-base and storybook

**Comment by arunoda** [comment]
@achtan Thanks for the repo. I'll check.

**Comment by ndelangen** [comment]
Please re-open if you are still experiencing this issue 👍
