### ISSUE TITLE
On Edge browser, Storybook doesn't reload styles for :disabled pseudo selector

### ISSUE THREAD

**Issue by borbediana** [storybooks/storybook#1913]
I am creating react components. When changing a prop from knobs, the styles for :disabled pseudo selector are not reloaded instantly (at re-render). You have to click on the story window to load them.

Using:
    "@storybook/addon-knobs": "3.1.9",
    "@storybook/react": "3.1.9",

**Comment by Hypnosphi** [comment]
How exactly does your example looks like? This seems to work ok in Edge:

```css
.my-button {
  background-color: #fff;
}

.my-button:disabled {
  background-color: #eee;
}
```

```js
import React from 'react';
import { storiesOf } from '@storybook/react';
import { withKnobs, boolean } from '@storybook/addon-knobs';

const MyButton = (props) => <button className="my-button" {...props} />;

storiesOf('MyButton', module)
  .addDecorator(withKnobs)
  .add('disabled', () => (
    <MyButton disabled={boolean('Disabled', false)}>
      Disable me in knobs tab
    </MyButton>
  ));
```

**Comment by borbediana** [comment]
I am using **react-jcss** for styling.

`    input: {
    '&:disabled + label': {
      '&:before': {
        backgroundColor: colorFlint
      }
    },
    '&:disabled:checked + label': {
      '&:before': {
        backgroundColor: colorFlint
      },
      '&:after': {
        backgroundColor: colorHammer
      }
    }
  }`

**Comment by Hypnosphi** [comment]
And what exactly does your knob do? Just toggles the `disabled` prop, as in my example above?

**Comment by borbediana** [comment]
I have a <input type="radio" />. I just change the `disabled` prop.
