### ISSUE TITLE
Add button to addon-knobs

### ISSUE THREAD

**Issue by Billy-** [storybooks/storybook#1914]
I'd like to suggest a feature for the knobs addon; a button which when clicked would fire some handler function, e.g:

```js
const onClick = button('Do Something', () => alert('Something!'))
```

And then this button would appear in the knobs panel.

My current solution is to simply put a button inside the story, which is not ideal.

Kind regards

**Comment by danielduan** [comment]
definitely makes sense to me. we welcome PRs 👍

**Comment by UsulPro** [comment]
Hi @Billy- 

>My current solution is to simply put a button inside the story, which is not ideal.

You can put your function to the story, and it will trigger each time when you select this story:

```js
.add('normal story', () => <Component />)
.add('story with action', () => {
  // Do Something:
  alert('Something!');
  return <Component />
})

```

**Comment by Billy-** [comment]
@UsulPro my intention is to allow the user of the story to trigger an action multiple times. In my case my action would dispatch an action to my redux store.

> we welcome PRs

I will look into it... :+1:

**Comment by Hypnosphi** [comment]
Does [`addon-events`](https://github.com/storybooks/storybook/tree/master/addons/events) serve your needs?

**Comment by Billy-** [comment]
> Does addon-events serve your needs?

Possibly.. I'm not sure.. it seems to be tied to an event emitter?

I have tried for several hours today but could not get a working development environment for storybook or the knobs addon. Could someone spell it out for me?

**Comment by Hypnosphi** [comment]
Please describe your troubles in an issue, or at our slack [support channel](https://storybooks.slack.com/messages/C55DBHZL0/convo/C4Q0S3MQR-1506807775.000043/)

**Comment by Hypnosphi** [comment]
> it seems to be tied to an event emitter?

No, it's just used as an example. In your case it would be

```
<WithEvents
  emit={store.dispatch}
  events={[
    {
      type: 'MY_ACTION',
      data: ...,
    },
    ...
  ]}
/>
```

It will create a separate control for each action in `events` array

**Comment by derrickpelletier** [comment]
Threw a PR together for this. I had hacked together something for similar functionality, so figured I'd clean it up and PR it after I saw this issue. Realize there's some discussion here, but I think @Billy- 's original issue is a different problem than the suggestions that were made.
