### ISSUE TITLE
Consider removing opencollective dependency

### ISSUE THREAD

**Issue by lucasmotta** [storybooks/storybook#1937]
I understand that Storybook is an open-source project and it somehow it needs to get donations and backers so the project can be maintained. But I doubt that the best way to do that is throwing a "DONATE NOW" message when installing the package.

To make things worse, at the moment, storybook cannot even be installed properly because [opencollective-cli](https://github.com/opencollective/opencollective-cli) published a new version of their package that is broken:
https://ci.appveyor.com/project/xdamman/opencollective-cli/build/1.0.20

Again, I am totally up for having a donate button on github or on the website, but doing that on the CLI does not sound like the best place...

An issue was also created at opencollective's repo:
https://github.com/opencollective/opencollective-cli/issues/3

**Comment by prabhu** [comment]
I think someone will answer this one after all the fun and games are over with opencollective.

**Comment by shilman** [comment]
Released as part of https://github.com/storybooks/storybook/releases/tag/v3.2.12
