### ISSUE TITLE
How to call function props in stories?

### ISSUE THREAD

**Issue by zainfathoni** [storybooks/storybook#1941]
Hi, I am testing a component using Storyshots. This component contains [function props](https://codecov.io/gh/zainfathoni/ojekbelanja/commit/4689e152ef45ac7806767a0ae510fdb1f7ed684c#D1-x94) like these:

```jsx
action={() => action(key)}
actionReverse={() => actionReverse(key)}
```

However, since those functions are not called, I am unable to reach 100% coverage test on that component.
How am I supposed to test those kind of props?

Thanks.

**Comment by zainfathoni** [comment]
I just change the function props into this one:

```jsx
action={actions[key]}
```

So it doesn't need to be called to reach 100% coverage on that file.

However, since it makes the code to be [more complicated](https://github.com/zainfathoni/ojekbelanja/pull/46/commits/4689e152ef45ac7806767a0ae510fdb1f7ed684c), I still want to know how to test that kind of function props. May be there is a better way in doing it while keeping the test coverage 100%.

Thanks.

**Comment by Hypnosphi** [comment]
I believe it depends on how your components call those function props. You should probably emulate the conditions in which this happens

**Comment by zainfathoni** [comment]
I think I need to simulate the `click` and `change` events to make it happens, which can be done using [Enzyme](http://airbnb.io/enzyme/).

From what I just read in [this article](https://www.codementor.io/vijayst/unit-testing-react-components-jest-or-enzyme-du1087lh8), I can use [Enzyme](http://airbnb.io/enzyme/) alongside Jest's Snapshot testing, can't I?

Then where am I supposed to write the test? Is it in the `*.stories.js` file as well, or in a separated `*.test.js` file? If it is in the `*.stories.js` file, then where exactly should I put the simulation test?

Thanks.

**Comment by zainfathoni** [comment]
I just tried writing the test file in a separated `*.test.js` file, and it works!

Thanks! 😄 

Please take a look at [this commit diff](https://github.com/zainfathoni/ojekbelanja/pull/46/commits/6f7da97b3ae44b3ead11eb671fbb0260703dac93) and correct me if I am doing things in bad ways.

**Comment by Hypnosphi** [comment]
You're doing good =) To enable snapshotting, just add this line:
```
expect(filterInput).toMatchSnapshot();
```

**Comment by zainfathoni** [comment]
Got it, thanks! 😄
