### ISSUE TITLE
Is this a bug or a feature ?

### ISSUE THREAD

**Issue by Slackercode** [storybooks/storybook#1942]
When I create a component which has another component as a child like so `MyComponent.MyChild`, storybook renders the code sampe like so : `MyChild`
expected result: `MyComponent.MyChild`

If it's a feature how can I disable it ?

**Comment by danielduan** [comment]
can you be more specific?

If you named a story MyComponent.MyChild, and you have hierarchy enabled with the `.` as a separator, it should render like this.

```
-- MyComponent
    |-- MyChild
```
