### ISSUE TITLE
Storybook custom name renders poorly when string is too long

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#1961]
<img width="236" alt="screen shot 2017-10-03 at 3 46 42 pm" src="https://user-images.githubusercontent.com/1474548/31145674-74ddae3e-a852-11e7-93bd-e762d8e31cbd.png">

The `STORYBOOK` in the upper left corner can be customized through `addon-options`. When the string overflows, it goes onto a new line and throws off the layout.

Perhaps it should just have ellipses?

**Comment by Hypnosphi** [comment]
I believe it was normally wrapping before, will check what happened

**Comment by Hypnosphi** [comment]
I believe it's #1769 that broke it
