### ISSUE TITLE
Action is very slow

### ISSUE THREAD

**Issue by stepankuzmin** [storybooks/storybook#1984]
Storybook Addon Actions is very slow in compare with console.log

Eg.

```js
const onClick = action('onClick');
```

![2017-10-06 12_44_28](https://user-images.githubusercontent.com/533564/31272592-345d1590-aa94-11e7-8410-beea74ee89a9.gif)

<img width="331" alt="screenshot 2017-10-09 13 29 28" src="https://user-images.githubusercontent.com/533564/31334202-f4f17658-acf5-11e7-9f96-2ee34cd2f619.png">

```js
const onClick = console.log.bind(console, 'click');
```

![storybook-action-2](https://user-images.githubusercontent.com/533564/31272308-2965aca2-aa93-11e7-9b6e-c9ef1ca6b60a.gif)

The rest of the code is the same for both cases

```js
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import StaticMap from './static-map';

storiesOf('MapGL', module)
  .add('Static Map', () => <StaticMap onClick={onClick} />);
```

**Comment by danielduan** [comment]
possibly related to https://github.com/storybooks/storybook/issues/1535

what's in the debugger waterfall chart under the event handler click?
