### ISSUE TITLE
can not load scss file with storybook 

### ISSUE THREAD

**Issue by wwlweihai** [storybooks/storybook#199]
i hava configed the webpack.config.js follow:

`const path = require('path');
module.exports = {
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loader:'style!css!sass',
                include: __dirname
            }
        ]
    }
}`

buy when i run storybook ,the error follow show:
@arunoda  can u help me.

`ERROR in ./imports/ui/layouts/app.scss
Module parse failed: /Users/ww/Desktop/dev/meteorPro/forum/imports/ui/layouts/app.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
`

**Comment by arunoda** [comment]
include should be `path.resolve(__dirname, '../)`
