### ISSUE TITLE
ESLint question

### ISSUE THREAD

**Issue by Luchanso** [storybooks/storybook#1992]
There is error in project: 
```[eslint] '@storybook/addon-actions' should be listed in the project's dependencies, not devDependencies. (import/no-extraneous-dependencies)``` [more about this rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md). So, how to resolve this issue? I won't add  `@storybook/addon-actions` in dependencies, but how to fix this error?

**Comment by Hypnosphi** [comment]
You may want to add something like this to your eslint config:
```
rules: {
  'import/no-extraneous-dependencies': [
      error,
      {
        devDependencies: [
          '.storybook/**',
          'stories/**' 
        ]
      }
    ]
}
```

This will allow usage of devDependencies in the listed directories

**Comment by Luchanso** [comment]
@Hypnosphi Yeah, it's work fine, thank you very much

**Comment by jhoch** [comment]
@Hypnosphi, you have a small typo in your [comment](https://github.com/storybookjs/storybook/issues/1992#issuecomment-335001056) above: `error` should be `'error'`.

Years later, I copied your suggestion, with a small tweak for my project, and it worked perfectly - thank you!  Including mine for anyone who would find it useful:
```javascript
rules: {
  // ...

  'import/no-extraneous-dependencies': [
    'error',
    {
      devDependencies: [
        '**/*.stories.tsx',
      ],
    },
  ],

  // ...
}
```

**Comment by Mattgic** [comment]
When you init a Storybook project with `sb init`, you have `@storybook/addon-essentials` installed which includes `@storybook/addon-actions`. In this case it would make sense not to include `@storybook/addon-actions` as a devDependency. 
Thing is you can't disable ESLint rule `import/no-extraneous-dependencies` for specific imports. That would be useful.

**Comment by hochan222** [comment]
@Hypnosphi 

Hi. I'd like to know the cause of this rather than simply changing the eslint configs. Because, I think `@storybook/addon-actions` should be in `devDependencies`. It's not a production environment. 

In fact, other open sources are also guessing it is a bug. https://github.com/pagarme/artis/pull/126#discussion_r165860685

Is it a story book idea or a bug?

**Comment by Hypnosphi** [comment]
That's how the corresponding rule from `eslint-plugin-import` package works. This package is *not* added to your project by storybook, so unfortunately storybook can't be responsible for configuring it for you. By default, it only allows regular `dependencies`. See details here: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md

**Comment by hochan222** [comment]
> That's how the corresponding rule from eslint-plugin-import package works.

I understood what it means. Thank you for your kind reply. After reading several issues/comments, I think it is not the responsibility of the storybook. ESLint is just a tool for proofreading, but I think my thoughts were short. Have a nice day :)
