### ISSUE TITLE
Config directory

### ISSUE THREAD

**Issue by josephchang** [storybooks/storybook#1994]
With the 3.3.0 releases, it looks like `--config-dir`/`-c` is not being used anymore, but in favour `SBCONFIG_CONFIG_DIR`, is this likely to change once it goes out of alpha, or is it going to stay?

**Comment by shilman** [comment]
From what I can tell:
- `SBCONFIG_CONFIG_DIR` has been around for months
-  `SBCONFIG_CONFIG_DIR` is an alternative way to specify the config dir via env variable, but `--config-dir / -c` still works just fine

Hope that helps!

**Comment by josephchang** [comment]
I recently upgraded to `3.3.0-alpha.2` and encountered errors, and found that in `server/config/utils.js`, a new `getConfigDir` function had been added, which seems to ignore the command line option.

```
var getConfigDir = exports.getConfigDir = function getConfigDir() {
 return process.env.SBCONFIG_CONFIG_DIR || './.storybook';
};
```

I'm not sure what other regression errors it has caused, but for me, it no longer loaded `preview-head.html` into `iframe.html.ejs`. `webpack.config(.prod).js` use the above function to get the contents of that file, but it was looking in `./.storybook/preview-head.html` without setting `SBCONFIG_CONFIG_DIR`.

**Comment by zdrummond** [comment]
I have a very similar issue with `3.3.0-alpha.4', but only with `preview-head.html`.

1. Start on a main line release of Storybook, like what I am using `3.2.15`
2. Setup your config directory somewhere other than `/.storybook`, add a `preview-head.html` to that directory and pass `-c` to the `start-storybook`.
3. Run storybook and see your `preview-head.html' injected
4. Upgrade to alpha 4
5. Run again and your `preview-head` changes are gone
6. Move config and `preview-head` to `/.storybook`
7. Run once more and now see your `preview-head` changes.

**Comment by Skovy** [comment]
I couldn't find this issue with googling, but I had this same issue and using the ENV var seems to fix the issue. 

https://github.com/storybooks/storybook/issues/2501
