### ISSUE TITLE
Styles are missing in development, but are added in production

### ISSUE THREAD

**Issue by 1egoman** [storybooks/storybook#1995]
I'm unable to get styles to properly display in my react storybook project in `development` mode.

Here's an example project that demonstrates this issue: https://github.com/DensityCo/storybook-issue

To reproduce, clone that repository and run `yarn && yarn storybook`. At `localhost:6006`, here's what I see:

![screen shot 2017-10-09 at 11 41 59 am](https://user-images.githubusercontent.com/1704236/31346365-e282de62-ace6-11e7-8309-eaecbd3cbb9b.png)

However, after running `yarn build-storybook && cd storybook-static && python -m SimpleHTTPServer 8000`, here's what I see:

![screen shot 2017-10-09 at 11 45 25 am](https://user-images.githubusercontent.com/1704236/31346531-6932a726-ace7-11e7-9693-d8d8eb406cad.png)

Am I doing something wrong? Thanks for the help.

**Comment by shilman** [comment]
Your example is working for me on my machine. Based on your screenshot, it looks like your actions pane is just taking up the whole screen. Try deleting the query params and navigating directly to http://localhost:6006/ ?

**Comment by 1egoman** [comment]
Visiting `http://localhost:6006` without query params doesn't seem to change anything.

Should the header of the action logger pane draggable? It doesn't seem to be on the development preview page.

**Comment by ndelangen** [comment]
@1egoman Can you clear your localStorage and check if there are any warnings/errors/info in the console to give us an indication of what's going on?

**Comment by 1egoman** [comment]
Rebooting then clearing localStorage seemed to fix it. Thanks for the suggestion @ndelangen!
