### ISSUE TITLE
Unnecessary <br> tags when using withNotes

### ISSUE THREAD

**Issue by szalonna** [storybooks/storybook#2005]
Currently the withNotes plugin replaces every new line to \<br /> tag.
https://github.com/storybooks/storybook/blob/21aa273812d79f4ca2e7a40738cb884dc739884e/addons/notes/src/register.js#L52

When I provide a HTML input for the plugin (e.g. compiled from a markdown file), it adds <br> tags to the code, which makes huge spaces between the tags. As far as I can see it is unable to disable this behaviour.

Current workaround can be that we remove new lines from the generated HTML code, but it contains example codes which compiles to \<pre\> tags and removing new lines breaks the \<pre\> tags' content.

**Comment by dangreenisrael** [comment]
So, the reason this is happening appears to be that the notes addon is expecting to handle just plain text.  Using an HTML string appears to be an undocumented side effect of replacing line breaks with `<br/>` tags and using `dangerouslySetInnerHTML`. Perhaps a better approach would be to determine if the note is a string, and if it is handle by replacing the newlines. If it a react node, then render it as such. This would allow you to use JSX in your notes without any workaround. If this is something that people want, I would be happy to put together a PR. @danielduan @szalonna

**Comment by danielduan** [comment]
@dangreenisrael please if you have time, we'd love a PR.

**Comment by dangreenisrael** [comment]
I'm looking into channels and to whether or not we can send react components over them

**Comment by Hypnosphi** [comment]
@dangreenisrael I'd say we can't, because react component types are functions, and functions aren't serializeable. We can support markdown instead (which we probably do already)
