### ISSUE TITLE
Last moment version broke storybook/addons-knobs

### ISSUE THREAD

**Issue by bameda** [storybooks/storybook#2006]
```
WARNING in node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '~/node_modules/moment/src/lib/locale'
```

This addons is broken since the last moment version was released.

Related issue: https://github.com/moment/moment/issues/4218

You could force the version to solve it.

**Comment by Ezku** [comment]
For a quick fix if you depend on knobs for development, try

```
cd node_modules/@storybook/addon-knobs
npm install moment@2.18.1
```

**Comment by kohlmannj** [comment]
I also manually edited my project's `yarn.lock` file to contain _only_ this entry for `moment@^2.18.1`:

```
moment@^2.18.1:
  version "2.18.1"
  resolved "https://registry.yarnpkg.com/moment/-/moment-2.18.1.tgz#c36193dd3ce1c2eed2adb7c802dbbc77a81b1c0f"
```

After saving the edit, I ran these commands:
```bash
$ rm -rf node_modules
$ yarn
```

**Comment by dptoot** [comment]
Changelog comment from moment@2.19.0 states to add this to webpack config

```
 resolve: {
      alias: {
        'moment$': 'moment/moment',
      }
    },
```

**Comment by ndelangen** [comment]
Moment discussion tracked here:
https://github.com/moment/moment/issues/4216

**Comment by danielduan** [comment]
Looks like moment broke a whole bunch of stuff. Gonna close this since it looks like reinstalling the dependencies would fix this issue.
