### ISSUE TITLE
addon-info package is not up to date on npm

### ISSUE THREAD

**Issue by mbeaudru-mrkl** [storybooks/storybook#2023]
Hi,

On github, the last version of the @storybook/addon-info package is 3.2.12 whereas it is 3.2.5 on npm. Is there a plan on when the npm package is going to be updated ? :blush: 

Thanks !

**Comment by shilman** [comment]
3.2.12 is the latest version on npm:

```
$ npm info @storybook/addon-info

{ name: '@storybook/addon-info',
  description: 'A Storybook addon to show additional information for your stories.',
  'dist-tags': { alpha: '3.3.0-alpha.2', latest: '3.2.12' },
  ...
}
```

**Comment by mbeaudru-mrkl** [comment]
Oops, I'm sorry ! The version was fixed on my package.json, I should have investigated more ><.
