### ISSUE TITLE
Optional chaining issue

### ISSUE THREAD

**Issue by anthify** [storybooks/storybook#2024]
Hey,

I added a `.babelrc` to the `.storybook` directory, installed [babel-plugin-transform-optional-chaining](https://www.npmjs.com/package/babel-plugin-transform-optional-chaining), and added this to the `.babelrc`.

```
{
  "presets": ["env", "stage-0", "react"],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }],
    "transform-optional-chaining"
  ]
}
```

The above config is just lifted from the one in the [storybook repo](https://github.com/storybooks/storybook/blob/master/.babelrc). I played around and experimented with a few different solutions but I couldn't get it to work. On each load it would see the use of `obj?.prop?.otherProp` and throw `Module build failed: SyntaxError: Unexpected token`.

`package.json`
```
  "dependencies": {
    "@storybook/react": "^3.2.12",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "styled-components": "^2.2.1"
  },
  "devDependencies": {
    "babel-plugin-transform-optional-chaining": "^7.0.0-alpha.13.1",
    "eslint": "^4.8.0",
    "eslint-config-prettier": "^2.6.0",
    "eslint-plugin-prettier": "^2.3.1",
    "eslint-plugin-react": "^7.4.0",
    "prettier": "^1.7.4"
  }
```

I'm hoping it's something simple I'm missing as it would be a very useful feature for my current project. Thanks.

**Comment by Hypnosphi** [comment]
This transform uses syntax which is only parseable by babel version 7. It’s still in alpha, so we use version 6 for now.

There’s a chance you can work it around by using webpack config [full control mode](https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode) with your own babel-loader. Please tell us if you have any success with that

**Comment by asmyshlyaev177** [comment]
It is still actual, i wanna enable this via babel, but can't get it work with storybook

**Comment by shilman** [comment]
@Hypnosphi any thoughts on this in 2020? 😅

**Comment by Hypnosphi** [comment]
@asmyshlyaev177 
Can you please create a GitHub repo with minimal reproduction of your issue?

**Comment by asmyshlyaev177** [comment]
@Hypnosphi we use custom webpack config, as i see plugin didn't added to final webpack config.
