### ISSUE TITLE
Way to disable Storybook from logging verbose on Travis?

### ISSUE THREAD

**Issue by erichdev** [storybooks/storybook#2029]
I have an app that runs Storybook in its Travis build, and Storybook is logging several thousand lines. Is there a way to disable this? It's making it hard to go through the log and causes lag with scrolling because of how long it is.

![storybook](https://user-images.githubusercontent.com/15041132/31509755-6f64fec6-af37-11e7-82b7-b2e7587b8960.PNG)

**Comment by danielduan** [comment]
Looks like you're already using a custom webpack file. You can just add some additional configuration to silence the output.

https://webpack.js.org/configuration/stats/

**Comment by erichdev** [comment]
@danielduan Thanks for the response. Adding `stats: 'none'` did not stop the logging. I also tried `stats: { chunks: false, chunkModules: false, maxModules: false }` based on tips I found [here](https://github.com/webpack/webpack/issues/4141), still no effect. I even tried adding both variations directly to the config at `@storybook/react/dist/server/config/defaults/webpack.config(&prod).js` and it still logs. Is this purely a webpack issue? Any ideas why adding the `stats` option had no effect?

**Comment by danielduan** [comment]
you shouldn't be running `start-storybook` on a server. that's intended for development purposes.

take a look at `build-storybook`. it outputs a static bundle so you can host it on any http server.

**Comment by erichdev** [comment]
Found the root cause -- Storybook's webpack config uses `ProgressPlugin` which does all the logging, regardless of the `{ stats: 'none' }` config. My solution was to remove that plugin with `storybookBaseConfig.plugins.pop()`. Let me know if there's a better solution, since this may not be safe if Storybook's config changes in the future.

**Comment by Hypnosphi** [comment]
I'd suggest `storybookBaseConfig.plugins = storybookBaseConfig.plugins.filter(plugin => plugin.constructor.name !== 'ProgressPlugin')`
