### ISSUE TITLE
cannot find package in npm

### ISSUE THREAD

**Issue by VadimZvf** [storybooks/storybook#2030]
base npm registry return 404.

https://registry.npmjs.org/@storybook

**Comment by kresli** [comment]
I'm not sure if this helps but shouldn't be https://registry.npmjs.org/storybook ? For example typescript typing are installed via `npm i @types/<package>` but you can't find `https://registry.npmjs.org/@types`. Only `https://registry.npmjs.org/types` are available.

**Comment by VadimZvf** [comment]
Thank.
I found mistake in sinopia
[bug](https://github.com/rlidwka/sinopia/issues/462)
