### ISSUE TITLE
Show shortcuts with `⌘ ?`

### ISSUE THREAD

**Issue by andrewmartin** [storybooks/storybook#2039]
Hi,

I was wondering if it would be possible to add a quick way to show the shortcuts panel. I'm fairly new to Storybook, and keep forgetting the keys after I've hidden the panels from view.

**Comment by andrewmartin** [comment]
If I can learn how to add the keyboard shortcuts properly, e.g. the main steps involved –– I'd love to contribute a PR for this

**Comment by Hypnosphi** [comment]
Sure, here's the contributing guide: https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md

You need to do the following to start:
— fork the repo and checkout to the `release/3.3` branch
— `yarn install`
— `yarn bootstrap --core`
— `yarn dev` to watch & autobuild the sources (this one should keep running in background)
— `yarn start` to launch the example app

The code for shortcuts operations mainly lives here:
https://github.com/storybooks/storybook/blob/release/3.3/lib/ui/src/libs/key_events.js
https://github.com/storybooks/storybook/tree/release/3.3/lib/ui/src/modules/shortcuts

And the action for toggling shortcuts help is here (you will probably need to move it to `modules/shortcuts`):
https://github.com/storybooks/storybook/blob/release/3.3/lib/ui/src/modules/ui/actions/ui.js

Feel free to join us on slack once you have any questions: https://now-examples-slackin-nqnzoygycp.now.sh/

**Comment by andrewmartin** [comment]
@Hypnosphi 

So, I followed your instructions to a "T", but for some reason I'm hitting this error. Any ideas?

```~/code/storybook release/3.3* 1m 33s
❯ yarn start
yarn start v0.27.5
$ npm --prefix examples/cra-kitchen-sink run storybook

> cra-kitchen-sink@3.3.9 storybook /Users/andrewmartin/code/storybook/examples/cra-kitchen-sink
> start-storybook -p 9010 -s public

sh: start-storybook: command not found```

**Comment by andrewmartin** [comment]
Thanks, doh, sorry!
