### ISSUE TITLE
missing dependency "babel-helper-explode-assignable-expression"

### ISSUE THREAD

**Issue by dontsave** [storybooks/storybook#2052]
just upgraded my storybook/react to 3.2.12. running storybook yields module not found "babel-helper-explode-assignable-expression" error. installing this module manually solves the issue, but thought you should know

**Comment by Hypnosphi** [comment]
How does your `.babelrc` file look like?

**Comment by dontsave** [comment]
I don't use babel I use typescript and ts-loader

**Comment by Hypnosphi** [comment]
Ok, that's quite weird then. Can you please create a GitHub repo with reproduction?

**Comment by dontsave** [comment]
weirdly, removing my package.lock, upgrading storybooks to 3.2.13 and doing a fresh npm i fixed this
