### ISSUE TITLE
Side nav doesn't work

### ISSUE THREAD

**Issue by lintiwen** [storybooks/storybook#2057]
I'm using 
```
    "@storybook/react": "3.2.8",
    "react-scripts": "1.0.12"
```

when I tried to click on side nav items, it won't work and throws this error:
<img width="1439" alt="screenshot at oct 16 01-32-18" src="https://user-images.githubusercontent.com/3269632/31602485-1979ffd8-b212-11e7-8ed1-5bd2132b1917.png">

```
Uncaught Error: Unable to find node on an unmounted component.
    at invariant (invariant.js:42)
    at Object.findDOMNode (react-dom.development.js:13870)
    at VelocityComponent._getDOMTarget (velocity-component.js:162)
    at VelocityComponent._stopAnimation (velocity-component.js:180)
    at VelocityComponent.componentWillUpdate (velocity-component.js:94)
    at ReactCompositeComponent.js:708
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:707)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:642)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:544)
```

I'm using the same versions in the other project and it works as expected. I checked syntaxes of my storybook/index.js multiple times and I'm pretty sure there are no mistakes.

**Comment by Hypnosphi** [comment]
Is the error stil present when you update to `3.2.12`?

**Comment by Hypnosphi** [comment]
Can you please upload your project to GitHub so that I could try it myself?

**Comment by lintiwen** [comment]
@Hypnosphi thanks for helping out:
https://github.com/lintiwen/ui-seed-project

You should be able to reproduce the bug right after checking out.
I'm using yarn 1.1.0 to install packages. I haven't tested with npm install yet.

**Comment by Hypnosphi** [comment]
Interesting: I can reproduce it with `yarn@1.1.0`, but not with `yarn@1.2.0` nor `npm@5.5.1`.

Is updating yarn version an option in your case?

**Comment by lintiwen** [comment]
@Hypnosphi 
I updated to yarn@1.2.1 and the bug goes away.

Yes, since I'm building a automation script for my team so I have total control of the environment.

Should we leave this issue open for now? 
other people might bump into the same bug but don't have the flexibility to just upgrade yarn.

Thanks for your time to help out, really appreciate it!

**Comment by Hypnosphi** [comment]
I think we can close and reopen once someone needs a fix on our side
