### ISSUE TITLE
can't see web in react native

### ISSUE THREAD

**Issue by zhaoheqi** [storybooks/storybook#2063]
![image](https://user-images.githubusercontent.com/6813909/31651062-b6c77d88-b2df-11e7-9113-e61db7e2a29d.png)
I use it in react native but it doesn't work in web but is ok in simulator
![image](https://user-images.githubusercontent.com/6813909/31651167-304a6ae4-b2e0-11e7-8528-6bbe8bd5e9eb.png)

**Comment by hellogerard** [comment]
I had this same issue. Upgrading to babel 6 fixed my problem. See https://github.com/storybooks/storybook/issues/13#issuecomment-323816036

**Comment by zhaoheqi** [comment]
@hellogerard I try it but it doesn't work

**Comment by quyentranvan** [comment]
@zhaoheqi Read careful at this docs, hope this help: https://github.com/storybooks/storybook/tree/master/app/react-native#start-storybook

- In react native app, we seems as can't see stories on web browsers. Only see list menu of stories.
- You must run react native app by run: `react-native run-<platform>`.
- Once your app is started, changing the selected story in web browser will update the story displayed within your mobile app.

**Comment by waltermvp** [comment]
@quyentranvan which do we run first?

`npm run storybook` or `react-native run-<platform>.`

**Comment by Hypnosphi** [comment]
It doesn't matter, they should run in parallel, in separate terminal tabs

**Comment by atinder** [comment]
@Hypnosphi 
the description on [this page](https://github.com/storybooks/storybook/tree/master/app/react-native) is little misleading

> With Storybook for React Native you can design and develop individual React Native components without running your app.

**Comment by Hypnosphi** [comment]
You don't actually run your app, see
https://github.com/storybooks/storybook/tree/master/app/react-native#create-react-native-app-crna

**Comment by atinder** [comment]
but we do need to run emulator right?
Stories list is blank until I run emulator. 
<img width="1080" alt="screen shot 2017-12-13 at 11 58 58 pm" src="https://user-images.githubusercontent.com/2451681/33955533-e41b8176-e061-11e7-9fc7-038bf64c778b.png">

**Comment by Hypnosphi** [comment]
No, you can't view RN stories in desktop browser currently

**Comment by swaroopa94** [comment]
@zhaoheqi Did you fixed the issue? I am also getting the same issue.
