### ISSUE TITLE
[storybook/ui] add react16 to peerdeps

### ISSUE THREAD

**Issue by brucewpaul** [storybooks/storybook#2091]
It seems as though there are a some things holding back adding react 16 as a peerdep to storybook/ui. Here is what's needed from what we can tell:

react-modal
- currently at 2.4.1, needs to be bumped to ^3.0.0

react-komposer
- PR is out to support react16 as peerdep https://github.com/arunoda/react-komposer/pull/169) but has not been merged in

react-treebeard
- PR has been merged in (https://github.com/alexcurtis/react-treebeard/pull/102), but has not released

react-simple-di@1.2.0 (required by manta-core as well)
- seems like it's not being actively maintained

react-stubber@1.0.0 (required by react-komposer as well)
- seems like it's not being actively maintained

Is it feasible to move away from react-stubber/react-simple-di so that the road to expanding the peerDependencies is clearer?

**Comment by brucewpaul** [comment]
seems like forks were made for react-simple-di and mantra-core (https://github.com/kadirahq/react-simple-di/issues/12#issuecomment-335722498) that, if used, would help

**Comment by Hypnosphi** [comment]
Please feel free to open PRs for updating `react-modal` and `react-treebeard` (as soon as it gets released).

@ndelangen I think we have to migrate from mantra/podda/komposer stack to something more actively maintained (redux maybe). What do you think?

**Comment by brucewpaul** [comment]
@Hypnosphi will do

I would also be interested in helping out with this effort as storybook/ui is our last dependency holding us back from upgrading to react16

**Comment by ndelangen** [comment]
> @ndelangen I think we have to migrate from mantra/podda/komposer stack to something more actively maintained (like redux or mobx). What do you think?

Yes, although I wonder if we even have a use-case for a state management library to begin with?

**Comment by mperrotti** [comment]
I have a pre-commit hook that runs `yarn check`, so I'm unable to submit new work for PR after upgrading to the latest Storybook.
Any recommendations for how to get around these issues in the short-term? Sadly, `--no-verify` isn't an option :(

**Comment by Hypnosphi** [comment]
> in the short-term

We're sorry but we have to admit that there are no quick solution here

**Comment by danielduan** [comment]
I'm going to close this since https://github.com/storybooks/storybook/pull/2314 on 3.2.16 should fix the last of the dependencies on the list here. Let me know if it doesn't.

**Comment by Hypnosphi** [comment]
> Any recommendations for how to get around these issues in the short-term

Can you please try 3.2.16 release? We removed the `react` version conflicts, so probably all you'll need to do will be add some dependencies like `prop-types` in your project

**Comment by mperrotti** [comment]
@Hypnosphi - that takes care of the issues. Thank you!
