### ISSUE TITLE
enable greenkeeper

### ISSUE THREAD

**Issue by brucewpaul** [storybooks/storybook#2092]
It would be great to enable greenkeeper so that we as major versions of packages that are in many peerdepencies get udpated, it's not as much of a pain to update to allow them (see https://github.com/storybooks/storybook/issues/2091)

It's would also be great to keep dependencies updated in general, and this would help with that.

**Comment by Hypnosphi** [comment]
Greenkeeper doesn't support multiple packages in a repo, so we use dependencies.io for deps management. Initially, I wanted to enable issue creation for major versions bump,  but @shilman and @danielduan had some objections

**Comment by danielduan** [comment]
Given the amount of dependencies we have, I think it'd be pretty noisy. I think greenkeeper opened an issue every few days the last time we had it turned on.

I am open to trying it out again though?

**Comment by Hypnosphi** [comment]
The check period is adjustable. It's 1 day currently, but we can change it to a week

**Comment by danielduan** [comment]
I'm fine with every week as long as someone is reviewing them.

**Comment by danielduan** [comment]
fixed with #2141
