### ISSUE TITLE
Bug : The hamburger goes behind the status bar on Android 

### ISSUE THREAD

**Issue by ritz078** [storybooks/storybook#2102]
Attaching the image.

<img width="557" alt="screen shot 2017-10-20 at 4 31 10 pm" src="https://user-images.githubusercontent.com/5389035/31818098-436f329a-b5b4-11e7-9357-328ec447be55.png">

**Comment by danielduan** [comment]
If you'd like to open a PR to fix it, we'd greatly appreciate it :)

**Comment by danielduan** [comment]
I might have a fix for you @ritz078. We should have the next patch version out in the next day or two, please let us know if that fixes this.

**Comment by shilman** [comment]
[3.2.15 released](https://github.com/storybooks/storybook/releases/tag/v3.2.15). Closing this--let us know if you're still having this issue!
