### ISSUE TITLE
Update React app favicon

### ISSUE THREAD

**Issue by dburles** [storybooks/storybook#2104]
Should use the new "S" logo

**Comment by Hypnosphi** [comment]
Looks like we take resourses from `create-react-app`'s `public` directory on purpose: https://github.com/storybooks/storybook/commit/f7a20a94bca62fa8f88e0a6461cb996341816b4d

The easiest workaround is to remove `-s public` from your `storybook` and `build-storybook` scripts in `package.json`.

Another issue is, our default favicon itself needs to be updated

Current favicon
![current favicon](https://raw.githubusercontent.com/storybooks/storybook/master/app/vue/src/server/public/favicon.ico)

Storybook v3 icon
![v3 logo](https://github.com/storybooks/press/raw/master/logo/v3/icon.png)

Feel free to open a PR on that part. PNG and SVG for new icon images are available in the [press repo](https://github.com/storybooks/press/tree/master/logo/v3)

**Comment by dburles** [comment]
Great! to be clear, I was referring to your second point that the current favicon is out of date :)

**Comment by andreasvirkus** [comment]
I wouldn't mind taking it if that's alright.

**Comment by danielduan** [comment]
published in `3.2.13`
