### ISSUE TITLE
Adding storybook support to webpack. Connect ETIMEDOUT 

### ISSUE THREAD

**Issue by nithyanv** [storybooks/storybook#2114]
Hi, 

Following these steps to add storybook to my app. 
$cd myApp
$npm i -g @storybook/cli
$getstorybook

But getting below error. 

Adding storybook support to your "Webpack React" app(node:76676) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: connect ETIMEDOUT

**Comment by danielduan** [comment]
check your internet connection and perhaps if you can install `@storybook/react`?

sounds like your npm or yarn installs are getting stuck.
