### ISSUE TITLE
How to add a copywebpackplugin to storybook webpack config in full control mode.

### ISSUE THREAD

**Issue by ssbiswal1987** [storybooks/storybook#2115]
I have tried to add the plugin like this

```js
baseConfig.plugins.push(
		new CopyWebpackPlugin([
			{
				from: `src/assets/customer/locale`,
				to: 'locale',
				debug: true
			}
		])
	);
```

but it does not work.

Below is how the storybook plugins list looks when consoled to terminal

```js
plugins: 
   [ DefinePlugin { definitions: [Object] },
     HotModuleReplacementPlugin {
       options: {},
       multiStep: undefined,
       fullBuildTimeout: 200,
       requestTimeout: 10000 },
     CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     WatchMissingNodeModulesPlugin {
       nodeModulesPath: '/Users/c-client/node_modules' },
     ProgressPlugin { profile: undefined, handler: undefined },
     { apply: [Function: bound apply] } ],
```

**Comment by ndelangen** [comment]
That's a mystery to me..

**Comment by Hypnosphi** [comment]
@ssbiswal1987 how exactly does your `.storybook/webpack.config.js` look like?

**Comment by ssbiswal1987** [comment]
`const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = (baseConfig) => {
	// Custom loaders
	baseConfig.module.rules = [
		...baseConfig.module.rules,
		scssLoader,
		fileLoader,
		imageLoader
	];

	baseConfig.plugins.push(
		new CopyWebpackPlugin([
			{
				from: `src/assets/customer/locale`,
				to: 'locale',
				debug: true
			}
		])
	);

	// Custom module paths
	const resolvedCustomModulePaths = [
		'../src/js',
		'../src/fonts',
		'../src/css'
	].map(toResolvedPath);

	baseConfig.resolve.modules = [
		...baseConfig.resolve.modules,
		...resolvedCustomModulePaths
	];

	return baseConfig;
};

const scssLoader = {
	test: /\.scss$/,
	loaders: ['style-loader', 'css-loader', 'sass-loader'],
	include: path.resolve(__dirname, '../src')
};

const fileLoader = {
	test: /\.(otf|ttf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
	loader: 'file-loader',
	query: {name: '[name].[ext]'}
};

const imageLoader = {
	test: /\.(jpe?g|png|gif|svg)$/i,
	loader: 'file-loader',
	query: {name: '../img/[name].[ext]'}
};

const toResolvedPath = targetPath => path.resolve(__dirname, targetPath);
`
@Hypnosphi

**Comment by Hypnosphi** [comment]
Looks like this `{ apply: [Function: bound apply] }` object is the `CopyWebpackPlugin` (at least, `ProgressPlugin` is the last one in base config). Another question is, why it doesn't work

**Comment by ssbiswal1987** [comment]
Yeah that is the one. It does not work.

**Comment by ssbiswal1987** [comment]
any help ?

**Comment by VRedondo** [comment]
I facing the same issue, opening a new ticket
