### ISSUE TITLE
React Native preview throws warnings for required URL props on OnDeviceUI and StoryView

### ISSUE THREAD

**Issue by b3ngineer** [storybooks/storybook#2117]
In the following code, {{url}} is required by <OnDeviceUI /> and <StoryView />, but only passed in without null values under certain circumstances.

In particular, if {{channel}} comes back from {{addons.getChannel()}} then the {{resetStorybook}} flag has to be true to initialize correctly according to PropTypes.

getStorybookUI(params = {}) {
    return () => {
      let webUrl = null;
      let channel = null;

      try {
        channel = addons.getChannel();
      } catch (e) {
        // getChannel throws if the channel is not defined,
        // which is fine in this case (we will define it below)
      }

      if (params.resetStorybook || !channel) {
        const host = params.host || parse(NativeModules.SourceCode.scriptURL).hostname;
        const port = params.port !== false ? `:${params.port || 7007}` : '';

        const query = params.query || '';
        const secured = params.secured;
        const websocketType = secured ? 'wss' : 'ws';
        const httpType = secured ? 'https' : 'http';

        const url = `${websocketType}://${host}${port}/${query}`;
        webUrl = `${httpType}://${host}${port}`;
        channel = createChannel({ url });
        addons.setChannel(channel);
      }
      channel.on('getStories', () => this._sendSetStories());
      channel.on('setCurrentStory', d => this._selectStory(d));
      this._events.on('setCurrentStory', d => this._selectStory(d));
      this._sendSetStories();
      this._sendGetCurrentStory();

      // finally return the preview component
      return params.onDeviceUI ? (
        <OnDeviceUI stories={this._stories} events={this._events} url={webUrl} />
      ) : (
        <StoryView url={webUrl} events={this._events} />
      );
    };
  }

**Comment by danielduan** [comment]
I'm not quite following here. Are you saying that the url proptype is incorrect because in some instances, it could be null and valid?

We're definitely open to a PR for this if you have some time.
