### ISSUE TITLE
storybook-hub

### ISSUE THREAD

**Issue by gabrielcsapo** [storybooks/storybook#2120]
will the code for storybook hub be released for use by the community?

**Comment by Hypnosphi** [comment]
Excuse me, but what is storybook hub?

**Comment by ndelangen** [comment]
I was never given access to it, we'd have to ping @arunoda to get it.

**Comment by gabrielcsapo** [comment]
@arunoda thoughts?

**Comment by gabrielcsapo** [comment]
@Hypnosphi here is what I am talking about https://github.com/storybook-eol/getstorybook.io/blob/b43499c4e7b3a78e1e9068ba742807c2aada864a/src/docs/storybook-hub/basics/getting-started.js#L11

**Comment by danielduan** [comment]
I'd actually would love to see what it does too. @gabrielcsapo we do have a deployer bundle that helps you deploy your Storybook to Github Pages if you're interested too.

**Comment by gabrielcsapo** [comment]
@danielduan I saw that, my main reasoning for wanting storybook hub is being able to code review PRs using storybook.

**Comment by gabrielcsapo** [comment]
Hub looked for PR hooks and would build the story book and link it in the PR so that people could review the changes and make comments to it.

**Comment by danielduan** [comment]
@gabrielcsapo we now have a netlify hook to build the static storybook per PR and host it remotely on their server. It's probably as close as we'll get. https://github.com/storybooks/storybook/pull/2304

**Comment by gabrielcsapo** [comment]
@danielduan this wasn't specifically for a solution for how to get similar functionality it was an ask to open source that code. Can you please reopen that?

**Comment by gabrielcsapo** [comment]
@arunoda can you speak to that ask?

**Comment by gabrielcsapo** [comment]
Some companies need a solution for private GitHub instances and are looking for more a host your own type solution that doesn't require rolling a server-less environment.

**Comment by ndelangen** [comment]
@gabrielcsapo These isn't anything actionable for us.

We're not in control of that code, I'd open source it if I could.

---

I see @danielduan re-opened the issue. When would you consider this issue closed? Because the code may never be released. I don't know; again: this is outside of our control.

**Comment by danielduan** [comment]
@gabrielcsapo realistically, the open source community hasn't been able to get a hold of him for months. I can reopen this but I wouldn't keep my hopes up if I were you.

**Comment by gabrielcsapo** [comment]
😞 okay yeah, I guess that is a noop. Sorry for bugging you guys, it was a cool product, really sad to see it die. Would you guys think about making something to support it?

**Comment by danielduan** [comment]
I can take a stab at it when I have some time, but implementations like this is often platform dependent.

I imagine the Storybook Hub does something like:

On PR create/update: 
1. Clone Storybook git repo and run build on a CI server
2. Copy to AWS folder with issue number as folder name

On PR merge/close:
1. Delete AWS folder with issue name

**Comment by gabrielcsapo** [comment]
@danielduan what if the service deployed the storybook to itself? Like an http file server that Hooke and built storybooks.

**Comment by danielduan** [comment]
In terms of server best practices, it's not good to keep any sort of state or user data permanently on a server.

Hypothetically if I were to create this for the community as a reusable GitHub deployer, that's the route I would take.

**Comment by gabrielcsapo** [comment]
@danielduan would you accommodate an FTP upload case? I could see this as simply execute a storybook build and then choosing a deployment strategy, linking the url to that strategy in the PR. The thing that storybook hub was the ability to comment on a storybook.

**Comment by danielduan** [comment]
I am by no means saying I'm going to build this. I'm just saying hypothetically if I were to build something like this for the open source community when I have free time, I think that would be how the tool would look like. At the moment, the Netlify GitHub integration works well enough for us for checking changes in the PR reviews.

There were a lot of addons in the past such as `storybook-database`, `storybook-comments`, etc.  that required custom setup and a combination of backend services for it work. We've deprecated all of those for simplicity purposes.

If you'd like to give something like recreating the Storybook Hub a try and open source it for the community, we would more than welcome your contribution if is something a lot of people can find useful.
