### ISSUE TITLE
Add platform support for haul react-native bundler

### ISSUE THREAD

**Issue by z4o4z** [storybooks/storybook#2128]
Currently when I'm using --haul option to start React-Native Storybook, Haul starts processing code for both platforms:

![screenshot at oct 26 12-41-29](https://user-images.githubusercontent.com/9130301/32046299-59e450fa-ba4b-11e7-9db3-3a5bae7bac76.png)

And sometimes it causes the problems:

![screenshot_20171026-123512](https://user-images.githubusercontent.com/9130301/32046315-66d4260a-ba4b-11e7-80c6-ddb72c48ed55.png)

After some research, I found that problem is Android device trying to run js code bundled for iOS.

To solve this problem I just changed `--platform all` to `--platform android | ios` in the `storbook-start.js` script

**Comment by danielduan** [comment]
published in `3.2.13`
