### ISSUE TITLE
Channel in storybook during the registeration doesn't catch the events

### ISSUE THREAD

**Issue by alexeybondarenko** [storybooks/storybook#2130]
Looks like this code is not working as expected. I expect to catch a test event and have `check test` in console. Do I do something wrong?
 
```js
import 'babel-polyfill';
import addons from '@storybook/addons';

addons.register('test', () => {
  console.log('register test');
  const channel = addons.getChannel();
  channel.on('test', () => {
    console.log('check test');
  });
  channel.emit('test');
});
```

**Comment by Hypnosphi** [comment]
In storybook, there are two JS environments: manager (the UI with panels), and preview. In `3.2`, you can only send events from manager to preview and vice versa. This [changes](https://github.com/storybooks/storybook/pull/1407) in the upcoming minor release, so you might want to try the alpha (`3.3.0-alpha.2`) version of `@storybook` packages

**Comment by alexeybondarenko** [comment]
@Hypnosphi thanks!
