### ISSUE TITLE
Links Addon + Knobs Addon = broken browser history

### ISSUE THREAD

**Issue by SuperOl3g** [storybooks/storybook#2134]
![screencast-2017-10-27-00-38-44](https://user-images.githubusercontent.com/11710986/32078872-2adf06ea-bab1-11e7-8a1f-1b01d35aa8f9.gif)

AFAIK knob addon change URL value many times before it finally loaded.
Does anyone have an idea how to fix it?

**Comment by Hypnosphi** [comment]
We should use `replaceState` instead of `pushState` most of the times

**Comment by shilman** [comment]
[3.2.15 released](https://github.com/storybooks/storybook/releases/tag/v3.2.15). Closing this--let us know if you're still having this issue!
