### ISSUE TITLE
Running storybook on my app's webpack or own route

### ISSUE THREAD

**Issue by ajnassar** [storybooks/storybook#2135]
Hello,

I am working with storybook right now, and my rails5 app already has webpacker. I want to be able to use the css in my app in the same storybook. I don't know how to hook it up so I am wondering if the storybook lived under my app instead on its own, maybe it would inherit the css.

So I guess my question is a to part. How do I get my app's css to go through to storybook dynamically like how the asset pipeline and webpack work so I don't have to import a ton of css files in my config?

Or

If that isn't possible can I run storybook on my rails server on its own route something like, example.com/styleguide?

**Comment by tmeasday** [comment]
Hi @ajnassar -- that's interesting; You can actually embed the preview iframe (the part of storybook that renders the stories) inside your app (I won't say easily, but it can be done, I have experimented with this a little).

However, I think rendering the *full* storybook (the "manager") may be a bit more difficult. This is due to the fact that the storybook having its own requirements for CSS etc. It really isn't intended to live inside another app.

It would be interesting to consider refactoring storybook in this way in the future but I'm not sure it would be easy!

**Comment by ajnassar** [comment]
Thanks for the quick reply and sounds interesting but I don't want to go that deep. I rather implement a styleguide a different way if it comes to doing too much work.

I think the main thing I need is I need my components that I am showing through storybook to be styled somehow and what better way to style them with the stylesheets you already have in your codebase. Is there a way I can do this?

I notice that in the examples all the components and stories are styled in some way or fashion, but I am not sure how they are styled. It might be my bad understanding of webpack or something else. 

Any ideas?

**Comment by tmeasday** [comment]
It depends on how the styling for your app is setup. 

Often it is just `import`-ed from a central frontend entry point in a global way. In such cases you just need to make the same `import`s in your `.storybook/config.js`.

**Comment by marchdoe** [comment]
@ajnassar - Did a quick search on github for some examples and found these.

https://github.com/tai2/webpacker-react-example
https://github.com/lbain/rise
https://github.com/assembleapp/assemble

I am not sure how good any of the implementations are, however it might point you in the right direction. Hope that helps.

**Comment by ajnassar** [comment]
Thanks all for the help. Going to try to reconcile my app's webpack.config.js with storybook's. Have them both resolve the directory where my styles are and then import them in my respective entrypoints. Not sure how to do this yet but I will figure it out with all the examples out there. The documentation isn't the best :(

**Comment by ajnassar** [comment]
Ok so an update here. On my rails app I upgraded to webpacker 3 and I have some resolved paths pointing to app/assets/stylesheets where my current css lives. Now what I need to do is do the same for storybook, but I can't figure out how to do it yet. 

I have read all through the documentation and have tried all sorts of things but it just doesn't work. 
Any thoughts/ideas?

currently my webpack.config.js in storybook looks like this:
```const path = require('path')

module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
        include: path.resolve(__dirname, '../')
      }
    ]
  }
}```

I thought I could just add 
```
resolve: {
    modules: ["node_modules", path.resolve(__dirname, '../app/assets/stylesheets')]
}
```

But ya that doesn't work.
