### ISSUE TITLE
ERROR in Loader /mantraproject/node_modules/css/index.js didn't return a function

### ISSUE THREAD

**Issue by ickyrr** [storybooks/storybook#214]
Need help with loading less file, still new to mantra and having a very difficult time with this. I installed the following modules:

less
less-loader
style-loader
raw-loader

I followed the the webpack's instructions [here](https://github.com/webpack/less-loader) but could not get it to work.

```
ERROR in Loader /mantraproject/node_modules/css/index.js didn't return a function
 @ ./client/assets/stylesheets/style.less 4:14-174 13:2-17:4 14:20-180
```

**Comment by mindjuice** [comment]
Not sure if you're asking for mantra or storybook, but my `webpack.config.js` for storybook handles `.less` files (and images and fonts):

```
const path = require('path');

module.exports = {
  module: {
    loaders: [
      {
        test: /\.less?$/,
        loaders: [ 'style', 'css', 'less' ],
        include: path.resolve(__dirname, '../')
      }, {
        test: /\.(jpg|png)$/,
        loader: 'url?limit=25000',
        include: path.resolve(__dirname, '../stories/')
      }, {
        // Fonts
        test: /\.(woff|woff2|ttf|eot|svg)$/,
        loader: 'file',
        query: { name: 'fonts/[name].[ext]' },
      }
    ]
  }
}
```

**Comment by ickyrr** [comment]
@mindjuice - did you install other loaders?

**Comment by ndelangen** [comment]
Please re-open if you are still experiencing this issue 👍
