### ISSUE TITLE
Document how to run tests locally

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2146]
Our testing process is getting more complicated.

We should document how to go about running the snapshots and integration tests in `CONTRIBUTE.md` and how to update them too.

**Comment by ndelangen** [comment]
If anyone wants to pick this up, I can help explain the process!

**Comment by syneva-runyan** [comment]
I'd love to pick up this issue!

**Comment by danielduan** [comment]
@syneva-runyan thanks! I think it's helpful to have the repo set up locally for yourself to try out the tests first. Basically, `yarn bootstrap` to install all the dependencies and then `yarn test` to run the tests.

@ndelangen are you aware that the cra and rn-vanilla tests would not run if the screenshot option isn't checked?

**Comment by ndelangen** [comment]
No I am not, did I make a mistake when adding the integration tests?

**Comment by ndelangen** [comment]
@syneva-runyan I have time this evening, if you want to join our slack, we can have a bit easier communication and I'll try and explain the process as best I can 😄 

https://now-examples-slackin-nqnzoygycp.now.sh/

**Comment by danielduan** [comment]
@ndelangen yeah, it throws a promise rejected error or something like that. Let me know if that happens for you too.

**Comment by syneva-runyan** [comment]
Created a pull request here https://github.com/storybooks/storybook/pull/2224
