### ISSUE TITLE
Speed up CircleCI integration tests

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2179]
The test kitchen CI feels like it takes a bit too long.

We can investigate ability to save the build pack into an artifact and then running tests on them.

**Comment by danielduan** [comment]
Create artifact bundles in CI and set up different stages could be an idea: https://circleci.com/docs/1.0/configuration/#artifacts

**Comment by Hypnosphi** [comment]
We use CircleCI 2.0. Is it still an option there?

**Comment by danielduan** [comment]
Yup https://circleci.com/docs/2.0/artifacts/#artifacts-overview
