### ISSUE TITLE
Searchbox. Overflow row if a story name too long. 

### ISSUE THREAD

**Issue by dmitrymalakhov** [storybooks/storybook#2183]
![screenshot from 2017-10-30 16-49-18](https://user-images.githubusercontent.com/2477267/32174809-f2c7d3dc-bd93-11e7-8cc5-1909a43896e6.png)

![screenshot from 2017-10-30 16-49-09](https://user-images.githubusercontent.com/2477267/32174820-fe4b7f9c-bd93-11e7-910e-091bddeb2fc8.png)

Chromium Version 62.0.3202.62

**Comment by danielduan** [comment]
We'd love to get a PR for this if you're interested in fixing it

**Comment by Hypnosphi** [comment]
There's a chance it should be fixed on [`react-fuzzy`](https://github.com/ritz078/react-fuzzy-search) side

**Comment by jozefpetro** [comment]
Hello, I would like to fix this :) can you assign it to me ? @danielduan

**Comment by Hypnosphi** [comment]
@jozefpetro It's an external component. Please open a PR in its repo: https://github.com/ritz078/react-fuzzy-search

**Comment by jozefpetro** [comment]
Oh I see, I will let you know once it’s done.

**Comment by jozefpetro** [comment]
Hey, I went through fuzzy-search-component and found out that we are using custom implementation for item template so I think that it should be also fixed on our side. Here is the function that is passed to react-fuzzy as resultsTemplate prop.

``` javascript
const suggestionTemplate = (props, state, styles) =>
  state.results.map((val, i) => {
    const style = state.selectedIndex === i ? styles.selectedResultStyle : styles.resultsStyle;
    return (
      <div key={val.value} style={style}>
        {val.value}
        <span style={{ float: 'right', opacity: 0.5 }}>
          {val.type === 'story' ? `in ${val.kind}` : 'Kind'}
        </span>
      </div>
    );
  });
```

and here is my idea of how it can be fixed
``` javascript
const suggestionTemplate = (props, state, styles) =>
  state.results.map((val, i) => {
    const style = state.selectedIndex === i ? styles.selectedResultStyle : styles.resultsStyle;
    return (
      <div key={val.value} style={{ ...style, display: 'flex', justifyContent: 'space-between' }}>
        <p style={{ margin: 0 }}>{val.value}</p>
        <p style={{ opacity: 0.5, margin: 0, paddingLeft: 10 }}>
          {val.type === 'story' ? `in ${val.kind}` : 'Kind'}
        </p>
      </div>
    );
  });
```

here is how it will look like after that
<img width="436" alt="screen shot 2017-12-03 at 21 23 24" src="https://user-images.githubusercontent.com/15748491/33525304-3d196670-d870-11e7-8697-bc63c90343d9.png">

**Comment by Hypnosphi** [comment]
Ok, please send a PR

**Comment by jozefpetro** [comment]
Here it is :) #2419
