### ISSUE TITLE
Use Storybook with plain html patterns (Feature request)

### ISSUE THREAD

**Issue by deporter** [storybooks/storybook#2187]
I would love to see Storybook have an option to build a plain html based pattern library. This seems to work, but the focus is more on using it with React or Vue. I am using the React version with plain html instead of React components. I get an error in console saying it is expecting 'className' instead of 'class'. I assume this is due to React itself. Is there potential that there will be focus on having the ability to use plain html patterns in the future?

**Comment by danielduan** [comment]
I'm gonna say probably not.

You could write your HTML and use dangerouslySetInnerHTML in react after you import your HTML files as strings though.
https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by Hypnosphi** [comment]
Actually, Storybook for Vue can be used as Storybook for plain HTML:
```
import { storiesOf } from '@storybook/vue';

storiesOf('WIdgets', module)
  .add('hello', () => ({
    template: `
      <div>
        <h1>Hello!</h1>
      </div>
   `
  }))
```

**Comment by deporter** [comment]
Thanks guys, I will try out the Vue approach.
