### ISSUE TITLE
Info addon, propTypes show up as other

### ISSUE THREAD

**Issue by TimGraf** [storybooks/storybook#2198]
We are using the info addon for storybook and the propType in the Prop Types table always show up as "other".  The required attribute seems to work correctly.

We are using the following versions.

```
"dependencies": {
   ...
   "prop-types": "15.5.10",
   ...

"devDependencies": {
   "@storybook/addon-info": "^3.2.13",
   "@storybook/react": "^3.2.13",
   ...
```

This issue is similar to a previously reported issue.
https://github.com/storybook-eol/react-storybook-addon-info/issues/145

**Comment by danielduan** [comment]
This is a known bug for a while. If you have some time to dig into why it's happening, we'd really appreciate it.

**Comment by TimGraf** [comment]
@danielduan So I forked the repo and looked at the info addon and noticed in the example storybook for the info addon the propTypes were displaying as expected.  So the bug had to be in our code.  I then looked more closely at our code and found the issue.

We were exporting our component as follows.

```
export const DataTable = ({
...
// we define the component and set prop types
...
export default DataTable
```

I removed the first export and we now have prop types displaying as expected with the info addon.

```
const DataTable = ({
...
// we define the component and set prop types
...
export default DataTable
```

I can close this issue if you'd like.

**Comment by danielduan** [comment]
thanks for reporting back! I think the propType detection support for named exports is definitely a bit shaky.

**Comment by adamgen** [comment]
It still happens, was it fixed or  is it the same issue since?

**Comment by shilman** [comment]
Addon-info is being superceded by addon-docs, which fixes a bunch of bugs and is easier to maintain. Please give it a try! medium.com/storybookjs/storybook-docspage-e185bc3622bf
