### ISSUE TITLE
getstorybook changes package.json indentation from tabs to spaces

### ISSUE THREAD

**Issue by tansongyang** [storybooks/storybook#2205]
## Steps

1. `mkdir test-proj`
2. `cd test-proj`
3. `npm init`. Keep all defaults.
4. Convert spaces in `package.json` to tabs.
5. `npm install react`
6. `getstorybook --use-npm`

## Result

`package.json` now has spaces.

## Expected

`package.json` should still have tabs.

**Comment by danielduan** [comment]
We don't actually write to your `package.json`. That's `npm`
https://github.com/npm/npm/issues/4718

You should switch to yarn or upgrade to npm5.

**Comment by tansongyang** [comment]
I see. Thanks for clearing that up.

**Comment by Hypnosphi** [comment]
> We don't actually write to your package.json.

That's actually not true at the moment: https://github.com/storybooks/storybook/blob/master/lib/cli/generators/REACT/index.js#L16-L18

**Comment by danielduan** [comment]
is this a bug that we should fix?
