### ISSUE TITLE
Info description strings containing React components get rendered as React components

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2207]
If I pass in a React component to `withInfo(markdown)`

```
const markdown = `
~~~js
  // source file for button
  <Button />;
~~~
`;
```

This will actually render `<Button />` into `<button></button>`

workaround is to escape the `<`

caused by marksy: https://github.com/cerebral/marksy/issues/26

**Comment by Hypnosphi** [comment]
> workaround is to escape the `<`

Should we do it maybe?

**Comment by danielduan** [comment]
If there's a desire on our side to maintain something like that, I don't see why not.

Basically something like if string is wrapped inside '~~~' and has tag, escape the open?

**Comment by Hypnosphi** [comment]
No, there are multiple ways to add code blocks in markdown, so it doesn't look such a good idea to me now.

So I would pick one of the options:
1. Apply the `highlight` workaround I mentioned here: https://github.com/cerebral/marksy/issues/26#issuecomment-342015940
2. Migrate to [`react-markdown`](https://github.com/rexxars/react-markdown), which has a similar API

**Comment by Hypnosphi** [comment]
Looks like we have a third option here =)
https://github.com/cerebral/marksy/issues/26#issuecomment-342068635
