### ISSUE TITLE
lint-staged pre-commit is broken on 3.3 branch

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2211]

**Comment by Hypnosphi** [comment]
It used to break after running CLI test, and the fix was just running `yarn install`. But this shouldn't be the case after merging #2201

**Comment by danielduan** [comment]
Right now, if I try to do `git commit`, it throws an error unless I use the `--no-verify` flag. I think we should fix it or get rid of it.

**Comment by Hypnosphi** [comment]
Can you please paste the error here?

**Comment by danielduan** [comment]
Okay yeah, that fix must have been it. Just pulled the latest release/3.3 and seems to be fine.
