### ISSUE TITLE
A change to one component yields hundreds of updated snapshots

### ISSUE THREAD

**Issue by brandondurham** [storybooks/storybook#2215]
In our codebase we have one test file for each component, most with several tests. This is included  at the top of each test file:

```
import initStoryshots from '@storybook/addon-storyshots';
initStoryshots();
```

If I add the text “Hello” to my button component which appears in approximately 6 components. This is the result after running tests:

```
Snapshot Summary
 › 659 snapshot tests failed in 48 test suites. Inspect your code changes or run with `yarn run test:watch -- -u` to update them.

Test Suites: 48 failed, 83 passed, 131 total
Tests:       659 failed, 5229 passed, 5888 total
Snapshots:   659 failed, 4671 passed, 5330 total
Time:        36.888s
Ran all test suites.
```

Updating the snapshots after failure returns this:

```
Snapshot Summary
 › 659 snapshots updated in 48 test suites.

Test Suites: 131 passed, 131 total
Tests:       5888 passed, 5888 total
Snapshots:   659 updated, 4671 passed, 5330 total
Time:        30.801s, estimated 32s
Ran all test suites.
```

Why are there 659 snapshots updated when the button only appears in 6 components?

**Comment by shilman** [comment]
@brandondurham 

```
import initStoryshots from '@storybook/addon-storyshots';
initStoryshots();
```

I think you just need to do this once for your entire codebase?

**Comment by brandondurham** [comment]
This bit in the README made me think it was for every test file:

> Create a new test file with the name `Storyshots.test.js`. (Or whatever the name you prefer, as long as it matches Jest's config [`testMatch`](http://facebook.github.io/jest/docs/en/configuration.html#testmatch-array-string)).
Then add following content to it:
>
>```js
>import initStoryshots from '@storybook/addon-storyshots';
>
>initStoryshots();
>```
>
>That's all.

Is it saying to create _that single file_ with only that init code and all other test files will pick it up?

**Comment by shilman** [comment]
Yep, storyshots creates snapshots from the storybook stories, so it will pick up whatever you're loading in your storybook config AFAIK. If that doesn't work, let me know!
