### ISSUE TITLE
[Feature request] Support for Aurelia

### ISSUE THREAD

**Issue by miguelzakharia** [storybooks/storybook#2226]
We use Aurelia heavily in our projects and having Storybook support Aurelia would be very useful. I understand there are other priorities, but just wanted to drop a request for this.

Thanks for the great work!

**Comment by danielduan** [comment]
Aurelia has definitely been an idea that's floated around in the past. We are open to community contributions for new platform support and if you or anyone else would like to dedicate some development time for it, we would love getting a PR.

**Comment by ndelangen** [comment]
Hi @miguelzakharia Thank you for the interest and effort opening a ticket!
These types of request warm my heart : bringing the communities together here!

I've previously met with @meelisd and @eriklieben and spoke about exactly this!

I'm all for it, and want to help make it happen! In fact just today I've worked with @naipath and @stijnkoopal and @leonrodenburg to get a Storybook for Polymer off the ground! https://github.com/storybooks/storybook/pull/2225

Though I'm unable to learn and be an expert in every UI library/framework in the JS ecosystem; I'm very very interested in helping out in the way I can: Pairing with people knowledgeable in Aurelia and together taking it step by step to build the support.

**Comment by weagle08** [comment]
until this feature exists there is something similar that is just for Aurelia: [Front End Creator](http://www.frontendcreator.com/)

**Comment by rowellx68** [comment]
Is Aurelia support still in the pipeline?

Some documentation as to how to add support for new front-end frameworks would be great.

**Comment by shilman** [comment]
@rowellx68 If you're interested in working on this, jump on our Discord and we can probably help you get going. It's still not documented, but it's a well-traveled path by this point. cc @ndelangen

**Comment by tomtomau** [comment]
Hey @rowellx68, have you started on the Aurelia support? I'd be keen to help out possibly?

**Comment by rowellx68** [comment]
@tomtomau I've got something very very basic [here ](https://github.com/rowellx68/storybook/tree/aurelia). Any help would be great. Currently battling the `Cannot find 'fs' module` issue.

**Comment by brandonseydel** [comment]
Anyone interested Aurelia 2 support is in my fork.  Once post alpha we will clean up and hopefully a PR will be accepted.

**Comment by ndelangen** [comment]
@brandonseydel A PR would definitely be accepted, do you need my help?

**Comment by brandonseydel** [comment]
Take a look in my repo.  I am cleaning up some things still, but it is working well it seems.

**Comment by brandonseydel** [comment]
After Aurelia 2 releases and this is merged can we get a spot on the homepage and in docs?

**Comment by shilman** [comment]
@brandonseydel Absolutely!
