### ISSUE TITLE
Is there a way to manually specify PropTypes? 

### ISSUE THREAD

**Issue by octalmage** [storybooks/storybook#2230]
I'm using Storybook for a [Reason](https://reasonml.github.io/) React project, and I would like to manually specify the proptypes for the docs since storybook can't find them.

**Comment by ndelangen** [comment]
Wow, that's pretty cool!

I think so actually! Normally we depend on a babel-plugin to extract the proptype information and place it in a global:

<img width="578" alt="screen shot 2017-11-04 at 21 18 34" src="https://user-images.githubusercontent.com/3070389/32409111-c7c7f278-c1a5-11e7-9392-fc4adf80d783.png">

This needs to be included in the preview bundle somehow.

**Comment by octalmage** [comment]
@ndelangen Awesome thank you! I'll give that a try.

**Comment by octalmage** [comment]
Got it working: 

https://github.com/octalmage/react-lastfm-widget/commit/956d59864cf9ad9d2921a87c9bee0d8c2ad7c0e3#diff-11c4ac4e1cb7b4cc2a07b3af5730890dR140

Thanks again! If I continue to use Reason for bigger projects I'd love to work on extracting this information in an automated fashion.
