### ISSUE TITLE
Default Set Up for CRNA Not Working

### ISSUE THREAD

**Issue by nickzuber** [storybooks/storybook#2235]
I followed the basic steps for set up and ran the commands:

```
npm -g i @storybook/cli
getstorybook
```

After installation, I replaced the contents of `App.js` with 

```
export default from './storybook';
```

And then ran 

```
npm run storybook
```

And when I went to `localhost:7007`, I saw exactly what was expected besides on the sidebar, there were no stories. I checked my `./storybook` directory and everything looked fine, but for some reason nothing was showing up for me in the storybook UI. I get no errors in the console. Any idea what could be the cause here?

**Comment by Hypnosphi** [comment]
The browser UI is only for navigation. To actually see the stories on your device, you need to follow the instructions for your platform: https://github.com/storybooks/storybook/tree/master/app/react-native#start-app

**Comment by ryanmagoon** [comment]
I have it all set up and my app also isn't showing anything in the side bar, even though my simulator is connected to the server and running storybook's default stuff on the left side.
<img width="1393" alt="screen shot 2017-11-05 at 7 55 15 pm" src="https://user-images.githubusercontent.com/5327290/32421133-4ced2776-c263-11e7-9a1f-53738ff6190d.png">

**Comment by Hypnosphi** [comment]
Do you mean that when you click on hamburger in device simuator, nothing shows up?

**Comment by ryanmagoon** [comment]
Sorry! First time installer. I thought the stories would be populated from my source code. It looks like I need to work on ui components in the `/storybook` directory and then transfer them to where they're going to end up?

**Comment by shilman** [comment]
In storybook for RN the stories don't show up in the browser until storybook is also running on your device or simulator (for reasons that I don't entirely understand). Did you also run the simulator?
