### ISSUE TITLE
Refactor Framework-independent storybook code

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#2240]
## why

Currently there is lots of copy-paste code for each framework (React, Vue, Angular, etc.)

## what

- [ ] Refactor this into a core library
- [ ] Add documentation and tests

**Comment by mAAdhaTTah** [comment]
I'd be interested in contributing to this, as I would love to get storybook integration for a framework I'm working on. I see #2241 in progress. Anything else I could do to help push this forward?

**Comment by ndelangen** [comment]
@mAAdhaTTah Let's chat in our slack, it's actually quite easy already, the PR just addresses a bit of duplicated code.

**Comment by danielduan** [comment]
Can we close this when https://github.com/storybooks/storybook/pull/3261 gets merged?

**Comment by igor-dv** [comment]
There is also #2636 this one.

**Comment by Hypnosphi** [comment]
Can someone gather a list of remaining duplications?

**Comment by Hypnosphi** [comment]
I'm going to start refactoring out `html.ejs` templates and error / nopreview views

**Comment by Hypnosphi** [comment]
Can anyone find anything else left to refactor? I can't =)
