### ISSUE TITLE
ShellJS Security Warning

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2242]
There's a `SEVERE` security warning for one of the dependencies we're using.
https://www.bithound.io/github/storybooks/storybook/master/dependencies/npm/shelljs#security-advisories

Is it something we're concerned about? Should we move off of it? Help patch it?

**Comment by Hypnosphi** [comment]
@ndelangen You had some considerations AFAIK

**Comment by danielduan** [comment]
gonna close this then.

**Comment by Hypnosphi** [comment]
> because this is first and foremost a devDependency

not anymore
https://github.com/storybookjs/storybook/blob/next/lib/core/package.json#L82

**Comment by ndelangen** [comment]
Hmm..

Still not vulnerability:
We use the `.mkdir` & `.cp` commands in user executed code:
https://github.com/storybookjs/storybook/blob/9835ab9d7982b3125a96582577b5b96dd2fee0d5/lib/core/src/server/build-static.js#L170

We do not use `.exec` in this context.

**Comment by Hypnosphi** [comment]
BTW, is there any reason not to use builtin `fs` module for that?
