### ISSUE TITLE
React-Native menu button and story title partially hidden on iPhone X

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2243]
screenshot from simulator:

![screen shot 2017-11-06 at 12 11 02 pm](https://user-images.githubusercontent.com/1474548/32453925-a86a9b14-c2eb-11e7-88ae-1f3cd03e131d.png)

related to: https://github.com/storybooks/storybook/issues/2102

**Comment by ndelangen** [comment]
Looks like a bug in the simulator to me, where's this dumb black blob on the top coming from?

**Comment by Hypnosphi** [comment]
@ndelangen https://www.apple.com/iphone-x/

**Comment by ndelangen** [comment]
I feel like Apple is trolling us.

**Comment by danielduan** [comment]
What if I told you I bought one? 😇

**Comment by ndelangen** [comment]
Then I think I know who's going to fix it. /troll

**Comment by ndelangen** [comment]
Thanks for fixing @danielduan !!!
