### ISSUE TITLE
Storyshots and jest --watch

### ISSUE THREAD

**Issue by slorber** [storybooks/storybook#2259]
Hi,

There are features in Jest that prevent from running the whole test suite if only a single file has been modified (see `-o`, `--watch`, `--findRelatedTests` ...)

I have setup Storyshots on my project, but for example running `jest --watch -o` does seem to trigger all the storyshot test suite even if I touch a single file.

Can Storyshots and Jest work correctly this way or it's too hard for Jest to track correctly the dependencies when using initStoryshots?

**Comment by macrozone** [comment]
@slorber did you come up with a solution for this? unfortunatly, the stale bot closed the issue

**Comment by igor-dv** [comment]
There are already few open issues about this. But meanwhile no progress

**Comment by slorber** [comment]
no, not working on that project anymore. Note if you think it's still not fixed and there's no open issue you may try to reopen a new one as closed issue comments are often ignored
