### ISSUE TITLE
Share storybook guidelines to ease addon integrations

### ISSUE THREAD

**Issue by Spy-Seth** [storybooks/storybook#2263]
I'm writing addons for some of the internal storybook of company. 

To integrate them correctly in the storybook UI I have to explore the source code of the existing official addons to copy/paste some of the styled component. It could be really nice if storybook share some button, title, manager panel style, form input in reusable way to allow addons authors to make event more beautiful addons 😻 

What did you think about this?

**Comment by Hypnosphi** [comment]
We have something like this on our roadmap, and you can actually help with it. The idea is to move the reusable components from addons and manager ui sources to `@storybook/components` package (located at `lib/components`), and move the styling from inline styles to [`glamorous`](https://glamorous.rocks/)

Feel free to reach us on slack if you're interested: https://now-examples-slackin-nqnzoygycp.now.sh/

**Comment by Spy-Seth** [comment]
I like that I'm not the first to have the same idea 😄 I could try to give you a hand on this 👍
