### ISSUE TITLE
Info Addon - Hide Prop Types

### ISSUE THREAD

**Issue by mattferderer** [storybooks/storybook#2266]
Is it possible or would a pull request be allowed to create an option for the Info add-on to allow hiding the prop types section or replacing it with text? 

For those of us using TypeScript, it would be nice if we could hide it or replace it with custom text.

**Comment by danielduan** [comment]
There's an option to pass an array of components to exclude.
https://github.com/storybooks/storybook/tree/master/addons/info#options-and-defaults

**Comment by mattferderer** [comment]
If I'm correct, those say I should be able to do something like this:

```jsx
storiesOf("ComponentName", module)
  .add("Test Component", 
    withInfo({propTablesExclude: [(<ComponentName />)], text: 'Text about component.'})(() => {
      return (
        <ComponentName />
      )
    })
  )

```

**Comment by danielduan** [comment]
correct.

**Comment by mattferderer** [comment]
Interesting. Not working for me but I'll investigate & open a new issue if I can find that it is a bug & not something wrong with TypeScript or my particular instance. 

Thank you.

**Comment by mbellgb** [comment]
@mattferderer I managed to get it working by passing the component itself rather than the rendered component.

E.g.:

```javascript
setDefaults({
  propTablesExclude: [ComponentName],
  ...
});
```

Instead of:

```javascript
setDefaults({
  propTablesExclude: [ <MyComponent /> ],
});
```

This wasn't that apparent when reading the documentation. Perhaps it's worth explaining this is what should be passed into the options rather than the rendered components? I only worked this out by reading the source code and seeing that `propTablesExclude` was expected to be an array of functions.

**Comment by mattferderer** [comment]
@danielduan would adding a pull request to the docs to include an example like @mbellgb showed be acceptable?

**Comment by danielduan** [comment]
@mattferderer would really appreciate that. sorry for the confusion.

**Comment by mattferderer** [comment]
I'll try & make a pull request today or tomorrow then, unless someone beats me to it.

**Comment by vanpacheco** [comment]
I feel that hiding all of the prop types could be a useful feature. Right now the way to achieve that is by filling the `propTablesExclude` array, but if a component is created inside a story, then it will appear in the props table.

**Comment by shilman** [comment]
@vanpacheco Working on a full replacement for `addon-info` that will have this feature and a lot more. Current progress:

<img width="752" alt="Storybook" src="https://user-images.githubusercontent.com/488689/57824514-dfe77600-77cd-11e9-9253-b78079c9f8d2.png">

More information about the project: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a
