### ISSUE TITLE
addon-knobs: Failed prop type: Invalid prop `knob.value` of type `array` supplied to `ObjectType`, expected `object`

### ISSUE THREAD

**Issue by cuzzins** [storybooks/storybook#2268]
The documentation for the object knob states:
Allows you to get a JSON object or array from the user.

But I get an error in console that it expects only an object:
Failed prop type: Invalid prop `knob.value` of type `array` supplied to `ObjectType`, expected `object`

The rendering still works correctly, so am assuming something is wrong in the prop type check

This is with the latest version

**Comment by danielduan** [comment]
If you'd like to open a PR for this, we'd really appreciate it.

**Comment by cuzzins** [comment]
Looks like it was fixed a few days ago so should be in the 3.3 release: https://github.com/storybooks/storybook/pull/2227

Apologies, did do a search but didn't find anything originally, will close.

**Comment by Hypnosphi** [comment]
Yeah, that's actually fixed twice =D #1701 #2227
So the fix included in `3.3.0-alpha.3` and will be included in `3.2.15`

**Comment by cuzzins** [comment]
Glad I didn't fix it a third time! ;-)  Thanks folks!
