### ISSUE TITLE
OnDeviceUI/menu_open.png:1 BUG

### ISSUE THREAD

**Issue by Amurmurmur** [storybooks/storybook#2277]
Hi there,
Running latest react-native v.0.50.3
Jest started to fail with the following error:
```
Test suite failed to run

    /node_modules/@storybook/react-native/dist/preview/components/OnDeviceUI/menu_open.png:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (node_modules/@storybook/react-native/dist/preview/components/OnDeviceUI/index.js:51:21)
      at Object.<anonymous> (node_modules/@storybook/react-native/dist/preview/index.js:47:19)

```
My package.json contains following packages:
```
"jest": "21.2.1",
"enzyme": "2.9.1",
"@storybook/addon-storyshots": "^3.2.13",
"@storybook/react-native": "^3.2.13",
"react": "16.1.0",
"react-native": "0.50.3",
```
Not too sure if the problem is with storybook not supporting latest react-native or so.

**Comment by danielduan** [comment]
you might need to stub the file when running rest.

**Comment by Amurmurmur** [comment]
@danielduan What do you mean?

**Comment by danielduan** [comment]
You'll need to mock your file imports when running jest because PNG is a binary and can't technically be inserted into a snapshot.

**Comment by Amurmurmur** [comment]
@danielduan Alright found the solution:
```
yarn -D add identity-obj-proxy@^3.0.0
package.json:
"jest": {
"moduleNameMapper": {
      "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "identity-obj-proxy"
    },
}
```

**Comment by mfru** [comment]
@Amurmurmur So I'm trying to test my App.js with a simple render test and I'm having the same issue. I'm using CRNA with Expo 25. 

As seen in [Jest Preset in React Native](https://github.com/facebook/react-native/blob/master/jest-preset.json#L10) there should be a mock for png files. 

I also tried using `identity-obj-proxy`, but the error keeps throwing.

Am I overlooking something important?

I don't seem to find a solution for this.
