### ISSUE TITLE
Mocking Imports in Storyshots

### ISSUE THREAD

**Issue by merlinpatt** [storybooks/storybook#2278]
I have a component similar to the following that outputs some random text. This causes problems when I use storyshots because the text changes every time.

How can I set up a mock for the `randomText` function within storyshots?

```
import randomText from './randomText';

const Component = () => (
  <span>
    {randomText()}
  </span>
);
```

**Comment by ndelangen** [comment]
Storyshots is a jest test.. You could mock the './randomText' have it return static data?

**Comment by merlinpatt** [comment]
That's my plan, to use static data, but I'm not sure where to put the mock. Do I put it above `initStoryshots`? Do I pass it to `snapshotWithOptions`?

**Comment by ndelangen** [comment]
before `initStoryshots` should do.

**Comment by merlinpatt** [comment]
That worked. I did

```
jest.mock('../randomText', () =>
  () => `random`
);

initStoryshots();
```

Thank you!
