### ISSUE TITLE
Addon backgrounds shows setup instructions after toggling down panel

### ISSUE THREAD

**Issue by desaias** [storybooks/storybook#2280]
When using the keyboard shortcut to toggle the down panel, it causes the backgrounds addon to show the setup instructions.  Refreshing the page or going to another story and back are the only ways to get the background color options back.

![storybook-addon-backgrounds](https://user-images.githubusercontent.com/3411447/32643558-399db7f4-c5aa-11e7-83a2-4933ed62de41.gif)

**Comment by Hypnosphi** [comment]
The same bug is observed in notes addon

**Comment by danielduan** [comment]
Published in 3.2.17
