### ISSUE TITLE
Action logger not showing logs using react native

### ISSUE THREAD

**Issue by dstollie** [storybooks/storybook#2283]
In a story we try use the `action('validate barcode')` method to send actions. But for some reason the action logger does not present them.

--- Update
We've figured out that `action` does not work inside a closure

This doesnt work:
```javascript
onClose={() => {action('close')}}
```

This does work:
```javascript
onClose={action('close')}
```

# Situation
- Yarn
- React v0.50
- Node 8.5.0
- React 16

**Comment by Hypnosphi** [comment]
`action(name)` doesn't log anything by it self, it returns a logger function. You can either pass it directly as a handler (`onClose={action('close')}`), or call it:
```
onClose={(...args) => {
  /* do your stuff */
  action('close')(...args)
}}
```
