### ISSUE TITLE
React-Native menu does not fully close

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2301]
This is due to the last UI refactor to make Storybook iPhone X compatible. It regressed on regular iOS devices.

- [ ] make one of the CRNA example backgrounds a darker color so we can catch regressions like this

<img width="280" alt="screen shot 2017-11-13 at 3 06 20 pm" src="https://user-images.githubusercontent.com/1474548/32746662-511058e2-c884-11e7-876f-60d481502f3e.png">

**Comment by danielduan** [comment]
#2300 should fix this.

**Comment by smooJitter** [comment]
How do I hide the menu.
