### ISSUE TITLE
Storybook menu on device not hiding with update 3.2.15

### ISSUE THREAD

**Issue by lee-d** [storybooks/storybook#2306]
Hi,
since the update to 3.2.15 the storybook menu on the simulators (android and ios) is not completely hiding anymore.

![visiblemenu](https://user-images.githubusercontent.com/452808/32771560-53840476-c923-11e7-8d59-c9e9f556c255.png)

**Comment by danielduan** [comment]
This duplicates https://github.com/storybooks/storybook/issues/2301 and has been fixed on master. We will publish a new version soon.
