### ISSUE TITLE
knob array of objects not working as expected

### ISSUE THREAD

**Issue by tsvetann** [storybooks/storybook#2310]
Version:
`"@storybook/addon-knobs": "^3.2.15"`

Usage:
```
stories
  .add('scatter', () => {
    const value = array('Data', measurements);
    return <ScatterChart width={600} height={400} min={60} data={value}></ScatterChart>
  })
```

measurements:
```
[
    {
        "high": 80,
        "time": "03:30"
    },
    {
        "high": 120,
        "time": "07:00"
    },
    {
        "high": 10,
        "time": "12:45"
    }
]
```

knob:
<img width="384" alt="screen shot 2017-11-15 at 10 17 01" src="https://user-images.githubusercontent.com/2565891/32829008-103fbd12-c9f1-11e7-977a-80c6a22ef190.png">

Expected:
To have the actual object representation and be able to interact with them via UI

Thx

**Comment by danielduan** [comment]
This should be taken care of by https://github.com/storybooks/storybook/pull/1460 but the pull request appears to have been abandoned.

**Comment by Hypnosphi** [comment]
You can actually pass JSON-serializeable arrays to `object` knob, like this:
```
const value = object('Data', measurements);
```

#1460 is for non-serializeable stuff like functions, which is not your case

**Comment by tsvetann** [comment]
@Hypnosphi Thx. It works now.
