### ISSUE TITLE
Refactor Storybook off of Komposer/Mantra/Podda stack

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2313]
These packages have not been maintained for a while. As a stop gap measure, I've published the offending packages to silence some peer dependency warnings. https://github.com/storybooks/storybook/issues/2303

**Comment by Hypnosphi** [comment]
Ok, I just realized that redux in `core` manages state in preview, and Mantra stack does it in manager. So it will be a separate store, but we can extract some shared helpers anyway

**Comment by danielduan** [comment]
I have second thoughts about even refactoring off this stack.

I spent a good few hours trying to understand how the state management and containers work within the `@storybook/ui` package. It doesn't seem like I can migrate things little by little, and it's a huge effort that'd be better spent just starting fresh with a new UI like the `SBNext` project.

**Comment by shilman** [comment]
Released in alpha: https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.0
