### ISSUE TITLE
Dependency for version of @storybook/channels that doesn't exist

### ISSUE THREAD

**Issue by rsolomon** [storybooks/storybook#2323]
Getting this error on npm install, depending only on version 3.2.15 of the packages:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/channels@^3.2.16
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@storybook/channel-postmessage'
npm ERR! notarget
```

`npm show @storybook/channel versions` does not list `3.2.16` as a published version.

**Comment by danielduan** [comment]
@shilman did we not publish something?

**Comment by shilman** [comment]
@danielduan agree it's probably a race condition. @rsolomon please try again .. i think it was just bad luck.

**Comment by rsolomon** [comment]
Yep, all good now. Thanks!
