### ISSUE TITLE
Storybook-addon-jsx

### ISSUE THREAD

**Issue by wcastand** [storybooks/storybook#2328]
Hi, i'm the creator of [storybook-addon-jsx](https://github.com/Kilix/storybook-addon-jsx) and soon i will leave my job and won't be able to maintain the addon anymore ( no one at my company wants to take over right now).

So i was wondering if you'll be interested in putting storybook-addon-jsx in your monorepo. so it can be maintain and updated with the rest of the ecosystem.

We already didn't maintain it properly and show some warnings about nested <button>.

**Comment by danielduan** [comment]
I'm sure @ndelangen will welcome the contribution under the @storybook org, but it probably won't get merged into the mono repo until we fix all the bugs. It might take a while as we still have some backlog to work through but we will help maintain it in the meantime.

Feel free to transfer the repo and the npm published package to us.

**Comment by ndelangen** [comment]
Can you transfer the repo to the github organisation? And also add me as an admin on the package on npm? 🙇

**Comment by wcastand** [comment]
Hi, thanks for taking the package in :)
I transfered the repo on github and added you as a collaborator on npm.

Let me know if something doesn't work :)
