### ISSUE TITLE
Superfluous vertical scrollbar in fullscreen

### ISSUE THREAD

**Issue by pelotom** [storybooks/storybook#2348]
In full screen mode, there is always a vertical scrollbar with a minute amount of wiggle room (maybe 1 pixel). This is with a brand new storybook:

![image](https://user-images.githubusercontent.com/128019/33107631-5dbc4944-cef5-11e7-85f6-c2c7a3781a42.png)

It doesn't matter what the actual content is or how you resize the window, although if you make it small enough that the content doesn't fit then you'll get 2 scrollbars:

![image](https://user-images.githubusercontent.com/128019/33107732-cf6a2246-cef5-11e7-8a0c-6459adceff46.png)

It seems like the outer scrollbar is completely unnecessary; removing the `overflow: auto` styling on the offending `div` from the dev console fixes it.

**Comment by Hypnosphi** [comment]
Would you like to make a PR?

**Comment by pelotom** [comment]
@Hypnosphi done: #2394

**Comment by tonyleeper** [comment]
I see this same issue in non-fullscreen mode in the top-right panel. Is there a plan to fix it there also?

**Comment by pelotom** [comment]
@tonyleeper I'm seeing this now too (appears to be a new issue in recent versions)... maybe submit a PR?

**Comment by lcsrinaldi** [comment]
Am also seeing this, I would submit a PR but don't know the solution.

**Comment by ndelangen** [comment]
Does this issue exist in the alpha version too?

**Comment by pelotom** [comment]
@ndelangen nope, it seems to be fixed in the alpha.
