### ISSUE TITLE
Not able to change overlay style

### ISSUE THREAD

**Issue by lcsrinaldi** [storybooks/storybook#2352]
https://github.com/storybooks/storybook/blob/0ed6e1f75bbb1a911306be0afdb42742df5cadd8/addons/info/src/components/Story.js#L159

I'm trying to remove some padding from the overlay page, but I saw it's using the default stylesheets object instead of the one from the component state.

Is this on purpose?

**Comment by danielduan** [comment]
Published in 3.2.17
