### ISSUE TITLE
Native storybook with storyshots broken when using knobs

### ISSUE THREAD

**Issue by ktj** [storybooks/storybook#2356]
When using knobs addon in native storybook, storyshots fail
```
 Storyshots › Button › with some emoji

    TypeError: Cannot read property 'STORYBOOK_ENV' of undefined
```

I made a reproduction of the problem:

https://github.com/ktj/storyshots-knobs-repro

run `yarn test`

Problem line: https://github.com/storybooks/storybook/blob/master/addons/knobs/src/index.js#L74
window is undefined in native

**Comment by xdmorgan** [comment]
Adding a script with `global.window = global;` to my Jest config's `setupFiles` array fixed this for me. Having `window` as a global fixes the undefined error which allows the default case to execute.
