### ISSUE TITLE
addon-info - setDefaults styles not working

### ISSUE THREAD

**Issue by luetkemj** [storybooks/storybook#2358]
Not sure if this is a bug or if I am just doing something wrong. 

I've read the docs and viewed the available styles to be overridden in 
`addon-info/src/components/Story.js` but I've had no luck seeing any styles change.

The info is displaying inline so I know that the setDefaults object is working. It is located in my `.storybook/config.js` file and looks like this:

```
// addon-info:
// https://github.com/storybooks/storybook/tree/master/addons/info
setDefaults({
  inline: true, // Displays info inline vs click button to view
  styles: {
    header: {
      body: {
        marginBottom: '10px',
      },
    },
    infoBody: {
      marginTop: '0px',
    },
  },
});
```

Version:
```
@storybook/addon-info: "3.2.16",
@storybook/react: "3.2.16",
```

**Comment by Mujaddadi** [comment]
Same bug here! I appreciate the work of developers in it but for version 3, this repo contains lot of bugs.

**Comment by itsdeezy** [comment]
There seems to be an issue with `withInfo`. The older `addWithInfo` API still works (as of `3.2.17`) with `setDefaults`

**Comment by pedrokermitgoncalves** [comment]
I have the same issue here, I've downgraded `@storybook/addon-info` to v3.2.18 and it works fine on that version, so the problem must has been introduces between there and v3.3.3

**Comment by Hypnosphi** [comment]
@luetkemj do you have a `styles` option in your stories, or is it only in `setDefaults`?

**Comment by pedrokermitgoncalves** [comment]
I have mine on the `setDefaults` in the config file

**Comment by Hypnosphi** [comment]
Then I can't reproduce the issue. 
Can you please create a GitHub repo with minimal reproduction?

**Comment by luetkemj** [comment]
@Hypnosphi I recently upgraded 

```
"@kadira/storybook": "2.35.3",
"@storybook/addon-info": "3.3.9",
```

Styles appear to be working now.

**Comment by Hypnosphi** [comment]
`@kadira/storybook` is an outdated package replaced by `@storybook/react`

**Comment by luetkemj** [comment]
@Hypnosphi thanks - I actually had both installed but was only using @storybook/react. Copypasta error. I'm happy to close this issue if there are no objections.
