### ISSUE TITLE
I want install cordova : npm install g- cordova

### ISSUE THREAD

**Issue by IssamAlhail** [storybooks/storybook#2360]
npm ERR! code E404
npm ERR! 404 Not Found: g-@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[MynameComputer]\AppData\Roaming\npm-cache\_logs\2017-11-23T17_10_36_232Z-debug.log

**Comment by Hypnosphi** [comment]
This is not cordova repository, but you probably need to put the dash before `g`:
```
npm install -g cordova
```
