### ISSUE TITLE
native storybook unable to resolve babel aliases

### ISSUE THREAD

**Issue by ximenean** [storybooks/storybook#2362]
I had a working storybook that broke when upgrading to RN 0.50. It can no longer resolve the babel aliases. The package was created with react-native init

RN: 0.50.3
Storybook: 3.2.16

My babelrc:

```
{
  "presets": ["flow", "react-native"],
  "plugins": [
    ["babel-plugin-module-resolver", {
      "root": ["."],
      "alias": {
        "crypto": "./src/polyfills/modules/crypto/index.js",
        "xenon": "./src"
      }
    }]
  ],
  "env": {
    "test": {
    },
  },
}
```

**Comment by ximenean** [comment]
Looks to be due to a breaking change in RN 0.50.
See https://github.com/facebook/react-native/commit/023ac57337b351959d443133c3c09607c4ffc800

Can be resolved by creating a `rn-cli.config.js` file with the following contents:

```module.exports = {
  getEnableBabelRCLookup() {
    return true;
  },
};```

(taken from https://github.com/facebook/react-native/releases/tag/v0.50.0)

I've not looked in to how storybook resolves references, is this approach just a workaround or the best way forward?

**Comment by ritz078** [comment]
Switch to haul just for storybook. That works.

**Comment by ximenean** [comment]
@ritz078 not for me. Haul runs in to issues with some of my dependencies. Specifically victory-native

**Comment by akiwarheit** [comment]
I'm getting the same error

```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "env": {
    "production": {
      "plugins": [
        "transform-react-constant-elements",
        "transform-remove-console"
      ]
    }
  },
  "plugins": [
    [
      "module-resolver",
      {
        "cwd": "babelrc",
        "root": ["./"],
        "alias": {
          "@assets": "./assets",
          "@domain": "./artifacts/domain",
          "@util": "./artifacts/util",
          "@lib": "./artifacts/lib",
          "@components": "./artifacts/components"
        }
      }
    ]
  ]
}
```

Already have the ff. file above - it still complains `Module @components does not exist in the Haste module map`

Already have the `rn-cli.config.js` file above, app works fine - just storybook.

**Comment by alanbueno** [comment]
any news regarding this one? 
same thing here, app works fine but when running storybook babel's not able to resolve any alias while pointing the --projectRoot storybook instead of replacing the app entry point
