### ISSUE TITLE
Support svg assets

### ISSUE THREAD

**Issue by folmert** [storybooks/storybook#2363]
Svg assets don't seem to be supported in Storybook, because I get error:

> TypeError: Cannot read property 'push' of undefined
>     at node_modules\@storybook\vue\dist\server\iframe.html.js:70:44

which is:
```javascript
urls[getExtensionForFilename(asset)].push(asset);
```

Coming from:
```javascript
var urlsFromAssets = function urlsFromAssets(assets) {
  if (!assets) {
    return {
      js: ['static/preview.bundle.js'],
      css: []
    };
  }

  var urls = {
    js: [],
    css: []
  };

  (0, _keys2.default)(assets)
  // Don't load the manager script in the iframe
  .filter(function (key) {
    return key !== 'manager';
  }).forEach(function (key) {
    var asset = assets[key];
    if (typeof asset === 'string') {
      console.log(asset); // returns icons.svg
      console.log(urls); // returns { js: [ 'static/preview.bundle.js' ], css: [] }, so there is no svg key
      urls[getExtensionForFilename(asset)].push(asset);
    }
```

I've added following rules for svg files to storybook's webpack config:
```javascript
config.module.rules.push({
        test:    /\.svg$/,
        include: [path.resolve(__dirname, '../src/assets/svg-icons')],
        use:     [
            {
                loader:  'svg-sprite-loader',
                options: {
                    extract:        true,
                    spriteFilename: 'icons.svg'
                }
            },
            {
                loader:  'svgo-loader',
                options: svgoConfig,
            },
        ],
    });

   config.plugins = [new SpriteLoaderPlugin()];
```

and I try to inject generated svg sprites with [svg-sprite-injector](https://github.com/TrySound/svg-sprite-injector) (couldn't find a better way, any alternatives?):
```javascript
const svgSpriteInjector = require('svg-sprite-injector');
const svgFiles = require.context('@/assets/svg-icons', true, /\.svg$/);
svgFiles.keys().forEach(key => svgFiles(key));
svgSpriteInjector('icons.svg', {revision: 1});
```

Anyhow, it works on webpack's dev server, but fails on Storybook.

**EDIT**
After adding svg to @storybook\vue\dist\server\iframe.html.js:
```javascript
  var urls = {
    js: [],
    css: [],
    svg: []
  };
```
all errors are gone, but the icons are not visible and turns out svg is still not injected anywhere (normally it's appended at the beggining of the `<body>`).

**Comment by danielduan** [comment]
svg file is already supported out of the box without the need for custom loaders:
https://github.com/storybooks/storybook/blob/master/app/react/src/server/config/defaults/webpack.config.js#L47

**Comment by folmert** [comment]
@danielduan yea, but this is for classic import/require only.

I've noticed however that this error doesn't occur when I'm putting my `icons.svg` in the root directory, I wondered why, and I've found out that for some reason the `assets` variable in previously mentioned iframe.html.js will become an object in both cases:
```
[ 'static/preview.bundle.js', 'static/preview.bundle.js.map' ]
object

[ 'static/icons.bundle.js',
  'static/icons.bundle.js.map',
  'icons.svg' ]
object
```

while for static/img/svg/sprites-icons.svg it's a separate string:

```
[[ 'static/preview.bundle.js', 'static/preview.bundle.js.map' ]
object

[ 'static/icons.bundle.js', 'static/icons.bundle.js.map' ]
object

static/img/svg/sprites-icons.svg
string
```

and because of that, in the first case it will get filtered out, but in the second it will throw an error - it appears it's due to a weird logic in [iframe.html.js](https://github.com/storybooks/storybook/blob/master/app/vue/src/server/iframe.html.js):

```javascript
  Object.keys(assets)
    // Don't load the manager script in the iframe
    .filter(key => key !== 'manager')
    .forEach(key => {
      let asset = assets[key];
      if (typeof asset === 'string') {
        urls[getExtensionForFilename(asset)].push(asset);
      } else {
        if (!Array.isArray(asset)) {
          asset = [asset];
        }
        asset
          .filter(assetUrl => {
            const extension = getExtensionForFilename(assetUrl);
            const isMap = extension === 'map';
            const isSupportedExtension = Boolean(urls[extension]);
            return isSupportedExtension && !isMap;
          })
          .forEach(assetUrl => {
            urls[getExtensionForFilename(assetUrl)].push(assetUrl);
          });
      }
    });
```

**Why there is no check for supported extension in case of a string?**
