### ISSUE TITLE
Update documentation about using the addon-jest 

### ISSUE THREAD

**Issue by sandinosaso** [storybooks/storybook#2366]
Hi, 
Thank you for the great job here guys. Just a small typo that can frustate new user because if you follow the Documentation you got a Red screen error with no enough information to know what is going on.

You should change:
`import withTests from '@storybook/addon-jest';`
For this:
`import { withTests } from '@storybook/addon-jest';`

At https://github.com/storybooks/storybook/tree/master/addons/jest

Kind Regards.

**Comment by sandinosaso** [comment]
Another typo I noticed, but in the code, is when no file found for a story that has tests configured on it, it says: 'This story has tests configures, but no file not found', it should say:
'This story has tests configures, but no file was found'

This is in components/Panel.js line 101.

Thank you

**Comment by Hypnosphi** [comment]
Hi sandinosaso! Can you please send a PR? If you need to change only one file, you can do that right from GitHub UI, using pencil icon: https://github.com/storybooks/storybook/blob/master/addons/jest/README.md

**Comment by sandinosaso** [comment]
Hi Hypnosphi !! Sure: https://github.com/storybooks/storybook/pull/2376
