### ISSUE TITLE
No tests found using the addon-jest

### ISSUE THREAD

**Issue by sandinosaso** [storybooks/storybook#2367]
Hi, thank you for this great tool, today I decided to use the addon-jest and found some problem, not sure if I am using it properly or it is a real bug.

I followed the documentation of the addon-jest and I got the 'This story has tests configures, but no file not found' (by the way I reported the typo, it should be 'was found' instead.

Not sure what is going on, I inspected the code and found that at some point at the emitAddTests function there is a call to fill the test property on an object like this:

tests: findTestResults(...)

One of the params is options.tests, but I found that property on options is undefined, not sure why, if it is related to the version of jest I am using or how are you loading the test results json file, but that is a fact here is my console showing that object:

<img width="1278" alt="screen shot 2017-11-25 at 1 07 34 am" src="https://user-images.githubusercontent.com/466105/33227355-1a3a3072-d180-11e7-8d7d-1df63522d209.png">

I am not a JS expert, and this is my first time looking at this code plus there is 1:30 am right now and I am really tired, the only thing I noticed is that if I change how you pass the data to the function and instead I pass it this way:

`{ testResults: options.testResults }`

Like this:

<img width="922" alt="screen shot 2017-11-25 at 1 10 15 am" src="https://user-images.githubusercontent.com/466105/33227332-c82b3aa6-d17f-11e7-89e6-82e6ef01b79a.png">

Everything works great:

<img width="1266" alt="screen shot 2017-11-25 at 1 27 41 am" src="https://user-images.githubusercontent.com/466105/33227340-eba0ed00-d17f-11e7-92bb-0b2eda41895c.png">

Again, kind regards for your work here, I hope my hints helps someone realize what is going on, if not I will try my best to figure out was is going on tomorrow :)

**Comment by Hypnosphi** [comment]
Which version of `@storybook/addon-jest` do you use?

**Comment by sandinosaso** [comment]
Hi, I am using
`"@storybook/addon-jest": "^3.2.16",`
And jest version is
`"jest": "^21.2.1",`
along with react 16:
`"react": "^16.1.1",`

Is this expected, I can not find in the code where options.tests came from? I think I am missing the part of the code that does the actual parsing of the json test results.

Regards.

**Comment by dmitrymalakhov** [comment]
Hi everybody! I too have experienced the problem described above.

```
"@storybook/addon-jest": "3.2.16",
"react": "15.6.2",
"jest": "21.2.1",
```
My problem here is "jest --json" use "testResults" in output file, but "addon-jest" use "options.results"

```javascript
const emitAddTests = ({ kind, story, testFiles, options }) => {
  addons.getChannel().emit('storybook/tests/add_tests', {
    kind,
    storyName: story,
    tests: findTestResults(testFiles, options.results, options.filesExt),
  });
};
```
And "findTestResults" gets the value of "jestTestResults" is undefuned

![screenshot from 2017-11-27 15-43-46](https://user-images.githubusercontent.com/2477267/33267204-aaae5d80-d389-11e7-90cb-1c4f52b8ab25.png)

**Comment by renaudtertrais** [comment]
Try to check the documentation in README I have just updated it because the examples regarding the usage of `withTests()` were wrong:  https://github.com/storybooks/storybook/tree/master/addons/jest#usage
