### ISSUE TITLE
Allow fileExt to be optional

### ISSUE THREAD

**Issue by kentcdodds** [storybooks/storybook#2368]
> Moved from https://github.com/storybooks/storybook-addon-jest/issues/4

Right now if you don't provide one this will append `undefined` to the end of the regex:

https://github.com/storybooks/storybook/blob/087647673aedfe925496698a4e9c3a6106b967f4/addons/jest/src/index.js#L9

**Comment by Hypnosphi** [comment]
Looks like it's just a matter of using empty string as a default value. If anybody wants to make a PR, go for it

**Comment by ndelangen** [comment]
If anyone new to storybook or open source in general wants to take this issue, I'm available to help!

**Comment by Promhize** [comment]
@ndelangen just dabbling into open source. Would make a PR

**Comment by ndelangen** [comment]
@Promhize
You'll have to
1. Fork the repo
2. Clone the forked repository to your computer
3. Create a branch named `feature/default-`
4. Edit the following file: `addons/jest/src/index.js`
    The change to apply: change line 3 from:
    ```js
    const findTestResults = (testFiles, jestTestResults, jestTestFilesExt) =>
    ```
    to:
    ```js
    const findTestResults = (testFiles, jestTestResults, jestTestFilesExt = '') =>
    ```
5. Commit the changed file and push to the remote
6. Go to our github page here: https://github.com/storybooks/storybook
7. GitHub should suggest to open a PR, if it doesn't you should be able to select your branch and our master branch here to create one: https://github.com/storybooks/storybook/compare (our master branch should be the base.
8. Describe the change you made in the title and description. 
9. Wait for someone to review the PR.
10. It should be merged pretty quick!

**Comment by Promhize** [comment]
@ndelangen thanks. Looking to make further contributions. You all are awesome

**Comment by renaudtertrais** [comment]
Already done. Check README here: https://github.com/storybooks/storybook/tree/master/addons/jest#withtestsoptions

**Comment by Hypnosphi** [comment]
Done, but not released yet

**Comment by renaudtertrais** [comment]
Actually it was release in 3.2.16 but not well documented:
https://unpkg.com/@storybook/addon-jest@3.2.16/dist/index.js#pos_47

Commit: https://github.com/storybooks/storybook/commit/d185d1abd7e15e0c435bdb740d0ac44e784d58c4#diff-c1ceced995a7529ca1ae8fcb2a0f4aafR26

**Comment by Hypnosphi** [comment]
Oh. Should we revert https://github.com/storybooks/storybook/pull/2373 then?

**Comment by renaudtertrais** [comment]
Yes, please. Sorry for the lack of documentation regarding it.

**Comment by ndelangen** [comment]
@Promhize drop by our slack channel.

That way we can collaborate much easier and faster, if you want to do more collaboration I can help get you on-boarded on the project.
