### ISSUE TITLE
Make a default location for the jest results

### ISSUE THREAD

**Issue by kentcdodds** [storybooks/storybook#2369]
> Transfer from  https://github.com/storybooks/storybook-addon-jest/issues/6

This way, so long as people are using the default location, they don't need to worry about providing it to the `withTests` function at all. Combine that with https://github.com/storybooks/storybook-addon-jest/issues/5 and https://github.com/storybooks/storybook-addon-jest/issues/4 and folks could do something as simple as:

```javascript
import withTests from '@storybook/addon-jest'

storiesOf('blah').addDecorator(withTests('./__tests__/my-test.js', '../../__tests__/my-other-test.js'))
// ... etc.
```

As an idea, the default location could be in `./node_modules/.cache/jest/results.json` or something. This way the cache is not only busted when someone nukes their `node_modules` directory, but it'll probably already be git ignored so they don't need to add another entry to their gitignore or find a good place to put it because a good recommendation (that doesn't pollute the root of the repo) is already suggested and the default.

If someone wants to specify their own options, then we could also expose another function:

```javascript
import { withTestsOptions } from '@storybook/addon-jest'
```

Or something like that.

Thoughts?

Thanks for this addon! I think it's super!

**Comment by Hypnosphi** [comment]
Sounds like a good idea.

More generally, supplying a file location string instead of imported JSON feels like a better API.  Not sure this is possible for dynamic strings though, given that `addon-jest` runs in a browser

**Comment by kentcdodds** [comment]
Yeah, I'm fine having to import it manually if I place it in the non-standard location. That actually makes the most sense to me. But having a standard place for it so I don't have to import it sounds good.

**Comment by renaudtertrais** [comment]
I tried it but it feel more complicated as it sounds. Results are loaded in "browser", not in node. So this happen at build time (Webpack).

**Comment by kentcdodds** [comment]
Maybe you could do:

```javascript
let testResults
try {
  testResults = require('.cache/jest/results.json')
} catch(e) {
  // ignore... They'll have to provide their own test results
}
```

That should work right? I think there's even a way to ask webpack if a dependency exists so you wouldn't need the try/catch.
