### ISSUE TITLE
@storybook/addon-info not working properly when building static styleguide

### ISSUE THREAD

**Issue by lifeiscontent** [storybooks/storybook#2374]
Hey there, I'm using recompose to build my UI Components and I'm not sure if that has anything to do with it, because when I run storybook e.g. `yarn storybook` from a create-react-app it works as expected but not when I build-storybook.

So the issue, is when I've set my propTypes, they display as expected, but when I run a build all of the propTypes types are equal to node, which is obviously a bug.

Any ideas on how to track this down, I'd be happy to work on the issue.

**Comment by clementallen** [comment]
Possible duplicate of #1661

**Comment by lifeiscontent** [comment]
@clementallen I also noticed it's not working when using recompose.
