### ISSUE TITLE
React Docgen Integration not working as expected

### ISSUE THREAD

**Issue by lifeiscontent** [storybooks/storybook#2377]
when using `@storybook/addon-info` I've tried to document my prop types of my react components but they don't seem to show up.

any ideas why? I'm using create-react-app. do I need to save `babel-plugin-react-docgen` as a dev dependency?

**Comment by mlmassey** [comment]
Duplicate of #2010

**Comment by gaurav5430** [comment]
facing the same issue when using a custom webpack config. 
`title`, `componentSubtitle` works as expected, but props information and description does not show up in the DocsPage tab, even though specified correctly in the docgen format
