### ISSUE TITLE
Background does not persist when changing between story scenarios

### ISSUE THREAD

**Issue by clementallen** [storybooks/storybook#2383]
When using a custom background, it resets to the default when changing to a different story scenario.  I'm not sure if this is deliberate or not but it seems like it would be more convenient to persist the background when changing.

Demo:
![storybook-background-bug](https://user-images.githubusercontent.com/6305750/33271665-d030eb68-d37f-11e7-9cda-b8c863bd95f7.gif)

**Comment by wuweiweiwu** [comment]
@Hypnosphi I can pick this up :)

**Comment by Hypnosphi** [comment]
Sure, go for it

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.2`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.2)
