### ISSUE TITLE
No horizontal Scrollbar on Sidebar (Firefox 57+)

### ISSUE THREAD

**Issue by tobilen** [storybooks/storybook#2387]
Seems to be the flex-basis of 0% on one of the nested pane divs. I changed it in the second screenshot and it works.

![image](https://user-images.githubusercontent.com/8217788/33287348-b6558eea-d3b8-11e7-8dd8-97c8119e89f2.png)

![image](https://user-images.githubusercontent.com/8217788/33287404-d529e550-d3b8-11e7-9df2-992fb72aa546.png)

**Comment by Hypnosphi** [comment]
Hi @tobilen =) Feel free to send a PR

**Comment by tobilen** [comment]
will do. probably not before friday though :)
