### ISSUE TITLE
Warning: Unsupported vendor-prefixed style property webkitOverflowScrolling

### ISSUE THREAD

**Issue by hoschi** [storybooks/storybook#2388]
In full screen mode I get an error
Warning: Unsupported vendor-prefixed style property webkitOverflowScrolling. Did you mean WebkitOverflowScrolling? Check the render method of `Layout`.

When I search in my `node_modules` folder I found that in:
ui/dist/modules/ui/components/layout/index.js
137:  webkitOverflowScrolling: 'touch'
When I change this to upper case `WebkitOverflowScrolling` the error is gone.

Also I found a bug which mentions this but is marked as open #1227
Storybook version is latest `3.2.16`

**Comment by Hypnosphi** [comment]
This is actually fixed in #2343, but not released yet
@shilman can we do a patch?

**Comment by danielduan** [comment]
Published in `3.2.17`
