### ISSUE TITLE
HMR problem with webpack DLL reference plugin

### ISSUE THREAD

**Issue by hoschi** [storybooks/storybook#2389]
I use the webpack feature to build and use DLL for vendor code. Our current version 3.2.12 works fine, but with 3.2.16 I found a bug. When I update a source file and HMR kicks in, storybook updates but throws an error:

![2017-11-28-122539_1320x1384_scrot](https://user-images.githubusercontent.com/163128/33317382-4009715a-d437-11e7-8ceb-9a251363348b.png)

To include the vendor bundle I added `script` tags into `preview-head.html` and `manager-head.html`:
`<script src='/vendor.bundle.js'></script>`

**Comment by hoschi** [comment]
Tested with current version `3.3.9`, but still get this error:
![2018-01-15-111914_1356x1370_scrot](https://user-images.githubusercontent.com/163128/34937665-ecc84672-f9e5-11e7-9001-92a64ab2a2f1.png)

**Comment by smithjustinb** [comment]
I am experiencing this issue as well. Was fine on 3.2.15, but similarly broken after upgrading to 3.3.9.

**Comment by hoschi** [comment]
still there with 3.3.14

**Comment by Hypnosphi** [comment]
The easiest workaround would be not to include dll plugin into your storybook webpack config (you probably only need it for your actual app). I'll try to investigate why the error happens though

**Comment by hoschi** [comment]
@Hypnosphi that is generally right, but it gives a significant performance boost.
/cc @MarkusLanger

**Comment by Hypnosphi** [comment]
@hoschi @smithjustinb can someone of you please create a GitHub repo with minimal reproduction of the issue, so that I could debug it myself?
