### ISSUE TITLE
 How to set addon-viewport viewport default value

### ISSUE THREAD

**Issue by zhipenglin** [storybooks/storybook#2395]
This plugin is very good , but I can not set a default value for its viewport so that it remembers the previously selected value the next time it opens

**Comment by danielduan** [comment]
This will probably require a PR to set something in the cookies or browser local storage.

**Comment by jalooc** [comment]
Do you think it would it be possible to export a _configuration_ function setting default values, like e.g. `setOptions` in `@storybook/addon-options`?

**Comment by mneumark** [comment]
Actually it would be great to set this per-story. So if I have a story I am trying to show that is intended just for mobile and looks terrible on desktop. Have a decorator option to set it.

**Comment by francesco-albanese** [comment]
Any news on that? It would be really useful  if one could pass a config to set the default viewport by default.

**Comment by igor-dv** [comment]
There is an ongoing PR - #3099.

**Comment by mshaaban088** [comment]
I agree, it'd be great to have those features, so I'll take it and address the following:

1. Export an option to configure the `default` viewport @francesco-albanese @jalooc 
2. Export a decorator component to override the default viewport per story @mneumark 

I think with option 1, we don't need to use cookie/local-storage, as I'll be set for the entire website/stories @zhipenglin @danielduan 

What do you think folks?

P.S. it'll be a separate PR though @igor-dv , and it might needs some adjustments on #3099

**Comment by mshaaban088** [comment]
Just a quick update, I've implemented the above functionality (see #3099), in case you want to see how it is implemented. Feedbacks are always welcomed!

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.0`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.0)
