### ISSUE TITLE
Sub menu items disappear on rebuild

### ISSUE THREAD

**Issue by powermikee** [storybooks/storybook#2402]
The items will appear again if you clear the url params.
![screen shot 2017-11-30 at 2 11 54 pm](https://user-images.githubusercontent.com/2126542/33412648-78aa129c-d5d8-11e7-8d43-5fd1d2836a71.png)
![screen shot 2017-11-30 at 2 12 30 pm](https://user-images.githubusercontent.com/2126542/33412662-8ebb6b44-d5d8-11e7-8685-a72b8790c50e.png)

**Comment by Hypnosphi** [comment]
Hi! Looks like you're using an outdated version. Latest version of `@storybook/react` and other packages is `3.2.16`.

If you use `@kadira/storybook`, you can migrate half-authomatically by running this command in your project root:
```
npx storybook
```
`npx` is a command-line tool bundled with node 8 and higher. If you're using earlier versions, you can install it from npm

**Comment by powermikee** [comment]
Thanks.

**Comment by powermikee** [comment]
Sorry guys still happening in new version.

![storybook](https://user-images.githubusercontent.com/2126542/33461798-ca564c12-d67f-11e7-98b5-e2ffce090eea.png)

**Comment by ndelangen** [comment]
@powermikee can you share a replication repository? A repo where you know this problem exists after install?

I'm unable to reproduce this.
