### ISSUE TITLE
addon-jest broke tests in the cra-kitchen-sink example

### ISSUE THREAD

**Issue by thomasbertet** [storybooks/storybook#2407]
Hi there,

I simply wanted to run the tests on the cra-kitchen-sink example project, and it fails due to Jest override in package.json:

# How to reproduce 
- Checkout the `cra-kitchen-sink` project
- run `yarn` 
- run `yarn run test` 

# Why
- On the addon-jest PR, some "jest" properties were added in package.json : https://github.com/storybooks/storybook/pull/2295/files#diff-a63f6fd207d99e7f8eacd7a4cf0ef793R46 
These configurations are not supported by react-scripts (CRA) and thus throw errors: 
![selection_119](https://user-images.githubusercontent.com/2551574/33442865-7aff7c80-d5f6-11e7-95cc-7e98ed3db9ca.png)

I'm not sure how to handle this properly since it seems one cannot simply remove these extra configuration keys _obviously_ :) 
I'm willing to make `yarn run test` work to continue implementing another feature so any help from any of you or maybe @renaudtertrais  could be timeless :+1:

**Comment by renaudtertrais** [comment]
Perhaps you could extract this configuration needed for addon-jest and put it in a separate file. Then you should just need to add `--config ./jest-config-for-addon-jest.json` to `generate-addon-jest-testresults` script.

Usage of `--config`:
https://facebook.github.io/jest/docs/en/configuration.html#content

**Comment by Hypnosphi** [comment]
This file is ignored in root jest config. So you can do `yarn jest examples/cra-kitchen-sink` in root

**Comment by ndelangen** [comment]
Perhaps we can ask CRA to support extending the jest config more?

**Comment by thomasbertet** [comment]
@ndelangen that's a lot of config properties to support and I believe they won't be incline to support all these. Maybe *you* can start an issue over there, it will certainly have more weight than me ? :) 

Also @renaudtertrais thanks for pointing me out to the right direction, I will fix it ASAP.

**Comment by ndelangen** [comment]
@thomasbertet If we found an alternative way, then I'm not going to create an issue asking for more configuration in CRA. I know this would be an uphill battle, which I'm personally not really interested in having.

Out of the box CRA-compatibility is important though, So I'm happy we found a way.
