### ISSUE TITLE
Feature: Storyshots: custom renderer

### ISSUE THREAD

**Issue by tobilen** [storybooks/storybook#2408]
I'd really appreciate an option to provide a custom renderer (i.e. enzymes shallow, mount or render) to the storyshots addon.

We do all of our snapshot testing with enzyme, and it feels consistently more robust and able to handle edge cases when compared to react-test-renderer. I totally understand not wanting to pull in another dependency into your project though.

So what im proposing is being able to pass the renderer as an option parameter to the initStoryshots addon and have it use this renderer. Only fall back to react-test-renderer if no custom renderer is specified. initialization would look like this:

```js
import { shallow } from 'enzyme';
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots({ renderer: shallow});
```

if you are open to the idea, i would be happy to create a PR

**Comment by Hypnosphi** [comment]
Sounds like a great feature! If you'll do a PR, please base it on `release/3.3` branch (sorry for inconvenience)
