### ISSUE TITLE
Change the Theme of storybook

### ISSUE THREAD

**Issue by Mujaddadi** [storybooks/storybook#2423]
I am interested in customizing the UI of storybook. I am talking about the styles not just layout. At the moment the chances of changing it are zero to none. The UI even don't use classes so we can't overwrite it. Is there is anyway to do it without forking the repo? If it is, I will appreciate.

**Comment by majapw** [comment]
We would also be interested in this feature. We use storybook to show off our internal design language, and it would be nice if we could leverage the features of the design language in the storybook as well.

A high-level styles object with a font stack, default spacing, colors, etc. would be a good start. 

cc @noratarano

**Comment by Mujaddadi** [comment]
I would like to work on it whenever I will get time, which I don't have at the moment.

**Comment by Mujaddadi** [comment]
Not sure what's the point of the bot to close issues even if they are inactive. Doesn't solve the issue or fulfill feature request.

**Comment by danielduan** [comment]
As an open source project, it's hard to accommodate every feature request ourselves. We use the bot to help close out any inactive issues so we spend more time coding and less time managing GitHub issues.

We do welcome any help we can get if anyone is interested in helping to implement support for theming. While there has been discussions about supporting theming, it isn't in our core roadmap in the near future.

**Comment by uliana-sirotina** [comment]
Hi, we are also interested in adjusting the styles of storybook. If there could at least be a className for every part of the story. Like "story-header" etc.

**Comment by ckeeney** [comment]
Is there a way to make stale bot ignore an issue?  An issue has been created for this topic a number of times:
- https://github.com/storybooks/storybook/issues/313
- https://github.com/storybooks/storybook/issues/428
- https://github.com/storybooks/storybook/issues/1107
- https://github.com/storybooks/storybook/issues/1360
- https://github.com/storybooks/storybook/issues/1576

The stale bot repeatedly closing these issues just fragments the conversation.

**Comment by ndelangen** [comment]
+1 on that @ckeeney. This is on the roadmap, I kinda like @uliana-sirotina idea as a intermediate solution.

I could do that, but it's also possibly easy enough for someone new to do it. Anyone here interested in taking it on?

**Comment by Mujaddadi** [comment]
I would like to do it as my first open source project. Although I am quite busy but its time to give back to the community. I will check it on this Sunday hopefully.

**Comment by Keraito** [comment]
If you need some help at some point, @Mujaddadi, I can gladly help, just @ me!

**Comment by Hypnosphi** [comment]
Does it mean that our layout will become a contract, and we won't be able to change it in non-major releases

**Comment by ndelangen** [comment]
@Hypnosphi I would propose a few select global scope classes so there's some room for customisation there.

I'm already working on proper theming.

**Comment by Mujaddadi** [comment]
@ckeeney and these issues are also been closed every time. I think this one is only the open issue. 

@ndelangen So there is no need to work on the proper theming support since you are already working on it?

**Comment by ndelangen** [comment]
I am working n it, but would love to pair-program in it, if anyone is interested!

I can open a hangout and screen-share if anyone is interested. PM me https://twitter.com/norbertdelangen

**Comment by thedaviddias** [comment]
Hey @everyone, I'm interested to work on that issue too... I'm currently working to build a new design system using storybook and I would like to easily add a different theme...

**Comment by ndelangen** [comment]
@thedaviddias The theming PR has been merged ands the latest alpha release contains it!

So you can try this today!

I'd love to see what your custom theme will look like!!

**Comment by Mujaddadi** [comment]
Great! I will test it. Thanks!

**Comment by igor-dv** [comment]
Any reason to not closing this issue?

**Comment by ndelangen** [comment]
no you're right we can close it

**Comment by massivelines** [comment]
Love what has been setup on allowing customization on the UI, but it is still extremely limiting. I am building a living style guide for a web app, but I need to style the navigation and other things like the app.

One idea that I was thinking about that would allow tons of customization would be to use emotion-theming like its already setup in a few files, but instead of passing only a variables for a few changes, pass in an object and have the styling in a separate file or maybe multiple files.

Building on top of that idea, keep the current in file styling and use maybe like an if else, where as if styling has been set in a theme file use that instead of the in file styling.

**Comment by ndelangen** [comment]
@massivelines I'm real happy with someone asking this.

I kept the theming PR limited on purpose so if this turned out too limited I would be able to hear from the requesters what their thoughts would be on what they want to change/theme in storybook.

I'd love to work with you and determine what sort of changes you'd want and how best to address them. Perhaps we could work together on a PR to hit a sweet spot of extensibility?

**Comment by massivelines** [comment]
@ndelangen I completely understand on keeping it limited and waiting on feedback.

I think working together on this is a great idea.

**Comment by ndelangen** [comment]
Would you care to join our slack so we can discuss this a bit more direct?

https://now-examples-slackin-rrirkqohko.now.sh/
