### ISSUE TITLE
[addon-knob] Why max number equals 10, by default?

### ISSUE THREAD

**Issue by DimaRGB** [storybooks/storybook#2431]
### Issue details
Always need pass options `number(, , { max: Infinity })`.

### Please specify which version of Storybook and optionally any affected addons that you're running
- `@storybook/react 3.2.17`
- `@storybook/addon-knobs 3.2.17`

### Screenshots / Screencast / Code Snippets (Optional)
[in source](https://github.com/storybooks/storybook/blob/master/addons/knobs/src/index.js#L25)
```js
<div
  style={{
    left: number('left', 20)
  }}
/>
```

**Comment by Hypnosphi** [comment]
That's a bug introduced with #2371. We shouldn't apply default min/max/step for plain number knob
