### ISSUE TITLE
Is there a watch mode? (without hot server)

### ISSUE THREAD

**Issue by skyrpex** [storybooks/storybook#2434]
Looking at the docs I just see the `start-storybook` and `build-storybook` modes... They are awesome but sometimes we work on machines that can't reserve ports.

The watch mode would create files (something like the build mode) but leaving the process open to more code changes.

Is it planned?

**Comment by danielduan** [comment]
Probably not. Your use case is pretty specific and it's probably the first time this is requested.

**Comment by Hypnosphi** [comment]
You can try `watch: true` in `.storybook/webpack.config.js`. Should work even using [extend mode](https://storybook.js.org/configurations/custom-webpack-config/#extend-mode)

**Comment by skyrpex** [comment]
Thanks for the support. Yeah, I know it's pretty specific. 😢 

Will try the webpack's built-in watch mode!
