### ISSUE TITLE
storybook/angular typing errors "implicit any"

### ISSUE THREAD

**Issue by ralzinov** [storybooks/storybook#2435]
### Issue details
Code written in typescript has no proper typings. 

### Steps to reproduce
Set ``` "noImplicitAny": true ``` flag in tsconfig.json

### Please specify which version of Storybook and optionally any affected addons that you're running
- storybook/angular 3.3.0-alpha.4
- typescript@2.3.4

### Screenshots / Screencast / Code Snippets (Optional)
```
ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts
(22,6): error TS7034: Variable 'timeout' implicitly has type 'any' in some locations where its type cannot be determined.

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts
(29,31): error TS7005: Variable 'timeout' implicitly has an 'any' type.

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts
(30,16): error TS7005: Variable 'timeout' implicitly has an 'any' type.

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts
(36,33): error TS7031: Binding element 'component' implicitly has an 'any' type.

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts
(47,26): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.

ERROR in ./node_modules/@storybook/angular/dist/client/preview/angular/helpers.ts
(59,32): error TS7006: Parameter 'meta' implicitly has an 'any' type.
...
```

**Comment by ralzinov** [comment]
Do you have plans to fix that soon? I can make PR.

**Comment by dereklin** [comment]
I can't tell what the work around is.  In my case, my code is compiling fine with functions like:

```
export function domeSomething(value) {
...
}
```
When I run storybook, I get this error:
```
error TS7006: Parameter 'value' implicitly has an 'any' type.
````

If I change the original function to 
```
export function domeSomething(value: any) {
...
}
```
It will work.

But I would need to change many files.

Is there a quick workaround?

**Comment by Quramy** [comment]
@dereklin 

TypeScript compiler tells the error if you define function with no-type annotated arguments.

You have 2 options to suppress this error:

- Define arguments' type like `domeSomething(value: any)`
- Turn off `noImplicitAny` option

```js
/* tsconfig.json */
{
  "compilerOptions": {
    "noImplicitAny": false,
  }
}
```

**Comment by dereklin** [comment]
@Quramy Using the custom tsconfig.json file to turn off noImplicitAny is the way to go for me.  The detail is here: https://github.com/storybooks/storybook/issues/2616

**Comment by superflyguy81** [comment]
legendary
