### ISSUE TITLE
Expand all categories

### ISSUE THREAD

**Issue by mnmtanish** [storybooks/storybook#244]
@arunoda 

It'll be easier to navigate if categories are always expanded. Even when there are many stories, as long as they're sorted alphabetically it won't take much effort to scroll to the category we're interested. And we also have filters to help for long lists.

**Comment by arunoda** [comment]
This is a good feature. But I don't think we have a alphabetically sorted functionality. It should be based on the order stories has been written (loaded).

**Comment by ndelangen** [comment]
Yes, this is something I'd like to see a PR on, please wait for #1383 #151 to be completed.

**Comment by ndelangen** [comment]
I think a keyboard shortcut for this would be a big ➕

**Comment by samjacoby** [comment]
I know this is stale, at this point, but has a solution emerged in the meantime?

**Comment by sky007** [comment]
Is there any implementation of this, I see there is an reference issue that has been merged but the documentation doesn't have an option to expand all the stories.

**Comment by shilman** [comment]
We don't have that feature -- not sure why that PR references this issue. Would you like to add it?

**Comment by wbern** [comment]
I'd like to chime in to say that I wouldn't mind all my categories being expanded from the start either.

**Comment by wbern** [comment]
I solved this in a rather crude way, but it does the trick.

add a `manager-head.html` file in your `.storybook` directory as per docs. (https://storybook.js.org/docs/configurations/add-custom-head-tags/#add-tags-or-scripts-to-the-main-ui)

inside, put the following:

```html
<script type="text/javascript">
    window.onload = function() {
        var clickCollapsedItems = () => {
            var items = Array.from(
                document.querySelectorAll(
                    ".simplebar-content [id^='explorer']:not([href])",
                ),
            );
            var expandedItems = Array.from(
                document.querySelectorAll(
                    ".simplebar-content [id^='explorer']:not([href]) + .css-0",
                ),
            ).map(e => e.previousSibling);

            var itemsLeftToClick = items.filter(item =>
                expandedItems.every(expandedItem => item !== expandedItem),
            );

            if (itemsLeftToClick.length > 0) {
                itemsLeftToClick.forEach(item => item.click());

                clickCollapsedItems();
            } else {
                // everything is now expanded!
            }
        };

        clickCollapsedItems();
    };
</script>
```

start storybook, and with a slight delay, the items all get expanded.

**Comment by jayrungta** [comment]
is there any support for this yet?

**Comment by shilman** [comment]
There's support for collapse all, but not AFAIK not expand all:

<img width="450" alt="sb-collapse-all" src="https://user-images.githubusercontent.com/488689/71701980-d9167d80-2e07-11ea-8894-c7d58b31e30d.png">

**Comment by atanasster** [comment]
@jayrungta - collapse all is in the menu as @shilman posted above.

Expand all is also implemented, but only with keyboard shortcuts (its not in the menu) since its not supposed to be used that often :) 

The shortcut for Expand All is:  
Command+Shift+DownArrow. (same as Collapse all but with down arrow opposite Up arrow)

**Comment by jayrungta** [comment]
@atanasster do you know why this is not supported as a configuration/option? Why is expanding all by default such a "bad idea"?

**Comment by atanasster** [comment]
@jayrungta - because there can be a lot of stories and expand all will take significant time. If you would prefer to have expand all in the menu, please file an issue

**Comment by lkraav** [comment]
> @jayrungta - because there can be a lot of stories and expand all will take significant time. If you would prefer to have expand all in the menu, please file an issue

Storybook 5.3.19 (latest stable): I would like to have "Expand all" as project default state. Is it possible to configure or programmatically trigger?

**Comment by phun-ky** [comment]
Perhaps and old issue, but I see no configuration for this still, I know the option is there in the UI:

![image](https://user-images.githubusercontent.com/1714029/102395412-603e1080-3fdb-11eb-81bd-f23e3d63031d.png)

But no configuration option. If this is by design, maybe storybook was not intended for large component-sets?

**Comment by scscgit** [comment]
Is this feature of default expansion state still being ignored? @atanasster mentions that it may take significant time in large projects, yet paradoxically this is most important for smaller projects where it'd be way easier to skim all entries than to expand all the roots manually every single time you refresh the storybook. You also switch between two extremes of expanding/collapsing everything, yet sometimes the most logical default would be to expand all root folders while keeping the specific stories hidden. They are all combined anyway if one uses the Docs to browse them. (Actually if you're concerned about bloating the UI, you could even enable an option to automatically hide the specific stories once a different entry is selected, or not to expand them at all.)

**Comment by danielrob** [comment]
A workaround that seems pretty solid is to create an addon just like this: 

`.storybook/addons/expand-all/register.js`
```
import { addons } from '@storybook/addons';

let hasExpanded = false;

addons.register('expand-all', (api) => {
  const emitter = addons.getChannel();

  emitter.on('storyRendered', () => {
    if (!hasExpanded) {
      setTimeout(api.expandAll) // Calling on the next tick after storyRendered seems to work reliably for initial load.
      hasExpanded = true;
    }
  })
});
```

Then, in `main.js`
```
  addons: [
    "@storybook/addon-actions/register",
    "@storybook/addon-links",
    "./addons/expand-all/register.js",
```

Problem sovled!

**Comment by CodeBear228** [comment]
@danielrob  Thanks a lot, wonderful answer, you are genius hhhhhh~

**Comment by llaenowyd** [comment]
> A workaround that seems pretty solid is to create an addon just like this ...

[Expand-All | @a110/storybook-expand-all](https://storybook.js.org/addons/@a110/storybook-expand-all/)
_This Storybook Add On aims to expand all the items in the sidebar when the Storybook launches in the browser._

I'm using it in [my Storybook](https://llaenowyd.github.io/cushman), seems to be working ok, thanks for pointing the way @danielrob.

**Comment by micahgodbolt** [comment]
> A workaround that seems pretty solid is to create an addon just like this:
> 
> `.storybook/addons/expand-all/register.js`
> 
> ```
> import { STORY_RENDERED } from '@storybook/core-events';
> import { addons } from '@storybook/addons';
> 
> let hasExpanded = false;
> 
> addons.register('expand-all', (api) => {
>   const emitter = addons.getChannel();
> 
>   emitter.on(STORY_RENDERED, () => {
>     if (!hasExpanded) {
>       setTimeout(api.expandAll) // Calling on the next tick after storyRendered seems to work reliably.
>       hasExpanded = true;
>     }
>   })
> });
> ```
> 
> Then, in `main.js`
> 
> ```
>   addons: [
>     "@storybook/addon-actions/register",
>     "@storybook/addon-links",
>     "./addons/expand-all/register.js",
> ```
> 
> Problem sovled!

Note that if your landing page is a MDX story, the event will be DOCS_RENDERED, not STORY_RENDERED

**Comment by llaenowyd** [comment]
I found listening for `CURRENT_STORY_WAS_SET` was most reliable. [The listener in this add-on](https://github.com/llaenowyd/storybook-expand-all) unregisters itself once it fires. If you try it, let me know if it's helpful or if you run into an issue.

**Comment by taylorvnoj** [comment]
Thank you for the workaround @danielrob - I'm wondering if there's an option to only have the folders open, and not the sub-stories within stories?  Or is this an all or nothing

**Comment by d9k** [comment]
@wbern, https://github.com/storybookjs/storybook/issues/244#issuecomment-519847685
> I solved this in a rather crude way, but it does the trick. (@storybook/vue, version 5.1.9)
> 
> add a `manager-head.html` file in your `.storybook` directory as per docs. (https://storybook.js.org/docs/configurations/add-custom-head-tags/#add-tags-or-scripts-to-the-main-ui)
> . . . . .

Fixed for storybook 7. Expand only folders:

```html
<script type="text/javascript">
  /*
   * Expand folders by default
   *
   * Forked from https://github.com/storybookjs/storybook/issues/244#issuecomment-519847685, thanks to https://github.com/wbern
   **/
  var clickCollapsedItemsUntilNoneLeft = () => {
    try {
      var itemsLeftToClick = Array.from(
        document.querySelectorAll(
          '#storybook-explorer-tree button.sidebar-item[data-nodetype="group"][aria-expanded="false"]',
        ),
      );

      if (itemsLeftToClick.length > 0) {
        itemsLeftToClick.forEach(item => item.click());

        clickCollapsedItemsUntilNoneLeft();
      }
    } catch (e) {
      console.error(e);
    }
  };

  window.onload = clickCollapsedItemsUntilNoneLeft;
</script>
```

**Comment by davelandry** [comment]
Fixed for Storybook v8, expand only folders (the CSS selectors changed, and I had to add a short timeout to let the sidebar render):

```js
<script id="storybook-mod-expand-all-folders" type="text/javascript">
  var clickCollapsedItemsUntilNoneLeft = () => {
    setTimeout(() => {
      try {
        var itemsLeftToClick = Array.from(
          document.querySelectorAll(
            '#storybook-explorer-tree .sidebar-item[data-nodetype="group"] button[aria-expanded="false"]',
          ),
        );
        console.log(itemsLeftToClick);
        if (itemsLeftToClick.length > 0) {
          itemsLeftToClick.forEach(item => item.click());
          clickCollapsedItemsUntilNoneLeft();
        }
      } catch (e) {
        console.error(e);
      }
    }, 200);
  };

  window.removeEventListener('load', clickCollapsedItemsUntilNoneLeft);
  window.addEventListener('load', clickCollapsedItemsUntilNoneLeft);
</script>
```
