### ISSUE TITLE
Add eslint-loader to the custom storybook webpack configuration

### ISSUE THREAD

**Issue by dcorb** [storybooks/storybook#2446]
### Issue details

Adding eslint-loader to story webpack config doens't seem to work

### Steps to reproduce
I have this in webpack.config.js:
after reading this documentation piece https://github.com/storybooks/storybook/blob/master/app/react/src/server/config/defaults/webpack.config.js

I can't get eslint to output any type of messages, I have a .eslintrc file in the root folder, and I have tried many different combinations of eslint options, loading as "pre", etc, etc.. also in Full control mode. No luck

```
const path = require('path');
module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        loaders: [ {
                loader: 'eslint-loader',
                 options: {
                  emitError: true,
                  failOnError: true
                },
              }],
        include: path.resolve(__dirname, '../src')
      }
    ]
  }
}
```
I tried also this example of an older issue 
 without success https://github.com/storybooks/storybook/issues/90#issuecomment-209224989

### version of Storybook and optionally any affected addons that you're running
````
 "@storybook/addon-actions": "^3.2.17",
    "@storybook/addon-info": "^3.2.17",
    "@storybook/addon-knobs": "^3.2.17",
    "@storybook/addon-links": "^3.2.17",
    "@storybook/addon-options": "^3.2.17",
    "@storybook/react": "^3.2.17",

"eslint": "^4.12.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-react": "^7.5.1",

````

**Comment by Hypnosphi** [comment]
To override loader for `js`, you need to use [Full Control Mode](https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode)
Don't forget to include babel-loader as well

**Comment by dcorb** [comment]
babel-loader fixed it for me, thanks Filipp
