### ISSUE TITLE
Multiple story hierarchies

### ISSUE THREAD

**Issue by Havelaer** [storybooks/storybook#2451]
Hi guys,

I've been working on a feature to have multiple hierarchies (or see it as a flattened first level). 
It's a small iteration on Igor's [story-hierarchy-in-storybook](https://medium.com/sears-israel/story-hierarchy-in-storybook-3-2-7506b5a6ceb9). 

A second 'Addons' hierarchy:
![screen shot 2017-12-08 at 21 36 52](https://user-images.githubusercontent.com/817113/33794001-0ecb3774-dcc3-11e7-9170-dfe4e6dea5bf.png)

Eligible for a PR? And should I submit it to master or to another branch? 
https://github.com/Havelaer/storybook/commits/feature/multiple-hierarchies

**Comment by Hypnosphi** [comment]
Looks promising. Please base on `release/3.3` branch

**Comment by Hypnosphi** [comment]
Released as [3.4.0-alpha.0](https://github.com/storybooks/storybook/releases/tag/v3.4.0-alpha.0)
