### ISSUE TITLE
Change URL structure to a better readable solution

### ISSUE THREAD

**Issue by sapkra** [storybooks/storybook#2466]
### Issue details

We want to link on our stories in our JIRA tickets for our QA.
It's really hard to create short readable URLs, so my suggestion is to create a new URL structure.

> /?selectedKind=Organisms%2FProductOverview&selectedStory=Filter&someAddonConfig=optional

should be restructured to

> /Organisms/ProductOverview/Filter?someAddonConfig=optional

### Steps to reproduce

You just have to create a story in a hierarchy tree.

### Affected platforms 

- All browsers

**Comment by Hypnosphi** [comment]
What if user defines a separator other than slash and uses slash as part of kind name?

**Comment by sapkra** [comment]
While generating the URL you can add a backslash or tilde sign before the slash which is added by the user and ignore these slashes in the routing. It's just an idea - better solutions are definitely welcome.

**Comment by astrotim** [comment]
+1 for this feature. We are using Storybook as a living style guide and the URLs are a pain point. Even loading app from the index automatically adds over 100 extra characters to the query string.
