### ISSUE TITLE
Use svg-url-loader instead of file loader for importing svg

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2474]
### Issue details

svg-url-loader is more optimized and can make the import around 30% smaller than url encoding a file.

Please turn on `noquotes` option so it could be used in `<img>` tag.
https://www.npmjs.com/package/svg-url-loader#noquotes

### Affected platforms 

- vue
- react
- angular

**Comment by ppatel221** [comment]
Hey Im a student in an open source development class. Im looking to contribute to a open source project. Can i take over?

**Comment by Hypnosphi** [comment]
Sure @ppatel221 ! You can refer to [contributing guide](https://github.com/storybooks/storybook/blob/master/CHANGELOG.md) to get familiar with our development setup
Feel free to join our [slack](https://now-examples-slackin-rrirkqohko.now.sh/) once you have any questions

**Comment by wuweiweiwu** [comment]
@Hypnosphi I'll pick this up and send in a PR probably this weekend :)

**Comment by wuweiweiwu** [comment]
@Hypnosphi Should I just add this plugin for every subdir that has a `webpack.config.js`?

**Comment by danielduan** [comment]
just the ones that are configured to accept `svg` files

**Comment by wuweiweiwu** [comment]
@danielduan Sounds good! Thanks

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.0`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.0)
