### ISSUE TITLE
[Release 3.3]: Cannot log non-object arguments in actions

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#2481]
### Issue details

An event handler that calls its prop with a non-object argument does not appear in the actions addon

### Steps to reproduce

Add this story to the `addon-actions.stories.js` in `cra-kitchen-sink`:

```js
  .add('Simple Payload', () => <Button onClick={action('simple')('simple')}>Simple Payload</Button>)
```

When you click the button, note no action is logged.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.3.0-alpha.4
- @storybook/addon-actions 3.3.0-alpha.4

**Comment by tmeasday** [comment]
Someone remove the `needs reproduction` label if they confirm the issue please

**Comment by tmeasday** [comment]
Ahh, I see this now: https://github.com/storybooks/storybook/pull/2438 covers this. I'll leave this open until that's merged, and we should probably add this story as a test case.

**Comment by Hypnosphi** [comment]
[Stories for different types](https://deploy-preview-2438--storybooks-cra.netlify.com/?selectedKind=Addon%20Actions&selectedStory=All%20types&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel)
