### ISSUE TITLE
Preview panel no longer scrolls after resize on Chrome/Safari

### ISSUE THREAD

**Issue by adrianblynch** [storybooks/storybook#2482]
### Issue details

After I use the grab-handle to resize the preview panel, it's no longer possible to scroll.

![no-scroll](https://user-images.githubusercontent.com/4160967/33980820-66b5a5e0-e0a2-11e7-8cf6-f2578098beec.gif)

### Steps to reproduce

Start Storybook with enough content in the preview panel to require scrolling.

Resize the panel using the horizontal handle.

Attempt to scroll the panel.

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/addon-actions 3.2.14
- storybook/addon-knobs 3.2.14
- storybook/addon-links 3.2.14
- storybook/react 3.2.14

### Affected platforms 

This is happening on:
- Chrome 63
- Chrome 65 (Canary)
- Safari 11.0.2

All on a Mac 10.11.6 using the touchpad. No mouse is plugged in.

Works on Firefox 57 on the same Mac.

**Comment by Hypnosphi** [comment]
Please check if it works on `3.3.0-alpha.4`. I believe we had fixed it at some point

**Comment by adrianblynch** [comment]
Checked on `3.3.0-alpha.4` by running:
```
yarn add @storybook/react@3.3.0-alpha.4
```

Works as expected. The panel now scrolls after a resize.

Sorry I didn't check this before posting.

**Comment by harbin1053020115** [comment]
> Checked on `3.3.0-alpha.4` by running:
> 
> ```
> yarn add @storybook/react@3.3.0-alpha.4
> ```
> 
> Works as expected. The panel now scrolls after a resize.
> 
> Sorry I didn't check this before posting.

By the way, what is reason of this problem and how to fix it?
