### ISSUE TITLE
Addons > StoryShots > Docs - Tutorial behind paywall

### ISSUE THREAD

**Issue by mantissa7** [storybooks/storybook#2516]
### Issue details

What happens: 
Readme points to a resource that is behind a paywall.

What should happen: 
Resource should be generally available, or alternatives should be provided.

https://github.com/storybooks/storybook/blob/master/addons/storyshots/README.md

Under ** Configure your app for Jest** the docs mention that if Create React App is used then it's fine, otherwise refer to the link. The link is behind a paywall, and so can be impossible for some users to view.
Pointing to a resource that users must pay for to access is blocking access to using the addon for those that don't know how to configure.
Pointing to a "better" resource behind a paywall is probably fine, but providing a way for people to get started with the addon could help adoption.

It's also unclear what the link is alluding to. The link URL suggests it is Storybook agnostic, but it's difficult to be sure. Some better description might help people Google the answer if the setup has nothing to do with Storybook. It might be worth mentioning then that the configuration of Jest is entirely agnostic to Storybook if that is case and maybe point to the Jest docs. If the configuration is specific to Storybook, I think it might be unfair to force payment to use the addon.

I haven't used Jest before, and starting with StoryShots may be the wrong way to go about it. Perhaps mention that previous experience with Jest is assumed, else point to learning material or docs for Jest. 

I'm going to have a play with it and hopefully I'll remember to come back and make a PR.

**Comment by danielduan** [comment]
We should not be including any paywall content inside our docs. @ndelangen thoughts on possible alternative for link?

**Comment by ndelangen** [comment]
Hi @mantissa7, thanks for checking out storybook and storyshots, and opening up a ticket, the effort is appreciated.

To setup storyshots you need to have jest setup first. So indeed there's some knowledge required.

I have no problem linking to payed courses, people have to make a living.
What's described in the payed content is how to use and setup Jest. Which is a prerequisite to using storyshots, but it is a step we do not maintain any tooling or documentation for ourselves.

Having said all that, I'm fine with adding links to addition -non payed- content besides the existing link.
