### ISSUE TITLE
React 16 update and react portals not working

### ISSUE THREAD

**Issue by leetercola** [storybooks/storybook#2523]
### Issue details

Using latest react 16 and creating a story for elements created by ReactDOM.createPortal(child, container)  the modal components are rendering outside the iframe and add a portal to the page every time you click the story. I would expect that the elements would be rendered to a container element inside the preview iframe and to visiting the story link would not create multiple portal containers for each visit. 

### Steps to reproduce
create a story with an element added through ReactDOM.createPortal(child, container). In my case I'm using reactstrap@5.0.0-alpha.4 

### Please specify which version of Storybook and optionally any affected addons that you're running

- "@storybook/addon-actions": "^3.3.0-alpha.4",
- "@storybook/addon-links": "^3.3.0-alpha.4",
- "@storybook/addon-storyshots": "^3.3.0-alpha.4",
- "@storybook/react": "^3.3.0-alpha.4",
- "storybook": "^1.0.0",
- "storybook-addon-jsx": "^5.0.0",

### Affected platforms 
osx latest,
chrome latest
![screen shot 2017-12-19 at 2 44 47 pm](https://user-images.githubusercontent.com/581174/34178035-67335f58-e4cb-11e7-93ae-3a842d12393f.png)

**Comment by Hypnosphi** [comment]
What do you pass as `container` argument?

**Comment by leetercola** [comment]
By container argument what do you mean? Here is the relevant code for the story
`const stories = storiesOf('MDT Modal', module);

stories.addWithJSX('Modal', () => {
    const props = {
        title: "I'm a modal",
        icon: "error",
        contents:[],
        isOpen: true,
        footer: false,
        hasHeader: true
    };
    const wrapper = <MDTModal {...props} ><p>I'm modal body</p></MDTModal>;
    const wrapped = mount(wrapper);
    specs(() => describe('MDTButton enabled', () => {
        it('Should return a button without label', () => {
            expect(wrapped).toBeTruthy();
        });
    }));
    return wrapper;
});`

For reference here is the core components of the Modal implementation itself
`export class MDTModal extends PureComponent {
    constructor(props) {
        super(props);
        this.state = {
            isOpen: props.defaultOpen
        };
        this.toggle = this.toggle.bind(this);
    }

    render() {

        const {
            title,
            icon,
            contents = [],
            footer = false,
            hasHeader = true,
            toggle = _isOpen => this.toggle(_isOpen)
        } = this.props;

        const {
            isOpen
        } = this.state;

        const lineElements = contents.map(line => <p dangerouslySetInnerHTML={{__html: line}}></p>);

        return (
            <Modal isOpen={isOpen} toggle={toggle} wrapClassName="modal-content" className="modal-content">
                {hasHeader && <ModalHeader toggle={toggle}>
                    <div className="container-fluid">
                        <div className="row">
                            <div className="col-xs-12">
                                <h4 className="modal-title">
                                    {icon && <Icon face={"notification_" + icon} />}
                                    <span className="title">{title}</span>
                                </h4>
                            </div>
                        </div>
                    </div>
                </ModalHeader> }
                <ModalBody>
                    <div className="container-fluid">
                        <div className="row">
                            <div className="col-xs-12">
                                {lineElements}
                                {this.props.children}
                            </div>
                        </div>
                    </div>
                </ModalBody>
                {footer && <ModalFooter>
                    {footer}
                </ModalFooter>}
            </Modal>
        );
    }

    toggle (isOpen = false) {
        this.setState('isOpen', !isOpen);
    }
}`

**Comment by Hypnosphi** [comment]
> By container argument what do you mean

The second one in `ReactDOM.createPortal(child, container)`

**Comment by leetercola** [comment]
Looks like reactstrap has changed and isn't using portals. 
`document.body.appendChild(this._element);`
https://github.com/reactstrap/reactstrap/blob/5.0.0-alpha.4/src/Modal.js
I would think the reference for document should be the iframe though and not the parent container

**Comment by Hypnosphi** [comment]
Yes, it defenitely should be the iframe. 
Can you please create a GitHub repo with minimal reproduction of this?

**Comment by leetercola** [comment]
https://github.com/leetercola/storybook-issue

**Comment by leetercola** [comment]
I'm not entirely sure where the React Portals code is happening it's not in my code and it's not in the

**Comment by Hypnosphi** [comment]
Looks like your didn't `git add -A` before commiting: the repo is empty

**Comment by leetercola** [comment]
Well now I feel like a scrub. Updated repo

**Comment by Hypnosphi** [comment]
Ok it turns out that those `ReactModalPortal` divs are parts of storybook UI (namely, containers for shortcuts help and search box), not of your stories

**Comment by Hypnosphi** [comment]
Here's the change you need to make the modal visible: https://github.com/leetercola/storybook-issue/pull/1

**Comment by michaelaflores** [comment]
I have the same issue when using a ref as a container argument. It's strange as this code works normally but in storybook I get a react error that it's an invalid element.
