### ISSUE TITLE
Storybook Centered Decorator & IE11 compatability

### ISSUE THREAD

**Issue by brianespinosa** [storybooks/storybook#2525]
### Issue details

When using the [Storybook Centered Decorator](https://github.com/storybooks/storybook/tree/master/addons/centered) addon, it appears that it may be trying to center the component before the iframe has been rendered when using IE11. This causes the component top be rendered out of the viewport.

### Steps to reproduce

1. Configure Storybook with a global centered decorator in `config.js` 
2. Run Storybook in a virtual machine running IE11

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.2.18
- @storybook/addon-centered 3.2.18

### Affected platforms 

- IE11

### Screenshots / Screencast / Code Snippets (Optional)

![image](https://user-images.githubusercontent.com/1161781/34223499-662eae1a-e574-11e7-82a4-582d40ff4440.png)
![image](https://user-images.githubusercontent.com/1161781/34223690-206d380a-e575-11e7-87f4-968b07571e74.png)

**Comment by igor-dv** [comment]
I think browser detection is the best way. But everything that is not changing an existing functionality (there are people that may just rely on flex) will be a good PR.

**Comment by brianespinosa** [comment]
Thanks @igor-dv. I will submit a PR on this either late today or sometime tomorrow. You can assign this to me if you want.

**Comment by Hypnosphi** [comment]
FYI: `display: flex` works in IE11 without prefixes

**Comment by brianespinosa** [comment]
@Hypnosphi It only _partially_ works on IE11. There are still a number of bugs due to how IE11 implemented. The above screenshots are from IE11.

**Comment by Hypnosphi** [comment]
Most of those [bugs](https://github.com/philipwalton/flexbugs) have fixes, we just need to find one

**Comment by brianespinosa** [comment]
I still have not had time to submit a PR on this... but I think that on IE in general it would make sense to use a different strategy for centering altogether, one not relying on flexbox (as much as I love it). This will make the centered decorator also work in older versions of IE, not having to worry about vendor prefixes (IE10), or lack of support altogether past that.

For modern browsers the current flex implementation is best 👍 .

**Comment by Hypnosphi** [comment]
AFAIK we don't even try to support IE10
