### ISSUE TITLE
Incorrect isStorybook-check ("Storyshots is intended only to be used with storybook")

### ISSUE THREAD

**Issue by leoselig** [storybooks/storybook#2531]
### Issue details

The `hasDependency()`-check to verify if `addon-storyshots` is running in a storybook-project is looks up the first package.json's dependency list via [`read-pkg-up`](https://www.npmjs.com/package/read-pkg-up). If the dependency resides in the `node_modules` on higher level (e.g. in certain monorepos) this check gives a false positive and fails. However, a lookup due to an `import '@storybook/react'` **would** succeed in jest/Node.js/Webpack/etc.

### Steps to reproduce

1. Setup repository like this
```
- package.json (contains @storybook/*-dependencies for all packages)
- packages/
  - package1/
    - package.json (only contains per-package scripts)
    - .storybook/
    - test/
      - storybook.spec.js
```

2. Make the `storybook.spec.js` look like this:
```javascript
import initStoryshots from "@storybook/addon-storyshots";

initStoryshots();
```

3. Run jest on `package1`

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.2.18
- @storybook/addon-storyshots 3.2.18

### Affected platforms 
- macOS (Sierra, 10.12.6)
- Node.js 6.10.2
- npm 3.10.10
- Yarn 1.3.2
- Jest 22.0.3

**Comment by igor-dv** [comment]
There is a [`framework`](https://github.com/storybooks/storybook/tree/master/addons/storyshots#framework) prop that should help you. We actually use StoryShots in the Storybook monorepo as you describe.

**Comment by leoselig** [comment]
Oh, I apologize for missing that one. Thanks for helping out!

**Comment by kimamula** [comment]
I came across the error `storyshots is intended only to be used with storybook` which took several hours for me to find the solution (setting `framework`).
I wish the error message would have been much more helpful and informative.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.25 containing PR #6383 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
