### ISSUE TITLE
Upgrade failed: from 3.2.8 to 3.2.18

### ISSUE THREAD

**Issue by frankstallone** [storybooks/storybook#2534]
### Issue details

Current project running version 3.2.8. Running `npm update @storybook/react` will properly upgrade to 3.2.18. We are running full control mode + default. 

What did you expect to happen?
Storybook to run fine, as it did before.

What happened instead? 
During start up we see `Failed to load ./.env.`. Storybook continues to load. Bringing it up in the browser produces Storybooks sidebar with no stories. 

### Steps to reproduce

1. Project running Storybook 3.2.8 with a few stories and full control + default config. 
2. Run `npm update @storybook/react`. 
3. Starting Storybook

### Please specify which version of Storybook and optionally any affected addons that you're running

Before:
```
"@storybook/addon-actions": "^3.2.6",
"@storybook/addon-knobs": "^3.2.8",
"@storybook/addon-options": "^3.2.6",
"@storybook/react": "^3.2.8",
```
After:
```
"@storybook/addon-actions": "^3.2.6",
"@storybook/addon-knobs": "^3.2.8",
"@storybook/addon-options": "^3.2.6",
"@storybook/react": "^3.2.18",
```
(Only change is @storybook/react version)
### Affected platforms 

- macOX 10.12.6
- npm 5.6.0
- node 8.8.1

### Screenshots / Screencast / Code Snippets (Optional)

webpack.config.js:
```javascript
// load the default config generator.
const genDefaultConfig = require('@storybook/react/dist/server/config/defaults/webpack.config.js');
const path = require('path');

module.exports = (baseConfig, env) => {
  const config = genDefaultConfig(baseConfig, env);

  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    include: [
      path.resolve(__dirname, '../src/components'),
      path.resolve(__dirname, '../stories'),
      path.resolve(__dirname, '../src/utils')
    ],
    loader: require.resolve('ts-loader')
  });

  config.module.rules.push({
    test: /\.scss$/,
    use: [{
        loader: 'style-loader' // creates style nodes from JS strings
    }, {
        loader: 'css-loader' // translates CSS into CommonJS
    }, {
        loader: 'sass-loader' // compiles Sass to CSS
    }],
    include: path.resolve(__dirname, '../src/styles/')
  });
  
  config.module.rules.push({
    test: /\.png$/,
    loader: 'url-loader?mimetype=image/png'
  });
  
  config.module.rules.push({
    test: /globalize/,
    loader: 'imports-loader?define=>false'
  });

  config.module.rules.push({
    test: /cldr-data.+\.js$/,
    loader: 'imports-loader?define=>false'
  });

  config.module.rules.push({
    test: /storybook__react/,
    loader: 'imports-loader?define=>false'
  });

  config.resolve.extensions.push('.ts', '.tsx');

  return config;
};
```

Console Before:
```bash
> [repo name] start /Users/...
> npm run storybook


> [repo name] storybook /Users/...
> start-storybook -s ./public -p 9001 -c ./storybook

@storybook/react v3.2.16

=> Loading static files from: /Users/.../public .
=> Loading custom addons config.
=> Loading custom webpack config (full-control mode).
 13% building modules 27/56 modules 29 active ...nents/node_modules/ansi-html/index.jsts-loader: Using typescript@2.5.3 and /Users/.../tsconfig.json
webpack built 5cde44dc7d4c8fae9958 in 10098ms                                             
Storybook started on => http://localhost:9001/
```
Console After:
```bash
> [repo name]@3.5.0 start /Users/...
> npm run storybook


> [repo name]@3.5.0 storybook /Users/...
> start-storybook -s ./public -p 9001 -c ./storybook

@storybook/react v3.2.18

=> Loading static files from: /Users/.../public .
Failed to load ./.env.
=> Loading custom addons config.
=> Loading custom webpack config (full-control mode).
 12% building modules 23/52 modules 29 active ....cssts-loader: Using typescript@2.5.3 and /Users/.../tsconfig.json
webpack built 444de5aa9fc293e454bc in 9974ms                                              
Storybook started on => http://localhost:9001/
```

**Comment by frankstallone** [comment]
This also appears to fail in the same way when installing 3.2.17.

**Comment by frankstallone** [comment]
Appears to be two issues. I can see [in 3.2.17's changelog](https://github.com/storybooks/storybook/releases/tag/v3.2.17) dotenv was added. Fine, we don't use it.

Second issue: If I am running storybook on 3.2.18, console tells me:

```
Uncaught Error: Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
    at AddonStore.getChannel (index.js:39)
    at setOptions (index.js:37)
    at Object.<anonymous> (config.js:46)
    at Object.module.exports (config.js:51)
    at __webpack_require__ (bootstrap d5665a90f6818bbf8470:678)
    at fn (bootstrap d5665a90f6818bbf8470:88)
    at Object.window.STORYBOOK_REACT_CLASSES (TimeFinder.tsx:53)
    at __webpack_require__ (bootstrap d5665a90f6818bbf8470:678)
    at bootstrap d5665a90f6818bbf8470:724
    at bootstrap d5665a90f6818bbf8470:724
getChannel @ index.js:39
setOptions @ index.js:37
(anonymous) @ config.js:46
module.exports @ config.js:51
__webpack_require__ @ bootstrap d5665a90f6818bbf8470:678
fn @ bootstrap d5665a90f6818bbf8470:88
window.STORYBOOK_REACT_CLASSES @ TimeFinder.tsx:53
__webpack_require__ @ bootstrap d5665a90f6818bbf8470:678
(anonymous) @ bootstrap d5665a90f6818bbf8470:724
(anonymous) @ bootstrap d5665a90f6818bbf8470:724
```

Going to [Why is there no addons channel?](https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel) I see that I may have different version of addons. I updated them and now my devDependencies look like this:

```json
    "@storybook/addon-actions": "3.2.18",
    "@storybook/addon-knobs": "3.2.18",
    "@storybook/addon-options": "3.2.18",
    "@storybook/react": "3.2.18",
```

Blowing out the `node_modules` folder and starting a fresh `npm i` still produces the same results. Storybook loads, blank sidebar, panel and console has the same issue.

1. I am not doing addon development
2. I am not using React Native
3. "You have inadvertently installed multiple addons with differing versions. Upgrade or downgrade all @storybook/addon-* modules so they have the same version." 

Okay well I made them all the same but am still getting this console error. Thoughts? I'll update if I find something new. For now reverting back to the following works fine:

```json
    "@storybook/addon-actions": "3.2.16",
    "@storybook/addon-knobs": "3.2.16",
    "@storybook/addon-options": "3.2.16",
    "@storybook/react": "3.2.16",
```

**Comment by danielduan** [comment]
@frankstallone you must use all addons to the same version as your react storybook package. If you have any lock files, you must delete them when deleting node_modules as well.

**Comment by frankstallone** [comment]
Thanks @danielduan for the response. Fresh start this morning. 

1. Deleted `node_modules` folder
2. Deleted `package-lock.json` file
3. Updated `package.json`*
4. Ran `npm i`
5. Ran `npm run storybook`
6. Profit 💰

Everything seems to be working perfectly now. I presume not previously deleting the `package-lock.json` file was the final culprit.

* Updated `package.json`:
```
    "@storybook/addon-actions": "3.2.19",
    "@storybook/addon-knobs": "3.2.19",
    "@storybook/addon-options": "3.2.19",
    "@storybook/react": "3.2.19",
```
