### ISSUE TITLE
Module not found @storybook/addon-knobs/vue

### ISSUE THREAD

**Issue by DrSensor** [storybooks/storybook#2560]
### Issue details

I'm trying to use [poi](https://github.com/poi-examples/storybook-vue-example) for prototyping component. So far so good without knobs but when I added this to `config.js`

```
import { configure, addDecorator } from '@storybook/vue'
import { withKnobs } from '@storybook/addon-knobs/vue'

addDecorator(withKnobs)
```

It gives me this error
```
module not found:

- @storybook/addon-knobs/vue: imported at ~/Projects/OSS/vue-annotator/src/stories/index.js
```

I believe this is an issue in `@storybook/addon-knobs` because when I open the folder `node_modules/@storybook/addon-knobs` there is no `vue.js` nor `vue/index.js` and no `files: {}` in `package.json`

### Version
- @storybook/vue 3.2.19
- @storybook/addon-knobs 3.2.19

**Comment by Hypnosphi** [comment]
Those files were introduced only in version `3.3`
