### ISSUE TITLE
Angular getstorybook broken

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#2569]
### Issue details

Added storybook to a fresh angular project and it needs extra steps to install.

### Steps to reproduce

Here's what I expected to work:
```
ng new angular-test
cd angular-test/
yarn add @storybook/cli --dev
yarn run getstorybook
yarn run storybook
```

Here are the additional steps I had to take to get the example working:

```
yarn add @storybook/addon-notes --dev
yarn add @types/lodash-es --dev
yarn storybook
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/cli 3.3.0

### Affected platforms 

- This appears to be a problem with the CLI for angular

**Comment by igor-dv** [comment]
So is it fixed?
