### ISSUE TITLE
[unexpected behavior] Restrict Storybook to be opened inside Storybook

### ISSUE THREAD

**Issue by shobhitchittora** [storybooks/storybook#2573]
### Issue details

I was crating a `Link` component and gave `href` as `/` for the anchor tag.  This opened Storybook inside the rendering area of the main Storybook. 
Screenshot is attached below - 

![screen shot 2017-12-27 at 12 07 52 pm](https://user-images.githubusercontent.com/4711855/34373282-3e297198-eb00-11e7-80ca-2381dd4d3a63.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@kadira/react-storybook-addon-info` : ^3.4.0
- `@kadira/storybook` : ^2.35.3
- `@kadira/storybook-deployer` : ^1.2.0

### Affected platforms 

- Mac OS High Sierra ( 10.13.1 )

**Comment by igor-dv** [comment]
Looks like you are using a very old version of Storybook. Can you please try the @storybook/react v3.2.x

**Comment by shobhitchittora** [comment]
@igor-dv The new version does not have this issue. 👍🏻
But when I change `href` to '#', it opens up the iframe in for the component, with the url as - 
```
http://localhost:9009/iframe.html?selectedKind=Link&selectedStory=with%20text
```
Is this an intended behavior?

**Comment by Hypnosphi** [comment]
What would you expect instead in that case?
