### ISSUE TITLE
Haul support for React Native not working on Windows

### ISSUE THREAD

**Issue by FredyC** [storybooks/storybook#2575]
### Issue details

I am trying to configure `storybook-react-native` with Haul because I want to use Typescript loader. On my Windows machine I end up with this error.

```bash
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
```

### Steps to reproduce

Run following on the Windows machine
`storybook start -p 7007 --haul webpack.haul.storybook.js`

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react-native: 3.3.1

### Affected platforms 

Windows 10

### Screenshots / Screencast / Code Snippets (Optional)

**webpack.haul.storybook.js**
```js
module.exports = ({ platform }, { module, resolve }) => ({
  entry: `./storybook/index.js`,
  module: {
    ...module,
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
      },
      ...module.rules,
    ],
  },
  resolve: {
    ...resolve,
    extensions: [
      '.ts',
      '.tsx',
      `.${platform}.ts`,
      '.native.ts',
      `.${platform}.tsx`,
      '.native.tsx',
      ...resolve.extensions,
    ],
  },
})
```

**Comment by Hypnosphi** [comment]
Fix released as [`3.3.4`](https://github.com/storybooks/storybook/releases/tag/v3.3.4)
