### ISSUE TITLE
Snapshot and reloading slowdown in 3.3.1

### ISSUE THREAD

**Issue by greggb** [storybooks/storybook#2583]
### Issue details

When using Storyshots with version 3.2.17 my tests generally run in about 15 seconds. After upgrading to 3.3.1 (all storybook packages), they are taking well over a minute.

Hot reloading has also increased from 1.9s to 4s after the upgrade.

Aside from the slowdown a few of my snapshots no longer match after the upgrade. For instance:
using `jest-glamor-react`
```
    -       className="glamor-2 glamor-3"
    +       className="glamor-1 e15dl3171"
```

### Steps to reproduce
My setup creates the snapshots as a sibling directory to my component. There are 60 snapshots across 16 components. Typical code for a UI test is:
```js
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots({
    configPath: './configs/.storybook',
    storyKindRegex: /^Buttons$/,
});
```

My Config look like this:
```js
import React from 'react';
import { configure, addDecorator } from '@storybook/react';
import initGlobalStyles from '../theme/globalStyles';

const req = require.context('..', true, /\.stories\.js$/);
if (process.env.NODE_ENV !== 'test') {
    addDecorator((story, context) => withInfo()(story)(context));
}
addDecorator(story => {
    initGlobalStyles();
    return <div>{story()}</div>;
});

function loadStories() {
    req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

### Please specify which version of Storybook and optionally any affected addons that you're running

 -  `@storybook/react 3.3.1`
 -  `@storybook/addon-storyshots 3.3.1`

### Affected platforms 
This is happening on the latest version of MacOS and the latest version of React. All tests are run with Jest, but updating Jest from 21.0.2 -> 22.0.4 did not have any effect.

**Comment by greggb** [comment]
3.3.3 has reduced this down to `Time: 31.207s`. I haven't dug into why yet. Also seems like my snapshots are back to all being correct.

Storybook recompile time back down to 2s as well.

Thanks folks - So happy I can upgrade now.

**Comment by greggb** [comment]
Just as a data point for anyone that may find this issue. Moving `initStoryshots` into a single file and not outputting to individual directories takes my test run from 31 seconds to 8 seconds. The organization of `storyKindRegex` doesn't seem to be worth the hit in speed.

**Comment by igor-dv** [comment]
Did you try the multisnapshot option ?

**Comment by greggb** [comment]
@igor-dv Yes, and it did exactly what I needed, but I wasn't able to get the [emotion serializer](https://github.com/emotion-js/emotion/blob/master/docs/testing.md) to work, so I'll need to revisit in the future.

I tried moving my testSetup serializer config into the init config, but no luck.

```
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';
import * as emotion from 'emotion';
import { createSerializer } from 'jest-emotion';
initStoryshots({
    configPath: './configs/.storybook',
    test: multiSnapshotWithOptions({
        serializer: createSerializer(emotion),
    }),
});

```

**Comment by iasinov** [comment]
@greggb Have you resolved emotion serializer issue? I get different snapshots on different platforms (Windows and Mac/Linux) for this reason.
Thanks
