### ISSUE TITLE
Hot Module Reload not working properly for `@storybook/react@3.3.1`

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#2587]
### Issue details

Due to https://github.com/storybooks/storybook/pull/2503

if you change a story's or component's implementation, it will not re-render on HMR.

### Steps to reproduce

Simply change any of the story implementations in kitchen-sink

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.3.1

**Comment by tmeasday** [comment]
See https://github.com/storybooks/storybook/pull/2588

**Comment by tmeasday** [comment]
Fixed in 3.3.2

**Comment by tmeasday** [comment]
I wonder if vue has this same problem: 

https://github.com/storybooks/storybook/blob/03f04e03dab9c1230be1b90afc60664674bbc59f/app/vue/src/client/preview/render.js#L63-L72

[Not introduced in 3.3 but there anyway?]

I'm not sure who to @ here @ndelangen

**Comment by ndelangen** [comment]
Could @ @kazupon ?
