### ISSUE TITLE
storybook-readme broken after version 3.3.0 update

### ISSUE THREAD

**Issue by lufego** [storybooks/storybook#2593]
### Issue details

After the update of `@storybook/react` to version 3.3.0, `@storybook-readme` addon seems to be broken

### Steps to reproduce

| Before | After |
|:---|:---|
|<img width="849" alt="screen shot 2017-12-28 at 14 28 09" src="https://user-images.githubusercontent.com/14938754/34412186-1c3d7df4-ebdc-11e7-8eba-60068e321921.png">|<img width="848" alt="screen shot 2017-12-28 at 14 29 53" src="https://user-images.githubusercontent.com/14938754/34412193-24d13e9c-ebdc-11e7-83b1-93290095ec6c.png">|

### Please specify which version of Storybook and optionally any affected addons that you're running

- from `@storybook/react` 3.3.0
- `@storybook-readme/with-readme` 3.1.1

### Screenshots / Screencast / Code Snippets (Optional)

```js
import withReadme from 'storybook-readme/with-readme';
import ReadmeFile from './README.md';

storiesOf('Example', module)
  .addDecorator(withReadme(ReadmeFile))
  .add('Component', () => (
    <Component />
  ));
```

**Comment by tuchk4** [comment]
@lufego I will fix this bug in few days

**Comment by tuchk4** [comment]
Try `storybook-readme@3.2.0`. Ping if any issues.

Not that now there are no additional webpack configuration for React Storybook.

https://github.com/tuchk4/storybook-readme#webpack-configuration-for-react-storybook

**Comment by tuchk4** [comment]
Close this issue for now.

Please reopen is any problems.
