### ISSUE TITLE
Add visual/css diffing

### ISSUE THREAD

**Issue by jakedeichert** [storybooks/storybook#26]
Just an idea, but it would be cool to see pixel-perfect diffing of your components/stories to see how they progress over time?

[PhantomCSS](https://github.com/Huddle/PhantomCSS#phantomcss) is a great example of what I mean.

**Comment by garris** [comment]
There is a probably a straightforward way to integrate BackstopJS (similar to PhantomCSS but with a workflow & UI tuned for diff-ing many states and viewport sizes).  If there is some interest I could look into it.

**Comment by wyattdanger** [comment]
I am currently using https://github.com/Galooshi/happo for visual diffing React components

**Comment by arunoda** [comment]
@wyattdanger Thanks. I saw you guys use it at AirBnb.

**Comment by sylvainbannier** [comment]
@wyattdanger have you managed to reuse react storybook stories with happo ?

**Comment by bartlomn** [comment]
Correct me if I am wrong but it looks like all the solutions linked so far use PhantomJs and therefore are suited for the CI integration. I am looking at slightly different use case - I would like to have an add-on that will add a panel with image diff for current story variant. I am looking at [Resemble.js](http://huddle.github.io/Resemble.js/) for that. Any advice / pointers / prior art / encouragements are welcome.

**Comment by garris** [comment]
BackstopJS is a wrapper around resemble.  It manages all the necessary resources for capturing screen shots, reporting and then displaying the diffs.  You can call it like a node module as well.   I am too busy to do the integration work but I'd happily guide you through it.

**Comment by ndelangen** [comment]
Storybook will not build visual regression testing, because there are tools that do it that integrate very nicely into Storybook. 

See:
https://percy.io/docs/clients/javascript/react-storybook
https://screener.io/

**Comment by oblador** [comment]
These are both paid services for web as far as I understand them. I'm working on a solution that works locally for both web, ios and android.

**Comment by ndelangen** [comment]
Be sure to let us know about if when it's demo-able we can feature it on our documentation 👍

**Comment by heinzmuller** [comment]
@oblador Give me a heads up if you need any testers/help with coding!

I looked at the suggestions @ndelangen but Percy seems very pricey, and screener will probably cost about the same.

**Comment by oblador** [comment]
@heinzmuller sure, DM me on twitter (@trastknast).
