### ISSUE TITLE
[3.3.3, addon-info] Incorrect parse props with babel-plugin-flow-react-proptypes

### ISSUE THREAD

**Issue by DimaRGB** [storybooks/storybook#2603]
### Issue details

`OneOfType` and `ArrayOf` try to get [propType.value](https://github.com/storybooks/storybook/blob/master/addons/info/src/components/types/OneOfType.js#L7) but only have `propType.elements`.

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at OneOfType (OneOfType.js:21)
```

```
The above error occurred in the <OneOfType> component:
    in OneOfType (created by PrettyPropType)
    in PrettyPropType (created by PropTable)
    in td (created by glamorous(td))
    in glamorous(td) (created by PropTable)
    in tr (created by PropTable)
    in tbody (created by PropTable)
    in table (created by glamorous(table))
    in glamorous(table) (created by PropTable)
    in PropTable
    in Unknown (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in Story
```

### Steps to reproduce

Use `babel-plugin-flow-react-proptypes` and union prop:

```
type Props = {
  unionProp: 'one' | 'two',
};

class A extends Component<Props> {}
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react 3.3.3`
- `@storybook/addon-info 3.3.3`
- `react 16.2.0`
- `flow-bin 0.62.0`
- `babel-plugin-flow-react-proptypes 13.0.1`

**Comment by tobilen** [comment]
can confirm. it also throws the same error without using babel-plugin-flow-react-proptypes though.

after some testing, i can boil it down to:
```js
// component.js
// @flow
import React from 'react';

type Props = {
  someValue?: 'one' | 'two' | 'three',
};

const SomeComponent = (props: Props) => <span>hey there</span>;

export default SomeComponent;
```

```js
// mystory.js
import React from 'react';
import { storiesOf } from '@storybook/react';
import SomeComponent from './component';

storiesOf('Example', module).add('error', () => <SomeComponent />); // afforementioned exception
```

or, in other words, have a component file with flow typing and union type (if story and component are declared in the same module, it'll work fine), try to render a story with this component and it'll throw.
if the component is being wrapped within another component in the story file, it'll also work (probably because addon-info doesnt look for proptypes recursively?), i.e.:
```js
// mystory.js
import React from 'react';
import { storiesOf } from '@storybook/react';
import SomeComponent from './component';

const Proxy = () => <SomeComponent />;

storiesOf('Example', module).add('error', () => <Proxy />); // no error. also, no prop types
```

**Comment by dlebedynskyi** [comment]
Any progress on this issue ?

**Comment by Hypnosphi** [comment]
#2902 should fix that

**Comment by Hypnosphi** [comment]
@DimaRGB Unfortunately, I can't find a simple solution for this (there is a [complex one](https://stackoverflow.com/questions/39194648/npm-install-package-from-github-repo-subfolder) though)

So you probably need to wait until the weekend release

**Comment by DimaRGB** [comment]
@Hypnosphi thanks :)
