### ISSUE TITLE
Unable to extend my webpack config

### ISSUE THREAD

**Issue by TomYeoman** [storybooks/storybook#2607]
### Issue details

Storybook is saying I don't have a CSS loader after attempting to extend the webpack config to allow for SASS in addition to CSS. It seems my webpack is getting overritten rather than extended

### Steps to reproduce

add **.storybook/webpack.config.js** with the following code

```
const path = require("path");

module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"],
        include: path.resolve(__dirname, "../")
    }
    ]
  }
};
```

![image](https://user-images.githubusercontent.com/14075632/34437888-3159140a-ec9a-11e7-8d56-5dcd9efc1628.png)

I've tried manually adding the cssLoader

const path = require("path");

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"],
        include: path.resolve(__dirname, "../")
    },
    {
        test: /\.css$/,
        use: ["style-loader", "css-loader"],
        include: path.resolve(__dirname, "../")
      }
    ]
  }
};
```
But then recieve this new error

![image](https://user-images.githubusercontent.com/14075632/34437914-926160fe-ec9a-11e7-8d6d-6d867b7edf93.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

    "@storybook/react": "^3.3.2",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",

### Affected platforms 

Windows 10

**Comment by ndelangen** [comment]
Please use the [Webpack2 syntax](https://webpack.js.org/configuration/)

**Comment by ndelangen** [comment]
This might be what you need:
https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode

**Comment by TomYeoman** [comment]
@ndelangen thanks for the speedy response!

That certainly looks like it would achieve what i'd be after, however i'm still experiencing the same error about needing a CSS loader after using that code aswell

webpack.config.js

```
const path = require("path");

// Export a function. Accept the base config as the only param.
module.exports = (storybookBaseConfig, configType) => {
  // configType has a value of 'DEVELOPMENT' or 'PRODUCTION'
  // You can change the configuration based on that.
  // 'PRODUCTION' is used when building the static version of storybook.

  // Make whatever fine-grained changes you need
  storybookBaseConfig.module.rules.push({
    test: /\.scss$/,
    loaders: ["style-loader", "css-loader", "sass-loader"],
    include: path.resolve(__dirname, "../")
  });

  // Return the altered config
  return storybookBaseConfig;
};
```

Error

![image](https://user-images.githubusercontent.com/14075632/34438184-cdbe98a4-ec9c-11e7-9adf-7906d766fe29.png)

Again the CSS loads fine without that webpack.config.js

**Comment by ndelangen** [comment]
the logged webpack config IS missing the css loaders..

**Comment by psimyn** [comment]
@TomYeoman it is failing to load a `.css` file because your loader is only configured for `.scss` files.

change `test: /\.scss$/,`

to `test: /\.s?css$/,`


```
const path = require("path");

// Export a function. Accept the base config as the only param.
module.exports = (storybookBaseConfig, configType) => {
  // configType has a value of 'DEVELOPMENT' or 'PRODUCTION'
  // You can change the configuration based on that.
  // 'PRODUCTION' is used when building the static version of storybook.

  // Make whatever fine-grained changes you need
  storybookBaseConfig.module.rules.push({
    test: /\.s?css$/,
    loaders: ["style-loader", "css-loader", "sass-loader"],
    include: path.resolve(__dirname, "../")
  });

  // Return the altered config
  return storybookBaseConfig;
};
```

**Comment by nimadera** [comment]
@TomYeoman, assuming you're using Material UI, wrapping the component in `<MuiThemeProvider>` within Storybook should get rid of the "Cannot read property 'prepareStyles' of undefined" error.

**Comment by hollandmatt** [comment]
FWIW, this is how I managed to accomplish adding a loader to the default webpack config: https://gist.github.com/hollandmatt/eae06135edc5cbfa6668d99a5333cc53
