### ISSUE TITLE
Storybook does not process .babelrc extends correctly

### ISSUE THREAD

**Issue by adamchenwei** [storybooks/storybook#2610]
### Issue details

_Please provide issue details here - What did you expect to happen? What happened instead?_ 
I expect `npm run storybook` to load correctly without errors show in screenshot below
### Steps to reproduce
get react-static, produce a site, install storybook-cli globally then `getstorybook` in the react-static produced base site.

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._
https://github.com/nozzle/react-static
_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running
@storybook/cli@3.3.3
@ "react": "^16.0.0",

### Affected platforms 
Win10

### Screenshots / Screencast / Code Snippets (Optional)
![image](https://user-images.githubusercontent.com/4201698/34457853-57a988d6-ed8c-11e7-9bbf-73890572f8d7.png)

```js
// code here
```

**Comment by Hypnosphi** [comment]
Here's the `.babelrc` this generator produces:
```
{
  "extends": "react-static/.babelrc"
}
```

Looks like we don't process this `extends` properly

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.20`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.20)
