### ISSUE TITLE
getstorybook doesn't work

### ISSUE THREAD

**Issue by kotpal** [storybooks/storybook#2617]
### Issue details

Followed the steps to create a storybook, but got an error when I ran getstorybook command:
 getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
    We couldn't detect your project type. (code: UNDETECTED)
    Please make sure you are running the `getstorybook` command in your project's root directory.
    You can also follow some of the slow start guides: https://storybook.js.org/basics/slow-start-guide/

### Steps to reproduce

npm i -g @storybook/cli
cd my-angular-project
getstorybook
npm run storybook

### Please specify which version of Storybook and optionally any affected addons that you're running

@storybook/cli

### Affected platforms 

-

### Screenshots / Screencast / Code Snippets (Optional)

-

**Comment by shilman** [comment]
Do you have a public repo I can look at to help diagnose and suggest a fix? Thanks!

**Comment by ersel** [comment]
Detect logic depends on inspecting the `package.json` file to figure out which generator template to run, it would be help if you could share the `package.json` file at least.

**Comment by kotpal** [comment]
I was just following the steps. What was missing in the steps - and I figured it out after reading more about how Storybook operates - is the creation of the appropriate app (be it React, Angular or Vue). 

I got the getstorybook to work. I see only the button components for Angular. I don't see any other components that are shown in the Medium post. What am I missing here?

**Comment by alterx** [comment]
@kotpal, the components you see in the post are just sample components you can find in the [sample app](https://github.com/storybooks/storybook/tree/master/examples/angular-cli/src/stories), most of them *are not* included if you use `getstorybook` to create a new project.

Since this is expected and you got  `getstorybook` working I'm going to close this issue :)
