### ISSUE TITLE
Info addon - setting an option within the story without using addWithInfo

### ISSUE THREAD

**Issue by tourshi** [storybooks/storybook#2619]
### Issue details

Is there a way to set the info addon options per story? I've added the info addon globally so that all my stories have the info-addon activated but what I would like to do is also pass options to an individual story. Particularly, the option to show PropTable or exclude a component from a PropTable. 

is this possible?

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.3.1
- @storybook/addon-something 3.3.1

Thank you

**Comment by psimyn** [comment]
you can use `withInfo`, example: https://github.com/storybooks/storybook/tree/master/addons/info#usage-with-options

**Comment by JonShort** [comment]
> Particularly, the option to show PropTable or exclude a component from a PropTable.

The `propTables` & `propTablesExclude` options accept arrays to configure the prop table on a per-story basis.

example - `ExampleComponent` story which excludes the prop table for the component, and shows prop tables for `Button` and `Align` component instead:
```
.add(
  'Example',
  withInfo({
    propTables: [Button, Align],
    propTablesExclude: [ExampleComponent],
  })(() => (
    <ExampleComponent />
  )),
)
```

Some more info on the available options [here](https://github.com/storybooks/storybook/tree/master/addons/info#options-and-defaults)

**Comment by tourshi** [comment]
Thank you @psimyn @JonShort 
I was hoping not to use 'withInfo' because I've set it globally and  if i am understanding correctly, I cannot use withInfo() if I've set the addon globally. 

> It is possible to add infos by default to all components by using a global or story decorator. The drawback is you won't be able to display a distinct info message per story.
https://github.com/storybooks/storybook/tree/master/addons/info#usage-as-decorator

In any case, I tried it, but I don't seem to be getting any output, here is my code:
`.add(
    'Default',
    withInfo(
      { propTablesExclude: [AppBanner] },
      withNotes("<p>mynote...</p>")(() => (
        <div>
          <AppBanner />
          <Window />
        </div>
      ))
    )
  )`

Thank you, I appreciate all the help!

**Comment by sam6ber** [comment]
Hello,
Try this : 

.add( 'Default',
withInfo( { propTablesExclude: [AppBanner] }) (
  withNotes("<p>mynote...</p>")(
    () => ( <div> <AppBanner /> <Window /> </div> )
  ) )
)

**Comment by danielduan** [comment]
Our current addon API does not allow global addons with customizations per story. It's a limitation we have to work with until our addon API gets refactored.

I apologize that we don't have a solution and I'm going to close this ticket.
