### ISSUE TITLE
Angular 2 APP_BASE_HREF problem

### ISSUE THREAD

**Issue by karlos1337** [storybooks/storybook#2620]
### Issue details
Can't load a component because of APP_BASE_HREF provider, I try to load component loading only  necesary dependencies and importing all AppModule, same error on loading APP_BASE_HREF, not sure but maybe because StoryBook adds `<base target="_parent">` to the iframe.
### Steps to reproduce
* Create a story for a component from an app with `<base href="/">`.
* With `providers: [  ]`
    * `No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document. ; Zone: <root> ; Task: Promise.then ; Value:`
* With `providers: [ { provide: APP_BASE_HREF, useValue: '/' }  ]`
    * `Can't resolve all parameters for NewComponent: ([object Object], [object Object], [object Object], [object Object], [object Object], [object Object], ?)`
### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook: 3.3.3
- @angular: 4.3.2

**Comment by igor-dv** [comment]
@karlos1337 , can you please provide a code example?

**Comment by glebmachine** [comment]
Got the same(

**Comment by alterx** [comment]
Guys, we'd love to look into this but we need a code example to replicate, if we don't have that sadly, we're going to focus on other bugs/features that we can properly replicate and diagnose.

**Comment by vidarc** [comment]
You can use manager-head.html in your storybook config directory to fix this. [Docs here](https://storybook.js.org/configurations/add-custom-head-tags/).

Just need to add:
``` html
<base href='/'>
```

**Comment by alterx** [comment]
@karlos1337 I haven't been able to replicate the errors you're getting when injecting the provider with our latest alpha. There's also a way to overwrite this behavior using @vidarc's example. I'm closing this since the main issue is resolved and we can't do more without an example to replicate. Please feel free to open a new issue for the injection bug (if you can replicate with the latest alpha).

**Comment by ibnYusrat** [comment]
> You can use manager-head.html in your storybook config directory to fix this. [Docs here](https://storybook.js.org/configurations/add-custom-head-tags/).
> 
> Just need to add:
> 
> ```
> <base href='/'>
> ```

Where is the storybook config directory?
