### ISSUE TITLE
[3.3.3 storybook/react] Content in panels is escaped

### ISSUE THREAD

**Issue by tobilen** [storybooks/storybook#2622]
### Issue details

Generated Content (as done by the [storybook-readme](https://github.com/tuchk4/storybook-readme) addon) is being auto escaped. The HTML is (ultimately) set via dangerouslySetInnerHTML (see https://github.com/acdlite/react-remarkable/blob/master/src/index.js#L31 ), addon worked prior to 3.3

addon-notes works fine **as long as no loader (like `raw-loader`) is specified in the webpack config**. If there is, the markup will also be escaped (since its wrapped in a `p` tag). Unfortunately, notes still cant be set via `addDecorator` as far as i can see, which means its not a drop-in replacement for us.

### Steps to reproduce

Provide readme to `withReadme` function like so:
```js
import React from 'react';
import { storiesOf } from '@storybook/react';
import withReadme from 'storybook-readme/with-readme';
import Readme from './readme.md';

storiesOf('story', module)
  .addDecorator(withReadme(Readme))
  .add('normal', () => (
    <span>Hello World</span>
  ));
```

HTML in readme panel will be escaped.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.3.3

### Screenshots / Screencast / Code Snippets (Optional)
With `raw-loader` in webpack config for *.md files (working fine in 3.2.x):
![image](https://user-images.githubusercontent.com/8217788/34499879-891af0ac-f008-11e7-9b20-8396da0db4ea.png)

Without `raw-loader`:
![image](https://user-images.githubusercontent.com/8217788/34499851-569cd352-f008-11e7-9499-c6fcb3371eda.png)

**Comment by tobilen** [comment]
duplicate of https://github.com/storybooks/storybook/issues/2593 👼

**Comment by tuchk4** [comment]
@tobilen now fixed.

Try `storybook-readme@3.2.0`

**Comment by tobilen** [comment]
works like a charm. nicely done ❤️

**Comment by tobilen** [comment]
@tuchk4 looks like storyshots are failing though:
```
 FAIL  stories\Storyshots.test.js
  ● Test suite failed to run

    D:\WebProjects\iris\node_modules\rockey-react\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import when from 'rockey/when';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
      at Object.<anonymous> (node_modules/storybook-readme/env/react/components/StoryPreview.js:6:20)
      at Object.<anonymous> (node_modules/storybook-readme/env/react/index.js:11:21)
```

seems like the code wasnt transpiled before publishing?
