### ISSUE TITLE
[Angular] Styles in .css files are not applied

### ISSUE THREAD

**Issue by Quramy** [storybooks/storybook#2629]
### Issue details

Styles in .css files are not applied to Storybook's iframe:

I wrote the following component with `styleUrls`:

```ts
/* my-button.component.ts */
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-my-button',
  templateUrl: './my-button.component.html',
  // use `styleUrls`: styles are not applied...
  styleUrls: ['./my-button.component.css'],
})
export class MyButtonComponent {
}
```

and 

```css
/* my-button.component.css */
p {
  color: red;
}
```

But the component rendered by Storybook is not applied this style ( the font-color is black).

And I use not `styleUrls` but `styles`:

```ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-my-button',
  templateUrl: './my-button.component.html',
  // use `styles`: red color applied
  styles: [`
    p {
      color: red;
    }
  `],
})
export class MyButtonComponent {
}
```

then, the component gets red colored.

### Steps to reproduce
I've created the reproducing repo:

```sh
git clone https://github.com/Quramy/storybook-ng-css.git
cd storybook-ng-css
npm run storybook
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/angular`:  3.3.3

And:

- `@angular/core`: 5.1.2
- `@angular/cli`: 1.5.4

**Comment by igor-dv** [comment]
Yeah, I'm familiar with this issue. It is because in this way `css` is not loaded as expected. Storybook has already a css rules that puts all the css to the `<style>` tag. So probably you need to take the full control mode of the `webpack.config` and to replace the existing css loaders with yours. And you probably need just to use the `raw-loader` 
Another solution is to use `scss` and add only scss related loaders to the webpack.config

**Comment by igor-dv** [comment]
So, did it work?

**Comment by Quramy** [comment]
Yeah. The above config works well.

**Comment by igor-dv** [comment]
Cool. I think it worth adding to `app/angular` docs. Would you mind to PR it?

**Comment by Quramy** [comment]
> Would you mind to PR it

OK, I'll send! 😄  Which file should I add? ( I think `docs/src/pages/basics/guide-angular/index.md` or `docs/src/pages/configurations/custom-webpack-config/index.md`)

**Comment by igor-dv** [comment]
I think start from the `docs/src/pages/basics/guide-angular/index.md` =)

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.6 containing PR #8200 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
