### ISSUE TITLE
new addson: story with a form to insert component value

### ISSUE THREAD

**Issue by jurgob** [storybooks/storybook#263]
What do you think about this idea? basically it's something like this project:
https://github.com/carteb/carte-blanche

The corner-case automatic generation could be really something

**Comment by arunoda** [comment]
@jurgob Yep. We talked with the authors. It's a great project.

For editing props, we've an discussion here - https://github.com/kadirahq/react-storybook/issues/166 I'm not sure, that can be done without changing the core of storybook.

But, corner case auto generation is something we can do with a addon. Actually, carte-blanche does not have that functionality. They just trick us with a nice screenshot :) But, that's a very coool idea.

**Comment by ndelangen** [comment]
I think `addon-knobs` fills this role now.
