### ISSUE TITLE
Missing capture in background addon readme

### ISSUE THREAD

**Issue by amireynoso** [storybooks/storybook#2642]
### Issue details
There capture image for the background addon in the readme is missing. It's linking to `https://github.com/storybooks/storybook/blob/master/addons/background/.storybook/backgrounds.gif` but there's nothing there.

### Steps to reproduce
Browse https://github.com/storybooks/storybook/tree/master/addons/background

### Screenshots / Screencast / Code Snippets (Optional)

![Image](https://user-images.githubusercontent.com/1855829/34567170-ec79708c-f13f-11e7-914c-ee2a05ea3580.png)

**Comment by ndelangen** [comment]
I will fix it
