### ISSUE TITLE
[Bug] Angular Components

### ISSUE THREAD

**Issue by amcdnl** [storybooks/storybook#2647]
I have 3 different bugs I've identified in this repo: https://github.com/amcdnl/angular-storybook-issue

### Basic
In the basic scenario, I import my app component and nothing renders.

### Basic 2
In the basic 2 scenario, I use a component directly that has a nested module dependency and its not resolving that module. It throws the following errors:

```
'app-test' is not a known element:
1. If 'app-test' is an Angular component, then verify that it is part of this module.
2. If 'app-test' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<div>
  Test?
  [ERROR ->]<app-test></app-test>
  <nav aria-label="Page navigation">
    <ul class="pagination">
"): ng:///NewModule/NewComponent.html@2:2 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
'app-test' is not a known element:
```

### CSS
The `boostrap.css` file included `config.js` is never injected.

**Comment by ralzinov** [comment]
Hello thank you for feedback, i have looked on your example, and at first story you trying to bootstrap app.component into another module, but i think it is not valid case (tell me if i wrong, [i have checked](https://stackblitz.com/edit/angular-mq4rrq) and got exactly the same error with pure angular) 
I think you should export component from module if you want it to render. Second is that "app-root" selector is actually occupied by storybook itself, (so that definitely should be fixed). With these changes fixed, the first example is working.

**Comment by amcdnl** [comment]
Any ideas on the styles? The others I can work around.

**Comment by alterx** [comment]
Yeah, the explanation for this behavior is that we create an inner module that contains our main component (this component dynamically renders each story). Since the nested `TestingModule` module can only be used by the module that's importing it `AppModule`, the component is not available for our own module. Doing something like this should work for issue #2: 

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    TestModule
  ],
  providers: [],
  bootstrap: [AppComponent],
  exports: [
    BrowserModule,
    TestModule
  ]
})
export class AppModule { }
```

**Comment by igor-dv** [comment]
@amcdnl , regarding the css:

Css in this case used in two different context: 
1. like an import as you did - for this we use style-loader
2. like a styleUrl in component - for this we need raw-loader

So we have a collision between css rules. 

What can you do: Use this [feature](https://storybook.js.org/configurations/add-custom-head-tags/) for the `boostrap.css`. Or even [this](https://storybook.js.org/configurations/serving-static-files/).

Or add an exclusion for the `bootstrap.css` in the custom `webpack.config` (there is already one for components):
```js
  const cssRule2 = config.module.rules.find(rule => rule.test && rule.test.toString() === '/\\.(html|css)$/');
  if (cssRule2) {
    cssRule2.exclude = /bootstrap\.css$/;
  }
```

**Comment by amcdnl** [comment]
I was just showing that 2 different ways of doing it. Neither worked for me.

**Comment by Hypnosphi** [comment]
Fix released as [`3.3.4`](https://github.com/storybooks/storybook/releases/tag/v3.3.4)

**Comment by igor-dv** [comment]
@amcdnl , did you manage to make css working?

**Comment by alterx** [comment]
Not sure we should be closing this one. Issues 1 and 2 have a workaround and an explanation so I think we're good with those (#2657 is not directly related). 

It looks like issue # 3 is still happening tho (?)

**Comment by Hypnosphi** [comment]
Oh sorry. I just stated "Issue: #2647"

**Comment by amcdnl** [comment]
Feedback for CSS work around:

```
const config = {
    rules: [{
        test: /\.ts$/,
        use: [{
            loader: 'awesome-typescript-loader',
            options: {
                configFileName: path.join(currentDir, '/storybook/config/tsconfig.json'),
                ignoreDiagnostics: [
                    2300 // omit 'TS2300: Duplicate identifier' type of errors
                ]
            }
        }]
    }, {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader'
    }, {
        test: /\.css$/,
        exclude: /\.async\.(css)$/,
        use: [
            {loader: 'style-loader'},
            {loader: 'css-loader'}
        ]
    }, {
        test: /\.html$/,
        loader: 'raw-loader',
        exclude: /\.async\.(html)$/
    }, {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: [{
            loader: 'url-loader',
            options: {
                limit: 10000,
                mimetype: 'application/font-woff'
            }
        }]
    }, {
        test: /\.(jpe?g|png|gif)$/i,
        use: [{
            loader: 'file-loader',
            options: {
                hash: 'sha512',
                digest: 'hex',
                name: '[hash].[ext]'
            }
        }]
    }, {
        test: /\.md$/,
        use: [{
            loader: 'html-loader'
        }, {
            loader: 'markdown-loader'
        }]
    }]
};
module.exports = (storybookBaseConfig) => {
    storybookBaseConfig.module.rules = config.rules;
    return storybookBaseConfig;
};
```

**Comment by amcdnl** [comment]
The following config worked me around the CSS issue.

```
const genDefaultConfig = require('@storybook/angular/dist/server/config/defaults/webpack.config.js');

module.exports = (baseConfig, env) => {
    const config = genDefaultConfig(baseConfig, env);

    const cssRule = config.module.rules.find(rule => rule.test && rule.test.toString() === '/\\.css$/');
    if (cssRule) {
        cssRule.exclude = /\.component\.css$/;
    }

    const cssRule2 = config.module.rules.find(rule => rule.test && rule.test.toString() === '/\\.(html|css)$/');
    if (cssRule2) {
        cssRule2.exclude = /bootstrap\.css$/;
    }

    config.module.rules.unshift({
        test: /\.component.scss$/,
        loaders: ['raw-loader', 'sass-loader']
    });

    config.module.rules.unshift({
        test: /\.component.css$/,
        loaders: ['raw-loader', 'css-loader']
    });

    config.module.rules.unshift({
        test: /\.scss$/,
        exclude: /\.component.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader']
    });

    return config;
};
```

**Comment by alterx** [comment]
Will close this one since there's a workaround for issue # 3 and, # 1 and # 2 work as expected. Also, there's related work happening in https://github.com/storybooks/storybook/issues/2688 🎉
