### ISSUE TITLE
[Addon Info] React warns unique "key" prop when using PropTypes.oneOfType

### ISSUE THREAD

**Issue by lcsrinaldi** [storybooks/storybook#2649]
### Issue details

The warning below appeared after I updated `addon-info` to 3.3.3. It happens when I use `PropTypes.oneOfType`, I think it got something to do with `PropTables` rendering.

```
warning.js:33 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `OneOfType`. See https://fb.me/react-warning-keys for more information.
    in span (created by OneOfType)
    in OneOfType (created by PrettyPropType)
    in PrettyPropType (created by PropTable)
    in td (created by glamorous(td))
    in glamorous(td) (created by PropTable)
    in tr (created by PropTable)
    in tbody (created by PropTable)
    in table (created by glamorous(table))
    in glamorous(table) (created by PropTable)
    in PropTable
    in Unknown (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in Story
    in ThemeProvider
```

### Steps to reproduce

1. Create a component
2. Add a story with `withInfo`
3. Add `PropTypes.oneOfType` to component's propTypes

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.3.3
- @storybook/addon-info 3.3.3

**Comment by igor-dv** [comment]
Don't we use "merged" label until it's published? Or are there new policies? =)

**Comment by Hypnosphi** [comment]
Sorry I forgot about github magic words
