### ISSUE TITLE
Scrollbar problems: Visible disabled scrollbars and overlapping of fixed elements

### ISSUE THREAD

**Issue by sapkra** [storybooks/storybook#2655]
### Issue details
The decorator set's the `overflow` to `scroll`, but it should be `auto` because if the content is not scrollable the scrollbars will be hidden with `auto`.

There is also an overlapping with fixed elements.
Problem: You can't place a fixed element relative to another fixed element but the backgrounds wrapper is a fixed element.

You can see both problems in the screenshot below.

### Please specify which version of Storybook and optionally any affected addons that you're running
- storybook/react 3.3.3
- storybook/addon-backgrounds 3.3.3

### Screenshot
![image](https://user-images.githubusercontent.com/8087568/34604184-330fc66e-f207-11e7-85cf-4a2be9aec1f8.png)

**Comment by Hypnosphi** [comment]
Hi @sapkra, sorry for the delay

Can you please elaborate a bit more what's the expected behaviour for fixed element in your case?
