### ISSUE TITLE
Shortcut for Inspect Element on Chrome overlaped

### ISSUE THREAD

**Issue by timgivois** [storybooks/storybook#2662]
### Issue details
What did you expect to happen?
Tried to open inspect element on Chrome.

What happened instead?
Open Addon panel.

### Steps to reproduce
Open storybook in Chrome and then type Ctrl/Cmd + Shift + C.

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react 3.2.12`
- `@storybook/addon-info 3.2.12`

**Comment by Hypnosphi** [comment]
See also https://github.com/storybooks/storybook/pull/1858#issuecomment-355970831

**Comment by andrewmartin** [comment]
I'd love to see a fix for this, it's incredibly annoying 😼

**Comment by Hypnosphi** [comment]
https://github.com/storybooks/storybook/pull/3237 should provide a workaround, will be released soon(ish)

**Comment by Hypnosphi** [comment]
Fix released as [`4.0.0-alpha.2`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.2)
