### ISSUE TITLE
React-native Menu (How to hide)?

### ISSUE THREAD

**Issue by smooJitter** [storybooks/storybook#2663]
### Issue details

How do I hide the menu in simulation mode?

**Comment by shilman** [comment]
Set `onDeviceUI` to `false` in `getStorybookUI`. See the release announcement for an example:

https://medium.com/storybookjs/announcing-storybook-3-2-e00918a1764c?source=linkShare-37242fe7b393-1515252239

**Comment by smooJitter** [comment]
@shilman thanks man.  I appreciate the quick response.
