### ISSUE TITLE
preview-head.html is no longer included in iframe.html after upgrading to v3.3

### ISSUE THREAD

**Issue by timhaines** [storybooks/storybook#2665]
Upgrading @storybook/react from 3.2.14 to 3.3.3, my preview-head.html file is no longer being included in the head of iframe.html when I build storybook or run start-storybook.

I'm using these scripts: 
* `"storybook": "start-storybook -p 9001 -c storybook -s ./storybook/public"`
* `"storybook:build": "build-storybook -c storybook -s ./storybook/public"`

**Comment by shilman** [comment]
Duplicate to #2501

**Comment by Hypnosphi** [comment]
Fixed in [`3.3.4`](https://github.com/storybooks/storybook/releases/tag/v3.3.4)

**Comment by timhaines** [comment]
Thanks so much @Hypnosphi and @shilman!
