### ISSUE TITLE
deprecated babel-preset-es2015@6.24.1

### ISSUE THREAD

**Issue by TwistedIsles** [storybooks/storybook#2667]
### Issue details
When installing using the instructions, warning for deprecated babel-preset-es2015 and no valid versions are available.

### Steps to reproduce
Running the following command:

`npm i -g @storybook/cli`

### Affected platforms 
npm version 5.6.0

### Error Log
Console Log
```
PS C:\projects\pt-helper-meteor> npm i -g @storybook/cli
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌
Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for timed-out

npm ERR! A complete log of this run can be found in:
```
Complete Log
[2018-01-06T19_50_12_143Z-debug.log](https://github.com/storybooks/storybook/files/1609180/2018-01-06T19_50_12_143Z-debug.log)

**Comment by Hypnosphi** [comment]
We don't actually use this preset directly, but our dependency `jscodeshift` does. They actually have an open [issue](https://github.com/facebook/jscodeshift/issues/222) about it, but unfortunately it didn't get any attention

**Comment by TwistedIsles** [comment]
@Hypnosphi  I'm not sure if jscodeshift fixed their issue but now I can install without getting an error, so ill close this
