### ISSUE TITLE
consume .env file like create-react-app

### ISSUE THREAD

**Issue by BLamy** [storybooks/storybook#2668]
Steps to reproduce
- start a new project with create-react-app
- come across the need for an API Key
- Put the `.env` file
```
REACT_APP_PLACES_API_KEY=SFlknsdpbpiSDLFYSDLKFYmfcxfbsfas_asdfs
```

- Put in `public/index.html`
```html
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=%REACT_APP_PLACES_API_KEY%&libraries=places"></script>
```

The issue is I cannot consume this variable from `.storybook/preview-head.html`. 

I could modify my project.json file to set them like here
https://storybook.js.org/configurations/env-vars/ but it would be nice if storybooks just played nicely with create-react-app.

**Comment by Hypnosphi** [comment]
Released as `v3.4.0-alpha.6`
