### ISSUE TITLE
Easy way to disable styles?

### ISSUE THREAD

**Issue by JamesBliss** [storybooks/storybook#2675]
Hi,

I have some complex styling in some of my components but on occasion I need them to render without any styling my only options seems to be:

1. Add a new prop which wraps the styling like this which has issues if referencing other components:

```
const UiButton = styled.button`
  ${ props => props.themeNone ? `` : `
    padding: 0;
    box-sizing: border-box;
  `};
`;
```

2. Have a second component which is the same minus using any of the styled components e.g. just render the button element.

Is there a better way to do it?

**Comment by JonShort** [comment]
Might be worth asking this question over at https://github.com/styled-components/styled-components as they probably have more knowledge on the subject.

**Comment by JamesBliss** [comment]
Completely right... put it in the wrong place sorry!

**Comment by JonShort** [comment]
No problem 👍
