### ISSUE TITLE
Adding nested angular component ?

### ISSUE THREAD

**Issue by titusfx** [storybooks/storybook#2691]
### Issue details
Adding a nested angular component which one component depends on other where those other are in different modules. If I just use the tutorial angular examples, didn't work.

### Steps to reproduce

Adding a nested angular component which one component depends on other where those other are in different modules. If I just use the tutorial angular examples, didn't work.
 The same error can be seen in spec test in angular. And is fixed adding in declarations the component or adding into imports the module where the nested component exist ( the second solution only works if the nested component is declared in exports ngModule ).

https://ibb.co/dTXdU6

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 1.5.x
### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```

**Comment by igor-dv** [comment]
Everything that component needs to be rendered should be provided with 
`moduleMetadata`. Take a look here - https://github.com/storybooks/storybook/blob/master/examples/angular-cli/src/stories/custom-metadata.stories.ts

**Comment by titusfx** [comment]
Thanks this definetly will fix it!

**Comment by amorenew** [comment]
@igor-dv I think a rich documentation will avoid opening several issues .

**Comment by igor-dv** [comment]
You are right. And we will be more than happy to get PRs with docs improvements 😉

**Comment by sam-berry** [comment]
@igor-dv I like the general idea of community-sourced documentation for sure, but I think it would be much better for individuals who are experienced with this framework to produce the first version of docs.

Storybook seems like an awesome tool and I'm hoping it can be something I can use to easily bridge the gap between design and implementation (for a project that has a designer who can create components). Immediately out of the gate I ran into the issue defined here though - trying to figure out how I can import an entire module for a component (Angular 5). 

Is there more in-depth API documentation somewhere for how to use the different options displayed in the example you pointed to? Specifically, `moduleMetadata` and `addDecorator`?

It is great that there are examples and I am confident I will be able to figure out what I need to from the code, but I agree with @amorenew that it would be very helpful to have some additional docs around how to do this specific thing at least. If users are following Angular best practice then they will almost certainly need to import an entire module.

If I have success with Storybook and move forward with it perhaps I will try to open up a PR for documentation, but like I said I think it would be much more efficient for someone who is already comfortable in this framework to fill in those few details.

**Comment by jcwarfield** [comment]
Is there any updated information on this issue? The moduleMetadata link is now dead, and I am having this same issue with a nested component. Seems no matter what combination of moduleMetadata declarations and imports I use, I get a  `Template parse errors:
'app-welcome' is not a known element:
1. If 'app-welcome' is an Angular component, then verify that it is part of this module.` error when running   storybook, however, my angular app renders fine outside of Storybook. I have a root AppComponent with a nested WelcomeComponent that simply supposed to render `<p>It  works!</p>. Can someone tell me how to structure moduleMetadata properly? I'm using Storybook version 5.2.8 and Angular version 8.2.14. Thanks!
