### ISSUE TITLE
storybook-vue: Module not found: Error: Can't resolve '@/components/...

### ISSUE THREAD

**Issue by dvelasquez** [storybooks/storybook#2695]
### Issue details

In storybook vue, i can't load a component with child components.
Stacktrace:

```
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/TheParentComponent.vue
Module not found: Error: Can't resolve '@/components/BaseChildComponent' in 'C:\Users\Danilo\dev\altiro-builders\src\components'
```

Im using the @ notation to load components used in vue-webpack

**I guess the problem is between the @/component notation and the extension .vue**
### Steps to reproduce

* Install vue webpack using vue-cli
* Install storybook for vuejs
* Install addon-viewport
* Create a story using a component who loads a child component

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue 3.3.3
- @storybook/addon-viewport 3.3.4

### Affected platforms 
- OSX High Sierra
- Windows 10

**Comment by dvelasquez** [comment]
This problem is solved with a webpack.config.js extension to support .vue files and @ notation.

```javascript
const path = require('path');

// load the default config generator.
const genDefaultConfig = require('@storybook/vue/dist/server/config/defaults/webpack.config.js');

module.exports = (baseConfig, env) => {
  const config = genDefaultConfig(baseConfig, env);

  // Extend it as you need.
  function resolve(dir) {
    return path.join(__dirname, '..', dir);
  }

  config.resolve = {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      vue$: 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    },
  };

  return config;
};

```

**Comment by lmiller1990** [comment]
Worked for me too. I placed it inside of `/.storybook/webpack.config.js`, on the same level as `/src`.

**Comment by phillduffy** [comment]
I have also managed to get it working for me using the following without getting the warning about the new way to alter the config

```
const path = require("path");

module.exports = (baseConfig, env, defaultConfig) => {
  defaultConfig.resolve.alias = {
    ...defaultConfig.resolve.alias,
    "@": path.resolve(__dirname, "../src"),
  };

  return defaultConfig;
};
```

**Comment by therealpecus** [comment]
this should go in the docs

**Comment by adamchenwei** [comment]
@phillduffy may I know where to put that config?

**Comment by DirkStevens** [comment]
I'm getting a similar problem loading mixins from a 'mixins' folder located at the same level of the .vue component that tries to load the mixin:

/visuals
`wsvg.vue -> imports './mixins/RootAnchorMixin.js`

/visuals/mixins/RootAnchorMixin.js

Storybooks serves, but no stories.
Client console complains:
`Uncaught ReferenceError: RootAnchorMixin is not defined
    at Object.__webpack_exports__.a.DebugMixin.props.debug.type (RootAnchorMixin.js:1)
    at __webpack_require__ (bootstrap f60c4e9af13422c59958:678)
    at fn (bootstrap f60c4e9af13422c59958:88)
    at Object.defineProperty.value (vuex.esm.js:931)
    at __webpack_require__ (bootstrap f60c4e9af13422c59958:678)
    at fn (bootstrap f60c4e9af13422c59958:88)
    at Object.__webpack_exports__.a.RootAnchorMixin.data (wSvg.vue:1)
    at __webpack_require__ (bootstrap f60c4e9af13422c59958:678)
    at fn (bootstrap f60c4e9af13422c59958:88)
    at Object.<anonymous> (config.js:1)`

**Comment by A7DC** [comment]
How is this meant to work for the latest version of Storybook, where you have a `main.js` file instead of the webpack stuff?

**Comment by shilman** [comment]
Main.js can configure webpack: https://storybook.js.org/docs/configurations/custom-webpack-config/

**Comment by john-craft** [comment]
I had this same question, @A7DC, and the code below is what worked for me. I had to tell webpack to use Vue's runtime compiler, thus the `'vue$': 'vue/dist/vue.esm.js'` line. Also, I already had the `stories` property set in `main.js` and that may not apply to you.

This is running on `@storybook/vue v5.3.18`.

```
const path = require('path')

module.exports = {
    stories: ['../src/**/*.stories.[tj]s'],
    webpackFinal: async config => {
        config.resolve.alias = {
            'vue$': 'vue/dist/vue.esm.js',
            '@': path.resolve(__dirname, "../src")
        }

        return config;
    }
};
```

**Comment by shevchenko-web** [comment]
thanks

**Comment by mbrosowicz** [comment]
This problem apparently happened to me again in `@storybook/vue v6.0.27`.

I have the following property in storybooks `main.js` module.exports:

`webpackFinal: async config => {
    config.module.rules.push({
      test: /\.(jpg|jpeg|png|gif|mp3|svg)$/,
      loaders: ['file-loader',],
    });

    config.module.rules.push({
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      use: 'babel-loader',
    });

    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader',],
      include: path.resolve(__dirname, '../'),
    });

    config.resolve.extensions = ['.js', '.vue', '.json',];

    config.resolve.alias = {
      'vue$': 'vue/dist/vue.esm.js',
      '@': path.resolve(__dirname, '../src'),
    };

    return config;
  },`

Terminal Output:

`> vue-cli-service storybook:serve -p 6006 -c config/storybook

info @storybook/vue v6.0.27
info
info => Loading presets
info => Loading presets
info => Loading config/preview file in "config/storybook".
info => Loading config/preview file in "config/storybook".
info => Adding stories defined in "config/storybook/main.js".
info => Loading custom manager config.
info => Using default Webpack setup.`

Notice the `info => Using default Webpack setup.` line.

Error example: 

`ERROR in ./src/modules/userSettings/_components/CreateUserThirdStep.vue?vue&type=script&lang=js& (./node_modules/vue-docgen-loader/lib??ref--18!./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/modules/userSettings/_components/CreateUserThirdStep.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '@/plugins/eventBus' in '/Users/mbrosowicz/Documents/Projects/dmexpress-mcqueen/src/modules/userSettings/_components'
 @ ./src/modules/userSettings/_components/CreateUserThirdStep.vue?vue&type=script&lang=js& (./node_modules/vue-docgen-loader/lib??ref--18!./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/modules/userSettings/_components/CreateUserThirdStep.vue?vue&type=script&lang=js&) 38:0-42 73:6-14 77:8-16 136:6-14 141:10-18
 @ ./src/modules/userSettings/_components/CreateUserThirdStep.vue?vue&type=script&lang=js&
 @ ./src/modules/userSettings/_components/CreateUserThirdStep.vue
 @ ./node_modules/vue-docgen-loader/lib??ref--18!./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/stories/BaseFormWizard.story.vue?vue&type=script&lang=js&
 @ ./src/stories/BaseFormWizard.story.vue?vue&type=script&lang=js&
 @ ./src/stories/BaseFormWizard.story.vue
 @ ./src/stories/FormWizard.stories.js
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^\/]*?\.stories\.(js|jsx|ts|tsx|mdx))$
 @ ./config/storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./config/storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/vue/config.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./config/storybook/preview.js-generated-config-entry.js ./config/storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined`

Any ideas?

**Comment by mbrosowicz** [comment]
This problem apparently happened to me again on `@storybook/vue v6.0.27`.

```const path = require('path');

module.exports = {
  stories: ['../../src/**/*.stories.@(js|jsx|ts|tsx|mdx)',],
  addons: [
    '@storybook/addon-actions',
    {
      name: '@storybook/addon-docs',
      options: {
        babelOptions: {
          presets: [
            [
              '@vue/cli-plugin-babel/preset',
              {
                jsx: false,
              },
            ],
          ],
        },
      },
    },
    '@storybook/addon-links',
    '@storybook/addon-notes',
    '@storybook/addon-controls',
    '@storybook/addon-backgrounds',
  ],
  webpackFinal: async config => {
    config.devtool = 'source-map';

    config.module.rules.push({
      test: /\.(jpg|jpeg|png|gif|mp3|svg)$/,
      loaders: ['file-loader',],
    });
    config.module.rules.push({
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      use: 'babel-loader',
    });
    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader',],
      include: path.resolve(__dirname, '../'),
    });

    config.resolve.extensions = ['.js', '.vue', '.json',];
    config.resolve.alias = {
      'vue$': 'vue/dist/vue.esm.js',
      '@': path.resolve(__dirname, '../src'),
    };

    return config;
  },
};
```

Initial Terminal Output:

```> vue-cli-service storybook:serve -p 6006 -c config/storybook

info @storybook/vue v6.0.27
info
info => Loading presets
info => Loading presets
info => Loading config/preview file in "config/storybook".
info => Loading config/preview file in "config/storybook".
info => Adding stories defined in "config/storybook/main.js".
info => Loading custom manager config.
info => Using default Webpack setup.```

Notice the `info => Using default Webpack setup.` line.

Error example:


```ERROR in ./src/modules/userSettings/_components/CreateUserFirstStep.vue?vue&type=script&lang=js& (./node_modules/vue-docgen-loader/lib??ref--18!./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/modules/userSettings/_components/CreateUserFirstStep.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '@/plugins/eventBus' in '/Users/mbrosowicz/Documents/Projects/dmexpress-mcqueen/src/modules/userSettings/_components'
 @ ./src/modules/userSettings/_components/CreateUserFirstStep.vue?vue&type=script&lang=js& (./node_modules/vue-docgen-loader/lib??ref--18!./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/modules/userSettings/_components/CreateUserFirstStep.vue?vue&type=script&lang=js&) 274:0-42 400:6-14
 @ ./src/modules/userSettings/_components/CreateUserFirstStep.vue?vue&type=script&lang=js&
 @ ./src/modules/userSettings/_components/CreateUserFirstStep.vue
 @ ./node_modules/vue-docgen-loader/lib??ref--18!./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/stories/BaseFormWizard.story.vue?vue&type=script&lang=js&
 @ ./src/stories/BaseFormWizard.story.vue?vue&type=script&lang=js&
 @ ./src/stories/BaseFormWizard.story.vue
 @ ./src/stories/FormWizard.stories.js
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^\/]*?\.stories\.(js|jsx|ts|tsx|mdx))$
 @ ./config/storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./config/storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/vue/config.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./config/storybook/preview.js-generated-config-entry.js ./config/storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined```
