### ISSUE TITLE
EntryComponents not supported in ModuleMetadata

### ISSUE THREAD

**Issue by amcdnl** [storybooks/storybook#2701]
## Bug
`entryComponents` are not supported in the module metadata. See [here](https://angular.io/guide/ngmodule-faq#when-do-i-add-components-to-entrycomponents) for more info on entry components.

Code Reference: https://github.com/storybooks/storybook/blob/master/app/angular/src/client/preview/angular/helpers.ts#L58

**Comment by Hypnosphi** [comment]
Released as [`3.3.7`](https://github.com/storybooks/storybook/releases/tag/v3.3.7)
