### ISSUE TITLE
addon-info doesn't show Proptypes and description

### ISSUE THREAD

**Issue by AhmadBehzadi** [storybooks/storybook#2708]
### Addon-info doesn't show Proptypes and description
Hi,
I have problem with addon-info when I use my component as an external package. There is no problem when I copy the component source into my storybook project, but when call it from **node module** the **PropType** and **description** does not show

![bug](https://user-images.githubusercontent.com/13084683/34774646-6332cfd6-f625-11e7-94f9-5b99a94334c3.png)

[My Component](https://github.com/raadhoosh/fantastic-components/blob/master/src/Breadcrumb/Breadcrumb.js) source code :
```js
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';
import BreadcrumbStyled from './style/BreadcrumbStyled';
import OlStyled from './style/OlStyled';
import LiStyled from './style/LiStyled';

class Breadcrumb extends React.Component {
  render() {

    const {
      items, primary, secondary, info, success, danger, warning, rtl
    } = this.props;
    const elements = [];
    for (let i = 0; i < items.length - 1; i += 1) {
      elements.push(items[i]);
    }
    const lastElement = items[items.length - 1];
    const themeProps = {
      primary, secondary, info, success, danger, warning, rtl
    };
    return (
      <BreadcrumbStyled {...this.props}>
        <OlStyled {...themeProps}>
          {elements.map((item, index) => {
            return (
              <LiStyled
                key={index}
                {...themeProps}
              >
                <Link
                  to={item.path
                }>
                  {item.name}
                </Link>
              </LiStyled>
            );
          })}
          <LiStyled {...themeProps}>{lastElement.name}</LiStyled>
        </OlStyled>
      </BreadcrumbStyled>
    );
  }
}
Breadcrumb.propTypes = {
  /** array of objects */
  items: PropTypes.array.isRequired,
  /** rtl is true component show  in right side of the window, default is false (from left side). */
  rtl: PropTypes.bool,
  /** Boolean indicating whether the component renders with Theme.primary color */
  primary: PropTypes.bool,
  /** Boolean indicating whether the component renders with Theme.secondary color */
  secondary: PropTypes.bool,
  /** Boolean indicating whether the component renders with Theme.info color */
  info: PropTypes.bool,
  /** Boolean indicating whether the component renders with Theme.warning color  */
  warning: PropTypes.bool,
  /** Boolean indicating whether the component renders with Theme.danger color  */
  danger: PropTypes.bool,
  /** Boolean indicating whether the component renders with Theme.success color */
  success: PropTypes.bool,
  /** The inline-styles for the root element. */
  style: PropTypes.object,
  /** The className for the root element. */
  className: PropTypes.string,
  /** The color renders with Theme.foreColor . */
  foreColor: PropTypes.string
};
Breadcrumb.defaultProps = {
  rtl: false,
  primary: false,
  secondary: false,
  info: false,
  warning: false,
  danger: false,
  success: false,
  style: {},
  className: '',
  foreColor: ''
};
export default Breadcrumb;
```

I tried both **compiling and installing from npm** and **linking to source code in github**, there was no different.

**Comment by jsanchez034** [comment]
Same thing is happening to me, looks like it's because in the `PrettyPropType` component...
https://github.com/storybooks/storybook/blob/master/addons/info/src/components/types/PrettyPropType.js#L34
The `propType` prop can be an object or a string and that prop is always destructured above. I will make a PR to fix this.

**Comment by jsanchez034** [comment]
Sorry actually the root cause of the issue looks to be related to..
https://github.com/storybooks/babel-plugin-react-docgen/issues/33

**Comment by thupi** [comment]
I had trouble with getting this to work while using Typescript :-) Even though it is fairly easy to use Typescript with storybook it seams to break addon-info's propTypes and description. However, defaultProps and property still works :-)

**Comment by wellyal** [comment]
Any updates on this. I'm also facing this problem. :(

**Comment by jsanchez034** [comment]
In my case the issue is only for stateless functional components defined as a regular function declaration, example...
```
import React, { PropTypes } from 'react'

const Child = () => (
  <div>Sample</div>
)

function FuncDeclaration({ children }) {
  return (
    <div>
      {children}
      <Child />
    </div>
  )
}

FuncDeclaration.propTypes = {
  children: PropTypes.node
}

export default FuncDeclaration
```
The issue has to do with [babel-plugin-react-docgen](https://github.com/storybooks/babel-plugin-react-docgen/issues/33). I created a PR in the babel-plugin-react-docgen repo to address my issue in particular...
https://github.com/storybooks/babel-plugin-react-docgen/pull/41/files

**Comment by kgwebsites** [comment]
The issue for me is the method of import. It seems that deconstructing the import is causing propType and Description table headers to go missing. 

This does not work:
`import {Input} from '../lib/elements/Forms';`

This does:
`import Input from '../lib/elements/form/Input';`

**Comment by naomiHauret** [comment]
I'm having this problem with components that use CSS-Modules :confused:  (more specifically [React CSS-Modules](https://github.com/gajus/react-css-modules))

**Comment by AhmadBehzadi** [comment]
@kgwebsites That didn't solve my problem

**Comment by denchen** [comment]
Hi, I'm seeing a similar issue, and I've narrowed it down to a case where I have multiple exports

Given this:

```
import React from 'react';
import PropTypes from 'prop-types';

class Test extends React.PureComponent {
  render() {
    return <button>test</button>;
  }
}

Test.propTypes = {
  /** Some description here */
  randomProp: PropTypes.string
};

export default Test;

export const Test2 = () => <div>Hi</div>;
```

The description will *not* show up for `randomProp`. HOWEVER, if I comment out the last line, as such:

    // export const Test2 = () => <div>Hi</div>;

Then the description for `randomProp` will show up. This is even if my Story does not import `Test2` at all.

I don't know if there are other situations where descriptions won't show up, but the scenario I described above is definitely reproducible.

**Comment by denchen** [comment]
Another curious case.

Docgen works for this:

```
import React from 'react';
import PropTypes from 'prop-types';

const Test = () => <button>A button</button>;

Test.propTypes = {
  /** Another label */
  randomProp: PropTypes.string
};

export default Test;
```

But this doesn't:

```
import React from 'react';
import PropTypes from 'prop-types';

export const Test = () => <button>A button</button>;

Test.propTypes = {
  /** Another label */
  randomProp: PropTypes.string
};
```

Of course, in the storybook, I'm using `import Test from 'Test'` in the first scenario and `import { Test } from 'Test'` in the second.

**Comment by Hypnosphi** [comment]
> I use my component as an external package

@AhmadBehzadi You probably need to remove this package from babel-loader `exclude`, so that docgen plugin gets applied to it. Alternatively, you can include `babel-plugin-react-docgen` in babel config for the component package

**Comment by Hypnosphi** [comment]
@denchen can you please open a separate issue? Looks like you are not importing an external package, are you?

**Comment by aaronincincy** [comment]
I'm experiencing this issue as well.  It looks in the prop table my propType is coming in as a string, but PrettyPropType is trying to destructure it into {name}.

**Comment by denchen** [comment]
@Hypnosphi I opened a new issue at #3059. My component is not an external package.

**Comment by lordgiotto** [comment]
I had a similar issue: propTypes and descriptions appear if I use a functional component, but doesn't work if I use a class component (only properties names are displayed).

**Comment by Neglexis** [comment]
I'm having the same issue.

This is my current setup that already fails.

Do not however that the defaultProps and isRequired are getting picked up, so no idea what I'm doing wrong.

### Test Component

```js
import React from 'react';
import PropTypes from 'prop-types';

const Test = ({ name }) => {
  return <div>Hello {name}</div>;
};

Test.propTypes = {
  /** This should be the description */
  name: PropTypes.string.isRequired,
};

Test.defaultProps = {
  name: 'mars',
};

export default Test;
```

### Index.js

```js
import React from 'react';
import { storiesOf } from '@storybook/react';
import Test from 'Framework/Test';
import '../assets/stylesheets/kayzrfont.css';
import { withInfo } from '@storybook/addon-info';

storiesOf('Test', module).add(
  'Default',
  withInfo(`
      description or documentation about my component, supports markdown
    
      ~~~js
      <Button>Click Here</Button>
      ~~~
    
    `)(() => <Test name="world" />),
);
```

### Storybook output

![image](https://user-images.githubusercontent.com/29750443/37292746-e0767d46-2611-11e8-8949-9bbe964187f2.png)

If you need any more info @Hypnosphi, don't hesitate to ping me!

**Comment by kgwebsites** [comment]
Well if you put .isRequired on a PropType, you cannot declare a defaultProp

**Comment by Neglexis** [comment]
@kgwebsites I know, but it was just to illustrate the point that those settings do work. If I only declare one of them, the propType and description column still won't work.

**Comment by loadingwyn** [comment]
I'm also facing this problem too!

**Comment by sauldeleon** [comment]
I think I am facing the same issue. I am not using defaultProps in my components, and some of set correctly the propTable in the info section, but with others I cant see the description neither the proptype :/

Trying to find some behaviour..

thanks!

**Comment by danielduan** [comment]
We do not support multiple exports within the same file with Info documentation at the moment. It's a limitation with our babel plugin and the way `react-docgen` works.

https://github.com/storybooks/babel-plugin-react-docgen/pull/46

**Comment by sauldeleon** [comment]
Thanks for your response. What i am doing now is generating the .__docgen manually.

I remove the default export, add a console.log(JSON.Stringify(myComponent.__docgeninfo)) in the storybook and then copy this log, and add It again as myComponent.__docgeninfo = JSON.parse(logText).

Then I add again the default export to the original component file.

It's a bit weird but it works :)

Thanks again

**Comment by Neglexis** [comment]
No, this is everything but stale. The real issue wasn't answered in @danielduan's reply.

**Comment by Hypnosphi** [comment]
Please try it with 3.4.1
AFAIK there were some huge fixes in that field

**Comment by Neglexis** [comment]
Still nothing.

Still fails with this component.

```js
import React from 'react';
import PropTypes from 'prop-types';

const Test = ({ name }) => {
  return <div>Hello {name}</div>;
};

Test.propTypes = {
  /** This should be the description */
  name: PropTypes.string.isRequired,
};

Test.defaultProps = {
  name: 'mars',
};

export default Test;
```

![image](https://user-images.githubusercontent.com/29750443/38864766-006cc3a8-423c-11e8-8aa6-f01abc3b233b.png)

**Comment by wellnine** [comment]
I also have the same issue. So the problem is actual.

**Comment by cprakti** [comment]
☝️ also have this issue

**Comment by mcissel** [comment]
I fixed this by 'extending' the `PropTable` component from storybook/addon-info.

```
import React from 'react';
import PropTable from '@storybook/addon-info/dist/components/PropTable';

const PropTypesTable = ({ propDefinitions, ...props }) => {
  propDefinitions.forEach((def) => {
    if (typeof def.propType === 'string') {
      def.propType = { name: def.propType };
    }
  });

  return <PropTable propDefinitions={propDefinitions} {...props} />;
};

export default PropTypesTable;
```

 Then override the TableComponent in storybook/config.js
```
import { setDefaults } from '@storybook/addon-info';

setDefaults({
  TableComponent: PropTypesTable, // Override the component used to render the props table
});
```

**Comment by icynoangel** [comment]
@mcissel Nice! That works, thank you!

**Comment by ewagulik** [comment]
Niecnasowa, worked for me, thanks :)

**Comment by rafal-r** [comment]
Maybe when your package resides in `node_modules` or outside project directory then weback treats those files on import as production builds which results in omitting comments and propTypes ?

My solution was to make symlink to my module (which was outside project directory) and then import  components from that directory.
This approach requires disabling symlinks in webpack resolver:
`const path = require("path");
module.exports = (storybookBaseConfig, configType, defaultConfig) => {
    defaultConfig.resolve.symlinks = false;
    return defaultConfig;
};` 

With this configuration my module written in ES6 syntax is fully parseable by webpack, propTypes and descriptions are visible in storybook and app is reloaded on every file change in module directory.

**Comment by JuhQ** [comment]
It seems I as well have this issue. I have it with pure components and higher order functions. Hopefully some resolution will be found in future versions of the addon.

**Comment by postnikovmaksim** [comment]
I ask you to tell me, should the plug be connected separately babel-plugin-react-docgen? Or you just need to wait for the update storybook?

**Comment by mikelax** [comment]
I see this issue is closed, has it been released in version 3.4.10? 
I am still seeing the problem in both 3.4.8 and 3.4.10. I have not yet tried any of the 4.x betas.

**Comment by Jony-Y** [comment]
@niecnasowa your solution worked for me.

**Comment by davidcalhoun** [comment]
Still had this issue even with the latest versions (see list below).  @niecnasowa's solution worked for me - I simply added `babel-plugin-react-docgen (add to .babelrc "plugins": ["react-docgen"])` without having to add `react-docgen`

Package Version info:
```
    "@storybook/addon-actions": "^4.1.2",
    "@storybook/addon-centered": "^4.1.2",
    "@storybook/addon-info": "^4.1.2",
    "@storybook/addon-knobs": "^4.1.2",
    "@storybook/addon-links": "^4.1.2",
    "@storybook/addon-options": "^4.1.2",
    "@storybook/addons": "^4.1.2",
    "@storybook/cli": "^4.1.2",
    "@storybook/react": "^4.1.2",
```

Code example that was failing:
```js
export default class SomeComponent extends PureComponent {
    static propTypes = {
        /** Test comment. */
        foo: PropTypes.string
    };
}
```

**Comment by tomasskopal** [comment]
@niecnasowa Worked for me. 👍 Note that if you have more plugins in `.babelrc` the "react-docgen" must be first.

**Comment by artyomtrityak** [comment]
It still does not work for me with docgen

**Comment by cassiewang01** [comment]
It still does not work for me with docgen @niecnasowa

**Comment by Lory1990** [comment]
This does not work for me @niecnasowa 

```
{
  "presets": [
    "@babel/preset-react",
    ["@babel/preset-env", { "useBuiltIns": "entry", "corejs": 3 }]
  ],
  "plugins": [
      "react-docgen",
      "@babel/plugin-proposal-class-properties",
     "babel-plugin-module-resolver"
  ]
}
```

**Comment by khainguyenvan** [comment]
In my case, I currently added the storybook to main project. My solution is extended a custom webpack config file inside storybook folder and replace jsx rules with this code.

```
const path = require('path');
const webpack = require('webpack');
const custom = require('../webpack.config.js');

module.exports = ({ config, mode }) => {
    const rules = custom.module.rules.filter(rule => rule.loader === 'babel-loader')
    return {
        ...config,
        module: {
            ...config.module,
            rules: [
                ...custom.module.rules,
                {
                    test: /\.stories\.(js|jsx)?$/,
                    loaders: [require.resolve('@storybook/source-loader')],
                    enforce: 'pre'
                },
                {
                    test: /\.jsx?$/,
                    loader: 'babel-loader',
                    exclude: /node_modules/,
                    query: {
                        cacheDirectory: true,
                        presets: ['@babel/preset-react'],
                        plugins: ["babel-plugin-react-docgen"]
                    },
                },
            ]
        },
    };
};
```

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by jeroenreijs** [comment]
We had this problem as well on components that had JSS. Because of the JSS wrapper, the columns for propType and description were empty. By exporting the 'raw' component and use that in the story, the problem was solved.

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
