### ISSUE TITLE
Need to have browser refresh automatically with code changes

### ISSUE THREAD

**Issue by jainprash** [storybooks/storybook#271]
Currently, the nodejs server ( webpack) picks up my changes and builts the file, but still I have to do one more step of refreshing the browser. Is there way to have websocket communication between browser an d server, so that the browser page is refreshed automatically ( similar to live reload script)

**Comment by arunoda** [comment]
Hmm. We've hot module reloading for code changes. It doesn't need to do a page refresh to do that. Components just updated with new data.

Are you looking for something else?

**Comment by andresin87** [comment]
I think @jainprash, you have made a mistake in your custom webpack config file or you are running build-storybook and you should run start-storybook script. The hot reloader is working fine.

**Comment by ndelangen** [comment]
Please re-open with more info about your setup if you are still experiencing this issue 👍
