### ISSUE TITLE
build-storybook not exitting when fail

### ISSUE THREAD

**Issue by davidkwan95** [storybooks/storybook#2716]
### Issue details

Expected behavior: build-storybook should exit when err.
Actual behavior: process is stuck and not exitting

### Steps to reproduce

1. Some fail imports in code
2. build-storybook

### Please specify which version of Storybook and optionally any affected addons that you're running

- @ storybook/react 3.3.6
- @ storybook/addon-actions 3.3.6
- @ storybook/addon-info 3.3.6
- @ storybook/addon-links 3.3.6

### Affected platforms 

- Node v8.9.3

**Comment by Hypnosphi** [comment]
Can't reproduce it on fresh CRA
```
$ npm run build-storybook

> test-app@0.1.0 build-storybook /Users/jetbrains/test-app
> build-storybook -s public

info @storybook/react v3.3.6
info
info => Loading custom addons config.
info => Using default webpack setup based on "Create React App".
info => Copying static files from: public
info Building storybook ...
ERR! Failed to build the storybook
ERR! Module not found: Error: Can't resolve '@stoybook/addon-actions' in '/Users/jetbrains/test-app/src/stories'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@0.1.0 build-storybook: `build-storybook -s public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-app@0.1.0 build-storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jetbrains/.npm/_logs/2018-01-11T10_54_03_281Z-debug.log
```

**Comment by Hypnosphi** [comment]
Can you please create a GitHub repo with minimal reproduction of your issue?

**Comment by davidkwan95** [comment]
I am trying to reproduce it in a new project, but so far I've been unable to reproduce it.

**Comment by ohelixa** [comment]
I have the same issue

**Comment by shilman** [comment]
@ohelixa what version?

**Comment by ohelixa** [comment]
Latest 5.0.5
