### ISSUE TITLE
LinkTo saves scroll position

### ISSUE THREAD

**Issue by nemanjacvejic** [storybooks/storybook#2729]
### Issue details

After clicking on LinkTo component it takes me to right story, but content is scrolled. The page saves scroll position from previous story.
### Version
 @storybook/react 3.3.7
 @storybook/addon-links 3.3.7

**Comment by Hypnosphi** [comment]
Fix released as [`4.0.0-alpha.2`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.2)
