### ISSUE TITLE
Missing "Storybook for Vue" in left sidebar of storybook documentation

### ISSUE THREAD

**Issue by DrSensor** [storybooks/storybook#2738]
Guide for Vue not listed in left sidebar.
![screenshot from 2018-01-13 16-05-41](https://user-images.githubusercontent.com/4953069/34904603-b3bcec86-f87b-11e7-95f3-4be4c5879bfb.png)

**Comment by Hypnosphi** [comment]
Looks like it's fixed by now (probably with #2714)
