### ISSUE TITLE
CLI command to uninstall storybook?

### ISSUE THREAD

**Issue by fandy** [storybooks/storybook#2748]
Is there a command that I can use to completely uninstall Storybook? If not is this the manual way to delete it:

* remove `.storybook` and `storybook`
* remove storybook script in package.json
* uninstall storybook module in package.json

**Comment by danielduan** [comment]
and `npm uninstall -g getstorybook` if you used the cli.

you should probably clean out your node_modules and reinstall the package.json as well.

There isn't any automated way to do it.
