### ISSUE TITLE
TypeError: Cannot read property 'hasErrors' of undefined

### ISSUE THREAD

**Issue by timhaines** [storybooks/storybook#2750]
On [this line](https://github.com/storybooks/storybook/blame/master/app/vue/src/server/build.js#L82) stats.hasErrors() is called, without checking if stats exists.

It seems if err exists, then stats may not.

Using @storybook/vue v3.4.0-alpha.1.

**Comment by Hypnosphi** [comment]
Hi @timhaines! You're more than welcome to open a PR fixing it. Unfortunately, we still have some duplication across different framework apps (#2240 should address it in the long term). So you'll need to apply the change to all 4 desktop frameworks

**Comment by BostonChuckDuncan** [comment]
This is still a problem... is there any hope that it will be fixed?

**Comment by danielduan** [comment]
Fixed in https://github.com/storybooks/storybook/pull/2937 `3.4-rc.3`

**Comment by jobaerkhan** [comment]
I solved this like this :

```
    <span class="help-block form-error text-danger small" 
    *ngIf="myForm.controls.name.required &&
    myForm.controls.name.touched">
    Name is Required </span>
```

**Comment by mehdijalal** [comment]
For the required this one line also fix:
                        <mat-error>Title is required</mat-error>
