### ISSUE TITLE
Storyshots always finding 0 stories

### ISSUE THREAD

**Issue by colinphanna** [storybooks/storybook#2755]
### Issue details

Recieving `Storyshots found 0 stories` when trying to initStoryshots everytime.

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

Other members of my team can run storyshots on the same codebase without issue.  Confirmed that yarn and node are same version.

### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

Happens when running `yarn test` which runs `jest`

Jest config from package.json

```"jest": {
    "setupFiles": [
      "./tests/setup-tests.js",
      "./.storybook/raf-polyfill.js",
      "./dist/svgs/svgs.js"
    ],
    "moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy",
      "^components/(.*)$": "<rootDir>/components/$1",
      "^services/(.*)$": "<rootDir>/services/$1",
      "^stories/(.*)$": "<rootDir>/stories/$1"
    }
  }
```

here is `.storybook/config`

```import { configure } from '@storybook/react';

function requireAll(requireContext) {
  return requireContext.keys().map(requireContext);
}

function loadStories() {
  requireAll(require.context("../stories", true, /^((?![\\/]ignored[\\/]).)*\.jsx?$/));
  if(!process || !process.env || !process.env.NODE_ENV || process.env.NODE_ENV !== 'test'){
    console.log(process.env.NODE_ENV);
    // console.log('running ignored stories');
    // requireAll(require.context("../stories/ignored", true, /\.jsx?$/));
  }
}

configure(loadStories, module);
```

We've also tried a directly requiring stories to the same effect

### Please specify which version of Storybook and optionally any affected addons that you're running

-`@storybook/addon-actions` 3.3.9
-`@storybook/addon-storyshots` 3.3.9
-`@storybook/addons` 3.3.9
-`@storybook/react` 3.3.9

### Affected platforms 

Windows 10 command line

**Comment by igor-dv** [comment]
@colinphanna , can you please describe your project structure? Are you able to run Storybook itself with stories? Maybe you can print screen the cmd output when you are runing the `yarn test`? Also how does the test containing `initStoryshots` look like?

**Comment by colinphanna** [comment]
Thank you Igor

We just found out it runs correctly without other tests.  Closing for now til we get a better understanding of the issue.
