### ISSUE TITLE
Watch mode on `build-storybook`?

### ISSUE THREAD

**Issue by yjcxy12** [storybooks/storybook#2762]
We are building storybook to integrate it into our existing Express app and using routing static server output of storybook to our route.

One thing is that looking at https://github.com/storybooks/storybook/blob/master/app/react/src/server/build.js#L74. It seems it doesn't support `watch` mode even if `watch: true` is passed in from `webpack.config.js`.

Would it be reasonable to run `webpack().watch` rather than `webpack().run` if `watch: true` is provided in `webpack.config.js`?

**Comment by Hypnosphi** [comment]
What's your reason not to use webpack dev server with `start-storybook` command when developing?

**Comment by yjcxy12** [comment]
We are exposing a route `/storybook` in our app for int and test environment, so that non-devs can access the storybook page.

We can develop locally using `start-storybook` and only use `build-storybook` in our CI, but then locally we have to run `build-storybook` to check`/storybook` endpoint is rending correctly. An option to utilise webpack's watch mode on `build-storybook` would be nice.

**Comment by Hypnosphi** [comment]
OK I think I got your point. Want to send a PR?

**Comment by yjcxy12** [comment]
Sure will do.

**Comment by Hypnosphi** [comment]
Released as `3.4.0-alpha.7`
