### ISSUE TITLE
withInfo decorator showing same info for every story

### ISSUE THREAD

**Issue by doque** [storybooks/storybook#2772]
### Issue details

Instead of showing a source specific per-story, I get the same information for each story:
![image](https://user-images.githubusercontent.com/1480751/35089915-85fd8ccc-fc38-11e7-95fd-bdffafe8bd4f.png)
If I remove the decorator and apply `withInfo` to each story separately, the output works as expected:
![image](https://user-images.githubusercontent.com/1480751/35090167-2207b566-fc39-11e7-9b36-5a0ae74ecdce.png)

### Steps to reproduce
Add the `withInfo` decorator as first decorator:

```js
addDecorator((story, context) => withInfo('common info')(story)(context));
```
then add some stories

```js
stories
  .add('Accept', () => <AcceptButton />)
  .add('Save', () => <SaveButton />);
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react ^3.3.9
- @storybook/addon-info ^3.3.9

### Additional info

Our components use `styled-components`, if that makes any difference.

**Comment by sdaconceicao** [comment]
Experiencing the same problem, unfortunately it makes the global decorator useless.
Running with knobs and addon info, all 3.4.0 release.
