### ISSUE TITLE
[Angular]  `ngOnChanges` not being called first time component is created

### ISSUE THREAD

**Issue by michaelgeorgeattard** [storybooks/storybook#2773]
Hi,

From angular docs "ngOnChanges is called right after the data-bound properties have been checked and before view and content children are checked if at least one of them has changed." (https://angular.io/api/core/OnChanges).

With storybook, unless I change a specific input with knobs I cannot get `ngOnChanges` to fire. Unfortunately most of our components are written in a way expecting `ngOnChanges` to be fired before `ngOnInit`.

In spec files, component exhibits same behavior with no `ngOnChanges` calls. We manually call `detectChanges` on the fixture which works around the problem.

Is there a similar way to trigger `ngOnChanges` in storybook, or this a limitation?

**Comment by igor-dv** [comment]
@michaelgeorgeattard, do you have an example somewhere, so we could reproduce it?

**Comment by alterx** [comment]
Also, which version of Storybook are you using? There's code specifically written to trigger that first change detection (the bug may be there, we recently rewrote it) but maybe you're just a bit behind in the version story

**Comment by michaelgeorgeattard** [comment]
@alterx Last version I tested was `3.3.9`. If you confirm that this version should have working change detection I can try an example that replicates the issue.

**Comment by alterx** [comment]
Well, @michaelgeorgeattard, that was actually before some related changes, could you please try with `v3.4.0-alpha.5` ?
If it doesn't work you could send us an example :)

**Comment by michaelgeorgeattard** [comment]
I will try `v3.4.0-alpha.5` out and get back to you. Thanks for the quick response @alterx :-)

**Comment by michaelgeorgeattard** [comment]
Small update, `v3.4.0-alpha.5` is working correctly :-)

**Comment by michaelgeorgeattard** [comment]
Reusing this issue for another related question; let's say I want to test how a component reacts to a value change, is it possible to trigger a change detection cycle?

Example:

```
storiesOf("FooComponent", module)
	.add("Foo", () => {
		let value = 55;
		setInterval(() => {
			value += 5;
                        // trigger change detection here
		}, 500);
		return {
			component: FooComponent,
			moduleMetadata: {
				imports: [GlobalModule],
				providers: [
					FooConfigService
				],
				schemas: [NO_ERRORS_SCHEMA]
			},
			props: {
				value
			}
		};
	});
```

**Comment by alterx** [comment]
That's not possible in Storybook for Angular. Something similar can be achieved in Storybook for React but both addons are third party (not maintained by the core team). Storybook represents a component in some state over time. So, once you return these values that's the state that's going to be rendered. For a way to dynamically change this you could use the `addon-knobs` but that's a bit different from what you want. However, the `addon-knobs` does offer a way to hook into angular's change detection so one way of solving this would be to create a new `interval` knob.

What's your use case for this? Is it something that you guys do often?

**Comment by michaelgeorgeattard** [comment]
@alterx At this stage I am trying to set up Storybook as a development tool and visual regression testing for our component libraries.

A use case that I was trying to create a story for: a component that shows an up arrow when a number has increased (input), and a down arrow when a number has decreased. This behavior requires state to change after the component has initialized.

Do you think a use case such as this falls under the scope of what Storybook is trying to do? If so I think the `interval` knob you mentioned would be useful, unless Storybook could expose a method to trigger change detection in the current component which would be ideal.

**Comment by igor-dv** [comment]
@michaelgeorgeattard  I had a similar use case in the react app, trying to trigger tooltip component. I've managed to do by just programmatically manipulating the dom.

**Comment by alterx** [comment]
Yeah, also I think the knobs addon could work here. If you use the range knob you can increase and decrease the number by manipulating the slider (technically, this is a method to trigger a change in the state/component, once it has been rendered). If you need this to happen automatically (after a fixed period of time) then, yes, an `interval` knob should do the work.

**Comment by igor-dv** [comment]
Let's close the issue, and if you feel you need this `interval` knob open a new one 😉
