### ISSUE TITLE
[Angular] Storybook fails to perform animation

### ISSUE THREAD

**Issue by evanliomain** [storybooks/storybook#2775]
### Issue details

I use storybook along with [@angular/material](https://github.com/angular/material2).
This ui framework use a lot of angular animation, that require the [_BrowserAnimationsModule_](https://angular.io/api/platform-browser/animations/BrowserAnimationsModule) instead of just [_BrowserModule_](https://angular.io/api/platform-browser/BrowserModule).

And so, it throw multiple `Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.` errors and can block some animation.

I expect to have no error and trigger animation.

I figure out that the bug disapear when I replace `BrowserModule` by `BrowserAnimationsModule` in `@storybook/angular/src/client/preview/angular/helpers.ts` :

L10:
```typescript
- import { BrowserModule } from '@angular/platform-browser';
+ import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
```
L150:
```typescript
-    imports: [BrowserModule, FormsModule, ...moduleMetadata.imports],
+    imports: [BrowserAnimationsModule, FormsModule, ...moduleMetadata.imports],
```

### Steps to reproduce

In a storybook project for angular, add this story :

```typescript
import { storiesOf } from '@storybook/angular';
import { Component } from '@angular/core';
import { MatInputModule } from '@angular/material/input';

@Component({
  selector: 'app-simple-input',
  template: `
  <mat-form-field>
    <input matInput placeholder="test">
  </mat-form-field>`
})
export class SimpleInputComponent {}

storiesOf('SimpleInput', module).add('test', () => ({
  moduleMetadata: {
    imports: [MatInputModule]
  },
  component: SimpleInputComponent
}));
```

- Try to fill the input
This error is trigger:
`Error: Found the synthetic property @transitionMessages. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (platform-browser.js:2991)`

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 3.4.0-alpha.1

**Comment by alterx** [comment]
@evanliomain, you need to include the module yourself. I see you're already including the `MatInputModule`. You need to do the same with the `BrowserAnimationsModule`.

```
import { storiesOf } from '@storybook/angular';
import { Component } from '@angular/core';
import { MatInputModule } from '@angular/material/input';

@Component({
  selector: 'app-simple-input',
  template: `
  <mat-form-field>
    <input matInput placeholder="test">
  </mat-form-field>`
})
export class SimpleInputComponent {}

storiesOf('SimpleInput', module).add('test', () => ({
  moduleMetadata: {
    imports: [MatInputModule, BrowserAnimationsModule]
  },
  component: SimpleInputComponent
}));
```
I've successfully tested this with the latest alpha but it should work with 3.4.0-alpha.1

**Comment by evanliomain** [comment]
Yes it work :+1:

**Comment by alterx** [comment]
Perfect!
