### ISSUE TITLE
[Angular] Inherited component `props` not detected

### ISSUE THREAD

**Issue by AlvYuste** [storybooks/storybook#2778]
### Issue details

When having a component that extends another, all the `@Input`s and `@Outputs`s inherited are ignored.

### Steps to reproduce

When having for example this component:

```ts
@Component({ selector: `base-button`, ...})
class BaseButtonComponent {
    @Input() label: string;
}
```
And we extended by this one:
```ts
@Component({ selector: `icon-button`, ...})
class IconButtonComponent extends BaseButtonComponent {
    @Input() icon: string;
}
```
We can definetly call:
```html
<icon-button [label]="myLabel"></icon-button>
```
**But this don't take the label**:
```ts
storiesOf('Icon button', module)
    .add('with label', () => ({
        component: IconButtonComponent,
        props: {
            label: 'Hello Button',
        }
}));
```

### Version of Storybook:

- storybook/angular: ^3.3.9

**Comment by igor-dv** [comment]
It does work for me with v3.4.0-alpha.5. Can you check it with this version for you as well?

**Comment by AlvYuste** [comment]
Updating to that version it **works as expected**. 🎉
Thank you so much! We will continue integrating Storybook with our components kit [Unicorn Components](https://github.com/nitsnets/unicorn_components).

**Comment by igor-dv** [comment]
Credits to @alterx for this fix =)
