### ISSUE TITLE
ERROR in   Error: Cannot find module '../../../../lodash/lodash.js'

### ISSUE THREAD

**Issue by Scit** [storybooks/storybook#2785]
`ERROR in   Error: Cannot find module '../../../../lodash/lodash.js'`
when try to run start-storybook.

Storybook version:
- @storybook/react v3.3.9

OS version:
- Ubuntu 16.04

![screenshot from 2018-01-19 15-57-20](https://user-images.githubusercontent.com/661855/35153251-c09c4252-fd36-11e7-818b-26a38883c229.png)

`
% start-storybook -c ./webpack/configs/storybook -p 9001

> @0.2.4 storybook:hot client-mobile-component-web
> start-storybook -c ./webpack/configs/storybook -p 9001

info @storybook/react v3.3.9
info 
Failed to load ./.env.
info => Loading custom webpack config (full-control mode).
webpack built 490106e3c7c42f8e11cc in 3070ms                                       
Hash: 490106e3c7c42f8e11cc
Version: webpack 3.10.0
Time: 3070ms
                       Asset     Size  Chunks             Chunk Names
    static/preview.bundle.js  36.2 kB       0  [emitted]  preview
    static/manager.bundle.js  28.8 kB       1  [emitted]  manager
static/preview.bundle.js.map    40 kB       0  [emitted]  preview
static/manager.bundle.js.map  31.1 kB       1  [emitted]  manager
                  index.html  1.98 kB          [emitted]  
                 iframe.html  1.98 kB          [emitted]  
   [0] ./node_modules/@storybook/react/dist/server/config/polyfills.js 113 bytes {0} {1} [built]
   [1] multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/addons.js ./node_modules/@storybook/react/dist/client/manager/index.js 52 bytes {1} [built]
   [2] ./node_modules/@storybook/react/dist/server/addons.js 105 bytes {1} [built]
   [3] ./node_modules/@storybook/react/dist/client/manager/index.js 404 bytes {1} [built]
   [4] multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./webpack/configs/storybook/config.js 64 bytes {0} [built]
   [5] ./node_modules/@storybook/react/dist/server/config/globals.js 105 bytes {0} [built]
   [6] (webpack)-hot-middleware/client.js?reload=true 7.35 kB {0} [built]
   [7] ./webpack/configs/storybook/config.js 429 bytes {0} [built]

ERROR in   Error: Cannot find module '../../../../lodash/lodash.js'
  
  - module.js:20 require
    internal/module.js:20:19
  
  - index.html.ejs:692 Object.<anonymous>
    [client-mobile-component-web]/[@storybook]/react/dist/server/index.html.ejs:692:9
  
  - index.html.ejs:639 __webpack_require__
    [client-mobile-component-web]/[@storybook]/react/dist/server/index.html.ejs:639:30
  
  - index.html.ejs:685 
    [client-mobile-component-web]/[@storybook]/react/dist/server/index.html.ejs:685:37
  
  - index.html.ejs:688 
    [client-mobile-component-web]/[@storybook]/react/dist/server/index.html.ejs:688:10
  
  - index.js:231 HtmlWebpackPlugin.evaluateCompilationResult
    [client-mobile-component-web]/[html-webpack-plugin]/index.js:231:26
  
  - index.js:117 
    [client-mobile-component-web]/[html-webpack-plugin]/index.js:117:21
  
  - util.js:16 tryCatcher
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/async.js:17:14
  

ERROR in   Error: Cannot find module '../../../../lodash/lodash.js'
  
  - module.js:20 require
    internal/module.js:20:19
  
  - iframe.html.ejs:692 Object.<anonymous>
    [client-mobile-component-web]/[@storybook]/react/dist/server/iframe.html.ejs:692:9
  
  - iframe.html.ejs:639 __webpack_require__
    [client-mobile-component-web]/[@storybook]/react/dist/server/iframe.html.ejs:639:30
  
  - iframe.html.ejs:685 
    [client-mobile-component-web]/[@storybook]/react/dist/server/iframe.html.ejs:685:37
  
  - iframe.html.ejs:688 
    [client-mobile-component-web]/[@storybook]/react/dist/server/iframe.html.ejs:688:10
  
  - index.js:231 HtmlWebpackPlugin.evaluateCompilationResult
    [client-mobile-component-web]/[html-webpack-plugin]/index.js:231:26
  
  - index.js:117 
    [client-mobile-component-web]/[html-webpack-plugin]/index.js:117:21
  
  - util.js:16 tryCatcher
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [client-mobile-component-web]/[html-webpack-plugin]/[bluebird]/js/release/async.js:17:14
  

Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  27.7 kB       0  
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/react/dist/server/index.html.ejs 1.69 kB {0} [built]
Child html-webpack-plugin for "iframe.html":
          Asset   Size  Chunks  Chunk Names
    iframe.html  27 kB       0  
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/react/dist/server/iframe.html.ejs 966 bytes {0} [built]
^Cnpm run storybook:hot  4,40s user 0,36s system 17% cpu 27,695 total
`

**Comment by igor-dv** [comment]
@Scit , can you please share your webpack.config.js that's used in Storybook config dir ?

**Comment by Scit** [comment]
Webpack config:
`
'use strict';

const webpack = require ('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');

const appConfig = require('../../../webpack.config.js');

const path = require('path');
const appDirname = path.resolve(__dirname, '../../../');
const appRules = require('../../../webpack/rules');

// css, js loader rules
const rules = appRules({
    dirname: appDirname
});

const baseConfig = {
    resolve: Object.assign({}, appConfig.resolve, {
        modules: [
            appDirname,
            'node_modules'
        ]
    }),

    resolveLoader: appConfig.resolveLoader,

    plugins: [
        new ExtractTextPlugin('[name].[chunkhash].css'),
        new CleanWebpackPlugin([
            path.resolve(appDirname, 'dist_storybook')
        ], {
            verbose: false,
            root: appDirname
        }),
        new CaseSensitivePathsPlugin(),
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale/, /(en-gb|ru)\.js/),
    ],

    module: Object.assign(appConfig.module, {
        rules: appConfig.module.rules.concat(rules)
    })
};

module.exports = function(storybookBaseConfig, configType) {
    Object.assign(storybookBaseConfig, baseConfig, {
        plugins: storybookBaseConfig.plugins.concat(baseConfig.plugins)
    });
    return storybookBaseConfig;
};
`

Result config object:
`
{ devtool: 'cheap-module-source-map',
  entry: 
   { manager: 
      [ '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/node_modules/@storybook/react/dist/server/config/polyfills.js',
        '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/node_modules/@storybook/react/dist/server/addons.js',
        '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/node_modules/@storybook/react/dist/client/manager/index.js' ],
     preview: 
      [ '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/node_modules/@storybook/react/dist/server/config/polyfills.js',
        '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/node_modules/@storybook/react/dist/server/config/globals.js',
        '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/node_modules/webpack-hot-middleware/client.js?reload=true',
        '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/webpack/configs/storybook/config.js' ] },
  output: 
   { path: '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/node_modules/@storybook/react/dist/server/config/dist',
     filename: 'static/[name].bundle.js',
     publicPath: '/' },
  plugins: 
   [ HtmlWebpackPlugin { options: [Object] },
     HtmlWebpackPlugin { options: [Object] },
     DefinePlugin { definitions: [Object] },
     HotModuleReplacementPlugin {
       options: {},
       multiStep: undefined,
       fullBuildTimeout: 200,
       requestTimeout: 10000 },
     CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     WatchMissingNodeModulesPlugin {
       nodeModulesPath: '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web/node_modules' },
     ProgressPlugin { profile: undefined, handler: undefined },
     DefinePlugin { definitions: {} },
     ExtractTextPlugin { filename: '[name].[chunkhash].css', id: 2, options: {} },
     CleanWebpackPlugin { paths: [Array], options: [Object] },
     CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     NoEmitOnErrorsPlugin {},
     ContextReplacementPlugin {
       resourceRegExp: /moment[\/\\]locale/,
       newContentResource: undefined,
       newContentRecursive: undefined,
       newContentRegExp: /(en-gb|ru)\.js/ } ],
  module: 
   { noParse: [ /\/node_modules\// ],
     rules: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  resolve: 
   { modules: 
      [ '/home/scit/alphaopen/alpha/client/client-mobile/client-mobile-component-web',
        'node_modules' ],
     alias: 
      { core: 'src/core',
        'widget-core': 'src/widget-core',
        vendors: 'src/vendors',
        widgets: 'src/widgets',
        locales: 'src/locales',
        client: 'src/apps/client' } },
  performance: { hints: false },
  resolveLoader: { moduleExtensions: [ '-loader' ] } }
`

![screenshot from 2018-01-22 10-29-47](https://user-images.githubusercontent.com/661855/35209474-3635273e-ff5f-11e7-9ddc-69a5c995cc9c.png)

**Comment by Scit** [comment]
Solved aflter fixing main webpack config: replaced  noParse: [ /\/node_modules\// ] with noParse: [ /\/node_modules\/jquery// ]
