### ISSUE TITLE
vue typescript

### ISSUE THREAD

**Issue by davidm-public** [storybooks/storybook#2792]
Question: does anyone know the magic incantations required to get storybook working with Vue and Typescript?

**Comment by igor-dv** [comment]
It does work for angular in our monorepo. And AFAIK, some people do use storybook with ts in react apps. So nothing magical 

1. Use full controll mode - https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode
2. Add your favorite ts loader
3. ...
4. Profit 💸

Am I missing something?

**Comment by davidm-public** [comment]
SOLVED:

These work, for Vue + Typescript + Webpack:

1) ./.storybook/config.js:
```ts
import { configure } from '@storybook/vue'

// automatically import all files ending in *.stories.js
const req = require.context('../src/stories', true, /.stories.ts$/);
function loadStories() {
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module)
```

2) ./.storybook/webpack.conf.js:
```ts
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

const genDefaultConfig = require('@storybook/vue/dist/server/config/defaults/webpack.config.js');

module.exports = (storybookBaseConfig, configType) => {
  const config = genDefaultConfig(storybookBaseConfig, configType);

  config.resolve.extensions.push('.ts', '.tsx', '.vue', '.css', '.less', '.scss', '.sass', '.html')

  config.module.rules.push({
    test: /\.ts$/,
    exclude: /node_modules/,
    use: [
      {
        loader: 'ts-loader',
        options: {
          appendTsSuffixTo: [/\.vue$/],
          transpileOnly: true // used with ForkTsCheckerWebpackPlugin
        },
      }
    ],
  })

  config.plugins.push(new ForkTsCheckerWebpackPlugin())

  return config;
};
```

**Comment by alterx** [comment]
It looks like this one is solved.

**Comment by almeynman** [comment]
I have written a blog post on configuring storybook with vue and typescript [here](https://medium.com/@almeynman/setup-vue-with-storybook-using-vue-cli-3-0-typescript-example-1be64a7cc7ac). I think it's a much better approach. Will appreciate feedback

**Comment by wfsovereign** [comment]
If above resolution can‘t satisfy you, you can try my solution.

**webpack.config.js**

```javascript
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');


module.exports = (baseConfig, env, defaultConfig) => {

  defaultConfig.resolve.extensions.push('.ts', '.tsx', '.vue', '.css', '.less', '.scss', '.sass', '.html')

  defaultConfig.module.rules.push({
    test: /\.ts$/,
    exclude: /node_modules/,
    use: [
      {
        loader: 'ts-loader',
        options: {
          appendTsSuffixTo: [/\.vue$/],
          transpileOnly: true
        },
      }
    ],
  })

  // If you use scss,
  //  defaultConfig.module.rules.push({ test: /\.scss$/, loaders: ['style-loader', 'css-loader', 'sass-loader'] })

  defaultConfig.module.rules.push({ test: /\.less$/, loaders: [ 'style-loader', 'css-loader', 'less-loader' ] })

  defaultConfig.plugins.push(new ForkTsCheckerWebpackPlugin())

  return defaultConfig;
};

```

**Comment by Al-un** [comment]
Many thanks @wfsovereign . With the [full control mode](https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode--default), the incantation becomes:

```
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");

module.exports = ({ config }) => {
  config.resolve.extensions.push(
    ".ts",
    ".tsx",
    ".vue",
    ".css",
    ".less",
    ".scss",
    ".sass",
    ".html"
  );

  config.module.rules.push({
    test: /\.ts$/,
    exclude: /node_modules/,
    use: [
      {
        loader: "ts-loader",
        options: {
          appendTsSuffixTo: [/\.vue$/],
          transpileOnly: true
        }
      }
    ]
  });

  config.module.rules.push({
    test: /\.scss$/,
    loaders: ["style-loader", "css-loader", "sass-loader"]
  });

  config.plugins.push(new ForkTsCheckerWebpackPlugin());

  return config;
};
```

**Comment by eightHundreds** [comment]
> Many thanks @wfsovereign . With the [full control mode](https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode--default), the incantation becomes:
> 
> ```js
> const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
> 
> module.exports = ({ config }) => {
>   config.resolve.extensions.push(
>     ".ts",
>     ".tsx",
>     ".vue",
>     ".css",
>     ".less",
>     ".scss",
>     ".sass",
>     ".html"
>   );
> 
>   config.module.rules.push({
>     test: /\.ts$/,
>     exclude: /node_modules/,
>     use: [
>       {
>         loader: "ts-loader",
>         options: {
>           appendTsSuffixTo: [/\.vue$/],
>           transpileOnly: true
>         }
>       }
>     ]
>   });
> 
>   config.module.rules.push({
>     test: /\.scss$/,
>     loaders: ["style-loader", "css-loader", "sass-loader"]
>   });
> 
>   config.plugins.push(new ForkTsCheckerWebpackPlugin());
> 
>   return config;
> };
> ```

``` diff
{
-    test: /\.ts$/,
+    test: /\.tsx?$/,
    exclude: /node_modules/,
    use: [
      {
        loader: "ts-loader",
        options: {
          appendTsSuffixTo: [/\.vue$/],
          transpileOnly: true
        }
      }
    ]
}
```

**Comment by vertic4l** [comment]
And how do you solve the wrong typings issue?

<img width="947" alt="Bildschirmfoto 2020-01-07 um 10 27 03" src="https://user-images.githubusercontent.com/1771763/71884346-73443180-3138-11ea-9238-31af45a1d819.png">

**Comment by FlorianWendelborn** [comment]
Here’s the version that worked for me with the recent versions (`5.3`) of storybook:

**`.storybook/main.js`**:

```js
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')

module.exports = {
	stories: [
		'../src/components/**/stories.ts',
		'../src/components/**/stories.tsx',
	],
	addons: ['@storybook/addon-actions', '@storybook/addon-links'],
	webpackFinal: async (config, { configType }) => {
		config.resolve.extensions.push(
			'.ts',
			'.tsx',
			'.vue',
			'.css',
			'.less',
			'.scss',
			'.sass',
			'.html',
		)

		config.module.rules.push({
			test: /\.ts$/,
			exclude: /node_modules/,
			use: [
				{
					loader: 'ts-loader',
					options: {
						appendTsSuffixTo: [/\.vue$/],
						transpileOnly: true,
					},
				},
			],
		})

		config.plugins.push(new ForkTsCheckerWebpackPlugin())

		return config
	},
}

```
