### ISSUE TITLE
The requested URL /iframe.html/ was not found on this server.

### ISSUE THREAD

**Issue by maxlibin** [storybooks/storybook#2802]
Sorry, can anyone give me simple guide I am trying to load this static file from Laravel, 

 Route::get('/storybook', function() {
  return File::get(app_path('/assets/js/style-component/index.html'));
});

but I am getting:

Not Found
The requested URL /iframe.html/ was not found on this server.

**Comment by Hypnosphi** [comment]
Is there an `iframe.html` file in the same directory as `index.html`? You probably need to serve that as well
