### ISSUE TITLE
Storyshots is unable to locate stories

### ISSUE THREAD

**Issue by mattmayo** [storybooks/storybook#2805]
### Issue details

I am getting the error **Your test suite must contain at least one test.** There are valid stories and they look fine when running storybook.

### Steps to reproduce

Run jest

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/addon-storyshots 3.3.10
- storybook/addons 3.3.10
- storybook/channels 3.3.10
- storybook/react 3.3.10

### Affected platforms 

- React 15.6.1
- Jest 21.1.0

Seems like the stories load in the internal value _data via addStory, but when getStorybook is called the internal value _data is empty

Any help or pointers would be appreciated, been stuck on this issue for a few days

**Comment by igor-dv** [comment]
"Your test suite must contain at least one test" is an error coming from Jest. 
Can you please share your storyshot test file and the jest configuration file?

**Comment by mattmayo** [comment]
Hi and thank you for responding very quickly. I got sidetracked and was hoping to setup a sample project to duplicate as I have a feeling that the storyshot test file and jest config may not be enough to diagnose the issue. I'll close for now since I haven't been following up and re-open or create a new issue when I have more to help demonstrate the issue.
