### ISSUE TITLE
Angular storybook render blank components

### ISSUE THREAD

**Issue by amorenew** [storybooks/storybook#2823]
### Issue details
Expected: rendering Angular components
Actual: rendering blank components

### Steps to reproduce
I followed guide from https://storybook.js.org/basics/guide-angular/

![untitled](https://user-images.githubusercontent.com/2842459/35318501-b5f20df0-00ec-11e8-8d14-289f2feebb1e.png)
### Please specify which version of Storybook and optionally any affected addons that you're running
- storybook/angular : "^3.3.10"
- angular/core : "^5.2.0"

### Screenshots / Screencast / Code Snippets (Optional)

```import {storiesOf} from '@storybook/angular';
import {HeadComponent} from '../src/app/head/head.component';

storiesOf('My Button', module).add('with some emoji', () => ({
    component: HeadComponent,
    props: {
        text: '😀 😎 👍 💯'
    }
})).add('with some emoji and action', () => ({
    component: HeadComponent,
    props: {
        text: '😀 😎 👍 💯'

    }
}));
```
or main repo
https://github.com/amorenew/travel-angular

**Comment by igor-dv** [comment]
Can you please try v3.4.0-alpha.5. There were a few improvements in css/scss loading.
Also, you are providing a "text" prop to something that doesn't have a "text" prop, though I don't think it's the problem

**Comment by amorenew** [comment]
@igor-dv  I changed sass to scss and downgrade bootstrap to 3 instead of 4 and it got fix I don't know why
But I have a different problem now 
the guide doesn't mention images or fonts handling
how could I add font and images to .storybook/webpack.config.js
![image](https://user-images.githubusercontent.com/2842459/35320828-3c2b25e2-00f6-11e8-9371-793686504367.png)

**Comment by igor-dv** [comment]
Storybook currently uses `raw-loader` to load html files for `templateUrl`. Let's try changing it to `html-loader`. Can you please override it via the [full control mode](https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode--default)?

**Comment by amorenew** [comment]
@igor-dv I add full control mode but the same result
![image](https://user-images.githubusercontent.com/2842459/35323499-c1f1726e-00fe-11e8-90a8-bd385a20e7f1.png)

**Comment by Quramy** [comment]
@amorenew 

Is the `assets` dir listed in your .angular-cli.json ?  Storybook serves only the listed files as static assets.

```js
  "apps": [
    {
      "root": "src",
      "assets": [
        "assets",   // <- this
        "favicon.ico"
      ],
      :
    }
  ],

```

**Comment by amorenew** [comment]
@Quramy yes it is there 
angular-cli here
https://github.com/amorenew/travel-angular/blob/master/.angular-cli.json

**Comment by igor-dv** [comment]
@Quramy wasn't it added to the v3.4.0-alpha.X ?

**Comment by Quramy** [comment]
I've added serving assets feature at v3.4.0-alpha.5 ( #2735 ).

**Comment by amorenew** [comment]
@Quramy I will try v3.4.0-alpha.5 and I will report what happen

**Comment by Quramy** [comment]
@amorenew I could fix this issue with your repo(https://github.com/amorenew/travel-angular) via the following steps:

```
git clone https://github.com/amorenew/travel-angular; cd travel-angular
yarn install
yarn add @storybook/angular@3.4.0-alpha.5 -D
rm .storybook/webpack.config.js # extending webpack config is no longer needed
yarn run storybook
```

Finally, we get the following story 😄 

[![https://gyazo.com/31fac53939f2fdfad4fd5e074b6f7c11](https://i.gyazo.com/31fac53939f2fdfad4fd5e074b6f7c11.png)](https://gyazo.com/31fac53939f2fdfad4fd5e074b6f7c11)

Please check this out!

**Comment by amorenew** [comment]
Yeah it's working and fonts too
.storybook/webpack.config.j make problem removing it is better.
:sob: Thank you all @Quramy @igor-dv  :smile_cat:

**Comment by amorenew** [comment]
@Quramy one thing remaining I have a different font than the one displayed in storybook
any solution for this issue too?

**Comment by Quramy** [comment]
@amorenew Have you tried custom head tag(https://storybook.js.org/configurations/add-custom-head-tags/) ?

I think adding a link tag to load the Ranco font on the custom header may help you.

**Comment by amorenew** [comment]
@Quramy I checked your link and I used https://github.com/typekit/webfontloader
it loads on angular but not on storybook
![image](https://user-images.githubusercontent.com/2842459/35336271-df2c6aee-0128-11e8-94e1-5018cb860399.png)
in index.html
https://github.com/amorenew/travel-angular/blob/master/src/index.html

```
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
  <script>try {
      console.log("Start Google Font Loading");
      WebFont.load({
        google: {
          families: ['Rancho']
        }
      });
    } catch (error) {
      console.log("Google Font error");
      console.log(error);
    }
  </script>
```

**Comment by amorenew** [comment]
@Quramy yes it is working now 
I added `preview-head.html` in `.storybook` folder and it worked
Thank you

```
<!doctype html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
  <script>try {
      console.log("Start Google Font Loading");

      WebFont.load({
        google: {
          families: ['Rancho']
        }
      });
    } catch (error) {
      console.log("Google Font error");
      console.log(error);
    }
  </script>
</head>
</html>
```

**Comment by Quramy** [comment]
I’m out now, I'll check it after going home :)
