### ISSUE TITLE
Error running storybook - sh: 1: start-storybook: not found

### ISSUE THREAD

**Issue by besrabasant** [storybooks/storybook#2824]
I am facing error running **storybook**.... even on a clean installation.

```
 npm run storybook

> @ storybook /media/programmersedge/New_Volume/devs/demostorybook
> start-storybook -p 9001 -c .storybook

sh: 1: start-storybook: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ storybook: `start-storybook -p 9001 -c .storybook`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I am using the latest **storybook** version.
and my **node** version is _6.11.1_ and **npm** version is _5.5.1_

I also tried installing storybook with **yarn** but I am facing the same problem
**yarn** version _1.3.2_

**Comment by besrabasant** [comment]
I kind of solved the issue. I had to restart my machine and then run `getstorybook -f` to resolve the issue. But I face this issue whenever I install an npm package. Why is it so?? I installed `@storybook/addon-options` before facing this issue.

**Comment by Hypnosphi** [comment]
Can you please create a GitHub repo with minimal reproduction of your issue?

**Comment by lirunhui** [comment]
very good!
