### ISSUE TITLE
Question: Passing changeable value as a prop to a component

### ISSUE THREAD

**Issue by sdh20** [storybooks/storybook#2825]
### Issue details

Hello everyone.
I am creating a story for a component that has state value from a outer component as a prop. I solved this by creating a wrapper inside the story. Now Im adding information about the component using storybook/addon-info and therefore the propTypes doesn't show since the wrapper doesn't have any propTypes. However the component that the wrapper returns do have them, which is the actual component I'm displaying in the story. My question is: Is there any better way passing props with changeable value down to a component I'm displaying in my story? 

### Version of Storybook

   "storybook/addon-actions": "^3.3.3",
    "storybook/addon-info": "^3.3.10",
    "storybook/addon-knobs": "^3.3.10",
    "storybook/addon-links": "^3.3.3",
    "storybook/react": "^3.3.3",

###Code Snippets 

```js
import React, { Component } from 'react';
import Dropdown from './Dropdown';

import { storiesOf } from '@storybook/react';
import { withInfo } from '@storybook/addon-info';

const infoObject = {
  text: 'Dropdown component',
};

const values = [
  { value: 'placeholder', label: 'Choose option', disabled: true },
  { value: '1', label: 'Option 1' },
  { value: '2', label: 'Option 2' },
  { value: '3', label: 'Option 3' },
];

class DropdownWrapper extends Component {
  constructor(props) {
    super(props);
    this.state = {
      option: 'placeholder',
    };
  }

  render() {
    return (
      <Dropdown
        options={values}
        value={this.state.option}
        onChange={e => {
          this.setState({ option: e.target.value });
        }}
      />
    );
  }
}
export const dropdownStory = storiesOf('Dropdown', module).add(
  'Dropdown',
  withInfo(infoObject)(() => <DropdownWrapper />)
);

```

**Comment by igor-dv** [comment]
@sdh20 , why don't you use knobs?

**Comment by Hypnosphi** [comment]
You can try any of the `addon-state`s: https://storybook.js.org/addons/addon-gallery/#state

**Comment by sdh20** [comment]
@sambego/storybook-state solves this problem since it doesn't create a wrapper component, thank you!
