### ISSUE TITLE
Question: How to use angular transclusion in a Storybook.js 

### ISSUE THREAD

**Issue by vasinkevych** [storybooks/storybook#2827]
### Issue details

Hi, is it possible in a story put some message via transcluding?

    "@storybook/angular": "^3.3.9",

### Steps to reproduce

```js
// component template
<button [type]="type"
        [ngClass]="['button']"
        [disabled]="disabled"
        [name]="name"
        >
  <ng-content></ng-content>
</button>

```
In that case, a button is empty. Is there any way to pass some text(html) in stories?

**Comment by igor-dv** [comment]
@vasinkevych  it's duplicate to #2817

**Comment by vasinkevych** [comment]
Thanks, a lot
