### ISSUE TITLE
[addon-a11y] Allow Configuration of aXe

### ISSUE THREAD

**Issue by codingmatty** [storybooks/storybook#2830]
### Issue details

We use aXe along with custom rules and checks to comprehensively check our components for accessibility issues. We also override some of aXe's rules locally if we find any inconsistencies. 

It would be really nice if we could pass our configuration into the a11y add-on for storybook, so all of our custom rules and checks are displayed.

Instead you run only the default configuration and nothing more: https://github.com/storybooks/storybook/blob/5143028caf7e64ca4307ab2e56621d8c66fe4576/addons/a11y/src/components/WrapStory.js#L40

**Comment by jbovenschen** [comment]
I am the original author of this plugin, I know that this could be a bit of an issue, it would be cool if we could just pass the configuration within the decorator, I'm currently not actively using storybook or this plugin, but would like to review any PR for this.

**Comment by wuweiweiwu** [comment]
I can pick this up! I'll work on it this week

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.0`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.0)
