### ISSUE TITLE
Unexpected token (css and sass) - addon-storyshots

### ISSUE THREAD

**Issue by jsanes** [storybooks/storybook#2832]
### Issue details

I get an Unexpected token error when running the Storyshots test. It happens at the `@import` from a SCSS file as well as the first bracket of a CSS file.

Stories work correctly but snapshot tests do not.

### Steps to reproduce

Import in the `.storybook/config.js` an SCSS or CSS file and run the test.

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react 3.1.9`
- `@storybook/addon-storyshots 3.3.10`

**Comment by igor-dv** [comment]
@jsanes can you please share your config.js / webpack.config.js / sotryshots test file?
Also, you've specified versions of something that is not clear what (And those versions are not matching, which is wrong). Do you use Storybook for react/angular/vue?

**Comment by jsanes** [comment]
@igor-dv I'm using Storybook for React. Sorry for not clarifying the versions I'm using (markdown hid the first part). I just fixed it. 

I have Storyshots working now. I had to install `jest-css-modules` and add `"scriptPreprocessor": "<rootDir>/node_modules/jest-css-modules"` to my `jest` configuration on `package.json`.

**Comment by igor-dv** [comment]
Cool !
