### ISSUE TITLE
Custom webpack configs: "Full control + remote

### ISSUE THREAD

**Issue by hollandmatt** [storybooks/storybook#2834]
### Issue details

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react x.x.x
- @storybook/addon-something x.x.x

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```

**Comment by igor-dv** [comment]
![travolta](https://user-images.githubusercontent.com/7867954/35378346-1f5eb31e-01bb-11e8-89ad-64afec5d621f.gif)

**Comment by hollandmatt** [comment]
Not sure what happened here! I'll close this.
