### ISSUE TITLE
Recommended way to shutdown server with image snapshots

### ISSUE THREAD

**Issue by interactivellama** [storybooks/storybook#2839]
### Issue details

[The readme](https://github.com/storybooks/storybook/tree/master/addons/storyshots#configure-storyshots-for-image-snapshots--alpha-) says to have the server concurrently running with the image snapshot tests. I can start an express server before the tests run, but I don't see any callback API with the `initImageSnapshot` function. What's the recommended way to shut down the server afterwards? Should `initImageSnapshot` be wrapped in a `describe`/ `before/after` structure?

I'm willing to pull request to the readme if you can provide me some direction.

### Steps to reproduce

Follow the directions in the readme. ;-)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/addon-something image-snapshots 3.4-alpha

**Comment by igor-dv** [comment]
I'm not sure I understand your question. 

[This ](https://github.com/storybooks/storybook/tree/master/addons/storyshots#specifying-options-to-jest-image-snapshots) example shows how to configure image snapshots with the **static** (exported) instance of Storybook.

What do you mean by 
> have the server concurrently running

**Comment by interactivellama** [comment]
I was unable to get `file:///path/to/my/storybook-static` working when pointed at my static build folder, so I've written my own Express server to allow access to the static Storybook build.

Should I be doing something like this?

```
let server;

const startServer = () => {
	// Create server
	const app = express();

	// Static directories
	app.use(
		'/assets',
		express.static(
			`${__dirname}/node_modules/@salesforce-ux/design-system/assets/`
		)
	);
	app.use(express.static(`${__dirname}/storybook`));

	// Listen
	server = app.listen(port, () => {
		console.log('Server listening on port ', server.address().port);
	});
};

// Comment out until all components are ready to be DOM snapshot tested
//  initStoryshots();

const getMatchOptions = ({ context: { kind, story }, url }) => ({
	failureThreshold: 0.2,
	failureThresholdType: 'percent'
});

describe('Image Snapshots', function imageSnapshotFunction () {
	beforeEach(() => {
		startServer();
	});

	afterEach(() => {
		server.close();
	});

	initStoryshots({
		suite: 'Image storyshots',
		test: imageSnapshot({
			storybookUrl: `http://localhost:${port}`,
			getMatchOptions
		})
	});
});
```

**Comment by igor-dv** [comment]
Ah, I see. IMO the recommended way is to make it working with the static version. But if you think that for your purposes running an express server is a better solution go for it =) 
Regarding the docs - everything that will help others to solve their problems is welcomed to be in docs 👍 .

P.S. Maybe @storybooks/team has another opinion.

**Comment by interactivellama** [comment]
I would love the for the static version to work. The static version doesn't serve my CSS and other cross origin issues (fonts, etc).

I get stuff like this:
![storyshots-test-js-image-snapshots-image-storyshots-slds-accordion-base-1-diff](https://user-images.githubusercontent.com/1290832/35403174-26b36398-01bc-11e8-9c54-dfaab8d50107.png)


@igor-dv How do you serve CSS in your static `file:///` version?

**Comment by igor-dv** [comment]
How do you load/serve your assets in your app?

**Comment by interactivellama** [comment]
We used to use Webpack for Storybook, but Jest choked on the CSS (token not recognized?), so I put the CSS `<link/>` in the `.storybook/preview-head.html` file.

This isn't for a real production application. It's for a React implementation of a [Design System](https://lightningdesignsystem.com/).

**Comment by interactivellama** [comment]
I'm going to close this issue. The following works:

```
import express from 'express';
import initStoryshots, { imageSnapshot } from '@storybook/addon-storyshots';

// Create server
const app = express();
app.use(express.static(`${__dirname}/storybook`));
// Static directories for assets
app.use(
	'/assets',
	express.static(
		`${__dirname}/node_modules/@salesforce-ux/design-system/assets/`
	)
);

const port = process.env.PORT || 9001;
let server;

const getMatchOptions = ({ context: { kind, story }, url }) => ({
	failureThreshold: 0.2,
	failureThresholdType: 'percent'
});

describe('Image Snapshots', function imageSnapshotFunction () {
	beforeAll((done) => {
		server = app.listen(port, () => {
			console.log('Storybook server listening on port ', server.address().port);
			done();
		});
	});

	afterAll((done) => {
		server.close(() => {
			console.log('Shutting down the server running Storybook');
			done();
		});
	});

	initStoryshots({
		suite: 'Image storyshots',
		test: imageSnapshot({
			storybookUrl: `http://localhost:${port}`,
			getMatchOptions
		})
	});
});

```

**Comment by interactivellama** [comment]
Unless a maintainer would like a pared down version of this in the readme?

**Comment by igor-dv** [comment]
@interactivellama , did you try to use -s ([static assets](https://storybook.js.org/configurations/serving-static-files/)) parameter with build-storybook command?

Also,
> We used to use Webpack for Storybook, but Jest choked on the CSS 

I am not sure I understand, why jest is related when you are exporting the static storybook

**Comment by interactivellama** [comment]
I don't know if it's Jest, but `build-storybook`, with Babel/Webpack's help doesn't choke on `@charset "UTF-8";`, but when I run a CSS/JS bundle with `@charset "UTF-8";` in it through Jest, it does. 

I was not aware of the `-s` argument. I figured `-o` was doing that, since there was a JS bundle there. I didn't need `-s` before, because the CSS was being bundled into the JS, so `build-storybook` always worked fine and Webpack understood it and it's been on the public internet for a while. [This was built with the CSS into JS bundling](http://design-system-react-components.herokuapp.com/?selectedKind=SLDSAccordion&selectedStory=Base&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) with Webpack's help. I will look into `-s`. Thanks!
