### ISSUE TITLE
New App [Frameworks], can they be built externally like add-ons?

### ISSUE THREAD

**Issue by jasonmacdonald** [storybooks/storybook#2841]
I just came across this project and it looks great! In fact, I have built tooling for my own project with a similar goal, but not nearly as "complete". My question is around supporting new frameworks; do they have to be built by this team and deeply integrated, or can they be built similar to add-ons? Specifically, I would like to use this with the Markojs framework, and I don't mind doing the work if I can build and run it without needing to get it included directly to this repo (not that I couldn't submit it). 

There doesn't seem to be docs relating to how to include new apps the same way there is for add-ons, so wasn't sure if this was possible as an external "app" that people could just require in an use.

**Comment by Hypnosphi** [comment]
We have some ongoing work on extracting common parts of the apps: #2240 

It should make supporting more frameworks a lot easier, and probably allow external apps. Feel free to contact us on slack if you'd like to collaborate on that: https://now-examples-slackin-rrirkqohko.now.sh/

**Comment by ndelangen** [comment]
Hi @jasonmacdonald Let's talk! I'd love to work with your to get storybook to support markojs!

You can PM me on our slack or on twitter, what you prefer!

**Comment by shilman** [comment]
@jasonmacdonald To add to what both of these guys just said, supporting a new framework is as simple as creating a new NPM package, and it doesn't necessarily have to be part of the Storybook repo (tho we'd love to include it). We're still documenting and improving that process, but your best bet is to work with @ndelangen to get yourself up and running. After success adding Vue, Angular, and soon Polymer, it's getting more and more streamlined. 😀

**Comment by jasonmacdonald** [comment]
Awesome! It was the "hidden" bits I was concerned about. I couldn't tell at first glance if all the moving parts were encapsulated within the apps themselves or not. Perhaps I'll start by just taking a crack at adding Marko as an app, and I'll ping you guys if I run into any major snags. Cheers!

**Comment by sixmen** [comment]
I'm also making a storybook app for Mithril, which I use.

What is your plan for these apps?
If you want to include apps for minor frameworks to the storybook repository, I will make a PR.
Or, I will publish it as own package.

**Comment by ndelangen** [comment]
@sixmen @jasonmacdonald I'd invite both of you for a skype call so I can explain to process. I think that will really help you along a lot.

And it would also give us the opportunity to meet and connect the communities a bit.

**Comment by igor-dv** [comment]
@ndelangen, there was also a question about Stencil recently in #support. Did something happen with this?
