### ISSUE TITLE
Vue Backgrounds Addon Support

### ISSUE THREAD

**Issue by adamsoffer** [storybooks/storybook#2845]
Are there any plans to port the backgrounds addon to vue? In the meantime is there a workaround to a implement a background color in a vue storybook?

**Comment by Hypnosphi** [comment]
It might be easier to do now when we've moved background wrapper outside of preview iframe in #2807

**Comment by wuweiweiwu** [comment]
I'll get this out in the next couple of days

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.4`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.4)
