### ISSUE TITLE
Angular CLI + Custom Config Causes Errors

### ISSUE THREAD

**Issue by amcdnl** [storybooks/storybook#2848]
## Issue
When you have a Angular CLI project that storybook is bootstrapping on and you use full control mode in combination with that the loaders are getting clobbered.

For example, I use `DefinePlugin` to conditionally include tests in full control mode:

```javascript
const fs = require('fs');
const webpack = require('webpack');

module.exports = (storybookBaseConfig, configType) => {
    storybookBaseConfig.plugins.push(
        new webpack.DefinePlugin({
            TESTS: fs.existsSync('./.test-results.json')
        })
    );

    return storybookBaseConfig;
};
```
When I run storybook, it throws errors like:

```
ERROR in ./src/assets/fonts/MarkWebPro-LightW01Regular.eot
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader?{"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss"}!./src/assets/styles/custom.css 7:1595-1645 7:1678-1728
 @ ./src/assets/styles/custom.css
```

Which seems to indicate that the loaders are getting clobbered somehow. If I remove `webpack.config.js`, everything works fine though.

**Comment by amcdnl** [comment]
After digging through the code, I found the CLI config is the third argument. If you use that, everything works fine.

```
module.exports = (storybookBaseConfig, configType, cliConfig) => {
    cliConfig.plugins.push(
        new webpack.DefinePlugin({
            TESTS: fs.existsSync('./.test-results.json')
        })
    );

    return cliConfig;
};
```

**Comment by igor-dv** [comment]
Actually, docs are updated =) And that caused to another misunderstanding #2836 =)))
