### ISSUE TITLE
master tests not passing

### ISSUE THREAD

**Issue by kn0ll** [storybooks/storybook#2859]
first i'd like to say... apologies for this issue... all signs would suggest this is very much *my* problem and not storybook's...

### Issue details

- What did you expect to happen?

on a fresh checkout, i expected the tests to pass.

- What happened instead?

the tests did not pass. instead they fail with snapshot errors, seemingly always involving dates. some dates seem to be off by a day (`January 20, 2017` vs `January 19, 2017)`-- i could imagine this has something to do with regenerating snapshots? forgive me, i am unfamiliar with snapshot testing. but other dates are actually correct, only parsed and displayed differently (`2017-1-20` vs `1/20/2017`). which is a little more suspicious, no? you can find the full output of my tests here: https://gist.github.com/kn0ll/49cbca55faffe74fe1aee40229135521

### Steps to reproduce

```
git clone git@github.com:storybooks/storybook.git
cd storybook
yarn install
yarn bootstrap --all
yarn test --core
```

### Please specify which version of Storybook and optionally any affected addons that you're running

`commit f8bd011e7374ff65f442aa1a8e6963f2d8d2b85d (HEAD -> master, origin/master, origin/HEAD)`

### Affected platforms 

- macOS 10.13.2 (17C205)
- node v9.4.0
- yarn 1.3.2
- [node_modules versions](https://gist.github.com/kn0ll/f3615c98dd56828e716fde750b16b72d)

**Comment by Hypnosphi** [comment]
@tobilen this looks related to your change in date displaying

**Comment by tmeasday** [comment]
@Hypnosphi - remind me, did we end up fixing that on the other issue?

Also weird with the locale printing the date differently. I would propose we just change this test to print out the date as a timestamp or something; we really don't need to test JS date formatting in our tests ;)

**Comment by Hypnosphi** [comment]
> did we end up fixing that on the other issue

Not really

I think we should just set both locale and timeyone explicitly everywhere we display a date

**Comment by tmeasday** [comment]
Hopefully this helps: https://github.com/storybooks/storybook/pull/2861

**Comment by tmeasday** [comment]
@kn0ll can you try latest `master` please?

**Comment by tvooo** [comment]
Had the same issue last week. Can confirm the tests now pass with a fresh checkout of master. Thanks!

**Comment by kn0ll** [comment]
seeing the same issue. will check again this evening to make sure it's not loading old linked module or something.
