### ISSUE TITLE
getstorybook errors with ETIMEOUT 

### ISSUE THREAD

**Issue by nehaverma8** [storybooks/storybook#2865]
### Issue details

I installed @storybook\cli
I navigated to my react project : demo
I ran the command : getstorybook 

I got an error
connect ETIMEOUT 151.101.208.162.80 

Expected the related folders and scripts to be added to my project
### Steps to reproduce

I am behind a enterprise proxy 

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/cli 3.3.11

### Affected platforms 

Windows 7 Enterprise 
### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```

**Comment by Hypnosphi** [comment]
@storybooks/team any idea how to debug that?

**Comment by danielduan** [comment]
you'll need to configure NPM to use a proxy.

```
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
```
