### ISSUE TITLE
ember.js support?

### ISSUE THREAD

**Issue by gabrielcsapo** [storybooks/storybook#2877]
Is there a hope that ember.js support will be added or open to being added in the future?

**Comment by gabrielcsapo** [comment]
Just saw a link in the roadmap https://github.com/storybooks/storybook/blob/243abc6e775d7ac8ccc0d3473deb6a3beed27711/ROADMAP.md#ember has there been any traction here?

**Comment by jbryson3** [comment]
I’d be interested in lending a hand with development. Has development already started for Ember framework support? Is there a guide/checklist to follow when adding support for a new framework?

**Comment by gabrielcsapo** [comment]
I would be down, just need a go from the ember folks and yeah a checklist from the storybook folks

**Comment by danielduan** [comment]
@ndelangen ?

**Comment by gabrielcsapo** [comment]
I wish I had someone I could ping... Oh wait @storybookgods! Here my prayer for an easier dev cycle with less churn and more storybook!

**Comment by igor-dv** [comment]
You can take a look #3244 - this is an open PR for a new framework support.

**Comment by ndelangen** [comment]
@jbryson3, @gabrielcsapo If you'd like to join us on slack, we can discuss this. I can give you insight on what it would take and teach you the architecture of storybook.

Please PM me 👍 

Would love to add support for ember to storybook!

**Comment by gabrielcsapo** [comment]
would be great to join the slack, can I get an invite to the slack group or can I just join without one?

**Comment by Hypnosphi** [comment]
Our slack is open to join without invite: https://now-examples-slackin-rrirkqohko.now.sh/

There is no #ember channel yet, feel free to create one

**Comment by gabrielcsapo** [comment]
leh sigh... 💨

**Comment by scalvert** [comment]
@ndelangen I've created an #ember channel in the storybook slack. 

@jbryson3 @gabrielcsapo feel free to join and we can start this discussion.

**Comment by scalvert** [comment]
Also, can we reopen this issue?

**Comment by gabrielcsapo** [comment]
It’s happening! 🎉

**Comment by ndelangen** [comment]
So awesome! Let me know what I can do to help!

**Comment by ndelangen** [comment]
Amazing achievement team!
