### ISSUE TITLE
Angular-cli Example Error Cannot find module '@storybook/addon-knobs/angular'

### ISSUE THREAD

**Issue by amorenew** [storybooks/storybook#2879]
### Issue details
I downloaded [Angular-cli example](https://github.com/storybooks/storybook/tree/master/examples/angular-cli) and it doesn't work

### Steps to reproduce
after you download the angular-cli example 
1- in cmd use yarn
2-then yarn start

```
ERROR in node_modules/@storybook/angular/index.d.ts(30,44): error TS2304: Cannot find name 'NodeRequire'.
src/stories/addon-knobs.stories.ts(14,8): error TS2307: Cannot find module '@storybook/addon-knobs/angular'.
src/stories/component-with-di/di.component.stories.ts(2,33): error TS2307: Cannot find module '@storybook/addon-knobs/angular'.
src/stories/custom-metadata.stories.ts(2,33): error TS2307: Cannot find module '@storybook/addon-knobs/angular'.
```
### Affected platforms 
-windows 10

### Screenshots / Screencast / Code Snippets (Optional)

![image](https://user-images.githubusercontent.com/2842459/35610847-f6a2f4cc-0673-11e8-85bd-e99458d1edf2.png)

**Comment by igor-dv** [comment]
@amorenew , you are trying to bootstrap a project which is part of the Storybook Monorepo. That means you can't actually setup it independently. You need to clone the full monorepo and bootstrap it as described [here](https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md).

**Comment by amorenew** [comment]
@igor-dv thank you
