### ISSUE TITLE
Improve tutorials for Angular version

### ISSUE THREAD

**Issue by plamf** [storybooks/storybook#2880]
### Issue details

It isn't clear how to write more complex stories for Angular, including modules and services

### Steps to reproduce

Add a story of an angular module which depends on a service

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 3.3.9 for angular

I'm trying to create a story for angular modules, since just the component alone is often not enough to display everything the component is supposed to do.
Is this even possible?

**Comment by amorenew** [comment]
@plamf 
they just are all volunteers and I think we could follow releases and helping them in improving the docs.
for now, this is the link for angular examples:
[Angular Story Examples](https://github.com/storybooks/storybook/tree/master/examples/angular-cli/src/stories)

How to edit docs:
![image](https://user-images.githubusercontent.com/2842459/35623229-d912a98e-069b-11e8-9a1a-426793ec36e6.png)

**Comment by noratodaitan** [comment]
Sorry, I said I could do it...
I'll improve it

**Comment by plamf** [comment]
Thanks for the link, @amorenew 
I'll check the examples out

**Comment by igor-dv** [comment]
I think we can close it. Please reopen if you think otherwise or encounter specific issues
