### ISSUE TITLE
build fails with relative image paths in markdown

### ISSUE THREAD

**Issue by mediafreakch** [storybooks/storybook#2881]
### Issue details

In my markdown file I do this: `![Image](static/myimage.png)`.
Then, when I run `build-storybook -s ./storybook/stories/static`, build fails with:

```
info @storybook/react v3.3.9
info 
info => Loading custom .babelrc
info => Loading custom addons config.
info => Loading custom webpack config (extending mode).
info => Copying static files from: ./storybook/stories/static
info Building storybook ...
ERR! Failed to build the storybook
ERR! ./storybook/stories/myimage.png
ERR! Module parse failed: Unexpected character '�' (1:0)
ERR! You may need an appropriate loader to handle this file type.
ERR! (Source code omitted for this binary file)
ERR!  @ ./storybook/stories/Home.md 1:36-71
ERR!  @ ./storybook/stories/index.js
ERR!  @ ./.storybook/config.js
ERR!  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./.storybook/config.js
```

The only way to get the build pass is to use an absolute path `![Image](/myimage.png)`.
But then images are broken when published on GitHub. I need to use relative paths.

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react v3.3.9`
- `@storybook/storybook-readme v3.0.6`

**Comment by Hypnosphi** [comment]
Do you use a custom webpack config? How does it look like?

**Comment by mediafreakch** [comment]
@Hypnosphi Nothing markdown specific anymore since v3.3.0. It looks like this:

```
module.exports = {
  plugins: [ ],
  module: {
    rules: [
      { test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel-loader' },
      { test: /\.scss$/, loaders: ['style-loader', 'css-loader', 'sass-loader?precision=10'] },
    ],
  },
}
```

**Comment by igor-dv** [comment]
@mediafreakch, is this still an issue?

**Comment by mediafreakch** [comment]
Resolved the issue by dropping the custom webpack config. Relative Image paths work as expected with the default one.
