### ISSUE TITLE
import markdown.md for addons "Cannot find module"

### ISSUE THREAD

**Issue by amorenew** [storybooks/storybook#2883]
### Issue details
I want to use markdown.md with addons but I can't import it

### Steps to reproduce
I got error import README1 from '../src/framework/content/README1.md';
`error TS2307: Cannot find module '../src/framework/content/README1.md'.
`

### Please specify which version of Storybook and optionally any affected addons that you're running
   -storybook/addon-notes": "^3.3.11",
   -storybook/angular": "^3.4.0-alpha.5",

### Screenshots / Screencast / Code Snippets (Optional)
![35622048-80ae5544-0697-11e8-9d4f-fd547f5f17cc](https://user-images.githubusercontent.com/2842459/35622904-939959c6-069a-11e8-941f-970efa42e9ec.png)

**Comment by Hypnosphi** [comment]
Can you please create a GitHub repo with minimal reproduction of your issue?

**Comment by amorenew** [comment]
@Hypnosphi 
The repo link on GitHub https://github.com/amorenew/travel-angular
Steps:
1-install packages >>`yarn`
2-run the angular app >>`yarn start`
3-run the storybook >>`yarn storybook`

**Comment by Hypnosphi** [comment]
@igor-dv mind taking a look?

**Comment by igor-dv** [comment]
👌  Will check tomorrow

**Comment by igor-dv** [comment]
So, I've tried to figure this out and looks like there is some problem with importing non ts file when using typescript. I think it's not related to storybook. Maybe @alterx or @amcdnl can shed some light

**Comment by amcdnl** [comment]
Try putting this in your TS code:

```
declare module '*.md';
```

**Comment by amorenew** [comment]
putting `declare module '*.md';` in index.ts not working

![image](https://user-images.githubusercontent.com/2842459/35755905-37a761ee-087a-11e8-9665-5cdf77bd3412.png)

I followed [angular docs ](https://angular.io/guide/typescript-configuration#typings) and then I made `typings.d.ts` file in root and I added in it
```
declare module "*.md" {
    const value: string;
    export default value;
}
```

it works no error but I don't think it returns value because `withNotes` addons doesn't show text

![aassa](https://user-images.githubusercontent.com/2842459/35756398-3623e8ae-087c-11e8-881a-f483e2bd8eba.png)
while without readme.md it show a value

![image](https://user-images.githubusercontent.com/2842459/35756417-49516e42-087c-11e8-9341-ded2bfb6bb51.png)

**Comment by vasinkevych** [comment]
hi @amorenew, I've used your above approach and added 'marked' module 
there is my story: 
import * as marked from 'marked';
import * as readme from '../app/components/popup/README.md';

storiesOf('comp', module)
  .addDecorator(withKnobs)
  .add(
    'withNotes',
    withNotes({ text: marked(readme) })(() => ({
...story there
    }))
  );
`

**Comment by amorenew** [comment]
@vasinkevych 
`import * as readme from '../app/components/popup/README.md';` works
not
`import README1 from '../src/framework/content/README1.md';`

Thanks a lot all.

**Comment by amorenew** [comment]
it works in normal case but not when I am trying to build
I use in building my storybook:
"storybook-build": "build-storybook -c .storybook -o dist/storybook"
and I got the following error:
```
ERR! ./src/framework/content/README1.md
ERR! Module parse failed: Unexpected character '#' (1:0)
ERR! You may need an appropriate loader to handle this file type.
```
![image](https://user-images.githubusercontent.com/2842459/35860311-a3dcb7ce-0b54-11e8-98af-2276addff5df.png)

I tried to use the following readme loader: 
https://github.com/peerigon/markdown-loader
```
const marked = require("marked");
const renderer = new marked.Renderer();

return {
    module: {
        rules: [{
                test: /\.md$/,
                use: [
                    {
                        loader: "html-loader"
                    },
                    {
                        loader: "markdown-loader",
                        options: {
                            pedantic: true,
                            renderer
                        }
                    }
                ]
            }]
    }
}
```
but it gives me
```
E:\Cross\travelangular\node_modules\@storybook\angular\dist\server\config.js:75
      rules: [].concat((0, _toConsumableArray3.default)(config.module.rules), (0, _toConsumableArray3.default)(customConfig.module.rules ||
[]))
                                                                                                                                   ^
TypeError: Cannot read property 'rules' of undefined
    at exports.default (E:\Cross\travelangular\node_modules\@storybook\angular\dist\server\config.js:75:132)
    at Object.<anonymous> (E:\Cross\travelangular\node_modules\@storybook\angular\dist\server\build.js:76:35)
```
@vasinkevych Are you able to **build** not just run your storybook?

**Comment by igor-dv** [comment]
@amorenew , you are right. Just checked and seems like rules for `md` files are not used in the static build configuration. I'll fix it asap. 

If the configuration you mentioned is a custom webpack.config you need to add it like this

```js
moudle.exports = { /// <----
    module: {
        rules: [{
                     //...
            }]
    }
}
```
Also we are using this rule for md files:
```
        {
          test: /\.md$/,
          use: [
            {
              loader: 'html-loader',
            },
            {
              loader: 'markdown-loader',
            },
          ],
        }
```

**Comment by amorenew** [comment]
in `.storybook` I added `webpack.config.js `with your config and it `works`
```
const path = require('path');

module.exports = {
    module: {
        rules: [{
            test: /\.md$/,
            use: [
              {
                loader: 'html-loader',
              },
              {
                loader: 'markdown-loader',
              },
            ],
            include: path.resolve(__dirname, '../')
          }]
    }
}
```
@igor-dv
after you patch so in next **alpha release** I don't need to add anything to webpack.config. right?

**Comment by igor-dv** [comment]
@amorenew, right

**Comment by amorenew** [comment]
really I don't see an open source repo with that much support before.
**😍 😆 😅 😆 😍**

**Comment by cwmrowe** [comment]
I'm using `@storybook/angular@3.4.0-alpha.8`, using @amorenew's `webpack.config.js` and importing markdown with 
```
import * as docs from './button.md';
```
But I'm still getting `error TS2307: Cannot find module './button.md'`. Any thoughts why this isn't working?

**Comment by amorenew** [comment]
@cwmrowe 
check my tsconfig.json
I have
```
"typeRoots": [
      "node_modules/@types","./typings.d.ts"
    ],
```
and In typings.d.ts
```
declare module "*.md" {
    const value: string;
    export default value;
}
```

Full repo
https://github.com/amorenew/travel-angular/blob/master/.storybook/webpack.config.js
but I still on alpha.5, not 8

**Comment by cwmrowe** [comment]
Thanks @amorenew

**Comment by KevinTHicks** [comment]
For those using Angular CLI with Storybook 3.4.0 release - you may have to add the typedef changes suggested by @amorenew in the typings.d.ts file _in the src directory_.  That's what got this to work for me!

Thanks for saving me a night of headaches tracking this down.

**Comment by Yunnkii** [comment]
@cwmrowe  did you solve your question? 
i use   `import * as docs from './button.md';`  
still ` I'm still getting error TS2307: Cannot find module './button.md'`

**Comment by Yunnkii** [comment]
@cwmrowe  did you solve your question?
i use `import * as docs from './button.md';`
but still `error TS2307: Cannot find module './button.md'`

**Comment by igor-dv** [comment]
Did you add 
```
declare module "*.md" {
    const value: string;
    export default value;
}
```

**Comment by littlepoolshark** [comment]
i encountered the same issue as @Yunnkii !
@cwmrowe  did you solve your question?

**Comment by dagatsoin** [comment]
Still have the warning event with the typings declaration.

**Comment by ifthenelse** [comment]
Hi guys, I'm still getting errors here.
I'm making a simple documentation using Angular Material components.
Here's my brief Storybook configuration:

**ng-cli**
```sh
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.2.1
Node: 11.9.0
OS: darwin x64
Angular: 7.2.0
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.0
@angular-devkit/build-angular     0.12.0
@angular-devkit/build-optimizer   0.12.0
@angular-devkit/build-webpack     0.12.0
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/animations               7.2.2
@angular/cdk                      7.3.0
@angular/cli                      7.2.1
@angular/material                 7.3.1
@ngtools/webpack                  7.2.0
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1
```

**tsconfig.json**
```ts
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": ["node_modules/@types", "./typings.d.ts"],
    "lib": ["es2018", "dom"]
  }
}
```

**typings.d.ts**
```ts
declare module '*.md' {
  const content: string;
  export default content;
}
```

**.storybook/addons.js**
```ts
/* eslint-disable import/no-extraneous-dependencies, import/no-unresolved, import/extensions */

import '@storybook/addon-options/register';
import '@storybook/addon-knobs/register'
import '@storybook/addon-actions/register';
import '@storybook/addon-notes/register';
```

**.storybook/config.js**
```ts
/* eslint-disable import/no-extraneous-dependencies, import/no-unresolved, import/extensions */
import { configure, addDecorator } from '@storybook/angular';
import { withOptions } from '@storybook/addon-options';
import { withKnobs } from '@storybook/addon-knobs';
import { action } from '@storybook/addon-actions';

import '@angular/material/prebuilt-themes/deeppurple-amber.css';

addDecorator(
  withOptions({
    name: 'Storybook Angular Material',
    addonPanelInRight: true
  })
);

addDecorator(withKnobs);

addDecorator(withNotes);

// import all files ending in *.stories.ts
const req = require.context('../src/', true, /.stories.ts$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

**src/app/material/mat-button.stories.ts**
```ts
import { storiesOf, moduleMetadata } from '@storybook/angular';
import { MatButtonModule, MatIconModule } from '@angular/material';
import basicDoc from '../notes/mat-button-basic.md';

import { boolean, select, text } from '@storybook/addon-knobs';

import { withNotes } from '@storybook/addon-notes';

storiesOf('Button', module)
  .addDecorator(
    moduleMetadata({
      imports: [MatButtonModule, MatIconModule],
      providers: []
    })
  )
  .add('Basic', () => {
    return {
      template: `<button mat-raised-button [disabled]="disabled" [disableRipple]="disableRipple" [color]="color">
        <span>{{ label }}</span>
        <mat-icon
          *ngIf="!!icon"
          [attr.aria-label]="'Icon ' + icon"
          style="margin-left: 0.25em;">
            {{ icon }}
          </mat-icon>
      </button>`,
      props: {
        label: text('label', 'Basic'),
        disabled: boolean('disabled', false),
        disableRipple: boolean('disableRipple', false),
        color: select(
          'color',
          {
            none: '',
            primary: 'primary',
            accent: 'accent',
            warn: 'warn'
          },
          ''
        ),
        icon: select(
          'icon',
          {
            none: '',
            favorite: 'favorite',
            home: 'home',
            weekend: 'weekend',
            sort: 'sort',
            gesture: 'gesture'
          },
          ''
        )
      },
      notes: { markdown: basicDoc }
    };
  });
```

**src/app/notes/mat-button-basic.md**
```md
# Button

Lorem ipsum dolor sit amet consectetur adipliscig elit...
```

Still getting error when compiling:
```sh
ERROR in /Users/ifthenelse/Sites/test/test-storybook-angular-material/src/app/material/mat-button.stories.ts
ERROR in /Users/ifthenelse/Sites/test/test-storybook-angular-material/src/app/material/mat-button.stories.ts(3,22):
TS2307: Cannot find module '../notes/mat-button-basic.md'.
```

Am I missing something?

**Comment by hipstersmoothie** [comment]
For me the errors go away if i switch the extension from 'stories.tsx' to just 'tsx'

**Comment by haldunanil** [comment]
Is using `.story.tsx` considered a reliable workaround? I basically want to know if this will continue to work down the road if I change all my existing `stories.tsx` files to `story.tsx`.

**Comment by hipstersmoothie** [comment]
@haldunanil this is exactly what i found too. If you have exclude the stories in your tsconfig, typescript will ignore your typings for those files. 

Thanks for the .npmignore tip!

**Comment by BobbyLH** [comment]
![image](https://user-images.githubusercontent.com/25814873/61440787-e5507080-a976-11e9-9f86-44eb1a952ae2.png)
Try adding `.md` in extension field at `.stroybook/webpack.config.js`

**Comment by guikeller** [comment]
An alternative solution for it - at the root of the project:
`npm i marked`

On your story - Import the MD file and 'marked' as following:
```ts
import * as marked from 'marked';
const componentNotes = require('./1-HeroSearch.stories.md').default;
```
Use 'marked' to read/parse for you and display as markdown:
```ts
    {
      notes: {
        markdown: marked(componentNotes)
      }
    }
```
Ta-da it works! :smiley: 
Good luck :+1:

**Comment by Rynxiao** [comment]
in CRA with typescript, can support markdown by editing react-app-dev.d.ts, add the declaration

```typescript
declare module '*.md' {
  const value: string;
  export default value;
}
```

and in your component

```typescript
import tReadme from '../readme.md';
```

**Comment by urswiss** [comment]
> For me the errors go away if i switch the extension from 'stories.tsx' to just 'tsx'
> 
> edit: actually any other extension that 'stories.tsx' works, even 'story.tsx'

seemed like an easy fix, but the error re-appears later on unfortunately

**Comment by imagine-design-system** [comment]
create global.d.ts at the root level and add the single line of code below.
 
declare module '*.md';
