### ISSUE TITLE
Storybook custom webpack loading empty scss objects

### ISSUE THREAD

**Issue by reggi** [storybooks/storybook#2892]
Also posted on [Stackoverflow](https://stackoverflow.com/questions/48551520/storybook-custom-webpack-loading-empty-scss-objects#).

I added a custom **webpack.config.js** file to my `.storybook` project so that I can import `.scss` files. This is what I added, straight from the storybook docs.

    const path = require('path');
    
    // Export a function. Accept the base config as the only param.
    module.exports = (storybookBaseConfig, configType) => {
      // configType has a value of 'DEVELOPMENT' or 'PRODUCTION'
      // You can change the configuration based on that.
      // 'PRODUCTION' is used when building the static version of storybook.
    
      // Make whatever fine-grained changes you need
      storybookBaseConfig.module.rules.push({
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"],
        include: path.resolve(__dirname, '../src')
      });
    
      // Return the altered config
      return storybookBaseConfig;
    };

Here's my story:

    import React from 'react';
    import { storiesOf } from '@storybook/react'; // eslint-disable-line import/no-extraneous-dependencies
    import { action } from '@storybook/addon-actions'; // eslint-disable-line import/no-extraneous-dependencies
    import { linkTo } from '@storybook/addon-links'; // eslint-disable-line import/no-extraneous-dependencies
    import Button from './'
    import ButtonStyles from './index.scss'
    import ButtonCompareTrayStyles from './compare-tray.scss'
    import ButtonCompareRemminderStyles from './compare-reminder.scss'
    
    console.log({ButtonStyles, ButtonCompareTrayStyles, ButtonCompareRemminderStyles})
    
    storiesOf('Button', module)
      .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
      .add('with some emoji', () => <Button onClick={action('clicked')}>😀 😎 👍 💯</Button>)
      .add('with default styles', () => <Button styles={ButtonStyles} onClick={action('clicked')}>Hello World</Button>)
      .add('with CompareTray styles', () => <Button styles={ButtonCompareTrayStyles} onClick={action('clicked')}>Hello World</Button>)
      .add('with CompareRemminder styles', () => <Button styles={ButtonCompareRemminderStyles} onClick={action('clicked')}>Hello World</Button>)

When I log some Button styles, it appears that each one of these objects is empty.

[![enter image description here][1]][1]

Why are these objects empty? How can I get scss working with storybook?

  [1]: https://i.stack.imgur.com/CQv2f.png

**Comment by Hypnosphi** [comment]
To use CSS modules, you need to [enable](https://github.com/webpack-contrib/css-loader#modules) them in css-loader:

```
loaders: ["style-loader", "css-loader?modules", "sass-loader"],
```

**Comment by igor-dv** [comment]
I assume it's resolved.
