### ISSUE TITLE
Running functions conditionally based on the story displayed.

### ISSUE THREAD

**Issue by joscha** [storybooks/storybook#290]
I am currently trying to integrate https://github.com/mrdoob/stats.js in order to add a `addMonitored` method that would allow specifying a performance monitored story like this:

``` javascript
storiesOf('something', module)
  .addMonitored('a component with monitored performance', () => (
    <Component />
  ), () => Math.random());
```

I tried like this:

``` javascript
setAddon({
  addMonitored(storyName, storyFn, rafFn) {
    this.add(storyName, (context) => {
      const stats = new Stats();
      stats.showPanel( 0 ); // 0: fps, 1: ms, 2: mb, 3+: custom
      document.getElementById('root').appendChild(stats.dom);
      function animate() {
        stats.begin();
        rafFn();
        stats.end();
        requestAnimationFrame(animate);
      }
      requestAnimationFrame(animate);
      return storyFn(context);
    });
  }
});
```

It kinda works:
![react_storybook](https://cloud.githubusercontent.com/assets/188038/16516150/9ddda238-3fb9-11e6-9723-dc5b0462f7c9.png)

however there are some flaws in that - the function passed to `this.add` gets called immediately and not only when that particular story is shown, hence the stats window is always visible. Also, the requestAnimationFrame is kicked off immediately. Potentially this could be done by wrapping `storyFn(context)` with a component that starts the stats on mount, but I am not sure how to achieve this. Any pointers?

**Comment by arunoda** [comment]
Yes you are correct, `this.add` called immediately. Here's you need to provide a React element. Inside that, render the perfTool, when mounted.

**Comment by arunoda** [comment]
Here's an example: https://github.com/kadirahq/react-storybook-addon-info/blob/master/src/index.js

**Comment by joscha** [comment]
Thank you for your help @arunoda - I successfully created an example here: https://gist.github.com/joscha/9e1d4eea6fddd50df25012d704180aa1

**Comment by arunoda** [comment]
Okay. We are good here right :)
Publish this into NPM and send me a PR to here - https://github.com/kadirahq/react-storybook/blob/master/docs/extensions.md#available-extensions

**Comment by ndelangen** [comment]
Did this ever make it into Storybook @joscha ?
Doesn't look like an open issue to me, if it's been open for over a year.

**Comment by joscha** [comment]
@ndelangen the linked example was sufficient, so closing it is fine! 👍
