### ISSUE TITLE
Allow use of npm instead of yarn (e.g. --use-npm flag)

### ISSUE THREAD

**Issue by kroeder** [storybooks/storybook#2904]
### Issue details

I am behind a proxy and can't use yarn. Please introduce a way to use npm instead of `yarn install` when fireing `getstorybook`

### Steps to reproduce

Call `getstorybook`

### Please specify which version of Storybook and optionally any affected addons that you're running

Storybook for Angular

### Affected platforms 

Environments that depend on npm instead of yarn

### Screenshots / Screencast / Code Snippets (Optional)

```
$ getstorybook

 getstorybook - the simplest way to add a storybook to your project. 

 • Detecting project type. ✓
 • Adding storybook support to your "Angular" app. ✓
 • Preparing to install dependencies. ✓

yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "tslib" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by Hypnosphi** [comment]
Well we actually have this flag:

```sh
$ getstorybook -h

  Usage: getstorybook [options]


  Options:

    -V, --version                         output the version number
    -f --force                            Forcely add storybook
    -N --use-npm                          Use npm to install deps
    -p --parser <babel | babylon | flow>  jscodeshift parser
    -h, --help                            output usage information
```

**Comment by Grsmto** [comment]
Hey,
So `getstorybook` uses Yarn but once you want to install an addon, the doc says to use npm: `npm i --save-dev @storybook/addons @storybook/addon-actions @storybook/addon-links @storybook/addon-notes` for example on the `Using addons` section.
This mix of Yarn and npm literally makes Create React App not work anymore (ie you can't `npm start` without a crash).

**Comment by Hypnosphi** [comment]
You definitely can use yarn to install any dependencies you want, the choice is only yours
