### ISSUE TITLE
Trigger knobs in fullscreen

### ISSUE THREAD

**Issue by ruxiang05** [storybooks/storybook#2905]
**I'm sorry this is not a proper issue**

Is there a way to trigger knobs in fullscreen (not changing the URL as this triggers a page reload)? I need to test on mobile.

**Comment by Hypnosphi** [comment]
I think the best you can do for now is to hide stories navigation panel (`stories=false` in URL) instead of using fullscreen

**Comment by Hypnosphi** [comment]
#3337 should help

**Comment by Hypnosphi** [comment]
Please try `4.0.0-alpha.3`, it hides stories panel on mobile by default
