### ISSUE TITLE
Lodash module not found error

### ISSUE THREAD

**Issue by marioharper** [storybooks/storybook#2909]
### Issue details

Attempting to setup storybook with React Native. I followed the steps for setting up and when I run 
`npm run storybook` I receive several errors in `./node_modules/velocity-react/velocity-transition-group.js` in the following form.

```
ERROR in ./node_modules/velocity-react/velocity-transition-group.js
Module not found: Error: Can't resolve 'lodash/collection/each' in '/Users/<username>/Source/<projectname>/node_modules/velocity-react'
```

### Steps to reproduce

On an ejected CRNA app run:
```
$ npm -g i @storybook/cli
$ getstorybook
$ npm run storybook
```

**_Expected_**: Opening http://localhost:7007 would load the storybook UI. 
**_Actual_**: Errors in console (outlined above) and no UI loading. 

### Please specify which version of Storybook and optionally any affected addons that you're running
 -   storybook/react-native@3.3.11
 -   storybook/addon-actions@3.3.11
 -   storybook/addon-links@3.3.11
 -   storybook/addons@3.3.11

### Affected platforms 
- macOS Sierra 10.12.6
- node@8.4.0
- npm@5.3.0

I found this related issue https://github.com/storybooks/storybook/issues/2357. But I did not add a custom webpack config, so i'm not sure if it's related. 

```
ERROR in ./node_modules/velocity-react/velocity-transition-group.js
Module not found: Error: Can't resolve 'lodash/collection/each' in '/Users/<username>/Source/<projectname>/node_modules/velocity-react'
 @ ./node_modules/velocity-react/velocity-transition-group.js 54:8-41
 @ ./node_modules/velocity-react/index.js
 @ ./node_modules/react-treebeard/lib/components/decorators.js
 @ ./node_modules/react-treebeard/lib/index.js
 @ ./node_modules/react-treebeard/index.js
 @ ./node_modules/@storybook/ui/dist/modules/ui/components/stories_panel/stories_tree/index.js
 @ ./node_modules/@storybook/ui/dist/modules/ui/components/stories_panel/index.js
 @ ./node_modules/@storybook/ui/dist/modules/ui/containers/stories_panel.js
 @ ./node_modules/@storybook/ui/dist/modules/ui/routes.js
 @ ./node_modules/@storybook/ui/dist/modules/ui/index.js
 @ ./node_modules/@storybook/ui/dist/index.js
 @ ./node_modules/@storybook/react-native/dist/manager/index.js
 @ multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js
```

**Comment by elijahmurray** [comment]
Same issue, and also get the error with another module, `react-modal`. I've tried deleting my `node_modules`, manually uninstalling and reinstalling the packages, and several other things with no luck.

**Comment by tryfonkov** [comment]
As a temporary solution - `npm i lodash`.
This will create `node_modules` in the `velocity-react` package directory.

**Comment by marioharper** [comment]
Retried this and Storybook UI loads properly at http://localhost:7007 . 

```
    "@storybook/react-native": "^3.3.14",
    "@storybook/addon-actions": "^3.3.14",
    "@storybook/addon-links": "^3.3.14",
    "@storybook/addons": "^3.3.14",
```
