### ISSUE TITLE
Suggestion: use react-markings for add-on notes

### ISSUE THREAD

**Issue by tsiq-swyx** [storybooks/storybook#2916]
hello, loving Storybook so far!

I want to use the Notes add on to display code alongside my notes (aka without importing from a separate `.md` file) but this involves the use of backticks. If I were to do this in a template literal that would fail, and `withNotes` currently doesn't support github flavored markdown (which has tilde versions of the backticks for this purpose). so for example this doesnt render as a code block:

```js
storiesOf('Notes', module)
  .addWithJSX(
    'with a WithService wrapper',
    withNotes(`
This demonstrates usage of Notes together with a WithService HOC (that uses a child render prop)

~~~js
<WithService service={exampleService}>
  {(itemList, onChange) => <Notes items={itemList} onChange={onChange} />}
</WithService>
~~~
    `)(() => (
      <WithService service={exampleService}>
        {(itemList, onChange) => <Notes items={itemList} onChange={onChange} />}
      </WithService>
    ))
  );
```

beacuse the ~ tildes are not recognized.

This is because we dont really do much processing in the [Notes addon source](https://github.com/storybooks/storybook/blob/master/addons/notes/src/register.js). I would like to propose using [react-markings](https://github.com/Thinkmill/react-markings) to add a richer inline markdown experience to the Notes addon.

Happy to do a PR for this but is this something that you'd like?

**Comment by Hypnosphi** [comment]
Does it mean an API change?

**Comment by tsiq-swyx** [comment]
No, API does not change. it just allows us to use github flavored markdown instead of "just" markdown. does that make sense?

I prefer addon notes as it doesnt involve a confusing shift to click that top right blue thing (as you do in addon-info) - it just lacks this one thing :)

**Comment by Hypnosphi** [comment]
Does “just” markdown currently work in addon-notes without using an `.md` file?

**Comment by Hypnosphi** [comment]
> I prefer addon notes

That's OK, my point was that it would make sence either to use marksy in notes as well, or move info to react-markings

**Comment by tsiq-swyx** [comment]
> Does “just” markdown currently work in addon-notes without using an .md file?

not sure. in any case it doesnt let me use github markdown

> That's OK, my point was that it would make sence either to use marksy in notes as well, or move info to react-markings

ok so you prefer marksy? i dont know marksy at all but whatever it is i would love to have github flavored markdown in addon-notes

**Comment by Hypnosphi** [comment]
We kinda maintain it, so yes =)
https://github.com/storybooks/marksy

**Comment by tsiq-swyx** [comment]
hey Hypnosphi!

so i finally had time to look at the code.

i think instead of using marksy i could just directly use `marked`. so i just put this in `addons/notes/src/index.js`:

```js
import marked from 'marked';


export const withNotesGfm = text => { // dont conflict with withNotes for now
  const channel = addons.getChannel();

  return getStory => context => {
    // send the notes to the channel before the story is rendered
    channel.emit('storybook/notes/add_notes', marked(text));
    return getStory(context);
  };
};
```

what do you think about that? would be pretty simple.

the usage would look like this:

```js
storiesOf('Notes', module)
  .addWithJSX(
    'with a WithService wrapper',
    withNotesGfm(`
This demonstrates usage of Notes together with a WithService HOC (that uses a child render prop)

~~~js
<WithService service={exampleService}>
  {(itemList, onChange) => <Notes items={itemList} onChange={onChange} />}
</WithService>
~~~
    `)(() => (
      <WithService service={exampleService}>
        {(itemList, onChange) => <Notes items={itemList} onChange={onChange} />}
      </WithService>
    ))
  );
```

and this would render with the codeblock like a github flavored markdown would.

**Comment by Hypnosphi** [comment]
given that notes understand html, this looks like the way to go

`withMarkdownNotes` maybe?

**Comment by tsiq-swyx** [comment]
done :)
