### ISSUE TITLE
Question about Info Addon: What If I use Typescript instead of prop-types?

### ISSUE THREAD

**Issue by tsiq-swyx** [storybooks/storybook#2917]
currently the Info Addon shows blank in the prop types section (which annoyingly can't be disabled...) but I use Typescript so this is kinda moot. I think Typescript has a bigger market share than prop-types now so it would be interesting to have an option to show typescript types instead of prop-types. This is probably above my typescript skill level right now but would appreciate a discussion on this (or a pointer in case this has been discussed before).

thanks!

**Comment by Hypnosphi** [comment]
Looks related to #1519

**Comment by tsiq-swyx** [comment]
ah yes. happy to close my issue and just watch that.
