### ISSUE TITLE
Proxy config compatibility with Create React App

### ISSUE THREAD

**Issue by chrbala** [storybooks/storybook#2921]
### Issue details

The proxy feature in Create React App should be supported by default for feature parity. This is a follow-up to https://github.com/storybooks/storybook/issues/208#issuecomment-354938784

### Steps to reproduce

The proxy config is stored in package.json and is passed along to Create React App. This config should be consumed in Storybook as well. This can be done with the following code in the userland middleware.js file:
```javascript
const proxy = require('http-proxy-middleware');

const { proxy: proxyConfigs } = require('../package.json');

module.exports = router =>
  Object.keys(proxyConfigs).forEach(key =>
    router.use(key, proxy(proxyConfigs[key]))
  );
``` 

### Please specify which version of Storybook and optionally any affected addons that you're running

@storybook/react ^3.2.14

### Affected platforms 

This is a feature request and affects all platforms

**Comment by swillis12** [comment]
@chrbala as a heads up this does not work when specifying the proxy [from create-react-app docs](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development) as follows in the package.json:
`"proxy": "http://localhost:8080"`

**Comment by chrbala** [comment]
Ah, you're right, that wouldn't work, and would likely be the most common case.

**Comment by swillis12** [comment]
This is extremely useful and I'll be using it in the mean time but it would be cool to find a way to support this "simple" config too ( only if CRA continues to support it too :) ). Thanks for providing this 👍

**Comment by chrbala** [comment]
There should be a fairly straightforward mapping from the simple config to the complex one, but offhand I'm not sure what it would be. Please add a note to this thread if you figure it out!

**Comment by swillis12** [comment]
I think something like this will work:

```
const proxy = require('http-proxy-middleware');

const { proxy: proxyConfigs } = require('../package.json');

module.exports = router => {
    if(typeof proxyConfigs === 'string')
        router.use(proxy('/', { target: proxyConfigs }));
    else
        Object.keys(proxyConfigs).forEach( key => router.use(key, proxy(proxyConfigs[key])) );
}
```
