### ISSUE TITLE
Error: read ECONNRESET on react-native when i refresh storybook-native browser tab with react-native 0.53

### ISSUE THREAD

**Issue by macrozone** [storybooks/storybook#2923]
### Issue details

refreshing browser window crashes storybook-native with latest storybook version and react-native 0.53

### Steps to reproduce

- start storybook `storybook start -p 7007`
- open app on device
- open chrome tab on localhost:7007
- refresh that tab with cmd+r
- storybook will crash with "Error: read ECONNRESET"

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react-native": "^3.3.12"
- react-native: 0.53.0

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
error Command failed with exit code 1.
```

**Comment by axelnormand** [comment]
Same here and I can't figure out what's causing it.
Something hot reload?

**Comment by sabbox** [comment]
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.8.1
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

same thing

**Comment by nikhedonia** [comment]
I was able to work around this bug by forcing the `ws` to `3.3.2`.
I've used [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to accomplish this.

**Comment by axelnormand** [comment]
Many thanks @nikhedonia the ws downgrade seems to have worked a treat for me.
Also thanks for the link to the underlying issue documenting the change in ws error behaviour in 3.3.3

**Comment by Hypnosphi** [comment]
Released [3.3.14](https://github.com/storybooks/storybook/releases/tag/v3.3.14)

@axelnormand you remove the downgrade now

**Comment by nikhedonia** [comment]
Thank you guys! 
I can confirm it works for us in https://github.com/newsuk/times-components.

**Comment by axelnormand** [comment]
works great. Many thanks @Hypnosphi !
