### ISSUE TITLE
TypeError: Cannot read property 'Component' of undefined (React is undefined)

### ISSUE THREAD

**Issue by oldwin** [storybooks/storybook#2925]
Storybook can not import React in Jest/Storyshot environment inside addon-knobs/src/react

When I run 'yarn test' it returns me an error

> TypeError: Cannot read property 'Component' of undefined

I found the problem in node_modules/_storybook/addon-knobs/src/react/WrapStory.js
in "import React from 'react'" line

React is undefined there.
Maybe it's some kind of circular dependencies, but everyhing is ok in general Storybook. Problem only with Storyshot and Jest.

```

    "@storybook/addon-actions": "3.3.12",
    "@storybook/addon-knobs": "3.3.12",
    "@storybook/addon-links": "3.3.12",
    "@storybook/addon-storyshots": "3.3.12",
    "@storybook/addons": "3.3.12",
    "@storybook/react": "3.3.12",
    "babel-jest": "22.1.0",
    "jest": "22.1.4",

    "react-test-renderer": "15.6.2"
    "react": "15.6.2",
    "react-dom": "15.6.2",
```

I didn't have this error with storybook 3.2.12

Another thing I have to add

```
    "transformIgnorePatterns": [
      "node_modules/(?!@storybook/addon-knobs/src/react/)"
    ],
```

to Jest config, because without it
```
    /Users/oldwin/www/bookingbricks/node_modules/@storybook/addon-knobs/src/react/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
```

The problem only inside storybook/addon-knobs/src/react as I understand.

**Comment by Hypnosphi** [comment]
I wonder why do it imports from `src` not `dist`

**Comment by oldwin** [comment]
@Hypnosphi 
I have the next error trace:

```
      at Object.<anonymous> (node_modules/@storybook/addon-knobs/src/react/WrapStory.js:72:45)
      at Object.<anonymous> (node_modules/@storybook/addon-knobs/src/react/index.js:41:219)
      at Object.<anonymous> (node_modules/@storybook/addon-knobs/dist/react/index.js:10:14)
      at Object.<anonymous> (node_modules/@storybook/addon-knobs/dist/index.js:22:14)
      at Object.<anonymous> (src/components/bookingForm/__stories__/BookingInfo.stories.js:3:19)
```

`storybook/addon-knobs/dist/react/index.js:10:14` line is `var _react = require('react');`

Seems like this line includes `storybook/addon-knobs/src/react/index.js` not React.
Any ideas why?

**src/components/bookingForm/__stories__/BookingInfo.stories.js**
```
import React from 'react';
import { storiesOf } from '@storybook/react';
import { date, number, text, withKnobs } from '@storybook/addon-knobs';
import IntlProvider from '../../../i18n/IntlProvider';
import BookingInfo from '../BookingInfo';

const now = new Date();

storiesOf('bookingForm', module)
  .addDecorator(withKnobs)
  .addDecorator(getStory => (
    <IntlProvider>
      <div id="dashboard-container">
        <div className="booking-block">
          <div className="booking-block-info">
            {getStory()}
          </div>
        </div>
      </div>
    </IntlProvider>
  ))
  .add('BookingInfo', () => (
    <BookingInfo
      checkIn={date('check_in', now)}
      checkOut={date('check_out', now)}
      numberOfGuests={number('number_of_guests', 3)}
      cancellationPolicy={text('cancellationPolicy', 'Cancellation policy')}
      cleaningPolicy={text('cleaning_policy', 'cleaning policy')}
      totalPrice={number('total_price', 1000)}
      additionalInformation={text('additional_information', 'Additional Info')}
    />
  ));

```

**Comment by oldwin** [comment]
Without knobs everything is working perfect with Jest/Storyshot
```

import React from 'react';
import { storiesOf } from '@storybook/react';

const Test = () => <div>Test</div>;

storiesOf('bookingForm', module)
  .add('BookingInfo', () => (
    <Test />
  ));
```

**Comment by Hypnosphi** [comment]
How does your custom webpack config look like?

**Comment by oldwin** [comment]
It includes some main development config rules, but to test I just changed it to an empty standard config

**.storybook/webpack.config.js**
`module.exports = {};`

And got exactly the same error.

**Comment by oldwin** [comment]
If I manually change

`var _react = require('react');` to `var _react = require('../../../../react');`

in `addon-knobs/dist/react/index.js` and `addon-knobs/dist/react/WrapStory.js`

Everything working good. But why the problem only inside this folder and only with react import. Maybe because folder's name is 'react' also...

**Comment by Hypnosphi** [comment]
Can you please create a GitHub repo with minimal reproduction of your issue?
> because folder's name is 'react' also

That's probably relevant, but it shouldn't resolve to this file unless you change module resolution scheme with options like [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolve-modules)

**Comment by oldwin** [comment]
Fixed, the problem was in Jest config. It was

```
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
```

I changed it to

```
    "moduleDirectories": [
      "node_modules",
      "<rootDir>/src"
    ],
```

Everything is working good now. Seems like Jest found first 'src' inside addon-knobs directory and then 'react' inside it and import it instead React from 'node_modules'.

**Comment by himanshu309** [comment]
import { Box, Text, Heading } from '../../components/base';
import React from 'react'
export default () => (
  <div className='mobilePadding'>
    <div>
      <Heading bold is="h1" my={2}>
      
        Reviews
      
      <div id='yotpo-testimonials-custom-tab'>
  </div>
      </Heading>
      <Text mb4>We use a third party company by the name of Yotpo to send and verify all of our product and site reviews.  
      <a href="https://reviews.me/office-supplies/theelegantoffice-com/7196850" target="_blank"> Click here</a> to read more of our reviews. If you have any questions or concerns, please let us know - we're a phone call away!</Text>
    </div>
    
   
 <script dangerouslySetInnerHTML={{__html: 
  `
 (function e(){
   var e=document.createElement("script");
   e.type="text/javascript",
   e.async=!0,
    e.src="//staticw2.yotpo.com/gzLifCZ7CnkFZTx4G1LaYq2lKf3l5GCCSQy6FivI/widget.js";
    var t=document.getElementsByTagName("script")[0]; 
    t.parentNode.insertBefore(e,t)})`}} />
  

<div id='yotpo-testimonials'>
   
</div>


    
  </div>
)



Help :Urgent @oldwin @Hypnosphi @theshortcut @karl 
I need to convert this --- --   export default = () => {   
// my code goes here
} 
to
 class Reviews extends React.Component{
//
}


While doing this I'm getting error  "   
Cannot read property 'Component' of undefined
TypeError: Cannot read property 'Component' of undefined
    at Object.module.exports.Object.defineProperty.value (http://localhost:3000/_next/1542968493709/page/pages.js:118687:16)
    at __webpack_require__ (http://localhost:3000/_next/1542968493709/manifest.js:714:31)
    at fn (http://localhost:3000/_next/1542968493709/manifest.js:117:20)
    at Object.module.exports.Object.defineProperty.value (http://localhost:3000/_next/1542968493709/page/pages.js:118173:16)
    at __webpack_require__ (http://localhost:3000/_next/1542968493709/manifest.js:714:31)
    at fn (http://localhost:3000/_next/1542968493709/manifest.js:117:20)
    at Object.<anonymous> (http://localhost:3000/_next/1542968493709/page/pages.js:117842:20)
    at Object.module.exports.Object.defineProperty.value (http://localhost:3000/_next/1542968493709/page/pages.js:118133:30)
    at __webpack_require__ (http://localhost:3000/_next/1542968493709/manifest.js:714:31)
    at fn (http://localhost:3000/_next/1542968493709/manifest.js:117:20)

**Comment by himanshu309** [comment]
> Without knobs everything is working perfect with Jest/Storyshot
> 
> ```
> 
> import React from 'react';
> import { storiesOf } from '@storybook/react';
> 
> const Test = () => <div>Test</div>;
> 
> storiesOf('bookingForm', module)
>   .add('BookingInfo', () => (
>     <Test />
>   ));
> ```

Hello , I just need  to convert the code same as above into class Something extends React.Component{
//
}


plz help me
