### ISSUE TITLE
When i using the Nuxt.js, how to attachment `router-link`?

### ISSUE THREAD

**Issue by jicjjang** [storybooks/storybook#2934]
### Issue details

When i using the Nuxt.js, how to attachment `router-link` or `nuxt-link`?

### Steps to reproduce

Nuxt router is not showing routes file on dev mode.
how to set the `vue-router > router-link` or `nuxt-link`?

I wrote below codes. but, displayed "TypeError: Cannot read property 'resolve' of undefined" message.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue@3.3.12

### Screenshots / Screencast / Code Snippets (Optional)

```js
import VueRouter  from 'vue-router';
Vue.use(VueRouter);

import NuxtLink from 'nuxt/lib/app/components/nuxt-link';
Vue.component('nuxt-link', NuxtLink);
```

**Comment by adi-zz** [comment]
Just as a workaround you may try something like this:

```
import {action} from '@storybook/addon-actions'
// import VueRouter  from 'vue-router' - not needed
// import NuxtLink from 'nuxt/lib/app/components/nuxt-link' - not needed

Vue.component('RouterLink', {
  props:   ['to'],
  methods: {
    log() {
      action('link target')(this.to)
    },
  },
  template: '<div @click="log()"><slot>RouterLink</slot></div>',
})

Vue.component('NuxtLink', {
  props:   ['to'],
  methods: {
    log() {
      action('link target')(this.to)
    },
  },
  template: '<div @click="log()"><slot>NuxtLink</slot></div>',
})
```
(`action` is used so that you can see a [log in Storybook](https://github.com/storybooks/storybook/tree/master/addons/actions))
