### ISSUE TITLE
Add storyshots watch compatability for jest --watch and wallaby

### ISSUE THREAD

**Issue by axelnormand** [storybooks/storybook#2936]
### Issue details

As per #2259, with storyshots there is one `storyshots.test.js` file so every time i change a story file, `jest --watch` or wallaby re-runs all the stories which is a bit slow.

Is there a way to correctly setup multiple jest tests, one per story file so the dependency chain is correct?
Happy to submit a PR but thought someone might have some ideas how I'd approach this?

Many thanks

Here is my `storyshots.test.ts` file where i'm using react native, typescript and prefer multiple snapshot files generated using enzyme shallow.

```
import initStoryshots, {
  getSnapshotFileName,
} from '@storybook/addon-storyshots';
import { shallow } from 'enzyme';
import toJson from 'enzyme-to-json';
import path from 'path';

//
// initialise storyshots
// https://github.com/storybooks/storybook/tree/master/addons/storyshots
//

// fix _global import in storyshots code to be jest global including describe method
jest.mock('global', () => global);

initStoryshots({
  framework: 'react-native',
  configPath: path.join(__dirname, 'storybook.config.js'),
  test: ({ story, context }: { story: any; context: any }) => {
    // do multi file snapshots with shallow not mount as nicer to compare for humans
    const snapshotFileName = getSnapshotFileName(context);
    const storyElement = story.render(context);
    const shallowTree = shallow(storyElement);

    if (snapshotFileName) {
      // @ts-ignore toMatchSpecificSnapshot added by storyshots
      expect(toJson(shallowTree)).toMatchSpecificSnapshot(snapshotFileName);
    }
  },
});
```

and my `storyshots.config.js` which just loads the stories dynamically generated to `storyLoader.js` using `react-native-storybook-loader` (https://github.com/elderfo/react-native-storybook-loader)

```
import { configure } from '@storybook/react-native';
import { loadStories } from './storyLoader';

//
// Loads the generated stories for Storybook.tsx and storyshots.test.ts
//

configure(() => {
  loadStories();
}, module);
```

**Comment by Hypnosphi** [comment]
cc @igor-dv

**Comment by igor-dv** [comment]
I'll try to take a look at it next week.

**Comment by igor-dv** [comment]
As you can imagine I failed to take a look. Hope will get to it soon

**Comment by arntj** [comment]
I have a related problem. If I have setup a precommit hook with jest, and I create a file, say:
`thingamabob.tsx`
and a corresponding story file:
`thingamabob.stories.tsx`
then if I change `thingamabob.tsx` then jest won't detect that the tests related to the stories related to that file should update. This happens even if I create a `thingamabob.test.tsx` to setup stories that would be in the same context as `thingamabob.tsx`.

**Comment by igor-dv** [comment]
I assume that these all are related also to #3483.

**Comment by igor-dv** [comment]
@thomasbertet added a fix to the `jest-specific-snapshot` that is published as v1.0.0. I assume it will be adopted here soon

**Comment by joycollector** [comment]
@igor-dv Hi, thanks for your great work. Are there any updates on this?

**Comment by igor-dv** [comment]
The change was not adopted here yet

**Comment by igor-dv** [comment]
It was released.

**Comment by axelnormand** [comment]
for any future people finding this thread, i actually ended up writing a little script to run in the `prestorybook` target that generates one `.test.ts` file per `.story.tsx` file. Watching then works no problem and you can check in that new `.test.ts` file to git.

I wrote up how i did it here: https://codeburst.io/react-native-storybook-generating-individual-test-files-to-snapshot-bdbda32625ce
