### ISSUE TITLE
react-native: HMR leads to "possible EventEmmitter memory leak"

### ISSUE THREAD

**Issue by macrozone** [storybooks/storybook#2942]
This is a problem that has been around for quite some versions and it still happens with 3.3.12.

After some hot reloading, I get this error:

```
(node) warning: possible EventEmitter memory leak detected
```

i am not sure if this affects storybook, but since HMR is extremly unrelyiable on react-native i think that this has something todo with it.

**Comment by iainheng** [comment]
I am having this issue on Windows 10 machine. I can see the memory quickly stacked up in my Task Manager when Hot Reloading is turned on in Android emulator.
