### ISSUE TITLE
Vue use 'addon-knobs' throw Error

### ISSUE THREAD

**Issue by iswear1987** [storybooks/storybook#2949]
### Issue details

I just want add `@storybook/addon-knobs/vue` to storybook, but it not work, could you tell me how to use 'addon-knobs' for vue components please，thanks

It throw
```
Uncaught TypeError: Cannot read property 'emit' of undefined
at KnobManager.js:92
```

### Steps to reproduce

```javascript
// .storybook/addons.js

import '@storybook/addon-actions/register';
import '@storybook/addon-notes/register';
import '@storybook/addon-knobs/register';

```

```javascript
// src/stories/index.js

import {storiesOf} from '@storybook/vue';
import { withKnobs, number } from '@storybook/addon-knobs/vue';
// ...
const stories = storiesOf('Storybook Knobs', module);
stories.addDecorator(withKnobs);
// ...
storiesOf('path/to/Component', module)
    .add('componentName', () => {
        const highlightTagId = number('highlightTagId', 64)
        // ...
    })
```

### Storybook and other modules version

- `@storybook/vue@3.3.12`
- `@storybook/addons@3.3.12`
- `vue@2.5.13`

### Affected platforms 

- OS: fedora 27
- Browser: chrome 64.0.3282.140 (64bit)

### Screenshots

![image](https://user-images.githubusercontent.com/7732965/36015746-e622aa00-0daa-11e8-973d-38494dfc193f.png)

![image](https://user-images.githubusercontent.com/7732965/36015793-0bb47ef6-0dab-11e8-9abb-950074ebaa50.png)

![image](https://user-images.githubusercontent.com/7732965/36016104-76e96c3a-0dac-11e8-93a2-7dd57b4e9b42.png)

**Comment by Flui** [comment]
Here you created two stories. But you missed to add the Knobs decorator to the second story.
```javascript
// src/stories/index.js

import {storiesOf} from '@storybook/vue';
import { withKnobs, number } from '@storybook/addon-knobs/vue';
// ...
// first story (this is an empty story)
const stories = storiesOf('Storybook Knobs', module);
stories.addDecorator(withKnobs);
// ...
// second story
storiesOf('path/to/Component', module)
    .addDecorator(withKnobs) // TODO: this line should fix your error
    .add('componentName', () => {
        const highlightTagId = number('highlightTagId', 64)
        // ...
    })
```

**Comment by iswear1987** [comment]
@Flui thanks Flui, that did it :)
