### ISSUE TITLE
[help wanted] generate storyshot with jest has import error

### ISSUE THREAD

**Issue by maple-leaf** [storybooks/storybook#2954]
when I use jest to generate storyshot, `SyntaxError: Unexpected token import` error occur.

```
 FAIL  src/components/logo/logo.storyshot.spec.ts
  ● Test suite failed to run

    projects/real-world-with-react-phoenix-psql/web/src/components/logo/logo.story.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'react';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
      at node_modules/@storybook/addon-storyshots/dist/require_context.js:39:24
          at Array.forEach (<anonymous>)
      at requireModules (node_modules/@storybook/addon-storyshots/dist/require_context.js:34:9)
      at node_modules/@storybook/addon-storyshots/dist/require_context.js:48:7
 
```

package.json

```json
{
  "name": "typescript-webpack-jest-boilerplate",
  "version": "0.0.1",
  "description": "typescript webpack jest boilerplate",
  "main": "src/index.ts",
  "directories": {
    "test": "test"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.3.12",
    "@storybook/addon-links": "^3.3.12",
    "@storybook/addon-storyshots": "^3.3.12",
    "@storybook/addons": "^3.3.12",
    "@storybook/react": "^3.3.12",
    "@types/jest": "^21.1.9",
    "awesome-typescript-loader": "^3.4.1",
    "babel-core": "^6.26.0",
    "babel-jest": "^22.0.4",
    "clean-webpack-plugin": "^0.1.17",
    "html-webpack-plugin": "^2.30.1",
    "jest": "^22.0.3",
    "jest-extended": "^0.5.0",
    "jsdom": "^11.5.1",
    "react-test-renderer": "^16.2.0",
    "source-map-loader": "^0.2.3",
    "ts-jest": "^22.0.0",
    "typescript": "^2.6.2",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7"
  },
  "scripts": {
    "test": "jest",
    "dev": "webpack-dev-server --open --config=./builds/webpack.dev.js",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "transform": {
      "^.+\\.(ts|tsx|js)$": "ts-jest"
    },
    "testMatch": [
      "<rootDir>/**/*.spec.(ts|tsx)"
    ],
    "setupTestFrameworkScriptFile": "jest-extended",
    "globals": {
      "document": true
    }
  },
  "keywords": [
    "typescript",
    "webpack",
    "jest"
  ],
  "author": "maple-leaf",
  "license": "MIT",
  "dependencies": {
    "@types/react": "^16.0.36",
    "@types/react-dom": "^16.0.3",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router": "^4.2.0"
  }
}
```

Demo repo: [https://github.com/maple-leaf/real-world-with-react-phoenix-psql/tree/storyshot-issue](https://github.com/maple-leaf/real-world-with-react-phoenix-psql/tree/storyshot-issue)

steps to reproduce:
- clone repo
- cd web
- npm i
- npm run test

By the way,`npm run storybook` and `npm run dev` all runs well while test fail.

**Comment by Hypnosphi** [comment]
You should be able to write your stories in typescript. Alternatively, you can add this to `jest.transform`:
```
"^.+\\.js$": "babel-jest"`
```
[See _Note_](https://facebook.github.io/jest/docs/en/configuration.html#transform-object-string-string)

**Comment by maple-leaf** [comment]
@Hypnosphi I change all stories with typescript. `Import` error gone, but stories is empty.

Result of `npm run test`

![image](https://user-images.githubusercontent.com/3980995/36062637-3a9e42d2-0eab-11e8-9d9b-7ae9ebc5a60f.png)

And `npm run story` will end up with no stories too.

**Comment by igor-dv** [comment]
Did you change the imports in config.js too?

**Comment by maple-leaf** [comment]
finally, got everything works. Here's what I can:
- use typescript to write story, and use `tsx`, nor `ts`
- place story in `src`. 
      An `--jsx flag not set` error will raise if place in `stories` folder, even I add `stories/**/*.(ts|tsx)` in `tsconfig.json`, which is wired that `dev` works well. Don't know why, If anyone has clues, please tell me.
- set `"moduleResolution": "node",` to make `import xxx from @storybook/xxx` works
- set `"noImplicitAny": false` if you want get ride of declaration error.
     This seems not a good solution for new project, which should add `@types` by myself to make `storybook` be a friend to `typescript`, but I thinks this should be done by `storybook` itself.

**Comment by maple-leaf** [comment]
I just find `@types` of `storybook` for `typescript`.

```
npm install --save-dev @types/storybook__react
npm install --save-dev @types/storybook__addon-actions
```

So now change `"noImplicitAny": false` to `"noImplicitAny": true`, everything works perfectly.

And last thanks for `storybook` team, wonderful project. 👍
