### ISSUE TITLE
Join to translation English to Indonesian 

### ISSUE THREAD

**Issue by rabooe** [storybooks/storybook#2955]
hello Mr., I am a translator, I want to translate English into Indonesian, Because majority of the population of Indonesia does not master English

**Comment by danielduan** [comment]
We would love to get Storybook localized for other languages, but at this point we don't have any plans. It's a huge task and would likely require some refactoring of UI strings as well.

**Comment by rabooe** [comment]
thank you, I will wait for that opportunity
