### ISSUE TITLE
storybook-react-native + react-native-web

### ISSUE THREAD

**Issue by soyjavi** [storybooks/storybook#2963]
### Issue details

If I use a basic native component everything works great. But I'm trying to use storybook with react-native & react-native-web and I always get:

```
can't find variable: document
```

### Steps to reproduce

Just try to create an story for a react-native-web and run storybook-react-native ... zero-issues when I'm running the same story in storybook-react.

### Please specify which version of Storybook and optionally any affected addons that you're running
```
    "@storybook/react": "^3.3.12",
    "@storybook/react-native": "^3.3.12",
```

### Screenshots / Screencast / Code Snippets (Optional)

![screen shot 2018-02-12 at 16 41 24](https://user-images.githubusercontent.com/559654/36090803-46b3d64e-1014-11e8-8951-de2b7a70f00a.png)

**Comment by Hypnosphi** [comment]
Isn't react native web supposed to run in a browser? You probably need to use `@storybook/react` for web–targeted components

**Comment by Hypnosphi** [comment]
Their official storybook example uses `@storybook/react` though:

https://github.com/necolas/react-native-web/blob/0.5.1/website/package.json

**Comment by danielduan** [comment]
> "React Native for Web" brings the platform-agnostic Components and APIs of React Native to the Web.

Pretty sure it's not supposed to be for RN or else it wouldn't be calling `document`
