### ISSUE TITLE
Typescript Declartions: storybook-addon-knobs

### ISSUE THREAD

**Issue by thupi** [storybooks/storybook#2964]
### Issue details

Stroybook-Addon-knobs do already have typings. However, the documentation tells to `import {withKnobs} from '@storybook/addon-knobs/react'`. That way of importing it is not allowed using the type declartions for this package. The current typing does only allow importing it like `import {withKnobs} from '@storybook/addon-knobs'` This might be easly solved by adding a corresponding folder and declare the same typings inside that folder.

**Comment by Hypnosphi** [comment]
Hi @thupi! Would you like to open a PR?

**Comment by thupi** [comment]
Hi @Hypnosphi :-) 

I am acutally not familiar with the pull request system but one day have to be the first right :-) 

I'll give i a shot :-)

Is there any api differences between the react, vuejs version of the package or is the api the same. If that's the case i can just expose the same typings from both vue and react folders :-) ?

**Comment by Hypnosphi** [comment]
@igor-dv might know better

**Comment by igor-dv** [comment]
Actually, we do not have type declarations in the addon knobs inside the monorepo. I suppose that the current declarations are coming from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bef4d2b27db722a9e5f262d470fa3e010b0f93e3/types/storybook__addon-knobs/index.d.ts). 

I thinks @joscha did it. Maybe it worth adding them to the monorepo...

**Comment by Hypnosphi** [comment]
Oh, I've just remembered that there is an open PR on definitely typed for adding framework-specific entry points https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22939

**Comment by thupi** [comment]
@igor-dv Oh, my bad. This might be the wrong place to create this  issue. 

@Hypnosphi  Ahh, there is allready a issue regarding this :-) 

Thanks for the quick response :-) !

**Comment by joscha** [comment]
> Oh, I've just remembered that there is an open PR on definitely typed for adding framework-specific entry points DefinitelyTyped/DefinitelyTyped#22939

There is, haven't gotten around to fixing this, yet :(
