### ISSUE TITLE
Feature request: Specify delay before screenshot

### ISSUE THREAD

**Issue by seberik** [storybooks/storybook#2965]
### Issue details

Feature request: Some visual regression tests fail because the components have animations. In order to run the imageSnapshot test function I would like to be able to add a delay after .goto(url) and before page.screenshot() so that the animation has completed.

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react 3.4.0-alpha.8
- storybook/addon-storyshots 3.4.0-alpha.8

**Comment by seberik** [comment]
I added a PR: #2972

**Comment by seberik** [comment]
The PR was mdrged

**Comment by thedamon** [comment]
@seberik the delay is very useful! 
just wanted to mention we had lots of weird text rendering issues even with a delay, so we added this CSS to our stories via a url param when running screenshots and it helped remove a bunch of false-positives

```
// remove transitions
*,
*::before,
*::after {
  animation-delay: -1s !important;
  animation-duration: 0s !important;
  animation-iteration-count: 1 !important;
  background-attachment: initial !important;
  scroll-behavior: auto !important;
  transition-duration: 0s !important;
  transition: none !important;
}

// grey-out media
img,
video,
iframe {
  background: blue !important;
  filter: brightness(1) contrast(0) !important;
}

svg {
  // Force precise svg rendering to remove rendering differences
  shape-rendering: geometricPrecision !important;
}

```

**Comment by B3Kay** [comment]
How to you add that css to your css stories? @thedamon

**Comment by thedamon** [comment]
in our storybook `config.js` we have something along the lines of:

```
  let paramsString = window.location.search;
  let params = new URLSearchParams(paramsString);
  if (params.has('disableMotion')) {
    import('./disableMotion.css');
  }
```

and then tack that onto the url when passing `storybookUrl` to the storyshot test itself
