### ISSUE TITLE
Internet Explorer 10

### ISSUE THREAD

**Issue by jonnylevy** [storybooks/storybook#298]
Hi,

I have setup some stories and storybook is working fine for me locally on latest versions of Chrome and Firefox on Mac OS 10.11.3 ,however, none of my stories are showing when I try on Internet Explorer 10 on Windows 7. It also seems to be failing silently so no error messages in the console.

I've noticed that this demo is not working on ie10 either: https://kadira-samples.github.io/react-storybook-demo/

Is ie10 not supported? What is the browser support for storybook?

Thanks

**Comment by arunoda** [comment]
Yes. We have seen similar issues.
See: https://github.com/kadirahq/react-storybook/issues/213

Looking forward to do a proper fix.
@mnmtanish could you arrange proper fix plan for windows.

**Comment by bjankord** [comment]
I spent a bit of time looking at this today. From what I could find, there were 2 issues I ran into getting storybook to work in IE10. 

The first issue is that storybook uses [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware) which [requires an eventSource polyfill](https://github.com/glenjamin/webpack-hot-middleware/issues/11) for it to work in IE10. This is why when you view storybook in IE10, if you open up the dev console you'll see the following message: `webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools`

This can be resolved by npm installing [eventsource-polyfill](https://github.com/amvtek/EventSource) and requiring it in @kadira/storybook/dist/server/config/polyfills.js

```js
require('eventsource-polyfill');
```

IMO, storybook should add this to their polyfills.js file.

The second issue is related to flexbox styles not having vendor prefixes for IE. Storybook uses [@kadira/react-split-pane](https://github.com/kadirahq/react-split-pane) to create the layout used for storybook. This project uses [CSS-in-JS to style](https://github.com/kadirahq/react-split-pane/blob/master/src/Pane.js#L15-L29) the `<Pane />` and `<SplitPane />` react components. These components use some flexbox styles but don't include IE vendor prefixes with these styles. This results in the `<Pane />` and `<SplitPane />` components rendering oddly in IE10. When I was looking at the `<Pane />` component that wraps the iframe it had no visible display in IE10. This is why "none of my stories are showing when I try on Internet Explorer 10" @jonnylevy.

I tried seeing if I could add the vendor prefixed styles for flexbox to [@kadira/react-split-pane](https://github.com/kadirahq/react-split-pane) but I didn't have much luck. I tried using [postcss-js](https://github.com/postcss/postcss-js/) to create the vendor prefix but ran into issues mapping the output to react components. See [this issue for more info](https://github.com/postcss/postcss-js/issues/15). I also tried hard-coding the vendor-prefixes into storybooks src. This worked somewhat but there is some dynamic state based styling in [@kadira/react-split-pane](https://github.com/kadirahq/react-split-pane) around when it applies flexbox styling that makes the hard-coded vendor-prefixes less than ideal.

Here is a screenshot of what I got in IE10.
<img width="1438" alt="screen shot 2017-02-08 at 3 42 56 pm" src="https://cloud.githubusercontent.com/assets/633148/22759758/3a2081ca-ee19-11e6-8d5d-3e216fa424bf.png">

I'm not sure what the core contributors on storybook think of supporting IE10, but those are two places that need work to get this working in that browser.

**Comment by ndelangen** [comment]
More information here:
https://github.com/storybooks/react-storybook/issues/688#issue-206236953

**Comment by ndelangen** [comment]
If we could support, we can put it on the roadmap.

**Comment by ronaldborman** [comment]
I also experienced the problems above in IE11. The first problem (the EventSource error message) was resolved by installing and requiring eventsource-polyfill (as described by @bjankord).

It looks like a solution for the second problem (the mangled display) is in https://github.com/tomkp/react-split-pane/issues/207.  Kadira/react-split-pane was a fork of this package, but since Storybook 3.0 the original package replaces the fork. 

After downgrading bowser to version 1.6.1 (npm install bowser@1.6.1 --save --save-exact) my component is now rendered correctly.

That said, I don't have IE10 installed so I can't confirm it also work under IE10.

**Comment by ndelangen** [comment]
> On January 12, 2016 Microsoft announced end of support for IE10

If anyone wants to make it work, be my guest, but I don't see much value.
So really feel free to make a PR, fixing storybook for unsupported browsers, it's welcome!

But I will not spend time on it. 

Related IE11 issues:
#1352 #213 #757

**Comment by Hypnosphi** [comment]
I'm not really sure that encouraging usage of browsers that don't get security updates is a good idea at all
https://www.xfive.co/blog/stop-supporting-ie10-ie9-ie8/

**Comment by ndelangen** [comment]
I'm going to close this, this remains unresolved.

A PR **is** still welcome.
