### ISSUE TITLE
Add support for Svelte Framework

### ISSUE THREAD

**Issue by vladejs** [storybooks/storybook#2984]
[Svelte Documentation](https://svelte.technology)

**Comment by danielduan** [comment]
@vladejs All of our framework support additions are done by community members. I don't think anyone has suggested Svelte yet, but if you're interested in helping out, definitely reach out.

**Comment by Hypnosphi** [comment]
Released as [4.0.0-alpha.18](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.18)
