### ISSUE TITLE
Using storybookAPI in  custom addon decorator

### ISSUE THREAD

**Issue by volodymyrl** [storybooks/storybook#2993]
Is it possible use storybookAPI.getQueryParams inside custom addon Decorator?

**Comment by Hypnosphi** [comment]
Yes, you should be able to access `storybookAPI ` object when [registering](storybookAPI) your addon. That means that it should have a "manager" part to interact with main window URI

**Comment by alexeychikk** [comment]
@Hypnosphi That doesn't answer the question. I need to call storybook api from the component returned from makeDecorator call. For example, I have the following code:
```TypeScript
import addons, {
	makeDecorator,
	StoryContext,
	StoryGetter
} from "@storybook/addons";
import * as React from "react";
import Provider from "./Provider";
import { ADDON_ID, Parameters } from "./shared";

export const withI18n = makeDecorator({
	name: "withI18n",
	parameterName: "i18n",
	skipIfNoParametersOrOptions: true,
	allowDeprecatedUsage: true,

	wrapper: (
		getStory: StoryGetter,
		context: StoryContext,
		{ parameters, ...rest }: { parameters: Parameters }
	) => {
		const channel = addons.getChannel();
		channel.emit(`${ADDON_ID}/register`, parameters);
		console.log(context, parameters, rest);

		return (
			<Provider channel={channel} {...parameters}>
				{getStory(context) as React.ReactNode}
			</Provider>
		);
	}
});
```
How can I pass storybook api to the `Provider` component?

**Comment by ViditaRustagi** [comment]
I have the similar case where I am using the global decorator, passed in decorators[] but not able to use useStorybookApi
