### ISSUE TITLE
http://getstorybook.io domain down

### ISSUE THREAD

**Issue by zephraph** [storybooks/storybook#3007]
### Issue details

When there's an issue with getstorybook it points to the domain http://getstorybook.io. That domain has expired and is no longer held by the project. The error message should probably be updated to point to some docs on here. 

### Steps to reproduce

Run storybook in a non-react directory. It'll give you the following error: 

![image](https://user-images.githubusercontent.com/3087225/36335683-c9c1ef92-134f-11e8-82af-9ea47ced3cd1.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- getstorybook 1.7.0

**Comment by zephraph** [comment]
Ahh, note, I accidentally installed the old storybook cli. We could potentially close this. Is there anyway to set that npm project as deprecated?

**Comment by Hypnosphi** [comment]
It says it's deprecated when you install it (at least it should)

**Comment by zephraph** [comment]
Hmm, I didn’t notice that. I may have just missed it. Thanks!
