### ISSUE TITLE
Add browser compatibility info to the README

### ISSUE THREAD

**Issue by mnmtanish** [storybooks/storybook#301]
Decide which browser we should support for storybook and add it to the README file. Also make sure storybook works without any errors with those browsers.

**Comment by arunoda** [comment]
Yep. Simply add this doesn't work with IE10 and Edge for now. And also note we are looking for help to fix it. May be show related issues.

**Comment by Guria** [comment]
It almost work in Edge if you use direct url to story. But stories list is empty.

**Comment by ndelangen** [comment]
At the very least we should state up front in which browser we know it does work and add this to the README

**Comment by ndelangen** [comment]
IE10 is not supported: https://github.com/storybooks/react-storybook/issues/298

**Comment by shilman** [comment]
@mnmtanish is there a PR for this?

**Comment by ndelangen** [comment]
Not high enough prio for right now, and possibly something we want to do in documentation over the readme?

It's a nice to have, So a PR is very much welcome!
