### ISSUE TITLE
Storyshots for react-native and dynamic stories

### ISSUE THREAD

**Issue by FredyC** [storybooks/storybook#3018]
### Issue details

For React (and other) the use of `require.context` is pretty much standard for loading a dynamic list of story files. There is a [mock included](https://github.com/storybooks/storybook/blob/ebe0ca863b8e9ee14411424d014063716353ff80/addons/storyshots/src/react/loader.js#L15) in Storyshots for these projects.

In the React Native it's not possible to dynamically load stories with the standard setup, but with [Haul support](https://github.com/storybooks/storybook/tree/master/app/react-native#using-haul-cli) this is working just fine. Unfortunately, for some reason this mock [is not included](https://github.com/storybooks/storybook/blob/ebe0ca863b8e9ee14411424d014063716353ff80/addons/storyshots/src/rn/loader.js#L16) for a react-native.

There is a minor difference that react-native storybook config file is in `./storybook/index.js` while for React project it's `./.storybook/config.js`. This is a bit hardcoded in there.

I might give it a shot to solve this, but I would like to know if there was some other reason than I've mentioned.

### Steps to reproduce

React Native projects are generally harder to reproduce I guess. Let me know if the issue is unclear and I can try for some simplified repo, but in my opinion issue at hand is clear.

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react-native ... 3.3.8
- storybook/addon-storyshots ... 3.3.13
- haul ... 1.0.0-beta.11
- jest ... 22.0.3

**Comment by igor-dv** [comment]
@FredyC , you are welcome to give it a try =) I have been the last one who refactored storyshots (For an easier multi-framework support). But I have not seen any Houl support there before.

**Comment by FredyC** [comment]
Annoying bot :) I've simply postponed need for this, but I will surely get to it eventually.

**Comment by slorber** [comment]
Hi @FredyC 

Sorry but I'm not sure how you deal with dynamic story imports in RN currently and I'm looking for a solution.

I've found this that may be handy as a workaround https://github.com/elderfo/react-native-storybook-loader

**Comment by FredyC** [comment]
@slorber Sorry, I've kinda left a world of React Native, so I am not really focused on looking for a solution.

@Hypnosphi I guess you can close it now or if @slorber wants to take over ... ?
