### ISSUE TITLE
[Angular] Can't get my global less file into storybook

### ISSUE THREAD

**Issue by kroeder** [storybooks/storybook#3020]
### Issue details

As I've read in several issues and merges Storybook's webpack loader automatically uses `.angular-cli` styles - correct?

In my current environment I need to use the following `.angular-cli` config for my global styles

```
  "styles": [
    "styles.less"
  ],
  "defaults": {
    "styleExt": "less",
    "component": {}
  }
```

I expected that my global less is getting imported by storybook

### Steps to reproduce

- Create an angular project
- Add a `styles.less` / add it to your `.angular-cli` config
- Create an angular component
- Add it as a story

### Please specify which version of Storybook and optionally any affected addons that you're running

-  "@ storybook/angular": "^3.3.13"

### Screenshots / Screencast / Code Snippets (Optional)

```js
// webpack.config.js
const genDefaultConfig = require('@storybook/angular/dist/server/config/defaults/webpack.config.js');

module.exports = (baseConfig, env) => {
    const config = genDefaultConfig(baseConfig, env);

    // Overwrite .css rule
    const cssRule = config.module.rules.find(rule => rule.test && rule.test.toString() === '/\\.css$/');
    if (cssRule) {
        cssRule.exclude = /\.component\.css$/;
    }

    // Add .scss rule
    config.module.rules.unshift({
        test: /\.less$/,
        loaders: ['raw-loader', 'less-loader'],
    });

    return config;
};
```

**Comment by igor-dv** [comment]
Yep. but in the alpha version. (3.4.something-alpha, take the latest).

**Comment by kroeder** [comment]
Works great and as expected! Great work :)

I had to remove my webpack.config.js and do some configurations in the .angular-cli (I removed most of the properties since it's a library that does not necessarily depends on .angular-cli) - after that it just started.
