### ISSUE TITLE
addon-info: docgen on PropTypes.shape()

### ISSUE THREAD

**Issue by shaun-sweet** [storybooks/storybook#3031]
I have my prop types 
```javascript
ApplicationSelector.propTypes = {
  /** Array of applications selector can render  */
  applications: PropTypes.arrayOf(PropTypes.shape({
    /** Name of application */
    name: PropTypes.string.isRequired,
    /** Label of link that actual renders to end user */
    displayName: PropTypes.string.isRequired,
    /** onClick link reference to the location of application */
    homePageUrl: PropTypes.string.isRequired
  })).isRequired
}
```

The descriptions don't actually show, nor do the isRequired flags in the nested props.  Is this possible using the babel plugin you're using at all?  Perhaps its currently implemented and I'm not doing something correct?   Heres a screenshot

![image](https://user-images.githubusercontent.com/16771592/36399781-b56853f0-158a-11e8-8bf5-9880540df8b5.png)

**Comment by Hypnosphi** [comment]
AFAIK this info is actually available in docgen. There was some suggestion about how it can be presented: https://github.com/storybooks/storybook/pull/1485#issuecomment-323404341

**Comment by shaun-sweet** [comment]
Hmm yea it shows the nested types, but there's a bit of missing data.  It seems like that wasn't added.  Perhaps I can dig into it a bit and expand it a bit.

**Comment by Hypnosphi** [comment]
Cool, go for it

**Comment by ndelangen** [comment]
This is fixed
