### ISSUE TITLE
Supported frameworks for certain addons are documented wrong

### ISSUE THREAD

**Issue by kroeder** [storybooks/storybook#3038]
### Issue details

I saw this table of supported addons: https://github.com/storybooks/storybook/blob/master/ADDONS_SUPPORT.md

Let's pick addon/actions: https://github.com/storybooks/storybook/tree/master/addons/actions 
It's documented that it supports `React, React Native and Vue`. The table of supported frameworks tells a different story: `React, React Native, Vaue, Angular, Polymer`

I noticed that every angular supported addon expect storyshots is differently documented
Which one is correct?

And in case of Angular: If they are not supported yet (I don't get notes to run with angular :( ) can you give an example on how to develop an addon for multiple frameworks? I might just don't get it right but I am not really experienced with react (95% of all examples are react related). 

But I do have lots of knowledge in Angular and are happy to help if I can.

**Comment by Hypnosphi** [comment]
cc @igor-dv

**Comment by Hypnosphi** [comment]
> can you give an example on how to develop an addon for multiple platforms?

[Knobs addon](https://github.com/storybooks/storybook/tree/master/addons/knobs) is a good example

**Comment by igor-dv** [comment]
This support table was actually done by me going and checking every addon, so this is the state of the support up to the current alpha version. 

> I don't get notes to run with angular 

Here are the live examples: https://github.com/storybooks/storybook#live-examples

**Comment by igor-dv** [comment]
Also, if you find that some addon is supported, feel free to add examples and changes the table =)

**Comment by kroeder** [comment]
I see! It's `withNotes({ text: 'my note' })` instead of `withNotes('test')`
I followed the example linked on the website: https://github.com/storybooks/storybook/tree/master/addons/notes  :) 

But it's still not working, even though I've added `import '@storybook/addon-notes/register';` in my config.js and copied a demo html story it shows "No panels available" - but this is a different topic.. If I can't get it run after some debugging I'll create an issue

**Comment by Hypnosphi** [comment]
> I've added import '@storybook/addon-notes/register'; in my config.js

It should be in `addons.js`

**Comment by kroeder** [comment]
My bad - tested too many things at once 👍. Thanks! 

In case you don't need this issue for any doc fixes you can close it! My questions are all solved by now - many thanks for the super quick help!
