### ISSUE TITLE
@storybook/addon-storysource is missing on npm

### ISSUE THREAD

**Issue by Hotell** [storybooks/storybook#3047]
yarn add -D @storybook/addon-storysource

![image](https://user-images.githubusercontent.com/1223799/36489091-6f4b9f66-1725-11e8-992d-d0d344951350.png)

![image](https://user-images.githubusercontent.com/1223799/36489112-7d57e88a-1725-11e8-9b9c-3bdeb40bacc5.png)

**Comment by igor-dv** [comment]
It's a new addon and will be released soon with v3.4

**Comment by Hotell** [comment]
Oh! Can you release it with rest of 3.4 alpha addons ? Maybe? 😎 No? Ok 😁

**Comment by igor-dv** [comment]
@shilman, when will be the next release?

**Comment by igor-dv** [comment]
Released as v3.4.0-alpha.9
