### ISSUE TITLE
Using puppeteer on storybooks server

### ISSUE THREAD

**Issue by ruxiang05** [storybooks/storybook#3048]
### Issue details

I want to open storybooks and run a puppeteer/jest script for visual testing on it. How do I approach this? I can't just do && cause storybooks blocks the pipeline.

**Comment by igor-dv** [comment]
You can build a static version of Storybook, and configure visual tests to use `index.html`

**Comment by ruxiang05** [comment]
Unfortunately, this does not work as it gives an unexpected token error at <!DOCTYPE ...

**Comment by igor-dv** [comment]
Can you please share more details about the error? It does work for us. 
Anyway, you can probably use something like `shelljs` inside the test and call the `exec` command that will start storybook as a child process.
