### ISSUE TITLE
Description not showing up with export const

### ISSUE THREAD

**Issue by denchen** [storybooks/storybook#3059]
### Issue details

I have a stateless component with PropTypes, but the description does not show up if it's an `export const`. This is on CRA + Storybook.

### Steps to reproduce

* `create-react-app my-app` (with latest CRA)
* `cd my-app`
* `getstorybook`
* `npm i -D @storybook/addon-info`
* Add a component named `Test.js`:

```
import React from 'react';
import PropTypes from 'prop-types';

export const Test = () => <button>A button</button>;

Test.propTypes = {
  /** A random label */
  randomProp: PropTypes.string
};
```

And a Storybook test:

```
import React from 'react';
import { storiesOf } from '@storybook/react';
import { Test } from '../Test';
import { withInfo } from '@storybook/addon-info';

storiesOf('Test', module)
  .add('testing description',
  withInfo()(() =>
    <Test>A button></Test>
));
```

I expect the description to show up for `randomProp`, but it doesn't.

However, if I change `Test.js` to this:

```
import React from 'react';
import PropTypes from 'prop-types';

const Test = () => <button>A button</button>;

Test.propTypes = {
  /** Another label */
  randomProp: PropTypes.string
};

export default Test;
```

and do an `import Test from '../Test`, then the description *does* show up.

And here's another case where it fails, using React.PureComponent:

```
import React from 'react';
import PropTypes from 'prop-types';

class Foo extends React.PureComponent {
  render() {
    return <button>test</button>;
  }
}

Foo.propTypes = {
  /** Some description here */
  randomProp: PropTypes.string
};

export default Foo;

export const Bar = () => <div>Hi</div>;
```

If I test `Foo`, then `randomProp`'s description does not show up. *But* if I comment out the last line:
    `// export const Bar = () => <div>Hi</div>;`
then the `randomProp` will show up for `Foo`.

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react 3.3.14`
- `@storybook/addon-info 3.3.14`
- `create-react-app 1.5.2`

**Comment by dangreenisrael** [comment]
There is an open PR for this: https://github.com/storybooks/babel-plugin-react-docgen/pull/46
