### ISSUE TITLE
getstorybook - connect ETIMEDOUT

### ISSUE THREAD

**Issue by markpritchett** [storybooks/storybook#3060]
### Issue details

Receive a **connect ETIMEDOUT** error when trying to install storybook into project.

I am behind a corporate proxy, which could be causing issues.

### Steps to reproduce

Run `getstorybook`

### Please specify which version of Storybook and optionally any affected addons that you're running

-  storybook/cli@3.3.14

### Affected platforms 

- npm 5.0.4
- OS - Windows 8.1

### Screenshots / Screencast / Code Snippets (Optional)

![image](https://user-images.githubusercontent.com/1267889/36586118-623e9ec8-1878-11e8-8ced-2de28a6ab2a7.png)

**Comment by Hypnosphi** [comment]
> I am behind a corporate proxy

You probably need to contact your admins

**Comment by danielduan** [comment]
You can use `npm config set proxy` and `npm config set https-proxy` to configure the proxy.

**Comment by markdalgleish** [comment]
@danielduan I think you mean @markpritchett :smile:

**Comment by markpritchett** [comment]
Thanks @danielduan.  `npm install` actually works fine for me.  I can use the Angular CLI without problems (which is doing a similar thing, installing packages).  I wonder whether the Angular CLI is respecting the proxy settings and `getstorybook` isn't?

**Comment by lucidtech** [comment]
@danielduan came here for same reasons - using react create-react-app, not angular.  also have proxy and have `npm config set proxy` and `npm config set https-proxy` set.  `npm i` works fine - but `getstorybook` times out with the same error as above.
Finally did `npm i --save-dev @storybook/react` - but I see elsewhere that this is supposedly deprecated?

**Comment by danielduan** [comment]
Created a ticket, basically we don't use `npm` or `yarn` to check for dependencies. Instead, we use a library which doesn't have proxy settings configured.

**Comment by Hypnosphi** [comment]
Released as [`3.4.0-rc.4`](https://github.com/storybooks/storybook/releases/tag/v3.4.0-rc.4)
