### ISSUE TITLE
How to disable HMR?

### ISSUE THREAD

**Issue by datenreisender** [storybooks/storybook#3062]
There are cases, when I want to disable HMR, e.g. because the HMR request makes it harder to debug a timing problem or because I want to visually compare a design change. But I did not find a documentation on how to disable HMR with storybook. I tried to provide a webpack config that should do the job (containing the following snippet), but that also did not do the job

```js
module.exports = {
  devServer: {
    inline: false,
    hotOnly: true,
    hot: false,
  },
};
```

**Comment by datenreisender** [comment]
Lacking a better solution, I now [create a static app](https://storybook.js.org/basics/exporting-storybook/), when I temporarily want to use Storybook without HMR.

**Comment by demerzel3** [comment]
I was able to disable the HMR using an env var by tinkering with the webpack config, here is an example (it uses `ramda` to manipulate the config, but it is not a requirement):

```javascript
// webpack.config.js

const always = require('ramda/src/always');
const complement = require('ramda/src/complement');
const contains = require('ramda/src/contains');
const evolve = require('ramda/src/evolve');
const filter = require('ramda/src/filter');
const when = require('ramda/src/when');
const { createDefaultWebpackConfig } = require('@storybook/core/server');

const hotReloadDisabled = process.env.STORYBOOK_HMR_DISABLED === 'true';

module.exports = (baseConfig, configType) => when(
    always(configType !== 'PRODUCTION' && hotReloadDisabled),
    evolve({
        entry: {
            preview: filter(complement(contains('webpack-hot-middleware'))),
        },
        plugins: filter(plugin => plugin.constructor.name !== 'HotModuleReplacementPlugin'),
    }),
    createDefaultWebpackConfig(baseConfig),
);
```

Basically to disable HMR you need to remove the `HotModuleReplacementPlugin` which is added by default, and remove also the client component, which is included in the `preview` entrypoint. Getting rid of both solves the problem.

**Comment by joeycozza** [comment]
For posterity: As of June 21 2019, all that was required to turn off HMR was removing the webpack-hot-middleware entry, there was no plugin being used called HotModuleReplacementPlugin.

```javascript
// webpack.config.js
require('dotenv').config()

module.exports = async ({ config }) => {
  //ability to turn off HMR with an envar
  if (process.env.DISABLE_HMR === 'true') {
    config.entry = config.entry.filter(singleEntry => !singleEntry.includes('/webpack-hot-middleware/'))
  }

  return config
}
```

**Comment by tfrijsewijk** [comment]
@joeycozza's solution still works (Storybook 6.2.5) :tada:

but... `config.entry` is an array of paths, and since I'm running Windows the entry I wanted to remove looks something like `node_modules\\webpack-hot-middleware\\client.js`

I changed the solution to

```
// webpack.config.js
require('dotenv').config()
const { sep } = require('path')

module.exports = async ({ config }) => {
  //ability to turn off HMR with an envar
  if (process.env.DISABLE_HMR === 'true') {
    config.entry = config.entry.filter(singleEntry => !singleEntry.includes(`${sep}webpack-hot-middleware${sep}`))
  }

  return config
}
```

I'm using Storybook to develop and run my Cypress tests on and want to resemble production as close as possible. `start-storybook --no-hmr` would be nice :)
