### ISSUE TITLE
Angular template with knobs

### ISSUE THREAD

**Issue by marcelorl** [storybooks/storybook#3066]
It would be great if I could keep using angular components which expect content inside of them with `ng-include` and still take advantage of knobs addon.

- @storybook/angular ^3.4.0-alpha.9
- @storybook/addon-knobs ^3.4.0-alpha.9

**Comment by igor-dv** [comment]
Can you please elaborate what doesn't work for you? Who do you use it?

**Comment by davidenke** [comment]
I could imagine that he means using the `template` property instead of `props`.

**Comment by haldunatar** [comment]
As it was mentioned here #3066, I would like to use also ng-content with .addDecorator(withKnobs). 

Issue is that if I add 'addDecorator(withKnobs)' the component will not be shown without any console errors!

This works

```
storiesOf('Button groups', module)
  .addDecorator(withKnobs) // !!!!! As I add this the component will not be displayed anymore..
  .add('My button groups', () => ({
    component: ButtonGroupComponent,
	moduleMetadata: {
		declarations: [ButtonGroupComponent, ButtonComponent],
	},
	props: {
	    type: select('type', {left: 'Left', right: 'Right'})
	},
	template: `
		<my-button-group>
			<my-button type="primary" role="none" label="Primary button"></my-button>
			<my-button type="secondary" role="none" label="Secondary button"></my-button>
		</my-button-group>
		`
        })
    );
```

**Comment by igor-dv** [comment]
I am not sure what's wrong in your setup, but as you can see [here](https://storybooks-angular.netlify.com/?knob-name=John%20Doe&knob-age=0&knob-phoneNumber=555-55-55&selectedKind=Addon%7CKnobs&selectedStory=Simple&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) (the v3.4 live example) it does work with knobs and templates.

You have both `component` and `template` props in use, maybe that's the problem.

**Comment by haldunatar** [comment]
@igor-dv that helps thanks!
