### ISSUE TITLE
Sending data from container to component with @storybook/mantra-core

### ISSUE THREAD

**Issue by fortuneNyl** [storybooks/storybook#3101]
I have a meteor v1.6.1 app, with react@16.2.0. But I have a problem with the composeWithTracker function. This function have been taken off react-komposer@2, used by storybook, but is still declared in @storybook/mantra-core/dist/index. So, I have a question. How could I send data from my containers to my components? Need help please.
    When I do this in my container with @storybook/mantra-core:
    import {useDeps, composeWithTracker, composeAll} from '@storybook/mantra-core';
export const classeComposer = ({context}, onData) =>{
    const {Meteor, FlowRouter, Collections,} = context();
    if (Meteor.subscribe('classes.list').ready()){
        const lesClasses = Collections.Classes.find({},
                                    {fields: {_id:1, code:1, nbrePlaces:1},
                                    sort: {code:1, nbrePlaces:1}}).fetch();
        const nbreClasses = Collections.Classes.find({}).count();
        onData(null, { lesClasses, nbreClasses});
    }else{
        onData();
    }
};
export const classeMapper = (context, actions) => ({
      addclasse: actions.classes.addclasse,
      updateclasse: actions.classes.updateclasse,
      deleteclasse: actions.classes.deleteclasse,
      context: () => context
});

export default (component) => composeAll(
      composeWithTracker(classeComposer),
      useDeps(classeMapper)
)(component);
    I have this error in my consol:
Uncaught (in promise) TypeError: composeWithTracker is not a function
    at eval (/imports/modules/core/containers/Classes.js:88:21)
    at Route._callee$ (http://localhost:4000/app/app.js?hash=9e577aa13e8896245acee791ed37df88948a09c2:381:32)
    at tryCatch (http://localhost:4000/packages/modules.js?hash=5763c96b3eee7f2b55565963c705a396d19a512b:34210:40)
    at Generator.invoke [as _invoke] (http://localhost:4000/packages/modules.js?hash=5763c96b3eee7f2b55565963c705a396d19a512b:34444:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:4000/packages/modules.js?hash=5763c96b3eee7f2b55565963c705a396d19a512b:34262:21)
    at tryCatch (http://localhost:4000/packages/modules.js?hash=5763c96b3eee7f2b55565963c705a396d19a512b:34210:40)
    at invoke (http://localhost:4000/packages/modules.js?hash=5763c96b3eee7f2b55565963c705a396d19a512b:34300:20)
    at http://localhost:4000/packages/modules.js?hash=5763c96b3eee7f2b55565963c705a396d19a512b:34310:13
    at http://localhost:4000/packages/meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:1167:22
    at <anonymous>

Need help please.

**Comment by danielduan** [comment]
Has `composeWithTracker` been deprecated? Or is it just left out by mistake?

You are welcome to submit a PR to `@storybook/mantra-core` if you'd like to try to fix this yourself. Mantra is effectively deprecated and I'm only committing to publishing bug fixes at this point.

**Comment by fortuneNyl** [comment]
I don't know if composeWithTracker is deprecated or just left by mistake in React-komposer. If it is deprecated, I think it would have another function to send data from containers to components right now. If not, it could be a mistake, and it must be added again.

**Comment by fortuneNyl** [comment]
Can Arunoda gives me more details, and the solution by the way?

**Comment by danielduan** [comment]
he's been working on other projects and haven't responded on any of his old requests which is why we published a fork.

again, if you're interested in putting in a fix, we'll definitely take a look. i don't imagine any of the old maintainers will put in any time to patch any bugs at this point.
