### ISSUE TITLE
Puppeteer cannot start chrome

### ISSUE THREAD

**Issue by wotaen** [storybooks/storybook#3110]
### Issue details

When using storyshots and `imageSnapshot`:
```
initStoryshots({suite: 'Image storyshots', test: imageSnapshot({storybookUrl: 'http://localhost:9001'})});
```

headless chrome process is started, but jest cannot connect to it, first error:
```
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
```

However, when I change this line in `test-body-image-snapshot.js`:
`.launch({ args: ['--no-sandbox ', '--disable-setuid-sandbox'] })`
to
`.launch({execPath: '/usr/bin/chrome'})` where `/usr/bin/chrome` is headless chrome driver, everything works as expected. 

### Please specify which version of Storybook and optionally any affected addons that you're running

storybook/addon-storyshots: ^3.4.0-alpha.9,

### Affected platforms 

- Ubuntu, 14.04

**Comment by danielduan** [comment]
I wonder if this is a problem with different Linux distros and the configs of the binarys. We do run it on a docker image with Linux and it seems to work fine.

**Comment by Hypnosphi** [comment]
Note that we also run this command before visual tests on CLI:

https://github.com/storybooks/storybook/blob/master/scripts/workaround-puppeteer-issue-290.sh

**Comment by EdenTurgeman** [comment]
I also just encountered this problem, would love to find out a solution.
