### ISSUE TITLE
Support .config/webpack.config.ts

### ISSUE THREAD

**Issue by ConneXNL** [storybooks/storybook#3125]
By default webpack supports typescript files as configuration files: https://webpack.js.org/configuration/configuration-languages/#typescript

However, .config/webpack.config.ts does not seem to work as also reported at https://github.com/TypeStrong/ts-loader/issues/730

**Comment by liuchaofeng1230** [comment]
I think I solved this problem today.

ts-loader in [storybook-doc](https://storybook.js.org/configurations/custom-webpack-config/) doesn't work.

Then I found I installed ts-loader@4.x, and the version of webpack in storybook is 3.x.

So, I installed ts-loader@3.5.0, and everything is OK.
