### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'helpers' of undefined

### ISSUE THREAD

**Issue by sabrinaluo** [storybooks/storybook#3126]
### Issue details
Not working with latest `vue-cli` generated project :(
Sorry I don't understand the error and dont know how to fix it, can anyone help? thank you in advance.

### Steps to reproduce
```
# vue-cli@3.0.0-beta.2
vue create myApp
cd myApp
yarn serve
```
until here it is still working

but after running `getstorybook`, it's not working anymore, it couldn't build the storybook which throws errors, meanwhile`yarn serve` throws errors too.

### Please specify which version of Storybook and optionally any affected addons that you're running
```
 "dependencies": {
    "vue": "^2.5.13"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.3.14",
    "@storybook/addon-links": "^3.3.14",
    "@storybook/addons": "^3.3.14",
    "@storybook/vue": "^3.3.14",
    "@vue/cli-plugin-babel": "^3.0.0-beta.2",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.2",
    "@vue/cli-plugin-unit-mocha": "^3.0.0-beta.2",
    "@vue/cli-service": "^3.0.0-beta.2",
    "@vue/eslint-config-prettier": "^3.0.0-beta.2",
    "@vue/test-utils": "^1.0.0-beta.10",
    "babel-core": "^6.26.0",
    "babel-preset-vue": "^2.0.1",
    "chai": "^4.1.2",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "vue-template-compiler": "^2.5.13"
  }
```
### Affected platforms 
mac os, node v9.7.0

### Screenshots / Screencast / Code Snippets (Optional)
warning when run `getstorybook`
![image](https://user-images.githubusercontent.com/5300359/36857242-fc041f3a-1db2-11e8-97b9-2ea9d23dc88c.png)

error when run `yarn run storybook`
![image](https://user-images.githubusercontent.com/5300359/36856495-1d8c152e-1db1-11e8-8b1e-bd766961b932.png)

**Comment by ndelangen** [comment]
@sabrinaluo Looks like you're using the vue-cli 3 beta, that might be the issue.

We'll have to investigate how to fix / be compatible with this new CLI.
The Vue-loader version version-mismatch is a first point of investigation.
