### ISSUE TITLE
API - Is it possible to retrieve story by context?

### ISSUE THREAD

**Issue by tourshi** [storybooks/storybook#3127]
### Issue details

I'm working on an addon (based of the info addon) and wondering if its possible to retrieve a story (the react element, from storyFn?) from a story's context (for eg. {kind: "Components/Tabs", story: "Basic"}). I'm trying to do this from within the panel. 

Something like: api.getStory(context) I've had a look at the documentation but couldn't find anything to that affect.

I tried emitting the story object (react element) but the story.type property never makes it to my addon (and I need it to retrieve docgen info)

Any help/direction would be appreciated. 
Thank you

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.3.14

**Comment by lmenus** [comment]
Hi, can you add some code? I am trying to understand how you'd imagine this working. Do you mean you will have a story component (from `storyFn()`) let's say like this.

```js
class Story extends Component {
  render() {
    return (
      <div>
        <Child />
      </div>
    }
  }
}
```

And you want to be able to dive into the component and retrieve `<Child />`?
