### ISSUE TITLE
Custom storybook UI

### ISSUE THREAD

**Issue by necolas** [storybooks/storybook#313]
I'm starting to use storybook for react-native-web - https://necolas.github.io/react-native-web/storybook - and internally at Twitter. In both cases, we could benefit from customising the UI outside of the iframe. For example:
- something more whitelabel that can be themed with React Native or Twitter brand styles (e.g., replace "React Storybook" with our own logo, style the sidebar)
- support for a deeper hierarchy
  
  "APIs" -> "StyleSheet" -> stories
  "Components" -> "Touchable" -> stories
- works on mobile (e.g., doesn't rely on keyboard shortcuts or mouse controls to change view modes)

Are there any plans in this vain – or is there any interest?

**Comment by arunoda** [comment]
I think you are referring to this: <https://github.com/kadirahq/storybook-ui>
We also started to work with the [React Native](https://github.com/kadirahq/react-native-storybook).

I think we could add more features into the storybook-ui and then simply upgrade the version in this repo.

Is this something you looked for?

**Comment by arunoda** [comment]
BTW: It's nice to see you guys started to using storybook and that's a nice storybook :)

And add some better mobile support is important. I think we can talk this on the storybook-ui repo.

**Comment by necolas** [comment]
Oh I see, thanks. Using `storybook-ui` directly feels more like developing another app which is something I want to avoid at the moment. But perhaps we can eventually help adapt `storybook-ui` to support some basic skinning and better mobile support. I see you already have https://github.com/kadirahq/storybook-ui/issues/4.

**Comment by arunoda** [comment]
I think we could work more features directly into the storybook-ui and put it here. 
There are still a few to merge. Implementing a mobile view is pretty important at this moment. 
We will work on that.

**Comment by gabrielhpugliese** [comment]
I wanted to do a single page with all stories, one on bottom of each other. Do you think it would be easy to do @arunoda ? If yes, how can I start doing that?

**Comment by ndelangen** [comment]
The work needed to make Storybook 100% customizable is in progress, but it's a long process. and Will take #1209 to be done.

**Comment by ndelangen** [comment]
There are quite a few issues about this:
#1360 #1107 #428 

I'll close a few, but of course it **IS** on the roadmap.
