### ISSUE TITLE
Support of @storybook/addon-info for Angular stories

### ISSUE THREAD

**Issue by ToniaDemchuk** [storybooks/storybook#3134]
### Issue details

Are there any plans to support of addon-info for Angular stories?

I would be nice to have an nice formatted info about:
- usage of components (info from template property);
- Input/Output properties and their types;
- what needs to be imported, declared or provided (info from moduleMetadata property).

**Comment by ftanrisevdi** [comment]
it would be great

**Comment by mtuzinskiy** [comment]
Yes please!

**Comment by shilman** [comment]
It's coming as part of Storybook Docs 💥 

<img width="727" alt="Storybook" src="https://user-images.githubusercontent.com/488689/55663227-3ddb8200-584e-11e9-9bdd-6a14b2c2fa72.png">

**Comment by shilman** [comment]
Docs info issue tracked here: https://github.com/storybooks/storybook/issues/6664
