### ISSUE TITLE
Scoped symlinks in node_modules not working

### ISSUE THREAD

**Issue by nschnierer** [storybooks/storybook#3138]
### Issue details

Scoped symlinks (e.g. `@babel/core`) in node_modules not working with `@storybook/react-native`.
https://github.com/storybooks/storybook/blob/4465ffa25da33a47e9233756c627373ba39893c9/app/react-native/src/bin/storybook-start.js#L62

`findSymlinksPaths` is not able to find scoped symlinks. There is an closed pull-request for a fix (https://github.com/facebook/react-native/pull/12400) but nothing happened yet, because metro is handling this part now.

### Steps to reproduce

In lerna we are able to add dependencies as a symlink:
```
lerna add @boring/package --scope=@boring/storybook-native
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react-native 3.3.14`

### Affected platforms 

macOS

**Comment by nschnierer** [comment]
Got a workaround for this issue. With a `haul` (https://github.com/callstack/haul) config we are able to solve this problem (feature pull-request #1294 🙏).

Create a config file (e.g. `haul.config.js`):
```js
const path = require('path');

module.exports = ({ platform }, defaults) => ({
  entry: `./storybook/index.${platform}.js`,
  resolve: {
    ...defaults.resolve,
    modules: [path.join(__dirname, 'node_modules')]
  }
});
```

Edit `npm run storybook` command in `package.json`:
```
"scripts": {
  "storybook": "storybook start -p 7007 --haul haul.config.js"
},
```

**Comment by igor-dv** [comment]
Reopen if needed.
