### ISSUE TITLE
Snapshot tests for the same repository on Windows and Linux should not fail.

### ISSUE THREAD

**Issue by gibbok** [storybooks/storybook#3140]
### Issue details

Snapshot tests for the same repository on Windows and Linux should not fail.
Instead when running the tests on different OS the "number" in `className` is different making the tests fail.

IMO this is related on how different OS order the files.

```
className="Comp-root-16" // example created on mac
className="Comp-root-43" // same test runned on win
```
### Steps to reproduce

- Create snapshots in MAC and commit/push.
- Run tets (tests are fine)
- Clone repo with snapshots onWIN.
- Run tests (tests are failing, different number in className)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react ^3.3.13
- @storybook/addon-storyshots ^3.3.13

**Comment by igor-dv** [comment]
Does it happen with multi-snapshot ? single-snapshot ? Also how is this class name generated ? Assumption - if you are using css modules, this number is a hash, so difference might be in the file itself. For example "new line" format.

**Comment by gibbok** [comment]
It happens during multi-snapshots, the class name is generated by material-ui (more info on this [ticket](https://github.com/mui-org/material-ui/issues/10517)).
Not sure if the problem is within material-ui itself or in storybbok-storyshots.

**Comment by igor-dv** [comment]
Can you please check if it happens with the single snapshot file (which is a Jest's standard way), if it does, I believe there is nothing to do with storyshots beside using some kind of custom serializer for material-ui

**Comment by gibbok** [comment]
It happens with multi-snapshots

**Comment by Hypnosphi** [comment]
> For example "new line" format

This looks looks like the answer to me

**Comment by igor-dv** [comment]
Please reopen if there are any new insights
