### ISSUE TITLE
fileName is always undefined in the object returned from getStorybook()

### ISSUE THREAD

**Issue by CLL80** [storybooks/storybook#3153]
### Issue details

`fileName` is always `undefined` in the object returned from `getStorybook()` 

### Steps to reproduce

This can be reproduced by logging the `getStorybook()` object in at least version 3.3.10 through 3.4.0-alpha.9. I've reproduced using the cra-kitchen-sink example.

```js
import { getStorybook } from '@storybook/react'
...
storiesOf('Lifecycle', module).add('logging', () => <LifecycleLogger />);
console.log(getStorybook())
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react 3.3.10` through `@storybook/react 3.4.0-alpha.9`

### Output

```js
[
  {
    fileName: undefined,
    kind: "Welcome",
    stories: [
      {
        name: "to Storybook"
      }
    ]
  },
  {
    fileName: undefined,
    kind: "Force ReRender",
    stories: [
      {
        name: "button"
      }
    ]
  },
  {
    fileName: undefined,
    kind: "Button",
    stories: [
      {
        name: "with text"
      },
      {
        name: "with some emoji"
      },
      {
        name: "with notes"
      },
      {
        name: "with some info"
      },
      {
        name: "with new info"
      },
      {
        name: "addons composition"
      }
    ]
  },
  {
    fileName: undefined,
    kind: "App",
    stories: [
      {
        name: "full app"
      }
    ]
  },
  {
    fileName: undefined,
    kind: "Some really long story kind description",
    stories: [
      {
        name: "with text"
      }
    ]
  },
  {
    fileName: undefined,
    kind: "Lifecycle",
    stories: [
      {
        name: "logging"
      }
    ]
  }
]
```

**Comment by CLL80** [comment]
I see this is due to the how webpack bundles the files. In looking through `lib/core/src/client/preview/client_api.js`, I don't see a good way to make this available in this case. Any ideas?

**Comment by igor-dv** [comment]
What is your usecase? `fileName` was added for the Storyshots purposes. It exists when you run it in Node (JEST). Webpack has a different definition of "module".

**Comment by CLL80** [comment]
We can close the issue. I understand if it's not a conventional use of storybook, and I can find another way to do what I need.

I'm supplying multiple potential themes for my components through a prop. The theme names are dynamic, but the imported path string needs to be available before webpack bundles the sass files or else they won't be found when importing, so I was thinking about using the filenames to determine this beforehand.
