### ISSUE TITLE
storyshots classnames of storybook frame cause snapshot mismatch

### ISSUE THREAD

**Issue by chrisjbrown** [storybooks/storybook#3155]
### Issue details

In CI build snapshots are different but it is complaining about classnames from the storybook frame and not the component. I expect this to only flag an error if there is an error in the rendered component.

Oddly enough I only have this issue when running on the CI build. running locally with `npm test` and even `npm test -- -ci` works as expected

### Steps to reproduce

running `npm test`

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react 16.1.1
- storybook/addon-storyshots 3.3.13

### Affected platforms 

- jest + storybook + storyshots

### Screenshots / Screencast / Code Snippets (Optional)

part of the output I receive.
```js
Storyshots › Button › Buy

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -396,185 +396,185 @@
                   "
                   Button
                   " Component
                 </h2>
                 <table
    -              className="css-glamorous-table--3qhq7f"
    +              className="css-1ytzlk7"
                 >
                   <thead>
                     <tr>
                       <th
    -                    className="css-glamorous-th--1gvy3it"
    +                    className="css-d52hbj"
                       >
                         property
                       </th>
                       <th
    -                    className="css-glamorous-th--1gvy3it"
    +                    className="css-d52hbj"
                       >
                         propType
                       </th>
                       <th
    -                    className="css-glamorous-th--1gvy3it"
    +                    className="css-d52hbj"
                       >
                         re
```

UPDATE:

seems `addon/withinfo` was adding some elements to the page which was create the snapshot miss match. 

removing `withinfo` has resolved the issue. Is anyone aware that there is a conflict when using both addons?

**Comment by Hypnosphi** [comment]
@ndelangen I remember there was a similar issue, but can’t find it. AFAIR the solution was to set some env var

**Comment by ndelangen** [comment]
glamorous DOES deterministic classnames, they are based on the hash of the content of the class. If I'm not mistaken @kentcdodds ?

**Comment by kentcdodds** [comment]
They are deterministic. What's happening here is the class name will have the component's `displayName` set to the `label` which glamor will include in the class name. But it only does that when the `NODE_ENV` is `development` I believe. Make sure that the `NODE_ENV` is unchanged from when you take the snapshot to when you compare it.

**Comment by ndelangen** [comment]
Thanks for the clarification ♥️
