### ISSUE TITLE
Support for react-native-windows 

### ISSUE THREAD

**Issue by jpshelley** [storybooks/storybook#3162]
Not an issue but a question, how do you get storybooks working for react-native-windows?
https://github.com/Microsoft/react-native-windows

It works fine on iOS and Android, but when I start my Windows application it cannot find the JS bundle

**Comment by danielduan** [comment]
It looks like react-native-windows uses a separate build system that is different from what react-native uses for iOS and Android. at this moment, we have no plans of supporting rn-windows.

We would love a pull request if you find a way to get it working with storybook-rn
