### ISSUE TITLE
[addon-info] [No propTypes defined] Using flow types

### ISSUE THREAD

**Issue by DiMoNTD** [storybooks/storybook#3163]
### Issue details

I'm using flow types instead of `prop-types` library. In my stories I use `addon-info`. And I noticed, that description of my props work only with stateless functions and if it returns jsx.

This works fine!
```js
//@flow
import React from 'react';

type TProps = {
  /** Button text */
  children: React$Node,
  /** Is button disabled*/
  disabled?: boolean,
  /** Click callback*/
  onClick: (e: MouseEvent) => void,
};

export default function Button(props: TProps) {
  return <button {...props}>{props.children}</button>;
}
```
and my story

```js
//@flow
import React from 'react';

import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { withInfo } from '@storybook/addon-info';

import Button from './index';

storiesOf('Controls/Button', module)
  .add(
    'with text',
    withInfo()(() => <Button onClick={action('click')}>Click me</Button>)
  );
```

![has props description](https://i.imgur.com/B66gHe1.png)

But, if I will return a local variable with jsx like this:
```js
export default function Button(props: TProps) {
  const myButton = <button {...props}>{props.children}</button>;
  return myButton;
}
```
there is no props description in storybook

![no props description](https://i.imgur.com/G9EMUCW.png)

If I declare Button class, there is no props description, too:

```js
export default class Button extends React.Component<TProps, *> {
  render() {
    return <button {...this.props}>{this.props.children}</button>;
  }
}
```

### Steps to reproduce

Install app with CRA, add flow-bin, add storybook and addon-info, then add Button component above and story withInfo

### Please specify which version of Storybook and optionally any affected addons that you're running

```js
"dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.1"
},
"devDependencies": {
    "@storybook/addon-actions": "^3.3.14",
    "@storybook/addon-info": "^3.3.14",
    "@storybook/addon-links": "^3.3.14",
    "@storybook/addons": "^3.3.14",
    "@storybook/react": "^3.3.14",
    "babel-core": "^6.26.0",
    "flow": "^0.2.3",
    "flow-bin": "^0.66.0"
}
```

**Comment by Hypnosphi** [comment]
Probably related: #3017

**Comment by 7yp0** [comment]
having the same issue.
sometimes it works for stateless components, sometimes only for class components

**Comment by danielduan** [comment]
fixed in https://github.com/storybooks/babel-plugin-react-docgen/issues/42
clear your lock files, reinstall, and let me know if this doesn't fix your issue

**Comment by thecalvinchan** [comment]
as a heads up, exporting an anonymous function will cause babel to throw and error when running through docgen

```
export default () => {}
```

isn't working for me on 4.0.0alpha14

but 

```
const Button = () => {}
export default Button
```

does work
