### ISSUE TITLE
angular@5.2.7: scss module parse failed: 'Unexpected character '@''

### ISSUE THREAD

**Issue by amitport** [storybooks/storybook#3165]
### Issue details

I have a  angular cli@1.7 app (no ejected webpack) and I can't write a story for components that use css import with a `@` char.

### Steps to reproduce

ng new app
cd app
getStorybook

write a component that use imports with '@' such as `@import '~@angular/material/theming';`
write a story for that component

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/angular@3.3.15`
- `@storybook/addon-notes@3.3.15`
- `@storybook/addon-actions@3.3.15`
- `@storybook/addon-links@3.3.15`
- `@storybook/addons@3.3.15`
- `@angular/cli@1.7.2`
- `@angular/core@5.2.7`

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)

![image](https://user-images.githubusercontent.com/1131991/37097908-3f74c17c-2225-11e8-8834-993bf21cb1a1.png)

```js
// code here
```

**Comment by igor-dv** [comment]
Can you please check the v3.4.0-alpha.9?

**Comment by ndelangen** [comment]
Yeah we added scss support by default for angular right?

**Comment by amitport** [comment]
now I'm getting:
```
ERROR in ./src/root/app/common/breadcrumbs.component.ts
[tsl] ERROR in <project-path>\src\root\app\common\my-components.component.ts(24,12)
      TS2304: Cannot find name 'require'.
Child html-webpack-plugin for "index.html":

```
line 24 is the styleUrls

**Comment by igor-dv** [comment]
> Yeah we added scss support by default for angular right?

Yeah, but more important is an integration with the css part of the `angular-cli's` webpack.config.

**Comment by igor-dv** [comment]
do you have a public repo with this issue?

**Comment by amitport** [comment]
https://github.com/amitport/storybook-issue-3165

`ng new --minimal` followed by `getStorybook` and using styleUrls

**Comment by igor-dv** [comment]
Adding `@types/node` as a devDep solved it form me

**Comment by igor-dv** [comment]
I think you need to exclude stories from your regular tsconig, and add a custom tsconfig to the `.storybook` dir that overrides this exclusion.

**Comment by amitport** [comment]
adding
```
"exclude": [
    "test.ts",
    "**/*.spec.ts",
    "stories"
  ]
```

to `src/tsconfig.app.json` seems to work

**Comment by DmitryEfimenko** [comment]
for me just `stories` didn't work. Had to do `"**/*.stories.ts"`

**Comment by igor-dv** [comment]
@amitport is probably using the `stories` dir to put all the stories in.
