### ISSUE TITLE
Setting publicPath almost works.

### ISSUE THREAD

**Issue by bionikspoon** [storybooks/storybook#3172]
### Issue details

Overriding `config.output.publicpath` does not work.

Here's the scenario:

As a developer, I want QA and Design teams to be able to review storybook on review apps.  I want to be able to publish storybook as a path on my main app: for example `pr-2200.example.com/storybook/`.  

If I set public path, it almost works:

```js
// .storybook/webpack.config.js
module.exports = (storybookBaseConfig, configType) => {
  if (configType === 'PRODUCTION') {
    storybookBaseConfig.output.publicPath = '/storybook/'
  }

  return storybookBaseConfig
}
```

There's one line, that seems to ignore webpack's publicPath:
https://github.com/storybooks/storybook/blob/abd4f0ef697c0b62ee724fd88e3c245efd4bd912/lib/core/src/client/manager/provider.js#L34

As a hack, I can fix this, by creating a redirect on my server.

For example, on rails, I can do:

```rb
  # config/routes.rb
  get 'iframe.html', to: redirect(path: '/storybook/iframe.html')
```
(edited this snippet): `redirect('/storybook/iframe.html')` -> ` redirect(path: '/storybook/iframe.html')`.  This subtle change forwards url params with the redirect. 

And everything works!

It would better if everything worked without creating a redirect on my server.

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react "3.2.x"

### Affected platforms 

- React version of the app.

**Comment by Hypnosphi** [comment]
Looks pretty easy to fix, feel free to open a PR

**Comment by Hypnosphi** [comment]
There's some related discussion in https://github.com/storybooks/storybook/pull/3010

**Comment by Hypnosphi** [comment]
In case of static build, you can just serve `storybook-static` to some path and it should work because of https://github.com/storybooks/storybook/blob/master/app/react/src/server/config/webpack.config.prod.js#L24-L29

**Comment by xiaolin** [comment]
@bionikspoon Did you ever resolve your issue besides using a redirect? I'm also running into the same issue setting up the static content to load in a django application.

**Comment by bionikspoon** [comment]
@xiaolin no, still using the redirect.

**Comment by Hypnosphi** [comment]
What happens if you don't override publicPath from our default config?

**Comment by Hypnosphi** [comment]
What do you need that for @chardskarth ?

**Comment by chardskarth** [comment]
Well.

Intuitively, I thought to be able to control webpack’s custom output path, I’d simply have to edit ‘output.path’. But then **there’s no other way to control the output directory but to use the ‘—output-dir’ option. 

And what do I need this for? **To control storybook-build’s path.**

**Comment by marco-silva0000** [comment]
@xiaolin I have just made the redirect solution in django. with the following view and url

```
from django.views.generic.base import TemplateView
class IframeView(TemplateView):
    template_name = 'iframe.html'
```
@chardskarth were you able to make this work without the redirect? can you provide an example?
If this is the case, it should be included on the documentation.

**Comment by chardskarth** [comment]
Just like what you mentioned to @xiaolin, I made the solution directly in java spring. 
```
@Configuration
public class WebMvcConfiguration implements WebMvcConfigurer {

   @Override
   public void addViewControllers(ViewControllerRegistry registry) {
       registry.addViewController("/storybook/**")
            .setViewName("forward:/storybook-build/index.html");
       registry.addViewController("iframe.html")
            .setViewName("forward:/storybook-build/iframe.html");
   }
}
```

**Comment by kimamula** [comment]
@Hypnosphi 

> In case of static build, you can just serve storybook-static directory to `/storybook/` path and it should work because of https://github.com/storybooks/storybook/blob/master/app/react/src/server/config/webpack.config.prod.js#L24-L29

If you visit `/storybook/index.html`, then it's OK.
However, if you visit `/storybook`, browser tries to fetch JS files under `/static` (not `/storybook/static`) which do not exist in this case.

**Comment by Hypnosphi** [comment]
You should serve all the `storybook-static` directory. So `storybook-static/static` should be served as `/storybook/static`

**Comment by Hypnosphi** [comment]
OK, you need a redirect then

**Comment by alexlafroscia** [comment]
I'm running into a similar issue as @kimamula, but in my case I'm trying to include the middleware for the server in an existing Express app, mounted at `/storybook`

If I make the request to `/storybook` I get an error about loading from `/static` but if I go to `/storybook/index.html` then the assets load correctly.

**Comment by signal-intrusion** [comment]
I feel like setting up server-side redirects is not the best solution for a client-side application. What if Storybook simply obeyed the consumer's setting for `publicPath` if it exists?

**Comment by joselcc** [comment]
static dir path mapping to a custom endpoint was added in this [PR](https://github.com/storybookjs/storybook/pull/12222) but it is available only in alpha version (6.1.0-alpha.23)
https://github.com/storybookjs/storybook/blob/next/lib/core/docs/standalone.md#for-static-mode

**Comment by chornos13** [comment]
> I've just figured this out finally! To fully set the path prefix you need to set `publicPath` in both `webpackFinal` and `managerWebpack` functions in the `.storybook/main.js` like this:
> 
> ```js
> // .storybook/main.js
> module.exports = {
>   webpackFinal: async (config, { configType }) => {
>     config.output.publicPath = '/my-prefix/';
>     return config;
>   },
>   managerWebpack: async (config) => {
>     config.output.publicPath = '/my-prefix/';
>     return config;
>   },
> };
> ```
> 
> Also, I had to build Storybook with the `preview-url` parameter to make it find the iframe file:
> 
> ```
> build-storybook -- --preview-url=/my-prefix/iframe.html
> ```
> 
> For some reason, I have found nothing about it in official docs, had to google it a lot...

Hey, thank you that's giving me hope about custom **publicPath**

In my case with Storybook version is 6.2.9 I need extra configuration in managerWebpack because **--preview-url** doesn't seem to works

```js
// .storybook/main.js
module.exports = {
  webpackFinal: async (config, { configType }) => {
    config.output.publicPath = '/my-prefix/';
    return config;
  },
  managerWebpack: async (config) => {
    configHtmlWebPackPlugin = config.plugins.find(plugin => plugin.constructor.name === 'HtmlWebpackPlugin')
    configHtmlWebPackPlugin.options.publicPath = '/assets/storybook/'
    config.output.publicPath = '/assets/storybook/'
    const oriTemplateParameters = configHtmlWebPackPlugin.options.templateParameters
    configHtmlWebPackPlugin.options.templateParameters = (compilation, files, options) => {
      oriReturn = oriTemplateParameters(compilation, files, options)
      oriReturn.globals.PREVIEW_URL = '/assets/storybook/iframe.html'
      return oriReturn
    }

    return config;
  }
};
```
you can replace /assets/storybook with your any prefix

Thanks

**Comment by brunomiguelbarrospinto** [comment]
> > I've just figured this out finally! To fully set the path prefix you need to set `publicPath` in both `webpackFinal` and `managerWebpack` functions in the `.storybook/main.js` like this:
> > ```js
> > // .storybook/main.js
> > module.exports = {
> >   webpackFinal: async (config, { configType }) => {
> >     config.output.publicPath = '/my-prefix/';
> >     return config;
> >   },
> >   managerWebpack: async (config) => {
> >     config.output.publicPath = '/my-prefix/';
> >     return config;
> >   },
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, I had to build Storybook with the `preview-url` parameter to make it find the iframe file:
> > ```
> > build-storybook -- --preview-url=/my-prefix/iframe.html
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For some reason, I have found nothing about it in official docs, had to google it a lot...
> 
> Hey, thank you that's giving me hope about custom **publicPath**
> 
> In my case with Storybook version 6.2.9 I just need managerWebpack configuration and giving some extra config because **--preview-url** doesn't seem to works
> 
> ```js
> // .storybook/main.js
> module.exports = {
>   managerWebpack: async (config) => {
>     configHtmlWebPackPlugin = config.plugins.find(plugin => plugin.constructor.name === 'HtmlWebpackPlugin')
>     configHtmlWebPackPlugin.options.publicPath = '/assets/storybook/'
>     config.output.publicPath = '/assets/storybook/'
>     const oriTemplateParameters = configHtmlWebPackPlugin.options.templateParameters
>     configHtmlWebPackPlugin.options.templateParameters = (compilation, files, options) => {
>       oriReturn = oriTemplateParameters(compilation, files, options)
>       oriReturn.globals.PREVIEW_URL = '/assets/storybook/iframe.html'
>       return oriReturn
>     }
> 
>     return config;
>   }
> };
> ```
> 
> you can replace /assets/storybook with your any prefix
> 
> Thanks

Sorry, i cant understand this implementation, could you show the full implementation file? Thanks

**Comment by chornos13** [comment]
> > > I've just figured this out finally! To fully set the path prefix you need to set `publicPath` in both `webpackFinal` and `managerWebpack` functions in the `.storybook/main.js` like this:
> > > ```js
> > > // .storybook/main.js
> > > module.exports = {
> > >   webpackFinal: async (config, { configType }) => {
> > >     config.output.publicPath = '/my-prefix/';
> > >     return config;
> > >   },
> > >   managerWebpack: async (config) => {
> > >     config.output.publicPath = '/my-prefix/';
> > >     return config;
> > >   },
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also, I had to build Storybook with the `preview-url` parameter to make it find the iframe file:
> > > ```
> > > build-storybook -- --preview-url=/my-prefix/iframe.html
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > For some reason, I have found nothing about it in official docs, had to google it a lot...
> > 
> > 
> > Hey, thank you that's giving me hope about custom **publicPath**
> > In my case with Storybook version 6.2.9 I just need managerWebpack configuration and giving some extra config because **--preview-url** doesn't seem to works
> > ```js
> > // .storybook/main.js
> > module.exports = {
> >   managerWebpack: async (config) => {
> >     configHtmlWebPackPlugin = config.plugins.find(plugin => plugin.constructor.name === 'HtmlWebpackPlugin')
> >     configHtmlWebPackPlugin.options.publicPath = '/assets/storybook/'
> >     config.output.publicPath = '/assets/storybook/'
> >     const oriTemplateParameters = configHtmlWebPackPlugin.options.templateParameters
> >     configHtmlWebPackPlugin.options.templateParameters = (compilation, files, options) => {
> >       oriReturn = oriTemplateParameters(compilation, files, options)
> >       oriReturn.globals.PREVIEW_URL = '/assets/storybook/iframe.html'
> >       return oriReturn
> >     }
> > 
> >     return config;
> >   }
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you can replace /assets/storybook with your any prefix
> > Thanks
> 
> Sorry, i cant understand this implementation, could you show the full implementation file? Thanks

Hey Bruno,
here is the simple implementation

.storybook/main.js
```js
function injectCustomPublicPath(configWebpack, publicPath) {
  configWebpack.output.publicPath = publicPath
  configHtmlWebPackPlugin = configWebpack.plugins.find(
    (plugin) => plugin.constructor.name === 'HtmlWebpackPlugin',
  )
  configHtmlWebPackPlugin.options.publicPath = publicPath
  const oriTemplateParameters =
    configHtmlWebPackPlugin.options.templateParameters
  configHtmlWebPackPlugin.options.templateParameters = (
    compilation,
    files,
    options,
  ) => {
    oriReturn = oriTemplateParameters(compilation, files, options)
    oriReturn.globals.PREVIEW_URL = `${publicPath}iframe.html`
    return oriReturn
  }
}


module.exports = {
  managerWebpack: async (config) => {
    // change /assets/storybook/ endpoint as you wish
    injectCustomPublicPath(config, '/assets/storybook/')
    return config
  },
}


```
