### ISSUE TITLE
preview-head.html is not rendered again in hot reload

### ISSUE THREAD

**Issue by caub** [storybooks/storybook#3176]
### steps

have a `preview-head.html` file at the root of storybook folder

insert `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">` in it for testing

in your stories add a story with `<span className="material-icons">close</span>` in it, this renders a cross icon, when the fonts are loaded

It works in the main storybook page, and even for that story (`&full=1`) if you reload, the fonts works

*but* in development mode (I use `"storybook": "start-storybook -p 9001 -c .storybook",`) as soon as editing this particular story, it's re-rendered, and you see suddenly `close` instead of a `❌`, I guess `preview-head.html` is ignored

### version

    "@storybook/react": "^3.3.14"

**Comment by caub** [comment]
for the reproduction, use any storybook setup (having react, babel, .. all set up), add a `preview-head.html` containing `body: {border: '2px red solid'}` for example, run `npx storybook`, edit a story, save and observe the body styling disappears

**Comment by caub** [comment]
I couldn't reproduce using `examples/official-storybook` (and its preview-head.html) I'll search more the issue

**Comment by ndelangen** [comment]
thanks! Will take a look if you can provide a reproduction repo 👍 .

**Comment by caub** [comment]
Ok, I found the issue
 https://github.com/caub/storybook-preview-head
I was using my main webpack config (because I needed special resolves) but that one were also using an html template, which was used after hot reload (hence the missing styling from `preview-head.html`)

I just need to avoid HtmlWebpackPlugin in storybook

Thanks
