### ISSUE TITLE
[angular] Support custom bootstrap options

### ISSUE THREAD

**Issue by amcdnl** [storybooks/storybook#3193]
## Request
In Angular, the `bootstrapModule` function accepts options such as `preserveWhitespaces`. Docs: https://angular.io/api/core/PlatformRef#bootstrapModule

Example:
```javascript
platformBrowserDynamic().bootstrapModule(AppModule, {
    preserveWhitespaces: false
});
```

I'd like the ability to pass options it accepts to this function here: https://github.com/storybooks/storybook/blob/master/app/angular/src/client/preview/angular/helpers.ts#L126

**Comment by alterx** [comment]
Yeah, I think we should add a `booststrapOptions` field to the story

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.31 containing PR #14852 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
