### ISSUE TITLE
Create React App feature compatibility

### ISSUE THREAD

**Issue by mattfysh** [storybooks/storybook#3194]
### Issue details

Strengthen compatibility between create-react-app and storybook build systems. There are some features of the CRA build (albeit, recent additions) which do not work with storybook (see steps to reproduce). Looking for any ideas here how to best get Storybook working with some of CRA's build features, plus any ideas to keep compatibility high as CRA grows.

### Steps to reproduce

1. `create-react-app myapp`
2. add storybook to myapp
3. add source code that uses babel macros, e.g. `emotion/macro`
4. add source code that uses SVG component imports, e.g. `import { ReactComponent as Logo } from './logo.svg'`
5. attempt to build source code with storybook

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react` 3.3.15

### Affected platforms 

Mac 10.13.3

### Screenshots / Screencast / Code Snippets (Optional)

Currently using this in my `.storybook/webpack.config.js`

```js
module.exports = config => {
  const babelLoader = config.module.rules.find(
    rule => rule.loader && rule.loader.indexOf('babel-loader') > 0
  )
  if (babelLoader) {
    babelLoader.query.plugins.unshift(require('babel-plugin-macros'))

    babelLoader.query.plugins.push([
      require.resolve('babel-plugin-named-asset-import'),
      {
        loaderMap: {
          svg: {
            ReactComponent: 'svgr/webpack![path]',
          },
        },
      },
    ])
  }

  config.module.rules.push({
    test: /\.svg$/,
    loader: require.resolve('file-loader'),
  })

  return config
}
```

**Comment by craigcoles** [comment]
@mattfysh Did you ever find a solution to this issue? I am experiencing the same issue now.

**Comment by mattfysh** [comment]
@craigcoles - only the `.storybook/webpack.config.js` from above, it works well enough for now
