### ISSUE TITLE
Multiple cross-depencies call = "Story of ... named ... already exists"

### ISSUE THREAD

**Issue by Inateno** [storybooks/storybook#3198]
Hi.

I'm running a critical issue, and after hours of browsing issues, I didn't find anything relevant.

Also, because I'm not sure how storybook is working I don't have steps to reproduce so first it would help me if you can tell me if I'm wrong.

It is a project with Lerna, I have several dependencies and some of them are requiring others (at the same level).
Here is how my project looks like:

Project

- Panel
- Changelog
- Header
- GeneralError
- ...

**Panel** is an independent module.
**Changelog** is importing Panel
**Header** is importing Changelog
**GeneralError** is importing Header

When running build-storybook everything is fine and when I run the start-storybook I got the error:
**Story of "Panel" named "with child" already exists**

If I search in the preview file "Panel",module there are 3 occurrences. So the build is including it 3 times right?

If I do a global search into the project with "storiesOf" I can see that Panel exist only once.

Why is this happening?

Maybe my webpack config file is broken?
Is there a way to add a "skipDuplicates" attribute?

Hope this is understandable.
Thanks

**Comment by igor-dv** [comment]
Where is the configuration of the Storybook is located?  Can you please share your config.js file?

**Comment by Inateno** [comment]
The file is in ./storybook

Here is it:

````
import React from 'react'
import { configure, addDecorator } from '@storybook/react'

import './storybook.css';

addDecorator((story) =>
    <div style={{padding:"10px"}}>
        {story()}
    </div>
);

function loadStories () {
    require('glob-loader!./stories.pattern')
}
configure(loadStories, module);
````

**Comment by igor-dv** [comment]
> The file is in ./storybook

Where the `./storybook` is places =) This is important since you are in a monorepo. 

If it's placed in root, probably `require('glob-loader!./stories.pattern')` brings you stories even from the node_modules of every package. And since A lot of things are dependent on `Panel`. you will get it many times. 

Try to exclude node_modules from the glob pattern.

**Comment by Inateno** [comment]
./storybook is in the top folder with /packages .eslintrc .lerna.json etc....

I try.

**Comment by Inateno** [comment]
Okay, I can't find the proper path to avoid node_modules with glob-loader.
Nothing in the doc and trying regex is not working.

https://github.com/seanchas116/glob-loader

Any idea?

**Comment by igor-dv** [comment]
Yeah, it's a hard one. BTW, where are your stories located?

**Comment by Inateno** [comment]
My stories are located at the same level than package src.

Example:

- Package
- - Header
- - - src/index.jsx
- - - src/index.story.js

**Comment by igor-dv** [comment]
Oh, so maybe you can specify a `src` dir in glob pattern ?

**Comment by Inateno** [comment]
It seems to work with the pattern ../packages/*/src/*.story.js
Not the best but at least it's working (for now).

Well I don't know why my mate used "glob-loader", I'll discuss about this, also there is not a lot of documentation on storybook about the "config.js" file (why not using only a webpack config?).

I'm new here and I'll try to push as much as I can.

Thanks for the help.
