### ISSUE TITLE
Support for custom webpackDevMiddleware options?

### ISSUE THREAD

**Issue by awright415** [storybooks/storybook#32]
I'd like to try out storybook in a Docker project that uses boot2docker (picking up the changes using webpack polling). Everything seems to work properly by providing a `watchOptions.poll` value in the webpackDevMiddleware options. Are you open to making those options configurable? If so, any preference on how it should be implemented?

(Edit: Included `lazy: true` as an option originally by mistake)

**Comment by arunoda** [comment]
Yes. Sure. I'm open to that.

Let's do like this.

* We support another config file called `webpack.devoptions.json` (or whatever the name works best)
* We can add additional config inside that.
* Then let's use it here with these default options: https://github.com/kadirahq/react-storybook/blob/master/src/server/index.js#L45

That's how I like to do it. But, I am open to suggestions.

**Comment by mking-clari** [comment]
Here is another reason why this would be good. I would like to use React Storybook to test Redux containers which make API requests to my backend. I think there's room for a middle ground between developing the full-fledged app (which wouldn't use Storybook) and developing pure UI components (which wouldn't make API requests). For example, I have a search result container that I want to develop in isolation.

**Comment by novascreen** [comment]
@awright415 what OS are you on?

I'm also trying to run Storybook inside of Docker (on Windows)

I tried adding
```
  watchOptions: {
    poll: 1000,
  },
```
to my webpack config and I see a bundle rebuilding, but after that nothing in Storybook is actually updates.

**Comment by ndelangen** [comment]
This is supported now:
https://github.com/storybooks/storybook/blob/67d6af3670e93364590a9a9423442cc6ebc0eb12/app/react-native/src/server/middleware.js#L49
