### ISSUE TITLE
More control over decorators for addon developers

### ISSUE THREAD

**Issue by mnmtanish** [storybooks/storybook#320]
Allow addon developers more control over decorators. Sometimes they may need to apply decorators to only some parts exported by the addon or ignore them completely.
Example usecase: https://github.com/kadirahq/react-storybook-addon-info/issues/40

That being said, this makes addons behaviour more ambiguous and harder to debug.

**Comment by arunoda** [comment]
I hope we already discussed about this.

**Comment by mnmtanish** [comment]
Need to reopen

**Comment by ndelangen** [comment]
#1209 Will be discussed for api-v2
