### ISSUE TITLE
[React] `yarn test` fail after getstorybook

### ISSUE THREAD

**Issue by Quramy** [storybooks/storybook#3214]
### Issue details

After `getstorybook` into create-react-app projects, `yarn test` throws the following error:

```
2018-03-14 18:55 node[1827] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-03-14 18:55 node[1827] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-03-14 18:55 node[1827] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
```

`yarn test` calls Jest in file watching mode by default, and I found that `CI=true yarn test` (single run mode) does not throw the error. 

### Steps to reproduce

```sh
create-react-app storybook-sample
cd storybook-sample
yarn add @storybook/cli@3.4.0-rc.2
yarn run getstorybook
yarn test
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.0-rc.2

### Affected platforms 

- OS: macOS Sierra(10.12.6)
- Node.js: 8.9.3
- yarn: 1.3.2

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```

**Comment by igor-dv** [comment]
I think it is not related to Storybook. Take a look here -  https://stackoverflow.com/questions/41657754/testing-with-jest-failed-with-error-error-watching-file-for-changes-emfile/41661452

**Comment by Quramy** [comment]
Thanks for your link. I’ll check it later :smile:

**Comment by caspic** [comment]
Hi, have the same issue:

- macOS High Sierra: 10.13.3 (17D102)
- node: 8.10.0
- npm: 5.6.0
- storybook/react: "^3.3.14"

uninstall storybook/react helped

**Comment by dangreenisrael** [comment]
@Quramy @caspic could you post the output of `watchman -v`

**Comment by caspic** [comment]
@dangreenisrael 
`zsh: command not found: watchman`
I haven't installed it. Is it a dependency?

**Comment by dangreenisrael** [comment]
It is, but you don't need to have installed globally. Jest uses it to watch files. Could you post the `devDependencies` section of your `package.json file`?

**Comment by caspic** [comment]
I use create-react-app tool everything is underhood. Here is [package.json](https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/package.json) for react-scripts

**Comment by dangreenisrael** [comment]
@caspic I want to see the version of you packages. I wonder is there is a version conflict with watchman. Perhaps there is something we can put in peer dependencies.

**Comment by dangreenisrael** [comment]
@caspic, could you also post your versions for the following:
```
    "react": "-------",
    "react-dom": "-------",
    "react-scripts": "------"
```

**Comment by caspic** [comment]
@dangreenisrael got it! here:
```
"dependencies": {
    "prop-types": "^15.6.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.1",
    "@storybook/react": "^3.3.14"
  },
```

```
"devDependencies": {
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.18.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0"
  }
```

**Comment by dangreenisrael** [comment]
Could you try using storybook version `^3.4.0-rc.2`?

Also, storybook should be a `devDependency`, as you don't want to bundle it and ship a dependency that you only use for development to users.

**Comment by Quramy** [comment]
@dangreenisrael Sorry for my late reply.

> watchman -v

watchman was not installed into local machine.

And I tried to reproduce this issue after `brew install watchman`, but I couldn't. So, my local error is resolved but I don't know what cause this issue in essence 🤔

**Comment by igor-dv** [comment]
I think we can close.

**Comment by carlorizzante** [comment]
Same problem for me, all good until I add Storybook to my project (create-react-app). The "yarn test" fails with the error at the top of this page.

Installing (or updating) Watchman via Brew seems to fix the issue.
