### ISSUE TITLE
Extending webpack config fails without user-provided `module` property (storybook/vue)

### ISSUE THREAD

**Issue by mattixittam** [storybooks/storybook#3215]
### Issue details

This issue is exactly as described in https://github.com/storybooks/storybook/issues/1467, only now with `@storybook/vue`. I would have tried the fix from that story, but the structure of the part where the webpack config is extended is a little more ancient in storybook-vue it seems and I couldn't quite make it work.

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/vue 3.3.15

**Comment by igor-dv** [comment]
What if you just add empty rules?

```js
{
   module: {
      rules: [],
   },
   plugins: [
     /// ,,,,
   ]
}
```

**Comment by mattixittam** [comment]
Yeah, that's the workaround, but that doesn't seem like something you want a user to have to think of.

**Comment by Hypnosphi** [comment]
Looks like we just need to apply https://github.com/storybooks/storybook/pull/1468 fix to other frameworks

**Comment by Hypnosphi** [comment]
Fix for vue released as [`3.4.0-rc.4`](https://github.com/storybooks/storybook/releases/tag/v3.4.0-rc.4). Please do the same for angular and polymer

**Comment by igor-dv** [comment]
It should've been fixed with moving server/config.js to the core

**Comment by Hypnosphi** [comment]
Yes, but not for 3.4

**Comment by igor-dv** [comment]
I think it can be closed already.
