### ISSUE TITLE
'withMarkdownNotes' isn't included in latest npm package (3.3.15)

### ISSUE THREAD

**Issue by cameron-lindsay** [storybooks/storybook#3220]
## Reproduce
* Create a new react storybook project
* Install the latest '@storybook/addon-notes' npm package (3.3.15 at this time)
* Import 'withMarkdownNotes' into a story module and hook it up as per the documentation
* Run storybook
* In browser, navigate to your story.
* Error appears: "Object(...) is not a function" etc....

I have examined the package and the code for 'withMarkdownNotes' simply isn't there. 'withNotes' still works fine.

**Comment by danielduan** [comment]
@Hypnosphi @shilman any changes here? sounds kind of serious

**Comment by Hypnosphi** [comment]
It should be present in `@storybook/addon-notes@3.4.0-rc.2`

**Comment by dangreenisrael** [comment]
@cameron-lindsay Can you post the `dev-dependencies` portion of your `package.json` file?

**Comment by danielduan** [comment]
is this intended to be released with 3.4? if so, let's close this.
