### ISSUE TITLE
Feature Request - Standalone React Native Build

### ISSUE THREAD

**Issue by f0rr0** [storybooks/storybook#3224]
### Issue details

This is a feature request. I believe something similar for the web version already exists. To add context, this isn't for an Expo for CRNA app. Just wondering if there's possibility for an alternative to https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh

**Comment by danielduan** [comment]
Can you go into more detail? What do you think we should separate here? Storybook RN from the RN bundler?

**Comment by f0rr0** [comment]
I want to be able to build a production mode RN app with the storybook UI that doesn’t need s server running.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by danielduan** [comment]
There's been discussions about separating the app from the desktop app.

Main problem - the Storybook app state is on the browser side and communicates over websocket to the RN app. We will need to refactor that if we want to split it.

Then, the concern here will be that addons like knobs will potentially not work anymore.

If you'd like to help us, let's discuss.

**Comment by f0rr0** [comment]
For sure, I’d be down to help. I’ve been using storybook for a while now. If I remember correctly, there didn’t use to be an in-app UI to change stories. You’d have to switch stories via the web UI to see the changes in the simulator. But there’s a drawer layout navigation now in the app. Of course things like knobs won’t work. I’m afraid I’ve not delved into the code yet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by f0rr0** [comment]
Got this to work:

```js
/* eslint-disable global-require */
import { AppRegistry } from 'react-native';
import { getStorybookUI, configure } from '@storybook/react-native';

configure(() => {
  require('./stories');
}, module);

const StorybookUI = getStorybookUI({
  port: 7007,
  onDeviceUI: true
});

AppRegistry.registerComponent('8fit', () => StorybookUI);

export default StorybookUI;
```

```js
module.exports = (_, { module }) => ({
  entry: './storybook/index.js',
  module: {
    ...module,
    rules: [
      {
        test: /\.js?$/,
        exclude: '/node_modules/',
        use: [
          {
            loader: 'babel-loader'
          }
        ]
      },
      ...module.rules
    ]
  }
  // any other haul config here.
});
```
For regular development:
```
storybook start -p 7007 --haul ./storybook/webpack.haul.storybook.js
```

Bundle standalone:
Change entry file here: can be passed as an argument from xcode.
https://github.com/facebook/react-native/blob/56971bbb152babb0ee745d7abd55f5a5d35ae004/scripts/react-native-xcode.sh#L108
