### ISSUE TITLE
Build react native static app? 

### ISSUE THREAD

**Issue by lsps9150414** [storybooks/storybook#3235]
Hey guys, is it possible to do [Exporting Storybook as a Static App](https://storybook.js.org/basics/exporting-storybook/) for react native so that I can run my mobile storybook without running the storybook server?

### My goal
I'm building a storybook for my react native component library and my goal is to publish it to Expo so that my teammates can check out the components simply by opening the storybook app with Expo without running the storybook server locally.

I've tried `exp publish` with storybook server running but the app crashed when opened in Expo client app.

**Comment by Hypnosphi** [comment]
Looks similar to #3224
