### ISSUE TITLE
storyshoots and graphql add-on do not work together

### ISSUE THREAD

**Issue by PetrSnobelt** [storybooks/storybook#3236]
### Issue details

When I have graphql addon in place and try to add/use storyshots addon - graphql test do not process graphql sample story

### Steps to reproduce

- Add graphql and storyshots addons, 
- setup graphql addon sample
- setup storyshoots addon 

- run tests 

expected: graphql story pass or ignored but error occured about including css file.
Even when I disable including css in jest using something like this 
```
moduleNameMapper: {
    "\\.(css|jpg|png)$": "<rootDir>/etc/empty-module.js",
  },
```
It still do not pass with something like this 
```
Error: Uncaught [TypeError: document.body.createTextRange is not a function]
          at reportException (/Users/petrsnobelt/Projects/kiwi-on-nitro/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at invokeEventListeners (/Users/petrsnobelt/Projects/kiwi-on-nitro/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
```
### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.3.15
- @storybook/addon-graphql 3.3.15
- @storybook/addon-storyshots 3.3.15

I know I can disable some stories using regexp in storyshoots config, or have separate config for storyshoots, but it is not fine to maintain two configs or maintain regexp

**Comment by danielduan** [comment]
As far as I know, the GraphQL addon hasn't been updated in a while. It definitely needs some love.

Do you think you can put in some time to fix this?
