### ISSUE TITLE
How to run storybook with dist folder's bundle.js minified js file instead of the original source code component files?

### ISSUE THREAD

**Issue by adamchenwei** [storybooks/storybook#3240]
### Issue details

I want to run storybook with the dist bundle instead of the original source code, so its kinda become a demostration app for all the components but only with the dist bundle I created... Unless if there is still way, but I just need to bundle things differently just for storybook? Is that even possible?

Thanks
### Steps to reproduce

I can't reproduce a steps, as its more of a new way of doing things I guess.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react latest

### Affected platforms 
All

### Screenshots / Screencast / Code Snippets (Optional)

I really do not know if its possible...

**Comment by Hypnosphi** [comment]
I'm not sure I understand your usecase correctly, but you probably can do something like this:

```
// somewhere in your entry point

window.components = {
  MyButton,
  MyInput
}
```

```
// my-button.stories.js

import './relative-path-to-your-bundle-js'
import React from 'react'
import { storiesOf } from '@storybook/react'

const {MyButton} = window.components

storiesOf('MyButton', module)
  .add('with text', () => (
    <MyButton onClick={action('clicked')}>Hello Button</MyButton>
  ))
```

**Comment by adamchenwei** [comment]
@Hypnosphi that's an interesting approach... hum... let me think about it

**Comment by lmenus** [comment]
Hi @adamchenwei, I wonder what's the use case for using a build bundle as a source? If I understand it correctly, in order to load those components, you would need to include Storybook inside your production bundle, which would increase it size. So I wonder why you want to do this?

**Comment by adamchenwei** [comment]
hey, the usage is to uploading compiled code instead of source code into an AWS instance for development demonstration for the public, but without having to risk uploading the whole source code into it directly.

Hope that clarifies a bit about the usage part.

**Comment by lmenus** [comment]
@adamchenwei It would be probably more helpful to see your code, but if you import only your stateless components into Storybook, you not only don't risk uploading the whole source, but you trim the fat since your components shouldn't have any imports maybe except for React-related imports and CSS.

**Comment by adamchenwei** [comment]
interesting i can look into it! thanks
