### ISSUE TITLE
Issues with CSSModules

### ISSUE THREAD

**Issue by jpaulsen-apixio** [storybooks/storybook#3241]
### Issue details

I'm having difficulty getting CSSModules to work with storybook. I've created a webpack config for the .storybook directory to incorporate the modules:

```
const paths = require('../webpack/config').paths

module.exports = {
  entry: {
    vendor: ['bootstrap-loader/extractStyles']
  },
  module: {
    rules: [
      // Apply loader
      {
        test: /^((?!\.module).)*scss$/,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader?sourceMap'
        ]
      },
      {
        test: /\.module.scss$/,
        use: [
          'style-loader?singleton',
          'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]__[hash:base64:5]',
          'postcss-loader?sourceMap',
          'sass-loader?sourceMap',
          {
            loader: 'sass-resources-loader',
            options: {
              // Provide path to the file with resources
              resources: [`${paths.node}/bootstrap/scss/bootstrap.scss`, `${paths.source}/scss/**/*.scss`]
            }
          }
        ]
      }
    ]
  },
};
```

When I run the storybook, the outer shell renders, but the inner iFrame looks like this:

![storybook](https://user-images.githubusercontent.com/37089206/37625208-3f40e08e-2b88-11e8-899d-efa8e21baedf.png)

There's really no stack trace to speak of, so it's exceptionally difficult to debug.

### Steps to reproduce

Here is the repo:

https://github.com/yazdog8/launchpad

If you don't want to use yarn...just use npm to install dependencies. From there all you need to do is run the storybook command `npm run storybook` or `yarn storybook`. This will start the server at http://localhost:9001/.

If you remove the css modules from some of the root modules, they will actually render (like the welcome.js). Otherwise you get the error mentioned above.

```
preview.bundle.js:45483 TypeError: Cannot assign to read only property 'children' of object '#<Object>'
    at linkElement (preview.bundle.js:45820)
    at preview.bundle.js:45823
    at mapSingleChildIntoContext (preview.bundle.js:17946)
    at traverseAllChildrenImpl (preview.bundle.js:17819)
    at traverseAllChildrenImpl (preview.bundle.js:17835)
    at traverseAllChildren (preview.bundle.js:17890)
    at mapIntoWithKeyPrefixInternal (preview.bundle.js:17966)
    at Object.mapChildren [as map] (preview.bundle.js:17988)
    at linkElement (preview.bundle.js:45820)
    at linkElement (preview.bundle.js:45818)
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- "storybook/addon-actions" 3.3.15
- "storybook/addon-backgrounds" 3.3.15
- "storybook/addon-info" 3.3.15
- "storybook/addon-knobs" 3.3.15
- "storybook/addon-links" 3.3.15
- "storybook/addon-notes" 3.3.15
- "storybook/addon-options" 3.3.15
- "storybook/addons" 3.3.15
- "storybook/react" 3.3.15

I am running webpack 4.1.1 as my webpack server for the regular build. Not sure if this is causing the issue.

**Comment by Hypnosphi** [comment]
> I am running webpack 4.1.1 as my webpack server for the regular build. Not sure if this is causing the issue.

This is most likely the case. Webpack 4 support is being added in #3148

**Comment by jpaulsen-apixio** [comment]
Thanks for the response! I see that you might be ready for an Alpha release soon. I'll wait for that, upgrade and see if that might fix the problem.

**Comment by Hypnosphi** [comment]
It turns out the problem is not related to webpack or even to storybook. If I change `Admin` component from `src` to this, `yarn start` breaks as well:

```
class Admin extends Component {
  render () {
    return (
      <div>
        <div styleName='foo'>Admin Section</div>
      </div>
    )
  }
}
```

Looks like `react-css-modules` package doesn't work well with React 16. See e.g. https://github.com/gajus/react-css-modules/issues/200

I would advice to use a bit more verbose but a lot less magical syntax for CSS modules:

```
import React from 'react'

import styles from './welcome.module.scss'

const Welcome = () => {
  return (
    <div className={styles.welcome}>
      <div className={styles.inner}>
        <h1>Welcome to the Company Storybook</h1>
        <p>This is a UI component development environment for interdisciplinary team collaboration of core and shared components in the Company web application.</p>
        <p>This page was built using <a href='https://storybook.js.org/' target='_blank'>React Storybook</a></p>
      </div>
    </div>
  )
}

export default Welcome
```
