### ISSUE TITLE
Using Flow, ReactNode breaks Prop Table in addon-info

### ISSUE THREAD

**Issue by codequistador** [storybooks/storybook#3256]
### Issue details

I'm using Flow in my project and trying to set up React Storybook with addon-info. Some of my components work fine while others fail to generate a prop table. Here is what I've narrowed it down to.

If I do this:

```js
import React, {
  PureComponent,
  type Node as ReactNode
} from 'react'
```
plus
```js
export default class ComponentX extends PureComponent<{
  children?: ReactNode,
  label?: ReactNode
}>
```
I don't get a prop table for ComponentX

But if I do this:

```js
import * as React from 'react'
``` 
plus
```js
export default class ComponentX extends PureComponent<{
  children?: React.Node,
  label?: React.Node
}>
```
I get a prop table for ComponentX.

According to these docs this is a supported way of doing imports of types: https://flow.org/en/docs/react/types/

### Steps to reproduce

Import React types manually (`type Node as ReactNode`) and set a prop to `ReactNode`. The prop table in addon-info does not work. 

### Please specify which version of Storybook and optionally any affected addons that you're running

- React Storybook 3.3.15
- addon-info 3.3.15

**Comment by codequistador** [comment]
Please let me know if there are questions I can answer or if more info is needed.

**Comment by danielduan** [comment]
fixed in https://github.com/storybooks/babel-plugin-react-docgen/issues/42
clear your lock files, reinstall, and let me know if this doesn't fix your issue
