### ISSUE TITLE
storyshots keep produce duplicate stories in each component when I initiate in each component's `.test.js` file.

### ISSUE THREAD

**Issue by adamchenwei** [storybooks/storybook#3263]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
I expect when I include these lines inside each component's `xxx.test.js` file, it only run on the specific component's `xxx.stories.js` file, instead of including the whole app's stories into each component' `.snap` file, which is duplicate!

### Steps to reproduce

run `npm run test` with https://github.com/adamchenwei/storybook-playground/tree/master/storyshot

you will see the the stories of the whole app is included in each component's `snap.js` file

### Please specify which version of Storybook and optionally any affected addons that you're running

@storybook/react storybook/react: "^3.3.15"
@storybook/addon-storyshots storybook/addon-storyshots: "^3.3.15"
@storybook/addon-storyshots 3.3.15

### Affected platforms 

all

### Screenshots / Screencast / Code Snippets (Optional)
below is a example I get from my test repo I show the link above, one of the xxx`.test.js.snap` file. all the components are in different folder, and they all included here in each component's snap file.

code I included in each `.test.js` file is
```js
import initStoryshots from '@storybook/addon-storyshots';
initStoryshots();
```

result looks like
```js
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`ChildComponent222 Component renders as expected 1`] = `
<h2>
  My Custom ChildComponent222 Has Value Of 
  none
</h2>
`;

exports[`Storyshots Component/App/Stand Alone another change 1`] = `
<div
  className="App"
>
  <header
    className="App-header"
  >
    <img
      alt="logo"
      className="App-logo"
      src="IMAGE_MOCK"
    />
    <h1
      className="App-title"
    >
      Welcome to React
    </h1>
    <h2>
      everything111
    </h2>
  </header>
  <p
    className="App-intro"
  >
    To get started22, edit 
    <code>
      src/App.js
    </code>
     and save to reload.
  </p>
</div>
`;

exports[`Storyshots Component/App/Stand Alone the default change 1`] = `
<div
  className="App"
>
  <header
    className="App-header"
  >
    <img
      alt="logo"
      className="App-logo"
      src="IMAGE_MOCK"
    />
    <h1
      className="App-title"
    >
      Welcome to React
    </h1>
    <h2 />
  </header>
  <p
    className="App-intro"
  >
    To get started22, edit 
    <code>
      src/App.js
    </code>
     and save to reload.
  </p>
</div>
`;

exports[`Storyshots Component/ChildComponent/Stand Alone another change 1`] = `
<h2>
  My Custom Component Has Value Of 
  my thing
</h2>
`;

exports[`Storyshots Component/ChildComponent/Stand Alone another change 2`] = `
<h2>
  My Custom Component Has Value Of 
  my thing
</h2>
`;

exports[`Storyshots Component/ChildComponent/Stand Alone another change 3`] = `
<h2>
  My Custom Component Has Value Of 
  my thing
</h2>
`;

exports[`Storyshots Component/ChildComponent/Stand Alone the default change 1`] = `
<h2>
  My Custom Component Has Value Of 
  none
</h2>
`;

exports[`Storyshots Component/ChildComponent/Stand Alone the default change 2`] = `
<h2>
  My Custom Component Has Value Of 
  none
</h2>
`;

exports[`Storyshots Component/ChildComponent/Stand Alone the default change 3`] = `
<h2>
  My Custom Component Has Value Of
  none
</h2>
`;

exports[`Storyshots Component/ChildComponent222/Stand Alone another change 1`] = `
<h2>
  My Custom ChildComponent222 Has Value Of 
  my thing
</h2>
`;

exports[`Storyshots Component/ChildComponent222/Stand Alone another change 2`] = `
<h2>
  My Custom ChildComponent222 Has Value Of 
  my thing
</h2>
`;

exports[`Storyshots Component/ChildComponent222/Stand Alone the default change 1`] = `
<h2>
  My Custom ChildComponent222 Has Value Of 
  none
</h2>
`;

exports[`Storyshots Component/ChildComponent222/Stand Alone the default change 2`] = `
<h2>
  My Custom ChildComponent222 Has Value Of 
  none
</h2>
`;

```

**Comment by igor-dv** [comment]
Sadly the expectation is wrong

For the out-of-the-box usage, it will be inefficient (performance-wise) to separate storyshots to per-story tests, because it runs a whole storybook in order to get stories from it. 

You have a few ways to perform:
1. Use only one Storyshots test to generate a one big snapshot.
2. Use a multi-snapshot option that will create snapshots according to the stories.
3. Use multiple snapshots tests and use `storyKindRegex`/`storyNameRegex` options to limit specific stories you want to test - but it will be very slow as I said ☝️ , because storybook will be built for every test. 

Probably in the nearest future (for the v4.0 release) we will make changes to the addon that will address some of these issues.

**Comment by adamchenwei** [comment]
@igor-dv would you elaborate on how to do 
`Use a multi-snapshot option that will create snapshots according to the stories.`

**Comment by adamchenwei** [comment]
I currently have this config to load seperated stories file in each component folder, what else I need to do so they can generate story shot the same way as how snapshot is generated in each component folder?

```
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

**Comment by Gidgidonihah** [comment]
@adamchenwei You closed the issue. What solution did you come up with?

**Comment by adamchenwei** [comment]
@Gidgidonihah 

try this, put an index.js file into your source folder


```
import expect from 'expect';
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots'; //eslint-disable-line

initStoryshots({
  storyKindRegex: /^((?!.*?DontTest).)*$/,
  test: multiSnapshotWithOptions({}),
});

// default test;
describe('Our first test', () => {
  it('should pass', () => {
    expect(true).toEqual(true);
  });
});

```

**Comment by hisapy** [comment]
This error is still happening though when I checked the generated .storyshot file, the stories were not repeated. Basically when you run `npm run test __test__/Storyshot.test.js` it seems that each story is tested twice.
