### ISSUE TITLE
Storybook and @vue/cli 3.0

### ISSUE THREAD

**Issue by aderaaij** [storybooks/storybook#3267]
### Bug

I've tried to add Storybook to a project which was set-up with `@vue/cli` 3.0. Adding storybook with `getStorybook` works fine, but when trying to run it asks for `babel-core`, wether `@babel/core` is installed or not. I figure that it could work with a custom Webpack config in `./storybook` but this overrides the Vue config completely.

### Steps to reproduce

Install a new project with `@vue/cli` (3.x), add storybook and try to run it.

### Please specify which version of Storybook and optionally any affected addons that you're running

- Storybook / vue @storybook/vue 3.3.15

### Affected platforms 

-`@vue/cli`

**Comment by danielduan** [comment]
sounds like this might be related to https://github.com/storybooks/storybook/issues/3335

**Comment by beeplin** [comment]
Hey guys, I have identified the problem: @vue/cli v3 beta.11 uses `vue-loader` v5, which is not compatible with storybook that is using `vue-loader` v3. 

According to https://vue-loader.vuejs.org/migrating.html#notable-breaking-changes, just add a `webpack.config.js` to `.storybook` folder and write the following in it: 

```js
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = (baseConfig, env, defaultConfig) => {

  defaultConfig.plugins.push(new VueLoaderPlugin())

  return defaultConfig;
};
```
This would do the trick.

**Comment by peakcool** [comment]
@beeplin  wow.....thanks, it's work

**Comment by pksunkara** [comment]
I am working on https://github.com/pksunkara/vue-cli-plugin-storybook

**Comment by aradjdi** [comment]
this minimalist config work for me : 
```
{
  "scripts": {
    "storybook": "start-storybook -p 9001 -c .storybook"
  },
  "dependencies": {
    "vue": "^2.5.2"
  },
  "devDependencies": {
    "@storybook/vue": "^3.4.10",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-vue-jsx": "^3.7.0",
    "glob-loader": "^0.3.0",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "vue-loader": "^13.3.0"
  }
}
```

**Comment by garretmh** [comment]
The problem is with getting Storybook to work with Vue CLI specifically, not just Vue.

**Comment by pksunkara** [comment]
My storybook plugin for vue-cli (https://github.com/pksunkara/vue-cli-plugin-storybook) has been working since last week. I think we can close this issue.

**Comment by elisiondan** [comment]
In my case all I had to do was to run `npm install -D vue-loader@15.9.6`

We're using `"@storybook/vue": "^6.2.9"`
