### ISSUE TITLE
ReactDOM.createPortal - Target container is not a DOM element.

### ISSUE THREAD

**Issue by joetidee** [storybooks/storybook#3268]
I am using `ReactDOM.createPortal` to place a component into a location in the DOM. The error `Target container is not a DOM element.` is being thrown.

### Steps to reproduce
this functional component will place a supplied component into the DOM location 'toast-container':
`const Toast = ({ children }) => ReactDOM.createPortal(children, 'toast-container');`

This `Toast` component is being included within a story:
```
storiesOf('Elements/Toast', module)
    .add('Test', () => (
        <InlineWrapper>
            <Toast>
                <ToastTemplate
                    id="test"
                    type='success'
                >
                Your details have been saved.
                </ToastTemplate>
            </Toast>
        </InlineWrapper>
    ));
```

I have defined the DOM location in the html file located at `storybook/index.html` and have also tried doing the same in 'storybook/iframe.html' :
```
<body style="margin: 0;">
    <div id="root"></div>
    <div id="toast-container"></div>
    <script src="static/bundle.js"></script>
</body>
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.2.3
- @storybook/addon-options 3.2.4

**Comment by danielduan** [comment]
> The first argument (child) is any renderable React child, such as an element, string, or fragment. The second argument (container) is a DOM element.

You passed in a string instead of a DOM element.

**Comment by lukaskoeller** [comment]
#### I am having the same problem but a different cause.

🚫  Throws Error when I want to show the Modal right away (`true`) without the need to first change `isVisible` state through an `onClick` event.
> Target container is not a DOM element.
```js
const [isVisible, setIsVisible] = useState(true);
```

✅  Works perfectly. When I click the "Open Modal" Button, the Modal opens as expected
```js
const [isVisible, setIsVisible] = useState(false);
```

**`.storybook/preview.js`**
```js
addDecorator(story => {
  const theme = useTheme(baseTheme);

  return (
    <>
      <ThemeProvider {...theme}>
        <Global styles={ css(globalStyles) } />
        <div id="app-root">
          {story()}
        </div>
        <div id="modal-root"></div>
      </ThemeProvider>
    </>
  )
});
```
