### ISSUE TITLE
Create documentation section for using TypeScript with Storybook

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#3270]
If you are creating a issue to track work to be completed, start here:
### Work summary

There is a decent amount of config needed for TypeScript to work within Storybook. We should document the TS definitions, scripts, configs, etc. needed to get all the features working.

### Where to start

A new page within `/docs` is probably the best way to go.

### Acceptance criteria

* Installing TS #1778 
* Using TS with addons such as Info https://github.com/storybooks/storybook/issues/1519
* Running Storybook with TS compilation
* Any other tips

### Who to contact

I personally don't use TS but it is a widely requested topic within our GitHub issues.

**Comment by tsiq-swyx** [comment]
i'll give this a crack next week

**Comment by igor-dv** [comment]
Probably it is time to add a label for TypeScript.

**Comment by estaub** [comment]
@tsiq-swyx, Here's some grist: 

- https://medium.com/@mtiller/storybook-react-typescript-and-jest-c9059ea06fa7  (I successfully* just used this as a guide; I'm a storybook noob)
- http://www.joshschreuder.me/react-storybooks-with-typescript/

*successfully: I'm on webpack 4, using the 4-compatible version of awesome-typescript-loader, which breaks on webpack 3, which is used in storybook 3.  Everything (so far) works fine with storybook 4.0.0-alpha.1.  I'd definitely include a webpack version caveat.

**Comment by tsiq-swyx** [comment]
appreciated! taking surprisingly long to get company approval, but def keen
to get started on this.

**Comment by tsiq-swyx** [comment]
Hi friends,

I am going to start work on this now. Appreciate the wait.

**Comment by tsiq-swyx** [comment]
Going to document how to get it to look a bit nicer too like this:

![image](https://user-images.githubusercontent.com/35976578/38376038-ac02b432-38c5-11e8-9aed-f4fa2e258f60.png)

**Comment by lukepighetti** [comment]
Any chance we can get a storybook installer that follows up https://github.com/Microsoft/TypeScript-React-Starter ? I'm not looking forward to setting up Storybook as a react noob.
