### ISSUE TITLE
Refactor CLI to use `npm` and `yarn` instead of third party packages

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#3274]
### Work summary

Our CLI relies on libraries like `latest-version` to check for the latest version of any published package. This creates a problem when the user is behind a corporate firewall and requires a proxy to access the internet.

#3060 

### Where to start

https://github.com/storybooks/storybook/blob/master/lib/cli/lib/helpers.js#L12

### Acceptance criteria

remove dependencies on `latest-version` and call `npm` or `yarn` when checking for latest version and installing

### Who to contact

Me

**Comment by Hypnosphi** [comment]
Released as [`3.4.0-rc.4`](https://github.com/storybooks/storybook/releases/tag/v3.4.0-rc.4)
