### ISSUE TITLE
 StaticInjectorError(NewModule)[NewComponent -> <Service> ]:

### ISSUE THREAD

**Issue by vamc-anne** [storybooks/storybook#3287]
### Tried storybook for Angular for my project with the setup mentioned in https://storybook.js.org/basics/guide-angular/ 

When I run my storybook on 9001, storybook beaks and throws the error
core.js:1448 ERROR Error: StaticInjectorError(NewModule)[NewComponent -> LoginService]: 
  StaticInjectorError(Platform: core)[NewComponent -> LoginService]: 
    NullInjectorError: No provider for LoginService!

### Steps to reproduce

- I have a Header component in Core module 
- Header component depends on Login service in Login module which basically deals with auth
- Login and header are connected by AppModule
- Try loading Header component in storybook, it breaks with the error below

![image](https://user-images.githubusercontent.com/6346501/37900183-1fc0c3f4-310b-11e8-9be8-bfb621e55d98.png)

### Version of story book
- @storybook/angular": "^3.3.15"
### Version of angular
- "@angular/common": "^5.2.8",
- "@angular/compiler": "^5.2.8",

### Affected platforms 
- Chrome on mac

### story for the component 
```js
import { storiesOf } from "@storybook/angular";
import { action } from "@storybook/addon-actions";
import { HeaderComponent } from "../src/app/core/components/header/header.component";

storiesOf("Core", module).add("Header menu component", () => ({
  component: HeaderComponent,
}));
```
### Expected
Story book should show the component

**Comment by igor-dv** [comment]
This is a very basic example of how to use the story with an Angular component. In most of the cases, you have to provide module metadata that meets all the needed dependencies, like you would do it with your regular module in your app.

I would suggest you using the latest **3.4** version (currently in a release call) that has a lot of improvements for angular.

[Here](https://release-3-4--storybooks-angular.netlify.com/?selectedKind=Metadata%7CShared&selectedStory=Shared%201&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) is a live exmaple of how to add a custom module metadata to your story (with the 3.4 version).

**Comment by vamc-anne** [comment]
@igor-dv , thank you!
