### ISSUE TITLE
Jest code coverage with storyshots (Angular)

### ISSUE THREAD

**Issue by michaelgeorgeattard** [storybooks/storybook#3289]
When using `imageSnapshot` test with `storyshots`, is it possible to get accurate coverage numbers?

With `renderOnly` I am getting the accurate numbers:

```
import initStoryshots, { renderOnly } from "@storybook/addon-storyshots";

initStoryshots({
    suite: "Image storyshots",
    test: renderOnly
});
```

However with `imageSnapshot` I am getting wrong coverage numbers:

```
import initStoryshots, { imageSnapshot } from "@storybook/addon-storyshots";

initStoryshots({
    suite: "Image storyshots",
    test: imageSnapshot({})
});
```

I am generating the image snapshots on a running instance of the playground.

**Comment by michaelgeorgeattard** [comment]
Any updates on this please?

**Comment by Hypnosphi** [comment]
cc @igor-dv

**Comment by Hypnosphi** [comment]
cc @thomasbertet

**Comment by penx** [comment]
+1 for a documented way of getting code coverage output from storybook stories

**Comment by penx** [comment]
that's a pretty aggressive stalebot
