### ISSUE TITLE
Do not execute "Storyshots Integrity" tests for imageSnapshot

### ISSUE THREAD

**Issue by markelog** [storybooks/storybook#3301]
### Bug or support request summary

In the `StoryShots` add-on context.

If `imageSnapshot` test is used it will also executes default `Storyshots Integrity` suite, which might take quite a bit of time –

![screen shot 2018-03-27 at 14 48 48](https://user-images.githubusercontent.com/945528/37965718-abb0cbf2-31ce-11e8-80cb-0049cf18fc24.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react@3.2.12
- storybook/addon-storyshots@3.4.0-rc.3

### Acceptance criteria

Do not execute `Storyshots Integrity` for `imageSnapshot` variation of the test, since that type of testing does not generates snapshot files

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.3`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.3)
