### ISSUE TITLE
Installing notes addon causes `yarn run storybook` to fail

### ISSUE THREAD

**Issue by paul42** [storybooks/storybook#3305]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

On ubuntu, using create-react-app and getstorybook command, adding the 'notes' addon (just installing it) causes start-storybook to fail, was trying to follow along with https://storybook.js.org/addons/using-addons/

### Steps to reproduce

install create-react-app
install storybook-cli
create new app with create-react-app
install storybook notes addon
attempt to 'yarn run storybook'

### Please specify which version of Storybook and optionally any affected addons that you're running
react-scripts@1.1.1
react@16.2.0
`@storybook/react v3.3.15`
`@storybook/addon-notes@3.3.15`

### Affected platforms 
16.04.1-Ubuntu

**Comment by Hypnosphi** [comment]
> install create-react-app
install storybook-cli
create new app with create-react-app
install storybook notes addon
attempt to 'yarn run storybook'

I assume it also includes running `getstorybook` after third step, right?

**Comment by Hypnosphi** [comment]
I can't reproduce the issue on Ubuntu 16.04

**Comment by paul42** [comment]
ah you're correct, yes.

**Comment by paul42** [comment]
I'm going back and double checking, and I think the main issue may be that I wasn't following the addons guide well - 
I used `npm install --save-dev @storybook/addon-notes` instead of `yarn add -D @storybook/addon-notes` after trying with yarn it appears to work. do you want me to close, or make a PR for the addon help page? Thanks for taking a look

**Comment by paul42** [comment]
updated repro steps:
1. `create-react-app test-app`
2. `cd test-app`
3. `getstorybook`
4. (optional) `yarn run storybook`
5. `npm i --save-dev @storybook/addon-notes`
6. `yarn run storybook`
6.1. Expected: Storybook runs
6.2 Actual: Storybook fails to run

**Comment by paul42** [comment]
made a PR for docs, if that's acceptable - not certain why installing from NPM vs Installing from yarn causes it to fail. please let me know your thoughts, thanks again for all the hard work on this great software!

**Comment by Hypnosphi** [comment]
Looks like you need to run `npm install` in your project before adding any dependencies using npm

**Comment by paul42** [comment]
I'll double check that when I get time, thanks for looking at this, @Hypnosphi

**Comment by Hypnosphi** [comment]
Documentation fix published as [`3.4.0`](https://github.com/storybooks/storybook/releases/tag/v3.4.0)
