### ISSUE TITLE
Storybook-dist not outputting babel-plugin-react-css-modules

### ISSUE THREAD

**Issue by yazdog8** [storybooks/storybook#3323]
In my current build, I have switched from react css modules to the babel-plugin-react-css-modules babel plugin as the former is deprecated. It actually runs perfectly when I run the storybook development server, but when I run `npm run build-storybook -c .storybook -o storybook_dist` (the 'build-storybook' in package.json, the build output in the rendered module doesn't convert the styleName into a class

Here's my repo: https://github.com/yazdog8/launchpad

When run in storybook server:

<img width="400" alt="screen shot 2018-03-30 at 12 58 59 pm" src="https://user-images.githubusercontent.com/1077709/38152002-687a1b7e-341a-11e8-892b-6f20440b11d7.png">
<img width="379" alt="screen shot 2018-03-30 at 12 59 19 pm" src="https://user-images.githubusercontent.com/1077709/38152003-68955358-341a-11e8-82b6-88cd5e70447c.png">
<img width="1424" alt="screen shot 2018-03-30 at 12 59 28 pm" src="https://user-images.githubusercontent.com/1077709/38152004-68ad6740-341a-11e8-821d-ea0961bdcb9d.png">

You can see that the styleNames are rendered into class and the class names match.

When I run storybook-dist:

<img width="364" alt="screen shot 2018-03-30 at 12 56 23 pm" src="https://user-images.githubusercontent.com/1077709/38152047-97dad174-341a-11e8-9c38-658dbf75cfca.png">
<img width="386" alt="screen shot 2018-03-30 at 12 56 43 pm" src="https://user-images.githubusercontent.com/1077709/38152048-97f3aa8c-341a-11e8-9f11-da3e27b339d0.png">
<img width="1423" alt="screen shot 2018-03-30 at 12 59 39 pm" src="https://user-images.githubusercontent.com/1077709/38152052-9dd901a4-341a-11e8-8e2c-22b7523e5177.png">

Style names are not being converted into css module names on the rendered react component.

I'm really not sure where the magic happens under the hood with storybook in terms of calling .babelrc or how the css modules plugin may be applied in the dist version.

**Comment by Hypnosphi** [comment]
Is there a chance that this plugin generates classNames differently depending on `process.NODE_ENV.env` being `production` or `development`?

**Comment by Hypnosphi** [comment]
AFAIR our static builds shamefully don't support custom babelrc. @danielduan are you aware of some issue about it that people could track?

**Comment by igor-dv** [comment]
@yazdog8, your repo is not available.

@Hypnosphi , Babel integration is placed in `server/config.js` which is common for both static and dev builds.

![image](https://user-images.githubusercontent.com/7867954/38190159-b68a3bf2-366b-11e8-9041-39b64802fa39.png)

Maybe there is something else.

**Comment by Hypnosphi** [comment]
I see. Looks like `babel.prod.js` is redundant then, because it's always overriden by these lines

**Comment by Hypnosphi** [comment]
@yazdog8 I get 404 when trying to open your repo

**Comment by yazdog8** [comment]
@Hypnosphi My apologies. Forgot to make it public. You should be able to view it now.

**Comment by Hypnosphi** [comment]
looks like babel plugins `react-css-modules` and `react-optimize` don't work well together. You only see it is storybook build because `react-optimize` doesn't actually get applied to your `yarn build`. You can reproduce it there if you add this line to `webpack.config.js`:

```
process.env.NODE_ENV = argv.mode
```

**Comment by yazdog8** [comment]
Interesting. I broke out all of the optimize plugins and found that this is the one that seems to be breaking the css modules: 'babel-preset-transform-react-inline-elements'.

https://github.com/babel/babel/tree/6.x/packages/babel-plugin-transform-react-inline-elements

Will investigate further with the individual repos.

Thanks for your help!

**Comment by yazdog8** [comment]
And it seems like this is the reason: https://github.com/gajus/babel-plugin-react-css-modules/issues/120

Not included in the documentation it seems.
