### ISSUE TITLE
addon-info: defaultProps strings shows two sets of quotes

### ISSUE THREAD

**Issue by teddybradford** [storybooks/storybook#3324]
### Bug summary

The default string values for PropTypes show up with 2 sets of surrounding quotes.

### Versions

- storybook/react: 4.0.0-alpha.1
- storybook/addon-info: 4.0.0-alpha.1

### Screenshot

<img width="452" alt="image" src="https://user-images.githubusercontent.com/3684553/38164936-26dc465e-34da-11e8-8de0-3ee469ce0a00.png">

```js
Button.propTypes = {
  size: PropTypes.string,
  color: PropTypes.string
};

Button.defaultProps = {
  size: "default",
  color: "primary"
};
```

**Comment by Hypnosphi** [comment]
Released as [`3.4.5`](https://github.com/storybooks/storybook/releases/tag/v3.4.5)
