### ISSUE TITLE
Using storybooks in another URL

### ISSUE THREAD

**Issue by sepehr1313** [storybooks/storybook#3330]
Hello,

I have an existing project and I want to add storybook in the project with a separate URL. For example the website is test.com and we want to see storybook on test.com/storybook so we need to add `router.use('/storybook', storyBook)` in our server.js file.
Also I don't want to use **start-storybook -p 9001 -c .storybook** and we have only **npm start** script to running the project. Is there any way to do that?

**Comment by igor-dv** [comment]
Maybe I don't fully understand your question. Can't you use a static build of Storybook and point to the index.html from the router?

**Comment by danielduan** [comment]
build the static version of storybook in a folder like `/storybook-static`, make that folder a public static folder in your web server, point your react router to that folder.
