### ISSUE TITLE
Update screenshots and links in Knob addon readme

### ISSUE THREAD

**Issue by SilencerWeb** [storybooks/storybook#3333]

**Comment by Hypnosphi** [comment]
Which one? All of the links from here work for me https://storybook.js.org/basics/live-examples/

**Comment by danielduan** [comment]
they break during new deploys after we merge things, not sure if that's something we can fix or not. thanks for reporting though @SilencerWeb

**Comment by SilencerWeb** [comment]
@Hypnosphi [here](https://github.com/storybooks/storybook/tree/master/addons/knobs) is the broken link [Live Storybook](https://git.io/vXdhZ)

**Comment by Hypnosphi** [comment]
Looks like we need to update screenshots there as well. PR is welcome

**Comment by Hypnosphi** [comment]
> they break during new deploys after we merge things

Oh, do they? If so, we should ask netlify guys do they have some options for seamless deployment

**Comment by danielduan** [comment]
I fixed the live storybook link in that readme.

**Comment by Hypnosphi** [comment]
Screenshots are still outdated, and the other link too: https://github.com/storybooks/storybook/tree/master/addons/knobs#additional-links
