### ISSUE TITLE
Migrate to babel@7.0.0-beta

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#3335]
### Work summary

* [x] move all apps to babel beta
* [x] Use [`loadPartialConfig`](https://babeljs.io/docs/en/next/babel-core.html#loadpartialconfig) for custom babel configs resolution. Should fix #2582 #2771 #2610 #754 #2635 #2758

### Who to contact

Me

**Comment by osdevisnot** [comment]
It seems this is needed for CRA and getstorybook integration when react-scripts@2.0 is ready (referenced in https://github.com/facebook/create-react-app/issues/3815). Currently, we run into incompatible versions for babel since react-scripts@2.0 is on Babel 7 and Storybook is on Babel 6.

**Comment by Hypnosphi** [comment]
> move @babel/core to direct dependencies again

Ok looks like we can't do that. Actually we must declare all the peer dependencies of the server-side packages we use as our own. Imagine the following situation:

— We depend on `A@2` which has a peer dependency on `B@3`
— We add a direct dependency on `B@3` to satisfy that
— User app has a direct dependency on `B@2` and doesn't have any dependency on `A`
— `npm` hoists `A@2` to root `node_modules`, but leaves `B@3` under `@storybook/*/node_modules` to avoid clashing with `B@2`
— inside `A@2`, `import 'B'` resolves to `B@2` instead of the expected `B@3`, which leads to an error

webpack's `resolve.alias` can solve this issue for client-side dependencies but not for server-side ones
