### ISSUE TITLE
Part of the device's viewport is hidden behind the addon panel and not scrollable in small screens

### ISSUE THREAD

**Issue by mshaaban088** [storybooks/storybook#3341]
### Steps to reproduce

1. Open this [Viewport story](http://storybooks-official.netlify.com/?selectedKind=Addons%7CViewport.Custom%20Default%20%28Kindle%20Fire%202%29&selectedStory=Inherited&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook-addon-viewport%2Faddon-panel) on small screen (e.g. 13")
2. You will see part of the story's content is hidden and you cannot scroll to see it
<img width="1280" alt="screen shot 2018-04-03 at 00 25 30" src="https://user-images.githubusercontent.com/3688136/38219391-b5a0dd3a-36d5-11e8-8140-04de001aea4a.png">

**Comment by Hypnosphi** [comment]
Fix released as [`4.0.0-alpha.2`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.2)
