### ISSUE TITLE
Installing @storybook/react@3.4.0 stops yarn from installing webpack-dev-server from other packages dependencies.

### ISSUE THREAD

**Issue by hally9k** [storybooks/storybook#3344]
### Bug or support request summary

On upgrading to @storybook/react@3.4.0 we found that the `webpack-dev-server` dependency was not installing in our project's `node_modules` any more. The `webpack-dev-server` dependency is provided to our project via our bootstrapping package Vitalizer. This arrises exclusively with `yarn` and using `npm i` works as expected

### Steps to reproduce

Clone https://github.com/hally9k/storybook-dependency-test
Run `yarn install`
Open the `node_modules` directory and scroll to the webpack-dev-middleware package.
Note that `webpack-dev-server` is not in the `node_modules` directory.
Run `yarn remove @storybook/react` and note that `webpack-dev-server` appears in the dependencies.
Run `yarn add @storybook/react` and note that `webpack-dev-server` disappears from the `node_modules` directory. 

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react 3.4.0

### Affected platforms 
MacOS@10.13.4
Yarn@1.5.1
Vitalizer@4.1.2
Webpack-dev-server@3.1.1

**Comment by danielduan** [comment]
have you tried clearing your lock file? I wonder if this has to do with us or yarn

**Comment by hally9k** [comment]
@danielduan I tried everything I could think of. Nuked the lock, rolled yarn back to earlier versions. Tried to reproduce with other libs. The example shows that nothing fixed it for yarn but I couldn't get to the bottom of it so I thought I'd post up to you guys and see if you had any ideas.

**Comment by strothj** [comment]
@hally9k 

If you make this change in Vitalizer's `webpack.config.babel.js` it appears to work as expected with Yarn:
```js
 modules: [
        require("path").join(__dirname, "node_modules"),
        "node_modules",
        paths.appCss,
        paths.appSrc,
        paths.appPublic
      ]
```

A small adjustment to your Webpack's `resolve.modules` setting is needed it looks like.

Storybook's version of webpack-dev-middleware is probably different from the one used by webpack-dev-server in your Vitalizer package. As a result, Yarn creates `node_modules` directories in both the Vitalizer and @storybook packages with the different versions. Your webpack script doesn't take that into account.

You can see webpack-dev-server ends up here:
`storybook-dependency-test/node_modules/vitalizer/node_modules/webpack-dev-server`

**Comment by Hypnosphi** [comment]
If you want to guarantee that some package is in the root of your node_modules, you need to add a direct dependency on it instead of relying on npm/yarn hoisting

**Comment by hally9k** [comment]
@Hypnosphi Although your point is valid in terms of relying on yarn hoisting being a bit shaky this approach would remove a lot of the value of having the project configuration delegated to a package, we would have to maintain our dependencies in 2 places.

**Comment by Hypnosphi** [comment]
Well, either your config is completely handled by Vitalizer, and than it should be OK to have `webpack-dev-server` under `storybook-dependency-test/node_modules/vitalizer/node_modules`. Or for some reason you import or call `webpack-dev-server` directly, an then you need it as direct dependency
