### ISSUE TITLE
Hosting Stories in Bitbucket or other

### ISSUE THREAD

**Issue by bacancy-swaroopa** [storybooks/storybook#3354]
It is not a issues but now the stoies are running in localhost by default but I want to run in my bitbucket server or other 
I have done like this

`const StorybookUI = getStorybookUI({port: 7007, host: '<My server>', onDeviceUI: true});`

But still it is running in localhost only.
Can anyone tell me how to do that 
   ```
 " @storybook/addon-storyshots": "^3.2.3",
    "@storybook/react-native": "^3.3.15",
    "@storybook/addon-actions": "^3.3.15",
    "@storybook/addon-links": "^3.3.15",
    "@storybook/addons": "^3.3.15"
```

**Comment by danielduan** [comment]
You will need to commit the static build to BitBucket and have it serve the static html version

**Comment by igor-dv** [comment]
It won't work with react-native though

**Comment by bacancy-swaroopa** [comment]
@danielduan I alreadt committed the code then how to serve the static html version?

**Comment by danielduan** [comment]
I must have been really tired when I answered that.. yeah sorry I don’t think what you’re asking for can be done.

**Comment by bacancy-swaroopa** [comment]
@danielduan then it is not possible?

**Comment by danielduan** [comment]
It is not possible to host react native storybook on a server at the moment.

**Comment by bacancy-swaroopa** [comment]
@danielduan okay thank you

**Comment by bacancy-swaroopa** [comment]
@danielduan can you tell me why it is not supported right now in react native and when can it will be available

**Comment by danielduan** [comment]
react-native is only meant to run on mobile phones and emulators, storybook RN is not an exception. 

there is a browser UI to control the mobile UI and display addon information, but it is not a replacement for running the actual storybook on an emulator or phone. they are meant to work together.
