### ISSUE TITLE
addon-knobs WrapStory component not importing React properly

### ISSUE THREAD

**Issue by leepercox** [storybooks/storybook#3355]
### Bug or support request summary

To start, I am 99% sure this is me doing something stupid, not a bug with storybook. I just cannot for the life of me figure out what could be wrong. All my other modules and apps work perfectly.

Every time I run storybook since updating, I get the following errors:

![screen shot 2018-04-04 at 12 14 30](https://user-images.githubusercontent.com/6492146/38304970-15fcca12-3803-11e8-8a0c-02f0193eacbc.png)

I have had a large update from Webpack 1 to Webpack 4 and have updated all other config. Our main app works perfect since the change, but StoryBook since updating, just will not work. Any help would be appreciated. 

### Steps to reproduce

Simply install the latest alpha versions of addons, addon-info, addon-knobs, storybook/react (4.0.-alpha.1 for all) and this is what I see after running `start-storybook -p 6006`

### Please specify which version of Storybook and optionally any affected addons that you're running

```
 "@storybook/addon-info": "^4.0.0-alpha.1",
    "@storybook/addon-knobs": "^4.0.0-alpha.1",
    "@storybook/addons": "^4.0.0-alpha.1",
    "@storybook/react": "^4.0.0-alpha.1",
"webpack": "^4.4.1",
"react-transform-catch-errors": "^1.0.2",
```

### Affected platforms 

Mac OS X

**Comment by danielduan** [comment]
you should remove `react-transform-catch-errors`
https://github.com/gaearon/react-transform-catch-errors

**Comment by leepercox** [comment]
Ignore this. I was an idiot. My 'resolve' was wrong.
