### ISSUE TITLE
addon-a11y uses React.Fragment without specifying react >=16.2.0

### ISSUE THREAD

**Issue by timothymclane** [storybooks/storybook#3370]
### Bug or support request summary

Using @​storybook/addon-a11y with Storybook in a React 15 project throws errors as React.Fragment is undefined.

This can be fixed by specifying a minimum React version or removing the Fragment usage in `./components/Report`. Given I have some React 15 projects using addon-a11y 3.4.0, I'd prefer removing it altogether.

I'd be happy to make a pull request to address the problem.

### Steps to reproduce

1. Start a new React v15 project (I used CRA and installed React and ReactDOM 15.4.0)
2. add Storybook via getstorybook
3. install and enable addon-a11y
4. Storybook now errors in browser.

[Repo with issue](https://github.com/timothymclane/storybook-a11y-react-15-bug)

### Please specify which version of Storybook and optionally any affected addons that you're running

@​storybook/addon-a11y 3.4.0
@​storybook/react 3.4.0

### Affected platforms 

- Impacts any project with a React version that doesn't support Fragments

**Comment by danielduan** [comment]
@timothymclane that'd be great if you can remove them. you're welcome to create a PR.

**Comment by Hypnosphi** [comment]
Yes, let's remove the Fragment usage

**Comment by timothymclane** [comment]
Sounds good. I will get my environment set up and make that request.

**Comment by Hypnosphi** [comment]
Released as [3.4.1](https://github.com/storybooks/storybook/releases/tag/v3.4.1)
