### ISSUE TITLE
Babel 7 with create-react-app

### ISSUE THREAD

**Issue by EugeneDraitsev** [storybooks/storybook#3371]
How I can use storybook with babel 7? When I try to run it with babel 7 I get an error:  
```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.0". 
```

### Steps to reproduce
1. Create simple react application: `create-react-app test`
2. Eject it `yarn eject`
3. Use babel 7 in package.json
```
"@babel/core": "^7.0.0-beta.44",
"@babel/preset-react": "7.0.0-beta.44",
"babel-eslint": "8.2.2",
"babel-jest": "23.0.0-alpha.4",
"babel-loader": "8.0.0-beta.2",
"babel-runtime": "7.0.0-beta.3"
```
and this minimal .babelrc (also remove babel section from `package.json`)
```
{
  "presets": [
    "@babel/preset-react"
  ]
}
```
4. Run `getstorybook` and `yarn storybook`
5. You will get an error about wrong babel version

### Versions:
 ```
@storybook/react 3.4.0
 @storybook/addon-actions 3.4.0
 @storybook/addon-links 3.4.0
 @storybook/addons 3.4.0
```

**Comment by ndelangen** [comment]
@Hypnosphi would supporting this be as simple as declaring compatibility in `package.json`?

**Comment by Hypnosphi** [comment]
Storybook has a peerDependency on `babel-core` so you may need to install [`babel-bridge`](https://github.com/babel/babel-bridge)

**Comment by EugeneDraitsev** [comment]
@Hypnosphi yep, it works fine with `babel-bridge`. Thanks a lot, you can close issue
