### ISSUE TITLE
@storybook/addon-knobs wrong types for typescript in @types/storybook__addon-knobs

### ISSUE THREAD

**Issue by FDiskas** [storybooks/storybook#3374]
### Steps to reproduce

- `@storybook/react 3.4.0`
- `@storybook/addon-knobs 3.4.0`
- `@types/storybook__addon-knobs 3.2.3`

```js
import { number, select } from '@storybook/addon-knobs';
...
select('Gutter XS', selectOptions, 2, groupName),
```
Got error:
```
Expected 3 arguments, but got 4.
```

**Comment by Hypnosphi** [comment]
Looks like the definition is outdated. Please open a PR for [Definitely typed](https://github.com/DefinitelyTyped/DefinitelyTyped) to support the fourth argument

**Comment by joscha** [comment]
PR is here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24797 - closing this ticket as tracking will continue in DefinitelyTyped.
