### ISSUE TITLE
@storybook/addon-storyshots: Inconsistency in framework string for react-native.

### ISSUE THREAD

**Issue by dawnmist** [storybooks/storybook#3375]
I have been working on putting together a typescript definition file for the storyshots addon, and when tracking through options provided to functions in the code noticed that the 'framework' string for react-native changes from `'react-native'` to `'rn'` when the react-native loader is used.

Affected lines:
https://github.com/storybooks/storybook/blob/9b3f63b304c381db4457449c32d37f03ce8e0a9a/addons/storyshots/src/rn/loader.js#L6-L9
https://github.com/storybooks/storybook/blob/9b3f63b304c381db4457449c32d37f03ce8e0a9a/addons/storyshots/src/rn/loader.js#L18-L23

Is this string supposed to be different in the Context information to what is required in the initStoryshots function options? It looked like the change in value may have been an oversight from refactoring, so I figured I'd check, as I need to specify the correct list of values in both the Context and the Options framework values for the typescript type definitions.

**Comment by igor-dv** [comment]
'rn' is used internally only. It is used to prevent image snapshots to be called for rn.

**Comment by dawnmist** [comment]
The output from the load function is used when creating the context information that is passed to the options.test function, so it is leaking out into user code as well.
https://github.com/storybooks/storybook/blob/9b3f63b304c381db4457449c32d37f03ce8e0a9a/addons/storyshots/src/index.js#L39
https://github.com/storybooks/storybook/blob/9b3f63b304c381db4457449c32d37f03ce8e0a9a/addons/storyshots/src/index.js#L56
https://github.com/storybooks/storybook/blob/9b3f63b304c381db4457449c32d37f03ce8e0a9a/addons/storyshots/src/index.js#L82-L90
If the user does not set a test function but does set a custom renderer, it leaks through into the custom renderer via the context information that is sent to the default snapshotWithOptions test function.
https://github.com/storybooks/storybook/blob/9b3f63b304c381db4457449c32d37f03ce8e0a9a/addons/storyshots/src/test-bodies.js#L4-L10
Anywhere where the context value is passed to is receiving the 'rn' value rather than the initial 'react-native' value for the framework field in the context.

**Comment by igor-dv** [comment]
I see. So probably changing it back to the  'react-native' will be a good thing.
