### ISSUE TITLE
How to use knobs with angular

### ISSUE THREAD

**Issue by rameshkunwar** [storybooks/storybook#3376]
Knobs with Angular is not same as with React. I tried to write story with Knobs, however, it will not modify my props as that is done using React which can be found [here](https://storybooks-official.netlify.com/?knob-Dollars=12.5&knob-Name=Storyteller&knob-Text=help&knob-Years%20in%20NY=9&knob-background=%23ffff00&knob-Age=70&knob-Items%5B0%5D=Laptop&knob-Items%5B1%5D=Book&knob-Items%5B2%5D=Whiskey&knob-Other%20Fruit=lime&knob-Container%20width=100&knob-Birthday=1484870400000&knob-Nice=true&knob-Styles=%7B%22border%22%3A%223px%20solid%20%23ff00ff%22%2C%22padding%22%3A%2210px%22%7D&knob-Fruit=apple&knob-Active=true&selectedKind=Components%7CNavigation%2FMenuLink&selectedStory=with%20knobs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).
### Bug or support request summary

 If I use knobs, for example, if I take a button, I am only able to change only one property of the button using knobs but if I write more than one 'props' for the button like, color, it will not work. 

### Steps to reproduce

```const myStory = storiesOf('Button', module);
myStory.addDecorator(withKnobs);
  myStory.add('with text', () => ({
    component: Button,
    props: {
      text: 'Hello Storybook Button',
    },
   }))
   .add('with knobs', () => ({
     component:Button,
     props:{
       text:text('MyButton','MyBlueButton'),
       color:color('ButtonColor','#002b4b')
     }
   }) )
```
_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/angular - latest version
- storybook/addon-knobs  -latest version
- angular -  5.2.9
- typescript - 2.5.3
### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)
![storybook-knob](https://user-images.githubusercontent.com/19685710/38424817-7f32974a-39b2-11e8-8fd7-b4a6186f0d87.JPG)

**Comment by igor-dv** [comment]
You have to name your knobs labels exactly as the name of the component props.

**Comment by rameshkunwar** [comment]
[This](https://github.com/storybooks/storybook/blob/master/examples/angular-cli/src/stories/addon-knobs.stories.ts) example helped me. I think this example should be added on **knobs** for **Angular**.

**Comment by Silverium** [comment]
Hi all, 

I've found a workaround. **Use functions!!**
As you may know, React is all about functions and so are knobs, with this approach, you have instant responsiveness:
```js
...
  .add('your story here', () => ({
    template: `
        <your-component-here
                [customHeight]="height()">
        </your-component-here>
    `,
    props: {
      height: () => number('height', 50)
    },
  }));
```
