### ISSUE TITLE
mdx stories?

### ISSUE THREAD

**Issue by tsiq-swyx** [storybooks/storybook#3379]
just an idea for general discussion - any interest in writing stories in guillermo rauch's mdx?

https://github.com/mdx-js/mdx

i was honestly surprised no one seems to have suggested this yet. seems like a very natural pairing.

**Comment by tsiq-swyx** [comment]
sad

**Comment by igor-dv** [comment]
@tsiq-swyx, I am not sure we need to support this in the core. Looks like it can be configured with a custom mode, (like TS or Flow 🤷‍♂️ )

**Comment by pupudu** [comment]
@tsiq-swyx I had the same thought. People are moving away from storybook to docz, and this is one of the reasons. Should be really convenient for everyone if addons like `info` supported mdx

**Comment by StanLindsey** [comment]
I think this really suits Storybook. We already display React Component's paired with markdown readmes. This would fit nicely out of the box.

**Comment by ndelangen** [comment]
YES! This is on our roadmap, and we've started work on this already, Sorry for the

**Comment by ndelangen** [comment]
Refining this epic here:
https://github.com/storybooks/storybook/issues/4341

We could use help, so if you're reading this, please contact me if there's something you might be able to do to help.

**Comment by shilman** [comment]
@centerwork80 @tsiq-swyx We have a technical preview released on the `5.2.0-alpha.x` releases. In the process of structuring the work & release cycle in `#docs-mode` on our Discord https://discord.gg/UUt2PJb

**Comment by smeijer** [comment]
Is there a way to try out / get started with that `sneak peak` version? Since I've used docz for one of my projects, I'm considering switching all my projects to `docz` instead of `storybook`. That was until I saw the medium blog.

Unfortunately, I cannot find any "try it now!" docs. Those would be very helpful, to see if it's something worth waiting for.

**Comment by centerwork80** [comment]
Take a look at this package docs.

https://www.npmjs.com/package/@storybook/addon-docs

**Comment by shilman** [comment]
@smeijer just saw this comment. here's the guide you want https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by smeijer** [comment]
@shilman, thanks. I did find my way after @centerwork80 hinted me to look at `@storybook/addon-docs` :)
