### ISSUE TITLE
Multiple copies of React being loaded because of storybook

### ISSUE THREAD

**Issue by nareshbhatia** [storybooks/storybook#3381]
### Bug or support request summary

I have a repo with two packages - one containing a reusable component library and another containing an app. I am using Storybook to test the reusable component library - it is a `devDependency` defined in the library package. Everything works fine here, Storybook is able to display the components.

However, when I use this library to build the app, I get the following error from React:

```
Element ref was specified as a string (container) but no owner was set.
This could happen for one of the following reasons:

1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded

See https://fb.me/react-refs-must-have-owner for more information.
```

Essentially the app is picking up a second copy of React because it is a dependency of Storybook. If I remove the Storybook dependency and rebuild the app, it works fine.

### Steps to reproduce

I have created a small example that reproduces this issue. Please see here: https://github.com/nareshbhatia/react-multiple-copies-issue. Steps to reproduce are detailed in the README.

### Storybook version

- @storybook/react 3.4.0

**Comment by Hypnosphi** [comment]
Released as [3.4.1](https://github.com/storybooks/storybook/releases/tag/v3.4.1)

**Comment by nareshbhatia** [comment]
Hi @Hypnosphi, thanks for the help. I see that you removed the hard dependency on React and changed it to a peer dependency. This does help, but it does not solve the issue. In order to run Storybook, I have to now include React in my library myself. I added it as a `devDependency` to make sure that it is not picked up by other dependent packages. In spite of this, when I run my app (which depends on this library), it somehow picks up two copies of React and crashes - with the same error.

At this point, it is not a Storybook issue, but a general issue with any tool that depends on React and uses it in a library package. I don't know how to investigate this further - my guess is that it's an issue with either `npm` or `webpack`. If you have any suggestions, I can try them. FWIW, I cleaned up my minimal example to reproduce the issue more easily: https://github.com/nareshbhatia/react-multiple-copies-issue.

**Comment by Hypnosphi** [comment]
You're importing `'react'` package from your source files, so you need to have it as direct dependency anyway. There's no guarantee that your indirect dependencies end up installing into the root of your `node_modules` (and are therefore available for import)

**Comment by nareshbhatia** [comment]
1. Yes I am using Lerna for my monorepo. `lerna bootstrap` creates the symlinks. No experience with yarn workspaces. Is it a similar concept?
2. By "hoist react devDependencies", you mean to simply move the React dependency to the root package, correct? I had it set up that way earlier, but the app was still picking up two copies of React.
3. Your "third package" solution seems to be the most viable, although not a great developer experience. Will give that a shot.

Do you have a guess for the root cause? Is it webpack, npm or something else. The way I have set this up, it **should** work - at least if everyone is behaving properly!!!

**Comment by Hypnosphi** [comment]
> Is it a similar concept?

Yes. You can actually use yarn for bootstrapping and lerna for publishing (that's what we do in storybook main repo). It deduplicates and hoists all the common dependencies automatically
https://yarnpkg.com/lang/en/docs/workspaces/

> I had it set up that way earlier, but the app was still picking up two copies of React.

Probably that's because `myapp` still had its own react dependency
