### ISSUE TITLE
Generate snapshot for all select options

### ISSUE THREAD

**Issue by oldwin** [storybooks/storybook#3394]
Hi everyone,

I was trying to find answer in docs and issues, but seems like there is now answer.
Is it possible to configurate different storyshot for each select option?

For example I have next

```js
<Component
  propName={select('propName', ['A', 'B'], 'A')}
/>
```

And it will create snapshot for only default value 'A'
```js
<Component propName="A" />
```

Is it possible to use all select values for snapshot generation to get all possible values?
```js
<Component propName="A" />
<Component propName="B" />
```

Maybe there is any plans to implement this feature?

**Comment by igor-dv** [comment]
It's not possible with the out-of-the-box usage. the addons are agnostic to each other. You should probably add a story for each state of the select, or some other automation.

**Comment by sg-brady** [comment]
Would love to see this supported somehow
