### ISSUE TITLE
Addon-info not showing description and propTypes after adding react-css-modules

### ISSUE THREAD

**Issue by Pavankumar1014** [storybooks/storybook#3398]
If you are reporting a bug or requesting support, start here:
### Bug  summary
Hi,

I am facing a issue with storybook addon-info that after adding css modules the proptables are not showing the description and proptypes 

## Component: 

`import React from 'react';
import CSSModules from 'react-css-modules';
import styles from './button.css';

 class Button extends AbstractComponent {
    render() {
        return (
            <button {...this.props} >
                
                {this.props.value}
              
            </button>);
    }
}

Button.propTypes = {
    /** Value to be shown on the button */
    value: PropTypes.string.isRequired
}

export default CSSModules(Button,styles)`

## Storybook code:

`const stories = storiesOf('Button', module);
stories.add('Default', withInfo({
    text: 'This component defines a clickable button with text.'
})(() => (
<Button value="Click" title="Click"></Button>
)));`

## Output:

![storybook](https://user-images.githubusercontent.com/32608520/38613796-a2d30ff0-3da8-11e8-99d7-ff309d8ac6b5.png)

**Comment by Pavankumar1014** [comment]
Hi stale,

We still stuck with the same issue. 

Please let me know if you need more info on this

**Comment by ersel** [comment]
You might need to extend your component using CSSModules before you export it and define the `propTypes` on top of that.

so instead of this:

```
export default CSSModules(Button,styles)`//your styles here`;
```

do something like:

```
const StyledButton = CSSModules(Button,styles)`//your styles here`;

StyledButton.propTypes = {
    value: PropTypes.string.isRequired
};

export default StyledButton;
```

**Comment by XOP** [comment]
same issue, extending component doesn't help

**Comment by mechabyte** [comment]
Also experiencing the same using `@material-ui/core`'s `withStyles` decorator

**Comment by ShaiDemri** [comment]
> Also experiencing the same using `@material-ui/core`'s `withStyles` decorator

me too, any news?
