### ISSUE TITLE
Flow Types not displaying in PropTypes table in addon-info

### ISSUE THREAD

**Issue by marciaga** [storybooks/storybook#3405]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Flow types don't show up in addon-info props table.

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

The documentation seems to suggest Flow types should work analogously to PropTypes.

### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

-  storybook/addon-info ^3.4.0
- storybook/react ^3.4.0

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

Chrome on Mac

### Screenshots / Screencast / Code Snippets (Optional)

```js
// @flow

import * as React from 'react';
import styled from 'styled-components';

type Button = {
  margin?: string,
  bgColor?: string,
  hoverColor?: string,
}

export const StyledButton = (styled.button`
  margin: ${props => (props.margin ? props.margin : '10px')};
  height: 40px;
  max-width: 254px;
  text-transform: uppercase;
  text-decoration: none;
  text-align: center;
  cursor: pointer;
  border-radius: 2px;
  background-color: ${props => (props.bgColor ? props.bgColor : 'rgb(255, 168, 39)')};

  &:hover {
    background: ${props => (props.hoverColor ? props.hoverColor : '#81A2CA')};
  }
`: React.ComponentType<Button>);

```
End bug report support request - delete the rest below

**Comment by danielduan** [comment]
will be fixed by #3403, we currently don't support named exports.

**Comment by marciaga** [comment]
It doesn't seem to work with default exports either:
```
type Button = {
  /** Button label */
  children: string,
  /** The color for the button */
  color?: string,
  /** The size of the button */
  size?: string,
  /** Gets called when the user clicks on the button */
  onClick: () => void
};
/**
 * The only true button.
 */
const Button = ({ color, size, onClick, children }) => {
  const s = size ? size : "small";
  const styles = {
    color: color || "cornsilk",
    fontSize: Button.sizes[s]
  };

  return (
    <button className="button" style={styles} onClick={onClick}>
      {children}
    </button>
  );
};

export default Button;

```

**Comment by danielduan** [comment]
yeah.. flow support is kind of wonky right now. once I get that version in and published, please test it for me.

**Comment by ruanmer** [comment]
any news about this bug?

**Comment by danielduan** [comment]
@ruanmer it should be available in the 4.0.0-alpha builds

**Comment by ruanmer** [comment]
I was able to make it work putting the `react-docgen` plugin in my babelrc (#3481).

```
//.babelrc
{
  ...
  "plugins": [
    "react-docgen"
  ]
}
```

**Comment by PolGuixe** [comment]
@danielduan should it work in v3.4.10?
