### ISSUE TITLE
Select knob is broken in 3.4.1

### ISSUE THREAD

**Issue by colincclark** [storybooks/storybook#3407]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Upgraded storybook and relevant packages to 3.4.1 and the [select](https://github.com/storybooks/storybook/tree/master/addons/knobs#select) knob stopped working. When loading a story that utilises this knob, we get "Maximum call stack size exceeded"

### Steps to reproduce

Load any story (on 3.4.1) which uses a `select` (nb: _not_ `selectV2`) knob.

### Please specify which version of Storybook and optionally any affected addons that you're running

```
"devDependencies": {
    "@storybook/addon-knobs": "3.4.1",
    "@storybook/react-native": "3.4.1",
```

```
import { storiesOf } from "@storybook/react-native";
import { select } from "@storybook/addon-knobs/react";
```

### Affected platforms 

- Latest Chrome browser

**Comment by Hypnosphi** [comment]
Our [official example](https://release-3-4--storybooks-official.netlify.com/?knob-Dollars=12.5&knob-Name=Storyteller&knob-Years%20in%20NY=9&knob-background=%23ffff00&knob-Age=70&knob-Items%5B0%5D=Laptop&knob-Items%5B1%5D=Book&knob-Items%5B2%5D=Whiskey&knob-Other%20Fruit=lime&knob-Birthday=1484870400000&knob-Nice=true&knob-Styles=%7B%22border%22%3A%223px%20solid%20%23ff00ff%22%2C%22padding%22%3A%2210px%22%7D&knob-Fruit=apple&selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) uses `select` knob (fruit) and works OK. 
Can you please create a GitHub repo with minimal reproduction of your issue?

**Comment by colincclark** [comment]
@Hypnosphi try changing it to an Array, rather than an object.
