### ISSUE TITLE
Viewport Addon: Custom devices are NOT appearing as available options in Viewport drop-down

### ISSUE THREAD

**Issue by anthonymetzler** [storybooks/storybook#3413]
### Bug or support request summary
I had previously been running viewport and using its default list of devices. I came across the need to add a custom device to test against a specific resolution, so I updated my .storybook/config.js file as instructed in the README. However, my custom devices are not appearing in the drop-down no matter what I try.

### Steps to reproduce
Here is my .storybook/config.js file contents
```
import { configure as reactConfig } from '@storybook/react';
import { configure as viewportConfig, INITIAL_VIEWPORTS } from '@storybook/addon-viewport';

function loadStories() {
  require('../src/stories');
}

reactConfig(loadStories, module);

const newViewports = {
  arrowDevice: {
    name: 'Arrow Device',
    styles: {
      width: '1280px',
      height: '800px',
    },
    type: 'tablet',
  },
};

viewportConfig({
  viewports: {
    ...INITIAL_VIEWPORTS,
    ...newViewports,
  },
  defaultViewport: 'arrowDevice'
});
```
### Please specify which version of Storybook and optionally any affected addons that you're running

**3.4.1**

### Who to contact
@anthonymetzler

**Comment by mshaaban088** [comment]
@anthonymetzler Version `3.4.1` does not support configuration, please use `4.0.0-alpha.x` instead.

I think you have seen the README file in master, no? ([README v3.4.1](https://github.com/storybooks/storybook/tree/v3.4.1/addons/viewport))

**Comment by SindreSvendby** [comment]
Ahh, I just did the same. I was expecting master to ref to the latest stable build and developing of a new version on another branch. Could it be an idea to give a little heads up in the readme files that master is about the new alpha version and point to README for the latest stable branch? 

I can send a PR on that if that is something that you want to have @mshaaban088

**Comment by mshaaban088** [comment]
@SindreSvendby More about the release process can be found in [RELEASES](/storybooks/storybook/blob/master/RELEASES.md) file. Feel free to raise your concern.
