### ISSUE TITLE
Deprecate Knob debounce option, Select V1, old export format

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#3416]
### Work summary

* Deprecate Select V1 API
* remove debounce in Knob
* Remove old Knob exports

### Where to start

Select: https://github.com/storybooks/storybook/blob/master/addons/knobs/src/components/types/Select.js
Debounce: https://github.com/storybooks/storybook/blob/master/addons/knobs/src/components/Panel.js#L3
Remove old Knobs exports: https://github.com/storybooks/storybook/blob/master/addons/knobs/src/index.js

### Acceptance criteria

Remove the usages, update tests and snapshots, test to make sure they work

### Who to contact

myself

**Comment by Samatar26** [comment]
Hi @danielduan, can I work on this one?

**Comment by sunilhari** [comment]
Hi @danielduan 

I have few queries regarding this .Kindly ignore if these questions are out of point,as am totally new to this project

1.Deprecate Select V1 API

Is this about updating the depreciation warning being shown for select v1 api in the file mentioned

2.remove debounce in Knob

Is this about stopping support for debounce

3.Remove old Knob exports

How to understand which are old knob exports?

Kindly ignore if these questions are not relevant
