### ISSUE TITLE
Unable to make @storybook/addon-storyshots work in a typescript/react project.

### ISSUE THREAD

**Issue by aircraft721** [storybooks/storybook#3417]
#### What I expected to happen: 
Generate images from the existing stories.

#### What happened instead:
I receive this error instead: 

```
(function (exports, require, module, __filename, __dirname) { import { configure } from "@storybook/react";
SyntaxError: Unexpected token import
```

### Steps to reproduce
https://github.com/aircraft721/typescript-storyshot
1. Clone the repo
2. yarn
3. yarn build-storybook
4. yarn test
### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react 3.4.1
- storybook/addon-storyshots 3.4.1

### Affected platforms 

- I tested only on WIndows 10

**Comment by dbenfouzari** [comment]
@aircraft721 Did you made it work ? I cannot get it to work :(
