### ISSUE TITLE
Test suite failed to run

### ISSUE THREAD

**Issue by CLL80** [storybooks/storybook#3427]
This issue introduced to master over the last few days:

```
 Your test suite must contain at least one test.

      at node_modules/jest-cli/build/test_scheduler.js:157:22
```

### Steps to reproduce
Clone storybook

`yarn bootstrap --core && yarn test --core --image`

storybook 4.0.0-alpha.2

**Comment by Hypnosphi** [comment]
You need to run `cd examples/official-storybook && yarn build-storybook` before image tests

https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#cra-kitchen-sink---image-snapshots-using-storyshots

**Comment by CLL80** [comment]
Yes, they all pass after this. Thanks.
