### ISSUE TITLE
Add better production build support

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybook#343]
Currently, our production build works. But it's not optimized properly for static pages. So, try to get some input from React Create App and adapt.

**Comment by willianjusten** [comment]
It would be great if we can get a way to change the title page to our component/app name and maybe add an og:image to share ^^

A friend of mine created a decorator to add the github corner inside the storybook and it helped a lot to opensource projects. 

[React Storybook Github Corner](https://github.com/Personare/react-storybook-decorator-github-corner)

**Comment by arunoda** [comment]
It's coming soon.

**Comment by willianjusten** [comment]
Let me know if you need some help. I really like this project, if you have some issues that you need help, call me.

**Comment by arunoda** [comment]
We are pretty happy to get more help. Have a look at the issue list in here.
If you are familiar with webpack, get some of the production optimizations added [here](https://github.com/facebookincubator/create-react-app/blob/master/config/webpack.config.prod.js) to storybook.
