### ISSUE TITLE
Storybook 4.0.0-alpha.2 with FontAwesome

### ISSUE THREAD

**Issue by emiyake** [storybooks/storybook#3435]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
I updated the storybook in my project and found out that SVG fonts are not loaded correctly by the default `wepack.config.js`.

I noticed that `.svg` extension was removed from the loader that deals with fonts in the #3221 commit:
```
 {
        test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2)(\?.*)?$/,
        loader: require.resolve('file-loader'),
        query: {
          name: 'static/media/[name].[hash:8].[ext]'
        }
      }
```

and [`svg-url-loader`](https://github.com/storybooks/storybook/blob/a504a08152d38d12e7594b1edb4bc6581c75bff6/lib/core/src/server/config/defaults/webpack.config.js#L42) was added:

```
{
        test: /\.svg$/,
        loader: require.resolve('svg-url-loader')
      },
```

The problem is that when there is a third-party components are loaded from `node_modules`, such as FontAwesome,  the `.svg` in the css gets converted, causing an error in the css:

```
@font-face {
  font-family: 'FontAwesome';
  src: url(/static/media/fontawesome-webfont.674f50d2.eot);
  src: url(/static/media/fontawesome-webfont.674f50d2.eot?#iefix&v=4.7.0) format('embedded-opentype'), 
url(/static/media/fontawesome-webfont.af7ae505.woff2) format('woff2'),
url(/static/media/fontawesome-webfont.fee66e71.woff) format('woff'),
url(/static/media/fontawesome-webfont.b06871f2.ttf) format('truetype'),
url("data:image/svg+xml,%3C?xml version='1.0' standalone='no'?%3E %3C!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd' %3E %3Csvg%3E %3Cmetadata%3E Created by FontForge 20120731 at ...
```
<img width="584" alt="screen shot 2018-04-17 at 15 49 15" src="https://user-images.githubusercontent.com/700479/38890157-fdc4be60-4256-11e8-8730-d9d035ad0b1b.png">

It should be: 

```
@font-face {
  font-family: 'FontAwesome';
  src: url(/static/media/fontawesome-webfont.674f50d2.eot);
  src: url(/static/media/fontawesome-webfont.674f50d2.eot?#iefix&v=4.7.0) format('embedded-opentype'),
url(/static/media/fontawesome-webfont.af7ae505.woff2) format('woff2'), 
url(/static/media/fontawesome-webfont.fee66e71.woff) format('woff'),
url(/static/media/fontawesome-webfont.b06871f2.ttf) format('truetype'),
url(/static/media/fontawesome-webfont.912ec66d.svg#fontawesomeregular)

```
The solution would be removing `svg-url-loader` from the default `webpack.config.js` and adding back the `|svg` test in [this line](https://github.com/storybooks/storybook/blob/a504a08152d38d12e7594b1edb4bc6581c75bff6/lib/core/src/server/config/defaults/webpack.config.js#L35).

**Comment by danielduan** [comment]
does using `url-loader` not have this issue?

**Comment by emiyake** [comment]
@danielduan This issue persists even with `url-loader`

**Comment by danielduan** [comment]
@emiyake it's not caused by that PR then. while we try to provide a sensible webpack configuration, it's impossible to support everything. your best bet is to use the `Full Control Mode` and remove the `svg-url-loader` entry

same problem as https://github.com/storybooks/storybook/issues/3450

**Comment by emiyake** [comment]
I see. Wouldn't it make sense not to add `svg-url-loader` in the default configuration and add it with `Extended Control Mode` when needed, instead of forcing developers to remove it from the baseConfig? 
My understanding of basic configuration is to have a minimum support and we should add additional loaders according to the project needs (just like when we add loaders such as typescript).

The current problem is that the incompatibility is caused with other packages, which could be avoided.

**Comment by Hypnosphi** [comment]
Makes sense to me @emiyake

**Comment by anthonymetzler** [comment]
I'm having a similar issue with Semantic UI...
"@storybook/react": "^4.0.0-alpha.2" will break all the FontAwesome icons baked into Semantic UI. It's affecting the npm package "semantic-ui-css" as well as a local version of the Semantic library I've built.

**Comment by emiyake** [comment]
@anthonymetzler  https://gist.github.com/emiyake/a1302eeca331cceaf129789bb0a6c216
