### ISSUE TITLE
Missing assetFileTransform when trying to run tests

### ISSUE THREAD

**Issue by andyo729** [storybooks/storybook#3441]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I ran `yarn run test` and received the following error:

### Steps to reproduce

1. Run `yarn bootstrap`
1. Select Core and Examples
1. Run `yarn run test`
1. Select Core, React, Vue etc..

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook@3.0.0

### Affected platforms 

- Contributing to project

### Screenshots / Screencast / Code Snippets (Optional)

<img width="867" alt="screen shot 2018-04-17 at 9 08 29 pm" src="https://user-images.githubusercontent.com/62094/38906279-ab220d66-4283-11e8-8354-7648d146c0a3.png">

**Comment by Hypnosphi** [comment]
You need to uncheck react-native

**Comment by andyo729** [comment]
Yea, didn't notice that was set by default. Thanks for commenting!
