### ISSUE TITLE
Add option to clear action logger on switching stories

### ISSUE THREAD

**Issue by merlinpatt** [storybooks/storybook#3443]
I would like to see an option to clear the action logger (and possibly the console) when switching between stories.

This could simply be `clearActionLogger: true`.

I would be happy to write this feature if someone can help me get started with where to look.

**Comment by Hypnosphi** [comment]
Hi @merlinpatt 

You can start with [`CONTRIBUTING.md`](https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md)

The addon configuration code is here: https://github.com/storybooks/storybook/blob/master/addons/actions/src/preview/configureActions.js
The code related to displayed actions list is here: 
https://github.com/storybooks/storybook/blob/master/addons/actions/src/containers/ActionLogger/index.js

**Comment by Keraito** [comment]
Willing to help out, if you need someone extra @merlinpatt!

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.4`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.4)
