### ISSUE TITLE
There isn't a test:watch script

### ISSUE THREAD

**Issue by andyo729** [storybooks/storybook#3469]
### Bug or support request summary

I tried to run `yarn run test:watch` and it seems that script does not exist. It is listed in the README, but doesn't seem to be supported.

### Steps to reproduce

Run `yarn run test:watch`

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react@3.0.0

### Affected platforms 

- Contributing

**Comment by Hypnosphi** [comment]
It's actually `yarn test --core --watch`. We need to update the docs. Would you like to open a PR?
