### ISSUE TITLE
addon-knobs array of object components

### ISSUE THREAD

**Issue by leozhao0709** [storybooks/storybook#3480]
Hello guys, I was using a table to show multiple UI in one story name. Here's a code example

```
const buttonComponents: { name: string, component: JSX.Element }[] = [
    {
        name: 'Button',
        component: (
            <Button
                text={text('text', 'Button')}
                onClick={action('button-click')}
                style={{ backgroundColor: color('Button-backgroundColor', '#26a69a') }}
            />)
    },
    {
        name: 'AddButton',
        component: (
            <AddButton
                onClick={action('addButton-click')}
                style={{ backgroundColor: color('AddButton-backgroundColor', '#EA7374') }}
            />
        )
    }
];

const buttonRow = buttonComponents.map(({ name, component }) => {
    return (
        <tr key={name}>
            <td>{name}</td>
            <td>{component}</td>
        </tr>
    );
});

storiesOf('Button', module)
    .addDecorator(withKnobs)
    .add('Button', () => {
        return (
            <div>
                <table cellSpacing="25px" >
                    <tbody>
                        <tr>
                            <th>Name</th>
                            <th>Component</th>
                        </tr>
                        {buttonRow}
                    </tbody>
                </table>
            </div>
        );
    });
```

In this way, looks like the `withKnobs` doesn't work. I can see the color bar and text input shows, but when I change the color or the text, it's not showing the change in storybook.

I find one way to solve this is to move the `const buttonComponents` and `const buttonRow` in side of the `add` function callback, then everything works well. 

So I want to know is this a bug or it's the expected behavior? In my case, I really want to define `const buttonComponents` outside of the storybook module, so want to know is there any ways to do it?

**Comment by igor-dv** [comment]
In order to be changed, the knob function should be called on every story rerender. In your case, the "color" function is called once. You can wrap everything with functions out of the story and it will work. 

E.g: 
```js
function getButtonComponents() {
 return [
     ...
     color(...) // <- when the getButtonComponents() is called, the color knob is called too
     ...
 ];
}

function getButtonRow() {
 return getButtonComponents().map(...);
}

storiesOf(...)
  .add('foo', () => (
     ...
       {getButtonRow()}
     ...
  ));
```

You can even change the `getButtonRow()`  ot `ButtonRow()` and use it as `<ButtonRow/>`.

**Comment by leozhao0709** [comment]
@igor-dv  thanks for your help! yeah, it works this way. Really thanks for the help.
