### ISSUE TITLE
Jest not recognising/updating Storyshots

### ISSUE THREAD

**Issue by Braden1996** [storybooks/storybook#3483]
### Bug or support request summary
Hello everyone,

I am trying to setup Storyshots on a project I am working on.
The initial snapshot generation is successful, however, all following changes are not picked up by jest's watch mode. If I want to update the snapshots, I have to use `npm run test -- -u` - which isn't ideal, as the tests never visibly fail.

From the screenshot in the readme, this shouldn't happen - so I am not sure as to what I am doing wrong.

### Steps to reproduce

I am not sure what, in particular, is causing this to happen. My setup uses [Microsoft/TypeScript-React-Starter](https://github.com/Microsoft/TypeScript-React-Starter), perhaps that's related. Explicitly writing a snapshot test seems to work as expected, so the issue appears to be solely related to storyshots. I have created a test repository which can be used to reproduce the issue. You can find it here: https://github.com/Braden1996/ts-react-boilerplate

### Please specify which version of Storybook and optionally any affected addons that you're running

- "@storybook/addon-storyshots": "^3.4.1",
- "@storybook/react": "^3.4.1",

### Affected platforms 

Please see my project's [package.json](https://github.com/Braden1996/ts-react-boilerplate/blob/master/package.json)

### Screenshots / Screencast / Code Snippets (Optional)

Screenshot in the readme:
![Jest Watch in Readme](https://raw.githubusercontent.com/storybooks/storybook/master/addons/storyshots/docs/storyshots-fail.png)

Screenshot from my terminal:
<img width="442" alt="screen shot 2018-04-24 at 14 15 22" src="https://user-images.githubusercontent.com/5165963/39189802-0b1a034e-47cb-11e8-96cf-68b412b5a79b.png">
(notice `Snapshots:   0 total`)

**Comment by Braden1996** [comment]
Okay, so this was a result of using `multiSnapshotWithOptions`. Unfortunately, as [this brilliant article](https://medium.com/sears-israel/adding-multi-snapshot-testing-to-jest-b61f23cf17ca) explains, it is a smart "monkey patch" - to state a custom snapshot filename. However, it has a few caveats; including the inability to update snapshots.

**Comment by igor-dv** [comment]
Hey @Braden1996, multi-snapshots should work with manual updating. I wasn't aware of the watch mode that automatically updates snapshot, so I should probably check it.

**Comment by igor-dv** [comment]
Small update here, I've tried multisnapshots outside the storybook (in the `jest-specific-snapshot` repo) and even though there was no a `u` command, I was able to press `u` and to update the snapshots. Here, in storybook it's not available (can't understand why, maybe because of the different Jest versions). 

Anyway, I will try to check if it's possible to add a custom command to the watch.

**Comment by thomasbertet** [comment]
@igor-dv I did some digging and proposed a solution https://github.com/igor-dv/jest-specific-snapshot/pull/9. Please let me know what you think of it :)

**Comment by igor-dv** [comment]
I've published the change as v1.0.0.

**Comment by igor-dv** [comment]
It was released
