### ISSUE TITLE
jsnext:main entry point should not contain next-gen JS

### ISSUE THREAD

**Issue by drphelps** [storybooks/storybook#3484]
### Bug or support request summary

Adding `jsnext:main` in v3.3.x and exposing the /src dir in v3.3.6 leads to parse errors if Webpack config `resolve.mainFields` includes `jsnext:main`. I realize this is kind of a non-standard but `jsnext:main` is meant to denote ES module syntax only and should not point to files that include next-generation JS features. Storybook should not require src files to be transpiled in order to run.

See: 
https://github.com/rollup/rollup/issues/969
https://shuheikagawa.com/blog/2017/01/05/main-jsnext-main-and-module/

Related to https://github.com/storybooks/storybook/issues/2704

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react 3.4.2`
- `@storybook/addon-actions 3.4.2`
- `@storybook/addon-links 3.4.2`
- `@storybook/addon-storyshots 3.4.2`

**Comment by Hypnosphi** [comment]
> `jsnext:main` is meant to denote ES module syntax only

I thought that's what `module` is for

**Comment by Hypnosphi** [comment]
[`eslint-plugin-imports`] still [requires](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/default.md) using this field for some of the rules to work. Please open an issue for them

**Comment by Hypnosphi** [comment]
This would require a separate build process that would transpile all the packages to ES5 + modules. Feel free to open a PR introducing that
