### ISSUE TITLE
When registering Notes addon, webpack creates two modules for the Addon store when bundled.

### ISSUE THREAD

**Issue by justinmwarner** [storybooks/storybook#3489]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

EXPECTED: Only one AddonStore in the bundle.
ACTUAL: Two AddonStore in the bundle.

### Steps to reproduce

I can't share our code. And I don't have a repro. 
But when I add ```import "@storybook/addon-notes/register";``` to our ```addons.js``` file, the bundle file webpack produces contains two modules with the AddonStore.  So when it registers the notes addon, it uses module 123. But when the addon store loads all the stories for the panel, it uses module 456.

### Please specify which version of Storybook and optionally any affected addons that you're running

- ```@storybook/react 3.4.1```
- ```@storybook/addon-notes 3.4.1```

### Affected platforms 

N/A

### Screenshots / Screencast / Code Snippets (Optional)

N/A

I'm checking if this is a simple issue on my end or something larger. Or any idea to debug it myself. AFAIK, webpack manages all the modules. I'm not sure why it would dupe the import unless one of the packages had a dependency on a different version, which I checked and didn't see happening.

**Comment by igor-dv** [comment]
I think it was fixed. @Hypnosphi fix me if I am wrong.

**Comment by justinmwarner** [comment]
@igor-dv what fixed this? Just curious. I am out on vacation for the next week or so, but will check back on this when I return.
