### ISSUE TITLE
RFE: use onBlur for text fields for knobs addon

### ISSUE THREAD

**Issue by oyvindberg** [storybooks/storybook#3490]
I have a use case where it's somewhat expensive to render after update to a knob value. When a user types in a text field (or array), any of the following symptoms are seen:
- focus moved out of text field
- missing typed characters
- cursor at the end of input

I should also mention that I've tried to use debouncing and waiting, but it's not really helping.

### Please specify which version of Storybook and optionally any affected addons that you're running
```
        "@storybook/addon-actions": "^3.4.0",
        "@storybook/addon-knobs": "^3.4.0",
        "@storybook/addon-links": "^3.4.0",
        "@storybook/addon-notes": "^3.4.0",
        "@storybook/react": "^3.4.0",
```

### Affected platforms 
- Both firefox and chrome, newest versions

### Work summary
I wrote a quick, local hack which replaces `onChange` with `onBlur`
```typescript
const replace: any = require('replace-in-file');

replace({
    files: ['./node_modules/@storybook/addon-knobs/dist/components/types/Text.js'],
    from: `value: knob.value,
    onChange: function onChange(e) {`,
    to: `defaultValue: knob.value,
    onBlur: function onChange(e) {`
}).then(
    (changes: any) => console.log('Modified files:', changes.join(', ')),
    (err: any) => console.warn(err)
);

replace({
    files: ['./node_modules/@storybook/addon-knobs/dist/components/types/Array.js'],
    from: `value: knob.value.join(knob.separator),
    onChange: function onChange(e) {`,
    to: `defaultValue: knob.value.join(knob.separator),
    onBlur: function onChange(e) {`
}).then(
    (changes: any) => console.log('Modified files:', changes.join(', ')),
    (err: any) => console.warn(err)
);
```
This gave me the performance i needed.

Would be happy to provide a PR if you agree it's a good idea, and also if you could specify against which branch.

**Comment by Hypnosphi** [comment]
Do those issues reproduce with `4.0.0-alpha.3`? We've added some debouncing in #3412

**Comment by oyvindberg** [comment]
Sorry it took a while, webpack 4 wasn't originally on my radar.

Just confirmed it on `4.0.0-alpha.4`. It seems overall **much** faster (thanks!), but this particular issue remains.

**Comment by Hypnosphi** [comment]
I wonder if we can find another fix for it. Updating on blur only seems a bit counter-intuitive to me

**Comment by Hypnosphi** [comment]
Can you please try using `withKnobsOptions({timestamps: true})`?
https://github.com/storybooks/storybook/tree/master/addons/knobs#withknobs-vs-withknobsoptions

**Comment by oyvindberg** [comment]
Oh yeah sorry, about late answer.

I had already tried `withKnobsOptions`. In fact i really dug somewhat deep into it to find a fix for the performance problems i had before i wound up with the patch described above
