### ISSUE TITLE
Use a more informative slider for number range knob 

### ISSUE THREAD

**Issue by gravitypersists** [storybooks/storybook#3495]
I am happy to implement the work for this request but I wanted to first get approval from the core contributors to know that this is something you'd like in scope for this project (and while I'm here, a huge **Thank you!** for building it).

Currently the slider does not impart any value information:

![no-val](https://user-images.githubusercontent.com/231863/39378825-530ede96-4a0e-11e8-8785-cc5e6d446364.gif)

I would like to replace this slider with a more informative one (perhaps [rc-slider](http://react-component.github.io/slider/examples/handle.html):

![with-val](https://user-images.githubusercontent.com/231863/39378899-8331f89c-4a0e-11e8-9f97-701155044c01.gif)

**Comment by Hypnosphi** [comment]
Actually, some info has been added in #2445 (released as `4.0.0-alpha.3`, [live demo](https://storybooks-official.netlify.com/?knob-Dollars=12.5&knob-Name=Storyteller&knob-Years%20in%20NY=9&knob-background=%23ffff00&knob-Age=70&knob-Items%5B0%5D=Laptop&knob-Items%5B1%5D=Book&knob-Items%5B2%5D=Whiskey&knob-Other%20Fruit=lime&knob-Birthday=1484870400000&knob-Nice=true&knob-Styles=%7B%22border%22%3A%223px%20solid%20%23ff00ff%22%2C%22padding%22%3A%2210px%22%7D&knob-Fruit=apple&selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)).
