### ISSUE TITLE
Accessibility testing using storybook.

### ISSUE THREAD

**Issue by aircraft721** [storybooks/storybook#3501]
If you are reporting a bug or requesting support, start here:
### Support request 

I'm curious if there is a way to do accessibility testing using `storybook/addon-storyshots` and what tools can be used to achieve this.
I already implemented `storybook/addon-a11y`, but I want to test the accessibility using a different approach like: 
```
initStoryshots({
    suite: 'Accessibility tests',
    storyKindRegex: /(component-)/,
    framework: 'react',
    test: (accessibility tests)
});
```

**Comment by gitMonks** [comment]
Hi @aircraft721 

I was looking for the same sort of solution. Did you find a way to achieve this?

Thanks
