### ISSUE TITLE
[addon-info] markdown in description

### ISSUE THREAD

**Issue by livemirsi** [storybooks/storybook#3502]
Hello. 
```js
storiesOf('atoms/buttons', module)
	.add('Button - custom', withInfo(`
	description or documentation about my component, supports markdown
    
	~~~js
	<Button>Click Here</Button>
	~~~

	`)(() => (
		<CustomButton
			onClickkkk={action('button-click')}
			disabled={boolean('disabled', false)}
			fullWidth={boolean('fullWidth', false)}
			innerAlignment={selectV2('innerAlignment', alignments, 'center')}
			variant={selectV2('variant', variants, 'primary')}
		>
			{text('Label', 'My button')}
		</CustomButton>
	)));
```
I see that the markup does not work
[show screen](http://joxi.ru/823OONoI6VeMX2)
How to fix that? 
- @storybook/react 3.4.2
- @storybook/addon-something 3.4.3

**Comment by Keraito** [comment]
As I'm already working on some Markdown-related stuff, I will try to look into it for you.

**Comment by Keraito** [comment]
After looking into your example, it seems that you're using tabs for indentation (in the markdown string). If you use spaces instead (should not be hard to convert them depending on your text editor), it will work. Can you see if that fixes it?

Tagging @Hypnosphi whether this is something storybook wants to cover on their side, or users should adhere to.

**Comment by livemirsi** [comment]
@Keraito  thanks for the help. Yes, if  i using spaces it is work. But, not have syntax highlighting.
[see screenshot](http://joxi.ru/Dr8KKGMskQGxwA)

**Comment by Keraito** [comment]
Hey @livemirsi, I looked into it a bit and couldn't quite solve it. Maybe I can find a fix later, but I don't expect that to be soon, sorry.

**Comment by wuweiweiwu** [comment]
Try with `4.0.0-alpha.4`?

**Comment by drmanitoba** [comment]
Just to add, I'm on 4.0.0-alpha.4 and am not seeing the syntax highlighting. Was also experiencing the issue where tabs would break the Markdown almost entirely.

**Comment by Keraito** [comment]
As far as I could see from playing around with the markdown stuff, is that the highlighting for the `addon-info` and `addon-notes` doesn't work, while it does work for example in the `Story Souce`.  It seemed like storybook was using different ways of rendering the markdown between those 2. I'm not quite sure whether the highlighting worked before (cuz i havent been around for so long), maybe someone else from the org knows?

**Comment by wuweiweiwu** [comment]
Interesting. I'll take a look this weekend
