### ISSUE TITLE
Inconsistencies between guides for add-on modules

### ISSUE THREAD

**Issue by GeorgeWL** [storybooks/storybook#3506]
### Bug or support request summary

I've noticed there's a major inconsistency between the Guide on the Docs and the Guide on the Add-on itself for quite a few of the official add-ons.

This includes, knobs & notes from what I've seen so far.

They're stating conflicting methods for adding them to Storybooks, which could cause major confusion.

https://github.com/storybooks/storybook/blob/master/docs/src/pages/addons/using-addons/index.md
https://github.com/storybooks/storybook/tree/master/addons/notes

### Please specify which version of Storybook and optionally any affected addons that you're running

* `@storybook/react` 3.4.2
* `@storybook/addon-notes` 3.4.2
* `@storybook/addon-knobs` 3.4.3

**Comment by Hypnosphi** [comment]
Documentation on `master` branch is for alpha version, th stable one is on `release/3.4`. It would make sense to add a note about it on top of each addon's readme, with a link to stable version docs. Would you like to open a PR adding that?

**Comment by GeorgeWL** [comment]
Ah brilliant, ta, shall do yeah.

I feel tbh though, master should only ever be the current stable release, with future and alpha/beta releases being on branches instead.

It's the more commonly seen practice.
