### ISSUE TITLE
Storybook with Angularjs (1.x)?

### ISSUE THREAD

**Issue by mdwagner** [storybooks/storybook#3508]
Hello! I've been using React-Storybook for a few small projects now and love it. However, at my work we still use Angularjs (1.x) and we'll be (incrementally) migrating to React soon. Currently, we use Hologram for rendering Angularjs component documentation, but we would like to migrate to something else (hopefully Storybook).

I was wondering what your suggestion(s) are for using Storybook with Angularjs, along with getting addons working. This [example](https://github.com/mdwagner/storybook-angularjs/blob/master/stories/AngularBootstrap.js) is the best I could come up with, but I can only get the withConsole addon to work with it.

Thank you for your time!

**Comment by ersel** [comment]
Interesting, we're also migrating from 1.x to React at my workplace. I think your approach is to render Angular within React components?

We're doing the exact opposite, using the https://github.com/ngReact/ngReact

It lets us build new components in React and slowly migrate existing bits into iteratively. So we can use all the modern tooling around the React components.

**Comment by mdwagner** [comment]
Yeah, we were initially going to use ngReact for migration, but we felt that it didn't fulfill our requirements, only developer happiness. Our migration approach will be to use [UI-Router/React-Hybrid](https://github.com/ui-router/react-hybrid) because our app is too large to migrate at one time and we wanted to take control away from Angularjs and move to a more framework-agnostic router.

**Comment by wuweiweiwu** [comment]
As angular1.x will be defunct in 3 years https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c I'm not if we should add support. 

I feel your pain too haha. We're still on angular1.x w no migration in sight :(

**Comment by Hypnosphi** [comment]
[`@storybook/html`](https://github.com/storybooks/storybook/pull/3475) may bring some hope

**Comment by mdwagner** [comment]
It lools like I'll use the storybook html package

**Comment by titonobre** [comment]
@mdwagner Last week I published a new addon to create stories in storybook with AngularJS components.

Check here https://github.com/titonobre/storybook-addon-angularjs
This depends on the lastest pre-realeses of Storybook, after https://github.com/storybooks/storybook/pull/3475.

There is also an example of usage [here](https://github.com/titonobre/storybook-addon-angularjs-example).
