### ISSUE TITLE
[v4.0.0-alpha.4] React - component ref innerWidth and innerHeight are 0 on page load

### ISSUE THREAD

**Issue by Grimones** [storybooks/storybook#3516]
### Bug or support request summary

The component needs parents `clientWidth` and `clientHeight` to properly size canvas when `componentDidMount()` on page load.

**Expected:** on v3.4.3 works as expected. The canvas gets his size.

**Happens:** on v4.0.0-alpha.4 `clientWidth` and `clientHeight` are 0 so cavas renders nothing. If you switch on other story and get back - everything works as expected.

### Steps to reproduce
A minimal project with issue
https://github.com/Grimones/storybook-issue-example

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.4

### What i have done

I have looked into the issue and found out that it happens after this commit c64125f81ae49a733fa595eebd7a21e3817a7511
The issue is caused by this style rule https://github.com/storybooks/storybook/blob/3f602a0f80512ab17edf3b00ccc58c7fc0a46e33/lib/core/src/server/iframe.html.ejs#L11-L15

When the page loads storySize is equal to zero https://github.com/storybooks/storybook/blob/a3d43fd2f1506f80d53ebfba9b5e8fcb5774f088/lib/core/src/client/preview/start.js#L112-L115
and shows no preview which sets mentioned above style.

Then goes another render (which is triggered, i guess, by updating the storyStore).
Now `storyStore.size()` isn't equal to 0 and the rendering process goes on.

My guess is that at this moment react component is rendering in a body which has `display` set to `none`
and all element bounds aren't rendered so the dimensions are equal to zero.

Then `sb-show` is added to the body and react component becomes visible. 
https://github.com/storybooks/storybook/blob/a3d43fd2f1506f80d53ebfba9b5e8fcb5774f088/lib/core/src/client/preview/start.js#L21-L26
But canvas size is already set 0.

### Hotfix

importing a css in stories `index.js`

```css
:not(.sb-show-main) > .sb-main {
  display: block;
}
```

or timeout in componentDidMount

**Comment by Hypnosphi** [comment]
Ok I think we need to call `showMain` before rendering

**Comment by Grimones** [comment]
Yes, I will open a PR. Should I add all frameworks in one PR?

**Comment by Hypnosphi** [comment]
Yes that would be great

**Comment by hepiyellow** [comment]
I think this issue is not resolved.
I am encountering an issue that looks very similar in alpha.06

I have a component which in `componentDidMount` calls `element.getBoundingClientRect().width` 
Something like this:
```
public componentDidMount() {
  this.updateLayoutIfNeeded();
}
```

The `updateLayoutIfNeeded()`is the one calling `element.getBoundingClientRect().width`.
It is getting the wrong width (360 in my case) while it should be (280).

If I add `setTimeout()` in the `componentDidMount()`, like this:
```
public componentDidMount() {
  setTimeout(()=>this.updateLayoutIfNeeded(), 0);
}
```
Then is works, it get 280.

Important thing to note, it that it happens ONLY in version `alpha.06`, if I run it with version `3.4.4` then is gets width 360 without needing the timeout.

**Comment by hepiyellow** [comment]
Turned out to be unrelated.
