### ISSUE TITLE
Path to webpack.config.js

### ISSUE THREAD

**Issue by tim-yao** [storybooks/storybook#3524]
### Support request summary

Need to know the location of storybook webpack config file I am using.

### Steps to reproduce

I am using vue.js and [`jest-webpack-resolver`](https://github.com/mkg0/jest-webpack-resolver) to work with stroybook, it can resolve the `jest` couldn't fine module errors. The question is `jest-webpack-resolver` ask for a location of webpack config js. Like this:
```
"jestWebpackResolver": {
    "webpackConfig": "./path/to/webpack.config.js"
  }
```

I am not sure which webpack config file I should use. I tried to use `./node_modules/@storybook/vue/dist/server/config/defaults/webpack.config.js` and it give me a error says:

```
    TypeError: Cannot read property 'module' of undefined

      at createDefaultWebpackConfig (node_modules/@storybook/vue/node_modules/@storybook/core/dist/server/config/defaults/webpack.config.js:25:60)
      at getWebpackResolveRules (node_modules/jest-webpack-resolver/index.js:83:20)
      at Object.<anonymous> (node_modules/jest-webpack-resolver/index.js:90:22)

Webpack Resolver using: ./node_modules/@storybook/vue/dist/server/config/defaults/webpack.config.js
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue 3.4.3

### Affected platforms 

- vue 2.5.16
- jest 22.4.3
- jest-webpack-resolver 0.3.0

**Comment by Hypnosphi** [comment]
Do you have any custom webpack config in `.storybook` dir? How does it look like?

**Comment by tim-yao** [comment]
Hi @Hypnosphi yes, I have a `.storybook/webpack.config.js`. 
I tested in "Full control mode + default" now. 
```
module.exports = (storybookBaseConfig, configType) => {
  storybookBaseConfig.module.rules.push({
    test: /\.(jpe?g|png|woff|woff2|eot|ttf)(\?[a-z0-9=.]+)?$/,
    loader: 'url-loader'
  });
  storybookBaseConfig.module.rules.push({
    test: /\.svg$/,
    use: [
      'svg-sprite-loader',
      'svgo-loader'
    ]
  });

  return storybookBaseConfig;
};
```
If I use that file, `npm test` will fail in error:
```
> jest

 FAIL  test/storyshots.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'module' of undefined

      48 | // Export a function. Accept the base config as the only param.
      49 | module.exports = (storybookBaseConfig, configType) => {
    > 50 |   storybookBaseConfig.module.rules.push({
      51 |     test: /\.(jpe?g|png|woff|woff2|eot|ttf)(\?[a-z0-9=.]+)?$/,
      52 |     loader: 'url-loader'
      53 |   });

      at module.exports (.storybook/webpack.config.js:50:23)
      at getWebpackResolveRules (node_modules/jest-webpack-resolver/index.js:83:20)
      at Object.<anonymous> (node_modules/jest-webpack-resolver/index.js:90:22)

Webpack Resolver using: `./.storybook/webpack.config.js`
```
Same `Cannot read property 'module' of undefined` error if I use "Full Control Mode". In extend mode, it give me other errors. So I am wondering I should not use that `./.storybook/webpack.config.js` because it is not the full config?

**Comment by tim-yao** [comment]
@Hypnosphi thanks, that make sense.
