### ISSUE TITLE
Unable to install with npm i --save-dev @storybook/react on mac

### ISSUE THREAD

**Issue by hitendramalviya** [storybooks/storybook#3525]
### Steps to reproduce

On terminal running the command `npm i --save-dev @storybook/react`

Error message during installation i see as below:

`error for @storybook/addon-actions@3.4.3 zlib: unexpected end of file`

After finished I see below error message

![image](https://user-images.githubusercontent.com/5709606/39562281-77c725c2-4ec8-11e8-95dd-44198419f8d9.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react@3.4.3

### Affected platforms 

- OS: Mac OS X

**Comment by Hypnosphi** [comment]
Is there a chance you’re using some corporate proxy for accessing npm? What does this command output for you?
```
npm config get registry
```

**Comment by hitendramalviya** [comment]
Yes we are using a proxy, nexus repository manager we are using, is there any workaround in such case?

**Comment by Hypnosphi** [comment]
You should probably contact your admins

**Comment by hitendramalviya** [comment]
Sure, I will contact them, but I am bit curious why it is happening on latest version of this package only, a previous version `3.4.2` of the same package got installed successfully. Anyway thanks for your inputs if you feel it not related anymore to this repo, feel free to close this issue.
