### ISSUE TITLE
[addon background] Not persisting background color

### ISSUE THREAD

**Issue by hally9k** [storybooks/storybook#3528]
### Bug
The background color flickers and reverts to default on 3.3.15

### Steps to reproduce
Boot up 3.3.15 with background addon and attempt to set a background. The `background` attr gets set on the iFrame's inline styles but doesn't show. If i manually set it on the html tag inside the iframe it works. Might be a chrome thing. In Safari it is just a fine line at the top, see below, the intended background color is that hideous violet.

<img width="513" alt="screen shot 2018-05-04 at 12 50 13 pm" src="https://user-images.githubusercontent.com/3803536/39609027-c96926e2-4f99-11e8-8504-62fe22b7a9d2.png">

### Please specify which version of Storybook and optionally any affected addons that you're running
- @ storybook/react 3.3.15
- @ storybook/addon-backgrounds 3.3.15

### Affected platforms 
- Chrome 66, macOS 10.13.4

**Comment by Hypnosphi** [comment]
It was fixed with https://github.com/storybooks/storybook/pull/3331
Please try version `4.0.0-alpha.4`
