### ISSUE TITLE
How to display state properties of a react component

### ISSUE THREAD

**Issue by amittkSharma** [storybooks/storybook#3561]
Hello Team, 

I am working with Storybook and using the info Addon for displaying the properties of the component in the story. And I wanted to display the state properties of the component too.

1. Is there some way I can use the same addon to display the state properties of the component?
2. Or there is some other addon I have to use for this purpose?

Thanks in advance.
Amit

**Comment by Keraito** [comment]
Hey @amittkSharma, what properties of the state do you exactly want to display?

The reason that the `addon-info` can display the additional information of the properties of components is cuz they are statically defined. As far as I'm aware, that is rarely to not done for the state of react components. Or are you referring to different information?

**Comment by amittkSharma** [comment]
Hi Keraito, 

Thanks for the response, but the thing I am referring is some kind of state interface that a react component has? This will be useful for the user using the storybook to get the information that what kind of state a component will be maintaining. 

Thanks
Amit

**Comment by wuweiweiwu** [comment]
Hi @amittkSharma,

The info addon currently uses the parse tree to generate propTypes docs. However, state documentation is not supported unless you just want to use `withInfo`. Perhaps in the future we can support flow annotations on state type definitions.

**Comment by amittkSharma** [comment]
Thanks, looking forward to the feature in the addon.

**Comment by wuweiweiwu** [comment]
For now, if you want to document state it'll prob be just just to write it out. 👍
