### ISSUE TITLE
Incorrect URL linking to Backgrounds from addons gallery

### ISSUE THREAD

**Issue by benbowes** [storybooks/storybook#3565]
### Bug

Incorrect URL linking to Backgrounds from addons gallery

https://storybook.js.org/addons/addon-gallery/#backgrounds

### Steps to reproduce

1. Visit https://storybook.js.org/addons/addon-gallery/#backgrounds
1. Click on Backgrounds link https://github.com/storybooks/storybook/tree/master/addons/background
1. 404 page is displayed

Should the URL be https://github.com/storybooks/storybook/tree/master/addons/backgrounds ?

**Comment by Keraito** [comment]
Can reproduce, but it seems like the link in https://github.com/storybooks/storybook/blob/master/docs/src/pages/addons/addon-gallery/index.md#backgrounds is correct though

**Comment by Hypnosphi** [comment]
The correct link is https://github.com/storybooks/storybook/tree/release/3.4/addons/background

https://github.com/storybooks/storybook/pull/3393 isn't live because no one labelled the PR as `patch`

**Comment by daraclare** [comment]
Is this issue done and the PR needs to be merged, or can I help with it? Thanks!

**Comment by Hypnosphi** [comment]
@daraclare no one has actually opened a PR so far, so feel free to do it

**Comment by daraclare** [comment]
Thanks, that's done. I hope it's ok: https://github.com/storybooks/storybook/pull/3619

**Comment by Keraito** [comment]
@Hypnosphi should all links to Storybook maintained addons then be changed to point to the `release/3.4` branch, instead of master?

**Comment by Hypnosphi** [comment]
@Keraito All of them

**Comment by daraclare** [comment]
This issue was fixed in my PR, which was merged by @Hypnosphi AFAIK. Can it be closed?
