### ISSUE TITLE
Normalize CSS and storybook

### ISSUE THREAD

**Issue by chemoish** [storybooks/storybook#3574]
I have implemented normalize css in the `preview-head.html` to give a baseline to the components I am building (I do the same in my app).

It seems like `storybook` css might be written based on Chrome default css—or similar?

Would there be any interest or recommendations for fixing style conflicts? Foundation injects normalize automatically, but I am not sure if this would be a good recommendation for everyone.

**Comment by Hypnosphi** [comment]
> It seems like storybook css might be written based on Chrome default css

What do you mean by that? We (almost) don't add any styles to story iframe

**Comment by chemoish** [comment]
@Hypnosphi Sorry for the vague description.

It is specifically in regards to `@storybook/addon-info`, https://github.com/storybooks/storybook/blob/9f004c88dd1883ed3d2a4cc8052b1ec335d4c81e/addons/info/src/components/markdown/pre/copyButton.js.

It seems there is a lot of styles under this addon, but I am sure there might be issues with any other CSS injected; if the source isn't normalized or reset.

The effect isn't too bad so it is very minor.
