### ISSUE TITLE
Wrong documentation on serving static files

### ISSUE THREAD

**Issue by Frikki** [storybooks/storybook#3577]
### Bug or support request summary

Following the documentation for serving static files as [presented here](https://storybook.js.org/configurations/serving-static-files/#1-via-imports) produces broken images with this path: `/static/media/[name].[hash:8].[ext]`

The documentation explicitly mentions:

> This is enabled with our default config. But, if you are using a custom Webpack config, you need to add the file-loader into your custom Webpack config.

The issue is that adding the _file-loader_ into my custom Webpack configuration is what breaks the functionality.

### Steps to reproduce

**webpack.config.js**

```js
module.exports = (baseConfig, env, defaultConfig) => {
    defaultConfig.module.rules.push({
        test: /\.(gif|jpg|png)(\?.*)?$/,
        loader: require.resolve('file-loader'),
    })

    return defaultConfig
}
```

In fact, omitting to add the _file-loader_ to the custom Webpack config correctly displays the images. Thus, I assume that the documentation is outdated and wrong.

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react@3.4.2`

### Affected platforms 

- Chrome, Safari, macOS High Sierra v10.13.4

### Screenshots / Screencast / Code Snippets (Optional)

```js
import React from 'react';
import { storiesOf } from '@storybook/react';

import imageFile from './static/image.png';

const image = {
  src: imageFile,
  alt: 'my image',
};

storiesOf('<img />', module)
  .add('with an image', () => (
    <img src={image.src} alt={image.alt} />
  ));
```

**Comment by wuweiweiwu** [comment]
Thats interesting. Because that path is the default path/filename that the default [configs](https://github.com/storybooks/storybook/blob/master/lib/core/src/server/config/defaults/webpack.config.js#L39) resolve to.

What happens if you replace the test with ` /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2)(\?.*)?$/`?

Seems like all the cases are covered.

**Comment by adbutterfield** [comment]
Hi - I just wanted to drop a comment real quick. I just encountered this very same problem. Removing file-loader form my webpack config also fixed the issue for me.
