### ISSUE TITLE
multiples storybook per project

### ISSUE THREAD

**Issue by darlanmendonca** [storybooks/storybook#3579]
I'm trying add multiple storybook's to a same project, a storybook in react, and another in angular.

This is possible?

I target the first to directory .storybook/react, and all works very well, but, when I add the devDependency @storybook/angular, when I start the react storybook, is loaded `@storybook/angular` instead `@storybook/react`

**Comment by ndelangen** [comment]
indeed, this is current a limitation.

We're using the same binary name for both apps.

You can possibly run like so:
```
// start
node ./node_modules/@storybook/angular/bin/index.js

// build
node ./node_modules/@storybook/angular/bin/build.js
```

**Comment by ndelangen** [comment]
I'm working on solving this limitation, and have you be able to run a single storybook with multiple frameworks.

**Comment by darlanmendonca** [comment]
thanks @ndelangen, I'm running binary manullay, as you write

```sh
node ./node_modules/@storybook/angular/bin/index.js
```
