### ISSUE TITLE
Notes Addon not working !

### ISSUE THREAD

**Issue by Safa2222** [storybooks/storybook#3586]
Hi, i installed the notes addon to my storybook and followed the doc steps : modify addon.js then modify config.js then modify stories using the parameter {notes : .......}. Unfortunately, this is not working and i get an 'Expecting a valid React element from the story [nameOfTheStory]' . What did i do wrong?

**Comment by Safa2222** [comment]
Oh sorry ! I didn,t see this isuue : [#3442](https://github.com/storybooks/storybook/issues/3442)

**Comment by Keraito** [comment]
No problem, glad you could find a solution in another issue. If you keep having troubles with it, feel free to open a new issue or reopen the one that you referenced. I'm closing this issue for now as your original problem is technically solved.
