### ISSUE TITLE
cli fails on custom (polymer) project with **yarn**

### ISSUE THREAD

**Issue by eavichay** [storybooks/storybook#3588]
### Fails on initializing story book (yarn issue)
I'm working on a "freestyle" project, using polymer as core library. The project WAS NOT created with the polymer-cli and the folder structure is unrelated to polymer's standard.

I have run `getstorybook` command and it failed to install npm dependencies, and failed to output it's own error.
on file `@storkybook\cli\lib\latest_version.js` I have changed the packageManager to `'npm'` and it seems to work.
```
yarn version v1.6.0
npm version 5.6.0
node version 9.11.1
```

When using 'autodetect' (with yarn) this is the error message (when I have printed manually the stderr as it fails to parse as JSON).
```
 • Detecting project type. ✓
 • Adding storybook support to your "Polymer" app

npm update check failed
Try running with sudo or get access
to the local update config store via
sudo chown -R $USER:$(id -gn $USER) C:\Users\aeyal\.config
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/polymer 3.4.4

### Affected platforms 
Windows 10

**Comment by ndelangen** [comment]
Could you try with the 4.0.0 alpha? I know there have been a couple of fixes and changes. This may have been resolved already.

**Comment by Keraito** [comment]
Confirming that this is most likely the same as https://github.com/storybooks/storybook/issues/3529#issuecomment-388006708. As stated above,  `v4.0.0-alpha.6` will fix this. Please note, @eavichay, that this most likely indicates an issue with your npm environment (and has nothing to do with yarn, for more information see the whole linked issue). You might want to try fix it (just google it and there are plenty of helpful links), as the fix on our side is to just ignore the warning.

**Comment by eavichay** [comment]
@Keraito thanks.
