### ISSUE TITLE
Is is possible to override the values of global addons

### ISSUE THREAD

**Issue by amittkSharma** [storybooks/storybook#3595]
Hi Team, 

Is it possible to override the value of global add-ons, within the story specific values?

Thanks in advance
Amit

**Comment by Hypnosphi** [comment]
It depends on which addon are we talking about. Right now it's possible at least for background and viewport addon, see examples:

http://storybooks-official.netlify.com/?selectedKind=Addons%7CBackgrounds&selectedStory=overriden&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
http://storybooks-official.netlify.com/?selectedKind=Addons%7CViewport.Custom%20Default%20%28Kindle%20Fire%202%29&selectedStory=Overridden%20via%20%22withViewport%22%20decorator&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

#3559 approach brings an easier way to override parameters for these and other addons in the future

**Comment by amittkSharma** [comment]
Hi Filipp, 

I am talking about the storybook/read-me addon.

Thanks
Amit

**Comment by Hypnosphi** [comment]
Do you mean this one? https://github.com/tuchk4/storybook-readme

This is not developed by us, so you may want to open an issue in that repo instead

**Comment by amittkSharma** [comment]
Thanks,  The issue is no opened in the respective repo.
