### ISSUE TITLE
Styles no longer imported after updating to v4.0.0-alpha - Angular 6

### ISSUE THREAD

**Issue by KolbySisk** [storybooks/storybook#3605]
### Bug or support request summary

After updating to Angular 6, Storybook stopped working. Based on the advice in [this Issue](https://github.com/storybooks/storybook/issues/3044) I updated to `4.0.0-alpha.3` This fixed my error and the Storybook server was running again, however now my styles (and fonts) aren't showing up.

I also tried updating to the latest version `4.0.0-alpha.7` but I get a giant list of errors similar to this:
`Module not found: Error: Can't resolve 'react-dom' in '/Users/KS185325/Projects/nui-angular/node_modules/velocity-react'` (Mentioned in [3602](https://github.com/storybooks/storybook/issues/3602))

### Steps to reproduce

I followed the [Angular getting started.](https://storybook.js.org/basics/guide-angular/#docs-content) Everything was working fine until I updated Angular and then updated Storybook. 

### Versions

- angular 6.0.0
- storybook/angular 4.0.0-alpha.3
- storybook/addon-actions 4.0.0-alpha.3
- storybook/addon-knobs 4.0.0-alpha.3

**Comment by wuyuanyi135** [comment]
Loading css problem probably is due to #3593. I start to use storybook just recently so I don't know whether `react-dom` was a explicit dependency. I had to install `react, react-dom@16.0.0` manually.

**Comment by igor-dv** [comment]
Alos should be related to #3491
