### ISSUE TITLE
cors calls not working

### ISSUE THREAD

**Issue by marcusnielsen** [storybooks/storybook#3613]
When I do a `window.fetch` call inside a stoy, I get a cors error.

_Please provide issue details here - What did you expect to happen? What happened instead?_ 
When I do the following call inside a story:
```
  fetch(
    'https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Vict&types=(cities)&language=pt_BR&key=[somekey]'
  )
    .then(r => r.json())
    .then(r => console.log(r))
```

I get:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Vict&types=(cities)&language=pt_BR&key=[my_key]. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

TypeError: NetworkError when attempting to fetch resource.
```

I expected storybook dev server to allow CORS calls either by default or by configuration.

I tried to add the following content to `.storybook/webpack.config.js`
```
module.exports = (baseConfig, env, defaultConfig) => {
  defaultConfig.devServer = {
    ...defaultConfig.devServer,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
      'Access-Control-Allow-Headers':
        'X-Requested-With, content-type, Authorization',
    },
  }

  return defaultConfig
}
```
but it doesn't affect the result at all.

- @storybook/react ^3.3.15
- @storybook/addon-options/register ^3.3.15

- Firefox and Chrome on Ubuntu.

**Comment by tmeasday** [comment]
Hi @marcusnielsen; sorry if I am being dense but isn't it the maps.googleapis.com server that would need to enable cors?

I think you just need to pass `{ cors: true }` to your `fetch` request..

**Comment by marcusnielsen** [comment]
@tmeasday welcome to the club of not trying to be dense about cors :-D

I think you are 100% correct. After reading your comment, I searched for some clues and found: https://stackoverflow.com/questions/30178359/how-to-enable-cors-for-google-places-api .

It basically says that their web API doesn't do cors. Yay.
I got a twitter tip on this as well, telling me to proxy through cors anywhere like this: `https://cors-anywhere.herokuapp.com/https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Vict&types=(cities)&language=pt_BR&key=[my_key]`. I'll keep it for now, and then proxy through our own server.

Thank you so much for replying, this has driven me crazy over the past week <3
