### ISSUE TITLE
Error: Unexpected value 'undefined' declared by the module 'DynamicModule'

### ISSUE THREAD

**Issue by madhumlr** [storybooks/storybook#3614]
I am using this storybook with Angular 5. I am trying to use  Knob addon. But i am getting "Unexpected value 'undefined' declared by the module 'DynamicModule'" in the browser. I get this error when I decorate my story with "withKnobs". No errors during the build.

const stories = storiesOf('Buttons', module);
**stories.addDecorator(withKnobs); //Adding this line gives error in the browser**

I have "import  'storybook/addon-knobs/register';" in my addon.js file.

My package.json
'storybook/addon-knobs': "^3.4.5",
'storybook/angular': "^3.4.5",
'babel-core': "^6.26.3"

Any help here appreciated.

Regards,
Madhukar

**Comment by Keraito** [comment]
Hey @madhumlr, this looks similar to https://github.com/storybooks/storybook/issues/3321, could you try it out with storybook [`v4.0.0-alpha.7`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.7) and see whether it resolves your issue?

**Comment by madhumlr** [comment]
Thank you @Keraito, With v4.0.0-alpha.7 version its working fine.

**Comment by viters** [comment]
@madhumlr 
You have to import knobs from `@storybook/addon-knobs/angular`, not from `@storybook/addon-knobs` 

@Keraito
There is mistake in docs https://github.com/storybooks/storybook/tree/master/addons/knobs

**Comment by Hypnosphi** [comment]
@viters master docs are for alpha, here's docs for 3.4
https://github.com/storybooks/storybook/tree/release/3.4/addons/knobs

Sorry for the confusion

**Comment by jelenans** [comment]
HI, I tried upgrading the storybook to 4.0.0-alpha.7, but still get the same error:

`Error: Unexpected value 'undefined' declared by the module 'DynamicModule'`

Does anyone have an idea what else could be the issue?

😞

**Comment by Keraito** [comment]
Hey @jelenans, sad to hear that it's not working. Can you create a new issue with what you've tried, provide us more information on your environment (specifics can be found in the issue template), what's different from the other reported issues (if you know) and what versions you're using of the different packages? We can focus on your case in that issue then!

**Comment by Sandwell** [comment]
If you declared some "props" you have to use them.
