### ISSUE TITLE
Storybook not global styles.scss file

### ISSUE THREAD

**Issue by akhildhiman1990** [storybooks/storybook#3618]
In Angular 5 storybook 3.4.5 was loading .angular-cli.json file on init and load global styles in provided in angular-cli file but after Upgrading to Angular 6 their is no longer .angular-cli.json file it is renamed to angular.json and global styles mentioned in that file. So it is not loading those styles.

**Comment by igor-dv** [comment]
There is WIP on this: #3491

**Comment by igor-dv** [comment]
Released as v4.0.0-alpha.10
