### ISSUE TITLE
Webpack plugin issue with Full Control and Default configuration

### ISSUE THREAD

**Issue by vladimirpossible** [storybooks/storybook#3620]
### Bug or support request summary

Trying to add a new webpack plugin [StyleLintPlugin](https://github.com/webpack-contrib/stylelint-webpack-plugin) to the default configuration using the combination Full control + default mode.
Expect to have the plugin run alongside the default plugins and loaders.
Nothing runs and no error message is displayed
When listing the content of defaultConfig, I can see that the plugin has a new value set to apply
```
[...]
  ProgressPlugin { profile: undefined, handler: undefined },
  DefinePlugin { definitions: {} },
  { apply: [Function: bound apply] } ]
```

### Steps to reproduce
- install StyleLintPlugin via npm
- configure the webpack.config.js with the plugin
- run storybook via CLI

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/core@3.4.4

### Screenshots / Screencast / Code Snippets (Optional)

```config.js

const StyleLintPlugin = require('stylelint-webpack-plugin');

module.exports = (baseConfig, env, defaultConfig) => {
[...]
  defaultConfig.push(
    new StyleLintPlugin(sassoptions),
  )
[...]

  return defaultConfig;
};

```

**Comment by vladimirpossible** [comment]
Turns out I have made a couple of mistake
First, it should read 
```
defaultConfig.plugins.push(new StyleLintPlugin());
```

And there shouldn't be a sassoptions object passed as a parameter of StyleLintPlugin

I'm fairly new to all of this and I don't understand why there wasn't any error messages displayed.

The Linting is working now so I will close that issue

**Comment by astrotim** [comment]
I am having this exact same issue using "Full Control Mode"

```js
const StyleLintPlugin = require('stylelint-webpack-plugin');

module.exports = storybookBaseConfig => {
  storybookBaseConfig.plugins.push(new StyleLintPlugin());
  console.log(storybookBaseConfig.plugins);
  return storybookBaseConfig;
};
```

When I log the plugins array as per the above code snippet, I also see 

```
[...]
  ProgressPlugin { profile: undefined, handler: undefined },
  DefinePlugin { definitions: {} },
  { apply: [Function: bound apply] } ]
```

@vladimirpossible I don't see any difference to how I am implementing it to what you posted in your second comment.

**Comment by vladimirpossible** [comment]
@astrotim I have had to specify the file path where my sass files where but I do not think that would change anything in your case.

`sassoptions = {
    files: 'src/components/**/*.s?(a|c)ss'
  }`

My version of stylelint is stylelint-webpack-plugin@0.10.5

The issue resolved itself on my side without really understanding how it was fixed unfortunately.
