### ISSUE TITLE
.__docgenInfo.description gives an error when used for components imported from other projects ?

### ISSUE THREAD

**Issue by Safa2222** [storybooks/storybook#3621]
Hello ! 
  I tried using **babel-plugin-react-docgen** to retrieve the documentation that i have in my components and show it in my storybook (info addon), it works with components from the project in which i installed storybook but when i try importing some from other projects that i need in my storybook, i get 'cannot find property description of undefined' for **withInfo(Component.__docgenInfo.description)** ?

**Comment by Keraito** [comment]
@danielduan @Hypnosphi Do you know whether docgen supports components imported from other projects/dependencies?

**Comment by danielduan** [comment]
No, it does not.

It is a limitation of `react-docgen` itself that it does not read props or comments from files other than the imported file. And it does not support precompiled node modules since those don't run through `babel`.
