### ISSUE TITLE
Move .storybook/configs.js

### ISSUE THREAD

**Issue by abbiteye** [storybooks/storybook#3622]
Thank you for the excellent job you are doing with Storybook. I am implementing a project in using Storybook as a platform to run automated tests. I want to move the .storybook/configs to a different path for example \\pcServer\42914\src\application\.storybook\configs.js

I want help to change the configs.js file so it points to the ../src
whitch is located on \\pcSysServer\\v2019-app-storybook\src

Thank you for your time.

  // Loading stories dynamically - automatically import all files ending in *.stories.js
const req = require.context('../src', true, /\.stories\.js$/)

function loadStories() {
  req.keys().forEach((filename) => req(filename))
}

configure(loadStories, module);

**Comment by Keraito** [comment]
A duplicate was made in #3640. But since that one is more elaborate, I will close this in favour of that one.
