### ISSUE TITLE
Chromeless Support for Storyshots

### ISSUE THREAD

**Issue by dmk255** [storybooks/storybook#3623]
### Work summary

The ability to use a different headless chrome tool to take screenshots. Specifically, [Chromeless](https://github.com/prismagraphql/chromeless) due to it's lambda support.

I'm happy to help with this endeavor. 

### Where to start

https://github.com/prismagraphql/chromeless - Has good docs for their api. My assumption is that based on a config value storyshots could determine whether to run puppeteer locally or use chromeless.

### Acceptance criteria

The ability to initiate storyshots with a chromeless config (API Key, etc) so that users can run their screenshots in lambda.

**Comment by danielduan** [comment]
If you can put together a PR, we'd be happy to take a look. Make sure you update our example Storybook to demonstrate and prove the functionality.

**Comment by igor-dv** [comment]
IMHO, image storyshots should've been separated to a separate addon (the shared code can be extracted, that's not a problem). Today when you want to bring addon-storyshots but use only regular snapshots you need to install all these puppeteer deps. I don't see how adding another headless browser thingy (even if it's useful) will simplify things here.

I think we need a refactoring that will bring some kind of separation like this:
- addon-storyshots - the initial looze storyshots api
- addon-storyshots-puppeteer-binding - extra api that brings puppeteer features
- addon-storyshots-chromeless-binding - extra api that brings chromeless features

**Comment by Hypnosphi** [comment]
Heavy plus one to @igor-dv 

If we're going to do that, right now is the best time as we're approaching major release

**Comment by igor-dv** [comment]
Yes. Will work on it 👍

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.10`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.10)

**Comment by igor-dv** [comment]
This one was not releasd =)

**Comment by dmk255** [comment]
Just wanted to chime in here and say that a chromeless adapter may not be necessary given that has [recently been deprecated](https://github.com/prisma/chromeless/pull/461).

Thank you for all the awesome work on this!
