### ISSUE TITLE
Addon storysource not workig ?

### ISSUE THREAD

**Issue by Safa2222** [storybooks/storybook#3626]
Hi, 

  I have some troubles using the addon storysource. In fact, i followed the steps in [this](https://github.com/storybooks/storybook/tree/release/3.4/addons/storysource) (since i have the 3.4 version of storybook) but i get nothing in the storysource toggle except from this : 

![image](https://user-images.githubusercontent.com/39192658/40385524-dcd5e47e-5dd4-11e8-8b81-a1e9a7f808d1.png)

Any help ? Thanks !

**Comment by Keraito** [comment]
Hey @Safa2222, could you provide us with your `config.js`, `webpack.config.js`, and the story file in which you specify your story? So we can help you further!

**Comment by corysimmons** [comment]
Same issue here. Please reopen.

`config.js`:
```js
import { configure } from '@storybook/react';

function loadStories() {
  require('../src/stories');
}

configure(loadStories, module);
```

`webpack.config.js`:
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.stories\.jsx?$/,
        loaders: [require.resolve('@storybook/addon-storysource/loader')],
        enforce: 'pre',
      },
    ],
  },
};
```

If it matters, `.babelrc`:
```json
{
  "presets": [
    "env",
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread",
    [
      "babel-plugin-root-import",
      { "rootPathSuffix": "src" }
    ],
    [
      "babel-plugin-styled-components",
      { "displayName": true }
    ]
  ]
}
```

**Comment by igor-dv** [comment]
Did you register it in the addons.js file?

**Comment by corysimmons** [comment]
@igor-dv Yes. =)

**Comment by igor-dv** [comment]
Maybe you should add this: `include: [path.resolve(__dirname, '../src')]` to the rule ?

Can't think of anything else without looking into the code 🤷‍♂️

**Comment by corysimmons** [comment]
No luck.

**Comment by igor-dv** [comment]
Can you share the repo?

**Comment by corysimmons** [comment]
Sorry I cannot and don't have time to put together a reduced test case. It's [CRA rewired](https://github.com/timarney/react-app-rewired) with [babel-plugin-root-import](https://github.com/entwicklerstube/babel-plugin-root-import).

Not terribly important if it seems to be working for everyone else... Feel free to close.

**Comment by AddictArts** [comment]
@corysimmons @igor-dv @Safa2222 @Keraito I believe I may be able to offer a solution to this, it certainly solved it for me and I had the same config and issue.

The default install for storybook using getstorybook creates a stories/index.js and the rules test in this addon is for files ending with .stories.js for example. So, a simple change to the the rules test and viola. So, if you were like me trying to see the source of "Welcome" and the buttons, it was a no go.

Note this is for a CRA rewired; However, anyone would run into this with the default story created by getstorybook. Maybe the convention of .stories.js is outdated or the README.md here should mention this.

.storybook/webpack.config.js
```
module.exports = function override(config, env) {
  config.module.rules.push({
    // test: /\.stories\.jsx?$/,
    test: /\.jsx?$/,
    loaders: [ require.resolve('@storybook/addon-storysource/loader') ],
    enforce: 'pre',
  })

  return config
}
```

**Comment by igor-dv** [comment]
Oh, wow, thanks for pointing me on this @AddictArts , I've completely missed this in the example @coryhouse has shown. 

@coryhouse, indeed in your example storysource will not be applied to your stories, however, I don't recommend to use this loader on every `js` file, because it may degrade a build time. 

You can use something like this, considering all your stories are located in the "src/stories" dir
```js
 test: /\.jsx?$/,
 include: path.resolve('./src/stories'),
```

**Comment by diegobh** [comment]
I`m getting the same error, reopen, please.

I`m getting error after create the file: webpack.config.js

addons.js:
`import '@storybook/addon-storysource/register';
import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';`

config.js:
`import { configure } from '@storybook/react';

function loadStories() {
  require('../src/stories');
}

configure(loadStories, module);`

webpack.config.js:
`module.exports = {
  module: {
    rules: [
      {
        test: /\.stories\.jsx?$/,
        loaders: [require.resolve('@storybook/addon-storysource/loader')],
        enforce: 'pre',
      },
    ],
  },
};`

Thank you!

**Comment by igor-dv** [comment]
@diegobh, your stories are located on `src/stories` that means you need to set in the rule something like `test: path.resolve('src/stories')`

**Comment by diegobh** [comment]
@igor-dv Thank you for help. I tried and it stills the same. I have all my stories in just one file: index.js inside the storybook standard folder: src/stories
Any advice? 
ty!

**Comment by mmukes1** [comment]
const path = require("path");
module.exports = {
  module: {
    rules: [
      {
        test: /\.stories\.jsx?$/,
        loaders: [require.resolve("@storybook/addon-storysource/loader")],
        test: path.resolve(__dirname, "../src/stories"),
        test: path.resolve(__dirname, "../src/components"),
        enforce: "pre"
      }
    ]
  }
};

This approach on your  .storybook/webpack.config.js   will work

**Comment by mmukes1** [comment]
const path = require("path");

module.exports = {
  module: {
    rules: [
      {
        test: /\.stories\.jsx?$/,
        loaders: [require.resolve("@storybook/addon-storysource/loader")],
        test: path.resolve(__dirname, "../src/stories"),
        test: path.resolve(__dirname, "../src/components"),
        enforce: "pre"
      }
    ]
  }
};

this approach on .storybook/webpack.config.js will work

**Comment by JabbyPanda** [comment]
The incorrect path to story files in `include` or `test` configuration most often leaves you in the dark...

It would be beneficial for the addon users if there will be some output in the console that will provide the feedback summary on the number of story files processed with it... 

consider the following format of the message:

`25 stories were found at <path> and successfully processed`

**Comment by jhamPac** [comment]
@corysimmons solution worked for me. One step I think the docs for this addon left out is that you have to notify webpack.
