### ISSUE TITLE
addon Notes does not work

### ISSUE THREAD

**Issue by petervijeh** [storybooks/storybook#3637]
### Bug or support request summary

markdown does not show up when using the notes addon.

### Steps to reproduce

After installing the notes addon and registering it:

![image](https://user-images.githubusercontent.com/39059911/40439168-28264104-5e88-11e8-9452-a61ec0958e52.png)

and then adding notes to my story

![image](https://user-images.githubusercontent.com/39059911/40439190-34b15904-5e88-11e8-8981-d3b77ecca282.png)

![image](https://user-images.githubusercontent.com/39059911/40439201-3c6e1f92-5e88-11e8-9c6b-0592bfbc3825.png)

none of the markdown appears

![image](https://user-images.githubusercontent.com/39059911/40439241-51157ba2-5e88-11e8-8c77-15e4cc91694a.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 16.2.0
- @storybook/addon-something 3.4.5

**Comment by Keraito** [comment]
Hey @petervijeh, the (markdown) content from `addon-notes` doesn't display in the story panel, but in the `NOTES` tab ([see the screenshot in this README](https://github.com/storybooks/storybook/blob/release/3.4/addons/notes/README.md)) where your addons are located. If you want to have your information in the panel you referred to, try out `addon-info`.
