### ISSUE TITLE
[addon-a11y] Usability

### ISSUE THREAD

**Issue by lokywin** [storybooks/storybook#3641]
### Summary

The a11y add-on is really good. But I had no idea each reported issue is clickable, which has super details and useful information. 

I have attached a screenshot for the proposed improvement. It is just a quick mock-up, so feel free to improve it. Thanks for working on this awesome tool.
![screen shot 2018-05-23 at 2 09 59 pm](https://user-images.githubusercontent.com/545713/40451299-1487a542-5e93-11e8-8145-14cd79ff358e.png)

**Comment by Keraito** [comment]
Thanks, @lokywin for your suggestion and mock-up, I will see what I can do for this!

**Comment by Hypnosphi** [comment]
Released as (`4.0.0-alpha.15`)[https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.15]
