### ISSUE TITLE
Use Storybook in own server / directly use react components instead of storybook bin

### ISSUE THREAD

**Issue by valorize** [storybooks/storybook#3644]
### Support request summary
Instead of running a npm script `start-storybook -p ...`
I would like to integrate storybook into a subpage of our app.
Therefore I thought it might be possible to

(prototyping on)
```
import { configure, storiesOf, getStories, componentRenderer } from "@storybook/react";
loadStories() { ... }
configure(loadStories, ...)
storiesOf.add...

export default componentRenderer(getStories);
```
Which then renders the storybook page with the defined story components within.

But I could not find anything in the docu.
Is this usecase possible?

**Comment by ndelangen** [comment]
Yes it is, but our documentation is lacking, it's not a very common use-case, but it is possible to get storybook to run as part of a larger express app.

Here's basicly what you'd need to call:
https://github.com/storybooks/storybook/blob/18f65211b83c3b0c8dd27295c0c9338110e0ab5c/lib/core/src/server/build-dev.js#L136

**Comment by valorize** [comment]
The solutuon @ndelangen proposed is not quite the thing I was looking for.
In my understanding storybook is just a page with some components which I could use in my index.tsx file.
So everything in storybook is already converted to es5 and then I should not need any webpack config for storybook.
