### ISSUE TITLE
/static/manager.bundle.js is not complete

### ISSUE THREAD

**Issue by maalej** [storybooks/storybook#3646]
Hi,
I am using storybook with react, everything seems to be ok, however loading /static/manager.bundle.js file fails.
The js code in /static/manager.bundle.js is cut (missing parts of code) 
Yarn: 1.7.0
Node: 10.0.2

Any help please?

**Comment by ndelangen** [comment]
Please make sure you're using the latest webpack 3, if you're using storybook 3.x or latest webpack 4 if you're using storybook 4.x (alpha)
https://github.com/webpack/webpack/issues/2450 seems related
