### ISSUE TITLE
XSS possibility in withInfo('')

### ISSUE THREAD

**Issue by 1Jesper1** [storybooks/storybook#3649]
XSS entered in the withInfo() function as text will be rendered as html when clicked on show info of a story.
'<IFRAME SRC=# onmouseover="alert(123)"></IFRAME>' is possible.

"storybook/addon-info": "3.2.19",
"storybook/addon-knobs": "3.2.19",
"storybook/react": "3.4.5",

**Comment by 1Jesper1** [comment]
Hello @Keraito Did you manage to reproduce this problem?

**Comment by danielduan** [comment]
This text is only configurable by the Storybook author right?

If the author wants to use XSS, I don't think we should be the judge as to whether that should be possible or not.

It would definitely be a security concern if, for example, a user is able to add the XSS script and send it to another user via the story URL parameters.

**Comment by 1Jesper1** [comment]
Ah @danielduan Thanks for the fast reply. I didn't know markdown was supported in the withInfo() method.

**Comment by 1Jesper1** [comment]
@danielduan But I don't think the `<IFRAME` tag is allowed for the markdown? There is a whitelist right?

**Comment by danielduan** [comment]
we use marksy https://github.com/storybooks/marksy for markdown rendering.

I don't see a filter for types of html elements but I could be wrong. Feels to me like this a very small edge case that users have to specifically has to opt into and I don't think we should prevent them from doing it.
