### ISSUE TITLE
React form without clicking submit button

### ISSUE THREAD

**Issue by Alphapage** [storybooks/storybook#3651]
Hello,

I can't find any example on how storybook can simulate a click on a button.
For now, I have a react form with a button to submit data. So, I manually click this button to show the validation process in storybook.

What I would like would be that storybook clicks the button when I select the story. 
Is it possible ?

Thank you in advance for your help.

**Comment by wuweiweiwu** [comment]
@Alphapage I would add a `componentDidMount` on your react component and on mount trigger the button to click via a [ref](https://reactjs.org/docs/refs-and-the-dom.html) ie `this.buttionRef.click()`

Hope that helps!.
