### ISSUE TITLE
Angular 6 doesn`t work with Knobs

### ISSUE THREAD

**Issue by ev45ive** [storybooks/storybook#3654]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Cannot use Angular 6 (webpack 4) with knobs. Works fine without knobs

Uncaught Error: Unexpected value 'undefined' declared by the module 'DynamicModule'
```
compiler.js:215 Uncaught Error: Unexpected value 'undefined' declared by the module 'DynamicModule'
    at syntaxError (compiler.js:215)
    at compiler.js:10508
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:10506)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (compiler.js:22567)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:22548)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync (compiler.js:22508)
    at CompilerImpl../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:143)
    at PlatformRef../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule (core.js:4790)
    at draw (helpers.js:89)
```
### Steps to reproduce

- install storybook
- update packages to v4.0.0-alpha.3
- install knobs
- import
```
import { text, withKnobs } from '@storybook/addon-knobs';
```
- add decorator before stories
```
addDecorator(withKnobs)
```
- or in story
storiesOf('Button', module)
.addDecorator(withKnobs)

### Please specify which version of Storybook and optionally any affected addons that you're running

```
    "@angular/core": "^6.0.3",

    "@angular/cli": "~6.0.5",

    "@angular/compiler-cli": "^6.0.3",

    "@storybook/addon-actions": "v4.0.0-alpha.3",
    "@storybook/addon-knobs": "v4.0.0-alpha.3",
    "@storybook/addon-links": "v4.0.0-alpha.3",
    "@storybook/addon-notes": "v4.0.0-alpha.3",
    "@storybook/addons": "v4.0.0-alpha.3",
    "@storybook/angular": "v4.0.0-alpha.3",
```

**Comment by ev45ive** [comment]
With story configuration as 
```
import { text, withKnobs } from '@storybook/addon-knobs';

import { Welcome, Button } from '@storybook/angular/demo';

storiesOf('Button', module)
  .addDecorator(withKnobs) // works fine without this line (no knobs)
  .add('with text', () => ({
    component: Button,
    props: {
      text: 'Hello Button',
    },
  }))
```

the code in helpers.ts fails:
```

var initModule = function (currentStory, reRender) {
    if (reRender === void 0) { reRender = false; }
    var storyObj = currentStory();
    var component = storyObj.component, template = storyObj.template, props = storyObj.props, styles = storyObj.styles, _a = storyObj.moduleMetadata, moduleMetadata = _a === void 0 ? {} : _a;
   
```
`component` is undefined, so declaration has undefined

**Comment by ev45ive** [comment]
function withKnobs(storyFn, context) {
  return wrapperKnobs()(storyFn)(context);
}
Context had undefined fileName parameters
kind:"Button"
parameters:{fileName: undefined}
story:"with some emoji"

**Comment by Keraito** [comment]
Hey @ev45ive, this looks similar to #3614. Can you try either 
> could you try it out with storybook v4.0.0-alpha.7 and see whether it resolves your issue? https://github.com/storybooks/storybook/issues/3614#issuecomment-390807269 

or 

> You have to import knobs from @storybook/addon-knobs/angular, not from @storybook/addon-knobs. It works with 3.4.5. https://github.com/storybooks/storybook/issues/3614#issuecomment-392150241 

and see whether it resolves the issue?

**Comment by ev45ive** [comment]
Changed import to  `@storybook/addon-knobs/angular`
Then it complained about 'react' 'react-dom' and 'babel-core'

then it worked perfectly! Thanks a lot @Keraito !

Please make sure Docs are updated - now its misleading telling you to include `@storybook/addon-knobs` instead of `@storybook/addon-knobs/angular`
https://github.com/storybooks/storybook/tree/v4.0.0-alpha.7/addons/knobs#with-angular

**Comment by Keraito** [comment]
> master docs are for alpha, here's docs for 3.4
https://github.com/storybooks/storybook/tree/release/3.4/addons/knobs
Sorry for the confusion
-- https://github.com/storybooks/storybook/issues/3614#issuecomment-392325624

No problem @ev45ive, glad it worked for you. Thank you for noticing us, we are aware of this (see quote above) and this is actually something that has to do with how we manage branches. Sorry for the confusion.
