### ISSUE TITLE
Question: ESLint no-undef errors for `module` parameter

### ISSUE THREAD

**Issue by IanVS** [storybooks/storybook#3656]
### Bug or support request summary

I'm just starting out with storybook, and am having difficulty understanding what the `module` parameter to `configure(loadStories, module);` and `storiesOf('Button', module)` is for, and how people typically deal with it being reported by ESLint.  I've looked through a few of the example repos, and it doesn't seem like other projects are having to disable the rule.  I assume there's some babel magic going on that injects a definition for `module`.  But if that's so, why can't babel also inject the parameter to `configure` and `storiesOf`?

What is the "standard" way to handle these linting errors?  Are there some docs explaining `module` and how to deal with it somewhere that I haven't found?

**Comment by IanVS** [comment]
I feel like an idiot and am tempted to delete this issue, but instead I'll make a note here for any future travelers who might come across this problem.  The `module` parameter is a node global.  So adding the `node` [eslint environment](https://eslint.org/docs/user-guide/configuring#specifying-environments) solves the problem (either in a config file, or a config comment).

**Comment by joeytwiddle** [comment]
But those storybook files don't actually execute in Node, do they? They are client files.

I used `commonjs` instead of `node`.

In `.eslintrc`: `env: { "commonjs": true }`

Or at the top of the file: `/* eslint-env commonjs */`

**Comment by wangdeweiseven** [comment]
tks
