### ISSUE TITLE
Errors logged by `official-storybook`

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#3679]
@ndelangen I'm creating an issue recording what I find here.

## "Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail."

This is due to switching certain UI components from classes to SFCs. The actually use of the ref comes on this line of `react-komposer`:

https://github.com/storybooks/react-komposer/blob/975fa67f07ca75f889ae2161b047b4d7037fa013/src/compose.js#L126-L128

I'm not sure if that `ref` is ever used (perhaps @Hypnosphi remembers something) but if I pass `{ withRef: false }` as a second argument to `compose()` [here](https://github.com/storybooks/storybook/blob/master/lib/ui/src/modules/ui/containers/layout.js#L22) and [here](https://github.com/storybooks/storybook/blob/master/lib/ui/src/modules/ui/containers/addon_panel.js#L17) the error goes away (and the UI still appears to work).

## Warning: Unsafe lifecycle methods were found within a strict-mode tree

This issue: https://github.com/emotion-js/emotion/issues/644

Plus similar problems with `react-split-pane` ([our issue](https://github.com/tomkp/react-split-pane/issues/261) and `react-modal` (https://github.com/reactjs/react-modal/issues/649), et al (Velocity also)

**Comment by merlinpatt** [comment]
I'm getting the bug: `Stateless function components cannot be given refs. Attempts to access this ref will fail.` as well. This happened after I decided to upgrade to the v4 alpha

It further says to check the following spots

  * Check the render method of `Container(Layout)`.
  * Check the render method of `Container(AddonPanel)`

So far, everything seems to be working despite the bug.

**Comment by ndelangen** [comment]
"Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail." is being fixed right now on the theming branch

**Comment by igor-dv** [comment]
BTW, It happens on every app, because of the manager.

**Comment by marvinhagemeister** [comment]
Comment to keep this issue open. We just ran into it with `v4.0.0-alpha10`.

**Comment by gnomeontherun** [comment]
It happens with using Angular at 4.0-alpha10 as well

**Comment by shiftsave** [comment]
seeing this issue still trying to incorporate an emotion theme decorator:

```javascript
import React from 'react';
import { storiesOf } from '@storybook/react';
import { Button } from './Button';
import { ThemeProvider } from 'emotion-theming';
import { theme } from '../../constants/theme';


const Theme = storyFn => (
    <ThemeProvider theme={theme}>{storyFn()}</ThemeProvider>
);

storiesOf('Components/Button', module)
    .addDecorator(Theme)
    .addWithJSX('primary', () => (
    <Button>I am a Button</Button>
));

```

**Comment by igor-dv** [comment]
It's not happening anymore.

**Comment by shiftsave** [comment]
thanks!
