### ISSUE TITLE
Access to the variable `global` in React Native

### ISSUE THREAD

**Issue by mashwinprdxn** [storybooks/storybook#3682]
### Bug or support request summary
I'm working on a React Native project created using `react-native init`. The app's color palette is stored in the `global` variable and is accessible throughout the react native code as: `global.PALETTE.PRIMARY.MAIN`. This variable isn't accessible when I import a component in storybook.

### Steps to reproduce
- Create app using `react-native init`
- Add storybook to project using the `getstorybook` command
- Run storybook by running the command `npm run storybook`
- Import one of the components that uses the `global` variable into `storybook/stories/index.js` and add these lines to the end:
    ```
    storiesOf('Screens', module)
      .add('LogFood', () => <LogFood/>)
    ```   
### Setup
- react: 16.3.1
- react-native: 0.55.4
- Developing for Android Lollipop 5.1.1

**Comment by soundyogi** [comment]
I have a similar Question.

I want to use the web3 provider (metamask) in my components but it is only available in the non-iframe global context.

How could one make such variable available to the stories?
