### ISSUE TITLE
Categories are sorted but Stories order is uncertain

### ISSUE THREAD

**Issue by dioxmio** [storybooks/storybook#3688]
### Bug or support request summary

Sorting is only working for high level items, not for stories. Tried used the provided option `sortStoriesByKind`

### Steps to reproduce

```
storiesOf('1. Fields', module)
    .add('2. item2', () => </>);

storiesOf('1. Fields', module)
    .add('1. item1', () => </>);

storiesOf('1. Fields', module)
    .add('3. item3', () => </>);

storiesOf('2. Layout', module)
    .add('3. item3', () => </>);
```

`setOptions({
    sortStoriesByKind: true,
});`

will only order `1. Fields` `2. Layout` but inside `1. Fields` items will not be sorted

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/addon-options  3.4.2

### Acceptance criteria

All items need to be sorted

something like this can be done

```
function sort(stories, sortStoriesByKind) {
  if (!sortStoriesByKind) return stories;
  stories = stories.map((item) => {
    item.stories = sortBy(item.stories);
  }
  return sortBy(stories, ['kind']);
}
```

and problem will be solved. what do you think? I could create PR if needed :D

**Comment by Keraito** [comment]
I added edited your multiline codeblocks to use triple backticks for readability purposes.

**Comment by igor-dv** [comment]
@dioxmio, sounds legit, wanna PR? 
Not sure if it's breaking change or not though...

**Comment by dioxmio** [comment]
sure, I will try to create the PR this week @igor-dv :D

**Comment by EskelCz** [comment]
@dioxmio  *bump* pretty please :)
can reproduce, things get messy without sorting

**Comment by pkuczynski** [comment]
This is still an issue!

**Comment by dioxmio** [comment]
I am working on this PR to fix this issue
https://github.com/storybooks/storybook/pull/3963

**Comment by dioxmio** [comment]
PR was merged to master. Closing this issue then
