### ISSUE TITLE
Storybook info outputs Unknown on compound components

### ISSUE THREAD

**Issue by Fralleee** [storybooks/storybook#3691]
I believe this has been overlooked or I am missing something entirely.

**Description**
When using compound components and storybook (info addon) the Story source outputs static methods as "Unknown" and in the propTypes as empty string ("").

**Screenshots**
![image](https://user-images.githubusercontent.com/6375613/40767788-d067fbd8-64b3-11e8-8361-ed07916fc22d.png)

**Component**
```jsx
import React, { Component } from 'react'

class CompoundComponent extends Component {
  static First = ({ children }) => <h1>{children}</h1>
  static Second = ({ children }) => <p>{children}</p>
  render() {
    return this.props.children
  }
}

export default CompoundComponent
```

**Story**
```jsx
import React from 'react'
import { storiesOf } from '@storybook/react'
import { withInfo } from '@storybook/addon-info'
import CompoundComponent from 'components/CompoundComponent'

const stories = storiesOf('CompoundComponent', module)
stories.add(
  'Default',
  withInfo()(() => (
    <CompoundComponent>
      <CompoundComponent.First>Heading</CompoundComponent.First>
      <CompoundComponent.Second>This will just be a paragraph</CompoundComponent.Second>
    </CompoundComponent>
  ))
)
```

**Comment by Fralleee** [comment]
Nevermind, my bad. Did not realize I could just set displayName of the static methods and storybook would use that.

**Comment by adyz** [comment]
@Fralleee  -- I have the same issue, can you post the solution for your issue using `displayName` as you've said, coz I'm not sure where you would add that


Thanks!

**Comment by Fralleee** [comment]
I don't have access to the code right now but if I recall correctly it was something like this.

    // Outside the class definition
    CompoundComponent.First.displayName = "CompoundComponent.First"
    CompoundComponent.Second.displayName = "CompoundComponent.Second"

**Comment by adyz** [comment]
@Fralleee  - Thank you!
I am using TypeScript and TS doesn't allow me to set `displayName` as you've mentioned so I had to create a new ReactComponent, set the `displayName` to that and than reference the static method to the new class like so:

```js

class TempClass extends React.Component {
    static displayName = 'Banner.Section';
    public render() {
        return <h1>{this.props.children}</h1>;
    }
}

class Banner extends React.Component<BannerProps> {
    static Section = TempClass;
    public render() {
        return (
            <div className="banner">
                 {this.props.children}
            </div>
        );
    }
}

export default Banner;

```

**Comment by wintercounter** [comment]
Same issue with React's 16.6 memo feature.
