### ISSUE TITLE
Special characters in info addon

### ISSUE THREAD

**Issue by Safa2222** [storybooks/storybook#3692]
Hello !
    I am using the addon info to retrieve jsdoc automatically from a project that is documented in french into my storybook. Unfortunately, special characters like "é", "à" or "ô" aren't rendered correctly in the info body. I tried using hex codes, numerical codes... but they are rendered as they are written. Is there a way to fix this ? 

![image](https://user-images.githubusercontent.com/39192658/40788740-bf1a9be6-64be-11e8-97c1-00ce38ed4c49.png)

**Comment by igor-dv** [comment]
Is it still a problem?
