### ISSUE TITLE
Development guidelines for addons

### ISSUE THREAD

**Issue by moshe** [storybooks/storybook#3693]
### Development guidelines for add-ons
Hey,
I want to modify the storyshots addon but I can't understand how should I check my code and run it against existing project with storybook configures.
I have a working setup (`vue-kitchen-sink` from the examples) with storyshots working.
Next step is to change the source code of storyshots and tun `jest` inside my example again.
what is the best way to do it? cause changing the code / running `yarn run prepare` / `lerna run prepare --parallel -- --silent` not working for me

Thanks!

**Comment by Keraito** [comment]
Hey @moshe, if you're trying to do everything inside the `storybook` repo, you should follow [this setup](https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#initial-setup), spin up the dev server and then when you run the storybook of the `vue-kitchen-sink` f.e. you will see the changes that you made in the addon. 

If the project that you're running the storyshots on is external, you need to do [set up a link](https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#working-with-your-own-app) between the addon and your project.

Is this helpful for you?

**Comment by moshe** [comment]
@Keraito Yes, thank you!
You are doing a wonderful job
