### ISSUE TITLE
Access storybook as library in iframe

### ISSUE THREAD

**Issue by chrisvxd** [storybooks/storybook#3695]
### Work summary

Make `getStorybook` available in the iframe, exporting `preview` as a library by default.

Some tools, like [story2sketch](https://github.com/chrisvxd/story2sketch), require users to export `getStorybook` in their config to add to `preview.js`, and then override their webpack config to enable `preview` to be accessed as a library in the iframe. In story2sketch, the iframe is loaded into puppeteer and the available stories extracted (see https://github.com/chrisvxd/story2sketch/blob/chris/add-examples/src/server/getStorybook.js).

The story2sketch README instructs users override their storybook webpack config:

```js
module.exports = (storybookBaseConfig, configType) => {
  const newConfig = {
    ...storybookBaseConfig
  };

  // Add this:
  // Export bundles as libraries so we can access them on page scope.
  newConfig.output.library = "[name]";

  return newConfig;
}
```

And to export `getStorybook` in their config:

```js
import { getStorybook } from "@storybook/react";

...

export { getStorybook }
```

It would be a nice enhancement to move this upstream, to make the setup of tools like story2sketch simpler.

### Where to start

lib/core/src/server/config/webpack.config.prod.js

### Acceptance criteria

* Running `preview.getStorybook()` in the iframe will return storybook.
*  Nothing breaks for existing users.

### Who to contact

Core storybook team, or myself (@chrisvxd) for any more info.

**Comment by chrisvxd** [comment]
Still keen to see this one added, but unfortunately don't time to do it myself right now.

Is it likely to get picked up by core at any point?

**Comment by igor-dv** [comment]
I think that you can try to extend a webpack.config.js with simething like this:

```js

const path = require('path');

module.exports = (storybookBaseConfig, configType, defaultConfig) => {
  storybookBaseConfig.entry.preview.push('myfile.js');
};
```

in `myfile.js` you can set the storybook object to global scope...

**Comment by chrisvxd** [comment]
I believe this might become a non-issue in storybook 4 due to https://github.com/storybooks/storybook/pull/3058
