### ISSUE TITLE
Where is the source code for the jest integration example?

### ISSUE THREAD

**Issue by quinn** [storybooks/storybook#3698]
Where is the source code for this example:

http://storybooks-official.netlify.com/?selectedKind=Addons%7Cjest&selectedStory=withTests&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Ftests%2Fpanel

?

**Comment by Keraito** [comment]
Hey @quinn, are you looking for `addon-jest.stories.js` and `addon-jest.testresults.json` on https://github.com/storybooks/storybook/tree/master/examples/official-storybook/stories?

**Comment by quinn** [comment]
yes, thank you!
