### ISSUE TITLE
error: unknown option `--metro-config' when integrating with react native typescript

### ISSUE THREAD

**Issue by Albert-Gao** [storybooks/storybook#3700]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
`npm run story` expect to work, but throws error instead

```bash
albert:ttt albertgao$ npm run storybook

> ttt@0.0.1 storybook /Users/albertgao/codes/temp/ttt
> storybook start -p 7007 --metro-config $PWD/rn-cli.config.js


  error: unknown option `--metro-config'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ttt@0.0.1 storybook: `storybook start -p 7007 --metro-config $PWD/rn-cli.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ttt@0.0.1 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/albertgao/.npm/_logs/2018-06-02T10_58_22_014Z-debug.log

```

### Steps to reproduce

1. Create a new react-native app: `react-native init test --template typescript`
2. Setup typescript support : `cd test && node setup.js`
3. `getstorybook`
4. replace `storybook` command with `storybook start -p 7007 --metro-config $PWD/rn-cli.config.js`
5. Run `npm run storybook`

### Please specify which version of Storybook and optionally any affected addons that you're running

- "react-native": "0.55.4"
- "@ storybook/react-native": "^3.4.6",
- "@ storybook/addon-actions": "^3.4.6",
- "@ storybook/addon-links": "^3.4.6",-
- "@ storybook/addons": "^3.4.6",

Found a PR https://github.com/storybooks/storybook/pull/3694, but seems the updated content not work at all.

**Comment by ikesyo** [comment]
That is because you are using 3.4.6 but the option was added from 4.0.0-alpha.2.

**Comment by Albert-Gao** [comment]
Thanks! It works now!

**Comment by iRoachie** [comment]
Has this feature been removed? This fails for me using `4.0.0-alpha.16`
