### ISSUE TITLE
Up/Down Arrow Support

### ISSUE THREAD

**Issue by AustinMCrane** [storybooks/storybook#3702]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I know there is a hot key setup to go through the storyboards but i would have thought with the side bar in focus that the up and down arrows would go through the storyboards.

### Steps to reproduce

with side bar in focus:
![image](https://user-images.githubusercontent.com/12687588/40919027-dc5dd3aa-67cd-11e8-8d01-0fa15c428fd6.png)

up arrow should go to:
![image](https://user-images.githubusercontent.com/12687588/40919049-edc4790a-67cd-11e8-9dda-de3c8c26b3da.png)

### Please specify which version of Storybook and optionally any affected addons that you're running
```
    "@storybook/addon-actions": "^3.4.6",
    "@storybook/addon-centered": "^3.4.6",
    "@storybook/addon-knobs": "^3.4.6",
    "@storybook/addon-links": "^3.4.6",
    "@storybook/addons": "^3.4.6",
    "@storybook/cli": "^3.4.6",
    "@storybook/react": "^3.4.6",
```
### Affected platforms 

- mac, but i believe any platform would be affected
- browser: chrome

**Comment by brunoreis** [comment]
This is a nice UX feature.

**Comment by Regaddi** [comment]
If keyboard navigation is a thing, you can actually tab through the menu links. You can also open and close the groups with enter.
Hijacking up/down arrow keys will possibly break the ability to scroll the frame with your keyboard.

**Comment by ndelangen** [comment]
Cool, will add this to my UI overhaul!

**Comment by ndelangen** [comment]
Done

**Comment by ndelangen** [comment]
@Jessica-Koch

**Comment by Jessica-Koch** [comment]
I'm working on this :)

**Comment by tmeasday** [comment]
This working in v5

**Comment by shilman** [comment]
Released in alpha: https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.0
