### ISSUE TITLE
Add support for launching Storybook with different groups of files

### ISSUE THREAD

**Issue by lavelle** [storybooks/storybook#3704]
### Bug or support request summary

As far as I can see the only way to customise which files are loaded into Storybook is via the `--config-dir` option, providing a new `config.js` which calls `configure` with a different set of `require` calls for different files.

Unfortunately, this also requires duplicating the entire Storybook setup, namely `addons.js`, `webpack.config.js` and `preview-head.html`.

We have reached the point in our Storybook usage at @thumbtack (100s of stories, some of which are very heavyweight) that running it with every story in our codebase is getting problematic. It takes several minutes to run the initial webpack build, seconds to switch between stories in the UI, and 10s of seconds to run Webpack Dev Server incremental rebuilds.

As such, we need a way to run `start-storybook` with a subset of story files. The simplest solution seems to be adding a new flag like `--config-file` that would allow you to specify a different `config.js` file, and would override the `config.js` found in `--config-dir`. This would allow us to define multiple config files for subsets of our codebase, without duplicating all our Storybook config for each one.

There are definitely other solutions though! Would be interested to hear your thoughts.

Many thanks for creating such a great tool.

**Comment by igor-dv** [comment]
This will be done as part of the single config file feature.
