### ISSUE TITLE
Help with addon-actions decorate

### ISSUE THREAD

**Issue by murphyke** [storybooks/storybook#3705]
The documentation on  `decorate` (from `addon-actions`) is not clear to me.

The following line blows up with a `TypeError: Object(...) is not a function` error.

```js
const stringifyDecorator = decorate([args => args.map(el => JSON.stringify(el, null, 2))]);
```

To elaborate on how the API of `decorate` is confusing to me, I don't understand the purpose of requiring an array of functions instead of just one function. My understanding is that the function is supposed to map the action arguments to whatever you want.  And ... you can provide multiple such functions that are applied in succession to each others' output? Apologies if my caffeine dearth is making me slow-witted.

- @storybook/react@3.4.6
- @storybook/addon-actions@3.4.6

**Comment by MIreland** [comment]
I'm seeing the same thing here- is the documentation up to date? I don't see 'decorate' as an available import from addon-actions.

**Comment by igor-dv** [comment]
`decorate` was introduced in v4-alpha and docs are relevant to the master branch which is a v4. 

The 3.4 release is here - https://github.com/storybooks/storybook/tree/release/3.4

**Comment by MIreland** [comment]
Perfect! Thanks.
