### ISSUE TITLE
Angular assets not available - 404 error

### ISSUE THREAD

**Issue by ev45ive** [storybooks/storybook#3711]
### Bug or support request summary

Angular Stories cannot load assets from /src/assets

### Steps to reproduce

project generated with angular cli and storybook added using storybook-cli

angular.json:
```
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
```

### Please specify which version of Storybook and optionally any affected addons that you're running

```
    "@storybook/addon-actions": "^4.0.0-alpha.7",
    "@storybook/addon-knobs": "v4.0.0-alpha.7",
    "@storybook/addon-links": "^4.0.0-alpha.7",
    "@storybook/addon-notes": "^4.0.0-alpha.7",
    "@storybook/addons": "^4.0.0-alpha.7",
    "@storybook/angular": "^4.0.0-alpha.7",
```

there are font files in assets/fonts but:
i get 404 error

GET http://localhost:6006/assets/fonts/SourceSansPro-Bold.ttf 404 (Not Found)

**Comment by igor-dv** [comment]
Will be fixed here #3491.

**Comment by saviomisael** [comment]
I do it using staticDirs configuration with objects.
My main.ts from .storybook folder.
```
import type { StorybookConfig } from '@storybook/angular';

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/angular',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  staticDirs: [{ from: '../src/assets', to: '/assets' }],
};
export default config;
```

**Comment by dorpeled** [comment]
> I do it using staticDirs configuration with objects. My main.ts from .storybook folder.
> 
> ```
> import type { StorybookConfig } from '@storybook/angular';
> 
> const config: StorybookConfig = {
>   stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
>   addons: [
>     '@storybook/addon-links',
>     '@storybook/addon-essentials',
>     '@storybook/addon-interactions',
>   ],
>   framework: {
>     name: '@storybook/angular',
>     options: {},
>   },
>   docs: {
>     autodocs: 'tag',
>   },
>   staticDirs: [{ from: '../src/assets', to: '/assets' }],
> };
> export default config;
> ```

 I added and updated the `staticDirs` line to work with the file structure of our platform, and it works great:
`staticDirs: [{ from: '../../../../assets', to: '/assets' }]`

Thanks
