### ISSUE TITLE
Angular 6 readme

### ISSUE THREAD

**Issue by therepo90** [storybooks/storybook#3713]
### Bug or support request summary

1) I can't get my head around adding decorator wrapping my story into a div
2) I can't make my storybook to serve static assets

Readme could be improved .

**Comment by ev45ive** [comment]
+1 Same here. Can`t figure a proper way to:
1. add global styles
2. serve assets - like fonts or images that I could use from styles or in templates

**Comment by wuyuanyi135** [comment]
Isn't Angular 6.0 support still in alpha? I have to get alpha and apply some workarounds #3593 to make it work.

**Comment by therepo90** [comment]
These usages don't contain wrappingstories around div. Only dependencies etc.
Assets: well Im using angular assets property and im using dynamic sources(that should be handled from /assets) but they are not ;/
