### ISSUE TITLE
getstorybook --html does not work

### ISSUE THREAD

**Issue by DannyMoerkerke** [storybooks/storybook#3718]
getstorybook --html does not work, it reports "unknown option '--html'"

storybook/cli 3.4.6
storybook/html 4.0.0-alpha.4
MacOS 10.13.5
Node 9.7.1

**Comment by igor-dv** [comment]
You probably need to use `@storybook/cli` 4 as well.

**Comment by DannyMoerkerke** [comment]
Great! I can confirm this works:
`@storybook/cli 4.0.0-alpha.8`
`@storybook/html 4.0.0-alpha.8`

I have a few other issues but I will dig into that and open a separate issue when needed, thanx!
