### ISSUE TITLE
publicPath attribute not working in the customised webpack config ?

### ISSUE THREAD

**Issue by Safa2222** [storybooks/storybook#3720]
Hello guys !
    I need to load some ressources from a repository  /bin/ to be used in the components displayed by the storybook. Unfortunately, it seems like the "publicPath" attribute of the "output" in my webpack.config.js is not taken into account. Is it a limitation of storybook ? here is the part i am working on in my webpack.config : 

` output: {
      path: path.resolve(__dirname, './../bin'),
      publicPath: '/bin/',
   },`

**Comment by igor-dv** [comment]
I think it's duplicate to #3172.
