### ISSUE TITLE
Actions addon doesn't work on Edge

### ISSUE THREAD

**Issue by dietergeerts** [storybooks/storybook#3729]
### Bug or support request summary

I'm just setting up Storybook, and tried the MyButton example with the Actions addon. This works on Chrome, but not on Edge. The actions aren't outputted, and no error is being logged on the console.

### Steps to reproduce

Run the Vue MyButton example on Edge

### Please specify which version of Storybook and optionally any affected addons that you're running

```
    "@storybook/addon-actions": "3.4.6",
    "@storybook/vue": "3.4.6",
    "babel-core": "6.26.3",
    "vue-loader": "14.2.3",
    "vue-template-compiler": "2.5.16"
```

### Affected platforms 

- Edge browser

**Comment by danielduan** [comment]
![screen shot 2018-06-08 at 3 50 24 pm](https://user-images.githubusercontent.com/1474548/41177959-c57cf116-6b33-11e8-8a5a-9d9970ec447d.png)
![screen shot 2018-06-08 at 3 50 40 pm](https://user-images.githubusercontent.com/1474548/41177961-c758b934-6b33-11e8-8a63-46b98a9afcc4.png)
Looks like we're using something Edge 15 doesn't support.

**Comment by rhalff** [comment]
Sorry, I've only just now noticed this issue, I'll have a look.

**Comment by rhalff** [comment]
@danielduan which versions of edge need to be supported?

The lack of WeakMap can propably be solved by adding a polyfill for it, this could be done at the place wherever storybook is currently adding the polyfills. 

My current virtualbox vm is  running `Microsoft EdgeHTML 16.16299` which doesn't give the above error.
It does bail out on trying to access the `console.memory` property though, it throws a warning and then does not log anything.

I could hook in some browser specific tests to solve 'edge' cases. Most of those will be iterable properties which shouldn't be accessed.  Firefox has some of those also, but will just throw a warning in the console and doesn't choke.
