### ISSUE TITLE
Styles aren't cleaned up in the preview area iframe

### ISSUE THREAD

**Issue by dietergeerts** [storybooks/storybook#3733]
### Bug or support request summary

In the example I'm creating, I have added multiple components which each have their own style block and their own story. If you load the story in the browser and inspect the iframe content, you'll see a style block in the head for the current shown component. This is fine. If you now select the other component, you'll see that an extra style block is added with the styles of that new selected component, which is also fine. BUT you'll also notice that the old style block from the previous selected component isn't removed, which isn't good. Why isn't this good? Well, because these styles can interfere with each other.

The other thing I saw is that if you have a story with those two components combined, you also get two style tags. In this case I would expect only 1, where the common import styles are being placed first.

What's the reason behind this? Is this something Storybook does? Or is this because how the vue-loader loads styles? I'm trying to accomplish some dependencies between styles and components, so that only the bootstrap style files needed will end up in the final build. If this is not possible, then we'll have to revert back to using one big scss file with all imports in the correct order.

### Please specify which version of Storybook and optionally any affected addons that you're running

```
  "devDependencies": {
    "@storybook/addon-actions": "3.4.6",
    "@storybook/addon-console": "1.0.0",
    "@storybook/addon-knobs": "3.4.6",
    "@storybook/addon-notes": "3.4.6",
    "@storybook/addon-options": "3.4.6",
    "@storybook/addon-viewport": "3.4.6",
    "@storybook/vue": "3.4.6",
    "babel-core": "6.26.3",
    "node-sass": "4.9.0",
    "sass-loader": "7.0.3",
    "vue-loader": "14.2.3",
    "vue-template-compiler": "2.5.16"
  }
```

**Comment by igor-dv** [comment]
Does it happen with v4 too?

**Comment by dietergeerts** [comment]
Don't know. But v4 requires webpack 4, and it's not possible to upgrade for the moment for us. It's a bug in v3 and v4 isn't out yet.
