### ISSUE TITLE
New feature: allow configurable entrypoint instead of requiring config.js

### ISSUE THREAD

**Issue by amacleay** [storybooks/storybook#3737]
Motivation:
- I have a typescript codebase and am adding storybook to it
- I want hot-reloading and no intermediate build step

To do this, my entrypoint into the stories should be a typescript file, which will be loaded with the typescript loader.

I have a working example of this in https://github.com/amacleay/demo-storybook-ts-hotreload:
* Add `config.ts` from the story configuration directory to the entrypoints: https://github.com/amacleay/demo-storybook-ts-hotreload/blob/eb88b22e600547536ae951185c388ab81316d0c2/webpack.config.js#L11
* Create an empty `config.js` file in the config directory: https://github.com/amacleay/demo-storybook-ts-hotreload/blob/eb88b22e600547536ae951185c388ab81316d0c2/config.js

I did not find a better way to have a pure-TS config entrypoint.

Possible solution:
* Add a new configuration parameter, `entrypoint`, which ttakes the name of the entrypoint file to use in place of `config.js`

**Comment by igor-dv** [comment]
I am not sure about a new parameter solution though

**Comment by amacleay** [comment]
I'm definitely open to other ideas; I am not terribly fond of a parameter for an entry point myself, but I think it would get the job done.

**Comment by amacleay** [comment]
I've rather resigned myself to the fact that, with storybook, one needs to write the code that storybook hooks into (`config.js`, `addons.js`) using the particular babel-ified flavor that storybook expects.

FWIW, I think this is a very sub-optimal interface because, in the general case, it ties the consumer tightly into the babel configuration of storybook itself without any clear way to know what that babel configuration is and how it will behave. I think that ship has long since sailed, though.

**Comment by Hypnosphi** [comment]
Released as (`4.0.0-alpha.15`)[https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.15]
