### ISSUE TITLE
Upgrade to webpack 4

### ISSUE THREAD

**Issue by maciej-gurban** [storybooks/storybook#3738]
Hi, I've tried using the [your own webpack config](https://storybook.js.org/configurations/custom-webpack-config/#using-your-existing-config) option, but I'm using webpack 4, while storybook is still at version 2. The changes to upgrade to higher version are rather small from my experience. Is there any chance you'd upgrade?

**Comment by igor-dv** [comment]
storybook v4 is in alpha with the webpack 4 upgrade.
