### ISSUE TITLE
Knobs seems limited with Angular components

### ISSUE THREAD

**Issue by yangwen2** [storybooks/storybook#3739]
There are use cases where the input properties to a component is not directly bound to the template. In this case, updating the input properties via knobs doesn't reflect in the component.  In the case of my component, it's leveraging the input property in the constructor function.

The behavior I need is once a prop has been updated in the Knobs tab (Or provide a refresh button), it re-initializes the component using the value specified via Knobs.  Or is this already possible currently?

**Comment by igor-dv** [comment]
Can you please share some code example?

**Comment by blemaire** [comment]
Here is an example that does not work:

```js
import {storiesOf, moduleMetadata} from '@storybook/angular';
import {Component, Input} from '@angular/core';
import {withKnobs, text} from '@storybook/addon-knobs';
import {FormsModule} from '@angular/forms';

@Component({
  selector: 'simple-component',
  template: `
    {{ name || 'default' }}
    <input type="text" [(ngModel)]="name" />
  `,
})
export class SimpleComponent {
  @Input() name: string;
}

storiesOf('component', module)
  .addDecorator(withKnobs)
  .addDecorator(
    moduleMetadata({
      imports: [FormsModule],
      declarations: [SimpleComponent],
    }),
  )
  .add('notWorking', () => ({
    component: SimpleComponent,
    props: {
      name: text('Name', 'outer name'),
    },
  }));
```

**Comment by michahell** [comment]
I Have the same issue. Basically, it looks like when defining a component - instead of inlining a template - knobs do not work. Is this a known storybook caveat?

**Comment by blemaire** [comment]
@igor-dv can this be reopened?
