### ISSUE TITLE
Storybook 4 with Angular 6 fails when assets are glob objects.

### ISSUE THREAD

**Issue by santialbo-actimo** [storybooks/storybook#3750]
### Bug or support request summary
When using [glob objects](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/asset-configuration.md) as assets, running the storybook fails because the following line is expecting a string.

https://github.com/storybooks/storybook/blob/9b13bfc6e973b1b06ed2b215d7d41e5e7c4d3c74/app/angular/src/server/angular-cli_utils.js#L41

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 4 alpha 9
- @angular 6.0.4

### Who to contact
@igor-dv

**Comment by santialbo-actimo** [comment]
Thanks @igor-dv will `alpha.10` be released soon?

**Comment by igor-dv** [comment]
Usually, it happens around the weekend

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.10`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.10)
