### ISSUE TITLE
logo for storybook

### ISSUE THREAD

**Issue by worlwide** [storybooks/storybook#3755]
Hello there. I design a logo in my free time. I want to design a logo for you. What do you think ? I want to contribute you. Do you have an idea ?

**Comment by Keraito** [comment]
cc @ndelangen for contact

**Comment by designorant** [comment]
Storybook has a well received logo already, see: #1100, and https://storybook.js.org/

**Comment by worlwide** [comment]
Ohh. I m sorry. I did not see

**Comment by ndelangen** [comment]
@worlwide would love to get help with design stuff on storybook though.

We're happy with the logo we got, but there's plenty to improve in the app's UI department and our docs. There's some work being done already. discussion is mostly in our slack. which you can join:
https://now-examples-slackin-rrirkqohko.now.sh/
