### ISSUE TITLE
Can we use dynamic import with storybook?

### ISSUE THREAD

**Issue by SindreSvendby** [storybooks/storybook#3756]
### Support request summary

Is it possible to use dynamic imports with storybook?

I have tried to create an minimalistic repo to check if I was able to get this do work, and for me it seems like 99% of this is working. It's just to show the component on the page. Hopefully this is just a silly mistake from me, but I was a bit surprised not to find any examples on this when I searched around in the issues and on github  So not sure this should work either. 

I get an error message that I have not render the react component correct! 
But when logging the component I want to render I get this:
```
    ƒ () {
      return __WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement(
        'p',
        null,
        'b'
      );
    }
``` 
and I assume this is a transpiled react element that is valid. But not sure... 

I try to render it by doing `<DynamicImportedComponent />`

If you simple can not have an async function in as the second argument to `.add` is there any know workaround for this? 

### Steps to reproduce

```
git clone https://github.com/SindreSvendby/storybook-dynamic-import-example
yarn install 
yarn storybook 
open http://localhost:6006
go to the dynamic story. 
`` 
The master branch is using latest stable version (3.4,7), I have also done the same with v4-alpha.9 (latest version as of now)

### Screenshots / Screencast / Code Snippets (Optional)

![image](https://user-images.githubusercontent.com/1047421/41308625-c1af8728-6e7c-11e8-8c51-f87e65e5a2e2.png)

**Comment by igor-dv** [comment]
The `add` method is not accepting async functions. 

You can try to invert this by doing something like this:

```js

const myStories = storiesOf('Modules loading', module)
  .add('static A', () => <A />)
  .add('static B', () => <B />);

getAsyncThings().then((things) => {
  myStories.add(/* .... */);
});
```
