### ISSUE TITLE
React 16's getDerivedStateFromProps does not run

### ISSUE THREAD

**Issue by mcissel** [storybooks/storybook#3763]
### Bug or support request summary

Component state should've been initialized from the code in getDerivedStateFromProps

### Steps to reproduce

Make a story for a component that has:
```
static getDerivedStateFromProps(nextProps, prevState) {
  console.log(`doesn't run in storybook`);
}
```

### Storybook and addons that I'm running
- @ storybook/addon-actions 3.4.7
- @ storybook/addon-info 3.4.7
- @ storybook/addon-knobs 3.4.7
- @ storybook/addon-options 3.4.7
- @ storybook/addon-viewport 3.4.7
- @ storybook/react 3.4.7

**Comment by igor-dv** [comment]
I've checked it with our v4.alpha, and it does work. 🤷‍♂️

**Comment by danielduan** [comment]
It's up to the user to polyfill those functions or upgrade the React version. Storybook should theoretically support both React 15 & 16.

We've made the necessary changes in the v4 branch for these lifecycle method deprecations.
