### ISSUE TITLE
Panel broken in react native in 3.4.7

### ISSUE THREAD

**Issue by chrisdrackett** [storybooks/storybook#3764]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I upgraded to 3.4.7 and the panel in my browser is no longer displaying contents and I'm getting an error:

![ ](https://cl.ly/1R2v0O1W1k2o/download/[69d385b0df08e18c887613cfa12545fb]_Screen%20Shot%202018-06-14%20at%209.26.44%20AM.png)

### Steps to reproduce

Install storybook 3.4.7 on a react native project, run project. I'm using knobs, notes, and action plugins.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react-native 3.4.7

### Affected platforms 

- tested with iOS simulator

Note that rolling back to 3.4.6 fixes this issue.

**Comment by danielduan** [comment]
@Gongreg you have any ideas?

**Comment by chrisdrackett** [comment]
this started to happen again to a colleague of mine and after more adjustments its now working for both of us even on 3.4.7. I'm not sure what the issue was, but we ended up not needing to change anything and 3.4.7 is working correctly. I wish I could offer more info, I'll close this for now!
