### ISSUE TITLE
[vue.js] [withKnobs] addon causes to re-create a new story at knobChange

### ISSUE THREAD

**Issue by y-nk** [storybooks/storybook#3777]
### Bug summary

knobs refresh mechanism is causing the story to re-render fully instead of recycling/updating it. I've hesitated for a long time to post this issue, but actually it's also in your [v4 demo](https://storybooks-vue.netlify.com/?selectedKind=Addon%7CKnobs&selectedStory=Simple) so i thought it was worth it.

### Steps to reproduce

1. create a story
2. add a few knobs
3. add `created` and `destroyed` hooks with `console.log` to witness the bug
4. play with the knobs. you should see the div#root remounting the whole thing

The most basic story does it : 

```javascript
storiesOf('Addon|Knobs', module)
  .addDecorator(withKnobs)
  .add('Simple', () => {
    const name = text('Name', 'John Doe');
    const age = number('Age', 44);
    const content = `I am ${name} and I'm ${age} years old.`;

    return {
      template: `<div>${content}</div>`,
      created() { console.log('created') },
      destroyed() { console.log('destroyed') },
    };
  })
```

### Reproduction URL

- https://storybooks-vue.netlify.com/?selectedKind=Addon%7CKnobs&selectedStory=Simple

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue 3.4.2
- @storybook/addon-knobs 3.4.2

### Quickfix

Beware : this hack assumes that knobs properties are in the `data()` reactive space and that knobs label and properties names are synced. it is definitely not ideal but it works, and you're not using any other decorators.

`node_modules/@storybook/addons-knobs/dist/vue/index.js` :

```patch
--- node_modules/@storybook/addon-knobs/dist/vue/index.js	2018-06-10 13:30:01.000000000 +0900
+++ node_modules/@storybook/addon-knobs/dist/vue/index.js	2018-06-20 12:18:25.000000000 +0900
@@ -51,7 +51,11 @@
             var knobOptions = knobStore.get(name);
 
             knobOptions.value = value;
-            this.story = this.getStory(this.context);
+            //this.story = this.getStory(this.context);
+
+            if (name.toLowerCase() in this.$children[0])
+              this.$children[0][name.toLowerCase()] = value;
+              
             this.$forceUpdate();
           },
           onKnobClick: function onKnobClick(clicked) {
```

Example story for this fix : 

```javascript
storiesOf('Addon|Knobs', module)
  .addDecorator(withKnobs)
  .add('Simple', () => {
    const name = text('Name', 'John Doe');
    const age = number('Age', 44);
    const content = `I am ${name} and I'm ${age} years old.`;

    return {
      data() { return {
        name : text('Name', 'John Doe'),
        age : number('Age', 44)
      }},
      computed: {
        content() { return `I am ${this.name} and I'm ${this.age} years old.`
      },
      template: `<div>${content}</div>`,
      created() { console.log('created') },
      destroyed() { console.log('destroyed') },
    };
  })
```

**Comment by y-nk** [comment]
I actually produced a more reliable patch, if anyone fixing is interested : 

```patch
--- node_modules/@storybook/addon-knobs/dist/vue/index.js	2018-06-10 13:30:01.000000000 +0900
+++ node_modules/@storybook/addon-knobs/dist/vue/index.js	2018-06-20 17:04:32.000000000 +0900
@@ -38,7 +38,7 @@
           };
         },
         render: function render(h) {
-          return h(this.story);
+          return this.story.render ? this.story.render(h) : h(this.story);
         },
```

**Comment by y-nk** [comment]
Here's a better patch, in case someone needs it. This assume you don't use any other decorator (i tried to make it work with `vue-info-addon` without success)

```patch
--- node_modules/@storybook/addon-knobs/dist/vue/index.js	2018-06-20 18:49:55.000000000 +0900
+++ node_modules/@storybook/addon-knobs/dist/vue/patch.js	2018-06-20 18:36:18.000000000 +0900
@@ -38,7 +38,16 @@
           };
         },
         render: function render(h) {
+          if (!this.cache) {
+            this.cache = h(this.story);
+          }
+
+          if (this.story.data && this.cache.child) { // replicating data changes
+            Object.entries(this.story.data())
+                  .forEach(([k, v]) => this.cache.child[k] = v)
+          }
+
-          return h(this.story);
+          return this.story.render ? this.story.render(h) : this.cache
         },
```

**Comment by y-nk** [comment]
well it's not inactive, it's been ignored.

**Comment by igor-dv** [comment]
Hey @y-nk, sorry for being not responsive. In the v4 version, we changed the knobs addon to be framework agnostic, in order to support by default every new framework.

@storybooks/team, can anyone familiar with `vue` integration suggest a solution for this?

**Comment by ndelangen** [comment]
@y-nk does is this issue still current on the alpha releases?

**Comment by igor-dv** [comment]
@ndelangen, I've checked this yesterday and it does exist.

**Comment by ndelangen** [comment]
I just tried this on my local branch (a few commit ahead of master) and I'm NOT seeing the logs when change knobs, but AM seeing them when switching stories.

That seems correct to me.

Sorry this took so long to report back @y-nk. The 4.0.0 release is close now, but in the mean-time you could try the alpha release.

**Comment by kuka-radovan** [comment]
I am using `@storybook/html 4.0.0-alpha.20` and `@storybook/addon-knobs` of the same version and `root` element is still fully re-rendered when I change a knob value.
It causes some issues to me so I am wondering if it is expected behaviour or a bug.

**Comment by y-nk** [comment]
@ndelangen thanks a lot for reporting. i don't feel very secure to use an alpha build, but i'll give it a try in a separate env before migrating. is there any set date for v4 release ?

@kuka-radovan oh. is that in a clean new env ?

**Comment by kuka-radovan** [comment]
@y-nk Yes... I don't have there anything else. Only one simple story with one addon - `addon-knobs`. Nothing more, nothing less.

**Comment by yukun-kooboo** [comment]
So, Is it fixed in the current v4 alpha version?

**Comment by y-nk** [comment]
@yukun-kooboo I didn't check the alpha as the cycle release takes some time (which i totally understand).

@kuka-radovan When we discovered this bug, we had many plugins installed, and the "matriochka" pattern of plugins made this bug quite hard to fix. We had to remove every single plugin to be able to use the knobs correctly. Do you think that this new version will also work with plugins ?

**Comment by y-nk** [comment]
@yukun-kooboo I didn't check the alpha as the cycle release takes some time (which i totally understand).

@kuka-radovan When we discovered this bug, we had many plugins installed, and the "matriochka" pattern of plugins made this bug quite hard to fix. We had to remove every single plugin to be able to use the knobs correctly. Do you think that this new version will also work with plugins ?

**Comment by kuka-radovan** [comment]
Sorry guys, I forgot this issue. I switched from html renderer to polymer renderer. We are playing with web-components but we were using stencil at that time, so I thought html renderer will be better decision. But we have switched to polymers lit-element and storybook works correctly now. I’m not sure if it is still happening with old stack.
