### ISSUE TITLE
CI failing on storybook snapshots

### ISSUE THREAD

**Issue by chrisahardie** [storybooks/storybook#3782]
### Bug or support request summary

When I snapshot a story in my storybook, my CI agent will fail the test if the component in the story is using an `action` to log interactions.

### Steps to reproduce

I have this story: 
```
storiesOf('Button', module)
  .add(
    'default',
    withInfo(`
      Plain button
    `)(() =>
      (<Button onClick={ action('clicked button') }>I am a button</Button>)),
  )
```

On my Windows laptop, I can execute my tests without issue. However, my linux build agent has started complaining that snapshots don't match where ever I  have used the `action` add-on in my component. The failure is this:

```
2018-06-21T15:15:27.3848294Z     -                            clicked button()
2018-06-21T15:15:27.3861475Z     +                            clicked button
```
When the agent runs the tests, it sees a difference regarding parentheses. Anyone know what the issue might be?

### Please specify which version of Storybook and optionally any affected addons that you're running

- storybook/react: "^3.4.3",
- storybook/addon-actions: "^3.4.3",

**Comment by igor-dv** [comment]
Do you have a lock file ?

**Comment by chrisahardie** [comment]
@igor-dv Yes, that appears to be the issue. Is there any work to be done on this issue, or shall I close this?

**Comment by igor-dv** [comment]
@Hypnosphi any thoughts here? Do you think heaving a note in Migrations.md will be enough? Or we should revert the change from the latest stable?

**Comment by Hypnosphi** [comment]
If we'll consider anything that requires storyshot recollection a breaking change, we'll have 10 major releases in a year
