### ISSUE TITLE
error: unknown option `--html' on installation and initial first run.

### ISSUE THREAD

**Issue by sturobson** [storybooks/storybook#3790]
### Bug Summary

I tried setting the [alpha version of the HTML version](https://github.com/storybooks/storybook/tree/master/app/html) in a folder with a single `index.html`. Following the steps in the [getting started section](https://github.com/storybooks/storybook/tree/master/app/html#getting-started).

### Steps to reproduce

- create a blank folder
- create a simple 'Hello World' HTML page
- `npm i -g @storybook/cli`
- `getstorybook --html`

At this point I get the following error.
```
error: unknown option `--html'
```
I also followed the [similar getting started instructions](https://storybook.js.org/basics/quick-start-guide/) from the [storybook website](https://storybook.js.org), without the `--html`.

- `getstorybook`

which gave me this error:
```
 • Detecting project type. ✓
    We couldn't detect your project type. (code: UNDETECTED)
    Please make sure you are running the `getstorybook` command in your project's root directory.
    You can also follow some of the slow start guides: https://storybook.js.org/basics/slow-start-guide/
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/html` (?)

**Comment by igor-dv** [comment]
You should use an alpha version of cli as well.

**Comment by sturobson** [comment]
Thanks @igor-dv 👍 

running `npm i -g @storybook/cli@v4.0.0-alpha.10` worked great.

Do you think it would be worthwhile if I made a pull request to update the getting [started documentation](https://github.com/storybooks/storybook/tree/master/app/html#getting-started)?

**Comment by igor-dv** [comment]
Anything that makes the process clearer is welcomed 👍
