### ISSUE TITLE
addDecoratord does not work from config.js?

### ISSUE THREAD

**Issue by kriugen** [storybooks/storybook#3792]
For the sake of experiment I put the following decorator into my Button.stories.tsx

```
const stories = storiesOf('Button', module)
stories.addDecorator(story => <div style={{backgroundColor: 'red', width: '500px', height: '100px'}}>{story()}</div>)
stories.add('with text', () => <Button>Hello Button</Button>)
```

It displayed button on top of red rectangle as expected.
But when I put the same decorator inside .storybook/config.js like this

```
import { addDecorator } from '@storybook/react'
addDecorator(story => <div style={{backgroundColor: 'red', width: '500px', height: '100px'}}>{story()}</div>)
```

it does not have any effect! Could the problem be caused by @storybook/react version? When I was trying to make storybook work with typescript I had to upgrade this package from 3.4.8 version to 4.0.0-alpha.10. Here are some versions from my package.json:

```
"react": "^16.4.1",
"react-dom": "^16.4.1",
"react-scripts-ts": "2.16.0",
"@storybook/react": "4.0.0-alpha.10",
```

**Comment by igor-dv** [comment]
I've checked this with the official react example, and couldn't reproduce the problem.
Do you have any reproduction to this?

**Comment by kriugen** [comment]
Sure, please find problematic project attached. I have created it using the following steps:
1. create-react-app cra-ts-sb --scripts-version=react-scripts-ts
2. getstorybook
3. add the following to .storybook/config.js
import { configure, **addDecorator** } from '@storybook/react';
addDecorator(story => <div style={{backgroundColor: 'blue'}}>{story()}</div>)

[cra-ts-sb.zip](https://github.com/storybooks/storybook/files/2142199/cra-ts-sb.zip)

(you can see steps 1 and 2 in git history and the last one is in git diff)
But it works when I put it locally inside stories/index.stories.js

**Comment by igor-dv** [comment]
The problem in your example is that you are adding this decorator **after** the `configure` statement.

**Comment by kriugen** [comment]
Hm, when I put it before configure statement, I'm getting an error:

```
React is not defined
ReferenceError: React is not defined
    at http://localhost:6006/static/preview.bundle.js:48454:3
    at http://localhost:6006/static/preview.bundle.js:49235:14
    at renderMain (http://localhost:6006/static/preview.bundle.js:49702:17)
    at renderPreview (http://localhost:6006/static/preview.bundle.js:49735:12)
    at renderUI (http://localhost:6006/static/preview.bundle.js:48557:26)
    at Object.dispatch (http://localhost:6006/static/preview.bundle.js:46355:7)
    at ConfigApi._renderMain (http://localhost:6006/static/preview.bundle.js:49438:24)
    at render (http://localhost:6006/static/preview.bundle.js:49389:17)
    at ConfigApi.configure (http://localhost:6006/static/preview.bundle.js:49414:9)
    at Object.<anonymous> (http://localhost:6006/static/preview.bundle.js:48461:68)
```

**Comment by igor-dv** [comment]
Because you have to import React in every place you are using jsx.

**Comment by kriugen** [comment]
Ah, you are right :) Thanks for your help!
