### ISSUE TITLE
Absolute paths 

### ISSUE THREAD

**Issue by therepo90** [storybooks/storybook#3794]
### Bug or support request summary

I want to use absolute paths in .scss files e.g.
@import "styles/resets";

storybook / angular: "^3.4.6",

I'm trying to do it this way: 

const appPath = path.join(process.cwd(), 'src');
    const rule = storybookBaseConfig.module.rules.find((e) => e.test.source.indexOf('scss') > 0);
    rule.include = [appPath];

But itdoesn't seem to work.

```
File to import not found or unreadable: styles/resets.
```

**Comment by igor-dv** [comment]
Probably, the solution here is similar to #3916
