### ISSUE TITLE
Use FontAwesome 5 in storybook

### ISSUE THREAD

**Issue by 5tormTrooper** [storybooks/storybook#3798]
### support request summary
I'm using React 16.4 (create-react-app) with Storybook. I'm able to use icons in my app using the method recommended in the official [FontAwesome 5](https://fontawesome.com/how-to-use/on-the-web/using-with/react) documentation, but when creating a story for a component, the icon doesn't show, and I get a console error like this:
```
index.es.js:269 Could not find icon {prefix: "fas", iconName: "stroopwafel"}
```
**Is there a way to include fontawesome here?**

- "fortawesome/fontawesome-svg-core": "^1.2.0-14",
- "fortawesome/free-solid-svg-icons": "^5.1.0-11",
- "fortawesome/react-fontawesome": "^0.1.0-11",
- "storybook/cli": "^3.4.8",
- "storybook/addon-actions": "^3.4.8",
- "storybook/addon-links": "^3.4.8",
- "storybook/addons": "^3.4.8",
- "storybook/react": "^3.4.8",

**Comment by Keraito** [comment]
Hey @5tormTrooper would it be possible to provide (an example of) the component that you're using and how your story looks like? If you could provide a minimal reproduction repo that would be even better!

**Comment by melismae** [comment]
@Keraito @5tormTrooper  Hi there! I'm actually running into this issue, but I think I found a work around. The way that Font Awesome is currently recommending that you use icons in React is by importing the following in your App.js
```
import { library } from '@fortawesome/fontawesome-svg-core'
import { faCheckCircle, faTimesCircle, faExclamationTriangle, faInfoCircle } from '@fortawesome/free-solid-svg-icons'
...
library.add(faCheckCircle, faTimesCircle, faExclamationTriangle, faInfoCircle);
```

In my Icons.js file, I then do the following:
```
import styled from 'styled-components';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { colors } from '../../styles/theme';

const Icon = styled(FontAwesomeIcon)``;

const IconSuccess = Icon.extend.attrs({ icon: 'check-circle' })`
    color: ${colors.green};
`;
```
I use the IconSuccess, for instance in an input field module on clearing a warning, but when I import that module into Storybook, I receive the error that @5tormTrooper mentions above, and the icon does not appear.

The work around is to register the library and import the icons in your Storybook config as you do in your App.js (or whatever), but I wonder if there's another way to do this that I'm missing?

**Comment by bgaynor78** [comment]
I know this is a closed issue and doesn't have a resolution, per se, but I just wanted to confirm what @melismae provided above with a bit more detail that works for my case. As mentioned, you need to add the Fontawesome imports of the `library` helper and the actual icons you want to use into something like your preview.js config in .storybook like:

```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faAsterisk, faChevronDown } from '@fortawesome/pro-light-svg-icons';

library.add(faAsterisk, faChevronDown);
```

Then you should be able to use the icons with the usual references detailed in Fontawesome's docs. Hope this detail helps anyone coming from the Google. 😄

**Comment by JanKalkan** [comment]
To add my 2 cents here, in case someone has the same problem.

There is actually an alternative to installing and importing the library in preview.js as mentioned by @bgaynor78 and @melismae. 

You can create the file .storybook/preview-header.html. There, you could just import font awesome via URL. This might be especially useful in case you don't want or can't use the lib-specific FontAwesomeIcon component and instead want to use plain html or you want to include a pro kit via URL:

    <script src="https://kit.fontawesome.com/xxxx.js" crossorigin="anonymous"></script>

Consequently, you can just use the html snippet like this:

    <i class="fa-solid fa-angle-down"></i>

**Comment by michaelpoltorak** [comment]
The solution suggested by @JanKalkan works well - just be aware that the file should be named  `.storybook/preview-head.html`. 

In `.storybook/main.ts` you can also use the `previewHead` function to include fonts and other assets. See: [https://storybook.js.org/docs/api/main-config-preview-head](https://storybook.js.org/docs/api/main-config-preview-head)
