### ISSUE TITLE
old knobs readme not clear

### ISSUE THREAD

**Issue by pashute** [storybooks/storybook#3808]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
problem with .md file in old storybook knobs repo

_Please provide issue details here - What did you expect to happen? What happened instead?_ 
Expected readme to be clear and with correct English

### Steps to reproduce
Take the following and replace the contents of the readme with them:

    # React Native Storybook

    This repo is out of date and no longer maintained. 
    The NPM package was originally called **@kadira/react-native-storybook**  

    A new repo with an updated version of the contents of this NPM package 
    is now called **@storybook/react-native** 
    and the code can be found at https://github.com/storybooks/storybook/tree/master/app/react-native 
    Please use that package. It is now part of the  [Storybook monorepo(https://github.com/storybooks/storybook/).

    WARNING: The repo you are looking at now is out of date and no longer maintained.

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._
read the readme file on https://github.com/storybook-eol/react-native-storybook/blob/master/readme.md

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react all
- @storybook/addon-knobs all

### Affected platforms 
Web

**Comment by igor-dv** [comment]
We are not supporting the EOL repo. In spite the typos, IMO, it's clear enough that it's unmaintained. 
Even though, you are welcome to PR any clarifications that will help others to understand the situation.
