### ISSUE TITLE
MenuLink.js:21 Uncaught TypeError: (0 , _reactEmotion2.default) is not a function

### ISSUE THREAD

**Issue by parris** [storybooks/storybook#3811]
### Bug or support request summary

While using alpha v10, I started the server, ran storybook and saw a white screen (no content rendered). When opening the browser console. I saw an error `MenuLink.js:21 Uncaught TypeError: (0 , _reactEmotion2.default) is not a function`. When pausing the script before the error occurred I noticed that `reactEmotion.default.default` is likely the expected value, so it seems that reactEmotion is getting double wrapped or something. This package is being used by storybook's "MenuLink" component, which is why I'm opening this up here.

### Steps to reproduce

I upgraded from v3 to v4 on an existing project. This project does auto generate examples rather than manually specifying stories. Not sure if that is related in anyway.

### Please specify which version of Storybook and optionally any affected addons that you're running

    "@storybook/addon-actions": "^v4.0.0-alpha.10",
    "@storybook/addon-console": "^1.0.0",
    "@storybook/addon-info": "^v4.0.0-alpha.10",
    "@storybook/addon-knobs": "^v4.0.0-alpha.10",
    "@storybook/addon-links": "^v4.0.0-alpha.10",
    "@storybook/react": "^v4.0.0-alpha.10",
    "babel-core": "^6.26.3",
    "lodash": "^4.17.10",
    "prop-types": "^15.6.1",
    "react": "16.4.1",
    "react-dom": "16.4.1",
    "react-intl": "^2.4.0",
    "react-storybook-addon-props-combinations": "^1.0.1",
    "react-storybook-decorator-background": "^1.0.5",
    "webpack": "^4.14.0",

### Screenshots / Screencast / Code Snippets (Optional)

```js
Uncaught TypeError: (0 , _reactEmotion2.default) is not a function
    at Object.../../node_modules/@storybook/components/dist/navigation/MenuLink.js (MenuLink.js:21)
    at __webpack_require__ (bootstrap:721)
    at fn (bootstrap:98)
    at Object.../../node_modules/@storybook/components/dist/index.js (index.js:17)
    at __webpack_require__ (bootstrap:721)
    at fn (bootstrap:98)
    at Object.../../node_modules/@storybook/addon-actions/dist/components/ActionLogger/style.js (style.js:12)
    at __webpack_require__ (bootstrap:721)
    at fn (bootstrap:98)
    at Object.../../node_modules/@storybook/addon-actions/dist/components/ActionLogger/index.js (index.js:39)
```

**Comment by dustinhorton** [comment]
@parris were you able to resolve this?

**Comment by srounce** [comment]
Hi, currently running `v4.0.0-alpha.14` on a project that was upgraded from v3. Having the same issue when loading _iframe.html_.

@parris How were you able to resolve this?

**Comment by parris** [comment]
@dustinhorton and @srounce so the reason I closed this ticket was because I figured the problem was actually in my configuration and integration with storybook rather than it directly being the fault of storybook. Below is my config, I basically removed module concatenation plugin and add more resolvers:

```
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const { plugins, resolve, rules } = require('../my-webpack-config.js');

module.exports = (storybookBaseConfig) => {
  storybookBaseConfig.module.rules = storybookBaseConfig.module.rules.concat(rules);
  // I removed module concatenation plugin because it seemed problematic (I thought)
  storybookBaseConfig.plugins = plugins.slice(1).concat(
    storybookBaseConfig.plugins,
  );
  // I don't think the right extensions were compiling
  storybookBaseConfig.resolve = Object.assign({}, resolve, {
    extensions: ['.js', '.jsx', '.json'],
  });
  return storybookBaseConfig;
};
```

I don't think posting my full webpack config is particularly useful. Basically, my recommendation is to drop plugins and add the "extensions" field to "resolve".
