### ISSUE TITLE
Cannot read property 'overlayClass' of null

### ISSUE THREAD

**Issue by delasky** [storybooks/storybook#3827]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

with version of storybook provided by `yarn add -D @storybook/react (4.0.0-alpha)
getting error `Cannot read property 'overlayClass' of null`,
storybook doesn't load

error is not present in @storybook/react 3.4.8

### Steps to reproduce

I went through the manual setup react steps listed here https://storybook.js.org/basics/guide-react/

i've set up a demo repo here https://github.com/delasky/storybook_test that has the same dependencies and yarn.lock file as the private repo i experienced the bug in.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha-11

**Comment by delasky** [comment]
sorry, started opening this last night, just realized it is a dupe of #3825

**Comment by shilman** [comment]
Closing as duplicate! 👍
