### ISSUE TITLE
Can not import ngUpgraded angularjs components

### ISSUE THREAD

**Issue by doroncy** [storybooks/storybook#3828]
### Bug or support request summary
I have a hybrid app which contains both Angularjs and Angular, I use ngUpgrade in order to upgrade angularjs components and use them in angular components.
importing native angualr components works fine, but when i try to import the angularjs upgraded component i get the following error:
```
zone.js:665 Unhandled Promise rejection: MultiGroupSelectElementDirective cannot be used as an entry component. ; Zone: <root> ; Task: Promise.then ; Value: Error: MultiGroupSelectElementDirective cannot be used as an entry component.
```
please, advice, I suspect that maybe I need to original angularjs module imported and loaded, can I do it?

### Steps to reproduce
1. Upgrade angularjs component to angular.
2. import it to and create a story
3. run the storybook

### Please specify which version of Storybook and optionally any affected addons that you're running
- @storybook/angular/alpha

### Affected platforms 
- Browser

**Comment by igor-dv** [comment]
Basically, storybook doesn't support stories with pre Angular 2 components. (From the version 4 of storybook we are supporting the v6) So you can't add stories of the angularjs components as is. 

I think you need to wrap them somehow. Also, you should provide all the needed dependencies of the components to the story.

Can you please share the code example?

**Comment by SergeyMell** [comment]
Hi @doroncy, how did you manage to add StoryBook to a hybrid application? Is there any manual regarding this? Any help is appreciated.
