### ISSUE TITLE
react-native - running simulator and storybook with custom ports causes Websocket: "Connection error"

### ISSUE THREAD

**Issue by casparss** [storybooks/storybook#3835]
When running Storybook and React Native IOS Simulator supplying custom ports (i have to do this as McAfe is running on port 8081) get following screen and the Storybook UI doesn't populate with any stories. Have tried this on another machine without McAfe with same versions and it works okay! Tried setting custom ports on this same machine and it blows up again.

<img width="369" alt="screen shot 2018-07-04 at 13 57 41" src="https://user-images.githubusercontent.com/3496153/42278397-9650172e-7f92-11e8-9932-73068cee901e.png">

### Steps to reproduce
Run react native app with simulator 
```
react-native run-ios --port 8087
```

Run Storybook
```
storybook start -p 7070 --packager-port 8087
```

Have got this in my App.js file
```
export default from './storybook';
```

### Versions

```
    "react": "16.3.1",
    "react-native": "0.55.4"
    "babel-preset-react-native": "4.0.0"
    "@storybook/react-native": "^3.4.8"
    "@storybook/addon-actions": "^3.4.8"
    "@storybook/addon-links": "^3.4.8"
    "@storybook/addons": "^3.4.8"

```

**Comment by Gongreg** [comment]
Hey.
I see that this is quite an old issue and I guess you managed to found the solution. But ff anybody else comes here:

The reason you are getting this error is because you used custom port for storybook. You are using port 7070. But in generated storybook code the port is 7007. Thats why it tries to connect to port 7007 and gets websocket error.

The solution:
Change port to 7007 or go to code and update port option to 7070 in getStorybookUI.

When 4.0 is released you can use disableWebsockets option in getStorybookUI if you don't want to have a server running.

**Comment by casparss** [comment]
Hey @Gongreg thanks for replying to me. Just tried changing the supplied port back to 7007 and i get the same result, white screen on the UI and not components showing in the simulator. :(

**Comment by casparss** [comment]
`
Error: not opened
    at WebSocket.send (/Users/casparss/Projects/chorus-mobile-ui/node_modules/ws/lib/WebSocket.js:219:16)
    at send (/Users/casparss/Projects/chorus-mobile-ui/node_modules/react-native/local-cli/server/util/webSocketProxy.js:24:12)
    at WebSocket.debuggerSocket.onmessage (/Users/casparss/Projects/chorus-mobile-ui/node_modules/react-native/local-cli/server/util/webSocketProxy.js:47:46)
    at WebSocket.onMessage (/Users/casparss/Projects/chorus-mobile-ui/node_modules/ws/lib/WebSocket.js:442:14)
    at WebSocket.emit (events.js:182:13)
    at Receiver.ontext (/Users/casparss/Projects/chorus-mobile-ui/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/casparss/Projects/chorus-mobile-ui/node_modules/ws/lib/Receiver.js:536:18
    at /Users/casparss/Projects/chorus-mobile-ui/node_modules/ws/lib/Receiver.js:368:7
    at /Users/casparss/Projects/chorus-mobile-ui/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:480:3)
`

**Comment by casparss** [comment]
Actually, it's working, so all good. Used latest version of storybook / RN and with your advice it works great, thank you!

**Comment by Gongreg** [comment]
Glad to hear that. I am closing the issue.
