### ISSUE TITLE
angular - addon centered - props are NOT propagated to the component

### ISSUE THREAD

**Issue by evanliomain** [storybooks/storybook#3836]
### Bug or support request summary

The addon-centered, used with angular, do not propagate the props for the component.

### Steps to reproduce

- I use storybook with angular.
- I write a story on a component that accept some inputs.
- I use the component syntax and define props for my component.
- I want my component centered, so I use the addon-centered.
- This addon do NOT propagate the props because it work when I remove it.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 4.0.0-alpha.10
- @storybook/addon-centered 4.0.0-alpha.10

I suspect that [here](https://github.com/storybooks/storybook/blob/master/addons/centered/src/angular.js#L12) the props are NOT passed to the component.

**Comment by igor-dv** [comment]
Does it work for you if you are using template syntax?

Like here:
https://storybooks-angular.netlify.com/?selectedKind=Addon%7CCentered&selectedStory=centered%20template&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

BTW, is there any reasonable preference of using `component` and not `template`?

**Comment by igor-dv** [comment]
I think that having both options is a bit complicates the maintenance, so I would like to deprecate the `component` syntax. 

Anyway, I am closing this one, as we do have a workaround

**Comment by evanliomain** [comment]
Personally, I prefere the component syntax as it is more DRY for propagate props.

BTW, if this workaround is the solution, it would be nice to add it in the addon documentation.

**Comment by igor-dv** [comment]
I think `template` syntax is much more extensible and allow much more features (for example combining components)

**Comment by evanliomain** [comment]
I agree that 2 syntax are harder to maintain.

Does It means the `component` syntaxe is deprecate for all stories ?

**Comment by igor-dv** [comment]
Not yet. I need to commit the depreciation. Also, I've tried to understand what more people think in our slack, but nobody answered me 🤷‍♂️

**Comment by michelcve** [comment]
@igor-dv Hmm, I ran into this today as well... Since the deprecation didn't come through (or so it seems), might it be an idea to reopen this issue and fix it for component syntax anyway?

I got the impression that it's a matter of adding the properties (which are availble) to the template [here](https://github.com/storybooks/storybook/blob/master/addons/centered/src/angular.js#L12) by looping over them and adding them as attributes to the tag. But maybe I overlook some complexity?

**Comment by hiepxanh** [comment]
1) I think `component` template is very useful when you have to make a quick center every story. I mean why I not need that center? That so elegant way. If my component not at the center. I'm feeling so pain. And add style center to every component to just make it look better is really pain.
2) if I do that quick center for all component in `index.stories.ts` that will casing empty in my all component. that so really sad.
![image](https://user-images.githubusercontent.com/16970990/57177951-cbcd7b80-6e93-11e9-9b71-5d75ad9af5a9.png)

**Comment by benbrowning** [comment]
Is this likely to be fixed, or do I need to just always use the template syntax when I want to use stories (which is fine, it can just be a bit more verbose)?
