### ISSUE TITLE
Error: Plugin/Preset files are not allowed to export objects, only functions

### ISSUE THREAD

**Issue by kirill-konshin** [storybooks/storybook#3843]
### Bug or support request summary

I tried latest Storybook @ `4.0.0-alpha.12` with latest React Scripts (Create React App) @ `2.0.0-next.3e165448` and got the following error:

```
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/xxx/web/node_modules/babel-preset-stage-0/lib/index.js

ERROR in ./.storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/xxx/web/node_modules/babel-preset-stage-0/lib/index.js
```

The reason I use `2.0.0` of React Scripts is support of mono repository and Lerna.

Content of `.storybook/config.js`:

```js
import {addDecorator, configure} from '@storybook/react';
import {decorator} from "../src/stories/Wrapper";

addDecorator(decorator);

configure(() => {
    var req = require.context('../src', true, /\.story\.js$/);
    req.keys().sort((a, b) => a.localeCompare(b)).map(req);
}, module);
```

Content of `.storybook/addons.js`:

```js
import '@storybook/addon-actions/register';
import '@storybook/addon-knobs/register';
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.12
- @storybook/addon-something 4.0.0-alpha.12
- react-scripts 2.0.0-next.3e165448
- webpack @ 4.15.1

I guess it's because `2.0.0` version is using Babel 7: https://github.com/storybooks/storybook/issues/3335

**Comment by Hypnosphi** [comment]
`npm install babel-core` should fix it for now, until #3746 is merged

**Comment by kirill-konshin** [comment]
I also tried this as my `.storybook/webpack.config.js`:

```js
const path = require('path');

module.exports = {
    module: {
        rules: [
            {
                test: /\.scss$/,
                loaders: ['style-loader', 'css-loader', 'sass-loader'],
                include: path.resolve(__dirname, '../')
            },
            {
                test: /\.js$/,
                loaders: ['babel-loader'],
                include: path.dirname(require.resolve('@somenamespace/lib'))
            }
        ]
    }
};
```

But then again I am getting errors like this:

```
ERROR in ./node_modules/xxx/font.svg
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <?xml version="1.0" standalone="no"?>
```

**Comment by kirill-konshin** [comment]
@Hypnosphi do you know the reason why I get only JS loader in Full Control Mode? Should I file a bug for that or is it an expected behavior?

**Comment by Hypnosphi** [comment]
> the reason why I get only JS loader in Full Control Mode

Because you're extending base config. To get all the loader, extend default config (third argument)
See https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode--default

**Comment by kirill-konshin** [comment]
Oh, IC...

**Comment by kirill-konshin** [comment]
The final look of `webpack.config.js` is:

```js
const path = require('path');
const reactScriptsWebpackConfig = require('react-scripts/config/webpack.config.dev');

module.exports = (baseConfig, configType, defaultConfig) => {

    defaultConfig.module.rules.shift();

    defaultConfig.module.rules.unshift(reactScriptsWebpackConfig.module.rules[2].oneOf[1]);

    defaultConfig.module.rules.push({
        test: /\.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
        include: path.resolve(__dirname, '../')
    });

    return defaultConfig;

};
```

This makes sure I use same Babel config as CRA, with all the monorepo packages.

**Comment by craigcbrunner** [comment]
I am also hitting the same error, can anyone help me resolve, when I run storybook I get this:

`ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/@storybook/core/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/craig.brunner/sources/chat-webclient/redacted/node_modules/babel-preset-stage-0/lib/index.js
    at createDescriptor (/Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/config-descriptors.js:138:11)
    at items.map (/Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at passPerPreset (/Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/config-descriptors.js:53:96)
    at cachedFunction (/Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/caching.js:32:19)
    at presets.presets (/Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/config-descriptors.js:25:84)
    at mergeChainOpts (/Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/config-chain.js:304:26)
    at /Users/craig.brunner/sources/chat-webclient/redacted/node_modules/@babel/core/lib/config/config-chain.js:267:7
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true`

My .storybook webpack.config is just this:
`module.exports = {
  plugins: [
    // your custom plugins
  ],
  module: {
    rules: [
      // add your custom rules.
    ],
  },
};
`

My .babelrc is this:
`module.exports = {
    plugins: [
        '@babel/plugin-transform-react-display-name',
        'babel-plugin-add-react-displayname',
        '@babel/plugin-proposal-object-rest-spread',
        '@babel/plugin-proposal-class-properties',
        ['@babel/plugin-proposal-decorators', { legacy: true }]
    ],
    env: {
        development: {
            presets: [
                [
                    '@babel/preset-env',
                    {
                        modules: false
                    }
                ],
                '@babel/react'
            ],
        },
        test: {
            presets: [['@babel/preset-env',], '@babel/react'],
        },
        production: {
            presets: [['@babel/preset-env', { modules: false }], '@babel/react'],
        }
    }
};
`

My storybook .config is this:
`import { configure } from '@storybook/react';

// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /.stories.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
`

My versions are this:
`    "@babel/core": "^7.0.0-beta.53",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.53",
    "@babel/plugin-proposal-decorators": "^7.0.0-beta.53",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.53",
    "@babel/plugin-transform-react-display-name": "^7.0.0-beta.53",
    "@babel/preset-env": "^7.0.0-beta.53",
    "@babel/preset-react": "^7.0.0-beta.53",
    "@babel/runtime": "^7.0.0-beta.53",
    "@storybook/addon-actions": "^4.0.0-alpha.14",
    "@storybook/addon-links": "^4.0.0-alpha.14",
    "@storybook/addons": "^4.0.0-alpha.14",
    "@storybook/react": "^4.0.0-alpha.14",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.2.3",
    "babel-jest": "^23.0.1",
    "babel-loader": "^8.0.0-beta",
    "babel-plugin-add-react-displayname": "^0.0.5",`


Any help would be appreciated...

**Comment by tjbenton** [comment]
This is what I had to do to get it working correctly.

```js
// ./storybook/webpack.config.js
module.exports = (baseConfig, env, defaultConfig) => {
  // this is how storybook shows to do it in their docs so it has to be reassigned
  // add support for `.js`, `.mjs`, `.jsx`
  defaultConfig.module.rules[0].test = /\.m?jsx?$/
  defaultConfig.resolve.extensions = [ '.js', '.jsx', '.mjs' ]

  // use babel-preset-react-native instead of storybook config
  defaultConfig.module.rules[0].query.presets = [ require.resolve('babel-preset-react-native') ]
  // remove extra plugins since they don't work with babel 7, otherwise it will error
  defaultConfig.module.rules[0].query.plugins = []

  return defaultConfig
}
```

package.json

```json
"@babel/core": "^7.0.0-beta.55",
"@storybook/addon-actions": "^3.4.8",
"@storybook/addon-knobs": "^3.4.8",
"@storybook/addon-links": "^3.4.8",
"@storybook/addon-options": "^3.4.8",
"@storybook/addons": "^3.4.8",
"@storybook/react-native": "^3.4.8",
"babel-core": "7.0.0-bridge.0",
"babel-preset-react-native": "5.0.2",
```


```bash
react-native run-ios && storybook start --port 9001 --skip-packager
```

**Comment by Hypnosphi** [comment]
With current alpha (`4.0.0-alpha.20`), Babel 7 should work OK without hacks with webpack config

**Comment by dusan-dragon** [comment]
@Hypnosphi I have still this kind of problem on 4.1.2

**Comment by stigi** [comment]
@Hypnosphi I ran into the same issue on 4.1.2 with react native 0.58.4

I created a demo repo (new react native project from scratch): https://github.com/stigi/storybook-issue-3843/tree/master

cc @dusan-dragon

**Comment by sidhusubhash** [comment]
create .babelrc inside storybook directory and paste the following in it.
{
"presets": ["module:metro-react-native-babel-preset"],
}
hope this helps..

**Comment by ghobashy** [comment]
best solution is found is to add 
```
"babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ]
 }

```
in package.json
