### ISSUE TITLE
[Support] Storybook + Angular 6 multiple apps (nrwl/nx)

### ISSUE THREAD

**Issue by jogelin** [storybooks/storybook#3868]
### Bug or support request summary
I would like to setup storybook in my monorepo to be able to develop and tests shared components across all applications. 

I have an issue concerning the import of the styles because storybook is using the property `projects[0].root` to resolve the paths of all styles from `projects[0].architect.build.styles` but my styles are also specifying the full path. So I see some errors like:

```
ERROR in multi ./apps/appName/libs/core/theme.scss ./apps/appName/apps/appName/src/styles.scss
Module not found: Error: Can't resolve 'C:\Users\user\dev\projects\frontend\monorepo\apps\appName\apps\crt\src\styles.scss' in 'C:\Users\user\dev\projects\frontend\monorepo'
 @ multi ./apps/appName/libs/core/theme.scss ./apps/appName/apps/appName/src/styles.scss +1
```
and my `angular.json` contain
```
...
"projects": {
    "appName": {
      "root": "apps/appName/",
      "sourceRoot": "apps/appName/src",
      ....
      "architect": {
        "build": {
            ...
            "styles": [
              "libs/core/theme.scss",
              "apps/appName/src/styles.scss"
            ],
...
```

### Dependencies

- @angular/*: 6.0.7
- @storybook/*: 4.0.0-alpha.13

**Comment by igor-dv** [comment]
I think @rhalff was able to work arround this.

**Comment by headonkeyboard** [comment]
I've reported the same problem here : #3864

**Comment by headonkeyboard** [comment]
Does anyone managed to get it work ?

**Comment by igor-dv** [comment]
I will close this one in favor of #3864, also @marshallmick007 PRed a fix. 

@jogelin, the angular builder is still relevant IMO.
