### ISSUE TITLE
storybook-build builds a blank screen

### ISSUE THREAD

**Issue by martis347** [storybooks/storybook#3869]
I am trying to build storybook for vue. Build succeeds without any issues, however generated content is not correct. When serving the contents from _storybook-static_ the only thing I get is a blank page (no console errors/warnings/messages). If I go to localhost:5000 - it's a blank page, but if I go to localhost:500/iframe - I see a component and I can update the url accordingly and it's state changes.
The strangest part is that when running _start-storybook -p 6006_ - content is being served successfully and there are no issues. 

I expect it to work and serve stories when running _storybook-build_ the same way it does with _start-storybook -p 6006_.

### Steps to reproduce

Setup vue-cli application using properties defined below and run _build-storybook_.

### Please specify which version of Storybook and optionally any affected addons that you're running

I'm using vue-cli (3.0.0-rc.3) with: Typescript (using class-style component syntax, babel-polyfill), PWA, Router, Vuex, SCSS, Linter (tslint), Unit Testing.
Storybook was added using _getstorybook_ (@storybook/cli@4.0.0-alpha.13)

- @storybook/addon-actions": "^4.0.0-alpha.13,
- @storybook/addon-links": "^4.0.0-alpha.13,
- @storybook/addons": "^4.0.0-alpha.13,
- @storybook/vue": "^4.0.0-alpha.13

### Affected platforms 

- I've tried Firefox, Google Chrome, IE, Edge

### Code Snippets

I'm using this webpack.config.js for storybook:
```js
const merge = require("webpack-merge");
const { createDefaultWebpackConfig } = require("@storybook/core/dist/server/config/defaults/webpack.config.js");
const vueConfig = require("@vue/cli-service/webpack.config.js");

module.exports = (storybookBaseConfig, configType) => {
  const storybookConfig = createDefaultWebpackConfig(
    storybookBaseConfig,
    configType
  );
  return {
    ...vueConfig,
    entry: storybookConfig.entry,
    output: storybookConfig.output,
    plugins: merge({
      customizeArray: merge.unique(
        "plugins",
        [
          "HotModuleReplacementPlugin",
        ],
        plugin => plugin.constructor && plugin.constructor.name
      )
    })(vueConfig, storybookConfig).plugins,
    resolve: {
      ...vueConfig.resolve,
      alias: {
        ...vueConfig.resolve.alias,
        vue$: storybookConfig.resolve.alias.vue$
      }
    }
  };
};
```
This is my vue.config.js:
```
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  lintOnSave: true,
  configureWebpack: {
    resolve: {
      alias: {
        "environment": __dirname + "/environment.config",
      }
    },
    plugins: [
      new CopyWebpackPlugin([{ from: 'src/assets', to: 'assets' }])
    ],
  },
  pwa: {
    name: 'AON',
    themeColor: '#FFFFFF',
    msTileColor: '#E01F26',
    appleMobileWebAppCapable: 'yes',
    appleMobileWebAppStatusBarStyle: 'default'
  }
};
```

**Comment by wuweiweiwu** [comment]
@martis347 How are you serving the static directory?

**Comment by martis347** [comment]
@wuweiweiwu Yes I am.
We've resolved this by removing typescript from our solution. Could not find another way to get it working.

**Comment by wuweiweiwu** [comment]
@martis347 glad you found a work around.
