### ISSUE TITLE
How to display ionic-components in storybook?

### ISSUE THREAD

**Issue by roboticbit** [storybooks/storybook#3871]
Is there a way to run storybook to display components of the ionic framework?
### support request summary

I am trying to render ionic-angular components in Storybook, but I'm (probably not unexpectedly) getting template parse errors of the sort:

    compiler.js:486 Uncaught Error: Template parse errors:
    'ion-title' is not a known element:
    1. If 'ion-title' is an Angular component, then verify that it is part of this module.
    2. If 'ion-title' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the             '@NgModule.schemas' of this component to suppress this message. ("
      <ion-navbar>
        [ERROR ->]<ion-title>login</ion-title>
      </ion-navbar>
    "): ng:///DynamicModule/LoginPage.html@9:4

I have set up storybook following the slow guide to angular
https://storybook.js.org/basics/guide-angular/
 and my `src/stories/index.ts` looks like this 
### index.ts

    import { LoginPage } from './../pages/login/login';
    import { TestComponent } from './../components/test/test';
    import { storiesOf } from '@storybook/angular';
    import { action } from '@storybook/addon-actions';

    storiesOf('TestComponent', module)
    .add('page', () => ({
        component: LoginPage,
    
        props: {
          text: '😀 😎 👍 💯',
        },
      }))
      .add('with some emoji', () => ({
        component: TestComponent,
        props: {
          text: '😀 😎 👍 💯',
        },
      }))

`TestComponent` is generic 
(has been generated with from the ionic cli with`ionic generate component testComponent`)
 and is displayed fine.

`LoginPage` however fails with the error above

### version of Storybook and optionally any affected addons that you're running
I'm using  
`@storybook/addon-actions": "^3.4.8"`,
`@storybook/angular": "^3.4.8"`,

**Comment by roboticbit** [comment]
So, it appears that the answer to this lies in moduleMetadata. It had to mirror the `@NgModule` of `app.module.ts`

so now index.ts becomes:

    import { HomePage } from './../pages/home/home';
    import { TestComponent } from './../components/test/test';
    import { storiesOf } from '@storybook/angular';
    import { action } from '@storybook/addon-actions';
    import {  App, NavController,IonicModule, IonicApp } from 'ionic-angular';
    import { MyApp } from '../app/app.component';

    storiesOf('TestComponent', module)
        .add('page', () => ({
            moduleMetadata:{
            declarations:[MyApp, HomePage],
            imports:[
                IonicModule.forRoot(MyApp)
             ],
             entryComponents:[MyApp, HomePage],
             bootstrap:[IonicApp],
              providers:[App,  NavController]
        },
        component: HomePage,
        props: {
            text: '😀 😎 👍 💯',
        },
      }))
      .add('with some emoji', () => ({
           component: TestComponent,
           props: {
               text: '😀 😎 👍 💯',
           },
      }))
 

Thanks for your attention, would wecome any further comments/suggestions

**Comment by roboticbit** [comment]
Given the `moduleMetadata` object above, storybook will display the html template of the component in question.

However, none of the scss styles are displayed. Could you please indicate what I might be missing?

**Comment by igor-dv** [comment]
How are the ionic's styles loaded to your regular app?

**Comment by roboticbit** [comment]
@igor-dv apparently a main.css file is compiled under www/build that is loaded by the generated index.html.

I was able to make some more progress by using `import '../www/build/main.css'` in `.storybook/config.js`. Is there any other way?

**Comment by igor-dv** [comment]
IMO, having this file in the `assets` field of angular.json should work as well. But importing this file in `config.js` is also an acceptable solution (at least in the `React` ecosystem)

**Comment by sneko** [comment]
Hi!

I'm working on a Vue.js project and according to the Storybook docs I add the following script in the `preview-head.html` file (https://storybook.js.org/configurations/add-custom-head-tags/):
```
<script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>
```

And to show a button I create a story like this one:
```
  .add('with ionic', () => ({
    template: '<ion-button>Hello Button</ion-button>'
  }))
```

Everything works well except the font-family. It should looks like:
![image](https://user-images.githubusercontent.com/8195958/44801870-88ab6200-abba-11e8-9cb0-508377d30547.png)

But it displays like:
![image](https://user-images.githubusercontent.com/8195958/44801901-a2e54000-abba-11e8-88fa-53e695f67ff6.png)

I don't understand when the button handles a change of its font-family :( ... 

Any idea please? Thanks

**Comment by sneko** [comment]
I was following the Ionic docs but it seems I have to add the style too accoding to their repo:
https://github.com/ionic-team/ionic/tree/master/core#vanilla-html

So I need to set:
```
<link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" rel="stylesheet">
<script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>
```

Now the font-family is concording with my Vue.js app. But I don't have animations on my Ionic elements (like when I click on a button, a circle expands).

**Comment by smnhgn** [comment]
> I was following the Ionic docs but it seems I have to add the style too accoding to their repo:
> https://github.com/ionic-team/ionic/tree/master/core#vanilla-html
> 
> So I need to set:
> 
> ```
> <link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" rel="stylesheet">
> <script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>
> ```
> 
> Now the font-family is concording with my Vue.js app. But I don't have animations on my Ionic elements (like when I click on a button, a circle expands).

@sneko  I think the problem is that ionic components need ```<ion-app>``` as a parent. I got the animations to work by writing a custom decorator in the config.js to wrap my stories with ```<ion-app>```.

This is how my config.js looks like now:

```import { configure, addDecorator, moduleMetadata } from '@storybook/angular';
import { IonicModule } from '@ionic/angular';


// automatically import all files ending in *.stories.ts
const req = require.context('../src/', true, /\.stories\.ts$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

const wrap = templateFn => storyFn => {
  const story = storyFn();
  return {
    ...story,
    template: templateFn(story.template)
  };
};
const ionicWrap = wrap(content => `<ion-app>${ content }</ion-app>`);

addDecorator(ionicWrap);
addDecorator(
  moduleMetadata({
    imports: [IonicModule]
  })
)

configure(loadStories, module);

**Comment by eikooc** [comment]
@smnhgn when I add the `<ion-app>` wrapper the component just renders _undefined_. If I on the other hand add the `<ion-app>` tag directly in the component it renders just fine.
The stories file looks like this:
```
storiesOf('Task', module)
  .addDecorator(
    moduleMetadata({
      declarations: [TestComponent],
    })
  )
  .add('default', () => {
    return {
      component: TestComponent,
    };
  });
```
