### ISSUE TITLE
Hiding panel on mobile devices

### ISSUE THREAD

**Issue by fibo** [storybooks/storybook#3875]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Question: I am using *viewport* addon, is it possible to disable panel on mobile? Maybe there is already some way to configure panel hiding on mobile devices, any hint?

### Steps to reproduce

See my storybook, with a mobile device. It looks ok and responsive but hiding panel would be great: 
http://g14n.info/trunx/

### Please specify which version of Storybook and optionally any affected addons that you're running

```
"@storybook/addon-options": "^3.4.7",
    "@storybook/addon-viewport": "^3.4.8",
    "@storybook/react": "4.0.0-alpha.3",
    "@storybook/storybook-deployer": "^2.3.0",
    "@types/react": "^16.4.1",
    "@types/react-dom": "^16.0.6",
```

**Comment by igor-dv** [comment]
It's possible in the latest alpha: https://storybooks-official.netlify.com

![image](https://user-images.githubusercontent.com/7867954/42639976-f04e1466-85f9-11e8-97df-f0bb621e6aa8.png)

**Comment by fibo** [comment]
@igor-dv thanks for the quick answer. I guess I will get it for free on next version.

Awesome!

The result also look really nice and it makes a lot of sense to have a compact panel on small screens.

Thank you again for storybook, it isanoce piece of software and I am using it as the base for my project documentation.
