### ISSUE TITLE
Handling of imported PropTypes with info addon

### ISSUE THREAD

**Issue by mvuajua** [storybooks/storybook#3878]
### Bug or support request summary

When importing PropTypes from another file, babel-plugin-react-docgen will [not follow the import](https://github.com/storybooks/babel-plugin-react-docgen/issues/28). Example:

Alert.js:
```
// ...
export const AlertShape = PropTypes.shape({
// ...
});
```

Alerts.js:
```
import { AlertShape } from './Alert.js';
// ...
Alerts.propTypes = {
    // ...
    alerts: PropTypes.arrayOf(AlertShape)
};
``` 

This will result in a "custom" type (within the `arrayOf` type) that looks like this:

```
{
    name: 'custom',
    raw: 'AlertShape'
}
```

The info addon will then render the name property in the PropTypes table like so: `[custom]`, which is not very informative as to what data the array is supposed to contain.

Since the variable name of the original import is contained in the `raw` property next to the currently in use `name`, I think it would make sense to check if `raw` is present (if `name` is set to `custom`), since I expect it will almost always be more informative than just printing `custom`, thus rendering a more informative `[AlertShape]`.

Could also make it this behaviour opt-in with a setting, of course.

### Steps to reproduce

See code above, or any other example that imports PropTypes from another file.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.8
- @storybook/addon-info 3.4.8

### Affected platforms 

All

I can supply a PR if this is something that you think is reasonable and would not break any behaviour I haven't thought of :)

**Comment by mlegait** [comment]
FYI, I opened a similar issue some months ago: https://github.com/storybooks/storybook/issues/3493

It seems that we can show the name of the imported type instead of `custom`. I didn't take the time to try it, sorry 😕 
Of course, having the name of the type  would be better than `custom` but for my need it won't be enough 😞

**Comment by mvuajua** [comment]
@mlegait oh I see - and I thought I had searched well enough :) Thanks for letting me know!

From reading through your issue, it definitely seems to be a (possible) problem for many people, and something out of the hands of storybook itself. 

I will try and prepare a PR for at least displaying the `raw` value for now, as it seems actually getting the import resolved might be a longer thing.. I will close this and use the other issue as reference, I don't think we need it twice :)
