### ISSUE TITLE
[addon-info] minified source code on static build

### ISSUE THREAD

**Issue by rwieruch** [storybooks/storybook#3879]
Hello there,

thanks for providing all these great add-ons for Storybook. Today I ran into an issue for the static build of Storybook with the add-on **addon-info**. All the information looks alright for the development build of Storybook. But if I do a static build for production and run the `.out` folder locally with `http-server`, the React component names are not the same anymore:

<img width="993" alt="screen shot 2018-07-12 at 16 06 28" src="https://user-images.githubusercontent.com/2479967/42638563-41cea7ee-85ee-11e8-9d0c-38017ccb6dfa.png">

As you can see, for **addon-storysource** everything is displayed fine, but not for **addon-info**. Also the PropTypes don't reflect the actual values anymore:

**Development:**

<img width="493" alt="screen shot 2018-07-12 at 16 18 20" src="https://user-images.githubusercontent.com/2479967/42638951-3945d858-85ef-11e8-8912-cae08d791ef3.png">

**Production:**

<img width="469" alt="screen shot 2018-07-12 at 16 17 14" src="https://user-images.githubusercontent.com/2479967/42638928-24609b30-85ef-11e8-93eb-6327a83cd20a.png">

As workaround I tried to exclude Uglify in my own webpack.config.js in *.storybook/webpack.config.js*, but it didn't work. This would be only a short-term solution though:

```
const path = require('path');

// Export a function. Accept the base config as the only param.
module.exports = (storybookBaseConfig, configType) => {
  storybookBaseConfig.module.rules.push(
    {
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      use: ['babel-loader'],
    },
    {
      test: /\.(woff(2)?|ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,
      use: ['file-loader'],
    },
    {
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    },
    {
      test: /stories\.(js|jsx)?$/,
      loaders: [require.resolve('@storybook/addon-storysource/loader')],
      enforce: 'pre',
    },
  );

  // doesn't work
  storybookBaseConfig.plugins = storybookBaseConfig.plugins.filter(
    p => p.constructor.name !== 'UglifyJsPlugin',
  );

  return storybookBaseConfig;
};
```

Any help for this is much appreciated 👍

**Comment by igor-dv** [comment]
Maybe you need to add the `displayName` to your component?

**Comment by rwieruch** [comment]
Yep, it works this way. If that's the official way to deal with it, the issue can be closed.
