### ISSUE TITLE
Cannot find module '../src' in '<my path>/stories'

### ISSUE THREAD

**Issue by TheImpressionist** [storybooks/storybook#3886]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Storybook alpha 4.0.0 cannot seem to resolve modules unless I add `*/index.<ext>` at the end.

### Steps to reproduce

This happens with an extended webpack config. I had to extend it in order to use typescript transpilation.

### Please specify which version of Storybook and optionally any affected addons that you're running

-@storybook/react": "^4.0.0-alpha.14

### Screenshots / Screencast / Code Snippets (Optional)

Config:

```js

const extendConfig = (baseConfig, env, config) => {
  config.module.rules.push({
    test: /\.tsx?$/,
    loaders: ['babel-loader', 'ts-loader'],
  }),

  config.resolve = {
    ...config.resolve,
    extensions: [...config.resolve.extensions, '.ts', '.tsx'],
  };

  return config;
};

module.exports = extendConfig;

```

`**/stories/index.js`

```js

import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';

import Slider from '../src';

const stories = storiesOf('Default', module);

stories.add(
  'Regular',
  () => (<Slider min={0} max={100} />),
);

```

It doesn't seem to like any import that do not have a filename at the end. It cannot resolve index files.
So I have to indicate EVERYWHERE that it has to load 'index.tsx' files, otherwise it won't work.

**Comment by igor-dv** [comment]
From the first glance everything looks fine in your setup, though I can't reproduce the problem, do you have a repo to play with?
