### ISSUE TITLE
Typo in exporting storybook instructions

### ISSUE THREAD

**Issue by wuweiweiwu** [storybooks/storybook#3888]
https://storybook.js.org/basics/exporting-storybook/

<img width="722" alt="screen shot 2018-07-17 at 12 03 12 am" src="https://user-images.githubusercontent.com/35270620/42801547-d3d44f36-8954-11e8-9ee7-ddf6cc8f25da.png">

"webpack" should be "web app"

**Comment by Rantelo** [comment]
Hi @wuweiweiwu, I have submitted a PR #3891 with the typo fixed

**Comment by wuweiweiwu** [comment]
@Rantelo Thanks for the contribution!
