### ISSUE TITLE
@storybook/react global has issues

### ISSUE THREAD

**Issue by imjeremyhi** [storybooks/storybook#3892]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

test-app/node_modules/@storybook/react/dist/client/preview/globals.js:5
`var rootEl = _global.document.getElementById('root');`
                              ^

TypeError: Cannot read property 'getElementById' of undefined

I expected it to not have any errors. Am I missing dependencies or doing something wrong?

### Steps to reproduce

package.json
```
{
    "name": "test-app",
    "dependencies": {
        "react": "^16.4.0"        
    },
    "devDependencies": {
        "@storybook/react": "4.0.0-alpha.6"
    }
}

```
test.js
`const { storiesOf } = require('@storybook/react');`

I run the file with `node test.js`

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 16.4.0

**Comment by igor-dv** [comment]
What do you mean by 

> I run the file with node test.js

That is not how you should run storybook

https://storybook.js.org/basics/guide-react/
