### ISSUE TITLE
How to use antd design with nextjs

### ISSUE THREAD

**Issue by byteties** [storybooks/storybook#3895]
I try to use storybook with nextjs 
I can use this without scss 
css from antd design not active
![image](https://user-images.githubusercontent.com/18192002/42871009-84e4ae84-8aa3-11e8-9057-ba9e8c627beb.png)

I use `webpack.config.js`

`const path = require('path')
const glob = require('glob')

module.exports = (storybookBaseConfig, configType) => {
  storybookBaseConfig.module.rules.push(
    {
      test: /\.css$/,
      use: ['babel-loader', 'raw-loader', 'postcss-loader'],
    },
    {
      test: /\.s(a|c)ss$/,
      use: ['babel-loader', 'raw-loader', 'postcss-loader',
        { loader: 'sass-loader',
          options: {
            includePaths: ['styles', 'node_modules']
              .map(d => path.join(__dirname, d))
              .map(g => glob.sync(g))
              .reduce((a, c) => a.concat(c), []),
          },
        },
      ],
    },
  );

  return storybookBaseConfig;
};
`

**Comment by igor-dv** [comment]
Did you solve the problem?
