### ISSUE TITLE
Can't instantiate ag-grid in Storybook (Angular)

### ISSUE THREAD

**Issue by nareshbhatia** [storybooks/storybook#3899]
### Bug or support request summary

I am trying to show an [ag-grid](https://www.ag-grid.com/) inside Storybook. However, I am getting errors when I try to include its metadata.

If I include the `AgGridModule` in the metadata, I get the following error:

    Unexpected module 'AgGridModule' declared by the module 'DynamicModule'. Please add a @Pipe/@Directive/@Component annotation.

If I include `AgGridNg2` (the actual component) in the metadata, then I get the following error:

    StaticInjectorError(DynamicModule)[Ng2FrameworkFactory -> BaseComponentFactory]

### Steps to reproduce

I have a minimal repo [here](https://github.com/nareshbhatia/angular-aggrid-testing-techniques). The story under question is [here](https://github.com/nareshbhatia/angular-aggrid-testing-techniques/blob/master/src/stories/index.stories.ts#L35-L40).

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 4.0.0-alpha.14

### Affected platforms 

All

### Screenshots / Screencast / Code Snippets (Optional)

```js
storiesOf('Order List', module)
    .addDecorator(
        moduleMetadata({
            declarations: [AgGridModule]
            // declarations: [AgGridNg2]
        })
    )
    .add('list with orders', () => ({
        component: OrderListComponent,
        props: {
            orders: orders
        }
    }));
```

**Comment by igor-dv** [comment]
Will be able to check this only by the end of the next week.

**Comment by jonrimmer** [comment]
@nareshbhatia Modules need to be included in `imports`, not `declarations`. E.g.

```js
  moduleMetadata({
    imports: [ AgGridModule ]
  })
```

**Comment by nareshbhatia** [comment]
Thanks so much, @jonrimmer! Works like a charm now.
