### ISSUE TITLE
[addon-viewport] Update list of Devices for current models

### ISSUE THREAD

**Issue by mikelax** [storybooks/storybook#3915]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

When using the `addon-viewport` Addon, the list of Devices is missing current models. At the very least, the new iPhones should be added: iPhone 7, iPhone 7 Plus, iPhone X. Maybe also include iPad Pro. The corresponding Android devices should also be added.

### Steps to reproduce

1. Install plugin `addon-viewport`
1. start storybook server, select a story
1. Open the Viewport panel, view the list of options in the Device dropdown

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 16.3.2
- @storybook/addon-viewport 3.4.8

### Affected platforms 

N/A

### Screenshots / Screencast / Code Snippets (Optional)

N/A

End bug report support request - delete the rest below

**Comment by Hypnosphi** [comment]
Released as (`4.0.0-alpha.15`)[https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.15]
