### ISSUE TITLE
[addon-storyshots] location of __snapshots__ folder

### ISSUE THREAD

**Issue by rwieruch** [storybooks/storybook#3917]
Currently I am using the latest alpha version of Storybook, but as I remember correctly it was the same behavior in version 3.x.

**Actual Behavior**

When I run all stories as snapshot tests with Storybook Storyshots, I get one __snapshots__ folder next to one arbitrary component with a story.

<img width="190" alt="screen shot 2018-07-24 at 14 41 28" src="https://user-images.githubusercontent.com/2479967/43138767-3ea53446-8f50-11e8-9c30-d0b8d28789fd.png">

**Expected Behavior**

I would love having a __snapshots__ folder for each component with a stories file. It shouldn't be the case that the __snapshots__ folder for all stories is located at one place, which would be fine, but not next to one arbitrary component with a story.

Maybe I am just missing a configuration or it's something on Jest's end, but I would be thankful to get any advice for this.

**Comment by igor-dv** [comment]
In the latest version, storyshots addon has this new thing:

https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-core#stories2snapsconverter

**Comment by rwieruch** [comment]
Thanks for your prompt reply @igor-dv  But as I see it, this is nothing for specifying the location of the __snapshots__ folder, is it?

**Comment by igor-dv** [comment]
You can derive from the `Stories2SnapsConverter` class and change this functionality

[Here](https://github.com/storybooks/storybook/blob/master/addons/storyshots/storyshots-core/stories/storyshot.configFunc.test.js) is an example.

**Comment by rwieruch** [comment]
Okay, this could work. Thank you!

**Comment by CrashyBang** [comment]
Hey @rwieruch,

Did you ever get this working? Trying to implement at the moment and not having a lot of luck.

Cheers,
Otis.

**Comment by rwieruch** [comment]
Nope @CrashyBang Unfortunately not. I would have expected it to be the default at some point :)

**Comment by CrashyBang** [comment]
Hey @rwieruch,

I kept playing with this and was able to get something like what you want with this:

```js
// This is my storybook.spec.js

import path from "path";
import registerRequireContextHook from "babel-plugin-require-context-hook/register";

import initStoryshots, {
  Stories2SnapsConverter,
  multiSnapshotWithOptions
} from "@storybook/addon-storyshots";

registerRequireContextHook();

initStoryshots({
  configPath: "./testing/config/storybook",

  // this creates a *.snap.js for each *.stories.js I have
  test: multiSnapshotWithOptions(),
  // this tells storybook we're to look for stories (I have all mine in one folder) but as far as I know it searches down recursively from here
  integrityOptions: {
    cwd: path.resolve(__dirname, "../../stories")
  },
  stories2snapsConverter: new Stories2SnapsConverter({
    // This puts all my *.snaps.js in a __snapshots__ folder next to my stories folder, the default is to have them next to the *.stories.js files themselves
    snapshotsDirName: "../__snapshots__",
    // This just sets the extension to *.snap.js which I like
    snapshotExtension: ".snap.js"
  })
});
```

**Comment by rwieruch** [comment]
Oh perfect! I will definitely check it out 👍

**Comment by tmeasday** [comment]
Seems reasonable to me -- I think @igor-dv is probably the one to make the call

**Comment by arty-name** [comment]
Should anyone come to this thread looking for answers, now there's [a nice built-in configuration `multiSnapshotWithOptions`](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core#multisnapshotwithoptionsoptions) for that: 
```js
initStoryShots({ test: multiSnapshotWithOptions({ renderer }) })
```
