### ISSUE TITLE
How to change previewHelp content of @storybook/react-native?

### ISSUE THREAD

**Issue by Victorien-Tardif** [storybooks/storybook#3928]
I started a storybook/react-native project and I would like to customize the content of the [previewHelp](https://github.com/storybooks/storybook/blob/master/app/react-native/src/manager/components/PreviewHelp.js) page which is displayed on the top right pane on the web browser.

How could I do that?

Thank you

**Comment by danielduan** [comment]
That is not something that is customizable at this point. We're in the process of bringing the web addon interface inside react-native and potentially deprecating the web interface. https://github.com/storybooks/storybook/pull/3903

**Comment by Victorien-Tardif** [comment]
Ah yeah that would be great! Thank you for your answer, I'll keep on eye on that PR.

**Comment by Gongreg** [comment]
@Victorien-Tardif Hey. To be exact there is undocumented way to set what preview is displaying:

```
const addons = require('@storybook/addons').default;
addons.setPreview(function setPreview() { return React.createElement('div')});
```

It is es5 code in this case, but of course you can use jsx here.
If it was called inside addons.js file it should work.

**Comment by Victorien-Tardif** [comment]
Thanks @Gongreg , indeed it works!!
