### ISSUE TITLE
font tag is removed

### ISSUE THREAD

**Issue by imjeremyhi** [storybooks/storybook#3931]
### Bug or support request summary

When run with `webpack4`, the font tag is removed in storybooks @4.0.0-alpha.6. The original behaviour in 3.4.3 was that the font tag was replaced by a span tag.

This occurred in a combined webpack and storybooks bump.

**Comment by danielduan** [comment]
Are you talking about `<font>text</font>`?

It's been deprecated for a while, you should definitely use CSS to apply font styles instead:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font
