### ISSUE TITLE
Setting a cookie during the storybook "config"

### ISSUE THREAD

**Issue by Inateno** [storybooks/storybook#3932]
Hi,

I'm using Storybook version 3.4.8 with React

I didn't found any topic about setting up a mock cookie in the config, I have some complex components that require a cookie and actually we do:

```
if ( process.env.NODE_ENV === "developement" ) {
  /* no cookie, bypass reading */
} else {
  /* read the cookie here */
}
```
Instead, I would like to be able to read the cookie "normally".

I'm not sure what can I do from "configure(loadStories, module);" in the ".storybook/config.js" file. Any help or link would be appreciated.

Thanks

EDIT: clarification

**Comment by igor-dv** [comment]
Just for clarification, did this work?

**Comment by Inateno** [comment]
My code works yes, but I would like to avoid this and find a way to set a cookie manually !

**Comment by igor-dv** [comment]
I am not sure I understand what do you mean by set it manually. If you have some kind of abstraction that wraps your cookie, let's say `myCookieDataProvider.js`, you can mock it and provide whatever you need...

**Comment by Inateno** [comment]
Mmmh, I mean.

When I do this in the .storybook/config.js file

```
  configure(loadStories, module);
```

I would like to find a way to set the cookie here to let the code be the closest as possible from production.
But I don't know what can I set in the storybook config before it launches. It's launching a node server so there is probably a way to put my hands inside the config sent to nodejs, but how?

**Comment by igor-dv** [comment]
You can probably use a custom [middleware](https://github.com/storybooks/storybook/pull/435#issuecomment-366701274). But ! It won't work for the static build. 

`config.js` is loaded before the stories, so it might be a place to set your cookie there. Also creating some kind of `addon-cookie` comes to my mind 🤔

**Comment by Inateno** [comment]
Ok, I'll dig around the middleware issue and see for an addon.
Was asking because this might exist without documentation (already seen on many "js" projects ;) ).

Thanks, closing.

**Comment by igor-dv** [comment]
Yeah. it's not so documented. Wanna PR it 😅 ?

**Comment by Inateno** [comment]
If I can spend some time why not, we have tons of stuff to do at the same time :p
