### ISSUE TITLE
[addon-info] PropTypes missing for build-storybook

### ISSUE THREAD

**Issue by rwieruch** [storybooks/storybook#3943]
In my development environment, addon-info works perfectly fine. It shows the PropTypes for each component:

<img width="786" alt="screen shot 2018-08-01 at 17 02 05" src="https://user-images.githubusercontent.com/2479967/43530098-089a0968-95ad-11e8-9d18-a8eb8d69fd3f.png">

However, once I build the Storybook for production with `build-storybook -c .storybook -o dist` and deploy it, the PropTypes are empty:

<img width="757" alt="screen shot 2018-08-01 at 17 02 13" src="https://user-images.githubusercontent.com/2479967/43530245-5e969246-95ad-11e8-96c5-6ab87059910e.png">

Anything I can do about it? That's one of my components:

```
...

const ContentButton = ({ onClick, children, className, ...props }) => (
    <BaseButton
      onClick={onClick}
      className={cs(className, 'content')}
      {...props}
    >
      {children}
    </BaseButton>
);

ContentButton.propTypes = {
  onClick: PropTypes.func.isRequired,
  children: PropTypes.string.isRequired,
  className: PropTypes.string,
};

ContentButton.displayName = 'ContentButton';

export default ContentButton;
```

 Any help is really appreciated.

**Comment by kylemh** [comment]
Do you potentially have a babel plugin or are you using a library that's stripping propTypes from a bundle in prod?

**Comment by rwieruch** [comment]
I wouldn't be aware of it.

*.babelrc*

```
{
  "presets": [
    "env",
    "react",
    "stage-2",
  ],
  "env": {
    "test": {
      "presets": [
        "env",
        "react",
        "stage-2",
      ],
      "plugins": ["require-context-hook"]
    }
  }
}
```
*webpack.config.js* in *.storybook/*

```
module.exports = (storybookBaseConfig, configType) => {
  storybookBaseConfig.module.rules.push(
    {
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      use: ['babel-loader'],
    },
    {
      test: /\.(woff(2)?|ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,
      use: ['file-loader'],
    },
    {
      test: /stories\.(js|jsx)?$/,
      loaders: [require.resolve('@storybook/addon-storysource/loader')],
      enforce: 'pre',
    },
  );

  return storybookBaseConfig;
};
```

**Comment by danielduan** [comment]
https://github.com/storybooks/storybook/issues/1661
