### ISSUE TITLE
Webpack 4.16.1 reverses chunk orders on Storybook

### ISSUE THREAD

**Issue by diagramatics** [storybooks/storybook#3945]
### Bug or support request summary

I've noticed a bug happening on the latest Storybook alpha (`v4.0.0-alpha.14`) with Webpack `v4.16.1` and up. Specifically it's https://github.com/webpack/webpack/pull/7721. This change has caused the orders of the production build of Storybook JS and CSS chunks to be injected in reverse (from `runtime` -> `vendor` -> `main file` to the other way around).

### Steps to reproduce

The CRA example can be used to reproduce this issue.

- Go to the example CRA app and run `npm run build-storybook` after doing the `npm install` prerequisite steps. Granted it seems like the current state of it is broken so I had to run `npm install moment` for the missing dependency and comment out `LifecycleLogger` stories because of an unidentified production build issue.
- Make sure you're running Webpack `^4.16.1`, so anything above is fine.
- Run the static Storybook generated app on `http-server` or anything else.
- Inspect the manager and the iframe for the preview. In both cases the injected JS and CSS would be injected in the reverse order.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.14 (and any other related packages)
- webpack 4.16.1 and up

### Affected platforms 

Only happens on production build because that's the only time chunk splitting based on vendors and runtime occurs.

### Screenshots / Screencast / Code Snippets (Optional)

![image](https://user-images.githubusercontent.com/5153378/43561508-a90bd02c-965a-11e8-948c-48c19b4e5c26.png)

![image](https://user-images.githubusercontent.com/5153378/43561526-ba9a27da-965a-11e8-92e7-92793c116ace.png)

**Comment by diagramatics** [comment]
Tried it again on the current version of master and it seems like @ndelangen fixed it with #3919. I haven't looked into how, but thanks!

**Comment by ndelangen** [comment]
Let me know if you run into any troubles following that change @diagramatics 🙇
