### ISSUE TITLE
Not found my components from src path angular-cli

### ISSUE THREAD

**Issue by YaroslavLyzlov** [storybooks/storybook#3948]
### Bug or support request summary
Not found my components from src path
I want use relative paths for comfortable:
- src/app/my-component
bad:
- import { cmp } from '../../../../../app/-my-component'
### Steps to reproduce

Base angular-cli project (i add rootDir's only) + getstorybook

### Please specify which version of Storybook and optionally any affected addons that you're running

- "@storybook/angular": "^4.0.0-alpha.14",
- "@storybook/addon-notes": "^4.0.0-alpha.14",
- "@storybook/addon-actions": "^4.0.0-alpha.14",
- "@storybook/addon-links": "^4.0.0-alpha.14",
- "@storybook/addons": "^4.0.0-alpha.14"

### Screenshots / Screencast / Code Snippets (Optional)

```js
const req = require.context('../src/stories', true, /.stories.ts$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);

```

```js
import { ButtonComponent } from 'src/app/shared-module/components/button/button.component';
```

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "rootDirs": [
      "src",
      "src/stories"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "resolveJsonModule": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

```
ERROR in ./.storybook/config.js
Module not found: Error: Can't resolve '../src/stories' in '/Users/yaroslavlyzlov/Projects/yourbet-web2.0/.storybook'
 @ ./.storybook/config.js 4:10-65
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true
```

**Comment by igor-dv** [comment]
Can you please share how your files structure looks like?

**Comment by YaroslavLyzlov** [comment]
![image](https://user-images.githubusercontent.com/2513879/43592645-737c8bba-968f-11e8-9c05-7e982892f52d.png)

**Comment by YaroslavLyzlov** [comment]
I want use path style:
src/app/shared-module/components/button.component
button component:
import { collapseX } from 'src/app/animations';
if use 
import { collapseX } from '../../../app/animations'; its PAIN :)

**Comment by igor-dv** [comment]
I think #3916 is what your are looking for

**Comment by YaroslavLyzlov** [comment]
Thanks! It's works for me :)
