### ISSUE TITLE
CLI Hangs on HTML type project

### ISSUE THREAD

**Issue by miguelramos** [storybooks/storybook#3956]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

After install latest CLI version and when generating app of --html, cli always hangs on 95%. Same thing happens if try html example application (HTML)

### Steps to reproduce

- npm i -g @storybook/cli@4.0.0-alpha.15
- getstorybook --html

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/cli@4.0.0-alpha.15

### Affected platforms 

- HTML

### Screenshots / Screencast / Code Snippets (Optional)
![image](https://user-images.githubusercontent.com/495720/43676834-5d191a7a-97f0-11e8-9763-df25c4e8e0c9.png)
 Has show in the preview command line always hang on unnamed compat plugin.

**Comment by igor-dv** [comment]
Looks the same issue as in #3953

**Comment by shilman** [comment]
Released a fix in [4.0.0-alpha.16](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.16)
