### ISSUE TITLE
Unable to use Info addon in react native

### ISSUE THREAD

**Issue by cortopy** [storybooks/storybook#3960]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

When I use addon-info in react native I'm getting this error:

> Module "./lib/nestedObjectAssign.js" was required dynamically. This is not supported by Metro builder

### Steps to reproduce

Use addon-info in react native in any suggested way:
- with `addDecorator`
- in the story itself

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react-native 3.4.10
- @storybook/addon-info 3.4.10

**Comment by cortopy** [comment]
I just saw in https://github.com/storybooks/storybook/blob/master/ADDONS_SUPPORT.md that react native is not supported

**Comment by RobinLebhar** [comment]
I made this maybe it will help you :

https://github.com/RobinLebhar/with-info-doc-expo-storybook
