### ISSUE TITLE
viewport addon seems out of date.

### ISSUE THREAD

**Issue by treyspiva** [storybooks/storybook#3971]
The viewport addon readme talks about the `withViewport` function.  However, the version deployed to NPM (https://www.npmjs.com/package/@storybook/addon-viewport) does not.  When I try to use the `withViewport`, it does not exist.  When is the version in the repository going to be deployed?

**Comment by igor-dv** [comment]
A readme you are probably looking at is for an alpha release. 
Here - https://github.com/storybooks/storybook/tree/release/3.4/addons/viewport it for the stable.

**Comment by treyspiva** [comment]
When is the release scheduled to be deployed?
