### ISSUE TITLE
Option to switch between horizontal and vertical radio addon knob

### ISSUE THREAD

**Issue by brycemhammond** [storybooks/storybook#3972]
Recently, for the v4.0.0-alpha.15 release, the radio addon knob was [implemented and added](https://github.com/storybooks/storybook/pull/3894), but there was also another addition for the knob to be [horizontal](https://github.com/storybooks/storybook/pull/3922). Is there any way to switch between the horizontal and vertical display of the knob?

**Comment by brycemhammond** [comment]
Additionally, when are the types for addons and addon actions released, or is this a separate process?

**Comment by ndelangen** [comment]
@astrotim 👋 Is this something you'd like to help with?

**Comment by astrotim** [comment]
@ndelangen yeah sure, I'll put up a PR for this and loop you in @brycemhammond

**Comment by astrotim** [comment]
I'm thinking something like this

```js
const options = {
  Kiwi: 'kiwi',
  Guava: 'guava',
  Watermelon: 'watermelon',
};

const displayHorizontal = true; // default is false

const = radios(name, options, defaultValue, displayHorizontal);
```

Alternatively, the default could be determined by the location of the dock (bottom or side) as per @Primigenus suggestion.

**Comment by igor-dv** [comment]
Can't it be hidden inside the `options` param?

**Comment by astrotim** [comment]
@ndelangen that's a much more involved piece of work than this issue was apparently requesting, but I agree that it would be best to have an `options` knob that combines the similar knobs.

I'll give it a go.

**Comment by ndelangen** [comment]
@astrotim yes it's bigger, but there's no need to implement all display-types in 1 PR.

We want to keep the API-surface sane amids the requests of features 🎈

**Comment by ndelangen** [comment]
Need any help @astrotim ?

**Comment by ndelangen** [comment]
Are they nice kids?

**Comment by astrotim** [comment]
I still have my hand up for this one 🤚 

I hope to get something into PR soon...

**Comment by astrotim** [comment]
Created a request for comments here: https://github.com/storybooks/storybook/pull/4317
