### ISSUE TITLE
How to run storyshots without create react app

### ISSUE THREAD

**Issue by summanerd** [storybooks/storybook#3978]
I created a storyshots.test.js file, but I have no idea how to execute it. I feel like I'm missing something obvious. It fails when running node storyshots.test.js. When I run jest, storyshots says "testStorySnapshots is intended only to be used inside jest". 

Storybook runs fine, I had the impression that storyshots was a simple addon, I'm guessing without create-react-app it becomes a whole separate project to setup. All examples say run `npm test` based on the screenshots they're running a create-react-app script.  

### Steps to reproduce

storyshots.test.js
```
var path = require('path');
var React = require('react');
var initStoryshots= require('@storybook/addon-storyshots');
var renderer = require('enzyme').mount;
var serializer = require('enzyme-to-json');
var multiSnapshotWithOptions = initStoryshots.multiSnapshotWithOptions;

// HTML Snapshots
initStoryshots({
    framework: 'react',
    configPath: path.join(__dirname, '../'),
    // integrityOptions: { cwd: path.join(__dirname, '..', 'stories') },
    // test: multiSnapshotWithOptions({
        renderer: renderer,
        serializer: serializer,
    // }),
});
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.8
- @storybook/addon-storyshots 3.4.8

**Comment by igor-dv** [comment]
This error means that you somehow run the test outside of the testing framework, it should not be executed with `node storyshots.test.js`.

Did you configure jest in your project?

**Comment by summanerd** [comment]
Apologies if my post is unclear, but I only get that error when I run it with jest. Yes jest is setup on my system. 

I’m unclear on how this works and the documentation is not clear. My stories require we pack to run, how can snapshots be created from stories without running we pack. I’m not seeing how this all comes together.

**Comment by igor-dv** [comment]
When running this test from jest, webpack is not used. Jest has its own module resolution mechanism. If you are using some kind of "special" features from webpack, you will probably need to polyfill them with babel. 

Can you please share jest.config / package.json / config.js

**Comment by summanerd** [comment]
Unfortunately with the project I'm working I am unable to post any code samples. I was just hoping to understand what I was missing from a high-level. I essentially need to do manual configuration to get jest working with storybook stories. Storyshots help bridge the gap, but I still need to do the jest setup. I was hoping it'd be as simple as the documentation due to time constraints. 

Thanks.
