### ISSUE TITLE
addDecorator is breaking @storybook/html stories

### ISSUE THREAD

**Issue by neginbasiri** [storybooks/storybook#3985]
### addDecorator is breaking for @storybook/html

My config.js

```js
    import { configure, addDecorator } from '@storybook/html';
    import { withInfo  } from '@storybook/addon-info';

    addDecorator(withInfo({
      header: false, // Toggles display of header with component name and description
      inline: true, // Displays info inline vs click button to view
      source: true // Displays the source of story Component
    }));
    // automatically import all files ending in *.js
    const req = require.context('../src/stories/partials', true, /\.js$/);

    function loadStories() {
      req.keys().forEach((filename) => req(filename))
    }

    configure(loadStories, module);
```

My story js

```js
    import { storiesOf } from '@storybook/html';
    import header from '../../templates/partials/header.html';

    storiesOf('Header', module).add('Header', () => header);

```

The error I'm getting

`Expecting an HTML snippet or DOM node from the story: "Header" of "Header".
            Did you forget to return the HTML snippet from the story?
Use "() => <your snippet or node>" or when defining the story.`

### I am using 

- @storybook/html 4.0.0-alpha.16
- @storybook/addon-info 4.0.0-alpha.16

**Comment by tmeasday** [comment]
Hi @neginbasiri - the info addon does not currently work with the HTML framework -- see the table here: https://github.com/storybooks/storybook/blob/master/ADDONS_SUPPORT.md

I wonder what you are thinking it would output for a HTML "component"? In the future we are moving away from this addon to a full-blown docs mode for stories, but I'm not sure we'll be able to do much for HTML.

**Comment by neginbasiri** [comment]
@tmeasday, oh, that's a shame! 
I have some components rendering server-side. I would like to display the html code for components so the sitecore / epi server developers just grab the code showing in Info section of component story.
It would be supper handy to have this feature for html  as well as scripts associated to those components.

**Comment by tmeasday** [comment]
Do they need the code for the component or for the story? If it's the second, perhaps the [Storysource](https://github.com/storybooks/storybook/tree/master/addons/storysource) addon would help?

**Comment by neginbasiri** [comment]
They need code for component. Basically the html source code. 
Storybook html source can be massively helpful to show the variations of those components.
lets say they have to do a credit check server-side and if it pass show the component variation A (lets say green background) otherwise show the component variation A (Red background with extra warning text)

**Comment by tmeasday** [comment]
I suspect storysource might be very helpful for your needs!

**Comment by neginbasiri** [comment]
@tmeasday  Actually, you re right! storysource would work too! Thanks

**Comment by neginbasiri** [comment]
Actually because we are importing html templates storysource dosen't show the code

![image](https://user-images.githubusercontent.com/806463/43874476-68e00354-9bcf-11e8-9f00-568e57bbd8b4.png)

**Comment by tmeasday** [comment]
How do those two stories render differently? sorry if I don't really understand how this works very well.

**Comment by neginbasiri** [comment]
At the moment these two are the same... The plan is to use ejs or handlebars so depending on the config data passed to templates it shows red or green... that's my next challenge to get loaders to generate html and feed those generated html to storybook!

**Comment by caiotriana** [comment]
We're having problems with same case here! We're trying to apply some code snippets in a story, because of a legacy system specific case, using pure HTML in its components.

We want to use something like this:

```
...
    import someHTMLElement from './pureHTMLs/some-html-file.html';

    storiesOf('someHTMLElement', someHTMLElement, {
        codeSnippet : someHTMLElement // html string 
    })
```
