### ISSUE TITLE
Proptypes component autodetection broken

### ISSUE THREAD

**Issue by martinmacko47** [storybooks/storybook#3989]
Regression in v4.0.0-alpha.16. If `propTables` option is omited, `addon-info` used to render proptypes tables for all used components. It does not render anything in v4.0.0-alpha.16  any more. It does not render proptypes tables at all.

It is caused by a search&replace typo in 935cefd2. See my comment where exactly: https://github.com/storybooks/storybook/commit/935cefd27a720548fb3fabcff9824dd8703d7b1b#r30022947

I can create a PR fixing it.

**Comment by Hypnosphi** [comment]
Released as [4.0.0-alpha.18](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.18)
