### ISSUE TITLE
node-logger v3.4.10 won't install as @storybook/react dependency

### ISSUE THREAD

**Issue by johnevanofski** [storybooks/storybook#3990]
### Bug or support request summary

When trying to install a react library with storybook on an existing project I'm getting an error in the console saying no matching version is found for `@storybook/node-logger@3.4.10`. I've verified with multiple users.

![marketingcontent_ _-bash_ _95x39](https://user-images.githubusercontent.com/3067506/43914813-b8f437aa-9bbd-11e8-9e40-0f6984ee7a77.jpg)

Node Version: 8.11

### Steps to reproduce

- Make a new folder
- Run `npm i @storybook/react`
- See error output

![test-logger_ _-bash_ _121x43](https://user-images.githubusercontent.com/3067506/43914922-0f079e34-9bbe-11e8-9eff-44992b05f8d4.jpg)

- Run `npm view @storybook/node-logger` ~ shows `3.4.8`

![test-logger_ _-bash_ _121x51](https://user-images.githubusercontent.com/3067506/43914981-396e92ae-9bbe-11e8-93df-504c5994a284.jpg)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react latest
- @storybook/node-logger@3.4.10

### Affected platforms 

all

**Comment by tomlagier** [comment]
Having this same issue - @johnevanofski have you been able to downgrade to a version that works? I'll need to remove storybook entirely if this doesn't get fixed soon.

**Comment by johnevanofski** [comment]
@tomlagier right now I am able to downgrade versions . 

```
# works, -> installs @storybook/node-logger@3.4.8 
npm install @storybook/node-logger
```

```
# does not work -> error about node-logger 3.4.10
npm install @storybook/react
```

**Comment by tomlagier** [comment]
this is my output for `yarn add @storybook/node-logger`
```
yarn add @storybook/node-logger                                                                                                                                                           
yarn add v1.9.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "backbone@1.1.2" is incompatible with requested version "backbone@~1.0.0"
error An unexpected error occurred: "https://registry.yarnpkg.com/@storybook%2fnode-logger: User not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/tlagier/Projects/web-client/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by rkdavidson** [comment]
Same issue.

Output of `npm view @storybook/node-logger` shows no `3.4.10` version, but the module's [npm page shows 3.4.10 is the latest version](https://www.npmjs.com/package/@storybook/node-logger)

Is this a `node-logger` package/publishing issue?

```› npm view @storybook/node-logger

{ name: '@storybook/node-logger',
  description: '[![Build Status on CircleCI](https://circleci.com/gh/storybooks/storybook.svg?style=shield)](https://circleci.com/gh/storybooks/storybook) [![CodeFactor](https://www.codefactor.io/repository/github/storybooks/storybook/badge)](https://www.codefactor.io/re',
  'dist-tags': { rc: '3.4.0-rc.4', alpha: '4.0.0-alpha.14', latest: '3.4.8' },
  versions:
   [ '3.3.0-alpha.5',
     '3.3.0-alpha.6',
     '3.3.0-rc.0',
     '3.3.0-rc.1',
     '3.3.0',
     '3.3.1',
     '3.3.2',
     '3.3.3',
     '3.3.4',
     '3.3.5',
     '3.3.6',
     '3.3.7',
     '3.3.8',
     '3.3.9',
     '3.3.10',
     '3.3.11',
     '3.3.12',
     '3.3.13',
     '3.3.14',
     '3.3.15',
     '3.4.0-alpha.0',
     '3.4.0-alpha.1',
     '3.4.0-alpha.2',
     '3.4.0-alpha.3',
     '3.4.0-alpha.4',
     '3.4.0-alpha.5',
     '3.4.0-alpha.6',
     '3.4.0-alpha.7',
     '3.4.0-alpha.8',
     '3.4.0-alpha.9',
     '3.4.0-rc.0',
     '3.4.0-rc.1',
     '3.4.0-rc.2',
     '3.4.0-rc.3',
     '3.4.0-rc.4',
     '3.4.0',
     '3.4.1',
     '3.4.2',
     '3.4.3',
     '3.4.4',
     '3.4.5',
     '3.4.6',
     '3.4.7',
     '3.4.8',
     '4.0.0-alpha.0',
     '4.0.0-alpha.1',
     '4.0.0-alpha.2',
     '4.0.0-alpha.3',
     '4.0.0-alpha.4',
     '4.0.0-alpha.6',
     '4.0.0-alpha.7',
     '4.0.0-alpha.8',
     '4.0.0-alpha.9',
     '4.0.0-alpha.10',
     '4.0.0-alpha.11',
     '4.0.0-alpha.12',
     '4.0.0-alpha.13',
     '4.0.0-alpha.14' ],
  users: {},
  readmeFilename: '',
  license: 'MIT',
  version: '3.4.8',
  main: 'dist/index.js',
  dist:
   { tarball: 'https://artifactory.nike.com/artifactory/api/npm/npm-nike/@storybook/node-logger/-/node-logger-3.4.8.tgz',
     shasum: '8f8abcd51920545c7458385b0b30199ae48ad78a' },
  dependencies: { npmlog: '^4.1.2' },
  directories: {},
  scripts: { prepare: 'node ../../scripts/prepare.js' },
  'jsnext:main': 'src/index.js' }```

**Comment by emckay** [comment]
I had this issue when fetching the packages through artifactory, but not when going directly against the npm registry. There is a workaround available here: https://jfrog.com/knowledge-base/why-am-i-getting-404-for-some-npm-packages/

**Comment by tomlagier** [comment]
We do use artifactory, but we're only using it as a local repo for some private packages (the above fix is for use as a remote proxy). I can confirm that the issue is with the `_auth` config set, but I'm at a loss as to how that's mangling the installation of scoped packages on the public repo. I've tried across a range of `yarn` versions, with a number of config setups and have had no luck at all.

**Comment by johnevanofski** [comment]
Thanks @emckay . We are using artifactory as well, so this is probably the issue.

**Comment by akae** [comment]
The fix works when using Artifactory as cache for the remote repo npmjs
"Bypass HEAD Requests" did the trick
Thanks @emckay

**Comment by dontry** [comment]
Same issue here.  "@storybook/node-logger@3.4.10"  seems to be unavailable in "npm" registry. Anyone knows how to fix it? 
```sh
error Couldn't find package "@storybook/node-logger@3.4.10" required by "@storybook/core@3.4.10" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@storybook/node-logger@3.4.10" required by "@storybook/react@^3.4.10" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:38986:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:92:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:105:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "@storybook/react-stubber@^1.0.0" required by "@storybook/react-komposer@^2.0.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at PackageRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:38986:17)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:92:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:105:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by acao** [comment]
does this need to be re-opened?

**Comment by rupurt** [comment]
I'm running into a similar problem but it's for `@storybook/react`

```
# package.json
{
   ...
   "devDependencies": {
      "@storybook/react": "^4.0.9"
   }
   ...
}

$ yarn
yarn install v1.12.3
[1/4] 🔍  Resolving packages...
error Couldn't find package "@storybook/react" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by igor-dv** [comment]
@rupurt do you have any corporate registry in your workplace?

**Comment by rupurt** [comment]
@igor-dv I think npm invalidated auth tokens which somehow affected downloading packages. I deleted my `~/.npmrc` and it now works.
