### ISSUE TITLE
Referencing a storybook configuration from a node_modules package

### ISSUE THREAD

**Issue by coreysnyder** [storybooks/storybook#3991]
If you are reporting a bug or requesting support, start here:
### support request summary

I'd like to be able to reference a common `.storybook` configuration directory from a module in `node_modules`. I'm running into issues and I'm guessing it's mostly related to the paths no longer referencing storybook directory appropriately. 

### Steps to reproduce
Copy your storybook configuration into a shared library that is included in other apps via NPM. Now in your parent app, make your `npm run storybook` reference that configuration. 
`"storybook": "start-storybook -p 9001 -c ./node_modules/MySharedPackage/.storybook"`

```
// /node_modules/MySharedPackage/.storybook/config.js`
import { configure } from '@storybook/react';

const req = require.context('../app/stories', true, /\.stories\.js$/)

function loadStories() {
  req.keys().forEach((filename) => req(filename))
}

configure(loadStories, module);
```

The stories would be at `./app/stories/` relative to the package.json file where the command was initiated from. 

When I run this I get all kinda of issues. 

I understand this is more a question specific to what I'm trying to do and likely not any issue w/ Storybook but I'd appreciate any help that can be provided. 

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.4.4

**Comment by mpeyper** [comment]
I am also running into this issue trying to build a shared, reusable configuration for multiple projects using storybook.

It also appears as though the config is resolved in the browser (after webpacking), making it difficult to use [a helper](https://github.com/kentcdodds/kcd-scripts/blob/master/src/utils.js#L48) to resolve the true location of the stories.

**Comment by mpeyper** [comment]
I've tried going down the route of using a custom webpack config and using a [babel plugin](https://github.com/FormidableLabs/babel-plugin-transform-define) to override a variable with a the string before webpacking, but it is not working.  

webpack.config.js
```js
const { fromRoot } = require('./utils')

module.exports = (baseConfig, env, defaultConfig) => {
  defaultConfig.module.rules[0].use[0].options.plugins = [ // safe?
    ...defaultConfig.module.rules[0].use[0].options.plugins,
    [require.resolve('babel-plugin-transform-define'), { STORIES: fromRoot('stories') }],
  ]

  return defaultConfig;
}
```

config.js
```js
import { configure } from '@storybook/react'

const req = require.context(STORIES, true, /\.stories\.js$/)

function loadStories() {
  req.keys().forEach((filename) => req(filename))
}

configure(loadStories, module);
```

When I inspect the the script in the browser, `SCRIPTS` has not been replaced.  Does `config.js` get processed in any way before being served?

**Comment by ndelangen** [comment]
@coreysnyder @mpeyper I'd like to hear more about this use-case.

Also it seems @gabrielcsapo needs this as well 👍 

Please know that this one is coming:
https://github.com/storybooks/storybook/issues/4169

Happy to discuss this some time, so we can work together on a solution that works for all.

**Comment by mpeyper** [comment]
Thanks @ndelangen for taking an interest.

In my case, you can think of it a little bit like `create-react-app` but for component libraries, i.e. `npm start` will start storybook, with a very opinionated set of babel, webpack and storybook configurations, that hopefully the user of the package is more or less unaware of.

The main advantages of doing this is:

1. less setup and configuration in each repo
2. easy upgrades of tools
3. less bikeshedding on tools

So an example folder structure might look something like:

- node_modules
  - common-dev-tools
    - babel
      - babel.config.js
    - bin
      - build.js
      - start.js
      - test.js
    - storybook
      - webpack.config.js
      - config.js
    - webpack
      -webpack.config.js
- stories
  - Component1.stories.js
  - Component2.stories.js
- src
  - Component1.js
  - Component2.js
  - index.js

The idea is the `node_modules/common-dev-tools/bin/start.js` will run storybook with the correct arguments to pick up the `common-dev-tools/storybook` configurations, i.e. `start-storybook node_modules/common-dev-tools/storybook`.

This all works fine, but there does not appear to be a reliable way to resolve the `stories` directory from the `common-dev-tools/storybook` package's `config.js` file as there is no guarantee that `npm` will install it in the root `node_modules` directory.

The `start.js` script can resolve it and inject it, but as my attempts above show, it does not appear to work with the current process for handling `config.js` (as far as I can tell).  I have not been able to find a work around for this as of yet, and consequently, `storybook` has not been included in my common-dev-tools package (internal package for my workplace), and we still have bespoke configurations and setups in the repos that use storybook.

I have taken a look at #4169 and I believe the `entries` proposal will allow this type of setup to be possible, so I'm very much looking forward to that.

**Comment by ndelangen** [comment]
Excellent explanation of the requested feature @mpeyper.

Besides the `entries` field there will also be a `presets` field, which will be immensely useful for the setup you described.

@igor-dv validates your ideas

**Comment by mpeyper** [comment]
If I understand the presets proposal, someone could use my packages config and extend it with some custom configuration unique to their project, right?

This is similar to how our babel and jest configurations are treated in the package (i.e. if  you don't care you don't have a config file and you get the opinionated defaults, but if you haves something unusual you need you create your own custom config file and reference the default config as a preset so that you don't have to set everything up as well).

Is there any ETA on when v5 might be ready?  Is there any possibility of enabling this in the current version?

**Comment by mpeyper** [comment]
Also, as I have an interest in seeing this come about, I'm happy to help in anyway I can, e.g. reviewing changes, contributing to discussions or even making changes (although I may have to start on some easy issues to get used to the codebase).

**Comment by ndelangen** [comment]
The config file is yet to be realised, but presets already work.

But they are a undocumented feature. we first will be using them internally, refining the apis maybe.

Then we'll create the single-file config, which will open up presets to users.

We expect to be maintaining most preset ourselves, like how babel core team in maintaining babel presets, but it will be available for individuals and companies to create their specialized storybook presets.

Single-File-Config is going to be a huge game-changer fos storybook.

We also want to make sure we take our time to make sure the transition is smooth for users.

**Comment by tmeasday** [comment]
@igor-dv / @ndelangen  I think our latest thinking here is that the `presets.js` file *will* be officially supported in v5, with the single-file-config coming somewhere further down the road. Hopefully we can put together some documentation about this soon. `presets.js` is already unofficially supported in v4, correct?

**Comment by ndelangen** [comment]
Correct it's supported in V4 already

**Comment by tmeasday** [comment]
OK, so let's maybe close this one and open a ticket to document it.

**Comment by tmeasday** [comment]
=> https://github.com/storybooks/storybook/issues/5301
