### ISSUE TITLE
Is it possible to disable the use of universal-dotenv?

### ISSUE THREAD

**Issue by zgreen** [storybooks/storybook#3997]
### Bug or support request summary

When starting storybook, environment variables are loaded using [universal-dotenv](https://github.com/sebastian-software/universal-dotenv). I don't _think_ this is documented. It's a good feature, but loading environment variables this way might not be desirable (or expected) in all cases. I expected storybook to start without loading any environment variables from `.env`, as I didn't instruct it to do so.

### Steps to reproduce

1. Create a `.env` file, with the contents `EXAMPLE_VAR=foo`
2. In `.storybook/config.js`, add `console.log(process.env.EXAMPLE_VAR)`.
3. Observe the environment variable logs to the console in the client.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react v3.4.10

Happy to submit a PR to address this, if it's something you all want to fix. Thank you for storybook, and for all your hard work!

**Comment by igor-dv** [comment]
We are using [`dotenv-webpack`](https://github.com/mrsteele/dotenv-webpack) plugin in the latest alpha. It can be removed by using the extended `.storybook/webpack.config.js`. I am not sure that extra configuration for this is necessary.
