### ISSUE TITLE
stories.addParameters is not a function

### ISSUE THREAD

**Issue by Ridermansb** [storybooks/storybook#3998]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Expect: Display jest tests
Happens: `TypeError: stories.addParameters is not a function`

### Steps to reproduce

1. On your `.config.js`

```
import { addDecorator } from "@storybook/react";
import { withTests } from "@storybook/addon-jest";
addDecorator(
	withTests({
		results,
		filesExt: "\\.test\\.jsx?$"
	})
);
```

2. On `TestForm.jsx`

```
const stories = storiesOf("<TestForm>", module);
stories.addParameters({ jest: ["TestForm"] })
```

3. on your `TestForm.test.jsx`

```
import React from "react";
import { render } from "enzyme";
import TestForm from "./TestForm";

describe("<TestForm /> component", () => {
	it("should render correctly", () => {
		const wrapper = render(<TestForm />);
		expect(wrapper).toMatchSnapshot();
	});
});
```

### Please specify which version of Storybook and optionally any affected addons that you're running

 - "@storybook/addon-actions": "^3.4.10",
 - "@storybook/addon-info": "^3.4.10",
 - "@storybook/addon-jest": "^3.4.10",
 - "@storybook/react": "^3.4.10",

### Screenshots / Screencast / Code Snippets (Optional)

<img width="891" alt="screen shot 2018-08-10 at 16 00 02" src="https://user-images.githubusercontent.com/725337/43976273-78be4cd0-9cb6-11e8-8508-74ad2c979a10.png">

```js
index.js:16 TypeError: stories.addParameters is not a function
    at Object.<anonymous> (VM23645 preview.bundle.js:123800)
    at Object.defineProperty.value (VM23645 preview.bundle.js:123836)
    at __webpack_require__ (VM23645 preview.bundle.js:708)
    at fn (VM23645 preview.bundle.js:113)
    at webpackContext (VM23645 preview.bundle.js:109647)
    at VM23645 preview.bundle.js:87064
    at Array.forEach (<anonymous>)
    at loadStories (VM23645 preview.bundle.js:87063)
    at ConfigApi._renderMain (VM23645 preview.bundle.js:88070)
    at render (VM23645 preview.bundle.js:88028)
```
End bug report support request - delete the rest below

**Comment by igor-dv** [comment]
The README you are seeing at **master** is for the **v4** alpha release. For the **v3.4** you need to change the branch to **release/3.4** - https://github.com/storybooks/storybook/tree/release/3.4

**Comment by Ridermansb** [comment]
Ok, thanks
