### ISSUE TITLE
moment and emotion requirement undocumented for addon-knobs

### ISSUE THREAD

**Issue by eps1lon** [storybooks/storybook#3999]
Adding `addon-knobs` requires `moment` and `emotion` installed which is not documented. It does produce a warning in yarn however which might be sufficient. Just filing this issue to be sure.

### Steps to reproduce
- list dependencies as described below
- `yarn`
    ```bash
   warning "@storybook/addon-knobs > react-emotion@9.2.6" has unmet peer dependency "emotion@^9.1.3".
    warning "@storybook/addon-knobs > react-datetime@2.15.0" has unmet peer dependency "moment@>=2.16.0".
   ``` 
- `yarn start storybook`
   ```bash
   ERROR in ./node_modules/react-datetime/DateTime.js
   Module not found: Error: Can't resolve 'moment' in '/home/eps1lon/Development/src/js/react-blend-circles/node_modules/react-datetime'
    @ ./node_modules/react-datetime/DateTime.js 6:10-27
    @ ./node_modules/@storybook/addon-knobs/dist/components/types/Date/index.js
    @ ./node_modules/@storybook/addon-knobs/dist/components/types/index.js
    @ ./node_modules/@storybook/addon-knobs/dist/components/Panel.js
    @ ./node_modules/@storybook/addon-knobs/dist/register.js
    @ ./node_modules/@storybook/addon-knobs/register.js
    @ ./.storybook/addons.js
    @ multi ./.storybook/addons.js ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js
   ```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.16
- @storybook/addon-knobs 4.0.0-alpha.16

Possible solutions:
- list `moment` and `emotion` as a peer to ´addon-knobs`
- list `moment` and `emotion` as optional to `addon-knobs` and allow tree shakeable import so that import e.g. `number` does not pull in `date`
- list `moment` and `emotion` as direct dependency

**Comment by igor-dv** [comment]
@ndelangen, is this somehow missed from the latest theme/deps changes?

**Comment by wuweiweiwu** [comment]
Can verify that this is an issue. I think moment should be a direct dep since its required by `react-datetime`

**Comment by eps1lon** [comment]
Thinking about this I'm pretty sure `moment` as a direct dependency is bad. As soon as the package that uses `addon-knobs` uses a conflicting `moment` version the localization configuration is lost.

I don't know what `emotion` is supposed to do so no feedback there.

I think listing both as a peer for now is a good workaround so that users are sure that they can't ignore that warning. In the long term it would be nice to be able to explicitly import only certain components e.g. `import number from '@storybook/addon-knobs/number'` or another tree shakeable solution

**Comment by ndelangen** [comment]
I'll check it out

**Comment by ndelangen** [comment]
I changed the knob for dates to use a more browser native version of date picker component.
It does not need moment

**Comment by eps1lon** [comment]
@ndelangen Could you link the change you made to address the issue? Github did not pick up any PR or commit references.

**Comment by ndelangen** [comment]
Sure:
https://github.com/storybooks/storybook/pull/4380
---
will be in 4.0.0

**Comment by eps1lon** [comment]
@ndelangen This looks like `emotion` was untouched? I'm not arguing against that but most libraries I know are pretty liberal with transitive peerDependencies. 

It is implied now that users actually have to resolve peerDependencies of their direct dependencies.

**Comment by ndelangen** [comment]
@eps1lon you are right, that's actually not what I intended.

We should add emotion to addon-knobs, would you be willing to open a PR @eps1lon ?

I think all it would take is to add emotion to the package.json?
