### ISSUE TITLE
how to use @import in scss files inside vue -> <style lang="scss">?

### ISSUE THREAD

**Issue by chovy** [storybooks/storybook#4001]
@import '~@/styles/defaults.scss';

This fails when I run `npm run storybook`

**Comment by igor-dv** [comment]
@chovy did you solve the problem?

**Comment by chovy** [comment]
No, I did not solve the problem.

**Comment by igor-dv** [comment]
Adding a custom webpack config as @nickdandakis did should solve this. 
Maybe @pksunkara has something else to add.

**Comment by pksunkara** [comment]
Yeah, what @nickdandakis did should work. I don't see any other issue with this.

**Comment by igor-dv** [comment]
👍

**Comment by wuweijia** [comment]
same problem

**Comment by wuweijia** [comment]
@chovy did you solve the problem?

**Comment by jrtitus** [comment]
@wuweijia I recently ran into this same problem. @nickdandakis's solution above worked for me. Just make sure you remember to `yarn add --dev vue-style-loader css-loader sass-loader`.

**Comment by igor-dv** [comment]
Would be great if you could PR to docs your findings

**Comment by wuweijia** [comment]
> @wuweijia I recently ran into this same problem. @nickdandakis's solution above worked for me. Just make sure you remember to `yarn add --dev vue-style-loader css-loader sass-loader`.
> 
> It's probably worth noting that [Storybook's documentation about extend mode](https://storybook.js.org/configurations/custom-webpack-config/?_sm_au_=iNVM4TVS1f4M4LQ6#extend-mode) did not work.

I have fixed this problem. Thank you
