### ISSUE TITLE
Why is `addon-actions.action()` wrapping what I give to it in an object?

### ISSUE THREAD

**Issue by Asday** [storybooks/storybook#4005]
### Bug or support request summary

To actually see what's going on with my actions, I need to click open a pair of expandos.  I don't know why my data is being wrapped in an object.  It's not useful to me, and is in fact obstructive.

### Steps to reproduce

1. Add a button to a story;
1. Set that button's `onClick` to fire an `action` populated with an object.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.10
- @storybook/addon-actions

### Affected platforms 

Linux Mint 18, Chromium and Firefox.

### Screenshots / Screencast / Code Snippets (Optional)

```es6
import { action } from '@storybook/addon-actions'

storiesOf('Button', module)
  .add('button', () => (
    <button
      onClick={() => action()({ type: 'button', payload: { id: 'button' }})}
    >
      Button
    </button>
  ))
```

Video of the issue:  https://www.youtube.com/watch?v=J0y2_f-_o_k

**Comment by igor-dv** [comment]
[Here](https://storybooks-official.netlify.com/?selectedKind=Addons%7CActions&selectedStory=All%20types&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example of what `addon-actions` can do

Anyway, I don't understand what are you asking here in this issue. If you have any better suggestion for the actions behavior you are welcome to PR

**Comment by Asday** [comment]
I am passing `{ 'type': 'button', 'payload': ... }`.  Storybook is wrapping that in an object, such that what I get back in the interface is `{ 0: { 'type': 'button', 'payload': ... } }`.

Why is there that wrapping object?  It is obstructive.

**Comment by igor-dv** [comment]
Try something like this:

```js
 <button
      onClick={action(JSON.stringify( { type: 'button', payload: { id: 'button' }} ))}
    >
```
