### ISSUE TITLE
Params based API for storyshots

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#4010]
As discussed on [this thread](https://github.com/storybooks/storybook/pull/3967#issuecomment-411616023), it'd be nice to be able to skip stories in storyshots with a param like:

```js
.add('error', () => null, { storyshots: { disable: true } })
```

In addition @igor-dv mentioned some other API nice-to-haves -- let's get it figured out!

## Complexities

At the moment, storyshots calls `clientApi.getStorybook()`, which returns an array of arrays of `{ name, story }` -- where `story` is a function that has context bound, including `parameters`. If storyshots wants access to the parameters, we'll need to either have it request the parameters directly of the `kind/name` combination, or else change `getStorybook` to include the parameters in the array.

Not sure either is a big deal to do.

**Comment by tmeasday** [comment]
What is the current API for disabling a single story though?

**Comment by igor-dv** [comment]
There are `storyNameRegex` and `storyKindRegex`, and they are not so good, because you need to define regex to "negate the inclusion" 🤕

**Comment by igor-dv** [comment]
Agreed. What do you think about having something like this:

```js
.add('error', () => null, { storyshots: false })
```
To disable storyshots at all for this story. And if we will need to introduce some more functionality we will able to extend this to some props object

**Comment by tmeasday** [comment]
Heh, we discussed this api for disabling an addon a while back but it was decided `{disable: true}` was more explicit and less likely to run into problems with falsiness. 

Although I prefer that too, I think we should be consistent with all the other params-based APIs.

**Comment by igor-dv** [comment]
Ok, probably missed this 😅

**Comment by ndelangen** [comment]
@tmeasday I think this is done right?

Or does this block 4.0.0 release?

**Comment by igor-dv** [comment]
It is not. And it is not blocking.

**Comment by tmeasday** [comment]
This got done somewhere along the line and is in v5
