### ISSUE TITLE
Wrong docs for setup react-native storybook with typescript

### ISSUE THREAD

**Issue by pavel1992** [storybooks/storybook#4015]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

In docs you see 

"Now update your storybook package.json script to the following

"scripts": {
   "storybook": "storybook --metro-config $PWD/rn-cli.config.js"
}
"
but for correct work you should use 

"storybook": "storybook start --metro-config $PWD/rn-cli.config.js -p 7007" 

or u get error.
### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

1) Try to run rn-storybook with script from docs ("storybook": "storybook --metro-config $PWD/rn-cli.config.js").
2) Get an error with unknown param --metro-config

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react-native 4.0.0-alpha.2

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```
End bug report support request - delete the rest below

If you are creating a issue to track work to be completed, start here:
### Work summary

_Please provide a description of the work to be completed here - Include some context as to why something needs to be done and link any related tickets._ 

### Where to start

_Please list the file(s) a contributor needs to figure out where to start work and include any docs or tutorials that may be applicable._

### Acceptance criteria

_Please include a checklist of the requirements necessary to close this ticket. The work should be narrowly scoped and limited to a few hours worth by an experienced developer at the most._

### Who to contact

_Add yourself and/or people who are familiar with the code changes and requirements. These people should be able to review the completed code._
End work issue - please tag this issue with the correct status and type labels

**Comment by igor-dv** [comment]
Would you like to PR this?

**Comment by bastienfp** [comment]
This issue should be closed.
@pavel1992 fixed it already => #4110

**Comment by pavel1992** [comment]
Forgot to do it after merge.
