### ISSUE TITLE
PropTypes not being recognized/parsed from component. 

### ISSUE THREAD

**Issue by brunoreis** [storybooks/storybook#4016]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I added a story using addon-info, but PropTypes are not showing. 

### Steps to reproduce

The code has some specific implementation with HOCs, but the propTypes declaration and defaultProps are pretty straightforward. 

BTW, the propTypes are being recognized in other components of the same project. 

```
import R from 'ramda';
import {
  withState,
  withHandlers,
  lifecycle,
} from 'recompose';
import PropTypes from 'prop-types';

import TabsRenderer from './TabsRenderer.jsx';

const Tabs = R.compose(
  withState('actualTab', 'setActualTab', p => p.defaultTab),
  lifecycle({
    componentDidMount() {
      this.props.onActualTabChange(this.props.actualTab);
    },
  }),
  withHandlers({
    setActualTab: p => (v) => {
      p.onActualTabChange(v);
      p.setActualTab(v);
    },
  }),
)(TabsRenderer);

Tabs.displayName = 'Tabs';

Tabs.defaultProps = {
  keyExtractor: tab => tab.id
};

Tabs.propTypes = {
  tabs: PropTypes.array.isRequired,
  keyExtractor: PropTypes.func.isRequired,
  renderItem: PropTypes.func.isRequired,
  defaultTab: PropTypes.any.isRequired,
};


export default Tabs;
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.16
- @storybook/addon-info 4.0.0-alpha.16

**Comment by fredcido** [comment]
+1
