### ISSUE TITLE
Please support Fusionjs integration for React components

### ISSUE THREAD

**Issue by jimbojetlag** [storybooks/storybook#4017]
It looks like the current support for React elements is limited to CRA projects.

Would it be possible to add support for the new CRA alternative https://fusionjs.com/ ?

**Comment by KevinGrandon** [comment]
Hi folks, Fusion.js core developer here. I'd be happy to work with folks to figure out the best way to get storybook & Fusion.js interop working well. Happy to jump on a call if helpful.

**Comment by igor-dv** [comment]
Join our [slack](https://now-examples-slackin-rrirkqohko.now.sh/). I think @ndelangen will be happy to onboard new people =)

Also we are working on the `presets` ecosystem for storybook, so it will also be possible as a preset in the feature.

**Comment by ndelangen** [comment]
@KevinGrandon Sorry for me jumping on this a bit late.

Let's schedule a meeting shall we?

When would be a good time for you?

**Comment by KevinGrandon** [comment]
I'd be happy to, but it sounds like waiting for the `presets` might be the best way to go here? Any documentation on the plan for those?

**Comment by ndelangen** [comment]
When @igor-dv is back from vacation I'm sure he'll add some docs about it.

We'll gradually be opening the presets feature and documenting it better.

To the point that once we have the [unified config](https://storybook.canny.io/roadmap/p/universal-config-file) we'll just have a list of add presets configured.

**Comment by KevinGrandon** [comment]
Sounds good, schedule is just a bit crazy these days, but will see if we can schedule some time to get this done!
