### ISSUE TITLE
[addon-centered] Centered addon doesn't pass props for Angular component

### ISSUE THREAD

**Issue by andrei-ilyukovich** [storybooks/storybook#4021]
### Bug or support request summary

While using centered addon for Angular it is not possible to pass props into component, they are appeared to be lost.

### Steps to reproduce

Create simple story with demo component

```js
import { storiesOf } from "@storybook/angular";
import { Button } from "@storybook/angular/demo";
import { centered } from "@storybook/addon-centered/angular";

storiesOf("Button", module)
    .addDecorator(centered)
    .add("with some emoji", () => ({
        component: Button,
        props: {
            text: "some text"
        }
    }));

```
Expected centered button:
![image](https://user-images.githubusercontent.com/6919053/44195475-d9927380-a141-11e8-8c39-d3910845ad47.png)

Actual button:

![image](https://user-images.githubusercontent.com/6919053/44195536-034b9a80-a142-11e8-901f-879f8465bafb.png)

### Version of Storybook and affected addons

- "@storybook/addons": "^4.0.0-alpha.16",
- "@storybook/angular": "^4.0.0-alpha.16",
- "@storybook/addon-centered": "^4.0.0-alpha.16"

**Comment by igor-dv** [comment]
Duplicate to #3836
