### ISSUE TITLE
@storybook/addon-backgrounds set background via name

### ISSUE THREAD

**Issue by donaldpipowitch** [storybooks/storybook#4025]
Hi there,

we have some `url(data:image/gif;base64,....)` set as a possible background with `@storybook/addon-backgrounds`. We would like to enable this background in a storyshot test only and not as the default background. It seems like the URL can't be used correctly in the test because of encoding problems. While I try to figure out the encoding problem, I'd like to ask if it would be possible to set the background as a query param via the `name` field of the background. We always thought why this wasn't possible (because it would make the URL "nicer", easier to understand and manipulate manually), but this is the first time were it would also make some technical problem easier, so I thought I'd share the feature request.

The concrete URL is `http://localhost:9001/?background=url%28data%3Aimage%2Fgif%3Bbase64%2CR0lGODlhEAAQAIAAAOXl5f%2F%2F%2FyH5BAAAAAAALAAAAAAQABAAAAIfjG%2Bgq4jM3IFLJgpswNly%2FXkcBpIiVaInlLJr9FZWAQA7%29`.

--- 

I'm sorry for deleting the template, but I just couldn't think of a good way to fit this request in the given template in a way that it is still easy to read 🤔 It seemed more suited for bugs instead of feature requests.

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.20`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.20)

**Comment by donaldpipowitch** [comment]
Thank you 😍
