### ISSUE TITLE
Alpha [info addon] Using withInfo in config.js causes stories not to load

### ISSUE THREAD

**Issue by Undistraction** [storybooks/storybook#4026]
### Bug or support request summary

Using the alpha and applying `withInfo` inside `.storybook/config.js` has no effect or breaks storybook.

### Steps to reproduce

Inside `.storybook/config`:

```javascript
addDecorator(
  withInfo({
    inline: true,
  })
)

configure(loadStories, module)
```

Results in no build errors, but:

![cap](https://user-images.githubusercontent.com/161489/44221020-24c77900-a178-11e8-9e5f-8f9db5bd987a.png)

Without the `addDecorator` it loads fine and shows all stories.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react ^4.0.0-alpha.16
- @storybook/addon-info ^4.0.0-alpha.16

End bug report support request - delete the rest below

**Comment by stclairdaniel** [comment]
I'm having this same issue. Once I add `addDecorator(withInfo);` to the config file, none of my stories load. No errors or warnings, just no stories.

**Comment by billyvg** [comment]
Getting the same issue in `3.4.10`
