### ISSUE TITLE
getstorybook with react-native, creates react structure.

### ISSUE THREAD

**Issue by amed** [storybooks/storybook#4029]
I am using: 

```
  "react": "16.3.1"
  "react-native": "0.55.4"
```
the app was created via `$ react-native init`
`getstorybook v3.4.10`.

inside the app directory I run`$ getstorybook` I got the following output:
```
 • Detecting project type. ✓
 • Adding storybook support to your "Create React App" based project. ✓
 • Preparing to install dependencies. ✓
 • Installing dependencies. ✓
```

created structure is react configurations, not react-native.

**Comment by kumarpatel** [comment]
https://github.com/storybooks/storybook/blob/master/lib/cli/lib/detect.js#L27-L30

That logic determines your project type as a react app based on the existence of react-scripts in your dependencies.

If that's the case, then you might be able to just remove your react-scripts from there temporarily. run getstorybook in project. Then bring back your react-scripts.

Hope that helps.

**Comment by ndelangen** [comment]
You can also add storybook manually, the CLI is just a helper.

The newer CLI also allows you to specify which framework you want.

Please post here if you need further help
