### ISSUE TITLE
[Documentation] Update sample tsconfig to have "emitDecoratorMetadata": true

### ISSUE THREAD

**Issue by andrei-ilyukovich** [storybooks/storybook#4035]
I think typescript config on guide page should be updated to contain 
```ts
"emitDecoratorMetadata": true
```

Without that property there is a big chance to get errors like below during building stories for components that have some dependencies
```
Uncaught Error: Can't resolve all parameters for SomeComponent: (?, ?)
```
### Steps to reproduce

Navigate to sample tsconfig snippet https://storybook.js.org/configurations/typescript-config/#tsconfigjson

**Comment by igor-dv** [comment]
Do you want to PR this?
