### ISSUE TITLE
storyshots-puppeteer: Incorrect error when screenshots do not much

### ISSUE THREAD

**Issue by markelog** [storybooks/storybook#4036]
### Bug or support request summary

When current screenshots do not much with previous ones. i.e. https://github.com/storybooks/storybook/blob/9ce7c434c2bc40413586da0f7eb72e107b9127a7/addons/storyshots/storyshots-puppeteer/src/index.js#L68

Current code path always pass the error to the logger - https://github.com/storybooks/storybook/blob/9ce7c434c2bc40413586da0f7eb72e107b9127a7/addons/storyshots/storyshots-puppeteer/src/index.js#L70

And since `expect` throws...

### Steps to reproduce

See above

### Please specify which version of Storybook and optionally any affected addons that you're running

```json
- "@storybook/addon-storyshots": "^4.0.0-alpha.16",
- "@storybook/addon-storyshots-puppeteer": "^4.0.0-alpha.16",
```

**Comment by Hypnosphi** [comment]
Released as [4.0.0-alpha.18](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.18)
