### ISSUE TITLE
How to configure tailwind css for use with storybook

### ISSUE THREAD

**Issue by anish000kumar** [storybooks/storybook#4038]
### Bug or support request summary

I am trying to configure tailwind css with storybook, but since it requires some webpack configuration, it's not as straightforward as other configs. At this point, I am not even sure if it's possible currently. 

### Steps to reproduce

So far, I have tried to  use custom webpack config (referring storybook and tailwind docs):
```javascript
const path = require("path");
const tailwindcss = require("tailwindcss");

// Export a function. Accept the base config as the only param.
module.exports = (storybookBaseConfig, configType) => {
  // configType has a value of 'DEVELOPMENT' or 'PRODUCTION'
  // You can change the configuration based on that.
  // 'PRODUCTION' is used when building the static version of storybook.

  // Make whatever fine-grained changes you need
  storybookBaseConfig.module.rules.push({
    test: /\.scss$/,
    loaders: ["style-loader", "css-loader", "sass-loader", "postcss-loader"],
    include: path.resolve(__dirname, "../")
  });
  storybookBaseConfig.plugins = [
    tailwindcss("./tailwind.js"),
    require("autoprefixer")
  ];

  // Return the altered config
  return storybookBaseConfig;
};
```

But that gives an error:
```
info => Loading custom webpack config (full-control mode).
/Users/anishkumar/Documents/react/ez2/node_modules/tapable/lib/Tapable.js:375
		arguments[i].apply(this);
		             ^

TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/anishkumar/Documents/react/ez2/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/anishkumar/Documents/react/ez2/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:33:19)
    at exports.default (/Users/anishkumar/Documents/react/ez2/node_modules/@storybook/core/dist/server/middleware.js:29:40)
    at buildDev (/Users/anishkumar/Documents/react/ez2/node_modules/@storybook/core/dist/server/build-dev.js:163:36)
    at Object.<anonymous> (/Users/anishkumar/Documents/react/ez2/node_modules/@storybook/react/dist/server/index.js:23:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/anishkumar/Documents/react/ez2/node_modules/@storybook/react/bin/index.js:3:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

### Please specify which version of Storybook and optionally any affected addons that you're running

```
    "@storybook/react": "^3.4.10",
    "@storybook/addon-actions": "^3.4.10",
    "@storybook/addon-links": "^3.4.10",
    "@storybook/addons": "^3.4.10",
```

**Comment by igor-dv** [comment]
It's not so clear what is the problem, but one thing I've noticed:

This:
```js
 storybookBaseConfig.plugins = [
    tailwindcss("./tailwind.js"),
    require("autoprefixer")
  ];
```

Should probably be this:
```js
 storybookBaseConfig.plugins = [
    ...storybookBaseConfig.plugins, // <----
    tailwindcss("./tailwind.js"),
    require("autoprefixer")
  ];
```

**Comment by anish000kumar** [comment]
Actually I tried the same before, it still produces the same error.

**Comment by igor-dv** [comment]
Ah, actually both `autoprefixer` and `tailwindcss` are PostCss plugins. And you are trying to set them to the Webpack plugins...

**Comment by Abramovick** [comment]
@igor-dv but the tailwind docs do show how to configure it with webpack like here: https://tailwindcss.com/docs/installation/#webpack

Did you manage to get tailwind to work with Storybook by the way? As I'm struggling here...

**Comment by rayoplateado** [comment]
Same problem here. Not sure how to solve this...

**Comment by Abramovick** [comment]
I did manage to get it working at the end

`// webpack.config.js`
```
const path = require('path');

// Export a function. Accept the base config as the only param.
module.exports = ({ config, mode }) => {

  /* Support for React Native Web */
  config.resolve = {
    modules: ['node_modules'],
    extensions: ['.web.js', '.js', '.json', '.web.jsx', '.jsx', 'ts', 'tsx'],
    alias: {
      'react-native': 'react-native-web',
    },
  };

  /* PostCSS Support */
  config.module.rules.push({
    test: /\.css$/,
    loaders: [
      // Loader for webpack to process CSS with PostCSS
      {
        loader: 'postcss-loader',
        options: {
          /* 
            Enable Source Maps
           */
          sourceMap: true,
          /*
            Set postcss.config.js config path && ctx 
           */
          config: {
            path: './.storybook/',
          },
        },
      },
    ],

    include: path.resolve(__dirname, '../'),
  });

  /* TypeScript Support */
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      {
        // Typescript compiler
        loader: require.resolve('awesome-typescript-loader'),
      },
      {
        // Webpack loader to generate docgen information from Typescript React components.
        loader: require.resolve('react-docgen-typescript-loader'),
      },
    ],
  });

  config.resolve.extensions.push('.ts', '.tsx');

  // Return the altered config
  return config;
};

```

**Comment by rayoplateado** [comment]
Yeah solved! thank you @Abramovick!!

**Comment by AmoDinho** [comment]
Thanks @Abramovick this literally saved my life bruv! 🎲

**Comment by urbgimtam** [comment]
This is great! Should be done as example on the docs! Thanks.

**Comment by ziodave** [comment]
Using _@storybook/preset-create-react-app_ and without custom a _webpack.config.js_ file, following [Custom Webpack Config](https://storybook.js.org/docs/configurations/custom-webpack-config/), this is how I changed `.storybook/main.js` to have postcss use the postcss.config.js file:

```
module.exports = {
  stories: ["../src/**/*.stories.js"],
  addons: [
    "@storybook/preset-create-react-app",
    "@storybook/addon-actions",
    "@storybook/addon-links",
   // ... your existing configuration here ...
  ],
  webpackFinal: (config) => {

    return {
      ...config,
      module: {
        ...config.module,
        rules: [
          // Filter out the default .css rule.
          ...config.module.rules.filter((rule) => /\.css$/ !== rule.test),
          // Add our own css rule which in turn will read the postcss.config.js from project root.
          {
            test: /\.css1$/,
            exclude: [/\.module\.css$/, /@storybook/],
            use: [
              "style-loader",
              {
                loader: "css-loader",
                options: { importLoaders: 1, sourceMap: false },
              },
              {
                loader: "postcss-loader",
                options: {
                  ident: "postcss",
                  sourceMap: false,
                },
              },
            ],
          },
        ],
      },
    };
  },
};
```

**Comment by zakkor** [comment]
@ziodave 's solution works, but with the Create React App preset, only in dev mode, because it's not filtering out the existing rules correctly.
Here's how I got it to work on the latest versions, using CRA:
```
const path = require('path')

module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-knobs',
    '@storybook/addon-actions',
    '@storybook/addon-links',
  ],
  webpackFinal: (config) => {
    return {
      ...config,
      module: {
        ...config.module,
        rules: [
          // Filter out the default .css and .module.css rules and replace them with our own.
          ...(config.module.rules = config.module.rules.map((f) => {
            if (f.oneOf === undefined) {
              return f
            }

            return {
              oneOf: f.oneOf.map((r) => {
                if (r.test === undefined) {
                  return r
                }

                if (r.test.toString() === '/\\.css$/') {
                  return {
                    test: /\.css$/,
                    exclude: [/\.module\.css$/, /@storybook/],
                    include: path.resolve(__dirname, "../"),
                    use: [
                      'style-loader',
                      {
                        loader: 'css-loader',
                        options: { importLoaders: 1, sourceMap: false },
                      },
                      'postcss-loader',
                    ],
                  }
                }
                if (r.test.toString() === '/\\.module\\.css$/') {
                  return {
                    test: /\.module\.css$/,
                    exclude: [/@storybook/],
                    include: path.resolve(__dirname, "../"),
                    use: [
                      'style-loader',
                      {
                        loader: 'css-loader',
                        options: { importLoaders: 1, sourceMap: false, modules: true },
                      },
                      'postcss-loader',
                    ],
                  }
                }
                return r
              }),
            }
          })),
        ],
      },
    }
  },
}
```

**Comment by coclav** [comment]
a minimal effort option that worked for me : https://stackoverflow.com/a/58924651/2656988 

Essentially `vue add storybook` and `npm run storybook:serve`

**Comment by robokozo** [comment]
> a minimal effort option that worked for me : https://stackoverflow.com/a/58924651/2656988
> 
> Essentially `vue add storybook` and `npm run storybook:serve`

I tried this approach out but unfortunately it was missing some of the benefits of using the more modern `npx sb init` process.

**Comment by jozsefDevs** [comment]
> @ziodave 's solution works, but with the Create React App preset, only in dev mode, because it's not filtering out the existing rules correctly.
> Here's how I got it to work on the latest versions, using CRA:
> 
> ```
> const path = require('path')
> 
> module.exports = {
>   stories: ['../src/**/*.stories.js'],
>   addons: [
>     '@storybook/preset-create-react-app',
>     '@storybook/addon-knobs',
>     '@storybook/addon-actions',
>     '@storybook/addon-links',
>   ],
>   webpackFinal: (config) => {
>     return {
>       ...config,
>       module: {
>         ...config.module,
>         rules: [
>           // Filter out the default .css and .module.css rules and replace them with our own.
>           ...(config.module.rules = config.module.rules.map((f) => {
>             if (f.oneOf === undefined) {
>               return f
>             }
> 
>             return {
>               oneOf: f.oneOf.map((r) => {
>                 if (r.test === undefined) {
>                   return r
>                 }
> 
>                 if (r.test.toString() === '/\\.css$/') {
>                   return {
>                     test: /\.css$/,
>                     exclude: [/\.module\.css$/, /@storybook/],
>                     include: path.resolve(__dirname, "../"),
>                     use: [
>                       'style-loader',
>                       {
>                         loader: 'css-loader',
>                         options: { importLoaders: 1, sourceMap: false },
>                       },
>                       'postcss-loader',
>                     ],
>                   }
>                 }
>                 if (r.test.toString() === '/\\.module\\.css$/') {
>                   return {
>                     test: /\.module\.css$/,
>                     exclude: [/@storybook/],
>                     include: path.resolve(__dirname, "../"),
>                     use: [
>                       'style-loader',
>                       {
>                         loader: 'css-loader',
>                         options: { importLoaders: 1, sourceMap: false, modules: true },
>                       },
>                       'postcss-loader',
>                     ],
>                   }
>                 }
>                 return r
>               }),
>             }
>           })),
>         ],
>       },
>     }
>   },
> }
> ```

This is super useful ⬆️ 🤯 💚

In addition to this, I have struggled a bit because I have CRA + TS + Craco setup. I'm just makin a switch from SCSS to Tailwind. 

So obviously I forgot to add a postcss.config.js inside the project root:

```
module.exports = { 
    plugins: [require('tailwindcss'), require('autoprefixer')] 
};
```

Also always remember that with Tailwind there is no import for the styles on component level (compared to simple CSS or CSS modules) so Webpack (used in Storybook) does not know where to grab the entry point for Tailwind. 

To make this happen, be sure that you make a ```import 'index.css';``` in  ```.storybook/preview.js```. This way as Webpack starts to load in, it can grab Tailwind's entry point. 

Sorry for the extension but I also needed these info to make this happen. Hopefully will help someone out there. 👋

Versions used:
```
    "react-scripts": "3.4.1",
    "@craco/craco": "^5.8.0",
    "@storybook/addon-actions": "6.0.21",
    "@storybook/addon-essentials": "6.0.21",
    "@storybook/addon-links": "6.0.21",
    "@storybook/node-logger": "6.0.21",
    "@storybook/preset-create-react-app": "3.1.4",
    "@storybook/react": "6.0.21",
    "@tailwindcss/aspect-ratio": "0.2.0",
    "@tailwindcss/postcss7-compat": "^2.0.2",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.2",
    "tailwindcss-truncate-multiline": "1.0.3",
```

**Comment by mimesis-technology** [comment]
@jozsefDevs big thanks for the additional comment! worked like a charm
