### ISSUE TITLE
@storybook/addon-storysource doesn't work when storiesOf is imported as alias

### ISSUE THREAD

**Issue by Everettss** [storybooks/storybook#4039]
If you don't use default `storiesOf` name `@storybook/addon-storysource` doesn't find story source

```js
import { storiesOf as storiesOfAlias } from '@storybook/react';

const stories = storiesOfAlias('Example', module);
stories.add('default', () => <div>Story source</div>);
```

This problem is related to searching of fixed name `const STORIES_OF = 'storiesOf';` in [file](https://github.com/storybooks/storybook/blob/master/addons/storysource/src/loader/parse-helpers.js#L1).

**Comment by igor-dv** [comment]
Yeah, I knew this moment would come... Currently, It supports a common use-case... For a more robust solution, it will require some more AST manipulation, like finding aliases. Also, the `stories.add` will probably break the navigation from within the storysource panel, because it searches for the pattern of `storiesOf().add().add()`

**Comment by Everettss** [comment]
@igor-dv I totally agree that this problem is more general than I initially described. It's easy to solve only this problem of `import { storiesOf as storiesOfAlias } from '@storybook/react';`. But new usecases can occur like:

```js
import { storiesOf } from '@storybook/react';
const storiesOfAlias = storiesOf;

const stories = storiesOfAlias('Example', module);
stories.add('default', () => <div>Story source</div>);
```
Question is open: **is it worth to work on it?**

**Comment by igor-dv** [comment]
I think any improvement is welcomed =) Do you want to work on it?

**Comment by Everettss** [comment]
I've got some implementation only for this problem `import { storiesOf as storiesOfAlias } from '@storybook/react';`. I will take a look at some more general solutions.
