### ISSUE TITLE
Not able to see stories, if imported from external module

### ISSUE THREAD

**Issue by shikaan** [storybooks/storybook#4041]
### Bug or support request summary
Not able to see stories, if imported from external module

### Steps to reproduce

I have a component library (namely, `component-lib`) which run its own Storybook and everything works great. Now, I want to run the same storybook within another project (aka `project`)  along with stories specific for `project`. 

I tried (mainly) two things:

**1) Create a build of stories in the component library**
This way I can include those with something like
```
configure(() => {
    // require local stories
   require('component-lib/stories')
}, module)
```
I am using _exactly_ the same configuration with which the Storybook is working within `component-lib` itself, the only difference is that in the `stories.js` build all the Storybook dependencies are webpack externals (because I want to use the storybook version I have in `project`).

Storybook start smoothly, the `storiesOf` method is called correctly, the `storyStore` is populated correctly, but for some reason I cannot see anything in interface (I got the empty state UI)

**2) Make `project` build, again, `component-lib`'s stories along with local ones** 
In this case I am importing all the `*.stories.js` files from `component-lib` in `project` and build them as if they were part of `project`.

In this case is webpack which is behaving funnily: apparently it has some problems while loading babel, as the JSX of the stories is not parsed. 

### Please specify which version of Storybook and optionally any affected addons that you're running

- "@storybook/addon-actions": "^4.0.0-alpha.16",
- "@storybook/addon-info": "^4.0.0-alpha.16",
- "@storybook/addon-knobs": "^4.0.0-alpha.16",
- "@storybook/addon-links": "^4.0.0-alpha.16",
- "@storybook/addon-options": "^4.0.0-alpha.16",
- "@storybook/addon-viewport": "^4.0.0-alpha.16",
- "@storybook/react": "^4.0.0-alpha.16",

**Comment by shikaan** [comment]
**Update**

Apparently the issue is that requiring Storybook stuff from `component-lib` and from `project` gives me two different instances of Storybook, even though I marked Storybook libraries as externals. That means that it's not a problem with storybook itself. 

I guess this can be closed, but I'll leave it here if someone has the same issue.

Thanks!

**Comment by jacoswarts** [comment]
Hi @shikaan, I'm not quite following your inclusion of stories in point (1). I would like to do something similar, but not sure how to go about it.

I have a separate repo for each component for our component library and each of these have their own storybook and stories. Once the component is published to npm, I would like to install it as a dependency of the component library and import its stories in some way.

Do you have a suggestion on how to export the stories from one of the component projects and how to import them into the component library project without making manual copies of the stories?
