### ISSUE TITLE
Question: How to set 'public path' for static files?

### ISSUE THREAD

**Issue by Jungwoo-An** [storybooks/storybook#4044]
I want to do access static files through public path (ex: /static, /public ...). what should i do?

**Comment by Jungwoo-An** [comment]
If can't set public path, can i modify source?

**Comment by tmeasday** [comment]
Hi @Jungwoo-An - have you tried the `-s` option to `start-storybook`?

**Comment by Jungwoo-An** [comment]
@tmeasday Yes. But i'm not access through directory name. only access `/` (url)

**Comment by igor-dv** [comment]
@Jungwoo-An, can you please elaborate your use case?

**Comment by Jungwoo-An** [comment]
@igor-dv Thank for your interested. 

my component is access static files via '/static/' url, but can't access static file in storybook. thus image crashed.

i solved this problem using middleware. but i hope i can use command line arguments.

```js
// middleware.js

const express = require('express');
const path = require('path');

module.exports = router => router.use('/static', express.static(path.join(__dirname, '../static')));
```

**Comment by gabrielbs** [comment]
@Jungwoo-An 

I'm not sure if I understand your problem, but if is access images on CSS like background-image, try with "~/" 

example: 

.div { background-image: url("~/background.jpg") }
