### ISSUE TITLE
Toggling decorator functionality when building storybook

### ISSUE THREAD

**Issue by ClemMakesApps** [storybooks/storybook#4049]
Is it possible to disable a decorator using a CLI argument when performing `build-storybook` or something similar? I'd like the option to toggle a decorator functionality when building storybook.

**Comment by igor-dv** [comment]
Who is this decorator? 
Anyway, you can add whatever **env** variable you wish and use them anywhere (almost) in your code.

```
cross-env STORYBOOK_MEGA_DUPER_DECORATOR=foobar npm run build-storybook .....
```

And then in the code:

```js
const thingy = process.env.STORYBOOK_MEGA_DUPER_DECORATOR
```
