### ISSUE TITLE
Support lit-html / Question html

### ISSUE THREAD

**Issue by daKmoR** [storybooks/storybook#4050]
## Support for lit-html
First I wanna say 4.0.0 alpha looks verrryyy nice :)
especially love the `storybook/app/html` :)

I could almost use it out of the box with [lit-html](https://github.com/Polymer/lit-html).

The only thing I needed to change was the render function in [render.js](https://github.com/storybooks/storybook/blob/master/app/html/src/client/preview/render.js) and add the dependency to [package.json](https://github.com/storybooks/storybook/blob/master/app/html/package.json).

## Main Question
So I'm a little unsure if it's worth it create a "fork" of `storybook/app/html` with just 2 file changes. 

If it's worth I could prepare a pull request.

### Expected behavior:
- I can use lit-html in stories e.g. something like this (using not yet released syntax)
```js
import { html } from 'lit-html';

storiesOf('Demo', module)
  .add('lit-html story', () => html`
    <div .property=${'foo'}>
       <button @click=${clickHandler}>click me</button>
    </div>
  `);
```

### More Details

deviation from to app/html/src/client/preview/render.js
```js
import { document, Node } from 'global';
import { html, render, TemplateResult } from 'lit-html';

// ... next 3 lines are for reference
  } else if (component instanceof Node) {
    rootElement.innerHTML = '';
    rootElement.appendChild(component);
// actual code added below
  } else if (component instanceof TemplateResult) {
    // `render` stores the TemplateInstance in the Node and tries to update based on that.
    // Since we reuse `rootElement` for all stories, remove the stored instance first.
    // But forceRender means that it's the same story, so we want too keep the state in that case.
    if (!forceRender) {
      render(html``, rootElement);
    }
    render(component, rootElement);
  } else {
```

**Comment by igor-dv** [comment]
Any reason you don't want to use `@storybook/polymer` ?

Maybe you can create a decorator for that, that way nothing will be changed in the source?

something like this:

```js
import { document } from 'global';
import { html, render, TemplateResult } from 'lit-html';

const litDecorator = (story) => {
  if (component instanceof TemplateResult) {
    const  el = document.createElement('section'); // this element probably can br reused.
    render(story(), el);
    return el;
  }

  return story();
}
```

And then in a story:

```js
storiesOf('Demo', module)
  .addDecorator(litDecorator)
  .add('lit-html story', () => html`
    <div .property=${'foo'}>
       <button @click=${clickHandler}>click me</button>
    </div>
  `);
```

You can also add it globally.

**Comment by daKmoR** [comment]
2 excellent points :)

How could I have overlooked that lit-html was in the polymer app? :see_no_evil: 
sorry for that will try it out :)

I may want to avoid the "polymer-webpack-loader" as I'm not in an mixed envirorment where I need support for html imports... but using a simple decoration will be an excellent choice then :)

=> I will report on what I will end up with :)

**Comment by daKmoR** [comment]
using `@storybook/polymer` directly works really well :)

thxxxx :)
