### ISSUE TITLE
What to do when I want to provide parameters to the my webpack.config.js?

### ISSUE THREAD

**Issue by Viperwow** [storybooks/storybook#4051]
### Question summary

I found that `-c` option is specifying a path to the folder with storybook's `config.js` file and `webpack.config.js` to customize the build process of the storybook of the app.

But is it possible to pass custom parameters to the `webpack.config.js`? I want to build a storybook with branded components  without the complexity of the multiple configs for each brand and therefore I have to pass different parameters like this:

**package.json** (_CURRENT_)
```json
{
  "scripts": {
    "storybook": "start-storybook -p 9001 -c ./configs"
  }
}
```

**package.json** (_WHAT I WANT_)
```json
{
  "scripts": {
    "storybook": "start-storybook -p 9001 -c ./configs --env.env=custom_env_variable --env.brand=my-awesome-brand"
  }
}
```

**webpack.config.js**
```js
module.exports = function (data) { // Get env parameter from --env
  return require("./webpack." + data.env + ".config.js")({env: data.env, brand: data.brand})
};
```

**Comment by igor-dv** [comment]
You can use, for example, [cross-env](https://github.com/kentcdodds/cross-env/issues/15) to set the environment variable.
And then, in the code, just take it from process.env.XXX
