### ISSUE TITLE
[Question] @storybook/addon-jest watch workflow

### ISSUE THREAD

**Issue by chemoish** [storybooks/storybook#4053]
### Support Request

Better understanding of guide to [generating-the-test-results](https://github.com/storybooks/storybook/tree/v3.4.3/addons/jest#generating-the-test-results).

### Steps to reproduce

1. Generate jest output and have it show up in storybook 👍 

    `jest --json --outputFile=jest-test-results.json`

    This will generate a test file at a location that can be consumed by the `withTests` decorator. Everything works as expected.

1. Generate jest output on watch ❓ 

    `jest --json --outputFile=jest-test-results.json --watch`

    This will generate an empty test file at the location and wait for changes (no changes since last commit). If you press `a` for all, then all tests will need to be generated before there is any HMR updates (While it technically works, its super slow with a large suite). If you press `w`, then generated test file will be empty until you go into a test and manually make a new change.

### Versions

- @storybook/addon-jest 3.4.3
- jest 21.2.1

### Acceptance criteria

1. Start storybook
2. Use storybook for both tests and stories

I don't see a reason to include tests outside of development as there are other means for managing test failures and code coverage and build time?

Maybe this just won't work my theoretical workflow, or with Jest output + watch mode?

Thanks!

**Comment by jeroenkampinga** [comment]
Having the same issue. Did you ever find a way to combine this?

**Comment by chemoish** [comment]
Unfortunately I did not, I never ended up using the addon.
