### ISSUE TITLE
storyshots should respect threshold on --updateSnapshot 

### ISSUE THREAD

**Issue by donaldpipowitch** [storybooks/storybook#4054]
### Bug or support request summary

Hi, we currently use storyshots in our CI and across developers who use either Mac or Linux. We use `failureThreshold` to not get failing tests with slight differences in font rendering. But when we run it with `--updateSnapshot` the new snapshots with slight differences in font rendering are written down to disk which creates noise in the Merge Requests. It would be nice, if these snapshots would only be written down if `failureThreshold` was hit.

### Steps to reproduce

If you need something I can try to create it, but I hope the description explains the use case enough :)

### Please specify which version of Storybook and optionally any affected addons that you're running

- "@storybook/react": "v4.0.0-alpha.14"
- "@storybook/addon-storyshots": "v4.0.0-alpha.14"

**Comment by igor-dv** [comment]
Does it something that [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) support?

**Comment by donaldpipowitch** [comment]
Not sure, as I haven't used it directly so far, but I can't find a related config in the README.

**Comment by igor-dv** [comment]
Are you using docker to run these tests?

**Comment by donaldpipowitch** [comment]
Yes :)

**Comment by igor-dv** [comment]
🤔 so why do you have changes?

**Comment by donaldpipowitch** [comment]
Oops 🙈 This issue is actually older than our Docker setup 🤣 we made it afterwards. It is correct that _we_ currently don't need it anymore, because we don't need any `failureThreshold` anymore currently. But I guess it is still good to have for anyone who uses `failureThreshold`.

**Comment by igor-dv** [comment]
I have no idea what to do with this 😅 PR is welcomed anyway.
