### ISSUE TITLE
Knobs + Object Props & re-initialization of component

### ISSUE THREAD

**Issue by yangwen2** [storybooks/storybook#4059]
So I'm using storybook with Angular.  Knobs works great when the inputs to the component are primitives.  The component's default change detection takes over and the component re-renders with the new values accordingly.

However when dealing with objects as prop, mutating the prop via knobs doesn't update the component.  This is to be expected, because the component in question likely does not recognize a change in the prop due to the data mutation.

What I really need, is for storybook to re-initialize the component with the latest prop value that I've supplied via knob. For example - I have a chart component that accepts an input object that describes the colors and other attributes for the chart.  When I tweak these settings via Knobs, I would like for the component to be re-initialized with the new values I've set via Knobs. 

I noticed that when I update the prop via Knobs, the deep URL gets updated with a parameter 'knob-options', which is set to the serialized value of the prop.  Is this used for something?  Is what I described above doable with  Knobs?

**Comment by igor-dv** [comment]
Hey @yangwen2, can you maybe share an example of the `story`?

**Comment by yangwen2** [comment]
Below is my story declaration.  I didn't find documentation on the differences between using an inline template versus a component property. I've found using the template property triggers more change detection via knobs than using the component property.
`stories.add('blah story', () => {
  const options = object('options', chartOptions);
  return {
    moduleMetadata: {
      imports: [ChartModule],
    },
    props: {
      options,
    },
    template: `<chart [options]="options"></chart>`,
  };
})`

The options input prop is a JS Obj. Below is a snippet of it.

{
    lineThickness: 10,
    innerRadius: 30,
    colorScale: ['#406A9C', '#FFD47D'],
}

As you can see, it contains info that affects rendering within the component. When I update the values in knobs, the component doesn't update since I'm simply mutating the prop object. From a component design perspective, I don't want to perform change detection on those visual attributes since there isn't a use case for those values to change post component initialization.

What I simply need is the ability to modify these properties via knobs, and then have the component re-initialize with the updated prop obj, so it reflects the new values I entered.  Is this possible?

**Comment by igor-dv** [comment]
What if you will create options like this:

```js
stories.add('blah story', 
  () => { 
    const options = {
      lineThickness: number(),
      innerRadius: number(),
      colorScale: select()
    }
  
    return {   /* blah blah */    }
)
```

**Comment by yangwen2** [comment]
Thanks for the quick reply.  Unfortunately, that didn't work.  Component is not being re-initialized.  Are there Angular component lifecycle hooks that I can register to observe the creation and destroy of components?

**Comment by binomialstew** [comment]
@yangwen2, have you tried to forcing a rerender using the addon knobs channel after the data is changed?
```js
import addons from '@storybook/addons'
import Events from '@storybook/core-events'
...
addons.getChannel().emit(Events.FORCE_RE_RENDER)
```

**Comment by conorriches** [comment]
We are also having this issue, and `addons.getChannel().emit(Events.FORCE_RE_RENDER)` doesn't make seem to work either.

Trying to get Storybook Knobs defined in an object which is passed into the component:

Here is my code:
```
const cardProps = {
  client: text("client", "ClientNameHere"),
   ...
};

stories.add("default", () => <Card {...cardProps} />, {
  jest: ["Card.test.jsx"]
});


```

**Comment by igor-dv** [comment]
You should define knobs in the story function. Or change `cardProps` to something like:
```js
const cardProps = () => {
  client: text("client", "ClientNameHere"),
   ...
};
```

**Comment by conorriches** [comment]
That worked - many thanks!

**Comment by wimbush** [comment]
Hi,

I'm running into this problem with React. Right now, I'm reacting to prop changes with static getDerivedStateFromProps and componentDidUpdate.

This is a bit clunky, and introduces a lot of extra work.

Can anyone provide guidance on how to force storybook to re-render a component based on in-browser changes to the configurable storybook knobs?

**Comment by anilanar** [comment]
I'm 99% sure that this is caused by using something like:

```
decorators: [
  StoryFn => <div><StoryFn /></div>,
]
```

instead of 

```
decorators: [
  storyFn => <div>{storyFn()}</div>,
]
```

The reason is, decorators are chained to create the `StoryFn` and its value by reference changes on every render. Thus when you try `<StoryFn />`, React sees a different function reference. When React sees a different function ref, it unmounts the previous and mounts the new, which destroys the internal state of the component.

If you want to mount your stories as components (let's say, because you need to consume context from a direct wrapper), just use the following HoC:

```
// Wraps your component with an intermediate component so that you can
// be sure that you will be mounted as a component, instead of being called as a function.
function indirect<T>(C: ComponentType<T>): ComponentType<T> {
  return props => {
    return <C {...props} />;
  };
}
```

Example:

```
const MyStory = indirect(() => {
  const foo = useContext(MyContext);
  return <MyComponent foo={foo} />;
});

**Comment by Aapzu** [comment]
@anilanar can't express how grateful I am that I found your comment. was having a mental breakdown with my components unmounting randomly... the next question is: why do storybook's docs tell to write the decorators like this:
```
export default {
  title: "Button",
  component: Button,
  decorators:  [(Story) => <div style={{ margin: '3em' }}><Story/></div>]
};
```
(https://storybook.js.org/docs/react/writing-stories/decorators#component-decorators)

**Comment by anilanar** [comment]
@Aapzu Knobs is a hack. The problem is with knobs, not with decorators/storybook API.

This kind of problems arise when the author of a library/tool doesn't acknowledge/admit that the author is employing a hack that will break in unexpected ways; especially demotivating for newcomers.

In this particular case, Storybook team themselves forgot about the knobs hack when they were writing those docs. The old docs suggested using `story()` instead of `<Story />`.

**Comment by anilanar** [comment]
@Aapzu That must be a mistake. Old docs suggested `story()` instead of `<Story />`.

**Comment by shilman** [comment]
When you write `<Story />` it allows you to use hooks in your story function. I guess there are tradeoffs in both directions and we haven't fully nailed this yet.
