### ISSUE TITLE
How to add a copywebpackplugin to storybook webpack config in full control mode.

### ISSUE THREAD

**Issue by VRedondo** [storybooks/storybook#4069]
As already reported in 
https://github.com/storybooks/storybook/issues/2115

try
```js
baseConfig.plugins.push(
    new CopyWebpackPlugin([
      {
        from: `src/assets`,
        to: 'assets'
      }
    ])
);
```
does not work.

**Comment by Hypnosphi** [comment]
@VRedondo I wasn't able to reproduce the issue in master. 
Can you please create a GitHub repo with minimal reproduction?

**Comment by VRedondo** [comment]
I'm sorry, I didn't update this before, not an issue anymore.
