### ISSUE TITLE
Error running storybook when path contains a space character

### ISSUE THREAD

**Issue by mjoyce91** [storybooks/storybook#4072]
### Bug or support request summary

When running storybook, I receive the following error in the console:

```
Scanning folders for symlinks in /my_path/Web Projects/my_app/node_modules (34ms)

ENOENT: no such file or directory, stat '/my_path/Web'
```

You can see that the space is not recognized. I have encountered this on other applications based on how it was configured to read file paths.

### Steps to reproduce

- Create a project that is in a folder (or within a sub-folder) that contains a space character in it's name. Examples: `/path/my Path/app`, `/documents/my app`, etc.
- `npm run storybook`
- ` react-native run-android`

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react-native": "^3.4.10"

**Comment by Keraito** [comment]
hey @mjoyce91 	I initialized and ran Storybook on a fresh `create-react-app` project in a `t est` folder (with space), and it succeeded. Could you try with an alpha version of Storybook?

**Comment by ndelangen** [comment]
Please re-open if this is still an issue

**Comment by ndelangen** [comment]
Thanks for checking @Keraito
