### ISSUE TITLE
Question: how to position addon-info "inline" option?

### ISSUE THREAD

**Issue by trevordmiller** [storybooks/storybook#4075]
I'd like to place proptype tables in my stories as documentation. So I know I need to use [the `inline` option](https://github.com/storybooks/storybook/tree/master/addons/info#options-and-defaults), but it doesn't seem like you can customize where the inline pieces are placed - would it be possible to tell where inline should place the prop table(s) (above/below rendered story)?

**Comment by igor-dv** [comment]
@trevordmiller, the code of the `addon-info` that renders everything is located [here](https://github.com/storybooks/storybook/blob/master/addons/info/src/components/Story.js)

You are welcome to play with it and PR =)

**Comment by trevordmiller** [comment]
Ok thanks
