### ISSUE TITLE
Array knob does not work with custom separator

### ISSUE THREAD

**Issue by martinmacko47** [storybooks/storybook#4078]
### Bug or support request summary

[Array knob](https://github.com/storybooks/storybook/tree/master/addons/knobs#array) does not work with custom separator. Instead, it converts the custom separator to comma and returns only a single item array.

### Steps to reproduce

For instace using:

```
const options = array('Options', ['aaa', 'bbb', 'ccc'], ':')
```

renders the knob values separated with a comma, not the colon as given in the parameter:

![1](https://user-images.githubusercontent.com/5547275/44623807-5f988200-a8d9-11e8-9ecc-8b237d811d48.png)

Editing the knob value by adding another item `:ddd` converts `:` to `,` again:

![2](https://user-images.githubusercontent.com/5547275/44623822-aa19fe80-a8d9-11e8-90ff-d4ace35806a8.png)

And sets the knob value returned from `array('Options', ['aaa', 'bbb', 'ccc'], ':')` to `["aaa,bbb,ccc,ddd"]`. The array with just a single item. Nothing gets separated by the separator, as my custom separator is being replaced with comma, so there is no separator left in the value string.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.18
- @storybook/addon-knobs 4.0.0-alpha.18

Confirmed with 4.0.0-alpha.14 as well.

### Affected platforms 

Affects all platforms

**Comment by martinmacko47** [comment]
Yes, the bug is still there.

**Comment by martinmacko47** [comment]
I think it is silly to have a bot closing unfixed bugs.

**Comment by martinmacko47** [comment]
lol

**Comment by igor-dv** [comment]
We have a bunch of issues with knobs. Sure, we do need to fix them. Any community help is much appreciated. If anyone wants to help by creating a PR with the fix until the team could handle this, that'd be great

**Comment by kallaugher** [comment]
This can no longer be reproduced in @storybook/react 4.1.2 and 
@storybook/addon-knobs 4.1.2.

![storybook-knobs-bug](https://user-images.githubusercontent.com/12979339/50057210-3d02d100-0135-11e9-93f2-01df950777db.gif)

**Comment by Keraito** [comment]
Confirmed in the official storybook examples that this has been fixed as described by @kallaugher, closing this!
