### ISSUE TITLE
Addon-Info: Fix issues with property names

### ISSUE THREAD

**Issue by fredcido** [storybooks/storybook#4087]
### Bug or support request summary

Addon-info is destructing the `propType` object when it comes as a string. https://github.com/storybooks/storybook/blob/master/addons/info/src/components/types/PrettyPropType.js#L34

### Steps to reproduce

When using a simple component, the prop types are not being presented on the PropTables:

```js
import React from 'react';
import PropTypes from 'prop-types';

/** Button component description */
const Button = ({ disabled, label, style, onClick }) => (
  <button disabled={disabled} style={style} onClick={onClick}>
    {label}
  </button>
);

Button.defaultProps = {
  disabled: false,
  onClick: () => {},
  style: {},
};

Button.propTypes = {
  /** Boolean indicating whether the button should render as disabled */
  disabled: PropTypes.bool,
  /** button label. */
  label: PropTypes.string.isRequired,
  /** onClick handler */
  onClick: PropTypes.func,
  /** component styles */
  style: PropTypes.shape,
};

export default Button;

...

storiesOf('Button', module)
  .add(
    'Default',
    () => <Button label="test" />,
  );
...

```

![button_story](https://user-images.githubusercontent.com/7162412/44715806-f40d0b00-aab8-11e8-9ff2-3baa6625952f.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.14
- @storybook/addon-info 4.0.0-alpha.1

**Comment by ryanfitzer** [comment]
I'm seeing the same issue with:

```
"@storybook/addon-info": "^3.4.11"
"@storybook/react": "^4.0.0-alpha.22"
```

**Comment by supadupdip** [comment]
Also seeing the same thing on 4.0.0-alpha.23
