### ISSUE TITLE
@storybook/react 4.0.0-alpha.18 alias to @babel/runtime breaks build with some libs

### ISSUE THREAD

**Issue by SleepWalker** [storybooks/storybook#4088]
### Bug

There are some structural changes between stable `@babel/runtime@7.0.0` and `@babel/runtime@7.0.0-beta.42` (or other beta versions, where @babel/runtime contained more helpers).

In default config we have an alias:

https://github.com/storybooks/storybook/blob/v4.0.0-alpha.18/lib/core/src/server/config/webpack.config.js#L107-L109

In case, when we have some dependencies, that rely on older babel version (`react-swipeable-views` in my case), current storybook configuration will break the build with similar to the following errors:

```
ERROR in ./node_modules/react-swipeable-views-utils/lib/bindKeyboard.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/builtin/possibleConstructorReturn' in '/home/danilenko/htdocs/fc-app/node_modules/react-swipeable-views-utils/lib'
 @ ./node_modules/react-swipeable-views-utils/lib/bindKeyboard.js 18:57-124
 @ ./node_modules/react-swipeable-views-utils/lib/index.js
 @ ./packages/app/search/components/PerformersListContainer.js
 @ ./packages/app/search/components/TopPerformersList.js
 @ ./packages/app/search/index.js
 @ ./packages/app/shell/App.js
 @ ./packages/app/shell/index.js
 @ ./packages/app/dev-tools/storybook/ContextProvider.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./node_modules/react-swipeable-views/lib/SwipeableViews.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/builtin/possibleConstructorReturn' in '/home/danilenko/htdocs/fc-app/node_modules/react-swipeable-views/lib'
 @ ./node_modules/react-swipeable-views/lib/SwipeableViews.js 20:57-124
 @ ./node_modules/react-swipeable-views/lib/index.js
 @ ./packages/app/search/components/PerformersListContainer.js
 @ ./packages/app/search/components/TopPerformersList.js
 @ ./packages/app/search/index.js
 @ ./packages/app/shell/App.js
 @ ./packages/app/shell/index.js
 @ ./packages/app/dev-tools/storybook/ContextProvider.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./node_modules/react-event-listener/dist/react-event-listener.cjs.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/builtin/typeof' in '/home/danilenko/htdocs/fc-app/node_modules/react-event-listener/dist'
 @ ./node_modules/react-event-listener/dist/react-event-listener.cjs.js 11:30-78
 @ ./node_modules/react-swipeable-views-utils/lib/bindKeyboard.js
 @ ./node_modules/react-swipeable-views-utils/lib/index.js
 @ ./packages/app/search/components/PerformersListContainer.js
 @ ./packages/app/search/components/TopPerformersList.js
 @ ./packages/app/search/index.js
 @ ./packages/app/shell/App.js
 @ ./packages/app/shell/index.js
 @ ./packages/app/dev-tools/storybook/ContextProvider.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```

If you remove an alias — everything works like a charm. Is there any reason to have a hardcoded alias?

### More details

Here is an example of the code, that will break the build with current storybook config:

```js
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/builtin/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.getDomTreeShapes = getDomTreeShapes;
exports.findNativeHandler = findNativeHandler;
exports.default = void 0;

// ...
```

`resolve.alias` will force to use the top-level `node_modules/@babel/runtime` module, instead of local module with correct version, e.g. `node_modules/react-swipeable-views/node_modules/@babel/runtime/helpers`

**Comment by SleepWalker** [comment]
As a temporary fix you can use `NormalModuleReplacementPlugin`:

```js
    new webpack.NormalModuleReplacementPlugin(
      /@babel\/runtime\/helpers\/builtin/,
      resource => {
        resource.request = resource.request.replace(
          '@babel/runtime/helpers/builtin',
          'react-swipeable-views/node_modules/@babel/runtime/helpers/builtin',
        );
      },
    ),
```

replace `react-swipeable-views` with the name of one of the modules, that failing to build

**Comment by xueqingxiao** [comment]
same issue.

**Comment by Hypnosphi** [comment]
> any reason to have a hardcoded alias

Mostly to avoid an extra peer dependency

**Comment by maosenchen6ix** [comment]
same issue here

**Comment by SleepWalker** [comment]
@Hypnosphi ok, I can submit PR. I'm considering an option to make more precise alias (e.g. only to directory helpers/esm, because regenerator runtime was untouched for years), but... I have removed alias entry completely and everything works fine. Can you please tell in which case it won't work or, probably point to an issue?

**Comment by cheapsteak** [comment]
react-powerplug is also broken by this

https://github.com/renatorib/react-powerplug/issues/166#issuecomment-417783881

**Comment by shilman** [comment]
@SleepWalker @cheapsteak Is this still an issue in `^4.0.0` or `4.1.0-alpha.*`? Thanks for your patience and help on this!

**Comment by SleepWalker** [comment]
@shilman It does not work on 4.0.9. In 4.1.0-alpha8 it does not work too.

It won't fix till we have babel runtime alias in storybook config or till all the libs will be upgraded to use stable babel 7 (i mean material-ui, react-swipeable and others).

**Comment by chikalaka** [comment]
> As a temporary fix you can use `NormalModuleReplacementPlugin`:

@SleepWalker can you explain where you have added this code? (currently not working for me)
Thanks.

**Comment by SleepWalker** [comment]
@chikalaka you need to use webpack.config.js (extend mode):

https://storybook.js.org/configurations/custom-webpack-config/#extend-mode

```
module.exports = {
  plugins: [...]
};
```

**Comment by chikalaka** [comment]
@SleepWalker I'm using the Full control mode + default, maybe a noob webpack question, but where did you get the webpack object?

My code:
```
module.exports = (baseConfig, env, defaultConfig) => {

  defaultConfig.plugins.push(
    new webpack.NormalModuleReplacementPlugin(
      /@babel\/runtime\/helpers\/builtin/,
      resource => {
        resource.request = resource.request.replace(
          '@babel/runtime/helpers/builtin',
          '@material-ui/node_modules/@babel/runtime/helpers/builtin',
        );
      },
    )
  )

// some other code here

  return defaultConfig
};
```

**Comment by SleepWalker** [comment]
Just type on top of file:

```js
const webpack = require('webpack');
```

**Comment by chikalaka** [comment]
Thanks.
Still getting an error:

ERROR in ./node_modules/react-event-listener/dist/react-event-listener.cjs.js
Module not found: Error: Can't resolve '@material-ui/core/node_modules/@babel/runtime/helpers/builtin/typeof' in '/Users/edanc/workspace/chika/frontend/client/node_modules/react-event-listener/dist'
 @ ./node_modules/react-event-listener/dist/react-event-listener.cjs.js 11:30-78
 @ ./node_modules/@material-ui/core/withWidth/withWidth.js
 @ ./node_modules/@material-ui/core/withWidth/index.js
 @ ./node_modules/@material-ui/core/index.es.js
 @ ./src/app/commonComponents/CustomTextField/enhance.js
 @ ./src/app/commonComponents/CustomTextField/CustomTextField.js
 @ ./src/app/commonComponents/CustomTextField/stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true

**Comment by ndelangen** [comment]
I think we can remove the alias from preview config now that the preview and manager are split @shilman Let me open a PR.

**Comment by SleepWalker** [comment]
@chikalaka it does not work probably because your Plugin config is incorrect. Both `@material-ui` and `react-event-listener` using stable babel 7+. Looks like your build previously have failed with some other package. You should temporary disable plugin, than look at the error during build and notice what the package is causing an issue and use it's name for plugin setup. E.g. if you have the following error:

>ERROR in ./node_modules/**`react-swipeable-views-utils`**/lib/bindKeyboard.js
> Module not found: Error: Can't resolve '@babel/runtime/helpers/builtin/possibleConstructorReturn' in '/home/danilenko/htdocs/fc-app/node_modules/react-swipeable-views-utils/lib'

you need to provide path relative to the `react-swipeable-views-utils` in your plugin config:

```js
module.exports = (baseConfig, env, defaultConfig) => {

  defaultConfig.plugins.push(
    new webpack.NormalModuleReplacementPlugin(
      /@babel\/runtime\/helpers\/builtin/,
      resource => {
        resource.request = resource.request.replace(
          '@babel/runtime/helpers/builtin',

          // here I'm using the module, that caused the original error
          'react-swipeable-views-utils/node_modules/@babel/runtime/helpers/builtin',

        );
      },
    )
  )

// some other code here

  return defaultConfig
};
```

**Comment by Hypnosphi** [comment]
BTW did you try replacing the default alias with your own?

```
module.exports = {
  resolve: {
    alias: {
      '@babel/runtime': <path to package>
    }
  }
}
```

**Comment by chikalaka** [comment]
@SleepWalker @Hypnosphi 
When using the "Full control mode + default":
```
module.exports = (baseConfig, env, defaultConfig) => {

  defaultConfig.resolve = {
    ...defaultConfig.resolve,
    alias: {
      ...defaultConfig.resolve.alias,
      "@babel/runtime": "@babel/runtime"
    }
  }

  // more code here

  return defaultConfig
}
```

**Comment by raiprabh** [comment]
Thanks @chikalaka, your solution worked for me!
