### ISSUE TITLE
Latest 4.0.0 alpha breaks with babel 

### ISSUE THREAD

**Issue by blainekasten** [storybooks/storybook#4090]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Latest 4.0.0 alpha breaks because `yup` has a dependency on a different pre-release version of @babel.

https://github.com/jquense/yup/blob/master/package.json#L88
https://github.com/storybooks/storybook/blob/master/package.json#L76

Now that babel 7 is officially released, it seems like it would make sense to coordinate with @jquense to update both packages to stable babel

### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.18

### Screenshots / Screencast / Code Snippets (Optional)

```
ERROR in ./node_modules/yup/lib/util/createValidation.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/builtin/objectWithoutProperties' in '/Users/kastens/Sites/kepler/haven/node_modules/yup/lib/util'
 @ ./node_modules/yup/lib/util/createValidation.js 8:55-120
 @ ./node_modules/yup/lib/mixed.js
 @ ./node_modules/yup/lib/index.js
 @ ./src/screens/account/profile.tsx
 @ ./stories/screens/account.tsx
 @ ./stories/screens sync \.tsx$
 @ ./stories/index.stories.tsx
 @ ./stories sync .stories.tsx$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

```

**Comment by bill-vatomic** [comment]
+1. Had to roll back to alpha-16 to make this work.

`ERR! Failed to build the storybook
ERR! ./.storybook/addons.js
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! ReferenceError: [BABEL] /Users/bill/Projects/wombo/.storybook/addons.js: Unknown option: /Users/bill/Projects/wombo/node_modules/react/index.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.
ERR! 
ERR! A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
ERR! 
ERR! Invalid:
ERR!   `{ presets: [{option: value}] }`
ERR! Valid:
ERR!   `{ presets: [['presetName', {option: value}]] }`
ERR! 
ERR! For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/Users/bill/Projects/wombo/node_modules/react/index.js")
ERR!     at Logger.error (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
ERR!     at OptionManager.mergeOptions (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
ERR!     at /Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
ERR!     at /Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
ERR!     at Array.map (<anonymous>)
ERR!     at OptionManager.resolvePresets (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
ERR!     at OptionManager.mergePresets (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
ERR!     at OptionManager.mergeOptions (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
ERR!     at OptionManager.init (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
ERR!     at File.initOptions (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/index.js:212:65)
ERR!     at new File (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/index.js:135:24)
ERR!     at Pipeline.transform (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
ERR!     at transpile (/Users/bill/Projects/wombo/node_modules/babel-loader/lib/index.js:50:20)
ERR!     at /Users/bill/Projects/wombo/node_modules/babel-loader/lib/fs-cache.js:118:18
ERR!     at ReadFileContext.callback (/Users/bill/Projects/wombo/node_modules/babel-loader/lib/fs-cache.js:31:21)
ERR!     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:242:13)
ERR!  @ multi ./.storybook/addons.js ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js manager[0]
ERR! ./.storybook/config.js
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! ReferenceError: [BABEL] /Users/bill/Projects/wombo/.storybook/config.js: Unknown option: /Users/bill/Projects/wombo/node_modules/react/index.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.
ERR! 
ERR! A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
ERR! 
ERR! Invalid:
ERR!   `{ presets: [{option: value}] }`
ERR! Valid:
ERR!   `{ presets: [['presetName', {option: value}]] }`
ERR! 
ERR! For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/Users/bill/Projects/wombo/node_modules/react/index.js")
ERR!     at Logger.error (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
ERR!     at OptionManager.mergeOptions (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
ERR!     at /Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
ERR!     at /Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
ERR!     at Array.map (<anonymous>)
ERR!     at OptionManager.resolvePresets (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
ERR!     at OptionManager.mergePresets (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
ERR!     at OptionManager.mergeOptions (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
ERR!     at OptionManager.init (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
ERR!     at File.initOptions (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/index.js:212:65)
ERR!     at new File (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/file/index.js:135:24)
ERR!     at Pipeline.transform (/Users/bill/Projects/wombo/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
ERR!     at transpile (/Users/bill/Projects/wombo/node_modules/babel-loader/lib/index.js:50:20)
ERR!     at /Users/bill/Projects/wombo/node_modules/babel-loader/lib/fs-cache.js:118:18
ERR!     at ReadFileContext.callback (/Users/bill/Projects/wombo/node_modules/babel-loader/lib/fs-cache.js:31:21)
ERR!     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:242:13)
ERR!  @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./.storybook/config.js iframe[2]
info Building storybook completed.
error Command failed with exit code 1.`

**Comment by jquense** [comment]
not sure how i'm involved but there is a new version of yup out now :P

**Comment by blainekasten** [comment]
😆 I made a mistake.. Doesn't actually seem like I have an issue here with storybooks. Updating yup fixed it for me.
