### ISSUE TITLE
How to install properly

### ISSUE THREAD

**Issue by mshaw-nm** [storybooks/storybook#4096]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

What is the correct way to install this, if I do an npm install @storybook/addon-knobs@latest, I get version 4.0.0, however this doesn't include all of the props mentioned in the documentation (i.e radio is missing and will throw an error). 

If I install using npm install @storybook/addon-knobs@4.0.0-alpha.18, when I try to run I get errors in that it can't compile:

Module not found: Error: Can't resolve '@babel/runtime/helpers/assertThisInitialized' 

here is what my .babelrc looks like:
{
  "presets": ["env", "stage-3", "react"],
  "plugins": ["react-hot-loader/babel", "styled-components", "transform-class-properties"]
}

The documentation seems to be showing features that are not in the latest version (4.0.0), which would be installed if you followed the instructions for the plugin.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react ^3.4.10
- @storybook/addon-knobs 4.0.0

**Comment by ndelangen** [comment]
I cannot reproduce this:

```
> $ yarn info  @storybook/addon-knobs
yarn info v1.10.1
{ name: '@storybook/addon-knobs',
  description: 'Storybook Addon Prop Editor Component',
  'dist-tags':
   { alpha: '4.0.0-alpha.25',
     latest: '3.4.11',
...
```
