### ISSUE TITLE
What about having a way to generate (click) snapshots for specific knob variables in the frontend. 

### ISSUE THREAD

**Issue by brunoreis** [storybooks/storybook#4103]
I'm thinking in a workflow where I set some dynamic data on my component and click to freeze that data in a component that can be snapshotted. 

Maybe I can create it in a new storybook stories dir/config. 

That could be nice to change knob values and grab snapshots of the actual values. The same would be very helpful for ApolloMocked provider. To grab some dynamic data and transform it into a mocked data in the "snapshots" stories dir.  

The ideal world scenario would be having an icon on that stories list showing that some tests are failing. 

Do those things make sense?
Do you like the idea? 
What is the path to get there? 

I can help to code it.

**Comment by andrei-ilyukovich** [comment]
I have the similar question regarding making screenshots for all possible knobs selected/updated. Right now storybook can make screenshot only for default component state, which doesn't cover all possible variants.
Is it possible to update storyshots addon to make this real somehow?

**Comment by ndelangen** [comment]
@brunoreis Yeah I've been thinking about these sort of functionality as well.

Saving a knob-state into a story sounds awesome.

We could start simple:
We add a tool-button to the knobs panel. When clicked this button would show the code that you'd have to write to add to your storyfile.

In order to write to the actual file, we'll need to add an api from manager to server.
We do not have such an api yet.

Let's schedule a call about this @brunoreis.

Join our Discord so we can chat?
https://discord.gg/sMFvFsG

**Comment by ndelangen** [comment]
@andrei-ilyukovic seems to me you should write stories for those examples then?

**Comment by andrei-ilyukovich** [comment]
> 
> 
> @andrei-ilyukovic seems to me you should write stories for those examples then?

I could but then I don't need to use knobs at all...and having a lot of stories for only one component doesn't look good to me, it is a mess. To my mind it is much better to use knobs functionality instead.

**Comment by brunoreis** [comment]
@andrei-ilyukovich, this is interesting because when I opened this task I was think similar to you but using it more I started to understand similar to @ndelangen that it's good to have multiple stories. 

Even because otherwise you would create a new kind of entity or pseudo entity (a mock variation story) with no correspondence to a file or code and that sure would add a lot of complexity to SB. 

One simple and not directly thing that helped me a lot to accommodate multiple variations of a component story on my mind was was discovering that I can nest stories into a deep hierarchy using "/" in story type names. If you already figured that out, won't make a difference. But, otherwise, will help you to organize things.

**Comment by ndelangen** [comment]
Yeah, join the discord and send me a PM, so we can discuss a bit faster/easier?

**Comment by brunoreis** [comment]
@ndelangen, I'm almost not using knobs in the actual workflow I'm using. I was waiting to be sure I had some real world need to tell you about regarding this task, but in fact I'm favoring other approaches than knobs here. I have a testData dir with "fixtures" and create a single story for every one. Most of them indeed are fed by Apollo mocked queries and mutations.

**Comment by ndelangen** [comment]
Related: #4996
