### ISSUE TITLE
Storybook flow-type error for addon-links?

### ISSUE THREAD

**Issue by techieshark** [storybooks/storybook#4104]
### Bug or support request summary

I believe there may be an error in Storybook's Flow type definitions. Either that or I'm misunderstanding something...

When I run `flow` I get the following error:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/stories/MyButton.story.js:10:45

Cannot create MyButton element because a callable signature is missing in SyntheticMouseEvent [1] but exists in
function type [2] in property onClick.

     src/stories/MyButton.story.js
      7│
      8│ export default () => {
      9│   storiesOf('MyButton', module).add('default', () => (
     10│     <MyButton onClick={linkTo('AnotherComponent')} />
     11│   ));
     12│ };
     13│

     flow-typed/npm/@storybook/addon-links_v3.x.x.js
 [1] 11│     ): SyntheticMouseEvent<T>,

     src/components/MyButton/MyButton.js
 [2]  7│   onClick: (SyntheticMouseEvent<>) => any,
```

(On my terminal, `linkTo('AnotherComponent')`, passed to `onClick` above,  is in red.)

I would expect to get no errors here.

### Steps to reproduce

* Create project with Create React App
* Follow default Storybook install instructions
* Install Flow definitions: `yarn add flow-typed && yarn flow-typed install` # downloads flow definitions for Storybook & addons since they're in package.json
* Create a component like MyButton.js, with an `onClick` property:
```
type Props = {
  onClick: (SyntheticMouseEvent<>) => any,
};

const MyButton = (props: Props) => (
  <button type="button" {...props}>Click me</button>
);
* `yarn add flow-bin`
* Run flow: `yarn flow`
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.6
- @storybook/addon-links 3.4.6
- flow-bin 0.80.0

### Affected platforms 

- OS X, flow-bin 

### Screenshots / Screencast / Code Snippets (Optional)

Tracking this down...

First, note [the definition of `linkTo`](https://github.com/storybooks/storybook/blob/release/3.4/addons/links/src/preview.js#L8
):

```js
export const linkTo = (kind, story) => (...args) => {
  const resolver = valueOrCall(args);
  openLink({
    kind: resolver(kind),
    story: resolver(story),
  });
};
```

It's a function which takes two arguments, and returns a click handler `(...args) => {...}`.

Flow describes [what click handlers should look like](https://flow.org/en/docs/react/events/) - for example, something like:

```js
 handleClick = (event: SyntheticEvent<HTMLButtonElement>) => {
   ...
  };
```

Finally, see the [Flow type defintion for `linkTo`](https://github.com/flow-typed/flow-typed/blob/8e2ca848b1a326e4770268834df077a59787c05a/definitions/npm/%40storybook/addon-links_v3.x.x/flow_v0.53.x-/addon-links_v3.x.x.js#L5):

```js
  declare module.exports: {
    linkTo<T>(
      book: string | LinkToFunction,
      kind?: string | LinkToFunction
    ): SyntheticMouseEvent<T>,
```

I believe that says, roughly, `linkTo` is a function of two arguments, which returns an event (a `SyntheticMouseEvent`). 

It seems like it should say it returns not an event, but rather a function from event to `void`.

I changed it locally (in `/flow-typed/npm/@storybook/addon-links_v3.x.x.js`) to the following:
```js
 linkTo<T>(
      book: string | LinkToFunction,
      kind?: string | LinkToFunction
    ): (SyntheticMouseEvent<T>) => void,
```
and it seems to work (running `flow` returns no errors).

**Comment by techieshark** [comment]
@pascalduez perhaps I should have reported this issue over at flow-typed. Pinging you here since I believe you authored the Storybook flow defs but may not have seen the issue above.

In a nutshell, it seems in the [existing flow-typed def for Storybook](https://github.com/flow-typed/flow-typed/blob/8e2ca848b1a326e4770268834df077a59787c05a/definitions/npm/%40storybook/addon-links_v3.x.x/flow_v0.53.x-/addon-links_v3.x.x.js#L5)

```
 linkTo<T>(
      book: string | LinkToFunction,
      kind?: string | LinkToFunction
    ): SyntheticMouseEvent<T>,
```

should really be

```
 linkTo<T>(
      book: string | LinkToFunction,
      kind?: string | LinkToFunction
    ): (SyntheticMouseEvent<T>) => void,
```

because Storybook [linkTo](https://github.com/storybooks/storybook/blob/release/3.4/addons/links/src/preview.js#L8) returns an event handler, not an event. 

If you are able to confirm that, I'm happy to submit a PR on flow-typed.

**Comment by pascalduez** [comment]
Hi @techieshark,

Yes obviously the current definition is quite false... 

But the `linkTo` function can also be used outside of an event handler, so maybe
```js
 ): (?SyntheticMouseEvent<T>) => void,
```
Or
```js
 ): () => void,
```
We need to test this thoroughly in the definition.
