### ISSUE TITLE
Cannot find module 'wide-align' when running  "yarn bootstrap --core"

### ISSUE THREAD

**Issue by brunoreis** [storybooks/storybook#4112]
I've cloned the repo and followed instuctions on CONTRIBUTING.md
But, when I run
```
yarn bootstrap --core
```

it throws an error saying that

```
Error: Cannot find module 'wide-align'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/scalablepath/storybook/node_modules/gauge/render-template.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
```

**Comment by igor-dv** [comment]
Hey, 
You should `yarn install` for the first time. Since you have no modules installed, yarn `bootstra won't` work

**Comment by brunoreis** [comment]
I did it. To double check I just cloned all again and run yarn install again. My node_modules listing is showing a total of 1280, but the same error is still happening and there is no wide-align module there.
 
<img width="376" alt="screen shot 2018-09-03 at 14 12 52" src="https://user-images.githubusercontent.com/217240/44997282-7d25b580-af83-11e8-8f53-df0b8121aa5e.png">

**Comment by igor-dv** [comment]
That is strange because I use `yarn bootstrap` pretty much a lot. Anyway `yarn install` will probably be enough for the basic usage. Also, you need to run `yarn dev` to watch the changes. And then just use one of the example apps to test the change.

**Comment by brunoreis** [comment]
Thanks. Would it be possible that the wide-align package is installed globally on your machine? I'm not very used to monorepos yet, but researching a little here I found out that with yarn workspaces you should only have a root yarn.lock. But, there is a yarn.lock inside the docs folder. Is that correct? Maybe that's what is causing that conflict.

**Comment by igor-dv** [comment]
`yarn list` gives me this:
![image](https://user-images.githubusercontent.com/7867954/45027696-d0167000-b04a-11e8-8cf6-178d57c96fe1.png)

it's not global IMO. 

Docs are not a part of the `workspace`, they are bootstrapped separately

**Comment by brunoreis** [comment]
In fact when I run yarn list it also shows wide-align@1.1.3 here.

The error occurs after the install command, that runs well. It happens when running
```
lerna run prepare -- --silent
``` 

I will need to lear more about lerna to go deeper into it.

**Comment by ndelangen** [comment]
@brunoreis that's super strange, could you clone master from scratch and try again?

Maybe upgrading yarn to the latest version could help?

We have no dependency on `wide-align` at all, I wish there was more that I could do..
I do not know if there's anything I can do, can you reproduce on an another machine?
