### ISSUE TITLE
mark babel-loader as a dependency

### ISSUE THREAD

**Issue by trippingtarballs** [storybooks/storybook#4116]
According to [the instructions](https://github.com/storybooks/storybook/blob/v4.0.0-alpha.20/docs/src/pages/basics/guide-react/index.md#add-storybookreact) to stand-up a Storybook React project all one need to do, from within their project;

```shell
$ npm i --save-dev @storybook/react
```

However, as see [in the source](https://github.com/storybooks/storybook/blob/620dc75db02056ee42a21cb4106b58b848ba1986/app/react/package.json#L39) for the `package.json` of `@storybook/react` (extract below), the need for `babel-loader` is marked as a `peerDependencies`. As in, the consumer of `@storybook/react` must provide their preferred version of `babel-loader`.

```json
  },
  "peerDependencies": {
    "babel-loader": "^7.0.0 || ^8.0.0 || ^8.0.0-beta.6",
    "react": ">=15.0.0",
    "react-dom": ">=15.0.0"
  }
```

However, without `babel-loader` installed by the consumer, and with `@storybook/react` installed in their React project, the following `babel` error is returned when attempting to invoke `start-storybook`;

```
Module not found: Error: Can't resolve 'babel-loader' in ...
```

Either the installation instructions for `@storybook/react` should include `babel-loader` as an additional dependency, or `babel-loader` should be listed in the `dependencies` section of the `package.json` for the `@storybook/react` project.

**Comment by Hypnosphi** [comment]
Yes, we need to update those instruction. If you'd like to open a PR, please refer to https://github.com/storybooks/storybook/blob/master/MIGRATION.md#babel-7

**Comment by ndelangen** [comment]
Hey @trippingtarballs would you be able to open a PR to fix? 🙇

**Comment by annezhou920** [comment]
@ndelangen I can take this on if @trippingtarballs haven't had the chance to. 

Should I update the instructions to say `Add react, react-dom, babel-core, and babel-loader` and include `npm i --save-dev babel-loader@7`?
https://github.com/storybooks/storybook/blob/v4.0.0-alpha.20/docs/src/pages/basics/guide-react/index.md#add-react-react-dom-and-babel-core

**Comment by ndelangen** [comment]
@annezhou920 that would be really welcome!

these are the peerDependencies for react:
https://github.com/storybooks/storybook/blob/master/app/react/package.json#L44-L46

here's vue:
https://github.com/storybooks/storybook/blob/master/app/vue/package.json#L45-L48

here's angular:
https://github.com/storybooks/storybook/blob/master/app/angular/package.json#L47-L54

here's html:
https://github.com/storybooks/storybook/blob/master/app/html/package.json#L39

They all have the babel-loader in common

**Comment by annezhou920** [comment]
@ndelangen it'll be my first time making a PR for the OSS community. i have a branch ready to be pushed up but i'm getting permission errors. do i need to have permission to push up to the repo?

**Comment by ndelangen** [comment]
@annezhou920 happy to welcome you into the OSS community! You're doing great!
