### ISSUE TITLE
Addon for multiple storybook versions of the same lib

### ISSUE THREAD

**Issue by kroeder** [storybooks/storybook#4124]
Our team is about to write an addon that allows us to
- Show the current version of our lib (package.json => version) e.g. in the bottom of the navigation bar
- Inject a dropdown that has multiple ways of adding something like
```
[{
  label: 'v1.0.0',
  url: '__BASE_HREF__/v1.0.0'
}, {
  label: 'v1.1.0',
  url: '__BASE_HREF__/v1.1.0'
}]
```
Either directly as `string[]` or something like a promise for async scan of available versions (e.g. on page reload)

**Why?**
We want to offer backward compatibility for our internal UI-Framework. If an app uses v1.0.0 of our framework but 3 years later there's a v3.0.0 a developer should be able to check the legacy documentation for v1.0.0

Currently, we do have a strict directory structure for this (pseudo):
```
public/
  |
  | --- awesome-ui-library
       |
       | --- v1.0.0
       | --- v1.1.0
```

**My questions:**
- Is it possible to hook in the sidebar and place something at the bottom of it (injecting the DOM-Elements is enough, CSS can handle the rest 💪 😂 )
- Is this something you are interested in and want to join me on a "how to implement" discussion? 

We are going to do this anyway, if it is possible. Just thought we could benefit from each other if we work together 👍

**Comment by kroeder** [comment]
From a library perspective I can imagine something like this in e.g. `.storybook/config.js`

```
const currentVersion = getPackageJsonVersion();
const availableVersions = getStorybookVersions(); // Either by HTTP-GET or string[] list

// one way could be to add it to the options
setOptions({
  availableVersions
});

// Or a seperate thing
addDecorator( withVersioning(currentVersion, availableVersions) ) // pseudo
```

**Comment by igor-dv** [comment]
@ndelangen is working on a major UI refactoring which will probably allow this kind of customization. But currently, it's not possible

**Comment by kroeder** [comment]
Alright, I'll implement it as a landing page story and check this again after the UI refactoring happened

**Comment by igor-dv** [comment]
Also, maybe you can add it as a addon to addons panel

**Comment by kroeder** [comment]
Hm, interesting idea. You mean like if you are on e.g. FancyButtonStory and click on "Versions" Panel, then switch versions but directly jump to the same story in a different version?

**Comment by igor-dv** [comment]
Yeah

**Comment by karankiri** [comment]
@kroeder Do let me know if you worked on this or have any addon. Thanks
