### ISSUE TITLE
Can't reexport the named export 'visitWithTypeInfo' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by sibelius** [storybooks/storybook#4125]
I'm using 4.0.0-alpha.20, to make storybook work well with babel 7

```jsx
ERROR in ./node_modules/graphql/index.mjs 64:0-70:117
Can't reexport the named export 'visitWithTypeInfo' from non EcmaScript module (only default export is available)
 @ ./node_modules/graphql-relay/lib/connection/connection.js
 @ ./node_modules/graphql-relay/lib/index.js
 @ ./src/common/utils.js
```

![image](https://user-images.githubusercontent.com/2005841/45105041-c43db300-b109-11e8-8444-e4249352fed8.png)

I'm hit this error, I think it is related to .mjs extensions, or a missing babelrc plugin

**Comment by fletcherist** [comment]
Same here

**Comment by igor-dv** [comment]
Google gave me this - https://github.com/graphql/graphql-js/issues/1272 issue. I belive it's not related to us directly.

**Comment by fletcherist** [comment]
@sibelius Actually I've solved this with [this comment](https://github.com/graphql/graphql-js/issues/1272#issuecomment-393903706). Why not to try it out?

Actually the problem here is that Storybook can't parse `.mjs` modules out of box.
I think this issue should be closed.

**Comment by sibelius** [comment]
@fletcherist you used a custom webpack config to achieve this?

can u share part of it?

**Comment by fletcherist** [comment]
@sibelius of course, sure:

```js
module.exports = (baseConfig, env, config) => {
  // ...
  config.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: "javascript/auto",
  });
  config.resolve.extensions.push(".mjs");
  // ... Rest params
  return config;
};```

**Comment by igor-dv** [comment]
@Hypnosphi, is this `mjs` something we would like to support by default ?
