### ISSUE TITLE
Move storybook.js.org to Netlify

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#4126]
## Why

Infrastructure for next-gen docs. We've already been deploying our docs and project storybooks there for awhile. With this change we can get rid of the hacked up github pages setup and it will also help us do versioned docs in docs 2.0.

## What

- [x] Update the js.org settings to point `storybook.js.org` at Netlify
- [x] Update https://storybooks.netlify.com/ settings as necessary

**Comment by shilman** [comment]
Log of what's happened so far until the switchover is complete:

1. Submitted the PR to js.org: https://github.com/js-org/js.org/pull/2304
2. js.org setting updated and the Storybooks.js docs site went down temporarily
3. I updated the netlify domain settings
4. The site came back up, but pointing to the github pages version of the site, not the netlify version
5. The PR got merged, and presumably the updated DNS settings are propagating
6. Fingers crossed that it serves properly when the DNS propagates

**Comment by ndelangen** [comment]
How can we verify?

**Comment by shilman** [comment]
Correction to above: apparently `js.org` is served _through_ cloudflare, so there are no DNS settings to propagate. Instead, I believe that Cloudflare is pointing to the Netlify site, and that the site is going through two levels of CDN, which is problematic.

Next steps:
- [ ] Verify that storybook.js.org is serving content from Netlify not GH-pages
- [ ] Set up HTTPS certificates on Netlify
- [ ] Ask `js.org` to bypass cloudflare for the Storybook site (a simple setting in CF)

**Comment by shilman** [comment]
Verify & cleanup:
- [ ] edit docs in minor way & push to `release/3.4` which will trigger netlify deploy
- [ ] verify changes on storybooks.netlify.com and storybook.js.org
- [ ] verify NO changes on `gh-pages` branch which corresponds to `storybooks.github.io/storybook`
- [ ] remove deploy step from circle config & issue PR and notify @pksunkara 
- [ ] update deploy directory on netlify since it's out of sync with `netlify.toml`

**Comment by pksunkara** [comment]
- [ ] Create netlify storybook team
- [ ] Invite storybook github team to netlify storybook team

**Comment by ndelangen** [comment]
There's a netlify team here:
https://app.netlify.com/teams/storybook/members

Let me know who to invite via a personal message

**Comment by pksunkara** [comment]
I have a question about this. Does netlify support deploy production only on tags? Because, we don't want the website to be changed for every commit on master. The documentation might be changed on master but it won't be valid until the next version is published, right?

**Comment by ndelangen** [comment]
yes

**Comment by pksunkara** [comment]
So, netlify doesn't support tag based deploys. It only talks about branches. See this, https://github.com/mochajs/mocha/issues/3206#issuecomment-385365665. Do we want to keep the deploy job in circleci?

**Comment by pksunkara** [comment]
The deploy job in circleci was broken anyway. Once we decide on the process of release deployment on netlify, I will create a new job on circleci. So, here are some more tasks in the list.

- [ ] Decide on the deployment schedule and how to
- [ ] If automated, set it up

**Comment by ndelangen** [comment]
Great topic for the roadmap meeting next week 👍

**Comment by Hypnosphi** [comment]
> we don't want the website to be changed for every commit on master

It's deployed from release branch not master. And we only cherry-pick commits there right before the release so it shouldn't be a problem

**Comment by shilman** [comment]
Almost there: https://github.com/js-org/js.org/pull/2340

**Comment by shilman** [comment]
@pksunkara Closing this and have opened up a follow-up issue regarding deployment: https://github.com/storybooks/storybook/issues/4207
