### ISSUE TITLE
Question: reusing stories in different file (with different parameter)

### ISSUE THREAD

**Issue by daKmoR** [storybooks/storybook#4127]
hey,

I'm just wondering if anyone has already thought of it.
Essentially I would like to reuse a story and "just" change the tag name.

so I have in the left menu "default" which shows 
```html
<example-vanilla>user content</example-vanilla>
```
and then I would like to have "extended" which shows
```html
<other-tag>user content</other-tag>
```
PS: this is, of course, a little simplified 🙈 

Basic Idea
```js
// source.stories.js
addParameters({ tag: 'example-vanilla' });

storiesOf('<example-vanilla>', module)
  .add('default', ({ parameters: { tag } }) => html`
    <${tag}>user content</${tag}>
  `);

export const stories = getAllCurrentStories(); // magically generate an object?

// other.stories.js (completely different location/repository)
import { stories } from './source.stories.js';
storiesOf('<other-tag>', module)
  .addParameters({ tag: 'other-tag' });
  .addStories(stories); // or any manual way
```

Another Idea:
```js
// other.stories.js
const exampleVanillaStories = getStoryKind('<example-vanilla>'); // e.g. a magic function which get's the other stories
storiesOf('<other-tag>', module)
  .addParameters({ tag: 'other-tag' });
  .add('default', exampleVanillaStories.default);

// probably will need to be iterateable so you can just get all stories at once as well
```

So is this completely crazy or might this be possible after digging a little in the code?

PPS: hacky way would be to stub/override storiesOf. addStories at the top of the file - export and then restore original function => would be cumbersome and will not support plugins

**Comment by daKmoR** [comment]
so I did some digging and there is the clientApi and the storyStore...
=> with that I can get the story and also add it but once you click it I get the feeling you can't reuse those stored functions => I just get a white page and quite console errors

maybe something with the scope of the function? it seems to be stored with multiple "wrappings" (multiple closures like defaultDecorateStory, metaSubscription) => as I will do an add of the story afterwards anyways I would only need the "raw" initial function... it seems it's not stored in there... any other place I could look for it?

```js
import 'otherPackages/stories/index.stories.js';
// import clientApi somehow

const store = clientApi._storyStore;
const baseStories = store._data['base-element'].stories.Welcome;

store.removeStoryKind('base-element');

addParameters({ tag: 'example-vanilla' });

storiesOf('Welcome', module)
  .add('from base', baseStories.fn);
```

**Comment by ndelangen** [comment]
`_storyStore` is an internal API bound to change, I recommend not accessing it directly.

I think abstracting the examples to make them more DRY is probably not a really good idea.

Many developers look at stories' source to see how the example was setup so they can mimic or copy it into where they are using the component.

If the example is generated so complex they can no longer see what's going on by just looking at it, I think that's not great.

Having said that, this is possible:
https://storybooks-official.netlify.com/?selectedKind=Core%7CParameters&selectedStory=passed%20to%20story&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by ndelangen** [comment]
Yeah that looks like a good pure-JS solution to me.

That's framework- and in fact storybook-agnostic

**Comment by ndelangen** [comment]
Just to add this this:

`addParameters({ tag: 'example-vanilla' })` is a fine solution as well, you can do this:

```js
storiesOf('path/to/Component')
  .addParameters({ data: 1 })
  .add('my example', ({ parameters: { data }}) => <div>{data}</div>);
```
