### ISSUE TITLE
Storybook Knobs Query Strings not unset/reset when navigating between Story pages

### ISSUE THREAD

**Issue by ReDrUm** [storybooks/storybook#4129]
### Storybook Knobs add `knob-${label}=${value}` query params for each knob added.
This is useful for retaining state for page refreshes and deep linking.

Unfortunately they're not being cleaned up when navigating between different story pages. They simply concatenate together. After browsing a storybook instance for a while and having visited many pages you end up with a mess in your url's query.

### Steps to reproduce

1. Add Knobs (with different names) to two or more pages.
2. Visit page 1. Observe that the query params are updated with the default knob values from that page's knobs.
3. Visit page 2. Observe that the query params are updated to include the knob values from this page, however the previous page's knob query params still exist, despite no longer being relevant.
4. Visit page 3. This page has no knobs. All of the previous page's knobs remain in the url query unexpectedly.

### Affected Versions

This has been happening for ages, but it's still present as of the latest alpha 20.

```
@storybook/addon-knobs": "4.0.0-alpha.20
@storybook/react": "^4.0.0-alpha.20
```

### Example

```
// page1.js
...
const showFoo = boolean('Show Foo', true); // results in '&knob-Show%20Foo=true'
...

// page 2.js
...
const title = text('Title', 'Hello World');// results in '&knob-Title=Hello%20World'
...
```

1. After deep linking to page 1 you'll see `?knob-Show%20Foo=false&&addons=1&stories=1...`
1. After selecting page 2 you'll see `?knob-Title=Hello%20World&knob-Show%20Foo=false&&addons=1&stories=1...`
1. Notice the prior page 1 knob query param is still present despite no longer being necessary.

**Comment by ReDrUm** [comment]
I'm still affected by this. Has no-one else experienced it with their projects? I can't see anything in my configuration which would cause this.

**Comment by igor-dv** [comment]
Hey, I am not sure I can reproduce it. Can you please somehow demonstrate it on the official example -https://storybooks-official.netlify.com

**Comment by ndelangen** [comment]
Knobs params have been removed from URL. It was causing waay to long url, making them unusable.

Addon knobs now support a button, when clicked it will copy the full URL, so you CAN still get back to the exact state. But the params is removed from the URL.

This is on master and will be part of 4.0.0
