### ISSUE TITLE
NPM script is missed for both Angular and React slow guides

### ISSUE THREAD

**Issue by fetis** [storybooks/storybook#4140]
Docs says  https://storybook.js.org/basics/guide-angular/#run-your-storybook
`npm run storybook`
but this script is never created. Only Vue guide has an explanation

**Comment by brickmaker17** [comment]
Is this still needed ? If so I may take a go at it.

**Comment by igor-dv** [comment]
I do see it here - https://storybook.js.org/basics/guide-angular/#add-storybookangular-and-babel-core
