### ISSUE TITLE
4.0.0-alpha with Haul

### ISSUE THREAD

**Issue by EskelCz** [storybooks/storybook#4142]
I'm using Storybook with the Haul packager method as described here:
https://github.com/storybooks/storybook/tree/master/app/react-native

yarn

`storybook start -p 7007 --haul ./storybook/webpack.haul.storybook.js`

haul config

```
import { createWebpackConfig } from 'haul'
export default {
  webpack: createWebpackConfig({
    entry: `./storybook/index.js`
  })
}
```

and the included webpack seems to be building a static bundle, therefore my device will not connect, if I understand correctly. In version 3 the connection and bundling worked fine.

![Image of packaging](https://i.imgur.com/Syar1SR.png)

Any idea how to fix this? Will version 4 support Haul as well? Thank you.

**Comment by EskelCz** [comment]
My use case is that I would like my stories in the same folder as my components, to easily see when I'm missing a story for something.

**Comment by EskelCz** [comment]
I'm trying the same thing without haul and with `react-native-storybook-loader`. Now the client connects but I see only white screen on the device and no components in the menu, although storybook loader says he loaded my components.
This is my fourth attempt to get storybook working and I'm on the cusp of giving up.

**Comment by igor-dv** [comment]
I am not familiar with the RN part of SB that much (and with haul), but I am not seeing from this printscreen that it's a static build.

**Comment by EskelCz** [comment]
I tried the same thing without haul and the client connected. Now I'm geting this error, with everything I try (both storybook 3 and 4):

![Error screen](https://i.imgur.com/5CkIlN4.png)

Maybe something in my stories, I'm digging deeper, will update this when I figure it out.

**Comment by igor-dv** [comment]
I see a few issues with this error, but all are not in RN

https://github.com/storybooks/storybook/issues/1549
https://github.com/storybooks/storybook/issues/3969

**Comment by EskelCz** [comment]
Hm, figured it out, it was a problem with my import aliases. Thank you for helping out.
