### ISSUE TITLE
Panels resizing in storybook-vue are slow and lagging

### ISSUE THREAD

**Issue by Mactaivsh** [storybooks/storybook#4151]
### Bug or support request summary

In @storybook/vue

The resizing of panels become quite slow and lagging

It seems to affect all the panels (include addons like option, action-log, knobs etc)

### Steps to reproduce

I made a reproduction repo, check [here](https://github.com/Mactaivsh/storybook-vue-alpha-test)

This repo has no addition addons, but you can still see the effect

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue 4.0.0-alpha.21
- no addons

### Affected platforms 

- OS: Mac OS 10.13.6
- Browser: Chrome 69.0.3497.81
- Node.js: v8.11.4

### Screenshots / Screencast / Code Snippets (Optional)

Official @storybook/vue demo:

![official](https://user-images.githubusercontent.com/12948083/45278218-aeabfd00-b4fe-11e8-8c5e-bb5206a1f83f.gif)

my demo:

![test](https://user-images.githubusercontent.com/12948083/45278233-c1becd00-b4fe-11e8-981a-87265bbcc747.gif)

**Comment by igor-dv** [comment]
@wuweiweiwu can this issue be also related to the `react-split-pane` ?

**Comment by wuweiweiwu** [comment]
@igor-dv I believe so. But I think #4153 will fix it.

**Comment by wuweiweiwu** [comment]
I'll double check locally with all the example storybooks

**Comment by Mactaivsh** [comment]
> Please specify which version of Storybook and optionally any affected addons that you're running
@storybook/vue 4.0.0-alpha.21
no addons

BTW, I found it also affects the non alpha version, my another test was using 3.4.10

**Comment by wuweiweiwu** [comment]
verified with my fix locally. I ran the vue kitchen sink example and it was dragging fine!

**Comment by wuweiweiwu** [comment]
closing by #4153
