### ISSUE TITLE
storybook for vue error: addon-backgrounds

### ISSUE THREAD

**Issue by qianqian05723** [storybooks/storybook#4157]
Bug or support request summary
![image](https://user-images.githubusercontent.com/17306867/45340253-82f54980-b5c8-11e8-8d14-cf82c2714d19.png)

Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue : 3.4.10
- @storybook/addon-backgrounds 3.4.10

"dependencies": {
    "postcss-flexibility": "^2.0.0",
    "vue": "^2.5.17"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.4.10",
    "@storybook/addon-backgrounds": "^3.4.10",
    "@storybook/addon-console": "^1.0.4",
    "@storybook/addon-knobs": "^3.4.10",
    "@storybook/addon-links": "^3.4.10",
    "@storybook/addon-storysource": "^3.4.10",
    "@storybook/addon-viewport": "^3.4.10",
    "@storybook/addons": "^3.4.10",
    "@storybook/vue": "^3.4.10",
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-preset-vue": "^2.0.2",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^1.1.1",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  }

```js
import { storiesOf } from '@storybook/vue'
import { withBackgrounds } from '@storybook/addon-backgrounds'

storiesOf('Addon|Backgrounds', module)
  .addDecorator(
    withBackgrounds([
      { name: 'twitter', value: '#00aced' },
      { name: 'facebook', value: '#3b5998', default: true }])
  )
  .add('story 1', () => {
    const content = 'You should be able to switch backgrounds for this story'
    return {
      template: `<button>${content}</button>`
    }
  })
  .add('story 2', () => {
    const content = 'This one too!'
    return {
      template: `<button>${content}</button>`
    }
  })
```

**Comment by johntips** [comment]
👍

**Comment by Keraito** [comment]
Hey @qianqian05723, it's basically as @katrynmc 	said. The documentation on the `master` branch is for the `alpha` release of Storybook packages, while you're using the `3.4` release. The documentation for that stable release is on another branch: https://github.com/storybooks/storybook/tree/release/3.4/addons/background, where as mentioned by @katrynmc 	the addon-backgrounds still made use of a default export instead of a named one. Note that the `3.4` version of backgrounds [doesn't support vue](https://github.com/storybooks/storybook/blob/release/3.4/ADDONS_SUPPORT.md).
