### ISSUE TITLE
Error about no parser with prettier

### ISSUE THREAD

**Issue by stramel** [storybooks/storybook#4159]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Running this plugin is causing, `No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.`

### Steps to reproduce

Run this plugin with default `prettierConfig` and/or specify a custom `prettierConfig` without `parser`

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react ^3.4.10
- @storybook/addon-storysource ^3.4.10

It would be nice for it to read a prettier config file https://prettier.io/docs/en/configuration.html

Related #3681

**Comment by igor-dv** [comment]
I think it was fixed in v4.
