### ISSUE TITLE
Single Configuration File - A.K.A. storybook.config.js - monoconfig

### ISSUE THREAD

**Issue by igor-dv** [storybooks/storybook#4169]
_let's discuss the "Single Configuration File" feature_ 

I will update this template with the agreed changes. The inspiration is from [here](https://github.com/storybooks/SBNext/blob/master/examples/react/storybook.config.js)

## API
The `storybook.config.js` will be at a root level, but we also may consider it to be configurable with the cli argumetns (for example for people that will have a few configurations).

### structure
```ts
interface SbConfg {
  entries?: Array<string> | string
  addons?: Array<string>
  presets?: Array<string> | Array<object>
  webpack?: object | function
  babel?: object | funciton
};
```

#### `storybook.config.js` exposes an object
```ts
module.exports = SbConfg;
```

#### `storybook.config.js` exposes a fuction
```ts
module.exports = (env, mode) => SbConfg  // anything else ?
```

### entries
Let's not call this field `stories`, because semantics will maybe changed

#### globs:
```js
{
  entries: 'src/**/*.story.js'
}
```

#### array of globs:
```js
{
  entries: ['src/**/*.stories.js', 'src/**/*.examples.js']
}
```

#### path to file:
```js
{
  entries: 'path/to/stories.js' // it may have a `require.context` or something else
}
```

#### combination
```js
{
  entries: ['path/to/stories.js',  'src/**/*.stories.js']
}
```

- I am not sure, but maybe regex is also relevant.
- we should add a sensible default, so it will work without any configuration

### addons

An array of addons in the following structure:

```js
{
  addons: ['@storybook/addon-X', '@storybook/addon-Y']
}

```

We will register the addons by ourselves (no need of `addons.js`). The question is what to do with the addon's defaults, for example with what we setup today in `config.js` ? we can use the same pattern as in `presets` 🤷‍♂️ 

#### array of strings
```js
{
  presets: ['@storybook/preset-scss', '@storybook/preset-typescript']
}
```

#### array of objects
```js
{
  presets: [
    {
      preset: '@storybook/preset-scss',
      options: { }
    }
  ]
}
```

#### combination
```js
{
  presets: [
    {
      preset: '@storybook/preset-scss',
      options: { }
    },
    '@storybook/preset-typescript'
  ]
}
```

#### object
Will be merged to the final SB webpack config
```js
{
  webpack: {
    module: {
      rulese: []
    },
    // other stuff
  }
}
```

#### function
Like today, but we may change if something is redundnat
```js
{
  webpack: (config, mode. default) => {} 
}
```

### babel
same as for `webpack`

#### object
Will be merged to the final SB babel config
```js
{
  babel: {
    plugins: [],
    presets: []
  }
}
```

#### function
```js
{
  babel: (config, mode) => {} 
}
```

### things to cover
- global decorators. How we will set them ?
- there are apps that has a customisation of configuration, for example we support custom `tsconfig.json` to be set in `.storybook` dir, only for angular app. How we will configure this ? maybe with `presets` ? IDK
- RN

### deprecations:
- `./storybook` dir
- custom webpack.config.js
- custom babelrc
- addons.js
- config.js
- parts of the `@storybook/app` api, like a `configure` method, that is used in `config.js`

**Comment by pksunkara** [comment]
All the `client` part of @storybook/[apps] can be deprecated also, right?

**Comment by igor-dv** [comment]
Which one? I am not sure

**Comment by tmeasday** [comment]
Re configuring addons, client side:

>  we can use the same pattern as in presets 🤷‍♂️

Only if the config is static though. If you e.g. want to register a react class or something, this is going to be tricky via a config file evaluated on the server. Maybe this is mostly fine though?

**Comment by tmeasday** [comment]
Also, what about global parameters? Can we add that to the unknown's list @igor-dv? :)

**Comment by igor-dv** [comment]
Global parameters?

**Comment by tmeasday** [comment]
Sure, like 

```js
import { addParameters } from '@storybook/react';
addParameters({ ... });
```

**Comment by igor-dv** [comment]
I think it's just one of the entries

**Comment by tmeasday** [comment]
We are not doing this in v5

**Comment by ndelangen** [comment]
Working on this

**Comment by leoyli** [comment]
I'm having a customized story loader that will generate stories on the fly..., it will also do something like `addon-smart-knobs`.  Not sure if this can be done in the core or reserve an option entry to run customized scripts?!

**Comment by ndelangen** [comment]
@leoyli that's something presets should be able to do.

**Comment by backbone87** [comment]
it should still be possible to use a storybook dir:
- it has just no special meaning
- the configuration can be set via cli option: `--config ./path/to/storybook.config.js` (filename optional, so `--config ./path/to` would be the same)
- entries can be referenced in parent dirs: `../src/**/*.stories.ts` (relative to config file)

theme configuration, automatically gets passed through `theme.create`:
```
module.exports = {
  theme: {
    base: 'dark',
    brandImage: '???', // previously it was possible to use webpack image imports here
  },
  theme: 'dark',
}
```

favicon configuration (maybe should be an option of theme):
```
module.exports = {
  favicon: '???', // previously it was possible to use webpack image imports here
}
```

**Comment by leoyli** [comment]
Are #6806 overlapped with this old issue?!

**Comment by ndelangen** [comment]
@leoyli you are 💯% correct sir.

I have a WIP branch, which does things a little differently from what's described in this issue, but is addresses these points. 

I'll close this issue in favor of https://github.com/storybooks/storybook/issues/6806
