### ISSUE TITLE
How to use `constructor` in `.stories.js`?

### ISSUE THREAD

**Issue by SatoshiKawabata** [storybooks/storybook#4174]
# Proposal
I want to use `constructor` in `.stories.js` file like [`riot.tag` method](https://riot.js.org/api/#-riottagtagname-html-css-attrs-constructor).
Like below.
```js
return {
  tags: [{ content: SimpleTestRaw, boundAs: 'mustBeUniquePlease' }],
  template:
    '<SimpleTest test={ "with a parameter" } value={"value is mapped to riotValue"}></SimpleTest>',
  tagConstructor: function(opts) {
    // tag constructor here
  }
}
```
### Who to contact

@libetl

**Comment by libetl** [comment]
Hello.

**Comment by libetl** [comment]
as a workaround what you can do is to use { compileNow } from @storybook/riot, then to mount it with your opts.

for example compileNow('<my-tag><div>etc...</div></my-tag>')

and then return {tagName: 'my-tag', opts: { }}

I will think about your proposal and try to find the good way.

Thank you.

**Comment by libetl** [comment]
In the meantime, I have a better workaround for you @SatoshiKawabata 
Why don't you use tag & mount ?

https://storybooks-riot.netlify.com/?selectedKind=Story%7CHow%20to%20create%20a%20story&selectedStory=built%20with%20tag&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by SatoshiKawabata** [comment]
@libetl  Thank you for your response.

I want to get `this` of riot tag in `.stories.js`. [This way](https://storybooks-riot.netlify.com/?selectedKind=Story%7CHow%20to%20create%20a%20story&selectedStory=built%20with%20tag&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) is also good so we've tried it already. Can you implement it in riot addon? Or can we create PR?

**Comment by libetl** [comment]
https://github.com/storybooks/storybook/pull/4258/commits
