### ISSUE TITLE
Error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by hassanshaikley** [storybooks/storybook#4178]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Getting `Error: Plugin/Preset files are not allowed to export objects, only functions.` 

### Steps to reproduce

package.json

```
 "@babel/core": "^7.0.0",
    "@storybook/addon-actions": "^4.0.0-alpha.20",
    "@storybook/addon-links": "^4.0.0-alpha.20",
    "@storybook/addons": "^4.0.0-alpha.20",
    "@storybook/react": "^4.0.0-alpha.20",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.24.0",
    "babel-eslint": "^7.1.1",
    "babel-jest": "^19.0.0",
    "babel-loader": "7.1.5",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.24.1",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "react": "^16.4.1",
    "react-dom": "^16.5.0",
    "react-redux": "^5.0.2",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "css-loader": "^0.28.0",
    "webpack": "4.16.2",
    "webpack-cli": "^3.1.0",
    "webpack-dev-middleware": "^1.10.1",
    "webpack-hot-middleware": "^2.18.0"

```
.storybook/webpack.config.js
```
// you can use this file to add your custom webpack plugins, loaders and anything you like.
// This is just the basic way to add additional webpack configurations.
// For more information refer the docs: https://storybook.js.org/configurations/custom-webpack-config

// IMPORTANT
// When you add this file, we won't add the default configurations which is similar
// to "React Create App". This only has babel loader to load JavaScript.

module.exports = {
  plugins: [
    // your custom plugins
  ],
  module: {
    rules: [
      // add your custom rules.
      {
        test: /\.(mov|mp4|jpg)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]'
            }  
          }
        ]
      },
      {
        test: /\.svg$/,
        use: 'url-loader?mimetype=image/svg+xml',
        exclude: /node_modules/
      }
      
    ],
  },
};

```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react: "^4.0.0-alpha.20"
- @storybook/addon-something: "^4.0.0-alpha.20" <-- it's that version for all of em

### Affected platforms 

MacOS

Thank you

**Comment by igor-dv** [comment]
If you are using `@babel/core` (which is v7), you should use `babel-loader` v8. And probably `babel-core` bridge because of jest.

**Comment by JiiB** [comment]
@hassanshaikley any news?

I get the same error. In my app the `babel-preset-react-app` package seems do be the problem. I'm still searching for a solution.

**Comment by igor-dv** [comment]
Did you try to do what I wrote?

**Comment by Hypnosphi** [comment]
@hassanshaikley why do you have `@babel/core` dependency? Looks like all your plugin and preset dependencies are for babel 6

**Comment by Hypnosphi** [comment]
@JiiB please try `babel-preset-react-app@canary`

**Comment by JiiB** [comment]
@Hypnosphi Thanks for your reply but unfortunately is still get the same error. 

### Error:
`Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/jiib/Documents/rasch-stack/node_modules/babel-preset-stage-0/lib/index.js
`

I checked my `yarn.lock` file and searched for `babel-preset-stage-0`. Storybook is the only package that depends on `babel-preset-stage-0`

I'm using `@storybook/react@^3.4.10` btw

**Comment by Hypnosphi** [comment]
> I'm using `@storybook/react@^3.4.10`

Do you have a dependency on `babel-core@bridge`?

**Comment by hassanshaikley** [comment]
@JiiB I eventually downgraded storybook & webpack

**Comment by igor-dv** [comment]
I am closing this since there are no action items from this issue. Let us know if any help needed.

**Comment by kevbost** [comment]
I ran into this while running a simi-standalone storybook app with a create-react-app base. 

I added a .babelrc -- received the `not allowed to export objects` error with `npm run storybook`, and used this solution from SO to resolve it:
https://stackoverflow.com/a/49183337/3864870

`prev .babelrc`
```json
{
  "presets": ["react"],
  "plugins": [
    "transform-object-rest-spread"
  ]
}
```

`updated .babelrc`
```json
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```
