### ISSUE TITLE
Broken with react-native@0.57 due to packager (local-cli) API change 

### ISSUE THREAD

**Issue by mgcrea** [storybooks/storybook#4179]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Bug

### Steps to reproduce

On a fresh project (`react-native init`):

```
$ yarn storybook
yarn run v1.9.4
$ storybook start -p 7007
=> Loading custom .babelrc from project directory.
=> Loading custom addons config.
=> Using default webpack setup based on "Create React App".
Scanning 1172 folders for symlinks in /Users/olivier/Projects/joonca/joonca-components/node_modules (12ms)

React Native Storybook started on => http://localhost:7007/


  error: unknown option `--projectRoots'

webpack built 91ec773834c48e7f9dab in 2184ms
Hash: 91ec773834c48e7f9dab
Version: webpack 3.12.0
Time: 2184ms
```

And another error after that:

```
ERROR in ./storybook/addons.js
Module build failed: Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "/Users/olivier/Projects/joonca/joonca-components/storybook"
```

Looks like this commit is the culprit:

https://github.com/facebook/react-native/commit/c5ce7626977a7650e8dce335f2ce78b94839a2a8#diff-4a892a6b8856f0253e2de7094e585ae6

### Please specify which version of Storybook and optionally any affected addons that you're running

```
    "@storybook/addon-actions": "^3.4.10",
    "@storybook/addon-links": "^3.4.10",
    "@storybook/addons": "^3.4.10",
    "@storybook/react-native": "^3.4.10",
```

### Affected platforms 

react-native

**Comment by resting** [comment]
Getting the same error.
Works with RN v0.55.4 though.

**Comment by jacquesdev** [comment]
This worked for me https://github.com/facebook/react-native/issues/20876

**Comment by cball** [comment]
@jacquesdev mind providing more detail on the steps you took? I was able to get a project to build correctly using storybook v4.0.0-alpha.21, `.babelrc.js` and explicitly requiring `metro-react-native-babel-preset` but Storybook didn't seem to function correctly after that.

**Comment by kdawgwilk** [comment]
@cball I am in the same situation as you. I can get things to build correctly with `v4.0.0-alpha.21` but the packager doesn't appear to run and so the simulator just gives me a `No bundle URL present` red screen

**Comment by griable** [comment]
Based on @jacquesdev comment, I followed this [recommandation](https://github.com/facebook/react-native/issues/20876#issuecomment-422555476).

I got it working by adding those two dependencies:

- "@babel/core": "7.1.0",
- "babel-core": "7.0.0-bridge.0",

**Comment by Amurmurmur** [comment]
@griable +1

**Comment by matheuscouto** [comment]
@griable +1

**Comment by K-Eo** [comment]
I have the same issue with a fresh react-native app. As @griable said on changing `babel-core` to `7.0.0-bridge.0` fixes metro module error and I can run the server but the Storybook UI doesn't show any component.

**Comment by robwalkerco** [comment]
@K-Eo If you run storybook with the `--skip-packager` option, you can continue to use the normal react-native packager that you app uses, and then
`import StorybookUI from '../storybook/storybook'`
add `<StorybookUI />` as a Component in your app to view it. 

I was able to get it working that way, so hopefully it will work ok for you too... 
(Also, see https://github.com/storybooks/storybook/pull/4196)

**Comment by Gongreg** [comment]
Hello everyone,
Regarding this issue use `--skip-packager` command when starting the storybook server.

Then use 

```

import { getStorybookUI } from '@storybook/react-native';

const StorybookUIRoot = getStorybookUI();
```

And somewhere in your app (a separate screen, admin panel, anything) render the StorybookUIRoot

```
class YourScreen extends Component {
  render() {
    return (
      <View>
        <StorybookUIRoot />
      </View>
    );
  }
}

```

I hope this helps.
We want to remove the packager completely (since it is bringing a lot of unnecessary issues), but I am away for some time.

Sorry that something is not working, we will update the docs explaining the issue.

**Comment by robwalkerco** [comment]
@sinewave440hz 
I have `metro-react-native-babel-preset` as a devDependency in package.json
I also have `"presets": ["module:metro-react-native-babel-preset"]` in `.babelrc`

**Comment by sinewave440hz** [comment]
Sorry, my mistake. I re-read the thread and realised I had missed upgrading the babel packages. All up and running now, thanks.

**Comment by petrbela** [comment]
If you don't want to include StorybookUI in your main app and want to continue to use the old standalone behavior, change the npm script to:

```js
"storybook": "storybook start -p 7007 --skip-packager | react-native start --projectRoot storybook",
```

**Comment by Gongreg** [comment]
@petrbela, you are completely correct, this is what we will suggest for people who want to use old behaviour.

**Comment by chawax** [comment]
Thanks @petrbela , your solution worked for me, Storybook now starts and can be used on device and simulator.

Anyway I can't make it work from the browser (which is the only solution if you use `actions` plugin for example). I have the following error in my browser console when opening `http://localhost:7007` :

```
app.js?f275:131 Uncaught TypeError: Cannot set property '_currentValue' of undefined
    at popProvider (react-dom.development.js?61bb:10977)
    at replayUnitOfWork (react-dom.development.js?61bb:11214)
    at renderRoot (react-dom.development.js?61bb:11773)
    at performWorkOnRoot (react-dom.development.js?61bb:12318)
    at performWork (react-dom.development.js?61bb:12239)
    at performSyncWork (react-dom.development.js?61bb:12216)
    at requestWork (react-dom.development.js?61bb:12116)
    at scheduleWorkImpl (react-dom.development.js?61bb:11991)
    at scheduleWork (react-dom.development.js?61bb:11951)
    at scheduleRootUpdate (react-dom.development.js?61bb:12579)
```

Anyone has an idea what causes this error ?

**Comment by chawax** [comment]
I found my problem. I had forgotten to change `react-dom` dependency to `16.5.0`, the same release as the one required by React Native 0.57.2 !

**Comment by lasersox** [comment]
I have followed the instructions here and resolved the metro bundler error, as well as upgraded babel and storybook packages.

Stuck on ```ERROR in ./storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/lasersox/Projects/pyggybank-app/src/app/storybook/addons.js: .comments is not a valid Plugin property
    at Object.keys.forEach.key (/Users/lasersox/Projects/pyggybank-app/src/app/node_modules/@babel/core/lib/config/validation/plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/lasersox/Projects/pyggybank-app/src/app/node_modules/@babel/core/lib/config/validation/plugins.js:50:20)
    at instantiatePlugin (/Users/lasersox/Projects/pyggybank-app/src/app/node_modules/@babel/core/lib/config/full.js:209:21)
    at cachedFunction (/Users/lasersox/Projects/pyggybank-app/src/app/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPluginDescriptor (/Users/lasersox/Projects/pyggybank-app/src/app/node_modules/@babel/core/lib/config/full.js:200:10)
    at config.plugins.reduce (/Users/lasersox/Projects/pyggybank-app/src/app/node_modules/@babel/core/lib/config/full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/lasersox/Projects/pyggybank-app/src/app/node_modules/@babel/core/lib/config/full.js:67:38)
    at loadFullConfig (/Users/lasersox/Projects/pyggybank-app/src/app/node_modules/@babel/core/lib/config/full.js:66:21)
 @ multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js manager[0]
```

Anybody else see this error?

**Comment by jjenzz** [comment]
I've done what @petrbela suggested to run storybook standalone and updated `babel-core` to `7.0.0-bridge.0`. 

The server starts fine now but when I try to run `$ react-native run-ios` I get a module resolution error for `react-transform-hmr` because it is trying to look for it within `./storybook/node_modules/react-transform-hmr` when it exists further up the tree. I don't suppose anyone knows how to fix this? 🙈 I realise I'm hijacking this thread a bit but my googling hasn't helped.

**Comment by chawax** [comment]
I had this problem and I solved it by making this change in `node_modules/metro/src/reactNativeTransformer.js`

```
const hmrConfig = makeHMRConfig(options, filename);
    const hmrConfig = makeHMRConfig(
      options,
      path.resolve(options.projectRoot, filename),
 );
```

If it works, you can use `patch-package` to create a patch and apply it on every `npm install`

**Comment by jjenzz** [comment]
@chawax Thank you! Looks like I have `metro@0.47.0` and this was fixed in `0.48.0`: https://github.com/facebook/metro/commit/e595178fc859263cc2d88de08650d99c52bcc0d9

**Comment by Gongreg** [comment]
@ndelangen, What do we do with this task? Do we close it after 4.0?

**Comment by esbenvb** [comment]
@petrbela your trick does not work with a version `0.57.0` of RN.

By looking at the source, it seems like the `--projectRoot` option is documented and validated but the usage of the provided value is not implemented. In `0.57.3` it works. 
https://github.com/facebook/react-native/compare/v0.57.0...v0.57.3#diff-33a4be2928925650375f54b552cb956f

Maybe that should be mentioned in your comment with the workaround :)

**Comment by Gongreg** [comment]
v4.0 is being released today. With it the packager is removed from storybook.

**Comment by princiya** [comment]
@Gongreg the above link is broken. could you please update to the right one https://medium.com/storybookjs/whats-new-in-storybook-4-0-react-native-741c7f481bbb. Thank you.

**Comment by Gongreg** [comment]
Thanks @princiya, fixed.

**Comment by hayanisaid** [comment]
I tried all the solutions above this is the only solution that solved my problem : 

```
 "  @babel/core": "^7.0.0-beta",
    "babel-core": "^7.0.0-beta",
    "babel-runtime": "^7.0.0-beta",
```
Reference (here)[https://github.com/storybooks/storybook/issues/3897]
