### ISSUE TITLE
storybook with vuejs is not processing correctly for vue component with jsx render method

### ISSUE THREAD

**Issue by adamchenwei** [storybooks/storybook#4188]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
I created a repo to experiment writing vue with jsx and load it into storybook, but its not working properly. I am not sure what I need to add to fix it. 
It generates error of `Module build failed: SyntaxError: Unexpected token (19:6)` for returned template in render function for a vuejs component.

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

### Steps to reproduce

1. clone https://github.com/adamchenwei/vuejs-storybook
2. npm install && npm run storybook
3. see error when you navigated to Banner component and in log when build

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue `^3.2.16`

### Affected platforms 

Mac OS

### Screenshots / Screencast / Code Snippets (Optional)

![screen shot 2018-09-17 at 12 31 21 pm](https://user-images.githubusercontent.com/4201698/45636719-7b291f80-ba76-11e8-96ac-ed15ce255fd3.png)

**Comment by Mactaivsh** [comment]
I met this problems too.

**Comment by adamchenwei** [comment]
its a problem still need to be resolved

**Comment by igor-dv** [comment]
Have you tried the v4?

**Comment by backbone87** [comment]
seems like a problem with your project setup, pls try vue-cli 3 + vue-cli-plugin-storybook
