### ISSUE TITLE
Build-storybook in docker yields no files

### ISSUE THREAD

**Issue by sztrzask** [storybooks/storybook#4197]
### Bug or support request summary

When trying to build storybook within docker, the output folder contains only favicon, without any actual static files.

### Steps to reproduce

Create minimal docker setup. Create CRA app with storybook from cli.

Create following Dockerfile
```
FROM node:10-alpine
RUN mkdir /dockerbook
COPY ./ /dockerbook
WORKDIR /dockerbook

RUN npm run build-storybook
```

### Please specify which version of Storybook and optionally any affected addons that you're running

  "@storybook/react": "4.0.0-alpha.21"

### Acceptance criteria

Either build-storybook fails with error or either it creates static files.

**Comment by dangreenisrael** [comment]
When I try using this dockerfile and then running `docker ps` I see no running containers. This is (I think) because the docker container exits when it finished `RUN npm run build-storybook`. 

Were you able to shell into the container and verify that the files weren't there or were you looking on your local machine?

**Comment by dangreenisrael** [comment]
After adding `CMD tail -f /dev/null` to the end of the docker file (just to keep it running) I was able to SSH in and verify that the files are there:

<img width="1327" alt="screen shot 2018-09-22 at 3 50 15 pm" src="https://user-images.githubusercontent.com/4509692/45921199-46a2d280-be7f-11e8-9ac0-02c211b739a7.png">


<details><summary>My `package.json`</summary>
<p>
<pre>
{
  "name": "temp-react-storybook",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-scripts": "1.1.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "devDependencies": {
    "@storybook/react": "^4.0.0-alpha.22",
    "@storybook/addon-actions": "^4.0.0-alpha.22",
    "@storybook/addon-links": "^4.0.0-alpha.22",
    "@storybook/addons": "^4.0.0-alpha.22",
    "@babel/core": "^7.1.0",
    "babel-loader": "^8.0.2"
  }
}
</pre>
</p>
</details>

<details><summary>My `dockerfile`</summary>
<p>
<pre>
FROM node:10-alpine
RUN mkdir /dockerbook
COPY ./ /dockerbook
WORKDIR /dockerbook
RUN npm run build-storybook
CMD tail -f /dev/null
</pre>
</p>
</details>

**Comment by dangreenisrael** [comment]
@sztrzask Can you provide other steps to reproduce this issue?

**Comment by sztrzask** [comment]
@dangreenisrael

Huh, this certainly is weird.

I have a Linux based TFS agent. I can only say that if I try to run the `build-storybook` the files are not created on that specific machine. I did shelled into container and verified the files are not there - even went so far as adding extra build step to list them after the `RUN npm... ` step.

The same dockerfile run on Windows with Docker for Windows creates the files. 

Unless this information helps with investigation, please close the issue.

**Comment by dangreenisrael** [comment]
Is this happening during a CI pipeline?
