### ISSUE TITLE
logic as standalone npm module

### ISSUE THREAD

**Issue by Xiphe** [storybooks/storybook#42]
I really love the idea of building a DSL for state mutations. Since this comes as a standalone application it's not possible to integrate it in existing pattern lab solutions. (And I would really like to do that, instead of reinventing the wheel here ;)

So any plans to distribute the logic as a standalone npm module without the UI?

**Comment by arunoda** [comment]
What you you mean by the logic? The UI is core part of Storybook.
Could you add more information a bit.

**Comment by Xiphe** [comment]
We already have an application that provides a visual overview for all our patterns. I do not want to setup another tool that provides the same thing with just another featureset.

here would be an imaginary flow on how to use the logic of this project in my application:

`npm install react-storybook --save`

```js
// my-stories.js
// ...
import { storiesOf } from '@kadira/storybook';

storiesOf('Button', module)
// register stories...
```

```js
// navigation.js
// ...
import { storiesOf } from '@kadira/storybook';

storiesOf('Button').forEach(story => /* my implementation of rendering a nav-entry */);
```

```jsx
// view.jsx
// ...
import { StoryView } from '@kadira/storybook';

<MyPatternlab>
  <MyNavigation></MyNavigation>
  <StoryView for=currentStory></StoryView>
</MyPatternlab>
```

This way I could use this as a less opinionated subcomponent in my own solution.

**Comment by arunoda** [comment]
Okay got it. Good idea.

**Comment by ndelangen** [comment]
Storybook stories are extractable see for example how storyshots is doing it:
https://github.com/storybooks/storybook/blob/master/addons/storyshots/src/index.js#L61
