### ISSUE TITLE
All addon's config is coming in one tile

### ISSUE THREAD

**Issue by gmukul01** [storybooks/storybook#4200]
### Bug 

All addon's config is coming in one tile

![image](https://user-images.githubusercontent.com/3636885/45731552-bf8ef980-bbf5-11e8-97b5-6620820fdbee.png)

### Version of Storybook and addon, i have used

- @storybook/addon-actions": "^3.4.10"
- @storybook/addon-info": "^3.4.10"
- @storybook/addon-knobs": "^3.4.11"
- @storybook/addon-options": "^3.4.10"
- @storybook/addon-viewport": "^3.4.11"
- @storybook/addons": "^4.0.0-alpha.2"
- @storybook/react": "^4.0.0-alpha.3"
- @types/enzyme": "^3.1.13"
- @types/jest": "^23.3.2"
- @types/react": "^16.4.13"
- @types/react-test-renderer": "^16.0.2"
- @types/storybook__addon-actions": "^3.4.1"
- @types/storybook__addon-info": "^3.4.2"
- @types/storybook__addon-knobs": "^3.4.1"
- @types/storybook__react": "^3.0.9"
- @types/styled-components": "^3.0.0"

### Code Snippets 

```js
Storybook config file
import { setOptions } from "@storybook/addon-options";
import { configure, setAddon, addDecorator } from "@storybook/react";
import infoAddon, { setDefaults } from "@storybook/addon-info";
import { withKnobs } from "@storybook/addon-knobs/react";
import { withThemesProvider } from "storybook-addon-styled-component-theme";

//Theme Addon
import { SingaporeTheme, TaiwanTheme } from "../src";
const themes = [SingaporeTheme, TaiwanTheme];
addDecorator(withThemesProvider(themes));

//Adding Knobs addon
addDecorator(withKnobs);

//Set option for story book
setOptions({
  name: "Component Library",
  addonPanelInRight: true
});

//Set default parameters for withinfo addon
setDefaults({
  inline: true,
  header: false,
  source: true,
  maxPropsIntoLine: 1
});

//Load all stories
const req = require.context("../stories", true, /.stories.tsx?$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

setAddon(infoAddon);

configure(loadStories, module);
```

```js
Addon File
import "@storybook/addon-options/register";
import "storybook-addon-styled-component-theme/dist/register";
import "@storybook/addon-knobs/register";
import "@storybook/addon-viewport/register";
import "@storybook/addon-actions/register";

```

**Comment by alex-fournier** [comment]
To avoid this, each addon should be aware of the `active` prop sent by Storybook and only render addon when `active` is `true`.

Example for Notes addon: https://github.com/storybooks/storybook/blob/master/addons/notes/src/register.js#L84

Storybook doc should be updated as it is not mentioned here: https://storybook.js.org/addons/writing-addons/#the-addon

I don't know if this is the correct solution to your issue but in my case, this solved my problem.

**Comment by gabrielcsapo** [comment]
We definitely should add this to the addon doc

**Comment by gmukul01** [comment]
make addon aware of active prop so storybook renders in its own panel #3,  this solved the problem of theme addon but others are still issue for me.

**Comment by gmukul01** [comment]
@gabrielcsapo  could you please tag someone from knobs team to fix this issue in their code aswell.
Below is the code which worked for me in register file of knob addon:
render: function render({ active }) {
      return active ? _react2.default.createElement(_Panel2.default, { channel: channel, api: api, key: "knobs-panel" }) : null;
    }
