### ISSUE TITLE
Publishing broken in Lerna 3

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#4204]
Publishing `4.0.0-alpha.22` in master. All the packages got published properly (AFAIK), but the overall command failed, due to this line in `package.json`:

```
  "workspaces": [
    ...
    "lib/cli/test/run/*"
  ],
```

Here's the log:
 
```
> npm run publish:alpha
...
lerna info published @storybook/react 4.0.0-alpha.22
lerna info published @storybook/riot 4.0.0-alpha.22
lerna info published @storybook/svelte 4.0.0-alpha.22
lerna info published @storybook/vue 4.0.0-alpha.22
lerna ERR! Error: Command failed: git checkout -- lib/cli/test/run/*/package.json
lerna ERR! error: pathspec 'lib/cli/test/run/*/package.json' did not match any file(s) known to git.
lerna ERR!
lerna ERR!     at makeError (/Users/shilman/projects/storybook/new/storybook/node_modules/@lerna/child-process/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/Users/shilman/projects/storybook/new/storybook/node_modules/@lerna/child-process/node_modules/execa/index.js:278:16)
lerna ERR!     at <anonymous>
lerna ERR! lerna Command failed: git checkout -- lib/cli/test/run/*/package.json
lerna ERR! lerna error: pathspec 'lib/cli/test/run/*/package.json' did not match any file(s) known to git.
lerna ERR! lerna
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @storybook/root@4.0.0-alpha.16 publish: `lerna publish --exact --concurrency 1 --force-publish "--npm-tag=alpha"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @storybook/root@4.0.0-alpha.16 publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shilman/.npm/_logs/2018-09-19T21_06_12_244Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @storybook/root@4.0.0-alpha.16 publish:alpha: `npm run publish -- --npm-tag=alpha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @storybook/root@4.0.0-alpha.16 publish:alpha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shilman/.npm/_logs/2018-09-19T21_06_12_309Z-debug.log
```

I believe this is related to:
- the CLI smoke tests by @igor-dv https://github.com/storybooks/storybook/commit/c5f54338a2e4bd65e1be09eedb4f692f86df0edf
- the upgrade to lerna@3 by @pksunkara https://github.com/storybooks/storybook/commit/2ccedd66c97b0c7802a1e3c966a5bc9ce8b46b3d

I don't understand the CLI side well enough to guess what the fix might be 😄

**Comment by shilman** [comment]
See also: https://github.com/lerna/lerna/issues/1602

Thanks @Hypnosphi !

**Comment by pksunkara** [comment]
We don't need to duplicate the packages information in lerna.json. We can add an ignore option for publish configuration.

**Comment by Hypnosphi** [comment]
> We can add an ignore option for publish configuration

And hope that this check comes before the one that causes the failure =)

**Comment by pksunkara** [comment]
Did some research. There's no ignore option for publish, and putting `packages` in lerna.json won't work if we still want to use yarn workspaces. A better way of fixing this issue would be to edit the testing script to write this line to package.json when testing.

**Comment by Hypnosphi** [comment]
> won't work if we still want to use yarn workspaces

What do you mean? We don't use `lerna bootstrap` command, we just `yarn install` directly. How can the latter be affected by `lerna.json`?

**Comment by pksunkara** [comment]
I mean, `lerna` won't respect `packages` in lerna.json when we are using yarn workspaces. https://github.com/lerna/lerna/blob/62843b04e3a5a03012ceabe465519b39a09fbcc1/core/project/index.js#L73

**Comment by Hypnosphi** [comment]
The long-term solution is to make https://github.com/storybooks/storybook/blob/master/scripts/run-e2e.sh work
CC @ndelangen

**Comment by pksunkara** [comment]
Yeah, to finalize the discussion, these are the possible solutions:

1. Remove `useWorkspaces` and add `packages` in lerna.json
2. Fix run-e2e.sh

**Comment by shilman** [comment]
I've been ignoring this failure on every release but it's still a problem. @pksunkara how complicated is the fix to `run-e2e.sh`?

**Comment by Hypnosphi** [comment]
@ndelangen should know better

**Comment by shilman** [comment]
Publishing is working smoothly again

**Comment by pksunkara** [comment]
How was this fixed
