### ISSUE TITLE
React Native Vector Icons don't load on react-native-web storybook

### ISSUE THREAD

**Issue by selipso** [storybooks/storybook#4208]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
I'm trying to add react-native-vector-icons as a font to my react-native-web project using storybook. I followed the instructions on react-native-vector-icons for web and was able to get the icons to show up in my project. However, they don't show up in my storybook even though I added the same configuration to the storybook's `webpack.config.js` and `config.js`. The icon shows up as a black square instead or gives the following error:

```
ERROR in ./node_modules/react-native-vector-icons/Fonts/FontAwesome.ttf
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

### Steps to reproduce
1. Create a new project with CRNA and web support using the following command in the terminal: `create-react-native-app my-app --with-web-support`

2. Add storybook using `getstorybook`

3. Install react-native-vector-icons `yarn add react-native-vector-icons@5`

4a. Configure webpack on the main repo to read TTF files. Mine has a section like the following:
```js
const ttfLoaderConfiguration = {
  test: /\.ttf$/,
  use: [
    {
      loader: 'file-loader',
      options: {
        name: './fonts/[hash].[ext]',
      },
    },
  ],
  include: [
    path.resolve(appDirectory, './src/assets/fonts'),
    path.resolve(appDirectory, 'node_modules/react-native-vector-icons'),
  ],
};
```

4b. Configure webpack in the .storybook hidden directory. Mine looks like the following:
```js
const path = require("path");

module.exports = (storybookBaseConfig, configType) => {
  storybookBaseConfig.resolve = {
    modules: ["node_modules"],
    extensions: [".web.js", ".js", ".json", ".web.jsx", ".jsx"],
    alias: {
      "react-native": "react-native-web"
    }
  };

  storybookBaseConfig.module.rules.push({
    test: /\.ttf$/,
    loader: "url-loader", // or directly file-loader
    include: path.resolve(__dirname, "node_modules/react-native-vector-icons"),
  });

  return storybookBaseConfig;
};
```

5a. Load the font in the main project by injecting CSS. My `index.js` (javascript entry point for web) looks like the following:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

// Generate required css
import iconFont from 'react-native-vector-icons/Fonts/FontAwesome.ttf';
const iconFontStyles = `@font-face {
  src: url(${iconFont});
  font-family: FontAwesome;
}`;

// Create stylesheet
const style = document.createElement('style');
style.type = 'text/css';
if (style.styleSheet) {
  style.styleSheet.cssText = iconFontStyles;
} else {
  style.appendChild(document.createTextNode(iconFontStyles));
}

// Inject stylesheet
document.head.appendChild(style);

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

5b. (optional) Configure storybook entry point at `.storybook/config.js` with a similar code snippet. Mine looks like the following:

```js
import { configure } from '@storybook/react';
// Generate required css
const iconFont = require('react-native-vector-icons/Fonts/FontAwesome.ttf');
const iconFontStyles = `@font-face {
  src: url(${iconFont});
  font-family: FontAwesome;
}`;

// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /.stories.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);

// Create stylesheet
const style = document.createElement('style');
style.type = 'text/css';
if (style.styleSheet) {
  style.styleSheet.cssText = iconFontStyles;
} else {
  style.appendChild(document.createTextNode(iconFontStyles));
}

// Inject stylesheet
document.head.appendChild(style);
```

6. Try adding icons to storybook and main project using react native vector icons and FontAwesome.
```js
import FAIcon from 'react-native-vector-icons/dist/FontAwesome';
...
render(){
  return <FAIcon name="plus" /> // works fine in App
}
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.10
- @storybook/addon-links 3.4.10
- @storybook/addon-actions 3.4.10
- @storybook/react-native 3.4.10
- react-native-vector-icons 5.0.0
- react-native-web 0.8.0

### Affected platforms 

- React Native Web

**Comment by igor-dv** [comment]
There is this line in your step `4b` 

```js
include: path.resolve(__dirname, "node_modules/react-native-vector-icons"),
```

Does it mean that `node_modules` are located in your `.storybook` dir?

**Comment by selipso** [comment]
No, the node module folder is one level up from the src, same standard
setup as CRNA

**Comment by selipso** [comment]
Ah whoops! This seems to work, thanks!

**Comment by Angelk90** [comment]
Hi @selipso, can I ask you how you did it, I'm not getting it to work.
What webpack configuration are you using?
