### ISSUE TITLE
How to get storybook dark styles as shown in React example?

### ISSUE THREAD

**Issue by actraiser** [storybooks/storybook#4210]
Sorry if this is obvious but I could not find any resource on how to switch my Storybook project to the dark theme as used in [the official Example](https://storybooks-official.netlify.com/). I use Storybook 4.0.0-alpha.22.

Pointer on how to configure the theme would be appreciated.

Greets
-act

**Comment by Keraito** [comment]
Hey @actraiser, the repo and configuration for the official Storybook example can be found here: https://github.com/storybooks/storybook/blob/master/examples/official-storybook/config.js. It also includes the code necessary to get the dark theme

**Comment by actraiser** [comment]
Much appreciated, thanks for the link! I will have a look and eventually open a PR for the docs.

Greets
-act

**Comment by smks** [comment]
I tried adding in the config and the theme is not working.

```javascript
import { addDecorator, configure } from "@storybook/react";
import { themes } from "@storybook/components";
import { withOptions } from "@storybook/addon-options";

addDecorator(
  withOptions({
    theme: themes.dark
  })
);

function loadStories() {
  require("../src/stories");
}

configure(loadStories, module);
```

**Comment by Keraito** [comment]
@smks Could you make a new issue and describe your context (like package versions) in slightly more detail? That way we can help you better

**Comment by spencersmb** [comment]
@Keraito I'm having same issue as @smks using the same config setup except I'm using typescript.

My package versions are:
"@storybook/addon-actions": "^4.0.9",
    "@storybook/addon-info": "^4.0.9",
    "@storybook/addon-links": "^4.0.9",
    "@storybook/addon-options": "^4.0.10",
    "@storybook/components": "^4.0.10",
    "@storybook/react": "^4.0.9"

Let me know what else would help if anything.

**Comment by Ziv-Barber** [comment]
Not working also here. I added the same code to the config.js file as on the docs.
I do have import '@storybook/addon-options/register' on my addon.js file.

On my package.json I have:

```
    "@storybook/addon-actions": "^4.1.13",
    "@storybook/addon-links": "^4.1.13",
    "@storybook/addon-options": "^4.1.13",
    "@storybook/addons": "^4.1.13",
    "@storybook/react": "^4.1.13",
```

It looks like the documentation is not updated with the last theme interface.

**Comment by supasole9** [comment]
I had to update my storybook and it worked.

**Comment by LazaroOnline** [comment]
Also remember it is needed to call `addParameters()` before calling `configure()`
```js
addParameters({
options: {
	theme: themes.dark,
	// ...
	}
})

configure(...)
```
