### ISSUE TITLE
Storybook CLI not runnable from npx

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#4212]
## why
When I run the following commands (in `@4.0.0-alpha.22`), it should install Storybook:

```
npx create-react-app my-app
cd my-app/
npx @storybook/cli@alpha storybook init
```

What it actually does is run `getstorybook` and fails midway through:
```
MMBP:my-app $ npx @storybook/cli@alpha storybook init
npx: installed 419 in 12.661s
WARNING: getstorybook is deprecated.
The official command to install Storybook from now on is:

   storybook init


 storybook init - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "Create React App" based project
```

Note that the following works:
```
npx -p @storybook/cli@alpha storybook init
```

## what
- [ ] `npx @storybook/cli@alpha` should run `storybook` instead of `getstorybook`
- [ ] `getstorybook` should either exit after deprecation warning or run to completion

**Comment by Keraito** [comment]
what does the `-p` flag do?

**Comment by Keraito** [comment]
Could it be possible that the first issue is caused by the order in https://github.com/storybooks/storybook/blob/master/lib/cli/package.json#L23?
