### ISSUE TITLE
build-storybook not exiting after build completes

### ISSUE THREAD

**Issue by nelsonomuto** [storybooks/storybook#4217]
### Bug or support request summary
- Running build-storybook works but does not exit the process making it impossible to proceed to in a CI process or script.

### Steps to reproduce

- Run 
`npx build-storybook`

<img width="246" alt="screen shot 2018-09-22 at 9 21 32 am" src="https://user-images.githubusercontent.com/1546207/45919361-f6108280-be48-11e8-9dbb-3f9682d651e0.png">

### Please specify which version of Storybook and optionally any affected addons that you're running
- Current alpha version
- master branch

### Affected platforms 
All

### Acceptance criteria

When the build-storybook script completes it should exit

**Comment by contra** [comment]
@nelsonomuto Did you find a solution for this? Hitting the same thing.

**Comment by JBusch** [comment]
Same Problem here. Node 12.16.1 on Windows.
