### ISSUE TITLE
Add Storybook to Next.js with Styled JSX Sass Plugin

### ISSUE THREAD

**Issue by Jauny** [storybooks/storybook#4227]
Hi all! I seem to have trouble adding Storybook into a Nextjs project, and don't seem to find any documentation on it.

### Bug or support request summary

Can't make storybook work with a new next.js app when Sass is added

Getting the following error when running `yarn run storybook`
```
ERROR in ./.storybook/config.js
Module build failed: Error: Plugin 0 specified in "<root_dir>/node_modules/next/babel.js" provided an invalid property of "default" (While processing preset: "<root_dir>/node_modules/next/babel.js")
```

### Steps to reproduce

Setup a new Next.js project, add https://github.com/giuseppeg/styled-jsx-plugin-sass then follow the @storybook/react setup steps.
You don't need to create and import a component, simply setting up a basic story rendering an empty `<div>` will be enough.

I have `.babelrc` copied both in the root directory and in `.storybook` folder:
```
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": [
            "styled-jsx-plugin-sass"
          ]
        }
      }
    ]
  ]
}
```

It seems like the issue might come from the addition of a custom .babelrc file, but I can't find clear documentation on how to have Storybook work once this is done.

### Please specify which version of Storybook and optionally any affected addons that you're running

"@storybook/react": "^3.4.11"

### Affected platforms 

I'm on Mac OS X

### Acceptance criteria

[ ] This should get closed once Storybook React is able to work in a Nextjs app

### Who to contact

You can contact me directly, jypepin@gmail.com

**Comment by ndelangen** [comment]
Could you try the latest alpha? I think you're hitting a babel7 incompatibility maybe?

the alpha release uses webpack 4 and Babel 7.

**Comment by Jauny** [comment]
Didn't try to latest alpha but Webpack 3 was the issue. I added webpack 4 as a hard dependency in my package.json and it fixed the issue.

Thanks!
