### ISSUE TITLE
Decorator gets added multiple times

### ISSUE THREAD

**Issue by sdussaut** [storybooks/storybook#4233]
Hello!
Thanks for all the work done on Storybook, it's amazing!

### Bug summary
When adding a decorator to wrap the story in the preview iframe, the decorator gets added multiple times.

### Steps to reproduce

WrapperElement is a Vue component that has the following template:

```html
<div class="wrap">
   <slot/>
</div>
```

Adding it to wrap a story in it:
```js
storiesOf('Button', module)
  .addDecorator(WrapperElement)
  .add('Default', () => ({
    components: { MyButton },
    template: '<MyButton>My button</MyButton>'
  }));
```

I get:

```html
<div class="wrap">
   <div class="wrap">
      <div class="wrap">
         <button>My button</button>
      </div>
   </div>
</div>
```

instead of:

```html
<div class="wrap">
   <button>My button</button>
</div>
```

I use @storybook/vue 4.0.0.alpha22. This bug also happens if I use the centered addon or if I add the decorator globally for all my stories.
Am I missing something?

Thanks!

**Comment by ndelangen** [comment]
@sdussaut that should not be happening, definitely a bug

**Comment by abilicz** [comment]
I created a PR for this issue in #4846.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybooks/storybook/releases/tag/v4.2.0-alpha.6 containing PR #5057 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
