### ISSUE TITLE
Speeding up Storybook runtime

### ISSUE THREAD

**Issue by theKashey** [storybooks/storybook#4235]
## Background
We are using storybook to present our components and pages in different states, to make our dev cycle easier, and also to be able to capture screenshots.

For the first time we have used (storybook-chrome-screenshot)[https://github.com/tsuyoshiwada/storybook-chrome-screenshot] by @tsuyoshiwada, which just opens storybook in puppeteer and shot it, but run into several performance issues, like #4145, as long switching stories in a hard operation :(
> Speed - 3 minutes to capture 200 stories.

After that we switched to another solution (not yet public), which opens stories in a `iframe.html` mode, and thus not bound to Storybook UI. 
> Speed - 20 seconds to capture 200 stories.

Then - we tried to adopt the same approach on another project. And time this time was about 5 minutes (and 2 minutes to build storybook). The problem - bundle size, 20Mb in our case. And no code splitting possible with storybooks.

## Proposed solutions
There is 2 solutions

### Remove page reload
Fix storybook UI, to make story switching faster. Also enable story switching without updating iframe. Please make it real.
From speed prospective - this is the best way, as long you may load JS only once, and next only re-render visuals. But it is not quite good from "storybook" prospective, as long all components and all code for all components would exists, and would be required/executed. All global side effects, including styles from `styled-components` would took a place. _Actually - as in real application_.

### Speed up page load
Isolate the currently chosen story. Not running not used code. It's not possible with the current approach to not include/code split all the code - as long `it` was used to define stories - it was already executed. But it is possible to skip some computations in "iframe.html" mode.
I've written a [small webpack plugin](https://github.com/theKashey/read-story-later), which wraps all stories with condition like
```js
if( !location.pathname.endsWith('iframe.html') || !query.selectedKind || ${JSON.stringify(stories)}.includes(query.selectedKind)) {
  ... module body
}
```
This will just not execute non-selected story, not require stuff used by non-selected stories. This leads to less amount of JS to be executes (but not loaded or evaluated).

In my tests - this approach, with support of `devtool:eval` to simplify script _evaluation_, could half time to load.

### Code split stories
Code splitting would help a lot - not just not-run scripts you dont need, but also not-to-load.
Probably scripts like `read-story-later` could help here:
 - use babel (or webpack plugin/loader) to extract story information and files required
 - make imports/requires invisible to webpack (aka https://github.com/sindresorhus/require-fool-webpack)
 - hoist dynamic imports to the story top, to let webpack create chunks.
 - make storiesOf API async.

**Comment by ndelangen** [comment]
Hey @theKashey thanks for this, I was about to contact you to collaborate on some of these exact improvements, Let's chat on discord?

**Comment by ndelangen** [comment]
https://discord.gg/sMFvFsG

**Comment by ndelangen** [comment]
If your issue is mainly related to screenshotting, we have image screenshotting build-in to storyshots, an addon for creating snapshots of stories.

There are also integration partners such as https://www.chromaticqa.com

**Comment by theKashey** [comment]
I've tried story shooter but it did not work as I needed. And we need not only images, but some meta information about what is displayed.
Any way - any solution would work not quite cool with big bindles.

**Comment by ConneXNL** [comment]
Been waiting for something like this for a long time. I think isolating the stories could make storybook a lot faster. Currently ,as your component library grows, the incremental built time also increases. I am going around this by commenting any component I am not working on but it feels really counterintuitive to do so.
