### ISSUE TITLE
Copy button from the info addon should not copy the ellipsed code

### ISSUE THREAD

**Issue by keul** [storybooks/storybook#4243]
### Work summary

When the example code of the storybook is too long it's cutt-off in the view using ellipsis  (which is ok) but the cut version if also the ones who is copied.

![storybook](https://user-images.githubusercontent.com/284924/46159236-12188780-c280-11e8-9aec-39464607f0ce.png)

I think that when clicking on the *copy* button a uses is expecting to get the whole example in the clipboard.

**Comment by ndelangen** [comment]
I agree

**Comment by robcronin** [comment]
Hi @ndelangen, any update on this issue?

**Comment by keul** [comment]
@robcronin it has been closed from the stale bot, so: no.

I think you should provide a PR yourself if you need it
