### ISSUE TITLE
Iframe bundle parse error

### ISSUE THREAD

**Issue by Jungwoo-An** [storybooks/storybook#4247]
### Bug or support request summary

I opened chrome developer tool after start-storybook.

### Steps to reproduce

![default](https://user-images.githubusercontent.com/17793088/46187116-f9aa7a80-c31c-11e8-9ca8-60578b1fd04b.PNG)

![2](https://user-images.githubusercontent.com/17793088/46187118-fca56b00-c31c-11e8-9b20-1151d9345474.PNG)

### Please specify which version of Storybook and optionally any affected addons that you're running

- react: "16.5.0"
- react-dom: "16.5.2"
- @storybook/addon-actions: "4.0.0-alpha.23"
- @storybook/addon-actions: "4.0.0-alpha.23"
- @storybook/addon-info: "4.0.0-alpha.23"
- @storybook/addon-links: "4.0.0-alpha.23"
- @storybook/addon-storysource: "4.0.0-alpha.23"
- @storybook/addons: "4.0.0-alpha.23"
- @storybook/react: "4.0.0-alpha.23"

```js
// config.js
import { configure } from '@storybook/react';
import '../src/styles/index.scss';

// automatically import all files ending in *.stories.js
const req = require.context('../src', true, /.stories.tsx$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);

```

**Comment by ndelangen** [comment]
Do you have a place where I could reproduce? We don't seem to have this problem locally in our codebase. maybe it's some dependency.

Looking at your screenshot looks like a piece on non-storybook code, but hard to be sure.

**Comment by Jungwoo-An** [comment]
Thanks to @ndelangen.

However, for reason state above, my component is not rendering

**Comment by ndelangen** [comment]
Have you tried to do a clean install of all dependencies?

seriously looks like some line from some library got wrapped over 2 lines when it shouldn't, just looking at the screenshot.

If you can me an repo I can reproduce this behavior on, I can debug and understand what's going on.
