### ISSUE TITLE
Missing styles

### ISSUE THREAD

**Issue by mmintel** [storybooks/storybook#4248]
### Bug or support request summary

There seem to be styles missing in the storybook, some styles are loaded, others are not, also fonts missing. No error message.

### Steps to reproduce

I don't know how to reproduce, I tried disabling all storybook addons, i disabled every story, disabled my custom webpack config (also restarted node afterwards) 

### Please specify which version of Storybook and optionally any affected addons that you're running

    "@storybook/addon-actions": "^4.0.0-alpha.23",
    "@storybook/addon-knobs": "^4.0.0-alpha.23",
    "@storybook/addon-links": "^4.0.0-alpha.23",
    "@storybook/addon-notes": "^4.0.0-alpha.23",
    "@storybook/vue": "^4.0.0-alpha.23",

### Affected platforms 

- Chrome 71
- MacOS 10.14

### Screenshots / Screencast / Code Snippets (Optional)

![screenshot 2018-09-28 at 10 11 29](https://user-images.githubusercontent.com/4574612/46196688-0cff1b00-c308-11e8-9f3c-2ca7c0de77fa.png)

**Comment by psimyn** [comment]
@mmintel can you try loading in a different browser (or in Incognito). Could be an extension conflicting

Are there any missing files in Chrome Network tab (404 etc)?

How did you install Storybook?

**Comment by joefiorini** [comment]
I can confirm I have the same issue. All the CSS classes that specify fonts say `inherit` and there doesn't seem to be anything specifying a font to use, so it's defaulting to `Times`. Here's my tree of storybook dependencies:

```
├─ @lcars/components-core@1.0.7
│  └─ @storybook/addons@3.4.11
├─ @storybook/addon-actions@4.0.0-alpha.23
│  ├─ @storybook/addons@4.0.0-alpha.23
│  ├─ @storybook/channels@4.0.0-alpha.23
│  ├─ @storybook/components@4.0.0-alpha.23
│  └─ @storybook/core-events@4.0.0-alpha.23
├─ @storybook/addon-info@4.0.0-alpha.22
├─ @storybook/addons@4.0.0-alpha.22
├─ @storybook/channel-postmessage@4.0.0-alpha.22
├─ @storybook/channels@4.0.0-alpha.22
├─ @storybook/client-logger@4.0.0-alpha.22
├─ @storybook/components@4.0.0-alpha.22
├─ @storybook/core-events@4.0.0-alpha.22
├─ @storybook/core@4.0.0-alpha.22
├─ @storybook/mantra-core@1.7.2
├─ @storybook/node-logger@4.0.0-alpha.22
├─ @storybook/podda@1.2.3
├─ @storybook/react-komposer@2.0.4
├─ @storybook/react-simple-di@1.3.0
├─ @storybook/react-stubber@1.0.1
├─ @storybook/react@4.0.0-alpha.22
└─ @storybook/ui@4.0.0-alpha.22
```

I checked this in incognito in Chrome 60 & Safari, same result in both.

**Comment by Keraito** [comment]
Seems like the issues from  #4211 are still there, @igor-dv

**Comment by igor-dv** [comment]
That is strange.. Doesn't happen to me.. Can anyone reproduce on a clean env?

**Comment by amoshydra** [comment]
Here is what I found from my environment Windows:

| Package manager | Version | Style |
| :-- | :-- | :--
| npm | 4.0.0-alpha.20 | ✔
| yarn | 4.0.0-alpha.20 | ❌
| yarn | 4.0.0-alpha.23 | ✔

**Comment by joefiorini** [comment]
It turns out I had a 3.x version of @storybook/addons sneak in. I updated that to the latest alpha and everything is working again.
  

  
  

  
  
>

**Comment by gabrielcsapo** [comment]
@mmintel could you verify this is no longer a bug?

**Comment by igor-dv** [comment]
IMO the latest alpha is ok. Please reopen with the reproduction.

**Comment by mmintel** [comment]
I installed storybook via the vue cli with `"vue-cli-plugin-storybook": "^0.4.8",` and I think this is the problem. A look at my `package-lock.json` shows this requires the alpha-20.

```JSON
    "vue-cli-plugin-storybook": {
      "version": "0.4.8",
      "resolved": "https://registry.npmjs.org/vue-cli-plugin-storybook/-/vue-cli-plugin-storybook-0.4.8.tgz",
      "integrity": "sha512-3uLZ+1jrympzd7OypZVHTeVaF8gqEY4K9qYpEd8uyzdMZasU794NT8yTqyzNTK/iHDSsWYmicd6HA/UGDHyQFw==",
      "dev": true,
      "requires": {
        "@storybook/addons": "4.0.0-alpha.20",
        "@storybook/vue": "4.0.0-alpha.20"
      },
```

**Comment by amoshydra** [comment]
Hi @mmintel 

I was using `vue-cli-pugin-storybook, v0.4.8` like you were when i posted [this comment 2 days ago](https://github.com/storybooks/storybook/issues/4248#issuecomment-427757894)

However, this styling issue is gone yesterday on my existing project. It happen after I explicitly installing `@babel/core` dependency as part of the process of adding `@vue/cli-plugin-unit-jest`.

I am no longer able to reproduce this problem on a fresh creation of vuecli project that uses `4.0.0-alpha.20`. See: https://github.com/amoshydra/repro-storybook-storybook-4248

### Suggestion:
Perhaps you can try
1. removing `yarn.lock` and `node_modules` 
2. Reinstalling your dependencies again `yarn`

</br>

##### Side note:
I have recently found out that, you can selectively override a dependency's dependency in the `package.json` if you are using yarn. https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

`package.json`
```json
{
  "resolution": {
    "vue-cli-plugin-storybook/@storybook/addons": "4.0.0-alpha.24",
    "vue-cli-plugin-storybook/@storybook/vue": "4.0.0-alpha.24"
  }
}
```

**Comment by vjpr** [comment]
Installed 5x and run into this problem.

**Comment by meebix** [comment]
I am having intermittent issues on v4.1.6 across the board.

```
    "@storybook/addon-actions": "4.1.6",
    "@storybook/addon-knobs": "4.1.6",
    "@storybook/addon-options": "4.1.6",
    "@storybook/addon-viewport": "4.1.6",
    "@storybook/react": "4.1.6",
```

Something strange going on with a race condition or similar with styling in the main Storybook UI.
