### ISSUE TITLE
Tear down DOM outside of Angular App Component

### ISSUE THREAD

**Issue by cwmrowe** [storybooks/storybook#4250]
When creating components that use Angular CDK Overlays. The overlays are not torn down (removed from the DOM) when navigating between stories.

This is because the DOM created by CDK Overlays exists outside the app component. 

I have created a Gist that fixes it in the short term, but there may be a better way of doing it.

https://gist.github.com/cwmrowe/86fa0671e632b1369635d4d8411c0d02

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular 4.0.0-alpha.20

### Acceptance criteria

Give a story that creates DOM outside of the Angular App Component (e.g. CDK Overlay)
When I navigate to another story
Then those DOM elements should be removed

CDK Overlay: https://material.angular.io/cdk/overlay/overview

**Comment by igor-dv** [comment]
IMO your solution is good enough =)

**Comment by igor-dv** [comment]
LMK if there are any suggestions for solving this
