### ISSUE TITLE
Vuex is undefined

### ISSUE THREAD

**Issue by KeionneDerousselle** [storybooks/storybook#4259]
### Bug or support request summary

My team is trying to use the alpha version of storybook because we are upgrading our project to use Nuxt 2. This requires that we use Webpack 4. 

When using @storybook/vue 4.0.0-alpha.23, any stories for components which require the Vue store, Vuex, throw errors. 

![screen shot 2018-10-01 at 4 25 38 pm](https://user-images.githubusercontent.com/6044786/46319547-aabc4980-c597-11e8-8491-401bae3dafea.png)

![screen shot 2018-10-01 at 4 26 07 pm](https://user-images.githubusercontent.com/6044786/46319562-b740a200-c597-11e8-8a4c-88cdf6fc0458.png)

This appears to be because the store is not defined on components which use it.

To test that, my team logged the value of the store on the `beforeMount` and `mounted` Vue lifecycle hooks.

```javascript
 beforeMount() {
    debugger
    console.log(this.$store)
  },
  mounted() {
    console.log(this.$store)
  },
```
Each time we viewed the console in the developer tools, when running storybook, we saw that `this.$store` was undefined. 

We followed [these instructions](https://storybook.js.org/basics/guide-vue/#create-the-config-file) to use Vuex. Is there something different we need to do to install the Vuex plugin? Currently, we have this in our `.storybook/config.js`:

```javascript
import { configure, addDecorator } from '@storybook/vue'
import { action } from '@storybook/addon-actions'

import Vue from 'vue'
import Vuex from 'vuex'
import VeeValidate from 'vee-validate'

import i18n from '@/utils/i18n'

import '@/utils/globals.js' // Global Components

Vue.use(Vuex)
Vue.use(VeeValidate, {
  dictionary: {
    en: require('@/locales/en/_global.json').global.validation.veeValidate
  },
  inject: false
})

// Register custom components.
function loadStories() {
  const req = require.context('@/components', true, /\.stories\.js$/)
  req.keys().forEach(filename => req(filename))
}

configure(loadStories, module)
```

We also tried running the [Vue Kitchen Sink Example](https://github.com/storybooks/storybook/tree/master/examples/vue-kitchen-sink) because we saw that it had upgraded to use @storybook/vue 4.0.0-alpha.23. We thought this example would show use if our configuration was wrong. We edited one of the components to use the Vuex store. When we ran the example, we experienced the same issue.

### Steps to reproduce
1. Upgrade @storybook/vue to 4.0.0-alpha.23
2. Run storybook
3. You will see an error that says something about `moment`, a dependency of `react-datetime`, being undefined
4. Fix the moment.js error (we were able to accomplish this by installing moment as a peer dependency at the version 2.22.1)
5. Run storybook in Chrome
6. Click on any component using the Vuex store
7. Inspect the console in the developer tools 

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue 4.0.0-alpha.23
- @storybook/addon-actions 4.0.0-alpha.23
- @storybook/addon-knobs 4.0.0-alpha.23
- @storybook/addon-links 4.0.0-alpha.23
- @storybook/addon-notes 4.0.0-alpha.23
- @storybook/addons 4.0.0-alpha.23

### Affected platforms 
- Mac OS High Sierra 10.13.6
- Chrome Version 69.0.3497.100
- Vue version 2.5.17
- Vuex version 3.0.1
- Nuxt version 2.1.0
- moment 2.22.1
- babel 7.0.0
- webpack 4.20.2

**Comment by kellym** [comment]
Also experiencing this issue.

**Comment by igor-dv** [comment]
I don't know much about vue + vuex, but we do have a working use-case in our official vue example app. 

https://storybooks-vue.netlify.com/?selectedKind=Custom%7CMethod%20for%20rendering%20Vue&selectedStory=vuex%20%2B%20actions&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

Can you please elaborate or maybe to reproduce the problem with the official example?

**Comment by zachmanring-natgeo** [comment]
I am having the same issue trying to setup a store via the config.js so that multiple components can use the same store.

**Comment by ChucKN0risK** [comment]
I'm experiencing the same issue. I created a question on StackOverflow : https://stackoverflow.com/questions/56682493/how-can-i-make-vuex-store-work-with-storybook
