### ISSUE TITLE
Pass serializers to addon-storyshots

### ISSUE THREAD

**Issue by tobilen** [storybooks/storybook#4272]
I'm not sure whether to call this a bug or feature request.

# My Problem
I am snapshotting a component that includes a javascript date in its props. When a date object is serialized, it applies the timezone to the printed string, which means a serialized date will be different depending on the machines timezone.
The solution to this problem is to apply a custom serializer that strips the timezone from dates ( https://www.npmjs.com/package/jest-date-serializer ). However, my specified serializers aren't applied by `addon-storyshots`.

# Analysis
Currently, `snapshotSerializers` specified in the jest configuration get ignored by addon-storyshots if the `multiSnapshot` option is used. This is because the subdependency (`jest-specific-snapshot`) uses its own serializers.

We currently already have an option to pass a single serializer, which is just a function that gets applied to the rendered tree before it is passed to jest for snapshot comparison.

# Solution
it would be cool if instead of a single serializer we could pass an array of serializers that gets applied to the jest configuration, just like the default `snapshotSerializers` option.

**Comment by igor-dv** [comment]
The v4 change is merged.

**Comment by igor-dv** [comment]
I am going to close this since it's merged into the v4.
