### ISSUE TITLE
Any way to run storyshots with just the component?

### ISSUE THREAD

**Issue by haldunanil** [storybooks/storybook#4278]
### Bug or support request summary

When running storyshot image tests, the screengrabs get not just the component but also the README/info file and whatever else might be in the middle section. Is there any way to limit it to just the component being rendered?

### Steps to reproduce

N/A

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 16.5
- @storybook/addon-storyshots 4.0.0-alpha.23
- storybook-readme 4.0.0-beta1

### Affected platforms 

N/A

### Screenshots / Screencast / Code Snippets (Optional)

N/A

**Comment by igor-dv** [comment]
You can create a separate setup for the storyshots that won't include problematic addons.

Or maybe you can customize the [storyshots-puppeteer](https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-puppeteer), and provide the `customizePage` parameter that will set a viewport rectangle of the page

**Comment by haldunanil** [comment]
Do you have any examples you can point me to that implements the viewport setting?

**Comment by igor-dv** [comment]
Found [this](https://github.com/GoogleChrome/puppeteer/issues/306#issuecomment-322929342)  comment.

Based on it, you need to do something like this:



```js

import initStoryshots from '@storybook/addon-storyshots';
import { imageSnapshot } from '@storybook/addon-storyshots-puppeteer';

initStoryshots({
  // blah blah initStoryshots fields
  test: imageSnapshot({
    // blah blah imageSnapshot fields
    // beforeScreenshot 👇 is an async function that called right before snapshot.
   // we will need to find the rectangle of the story to snapshot
    beforeScreenshot: async (page, { context }) => {
      const rect = await page.evaluate(selector => {
        const element = document.querySelector(selector);
        const {x, y, width, height} = element.getBoundingClientRect();
        return {left: x, top: y, width, height, id: element.id};
      }, selector); // here you need to set a selector to the section you want to snapshot

      // this is a hack, since we don't have an option to pass the "page" 
      // to the "getScreenshotOptions" paramater, should create a PR for this
      context.rect = rect;
    },
    
    // getScreenshotOptions 👇 is not an async function that called 
    // to customize the snapshot parameters. we probably need to change this.
    getScreenshotOptions: ({ context }) => {
      // we've put "react" to the context in the "beforeScreenshot"
      const { rect } = context;

      retrurn {
        clip: {
          x: rect.left - padding,
          y: rect.top - padding,
          width: rect.width + padding * 2,
          height: rect.height + padding * 2
        }
      };
    }
  });
});
```

**Comment by haldunanil** [comment]
Looks good, I'll give it a try and report back!

**Comment by yfr** [comment]
Anything new on that? would love to do the same.

**Comment by igor-dv** [comment]
let us know If anything is missing here.
