### ISSUE TITLE
export 'default' (imported as 'PropTypes') was not found in 'prop-types'

### ISSUE THREAD

**Issue by jasonbarry** [storybooks/storybook#4279]
### Bug or support request summary

I'm receiving this error multiple times when trying to run start-storybook. Currently running version 4.0.0-alpha.23. localhost:9001 appears in my browser, but the whole page is blank. The JS error is `TypeError: Attempted to assign to readonly property.`. Stack trace: 

<img width="656" alt="screen shot 2018-10-03 at 6 27 44 pm" src="https://user-images.githubusercontent.com/236451/46449538-56ed6400-c741-11e8-87c4-1d1adf0a6f5d.png">

In my terminal console, I see the following: 

```
WARNING in ./.storybook/node_modules/react-split-pane/dist/index.esm.js 712:47-56
"export 'default' (imported as 'PropTypes') was not found in 'prop-types'
 @ ./.storybook/node_modules/@storybook/components/dist/layout/desktop.js
 @ ./.storybook/node_modules/@storybook/components/dist/layout/index.js
 @ ./.storybook/node_modules/@storybook/components/dist/index.js
 @ ./.storybook/node_modules/@storybook/addon-knobs/dist/components/Panel.js
 @ ./.storybook/node_modules/@storybook/addon-knobs/dist/register.js
 @ ./.storybook/node_modules/@storybook/addon-knobs/register.js
 @ ./.storybook/addons.js
```

### Steps to reproduce

1. Run `start-storybook`

### Please specify which version of Storybook and optionally any affected addons that you're running

"@storybook/addon-backgrounds": "4.0.0-alpha.23",
"@storybook/addon-centered": "4.0.0-alpha.23",
"@storybook/addon-knobs": "4.0.0-alpha.23",
"@storybook/addon-storyshots": "4.0.0-alpha.23",
"@storybook/addon-viewport": "4.0.0-alpha.23",
"@storybook/react": "4.0.0-alpha.23",
"mini-css-extract-plugin": "^0.4.3",
"storybook-addon-jsx": "5.4.0",

### Affected platforms 

macOS 10.14
node 10.8

**Comment by gabrielcsapo** [comment]
could you provide a minimal viable example to reproduce?

**Comment by jasonbarry** [comment]
@gabrielcsapo turns out this was the same as https://github.com/storybooks/storybook/issues/4246. I had a `node_modules` folder inside my `.storybook` dir that was causing conflicts (my text editor hides node_modules to reduce noise in the sidebar which made tracking this down tricky). Perhaps a warning should be thrown if a non-root node_modules dir is detected? I imagine monorepos could run into this issue.
