### ISSUE TITLE
Add theming support 

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybook#428]
Add the ability to theme storybook as needed.
We should also carry a new theme with getstorybook.io look and feel.

**Comment by Krabaul** [comment]
What about using [react-with-styles](https://github.com/airbnb/react-with-styles) by airbnb?

I have already used it together with [aphrodite](https://github.com/khan/aphrodite) and its working really well.

**Comment by tuchk4** [comment]
Any plans?)

**Comment by UsulPro** [comment]
We can add theming support as a separate feature on par with UI customization (#313, #1266)

I propose to start implementing theming via follows:

- Add mantra module and API to `@storybook/ui`

- Decide what parameters we'll include to themes (colors, styles, sizes). What the structure of theme object?

- Create default themes (white, black)

- Create the tool for themes development and API to support custom themes (on par with API for custom UI components which could support theming or not)

**Comment by ndelangen** [comment]
My long-term goal is to migrate al UI components to a specialised package, and from the app allow addons to wrap any of these.

This will allow for custom placeholders, theme changes, data enrichment, custom ui behavior.

This work is in progress, but moving all components is a large task.
