### ISSUE TITLE
AddDecorator breaks AddWithInfo

### ISSUE THREAD

**Issue by tomitrescak** [storybooks/storybook#429]
Info text is rendered in the decorator.

If I do this:

```
  .addDecorator((story: any) => (
    <Segment style={{ width: '300px', margin: '10px' }}>
      {story()}
    </Segment>
  ))
```

Info text is rendered in the very small window of 300px wide.

**Comment by arunoda** [comment]
@mnmtanish @roonyh could you guys help us?

**Comment by arunoda** [comment]
Ping @mnmtanish

**Comment by mnmtanish** [comment]
We can't fix this unless we fix this issue
https://github.com/kadirahq/react-storybook/issues/320#issuecomment-247248502

**Comment by tomitrescak** [comment]
Is it possible to render info in a separate iframe?
Rendering it around story seriously interferes with component structure.

I'm using semantic-ui and for example when component is list-item component and I render decorator that wraps the list item with list, adding info leads to broken view and the only way to deal with that is to include also list component in the story.

**Comment by ndelangen** [comment]
#1147 Will happen soon! @tomitrescak
