### ISSUE TITLE
Explicit overriding of default babel configuration does not work

### ISSUE THREAD

**Issue by kuka-radovan** [storybooks/storybook#4295]
Acording to [documentation](https://storybook.js.org/configurations/default-config/#babelrc-support), in case of project specific `.babelrc` file, storybook use that instead of the default one. It looks like this does not work.

I use `@storybook/polymer 4.0.0-alpha.24` and I have following `.babelrc` file
```json
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "targets": {
        "esmodules": true
      }
    }]
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}
```

and `.browserslistrc` file
```
last 2 versions
IE >= 11
```

This configuration is mandatory, because `custom elements` requires ES2015 classes. Everything works fine in project, but when I wanted to integrate storybook to the project I got following error in browser console.
```
Uncaught TypeError: Class constructor LitElement cannot be invoked without 'new'
```

This is probably caused by storybook's default babel configuration that uses class polyfill when transpiling the code. If I copy my `.babelrc` file to `.storybook` directory, everything works as expected.

**Comment by igor-dv** [comment]
@Hypnosphi, looks like our default babel config overrides props from the user's root `.babelrc`

**Comment by Hypnosphi** [comment]
In 4.0, after https://github.com/storybooks/storybook/pull/4077, storybook's default babel config should get merged with whatever user has. To completely opt out of this, you need a `.storybook/.babelrc` file.

We probably need to update docs and MIGRATION.md

**Comment by tonai** [comment]
I have created a new issue as it is not directly related to that issue : https://github.com/storybooks/storybook/issues/4958
