### ISSUE TITLE
Storybook does not work with Vue components that import mixins

### ISSUE THREAD

**Issue by DirkStevens** [storybooks/storybook#4313]
- Cloned the vue kitchen sink from Storybook 3.4.11
- npm i
- npm run storybook

=> All kinds of errors because of missing vue-template-compiler...

- npm i --save vue-template-compiler

- npm run storybook
=> Appears to work now

- Add file /src/stories/MyMixin.js with:
`export default MyMixin = {};`
![image](https://user-images.githubusercontent.com/1837524/46584654-32a5c600-ca66-11e8-93cf-43613d4b5424.png)

- Add to /src/stories/Button.vue:
`import MyMixin from 'MyMixin.js';`
![image](https://user-images.githubusercontent.com/1837524/46584684-9def9800-ca66-11e8-8dbd-15a837700969.png)

Refresh browser and Storybook now reports:
`ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/stories/Button.vue
Module not found: Error: Can't resolve 'MyMixin.js' in '/Users/madewith/MadeWith/vue-kitchen-sink/src/stories'`

I've read about webpack settings that solved a seemingly similar issue with importing sub components here:
https://github.com/storybooks/storybook/issues/2695

**Comment by DirkStevens** [comment]
@gabrielcsapo Thank you for following up.

I've tried the exact same thing in Storybook 4 Alpha with the same outcome.

**Comment by igor-dv** [comment]
that's not how we run the examples in the monorepo. You need to bootstrap everything before, not just the example. 

Anyway, you should probably import it like this:

```js
import MyMixin from './MyMixin.js';
```
