### ISSUE TITLE
Storyshot doesn't load addons

### ISSUE THREAD

**Issue by donaldpipowitch** [storybooks/storybook#4315]
### Work summary

My previous PRs (https://github.com/storybooks/storybook/pull/4081, https://github.com/storybooks/storybook/pull/4176) had the goal to set a different background for storyshot tests. But I just noticed that the addons aren't loaded in storyshot tests, because they open the `iframe.html` directly. We would need to modify storyshot so it loads the "normal" storybook example, but without the "chrome" (e.g. without the navigation on the left side and the addon tabs in the bottom). Maybe this behavior could be triggered with a new config parameter (e.g. `withAddons: true`).

### Where to start

- `const { imageSnapshot } = require('@storybook/addon-storyshots-puppeteer');` needs to accept a new config parameter `withAddons?: boolean` (in case we don't want to enforce this new behavior by default).
- We still have a `storybookUrl` like `http://localhost:9001?background=transparent`, but now we don't add `/iframe` to the URL (see [here](https://github.com/storybooks/storybook/blob/36dd38c8799d351e0bf586df55d24956c0caf82d/addons/storyshots/storyshots-puppeteer/src/url.js#L6)), but maybe something like `?chromeless` and load the real storybook instance.
- The storybook would need to accept `?chromeless` as a param to hide the navigation and addons panel (may [this would be a good place](https://github.com/storybooks/storybook/blob/master/lib/ui/src/modules/ui/routes.js#L26) to do it?).
- Update docs to inclue `withAddons?: boolean` and `?chromeless` in the right places.

### Acceptance criteria

I can create a storyshot tests which uses a `storybookUrl` like `http://localhost:9001?background=transparent` which actually switches a real background named `transparent` in a storybook instance which uses `@storybook/addon-backgrounds`.

### Who to contact

_Add yourself and/or people who are familiar with the code changes and requirements. These people should be able to review the completed code._
End work issue - please tag this issue with the correct status and type labels

---

(Some general feedback: I feel like the initial GitHub issue template is a little bit complicated. It always takes a minute for me to figure out what I actually need to write. 😕)

**Comment by jacksbox** [comment]
+1 this would be handy
