### ISSUE TITLE
Have addon knobs url parameters been removed in v4?

### ISSUE THREAD

**Issue by Eelsie** [storybooks/storybook#4325]
### Support request summary

I don't know if it is a bug or a wanted feature, but in version 4 knobs are not anymore part of the url parameters. How would it be possible to retain a changed prop? Now props are always reset to default. Issue is related to #3736.

Is it a bug or should I switch to version 3 if I want knobs as url parameters? Thanks!

**Comment by Eelsie** [comment]
Great! Thank you! Old url paramenters don't work anymore though.. how could I build them? With storybook 3 I had for example `&knob-fixed=%20true`. All the url `https://mydomain/?selectedKind=components&selectedStory=logo&knob-fixed=%20true`.

**Comment by shilman** [comment]
@Eelsie do you have a repro? you can see the knobs in action on the storybook example:

1. Navigate to [the example](https://storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
2. Open the knobs addon, and set `Fruit` to `Banana`
3. Click on the `Copy` button in the lower right corner.
4. It will copy a link to [the story with `Banana`](https://storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
5. Open that link in another tab. Initially it should say `Apple`, but after a second it should update to `Banana`

**Comment by Eelsie** [comment]
Great @shilman! Thank you! This is a great help!

**Comment by nicgirault** [comment]
This does not working on dev server with hot reload :-(

**Comment by shilman** [comment]
@nicgirault which part?

**Comment by nicgirault** [comment]
(sorry for the delay)

I start the dev server
I navigate to un story
I choose an option in a knob select list
I click on the copy button
I past the link in a new tab
In my case I get redirected from `http://localhost:9001/?path=/story/exercise-headers--sound-header&knob-Characters=4&knob-Sound Status=SOUND_PLAYING&knob-image=` to `http://localhost:9001/?path=//story/exercise-headers--sound-header`

**Comment by shilman** [comment]
@nicgirault which version?

**Comment by nicgirault** [comment]
"@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-knobs": "^5.0.11",
    "@storybook/addon-links": "^5.0.11",
    "@storybook/addons": "^5.0.11",
    "@storybook/react": "^5.0.11",
    "@storybook/theming": "^5.0.11",

And here is the code of the story:

```typescript
storiesOf('Exercise/Headers', module)
  .add('Sound Header', () => {
    const characterIndex = select(
      'Characters',
      forestCharacters.map((_, index) => index),
      0
    )

    const soundStatus = select(
      'Sound Status',
      { SOUND_PLAYING, SOUND_REPEAT, None: null },
      SOUND_PLAYING
    )

    const image = boolean('image', false)

    return (
      <SoundHeaderBase
        characterIndex={characterIndex}
        soundStatus={soundStatus}
        onClick={action('click header')}
        isSuccess={null}
        showContent={true}
        image={image ? 'alligator' : null}
      />
    )
  })
```

**Comment by shilman** [comment]
@nicgirault can you try updating to the latest? I think this was fixed at some point but I cannot find the exact PR at the moment.

**Comment by phloe** [comment]
This still doesn't seem to work with version 5.3.8 :(

**Comment by shilman** [comment]
This is working in `official-storybook`, try the knobs stories:

https://next--storybookjs.netlify.com/official-storybook/
