### ISSUE TITLE
How to intercept call to manager with custom script?

### ISSUE THREAD

**Issue by FaresAbu-Khiarah** [storybooks/storybook#4329]
Hi guys,

I am trying to secure our storybook with a login, using keycloak-js and react. Therefore I need to intercept any calls to the manager.

I attempted to write a Full Mode(extend) webpack.config.js like so
```
const path = require('path');
module.exports = (baseConfig, env, defaultConfig) => {
  // Extend storybook defaultConfig
  defaultConfig.entry.manager.push(path.resolve(__dirname, '../src/login.jsx'));
  return defaultConfig;
};
```
Unfortunately this did not work for me and it also does not include keycloak's iframe. I also tried the manager-head.html - way. The problem with that is, that keycloak expects its own iframe to be loaded into the body at this point. 

Does anyone know a workaround for my problem, that does not include maintaining an own fork or any major hacking :)

Thanks

**Comment by igor-dv** [comment]
What about adding it as an addon?

**Comment by FaresAbu-Khiarah** [comment]
After looking through the AddonsApi, I'm not really sure how that would work.

**Comment by igor-dv** [comment]
I am not familiar with `keycloak-js`, but the proper way to register external things to the SB manager is an addons API. You need to understand though, that stories are executed in the iframe (I don't know if it's relevant =) )

BTW, did the `login.jsx` executed ?

**Comment by FaresAbu-Khiarah** [comment]
First of all, thank you for your reply :)

The strange thing is that the login.jsx gets executed and it works properly as long as I don't refresh the page. Because as soon as I refresh the page, I get an infinite refresh loop until I cancel it manually. I'm aware of the fact that stories get executed in an iframe and maybe this is the cause for the infinite loop, but this is just a wild guess.. Also if the user logs out in another tab, it needs to logout from the storybook application, which is not working either.

Assuming I'd write an addon. My first approach would be to register it, then listen for the onStory event and fire my login logic?
Or should i use the getChannel function and communicate via the channel with the manager? If so, how would I go about this?

Thanks!

**Comment by FaresAbu-Khiarah** [comment]
So I just tried to write it as an addon, which was simpler than I thought. The result is actually the same..

**Comment by igor-dv** [comment]
Anything you can share ?

**Comment by FaresAbu-Khiarah** [comment]
Sure.

So this is my addon:
```
import addons from '@storybook/addons';
import login from '../../login';

addons.register('my-company/login', (storybookAPI) => {
  storybookAPI.onStory(login);
});
```
This is my login.js:
```
import Keycloak from 'keycloak-js';
import config from 'config';

export default function () {
  const keycloak = Keycloak(config.get('keycloak'));

  keycloak.init({ onLoad: 'login-required' }).success((authenticated) => {
    if (authenticated) {
      setInterval(() => {
        keycloak.updateToken(10).error(keycloak.logout);
      });
    }
  });
}
```

I've also imported it in my addons.js
```
...
import '../src/addons/login/register';
```

**Comment by FaresAbu-Khiarah** [comment]
Also if I directly go to the base url (e.g. localhost:6006) it works fine, but if i refresh from a url with parameters the refresh loops begins

**Comment by igor-dv** [comment]
Oops

**Comment by igor-dv** [comment]
Did you find what causes to the refresh loop?

**Comment by FaresAbu-Khiarah** [comment]
Yes finally figured it out! :)

It had to do with query parameters being appended to the url. Keycloak has a setting for response mode, which is defaulted to fragment ('#'), whereas Storybook uses query ('?'). This produced a conflict between the url that keycloak tried to build and the url that storybook needs to determine the location. The response mode can be changed to query thankfully.

**Comment by prashant1k99** [comment]
Did you know that StoryBook creates static assets. Which means the security can easily be bypassed as the entire assets are served upon request. You should think of something about server side implementation of the request and once authenticated then serve the route desired by the Client. I believe it can easily be done with Express....
