### ISSUE TITLE
Change RN Storybook folder from storybook to .storybook

### ISSUE THREAD

**Issue by Gongreg** [storybooks/storybook#4332]

**Comment by Gongreg** [comment]
Sadly React Native seems to really not like folders beginning with .

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.7 containing PR #4942 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
