### ISSUE TITLE
[addon-info] Need another way to pull description from docgen info

### ISSUE THREAD

**Issue by joefiorini** [storybooks/storybook#4373]
### Bug or support request summary

I created components with docgen description comments like:

```javascript
/** This is the description */
class Button extends React.Component {
  // ...
}
```

And then I create a story named "Secondary Button", when I click "Show Info" I expect to see "This is the description" from my component somewhere on the page, but I do not.

If I rename the story to just "Button" then I _do_ see "This is the description".

The problem seems to be in the `_getComponentDescription()` function, which is comparing the `displayName` of the component to `context.story`, which appears to be the story name.

It seems like having a secondary condition here might be useful. One approach might be adding another option to the parameters for info like:

```
{
  info: {
    descriptionClass: Button
  }
}
```

Another option would be to allow passing the class where we can currently pass a string description (ie. `text`), ie:

```
{
  info: {
    text: Button
  }
}
```

As a bonus, with multiple components, this would allow us to tell which component to get the description from.

Thoughts?

### Steps to reproduce

Create a story for a component that has a docgen description comment, where the story name is not the same as the component's `displayName` property and you will see this issue.

### Please specify which version of Storybook and optionally any affected addons that you're running

```
❯ yarn list --pattern @storybook
yarn list v1.10.1
├─ @storybook/addon-actions@4.0.0-alpha.24
├─ @storybook/addon-info@4.0.0-alpha.22
│  ├─ @storybook/addons@4.0.0-alpha.22
│  ├─ @storybook/channels@4.0.0-alpha.22
│  └─ @storybook/components@4.0.0-alpha.22
├─ @storybook/addon-knobs@4.0.0-alpha.24
├─ @storybook/addon-storysource@4.0.0-alpha.24
├─ @storybook/addons@4.0.0-alpha.24
├─ @storybook/channel-postmessage@4.0.0-alpha.24
├─ @storybook/channels@4.0.0-alpha.24
├─ @storybook/client-logger@4.0.0-alpha.22
├─ @storybook/components@4.0.0-alpha.24
├─ @storybook/core-events@4.0.0-alpha.24
├─ @storybook/core@4.0.0-alpha.24
│  └─ @storybook/client-logger@4.0.0-alpha.24
├─ @storybook/mantra-core@1.7.2
├─ @storybook/node-logger@4.0.0-alpha.24
├─ @storybook/podda@1.2.3
├─ @storybook/react-komposer@2.0.4
├─ @storybook/react-simple-di@1.3.0
├─ @storybook/react-stubber@1.0.1
├─ @storybook/react@4.0.0-alpha.24
└─ @storybook/ui@4.0.0-alpha.24
```

**Comment by ndelangen** [comment]
Marking this as a todo for #4341

**Comment by brandonce** [comment]
This looks similar to https://github.com/storybooks/storybook/issues/4643
