### ISSUE TITLE
Select a story when expanding a group by default

### ISSUE THREAD

**Issue by supadupdip** [storybooks/storybook#4374]
### Add option to automatically select a story when using the dropdown selector

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

### When I click on a group on the left panel and I see a something with a dropdown if I click the item it should expand to reveal its stories but also select the first one and load it. This would also be great for components that don't have multiple stories and just need one page, you wouldn't have to first expand and then click on the only story available.

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react x.x.x
- @storybook/addon-something x.x.x

### Affected platforms 

- All browsers

**Comment by gabrielcsapo** [comment]
@supadupdip would you be able to explain this more? is this a feature request?

**Comment by igor-dv** [comment]
This is duplicate to #3105. And IMO the better solution is to support something similar to this #2863.
