### ISSUE TITLE
.babelrc es2015 preset breaks Meteor build

### ISSUE THREAD

**Issue by dburles** [storybooks/storybook#440]
It seems to somehow conflict with Meteor's build process as immediately after running Meteor I see an undefined error on the server caused by a reference to a global variable that's defined deep within a lib directory. Meteor 1.4.1.1.

**Comment by arunoda** [comment]
Have you fixed it? If so how?

**Comment by dburles** [comment]
I haven't really dug into it any further

**Comment by dburles** [comment]
I'll create a reproduction

**Comment by dburles** [comment]
See here https://github.com/dburles/meteor-storybook-babelrc-issue

**Comment by achtan** [comment]
my solution:
put `.babelrc` for storybook into `.storybook/` dir
and dont let meteor load any files where `@kadira/storybook` is imported (put all files under /imports dir)

**Comment by arunoda** [comment]
@achtan That's a good solution and I'll change the getstorybook tool to be like that.

**Comment by dburles** [comment]
hey @arunoda what's ETA on this fix? :)

**Comment by ndelangen** [comment]
If you are still experiencing this issue, please re-open 👍
