### ISSUE TITLE
Module build failed 

### ISSUE THREAD

**Issue by sonusasankan** [storybooks/storybook#4444]
I have installed storybook freshly using  `npx -p @storybook/cli@alpha sb init`. I expected the storybook should be opened on 'localhost:9009' when I run. But unfortunately it thrown a error message like `ERROR in ./src/stories/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:/repos/kool-kanya/src/stories/index.js: Unexpected token (9:55)`

### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

![image](https://user-images.githubusercontent.com/15810732/47001291-bab35c00-d147-11e8-8615-3f5382705b1c.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react": "^4.0.0-alpha.25

.storybook/config.js
```
import { configure } from '@storybook/react';

function loadStories() {
  require('../src/stories');
}

configure(loadStories, module);
```
stories/index.js
```
import React from 'react';

import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { linkTo } from '@storybook/addon-links';

import { Button, Welcome } from '@storybook/react/demo';

storiesOf('Welcome', module).add('to Storybook', () => <Welcome showApp={linkTo('Button')} />);

storiesOf('Button', module)
  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
  .add('with some emoji', () => (
    <Button onClick={action('clicked')}>
      <span role="img" aria-label="so cool">
        😀 😎 👍 💯
      </span>
    </Button>
  ));
```

**Comment by igor-dv** [comment]
Do you use babel 6?

**Comment by sonusasankan** [comment]
@igor-dv yes, I am using Babel 6

**Comment by igor-dv** [comment]
Take a look at the [MIGRATION guide here](https://github.com/storybooks/storybook/blob/master/MIGRATION.md#babel-7)

LMK if this didn't work for you.

**Comment by sonusasankan** [comment]
@igor-dv  Thanks, migrated to babel core 7 and its worked.
