### ISSUE TITLE
Text knob transforms characters

### ISSUE THREAD

**Issue by cichelero** [storybooks/storybook#4445]
<img width="510" alt="knob issue" src="https://user-images.githubusercontent.com/9719178/47003706-2f7a9c00-d130-11e8-9bff-5b7d8979a31e.png">

### Bug or support request summary

With storybook and knobs release candidate 4, I have the **'** string misformated as in the image.

### Steps to reproduce

Configure a text knob with text like `You're great!`, it will be displayed as `You&#39;re great!`.

Minimal repository [reproducing the bug](https://github.com/cichelero/storybook4-knob-issue)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-rc.0
- @storybook/addon-knobs 4.0.0-rc.0

### Affected platforms 

Saw it on Chrome and Firefox

### Screenshots / Screencast / Code Snippets (Optional)

```js
import { withKnobs, text } from '@storybook/addon-knobs';

import Title from '../Title';

storiesOf('Knobs', module)
  .addDecorator(withKnobs)
  .add('Title', () => <Title text={text('text', "You're great!")} />);
```

**Comment by brunoreis** [comment]
I found the same behavior on object knob props on alpha.16

**Comment by pho3nixf1re** [comment]
Is there a workaround for this?

**Comment by igor-dv** [comment]
Knobs are using https://github.com/component/escape-html package to escapes ", `', &, <, and >. ` 

To prevent escaping you can use it like this:

```js
storiesOf(...)
  .add('name', () => {}, {
    knobs: {
      escapeHTML: true
    }
  })
```

**Comment by pho3nixf1re** [comment]
This can be applied globally by passing it to the decorator setup.

```js
addDecorator(
  withKnobs({
    escapeHTML: false,
  })
);
```

**Comment by aminimalanimal** [comment]
fwiw, with the new exported story format, it goes under `parameters`:

```js
export default {
  title: 'Base Component',
  component: { BaseComponent },
  decorators: [withKnobs],
  parameters: {
    knobs: {
      escapeHTML: false,
    },
  },
}
```

**Comment by evans** [comment]
I found adding the following to `.storybook/preview.js` gave me back the functionality of https://github.com/storybookjs/storybook/issues/4445#issuecomment-434775097

```
const parameters = {
  knobs: {
    escapeHTML: false,
  },
};
```

[storybook docs for global parameters](https://storybook.js.org/docs/react/writing-stories/parameters#global-parameters)
