### ISSUE TITLE
Hierarchy Root Separating

### ISSUE THREAD

**Issue by Oddisey** [storybooks/storybook#4463]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I have put the hierarchyRootSeparator in my config.js the same way as the 3.4.11 example does and then add a pipe character into the `storiesOf` function call and it does not do the hierarchy separating.

The story title looks like "Forms|Form Elements"

### Steps to reproduce
run the server

### Please specify which version of Storybook and optionally any affected addons that you're running

    "@storybook/addon-actions": "3.4.11",
    "@storybook/addon-knobs": "3.4.11",
    "@storybook/addon-links": "3.4.11",
    "@storybook/addon-notes": "3.4.11",
    "@storybook/addon-options": "3.4.11",
    "@storybook/addon-storyshots": "3.4.11",
    "@storybook/addon-storysource": "3.4.11",
    "@storybook/addons": "3.4.11",
    "@storybook/angular": "3.4.11",

### Affected platforms 

- Not sure if this is dependency related or UI related.

### Screenshots / Screencast / Code Snippets (Optional)

```
// config.js
import { configure } from '@storybook/angular';
import { setOptions } from '@storybook/addon-options';

setOptions({
    hierarchyRootSeparator: /\|/
});

function loadStories() {
    require("../../libs/style-guide/src/lib/stories");

    // automatically import all story ts files that end with *.stories.ts
    const req = require.context('../../libs/style-guide/src/lib/', true, /\.stories\.ts$/);
    req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

```
//story sample
storiesOf("Forms|Form Elements/Date/Date Range", module)
```

End bug report support request - delete the rest below

**Comment by igor-dv** [comment]
Did you register the addon in `addons.js` ?

**Comment by wgrabowski** [comment]
@igor-dv of course I didn't

**Comment by wgrabowski** [comment]
I believe this issue should be closed

**Comment by igor-dv** [comment]
=)
