### ISSUE TITLE
Storybook knob url parameters not setting state in /iframe.html

### ISSUE THREAD

**Issue by mattrlong** [storybooks/storybook#4468]
### Bug or support request summary

When access `/iframe.html` the knob values are not being passed to the component that's rendered. When supplied to the full storybook ui's url they are setting the knobs values and the underlying components state is updated appropriately. 

### Steps to reproduce

Render story using following iframe url structure:

`[story_book_baserurl]/?selectedKind=[value]&selectedStory=[value]&knob-[key]-[value]` <- knobs set and component rendered as expected. 

`[story_book_baserurl]/iframe.html?selectedKind=[value]&selectedStory=[value]&knob-[key]-[value]` <- component not rendered in same state as above. 

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-alpha.24
- @storybook/addon-knobs 4.0.0-alpha.24

**Comment by mattrlong** [comment]
Related to https://github.com/storybooks/storybook/issues/1813

**Comment by evexoio** [comment]
@mattrlong any updates on this?
