### ISSUE TITLE
Not able to setup storyshot onto storybook with addon-storyshot for Vue app generated by vue cli 3

### ISSUE THREAD

**Issue by adamchenwei** [storybooks/storybook#4484]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

_Please provide issue details here - What did you expect to happen? What happened instead?_ 
What expect
Build stories as snapshot test correctly

What happened
I encounter error when I start running the jest after completely setup
### Steps to reproduce
git clone git@github.com:adamchenwei/vue-storybook-n-storyshots.git
(https://github.com/adamchenwei/vue-storybook-n-storyshots)
yarn jest

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

<img width="1039" alt="screen shot 2018-10-19 at 9 37 32 am" src="https://user-images.githubusercontent.com/4201698/47221550-aa3af580-d382-11e8-96b9-e7417ab021f3.png">

### Please specify which version of Storybook and optionally any affected addons that you're running

```json
    "@storybook/addon-storyshots": "^3.4.11",
    "@storybook/vue": "^3.4.11",
    "@vue/cli-plugin-babel": "^3.0.5",
    "@vue/cli-plugin-eslint": "^3.0.5",
    "@vue/cli-plugin-unit-jest": "^3.0.5",
    "@vue/cli-service": "^3.0.5",
    "@vue/test-utils": "^1.0.0-beta.20",
    "babel-core": "^6.26.3",
    "babel-jest": "^23.0.1",
    "jest-vue-preprocessor": "^1.4.0",
    "vue-template-compiler": "^2.5.17"
```

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
MacOS X
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_
Vue with Storybook and Storyshot

**Comment by igor-dv** [comment]
`yarn test` doesn't run Jest for you.

**Comment by adamchenwei** [comment]
@igor-dv sorry if my screenshot was confusing. I ran `yarn jest`

**Comment by igor-dv** [comment]
Can you please share your test file and jest.config ?

**Comment by igor-dv** [comment]
I've checked your repo, and couldn't find there any jest.config  and test that contains Storyshot (in all 3 branches)

**Comment by igor-dv** [comment]
Adding `babel-preset-vue` and changing setting it to .babelrc instead of `@babel/app` fixes the problem. I don't know though how it affects your app. There is some kind of versions mismatch between babel, vue, and storybook. 

CC #4475
