### ISSUE TITLE
storybook does not use NODE_PATH from .env for building code

### ISSUE THREAD

**Issue by vadzim-revolist** [storybooks/storybook#4496]
After upgrading from `4.0.0-alpha.24` to `4.0.0-rc.1` storybook stopped loading `.env` file.
I'm using CRA and there is NODE_PATH variable that is needed to compile source.
I've solved the problem by adding `env $(cat .env)` to the storybook scripts in package.json, but could someone please tell is that a bug or a feature? Will storybook support `.env` file in the future?
Sorry, I've not found any info in the documentation... (

**Comment by igor-dv** [comment]
@pksunkara , @ndelangen , could it be related to the recent env loading changes ?

**Comment by pksunkara** [comment]
Possibly. But loading from `.env` is working as we have chromatic based tests for this.

**Comment by vadzim-revolist** [comment]
@pksunkara It's weird :(

**Comment by vadzim-revolist** [comment]
@pksunkara @igor-dv 
I've created test repo.
https://github.com/vadzim/test-storybook

`yarn start` works as expected

`yarn storybook` does not work

`env $(cat .env) yarn storybook` runs storybook

**Comment by ndelangen** [comment]
@vadzim-revolist Have you tried this with anything other then NODE_PATH?

**Comment by vadzim-revolist** [comment]
@ndelangen I've tried just now.
Actually it reads `.env` file and passes all the content of it into storybook js, but does not use NODE_PATH from `.env` to build storybook itself.
If I set NODE_PATH from command line like `NODE_PATH=src yarn storybook` then it works.

**Comment by vadzim-revolist** [comment]
On rc-3 this error still persists

**Comment by pksunkara** [comment]
Related discussion, https://github.com/facebook/create-react-app/issues/2230
