### ISSUE TITLE
Deprecated Warnings in Storybook Examples

### ISSUE THREAD

**Issue by teckliew** [storybooks/storybook#4501]
### Bug or support request summary
In the examples, there are deprecated warnings like `default export of @strorybook/addon-backgrounds` or `withKnobsOptions` in all the examples.

### Steps to reproduce
Run any examples (for example: `cra-kitchen-sink` or `official-storybook`). There are deprecation warnings in the console:
<img width="872" alt="screen shot 2018-10-19 at 5 58 21 pm" src="https://user-images.githubusercontent.com/8940009/47249510-f90b7e00-d3c8-11e8-9601-f32118c3d73f.png">

### Please specify which version of Storybook and optionally any affected addons that you're running
- `v4.0.0-rc.1`

### Additional notes
I started some of the clean up here (https://github.com/storybooks/storybook/compare/master...teckliew:examples/deprecation-cleanup) but there are some issues...

Such as replacing `setOptions({ selectedAddonPanel: 'storybook/notes/panel' })` to `withOptions({ selectedAddonPanel: 'storybook/notes/panel' })` in `../examples/cra-kitchen-sink/src/stories/index.stories.js` that'll give this warning:
<img width="1290" alt="screen shot 2018-10-19 at 6 36 58 pm" src="https://user-images.githubusercontent.com/8940009/47249865-0e36db80-d3ce-11e8-986d-c5f2fd4fbfdb.png">

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.8 containing PR #6134 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
