### ISSUE TITLE
JS Stacktrace caused by error in CSS

### ISSUE THREAD

**Issue by ecbrodie** [storybooks/storybook#4512]
### Bug summary

A CSS error will cause the Storybook process to crash with a JS Stacktrace

### Steps to reproduce

1. Have a Storybook process running in a terminal tab with working code
1. Cause a CSS error. For example, if I am in the middle of extending a rule for a single CSS selector to be applied to two selectors and I press save without separating the selectors with a comma.
1. Observe the Storybook process crash. Here's an example stacktrace:

```
<--- Last few GCs --->

[21076:0x102801e00]  4013250 ms: Mark-sweep 1385.7 (1445.9) -> 1385.7 (1445.9) MB, 287.1 / 0.0 ms  allocation failure GC in old space requested
[21076:0x102801e00]  4013609 ms: Mark-sweep 1385.7 (1445.9) -> 1385.6 (1410.4) MB, 359.5 / 0.0 ms  last resort GC in old space requested
[21076:0x102801e00]  4013969 ms: Mark-sweep 1385.6 (1410.4) -> 1385.6 (1410.4) MB, 359.8 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x248c462a5879 <JSObject>
    2: replace(this=0x248c04aff501 <Very long string[569078]>,0x248c55ac5971 <String[32]: var HTML_WEBPACK_PLUGIN_RESULT =>,0x248cd8d02431 <String[0]: >)
    3: /* anonymous */ [/Users/evanbrodie/src/go/master/client/node_modules/html-webpack-plugin/index.js:224] [bytecode=0x248c861f1ad1 offset=39](this=0x248c5fc65679 <HtmlWebpackPlugin map = 0x248ce59ee0a9>,compilation=0x248c0845b989 <Tapable m...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/evanbrodie/.nvm/versions/node/v8.12.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/evanbrodie/.nvm/versions/node/v8.12.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/evanbrodie/.nvm/versions/node/v8.12.0/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Users/evanbrodie/.nvm/versions/node/v8.12.0/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/Users/evanbrodie/.nvm/versions/node/v8.12.0/bin/node]
 6: v8::internal::String::IndexOf(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, int) [/Users/evanbrodie/.nvm/versions/node/v8.12.0/bin/node]
 7: v8::internal::Runtime_StringIndexOfUnchecked(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/evanbrodie/.nvm/versions/node/v8.12.0/bin/node]
 8: 0x2c5589b842fd
 9: 0x2c5589bede22
10: 0x2c5589be881c
11: 0x2c5589c3d1d6
```

### Storybook versions

- @storybook/react 3.4.10
- @storybook/addon-actions 3.4.10
- @storybook/addon-knobs 3.4.10
- @storybook/addon-links 3.4.10
- @storybook/addon-storyshots 3.4.10
- @storybook/addons 3.4.10

### Affected platforms 

- Mac OS 10.13.6
- Node 8.12.0

Let me know what other information is required.

**Comment by igor-dv** [comment]
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` sounds like something that we can't take care of. 
It could be related to webpack / your css ramework / css loaders  versions. 

Anyway your are using the 3.4 release, and I am not sure that we have an intent to investigate this issue since we are at the end of the v4 release. Could you please check the latest v4.rc and let us know if the issue still exists?

**Comment by ecbrodie** [comment]
Makes sense. Feel free to close. I'll either request this issue to be reopened or make a new one if I run into the same problems in v4.

**Comment by igor-dv** [comment]
👌
