### ISSUE TITLE
React demo components incompatible with Storyshots default setup

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#4523]
### Bug or support request summary

Currently the SB4 CLI adds `Button`/`Welcome` components from `@storybook/react`:

```
import { Button, Welcome } from '@storybook/react/demo';
```

These components use `emotion`, which makes them themable (and probably overly complex for a default?). But they are also apparently incompatible with the default setup for `storyshots.test.js`:

```js
import initStoryshots from "@storybook/addon-storyshots";
initStoryshots();
```

This results in the error:
```
  TypeError: Cannot read property 'theme' of undefined
...
```

The `official-storybook` gets around this by using `enzyme as the renderer:

```js
import initStoryshots, {
    multiSnapshotWithOptions
} from "@storybook/addon-storyshots";
import { render as renderer, configure } from "enzyme";
import Adapter from "enzyme-adapter-react-16";
import { createSerializer } from "enzyme-to-json";

configure({ adapter: new Adapter() });
initStoryshots({
    test: multiSnapshotWithOptions({ renderer }),
    snapshotSerializers: [createSerializer()]
});
```

However, this is complex and not documented. So we should either:
1. Change the CLI to not use demo components that use `emotion`
2. Change the docs to help people use Enzyme or some other trick to get theming working out of the box

**Comment by ndelangen** [comment]
Let's dumb there dummy components down
