### ISSUE TITLE
Add definitely typed typings for v4.0 release

### ISSUE THREAD

**Issue by abbottdev** [storybooks/storybook#4526]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

When creating a new storybook project using the typescript option via the CLI, there are a few areas where the typings are missing. (Or I'm missing something!)

### Steps to reproduce

- Create new storybook project using cli
- Select TypeScript as language
- Try to use `addParameters` in a story 

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 4.0.0-rc.2
- @storybook/addon-knobs 4.0.0-rc.2

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```
End bug report support request - delete the rest below

**Comment by igor-dv** [comment]
We are not maintaining types in the definitely typed repo. 
Closing this in favor of #3206
