### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/ProjectFolder/node_modules/@storybook/core/dist/server/public/index.html'

### ISSUE THREAD

**Issue by lu4** [storybooks/storybook#4542]
### Missing @storybook/core/dist/server/public/index.html for storybook v4.0.0-rc.3 with custom webpack config (full-control mode) (Mac OS High Sierra 10.13.6 / Google Chrome 69.0.3497.100)

I'm working on a React project **that was not created using Create React App**. We use WebPack ^4.4.1 which does not work with storybook versions 3.3.4-3.3.11

That's why I've tried to use storybook `v4.0.0-rc.3`. Generally `rc.3` it took away most of the problems that I was facing with earlier rc's / alphas of `v4.0.0`. But it also uncovered new one which is just probably caused by my misunderstanding of proper storybook configuration.

Generally the webpack build goes fine but when I'm trying to access storybook via browser I get this unformatted node error:

`Error: ENOENT: no such file or directory, stat '/MyProjectDir/node_modules/@storybook/core/dist/server/public/index.html'`

[Here's screenshot](https://i.imgur.com/pPEwgt1.png)

I've checked this `node_modules/@storybook/core/...` folder and it does really lack both folder and file `public/index.html`. 

[Here's screenshot](https://i.imgur.com/34aJWij.png)

Here is my `webpack.config.js` from `.storybook` folder:

```const ExtractTextPlugin = require('extract-text-webpack-plugin');
const autoprefixer = require('autoprefixer');

module.exports = function(env, argv) {
  return {
    mode: 'development', // env === 'development' ? 'development' : 'production',
    devServer: {
      port: 3000,
      historyApiFallback: true,
    },
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          loader: 'babel-loader',
          include: /node_modules\/ui-framework\//,
          options: {
            presets: ['env', 'react'],
            plugins: ['transform-object-rest-spread', "babel-plugin-transform-decorators-legacy"],
            cacheDirectory: true,
            sourceMaps: 'inline',
          },
        },
        {
          test: /\.(js|jsx)$/,
          loader: 'babel-loader',
          exclude: /node_modules/,
          options: {
            presets: ['env', 'react'],
            plugins: ['rewire', 'transform-object-rest-spread', "babel-plugin-transform-decorators-legacy"],
            cacheDirectory: true,
            sourceMaps: 'inline',
          },
        },
        {
          test: /\.css/,
          use: [
            'style-loader',
            'css-loader',
            {
              loader: 'postcss-loader',
              options: {
                plugins: () => [
                  autoprefixer({
                    browsers: [
                      '>1%',
                      'last 4 versions',
                      'Firefox ESR',
                      'not ie < 9',
                    ],
                  }),
                ],
              },
            },
          ],
        },
        {
          test: /\.(sass|scss)$/,
          exclude: /node_modules/,
          use: ExtractTextPlugin.extract(['css-loader', 'sass-loader']),
        },
      ],
    },
    resolve: {
      extensions: ['.js', '.json', '.jsx'],
    },
    plugins: [
      new ExtractTextPlugin({
        filename: 'styles.css',
        allChunks: true,
      }),
    ],
    output: {
      publicPath: '/',
    },
  };
};
```

**Comment by igor-dv** [comment]
I didn't get if this setup worked before or not.

Can you please share the screen of SB output in console ?

**Comment by igor-dv** [comment]
Ok, I see now. Looks like your custom webpack config is wrong

if you are using the custom config as a **function** (full controll mode) it should look like this:

```js
module.exports = function (baseConfig, mode, defaultConfig) {
  // here you should extend baseConfig or defaultConfig and return it
  baseConfig.module.rules = [
    ...baseConfig.module.rules,
    // extend whatever rules
  ];

  return baseConfig;
}
```

In your case, you just return a config that doesn't even have any storybook entries

**Comment by lu4** [comment]
@igor-dv Ok, now I'm using rc.6, I've tried returning unmodified baseConfig, defaultConfig and their extended versions with our configuration. As a result I get one same error that originates in `addon-knobs`:

![image](https://user-images.githubusercontent.com/1069295/47492924-c6450800-d856-11e8-84a6-5dd21472d867.png)

**Comment by igor-dv** [comment]
Does it work without knobs?

**Comment by lu4** [comment]
No, it doesn't, the same error but different origin:
![image](https://user-images.githubusercontent.com/1069295/47499426-96066500-d868-11e8-9133-6e339fe26c7b.png)

I've tried debugging the error, it's hard though due to minification, from what I see is that react is not properly imported an error occurs due to `createContext` might be an object such as `undefined`, I can not inspect it, it's wrapped into __webpack_require__ call...

**Comment by igor-dv** [comment]
The problem is definitely coming from `@emotion`. 
Do you have any custom `.babelrc` in the `.storybook` dir?

**Comment by igor-dv** [comment]
Can you try changing the polyfill to `true` 🤔  ?

**Comment by lu4** [comment]
Nope, it didn't work, same issue same origin...

**Comment by igor-dv** [comment]
Do you have a reproduction somewhere ? I am out of ideas

**Comment by lu4** [comment]
No, the project is private, I can conduct a screen-sharing session, though I don't expect that you would be happy about such way of communication...

**Comment by lu4** [comment]
@igor-dv I will try to create a reproduction case and have it published somehow and then return back to you in this regard

**Comment by jmakGH** [comment]
@lu4 Not sure if this extends to your situation but what version of React are you using? I ran into this issue today but realized that the project I was working on was using an older version of React before the `createContext` API was added. Updating React past v16.3.0 helped solved this for me.
