### ISSUE TITLE
Uncaught ReferenceError: returnfalse is not defined

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#4543]
This is probably caused by some of the dependencies or by the fact that we use two minifiers (babel and uglify)

Here's the very minimal repro repo https://github.com/Hypnosphi/returnfalse-repro/tree/master

**Comment by Hypnosphi** [comment]
An issue for babel/minify: https://github.com/babel/minify/issues/920

**Comment by Hypnosphi** [comment]
Downgrading webpack to `~4.21.0` helps

**Comment by Hypnosphi** [comment]
Fixed in `webpack@4.23.1`, let's upgrade to that

**Comment by shilman** [comment]
Confirmed fixed in repro repo
