### ISSUE TITLE
Changing Styles of Side Panel Only

### ISSUE THREAD

**Issue by MansoorBashaBellary** [storybooks/storybook#4545]
Is there any way in Storybooks to change Stylings of SidePanel where I navigate through different stories. Stylings such as:

- Changing background color of SidePanel only
- Changing font sizes of SidePanel only
- Changing Spacings of SidePanel

I have tried to apply it through themes of StoryBook options through changing `mainBackground` option, but that changes background color of entire storybook. Is there any option so that I can change styles of only SidePanel. Help will be appreciated.

**Comment by igor-dv** [comment]
Here are the docs for theming:

https://storybook.js.org/configurations/theming/

**Comment by anil-hulkapps** [comment]
Add this in manager-head.html
```
.sidebar-container * { /* This will target all of the children */
  font-size: 110% !important;
}
```

I have changed font size of sidebar stories title like this..you can target different class and use css..
