### ISSUE TITLE
4.0.0-rc.6: knob "select" with a simple array only shows a "k" option

### ISSUE THREAD

**Issue by danielg2002** [storybooks/storybook#4560]
select("locale", ["es", "en"], "en")

- @storybook/4.0.0-rc.6

<img width="284" alt="storybook 2018-10-25 08-15-40" src="https://user-images.githubusercontent.com/11050021/47496753-33907300-d82e-11e8-89a4-af150cb07f0a.png">

**Comment by danielg2002** [comment]
@ndelangen FYI

**Comment by danielg2002** [comment]
@diagramatics  @ndelangen it still does not work on 4.0.0

**Comment by teddybradford** [comment]
I'm running into the same issue. I don't think this was actually fixed. :(

**Comment by diagramatics** [comment]
Just checked, turns out the PR isn't cherry picked in `4.0.0`. @shilman do you mind revisiting this for us?

**Comment by Drapegnik** [comment]
@danielg2002 @teddybradford @diagramatics, temporarily fixed it https://github.com/ds300/patch-package

`patches/@storybook/addon-knobs+4.0.0.patch`:

```diff
patch-package
--- a/node_modules/@storybook/addon-knobs/dist/components/types/Select.js
+++ b/node_modules/@storybook/addon-knobs/dist/components/types/Select.js
@@ -21,7 +21,7 @@ var SelectType = function SelectType(_ref) {
   var options = knob.options;
   var entries = Array.isArray(options) ? options.reduce(function (acc, k) {
     return Object.assign(acc, {
-      k: k
+      [k]: k
     });
   }, {}) : options;
   var selectedKey = Object.keys(entries).find(function (k) {
```

**Comment by shilman** [comment]
@diagramatics I'll get it into a release today.
