### ISSUE TITLE
knobs with react-native: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by mimamuh** [storybooks/storybook#4562]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
Get the following error trying to run the knobs plugin with react native:

```
Cannot read property 'emit' of undefined
<unknown>
    KnobManager.js:128:22
<unknown>
    JSTimers.js:256:17
_callTimer
    JSTimers.js:152:6
Object.callTimers
    JSTimers.js:405:6
MessageQueue.__callFunction
    MessageQueue.js:349:41
<unknown>
    MessageQueue.js:106:11
MessageQueue.__guard
    MessageQueue.js:297:8
MessageQueue.callFunctionReturnFlushedQueue
    MessageQueue.js:105:9
<unknown>
    debuggerWorker.js:72:58
```

Story
```js
storiesOf('AIconMaterial', module)
	.addDecorator(getStory => <CenterView>{getStory()}</CenterView>)
	.add('default', () => (
		<AIconMaterial
			theme={text('theme', 'normal')}
		/>
	));
```

I'm not sure if I do something wrong. It is not super clear in the docs if I need to have both addons, the normal one `import '@storybook/addon-knobs/register';` and the device specific one with `import '@storybook/addon-ondevice-knobs/register';`. But anyway, I had the issue with both setups.

### Steps to reproduce

Check this [simple repro here:](https://github.com/mimamuh/storybook-issue-4562)
1. Run `yarn run start`
2. Run `yarn run storybook`
3. Run `yarn run ios:emulator:iphone6`
4. Navigate to one of the button stories and make sure to switch to the fullscreen view.

### Please specify which version of Storybook and optionally any affected addons that you're running

"@storybook/addon-actions": "^v4.0.0-rc.6",
"@storybook/addon-knobs": "^v4.0.0-rc.6",
"@storybook/addon-links": "^v4.0.0-rc.6",
"@storybook/addon-ondevice-knobs": "^4.0.0-rc.6",
"@storybook/addons": "^v4.0.0-rc.6",
"@storybook/react-native": "^v4.0.0-rc.6",

### Affected platforms 

- ios/android

**Comment by Gongreg** [comment]
Hey @mimamuh, I am looking into it. Thank you very much for creating a demo for the issue.

**Comment by Gongreg** [comment]
Hey,
Seems like you forgot to add knobs decorator in your stories.

```
import React from "react";
import { withKnobs } from '@storybook/addon-knobs';
import { storiesOf, addDecorator } from "@storybook/react-native";
import { text } from "@storybook/addon-knobs";

...

addDecorator(withKnobs);

storiesOf("Button", module)
	...
```

**Comment by mimamuh** [comment]
Oh no, sorry. Thx for help!

**Comment by Gongreg** [comment]
No problem. I am really glad you are trying things out. If you have any suggestions they are really welcome.

**Comment by mimamuh** [comment]
Hi @Gongreg, I added the decorator today and upgraded to `4.0.4` but still have the same error when using the knob.

**Comment by Gongreg** [comment]
@mimamuh, can you update example repo with your latest code? I can look into it.

**Comment by mimamuh** [comment]
I already did it. :) [Here is the repro.](https://github.com/mimamuh/storybook-issue-4562)

**Comment by Gongreg** [comment]
hey @mimamuh, make sure to set up decorators before setting the stories.

So if you write:

```
// global decorators
addDecorator(withKnobs);

// import stories
configure(() => {
  require("./../src/stories");
}, module);
```

it will work.
