### ISSUE TITLE
Breakpoints or Source Maps not working properly in Chrome

### ISSUE THREAD

**Issue by mindjuice** [storybooks/storybook#457]
I'm using Storybook for some components, but breakpoints are not working correctly in Chrome Dev Tools.

I was able to reproduce the same issue in the[`kadira-samples/react-storybook-demo`](https://github.com/kadira-samples/react-storybook-demo) app with no modifications (the Todos app sample).  Just clone it from github, do `npm i` and `npm run storybook` and open your browser to `localhost:9001`.

If I open `TodoItem.js` in the Chrome Dev Tools "Source" tab, and put a breakpoint on the first line of `render()`, then make a change in Storybook that causes a TodoItem to need to re-render (e.g., mark one as complete), the debugger "breaks", but the file that Chrome Dev Tools shows has the name `?d41d`, and the contents of the file is just the following:

```
undefined


/** WEBPACK FOOTER **
 ** 
 **/
```

Switching over to `TodoItem.js` has no effect, and single stepping just continues execution.

Anyone else have debugging working in Storybook?

**Comment by arunoda** [comment]
I've also seen this issue.
Would love to work on this.

**Comment by jennylia** [comment]
@arunoda Could you please add this feature, it would help me (and others) so much to learn React. <3

**Comment by nikhilbaradwaj** [comment]
https://github.com/FountainJS/generator-fountain-webapp/issues/129

**Comment by nikhilbaradwaj** [comment]
https://github.com/webpack/webpack/issues/2145 has the discussion and temporary fix.

**Comment by arunoda** [comment]
@nikhilbaradwaj Thanks for the reference.

**Comment by jennylia** [comment]
@nikhilbaradwaj Thanks but this did not fix the problem of being able to stop on debug points, but not being able to see which javascript line the code is "breaks" on for me. I still see @mindjuice error earlier.

**Comment by jennylia** [comment]
@arunoda I changed node_modules/@kadira/storybook/dist/server/webpack.config.js to use devtool: 'inline-source-map' instead of  devtool: '#cheap-module-eval-source-map' and this problem was resolved. Technically, I don't like to change config files in node_modules. I think maybe we can do something to the webpack.config file? Changing it in node_module not the best idea, it usually gets gitignored.

**Comment by ndelangen** [comment]
If you are still experiencing this issue please re-open 👍

**Comment by knaos** [comment]
I am having this issue when developing a react storybook.

**Comment by ndelangen** [comment]
What version are you using @knaos ?

**Comment by dagatsoin** [comment]
Still an issue on 4.1.6

**Comment by markov00** [comment]
@dagatsoin I'm currently on 4.1.11 and it's just a matter of adding the following on your storybook webpack config:
```js
  config.devtool = 'inline-source-map';
```

**Comment by trianta2** [comment]
Thanks @markov00 , your solution worked for me. For those like me who are still new to storybook, follow [this example](https://storybook.js.org/docs/configurations/custom-webpack-config/#examples) to update the storybook webpack config.
