### ISSUE TITLE
Support <> React.Fragment tags

### ISSUE THREAD

**Issue by jasperdunn** [storybooks/storybook#4576]
### Steps to reproduce

Use latest version of create-react-app and react, latest versions allow for <> and </> in place of <React.Fragment>

- @storybook/react 3.4.11

```
ERROR in ../path/to/file.jsx
Module build failed: SyntaxError: Unexpected token (6:5)

> 6 |     <>
```

**Comment by igor-dv** [comment]
Only SB v4 will support CRA2 + latest React versions.
