### ISSUE TITLE
Feature request: get all stories via global var

### ISSUE THREAD

**Issue by Diokuz** [storybooks/storybook#4588]
Hey, guys! I have a problem: I want to check all stories in my storybook with puppeteer, but I dont have a stories list, something like that:

```js
const storiesList = [ { selectedStory: 'Story', selectedKind: 'Blocks/test-a' },
      { selectedStory: 'Story', selectedKind: 'Blocks/test-b' },
      { selectedStory: 'Story', selectedKind: 'Blocks/qwe/asd/zxc' },
      { selectedStory: 'Story 2', selectedKind: 'Blocks/qwe/asd/zxc' },
      { selectedStory: 'Story 3', selectedKind: 'Blocks/qwe/asd/zxc' },
      { selectedStory: 'Story', selectedKind: 'Blocks/sss/zxc' },
      { selectedStory: 'Story 2', selectedKind: 'Blocks/sss/zxc' },
      { selectedStory: 'Story 3', selectedKind: 'Blocks/sss/zxc' } ]
```
(or any other format)

Your addon `storyshots` has an approach, which doesnt fit my needs: it parses all *.story.js files and creates stories list from them.

Is there any possibility to extract `storiesList` from built and launched storybook instance?

Right now I have to _click()_ each menuitem to expand them, and then walk on DOM tree to find all stories, but that 1) takes some extra time 2) could fail after next storybook upgrade.

Thanks!

**Comment by Diokuz** [comment]
My walker)

```js
      const selectedKind = await page.evaluate(el => {
        let arr = []
        let parent = el

        while (parent !== document.body) {
          parent = parent.parentNode

          if (parent.tagName === 'LI') {
            const menuitem = parent.querySelector(':scope > [role="menuitem"]')

            if (menuitem) {
              arr.unshift(menuitem.innerText.trim())
            }
          }
        }

        return arr
      }, story)
```

**Comment by igor-dv** [comment]
I think @tmeasday has something about it.

**Comment by tmeasday** [comment]
@Diokuz this should work in SB3.4+:

```js
__STORYBOOK_CLIENT_API__._storyStore.getStorybook().map(({ kind, stories }) => {
  stories.map(({ name }) => {
    // kind, name define the story.
    // you can get other details with e.g. `storyStore.getStoryAndParameters(kind, name)`
  })
})

**Comment by tmeasday** [comment]
We'll probably add a new API sometime that makes this slightly simpler too.

**Comment by SkReD** [comment]
> __STORYBOOK_CLIENT_API__._storyStore.getStorybook

There is no such method in store. __STORYBOOK_CLIENT_API__ itself has such method
