### ISSUE TITLE
Storybook should prompt user when it runs on a different port

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#4602]
**Is your feature request related to a problem? Please describe.**

In SB4, storybook was improved to run on a different port if the desired port is busy, inspired by CRA. However it's confusing when you're expecting it to be running on port X and it's running on port Y.

**Describe the solution you'd like**

Storybook should prompt the user when it switches ports, like CRA does:

<img width="471" alt="1__node_and_index_js_ _storybook" src="https://user-images.githubusercontent.com/488689/47628048-9fe0de80-db6e-11e8-82f8-efe360ac368b.png">

**Are you able to assist bring the feature to reality?**

Yes, but I'd love it if somebody else could take this.

**Comment by mpaarating** [comment]
I'm interested in working on this. What's the desired functionality if the user doesn't want to run the app on a different port? Should it exit?

**Comment by Armanio** [comment]
Hi @mpaarating! If you didn't change your mind and its feature request its actually: yes if user choice "no" app should be an exit. 
Let me know if you want to start working about this.
Thank you!

**Comment by mpaarating** [comment]
@Armanio great! I'll start working on this!

**Comment by mpaarating** [comment]
@shilman I think this feature already exists. If not, can you provide a bit more detail about the change you'd like to see?

Current behavior:
[![Image from Gyazo](https://i.gyazo.com/970282c753125c79601443669bdecac3.png)](https://gyazo.com/970282c753125c79601443669bdecac3)

**Comment by shilman** [comment]
Hmm, looks like it got added, or maybe I goofed!? Anyway thanks for investigating @mpaarating 👍

**Comment by basickarl** [comment]
@shilman Is it possible to automatically accept the new port number with a flag such as `--yes` for example?
