### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js): TypeError: Property name expected type of string but got null

### ISSUE THREAD

**Issue by Zwerge** [storybooks/storybook#4615]
Ever since upgrading to CRA 2.0.5 and storybook 4.x.x I have been getting this error. This was working in the previous version of storybook. 

I have narrowed the issue down to destructuring an await will make the build fail.
(NOT WORKING)

```
const { data } = await login({ username, password: encryptedPassword })
```
```
const res = await login({ username, password: encryptedPassword })
const { data } = res
```

While if I re-write to:
(Working)
```
      const res = await login({ username, password: encryptedPassword })
      const data = res.data
```

**Comment by shilman** [comment]
@Zwerge just released a new version that should solve your issue. Mind testing it out for me? https://github.com/storybooks/storybook/releases/tag/v4.1.0-alpha.8 Feel free to re-open this if it's still a problem.

**Comment by divmgl** [comment]
I'm having this exact same issue. @shilman I see the storybook release that fixes it, but I'm not sure which of the patches addresses this particular bug.

**Comment by divmgl** [comment]
To anyone who is seeing this in the future:

Don't use `babel-polyfill` in your `webpack` configuration. Instead, add the Babel runtime and run your `async/await` transforms through there:

```
$ npm install @babel/runtime
```

```
plugins: [
  [
    '@babel/plugin-transform-runtime',
    {
      regenerator: true
    }
  ]
}
```
