### ISSUE TITLE
Non transparent background in full screen mode

### ISSUE THREAD

**Issue by 454de6e** [storybooks/storybook#4620]
**Describe the bug**
I use Storybook full screen mode for visual regression testing, i.e. I take screenshots of components displayed in full screen mode. Storybook v4 creates and semi transparent background in full screen mode. This interferes with visual regression testing, because you can see the normal UI semi transparently in full screen mode. To solve the issue I tried modifying the `overlayBackground` variable of the `normal` theme. It looks like this variable applies to the keyboard shortcut overlay only, but it has no effect on full screen mode.

**To Reproduce**
Go in Full screen mode and you will see the normal UI semi transparent in the background.

**Expected behavior**
Either a non transparent white background in the normal theme or a theme variable to change the background appearance in full screen mode.

**Comment by igor-dv** [comment]
You can try adding `preview-head.html` with css changing body's background to white.

**Comment by mdotasia** [comment]
Your suggested workaround works. The question is: should current behavior of showing semi-transparent background be default or not.

Related: https://github.com/storybooks/storybook/issues/4646

**Comment by igor-dv** [comment]
I am not sure what was it for, at the beginning (you can try to find this in a git history maybe) ... Anyway there is a big UI change (#4086) coming soon, so I am not sure we will invest in fixing this

**Comment by StevenFewster** [comment]
sorry for jumping in on this issue, but where exactly do you put the preview-head.html file, as currently I've got it under .storybook, src and src/stories and can't get it to pick up?!  Documentation says 

> You can do this very easily. Simply create a file called preview-head.html inside the Storybook config directory

but as config.js is a file, I'm assuming this is the .storybook folder, but that's not working.  All help gratefully received.

**Comment by igor-dv** [comment]
it should be located under the `.storybook` dir
