### ISSUE TITLE
@storybook/addon-knobs not rendering Dropdowns and Text areas as expected in 4.0.0

### ISSUE THREAD

**Issue by MansoorBashaBellary** [storybooks/storybook#4621]
When I started updating `@storybook/addon-knobs` version to `4.0.0`, observed some issues with Dropdowns and Text areas of `addon-knobs`.

**Issue with Dropdowns:**

I am trying to do something like below:

`import { select } from '@storybook/addon-knobs';`

And in my story, I am adding knobs with dropdowns like:

`select('Dropdown 1', ['', 'top', 'bottom'], 'top')`

Here I am using options of `Array type`. On using options of `Array type`, the rendered dropdowns just have a output of `k` value like below:

![screen shot 2018-10-29 at 4 17 21 pm](https://user-images.githubusercontent.com/42977064/47678297-d0893e00-db97-11e8-8d33-55236a5f6f5e.png)

If I use options of `Object` type then it works fine. It does not work fine with `Array` type only. I guess that is happening because of the `reduce` function used in the file `@storybook/addon-knobs/src/components/types/Select.js` like:

`options.reduce((acc, k) => Object.assign(acc, { k }), {})`

**Issue with TextAreas:**

I am trying to do something like below:

`import { text } from '@storybook/addon-knobs';`

And in my story, I am adding knobs with text areas like:

`text('message', '<ul><li>This is some lorem ipsum foo bar content.</li></ul>')`

Above text is not escaping the `html tags`. Screenshot for the same is:

![screen shot 2018-10-29 at 4 18 11 pm](https://user-images.githubusercontent.com/42977064/47678876-31654600-db99-11e8-91c0-344e66bebab9.png)

**Comment by diagramatics** [comment]
Re: dropdowns, you're absolutely right, that was it. #4560 was the duplicate to your issue and I made the fix earlier (#4586), it just hasn't landed in `4.0.0`.

**Comment by shilman** [comment]
This got fixed in `4.0.1`, closing!
