### ISSUE TITLE
@storybook/ember still has missing dependencies

### ISSUE THREAD

**Issue by joelcox** [storybooks/storybook#4639]
**Describe the bug**
I tried adding @storybook/ember": "^4.0.0" to an existing Ember project and still had to add babel-loader and @babel/core to my dependencies to get Storybook running.

**To Reproduce**
1. Go to an existing Ember project
2. Install Storybook (`yarn add @storybook/ember`)
3. Add `"storybook": "start-storybook -p 9001 -s dist"` to your `package.json`
4. Run storybook (`yarn storybook`)
5. 
```
➜ yarn storybook
yarn run v1.10.1
$ start-storybook -p 9001 -s dist
info @storybook/ember v4.0.0
info
info => Loading static files from: /Users/path/web/dist .
info => Loading presets
ERR! Error: Cannot find module 'babel-loader/package.json' from '/Users/path/web'
ERR!     at module.exports (/Users/path/web/node_modules/resolve/lib/sync.js:43:15)
ERR!     at isBabelLoader8 (/Users/path/web/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:68:52)
ERR!     at _default (/Users/path/web/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:88:10)
ERR!     at Object.babel (/Users/path/web/node_modules/@storybook/core/dist/server/core-preset-dev.js:36:45)
ERR!     at accumulationPromise.then.newConfig (/Users/path/web/node_modules/@storybook/core/dist/server/presets.js:73:72)
ERR!     at <anonymous>
ERR!     at process._tickCallback (internal/process/next_tick.js:189:7)
ERR!  { Error: Cannot find module 'babel-loader/package.json' from '/Users/path/web'
ERR!     at module.exports (/Users/path/web/node_modules/resolve/lib/sync.js:43:15)
ERR!     at isBabelLoader8 (/Users/path/web/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:68:52)
ERR!     at _default (/Users/path/web/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:88:10)
ERR!     at Object.babel (/Users/path/web/node_modules/@storybook/core/dist/server/core-preset-dev.js:36:45)
ERR!     at accumulationPromise.then.newConfig (/Users/path/web/node_modules/@storybook/core/dist/server/presets.js:73:72)
ERR!     at <anonymous>
ERR!     at process._tickCallback (internal/process/next_tick.js:189:7)
ERR!   stack: 'Error: Cannot find module \'babel-loader/package.json\' from \'/Users/path/web\'\n    at module.exports (/Users/path/web/node_modules/resolve/lib/sync.js:43:15)\n    at isBabelLoader8 (/Users/path/web/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:68:52)\n    at _default (/Users/path/web/node_modules/@storybook/core/dist/server/loadCustomBabelConfig.js:88:10)\n    at Object.babel (/Users/path/web/node_modules/@storybook/core/dist/server/core-preset-dev.js:36:45)\n    at accumulationPromise.then.newConfig (/Users/path/web/node_modules/@storybook/core/dist/server/presets.js:73:72)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)',
ERR!   code: 'MODULE_NOT_FOUND' }
✨  Done in 2.11s.
```
**Expected behavior**
```
yarn run v1.10.1
$ start-storybook -p 9001 -s dist
info @storybook/ember v4.0.0
```

**Screenshots**
-
**Code snippets**
-

**System:**
 - OS: MacOS High Sierra 10.13.6 (17G2307)
 - Device: MacBook Pro
 - Browser: -
 - Framework: Ember.js
 - Addons: -
 - Version: 4.0.0

**Additional context**
Running `yarn add @babel/core babel-loader` seems to resolve the problem.

**Comment by igor-dv** [comment]
`babel-loader` is a peer dep for Storybook and `@babel/core` is a peer of the `babel-loader`. `@storybook/cli` does install them for you.

**Comment by joelcox** [comment]
@igor-dv Thanks! In that case the documentation for setting up an ember project seems to be inaccurate. `@storybook/cli` is not mentioned there.

https://storybook.js.org/basics/guide-ember/

**Comment by igor-dv** [comment]
PR to docs is incredibly appreciated 😉 

CC @gabrielcsapo

**Comment by joelcox** [comment]
Happy to do so, but adding @storybook/cli to my dependencies still did not resolve the issue. I noticed that @gabrielcsapo is doing some great work on the onboarding of existing ember apps which is progressing nicely :-)

**Comment by igor-dv** [comment]
> but adding @storybook/cli to my dependencies still did not resolve the issue

What do you mean by this? You don't need to add this to deps. just to run it once:

`npx -p @storybook/cli sb init`

**Comment by joelcox** [comment]
Got it. Thanks @igor-dv.
