### ISSUE TITLE
@storybook/angular shouldn't depend on zone.js

### ISSUE THREAD

**Issue by emilio-martinez** [storybooks/storybook#4641]
**Describe the bug**
Currently, @storybook/angular lists zone.js within its dependencies; however, (as far as I can tell) in practice @storybook/angular doesn't actually depend on it. Of course, [Angular does](https://angular.io/guide/npm-packages#support-packages) but perhaps it's worth removing it as a @storybook/angular dependency to avoid conflicts.

**To Reproduce**
See https://github.com/storybooks/storybook/blob/v4.0.0/app/angular/package.json#L44.

**Expected behavior**
 @storybook/angular shouldn't depend on zone.js if it doesn't use it.

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Browser: Chrome
 - Framework: Angular
 - Addons: none
 - Version: 4.0.0

**Additional context**
N/A

**Comment by kroeder** [comment]
@igor-dv @storybook/angular does not depend on it. Wasn't it core or something? We already had a discussion about zone.js

**Comment by emilio-martinez** [comment]
Sorry, re-read my description and realized it was very odd/poorly written 😅updated.

**Comment by igor-dv** [comment]
It's used in polyfills

https://github.com/storybooks/storybook/blob/master/app/angular/src/client/preview/angular-polyfills.js#L53

Do we really need these polyfills, though ?

**Comment by kroeder** [comment]
Well, this time zone.js isn't a dependency of a dependency (like webpack is just a dep of angular core). zone.js is a direct dep of angular - maybe we can put zone.js as peer dep and dev dep for development this time?

**Comment by emilio-martinez** [comment]
Peer dependency makes sense. The way I see it, Storybook should be pulling the version of zone.js already being used in the host Angular project anyway, unless there's a specific task Storybook is using zone.js for that differs from the rest of the project.

**Comment by igor-dv** [comment]
Wanna PR this ?

**Comment by emilio-martinez** [comment]
For sure. Opened!
