### ISSUE TITLE
Info addon doesn't renders component description

### ISSUE THREAD

**Issue by MihaChicken** [storybooks/storybook#4643]
### Bug or support request summary

I'm using Storybook with info-addon to auto create documentation based on Flow specification and jsdoc comments. The problem is that props table is displayed correctly but there is no component description. After debuging I found out that the problem is actually in this line:
https://github.com/storybooks/storybook/blob/master/addons/info/src/components/Story.js#L253
```js
if (STORYBOOK_REACT_CLASSES[key].name === context.story) {
     retDiv = <div>{STORYBOOK_REACT_CLASSES[key].docgenInfo.description}</div>;
}
```
This condition in `if` statement is never truthful because left side is a component name but right side is a story description (like 'bold centered text with no margins').
Changing the condition to: `if (STORYBOOK_REACT_CLASSES[key].name === context.kind) {` solves all the problems.

Could anyone please tell me is it a bug or am I doing something wrong?

- @storybook/react 4.0.0
- @storybook/addon-info 4.0.0

**Comment by shilman** [comment]
This certainly looks like a bug. @danielduan mind taking a quick look? @MihaChicken any chance you could put together a PR for this?

**Comment by MihaChicken** [comment]
@shilman Already done :)
https://github.com/storybooks/storybook/issues/4685

**Comment by shilman** [comment]
@MihaChicken dang guys, you're 5 steps ahead. 😲 Will get that out soon. Thanks for making it happen! 🙇

**Comment by shilman** [comment]
This just went out in https://github.com/storybooks/storybook/releases/tag/v4.0.9, closing!

Great work @MihaChicken 🎉
