### ISSUE TITLE
Can not resolve modules with absolute path in v4.0.0

### ISSUE THREAD

**Issue by SarantopoulosKon** [storybooks/storybook#4647]
**Describe the bug**
I upgraded storybook from version 4.0.0-alpha.25 to v.4.0.0 but i get errors like **Module not found: Error: Can't resolve ...** for all the modules that i have imported with absolute paths. In the migration guide i don't see any changes regarding absolute paths, am i missing something?

**Screenshots**
![image](https://user-images.githubusercontent.com/33217757/47730811-9a1cf300-dc6b-11e8-9ee4-9f7190b1adbe.png)

**System:**
 - OS: Windows10
 - Node: 10.7.0
 - Framework: react
 - Addons: actions, viewport, links, knobs
 - Version: 4.0.0

**Additional context**
I use create-react-app v.2

**Comment by igor-dv** [comment]
Do you have any custom webpack.config,js ?

**Comment by SarantopoulosKon** [comment]
@igor-dv no, just plain create-react-app v2 (not ejected) and i have a **.env** file in the root folder with `NODE_PATH=src` for absolute imports.

**Comment by igor-dv** [comment]
I think it's related to `NODE_PATH`, and not to the absolute imports. 
We have an open issue for this already - #4496, let's continue the discussion there. 

Anyway, you can workaround absolut imports by adding the custom webpack.confing.js:

```js
//.storybook/webpack.config.js

module.exports = {
  resolve: {
    modules: ['path to src dir'],
  }
}
```

**Comment by SarantopoulosKon** [comment]
Ok,

Btw running storybook with `cross-env NODE_PATH=src/ start-storybook -p 9009 -s public` it works, but i'd prefer not to have an extra dependency just for this.

Thank you for your time @igor-dv !

**Comment by igor-dv** [comment]
👍
