### ISSUE TITLE
Break apart webpack rule tests a bit

### ISSUE THREAD

**Issue by IanVS** [storybooks/storybook#4650]
**Is your feature request related to a problem? Please describe.**
It's a bit difficult to change the default webpack config (in full-power mode), because of the grouping of multiple filetypes into single rules.  For example, [this change](https://github.com/storybooks/storybook/commit/fa1e1b717bd71dd718ef7ed06d1f89cbd6112244) broke svgs in my storybook because I use `svg-react-loader` instead of a file loader.  Before that commit, I was finding the rule with a `test` including `.svg`, and changing the loader.  But after it got grouped into the `file-loader` test, my config broke, and I had to do something like this to remove it from the test:

```js
const svgFileLoaderRule = defaultConfig.module.rules.find(rule =>
    rule.test.toString().includes('svg') && rule.loader.includes('file-loader')
);
if (svgFileLoaderRule) {
    svgFileLoaderRule.test = new RegExp(svgFileLoaderRule.test.source.replace('svg|', ''));
}
```
Which is a bit clunky and feels even more brittle.

**Describe the solution you'd like**
My suggestion is to break out all rules into single filetypes, or at least tighter groupings, to make them easier to find/override in custom configs.

Taking the `file-loader` rule as an example, it might go from:

```js
{
    test: /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2)(\?.*)?$/,
    loader: require.resolve('file-loader'),
    query: {
        name: 'static/media/[name].[hash:8].[ext]',
    },
},
```

to

```js
{
    test: /\.svg(\?.*)?$/,
    loader: require.resolve('file-loader'),
    query: {
        name: 'static/media/[name].[hash:8].[ext]',
    },
},
{
    test: /\.(ico|jpg|jpeg|png|gif)(\?.*)?$/,
    loader: require.resolve('file-loader'),
    query: {
        name: 'static/media/[name].[hash:8].[ext]',
    },
},
{
    test: /\.(eot|otf|webp|ttf|woff|woff2)(\?.*)?$/,
    loader: require.resolve('file-loader'),
    query: {
        name: 'static/media/[name].[hash:8].[ext]',
    },
},
```

I'm not sure further resolution is needed / helpful, but at least grouping svg separately from images separately from fonts could for sure be useful.  

**Describe alternatives you've considered**
I guess the alternative is what I'm doing now.  But it was kinda tricky to figure out, and it might be easier for folks to deal with svg files their own way if it's split out on its own.

**Are you able to assist bring the feature to reality?**
Sure.

**Additional context**

**Comment by smashercosmo** [comment]
Relevant for me as well. I'm using svgr to include svg files as components, and now it's pretty hard to change config.

**Comment by smashercosmo** [comment]
Well, actually it's not that hard. Solved it like this:
```js
module.exports = (baseConfig, env, defaultConfig) => {
  const rules = defaultConfig.module.rules.filter(rule => {
    return !rule.loader || (rule.loader && rule.loader.indexOf('file-loader') === -1)
  })

  rules.push({
    test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2)(\?.*)?$/,
    loader: require.resolve('file-loader'),
    query: {
      name: 'static/media/[name].[hash:8].[ext]',
    },
  })
  rules.push({ /** my svg rules */ });
  defaultConfig.module.rules = rules
  return defaultConfig;
};
```
