### ISSUE TITLE
addon-info can not show class component struct

### ISSUE THREAD

**Issue by helios741** [storybooks/storybook#4659]
**Describe the bug**
i use [@storybook/addon-info](https://github.com/storybooks/storybook/tree/release/4.0/addons/info), 
I am writing a component in order to test my own components, if this component is function component is ok, but if it is a class component, it will not display the structure.

Because there is interaction, all use state.

``` jsx 
// function component
const component = () => (
    <div>
        <Switch>NO</Switch>
    </div>
)

``` 

show:
``` DOM
<div>
    <Switch>NO</Switch>
</div>
```

```
// class component
class pDSwitch extends Compoent {

  render() {
    return (<div><Switch>NO</Switch></div>)
  }

}
```

show: 
```DOM

<PdSwitch />
```

**System:**
 - OS: [ MacOS]
 - Device: [Macbook Pro 2017]
 - Browser: [ chrome]
 - Framework: [react]
 - Addons: [info]
 - Version: [3.4.11]

**Comment by VladimirPittner** [comment]
Hi @helios741 I guess you are doing something like this?
```
storiesOf('Switch', module)
  .add('Switch', () => <pDSwitch />);
```
which unfortunately kind of make sense that it will output only 
```
<PdSwitch />
```
because thats the JSX you return in the arrow function.
The same way in this case
```
<div>
    <Switch>NO</Switch>
</div>
```
does not show what you render inside of the `Switch`.

As much as I would also like to be able to access the rendered JSX from class component (specially when its only to mock the state) I could not find a way for that.

**Comment by helios741** [comment]
@VladimirPittner yes, as you said. i can only copy jsx in the readme now.  do you have any better plans?

**Comment by VladimirPittner** [comment]
@helios741 Well it depends on how your component, which you are writing, is working. If you are accessing the `storyFn` and try to read that I am not sure if I can help. But ... for example

I am using our own (custom) component (combo of react-element-to-jsx-string and react-syntax-highlighter)) to show the "source JSX" in the addon-info and I have the default disabled. 
So for me, one thing is what I pass to "story" and other thing what I pass to our "MyCustomSource" component. That way I can "fake" the management of state with some "wrapper" and still show "pure" source code.

Something like this (dummy):
```js
let fakeState;
const onChange = (value) => {
  fakeState = value;
};

class Wrapper extends React.Component {
  // forceUpdate here
}

const pureComponent = forceUpdate => (
  <Component
    value={fakeState}
    onChange={value => {
      onChange(value);
      if (forceUpdate) forceUpdate();
    }}
  />
);

const component = () => <Wrapper>{({ forceUpdate }) => pureComponent(forceUpdate)}</Wrapper>;

storiesOf('Component', module).add('Story Title', component, {
  info: {
    text: (
      // ... some JSX
      <MyCustomSource>{pureComponent()}</MyCustomSource>
      // ... another JSX
    ),
    source: false
  },
);
```
Its not the most optimal way and probably at some time we will drop the addon-info completely, but atm it serves the purpose.
