### ISSUE TITLE
Component names in build version

### ISSUE THREAD

**Issue by RRonaldMM** [storybooks/storybook#4664]
**Describe the bug**
When I build my storybook using `build-storybook` a .html is generated as expected. The problem is, all component names show up as <t> elements instead of the actual component names (e.g. <InputPanel>)
How to fix this, so users can copy-paste actual useful code snippets?

**Code snippets**

**In code:**
`.add('plain', () => (
        <LabelInput/>
    )`

**In local version (`start-storybook`):**
`<LabelInput />`

**In exported version (`build-storybook`):**
`<t />
`

**Comment by igor-dv** [comment]
Did you try using the `displayName` prop?

**Comment by RRonaldMM** [comment]
Ah, looking for displayName usage did not only lead me to the cause of the problem, but it is also a fix. thanks!

**Comment by tirthaguha** [comment]
Sorry, I'm a little new to storybook. I have the exact same issue with `@storybook/react": "^4.0.7"`, How Do I use this `displayName` prop?

**Comment by shilman** [comment]
```js
const MyComponent = () => <div> .... </div>
MyComponent.displayName = 'MyComponent
```
