### ISSUE TITLE
Version 4 fails on startup with Unexpected token

### ISSUE THREAD

**Issue by kendagriff** [storybooks/storybook#4668]
`npm run storybook` fails with "Unexpected token" on version 4.

```
> platform-app-client@0.0.1 storybook /Users/kendagriff/platform-app-client
> start-storybook -p 6006

/Users/kendagriff/platform-app-client/node_modules/@storybook/core/dist/server/config/webpack.config.default.js:13
  return { ...storybookBaseConfig,
           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kendagriff/platform-app-client/node_modules/@storybook/core/server.js:1:92)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! platform-app-client@0.0.1 storybook: `start-storybook -p 6006`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the platform-app-client@0.0.1 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kendagriff/.npm/_logs/2018-10-31T18_29_17_317Z-debug.log
```
**System:**
 - Framework: React 16.3.0
 - Version: 4.0.0

Any suggestions? It seems to be related to babel somehow (failing on `...`).

**Comment by igor-dv** [comment]
What Node version do you use ?

**Comment by kendagriff** [comment]
v8.1.2. Thanks for the quick reply!

**Comment by igor-dv** [comment]
That is strange. I thought spread is supported since the early 8 versions... Can you check with 8.11 ?

**Comment by igor-dv** [comment]
Yep - https://node.green/#ES2018-features-object-rest-spread-properties

**Comment by kendagriff** [comment]
Yes! Thanks, that fixed it. Unfortunately my build is now failing because of #3044, so I'll do so more research...

**Comment by jithinvj** [comment]
Hi ,

I am having the exact same issue with latest version of storybook. Am on node v6.6.0. 

When using @storybook/react v4.0.0-alpha.1 storybook is loading perfectly. Even the webpack default [config](https://github.com/storybooks/storybook/blob/v4.0.0-alpha.1/lib/core/src/server/config/defaults/webpack.config.js) on that version is using spread operator, how it's working?

Thanks in advance,
Jithin Varghese

**Comment by igor-dv** [comment]
We are transpiling our non-client code for node 8.11 that supports the spread operator. 
Also, it's better for performance, and many js features are natively supported. It's better for webpack 4, as well - https://twitter.com/wSokra/status/967852475918274561
