### ISSUE TITLE
Storyshots don't rerun in watch mode

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#4670]
**To Reproduce**

run `yarn test --core --watch`
edit some of the stories in `examples/official-storybook`
jest outputs "No tests found related to files changed since last commit."

**Comment by igor-dv** [comment]
I will check. IMO it's a bit heavy. 
If I run `yarn jest storyshots --watch` it does watch changes though.

**Comment by Hypnosphi** [comment]
@igor-dv this is because in this case it switches from "only run tests related to changed files" mode (`o`) to "filter by a filename regex pattern" (`f`). Note that it reruns all the tests on each change instead of only rerunning affected tests
