### ISSUE TITLE
addon-jest - Tests not being found

### ISSUE THREAD

**Issue by lflpowell** [storybooks/storybook#4679]
Tests are not being found within the `jest-test-results.json` file

The issue seems to be this commit [https://github.com/storybooks/storybook/commit/7aa23d42f2d185a4996cec37225ba3112f04f4fe#r31119578](https://github.com/storybooks/storybook/commit/7aa23d42f2d185a4996cec37225ba3112f04f4fe#r31119578)

Where Storybook is creating a regex structure such as `MyTest.((\.specs?)|(\.tests?))?(\.js)?$`, however that is then used to test against a path string using `includes` which will never work.

**Expected behavior**
Tests to be returned.

Reverting it back to the version of using a RegExp test works as expected.

**Comment by igor-dv** [comment]
Duplicate to #4497
