### ISSUE TITLE
Storybook build hangs on Win10/WSL

### ISSUE THREAD

**Issue by 454de6e** [storybooks/storybook#4684]
**Describe the bug**
When I run `yarn run build-storybook`, defined as

```
"build-storybook": "rm -rf ./storybook-static && build-storybook -s ./public -c config/storybook",
```

the build seem to hang and never finish on Win10/WSL. See screenshot. Same command on Mac works fine.

**To Reproduce**
You can try to reproduce with this repo/commit: https://github.com/UNDataForum/components/tree/7b3864b51a8bcc34849b419870fafbffbdd5504f

If you have the same issue on Win10/WSL, please comment.

**Expected behavior**
Build should complete.

**Screenshots**
This is what I see and it never finishes. It does not create any files on the file system.

![capture](https://user-images.githubusercontent.com/1482402/47857729-ca29da80-ddc0-11e8-8177-41732abbb6f1.PNG)

**Comment by igor-dv** [comment]
Does this still happen? Did you maybe try other versions of SB?
