### ISSUE TITLE
Storybook not compatible with React hooks

### ISSUE THREAD

**Issue by ilias-t** [storybooks/storybook#4691]
**Describe the bug**
Attempting to render a react component that uses hooks into a storybook staging environment throws an error `Hooks can only be called inside the body of a function component`.

**To Reproduce**
1. Create a react component that uses hooks
2. Import & render the component in storybook

**Expected behavior**
Storybook should be able to display React components that use hooks.

**Code snippets**

Component code
```
import React, { useState } from "react";

export default function ColorChanger() {
  const [color, setColor] = useState("#000");
  const randomColor = "#" + Math.floor(Math.random() * 16777215).toString(16);
  return (
    <div style={{ color }} onClick={() => setColor(randomColor)}>
      Color is: {color} (click to change)
    </div>
  );
}
```
Note, this code is working on codesandbox: https://codesandbox.io/s/n5rmo77jx0

**System:**
 - Browser: Firefox
 - Framework: React
 - Version: 4.0.2

**Comment by gitman** [comment]
Any update suggestion I am getting the same error?

**Comment by Amolang** [comment]
I had the same problem but got it working.

- First I had an error because my function wasn't capitalized e.g. example => Example
- Second I forgot how to React and tried to call the function, instead of passing it as JSX element
  - So to use ilias-t's example, render the function component like <ColorChanger /> and not ColorChanger()
- Lastly, after rendering my function as JSX element, it said I needed to import React in my example code from the React docs.
  - And now it works.

I did also update the react-dom package to **16.7.0-alpha.0** before I tried any of this, so perhaps, if you haven't already, give that a go as well.

**Comment by ilias-t** [comment]
@Amolang Pretty sure I'm doing all of the same steps. The specific error message that I'm seeing leads me to believe the error isn't a result of one of those cases.

Good thought regarding react-dom—I thought that might be it, but I updated it and still go the same error 😕

**Comment by gitman** [comment]
@Amolang I am doing all the same thing as you explained and getting the same error as @ilias-t  suggested.
Further more investigation land me to resolveDispatcher() function in react library where its calling 
`ReactCurrentOwner.currentDispatcher;`
and which is set like below on top somewhere in the react.development.js file 
```
var ReactCurrentOwner = {
  /**
   * @internal
   * @type {ReactComponent}
   */
  current: null,
  currentDispatcher: null
};

```
and thats why I am getting `Hooks can only be called inside the body of a function component`
as in the code below
```
function resolveDispatcher() {
  var dispatcher = ReactCurrentOwner.currentDispatcher;
  !(dispatcher !== null) ? invariant(false, 'Hooks can only be called inside the body of a function component.') : void 0;
  return dispatcher;
}

```

**Comment by Amolang** [comment]
Might be a silly question but, is both of your React packages also updated to  **16.7.0-alpha.0**?

That is the only other thing I have done, which I didn't mention above.

**Comment by ilias-t** [comment]
Yes. It looks like it may have something to do with this: https://github.com/facebook/react/issues/13972#issuecomment-433538714, which is in turn related to https://github.com/facebook/react/issues/14022

**Comment by Amolang** [comment]
I think you will have more luck finding answers in those issues. My knowledge is very limited.

**Comment by ilias-t** [comment]
@Amolang No worries! Would you mind uploading the project that you got it working in, so I can compare? It definitely could be an issue with some of my configs. I was trying to do it in a package of a lerna'ed repo, which adds a layer of complexity 😬

**Comment by Amolang** [comment]
The code can be found in [my project](https://github.com/Amolang/graphical-notes).
The Example is in App.js under src/client.  :)

**Comment by ilias-t** [comment]
@Amolang gotcha, yeah this issue is only happening for me in when using hooks with storybook, which is why I filed the issue against the storybook repository.

**Comment by phaistonian** [comment]
Try:

```js
import { setConfig } from 'react-hot-loader';
setConfig({ pureSFC: true });
```

in your .config file.

This should do the trick - for now.

**Comment by gitman** [comment]
@phaistonian Tried this and still this 
![image](https://user-images.githubusercontent.com/77248/47956446-e44eee80-df61-11e8-8a80-1f4ce1038cc6.png)

**Comment by ChrisBrownie55** [comment]
> ```js
> import { setConfig } from 'react-hot-loader';
> setConfig({ pureSFC: true });
> ```

This didn't work for me, I get the exact same error with or without it.

**Comment by theKashey** [comment]
Could anyone provide a bit more verbose output?
`pureSFC` should work, and it's easy to check it - _hooked_ should be called from a function named `ProxyFacade`, not `hotComponentRender`

**Comment by ChrisBrownie55** [comment]
Nvm, I was using hooks inside of the `.add('with ...', () => { ... return (<Component></Component>) }` part which is a no go, my bad. Instead I'm creating a function outside of it and using it like `.add('with ...', () => (<ComponentWithHooks></ComponentWithHooks>))` to test it with hooks.

**Comment by theKashey** [comment]
And it works?

**Comment by theKashey** [comment]
Please try [ReactHotLoader@next](https://github.com/gaearon/react-hot-loader#-hot-labs-).
It potentially could solve any problems, but would require `react-dom` to be processed by RHL `webpack-loader`. Ie could cause problems with custom webpack configuration, and will not work for the configuration from CRA.

**Comment by nithinpeter** [comment]
@theKashey Is there a way to get around this issue when using a [custom webpack configuration](https://storybook.js.org/configurations/typescript-config/#setting-up-typescript-to-work-with-storybook)?

**Comment by theKashey** [comment]
Just use webpack aliases to rewire `react-dom` to `hot-loader/react-dom` - see this thread - https://github.com/gaearon/react-hot-loader/issues/1088#issuecomment-440624088

**Comment by Syynth** [comment]
So I ran into this issue using CRA 2.1.1 with typescript on the 4.1.0-alpha.8 version of `@storybook/react` and hooks and it ended up coming down to the fact that the package includes it's own local copy of React so when the hook is called it can't find the `ReactSharedInternals.ReactCurrentOwner.currentDispatcher` instance.
As silly as it felt, I just updated my npm scripts to the following:
```json
"storybook": "rm -rf ./node_modules/@storybook/react/node_modules/react && rm -rf ./node_modules/@storybook/react/node_modules/react-dom && start-storybook -p 9009",
```
And everything seemed to work. Maybe react/react-dom need to be peer-dependencies of `@storybook/react` instead of regular deps?

I tried the `react-hot-loader` setConfig thing only to find that react-hot-loader wasn't installed in the first place. Maybe this is a change with the 4.1 alpha but I'm new to storybook in general so I wouldn't know.

**Comment by igor-dv** [comment]
That was done in order to support different versions of React. One for the `manager` and one for the `client`. Is there any way we can make hooks available out of the box 🤔 ?

**Comment by theKashey** [comment]
As long as you are using webpack loader - add ‘ignoreSFC:true’ to configuration.
But actually it should work even without it. Probably the setting is not actually set.

**Comment by jgoux** [comment]
@theKashey I tried with a more manual way by aliasing `react-dom` and installing `@hot-loader/react-dom` and it works!

I'd prefer using the webpack's plugin but doing : 
```
  defaultConfig.module.rules.push({
    test: /\.jsx?$/,
    include: /node_modules/,
    use: ['react-hot-loader/webpack']
  })
```
doesn't seem to work.

I have no other issue with manipulating storybook's webpack config with other plugins.

**Comment by theKashey** [comment]
React-Hot-Loader 4.6.0 should work with hooks out of the box.
https://medium.com/@antonkorzunov/react-hot-loader-4-6-41f3ce76fb08

**Comment by domenico-ruggiano** [comment]
The fix I've finally found is to force a specific version of **@hot-loader/react-dom** during the installation of the patch.

My current version of react-dom is **16.7.0-alpha.2**, so I just did:

```
yarn add @hot-loader/react-dom@16.7.0-alpha.2
```

and my **webpack.config.js** inside the .storybook folder is:

```javascript
module.exports = (baseConfig, env, defaultConfig) => {

  // other configs here...

  defaultConfig.resolve.alias['react-dom'] = '@hot-loader/react-dom';
  return defaultConfig;
};
```

And now hooks are working fine inside storybook!

**Comment by jgoux** [comment]
> React-Hot-Loader 4.6.0 should work with hooks out of the box.
> https://medium.com/@antonkorzunov/react-hot-loader-4-6-41f3ce76fb08

I'm using 4.6.1 and if I don't alias `react-dom`, it doesn't work out of the box.

Using the webpack's plugin is not working, I get the `Hooks can only be called inside the body of a function component` error.

**Comment by theKashey** [comment]
> I'm using 4.6.1 and if I don't alias react-dom, it doesn't work out of the box.

@jgoux - just give me an example, and I will fix it. `pureSFC` is working well in my examples, but probably I miss your case.

PS: webpack loader should work, that's another strange thing.

**Comment by jgoux** [comment]
My example is just above ☝️ : https://github.com/storybooks/storybook/issues/4691#issuecomment-445244958

The 4.6.1 is working by only aliasing `react-dom` and doing nothing else, which is great! But I wasn't able to make it works using the webpack plugin with storybook.

**Comment by domenico-ruggiano** [comment]
> @theKashey My example is just above ☝️ : [#4691 (comment)](https://github.com/storybooks/storybook/issues/4691#issuecomment-445244958)
> 
> The 4.6.1 is working by only aliasing `react-dom` and doing nothing else, which is great! But I wasn't able to make it works using the webpack plugin with storybook.

try to add the alias inside the webpack.config like here https://github.com/storybooks/storybook/issues/4691#issuecomment-447570189

`defaultConfig.resolve.alias['react-dom'] = '@hot-loader/react-dom';`

**Comment by FredyC** [comment]
I am not sure why are you complicating things like this. I've just forced react packages to version `16.7.0-alpha.2` and it works just fine. If you are a lucky user of Yarn, just put this into your package.json. No need to tweak any configuration or mess with web pack config.

```json
  "resolutions": {
    "react": "16.7.0-alpha.2",
    "react-dom": "16.7.0-alpha.2"
  }
```

**Comment by FredyC** [comment]
@theKashey I had the exact same problem as in OP and by forcing react versions it was gone.  I assume it's because Storybook uses a hook-less version of React to drive the rendering. However, when you import eg. `useState`, it's a React 16.7 and it looks for the dispatcher which is probably somehow different. I don't know internals that much. 

From all these comments it makes the most sense to me. I don't get why would hot loader be involved at all. I am on Storybook 4.1.2 and `react-hot-loader` is [not even installed as a dependency](https://github.com/storybooks/storybook/blob/v4.1.2/app/react/package.json).

**Comment by theKashey** [comment]
You are lucky one, then :)

**Comment by iamruhul** [comment]
@FredyC  it worked for me alhamdulillah! thanks

**Comment by jgoux** [comment]
@domenico-ruggiano Yes I know that aliasing is working, that's what I use too.
I just wanted to point out that the webpack plugin approach isn't working with storybook. 👍

**Comment by theKashey** [comment]
@jgoux - sorry, still didn't get enough time to reproduce your example, but could you try to use `unshift` instead of `push`?

**Comment by jgoux** [comment]
@theKashey Not sure what's going on but it's not working anymore, even with the alias solution.
Environment :
- storybook v4.2.0-alpha.4
- react-hot-loader v4.6.3
- @hot-loader/react-dom 16.7.0-alpha.2.4

```
Object(...) is not a function
    TypeError: Object(...) is not a function
    at TestHook (http://localhost:9009/main.f5798b722fe2ceddc6c1.bundle.js:88:73)
    at mountIndeterminateComponent (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:16891:13)
    at beginWork (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:17395:16)
    at performUnitOfWork (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:20152:12)
    at workLoop (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:20192:24)
    at renderRoot (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:20278:7)
    at performWorkOnRoot (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:21169:7)
    at performWork (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:21081:7)
    at performSyncWork (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:21055:3)
    at requestWork (http://localhost:9009/vendors~main.f5798b722fe2ceddc6c1.bundle.js:20924:5)
```

I used this minimal example : 
```js
import { useState } from 'react'
import { storiesOf } from '@storybook/react'

function TestHook() {
  let [state, setState] = useState(0)
  return (
    <button onClick={() => setState(state + 1)}>clicked {state} times</button>
  )
}

storiesOf('Test', module)
  .add('test', () => <TestHook />)
```

**Comment by FredyC** [comment]
@jgoux Yea, this latest gotcha :D React 16.7.0 was released *without hooks* and if you are not careful, it can break apps. See more info here: https://reactjs.org/blog/2018/12/19/react-v-16-7.html#why-is-this-bugfix-a-minor-instead-of-a-patch

**Comment by jgoux** [comment]
@FredyC Wow I totally missed that! So it means that we need to stick to 16.7.0-alpha to keep hooks?

**Comment by jgoux** [comment]
@theKashey Sorry for the noise, just tested with react 16.7.0-alpha.2 and 16.7.0-alpha.2.4 and it works in both cases (alias + webpack)! 👏

**Comment by theKashey** [comment]
> React-Hot-Loader 4.6.0 should work with hooks out of the box.

**Comment by jgoux** [comment]
@theKashey Indeed! I was confused by this : https://github.com/gaearon/react-hot-loader#-hot-labs- : 

> (required) use webpack plugin to let RHL patch React-DOM for you.

**Comment by gaurav5430** [comment]
I don't have a custom webpack config for storybook.
I don't have hot-loader installed.

i was able to make it work by forcing:
"@storybook/react": "4.2.0-alpha.5", in devDependencies
and
"react": "16.7.0-alpha.2",
"react-dom": "16.7.0-alpha.2" in dependencies

**Comment by mrmckeb** [comment]
@gaurav5430, are you using create-react-app?

FYI: There's a new alpha of React with hooks: https://www.npmjs.com/package/react/v/16.8.0-alpha.1

**Comment by gaurav5430** [comment]
No, i am not using create-react-app.

Regarding the new alpha with hooks, great, I would try that out.

**Comment by Mathias54** [comment]
For my, it worked: 

```
const MyComponent = () => {
    const [number, setNumber] = useState(0);
    return (
        <div>
            <button onClick={() => setNumber(number + 1)}>Inc</button>
            <div>{number}</div>
        </div>
    )
};

storiesOf('MyStoreOf', module)
    .add('myComponent', () => (<MyComponent /> ));

```

**Comment by ChrisBrownie55** [comment]
I guess this should be closed then @ilias-t

**Comment by JasonTheAdams** [comment]
I was able to get hooks working, but unfortunately the knobs addon stopped working and the jsx addon just showed the story container component. To bad, it would be really nice to be able to manage the state for the sake of example.

**Comment by shilman** [comment]
@JasonTheAdams pretty sure @hipstersmoothie has something working with the jsx addon -- maybe he can chime in here?

**Comment by hipstersmoothie** [comment]
@JasonTheAdams Here I describe a simple way to use hooks and still retain the jsx.

https://mobile.twitter.com/HipsterSmoothie/status/1107182717467156484

My co worker built a tiny library with a hooks like API that he just released that is also jsx friendly 

https://github.com/adierkens/storybook-addon-state

**Comment by JasonTheAdams** [comment]
Thanks, @hipstersmoothie! In your example, it doesn't just show `<InputState />` in your Story Source? Does it show the `<Input />` component inside or only that?

I really like your co-workers library, but I'm reluctant to use a complete recreation of `useState`, as he's not using the React `useState` at any point, which means he'd have to update this function to reflect any future changes React makes.

**Comment by hipstersmoothie** [comment]
> In your example, it doesn't just show <InputState /> in your Story Source? Does it show the <Input /> component inside or only that?

the jsx addons should show `Input` and `InputState`. you can use the skip param to get skip state though.

> as he's not using the React useState at any point, which means he'd have to update this function to reflect any future changes React makes.

> I really wish Storybook treated the function passed to the story as a functional component, allowing it to take full advantage of React.

You are right on the money here. IDK if it would work but there might be some changes to @storybook/react that could support this. This is the reason when my coworkers library doesn't use react.useState

**Comment by mikkelking** [comment]
I hit the same problem using a hooks based component, and after some experimentation found the cause of it...

My story markup looked like this
```
<div style={{maxWidth: '280px'}}>
  <MyComponent/>
</div>
```
It appears that a normal `<div>` tag is what confuses the matter, and the solution is to make sure that the wrapping component is a React component, and not just a regular html tag. So I defined a `Wrapper` component like this:
```
const Wrapper = props => <div style={{maxWidth: '280px'}}>{props.children}</div>
```
and then changed my story markup to be like this
```
<Wrapper>
  <MyComponent>
</Wrapper>
```

Problem solved, and no need to import any special libraries to make it work.

**Comment by antoinejaussoin** [comment]
I also had this problem, and tracked it down (as someone else said before) to the fact that Storybook uses a different instance of React (one in my workspace node_modules, and one in the storybook node_modules, I'm using Yarn Workspaces, monorepo).

I tried the package.json resolution trick, to no avail.

I got it working though by tweaking the webpack.config by using aliases and forcing both react and react-dom to be used from the root node_modules:

```
const aliases = {
react: path.resolve(__dirname, '../../../node_modules', 'react'),
 'react-dom': path.resolve(__dirname, '../../../node_modules', 'react-dom'),
};
```

and then in your config :
```
config.resolve.alias = aliases;
```

Hope that helps.

**Comment by mrmckeb** [comment]
Hey, so this is a known issue with hooks, I believe they have it documented on the React side - you can also symlink react (if you're symlinking a package into your project - you symlink React from the project back to your package).

**Comment by byilagan** [comment]
Wrapping the story in a div worked for me

```
storiesOf("Hooks", module)
  .add(
    "Hook",
    () => (
      <div>
        <Hook/>
      </div>
    ),
  );
```

**Comment by zibra** [comment]
I'm still facing this issue in storybook. Is this output from npm ls correct or not?
![image](https://user-images.githubusercontent.com/4493100/62351904-20ba7580-b507-11e9-861c-e64a151732e7.png)![image](https://user-images.githubusercontent.com/4493100/62351908-23b56600-b507-11e9-9ad5-6f28ad7c8f75.png)

**Comment by zibra** [comment]
In my case, the problem was caused by `why-did-you-update` module.

**Comment by shilman** [comment]
Hooks fully supported in 5.2. Upgrade to try it out. Here's the PR: https://github.com/storybookjs/storybook/pull/7571

**Comment by helsont** [comment]
@mikkelking's suggestion did the trick for me. Just having intermediary component solves the hooks issue.

**Comment by shilman** [comment]
@helsont you shouldn't need to do that anymore in a recent 5.2 beta

**Comment by StJohn3D** [comment]
Trying to use a hook in a custom addon is not working for me on 5.2.8
It does work in stories though.
