### ISSUE TITLE
Mobile layout for storybook version 4

### ISSUE THREAD

**Issue by fibo** [storybooks/storybook#4692]
### Mobile layout for storybook version 4
 
Hi, I love storybook and it is really helping me creating a React component library of React components using Bulma CSS framework.

I updated to storybook v4 and the layout on mobile has a font that ia too small, it seema to be not responsive, any hint?

### Steps to reproduce

Just deploy a storybook v4 and look it on a mobile device, or see this storybook: 
http://g14n.info/trunx

## version of Storybook

- @storybook/react 4.0.2

### Affected platforms 

Any mobile

### Work summary

Please provide a responsive layout or give some tips to achieve it in a storybook build.

### Who to contact

https://github.com/fibo

**Comment by fibo** [comment]
@igor-dv 	thanks for the hint, I tryed to modify font size, but to achieve the result I want, i.e. make it look nice on a mobile device, this meta tag (or something similar) is needed

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```
hence I added a *manager-head.html* file as [documented here](https://storybook.js.org/configurations/add-custom-head-tags/) with the meta tag above.

**Comment by jackkoppa** [comment]
Thanks @fibo - that's exactly what I was looking for. I know it's important to prevent the default `<head>` of the main Storybook UI from being polluted, but is there a reason that I can't think of, that this particular viewport tag isn't included by default?

I think it's a fair assessment to say that most sites being built with Storybook are intended to be responsive (i.e. will usually have the above viewport tag), and that Storybook itself is intended to be responsive after PR #3337. But without setting `device-width` and `initial-scale` for the main UI, when viewing Storybook on mobile, it will still be significantly zoomed out.

I'm sure there could be a justification I'm not thinking of, but would people be open to a PR that includes @fibo's meta tag in the default head?

**Comment by fibo** [comment]
It would be also nice to have the navigator on mobile to be closed after click on a menu entry.
