### ISSUE TITLE
Storybook 4 Migration Guide for Babel 6 Presets & Plugins

### ISSUE THREAD

**Issue by vincelawbc** [storybooks/storybook#4693]
I noticed something missing about Babel 7 in the migration guides at:

https://medium.com/storybookjs/migrating-to-storybook-4-c65b19a03d2c
https://github.com/storybooks/storybook/blob/master/MIGRATION.md#babel-7

In my project, I just upgraded to Babel 7 and I also have a .babelrc in my project directory.

I had to replace the old Babel 6 presets with new ones such as:

@babel/preset-env
@babel/preset-react

I also had to replace babel-plugin-transform-class-properties with @babel/plugin-proposal-class-properties.

Add the new Babel 7 presets and plugins into .babelrc:

```
{
  "presets": ["@babel/env", "@babel/react", ["minify", {
    "builtIns": false,
    "evaluate": false
  }]],
  "plugins": ["babel-plugin-styled-components", "@babel/plugin-proposal-class-properties"]
}
```

If you are using babel-jest, you will need to install babel-core@^7.0.0-bridge to make it work with Babel 7.

This fixed my storybook compilation issues.

I hope this helps someone who struggled to upgrade to Storybook 4.

**Comment by shilman** [comment]
Thanks @vincelawbc! Will update both docs this weekend. 🙇

**Comment by igor-dv** [comment]
I am not sure we need to explain how to migrate from babel 6 to babel 7 (Or anything else which is a 3rd party to SB). For this, you need to check babel's migration guide.
Link to their docs should be enough.

**Comment by Lelith** [comment]
@vincelawbc thank you for putting it here - saving me after almost 4 hours of pain WHY the heck it was not working anymore as soon as i tried to add preset in babelrc
