### ISSUE TITLE
@storybook/html - html-loader not working in 4.0.2

### ISSUE THREAD

**Issue by tarikhamilton** [storybooks/storybook#4697]
**Describe the bug**
In 4.0.2, it'll say the appropriate loader is missing.

**To Reproduce**
1. Import a html file in a story.
2. See error in console.

**Expected behavior**
html-loader is a dependency of @storybook/html, so it is there and should work. To resolve momentarily, I installed @storybook/html@4.0.0.

**Comment by igor-dv** [comment]
Sorry, I couldn't reproduce this with 4.0.2. Can you share the reproduction?

**Comment by tarikhamilton** [comment]
I cannot reproduce. It's working at 4.0.2 now. I really apologize. I did spend a decent amount of time on this before posting, but it must've ultimately been some weird npm or dependency glitch. Closing and thank you for trying to reproduce.
