### ISSUE TITLE
Absolute imports broken in v4

### ISSUE THREAD

**Issue by arvigeus** [storybooks/storybook#4700]
**Describe the bug**
Absolute imports no longer work.

**To Reproduce**
1. Clone https://github.com/arvigeus/storytime
2. Run storybook to confirm it's working
3. Update to storybook 4

**Expected behavior**
Should keep working as it was in v3

**Comment by chadfawcett** [comment]
I believe this is a duplicate of #4496

**Comment by igor-dv** [comment]
Yep, it is.
