### ISSUE TITLE
a11y addon add on one story displays on all stories

### ISSUE THREAD

**Issue by hipstersmoothie** [storybooks/storybook#4703]
**Describe the bug**

I added addon a11y to just 1 story but the accessibility tab is on all stories

**To Reproduce**
1. add a11y
2. add to just 1 story
3. every story has accessibility panel

**Expected behavior**

Should only display accessibility panel on the one story that uses it.

**System:**
 - Device: macbook pro
 - Browser: chrome
 - Framework: react
 - Addons: a11y
 - Version: 4.0.0

**Comment by igor-dv** [comment]
I think it's fixed.
