### ISSUE TITLE
How to get CRA with babel-plugin-macros (emotion/macro) with require.context working?

### ISSUE THREAD

**Issue by guy-kdm** [storybooks/storybook#4711]
**Describe the bug**
in CRA i'm trying to use then new macros feature (emotion/macro) while requiring .stories.tsx in config.js.  babel-plugin-macros and require.context conflict, so tried adding `"plugins": ["require-context-hook"]` > `.storybook/.babelrc` but than no stories are loaded. Any idea? 
This should be a common scenario so I'll contribute docs when it's resolved.

**To Reproduce**
1. create a project with CRA (--typescript in my case) 
2. npx -p @storybook/cli sb init
3. `import styled from 'react-emotion/macro'` > src/components/test.stories.tsx
4. `require.context('../src/components', true, /\.stories\.tsx?$/)` > config.js
4. see: 

> WARNING in ./node_modules/babel-plugin-macros/dist/index.js 62:46-53
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

5. add   "plugins": ["require-context-hook"] > .babelrc
6. no stories are loaded.

**Code snippets**
If applicable, add code samples to help explain your problem.
config.js:
```
import { configure } from '@storybook/react'
const req = require.context('../src/components', true, /\.stories\.tsx?$/)

function loadStories() {
  req.keys().forEach(filename => req(filename))
}

configure(loadStories, module)
```

.babelrc:
```
{
  "plugins": ["require-context-hook"]
}
```

webpack.config.js be like:
```
const path = require('path')
const TSDocgenPlugin = require('react-docgen-typescript-webpack-plugin')

module.exports = (baseConfig, env, config) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    loader: require.resolve('awesome-typescript-loader'),
  })
  config.plugins.push(new TSDocgenPlugin()) // optional
  config.resolve.extensions.push('.ts', '.tsx')
  return config
}
```

**System:**
 - OS: Manjaro 4.14
 - Framework: react, emotion

**Comment by igor-dv** [comment]
`require-context-hook` is definitely should **not** be added. It's needed to polyfill `require.context` for Node (for example tests)

What is this `.babelrc` you are using? Don't CRA hide their `babelrc`?

**Comment by guy-kdm** [comment]
it does, I tried putting a .babelrc in stories, just to try that plugin.

**Comment by igor-dv** [comment]
CRA is now [using](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L232) `babel` to transpile typescript, that is how `babel-plugin-macros` [kicking in](https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/package.json#L33). If using `ts-loader`/`awesome-typescript-loader` babel won't be applied. 

You need probably to replace your ts rules with `babel-loader` and `@babel/preset-typescript`
Or you can help with this #4587, and it will be working by default =)
