### ISSUE TITLE
CRA's webpack configuration is mangling function names (and removing prop types) in static build

### ISSUE THREAD

**Issue by jansav** [storybooks/storybook#4717]
**Describe the bug**
When webpack configuration is used directly when CRA, it causes `build-storybook` to mangle function names. This causes issues that code source and prop types are not presented correctly.

As #3879 says, it could be solved by adding `.displayName` to each component, but since CRA is now removing prop types in production builds (https://github.com/facebook/create-react-app/pull/3818), prop types are not visible in static version of storybook.

**To Reproduce**
1. Create app using Create React App
2. Install storybook
3. Create functional component and stories for it
4. Run`npm run build-storybook` (without having custom webpack configuration)
5. Serve static storybook and see results.

**Expected behavior**
Function name is used as display name. Prop types are visible in page.

**System:**
 - Framework: React, react-scripts (2.1.1)
 - Addons: **Info**, knobs, options
 - Version: 4.0.2

**Additional context**
It might be that this is something that storybook can't really do anything else than suggest **not** using CRA's webpack configuration directly. However I would like to see if there is any suggestions how to solve this issue without using full control mode.

**Comment by jansav** [comment]
Any tips?

**Comment by davidchristie** [comment]
I recently hit this issue when upgrading `@types/react` to version 16.7.6.

Dropping back to 16.4.18 fixed it for me: https://github.com/davidchristie/social-network/pull/216/commits/9d6f0046d5a277e2020aba4794a09f6fe8318472
