### ISSUE TITLE
Exporting React Native 0.56.1 for Web

### ISSUE THREAD

**Issue by jpeet86** [storybooks/storybook#4738]
**Describe the bug**
We are looking to export our Storybook React Native project to web.
After trying to fix a few errors when running https://storybook.js.org/basics/exporting-storybook/  adding packages etc. we found this article https://medium.com/@agent_hunt/storybook-setup-for-desiloed-development-with-react-native-ios-android-web-85b6d64fb1b4 which was similar to what we had almost achieved.

Running the working project works fine locally, however when replicating this in our current project we get errors, including:
 
```
ERROR in ./node_modules/react-navigation/src/views/withNavigation.js 9:23
Module parse failed: Unexpected token (9:23)
You may need an appropriate loader to handle this file type.
| export default function withNavigation(Component) {
|   class ComponentWithNavigation extends React.Component {
>     static displayName = `withNavigation(${Component.displayName ||
|       Component.name})`;
|
 @ ./node_modules/react-navigation/src/react-navigation.js 166:11-44
 @ ./src/components/ui/components/headerButtons/HeaderRightCloseButton.js
 @ ./src/components/ui/components/headerButtons/index.js
 @ ./src/components/ui/index.js
 @ ./src/__stories__/ui/boxes/boxes.stories.js
 @ ./.storybook/config.js
```

We have extended the presets of our webpack config to include:
```
presets: [
        'react-app',
        '@babel/preset-env',
        '@babel/preset-react',
        'react-native',
        'stage-0'
],
```
And then we get this error instead:

```
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions.
```

Is there another loader we can use for this? Or is this an issue with versions?
The main packages and there versions are:

```
  "dependencies": {
…
"react": "^16.4.1",
"react-native": "^0.56.1",
"react-native-web": "^0.9.5",
"react-dom": "^16.2.0",
…
```
```
"devDependencies": {
…
"@storybook/addon-actions": "^3.4.8",
"@storybook/addon-links": "^3.4.8",
"@storybook/addons": "^3.4.8",
"@storybook/react": "^4.0.2",
"@storybook/react-native": "^3.4.8",
"@babel/core": "^7.1.2",
"babel-core": "^7.0.0-bridge.0",
"babel-jest": "^23.6.0",
"babel-plugin-module-resolver": "^3.1.1",
"babel-preset-react-app": "^6.0.0",
"babel-preset-react-native": "^5.0.2",
```

**System:**
 - OS: MacOS
 - Framework: react native
 - Addons: actions and links

**Comment by samjt** [comment]
This `webpack.config.js` in `.storybook` is working for me at the moment.
Notice the presets I'm using and the plugins. These are for RN 0.57, but it shouldn't be any different for 0.56
```
const { resolve } = require("path");

module.exports = (storybookBaseConfig, configType) => {
  storybookBaseConfig.module.rules =[
    ...storybookBaseConfig.module.rules,
    {
      test: /\.(js|jsx|mjs)$/,
      loader: resolve(__dirname, '../', 'node_modules', 'babel-loader'),
      options: {
        babelrc: false,
        presets: ["@babel/preset-env","@babel/preset-react"],
        plugins: [
          [require("@babel/plugin-proposal-class-properties")],
          [require("babel-plugin-react-native-web")]
        ],
        cacheDirectory: true,
      },
    },
    {
      test: /\.(gif|jpe?g|png|svg)$/,
      use: {
        loader: "url-loader",
        options: { name: "[name].[ext]" }
      }
    }
  ];

  return storybookBaseConfig;
};
```

```
"dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
},
 "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.1.2",
    "@storybook/addon-actions": "^4.0.0",
    "@storybook/addon-info": "^4.0.2",
    "@storybook/addon-knobs": "^4.0.0",
    "@storybook/addon-links": "^4.0.0",
    "@storybook/addon-options": "^4.0.0",
    "@storybook/addons": "^4.0.0",
    "@storybook/react": "^4.0.0",
    "@storybook/react-native": "^4.0.0",
    "@storybook/storybook-deployer": "^2.3.0",
    "@storybook/ui": "^3.4.11",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "23.6.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-react-native-web": "^0.9.3",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-preset-react-app": "^3.1.2",
    "babel-preset-react-native": "^5",
    "babel-runtime": "^7.0.0-beta",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.3",
    "moment": "^2.22.2",
    "react-art": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-native-web": "^0.9.4",
    "react-native-web-player": "^2.0.0-alpha.3",
    "react-test-renderer": "16.6.0-alpha.8af6728",
    "storybook-addon-jsx": "^5.4.0"
  }```

**Comment by jpeet86** [comment]
Thanks @samjt , however this gives me errors from node modules as they're not being excluded

**Comment by samjt** [comment]
You can still add and exclusion clause to the webpack config, if that helps

**Comment by jpeet86** [comment]
I get the original errors when I exclude node_modules. If it works for you then there must be an issue with some of the modules we are using. We will investigate further. Thanks for your help @samjt

**Comment by slorber** [comment]
Hey, also tried to be able to use my RN design system with react-native-web. Not that I use react-native-web on any webapp, but just because visual regression testing tools (storyshot, applitools eyes...) do not work with RN yet (afaik)

That would be cool if react-native-web was officially supported in storybook imho. I've tried to make it work but was unsuccessful and my webpack/babel config is not good I guess... + I use typescript with Babel7... that probably does not help ;)

**Comment by igor-dv** [comment]
@slorber, you just need to set `babel-plugin-react-native-web` properly for the storybook. We can make it as a preset for storybook in the future. What exactly doesn't work for you now?

**Comment by slorber** [comment]
I don't remember exactly what did not work for me but my attempt to make storybook web + native work on the same RNW project did not work. I'll probably give it another try sooner or later because I really want visual diffing feature of my RN components. Will report here on my next attempt.

However if you can provide a sample repo where you made this work fine please don't hesitate ;)

**Comment by igor-dv** [comment]
We used rn-web at work and just separated a storybook for native into a separate package.
