### ISSUE TITLE
How to use with metamask / injected web3 Provider / global window contexts

### ISSUE THREAD

**Issue by soundyogi** [storybooks/storybook#4743]
Hi!

I am trying to build a ethereum dapp frontend with Storybook.
The Components need the web3 Provider that gets injected into the window context by metamask or other providers. e.g.: ```window.web3```

Of course this is not available inside the iframes since the variable is injected by a browser extension into the main window running storybook.

How can I give my components in the iframes access to it?
What is the general practice to do so? Writing an addon for example.

I would appreciate any pointers :)

Thank You in Advance

https://github.com/ethereum/web3.js/
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#partly_sunny-web3---ethereum-browser-environment-check

**Comment by jacksbox** [comment]
you could include the metamask script inside the iframe, this way the window properties would be set there and be available to the components.

**Comment by soundyogi** [comment]
Turns out I am stupid, web3 gets injected into iframes now by metamask. thanks anyway!
