### ISSUE TITLE
StoryShots: Add option to use shallowSnapshot with multiSnapshotWithOptions 

### ISSUE THREAD

**Issue by ewolfe** [storybooks/storybook#4746]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to use multiSnapshotWithOptions while also only performing a shallow snapshot

**Describe alternatives you've considered**
I've looked through the documentation and seen the examples here https://github.com/storybooks/storybook/tree/4c757d05f162925217751bb5d61518c108d0935b/addons/storyshots/storyshots-core/stories

I'm not sure if this feature request is currently possible and I'm just getting the configuration wrong.

**Are you able to assist bring the feature to reality?**
Maybe

**Additional context**
NA

**Comment by igor-dv** [comment]
Should be something like this: 

```js
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';
import { shallow } from 'enzyme';

initStoryshots({
  test: multiSnapshotWithOptions({
    renderer: shallow,
  }),
});
```

**Comment by stereodenis** [comment]
@igor-dv it's not working for React Native

**Comment by moroine** [comment]
After some investigation on the source code, I've found the proper way to do it

```
import { shallow } from 'enzyme';
import { createSerializer } from 'enzyme-to-json';
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';

initStoryshots({
  framework: 'react',
  test: multiSnapshotWithOptions({
    renderer: shallow,
  }),
  snapshotSerializers: [createSerializer()],
});
```
