### ISSUE TITLE
Offer options when project type cannot be determined automatically

### ISSUE THREAD

**Issue by jason-ivy** [storybooks/storybook#475]
getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
    Unsupported Project type. (code: UNDETECTED)
    Visit http://getstorybook.io for more information.

**Comment by mnmtanish** [comment]
Hi,
Can you run it from the directory which has the `package.json` file.

**Comment by arunoda** [comment]
@jeffrygan anyway, you can start here: https://getstorybook.io/docs/basics/slow-start-guide

**Comment by jeffrygan** [comment]
@mnmtanish the project already has package.json. 
@arunoda I do this way, but complicated procedures

**Comment by arunoda** [comment]
@jeffrygan we detect your project type based on the package.json.
We'd like to see it or the repo to fix the original issue.

Here's the detection logic we are doing: https://github.com/kadirahq/getstorybook/blob/master/lib/detect.js

**Comment by jeffrygan** [comment]
@arunoda thx, I only init the package.json without install react or anything. I have to install react first.

**Comment by arunoda** [comment]
Ah okay. Cool.

**Comment by batjko** [comment]
Will the quick start guide ever work without havinbg done all the things in the slow-start guide first?

The quick start implies that nothing else is necessary and it should just work "with any kind of React project", which doesn't seem to be the case, unless you have storybook package installed locally, an npm script present and all that jazz....

**Comment by akatech** [comment]
Hi gys, i need help
 Detecting project type. ✓
    Unsupported Project type. (code: UNDETECTED)
    Visit https://storybook.js.org for more information.

**Comment by UsulPro** [comment]
Hi @akatech !
what is your actual project type?
If getstorybook cant work with it you can try to do it [manually](https://storybook.js.org/basics/slow-start-guide/)

**Comment by marcushenrique** [comment]
@akatech like @jason-ivy said, I had to install react first but I don't know why it is not automatic.

**Comment by alterx** [comment]
@marcushenrique,  we support other libraries (eg. Vue), so installing React automatically wouldn't make sense for everyone. What you should do first is create a React or Vue project and after that install storybook.

**Comment by jomarquez** [comment]
the project I am trying to install playbook is using angular. i am running ```sb-create``` in the same location my package.json is located. 

i am getting the same error as above
```
Detecting project type
    Unsupported Project type. [code: UNDETECTED]. For now SB support only Angular 1 projects.
```

My project does not use React. Should I still install React to get this working. Also, where is the slow-start guide located?

**Comment by Hypnosphi** [comment]
It would be handy to show a prompt with options when automatic detection fails

**Comment by Hypnosphi** [comment]
@jomarquez we don't have `sb-create` command. Looks like you're trying to use another [similar tool](https://github.com/ui-storybook/sb) thats seems to support Angular 1, so you can open an issue about supporting later versions there.

But maybe you don't need to. Actually, we're working on supporting Angular 2+, you can track the progress in https://github.com/storybooks/storybook/issues/269

**Comment by chennn1990** [comment]
try installing react & react-dom

**Comment by Hypnosphi** [comment]
A more human-friendly message is printed since version `3.3.0-alpha.2`
