### ISSUE TITLE
How to preload assets?

### ISSUE THREAD

**Issue by rndmerle** [storybooks/storybook#4751]
### Bug or support request summary

**Any alternative to preload-webpack-plugin ?**

We're running screenshot tests thru Storybook.
To avoid issues with invisible icons or different text when a menu opens and used fonts are not loaded, we were using preload-webpack-plugin to preload all needed fonts.

It's no longer possible under Storybook 4 because it seems html-webpack-plugin as been replaced by generate-page-webpack-plugin.

Any alternative ?

Can't just preload assets in preview-head.html because assets have hashes.

### Steps to reproduce

Add in webpack's plugins:
```
 new PreloadPlugin({
      rel: 'preload',
      as: 'font',
      include: 'allAssets',
      fileWhitelist: [/(icons).*woff2/i],
    })
```
Leads to error: `TypeError: HtmlWebpackPlugin.getHooks is not a function`

### Please specify which version of Storybook and optionally any affected addons that you're running

- vue-cli-plugin-storybook 0.4.8

**Comment by rndmerle** [comment]
Well for now I'm using a workaround by removing hashes from fonts in Storybook's Webpack config:
```
storybookConfig.module.rules.find(rule => rule.test.toString().includes('woff2')).use[0].options.fallback.options.name = 'fonts/[name].[ext]'
```
And then preloading needed fonts in preview-head.html:
```
<link as=font href=/fonts/icons.woff2 rel=preload>
```

**Comment by igor-dv** [comment]
SB v4 is using `html-webpack-plugin` back again.

**Comment by rndmerle** [comment]
That's cool so. Thanks!
