### ISSUE TITLE
Does forcererender exist in @storybook/angular? 

### ISSUE THREAD

**Issue by ruudyroon** [storybooks/storybook#4760]
I'm currently using @storybook/angular 4.0.2, just wanted to know if I can use forceRerender in angular like i see it being used for React.

**Comment by ruudyroon** [comment]
found the solution, closing it

**Comment by andrei-ilyukovich** [comment]
@ruudyroon Have you found an answer about usage in Angular?

**Comment by ruudyroon** [comment]
@andrei-ilyukovich https://github.com/storybookjs/storybook/issues/4762

**Comment by andrei-ilyukovich** [comment]
Thanks! I see that now forceRerender is available to import but unfortunately it doesn't make any effect on the story, component is not updating.
 I've tried to invoke it inside button knob like:
```
 button: button("Update Story", () => {
           forceReRender();
 })
```
Probably is there any example with explanation how to call forceRerender() properly?
