### ISSUE TITLE
RFC: npm module to generate story metadata

### ISSUE THREAD

**Issue by transitive-bullshit** [storybooks/storybook#4766]
Posting this here to get feedback on the idea and implementation.

My team is planning on creating an npm module along the lines of `generate-storybook-metadata`, which would generate the full storybook metadata for any valid storybook project.

E.g., it would output:

```js
[
  {
    "kind": "Components/AjaxContent",
    "fileName": "./packages/component-ajax-content/src/AjaxContent.stories.js",
    "stories": [
      {
        "name": "Default"
      }
    ]
  },
  {
    "kind": "Components/Alert",
    "fileName": "./packages/component-alert/src/Alert.stories.js",
    "stories": [
      {
        "name": "Alert"
      },
      {
        "name": "Language: Arabic (RTL)"
      }
    ]
  },
  ...
]
```

This would be really useful for allowing other projects and design system tools to integrate with Storybook.

Our current [implementation of this](https://github.com/hydrateio/docz-plugin-storybook/blob/master/src/build-storybook.js) for Storybook v4 works, but it is quite slow and cumbersome. Our goal is to support Storybook v3 and v4.

So here are our concrete questions to the Storybook maintainers and community:

1) Is there a cleaner / more efficient way of generating all the story metadata server-side from within a valid storybook project?

2) Would anyone else find this type of module useful?

Thanks!

cc @mergebandit

**Comment by igor-dv** [comment]
With `sb/standalone` you probably won't be able to support v3. You can try using AST parsing of the stories to extract this metadata (We are doing this internally for storysource addon), but it also won't support some esoteric examples. 
I think after the #4848 everything will be much easier.
