### ISSUE TITLE
Opt-out for knobs URL update

### ISSUE THREAD

**Issue by tonai** [storybooks/storybook#4774]
**Is your feature request related to a problem? Please describe.**
If you have a lot of complexes props on some component, you might end up with a too long URL in the browser bar.
Then when you refresh the page or try to add iframe.html to the URL you will get an "Request-URI Too Long" error.

**Describe the solution you'd like**
Add an opt-out to not update the URL with knobs values.
Ideally you want to opt-out only for some knobs (huge object knobs for instance).
A general opt-out can also be a solution.

**Describe alternatives you've considered**
Not using knobs ?

**Are you able to assist bring the feature to reality?**
Maybe. Need to ask my boss.

**Additional context**
This is a duplicate of closed issue #1680

**Comment by ndelangen** [comment]
knobs now no longer appear in the url, unless you generate a share-url
