### ISSUE TITLE
Addons panel position resets with each knob change

### ISSUE THREAD

**Issue by emyarod** [storybooks/storybook#4776]
**Describe the bug**
The position of the addons panel position resets with each story or knob change

**To Reproduce**
1. Reposition addons panel (`cmd`+`shift`+`G` or `ctrl`+`shift`+`G`)
2. Click on a different story or modify a story knob

The panel will then reset its position

**Expected behavior**
The storybook should remember the position of the panel for the current session

**Screenshots**

![kapture 2018-11-12 at 13 42 38](https://user-images.githubusercontent.com/8265238/48371224-ea8b4c00-e680-11e8-9744-1e98eab5d1f1.gif)

**System:**
 - OS: MacOS 10.14
 - Device: Macbook Pro 2018
 - Browser: Chrome 70+, Firefox 65+
 - Framework: react
 - Addons: a11y, actions, info, knobs, links, options, storysource
 - Version: 4.0.4

**Comment by igor-dv** [comment]
IMO shortcuts are not persistent. 
@ndelangen, @Jessica-Koch, will this be handled in the ui overhaul?

**Comment by Jessica-Koch** [comment]
Yes this was held up because of a bug that caused the constructor to load twice

**Comment by igor-dv** [comment]
Can the fix be extracted to v4?

**Comment by Jessica-Koch** [comment]
Sorry if that doesn’t answer the question, I have no idea when things are getting released.  I took off work to work on this today

**Comment by lmenus** [comment]
I experience this issue when I load up Search box (⇧ + ⌘ + O) and then press Esc to close it. If I perform a search and select a result, this bug is not present.

**Comment by nicgirault** [comment]
This issue is still happening and very frustrating to work on components

**Comment by shilman** [comment]
@nicgerault v5?

**Comment by malykhinvi** [comment]
> Click on a different story
This part of the bug is the same as https://github.com/storybooks/storybook/issues/6114, though 6114 is not related to knobs. @shilman should we consider these two tickets as duplicates, or these are separate ones?

**Comment by shilman** [comment]
Sure, let's pick this up in #6114. Closing this as a dupe.
