### ISSUE TITLE
The Discord invite link in README.md is broken

### ISSUE THREAD

**Issue by shawwn** [storybooks/storybook#4777]
**Describe the bug**
The Discord invite link in README.md is broken: https://discord.gg/sMFvFsG/

**To Reproduce**
1. Open discord
2. Click "Join a server"
3. Enter https://discord.gg/sMFvFsG/

**Expected behavior**
The user should be able to join the Storybook discord server.

**Screenshots**
![image](https://user-images.githubusercontent.com/59632/48373603-e6aef800-e687-11e8-9ed9-eca402661a81.png)

**Code snippets**
`rm -rf "${HOME}"`

**Additional context**
Nobody exists on purpose.

**Comment by msmyers** [comment]
So, like, that `code snippet.`
