### ISSUE TITLE
addon-storyshots not working in angular

### ISSUE THREAD

**Issue by x1c0** [storybooks/storybook#4778]
**Describe the bug**
After following the steps for addon-storyshots using jest-preset-angular the jests tests pass but I got this error on the Storyshots.test.js file

**To Reproduce**
1. clone https://github.com/x1c0/test-angular-storybook
2. run `ng test`

**Expected behavior**
I should have some screenshots 

**Screenshots**
![image](https://user-images.githubusercontent.com/2421483/48377358-e1749c00-e6cd-11e8-80b7-efe755827db4.png)

**System:**
 - OS: MacOS
 - Device: Macbook Pro
 - Framework: angular
- Angular CLI: 7.0.5
- Node: 9.0.0
- Angular: 7.0.3

ps. In the past I was also not able to integrate storyshots with angular, but since now there is a new way of configuring storybook with angular and since angular also changed a bit, I decided to create a new one using latest versions of everything and try again. I hope that's ok. Thank you in advance!

**Comment by igor-dv** [comment]
PR is here - https://github.com/x1c0/test-angular-storybook/pull/1

**Comment by igor-dv** [comment]
If there are some missing action items in docs, that'd be great you could add them 😉

**Comment by x1c0** [comment]
Sure! I’ll do, once again thanks for your help

**Comment by x1c0** [comment]
would it be better if I try to fix it on https://github.com/storybooks/storybook/tree/next/examples/angular-cli and then add maybe a link into main README on the angular section?
