### ISSUE TITLE
Feature Request: Addon for live code playground

### ISSUE THREAD

**Issue by simpleimpulse** [storybooks/storybook#4782]
**Introduction**
As providers of the TELUS Design System's component catalog, we'd like our users to be able to interact with potential components and experiment with various props and settings in a live code playground.

**Describe the solution you'd like**
We would like to have a live code playground that allows our users to edit source code and view the results rendered immediately.

**Describe alternatives you've considered**
The Knobs addon is the only thing that comes close to providing similar functionality, but it still isn't the same experience as being able to edit code and view the results rendered instantaneously.

**Are you able to assist bring the feature to reality?**
Yes, we are willing to work with Storybook to help build this feature.

**Additional context**
The live playground would be similar to what CodePen provides, or our current [Styleguidist solution](https://tds.telus.com/components/index.html#!/Heading/0)

**Comment by Keraito** [comment]
As far as I remember, I think @expe-lbenychou was working on something like this together with Norbert. Tagging him to see whether this was the case and what the potential status is
