### ISSUE TITLE
Feature Request: Ability to make Storybook more themable

### ISSUE THREAD

**Issue by simpleimpulse** [storybooks/storybook#4783]
**Introduction**
As providers of the TELUS Design System's component catalog, we'd like to be able to theme our Storybook catalog, including adding the Telus logo, colours and other brand elements to give our users a consistent experience across our products.

**Describe the solution you'd like**
A theming addon or other similar solution that provides more options than what is currently available. 
The top things that we need are:
- Custom logo
- Custom fonts and colours on the sidebar
- Ability to make the whole thing responsive

**Describe alternatives you've considered**
We have tried using the currently available theming options and they seem to only be working partially, and do not cover our current needs.

**Are you able to assist bring the feature to reality?**
Yes, we are willing to work with Storybook to help bring this feature to life.

**Comment by Keraito** [comment]
Hey @simpleimpulse, this is definitely something that is actively being worked on. See: https://twitter.com/NorbertdeLangen/status/1063790691988504576. We definitely value any feedback or suggestions regarding it. The best way to speed up the progress is either through joining our Discord (see README) or contacting @ndelangen via either Twitter or Discord.
