### ISSUE TITLE
Memory leak and high cpu when using symlinks 

### ISSUE THREAD

**Issue by RuneKR** [storybooks/storybook#4788]
**Describe the bug**
Memory leak and high cpu when using symlinks 

**To Reproduce**
I am using storybook v3.4.11. I can provide an example repo on request.

I have a monorepo setup:

- node_modules (root of symlink)
- packages/node_modules/my-scope/
  - packagea
    - node_modules (symlink)
  - packageb
    - node_modules (symlink)

**Expected behavior**
When i use symlinks the CPU goes to 99% and uses more than 2 GB of memory! Removing the symlinks and running start-storybook will result in normal behavior of 30 % cpu and 500 MB of memory.

**System:**
 - OS: Windows 10 and also Mac OS

**Comment by RuneKR** [comment]
I suspect it might be related to my require.context:

```require.context('../packages/node_modules/@my-scope/', true, /story\.tsx$/)``` 

since i will have a node_modules folder under `@my-scope/{package}`

**Comment by igor-dv** [comment]
Can we help in some way? It's not directly related to Storybook, but if you have some reproduction I will try to take a look.

**Comment by RuneKR** [comment]
Hi,

Awesome to hear. I will get something setup later today!

It doesn't look like to be caused by the fact that the modules are symlinked but rather that node_modules gets scanned even though they are a part of the regex ignore

**Comment by RuneKR** [comment]
Sorry for the delay - https://github.com/RuneKR/bad-performance

I did come up with a solution, but i am keen to hear your thoughts!

**Comment by igor-dv** [comment]
Will check this soon

**Comment by RuneKR** [comment]
Thank you!

**Comment by remorses** [comment]
I am facing the same issue when using pnpm, pnpm uses symlinks for every dependency

I think storybook recompiles the same package more than once because it is using the symlinked path to identify a module, it should instead use the real resolved path

**Comment by remorses** [comment]
Or maybe the issue is `require.context`

**Comment by shilman** [comment]
@remorses there are a few possibly related PRs that just got merged into 6.1. does this fix the problem? https://github.com/storybookjs/storybook/pulls?q=is%3Apr+author%3Amerceyz+is%3Aclosed

**Comment by RuneKR** [comment]
I found my issue to be related to webpack watch and babel transpile. I had to ignore the node module folders in the symlinked paths manually:

```
// watch configuration
config.watchOptions.ignored = ['./node_modules', './packages/**/node_modules']

// babel configuration for each symlinked path
config.module.rules[0].exclude.push('./packages/my-path/node_modules')
config.module.rules[0].exclude.push('./packages/my-other-path/node_modules')
)
````

**Comment by remorses** [comment]
I resolved my issue by making `resolve.symlinks` true in the storybook webpack config

Compiled modules went from 20k to 6k
