### ISSUE TITLE
Migration to Storybook 4 issue with webpack config

### ISSUE THREAD

**Issue by amittkSharma** [storybooks/storybook#4799]
Hi Team,

During migration the storybook to new version 4.0.7, there is an issue in starting the storybook. Webpack is freaking out. The application is based on Create-React-App 1 and storybook has an extended webpack.config.js.  There are two issues:

1. Failed to load presets
2.  Cannot read property 'rules' of undefined (During the loading custom webpack config task)

The webpack config looks like:
```javascript
const path = require("path")
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

module.exports = (baseConfig, env, config) => {
  baseConfig.module.rules.push({
    test: /\.css$/,
    loaders: [
      'style-loader',
      'css-loader'
    ],
    include: path.resolve(__dirname, "../")
  });
  config.module.rules.push({
    test: /\.tsx?$/,
    loader: [
      'thread-loader',
      'ts-loader?happyPackMode=true',
      'react-docgen-typescript-loader'
    ]
  }, {
    test: /\.md$/,
    loader: [
      'thread-loader',
      'markdown-loader'
    ]
  })
  config.plugins.push(new ForkTsCheckerWebpackPlugin({
    checkSyntacticErrors: true,
    watch: path.resolve(__dirname, "../stories"),
    workers: ForkTsCheckerWebpackPlugin.TWO_CPUS_FREE,
  }))
  config.resolve.extensions.push(".ts", ".tsx")
  return config;
}
```

Waiting for some pointers from your side in order to rectify the problem.

Thanks in advance
Amit

**Comment by igor-dv** [comment]
So, I understand that before migration to v4 everything worked ok with this custom `webpack.config.js`? Can you also share some stack trace / error log?

**Comment by amittkSharma** [comment]
I tried by removing the rule as suggested above, but still getting the same error.

**Comment by ronihcohen** [comment]
On a new project (CRA 2.1.1 + Storybook 4.0.1) https://storybook.js.org/configurations/typescript-config/ didn't work for me today.

**Comment by igor-dv** [comment]
v4.1.0-alpha already supports TS out of the box for the CRA2 users, without creating a custom webpack.config. Can you check this ?

**Comment by igor-dv** [comment]
@amittkSharma , do you have a reproduction repo?

**Comment by amittkSharma** [comment]
@igor-dv: Will create one tomorrow and send you the repo name.

Thanks
- Amit

**Comment by amittkSharma** [comment]
@igor-dv: Here is the basic [repo structure](https://github.com/amittkSharma/cra1-storybook), please take a look at it. In my system, I am not able to reproduce the above error as there were some updates in the past but feel free to check it.

Thanks 
Amit

**Comment by amittkSharma** [comment]
This is issue is closed as reproduction repo is provided to the concerned team.
- Amit

**Comment by andremw** [comment]
Same problem here. @amittkSharma have you found a solution?
