### ISSUE TITLE
Solo Mode

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybook#480]
Currently we need to install React Storybook into an app in order to use it. 

But it would be pretty useful to run few stories, without a full app. We do it by installing storybook globally. 

Then we can run command like this and we get a storybook:

```
start-storybook -p 6873 path/to/stories
```

What do you guys think?

**Comment by rhalff** [comment]
If so, it's better to use commands I think, e.g:

```bash
storybook start -p 6873 path/to/stories
storybook build
```

**Comment by mnmtanish** [comment]
We should also consider other frameworks. We currently support both React and React Native and there'll be more in the future.

If it'll be used only as a global command, it'll be okay to bundle all frameworks with it and automatically detect the framework when it's executed.

**Comment by ndelangen** [comment]
#1108 Is where We'll consider this. I think even with just the current CLI it's possible.

**Comment by ndelangen** [comment]
With support for multiple app types, this new CLI option would have to ask the user what app they want!
