### ISSUE TITLE
Static build (S)css issue

### ISSUE THREAD

**Issue by mick-feller** [storybooks/storybook#4802]
**Describe the bug**
When running storybook everything works perfect as soon as i'm generating a static build most of my scss files are not being included

**Expected behavior**
I expect that the static build looks the exact same as the storybook run command.

**Screenshots**
When running Storybook:
![image](https://user-images.githubusercontent.com/32658692/48647966-a0c19f00-e9bb-11e8-97a1-3056031a115c.png)

When generating a static bundle:
![image](https://user-images.githubusercontent.com/32658692/48647934-8a1b4800-e9bb-11e8-9034-8a3dae9fa7dc.png)

**Code snippets**
.storybook/webpack.config.js
```js
const path = require("path");
const eslintFormatter = require('react-dev-utils/eslintFormatter');
const fs = require('fs');
const appDirectory = fs.realpathSync(process.cwd());

module.exports = {
  module: {
    rules: [
      {
        test: /\.stories\.jsx?$/,
        loaders: [require.resolve('@storybook/addon-storysource/loader')],
        enforce: 'pre',
      },
      {
        test: /\.(js|jsx|mjs)$/,
        enforce: 'pre',
        use: [
          {
            options: {
              formatter: eslintFormatter,
              eslintPath: require.resolve('eslint'),
              emitWarning: true
            },
            loader: require.resolve('eslint-loader'),
          },
        ],
        include: path.resolve(appDirectory, 'src'),
      },
      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"],
        include: path.resolve(__dirname, "../")
      },
      {
        test: /\.svg$/,
        loader: 'raw-loader'
      }
    ]
  }
};
```
Accordion.stories.jsx
```js
import React from 'react';
import { storiesOf } from '@storybook/react';
import Accordion, { AccordionHeader, AccordionContent } from 'components/Accordion';

storiesOf('Components|Accordion', module)
  .addParameters({ jest: ['AccordionContext'] })
  .add('Accordion Example', () => {
    return (
      <Accordion auid="Story">
        <AccordionHeader auid="Story">
          Accordion Title
        </AccordionHeader>
        <AccordionContent auid="Story">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In malesuada ante
          vel libero elementum sollicitudin. Proin quis est neque. Curabitur mollis
          scelerisque odio, eget convallis nisi egestas sit amet. Duis ut iaculis
          dolor, id pretium justo. Class aptent taciti sociosqu ad litora torquent per
          conubia nostra.
        </AccordionContent>
      </Accordion>
    );
  });
```
Snippet of the actual component, to show how i'm importing scss file
```js
import React, { Component } from 'react';
import classNames from 'classnames';
import PropTypes from 'prop-types';
import { AccordionContext, DISPLAY_NAME } from './AccordionContext/AccordionContext';
import toAuid from '../../utils/auid';
import './Accordion.scss';
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Browser: chrome
 - Framework: react
 - Version: 4.0.6

**Additional context**
I have also tried to extract the css with minicssextractplugin same result happens

My folder structure looks like this:
- .storybook
- components
-- Accordion
--- Accordion.jsx
--- Accordion.scss
- stories
-- Components
--- Accordion
---- Accordion.stories.jsx

This happens with all the stories not just this specific one FYI.

One thing to mention every .scss file i include in my .storybook/config.js file is being included properly.

I've also tried setting the
```js
include: path.resolve(__dirname, '../')
```

to:
```js
include: path.resolve(__dirname, '../components')
```

Which results in an error saying it can't include the .scss file i probably need a correct loader for that file.

Any help would be welcome

**Comment by igor-dv** [comment]
Hey @mick-feller ,do you have a reproduction somewhere?

**Comment by mick-feller** [comment]
Here you go:
https://github.com/mick-feller/storybook-build-debug

Tried to make it as small as possible but left all addons etc.

I've in the meanwhile upgraded to the new alpha version to see if that helped, no luck there either

**Comment by igor-dv** [comment]
I've tried to set up the repo, but there are some `@od/*` packages (probably internals ?) that are missing...

**Comment by igor-dv** [comment]
Ok, I don't get what's the thing here... Downgraded it down to v4.0.0, and the problem still remains 🤦‍♂️

**Comment by mick-feller** [comment]
The problem with the build still remains you mean?

**Comment by igor-dv** [comment]
I meam the problem with the build.

**Comment by mick-feller** [comment]
The only potential difference i can see from other projects is that i don't have any cra or other build for my app/components. I'm relying only on the storybook build. I don't know if this makes any difference.

**Comment by anhmv91** [comment]
I am facing with this problem too when build static, and I think somethings went wrong with `mini-css-extract-plugin`, I currently temperature fix by move   `<script src="css/iframe.7bbbcae7.css" defer></script>` and `        <script src="css/iframe.7bbbcae7.css" defer></script>` up to the `<head>` and use the `link ref stylesheet` instead, in `frame.html`

**Comment by igor-dv** [comment]
I think @mick-feller is not using `mini-css-extract-plugin` for static storybook mode.

**Comment by mick-feller** [comment]
I tried several ways actually.

Without mini-css-extract-plugin, with mini-css-extract-plugin and with extract-text-plugin.

Non of these worked for me

**Comment by igor-dv** [comment]
A good friend of mine (@leeran88) pointed me to an issue (#4918) that straight connected me to this problem 😄 

The thing that I missed in your setup is a `"sideEffects": false` in your `package.json`. 
Checked it right now and setting `sideEffects: true` to the specific rule solved the issue 👍 

```js
{
        test: /\.scss$/,
        sideEffects: true,
        loaders: [
            "style-loader",
            "css-loader",
            "sass-loader"
        ],
        include: path.resolve(__dirname, "../")
    }
```

**Comment by mick-feller** [comment]
You are the MAN!!!

Thank you very much, never realized that this could cause that.

Thanks again!!

**Comment by edelgado** [comment]
Thank you again! 🎉
