### ISSUE TITLE
I don't see a "play" option anymore 

### ISSUE THREAD

**Issue by kwintessential2** [storybooks/storybook#4803]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: [e.g. iOS, Windows10, MacOS]
 - Device: [e.g. iPhoneX, Macbook Pro 2018]
 - Browser: [e.g. chrome, safari]
 - Framework: [e.g. react, vue, angular]
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0]

**Additional context**

**Comment by Keraito** [comment]
@kwintessential2 could you provide more detail on what you mean exactly? It's quite unclear on what your problem is right now.

**Comment by kwintessential2** [comment]
![image](https://user-images.githubusercontent.com/13756210/48675033-14c58980-eb19-11e8-9523-67fa43b30b6f.png)

**Comment by igor-dv** [comment]
@kwintessential2, sorry I am closing this.
Let us know If you have a proper explanation of what the "play" option you are missing. 
(Are you sure it's related to Storybook ?)
