### ISSUE TITLE
Having a frozen lockfile prevents storybook from installing its dependencies during init

### ISSUE THREAD

**Issue by StephanBijzitter** [storybooks/storybook#4805]
**Describe the bug**
Having a frozen lockfile prevents Storybook from installing its dependencies during init.

**To Reproduce**
1. Have a project with some dependencies
2. Have a `.yarnrc` file with `--install.frozen-lockfile true`
3. Run `yarn sb init`

**Expected behavior**
Storybook should install dependencies using yarn's cli, rather than modifying the `package.json` itself.

**Screenshots**
<img width="626" alt="screenshot 2018-11-18 at 20 58 31" src="https://user-images.githubusercontent.com/1649903/48677397-be863400-eb74-11e8-9acf-7c985ba6abaa.png">

**Code snippets**
`.yarnrc`:
```
--install.frozen-lockfile true
save-prefix ""
```
Note that Storybook also completely ignored my `save-prefix` value.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Framework: React
 - Addons: None
 - Version: 4.0.7

**Comment by StephanBijzitter** [comment]
Now it's not stale anymore :-)

**Comment by shilman** [comment]
@StephanBijzitter Is this something you might be able to contribute on? The CLI code should be pretty accessible.

**Comment by StephanBijzitter** [comment]
I'll see if I can make some time, but I don't think I'll be able to do this anytime soon

**Comment by MikaelCarpenter** [comment]
Haha coming in two days too late for stale bot. But this is a blocker for my team being able to adopt storybook so I'll take a crack at a PR for this 👍

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.36 containing PR #6629 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.37 containing PR #6695 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
