### ISSUE TITLE
Pressing on Sidebar list item could show content instead of just expanding content

### ISSUE THREAD

**Issue by bernatfortet** [storybooks/storybook#4818]
I wonder if it possible to start showing content when pressing in the dropdowns of the Manager App like in the older version of Storybook. [Hack Oregon is a good example](https://hackoregon.github.io/component-library/?selectedKind=Welcome&selectedStory=to%20Storybook&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

This image also shows the sidebar without dropdowns:
![image](https://user-images.githubusercontent.com/390010/48754842-02963900-ec48-11e8-8e28-942f62a984f0.png)

**Comment by Keraito** [comment]
@bernatfortet So basically you want that when you click the dropdown menus, the first story (for example) would be immediately shown?

**Comment by igor-dv** [comment]
Closing this as a duplicate to #2863.
