### ISSUE TITLE
Build error from slow start - babel-core vs @babel/core

### ISSUE THREAD

**Issue by andyhall** [storybooks/storybook#4821]
Hi,

I'm following the [slow start](https://storybook.js.org/basics/guide-vue/) instructions, which start with:

```sh
npm i --save-dev babel-core
npm i --save-dev babel-loader
```

When I later run the script to start storybook, it fails out with:

```
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). 
If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
```

Do I need a different `core` or a different `loader`, or is something else going on?

(Or even better, is there any way to get a "built" version of storybook that's already transpiled and doesn't need Babel to be present at runtime? I assume not but if there is that would be ideal!)

Thanks!

**Comment by igor-dv** [comment]
The is a bit outdated. You should use `@babel/core`.

**Comment by y-nk** [comment]
@andyhall i'm gonna update the wiki page as we speak, but meanwhile you can use [this post](https://github.com/storybooks/storybook/issues/4505#issue-372454482) as a up-to-date slow start instruction set for vue.

**Comment by andyhall** [comment]
@y-nk Those steps work, thanks! Feel free to close this when the doc issue is resolved.

**Comment by y-nk** [comment]
@andyhall PR to update doc is on its way. Thank you for reporting !
