### ISSUE TITLE
New story file format

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#4848]
As part of a push towards [a better documentation mode](
https://github.com/storybooks/storybook/issues/4341), and to make stories more general and more easily consumed by other tools (thus making things like a [Docz plugin](https://github.com/hydrateio/docz-plugin-storybook) easier), we are considering a new file format for stories that is less tied to SB APIs:

The current proposal is a file `Component.examples.js`, which in it's simplest form looks like:

```js
import React from 'react';

import Component from 'somewhere';

export default Component;

export const variant1 = () => <Component variant="1" />;
export const variant2 = () => <Component variant="2" />;
export const variant3 = () => <Component variant="3" />;
````

More detail is proposed [in this gist](https://gist.github.com/tmeasday/4de20eab47226a870ab1025642ba848c) as well as some discussion with @igor-dv and @transitive-bullshit with regards to some thoughts about the format.

The primary use cases we are considering include (please reach out if you have others that are relevant):

1. Defining a set of components and stories to appear inside storybook / docs automatically
2. Making it easy to render one story, or the metadata of one component at a time inside a `mdx` file.
3. Making it easy to re-use a story to drive a test case in a tool like Jest.
4. Making it easy for external tools to catalogue a list of stories inside a project w/o needing the storybook runtime.

If you have other proposals, this is the place to reach out with them. Some alternatives:

## Proposal B: A more modern view on the current format 
[by @transitive-bullshit here](https://gist.github.com/tmeasday/4de20eab47226a870ab1025642ba848c#gistcomment-2767279):

```js
import { Story, Stories } from '@storybook/react'
import Button from './Button'

export default new Stories(Button, [
  new Story('with text', () => (
    <Button>Hello Button</Button>
  )),

  new Story('with emoji', () => (
    <Button>
      <span role='img' aria-label='so cool'>
        :+1: 
      </span>
    </Button>
  ))
])
```

**Comment by donaldpipowitch** [comment]
> As part of a push towards [a better documentation mode](#4341)

FYI: The link points to this issue, because #4341 is treated as an anchor.

**Comment by tmeasday** [comment]
After talking with @transitive-bullshit about his format's pros+cons we've agreed to have a go with the format in the gist to get a feel for it. PR/branch is here: https://github.com/storybooks/storybook/pull/4885 -- all welcome to get involved / make suggestions
