### ISSUE TITLE
addon-options `withOptions` not typed

### ISSUE THREAD

**Issue by dfee** [storybooks/storybook#4849]
`@storybook/addon-options` has deprecated `setOptions`, and forwards us to `withOptions`. This, however, is untyped.

It appears that a good(?) type for it would be:
```ts
export function withOptions(options: Options): void;
```

here is the code: https://github.com/storybooks/storybook/blob/0a8e860ee335611204c8bc5b5fd3e6c7b7f964b8/addons/options/src/preview/index.js#L52
here are the types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/storybook__addon-options/index.d.ts

@joscha (tagged because you're one of the `@types` authors)

**Comment by shilman** [comment]
@dfee I'm not sure what's the recommended protocol for updating types in DefinitelyTyped, perhaps this? https://definitelytyped.org/guides/pull-request.html

That said, we've also been discussing pulling back the type definitions into the Storybook repo, and issues like the one you've raised here is why. https://github.com/storybooks/storybook/pull/4753

**Comment by igor-dv** [comment]
As was already mentioned in similar issues, we are not maintaining typings in definitelytyped, and we are going to bring types into Storybook soon.

**Comment by joscha** [comment]
They should be, I think the pull request was merged last week.
@igor-dv agree co-locating the types would be best but the types have been much more up to date ever since they are on DefinitelyTyped - more hands to help I think ;)
