### ISSUE TITLE
Better terminal output for webpack built

### ISSUE THREAD

**Issue by Donaldini** [storybooks/storybook#486]
Even though it's great to have hot reloading whenever the code is built again, I would like a clearer message in my console to tell me my code has been built.

As an example I can show you how parallel-webpack outputs this:

![screen shot 2016-09-23 at 13 26 53](https://cloud.githubusercontent.com/assets/2185680/18784357/e081d694-8191-11e6-9d80-dab6f5e0512f.png)

Reference code: https://github.com/trivago/parallel-webpack/blob/master/src/webpackWorker.js#L91

Advantages:
- They add a timestamp to show when the built was ready (this is probably the best advantage)
- Use of colors to differentiate between different kind of data like time and other messages.

**Comment by arunoda** [comment]
Okay. I like this.
Another idea is to integrate [webpack dashboard](https://github.com/FormidableLabs/webpack-dashboard).
May be it'll too big for here.

I'm open for PRs for this.
