### ISSUE TITLE
Allow storybook components to be listed without directory

### ISSUE THREAD

**Issue by iambumblehead** [storybooks/storybook#4861]
**Is your feature request related to a problem? Please describe.**
Allow storybook components to be listing without directory

For example, [here][0] two different buttons are listed under "Button". Offer an abstraction that would allows one to list items like "button-text" or "button-emoji" at the top level of the list without nesting inside another item such as "Button"

[0]: https://storybook.js.org/basics/guide-react/#write-your-stories

**Comment by hughanderson4** [comment]
I need a top level item in the nav as well.  Not nested under anything else.
It will be a "Getting Started" guide.
Please offer a way to write a story that is not nested under a sub-nav.

**Comment by hipstersmoothie** [comment]
@hughanderson4 You can do something like I did here 

I am not sure how to not have a dropdown. But this will get you an intro.

https://github.com/hipstersmoothie/materialize-hooked/blob/master/Components/welcome.story.tsx
http://hipstersmoothie.com/materialize-hooked/?selectedKind=Welcome&selectedStory=Introduction&full=0&addons=0&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel&background=%23fff

**Comment by igor-dv** [comment]
I think it's duplicate to #2863
