### ISSUE TITLE
Storybook takes up to 2 minutes to start and up to 10 to reload

### ISSUE THREAD

**Issue by victorct-pulsarup** [storybooks/storybook#4864]
**Describe the bug**

I've been using Storybook for like two days and it seems the initial loas is very slow, it takes up to 2 mins!

I have 10 stories so far, when I change something inside a Story it can take up to 10 mins to do a hot-reloading!  

I'd like to investigate this further and, if possible, improve this but I don't really know where to start.

**Expected behavior**
Not to take too much time to start and to do hot reloading

**Screenshots**
![captura de pantalla 2018-11-26 a la s 4 28 25 p m](https://user-images.githubusercontent.com/44884350/49046030-6e245d00-f198-11e8-8ffd-68d84bb183d6.png)

**Code snippets**
Here is my custom webpack configuration (really simple)

```
const path = require("path");

// Export a function. Accept the base config as the only param.
module.exports = (storybookBaseConfig, configType) => {
  // configType has a value of 'DEVELOPMENT' or 'PRODUCTION'
  // You can change the configuration based on that.
  // 'PRODUCTION' is used when building the static version of storybook.

  // Make whatever fine-grained changes you need
  storybookBaseConfig.devtool = "(none)"
  storybookBaseConfig.profile = true

  // Return the altered config
  return storybookBaseConfig;
};

```

My config file:

```
import { configure, addDecorator, setAddon } from '@storybook/react';

import { withInfo } from '@storybook/addon-info';
import { withBackgrounds } from '@storybook/addon-backgrounds';
import centered from '@storybook/addon-centered';

import '../src/index.css';

// import '../src/fontIconsInitializer'


addDecorator(withInfo)


addDecorator(centered)	

addDecorator(
  withBackgrounds([
    { name: 'white', value: '#ffffff', default: true},
    { name: 'blue', value: '#3b5998' },
  ])
)


const stories = ["./Onboarding/ProgressBar.stories.js", "./components/common/Buttons/Button.stories.js",
				"./components/common/Buttons/ButtonIcon.stories.js", "./components/common/Links/Links.stories.js",
				"./components/common/Texts/TextEdition.stories.js", "./login/Login.stories.js", "./sections/kanban/lane/components/LaneContainer.stories.js"]

// const req = require.context('../src/stories', true, /.stories.js$/);

function loadStories() {
	// console.log(req.keys(), req)
	stories.map( story => require(story))
	// req.keys().forEach(filename => req(filename));
	// req('')
}

configure(loadStories, module);
```

And the addons file:
```

import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-backgrounds/register';


```

**System:**
 - OS: MacOS Mojave
 - Device: MacBook Pro (Mid 2012)
 - Framework: react
 - Version: 4.06.5

**Additional context**

Using Docker 2.0.0

**Comment by victorct-pulsarup** [comment]
Hello, I have found the problem is related to Docker and Mac themselves, I will close the issue, and leave the url for the Docker github issue regarding mounting systems.

Maybe it could be worth mentioning this in the README.md for further reference.

https://github.com/docker/for-mac/issues/77

**Comment by ndelangen** [comment]
Great to see you found the problem @victorct-pulsarup 

Would you want to open a PR adding the docker on mac notice?

**Comment by victorct-pulsarup** [comment]
Yeah I will open a PR
