### ISSUE TITLE
addon-knobs `select` seemingly mistyped (typescript)

### ISSUE THREAD

**Issue by dfee** [storybooks/storybook#4865]
If I want to provide a `null` option for a `select` options, I have to do casting:

```typescript
const alignSelectOptions = ({
  Default: null,
  centered: "centered",
  right: "right",
} as unknown) as { [k: string]: string };
```

In the [documentation](https://github.com/storybooks/storybook/tree/next/addons/knobs#select) however it provides the following example:
```js
import { select } from '@storybook/addon-knobs';

const label = 'Colors';
const options = {
  Red: 'red',
  Blue: 'blue',
  Yellow: 'yellow',
  Rainbow: ['red', 'orange', 'etc'],
  None: null,
};
const defaultValue = 'red';
const groupId = 'GROUP-ID1';

const value = select(label, options, defaultValue, groupId);
```

But the types doesn't match, as the `SelectValue` is expected to be a `string` or a `number` (hence my casting to `unknown`, then re-casting to `string`):
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7d88a7099f407a449bb210a4c36fecbdc0454ff/types/storybook__addon-knobs/index.d.ts#L50

As discussed in another issue (https://github.com/storybooks/storybook/issues/4849) these typings might be brought in-house, so I figured I'd file another issue.

**Comment by igor-dv** [comment]
So what is this issue about and would mind to PR the fix ? 😉
