### ISSUE TITLE
Document configuration options for Storyshots test

### ISSUE THREAD

**Issue by spawnia** [storybooks/storybook#4875]
I use storyshots to do a simple smoke test for my stories. As my components use **ref** and **portal**, the default react-test-renderer does not work for me.

After digging through the source code, i found that it is indeed possible to overwrite the renderer, contrary to what the documentation says about the `test` option: https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-core#test

```js
import initStoryshots, { renderWithOptions } from '@storybook/addon-storyshots';
import { mount } from 'enzyme';

// Ensure the stories are rendered without an error
initStoryshots({
  test: renderWithOptions({
    // Overwrite the default react test renderer, as it does not support
    // refs and portals, both of which are heavily used by antd
    renderer: mount,
  }),
});
```

The documentation could be improved by specifying the options that can be given to `renderWithOptions` and `snapshotWithOptions`, especially this hidden functionality of overwriting the renderer.

**Comment by igor-dv** [comment]
Would you like to PR this to docs?

**Comment by spawnia** [comment]
@igor-dv Sent a PR :)
