### ISSUE TITLE
Missing Styles in Storybooks when used with Vue-CLI

### ISSUE THREAD

**Issue by MansoorBashaBellary** [storybooks/storybook#4877]
**Describe the bug**

Styles are missing in storybooks when used with Vue CLI. Some styles are loaded, others are not. Fonts are missing. No error messages though.

**To Reproduce**

Reproduction URL for the same is:
https://github.com/MansoorBashaBellary/vue-cli-storybook

**Expected behavior**

Storybooks shouldn't break as in the screenshot below

**Screenshots**

![screen shot 2018-11-27 at 2 43 57 pm](https://user-images.githubusercontent.com/42977064/49107586-16e3c280-f254-11e8-85c5-8ba5cb518e77.png)

**Additional context**

Prior to this issue, I was using `@storybook/vue` version of `4.0.0-alpha.20`, while using this specific version of `@storybook/vue`, storybooks were working fine.

In the recent times, I have added changes to `Deep theme` stories nav panel. PR for the same is:

https://github.com/storybooks/storybook/pull/4702

Above `deep theme` changes got published to `4.1.0-alpha.x` version. On upgrading the `storybook` dependencies to `4.1.0-alpha.8`, I see styles of storybooks are broken.

Storybooks without Vue CLI is working fine. Reproduction URL for the same is:
https://github.com/MansoorBashaBellary/react-storybooks

Could someone help fixing this issue. I wanted to use the changes of `Deep theme` without breaking the storybooks.

**Comment by MansoorBashaBellary** [comment]
Tried to figure out root cause of this issue, but was not able find it. But got a work around to fix this issue with `resolutions` field in `package.json` like:

"resolutions": {
  "@storybook/components": "4.1.0-alpha.2",
  "@storybook/ui": "4.1.0-alpha.2"
}

Adding above code in `package.json` fixed my issue

**Comment by igor-dv** [comment]
That strange. I can't see this problem in the official example

**Comment by MansoorBashaBellary** [comment]
@igor-dv - This is happening due to `vue-cli-plugin-storybook`. This is not as such issue of `storybooks`. Created an issue for `vue-cli-plugin-storybook`:

https://github.com/storybooks/vue-cli-plugin-storybook/issues/40

Closing this issue

**Comment by igor-dv** [comment]
@y-nk , IMO we need to bring the `vue-cli` integration into SB as a preset.
