### ISSUE TITLE
Create "sitemap"/list of all stories on build

### ISSUE THREAD

**Issue by donaldpipowitch** [storybooks/storybook#4878]
**Is your feature request related to a problem? Please describe.**
It is possible to get all stories at runtime/on the client with `import {configure, getStorybook} from '@storybook/react';`, but sometimes you want to have the same information somewhere else. E.g. if you want to run a test against all stories and the test runner isn't aware of Storybook at all.

You can _expose_ the stories on your client and let the test runner crawl the information (as I did in the case https://gist.github.com/donaldpipowitch/898854e2f71f64d0d91e199537b3ee1a#file-config-js), but this seems to be a brittle workaround and makes certain things harder to achieve (e.g. if I would use Jest in this example and I'd want to create a `test` for every story, I'd need to add a custom setup/environment to fetch my data _before_ the tests are opened, because fetching is async and test definitions in Jest need to be known synchronous/on startup). This can be quite cumbersome and would be solved if a "sitemap"/list of all stories would be created as an artefact during the build. Then I could just `require` that information.

**Describe the solution you'd like**
I'd suggest that Storybook would include a custom plugin (either by default or as an opt-in) to create some `stories.json` in the root of the storybook. The `stories.json` could look like this:

```json
[
  {
    "kind": "Hello",
    "story": "World"
  }
]
```

My main use case is crawling the storybook, so maybe it could even include the `encodeURIComponent`'d version or even the complete query, but that would be a nice-to-have:

```json
[
  {
    "kind": "Hello 1",
    "story": "World 2",
    "encodedKind": "Hello%201",
    "encodedStory": "World%202",
    "query": "?selectedKind=Hello%201&selectedStory=World%202"
  }
]
```

**Describe alternatives you've considered**
Mainly two things:
- Keep a file system convention so that every kind is represented by a single directory and every story is represented by a single file. (We partially do this, but it can be brittle. It needs to be explained to others, it is a custom solution, it can become more complex for nested kinds).
- The solution represented in the gist: https://gist.github.com/donaldpipowitch/898854e2f71f64d0d91e199537b3ee1a#file-config-js.

**Are you able to assist bring the feature to reality?**
Probably yes :)

**Comment by BPScott** [comment]
This would be useful for [percy-storybook](https://github.com/percy/percy-storybook) which currently does something very similar to @donaldpipowitch's gist workaround.

**Comment by fredboyle** [comment]
Was there ever a solution implemented for this? This would be very useful for our team as well.

**Comment by xettri** [comment]
Following code example works for me after

```diff
"scripts": {
    "storybook": "storybook dev -p 6006",
-   "build-storybook": "storybook build",
+   "build-storybook": "storybook build && node ./generate-sitemap.js",
 }
```

#### generate-sitemap.js
```js
const fs = require('fs');
const data = require('./storybook-static/index.json');

const sitemapHead =
  '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

function generateSitemap(entries) {
  const lastmod = `    <lastmod>${new Date().toJSON()}</lastmod>\n`;

  let sitemap = '';
  for (const key in entries) {
    if (entries.hasOwnProperty(key)) {
      const entry = entries[key];
      const url = `https://<your-storybook-url>/?path=/${entry.type}/${key}`;
      sitemap += `  <url>\n    <loc>${url}</loc>\n${lastmod}  </url>\n`;
    }
  }
  return `${sitemapHead}${sitemap}</urlset>`;
}

const sitemapXML = generateSitemap(data.entries);
fs.writeFileSync('./storybook-static/sitemap.xml', sitemapXML, 'utf-8');
```
