### ISSUE TITLE
react native -> /dist not needed?

### ISSUE THREAD

**Issue by slorber** [storybooks/storybook#4879]
Hi,

``` 
"main": "dist/index.js",
  "jsnext:main": "src/index.js",
  "bin": {
    "storybook": "dist/bin/storybook.js"
  },
  "scripts": {
    "prepare": "node ../../scripts/prepare.js"
  },
```

For ReactNative, the /dist package is not needed because all RN packages are transpiled by Metro by default. Btw Metro does not use jsnext:main so not sure this setting is useful.

Also I tried to run StorybookUI on RN with src and it works fine.

Just wanted to mention that, not sure exactly what should be done but I suspect it's not needed to transpile / use the whole src folder. Maybe it's needed for the storybook bin which start the web server ?

**Comment by Gongreg** [comment]
Hey @slorber, you are correct, the transpilation is unneeded for preview folder in react-native. It is necessary for server part. Moving forward we will separate preview part from server part to a separate module. There is a PR for that done by me, but it is a little bit stale so I will have to redo it.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.7 containing PR #4942 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
