### ISSUE TITLE
Request: Support For Stories Distributed Amongst Lerna Packages

### ISSUE THREAD

**Issue by Undistraction** [storybooks/storybook#4890]
**Is your feature request related to a problem? Please describe.**
At present Storybook will not work with stories distributed amongst packages in a monorepo. Storybook's babel loader assumes that it only needs to transpile js within `src`, so if you use a configuration that looks for stories outside of `./src` that are not transpiled, for example:
```
const req = require.context('../../../packages', true, /.stories.js$/)
```
Loading these (untranspiled) stories results in errors such as:
```
ERROR in ../components/src/components/nav/LinkList/LinkList.js 9:2
Module parse failed: Unexpected token (9:2)
You may need an appropriate loader to handle this file type.
```
This is because it is encountering JSX in files that are outside of `src` that are not transpiled and is choking on them.

**Describe the solution you'd like**
It would be great if Storybook offered a config option to specify which directories it should load using babel-loader.

**Describe alternatives you've considered**
There is a generic solution for create-react-apps [here](https://www.npmjs.com/package/babel-loader-lerna-cra)

**Are you able to assist bring the feature to reality?**
maybe

**Comment by hipstersmoothie** [comment]
This should work. I have a storybook that loads stories from another monorepo package. Try adding this to your storybook webpack config. Find the babel rule in loaders and modify the include and exclude to include the parent directory (for a monorepo this will be `packages`).

```
module.exports = (baseConfig, env, config) => {
  // Find Babel Loader
  const babelRules = config.module.rules.filter(rule => {
    let isBabelLoader = false;

    if (rule.loader && rule.loader.includes('babel-loader')) {
      isBabelLoader = true;
    }

    if (rule.use) {
      rule.use.forEach(use => {
        if (typeof use === 'string' && use.includes('babel-loader')) {
          isBabelLoader = true;
        } else if (
          typeof use === 'object' &&
          use.loader &&
          use.loader.includes('babel-loader')
        ) {
          isBabelLoader = true;
        }
      });
    }

    return isBabelLoader;
  });

  babelRules.forEach(rule => {
    rule.include = /../;
    rule.exclude = /node_modules/;
  });
  
  return config;
};
```

Let me know if it helps you!

**Comment by Undistraction** [comment]
@hipstersmoothie Thanks. I'm off today but I'll give this a try on Monday.

**Comment by Undistraction** [comment]
@hipstersmoothie  I've spent the morning trying to get this working. I think I'm close. Storybook is no longer choking on jsx, but I cannot get Storybook to display stories from other packages. Even if I hardcode the import into my `./storybook/config.js`:

function loadStories() {
  require('../../example/src/components/DisclosingText/DisclosingText.stories.js')
}

Storybook still opens without error, but with no stories loaded. I've checked and rechecked this path and Webpack doesn't complain. 

Would you mind sharing your storybook `config.js`, or at least how you are requiring the stories in your other packages?

**Comment by Undistraction** [comment]
I've opened a separate issue as the problem seems to be related to loading stories from parent or sibling directories: #4910

**Comment by jalal246** [comment]
This might be helpful but it has performance issues  regarding to loading.

`
const req = require.context('..', true, /packages\/((?!node_modules).)*\/stories\/[^\/]+\.js$/);
`

I am not sure if this is the best solution to load stories from `packages`

**Comment by Undistraction** [comment]
@jalal246 Thanks for the suggestion. I actually switched to transpiling the stories as I thought that would allow me to sidestep this issue. I thought that this would allow me to load the transpiled stories directly from within my lerna packages which are just symlinks in my package's `node_modules`, however even if I use an explicit import, for example: 
```JavaScript
require('../node_modules/@company/components/lib/components/branding/Logo/Logo.stories')
```
Storybook just will not load the story.

**Comment by hipstersmoothie** [comment]
@jalal246 I could probably just change it to:

```js
rule.include = /..\/path\/to\/stories/;
```

**Comment by hipstersmoothie** [comment]
I've double checked and I am 99% sure that I have no other config for storybook to see the other dir

**Comment by jalal246** [comment]
Hi again, 

It sounds complicated for me right now, and I want to keep it simple. So, inside `.storybook\config.js`  
I added the paths manually,  should be a better way to do it but it works good and fast for now.

```js
import { configure } from "@storybook/react";

const requests = [];

const req1 = require.context(
  "../packages/component1/stories",
  true,
  /.stories.js$/
);

const req2 = require.context(
  "../packages/component2/stories",
  true,
  /.stories.js$/
);

requests.push(req1);
requests.push(req2);

function loadStories() {
  requests.forEach(req => {
    req.keys().forEach(fname => req(fname));
  });
}

configure(loadStories, module);


```

@hipstersmoothie @Undistraction

**Comment by earGO** [comment]
this 

> This should work. I have a storybook that loads stories from another monorepo package. Try adding this to your storybook webpack config. Find the babel rule in loaders and modify the include and exclude to include the parent directory (for a monorepo this will be `packages`).
> 
> ```js
> module.exports = (baseConfig, env, config) => {
>   // Find Babel Loader
>   const babelRules = config.module.rules.filter(rule => {
>     let isBabelLoader = false;
> 
>     if (rule.loader && rule.loader.includes('babel-loader')) {
>       isBabelLoader = true;
>     }
> 
>     if (rule.use) {
>       rule.use.forEach(use => {
>         if (typeof use === 'string' && use.includes('babel-loader')) {
>           isBabelLoader = true;
>         } else if (
>           typeof use === 'object' &&
>           use.loader &&
>           use.loader.includes('babel-loader')
>         ) {
>           isBabelLoader = true;
>         }
>       });
>     }
> 
>     return isBabelLoader;
>   });
> 
>   babelRules.forEach(rule => {
>     rule.include = /../;
>     rule.exclude = /node_modules/;
>   });
>   
>   return config;
> };
> ```
> 
> Let me know if it helps you!

This one helped with local storybooks while importing components from other packages. Thank you!!
