### ISSUE TITLE
@storybook/addon-options missing v4.0.9 release in npm

### ISSUE THREAD

**Issue by airato** [storybooks/storybook#4897]
@storybook/addon-options is missing v4.0.9 release in npm. And @storybook/addon-backgrounds too

![image](https://user-images.githubusercontent.com/4506749/49310391-01a8a700-f493-11e8-93e0-4d4de42d9813.png)

**Comment by igor-dv** [comment]
Indeed @shilman 
https://www.npmjs.com/package/@storybook/addon-options

**Comment by shilman** [comment]
Sorry about that--this one was due to a bug in lerna or how I was using it. I've released 4.0.10 that publishes all packages.

https://github.com/storybooks/storybook/releases/tag/v4.0.10

**Comment by igor-dv** [comment]
@shilman, maybe we should create a test that will check all the packages are having the right version in npm?

**Comment by shilman** [comment]
@igor-dv that's a good idea. In this case it was a lerna issue, but in the past there have been cases where NPM just ignores the publish in some cases. I'll add that to my release process.

**Comment by airato** [comment]
Thanks guys!

**Comment by shilman** [comment]
@igor-dv I've added it to my release script so we won't have to wait for issues to be filed to know when something went wrong with the publishing 😊
