### ISSUE TITLE
Storybook 4/Addon Dependencies breaks mobx/mobx-react @observable

### ISSUE THREAD

**Issue by Frankcarvajal** [storybooks/storybook#4909]
**Describe the bug**

_I couldn't determine if this should be filed as a Storybook bug or as a Feature request for support with MobX/Mobx-react._

https://stackoverflow.com/questions/53547412/storybook-breaks-mobx-mobx-react

With most recent versions of React/MobX/mobx-react @observable variables are defined,
after running `npm i --save-dev @storybook/react @storybook/addon-notes @storybook/addon-links @storybook/addon-actions @storybook/addon-knobs` all of those @observable variables become undefined leading to a failure to compile.

**To Reproduce**

_Steps to reproduce the behavior:_
1. CRA and eject or use react-rewired
2. Insure you have the newest versions of React/MobX/MobX-React dependencies
3. Create some variables under mobx @observable, ensure that babel plugins in `package.json` has `"transform-decorators-legacy".`
4. Run `npm run start` to see the variables working as defined pre installation of storybook
5. Install storybook using CLI and see that variables are undefined and the app fails to compile.
6. while storybook and addon dependencies installed, run `npm run storybook` script to see that Storybook works fine, it's the standard app that fails to compile.
7. run `npm uninstall --save-dev @storybook/react @storybook/addon-notes @storybook/addon-links @storybook/addon-actions @storybook/addon-knobs` to see that `npm run start` to run the application works again.

**Expected behavior**

Install storybook CLI and both `npm run start` and `npm run storybook` to work simultaneously without failure to compile do to undefs.

**System:**
 - OS: [MacOS Mojave 10.14.1]
 - Device: [MacBook Pro (15-inch, 2018)]
 - Browser: [Chrome, Firefox, Safari]
 - Framework: [React]
 - Addons: [MobX, MobX-React]
 
Versions: 

    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "mobx": "^5.6.0",
    "mobx-react": "^5.4.2"

    "devDependencies": {
        "@storybook/addon-actions": "^4.0.9",
        "@storybook/addon-knobs": "^4.0.9",
        "@storybook/addon-links": "^4.0.9",
        "@storybook/addon-notes": "^4.0.8",
        "@storybook/react": "^4.0.9"
      }

**Comment by igor-dv** [comment]
We should probably setup a CLI test for this...
Anyway, can you create a reproduction repo?
