### ISSUE TITLE
Cannot Require Stories From Parent or Sibling Directories

### ISSUE THREAD

**Issue by Undistraction** [storybooks/storybook#4910]
**Describe the bug**
Storybook is unable to require stories if their location is outside the root of the directory containing the `.storybook` config directory.

**To Reproduce**
1. Create a project using Storybook
2. Require a `*.stories.js` file located in a directory that is not a subdirectory to the directory containing the storybook config directory.

**Expected behavior**
The story is loaded into Storybook.

**Actual behavior**
The story is not loaded and no error occurs.

**Code snippets**
Using a file that is transpiled to ES5, the following will work:

```javascript
function loadStories() {
  require('../example.stories.js')
}
```

However the following will fail silently (note the path is correct and doesn't raise an error during compilation):

```javascript
function loadStories() {
  require('../../example.stories.js')
}
```

The same is true if loaded from a sibling directory, for example:

```javascript
function loadStories() {
  require('../../sibling/example.stories.js')
}
```

The same is also true if loaded from a package inside `node_modules`:

```javascript
function loadStories() {
  require('../node_modules/example.stories.js')
}
```

The story I'm using to test:
```JavaScript
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

var _react = _interopRequireDefault(require("react"));

var _react2 = require("@storybook/react");

var Component = function Component() {
  return _react.default.createElement("p", null, "LOADED");
};

(0, _react2.storiesOf)("Blah", module).add("Default", function () {
  return _react.default.createElement(Component, null);
});
```

In all cases, there is no error, however Storybook displays a popover containing:

> No Preview
> Sorry, but you either have no stories or none are selected somehow.
> Please check the storybook config.
> Try reloading the page.

It displays this in front of any stories loaded from within the package's src directory.

**System:**
 - OS:OSX
 - Browser: Chrome
 - Framework: React
 - Version: 4.0.11

**Comment by hipstersmoothie** [comment]
@Undistraction throw this in a repo so i can try to fix it?
