### ISSUE TITLE
mockChannel from FAQ does not exist?

### ISSUE THREAD

**Issue by hoopes** [storybooks/storybook#4911]
### Bug or support request summary
Hi, I'm trying to use the `addons-knobs` plugin, and I get this error: `Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel`. However, when I try to do what it says, there does not appear to be a `mockChannel` within `@storybook/addons`.

```
> lib = require('@storybook/addons');
{ AddonStore: [Function: AddonStore],
  default:
   AddonStore {
     loaders: {},
     panels: {},
     channel: null,
     preview: null,
     database: null } }
```

There is also the promisingly-named `@storybook/channels`, which exposes a `Channel` class, but i can't see exactly how to make that a mock channel.

If I add a debugger deep inside the knobs code, when _it_ imports `@storybook/addons`, it appears to have a `mockChannel` (which you can see from within the `addons-knobs` code). This does not look (to me) like it's available, though.

### Steps to reproduce

Attempt to import a `mockChannel`.

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react 3.4.11`
- `@storybook/addon-knobs 4.0.11`

### Affected platforms 

```
$ node -v
v10.13.0
```

Thanks very much for any help!

**Comment by igor-dv** [comment]
You have to use all of the storybook packages with the same version.

**Comment by hoopes** [comment]
Got it - thank you very much @igor-dv !
