### ISSUE TITLE
Knobs Addon:  example for Polymer

### ISSUE THREAD

**Issue by Edd-Strickland** [storybooks/storybook#4920]
**Is your feature request related to a problem? Please describe.**
Within the supported addons table for the Polymer column it says Knobs is supported.  However there's limited examples of how this could be done.  

In the Polymer showcase this is also up and running meaning it's like to be possible to set up yet again no examples or code base which doesn't trigger the append child error. 

**Describe the solution you'd like**
Clear documentation which covers Polymer please. 

Thanks

**Comment by Edd-Strickland** [comment]
TBH I'd settle for a peak at the code for the working polymer example and I can maybe work it out from there?

Thanks

**Comment by igor-dv** [comment]
You are welcome to add more example 😉

**Comment by Edd-Strickland** [comment]
Love to but really I need to see working code so I can backwards engineer it or at least some support from the core team so I know what I should be doing.   Theres no documentation and it's experimental i get that but its clear from the demo site someone has it working so a repo of that would be helpful to at least guide those of use attempt to use it, expand, develop on it or for it...

**Comment by tpluscode** [comment]
@Edd-Strickland feel to free to look around my repo where I use knobs: https://github.com/wikibus/lit-any

I'm on Slack too if you'd like to ask some questions
