### ISSUE TITLE
How to define a custom tsconfig just for StoryBook?

### ISSUE THREAD

**Issue by samuelcastro** [storybooks/storybook#4924]
This is not a bug and I think you support this, I have different compilations props for storybook and for the regular app, how can I config a different tsconfig file for Storybook?

Thanks.

**Comment by igor-dv** [comment]
Is this for sb/angular?

**Comment by samuelcastro** [comment]
@igor-dv It's for a React app.

**Comment by igor-dv** [comment]
Can you elaborate more about your setup? SB version ? do you use CRA ?

**Comment by samuelcastro** [comment]
@igor-dv This is a typescript project for React UI components, I'm not using CRA, it's a plain webpack + jest setup.

**Comment by samuelcastro** [comment]
I just fixed the problem adding a compilation option on storybook webpack like so:

```
compilerOptions: {
        module: 'es2015'
      }
```

**Comment by igor-dv** [comment]
Cool. 👍 
Anyway, if you are defining TS rules by yourself in the custom webpack config, you can provide a custom `tsconfig.json` file to consume there.
