### ISSUE TITLE
What about SBNext?

### ISSUE THREAD

**Issue by kyleoliveiro** [storybooks/storybook#4930]
**Is your feature request related to a problem? Please describe.**
So I stumbled upon https://github.com/storybooks/SBNext and noticed that the project hasn't been updated in a while, and there isn't a way to create an issue there. Are there plans to continue development on SBNext?

**Are you able to assist bring the feature to reality?**
Yes.

**Comment by igor-dv** [comment]
SBNext is kinda an agenda to where we want to move storybook. This project won't be published in the nearest future, but part of its apis/concepts will be implemented here soon (in the v4.1 and v5, etc)
