### ISSUE TITLE
TS definitions for @types/storybook__addon-knobs@^3.4.1 missing radios

### ISSUE THREAD

**Issue by rileytb** [storybooks/storybook#4931]
**Describe the bug**
The TS definitions (@types/storybook__addon-knobs@^3.4.1) appear to be missing the definition for `radios`

**To Reproduce**
1. Go to @storybook/addon-knobs/src/index.js
2. There you can see `export function radios(...`
3. Go to @types/storybook__addon-knobs/index.d.ts
4. There you'll see the definitions for everything _but_ the radios

**Expected behavior**
I can use the @types for radios

**Comment by igor-dv** [comment]
We are not maintaining types in the definitelytyped. But we will bring our types into the repo soon.
