### ISSUE TITLE
SCSS doesn't work out of the box on Windows

### ISSUE THREAD

**Issue by tirli** [storybooks/storybook#4940]
**Describe the bug**
scss is still not working under windows out of the box. We tested it on Linux and it works OK, but with the same config(just initialized) on windows it fails with error `You may need an appropriate loader to handle this file type.`

Tested in the combination of storybook 4.0.12 and CRA 2.1.1

**To Reproduce**
1. Initialize new CRA project
2. Initialize storybook
3. Rename App.css to App.scss
3. Create a story for App.js 
4. Run storybook
5. You see an error `You may need an appropriate loader to handle this file type.` about scss files and svg import

**Expected behavior**
Working SCCS and SVG import out of the box

**Screenshots**
![image](https://user-images.githubusercontent.com/7783308/49567976-22ac4480-f938-11e8-93cb-d0d848367a3f.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: Windows10
 - Browser: chrome (actually doesn't matter)
 - Framework: react
 - Addons: react-scripts 2.1.1
 - Version: 4.0.12

**Additional context**
Seems like #4405 doesn't support it properly.

**Comment by kylemh** [comment]
The issue is that you need to rename `App.css` to `App.module.scss` to get CSS Modules with Sass working 👍 

Really well-written issue btw, thank you for taking that time.

**Comment by kylemh** [comment]
The code in question: https://github.com/storybooks/storybook/blob/next/app/react/src/server/cra-config.js

This smells like it could be some kind of cross-platform issue with `fs` or `path` in [this function](https://github.com/storybooks/storybook/blob/next/app/react/src/server/cra-config.js#L13)

Googling issues related to methods called + "windows problem" led me to the following open (or unresolvable) issues:

https://github.com/nodejs/node/issues/8897
https://github.com/nodejs/node/issues/8237

Do any of them pertain to your situation?

Additionally, can you tell us which version of node and windows you are using?

It would also be lovely if you could share the explicit file path to your node_modules.

**Comment by kylemh** [comment]
Also, ping @igor-dv

**Comment by tirli** [comment]
I'm using node 10.13.0 and Windows 10.0.17134.407 (but tried on 3 different windows computers and two linux + macbook).  

Not sure what do you mean about "explicit path to node_modules", but for example `process.cwd` output is `'C:\\Users\\Yoga\\projects\\app'`

Also I tried to run such code in node (taken from storybook sources) to understand what is wrong
```js
const fs = require('fs');
const path = require('path');

let reactScriptsPath;

function getReactScriptsPath({ noCache } = {}) {
  if (reactScriptsPath && !noCache) return reactScriptsPath;

  const appDirectory = fs.realpathSync(process.cwd());
  const reactScriptsScriptPath = fs.realpathSync(path.join(appDirectory, '/node_modules/.bin/react-scripts'));

  reactScriptsPath = path.join(reactScriptsScriptPath, '../..');
  const scriptsPkgJson = path.join(reactScriptsPath, 'package.json');

  if (!fs.existsSync(scriptsPkgJson)) {
    reactScriptsPath = 'react-scripts';
  }

  return reactScriptsPath;
}

console.log(getReactScriptsPath());
```

 I'm getting such error:
```
Error: ENOENT: no such file or directory, lstat 'C:\Users\Yoga\projects\app\node_modules\.bin\react-scripts'
    at Object.realpathSync (fs.js:1454:7)
    at getReactScriptsPath (C:\Users\Yoga\projects\app\script.js:10:37)
    at Object.<anonymous> (C:\Users\Yoga\projects\app\script.js:22:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

So seems like `realpathSync` is a problem :(

**Comment by occar421** [comment]
I met a similar problem today. So I inspected the code in @storybook/react.

In "app/react/src/server/cra_config.js" on "v4.0.12" tag, I just thought
```js
reactScriptsPath = path.join(reactScriptsScriptPath, '../..');
```
is wrong and it should be
```js
reactScriptsPath = path.join(reactScriptsScriptPath, '../../react-scripts');
```
Modifying locally-installed dist js, now storybook seemed to load CRA's config.

On "next" branch (default; and you'd saw), this code is resolved like that by #4836 only for v4.1 alpha version.

**Comment by kylemh** [comment]
Not 100% certain because I’m on mobile but that PR seems to resolve both the SVG loader and Sass loader

**Comment by igor-dv** [comment]
I encountered some problems with windows too but in a monorepo. @tirli, can you check if this happens with 4.1.0-alpha?

CC @mrmckeb

**Comment by mrmckeb** [comment]
@occar421, the reason it isn't `../../react-scripts` is that CRA supports custom `react-scripts` packages, which can have any name they like. 

Are you working in WSL, or in PowerShell/Command Prompt? And can you share the value of `reactScriptsScriptPath` from your `cra_config.js` please? :)

I have a team working on Windows, MacOS, and Linux - and this works for all - but none of the Windows users work outside of WSL.

**Comment by tirli** [comment]
@igor-dv Sorry for the late reply. Tested and it works on 4.1.0-alpha!
