### ISSUE TITLE
Style loader data remains in iframe when changing stories

### ISSUE THREAD

**Issue by ozzyogkush** [storybooks/storybook#4945]
**Describe the bug**
When switching between viewing stories, the <style> tags from previous style-loader outputs remain in the preview iframe.

**To Reproduce**

1. Make a story that addDecorator() that requires() a SASS/CSS file
2. Make a separate story that does not
3. View the first story
4. View the second story
5. The second story has the first story's CSS applied to it

**Expected behavior**
Each story preview iframe only shows loaded styles for decorators and components directly used in that story.

**Code snippets**

```
// appSassDecorator
export default story => {
    require('js-file-that-includes-sass');

    return story();
};

// story 1
const stories = storiesOf('First Set', module);
stories
  .addDecorator(appSassDecorator)
  .add('Story 1', () => <div>Should Include Styles</div>);

// story 2
const stories = storiesOf('Different Set', module);
stories
  .add('Story 2', () => <div>Should NOT Include Styles</div>);
```

**System:**
 - OS: OSX
 - Device: MBP 2018
 - Browser: Chrome
 - Framework: React
 - Addons: custom decorator
 - Version: 4.0.9

**Comment by ozzyogkush** [comment]
Bump to keep active.

**Comment by ozzyogkush** [comment]
This is still a problem for my org... please advise!

**Comment by shilman** [comment]
@ozzyogkush Have you looked at:

https://github.com/storybooks/storybook/tree/next/addons/cssresources
