### ISSUE TITLE
Color knob disappears on click in firefox

### ISSUE THREAD

**Issue by mweibel** [storybooks/storybook#4949]
**Describe the bug**
As shown in the following GIF, the color knob is disappearing when clicking on the small modal window to select a color (or clicking anywhere within it, actually). It works in Chrome but not in Firefox. 

![color-knobs-firefox](https://user-images.githubusercontent.com/307427/49635004-9fa1f180-f9fe-11e8-8a04-23766ce0fb85.gif)

**To Reproduce**
1. Have a storybook with a color knob
2. Open it with Firefox
3. Click on the color value to change it
4. Click anywhere within the modal window that pops up

**Expected behavior**
Color is being changed to where you clicked on, or you can enter manually the color values.

**System:**
 - OS: macOS
 - Device: Macbook Pro
 - Browser: Firefox 65.0b1 (but also doesn't work in current stable version 63)
 - Framework: react
 - Addons: knobs, actions
 - Version: 4.0.12

**Comment by igor-dv** [comment]
I think it's duplicate to the issues we already have with the color knob - #4694. Waiting for a brave soul to help us with the fix 😉
