### ISSUE TITLE
HMR not working for components

### ISSUE THREAD

**Issue by Richacinas** [storybooks/storybook#4950]
**Describe the bug**

When changing any of the components that I am using from my stories, HMR is not reloading the content of the story.

**To Reproduce**

1. Go to the story of, for example, Button.
2. Go to './src/components/Button.jsx'
3. Change any content in your React component.
4. Watch how the component doesn't reload in your story.

**Expected behavior**

HMR should work and detect those changes and reload the component we are seeing inside the story.

**System:**

## System:
 - OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - Memory: 4.55 GB / 15.53 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm

**Additional info**

If I change a story, HMR is working fine.

**Comment by Richacinas** [comment]
Ok, I found some more information.

It detects changes and reloads up to **3 levels deep**. That means that anything you change inside Header folder or anything at that level and up, will be detected and will trigger a new build and reload.

If I change something inside **HeaderNav folder**, nothing gets detected.

![image](https://user-images.githubusercontent.com/7046504/49718072-4b467e00-fc59-11e8-9420-cba0c880e41a.png)

**Comment by igor-dv** [comment]
Can you please share some story file?

**Comment by Richacinas** [comment]
Hi Igor.

I'm working on a Ubuntu machine, which seems to have a limit of some levels deep of folders for this kind of watch and build process.

Here, you can find information to solve it. As I have read, there is not such a limit on Windows (I never had a problem on that OS).

[Post on StackOverflow](https://stackoverflow.com/questions/35367533/webpack-react-hot-loading-not-working-for-files-in-sub-folders)

[Solution](https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit)

Sorry for the confusion. I hope it helps somebody else.

Ricardo
