### ISSUE TITLE
.babelrc gets ReferenceError and can't find relative to directory. 

### ISSUE THREAD

**Issue by mistyhx** [storybooks/storybook#4952]
**Describe the bug**
Following the .babelrc configuration in the documentation for REACT.
`{
  "presets": ["..."],
  "plugins": ["..."],
  "env": {
    "test": {
      "plugins": ["require-context-hook"]
    }
  }
}`,

 `Storyshots.test.js` gets Reference error, when removed `"plugins": ["..."]` from `.babelrc`,`Storyshots.test.js` gets error on not finding presets and env. 

**Screenshots**

![screen shot 2018-12-07 at 11 37 46 am](https://user-images.githubusercontent.com/11740360/49660505-c0754180-fa14-11e8-8c56-a2d6e08c1053.png)
![screen shot 2018-12-07 at 11 39 03 am](https://user-images.githubusercontent.com/11740360/49660506-c0754180-fa14-11e8-94b6-e1735ff2d8f8.png)
![screen shot 2018-12-07 at 11 45 55 am](https://user-images.githubusercontent.com/11740360/49660885-ad16a600-fa15-11e8-8e38-58a6bdc7c379.png)

**Comment by igor-dv** [comment]
"..." means "Here you put all the plugins you are using in your app".  This example is mostly to show how to use `babel-plugin-require-context-hook`
