### ISSUE TITLE
Storybook React Native Unable hide UI by getStorybookUI param

### ISSUE THREAD

**Issue by mowbell** [storybooks/storybook#4953]
**Describe the bug**
in [Docs](https://github.com/storybooks/storybook/tree/next/app/react-native) `getStorybookUI` has a param to hide UI `isUIHidden`. 

But in source code in **preview/index.js** it expect param with name `isUIOpen` instead of `isUIHidden`
The correct param name is `isUIHidden` that is expected by **preview/OnDeviceUI/index.js** 

**To Reproduce**
Try writing
```js
const StorybookUIRoot = getStorybookUI({ port: 7007, onDeviceUI: true, isUIOpen: false });
```
```js
const StorybookUIRoot = getStorybookUI({ port: 7007, onDeviceUI: true, isUIHidden: false });
```
None is working

**Expected behavior**
Expected menu hidden on storybook start

**System:**
 - OS: MacOS
 - Device: Simulator Iphone 7
 - Framework: React Native
 - Version: ^4.0.11

**Comment by Gongreg** [comment]
Hey @mowbell, I will look into this tomorrow.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v4.2.0-alpha.6 containing PR #5067 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybooks/storybook/releases/tag/v4.1.11 containing PR #5067 that references this issue. Upgrade today to try it out!
