### ISSUE TITLE
isReactScriptsInstalled unable to identify CRA dependency on windows.

### ISSUE THREAD

**Issue by gm90** [storybooks/storybook#4959]
**Describe the bug**
Currently using storybook with a CRA setup. On OSX 'cra_confix.js' correctly identifies that react-scripts is installed and adds the required loaders for scss. With the same setup on Windows it fails when it reaches the first scss file.

**Expected behavior**
CRA config is able to identify the presence of react-scripts consistently

**Screenshots**
![image](https://user-images.githubusercontent.com/285740/49723954-14279b00-fc60-11e8-998f-bc3ab8b10637.png)

**System:**
 - OS: [Windows7 64bit]
 - Device: [e.g. HP Desktop Intel(R) Core(TM) i7-4790 CPU @ 3.60 GHz]
 - Browser: N/A
 - Framework: [react, cra, storybook]
 - Version: [e.g. 4.0.12]

**Additional context**
Having debugged the issue it appears the *getReactScriptsPath* method within 'cra_config.js' is at fault. 

reactScriptsScriptPath is set slightly differently on mac vs windows and as a result upon traversing the directory structure windows ends up looking in the node_modules directory instead of the react-scripts directory for the package.json:

Mac:
reactScriptsScriptPath: /Users/..../project/node_modules/react-scripts/bin/react-scripts.js
reactScriptsPath /Users/..../project/node_modules/react-scripts

Windows
reactScriptsScriptPath: 'E:\\....\\project\\node_modules\\.bin\\react-scripts'
reactScriptsPath: 'E:\\....\\project\\node_modules'

**Code snippets**
```javascript
let reactScriptsPath;
function getReactScriptsPath() {
  if (reactScriptsPath) return reactScriptsPath;
  const appDirectory = fs.realpathSync(process.cwd());
  const reactScriptsScriptPath = fs.realpathSync(
    path.join(appDirectory, '/node_modules/.bin/react-scripts')
  );
  reactScriptsPath = path.join(reactScriptsScriptPath, '../..');
  return reactScriptsPath;
}
```

**Comment by igor-dv** [comment]
Yeah, we have some issues with resolving symlinks in Windows. Can you please try using the latest alpha (4.1.0-alpha) ?

**Comment by igor-dv** [comment]
👍 4.1 is soon out, so closing this.
