### ISSUE TITLE
shouldPersistSelection not working

### ISSUE THREAD

**Issue by llccrr** [storybooks/storybook#4972]
**Describe the bug**
Setting shouldPersistSelection to `true` as above:
`const StorybookUIRoot = getStorybookUI({ port: 7007, onDeviceUI: true, shouldPersistSelection: true });`
But it does not seem to work. 

I looked out the PR and figured out that it was supposed to write into the **Async Storage** with the `lastOpenedStory` key. 
I tried to console.log it in the render of my story but the value remains `null` and does not seem to be set at any time.

**Expected behavior**
Refreshing my device should initialize storybook with the last selected story

**System:**
 - OS: MacOS
 - Device: [iPhoneX Emulator, Iphone 6 Emulator] (Xcode)
 - Framework: react-native
 - Addons: [addon-actions, addon-knobs, addon-links]
 - Version: @4.0.12

**Additional context**
My stories does not have any other problem and are rendering perfectly.

**Comment by llccrr** [comment]
Changing the port from 7007 to 7008 does not seem to work either.

**Comment by Gongreg** [comment]
Hey @llccrr, I will look into this tomorrow :)

**Comment by Gongreg** [comment]
Hey, @llccrr, I've just tested the functionality and it seems to work. Could you create a reproduction for this?

**Comment by teo029** [comment]
I also find that it doesn't work.
