### ISSUE TITLE
GraphQL Addon: Blank last line breaks formatter

### ISSUE THREAD

**Issue by TimoSta** [storybooks/storybook#4975]
**Describe the bug**
When using the GraphQL addon to submit a GraphQL query inside GraphiQL, the addon formats the query to remove unnecessary indentation.

If the last line of the query is blank however, this formatting step fails, and only the last character of each line is kept, rather than removing only whitespace from the beginning of a line.

**To Reproduce**
1. Clone https://github.com/TimoSta/storybook-graphql-repro.git
2. Run `yarn install`
3. Run `yarn run storybook`
4. Open story _GraphQL/Broken_

**Expected behavior**
The full query should be displayed and executed, with unnecessary indentation removed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/5621996/49814583-eb72d480-fd37-11e8-814b-991b91a99f1f.png)

**Code snippets**
See [the reproduction repo](https://github.com/TimoSta/storybook-graphql-repro/blob/master/stories/index.stories.js).

```js
import React from "react";
import { storiesOf } from "@storybook/react";
import { setupGraphiQL } from "@storybook/addon-graphql";

const graphiql = setupGraphiQL({ url: "http://localhost:3000/graphql" });

const query = `
{
  hero {
    name
    age
  }
}
`;

storiesOf("GraphQL", module)
  .add("Broken", graphiql(query))
  .add("Not broken", graphiql(query.trim()));
```

**System:**
 - OS: Win 7
 - Device: PC
 - Browser: Chrome
 - Framework: React
 - Addons: `@storybook/addon-graphql`
 - Version: 4.0.12

**Comment by mmerezhko-hv** [comment]
Hello!
Is there any workaround to run this addon with storybook v6-7?

More details: https://github.com/storybookjs/addon-graphql/issues/2
