### ISSUE TITLE
[ReactNative] Not working at all with 0.57.7

### ISSUE THREAD

**Issue by scerelli** [storybooks/storybook#4986]
**Describe the bug**
Fail compiling on newly created react native project.

This is the error i get:
```
[./storybook/addons.js] 88 bytes {manager} [built]
    + 695 hidden modules

ERROR in Template execution failed: ReferenceError: dlls is not defined

ERROR in   ReferenceError: dlls is not defined

  - index.ejs:47 eval
    [.]/[loader.js!.]/[@storybook]/core/src/server/templates/index.ejs:47:2

  - index.ejs:60 module.exports
    [.]/[loader.js!.]/[@storybook]/core/src/server/templates/index.ejs:60:3

  - index.js:407 templateParamsPromise.then
    [testApp]/[html-webpack-plugin]/index.js:407:16

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

**To Reproduce**
1. Open the terminal
2. Type: `react-native init testApp`
3. Wait few years
4. `npx -p @storybook/cli sb init`
5. Wait again
6. Type in your terminal: `yarn run storybook`
7. Wait until it fails compiling.

**Expected behavior**
I expect that it compiles file in a newly created app without the
need of debug errors. 

**Code snippets**
Didn't write a single line of code on the project i created to test this thing.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Framework: React Native
 - Addons: The addons installed by default by `npx -p @storybook/cli sb init`
 - Version:`4.1.0`

**Additional context**

**Comment by igor-dv** [comment]
Duplicate to #4984
