### ISSUE TITLE
use both package.json and .babelrc

### ISSUE THREAD

**Issue by iamnewton** [storybooks/storybook#4987]
**Describe the bug**

It doesn't appear you can use the `babel` key in the package.json, otherwise you get errors.  It seems you are only allowed to use a `.babelrc`.

**System:**
 - OS: [e.g. iOS, Windows10, MacOS] unrelated
 - Device: [e.g. iPhoneX, Macbook Pro 2018] unrelated
 - Browser: [e.g. chrome, safari] unrelated
 - Framework: [e.g. react, vue, angular] react
 - Addons: [if relevant] unrelated
 - Version: [e.g. 4.0.0] 3.4.11

**Additional context**

**Comment by igor-dv** [comment]
With the v4 you can
