### ISSUE TITLE
Storybook can not watch node_modules.

### ISSUE THREAD

**Issue by janryWang** [storybooks/storybook#4990]
**Describe the bug**
I want the storybook watch node_modules but it not work.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: [e.g. iOS, Windows10, MacOS]
 - Device: [e.g. iPhoneX, Macbook Pro 2018]
 - Browser: [e.g. chrome, safari]
 - Framework: [e.g. react, vue, angular]
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0]

**Additional context**

**Comment by igor-dv** [comment]
You should use a custom webpack config for Storybook and include nodules_modules in the relevant rules.
