### ISSUE TITLE
Emotion v10 crashes Storybook 4.1.1

### ISSUE THREAD

**Issue by wileym** [storybooks/storybook#4994]
**Describe the bug**
Storybook crashes at runtime (in browser) when project uses emotion v10.

**To Reproduce**
1. git clone https://github.com/wileym/emotion10CrashesStorybook.git
2. cd emotion10CrashesStorybook
3. npm install
4. npm run storybook
5. http://localhost:6006
6. Note blank browser screen and error in console

**Expected behavior**
Browser loads Storybook and one story appears for Button

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2017]
 - Browser: [chrome, safari]
 - Framework: [react]
 - Addons: [emotion v10]
 - Version: [4.1.1]

**Additional context**
Running `npm run start` will run the default app (http://localhost:8081) that renders the button as expected in storybook.

**Comment by igor-dv** [comment]
Duplicate to #4525
