### ISSUE TITLE
addDecorator documentation for @storybook/html

### ISSUE THREAD

**Issue by gsouquet** [storybooks/storybook#4997]
Hi,

First and foremost, thank you for Storybook, I love it! Used it across multiple React projects, and I am now experiencing with the `@storybook/html` package

### Bug or support request summary

I am currently implementing Storybook in a project that does not contain React and if possible I would like to keep it that way. Thus me using `@storybook/html`.
I wanted to use the `addDecorator` function exposed in the package, however I was unable to make it work nor find documentation regarding its usage.

### Steps to reproduce

Following the documentation from `@storybook/react#addDecorator` I attempted a few thing to add a global decorator

```
import { configure, addDecorator } from "@storybook/html";

// ...

addDecorator(story => {
  const wrapper = document.createElement("section");
  wrapper.appendChild(story); // also tried `story()`
  return wrapper;
});

// ...
```

The reason why I tried the above is that it is what seems to be the closest to what `@storybook/react` does

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/html

### Affected platforms 

All

### Work summary

I'd like to get a bit of help from someone to explain how this feature works.

And after I am more than happy to open a PR to document that on the Storybook website

**Comment by ndelangen** [comment]
Hello @gsouquet, thank yu fro the kind words! 

What does your storyFn return?

You should call it and depending on what you return from your storyFn do different things..

- If your storyFn returns a string, you'll need to use innerHTML or a DomParser.
- If your story returns a Element instance, you can set as child.

Storybook internally should be able to do both.

**Comment by gsouquet** [comment]
My story looks like the following

```
storiesOf("VideoContext", module)
    .add("Code playground", () => {

        const canvas = document.createElement("canvas");
        
        // Do canvas operation

        return canvas;
    });
```

And my decorator is meant to be a global decorator

```
import { configure, addDecorator } from '@storybook/html';

addDecorator(storyFn => {
  const wrapper = document.createElement("section");
  wrapper.appendChild(storyFn());
  return wrapper;
});

function loadStories() {
    require('../stories/index.js');
}

configure(loadStories, module);
```

I added the `addDecorator` there following the documentation on [https://storybook.js.org/basics/writing-stories/](https://storybook.js.org/basics/writing-stories/)

After inspecting the DOM it looks like my decorator is not taken in account at all.

<img width="364" alt="screen shot 2018-12-14 at 11 42 36" src="https://user-images.githubusercontent.com/769871/50001707-97652b80-ff95-11e8-8a56-394c0a6c9745.png">

Any ideas on what I am doing wrong?
Looking at your response above it seems that I a return an `Element` instance and set my `storyFn` as a child using the DOM API

**Comment by gnclmorais** [comment]
Hey @gsouquet, `storyFn()` returns an HTML string, which [are allowed as stories][0], so you can do the following:
```js
addDecorator(story => `<section>${storyFn()}</section>`);
```

[0]: https://storybook.js.org/basics/guide-html/#write-your-stories

**Comment by gnclmorais** [comment]
I have a similar case (where I want to wrap elements with Bootstrap classes) and I did the following:
```js
const storyAsString = (story) => `<div class="container m-5">${story}</div>`;
const storyAsNode = (story) => {
  const wrapper = document.createElement('div');
  wrapper.className = 'container m-5';
  wrapper.appendChild(story);
  return wrapper;
};

addDecorator(story => {
  const tale = story();
  return typeof tale === "string" ? storyAsString(tale) : storyAsNode(tale);
});
```

**Comment by gliesche** [comment]
@gnclmorais Thanks for the examples. The show code block, shows the decorated code, though. Do you know a way to avoid this?

**Comment by gnclmorais** [comment]
I don’t think so, sorry… I haven’t touched this in two years. 😅

**Comment by gliesche** [comment]
> I don’t think so, sorry… I haven’t touched this in two years. 😅

No problem. Thanks though!

**Comment by beumsk** [comment]
Here is what I found to be working and not showing inside the 'show code block'.
Inside preview.js: 
```
export const decorators = [(Story) => `<div class="anything">${Story().outerHTML || Story()}</div>`];
```
