### ISSUE TITLE
CRA2 TypeScript type-checking is not working

### ISSUE THREAD

**Issue by mucsi96** [storybooks/storybook#5005]
**Describe the bug**
I am trying to use react + typescript + cra v2. The storybook runs fine with typescript files out of the box without any changes needed. The only problem is that there is no type-checking during the build. 
I made a minor investigation. The type checking in CRA is done using a webpack plugin called `ForkTsCheckerWebpackPlugin` https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L618

Unfortunate all CRA Webpack plugins are ignored during the construction of Webpack config. 
https://github.com/storybooks/storybook/blob/next/app/react/src/server/cra-config.js#L124

This shoud be the reason why there is no typechecking.

Possible solution would be to merge the `baseConfig.plugins` with CRA Webpack plugins making a unique array based on `plugin.constructor.name` similarly as suggested in [webpack-merge](https://www.npmjs.com/package/webpack-merge#mergeuniquefield-fields-field--field) popular package. This will make future improvements in CRA webpack config automatically available in storybook integration.

I can send a PR if you agree with the approach 👍

**Comment by igor-dv** [comment]
@mucsi96, still wanna work on this?

**Comment by mucsi96** [comment]
@igor-dv Sure! If you like the approach of merging the plugins then I can submit a PR soon.

**Comment by igor-dv** [comment]
Yeah, that is what we are doing with rules other things, just take a look at what plugins are being merged to not have any conflicts.
