### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 

### ISSUE THREAD

**Issue by alun-430** [storybooks/storybook#5013]
E
![image](https://user-images.githubusercontent.com/29272929/50062858-5d3d9900-01e4-11e9-8b22-942b903bdb23.png)

E
![image](https://user-images.githubusercontent.com/29272929/50063850-1c944e80-01e9-11e9-96ad-179dbbad00c9.png)

l
![image](https://user-images.githubusercontent.com/29272929/50063860-27e77a00-01e9-11e9-988b-e7a13eac733b.png)

e
![image](https://user-images.githubusercontent.com/29272929/50063872-32a20f00-01e9-11e9-8a61-f62cd952c8c0.png)

ment type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Strategy`.
    Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Strategy`.
    at invariant (http://localhost:6006/static/iframe.bundle.js:24211:15)
    at createFiberFromTypeAndProps (http://localhost:6006/static/iframe.bundle.js:34114:11)
    at createFiberFromElement (http://localhost:6006/static/iframe.bundle.js:34135:15)
    at createChild (http://localhost:6006/static/iframe.bundle.js:37304:28)
    at reconcileChildrenArray (http://localhost:6006/static/iframe.bundle.js:37555:25)
    at reconcileChildFibers (http://localhost:6006/static/iframe.bundle.js:37878:14)
    at reconcileChildren (http://localhost:6006/static/iframe.bundle.js:38234:28)
    at updateHostComponent (http://localhost:6006/static/iframe.bundle.js:38579:3)
    at beginWork (http://localhost:6006/static/iframe.bundle.js:39243:14)
    at performUnitOfWork (http://localhost:6006/static/iframe.bundle.js:41976:12)

**Comment by praneybehl** [comment]
Getting the same issue, were you able to resolve it?

**Comment by minardimedia** [comment]
What is the solution for this issue?

**Comment by vivek-kandhvar** [comment]
The issue is still happening, and how can you guys just mark it closed, without a solution?

**Comment by rennehir** [comment]
Anyone figured this out?

**Comment by callumacrae** [comment]
Getting this too, did anyone figure out a solution?

**Comment by shilman** [comment]
This is a generic error that can come from anywhere. It's typically a user error when one tries to use a non-component as a react component.

Consider the following two snippets:

```js
import Button from './Button';
```

```js
import { Button } from './Button';
```

If `Button` is the default export then first is correct. If it's a named export, then the second is correct. If you accidentally uses the wrong one, you'll get this error.

**Comment by emmanuelsio** [comment]
> ```js
> import { Button } from './Button';
> ```

thanks, is the right answer

**Comment by josesteva** [comment]
Thank you!

**Comment by hallya** [comment]
I've met this issue not because of bad use of `import/export` but because of the definition of a static property which somehow mess up with it.

```js
import React, { ReactNode, HTMLProps, createContext, useMemo, ChangeEvent } from 'react';
import { Radio } from './Radio';
import styles from './RadioGroup.m.scss';

type RadioContext = {
  name: string;
  onChange(event: ChangeEvent<HTMLInputElement>): void;
  required?: boolean;
  value: string;
} & HTMLProps<HTMLInputElement>;

type RadioGroupProps = {
  children: ReactNode;
} & RadioContext;

export const RadioContext = createContext<RadioContext>({} as RadioContext);

export function RadioGroup(props: RadioGroupProps) {
  const { children, direction, error, invalid, name, onChange, required, spread, value } = props;

  const radioContextValue = useMemo(() => ({ name, onChange, required, value }), [
    name,
    onChange,
    required,
    value,
  ]);

  return (
      <RadioContext.Provider value={radioContextValue}>{children}</RadioContext.Provider>
  );
}

RadioGroup.Radio = Radio; // <- definition of `Radio` as static property `Radio` of `RadioGroup`
```

when importing RadioGroup this way

```js
import React, { useState } from 'react';
import { RadioGroup } from '.';

const styleContainer = { height: '85vh', width: '99vw' };

export default {
  title: 'Kit UI/RadioGroup',
  decorators: [
    Story => (
      <div style={styleContainer}>
        <Story />
      </div>
    ),
  ],
};

export const BasicColumn = () => {
  const [value, setRadioValue] = useState('');

  function handleChange(e) {
    setRadioValue(e.currentTarget.value);
  }

  return (
    <RadioGroup direction={'column'} name="name" onChange={handleChange} value={value}>
      <RadioGroup.Radio label="Option a" value="a" />
      <RadioGroup.Radio label="Option b" value="b" />
      <RadioGroup.Radio label="Option c" value="c" />
      <RadioGroup.Radio label="Option d" value="d" />
    </RadioGroup>
  );
};
```

**Comment by RayLuxembourg** [comment]
Seems like the compound component pattern is not working properly with the storybook.

**Comment by gynekolog** [comment]
Same problem.
I had folder `components/ui`. There is barrel index.ts:
```
export { default as Icon } from './Icon';
```
and my component `Icon` that has default export. 

I had another components folder `components/shared`. When I import any component from the UI folder to any `shared` component I get the error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by omril1** [comment]
This was solved for me by adding `import 'reflect-metadata';` at the top of the storybook entrypoint (preview.js/ts).
Without this some modules were being imported as empty modules.

**Comment by figalex** [comment]
Having same problem when trying to import class-based components. No solution suggested here worked for me. I'm importing the component file directly (no index.js file) and the default import is always undefined.

**Comment by rusakovic** [comment]
> Having same problem when trying to import class-based components. No solution suggested here worked for me. I'm importing the component file directly (no index.js file) and the default import is always undefined.

Confirm this bug. Thank you for your solution!

**Comment by Enalmada** [comment]
I got this error trying to setup storybook v7.2.3 as a new user on a simple demo project.  I nearly gave up but found that switching my components from functional like so fixes the problem:

Fails
```
const Task = (props: Props) => {
  ...
};

export default Task;
```

Works
```
export default function Task(props: Props) {
  ...   
}
```

Is there a way to make storybook work with functional components?

**Comment by hkogge** [comment]
Make sure all your storybook dependencies are using the same version!
I was using the following dependencies and had the same issue:

```json
"devDependencies": {
    "@storybook/addon-a11y": "^7.0.5",
    "@storybook/addon-essentials": "^7.0.5",
    "@storybook/addon-interactions": "^7.0.5",
    "@storybook/addon-links": "^7.0.5",
    "@storybook/nextjs": "^7.0.5",
    "storybook": "^7.0.5"
  }
```


Somehow, `storybook` was updated to `7.3.1`, during a lockfile refresh of our dependency bot, while the others remained at `7.2.3`.  

Manually deleting `node_modules` (not sure if necessary), updating the deps to `^7.3.1` and doing a fresh `npm install` fixed the issue for me.

**Comment by nerdyman** [comment]
Just in case anyone is as dumb as I am... I was using the `StoryObj` pattern but wasn't setting `children` so _my_ component was the thing throwing this error, not Storybook.

```ts
type Story = StoryObj<typeof Text>;

export const Default: Story = {
  args: {
    level: "title",
    children: "Hello, world!", // 🤦‍♂️
  },
};
```
