### ISSUE TITLE
Storybook 4.1 renders using SB's `react-dom`, not the app's

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#5014]
**Describe the bug**
`@storybook/react` calls `ReactDOM.render` using the version of `react-dom` (16.6) storybook ships with, not the version that the user's app uses. This means if the app uses `react-dom` internally (e.g. `ReactDOM.findDOMNode()`), all heck breaks loose:

```
Unable to find node on an unmounted component.
    invariant@http://localhost:7000/vendors~main.b5d3e831a4562a230f16.bundle.js:43768:24
findCurrentFiberUsingSlowPath@http://localhost:7000/vendors~main.b5d3e831a4562a230f16.bundle.js:47871:39
<snip>
```

**To Reproduce**
1. Check out https://github.com/tmeasday/sb-react-dom-version-mismatch
2. Run the storybook. Observe error

Not this is a modified version of CRA that depends on `react-dom@16.5`. If you allow the app to use `react-dom@16.6` (and thus share it with SB), the problem does not occur.

**Expected behavior**
The preview window should render with the user's version of `react-dom`

**Screenshots**
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/132554/50067211-051e8b00-0214-11e9-81b5-d07309559fc4.png">

**Comment by shilman** [comment]
I'm still able to repro this with `4.2.0-alpha.3` that contains this change, re-opening.

**Comment by shilman** [comment]
Confirmed the fix was successful in release https://github.com/storybooks/storybook/releases/tag/v4.2.0-alpha.4
