### ISSUE TITLE
Stories that return a DOM element don't update when knobs change

### ISSUE THREAD

**Issue by andyearnshaw** [storybooks/storybook#5017]
**Describe the bug**
When you adjust knobs, stories don't update when they return a DOM element but they do when you return a HTML string.  The story code is executed but is discarded due to a `forceRender` variable that is always `true`, possibly introduced in [this commit](https://github.com/storybooks/storybook/commit/5a33ea024d9e09f82ba53c8a3601a695d6e4680e#diff-a52740ffdc7b42a685aa7f8cb085d9af).

**To Reproduce**
Use the following JS for a story:

```javascript
import { storiesOf } from '@storybook/html';
import { withKnobs, text } from '@storybook/addon-knobs';

storiesOf('TestComponent', module)
  .addDecorator(withKnobs)
  .add('html', () =>  {
    let message = text('Heading', 'Hello World');
    return `<h1>${ message }</h1>`;
  })
  .add('dom', () => {
    let h1 = document.createElement('h1');
    h1.textContent = text('Heading', 'Hello World');

    return h1;
  });
```

**Expected behavior**
As you change the "Heading" knob, the stories should re-render.  In reality, only the one that returns the HTML string does.

**System:**
 - OS: macOS
 - Browser: all
 - Framework: none
 - Addons: knobs
 - Version: 4.1.1

**Comment by igor-dv** [comment]
@Atekon, didn't you get thing problem as well?

**Comment by cdutson** [comment]
Hi there! I'm actually running into this issue right now. I'm trying to build up a doc library for a web component-based component library at my workplace. I've started by generating kitchen sink stories for all of the components, and dynamically creating the knobs for the components based on the props of each component.

This works great, except that it's not re-rendering if a dom element is returned. It does if I return a string (el.outerHTML) but this isn't ideal since I'm not just setting html atributes on all of these components. some are JS-based props. SO I need to return the dom element.

Kind of stuck in a weird place here. I could probably switch over to react and just export fragments, but that seems like an ugly workaround.

I'm happy to provide further details, sample code, etc as needed

**Comment by Nightbr** [comment]
Hey, same bug here with Web Components (build with Stenciljs):

```
import { storiesOf } from '@storybook/html';
import { withReadme } from 'storybook-readme';
import README from './readme.md';
import { withKnobs, text, number } from '@storybook/addon-knobs';
import { action } from '@storybook/addon-actions';

const percentageRange = {
  range: true,
  min: 0,
  max: 100,
  step: 1
};

storiesOf('Components/MyComponent', module)
  .addDecorator(withReadme(README))
  .addDecorator(withKnobs)
  .add('With Input', () => {
    const el = document.createElement('my-component');
    const value = number('Percentage', 50, percentageRange);
    console.log(value);
    el.value = value;
    el.test = text('test', 'John');
    el.addEventListener('myComponentClicked', e => {
      action('myComponentClicked')(e.detail);
      el.test = 'plop';
    });
    return el;
  });
```

The stories is not rerendered :/ I will try to return and HTML string to see if it is rerendered.

**Comment by dwightjack** [comment]
Hi,

just to add a note I'm experiencing the same issue with version 5.0.1. As @andyearnshaw pointed out the problem looks like to be [this check](https://github.com/storybooks/storybook/blob/master/app/html/src/client/preview/render.js#L20).

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.15 containing PR #6190 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by mitni455** [comment]
@Nightbr 
The only workaround I found was adding the element to the global scope, rather than the `story.add` scope: 

e.g. 
```javascript
/* move to here */ const el = document.createElement('my-component');

storiesOf('Components/MyComponent', module)
  .addDecorator(withReadme(README))
  .addDecorator(withKnobs)
  .add('With Input', () => {
    /* move from here ---> const el = document.createElement('my-component'); */
    // .... ect ect 
    el.test = text('test', 'John');
  })
```

**Comment by mitni455** [comment]
> **Describe the bug**
> When you adjust knobs, stories don't update when they return a DOM element but they do when you return a HTML string. The story code is executed but is discarded due to a `forceRender` variable that is always `true`, possibly introduced in [this commit](https://github.com/storybooks/storybook/commit/5a33ea024d9e09f82ba53c8a3601a695d6e4680e#diff-a52740ffdc7b42a685aa7f8cb085d9af).
> 
> **To Reproduce**
> Use the following JS for a story:
> 
> ```js
> import { storiesOf } from '@storybook/html';
> import { withKnobs, text } from '@storybook/addon-knobs';
> 
> storiesOf('TestComponent', module)
>   .addDecorator(withKnobs)
>   .add('html', () =>  {
>     let message = text('Heading', 'Hello World');
>     return `<h1>${ message }</h1>`;
>   })
>   .add('dom', () => {
>     let h1 = document.createElement('h1');
>     h1.textContent = text('Heading', 'Hello World');
> 
>     return h1;
>   });
> ```
> 
> **Expected behavior**
> As you change the "Heading" knob, the stories should re-render. In reality, only the one that returns the HTML string does.
> 
> **System:**
> 
> * OS: macOS
> * Browser: all
> * Framework: none
> * Addons: knobs
> * Version: 4.1.1
@andyearnshaw 

Try add the element to the global scope 

```javascript
import { storiesOf } from '@storybook/html';
import { withKnobs, text } from '@storybook/addon-knobs';

/* move here */ let h1 = document.createElement('h1');

storiesOf('TestComponent', module)
  .addDecorator(withKnobs)
  .add('html', () =>  {
    let message = text('Heading', 'Hello World');
    return `<h1>${ message }</h1>`;
  })
  .add('dom', () => {
    /* was here  --->  let h1 = document.createElement('h1'); */
    h1.textContent = text('Heading', 'Hello World');

    return h1;
  });
```
