### ISSUE TITLE
React and Preact in same Storybook instance

### ISSUE THREAD

**Issue by edmundas04** [storybooks/storybook#5029]
I need to introduce Storybook for both React and Preact components. Is there a way to have the same Storybook instance for both React and Preact components? If not is it a feature we can expect in future?

**Comment by igor-dv** [comment]
It's not possible right now, but there was a discussion to support that in the future, though it requires a major refactoring of the rendering ability. 
Anyway, we have it in https://storybook.canny.io/roadmap, so closing it.
