### ISSUE TITLE
addon-info returning "Uncaught TypeError: template.asWrappedLayout is not a function"

### ISSUE THREAD

**Issue by transitorytammy** [storybooks/storybook#5036]
**Describe the bug**
I am trying to add `@storybook/addon-info` to my ember storybook repo.

This is what my `.storybook/config.js` file looks like.

```
import { configure, addDecorator } from '@storybook/ember';
import { withInfo } from "@storybook/addon-info";
import { withNotes } from '@storybook/addon-notes';
import { checkA11y } from "@storybook/addon-a11y";
import Centered from "@storybook/addon-centered/ember";

addDecorator(withInfo);
addDecorator(withNotes);
addDecorator(checkA11y);
addDecorator(Centered);

function loadStories() {
    require('../stories/index.js');
    // You can require as many stories as you need.
}

configure(loadStories, module);
```

When I go to `http://localhost:9001/`, I see this error in the console and my elements don't load on the page.

<img width="667" alt="screen shot 2018-12-18 at 10 46 14 am" src="https://user-images.githubusercontent.com/1967604/50175973-03f06b00-02b3-11e9-9f75-509345889c36.png">
<img width="1275" alt="screen shot 2018-12-18 at 10 52 57 am" src="https://user-images.githubusercontent.com/1967604/50176013-21bdd000-02b3-11e9-86a4-cfdbca481cf0.png">

**To Reproduce**
1. Go to `.storybook/config` and add `import { withInfo } from "@storybook/addon-info";` and `addDecorator(withInfo);` to the file.
2. Start server by running `npm run storybook`
3. Go to `http://localhost:9001` and open console to see error

**Expected behavior**
I expect no error and to be able to use `addon-info`

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [chrome]
 - Framework: [ember]
 - Addons: [@storybook/addon-a11y]
 - Version: [e.g. 4.0.0]

**Comment by igor-dv** [comment]
If you leave only an info addon configured, does the error remain?

**Comment by transitorytammy** [comment]
hi @igor-dv.  i tried removing everything else and just using the info addon and i am still getting the same error.

**Comment by barryofguilder** [comment]
I'm getting this error too, but instead of doing it in the config file, I'm doing it directly in my story. My code looks like this:

```
import hbs from 'htmlbars-inline-precompile';
import { storiesOf } from '@storybook/ember';
import { action } from '@storybook/addon-actions';
import centered from '@storybook/addon-centered';

storiesOf('Button', module)
  .addDecorator(centered)
  .addParameters({ options: { selectedAddonPanel: 'storybook/actions/actions-panel' } })
  .add('with defaults', () => {
    return {
      template: hbs`
        <UiButton @onClick={{action "buttonClick"}}>
          Click Me
        </UiButton>
      `,
      context: {
        actions: {
          buttonClick: action('clicked'),
        },
      },
    };
  });
```

**Comment by gabrielcsapo** [comment]
@transitorytammy can you comment the version of ember you are using and the story code?

**Comment by transitorytammy** [comment]
@gabrielcsapo  I am on Ember 3.14

```
ember-cli: 3.1.4
node: 10.13.0
os: darwin x64
```

**Comment by ilkkao** [comment]
I had this error too in my Ember add that uses React. My parent Ember component had layout property set to a string. This stopped working after upgrading Ember. In my case I was simply able to remove the overridden layout and fallback to default layout.

**Comment by transitorytammy** [comment]
@ilkkao where did you "remove the overridden layout"?  just wondering what file you are talking about adjusting to fix the issue.  thanks.

**Comment by ilkkao** [comment]
I was talking about my Ember component. 

I'm not sure what the context is here. I just saw the exact same error message in my Ember app, this PR was the only hit when I googled it. Please ignore my comment if you are not using Ember components here.

**Comment by shilman** [comment]
@transitorytammy `addon-info` is only compatible with React at the moment. We'll be moving that functionality to the addons panel and making it cross framework as soon as v5 is released in a few weeks. https://github.com/storybooks/storybook/issues/1147

Closing this for now.

**Comment by tau150** [comment]
@ilkkao I am having the same issue in Ember, I am new in Ember, could you pass me an example of how did you solve it?

**Comment by ilkkao** [comment]
@tau150 in my case it was ember component with `layout` property set to HTML string. If you are in same situation you can find it by searching for `layout:` in your code.

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
