### ISSUE TITLE
Support Dank Memes in Notes

### ISSUE THREAD

**Issue by chrisstrahl** [storybooks/storybook#5041]
**Is your feature request related to a problem? Please describe.**

Communication richness is increasing with the ubiquity of chat tools, social media integrations, and unprecedented levels of arguments about pronouncing .gif. The tools we use to annotate and comment on our favorite projects should also support our favorite memes.

**Describe the solution you'd like**
Create a basic integration for giphy or another service that allows for the searching and posting of dank memes as a part of comments and annotations.

**Describe alternatives you've considered**
Slack works reasonably well at being able to react to links to Storybook. However, it doesn't support giphy in threads, and honestly, Storybook should try to own this part of the ecosystem internally rather than relying on integrated tooling.

**Are you able to assist bring the feature to reality?**
Unfortunately, no. I just think it would be cool.

**Comment by igor-dv** [comment]
IMO, it's a very important feature. I would say having memes in Storybook is vital for this project, however, we have some less important stuff to finish before, therefore I will mark this as a "good first issue".

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.10 containing PR #5381 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
