### ISSUE TITLE
Make absolute path for dlls relative

### ISSUE THREAD

**Issue by cmwhiting** [storybooks/storybook#5055]
The dlls are loaded as `dlls: ['/sb_dll/storybook_ui_dll.js']` in `@storybook/core/src/server/manager/manager-webpack.config.js`, but if you're serving static files outside of the root directory, this will fail. This should hopefully be something relative, like `dlls: ['sb_dll/storybook_ui_dll.js']` or `dlls: ['./sb_dll/storybook_ui_dll.js']`

Ex: I have a node server stood up on `localhost:4000`, serving from `./public`. I change my storybook output directory to `./public/storybook`. The files are created, and loading `localhost:4000/storybook` serves the page, but requests `localhost:4000/sb_dll/storybook_ui_dll.js`, which doesn't exist. With relative pathing, it would request as `localhost:4000/storybook/sb_dll/storybook_ui_dll.js`, which would resolve correctly.

**Comment by ozio** [comment]
The same problem. We have a several environments and want to put storybooks to each of them as a subfolder, but we can't because of that absolute path. Had tried to change `publicPath` in webpack config, but it works only for paths in iframe.html.

**Comment by gpincheiraa** [comment]
Same problem here!

**Comment by unindented** [comment]
I'm also affected by this. In my case, I'm publishing to GitHub Pages, which are always `https://<user>.github.io/<project>/`, so `storybook_ui_dll.js` can never be found.

**Comment by Pluzu** [comment]
Same problem here

**Comment by dangerdespain** [comment]
+1, I'm affected by this as well

**Comment by dangerdespain** [comment]
For anyone else running across this, here's a build command that should fix this temporarily
```json
{
  "scripts" : {
    "build-storybook": "rm -rf storybook-static && build-storybook && sed -i -e 's/\\\/sb_dll/sb_dll/g' storybook-static/index.html"
  }
}
```

**Comment by ndelangen** [comment]
I'm going to fix this ASAP

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.1 containing PR #5238 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.1 containing PR #5238 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Mind giving this a try and letting me know if it works for you? If so, I\'ll cherry-pick this\nback to `master` and do a patch release. Thanks!

@cmwhiting @mysticatea @alex996 @ozio @asychev @Chariyski @baohouse @benjablanko @gpincheiraa @Stevo14850 @unindented @liss-mouse @vio @Pluzu @lauriejones @yhuard @johnhunter @heavenshell @dkimura @dangerdespain @ndelangen

**Comment by ozio** [comment]
Already. Can confirm that new path is relative: `./sb_dll/storybook_ui_dll.js` instead of `/sb_dll/storybook_ui_dll.js`.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v4.1.9 containing PR #5238 that references this issue. Upgrade today to try it out!
