### ISSUE TITLE
info addon: TypeScript/React PropTypes: "No propTypes defined!"

### ISSUE THREAD

**Issue by mweibel** [storybooks/storybook#5073]
When using TypeScript, React, and styled components the info addon doesn't seem to be able to show propTypes for the components. 

**To Reproduce**
A minimal reproducing example is found here:

https://github.com/mweibel/storybook-typescript-example

You can start storybook with `npm start`.

**Expected behavior**
Available propTypes are being shown. 

**Screenshots**
<img width="584" alt="screenshot 2018-12-21 at 07 25 35" src="https://user-images.githubusercontent.com/307427/50328099-055ba680-04f2-11e9-95e4-b2f6f42b4fae.png">

**System:**
 - OS: macOS
 - Device: MacBook Prop
 - Browser: Firefox 
 - Framework: react
 - Addons: actions, info, knobs
 - Version: 4.1.3 but also happens with 4.0.12 (and possibly lower, didn't check those)

**Comment by mergpippa** [comment]
The properties table is created in [makeTableComponent.js:80](https://github.com/storybooks/storybook/blob/master/addons/info/src/components/makeTableComponent.js#L80), this function is trying to get the proptype definition from [`type.propTypes`](https://github.com/storybooks/storybook/blob/master/addons/info/src/components/makeTableComponent.js#L43) or  [`type.__docgenInfo`](https://github.com/storybooks/storybook/blob/master/addons/info/src/components/makeTableComponent.js#L20).

You're usually not setting static `propTypes` properties on your React component when you're also using typescript. This means that you should use a documentation generator to create the `type.__docgenInfo` property for your components.

You're using a different documentation generator in your `webpack.config.js` than the one used in the [typescript configuration example](https://storybook.js.org/configurations/typescript-config/). Try using the documentation generator from the example, that one works fine for me.

**Comment by mweibel** [comment]
You're right! Using the docgen typescript loader instead of the plugin solved the issue for me.

FTR:
```
diff --git a/config/storybook/webpack.config.js b/config/storybook/webpack.config.js
index 7b09508..f048270 100644
--- a/config/storybook/webpack.config.js
+++ b/config/storybook/webpack.config.js
@@ -1,5 +1,4 @@
 const path = require("path");
-const TSDocgenPlugin = require("react-docgen-typescript-webpack-plugin");

 module.exports = (baseConfig, env, config) => {
   config.module.rules.push({
@@ -7,10 +6,12 @@ module.exports = (baseConfig, env, config) => {
     use: [
       {
         loader: "ts-loader"
+      },
+      {
+        loader: "react-docgen-typescript-loader"
       }
     ]
   });
-  config.plugins.push(new TSDocgenPlugin());
   config.resolve.extensions.push(".ts", ".tsx");
   return config;
 };
```

Thanks!

**Comment by adyz** [comment]
Also, if you are using React with Typescript and use this:

```jsx
export default class MyComponent {}
```

instead of:

```jsx
class MyComponent {}
export default MyComponent
```

it will not show the prop types
