### ISSUE TITLE
Dependency conflicts `@storybook/react` and `docz-default-theme` around `@emotion/core`

### ISSUE THREAD

**Issue by JustFly1984** [storybooks/storybook#5110]
Please update dependencies for @storybook/core && /components && /ui

<img width="331" alt="screenshot 2018-12-27 14 41 49" src="https://user-images.githubusercontent.com/2255993/50490836-9c8a9780-09e5-11e9-9b3d-9b23f04fe3c1.png">

`docz-default-theme` uses latest `@emotion/core@10.x`

It leads to impossible usage of both apps in same project.

**Comment by shilman** [comment]
@JustFly1984 FYI we're in 5.0-RC right now. Please check out the latest on the `next` NPM tag
