### ISSUE TITLE
Viewport Addon: Add responsive viewport option

### ISSUE THREAD

**Issue by s4l4x** [storybooks/storybook#5152]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to drag the corner of the viewport to dynamically resize it.

**Additional context**
As an example, please see the responsive design mode of Firefox Developer Edition.
https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

**Comment by amypellegrini** [comment]
I was just thinking about this and I'm glad I found this ticket here. I think that support for responsive viewport would add great value to Storybook.

Myself have to do some tricks if I want to test responsive/device-specific stuff within the Storybook UI.

**Comment by rijkvanzanten** [comment]
Is there any way to do this with the viewport addon currently? Stalebot gives me the impression that this feature request was ignored into oblivion, but it's hard to tell sometimes..

**Comment by shilman** [comment]
@rijkvanzanten Nobody picked it up, so it staled out :) AFAIK it's not implemented.
