### ISSUE TITLE
addon-info empty propType column

### ISSUE THREAD

**Issue by NoriSte** [storybooks/storybook#5162]
**Describe the bug**
The `propType` column is empty

**Code snippets**
Playing with the source code it looks that, in the `PrettyProType.js` file
```
const PrettyPropType = props => {
  const { propType, depth } = props;
  if (!propType) {
    return <span>unknown</span>;
  }

  const { name } = propType || {};

  if (propTypeComponentMap.has(name)) {
    const Component = propTypeComponentMap.get(name);
    return <Component propType={propType} depth={depth} />;
  }
  
  // Otherwise, propType does not have a dedicated component, display proptype name by default
  return <span>{name}</span>;
};
```
when you do ` const { name } = propType || {};` that's wrong because `propType` is a string, not an object

**System:**
 - OS: MacOS 10.13.6 (High Sierra)
 - Browser: Chrome Version 72.0.3626.28 (Official Build) beta (64-bit)
 - Framework: react
 - Addons: info
 - Version: 4.1.2

**Additional context**
I'm using Typescript

**Comment by ebrentnelson** [comment]
I noticed this today as well.

**Comment by ebrentnelson** [comment]
I'll create an PR (if that is even allowed--I need to check).

**Comment by ebrentnelson** [comment]
Already fixed: https://github.com/storybooks/storybook/blob/06e3e8da16bd04b8bf3f5399a41c7c7fc97eb089/addons/info/src/components/types/PrettyPropType.js#L40

Just needs to be released.
