### ISSUE TITLE
Running smoke test shows that storybook started

### ISSUE THREAD

**Issue by iliyanyotov** [storybooks/storybook#5164]
**Describe the bug**
When test running storybook with the shown command below, the details for the app being started with the URLs is still displayed without the app actually running.

`> start-storybook -p 9001 -c .storybook --quiet --smoke-test --ci`

**To Reproduce**
1. Run the command shown above.
2. The details panel is still shown.

**Expected behavior**
Don't show that the app is started when running the smoke test as it's confusing.

**Screenshots**
[https://imgur.com/hVs8hKu](https://imgur.com/hVs8hKu)

**Code snippets**
n/a

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: n/a
 - Framework: React
 - Addons: n/a
 - Version: `@storybook/react": "^4.1.4"`

**Additional context**
n/a

**Comment by iliyanyotov** [comment]
Don't close this issue, I will try to create a pull request in the next week or so. The fix should be really trivial.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.30 containing PR #6949 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
