### ISSUE TITLE
Don't replace full `process.env` object in DefinePlugin

### ISSUE THREAD

**Issue by franjohn21** [storybooks/storybook#5166]
**Describe the bug**
If a consumer uses it's own `DefinePlugin` or `EnvironmentPlugin` to replace environment variables, storybook replacing all of `process.env` introduces a potential point of conflict or breaking point if the environment variables are not resolved the same way. For example, if you use something like [node-config](https://github.com/lorenwest/node-config), you may want to configure the define plugin as such:

```js
const config = require('config');

new DefinePlugin({
  'process.env.FOO': config.FOO
});
```

The above conflicts when storybook fully replaces `process.env` [with its own environment variable handling](https://github.com/storybooks/storybook/blob/fe43e42180495269bc379e869beaaa76d3184ed1/lib/core/src/server/manager/manager-webpack.config.js#L55). I don't understand why storybook can't just replace the keys it knows about as described [in the webpack documentation](https://webpack.js.org/plugins/environment-plugin/#usage) so that it never breaks more complex environment variable logic as handled by the consumer:

```js
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
  'process.env.DEBUG': JSON.stringify(process.env.DEBUG)
});
```

**To Reproduce**
1. Use a custom webpack config with full control mode that adds a `DefinePlugin` to set `{ 'process.env.FOO': 'blah' }` and in your story console log the value of `process.env.FOO`.
2. Browse to your story and `process.env.FOO` will be undefined.
3. In the code you should see a `Object({"NODE_ENV":"development","NODE_PATH":"","PUBLIC_URL":"."}).FOO`

**Expected behavior**
Expected behavior is to not override other instantiations of DefinePlugin in storybook by setting environment variables to `undefined` when they wouldn't be otherwise

**Comment by SebastiaanNijland** [comment]
This is an issue for us as well. Some of our components have different behaviour based on `process.env` variables. The stories for these components currently break, because these variables are `undefined`. It would be nice if storybook could retain any `process.env` variables that are set with `DefinePlugin`.

**Comment by callmephilip** [comment]
i have noticed that Storybook picks up env settings from `.env` (using dotenv maybe?). @SebastiaanNijland might be a workaround for the problem you are facing

**Comment by gijoehosaphat** [comment]
This is also a problem for us. We don't want to have to change our application to use .env files, nor change where our config is located. We are passing some config in via CLI for now as a temporarily workaround.

**Comment by Armanio** [comment]
Hi! Can you show you custom webpack config. I trying reproduce and all is works fine. 
Yes, you right storybook replace `process.env` to object, but important to understand: webpack define plugin its literally plugin for text replacing. He don't create `process` object with `env` object inside. He replace `process.env.FOO` string to real FOO value.

My webpack.config.js file in .storybook dir:
```
const webpack = require('webpack');

module.exports = async ({ config }) => {
  config.plugins.push(
    new webpack.DefinePlugin({
      'process.env.FOO': JSON.stringify('asasd'),
      'process.env.STORYBOOK_FOO': JSON.stringify(false),
    })
  );
  return config;
};
```
In src/stories/index.js `console.log(process.env.FOO);`. I receive `asasd` in console.
After webpack processing:
`console.log("asasd");` - not process.env, the value

**Comment by SebastiaanNijland** [comment]
We recently upgraded to Storybook 5 and it seems to work fine for our use case now. Currently on Storybook 5.3.0.

**Comment by shilman** [comment]
@franjohn21 can we close this?

**Comment by franjohn21** [comment]
Based on the example from @Armanio it sounds like v5 fixes this - that was the same shape of my webpack config.

**Comment by wlblanchette** [comment]
Is this fixed? I'm using 5.0.11 which seems to be the latest version and storybook's DefinePlugin is still overriding `process.env`

**Comment by shilman** [comment]
@wlblanchette This is fixed in 5.1.0-rc.4. Full 5.1 release in the next few days.

**Comment by VictorienT** [comment]
Hi, I'm using 5.3.19 and trying to set a variable the same way @Armanio is is not working for me. 
process.env.FOO is undefined. 

Has something been broken since?

**Comment by SalathielGenese** [comment]
> Based on the example from @Armanio it sounds like v5 fixes this - that was the same shape of my webpack config.

Please, hos to I disable that behaviour... I genuinely don't want `process.env` to be evaluated during the build. Only at runtime, with custom values from my cloud provider.
