### ISSUE TITLE
"invalid storybook selection" warning

### ISSUE THREAD

**Issue by howitworks18** [storybooks/storybook#5168]
has anyone else encountered this warning? followed the set up process like README suggests and couldnt find anything in the docs.
![screen shot 2019-01-07 at 3 34 56 pm](https://user-images.githubusercontent.com/20389993/50794872-fdda2280-1291-11e9-9124-61d2a6a5568f.png)

**Comment by ugrky** [comment]
Same issue here:

`[11:59:58] invalid storybook selection
- node_modules/expo/build/environment/logging.js:25:23 in warn
- ... 19 more stack frames from framework internals

[12:00:00] invalid storybook selection
- node_modules/expo/build/environment/logging.js:25:23 in warn
- ... 19 more stack frames from framework internals
`

![screenshot_2019-01-08-12-01-19](https://user-images.githubusercontent.com/25139198/50820288-48fd3f80-133d-11e9-8ac8-840feec15f31.png)

**Comment by PanRada** [comment]
same +1

**Comment by Gongreg** [comment]
Hey, this warning should disappear some time in the future v4 version.

**Comment by inferusvv** [comment]
+1 Upgraded from 4.0.4 to 4.1.6

![2019-01-15 14 51 46](https://user-images.githubusercontent.com/3227120/51178916-1fac5880-18d5-11e9-9f7d-7c8c65c20d3f.png)

**Comment by JoaoBGusmao** [comment]
same here with 4.1.6

**Comment by alvincrespo** [comment]
Updated to 4.1.6 and still getting that warning.

**Comment by sejas** [comment]
+1

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybooks/storybook/releases/tag/v4.1.11 containing PR #5068 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
