### ISSUE TITLE
Native storybook unable to resolve babel aliases

### ISSUE THREAD

**Issue by akiwarheit** [storybooks/storybook#5201]
**Describe the bug**
I'm getting the same error as #2362 

`Module @components does not exist in the Haste module map`

Already have the `rn-cli.config.js` file from #2362 , app works fine - just storybook.

**To Reproduce**
The ff. `babelrc`
```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "env": {
    "production": {
      "plugins": [
        "transform-react-constant-elements",
        "transform-remove-console"
      ]
    }
  },
  "plugins": [
    [
      "module-resolver",
      {
        "cwd": "babelrc",
        "root": ["./"],
        "alias": {
          "@assets": "./assets",
          "@domain": "./artifacts/domain",
          "@util": "./artifacts/util",
          "@lib": "./artifacts/lib",
          "@components": "./artifacts/components"
        }
      }
    ]
  ]
}
```

**Expected behavior**
Should resolve the modules

**Screenshots**
<img width="1280" alt="screen shot 2019-01-10 at 2 59 33 pm" src="https://user-images.githubusercontent.com/713107/50941097-61f62400-14e8-11e9-8a21-70d3096fa5dd.png">

**Code snippets**
I use the ff. script to run storybook
`"storybook": "storybook start -p 7007 | react-native start --projectRoot storybook --reset-cache"`

**System:**
 - OS: MacOS
 - Device: iPhone XR Simulator
 - Framework: React Native
 - Version: 4.1.4

**Additional context**
```
    "@storybook/addon-actions": "^4.1.4",
    "@storybook/addon-links": "^4.1.4",
    "@storybook/addons": "^4.1.4",
    "@storybook/react-native": "^4.1.4",
```

**Comment by Gongreg** [comment]
Hey, Your issue is because RN storybook is still expecting babel 6. In storybook v5 we will use babel 7 and you won't have this issue anymore. Relevant PR https://github.com/storybooks/storybook/pull/4942

**Comment by akiwarheit** [comment]
I didn't want to do the ff. within my App's index file. (or at least didn't have to back in sb v3)

`export default StorybookConfig.useStorybook ? StorybookApp : App`

hence running `--projectRoot storybook` - it doesn't properly pick up the aliased modules this way though.

Seems like there's no way getting around it. Works fine if you don't set the `projectRoot` (but will have to toggle which app gets registered)

@Gongreg should I close?

**Comment by Gongreg** [comment]
Hey,
I am not 100% sure I follow the issue, but lets keep it for now. After we switch to babel 7 things might change.
