### ISSUE TITLE
@storybook/react@4.1.6 breaks module resolving if react folder in user sources

### ISSUE THREAD

**Issue by galefebvre-adeo** [storybooks/storybook#5204]
**Describe the bug**

Having a `src/react` folder in the user sources breaks absolute imports with `@storybook/react@4.1.6`.

**To Reproduce**
1. Install latest `yarn add -D @storybook/react@4.1.6`.
2. Create a component in `src/react/components/Button.jsx`.
3. Import this component from a story.
4. Launch storybook `start-storybook -p 9001 -c .storybook`.
5. Error in console `Module not found: Error: Can't resolve 'react/components/Button' in XXX`.

**Expected behavior**
The storybook builds fine.

**System:**
 - OS: Windows10
 - Framework: react
 - Version: 4.1.6

**Additional context**
This comes from this PR: #5148, specifically line 87 of `lib/core/src/server/preview/iframe-webpack.config.js`. It adds an alias of `react` to `node_modules/react` to make sure to import the react version of the user instead of the version used by the storybook ui. The problem is that webpack doesn't lookup the folders specified in `resolve.modules` (i.e. `src`) if it finds that the imported path matches an alias.

For the time being I simply overrode the webpack config in `.storybook/webpack.config.js` to remove the `react` alias since I'm using the same version as storybook.

```js
// .storybook/webpack.config.js
module.exports = (baseConfig, env, defaultConfig) => {
  delete defaultConfig.resolve.alias.react;
  return defaultConfig;
};
```

This is not ideal since it basically removes the feature of importing the user react version. Not sure how to fix this besides changing the `src/react` folder name, but that makes storybook enforce an arbitrary rule to the user code base.

**Comment by mpelekh** [comment]
The same issue exists with storybook/react@4.1.12 as well.
