### ISSUE TITLE
@storybook/react uses babel-loader version incompatible with react-scripts

### ISSUE THREAD

**Issue by cfv1984** [storybooks/storybook#5208]
**Describe the bug**
```react-scripts``` demands babel-loader 8.0.4 and ```@storybook/react``` demands 8.0.5

**To Reproduce**
1. With CRA 2, create a new react app
2. With sb-cli, add a new storybook
3. Start the CRA React app

**Expected behavior**
Tools should not be mutually incompatible if they are advertised as compatible.

**Comment by aericson** [comment]
duplicate of #5183

**Comment by mrmckeb** [comment]
Closing as a duplicate of #5183 (thanks @aericson).

I'll comment on that issue, @cfv1984.
