### ISSUE TITLE
No rotation options for iPhone 6 on Viewport

### ISSUE THREAD

**Issue by mneumark** [storybooks/storybook#5209]
**Describe the bug**
When using the viewport addon, no rotation option exists for iPhone 6. The Rotation option appears for every other device I have tried. See the screenshots below.

**To Reproduce**
1. Open the viewport tab at the bottom
2. Select iPhone 6 Plus
3. Notice that the rotation option exists
4. Select iPhone 6
5. Notice that the rotation option disappears

**Expected behavior**
Rotation option should remain for the iPhone 6

**Screenshots**
![iPhone 6 Plus has Rotation](https://user-images.githubusercontent.com/8795693/50996410-aa0c4b00-14d6-11e9-852c-75c2f5fbdc8e.png)

![iPhone 6 does not have rotation](https://user-images.githubusercontent.com/8795693/50996399-a1b41000-14d6-11e9-898a-fa19a6f5c741.png)

**System:**
 - OS: macOS Mojave 10.14.2
 - Device: Macbook Pro 2017
 - Browser: Chrome 71
 - Framework: React
 - Addons: viewport
 - Version: 4.1.6

**Comment by dmitrbrvsk** [comment]
@mneumark What version of `@storybook/addon-viewport` are you using?

**Comment by Keraito** [comment]
> Version: 4.1.6

@dmitrbrvsk, I assume the above stated version is both the framework and the respective addon. But just in case, @mneumark, can you confirm this? 😄 

Also, could you check whether this is only for iPhone 6 or also for other devices? Or maybe whether it always happens with the second chosen device?
