### ISSUE TITLE
SB5 CRA stories not showing up

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#5227]
**Describe the bug**
When you run SB5 on a default CRA setup, no clickable stories show up in the tree view.

**To Reproduce**
```
npx create-react-app cra2
cd cra2
npx -p @storybook/cli@next sb init
yarn storybook
```

**Expected behavior**
Expect clickable stories, get only headings:

<img width="818" alt="storybook" src="https://user-images.githubusercontent.com/488689/51094925-e0560d00-17eb-11e9-890b-73bf3d498af2.png">

**System:**
 - OS: MacOS
 - Device: Macbook Pro
 - Browser: chrome
 - Framework: react
 - Addons: [if relevant]
 - Version: 5.0.0-alpha.0

**Comment by tmeasday** [comment]
I can fix this. This is something to do with the default behaviour of roots vs groups vs stories

**Comment by tmeasday** [comment]
Fixed by #5236 I think

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.1 containing PR #5236 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.1 containing PR #5236 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.1 that addresses this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
