### ISSUE TITLE
4.1.6, Storybook UI visible in the background in fullscreen mode

### ISSUE THREAD

**Issue by Volune** [storybooks/storybook#5234]
**Describe the bug**
In fullscreen mode, the left panel is still visible through transparent iframe background.
Duplicate of closed ticket #4265 

**To Reproduce**
Install `@storybook/react` (tested with `4.1.6`)
Storybook config:
```
import React from 'react';
import { storiesOf, configure } from '@storybook/react';

configure(() => {
  storiesOf('Test').add('example', () => React.createElement('div'));
}, module);
```
Start storybook. Change layout to fullscreen.

**Expected behavior**
The Storybook UI is not visible in the background

**Screenshots**
![screenshot](https://gist.githubusercontent.com/Volune/ffd6efc2ab0a285d4a9e9673c335d897/raw/4a3a7fd36309eaf2d92b31ff3c6eb4735696641f/storybook-background-bug.jpg)

**Comment by ndelangen** [comment]
Should be fixed in V5
