### ISSUE TITLE
Typescript CRA2 doesn't shows any stories on running storybook

### ISSUE THREAD

**Issue by kushalmahajan** [storybooks/storybook#5237]
`yarn run storybook` doesn't shows any stories. I followed the guide [here](https://storybook.js.org/configurations/typescript-config/) 

Dynamic loading of stories doesn't works but static works. Since, the storybook  runs without errors, so I'm guessing something needs to be done in this code

```
// automatically import all files ending in *.stories.tsx
const req = require.context('../stories', true, /.stories.tsx$/);

function loadStories() {
  req.keys().forEach(req);
}

configure(loadStories, module)
```

It would be helpful if each line was explained in full to what it does. 

Moving on, I've my stories folder in root of the project having one story as 

```
import * as React from 'react';
import { storiesOf } from '@storybook/react';
import Button from '../src/components/Button';

const stories = storiesOf('Button', module);

stories.add('Button', () => <Button />, {
    info: { inline: true }
});

```

I've the following `devDependencies` in `package.json`

```
 "devDependencies": {
    "@storybook/addon-info": "^4.1.6",
    "react-docgen-typescript-webpack-plugin": "^1.1.0"
  }
```
and `tsconfig.json` mentions 

```
   "rootDirs": [
        "src",
        "stories"
    ]
```
_Important_ - I would later want to load stories from src/components/Button/Button.stories.tsx file 
and similarly for other UI components to load at once. 

I tried doing the following and doesn't compiles properly.

```
const req = require.context('../src/**/*', true, /.stories.tsx$/);
```

So again, how does require.context works? 

About the main issue, any idea where did things go wrong?

**Comment by martinmckenna** [comment]
@kushalmahajan I'm still having similar issues as you. What import were you missing exactly?
