### ISSUE TITLE
Global style not loaded in Angular

### ISSUE THREAD

**Issue by aloifolia** [storybooks/storybook#5239]
**Describe the bug**
I want to include a stylesheet file in my stories globally. However, the file is not loaded. My `angular.json` looks like this (the last line contains the style inclusion):

```json
{
    "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
    "version": 1,
    "newProjectRoot": "projects",
    "projects": {
        "my-project": {
            "root": "..",
            "sourceRoot": ".",
            "projectType": "application",
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser",
                    "options": {
                        "outputPath": "dist",
                        "index": "./components/root/static/index.html",
                        "main": "./app.entry.ts",
                        "tsConfig": "./tsconfig.json",
                        "polyfills": "./app/app.dependencies.ts",
                        "assets": ["app/assets"],
                        "styles": ["app/assets/style/style.scss"],
```

**System:**
 - OS: MacOS
 - Browser: chrome
 - Framework: angular 7.2
 - Version: Storybook 4.1.4

**Comment by mrkpks** [comment]
Same problem with **Storybook 4.1.6**. Tried various solutions with `webpack.config.ts` but nothing worked. Component styles are loaded fine.

**Comment by ThibaudAV** [comment]
Same problem when I updated the different angular dependencies from 7.1.4 to 7.2.1

**Comment by kommundsen** [comment]
I have the samme issue after upgrading to Angular 7.2.1.

**Comment by yjcxy12** [comment]
Looks like this is breaking change.
https://github.com/angular/angular-cli/commit/4f8a5b7a55316f773c1ae80505864212dc278b6a#diff-ef298d20cc5b49a2407cabad6876a7b4R23

And this line might need to add `buildOptions.optimization` and `buildOptions.sourceMap` as empty object by default.
https://github.com/storybooks/storybook/blob/v4.1.11/app/angular/src/server/angular-cli_config.js#L90

**Comment by crushjz** [comment]
Following this as I'm having the same issue.

**Comment by aloifolia** [comment]
Well, as long as it is not fixed, the bug should stay open.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.7 containing PR #5776 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
