### ISSUE TITLE
Webpack Full control silence warnings or disable HMR

### ISSUE THREAD

**Issue by Edd-Strickland** [storybooks/storybook#5250]
**Is your feature request related to a problem? Please describe.**
This would allow the Polymer/Web components version to run without large overheads of warnings which are thrown up by web packs HMR issues. 

**Describe the solution you'd like**
Clear documentation on how webpack works in the context of storybook.  

using standard webpack module.exports within Full control mode the options are ignored entirely by the SB implementation by following the examples in the documentation. 

**Describe alternatives you've considered**
I've tried the following:

  module.exports = {
    devServer: {
      stats: 'errors-only'
    }
  }
------------
  module.exports = {
      stats: 'errors-only'
  }
------------

storybookBaseConfig.devServer ({
stats: 'errors-only'
})

No of which work because the full control mode config is ignored. 

**Are you able to assist bring the feature to reality?**
No, at least not without guidance of how this currently works. 

**Additional context**
The issue here is that HMR reloads and doesn't understand the difference between the app and the iframe it appears so thinks the named resource has been called already so pings a warning about it. 

either HMR needs to be configurable to turn off (not a great solution) or warnings need disabling (again not the best solution).

I believe this is an issue which was previously caused in react versions by not including the module as the second argument in the storys however even with this the warnings persist. (as per the fix to include modules and throw a warning) but this isn't helpful in the polymer version as these warnings mean as the storybook grows it causes an out fo memory exception on the browser in dev mode. 

I've tried asking for help on the discord and also slack however have had zero responses to my questions.  

If SB is to support Web components as well then this needs fixing.  I believe that looking at the 5 alpha this might have been realised as there's a new way of doing the webpack config now however until this is release or there's a polymer / web components version then this is a short term fix.

**Comment by paco3346** [comment]
Using the method approach to webpack overrides (in `.storybook/webpack.config.js`) you can add the following to disable warnings in your webpack console:
`config.devServer = {stats: 'errors-only'};`

Full working copy:
```
module.exports = async ({ config, mode }) => {
  config.devServer = {stats: 'errors-only'};
  return config;
};
```
