### ISSUE TITLE
Changes listed in react native alpha release notes are not in npm module

### ISSUE THREAD

**Issue by owinter86** [storybooks/storybook#5264]
**Describe the bug**
A contribution I made that updated the react native on device ui does not seem to have been transferred to the npm build when installing storybook alpha releases.

```
## 4.2.0-alpha.6 (December 20, 2018)

### Features

* React-Native: Change on-device layout to absolute position ([#4962](https://github.com/storybooks/storybook/pull/4962))
...
```
I can confirm the repo has the #4962 changes, but the actual npm module does not.

my package.json snippet
```
"devDependencies": {
    "@storybook/react-native": "^4.2.0-alpha.6",
    ...
}
```

**To Reproduce**
Install npm module "@storybook/react-native": "^4.2.0-alpha.6", and compare onDevice ui components to the main repository. Changes have not been included.

**Comment by shilman** [comment]
@owinter86 They are included in `4.2.0-alpha.6` and above.

However, when you install `^4.2.0-alpha.6` it actually installs `4.2.0-cra-debug.0` which was released on the `debug` NPM tag bug unfortunately matches the `-alpha` semver range.

I would suggest either:
- Installing a specific version e.g. `4.2.0-alpha.11` (the latest 4.2 alpha)
- Installing from the `@next` NPM tag (which is currently `5.0.0-alpha.5`)

Needless to say, I would be using the `-debug-xxx` suffix anymore. Sorry for the inconvenience.
