### ISSUE TITLE
Build creating nested storybook UI - Inception!

### ISSUE THREAD

**Issue by dstroot** [storybooks/storybook#5269]
**Describe the bug**
Using vanilla Create-React-App, then add storybook, then run build-storybook.  Here is the results:
<img width="1373" alt="screen shot 2019-01-16 at 11 39 14 am" src="https://user-images.githubusercontent.com/1438457/51274341-cd764080-1983-11e9-8c27-f9193e934a4c.png">

**To Reproduce**
 - Run CRA
 - Add storybook
 - Run `build-storybook` 
 - serve the results

**Expected behavior**
Storybook should look the same as when you use `yarn storybook`

**Screenshots**

<img width="1373" alt="screen shot 2019-01-16 at 11 39 14 am" src="https://user-images.githubusercontent.com/1438457/51274461-2219bb80-1984-11e9-8f93-aac15f802656.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS:MacOS
 - Device: Macbook Pro 2018
 - Browser: Chrome latest
 - Framework: React
 - Addons: None - Using CRA to bootstrap app
 - Version: 4.1.6 and Latest

**Additional context**

**Comment by tmeasday** [comment]
Hi @dstroot, thanks for the report.

I tried to reproduce this with `react-scripts@2.1.3` and `@storybook/react@4.1.6` and I am not seeing the problem. I opened the built storybook directly (as in `file://`) and served it with `npx serve`.

I wonder how you are serving you storybook? Perhaps it is somehow redirection `/iframe.html` to `/`?

**Comment by shilman** [comment]
Found tis other nice bug while trying to repro 😉 : https://github.com/storybooks/storybook/issues/5274

**Comment by dstroot** [comment]
I am going to close this - just tried again with `npx serve` and no issues.  I was using "serve" installed globally (npm -g) but I doubt that is the real root cause.  So weird - yesterday no matter what I could not get it to work and today is works great.

**Comment by efmr** [comment]
Found the same issue to reproduce it:

`serve -s storybook-static`

Removing the single page app flag fixes it:

`serve storybook-static`

**Comment by dstroot** [comment]
@efmr > Gah!  That was it!

**Comment by ksegal** [comment]
I encountered this same resulting nested storybook behavior but the cause of the bug was slightly different. There is a bug in the babel 7.7.0 release, reported [here](https://github.com/babel/babel/issues/10654). As a result of these type errors, my storybook build fails but then renders like the image above. Once [this fix](https://github.com/babel/babel/pull/10656) is out in a release, it should be safe to upgrade, but until then you may want to lock in the babel 7.6 minor version.

**Comment by shilman** [comment]
Thanks @ksegal! Hope they get that fix out soon 🙏

**Comment by jimjeffers** [comment]
What exactly is the solution to this issue? Or what are the steps to troubleshoot this? It's not clear to me why this is occurring.

**Comment by shilman** [comment]
@jimjeffers https://github.com/storybookjs/storybook/issues/5269#issuecomment-503765857

**Comment by jimjeffers** [comment]
Thanks @shilman in this case I'm not using serve - I just deployed a static build to an S3 bucket but I'm getting the crazy inception issue. I just tried using serve without the -s flag but still get the inception! So odd. I can't spot any errors in the console so I'm having trouble debugging this one. I must have a different issue but same outcome as has been discussed on this thread.

**Comment by shilman** [comment]
Are you using the -p option?

**Comment by jimjeffers** [comment]
@shilman This is what I've been using to deploy:

```json
{
// ...
        "deploy-storybook": "storybook-to-aws-s3 --bucket-path=gigzilla-stories --aws-profile=gigzilla-storybook",
        "build-storybook": "build-storybook -s public",
//...
}
 ```

**Comment by jimjeffers** [comment]
@shilman here are the versions I'm on if it helps:

```json
    "devDependencies": {
        "@storybook/addon-actions": "^6.2.9",
        "@storybook/addon-essentials": "^6.2.9",
        "@storybook/addon-links": "^6.2.9",
        "@storybook/node-logger": "^6.2.9",
        "@storybook/preset-create-react-app": "^3.1.7",
        "@storybook/react": "^6.2.9",
        "@storybook/storybook-deployer": "^2.8.7",
     }
```

**Comment by shilman** [comment]
Does it also have that problem when you serve locally?

**Comment by jimjeffers** [comment]
@shilman Looks like it! If I build locally and run serve from the output dir as such:

```
storybook-static % npx serve
```

I get that recursion issue. No errors in the console however.

**Comment by shilman** [comment]
Are there any soft links in the public directory? Do you have a repro you can share?

**Comment by jimjeffers** [comment]
@shilman I gave up and just moved the components/stories into a fresh CRA project. I have no idea what was causing it but we're migrating the project anyway. It would be handy if there was a way to isolate the error that causes the 'inception' though! My guess is it happens somewhere in the iframe which is why we don't see any errors in the inspector?

**Comment by nilslp** [comment]
Did anyone manage to find a solution for this?

All was working locally via `yarn start` (dev) and when `yarn build` (production) then serving.
Once we tested a deployment on amplify the inception UI issue appeared.

**Comment by Alpha1337k** [comment]
@nilslp Take a look at the redirects of amplify. It might be that all requests would be redirected to /index.html instead of /iframe.html etc.

Hope this helps.

**Comment by nilslp** [comment]
> @nilslp Take a look at the redirects of amplify. It might be that all requests would be redirected to /index.html instead of /iframe.html etc.
> 
> Hope this helps.

You were right @Alpha1337k, I had meant to return to post this as amplify was the issue all along. Thanks
