### ISSUE TITLE
Setting a11y config before loading stories stops stories loading

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#5270]
See https://github.com/storybooks/storybook/issues/5235#issuecomment-454978718

I'll try to create a simpler reproduction

**Comment by ndelangen** [comment]
@tmeasday https://github.com/storybooks/storybook/issues/5235#issuecomment-455731433

**Comment by tmeasday** [comment]
TLDR of above is: we now use a parameters-based API for addon-a11y.

Perhaps better to ask on this issue:
@ndelangen can we retain backwards compatibility (and deprecate) in this release?

**Comment by tmeasday** [comment]
Looks like this was fixed by https://github.com/storybooks/storybook/commit/ecaf37a5d462dfe805a3dd181023db0bb3e44db8 -- is that right @codebyalex?
