### ISSUE TITLE
[addon-storysource] Not showing render prop components / children as function

### ISSUE THREAD

**Issue by rwieruch** [storybooks/storybook#5273]
Hello everybody. So far, StorySource worked perfectly for me. However, once I started to use render prop components, StorySource didn't show the whole story anymore. Everything inside the children as a function is missing.

For instance, I have the following story for my Table component:

```
const list = [
  { id: '1', name: 'Hello', stars: 24, count: 42 },
  { id: '2', name: 'World', stars: 42, count: 24 },
];

storiesOf('3. Organisms/03. Table', module)
  .add('default', () => {
    return (
      <Table list={list}>
        {tableList => (
          <Table.Content>
            <Table.Header>
              <Table.HeaderRow>
                <Table.HeaderCell>Name</Table.HeaderCell>
                <Table.HeaderCell>Stars</Table.HeaderCell>
                <Table.HeaderCell>Count</Table.HeaderCell>
              </Table.HeaderRow>
            </Table.Header>

            <Table.Body>
              {tableList.map(item => (
                <Table.Row key={item.id}>
                  <Table.Cell>{item.name}</Table.Cell>
                  <Table.Cell>{item.stars}</Table.Cell>
                  <Table.Cell>{item.count}</Table.Cell>
                </Table.Row>
              ))}
            </Table.Body>
          </Table.Content>
        )}
      </Table>
    );
  });
```

whereas the Table is a render prop component which uses the children as render function. Now in my Storybook, I get the following output for my StorySource:

<img width="543" alt="screen shot 2019-01-17 at 12 27 00" src="https://user-images.githubusercontent.com/2479967/51295683-bef75a00-1a53-11e9-80c5-65812733af46.png">

I have seen this problem with other render prop components as well. Is there anything I can do about it or an issue about it that I couldn't find? Thanks for your help!

All my Storybook node packages are at 4.1.6.

**Comment by mrmckeb** [comment]
Hi @rwieruch, thanks for raising this. This looks like a bug with that addon.

Would you like to take a look? If so, let me know, otherwise I can take a look during the week.

**Comment by rwieruch** [comment]
Not really sure if I find the time for it @mrmckeb But there is no rush in fixing this from my side. It's just a client of mine who noticed it as regression bug after I upgraded the Storybook packages to the latest versions. Still they are able to use it and excited to have it in their tech stack :)

**Comment by mrmckeb** [comment]
I did not sorry @rwieruch, and was out of action sorry... but back and can still look into this.

This issue is still occurring for you?
