### ISSUE TITLE
SB5 story navigation broken when using `file://` URL

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#5274]
**Describe the bug**

When you build a static storybook and view it with a file URL, navigation doesn't work

**Repro**

```
npx create-react-app cra
cd cra
npx -p @storybook/cli@next sb init
yarn build-storybook
cd storybook-static
open index.html
```

Then click on a story in the treeview.

It will nav to something like `file:///?path=/story/button--with-text` and show your file system.

NOTE: this works in SB4

**Comment by ndelangen** [comment]
Confirmed, I will fix this.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.7 containing PR #5295 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
