### ISSUE TITLE
import { object } from '@storybook/addon-knobs/angular' throw error

### ISSUE THREAD

**Issue by doroncy** [storybooks/storybook#5276]
**Describe the bug**
When using ```import { object } from '@storybook/addon-knobs/angular';``` 
and creating an object (for example: ), the following error is outputting to the console.
```
Warning: `ObjectType` uses `getDerivedStateFromProps` but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `ObjectType`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape.
```

**To Reproduce**
1. Import object from '@storybook/addon-knobs/angular'
2. create a new object
3. run storybook
4. See the error in the console

**Expected behavior**
there shouldn't be any error.

**System:**
 - OS:MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: angular
 - Addons: [ knobs ]
 - Version: 4.1.6

**Comment by alinkedd** [comment]
I have the same error ( importing `{ object }` from `@storybook/addon-knobs` of version 4.0.9) in development mode. Clearly, [ObjectType component](https://github.com/storybooks/storybook/blob/next/addons/knobs/src/components/types/Object.js) does not have initial state.

**Comment by frebro** [comment]
Same thing for me, except using 

`import { object } from "@storybook/addon-knobs"`

…and using Vue framework on the same specs running 4.2.0-alpha.11.

**Comment by IvanGrimes** [comment]
I am also have the same trouble, but with React.

**Comment by renatho** [comment]
I have the same problem here with React

**Comment by Pittan** [comment]
I have the same problem with Vue
@storybook/addon-knobs 4.1.11

**Comment by kaiyoma** [comment]
Running into this with Storybook for our React components. Versions:

```
    "@storybook/addon-actions": "4.0.12",
    "@storybook/addon-knobs": "4.1.4",
    "@storybook/addon-notes": "4.1.4",
    "@storybook/addons": "4.0.12",
    "@storybook/react": "4.0.12",
```

**Comment by kallrobin** [comment]
Also having the same bug 
Versions: 
```
    "@storybook/addon-actions": "^5.0.0",
    "@storybook/addon-info": "^5.0.0",
    "@storybook/addon-knobs": "^5.0.0",
    "@storybook/addon-links": "^5.0.0",
    "@storybook/addon-options": "^5.0.0",
    "@storybook/addons": "^5.0.0",
    "@storybook/react": "^5.0.0",
    "@storybook/theming": "^5.0.0",
```

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.13 containing PR #6159 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.4 containing PR #6159 that references this issue. Upgrade today to try it out!
