### ISSUE TITLE
[addon-centered] import breaks webpack dev server

### ISSUE THREAD

**Issue by thatbudakguy** [storybooks/storybook#5292]
**Describe the bug**
Importing the 'centered' addon causes the webpack dev server to stop working, and fail to start on all subsequent builds.

**To Reproduce**
1. run storybook with `start-storybook -p 9001 -c .storybook`
2. add `import '@storybook/addon-centered/register'` to `addons.js`
3. web ui will refresh and show a blank white screen.
4. stop dev server with <kbd>ctrl</kbd>+<kbd>c</kbd> and restart it
5. webpack will complete the build, but will not start the dev server again and show the "running on port 9001" message.

**Expected behavior**
Importing the module will allow me to use it.

**Code snippets**
`config.js`
```js
import { configure } from '@storybook/vue'
const req = require.context('../src/stories', true, /stories\.js$/)
const loadStories = () => req.keys().forEach(filename => req(filename))
configure(loadStories, module)
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Browser: Firefox 65
 - Framework: Vue
 - Addons: centered
 - Version: 4.1.7

**Comment by ndelangen** [comment]
Do not do this:
`import '@storybook/addon-centered/register' in addons.js

addon-centered has no part in the manager.

For vue you should just import the decorator in your stories like so:

```js
import centered from '@storybook/addon-centered/dist/vue`;
```

In V5 I'll fix it so you can do:
```js
import centered from '@storybook/addon-centered/vue`;
```

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.7 containing PR #5296 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
