### ISSUE TITLE
addon withinfo decorator showing same component for different module

### ISSUE THREAD

**Issue by himanshu-dixit** [storybooks/storybook#5319]
**Describe the bug**
For different story modules, the storybook within addon is showing same component name, props.

**Expected behavior**
Respective component name

**Screenshots**
![screen shot 2019-01-21 at 12 53 29 pm](https://user-images.githubusercontent.com/6849438/51458659-fcbdf080-1d7b-11e9-9791-fd7cb06024a3.png)
![screen shot 2019-01-21 at 12 53 18 pm](https://user-images.githubusercontent.com/6849438/51458660-fcbdf080-1d7b-11e9-8427-d85a3868a795.png)

**Comment by Keraito** [comment]
That doesn't look right. I couldn't quite reproduce this behaviour tho @himanshu-dixit, could you share which versions of the respective packages you are using and possible also a reproduction that we can look into?
