### ISSUE TITLE
Vuejs HMR is not working (vue-cli 3)

### ISSUE THREAD

**Issue by noah004B** [storybooks/storybook#5325]
**Describe the bug**

When changing the components that I am using from my stories(), HMR is not reloading the content of the story.
"http://ip of my dev machine:6006/__webpack_hmr" is causing "Provisional headers are shown" in the Chrome dev tool. 

**To Reproduce**

1. Create vue project with storybook

```
$ vue create sample-project
Vue CLI v3.3.0
? Please pick a preset: default (babel, eslint) 
$ vue add storybook
$ npm run storybook:serve
```

2. Open storybook ui with Chrome
3. Edit './src/components/MyButton.vue
4. HMR not working.

**Expected behavior**

HMR should work and detect those changes and reload the component we are seeing inside the story.

**Screenshots**

![image](https://user-images.githubusercontent.com/43510508/51510538-c9916500-1e40-11e9-8612-3c88d3ba36d3.png)

**System:**

Windows10(Chrome) <--> CentOS7.5 on VMware ESXi (Project codes, Nodejs and vim)

I'm developing in remote server(CentOS7.5 on ESXi) in my office.
"npm run storybook:serve" is running the Linux machine.
I access the web ui of storybook from my windows machine with Chrome.

Linux machine
- OS: CentOS7.5
- Nodejs: v8.12.0
- npm: 6.4.1
- vue-cli: 3.3.0
- storybook: 4.1.7

Windows machine
- OS: Windows 10
- Chrome: 71.0.3578.98（Official Build）64bit

I am happy if anyone can help me to solve this problem.

**Comment by crowphy** [comment]
> **Describe the bug**
> 
> When changing the components that I am using from my stories(), HMR is not reloading the content of the story.
> "http://ip of my dev machine:6006/__webpack_hmr" is causing "Provisional headers are shown" in the Chrome dev tool.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Create vue project with storybook
> 
> ```
> $ vue create sample-project
> Vue CLI v3.3.0
> ? Please pick a preset: default (babel, eslint) 
> $ vue add storybook
> $ npm run storybook:serve
> ```
> 1. Open storybook ui with Chrome
> 2. Edit './src/components/MyButton.vue
> 3. HMR not working.
> 
> **Expected behavior**
> 
> HMR should work and detect those changes and reload the component we are seeing inside the story.
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/43510508/51510538-c9916500-1e40-11e9-8612-3c88d3ba36d3.png)
> 
> **System:**
> 
> Windows10(Chrome) <--> CentOS7.5 on VMware ESXi (Project codes, Nodejs and vim)
> 
> I'm developing in remote server(CentOS7.5 on ESXi) in my office.
> "npm run storybook:serve" is running the Linux machine.
> I access the web ui of storybook from my windows machine with Chrome.
> 
> Linux machine
> 
> * OS: CentOS7.5
> * Nodejs: v8.12.0
> * npm: 6.4.1
> * vue-cli: 3.3.0
> * storybook: 4.1.7
> 
> Windows machine
> 
> * OS: Windows 10
> * Chrome: 71.0.3578.98（Official Build）64bit
> 
> I am happy if anyone can help me to solve this problem.

I have the same issue, but on macos
