### ISSUE TITLE
Absolute path output in build-storybook doesn't work as expected

### ISSUE THREAD

**Issue by jtamary** [storybooks/storybook#5334]
**Describe the bug**
When absolute path output is given to build-storybook, the output will be relative to the working directory concatenated with the given absolute path.

**To Reproduce**
Steps to reproduce the behavior (Storybook version 4.1.7):
1. Run` build-storybook -o '/absolute/path'`
2. The output will be relative to the working directory with a concatenation of the absolute path `<command dir>/absolute/path`. 

**Expected behavior**
The output of the static files should be in the absolute path form the command line arguments.
On Storybook 4.0.4 it works as expected, so it's kind of a regression.

I think that it's related to this change https://github.com/storybooks/storybook/commit/a92ddc53d97e20f31ac30b275e6b0b52356ffa9f#diff-329a7cb6ceb533e8db66ba0c81dda4a0R18

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2015
 - Framework: react
 - Version: 4.1.7

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-beta.4 containing PR #5573 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
