### ISSUE TITLE
Remove selectedKind and selectedStory

### ISSUE THREAD

**Issue by aharon87** [storybooks/storybook#5336]
Hey, 
Is it possible to run storybook without selectedKind and selectedStory in the URL?

only http://localhost:9010

I am trying to test href with some rout  http://localhost:9010/someroutexample.

( I've tried to run Storybook as a Static App, but on the server side we have a problem to create a valid user from that request.)

**Comment by ndelangen** [comment]
V5 will migrate to a single path in the url via a router.

Can you check out the latest RC release and tell us if this resolves your issue?
