### ISSUE TITLE
Angular issues with symlinks in lerna monorepo

### ISSUE THREAD

**Issue by acailly** [storybooks/storybook#5362]
# Context

This is a resolved issue, I spent several days to make it work and I did not found any issue targeting this specific point so I write one for others having the same problem

I have several Angular libs built with ngpackagr and using storybook, all these libs are in a lerna monorepo and some libs depends on others

I was in the situation where:
- main app was working
- tests were working for libs and main app
- storybook was working for main app

But storybook was not working for a lib A that depends on other lib B

I had errors like:
- Error: inject() must be called from an injection context
- NullInjectorError: No provider for HttpClient!

# Symlinks are the root cause

When I replaced the symbolic link to B contained in the node_modules folder of A by a copy of B, everything worked

# Solution

In an angular app, putting `preserveSymlinks` in the build config of `angular.json` usually do the trick

But it is a lib built with ngpackagr and there is no option `preserveSymlinks`

I fixed this issue by creating a custom webpack config (`.storybook/webpack.config.js`) that sets `resolve.symlinks` to false (maybe that's what `preserveSymlinks` does for angular apps?): 

```
module.exports = baseConfig => {
  // Extend defaultConfig as you need.

  baseConfig.resolve = {
    ...baseConfig.resolve,
    symlinks: true
  };

  return baseConfig;
};
```

**Comment by markchitty** [comment]
Thanks @acailly, this finally solved several hours of pain for me. Just to note, your solution code accidentally has `symlinks: true` where the [actual solution](https://webpack.js.org/configuration/resolve/#resolvesymlinks) is `symlinks: false` (as you correctly describe in you commentary).

Updated for Storybook 5.3 Webpack syntax, it looks like this:

```
/* .storybook/main.js */

module.exports = {
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({ /* webpack rule tweaks */ });

    // Make Storybook work with npm link symlinks \o/
    config.resolve = { ...config.resolve, symlinks: false };

    return config;
  },
};
```
