### ISSUE TITLE
React Fragments Rendering as Undefined

### ISSUE THREAD

**Issue by shannontan-bolt** [storybooks/storybook#5364]
**Describe the bug**
When using `<Fragment>` syntax with React 16.7, the HTML shows an `<undefined>` wrapping tag instead of omitting that altogether. This appears specific to Storybook, as this undefined tag is not shown in the HTML elsewhere.

**To Reproduce**
1. Wrap with `<Fragment>` instead of `<div>`
2. Run Storybook + regular client
3. See the undefined element in Storybook.

**Expected behavior**
There shouldn't be any additional element when using React.Fragment.

**System:**
 - OS: MacOS
 - Device: MacBook Pro 2018
 - Browser: Chrome
 - Framework: React v16.7
 - Addons: N/A
 - Version: 4.1.9

**Additional context**
Could this be a config issue?

**Comment by Keraito** [comment]
@igor-dv do you by chance have a clue why this is happening?
@shannontan-bolt do you have a small/minimal reproduction that produces the error and that we can easily look at?

**Comment by shannontan-bolt** [comment]
I don't have a side reproduction at the moment and don't have the bandwidth to do so at the moment. However, I will try to repro next week. If you could repro, that would be great.

My component was really simple and it just wrapped two divs with a `Fragment` instead of a `div` since I didn't need the outer div to enforce any CSS.

**Comment by Keraito** [comment]
> However, I will try to repro next week. If you could repro, that would be great.

Awesome! I will try to see if I can reproduce it in the kitchen sink of Storybook's own stories. Should be easy to do so if it's the matter of adding a Fragment element.

**Comment by Keraito** [comment]
@shannontan-bolt 	I tried it in the official example stories that we have in the repo, but it correctly gets rid of the `Fragment` elements there. Could you reproduce and share your bug?

**Comment by shannontan-bolt** [comment]
@Keraito Our team managed to isolate this issue to our use of Preact in certain places impacting our React components. 

Sorry for flagging this inappropriately, and thanks so much for your help!

**Comment by wahidshafique** [comment]
> @Keraito Our team managed to isolate this issue to our use of Preact in certain places impacting our React components.
> 
> Sorry for flagging this inappropriately, and thanks so much for your help!

I am having the same issue, can you described what caused it in more detail, or is it too specific to the app you were working on.
