### ISSUE TITLE
React Native 0.58 crashing from node core module reference in dependency

### ISSUE THREAD

**Issue by ryanmagoon** [storybooks/storybook#5378]
**Describe the bug**
It looks like `safe-eval`, a module required by `telejson`, requires `vm`, which is a core node module and can't be used in the metro bundler without some kind of polyfill, so maybe a different library should be used there or telejson should be modified

**To Reproduce**
set up a new storybook project in a brand new react native project
`npx -p @storybook/cli@next sb init`

**Expected behavior**
the default ui setup to be there and working

**Screenshots**
<img width="427" alt="screen shot 2019-01-27 at 12 08 36 am" src="https://user-images.githubusercontent.com/5327290/51796905-6f89fa00-21c8-11e9-8de4-ee201884f38f.png">

**Code snippets**
The offending file:
<img width="894" alt="screen shot 2019-01-27 at 12 16 39 am" src="https://user-images.githubusercontent.com/5327290/51796926-deffe980-21c8-11e9-967e-42d6562482bd.png">

**System:**
 - OS: MacOS
 - Device: MacBook Pro 2015
 - Framework: react-native
 - Version: 5.0.0-alpha.9

**Comment by shilman** [comment]
cc @Gongreg

**Comment by nemonweb** [comment]
Because of this bug it is not possible to use storybook 5.x with react native. Fix it please

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.12 that addresses this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
We’ve released a brand new `@storybook/react-native` with a bunch of core improvements. It’s available in the latest `5.1-alpha` on `next` and has been verified by several RN users on their existing apps. It should fix a bunch of compatibility issues, especially if you’re using the web server feature. Please give it a try and comment here if it fixes your problem. Migration instructions available here: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-native-server

@ryanmagoon @tsvetan-ganev @Aleksefo @hugofovargue @nemonweb @FLGMwt @thamo01 @loic-lopez @stale

**Comment by FLGMwt** [comment]
Thanks for the update! Will try it out in the next few days : )

**Comment by nemonweb** [comment]
@shilman `5.1-alpha` works fine. Thanks

**Comment by shilman** [comment]
That was fast @FLGMwt! Technically "in the next few days" I suppose 😆 

Hmm.. seems like it's working for @nemonweb 

Sometimes the channel can be null if there are multiple versions of things installed. Can you try removing your node_modules completely and possibly even yarn.lock if that doesn't work and see if that solves the problem?

**Comment by shilman** [comment]
Closing. Please comment if you're still seeing this problem on recent alphas
