### ISSUE TITLE
@storybook/addon-knobs: color selector doesn't work in Firefox

### ISSUE THREAD

**Issue by dfilatov** [storybooks/storybook#5390]
**Describe the bug**
Color control doesn't work in Firefox at all. Popup opens but click to control just closes it, color isn't changed.

**To Reproduce**
Try to change color with corresponding control in Firefox.

**Expected behavior**
Color is changed.

**Actual behavior**
Nothing happens.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: Firefox
 - Framework: react
 - Addons: knobs
 - Version: 4.1.7

**Comment by Eelsie** [comment]
I have exactly the same issue with storybook for vue, addon-knobs version 4.0.0.

**Comment by dfilatov** [comment]
The problem is that `<Popover/>` is put inside `<button>`. I've tried to extract it from button and everything starts working.

**Comment by dfilatov** [comment]
The bug is still reproduced

**Comment by shilman** [comment]
@dfilatov Can you make a PR with the fix?
