### ISSUE TITLE
notes addons will delete the character '\n' in the text passed by the notes option

### ISSUE THREAD

**Issue by kobe990** [storybooks/storybook#5392]
**Describe the bug**
when I pass a text with '\n' or  '\r\n', the addon-notes will remove the '\n', that will result in some bad results on the final page. This issue happen in version 4. But the addon-notes of version 3 is good. 

**To Reproduce**
1. storiesOf.add('module1', ()=> component, { notes: 'test /n test' }) or withNotes({ text:  'test /n test' })
2. Install the add-notes of version4. the notes will show like this: 
```
test test
```
Without newline between the test words.
3. If I install version 3, everything is good. will show like this: 
 ```
test
test
```
So I think the the addon-notes of version 4 will remove the character '\n'. Could you please recover this?

**Additional context**

**Comment by Keraito** [comment]
Hey @kobe990, I tried this in one of the kitchen sinks stories on `master` branch, which is on `v4.1.11`, and it works there. Which versions of Storybook and the notes addon are you using exactly?

**Comment by kobe990** [comment]
I use @storybook/vue v4.11.1 and @storybook/addon-notes v4.11.1 . finally I use @storybook/addon-notes v3.4.6 to solve this issue....

**Comment by Keraito** [comment]
Hey @kobe990 	could you share your work or a small reproduction that displays the bug?
