### ISSUE TITLE
HTML storybook doesn't build since 4.1.11

### ISSUE THREAD

**Issue by tamlyn** [storybooks/storybook#5401]
**Describe the bug**
I'm using `@storybook/html` in a server-side project which needs to generate some HTML templates. It works fine on 4.1.9 and before but on upgrading to 4.1.11 `start-storybook` stalls before showing the pink box and "Storybook started" message. When loading it in the browser it shows a generic `Cannot GET /` message. `build-storybook` also fails but in a different way with the message 

```
ERR! => Failed to build the manager
ERR! Module not found: Error: Can't resolve 'react-modal' in '/Users/tamlyn/projects/reason/symphony-rfq/node_modules/@storybook/html/node_modules/@storybook/ui/dist/modules/ui'
(node:82208) UnhandledPromiseRejectionWarning: ModuleNotFoundError: Module not found: Error: Can't resolve 'react-modal' in '/Users/tamlyn/projects/reason/symphony-rfq/node_modules/@storybook/html/node_modules/@storybook/ui/dist/modules/ui'
```

**To Reproduce**
1. Run `start-storybook -c .storybook`
2. Storybook does not successfully compile

(Sorry, these are not very useful repro steps, I can try and make a separate repo to demo the issue if necessary.)

**Expected behavior**
Storybook compiles

**System:**
 - OS: MacOS
 - Node: 8.15.0
 - Device: n/a
 - Browser: n/a
 - Framework: n/a
 - Addons: n/a
 - Version: 4.1.11

**Additional context**
The package is in a monorepo where some packages are using Babel (7) but this package is plain, untranspiled ES2018.

**Comment by Haaruun-I** [comment]
From the error message it looks like you don't have react-modal instated, try:
` npm install --save react-modal `

**Comment by tamlyn** [comment]
`react-modal` is installed at `node_modules/@storybook/ui/node_modules/react-modal`. If I forcibly install it into the root of the workspace and try a build again, I get a similar error about `react-fuzzy`. 

However that did lead me to discover that I had `@storybook/ui` in two places in my `node_modules`. Deleting `node_modules` and reinstalling seems to have fixed it. 

Thanks for encouraging me down the right path 🙂

**Comment by Haaruun-I** [comment]
No problem!
