### ISSUE TITLE
[addon-options] resets UI on page/hot reload

### ISSUE THREAD

**Issue by thebuilder** [storybooks/storybook#5411]
**Describe the bug**
After adding `@storybook/addon-options`, the UI will reset the state (and query params) to the default whenever the page is reloaded. This resets *Fullscreen*, *Addon panel*, *Stories Panel*, etc.

**To Reproduce**
1. Go to [Storybook Official](https://storybooks-official.netlify.com)
2. Toggle the Addon panel or enter fullscreen mode.
3. Reload page
4. The UI has been reset

**Expected behavior**
The UI state should not change, but should respect the current query parameters.

**Comment by shilman** [comment]
Ouch, this is a pretty bad bug. Note that we're deprecating `addon-options` in v5, which is currently in RC.

**Comment by thebuilder** [comment]
So this issue seems to have been fixed with the the 5.0 release. 👍
