### ISSUE TITLE
React-Native Storybook Issue regarding loader to handle a file type.

### ISSUE THREAD

**Issue by astha-nimblechapps** [storybooks/storybook#5412]
**Describe the bug**

I have use Storybook + TypeScript + React-Native . getting issue with find appropriate loader to load the react-native component. "You may need an appropriate loader to handle this file type". I tried each an every loader need for typescript such as 'ts-loader' , 'babel-loader' and 'awesome-typescript-loader'.

**Expected behavior**
I have to load my storybook on web and deploy on Heroku. 

webpack.config.js

```
> const path = require("path");
> 
> module.exports = (baseConfig, env, defaultConfig) => {
>   // Extend defaultConfig as you need.
> 
>   // For example, add typescript loader:
>   defaultConfig.module.rules.push({
>     test: /\.(ts|tsx)$/,
>     include: path.resolve(__dirname, "../src"),
>     loader: require.resolve("ts-loader")
>   });
>   defaultConfig.resolve.extensions.push(".ts", ".tsx");
> 
>   return defaultConfig;
> };
```

**Screenshots**
![screenshot 2019-01-30 at 2 54 30 pm](https://user-images.githubusercontent.com/45165629/51972012-8b2f2200-24a0-11e9-9875-027885c1e356.png)

![screenshot 2019-01-30 at 2 54 01 pm](https://user-images.githubusercontent.com/45165629/51972022-8e2a1280-24a0-11e9-8182-5d5fd360973a.png)

**Code snippets**

```

> import { configure } from '@storybook/react';
> const req = require.context('../storybook/stories', true, /.tsx$/);
> __webpack_public_path__ = "/stories/"
> function loadStories() {
>   req.keys().forEach(req);
> }
> 
> configure(loadStories, module);

```

**Comment by Gongreg** [comment]
Hello. I am not sure what exatly you are trying to achieve here. If you are using React Native then the only way to see the stories is through the simulator.

**Comment by astha-nimblechapps** [comment]
> Hello. I am not sure what exatly you are trying to achieve here. If you are using React Native then the only way to see the stories is through the simulator.

Yes but I need to run on web also like this link for reference [https://medium.com/@agent_hunt/storybook-setup-for-desiloed-development-with-react-native-ios-android-web-85b6d64fb1b4] so that I can deploy the storybook on heroku.
