### ISSUE TITLE
[v5] Keyboard shortcut and about screen UX

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5417]
**Describe the bug**
It's difficult to go back to the previous UI when you've entered the keyboard shortcut or about screen

**To Reproduce**
1. Go to keyboard shortcuts or about screen
2. Try to exit back to your previous route (via esc or close)
3. There's no way to do this except to navigate to a new story - which is not intuitive

**Expected behavior**
- Pressing esc should exit the keyboard shortcut and about screens 
- Both screens should have headers that include a close button

**Comment by tmeasday** [comment]
@domyen -- I think this is now fixed on `next`? Please re-open if not.
