### ISSUE TITLE
@addons-notes@5.0.0 - Notes do not appear on initial storybook load of default story

### ISSUE THREAD

**Issue by pgoforth** [storybooks/storybook#5418]
**Describe the bug**
When you initially run storybook, 'Notes' do not appear in the notes tab until you change to a different story.

**To Reproduce**
1. Create a storybook that has a story that utilizes the `addon-notes`
2. Make sure the story with notes is the default story that loads on startup
3. Run `start-storybook`
4. Open the storybook uri in your browser and click on the 'Notes' tab

**Expected behavior**
Notes for a particular story should appear when storybook default story is initially loaded.

**System:**
 - OS: MacOS
 - Device: Macbook Pro
 - Browser: Chrome
 - Framework: React
 - Addons: notes
 - Version: 5.0.0-alpha.10

**Additional context**
I have noticed that this same problem occurs with other addons that update on the `STORY_CHANGED` event, and that this same issue occurs in those addons as well. Likely because that event does not dispatch on initial load of a story.

**Comment by CodeByAlex** [comment]
+1

**Comment by pgoforth** [comment]
@CodeByAlex 
Can you verify that the PR fixed your issue? If so I'm going to close the issue.

**Comment by CodeByAlex** [comment]
@pgoforth I am still having the issue using 5.0.0-beta.1. Is there a different version you are thinking of, please let me know. as of this version, the notes do not load on default and they do not change as expected when switching between components. 

Ex. If I am on component A and I go to the notes section, eventually(with some clicking around) the notes will populate. Once populated, if you go to component B's notes section, the notes from component A will still be showing.

**Comment by pgoforth** [comment]
@CodeByAlex 
The PR has been merged into the `next` branch. There has not been a beta released with the fix yet. It will likely go out in the next beta build.

**Comment by CodeByAlex** [comment]
@pgoforth , The fix resolved the issues I was seeing. Thanks!
