### ISSUE TITLE
[v5] Fix or remove jerky UI transitions when toggling addon panel

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5420]
**Describe the bug**
When toggling addon panel there's a jerky transition which causes the preview window to "hop".

**To Reproduce**
1. Press [s] to hide the addons
2. Press [s] to reveal the addons
3. See the jerky transition on reveal

![screen recording 2019-01-30 at 11 38 am](https://user-images.githubusercontent.com/263385/51996880-a3447880-2483-11e9-9c3e-57e56c96a076.gif)

**Comment by tmeasday** [comment]
@ndelangen fixed this
