### ISSUE TITLE
[v5] PropType check fails for `viewMode`

### ISSUE THREAD

**Issue by Vivalldi** [storybooks/storybook#5422]
**Describe the bug**
```
Warning: Failed prop type: The prop `viewMode` is marked as required in `<<anonymous>>`, but its value is `undefined`.
    in Unknown (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
```

**To Reproduce**
Any storybook in v5 produces this for me

**Expected behavior**
For all proptypes to pass

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Addons: seemingly n/a
 - Version: 5.0.0-alpha.10

**Comment by alflennik** [comment]
If you're updating an existing storybook, try running `npm install --save  @emotion/core` to upgrade from v0 to v10.

**Comment by Vivalldi** [comment]
Started from scratch and installed `@emotion/core`. Ended up with the same results.

**Comment by danielbuechele** [comment]
Upgrading to `@emotion/core@10.0.7` fixed it for me using beta2. beta1 only worked with `@emotion/core@10.0.6` though. Make sure to explicitly install this the exact version.

**Comment by Vivalldi** [comment]
Still problematic with `@emotion/core@10.0.7` and `@storybook/react@5.0.0-beta.2`

**Comment by Vivalldi** [comment]
Seems to happen only when loading without a `path` arg in the query string

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-beta.4 containing PR #5601 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
