### ISSUE TITLE
@storybook/angular does not autoprefix as angular-cli

### ISSUE THREAD

**Issue by alexan** [storybooks/storybook#5436]
**Describe the bug**
@storybook/angular does not respect .browserlist or any other way described in [angualr story autoprexier](https://github.com/angular/angular-cli/wiki/stories-autoprefixer)

**To Reproduce**
1. generate angular projekt: https://storybook.js.org/basics/guide-angular/
2. add .browserslistrc to root (see code snippet for example)
3. create component + story with css property that should be autoprefixed (e.g. apperance: none, display: flex, )
4. start storybook

**Expected behavior**
the generated css with storybook should contain prefixed css properties

**Screenshots**
![bildschirmfoto 2019-01-31 um 09 49 58](https://user-images.githubusercontent.com/563746/52042496-a603a400-253d-11e9-9507-369c1358f700.png)

with work around:
![bildschirmfoto 2019-01-31 um 09 51 48](https://user-images.githubusercontent.com/563746/52042604-dd725080-253d-11e9-9e4e-2472fa6e635e.png)

**Code snippets**
story
```
import { moduleMetadata, storiesOf } from '@storybook/angular';
import { CheckboxComponent } from './checkbox.component';

const stories = storiesOf('Input/Checkbox', module)
  .addDecorator(
    moduleMetadata({
      entryComponents: [CheckboxComponent],
      declarations: [CheckboxComponent],
    })
  );

stories.add('unchecked', () => ({
  template: `<input prefix-checkbox type="checkbox">`
}));
```
component:
```
@Component({
  selector: 'input[prefix-checkbox]',
  templat: '<ng-content></ng-content>,
  styleUrls: ['./checkbox.component.scss']
})
export class CheckboxComponent {
}
```
style:
```
:host {
  appearance: none;
}
```
.browserslistrc
```
### Supported Browsers
last 2 version
IE >= 10
```

generated css should be:
```
-webkit-appearance: none;
-moz-appearance: none;
appearance: none;
```
**System:**
 - Framework: [e.g. react, vue, angular]
 - Addons: [@storybook/angular]
 - Version: [4.1.11]

**Additional context**
at the moment I am useing a project webpack config to work around this problem:
```
module.exports = baseConfig => {
  let cssRule = baseConfig.module.rules.find(
    rule => rule.test.toString() === /\.s(c|a)ss$/.toString()
  );
  if (!cssRule) {
    throw new Error('css rule for modification not found');
  }
  cssRule.use = [
    { loader: require.resolve('raw-loader') },
    { loader: require.resolve('postcss-loader'),
      options: {
        plugins: [
          require('autoprefixer')
        ]
      }
    },
    { loader: require.resolve('sass-loader') },
  ];

  return baseConfig;
};
```

**Comment by alexan** [comment]
I will create a merge request modifying https://github.com/storybooks/storybook/blob/4da246bbe9413510b48d1ab8b9faf4fae4656d92/app/angular/src/server/framework-preset-angular.js
to add this behavior to @storybook/angular

**Comment by ifthenelse** [comment]
Have you tried adding modules to an extended Storybook Webpack configuration from the project `package.json` and requiring them via relative path? This works to me:

`npm -i  -D css-loader postcss-loader autoprefixer`
or
`yarn add css-loader postcss-loader autoprefixer --dev`

```js
const path = require("path");

module.exports = (baseConfig, env, defaultConfig) => {

  // Add custom css-loader, postcss-loader and postcss autoprefixer plugin
  defaultConfig.module.rules.push({
    test: /\styles.css$/,
    include: path.resolve(__dirname, "../src"),
    use: [
      require.resolve('style-loader'),
      require.resolve("../node_modules/css-loader"),
      {
        loader: require.resolve("../node_modules/postcss-loader"),
        options: {
          plugins: [require.resolve("../node_modules/autoprefixer")],
        }
      },
    ]
  });
```

**Comment by anoopsinghbayes** [comment]
would this feature help in fixing angular related issues?
https://github.com/storybooks/storybook/issues/3995

**Comment by alexan** [comment]
I don't think so

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.6 containing PR #5612 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
