### ISSUE TITLE
Webpack stops when adding custom addon

### ISSUE THREAD

**Issue by seokju-na** [storybooks/storybook#5462]
**Describe the bug**
Hello! first of all, thanks for making good open source.

I'm using storybook with React and Typescript. There was a problem creating a custom add-on. After write custom add-on, I run storybook. 

The results on the console were successful in building the webpack but stopped at that state, and WebpackDevServer not worked.

**Screenshots**
<img width="1026" alt="2019-02-03 5 28 56" src="https://user-images.githubusercontent.com/13250888/52174582-6d7ff680-27d9-11e9-8e5e-187182e55bd9.png">

**Code snippets**

Run cli command: `npx start-storybook -p 9001 -c stories/`

stories/config.js:
```typescript
import { withInfo } from '@storybook/addon-info';
import { withOptions } from '@storybook/addon-options';
import { addDecorator, configure } from '@storybook/react';
import '../src/styles.scss';


// Global addons
addDecorator(
    withInfo({
        inline: true,
        source: false,
    }),
);

addDecorator(
    withOptions({
        name: 'Geek\'s Log UI',
    }),
);


// Imports stories tsx files
// const req = require.context('./', true, /\.story.tsx$/);

function loadStories() {
    // req.keys().forEach(fileName => req(fileName));
    require('./ui/button.story');
}

configure(loadStories, module);
```

stories/webpack.config.js:
```javascript
const path = require('path');


module.exports = (baseConfig, env, config) => {
    config.module.rules.push({
        test: /\.(ts|tsx)$/,
        use: [
            {
                loader: require.resolve('awesome-typescript-loader'),
                options: {
                    configFileName: path.resolve(__dirname, '../tsconfig.story.json'),
                },
            }, {
                loader: require.resolve('react-docgen-typescript-loader'),
            },
        ],
    });

    // config.module.rules.push({
    //     test: /\.scss$/,
    //     loaders: ['style-loader', 'css-loader', 'sass-loader'],
    //     include: path.resolve(__dirname, '../src'),
    // });

    config.resolve.extensions.push('.ts', '.tsx', '.js', '.jsx');

    return config;
};
```

stories/addons.js:
```javascript
import '@storybook/addon-actions/register';
import '@storybook/addon-options/register';
import '../src/addons/theme-addon';
```

src/addons/theme-addon.tsx:
```typescript
import addons, { AddonStore } from '@storybook/addons';
import * as React from 'react';


// interface IPanelProps {
//     readonly channel: Channel;
//     readonly active?: boolean;
// }
//
//
// class Panel extends React.Component<IPanelProps> {
//     render() {
//         if (!this.props.active) {
//             return null;
//         }
//
//         const panelStyle = {
//             width: '100%',
//             height: '100%',
//             overflow: 'auto',
//         };
//
//         return (
//             <div style={panelStyle}>
//                 Panel
//             </div>
//         );
//     }
// }


addons.register('THEME_ADDON', (store: AddonStore) => {
    const channel = store.getChannel();

    store.addPanel('THEME_ADDON/PANEL', {
        title: 'Theming',
        render: () => <div>Hello</div>,
    });
});
```

**System:**
 - OS: macOS
 - Device: Macbook Pro 13-inch, Early 2015
 - Browser:
 - Framework: react
 - Addons:
 - Version: @storybook/react@^4.1.11

**Comment by mrmckeb** [comment]
Hi @seokju-na, to confirm, this works correctly when you're not using your custom add-on?

Are you able to share a test repository? Thanks!

**Comment by seokju-na** [comment]
Hi @mrmckeb !

- Yes. When I removed custom add-on, it works correctly.
- I worked in my [repository](https://github.com/geeks-log/geeks-log-web). You can see storybook configurations in `stories/`.

**Comment by martinshing** [comment]
Hi @seokju-na ,

I faced a similar issue with one of our custom addons and spent some time debugging it and it turns out there was a webpack error importing a css file. I'm not sure if the manager portion of storybook is using a separate webpack config but commenting out the line fixed it for us and we have temporarily moved the css into the manager-head.html file as an interim fix.

**Comment by jcampalo** [comment]
I face the same issue also, in my case I only use `ts-loader`.

What I've discovered for now is that some options from `ts-loader` caused this bug. 

`
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const ForkTsCheckerNotifierWebpackPlugin = require('fork-ts-checker-notifier-webpack-plugin');
const path = require('path');

module.exports = (baseConfig, env) => {
  const config = { ...baseConfig };
  const tsconfig = path.resolve(__dirname, './tsconfig.json');
  const include = [path.resolve(__dirname, '../src'), path.resolve(__dirname, '.')];
  const exclude = [path.resolve(__dirname, '../src/**/__tests__')];

  config.module.rules.push({
    test: /\.tsx$/,
    include,
    exclude,
    use: [
      'cache-loader',
      {
        loader: 'ts-loader',
        options: {
          configFile: tsconfig,
          onlyCompileBundledFiles: true,
          transpileOnly: true,
          compilerOptions: {
            declaration: false,
          },
        },
      },
      'react-docgen-typescript-loader',
    ],
  });

  config.resolve.extensions.push('.tsx');
  config.module.rules[0].include = include;
  config.module.rules[0].exclude = exclude;

  if (env === 'DEVELOPMENT') {
    config.plugins.push(
      new ForkTsCheckerWebpackPlugin({
        tsconfig,
      }),
    );
    config.plugins.push(
      new ForkTsCheckerNotifierWebpackPlugin({ title: 'Storybook', skipSuccessful: true }),
    );
    config.watchOptions = { ignored: exclude };
  }

  return baseConfig;
};
`
If I remove configFile, onlyCompileBundledFiles and transpileOnly, it works.

**Comment by creaux** [comment]
Using babel with typescript-preset. Same issue.
