### ISSUE TITLE
Support for testing storybook breaks on each code commit

### ISSUE THREAD

**Issue by mcreations** [storybooks/storybook#547]
Hi,
We heavily use React storybook for building React components in our project. There are multiple teams working on the project. We build stateless components and use props to pass values to the components. One of the main issues we face is that there are unintentional storybook breaks when one team changes data structures without changing the storybook tests. It would be better if we can add a pre-commit hook where we can test whether there are any storybook breaks before any commit. 
We tried out storybook snapshots but it didn't serve our purpose. Any future ideas to implement a feature or addon for this or is there a method already to do this?
Thanks

**Comment by evgenykochetkov** [comment]
Hi! I encountered a similar problem and would like to know what kind of solution you came up with.
Is [specifications addon](https://github.com/mthuret/storybook-addon-specifications#use-your-stories-with-a-test-runner) a good fit for this?

**Comment by tmeasday** [comment]
@mcreations -- can I ask for more information? What is the issue with storyshots?

**Comment by tmeasday** [comment]
Is this problem solved by #1034?

**Comment by mcreations** [comment]
@tmeasday, Thanks for this solution. This seems to be what I was looking for. Let me try this out and get back to you if I come across any issues. Thanks again for your support.
