### ISSUE TITLE
@storybook/angular does not work with vanilla CSS

### ISSUE THREAD

**Issue by Pringels** [storybooks/storybook#5486]
**Describe the bug**
When installing and running storybook in a freshly generated Angular 7 project (created by angular CLI with CSS as the stylesheet format) I receive the following error when attempting to view my component in storybook UI:

`Expected 'styles' to be an array of strings.`

**To Reproduce**
1. Follow the installation steps exactly as described here: https://storybook.js.org/basics/guide-angular/
_NOTE: Be sure to select CSS as your preferred stylesheet format during the angular CLI app installation process_
2. Run storybook and view the `My Button` story.

**Expected behavior**
I should see my component in storybook with styling applied.

**Code snippets**
`./src/app/my-button/my-button.component.ts`
```ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-my-button',
  templateUrl: './my-button.component.html',
  styleUrls: ['./my-button.component.css']
})
export class MyButtonComponent implements OnInit {
  @Input()
  text: string;

  constructor() { }
  ngOnInit() {}
}
```
`./src/app/my-button/my-button.component.css`
```css
button {
    border: 1px solid red;
}
```
`./src/app/my-button/my-button.component.html`
```html
<button>
  {{ text }}
</button>
```
`./src/stories/index.ts`
```ts
import { storiesOf } from '@storybook/angular';

import { MyButtonComponent } from '../app/my-button/my-button.component';

storiesOf('My Button', module)
  .add('with some emoji', () => ({
    component: MyButtonComponent,
    props: {
      text: '😀 😎 👍 💯',
    },
  }));
```
**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: angular 7.2.3
 - Version: 4.1.11

**Additional context**
I have not modified my angular or storybook configurations. I simply installed storybook as described in the documentation.

I can get storybook to behave as expected under the following conditions:
- I remove the "styleUrls" property on my component. 
- I select the "Sass" stylesheet format during the angular CLI app installation process.

**Comment by shilman** [comment]
Related #5239

**Comment by climberger** [comment]
I have the same problem:

To reproduce:

- I created an Angular project with Angular CLI.
- Then I added storybook to the project with command `npx -p @storybook/cli sb init`
- I created my own component to test it with storybook.

I can start storybook with `npm run storybook`
When I click on my component story in storybook, I get following error:

`Unhandled Promise rejection: Expected 'styles' to be an array of strings.`

**Comment by shilman** [comment]
@climberger Why does the screen capture say `v4.1.13` if you've upgraded to `5.0.0-rc.7`?

**Comment by climberger** [comment]
Tja screen capture is from the former version, where it did not work.
With version 5, as I described, it works and the error does not occur anymore.

**Comment by shilman** [comment]
@climberger Sorry I missed that! Glad to hear it's sorted!
