### ISSUE TITLE
silent console.warn() causing @@iterator problems on React Native

### ISSUE THREAD

**Issue by fssantos** [storybooks/storybook#5499]
**only happening on REACT NATIVE**

**Describe the bug**
Somehow console.warn() was causing this problem when inside a render() component method:

> TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === "function'" ? Symbol.iterator : "@@iterator"]()')

**To Reproduce**
1. Go to any component and put a console.warn() on it's render;
2. Click on it's preview on navigator;
3. See error

**Expected behavior**
Just appear a console.warn normally;

**System:**
 - OS: [UBUNTU]
 - Device: [Android Emulator]
 - Browser: [NA]
 - Framework: [react native]
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0]

**Additional context**
It was completly a silent error since I forgot to place a key on a .map() function and my component was warning the key missing.

Anyone facing the same issue? Maybe it's related to #5291

**Comment by shilman** [comment]
Did you try the workaround referenced in #5291?

**Comment by shilman** [comment]
Closing as a dupe to #5291
