### ISSUE TITLE
Exports missing from `addon-viewport`

### ISSUE THREAD

**Issue by garrettmaring** [storybooks/storybook#5500]
**Describe the bug**
It seems as though a `withViewport` and `configureViewport` functions are not exported from the `addon-viewport` module.

**To Reproduce**
1. Follow [documenation for customizing viewport](https://www.npmjs.com/package/@storybook/addon-viewport#use-custom-set-of-devices)

**Expected behavior**
Viewports can be customized, default viewport can be set, and individual story can have viewport decorators.

**Code snippets**
```
// .storybook/config.js
import { configureViewport } from '@storybook/addon-viewport';
 
configureViewport({
  defaultViewport: 'iphone6'
});

// This produces "Uncaught TypeError: Object(...) is not a function"
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Addons: viewport
 - Version: `@storybook/react: 4.0.0-alpha.3`

**Comment by shilman** [comment]
@garrettmaring This is working for me in Storybook 4.x (it appears to have broken in SB5). I'm wondering if you're running into this issue? https://github.com/storybooks/storybook/issues/4796
