### ISSUE TITLE
Nunjucks template?

### ISSUE THREAD

**Issue by kkashou** [storybooks/storybook#5506]
I am currently using storybook html and got everything I need going except one thing, that is the support for importing a nunjucks partial. Is there a way to do that? If so what’s the best approach?

I see some people using storybook set up with vue template option but I feel like hack approach.

Let me know what you think.

Thank you!

**Comment by kkashou** [comment]
Decided to move away form storyboard since I found a different solution.

**Comment by stockmind** [comment]
Sorry for the hijack, but I stumbled upon this issue, what alternative solution did you found?

**Comment by shilman** [comment]
could you add nunjucks-loader to your webpack config?

https://github.com/at0g/nunjucks-loader

**Comment by radum** [comment]
main.js

```js
module.exports = {
	stories: [
		'../src/**/*.stories.mdx',
		'../src/**/*.stories.@(js|jsx|ts|tsx)'
	],
	addons: [
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		"@storybook/preset-scss"
	],
	webpackFinal: async (config, { configType }) => {
		// `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
		// You can change the configuration based on that.
		// 'PRODUCTION' is used when building the static version of storybook.

		// Make whatever fine-grained changes you need
		config.module.rules.push({
			test: /\.njk$/,
			use: [
				{
					loader: 'simple-nunjucks-loader',
					options: {}
				}
			]
		});

		// Return the altered config
		return config;
	}
};
```

test.stories.js

```
import { action } from '@storybook/addon-actions';

import Button from  'Button.njk';

export default {
	title: 'Design System/Atoms/Button',
	argTypes: {
		label: { control: 'text' }
	}
};

const Template = ({ onClick, label }) => {
	return Button({ label });
};

export const Text = Template.bind({});
Text.args = {
	label: 'Button',
	onClick: action('onClick')
};
```

Button.njk

```
{% macro Button(label='Button') %}
<button type="button" class="lta-btn">{{ label }}</button>
{% endmacro %}

{{ Button(label) }}
```

And that is it, this works.

**Comment by GreatState** [comment]
I would love to get this working. I wish there was an official starter or option for this when installing. I'm using the latest version of storybook and cannot get this to work. simple nunjucks loader won't work for me and not sure if this is due to webpack versions

![image](https://user-images.githubusercontent.com/35596657/141086990-7f873a6b-56fa-44a3-b843-328d5e1f3407.png)

I've swapped this out for nunjucks-html-loader

```
use: [
        'html-loader',
        {
          loader: 'nunjucks-html-loader',
          options: {
            // Other super important. This will be the base
            // directory in which webpack is going to find
            // the layout and any other file index.njk is calling.
            searchPaths: [...returnEntries('./src/templates/**')],
          },
        },
      ],
```

but i get this error when it loads

![image](https://user-images.githubusercontent.com/35596657/141091636-4a18161b-71bf-432f-95f9-9dd3cc0c9ac5.png)
