### ISSUE TITLE
Angular 7 assets images path

### ISSUE THREAD

**Issue by gogs85** [storybooks/storybook#5509]
Hi, I try to use to make components for icons, and icons is in assets /img folder.
` <svg>
  <use xlink:href="assets/img/icons.svg#customer"></use>
</svg>`
with ng serve this is working fine, but when use npm run storybook images is not show.
How I can include assets to use with storybook in Angular 7?

Thanks

**Comment by wunderkind2k1** [comment]
Hi @gogs85 anything new on that? Is your problem solved? I am asking as I have the problem. Storybook worked fine on ng-6 but after upgrading to 7 the asset path resolution is not working anymore i.e. images and styles are not found/ used.

**Comment by gogs85** [comment]
Hi, I solved the problem. Thanks.

**Comment by wunderkind2k1** [comment]
may I know how?

**Comment by anirudhvarma12** [comment]
@gogs85 , can you please share the solution? I am also running into the same issue.

**Comment by Draccoz** [comment]
@gogs85 Could you elaborate please? This issue seems to hit not just you, would be great to know how to fix that.

**Comment by mtuzinskiy** [comment]
@gogs85  same for me. Did you use webpack's copy?

**Comment by gogs85** [comment]
I didn't solve in ng-7, just move back go ng-6. This is separate project to display components. For that for us it was not problem to stay on ng-6. Sorry for late answer...

**Comment by NavyJot** [comment]
I am also facing same issue

**Comment by velval** [comment]
You can sue the staticDirs config under your .storybook/main.tx config file

`staticDirs: ['../public', '../static'],`
