### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by titouancreach** [storybooks/storybook#5510]
**Describe the bug**
I just migrated from v5 alpha to v5 beta. Now I can see in the console: "ReferenceError: regeneratorRuntime is not defined". I've so added [babel-plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) to the list of my babel plugins but nothing changed (I think this include only the polyfill to my code and not to Storybook) .

**To Reproduce**
  - Storybook that work well in v5 alpha
  - Upgrade to v5 beta
  - Run Storybook
  - Blank page with error in the console

**Expected behavior**
Storybook that run

**Screenshots**
Should not be very usefull but here is the code that throw
![image](https://user-images.githubusercontent.com/3995719/52414066-8e9b5c80-2ae3-11e9-86a2-6a7c77e1e54f.png)

**System:**
 - OS: [Linux]
 - Device: [All]
 - Browser: [chrome]
 - Framework: [react]
 - Version: tested with: 5.0.0-beta.1 and 5.0.0-beta-3

Thanks for reading :)

**Comment by tmeasday** [comment]
Hi @titouancreach, any chance you could upload your code somewhere? 

The issue is in the ui code (ie not your code controlled by your babel config). The regenerator runtime should be part of the manager webpack config. Can you try with the latest beta (`beta.3`)?

**Comment by titouancreach** [comment]
Sure I'll try, if it doesn't work, I will do a repro repo!

**Comment by titouancreach** [comment]
`5.0.0-beta.3` doesn't fix this bug. I've created a minimal reproduction based on create-react-app [here](https://github.com/titouancreach/repro-storybook-5510)

**Comment by tmeasday** [comment]
🙏 @titouancreach 

You know it is interesting, I defaulted to installing via `yarn` and your repro worked fined. Then I saw you had a `package-lock.json`, installed via `npm`, and it failed. A bit of a hint I think 😉

**Comment by tmeasday** [comment]
Aha! I knew this would come to bite us! The issue is you have put in `^5.0.0-beta.3` in your `package.json` but a while back @shilman released a `5.0.0-debug.3` (which matches that specifier sadly).

If you change to an exact match (`5.0.0.beta.3`) it'll work fine.

Sorry about this!

**Comment by titouancreach** [comment]
Nice, I was wondering why storybook show "5.0.0-debug-3" in the console!  Thank :)

**Comment by juliankrispel** [comment]
I'm on `6.1.10` and I'm experiencing this issue :/
