### ISSUE TITLE
Refreshing page loses current story

### ISSUE THREAD

**Issue by gavmck** [storybooks/storybook#5511]
**Describe the bug**
Running 5.0.0-beta.1, I can navigate to a story successfully, but when I refresh the page, it shows the "No preview" view.

Url example: http://localhost:1337/?path=/story/templates-payment-direct-debit--default 

**To Reproduce**
1. Go to a story
2. Click on the browser refresh button
3. See the "No preview" view

**Expected behavior**
The story should load.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Browser: Chrome 70
 - Framework: Angular 7
 - Version: 5.0.0-beta.1

**Additional context**
Local development, have not tried in a compiled static storybook.

**Comment by Vivalldi** [comment]
I'm personally not seeing this problem in 5.0.0-beta.2

**Comment by gavmck** [comment]
Confirmed, this is fixed in 5.0.0-beta.2
Yay!

**Comment by eranimo** [comment]
I'm having this problem again in 6.2.5
