### ISSUE TITLE
Iframe.html view loses the url and updates to /

### ISSUE THREAD

**Issue by gavmck** [storybooks/storybook#5512]
**Describe the bug**
When ejecting from the storybook view and into the direct /iframe.html view, once it finishes loading, the browser url is set to the domain root so you can't refresh the page to see updates.

Start: http://localhost:1337/iframe.html?id=templates-payment-card--default
End: http://localhost:1337/

**To Reproduce**
1. Go to a story
2. Click on the little eject icon top right
3. Wait for the page to load
4. See the url has updated to /

**Expected behavior**
The url will persist so you can refresh the page to see changes whilst developing.

**System:**
* OS: MacOS
* Device: Macbook Pro 2017
* Browser: Chrome 70
* Framework: Angular 7
* Version: 5.0.0-beta.1

**Additional context**
Local development, have not tried in a compiled static storybook.

**Comment by leoyli** [comment]
This can not reproduced in my case.

**System:**

* OS: MacOS
* Device: Macbook Air 2013-mid
* Browser: Chrome 72
* Framework: React 16
* Version: 5.0.0-beta.1

**Comment by gavmck** [comment]
You're right! It's me!

I needed to add
```
{ path: 'iframe.html', component: BrComponent }
```
to the RouterModule declaration in the story imports or it detects and invalid rout and redirects to /.

Thanks for investigating, it put me on the right track.
