### ISSUE TITLE
THEME option missing? Storybook docs say theme is an option, is it gone?

### ISSUE THREAD

**Issue by alienfacepalm** [storybooks/storybook#5515]
`addDecorator(
  withOptions({
    name: 'Storybook',
    theme: themes.dark
  })
)`

Error says `theme` does not exist as an option

**Comment by Keraito** [comment]
Hey @alienfacepalm , what versions of storybook and the options addon are you using? Can you also try with `addParameters` instead of `addDecorator` as in https://github.com/storybooks/storybook/blob/next/examples/official-storybook/config.js#L49?

**Comment by alienfacepalm** [comment]
addParameters compiles with no issue, doesn't appear have any effect from my config, `info` section works, none of the `options` are applied, but that's another issue. 

```addParameters({
  options: {
    name: 'NowSecure UI 1.0',
    hierarchySeparator: /\/|\./,
    hierarchyRootSeparator: '|',
    theme: dark
  },
  info: {
    inline: true,
    styles: {
      header: {
        h1: {
          color: '#002e48'
        }
      }
    }
  }
})
```
