### ISSUE TITLE
Keyboard shortcuts order is not the same as treeview order

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#5518]
**Describe the bug**
A bit of an edge case. When you create a new story for a component, it appears in the right place in treeview, but is treated as if it is at the very end as far as keyboard shortcuts are concerned.

## Reproduction (via same kind in two files, kind of weird, but easy to repro):

1. Create three story files, `A`, `B` and `C`. 
2. Make `A` + `C`'s stories both apply to the same kind.
3. In the UI `A`+`C`'s stories will be grouped.
4. However, keyboard shortcuts will apply in the order the stories are added; ie `A` -> `B` -> `C`

## Reproduction (via HMR, more common):

1. Browse to a story in official storybook, e.g. "Placeholder > twoChildren"
2. Edit the story file, export a third story
3. Press "option + ->" (i.e. browse to next story). Notice it takes you to the next component
4. Click on the new story within the Placeholder.
5. Press "option + ->" (i.e. browse to next story). Notice nothing happens (it is treated as the last story)
6. Press "option + <-" (i.e. browse to prev story). Notice the very last story in the storybook is opened.

**Comment by tmeasday** [comment]
This is way better now. One remaining issue (documented above)

**Comment by tmeasday** [comment]
@ndelangen I think you are on top of this stuff but I am happy to take a look if you like.

**Comment by tmeasday** [comment]
Ok the reason for this is the implementation of the `setStories` function inside `core/stories.js`

What it does is take a datastructure of the form

```js
{
  id1: story1,
  id2: story2,
}
```

And produces something like:

```js
{
   groupId1: {...., children: ['groupId2'] },
   groupId2: {...., children: ['storyId1'] },
   storyId1: story1
   ...
}
```

The problem is that if a story is added "out of order" (via either of the mechanisms described in the repros above) you end up with something like:

```js
{
   groupId1: {...., children: ['groupId2'] },
   groupId2: {...., children: ['storyId1', 'storyId3'] },
   storyId1: story1
   groupId3: {...., children: ['groupId4'] },
   ...,
   storyId3: story3
}
```

So the children of all groups are ordered as you might expect. And the groups are ordered as you might expect (this data is used to drive the treeview).

However the order of the top-level story keys in that data structure is different.

**Comment by tmeasday** [comment]
=> https://github.com/storybooks/storybook/pull/5805

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.8 containing PR #5805 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
