### ISSUE TITLE
Webpack error on static build

### ISSUE THREAD

**Issue by klaidman** [storybooks/storybook#5526]
**Describe the bug**
Webpack loader error when building a static site using `build-storybook,` with default setup:

```
./stories/index.stories.js 9:55
Module parse failed: Unexpected token (9:55)
You may need an appropriate loader to handle this file type.
| import { Button, Welcome } from '@storybook/react/demo';
```

I have tried tweaking webpack.config.js in .storybook, but can't figure out the correct settings that will get this to build correctly. Thanks for any assistance with this.

**To Reproduce**
1. Fresh repo (cloned from react-boilerplate, as per quick start instructions)
2. `npx -p @storybook/cli sb init`
5. `npm run build-storybook`

**Expected behavior**
Storybook static site builds correctly.
`npm run storybook ` works fine locally, but cannot build a static site.
Attempting to deploy to gh-pages using `storybook-deployer` has the same error (deploys successfully, but storybook is broken).

**System:**
- OS: Windows 7
- NodeJS 10.15.0
- Storybook 4.1.11 
- React 16.6.0
- Webpack 4.23.1

**Comment by worc** [comment]
i'm getting a very similar issue when just running storybook@5.1.1:

```
Module parse failed: Unexpected keyword 'var' (4:23)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
```

the default storybook webpack config seems to be falling over on function components.

**Comment by diego06884** [comment]
@worc I am getting the same error. Were you able to fix it on your end?

**Comment by Alphavader** [comment]
same here..
