### ISSUE TITLE
storybook won't start with eslint-loader if failOnError is false with error present

### ISSUE THREAD

**Issue by sowhatdoido** [storybooks/storybook#5528]
**Describe the bug**
If storybook is put into full-control mode, and eslint-loader is added without the option `failOnError: true`, storybook is unable to start up if there is an existing eslint error. This feels a little backwards because failOnError is set to false, so the build should continue.

**To Reproduce**
Add `webpack.config.js` to your `.storybook` folder with the following options:
```
const path = require("path");
module.exports = (baseConfig, env, defaultConfig) => {
  defaultConfig.module.rules.unshift({
    test: /\.(js|mjs|jsx)$/,
    enforce: 'pre',
    loaders: [{
      loader: require.resolve('eslint-loader'),
      options: {
        failOnError: false,
      },
    }],
    include: path.resolve(__dirname, '../src'),
  });

  return defaultConfig;
};
```

**Expected behavior**
When starting up the app, you expect to see a working storybook instance in your browser, as well as the following in your terminal:
![image](https://user-images.githubusercontent.com/1973601/52514127-253f4a80-2bc4-11e9-85fb-f957779b5ae6.png)

However if there is an eslint error present, storybook started prompt never occurs and the page is inaccessible:
![image](https://user-images.githubusercontent.com/1973601/52514378-fd50e680-2bc5-11e9-8dd1-549404a97364.png)

![image](https://user-images.githubusercontent.com/1973601/52514164-5f105100-2bc4-11e9-977c-b9e50a8f75b7.png)

**Additional Information**
I'm using storybook with create-react-app. Here are my dependencies:
```
    "@babel/core": "^7.2.2",
    "@storybook/react": "^4.1.11",
    "babel-loader": "^8.0.5",
    "node-sass": "^4.9.4",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-scripts": "2.1.1",
    "react-testing-library": "^5.2.3"
```

**Comment by themre** [comment]
i'm having the same issue with 5.0.1. if an error occurs when starting, it won't rebuild fully and localhost is not accessible.
