### ISSUE TITLE
Failing to load config when doing unit tests with Jest (default config)

### ISSUE THREAD

**Issue by CrashyBang** [storybooks/storybook#5537]
**Describe the bug**

Storybooks fails fails to load/find `.storybooks`.

**To Reproduce**

Create new project with `vue-cli`.

Use [`vue-cli` plugin](https://github.com/storybooks/vue-cli-plugin-storybook) to add storybook to a fresh Vue project.

Follow instructions in the ['Getting Started'](https://www.learnstorybook.com/vue/en/simple-component/) guide on setting up 'Snapshot Testing' (with Storyshots plugin).

Run:
```
npm run test:unit
````
Get:
```
ENOENT: no such file or directory, lstat '/path/to/project/.storybook'
``` 

**Expected behavior**

Tests to run.

**Screenshots**

N/A.

**Code snippets**
If applicable, add code samples to help explain your problem.

N/A.

**System:**
 - OS: Ubuntu 18.10
 - Device: Desktop
 - Browser: Chrome
 - Framework: Vue
 - Addons: N/A.
 - Version: 
```
    "@storybook/addon-actions": "^4.1.0",
    "@storybook/addon-knobs": "^4.1.0",
    "@storybook/addon-links": "^4.1.0",
    "@storybook/addon-notes": "^4.1.0",
    "@storybook/addon-storyshots": "^4.1.11",
    "vue-cli-plugin-storybook": "^0.5.1",
```

**Additional context**

N/A.

**Comment by tmeasday** [comment]
Hi @CrashyBang - any chance you could upload what you have to github?

**Comment by tmeasday** [comment]
Or at least what your `scripts` section of `package.json` looks like?

**Comment by CrashyBang** [comment]
Hey @tmeasday,

Sure here is the `scripts` section:
```
"scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "storybook:build": "vue-cli-service storybook:build -c testing/config/storybook",
    "storybook:serve": "vue-cli-service storybook:serve --ci -p 8081 -c testing/config/storybook",
    "test:e2e": "vue-cli-service test:e2e",
    "test:unit": "vue-cli-service test:unit"
}
```

And here is my `jest.config.js` (tests are being run by jest as per tutorial):
```js
module.exports = {
  moduleFileExtensions: ["js", "jsx", "json", "vue"],
  transform: {
    "^.+\\.vue$": "vue-jest",
    ".+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$":
      "jest-transform-stub",
    "^.+\\.jsx?$": "babel-jest"
  },
  transformIgnorePatterns: ["/node_modules/(?!(@storybook/.*\\.vue$))"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1"
  },
  snapshotSerializers: ["jest-serializer-vue"],
  testMatch: [
    "**/testing/suites/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx)"
  ],
  testURL: "http://localhost/"
};
```

And here is my `babel.config.js` (had to make ES5 compliant to work with Cypress):
```js
module.exports = api => {
  // No ES6 https://github.com/cypress-io/cypress/issues/2945
  const test = {
    presets: ["@vue/app"]
  };

  if (api.env("test")) test.plugins = ["require-context-hook"];

  return test;
};
```

And for your reference the directory structure of `testing/`:
```
├── config
│   └── storybook
│       ├── addons.js
│       └── config.js
├── data
│   ├── charts.data.js
│   ├── collapsable-list.data.js
│   ├── event-drawer.data.js
│   └── graph.data.js
├── stories
│   ├── charts.stories.js
│   ├── collapsable-list.stories.js
│   ├── date-range.stories.js
│   ├── event-drawer.stories.js
│   ├── graph.stories.js
│   └── index.stories.js
└── suites
    ├── e2e
    │   ├── plugins
    │   │   └── index.js
    │   ├── specs
    │   │   └── test.js
    │   └── support
    │       ├── commands.js
    │       └── index.js
    └── unit
        ├── graph.spec.js
        └── storybook.spec.js
```

**Comment by CrashyBang** [comment]
Still experiencing this issue, have been unable to figure out the cause.

**Comment by CrashyBang** [comment]
Tried this in another project using the updated plugins:
```
"@storybook/addon-actions": "^5.0",
"@storybook/addon-knobs": "^5.0",
"@storybook/addon-links": "^5.0",
"@storybook/addon-notes": "^5.0",
"vue-cli-plugin-storybook": "^0.6.1",
```

I thought it may be related to runnning the project in a Docker container, but even running it locally (tried nuking and re-install `node_modules` as well) didn't appear to have any difference.

Cheers!

**Comment by tmeasday** [comment]
Hi @CrashyBang -- sorry I didn't see your messages above (?)

I think your issue here is you have put your storybook config in a non-standard location (`config/storybook`). Try passing `{ configPath: './config/storybook' }` to the `initStoryshots` function.

**Comment by CrashyBang** [comment]
Hey @tmeasday,

Yep that sorted it, I had to use `{ configPath: './testing/config/storybook' }` but now everything works accordingly.

Cheers!
