### ISSUE TITLE
[5.0.0] Mobile layout broken

### ISSUE THREAD

**Issue by mrsufgi** [storybooks/storybook#5544]
**Describe the bug**
When resizing the screen it turns white, console errors shows:

Uncaught TypeError: Cannot read property 'initialActive' of undefined
which lead to Mobile ctor.   (calling this.state = { active: options.initialActive }) options in undefined. 

**To Reproduce**
1. Go to Storybook
2. Resize to mobile view
3. App crash and needs a full refresh 

**Expected behavior**
change to mobile view successfully or just don't break everything :)  

**System:**
 - OS:MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome 
 - Framework:React  16.8.2
 - Version: 5.0.0.beta2

**Comment by leoyli** [comment]
I guess the core team haven't reach mobile version yet... still have some changes ongoing on the desktop from my understanding.

**Comment by tmeasday** [comment]
Fixed in https://github.com/storybooks/storybook/pull/5603
