### ISSUE TITLE
addon-ondevice-knobs does not support React Native >= 0.56 (requires dependency upgrade)

### ISSUE THREAD

**Issue by erikthedeveloper** [storybooks/storybook#5545]
**Describe the bug**

`@storybook/addon-ondevice-knobs` does not support React Native >= 0.56 due to its dependency on `react-native-modal-datetime-picker`. My Storybook in React Native is working great until attempting to introduce knobs. Attempting to use knobs results in this error:

```
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```

https://github.com/storybooks/storybook/blob/d9cd83c2d5e1d160effdc6f51d1dd19a279b5028/addons/ondevice-knobs/package.json#L28

This has been fixed/release in https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v6.0.0 see merged PR https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/171 and original reported issue https://github.com/react-native-community/react-native-modal/issues/178

Upgrading `react-native-modal-datetime-picker` to `6.0.0` should fix the problem.

**To Reproduce**
1. Attempt using addon-knobs with React Native >= 0.56. Follow instructions at:
    1. https://github.com/storybooks/storybook/tree/master/addons/knobs
    2. https://github.com/storybooks/storybook/tree/next/addons/ondevice-knobs

**Expected behavior**
App should build/run. Knobs should work.

**Screenshots:**
![image](https://user-images.githubusercontent.com/1240178/52564602-d8c15e00-2dc1-11e9-8968-c67cf6bd90ae.png)

**System:**
 - Framework: React Native
 - Addons: knobs, ondevice-knobs
 - Version: 4.1.11 (through to 5.x)

**Comment by Gongreg** [comment]
Hey @erikthedeveloper, there is https://github.com/storybooks/storybook/pull/4425 opened some time ago. Did you try out version 6 and it helped? It didn't break anything else? We could just update the dependency then.

**Comment by shilman** [comment]
Released a fix at https://github.com/storybooks/storybook/releases/tag/v4.1.14

Please give it a try! Closing this for now.
