### ISSUE TITLE
Prevent navigation in some stories?

### ISSUE THREAD

**Issue by ZebraFlesh** [storybooks/storybook#5563]
Is there a way prevent navigation in some stories? I have a language picker component (renders an HTML `<select>`) which sets `window.location` when an option is chosen. I'd like to prevent navigation in these stories, but not in others. I'm using react, but not react-router.

- @storybook/react 4.1.11
- react 16.7.0

**Comment by tmeasday** [comment]
Hey @ZebraFlesh,

I'm not sure there's an easy way without refactoring the component. I think it's good practice to do so anyway -- typically I would pass `onNavigate` or something as a prop to the component, then you can use an action to mock it out in Storybook.

If you need the component to be "self contained", you can export both a Pure version that uses `onNavigate` and a wrapper that sets `onNavigate` to `window.location = ...`. (If that makes sense)

**Comment by ZebraFlesh** [comment]
Yep, that makes sense. Thank you!
