### ISSUE TITLE
Tooltip stories no longer appear by default and are not clickable

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5591]
**Describe the bug**
Tooltip stories no longer appear by default and are not clickable

**To Reproduce**
1. Go to [TooltipLinklist](http://localhost:9011/?path=/story/basics-tooltip-tooltiplinklist--links), [TooltipMessage](http://localhost:9011/?path=/story/basics-tooltip-tooltipmessage--default), and [TooltipNote](http://localhost:9011/?path=/story/basics-tooltip-tooltipnote--default)
2. These should appear open by default because of the `startOpen` prop. 

**Expected behavior**
The tooltips should appear "open", i.e., shown, because of the `startOpen` prop which is passed through `WithTooltip`. 

**Screenshots**
This is what the stories currently look like.
![image](https://user-images.githubusercontent.com/263385/52825793-38eb2500-308c-11e9-9336-c4dbe243f0e1.png)

cc @tmeasday wrote the first version of WithTooltip and @ndelangen refactored it for SB 5.0

**Comment by tmeasday** [comment]
Fixed by https://github.com/storybooks/storybook/pull/5610

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.2 containing PR #5610 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
