### ISSUE TITLE
Collapse parent item (folder or component) when a story is selected

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5594]
**Describe the bug**
I can’t collapse the parent item (folder or component) when a story is selected. This ends up being cumbersome when there are a lot of nested sibling stories because users have to scroll long distances to navigate the sidebar. I was able to do this in 4.x which mirrors how [file managers UIs](https://www.dropbox.com/s/s9hl071ftuddywj/Screenshot%202019-02-14%2019.34.30.png?dl=0) in code editors behave.

**To Reproduce**
1. Click on a folder to reveal stories
2. Click on a story
3. Try to collapse the folder
4. See that it wont collapse

**Expected behavior**
I expect to be able to collapse parent elements arbitrarily even if something nested inside them is selected. 

**Screenshots**
Gif: https://cl.ly/cadadcbd9f78

**Comment by tmeasday** [comment]
I'm going to have a stab at doing this with `getDerivedStateFromProps`. Note that this will also solve part of https://github.com/storybooks/storybook/issues/5419. Will write more on the PR

**Comment by tmeasday** [comment]
(Not tonight though. @ndelangen if you want to take a stab, go for it). My plan is to lift the prop-dependent state out to make a fully controlled (i.e. stateless) `TreeWithSearch` or something (ala https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) and a `TreeWithSearchState` which has something like:

```js
class TreeWithSearch {
  getDerivedStateFromProps({ dataset, storyId, filter }) {
     // if the dataset, story or filter changes, we reset the expanded nodes
     return {
        expanded: /* basically our current calculateTreeProps */
     }
  }
}

class TreeWithSearchState {
  state = { filter }
  render() { 
     return <TreeWithSearch onFilter={filter => this.setState({ filter })} filter={this.state.filter} {...this.props} />
  }
}
```

I hope that makes some vague sense

**Comment by tmeasday** [comment]
Ignore the above comment I got this in a slightly different way

**Comment by tmeasday** [comment]
=> https://github.com/storybooks/storybook/pull/5625

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.2 containing PR #5625 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
