### ISSUE TITLE
Toolbar should not have separators between each addon icon

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5597]
**Describe the bug**
Icons in the toolbar should not have separators between each of them. Separators should only appear if there are more than two icons present in a feature or addon (i.e., like the Zoom feature).

**To Reproduce**
1. Go to Storybook that has Toolbar addons
2. See that each icon that corresponds to addons has a toolbar between it

**Expected behavior**
There shouldn't be separators here:
![image](https://user-images.githubusercontent.com/263385/52827158-9f267680-3091-11e9-80de-7c53466da9f0.png)
or here
![image](https://user-images.githubusercontent.com/263385/52827267-178d3780-3092-11e9-859c-5dd1461c28b7.png)

**Comment by leoyli** [comment]
But I think they are nice to have, at least it is clear to me what kind of add-on are grouped...?!

**Comment by domyen** [comment]
Each icon already represents discrete functionality - they don't need to be further separated from other icons to achieve that. 

So they end up occupying more horizontal space yet don't communicating anything new.

**Comment by ndelangen** [comment]
This is fixed?

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.5 containing PR #5711 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
