### ISSUE TITLE
hide chunks/warnings in storybook

### ISSUE THREAD

**Issue by joscha** [storybooks/storybook#560]
Has anyone had any luck disabling the chunk display when running storybook with a warning, e.g.: 

``` console
...
 [2572] ./~/react-modal/lib/index.js 49 bytes {1} [built]
 [2573] ./~/react-simple-di/dist/index.js 2.96 kB {1} [built]
 [2574] ./~/shallowequal/modules/index.js 1.18 kB {1} [built]
 [2611] ./~/uuid/rng-browser.js 735 bytes {1} [built]
 [2612] ./~/uuid/uuid.js 5.29 kB {1} [built]

WARNING in ./packages/ak-editor-schema/~/ajv/dist/ajv.bundle.js
Critical dependencies:
1:476-483 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./packages/ak-editor-schema/~/ajv/dist/ajv.bundle.js 1:476-483
```

I tried

``` js
  storybookBaseConfig.stats = {
      warnings: false,
      chunks: false,
    };
```

``` js
  storybookBaseConfig.devServer = {
    stats: {
      warnings: false,
      chunks: false,
    },
  };
```

``` js
  storybookBaseConfig.webpackMiddleware = {
    stats: {
      warnings: false,
      chunks: false,
    },
  };
```

to no avail

**Comment by pierrecholhot** [comment]
I'm also struggling trying to hide those chunks and warnings. However @joscha regarding your specific warning, you could try and circumvent it by making webpack ignore this file.

```
storybookBaseConfig.module = {
  noParse: [/ajv\.bundle\.js/],
  loaders: [ ... ]
}
```

**Comment by evandavis** [comment]
Same, this is currently driving me nuts.

I want to see warnings and errors; I _never_ want to see chunk output.

**Comment by arunoda** [comment]
Yep. This is needed.
We may wanna use this: https://github.com/geowarin/friendly-errors-webpack-plugin

I'm open for a PR for this.

**Comment by banditrider** [comment]
Did anyone achieve this issue's goal with @arunoda's suggestion?

Nice plugin, but it doesn't silence Webpack's output, needs to be done manually. Which this issue is all about.

Has anyone found a working solution?

**Comment by danielduan** [comment]
I think the output has been silenced for the default webpack config. If you're using a custom config, you might still run into this. Closing.
