### ISSUE TITLE
Warnings about `:first-child`

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#5602]
Can we remove these by changing to `first-of-type` (as suggested)? 

Can confirm that a search and replace does indeed remove the warning, with no obvious visual bugs 🤷‍♂️ .

**Comment by domyen** [comment]
Removed it in the UI.

**Comment by domyen** [comment]
This shipped in 5.0.0 rc3 PR #5650

**Comment by shilman** [comment]
@domyen if you reference the issue in the first line of the PR where it says "Issue: " my script will close the issue and add a link to the release as a comment

**Comment by claudio-moya** [comment]
Hi guys,

The warning still available at the v5.1.0-rc.2, any plan to remove it?
