### ISSUE TITLE
Broken build - Cannot find module 'babel-preset-env'

### ISSUE THREAD

**Issue by CodeByAlex** [storybooks/storybook#5615]
**Describe the bug**
Getting error: Cannot find module 'babel-preset-env' when upgrading from beta.3 to beta.5

**To Reproduce**
1. Update to Beta .4,
2. run npm install
3. start storybook

**Expected behavior**
Start up storybook without breaking

**Screenshots**
![image](https://user-images.githubusercontent.com/29763590/52867900-fbc87680-310f-11e9-8fcf-3d01a235acc7.png)

**System:**
 - OS: [MacOS]
 - Browser: [chrome]
 - Framework: [Angular]
 - Version: [e.g. 5.0.0-beta.4]

**Comment by tmeasday** [comment]
Thanks @CodeByAlex. I think @Hypnosphi is all over it: https://github.com/storybooks/storybook/pull/5617

For now you could probably just add that dependency if you want to keep going.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.1 that addresses this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
