### ISSUE TITLE
When Storybook is loading there is a "no stories message"

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5620]
**Describe the bug**
When Storybook is initially loading a "no stories" message appears for some time. Sometimes between 100ms and 1000ms depending on the size of your Storybook. This makes Storybook feel slow and sluggish. 

**To Reproduce**
1. Refresh Storybook
2. See the "no stories" message
3. See that the stories populate the sidebar sometime after

**Expected behavior**
Rather than seeing the no stories message we should show a loading state instead. The no stories message should only show if there truly are no stories found.

I created up a [Sidebar:loading](http://localhost:9011/?path=/story/ui-sidebar-sidebar--loading) state. I could use help implementing it. 
![screen recording 2019-02-15 at 06 58 pm](https://user-images.githubusercontent.com/263385/52890617-b463d980-3153-11e9-9da8-f4f61a4a202a.gif)

**Screenshots**
Screen recording: https://cl.ly/9095de04dff7

**Comment by tmeasday** [comment]
@ndelangen do you think we can technically do this right now? Or do we need a new "`configure` ran" event to be able to distinguish between no stories and loading?

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.7 containing PR #5756 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
