### ISSUE TITLE
Move show info button to the tooltip (addon-info)

### ISSUE THREAD

**Issue by leoyli** [storybooks/storybook#5622]
**Is your feature request related to a problem? Please describe.** 
The top-right corner is occupied by the "show info" button, which is kind of annoying in some situation.

**Describe the solution you'd like**
It would be nice if we can move "show info" button into the tooltip.

**Describe alternatives you've considered**
N/A

**Are you able to assist bring the feature to reality?**
I think I may be able to help on this after diving in to the source code and acquire consensus with people.

**Additional context**
N/A

**Comment by tmeasday** [comment]
Hey @leoyli - @shilman is working on a larger project to migrate the info addon to the addons panel - (here's a super old ticket about it: https://github.com/storybooks/storybook/issues/1147)

I'm not sure if it makes sense to put the button in the toolbar (is this what you mean?) vs a documentation pane (ala the notes addon in v5) vs a panel. Perhaps it makes sense to move this discussion there?

**Comment by leoyli** [comment]
@tmeasday Thanks! Yes I mean the toolbar, I call it `tooltip` is because there is a component named as tooltip not toolbar...
