### ISSUE TITLE
Keyboard controls for treeview not working

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#5623]
I'm not quite sure what the UX is supposed to be (how do you focus the treeview, what does the focussed element look like?) but although I think the code is correct, the treeview keydown events don't do anything.

**Comment by domyen** [comment]
Strawman keyboard UX: 
- Allow focussing folders and components (right now I can only tab to stories)
- Right arrow key expands the folder or component content
- Right arrow key of an already expanded folder or component focusses the first child 
- Left arrow key on folder or component collapses expanded contents
- Left arrow key on a story collapses the parent folder or component and focusses it
- Enter opens the story _or_ expands the folder/component

**Comment by tmeasday** [comment]
That sounds fairly similar to the existing code that's there. What I don't understand is the first step -- how do I do that, literally? Also what does a focussed folder/component look like?

**Comment by domyen** [comment]
re: focussed states, I can style it we can get the basic functionality working again 😅

**Comment by tmeasday** [comment]
But how do I focus it? Do I tab to it? Do I click on it? Is there a shortcut?

**Comment by domyen** [comment]
1. Click into the sidebar either on a blank space which sets tab index to default (I think this is what it's called) or on an item
2. From there you can tab around or use the arrow key (with no modifiers) to move around the treeview

Probably missing some edge cases from the above but that's how I'd expect it to work at first glance.
