### ISSUE TITLE
 Cannot find module 'react-scripts\config\webpack.config.js'

### ISSUE THREAD

**Issue by quirimmo** [storybooks/storybook#5627]
**Describe the bug**
When executing `start-storybook -p 9009 -s public` I get the following error:

> Cannot find module 'react-scripts\config\webpack.config.js'

If I go inside the `react-scripts\config` folder, actually that file is not there. 
But there are two config files:

`webpack.config.dev.js`
`webpack.config.prod.js`

Opening your source file inside `node_modules` subfolder: 

`node_modules\@storybook\react\src\server\cra-config.js`

at line 81, there is a method called `getCraWebpackConfig`.

This method actually expects those two files, as they are in the `react-scripts` folder, but the check `fs.existsSync(pathToWebpackConfig)` returns `false`, even if actually the `config/webpack.config.dev.js` is there in the path, which looks right.
Being `false`, the config to be loaded fallbacks to `'config/webpack.config.js'`, as stated inside that `if`, pointing to a file which is not in the `react-scripts` instead.  

I found two workarounds changing the local code in my `node_modules` subfolder, but it would be great to understand why this issue is happening, and how to fix it without manually changing the `node_modules` packages locally. 

- The first workaround is to comment out that check and go on with the config, without checking if the file is really there through `fs`.  Of course this change should be made inside the `dist` rather than the `src` file of your `cra-config.js`. 
- Another workaround, is to go inside the `node_modules\react-scripts\config\` folder locally and add a `webpack.config.js` file with the same content of the `webpack.config.dev.js` which is in the same folder. 

**Expected behavior**
The command should automatically load the present config in that path. 

**System:**
 - OS: Windows 10
 - Framework: react
 - Versions: 
   ```
    "react-scripts":` "2.1.5",
    "@storybook/react": "^4.1.11",
   ```

**Comment by c-moss-talk** [comment]
`If I go inside the `react-scripts\config` folder, actually that file is not there.`

`webpack.config.js` should be there. I would focus on why it's not.

**Comment by quirimmo** [comment]
@c-moss-talk 

There is a chunk of code which says "if the file is not there, fallback to another one" and the file is there... and I should focus on why there is not the fallback file? 

I will try a new fresh install of CRA and see if the file is there, but `react-scripts` seems to work without any issue. If there was a missing file, maybe I should have noticed some error.

**Comment by quirimmo** [comment]
It looks like with new projects, that file is there. Closing the issue then.
