### ISSUE TITLE
display registered action handlers for active story

### ISSUE THREAD

**Issue by tkryskiewicz** [storybooks/storybook#5631]
**Is your feature request related to a problem? Please describe.**
For some components, I'm creating a `default` story with actions that are always available:
~~~jsx
storiesOf("Component, module)
  .add("default", () => (
    <Component
      onExitMouseEnter={action("Exit Mouse Enter")}
      onExitMouseLeave={action("Exit Mouse Leave")}
      onExitClick={action("Exit Click")}
    />
  ));
~~~
and then specialised stories for possible actions:
~~~jsx
  .add("dismissal", () => (
    <Component
      dismissible={boolean("Dismissible?", true)}
      onDismissMouseEnter={action("Dismiss Mouse Enter")}
      onDismissMouseLeave={action("Dismiss Mouse Leave")}
      onDismissClick={action("Dismiss Click")}
    />
  ));
~~~
but without additional description or some guessing, there's no way to tell what actions are available.

**Describe the solution you'd like**
Would be great to have a list of all registered action handlers displayed in action logger panel, like:
~~~
Registered handlers:
  Dismiss Mouse Enter
  Dismiss Mouse Leave
  Dismiss Click
~~~

**Describe alternatives you've considered**
Open to suggestions.

**Are you able to assist bring the feature to reality?**
Yes, I can... with some guidance.

**Additional context**
None.

**Comment by tmeasday** [comment]
Hi @tkryskiewicz - I'm not quite sure what you are thinking here, but I'm not sure that is technically possible.

Can you explain a little more about the use case you are trying to serve here, perhaps we can come up with something? Are you thinking about documenting the component?

**Comment by tkryskiewicz** [comment]
Hi @tmeasday, 

I think we can simplify things quite a bit here. Let's say we have a story for `Component` with a `Click` action handler registered.

```jsx
<Component
  onClick={action("Click")}
/>
```

When we open this story, without additional description or addons like Storysource, we have no idea that we should be able to click and execute this handler (there's nothing in the UI that tells that).

It would be great to see a list of action handler names (in `Action Logger` panel), that were registered during story (re)rendering. In our case it would be:
```
Registered handlers:
- Click
```

The overall goal is to inform the user on what he's able to within that story.

Hope I made myself clear this time ;)

**Comment by shilman** [comment]
@tkryskiewicz Nice idea! I'm also not sure whether it's possible, but it would be cool/useful if we could make it happen!

**Comment by tkryskiewicz** [comment]
Thanks @shilman!

Looks like this should be possible, would require to:
- add an event for action handler registration
- emit such event when calling `action()`
- handle that event in `ActionLogger` container (add to list)
- present a list of registered handlers in `ActionLogger` component
- clear list when switching story

Solution seems simple, but there are a couple of problems I've encountered:
- when opening actions root from examples a lot of handlers get registered
- sometimes some helper actions seem to be registered that aren't obvious
- performance when rendering a lot of stories and other edge cases

https://github.com/tkryskiewicz/storybook/commit/a184d4d47274486fe96461be80f52090197fced6

**Comment by tmeasday** [comment]
The problem is you don't have to call `action` inside the story function. I guess you could make it a requirement to use this feature.

**Comment by tkryskiewicz** [comment]
True. Right now I see this feature more as opt-in. 

Given that you can emit an event from basically anywhere, other ways to register handlers should also be doable. One problem is, that if you create them with `actions()`, then clearing list during story re-rendering doesn't apply. The other one is that only a few might be applicable to the active story.

Also the naming is left up to the user. It's not a problem to register 2 handlers with same name (intentionally or not).

Will look into those things.

**Comment by tkryskiewicz** [comment]
Hi,

Finally had some time to work on this - https://github.com/storybooks/storybook/compare/next...tkryskiewicz:display-registered-action-handlers?expand=1.

Would see this feature looking something like this (with better styling, maybe being collapsible, etc.):

![Screenshot 2019-03-18 at 16 47 15](https://user-images.githubusercontent.com/19226713/54543426-f0ca6580-499d-11e9-9c69-321274e97e3b.png)

When using `actions(...)`:

![Screenshot 2019-03-18 at 16 47 35](https://user-images.githubusercontent.com/19226713/54555890-f46ae600-49b7-11e9-8d0d-cefaef001d13.png)

Sometimes `action()` is called like `onClick={() => action('Boolean')(false)}`, added `*` to distinguish them:

![Screenshot 2019-03-18 at 16 48 03](https://user-images.githubusercontent.com/19226713/54556248-c1752200-49b8-11e9-8e96-5b51bf664e18.png)

List is cleared when changing stories.

Things left to do:
- on initial load, handlers from multiple stories are registered, not sure if there's currently a way to fix this
- handle addons panel orientation toggle
- visuals

**Comment by shilman** [comment]
Pretty neat! I think this will be a useful option -- any plans to push it forward?

**Comment by tkryskiewicz** [comment]
hey @shilman,
Definitely yes! Been quite busy lately. Will find some time in the upcoming days to work on styling.

**Comment by tkryskiewicz** [comment]
Sorry. Can't really find time to finish this. Once I'm free, I'll get back to this. :)
