### ISSUE TITLE
Storybook v4 addons break storybook v5

### ISSUE THREAD

**Issue by Rolandisimo** [storybooks/storybook#5645]
**UPDATE**
Seems related to https://github.com/storybooks/storybook/issues/4525
<hr />

**Describe the bug**
`"@storybook/react": "^4.1.12"` causes storybook not being able to run with the current CRA2 project causing `Uncaught TypeError: Object(...) is not a function`.

✅ Below is a dependency list that **worked for the ongoing project and a clean CRA2 app if addons are not registered:**
```
    "@storybook/addon-actions": "^4.1.12",
    "@storybook/addon-knobs": "^4.1.12",
    "@storybook/addon-links": "^4.1.12",
    "@storybook/addon-options": "^4.1.12",
    "@storybook/addons": "^4.1.12",
    "@storybook/react": "^5.0.0-rc.1", // <--- below version 5, storybook would throw the issue above
```

❌ Issue occurred after registering addons:
```
// .storybook/addons.js
import '@storybook/addon-knobs/register' // <--- any v4 addon fails the build
```

**Result**
- With an ongoing CRA2 build, I get this: `Uncaught TypeError: Object(...) is not a function`
- With a fresh CRA2 app, I get this: `TypeError: _addons.default.getElements is not a function` and other errors

**To Reproduce**
1. Create CRA2 app
2. Install dev dependencies as posted above
3. Launch storybook
4. Observe 👀

**Screenshots**
 - For ongoing CRA2 project:
![screenshot 2019-02-18 at 12 17 07](https://user-images.githubusercontent.com/9778368/52947486-249e7500-3377-11e9-93ae-e651874d0198.png)

```javascript
// vendors-main:1624
var Styled = Object(_emotion_core__WEBPACK_IMPORTED_MODULE_2__["withCSSContext"])(function (props, context) { // <--- failing part
  // ...
}
```

**Comment by shilman** [comment]
@Rolandisimo v4 addons are not intended to be used with v5 -- that's why we're releasing this as 5.0.0 and not 4.2.0 (see https://semver.org/). Is there a reason you don't want to upgrade the addons as well?

**Comment by Rolandisimo** [comment]
@shilman I actually honestly searched for add-ons v5 but couldn't find them. Which made me suspicious, of course. My bad. 

Could you provide a link possibly to a release?

Thanks!

**Comment by Rolandisimo** [comment]
Found it https://github.com/storybooks/storybook/tree/next/addons
Now everything works like a charm on v5.

Thanks @shilman 
Sorry for bothering

**Comment by shilman** [comment]
No worries, good luck!

**Comment by pnarielwala-tc** [comment]
Hello! 👋 I'm getting this issue as well but with all my packages being on `4.1.12`. I can't upgrade to v5 just yet as we're using `react@15.6.2` and `react-scripts@2.1.8`

![Screen Shot 2019-04-23 at 5 16 54 PM](https://user-images.githubusercontent.com/37671065/56619625-ccd8f000-65eb-11e9-8502-f982fc51ff0a.png)

![Screen Shot 2019-04-23 at 5 17 11 PM](https://user-images.githubusercontent.com/37671065/56619630-cfd3e080-65eb-11e9-9ff0-8edcd651d5b3.png)

Is there a way I could get it to work without having to upgrade my React to v16?

Thanks!

**Comment by shilman** [comment]
@pnarielwala-tc can you open a separate issue? v5 should work with React v15

**Comment by Parthchokshi** [comment]
@pnarielwala-tc Hey! Did you solve or open that issue? I am getting the same error. 

Using 4.1.18 for all storybook packages and 16.8.6 for react and react-dom.
