### ISSUE TITLE
No stories are shown when using Angular 7

### ISSUE THREAD

**Issue by ohadinho** [storybooks/storybook#5647]
**Describe the bug**
Storybook is loaded successfully (I'm using Angular 7) but in dashboard this message is displayed:
"Sorry, but you either have no stories or none are selected somehow.".
I DO have stories under `src\stories`.
When typing garbage in `index.stories.ts` I DO get an error in dashboard (that means the file is compiled and read by storybook lib).

**To Reproduce**
Configure storybook almost exactly step by step (use angular 7):
https://storybook.js.org/basics/guide-angular/

**Expected behavior**
See in dashboard a single story named hello world.

**Code snippets**
**.storybook/config.js**
```
import { configure } from '@storybook/angular';

// automatically import all files ending in *.stories.ts
const req = require.context('../src/stories', true, /.stories.ts$/);
function loadStories() {
    req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

**.storybook/tsconfig.json**
```
{
  "extends": "../tsconfig.json",
  "exclude": [
    "../src/test.ts",
    "../src/**/*.spec.ts",
    "../projects/**/*.spec.ts"
  ],
  "include": [
    "../src/**/*",
    "../projects/**/*"
  ]
}
```

**src/stories/index.stories.ts**
```
import {AppComponent} from '../app/app.component';
import {storiesOf} from '@storybook/angular/src/client/preview';
import {moduleMetadata} from '@storybook/angular';
import {ApiServiceMock} from './api.service.mock';
import {FormsModule} from '@angular/forms';

storiesOf('My Component', module)
    .addDecorator(
        moduleMetadata({
            imports: [FormsModule],
            providers: [ApiServiceMock]
        })
    )
    .add('hello world', () => ({
        component: AppComponent
    }));
```

**System:**
 - OS: Windows 10
 - Device: Laptop
 - Browser: Chrome
 - Framework: Angular (7.2.4)
 - Addons: None
 - Storybook Version: 4.1.11 , babel-loader: 8.0.5, babel/core: 7.3.3

**Comment by CodeByAlex** [comment]
Which version of storybook are you using?

**Comment by ohadinho** [comment]
@CodeByAlex  I'm using version 4.1.11 (I've edited the original question).

**Comment by ohadinho** [comment]
@CodeByAlex I'm using 4.1.11. I've edited the original question.

**Comment by CodeByAlex** [comment]
@ohadinho Sorry for the delay. I believe the 5.0 release is optimized for Angular 7 and there may be some backward compat issues. Are you still seeing this issue? If so, are there any errors?

**Comment by ohadinho** [comment]
Hi Alex,
I've started a new angular 7 + storybook project from scratch and
everything is working fine.

**Comment by CodeByAlex** [comment]
@ohadinho Great to hear! Im going to close this issue
