### ISSUE TITLE
Issue with Webpack and multiple `node_modules` folders.

### ISSUE THREAD

**Issue by robtarr** [storybooks/storybook#5651]
**Describe the bug**
Using Lerna, each of my modules has it's own `node_modules` folder. When Webpack bundles `moment` (and other dependencies) from `packages/moduleName/node_modules` it does not get bundled correctly. This results in 
```
Cannot set property 'moment' of undefined
    TypeError: Cannot set property 'moment' of undefined
    at http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:66663:309
    at Module.<anonymous> (http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:66664:3)
    at Module../packages/timeModule/node_modules/moment/moment.js (http://localhost:6007/vendors~main.f4ce6b32bc79f7651537.bundle.js:71242:30)
    at __webpack_require__ (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:782:30)
    at fn (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:150:20)
    at Module../packages/timeModule/index.js (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:71:64)
    at __webpack_require__ (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:782:30)
    at fn (http://localhost:6007/runtime~main.f4ce6b32bc79f7651537.bundle.js:150:20)
    at Module.<anonymous> (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:48:59)
    at Module../packages/timeModule/index-story.js (http://localhost:6007/main.f4ce6b32bc79f7651537.bundle.js:56:30)
```
**Expected behavior**
I expect `moment.js` to be bundled correctly and not throw errors.

**Code snippets**
I have put together a repo top show this problem.
https://github.com/robtarr/storybook-test
- `master` is in the broken state
- `working-without-lerna` builds correctly

**System:**
 - OS: MacOS 
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Version: 4.1.11

I crossposted this with Webpack - https://github.com/webpack/webpack/issues/8809

**Comment by tmeasday** [comment]
Hi @robtarr - using lerna is nothing strange, in fact the storybook monorepo uses it as do many other projects.

This seems like a webpack configuration problem. Have you tried without your custom webpack config? I would hazard a guess it is leading to the issue.

**Comment by robtarr** [comment]
I get the exact same results without my webpack config file.

**Comment by tmeasday** [comment]
Hey @robtarr, oh, I see the issue is because `moment` is being compiled by babel (it is not easy to debug this, but I think this is the second time I've seen this `exports` vs `__webpack_exports__` issue due to that).

You need to add your subproject's node modules to the exclude list for SB's babel loader, something like:

```js
// in webpack.config.js

const babelLoader = storybookBaseConfig.module.rules[0];
  babelLoader.exclude.push(resolve('./packages/timeModule/node_modules'));
```

I don't know if there is a recommended/better way to do this. We should probably be excluding all `node_modules` directories by default (including sub-subdirs).

**Comment by ndelangen** [comment]
https://github.com/storybooks/storybook/blob/20d4131ef6e6e9faa6e39f22cf6b847535c9f9a1/lib/core/src/server/common/babel-loader.js

I think this needs an exclude?

**Comment by tmeasday** [comment]
On this line, right: https://github.com/storybooks/storybook/blob/20d4131ef6e6e9faa6e39f22cf6b847535c9f9a1/lib/core/src/server/config/utils.js#L5

**Comment by robtarr** [comment]
It turns out this was an error in my alias configuration. Sorry the hassle.

**Comment by shilman** [comment]
Glad you solved it!

**Comment by thematho** [comment]
> It turns out this was an error in my alias configuration. Sorry the hassle.

It would be nice to know the correct configuration, I'm running into the same issue.
