### ISSUE TITLE
Mobile styling

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5652]
**Describe the bug**
Mobile styling requires improvement. (see expected behavior)

**To Reproduce**
1. Shrink screen width to mobile size
2. Click on "nav" or "panel"
3. See that the bottom bar is incorrect color, and the addons panel has an incorrect backgrounds 

**Expected behavior**
- [X]  Bottom bar should have the same background as the `Toolbar`
- [x] Addons panel should be scrollable
- [x] Addons panel should extend the whole height of the viewport
- [x] Addons panel should not have "change orientation" or "close" icons
- [x] Canvas toolbar should not have "fullscreen" 

**Screenshots**

| Canvas | Sidebar | Addons |
|------|------|------|
| <img width="538" alt="screen shot 2019-02-18 at 4 46 16 pm" src="https://user-images.githubusercontent.com/263385/52977887-119e9b80-339d-11e9-86ad-039d81868cdb.png"> |  <img width="537" alt="screen shot 2019-02-18 at 4 46 22 pm" src="https://user-images.githubusercontent.com/263385/52977894-14998c00-339d-11e9-80ee-0692d0e0f3a8.png"> | <img width="538" alt="screen shot 2019-02-18 at 4 46 05 pm" src="https://user-images.githubusercontent.com/263385/52977898-16634f80-339d-11e9-963e-28a17374fe25.png"> |

**Comment by shilman** [comment]
@domyen Is this a bug or a feature request?

**Comment by domyen** [comment]
These are bugs. There was another bug that prevented mobile QA that was fixed recently. That's why these bugs are surfacing now.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.5 containing PR #5709 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
