### ISSUE TITLE
Keyboard shortcuts reversed for Sidebar and Addons panels in 5.0.0-rc.2

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#5666]
@domyen Not sure if this is a design issue or implementation bugs, but it seems like the keyboard shortcuts for Addons/Sidebar panels are reversed? LMK

<img width="221" alt="welcome_-_to_storybook_ _storybook" src="https://user-images.githubusercontent.com/488689/53007162-a70b5f80-3471-11e9-94e6-e5409fbf36bb.png">

**Comment by domyen** [comment]
I'm in favor of switching the keyboard shortcuts if there are no objections. They pre-date my work on the UI. 

I don't know the exact history of why those keyboard shortcuts were chosen. Probably something to do with the original presentational names of the Sidebar (nav/explorer) and Addons (panel). cc @ndelangen.

**Comment by ndelangen** [comment]
I'm on it

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.4 containing PR #5677 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by mattdeboard** [comment]
Hi sorry but are the keyboard shortcuts documented somewhere? I keep tappign something that makes the story panel disappear and I can't get it back without completely restarting the process.
