### ISSUE TITLE
Cast event when switching stories

### ISSUE THREAD

**Issue by phaistonian** [storybooks/storybook#5668]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Either enable passing a handler or casting an event on window, e.g `storyChanged` when the story changes.

**Are you able to assist bring the feature to reality?**
Yes, if I get the time

**Comment by jasonsturges** [comment]
This is probably more  accurately titled as: "Dispatch event on story change".

Guessing https://github.com/storybookjs/storybook/issues/845 "Hook on leaveing a story" is the actual use case.

This is a challenging topic to search for within storybook - terminology / typos in titles don't help.
