### ISSUE TITLE
Error: UnhandledPromiseRejectionWarning in 5.0 RC3

### ISSUE THREAD

**Issue by Kailaash-Balachandran** [storybooks/storybook#5670]
**Description**
While building Storybook for Vue, I get the following error

```
WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

(node:16) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'compilation' of undefined at buildDevStandalone (/app/code/node_modules/@storybook/core/dist/server/build-dev.js:347:58)

(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

```
**Package**

Webpack: v4.29.5
Storybook: v5.0.0-rc.3

**Comment by B3zo0** [comment]
probably there is an error in your webpack config. you can see the error message with a little hack
add this to `/node_modules/@storybook/core/dist/server/build-dev.js` 
```js
_nodeLogger.logger.error(error)
```
after line 341, this way you can see the actual error.

**Comment by seanmcintyre** [comment]
`Cannot read property 'rules' of undefined`

`config.modules.rules` is undefined?

This seems to contradict the migration instructions: 
https://github.com/storybooks/storybook/blob/next/MIGRATION.md#from-version-41x-to-50x

**Comment by seanmcintyre** [comment]
It's a typo.

`config.modules` should be `config.module`

@Kailaash-Balachandran

**Comment by tmeasday** [comment]
Assuming @seanmcintyre and @Kailaash-Balachandran are looking at the same codebase I think we can close this? LMK if not ;)

**Comment by Kailaash** [comment]
Thanks @seanmcintyre. The migration instructions solved the issue.

**Comment by Kailaash-Balachandran** [comment]
Thanks @seanmcintyre. The migration instructions solved the issue for me.
