### ISSUE TITLE
process.env.REACT_APP_* broken in 5

### ISSUE THREAD

**Issue by KhodeN** [storybooks/storybook#5681]
**Describe the bug**
After updating to `5.0.0-rc.3` all `process.env.REACT_*` variables disappeared.

**Expected behavior**
Storybook should keep reading `REACT_*` variables from dotEnv files (in CRA project).

**Code snippets**
I used this code for proxying API requests:

```js
const proxy = require('http-proxy-middleware');

module.exports = function expressMiddleware(router) {
   const host = process.env.REACT_APP_API_HOST;

   router.use('/v1', proxy({
      headers: {
         Host: host,
      },
      secure: false,
      target: 'https://' + host,
   }));
};
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Browser: no matter
 - Framework: react (CRAv2)
 - Addons: -
 - Version: 5.0.0-rc.3

**Comment by shilman** [comment]
@KhodeN Can you help me repro this?

### What I did

1. Create a `.dotenv` file containing:
```
REACT_APP_API_HOST=localhost:3000
```
2. Create a `middleware.js` file including your snippet above and a `console.log` statement.

### What I'm seeing

I see consistent behavior between 4.x and 5.x. Specifically:
1. `REACT_APP_API_HOST=localhost:3000 yarn storybook` shows `host` is defined
2. `yarn storybook` shows `host` is `undefined`

I've tried this in:
- `examples/official-storybook` on both `master` (4.x) and `next` (5.x)
- A standalone test-app running `@storybook/react@5.0.0-rc.9` (latest)

**Comment by KhodeN** [comment]
I check version 5.0.1. It is OK! Thanks!
