### ISSUE TITLE
`channel.emit` in addons-actions is slow in v5.0.0-rc3

### ISSUE THREAD

**Issue by jonathanj** [storybooks/storybook#5682]
**Describe the bug**
Defining an action, passing it as an event handler, and subsequently clicking it in Storybook v5.0.0-rc3 seems to block for a noticeable (1-2s on my machine) amount of time. Especially noticeable on buttons.

Not passing the action as an event handler doesn't cause the UI to block.

I'm using 5.0.0-rc3 for all my addons and Storybook.

**To Reproduce**
1. Create a new Storybook project on version 5.0.0-rc3
2. Add a new story using the code below
3. Navigate to the story and click the button
4. See the button remain in the active state after the mouse button was released and the action only log after the button returns to it's normal state, a second or two later.

**Code snippets**
```jsx
import React from 'react'
import {storiesOf} from '@storybook/react'
import {action} from '@storybook/addon-actions'

const onClick = action('onClick')
storiesOf('Repro', module)
  .add('Not broken', () => <button>Click me</button>)
  .add('Broken', () => <button onClick={onClick}>Click me</button>)
```

**System:**
 - OS: macOS 10.14.3
 - Device: Macbook Pro 2019
 - Browser: Chrome 74.0.3702.0
 - Framework: React
 - Addons: addons-actions
 - Version: 5.0.0-rc3

**Context:**
The only vaguely related issue I could find was #2590, which seems pretty old. It's possible I was searching for the wrong thing and didn't find a more relevant issue.

**Comment by shilman** [comment]
Duplicate to #5551, closing :)
