### ISSUE TITLE
Incorrect homepage URL in storyshots package.json

### ISSUE THREAD

**Issue by erikjung** [storybooks/storybook#5686]
### Bug or support request summary

The `@storybook/addon-storyshots` package.json has a typo ("storyshorts") in the homepage URL: https://github.com/storybooks/storybook/blob/master/addons/storyshots/storyshots-core/package.json#L9

### Steps to reproduce

1. Visit the URL specified in the package.json
2. Experience the GitHub 404 page.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/addon-storyshots 4.1.6

### Affected platforms 

Any browser.

**Comment by shilman** [comment]
Thanks for the bug! This is fixed in `next` so we'll focus on getting v5 out
