### ISSUE TITLE
withViewport doesn't work work well with withKnobs

### ISSUE THREAD

**Issue by eldyvoon** [storybooks/storybook#5701]
withViewport addon worked for me to develop responsive component.
```
stories.addDecorator(withKnobs).addDecorator(withViewport())
stories.add(
  'Destination',
  () => (
    <Destination
      destination={{
        title: text('Title', 'Taiwan'),
      }}
    />
  ),
  {
    viewport: 'mobile'
  }
)
```
The problem I'm facing is when a knob option is change, the viewport will bounce back to the default viewport value. 

<img src="https://im.ezgif.com/tmp/ezgif-1-d560419ddbc2.gif" />

**Comment by shilman** [comment]
@eldyvoon Which version?

**Comment by eldyvoon** [comment]
@shilman 

@storybook/addon-viewport": "^4.1.11",
@storybook/addon-knobs": "^4.1.11",
