### ISSUE TITLE
[addon-cssresources] Resource IDs are not displayed in panel

### ISSUE THREAD

**Issue by huntie** [storybooks/storybook#5704]
**Describe the bug**

Per documented behaviour, I expect to see the ID of each resource I have added in the addon panel interface. However, it prints a `#` without any name value for each stylesheet.

**To Reproduce**

1. Add `cssresources` options as documented:

```js
addDecorator(
  withCssResources({
    cssresources: [
      {
        id: 'core-framework',
        code: '<link rel="stylesheet" type="text/css" href="/assets/css/main.min.css">',
        picked: true
      }
    ]
  })
);
```

2. Click on 'CSSRESOURCES' addon panel.
3. See no name/ID label and React `key` usage warning (see screenshot below).

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/2547783/53170670-975a5b00-35d8-11e9-8789-19da42d52347.png)

**Code snippets**

Error message (pre stack trace):

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `CssResourcePanel`. See https://fb.me/react-warning-keys for more information.
```

**System:**
 - OS: Served on Ubuntu 18.04 via WSL, viewed in browser on Windows 10
 - Browser: Chrome
 - Framework: vue
 - Addons: cssresources 4.1.13
 - Version: 4.1.12

**Comment by shilman** [comment]
cc @nm123github

**Comment by ndelangen** [comment]
Is this issue still present in V5?

**Comment by Nejik** [comment]
same history with vue storybook installed withvue-cli-plugin-storybook, but i changed prop "id" to "name", and it works

Working example:
`addParameters({
    cssresources: [{
        name: `bluetheme`,
        code: `<style>body { background-color: lightblue; }</style>`,
        picked: true,
      },
    ],
  })`

**Comment by huntie** [comment]
@Nejik Same use case here with Vue, looks to just be a documentation blip then!

**Comment by shilman** [comment]
@huntie @Nejik mind creating a small PR to fix the docs?

**Comment by huntie** [comment]
It appears that the default branch on this repository (and therefore the docs) is simply ahead of the currently distributed version (4.1.13), and includes https://github.com/storybooks/storybook/commit/412cd179849fdc442206b93616d57faf30a0c0cd where `id` is used consistently and documented. Probably worth moving forward with that release, and having this issue as reference. Maybe docs in this repository should be published at the same released version of each package.

**Comment by shilman** [comment]
@huntie There are a couple things going on here:
- `master` branch is equivalent to `latest` npm tag (version 4.1.x currently)
- `next` branch is equivalent to `next` npm tag (version 5.0-rc.x currently)

If there is a breaking change in `next` we should document this in `MIGRATION.md` so that people who are upgrading from 4.x to 5.x can expect it and know how to fix it. Better yet, we deprecate the old behavior so that nothing breaks, and then remove it in 6.0. Can you let me know whether this is a breaking change?

**Comment by huntie** [comment]
@shilman Understood. What I meant is that a user (like myself on this occasion) will commonly jump to a GitHub homepage for a project, ignore the default branch and essentially read the documentation there, which is ahead. On npm however, the correct state of `README.md` is present for the release and the documentation is correct.

A breaking change will therefore be introduced between 4.1.x and 5.0.0 :+1: I'll open the PR for `MIGRATION.md` soon. :wink:
