### ISSUE TITLE
Addon with-info wrap the story in a div with `position: relative;`

### ISSUE THREAD

**Issue by yachaka** [storybooks/storybook#5707]
**Describe the bug**
See https://github.com/storybooks/storybook/blob/master/addons/info/src/components/Story.js#L49
Story is being wrapped in a `position: relative;` div.
Combined with the centering addon, it makes it so absolute element are not positioned relatively to the window but to the story itself.

**To Reproduce**
1. Add addon-centered
2. Add addon-info
3. Create a story with a static fixed width element, and an absolute-positioned element
4. Notice how the absolute-positioned element will be positioned relatively to the static fixed width element, and not the window

**Expected behavior**
Expected the absolute-positioned element to be positioned relatively to the window

**Screenshots**
![capture d ecran 2019-02-21 a 16 13 30](https://user-images.githubusercontent.com/8074336/53179273-b3b7c100-35f3-11e9-8b52-b7372054f6ed.png)
^ This menu should be positioned relatively to the window because there is no wrapping relative div. It should stick to the left and right edges precisely.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: MacOS
 - Device: Macbook Pro
 - Browser: Chrome
 - Framework: React
 - Addons: addon-info, addon-centered
 - Version: addon-info@4.1.12, addon-centered@4.1.12

**Additional context**

**Comment by shilman** [comment]
Hey @yachaka, thanks for the bug report. Fortunately (unfortunately?) we are going to deprecate `addon-info` and move it to the addons panel as soon as v5 is out, so probably won't get around to this, but if anybody wants to submit a PR with the fix I'd probably release it in the meantime. Closing for now! 🙇
