### ISSUE TITLE
upgraded to 4.1.3, now only cra devserver shows up in port 9001

### ISSUE THREAD

**Issue by d3bgger** [storybooks/storybook#5720]
**Describe the bug**
I had a working installation of storybook 4.0.7 with cra. 
I upgraded to 4.1.3 and now when i start storybook, it builds ok, but in browser localhost:9001 just shows the same output as if i was in localhost:3000. I don't see anything storybook related (apart from the favicon). 

If i stop the webpack devserver of my app, then in localhost:9001 in browser i just see:
Error occured while trying to proxy to: localhost:9001/.

I don't know what is going on. 

**System:**
 - OS: Windows10
 - Framework: react
 - Version: 4.1.3

**Comment by shilman** [comment]
@d3bgger What version of CRA are you running? Do you have a sample repo?

**Comment by d3bgger** [comment]
cra v2. I'll see if i can reproduce this in simple test project.

thanks

**Comment by d3bgger** [comment]
That was responsible...

`const proxy = require('http-proxy-middleware');

module.exports = function expressMiddleware(router) {
  router.use(
    '/',
    proxy({
      target: 'http://localhost:3000',
      changeOrigin: true
    })
  );
};`

This was working in previous versions (proxy was not affecting the initial document request of storybook) but now doesn't like it. I changed it to be more specific about the paths i want to proxy to cra devserver.

I guess this can be closed? 

thanks
