### ISSUE TITLE
Type of withKnobs 

### ISSUE THREAD

**Issue by Jack-Barry** [storybooks/storybook#5727]
**Describe the bug**
The type of `withKnobs` is not valid for the `addDecorator` function. Looks like the `@types/storybook_addon-knobs` is out of date maybe?

**To Reproduce**

Using the following relevant libraries:

```json
    "@babel/core": "^7.2.2",
    "@storybook/addon-knobs": "^4.1.13",
    "@storybook/vue": "^4.1.11",
    "@types/node": "^11.9.4",
    "@types/react": "^16.8.4",
    "@types/storybook__addon-knobs": "^4.0.1",
    "@types/storybook__vue": "^3.3.2",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.5",
    "babel-preset-vue": "^2.0.2",
    "ts-loader": "^5.3.3",
    "typescript": "^3.3.3",
    "vue-template-compiler": "^2.6.6",
    "vue": "^2.6.6"
```

Not exactly sure the `@types/react` is needed, but it's part of the docs for using knobs with TypeScript.

### `Component.stories.ts`

```ts
import { storiesOf, Story } from '@storybook/vue'
import { withKnobs, text } from '@storybook/addon-knobs'
import MyComponent from './MyComponent.vue'

const stories: Story = storiesOf('MyComponent.vue', module)

// This throws a type checking error
stories.addDecorator(withKnobs)

// This compiles and works as expected
stories.addDecorator(<any>withKnobs)

stories.add('as component', () => ({
  components: { MyComponent },
  props: {
    text: {
      default: text('Text', 'some text')
    }
  },
  template: '<my-component></my-component>'
})
```

**System:**
 - OS: Windows10
 - Device: Toshiba Satellite
 - Browser: N/A
 - Framework: Vue
 - Addons: knobs
 - Knobs Version: `4.1.13`
 - Knobs Types Version: `4.0.1` (This is latest)
 - Storybook Version: `4.1.11`

**Additional context**

This isn't a huge deal, just a minor annoyance as I cringe any time I have to use the `any` type.

**Comment by shilman** [comment]
Thanks for the bug! Unfortunately, we don't maintain the types on DefinitelyTyped and I'm not sure about what's the procedure for getting those updated.

The good news is that we're in the process of converting our codebase into Typescript, so you should be seeing those types defined "in house" in an upcoming release. You can check the progress and contribute yourself here: https://github.com/storybooks/storybook/issues/5030

Closing this for now! 🙇

**Comment by Jack-Barry** [comment]
Awesome, that will be great! Thanks @shilman
