### ISSUE TITLE
Custom theme is only applied after navigating to a story

### ISSUE THREAD

**Issue by pvdstel** [storybooks/storybook#5746]
**Describe the bug**
We're using the `@storybook/addon-options` package to set the theme of our Storybook app. This theme is not applied after loading the page, but is applied correctly after navigating to another story (one that's not selected by default). After this first navigation, the theme remains applied.

**To Reproduce**
1. Run `start-storybook -p 6006` and wait for the browser to open.
2. Observe that the correct theme is not applied.
3. Navigate to another story.
4. Observe that the theme is now applied.

**Expected behavior**
The theme should be applied right away.

**Screenshots**

Before navigation:

![image](https://user-images.githubusercontent.com/17430732/53323727-418af900-38df-11e9-9563-e15e983e4ea3.png)

After navigation:

![image](https://user-images.githubusercontent.com/17430732/53323742-4c458e00-38df-11e9-8c99-d99611930a70.png)

**Code snippets**
```js
const theme = getTheme(); // a function returning the result of the theme `create` function

addParameters({
    ...
    options: {
        ...
        theme: theme,
    },
    ...
});
```

**System:**
 - OS: Windows10
 - Device: desktop
 - Browser: Firefox, Chrome, Edge
 - Framework: React
 - Addons: options, viewport, knobs
 - Version: 5.0.0-rc.5

**Additional context**
If any other details are required, feel free to ask.

**Comment by fillipvt** [comment]
Similarly the default dark th8eme from `@storybook/theming` is only applied when reloading or navigating between stories (version: 5.0.0-rc.5)

**Comment by shilman** [comment]
Can you guys post how you're calling `create`? Re-assigning this to @ndelangen since apparently he's seen this one before.

**Comment by fillipvt** [comment]
I'm not using any custom theme but the dark theme still flashes. The implementation consists of:

```
import {configure, addParameters} from '@storybook/react'
import {themes} from '@storybook/theming'

addParameters({
  options: {
    theme: themes.dark
    /**
     * plus other configs
     */
  }
})

const req = require.context('../stories', true, /.stories.js$/)
function loadStories() {
  req.keys().forEach(filename => req(filename))
}

configure(loadStories, module)
```

If there's anything else I can provide let me know.

**Comment by ndelangen** [comment]
I'm on it

**Comment by ndelangen** [comment]
PR is ready

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.9 containing PR #5787 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
