### ISSUE TITLE
Viewport addon hidden by default, does not accept defaultViewport parameter

### ISSUE THREAD

**Issue by Jessidhia** [storybooks/storybook#5757]
**Describe the bug**
`@storybook/addon-viewport` crashes on initial render, which causes storybooks to render a blank page.

**To Reproduce**
It seems that all that you need is to specify a `defaultViewport`:
![image](https://user-images.githubusercontent.com/73085/53382807-c269f380-39b8-11e9-8066-db98f5c74fb7.png)

When it is converted by `toList`, it splits the string:

![image](https://user-images.githubusercontent.com/73085/53382851-e88f9380-39b8-11e9-8426-488d2ded3375.png)

When the list is eventually processed, `list.map` tries to access named properties but the only one that exists is `id`:

![image](https://user-images.githubusercontent.com/73085/53382972-5b007380-39b9-11e9-8563-92761a6a1b3b.png)

Which eventually crashes inside `createItem`:

![image](https://user-images.githubusercontent.com/73085/53382994-6ce21680-39b9-11e9-9003-7885ec124066.png)

**Expected behavior**
No crash.

**Screenshots**
It's a blank page, but I added screenshots of the debugger.

**System:**
 - OS: MacOS
 - Device: MBP
 - Browser: Chrome
 - Framework: Vue
 - Addons: viewport
 - Version: 5.0.0-rc.6

**Comment by Jessidhia** [comment]
Likely broken by https://github.com/storybooks/storybook/commit/a86e25f0403c5a729fffdf0606f06c7dd4be02c8#diff-0b19096a27d5827867e96b205e01a2ffR13 because it treats the `string` as an `object`, copying the enumerable properties.

**Comment by Jessidhia** [comment]
This seems to have been a misconfiguration: https://github.com/storybooks/storybook/tree/next/addons/viewport#change-the-default-viewport

(change from the alphas? or was it just misconfigured all along?)

**Comment by Jessidhia** [comment]
It seems the deprecation message in `configureViewport` is misleading.

**Comment by shilman** [comment]
NOTE: I can repro this in the official storybook in `next` and `master`

**Comment by tmeasday** [comment]
Thanks for the report @Jessidhia.

`.addParameters({ viewport: 'string' })` will no longer be supported (we need to it to be an object so it can be sensibly merged by the parameters system) but we need to (a) allow setting the default viewport and (b) not throw up if you do the old thing. See #5829

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.10 containing PR #5829 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.11 containing PR #5829 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
