### ISSUE TITLE
Search menu item broken

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#5772]
**Describe the bug**

Clicking on the 'search' menu item does not place focus in search box

Note:
- Typing `/` triggers the search
- Clicking in the search box triggers the search

**To Reproduce**
1. Go to https://next--storybooks-official.netlify.com/
2. Click menu > search
3. Start typing

**System:**
 - Browser: Chrome, Firefox
 - Version: 5.0.0-rc.6

**Comment by Phoenixton** [comment]
As far as I can see, this is due to the onClick() method of the search button in the toolbar not actually calling any api method to focus on the search text area, in nav.js. I'll try and change it tonight :)

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.6 containing PR #6027 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.2 containing PR #6027 that references this issue. Upgrade today to try it out!
