### ISSUE TITLE
Addon Panel -  Set to its max width and overlaps component after toggle

### ISSUE THREAD

**Issue by CodeByAlex** [storybooks/storybook#5779]
**Describe the bug**
Addon panel is moving to a max width when trying to switch from bottom to Left

**To Reproduce**
1. Set up a project for angular app with Storybook
2. Click on panel toggle and watch the addon panel widen far passed the component in view

**Expected behavior**
the addon panel should either be set to an acceptable width or fit to the component width with additional padding

**Screenshots**
![sidebar-too-far](https://user-images.githubusercontent.com/29763590/53447812-fd355100-39e3-11e9-9fba-76deda020e08.gif)

**System:**
 - Browser: [e.g. chrome, Firefox]
 - Framework: [Angular]
 - Version: [5.0.0-rc.6]

**Comment by n9niwas** [comment]
Also it doesn't remember resizing.  
If I set addons panel to render on the right side, manually adjust its width and reload the page - it still squishes the preview.  
In v4 it saved panel sizes.

**Comment by leerob** [comment]
In v4, the panel was never this large. I would love to see it returned to the same initial width as before. The large size becomes an issue when you default to opening on the right.

**Comment by shilman** [comment]
There are two bugs here:
- Choice of initial width, which should be a tweak
- Not remembering the layout, which AFAIK is supposed to work in v5

Hopefully it's a straightforward fix. Anybody wanna pick it up?

**Comment by Phoenixton** [comment]
I'm taking a look at this. Contrary to @leerob , my add-on panel on the right is way too small by default and I don't have any horizontal scrolling going on in it, so I'd love for it to actually be larger. But as you said, that should be a tweak. On the other hand, it definitely doesn't remember resizing, so that's what I'm gonna try to figure out.

**Comment by shilman** [comment]
@Phoenixton Thanks for picking this up! @ndelangen you worked on the layout, can you chime in here?

**Comment by wintercounter** [comment]
I want to be able to set maxWidth. Unfortunatelly it doesn't have any unique selector I'd be able to use from CSS.

**Comment by adberard** [comment]
downPanelInright: true in the the deprecated  setOptions() was working better than panelPosition: 'right'. 
How do we fix this ?

**Comment by shilman** [comment]
@adberard The whole UI was reimplemented, so the `downPanelInRight` vs `panelPosition` is just a naming change. The real issue here that the new UI needs some love. If you're interested in working on it, you can join our Discord and @ndelangen can help onboard you!

https://discord.gg/UUt2PJb
