### ISSUE TITLE
Addon-info not show component source props and props table correct

### ISSUE THREAD

**Issue by iamgbayer** [storybooks/storybook#5783]
**Describe the bug**
In story source, not is showing component props like example above, and the table not render borders correctly.

**Screenshots**
![screen shot 2019-02-27 at 00 41 03](https://user-images.githubusercontent.com/5483459/53464278-663eb800-3a28-11e9-900e-b8914377881a.png)

**Code snippets**
Story code
```js
storiesOf(`Button`, module)
  .addDecorator(withInfo)
  .addParameters({
    info: {
      inline: true,
      header: false,
      source: true
    }
  })
  .add('Default', () => <Button palette="primary">Example text</Button>)
```

Component code
```js
export const Button = styled.button`
  width: 110px;
  height: 36px;
  border-radius: 6px;
  border: none;
  cursor: pointer;
  ${switchProp('palette', {
    primary: css`
      background-color: ${theme.palette.mirage};
      color: ${theme.palette.white};
    `
  })};
`

Button.displayName = 'Button'

Button.defaultProps = {
  palette: 'primary'
}

Button.propTypes = {
  palette: PropTypes.oneOf(['primary', 'secondary'])
}
```

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2011]
 - Browser: [Chrome]
 - Framework: [React]
 - Version: [4.1.13]

**Comment by shilman** [comment]
Styling issue addressed reported and being addressed in #5278

The missing props is new. What is your webpack setup? Are you using `create-react-app`?

**Comment by guuibayer** [comment]
I'm not using **CRA**, I generate the storybook config with `npx -p @storybook/cli sb init`

**Comment by Ben07** [comment]
+1,how to display table border?

**Comment by arpitprod** [comment]
I added this css code inside '.storybook/preview-head.html' file and old storybook props table default css style showing

> 
	<style>
		.info-table, .info-table td, .info-table th {
			border-collapse: collapse;
			border: 1px solid #ccc;
			color: #444;
			margin-top: .25rem;
			padding-right: .5rem;
			padding: .25rem;
			text-align: left;
			vertical-align: top;
		}
		.info-table {
			width: 100%;
		}
		.info-table-monospace {
			font-family: Menlo, Monaco, "Courier New", monospace;
			font-size: .88em;
		}
    </style>

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
