### ISSUE TITLE
setOptions resets to the defaults

### ISSUE THREAD

**Issue by theKashey** [storybooks/storybook#5784]
**Describe the bug**

`setOptions(options)` would reset all not listed options to the default value.
basically, new options got merged with default ones, not the current ones.

**To Reproduce**
1. add setOptions({anything}) to the `.storybook/config.js`
2. open storybook with `full=1`
3. Page would be loaded with `full=0` (default)

**Expected behavior**
In 4-alpha it was working as expected, at the latest 4.1.12 it does not

**Code snippets**
If applicable, add code samples to help explain your problem.

https://github.com/storybooks/storybook/blob/master/lib/ui/src/modules/shortcuts/actions/shortcuts.js#L62-L65

```js
setOptions({ clientStore }, options) {
    clientStore.update(() => {
      const updatedOptions = {
        ...defaultState.shortcutOptions,
        ...pick(options, Object.keys(defaultState.shortcutOptions)),
      };
```

__this code was refactored in v5__, and I am not sure is it a problem for the next branch.

**Additional context**
I need to open storybook fullscreen using a deep link.

**Comment by shilman** [comment]
cc @tmeasday

**Comment by tmeasday** [comment]
Wow I have zero memory of this code change but I can say it got completely refactored for 5.0. 

My guess is there is a bit of a tension here between the use case @theKashey has (where the initial state set via query parameters needs to stick around, i.e. the state needs to be stateful), and the `parameters` API, where if one story sets and option and the next does not, we don't want the previous story's state to persist (i.e. we want it to be stateless).

I think I actually raised a similar point fairly recently with regards to the current v5 code so I'm not sure a solution has been found yet that satisfies both use cases? Do we want to try and fix in both branches?

**Comment by shilman** [comment]
@tmeasday Is this related? https://github.com/storybooks/storybook/issues/5781

**Comment by tmeasday** [comment]
@shilman - I don't think so. I imagine that one has something to do with refactorings in the story store that @ndelangen has made.

**Comment by shilman** [comment]
Closing this now that 5.0 is out. Please re-open if you're stuck on 4.x
