### ISSUE TITLE
Fix welcome component to work with dark theme

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#5785]
Currently the welcome component that `sb init` installs has no background and is unreadable with the dark theme. It's a detail, and presumably most people delete the story anyway, but it's an ugly detail. 😄 

<img width="753" alt="storybook" src="https://user-images.githubusercontent.com/488689/53474673-b2314180-3aa8-11e9-879e-aa2fdec497ff.png">

**Comment by francopetra** [comment]
Oh yes, I noticed. I can take a look at this.

**Comment by ndelangen** [comment]
Need any help @francopetra ?

**Comment by francopetra** [comment]
Hi @ndelangen! I don't know how to try sb init from my local repo (without a package manager like npm).
Thanks!

**Comment by ndelangen** [comment]
@francopetra Want to schedule a call? I can give you a tour around the codebase and show you how I work. And talk a bit about the roadmap and such.

The gist is that we have examples in the monorepo, so after bootstrapping you can just run one of those and see the changes.

**Comment by francopetra** [comment]
Sure! I would love to take a look at it. Will send you an email right away!

ps. Sorry for the delay, just moved to a different city.

**Comment by malykhinvi** [comment]
Hello everyone! @shilman what is the expected UI? White background or light text?
![5785](https://user-images.githubusercontent.com/5537715/54068797-91fc4200-4261-11e9-9f98-664a702c1194.png)

@francopetra if you don't have enough bandwidth to work on this issue, I would love to contribute as well.

**Comment by shilman** [comment]
Yeah I think white background is the simplest thing. It's a simple fix, but it should be applied to all the different frameworks (React, Vue, Angular, etc. etc.)

**Comment by francopetra** [comment]
> Hello everyone! @shilman what is the expected UI? White background or light text?
> ![5785](https://user-images.githubusercontent.com/5537715/54068797-91fc4200-4261-11e9-9f98-664a702c1194.png)
> If I understand correctly, component look and feel should not depend on theme in this case, so white background is expected, right?
> 
> @francopetra if you don't have enough bandwidth to work on this issue, I would love to contribute as well.

@maacky I see you already moved forward, so go ahead!

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.4 containing PR #5998 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.2 containing PR #5998 that references this issue. Upgrade today to try it out!
