### ISSUE TITLE
Static `official-storybook` is broken on `next`

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#5788]
**Describe the bug**

The dev branch of Storybook doesn't load:

https://next--storybooks-official.netlify.com/

The error in the browser console is:

```
index.js:2 TypeError: function call() { [native code] } is not a function!
    at axe.js:12
    at J (axe.js:12)
    at Q (axe.js:12)
    at Yt (axe.js:12)
    at axe.js:12
    at Object.<anonymous> (axe.js:12)
    at Object.<anonymous> (axe.js:12)
    at __webpack_require__ (bootstrap:2)
    at Object.<anonymous> (index.js:9)
    at __webpack_require__ (bootstrap:2)
```

**To Reproduce**

I can reproduce locally:

```
yarn bootstrap --reset --core
cd examples/official-storybook
yarn build-storybook
cd storybook-static
serve
open http://localhost:5000
```

**NOTE:** I'm NOT able to reproduce this locally when I run it in dev mode. 

**Expected behavior**
Expect stories to load

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [chrome, safari]
 - Framework: [react]
 - Addons: [a11y + many more]
 - Version: [next]

**Comment by shilman** [comment]
Thankfully this does not repro on the `release/5.0` branch

**Comment by karltaylor** [comment]
I had a problem with storybook not fully compiling, no errors / warnings on `4.1.13`. Rolled back to `4.1.6` and everything was fine

**Comment by ndelangen** [comment]
Seems related to simple-bars

**Comment by ndelangen** [comment]
correction axe related possibly

**Comment by ndelangen** [comment]
PR with a fix is open

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.9 containing PR #5816 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
