### ISSUE TITLE
Add a way to disable docgen integration

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybook#579]
Sometimes, docgen support may cause issues.
So, we should provide a way to disable it.

**Comment by cubodehelio** [comment]
This would be cool. For me this is specially annoying when using the `addon-info` addon. I'm looking for a way to disable it. I have a bunch of documented components and that documentation looks ugly in the info panel, they are all mixed up with the actual info (the one that i had written for the info panel) and there is no way to avoid it other than either removing the components documentation (which I can't) or not to write the info text at all.

**Comment by quinn** [comment]
This is (as far as I can tell) breaking my ability to use storybook. Can this be reopened ?
