### ISSUE TITLE
run the server without opening the browser?

### ISSUE THREAD

**Issue by ianstormtaylor** [storybooks/storybook#5798]
**Is your feature request related to a problem? Please describe.**

Right now it doesn't seem like there's a way to run the server without having it open up a tab in the browser when the server starts? This is frustrating for situations where you have a `yarn start` command that does multiple things, one of which is Storybook. You end up having to keep closing the tab each time you re-run `yarn start`.

**Describe the solution you'd like**

It would be nice to have a CLI flag to prevent the browser opening.

**Comment by shilman** [comment]
There is!

```
--ci                          CI mode (skip interactive prompts, don't open browser
```

**Comment by ianstormtaylor** [comment]
Ah wow I'm an idiot, thank you! That's perfect.
