### ISSUE TITLE
Docgen causes HoC to stop working

### ISSUE THREAD

**Issue by jeffijoe** [storybooks/storybook#580]
Opening a new issue as requested in #557

After that react docgen babel plugin was added, my stuff stopped working. Trimmed down example:

Component:

``` js
export function hoc (Inner) {
  const C1 = (props) => <div />
  const C2 = (props) => <div />
  return {
    C1,
    C2
  }
}
```

Story:

``` js
import { hoc } from './hoc'

const Test = () => <div/>
const { C1, C2 } = hoc(Test)
// etc etc
storiesOf(...)
```

Error:

```
ReferenceError: C1 is not defined
```

I think this happens because C1 is out of scope or something.

**Comment by arunoda** [comment]
Yep. I can understand the issue.
I'll do a fix today.

**Comment by arunoda** [comment]
@madushan1000 check the above code, I think we've a problem in babel-plugin when detecting these.
BTW: We should try to detect only top level functions.

We could try something like this for a hot fix:

```js
if (typeof CalendarDay !== 'undefined') {
   CalendarDay.__docgenInfo = {...};
}
```

This is **ASAP**.

**Comment by madushan1000** [comment]
I can't reproduce the issue with the above code. Plugin shouldn't inject any code at all here since `react-docgen` doesn't detect any react components. It returns an error and that error is handled internally by the plugin. 
Maybe a more comprehensive example would help.

**Comment by jeffijoe** [comment]
@madushan1000 how about:

```js
export function hoc (Inner) {
  const C1 = (props) => <ActualC1 {...props} />
  const C2 = (props) => <ActualC2 {...props} />
  return {
    C1,
    C2
  }
}

class ActualC1 extends React.Component {
  render() { return <div/> }
}

class ActualC2 extends React.Component {
  render() { return <div/> }
}
```

**Comment by madushan1000** [comment]
@jeffijoe great. I'll try with this.

**Comment by madushan1000** [comment]
Even with this code, neither the plugin nor react-docgen gives any output.

**Comment by jeffijoe** [comment]
That's odd. 🤔

**Comment by jeffijoe** [comment]
I also noticed that the problem goes away after a rebuild, but if you Ctrl+C to exit Storyboo and then run it again, problem is back.

**Comment by jeffijoe** [comment]
Problem is gone now, just updated to 2.28.1.

**Comment by madushan1000** [comment]
Do you know what was the previous version? I need to track down the problem.

**Comment by madushan1000** [comment]
@arunoda I guess we probably don't need kadirahq/babel-plugin-react-docgen/pull/18 now?

**Comment by jeffijoe** [comment]
Last working version was 2.24.

**Comment by madushan1000** [comment]
@jeffijoe Do you remember the version you had the issue with?

**Comment by wallslide** [comment]
I have this problem on version `2.28.1`

**Comment by jeffijoe** [comment]
@madushan1000 it started at 2.25 I believe

**Comment by Monar** [comment]
Same here.
Last working version `2.24.1`, problem still present with `2.28.1`.

Generated code:
```
const wrapComopnent = exports.wrapComponent = (Component) => {
  const WrappedComponent = props => _react2.default.createElement(
    Wrapper,
    { },
    _react2.default.createElement(Component, props)
  );
  return WrappedComponent;
};

[...]

class Wrapper extends _react2.default.Component { ... }

[...]
WrappedComponents.__docgenInfo = {
  description: '',
  props: {
    children: {
      type: {
        name: 'union',
        value: [{
          name: 'array'
        }, {
          name: 'element'
        }]
      },
      required: false,
      description: ''
    },
    isRelative: {
      type: {
        name: 'bool'
      },
      required: false,
      description: '',
      defaultValue: {
        value: 'true',
        computed: false
      }
    }
  }
};

```

And error occurs for line `WrappedComponents.__docgenInfo = {`
This was generated from:
```
class Wrapper extends React.Componen {...}
```
```
export const wrapComopnent = (Component) => {
  const WrappedComponent = props => (
    <Wrapper>
        <Component/>
    </Wrapper>
  );
  return WrappedComponent;
};
```

**Comment by arunoda** [comment]
Hey guys,

We update storybook with a [potential fix](https://github.com/kadirahq/babel-plugin-react-docgen/pull/17) done by @madushan1000.

Could you try to update @kadira/storybook to version `2.29.0`.

**Comment by Monar** [comment]
Version `2.29.0` is working again. Thanks, Good Job!
