### ISSUE TITLE
addon-jest display wrong result

### ISSUE THREAD

**Issue by tourniquet** [storybooks/storybook#5809]
**Describe the bug**
Hi guys! I'm trying to use addon-jest for a few projects I am working on, but there is a weird bug. 

I have a component called Button, but I also have other components called SwitcherButton, ToggleTypeButton, FixedButton, and so on. In my Button.story.js I have specified that it should look for the Button.test.js like this:

```javascript
.addParameters({ jest: ["Button"] })
```

But when the jest JSON test report is generated, the test results of these button components appear in random order, and addon-jest simply picks the first match of the string "Button", so that means that it sometimes shows the test result of ToggleTypeButton.test.js or SwitcherButton.test.js and so on, instead of actually showing the test result of the Button.test.js.

I have tried several regex expressions instead of simply writing "Button" but with no luck.

The only solution I have found is that I rename my Button.test.js to something more unique like CustomButton.test.js but I would prefer to keep the name short and not change the name of a lot of existing components/tests.

So I have 2 questions:
1. Is there a way to specify an exact name/path for the test, so I'm sure that it will pick up the right test results?
2. Is it possible that somebody can update the logic in addon-jest to find an exact match and not allow that the name is partially found in the test result name?

**To Reproduce**
- Add at least two tests: "Button" and "MyButton"
- Generate the test report until the MyButton.test.js is executed before the Button.test.js. 
- Add a Button.story.js and link it with the test like:
```javascript
.addParameters({ jest: ["Button"] })
```
- Start the storybook
- Go to the Button and see the test results in the panel

**Expected behavior**
addon-jest must display correct test results for the component

Correct result:
![breadcrumbnavigation](https://user-images.githubusercontent.com/9606815/53632020-cd689200-3c0b-11e9-85bc-bd300a180ffc.png)

Wrong result:
![book](https://user-images.githubusercontent.com/9606815/53632019-cd689200-3c0b-11e9-8c96-eb2a9f7596c7.png)

**Code snippets**
*.storybook/config.js*
```javascript
import results from "../jest-test-results.json";

import { withTests } from "@storybook/addon-jest";

addDecorator(
  withTests({
    results
  })
);
```

*Example of generated JSON*
```json
{
  "assertionResults":[
    {
      "ancestorTitles":[],
      "failureMessages":[],
      "fullName":"SwitcherButton: renders without crashing"...
{
  "assertionResults":[
    {
      "ancestorTitles":[],
      "failureMessages":[],
      "fullName":"ToggleTypeButton: renders without crashing"...

{
  "assertionResults":[
    {
      "ancestorTitles":[],
      "failureMessages":[],
      "fullName":"FixedRefreshButton: renders without crashing"...

{
  "assertionResults":[
    {
      "ancestorTitles":[],
      "failureMessages":[],
      "fullName":"Button: renders without crashing"...
```

**Comment by ndelangen** [comment]
@tourniquet would you be interested in helping us fix this issue?

The jest addon can be improved a lot I think, I just haven't have had the time yet.

**Comment by tourniquet** [comment]
@ndelangen , unfortunately, I don't have enough knowledge to fix this issue

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.31 containing PR #6539 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
