### ISSUE TITLE
Backgrounds addons do not show by default

### ISSUE THREAD

**Issue by hipstersmoothie** [storybooks/storybook#5818]
**UPDATE:**

This issue describes problems with both `addon-backgrounds` and `addon-viewports`. The viewports bug is a duplicate to #5757, so I'm reappropriating this issue to backgrounds since it's a separate work item. --@shilman

---

**Describe the bug**

addon-backgrounds and addon-viewport do not display in any way

**To Reproduce**
1. Go to https://github.com/hipstersmoothie/story-bug
2. Click on `yarn && yarn storybook`
3. backgrounds and viewport do not display

**Expected behavior**

Should display

**Screenshots**

![screen shot 2019-03-01 at 11 13 29 pm](https://user-images.githubusercontent.com/1192452/53678716-ae074e80-3c77-11e9-93fc-fb4f6bb5190c.png)

**System:**
 - OS: Mac High Sierra
 - Device:  Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Addons: viewport, backgrounds
 - Version: 5.0.0-rc.8

**Comment by hipstersmoothie** [comment]
I got it to work but only by doing the following 

```ts
stories.add('Basic', () => <Card style={styles}>I'm a simple card</Card>, {
  notes: {
    markdown
  },
  backgrounds: [
    { name: 'white', value: 'white', default: true },
    { name: 'twitter', value: '#00aced' },
    { name: 'facebook', value: '#3b5998' }
  ]
});
```

**Comment by hipstersmoothie** [comment]
It seems like this can also be done for the viewport with

```
addParameters({
  backgrounds: [
    { name: 'white', value: 'white', default: true },
    { name: 'twitter', value: '#00aced' },
    { name: 'facebook', value: '#3b5998' }
  ],
  viewports: INITIAL_VIEWPORTS
});
```

all current documented ways are incorrect (i think)

**Comment by shilman** [comment]
@hipstersmoothie Great catch, we should fix this before launch.

Your repo also revealed another good one: https://github.com/storybooks/storybook/issues/5822

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.10 containing PR #5828 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.11 containing PR #5829 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by Pushplaybang** [comment]
@shilman @hipstersmoothie  - not certain if this is related, but currently using the viewport addon obscures the very useful background grid, let me know if this should be a separate issue.
