### ISSUE TITLE
Base themes broken in v5

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#5824]
### Example 1

```js
addParameters({
  options: {
    theme: create({
      base: 'dark',
	}
  }
});
```

Results:
- No dark theme
- Warnings about missing primary/secondary colors

### Example 2

```js
addParameters({
  options: {
    theme: create({
      base: 'dark',
      colorPrimary: 'red',
      colorSecondary: 'green',
	}
  }
});
```

Results:
- No dark theme
- No warnings about missing primary/secondary colors

**System:**
 - Version: 5.0.0-rc.9

**Comment by ndelangen** [comment]
I'll make this work:

```js
create({
  base: 'dark',
  colorPrimary: 'red',
  colorSecondary: 'green',
});
```

**Comment by ndelangen** [comment]
PR is open

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.11 containing PR #5843 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
