### ISSUE TITLE
React - No Knobs on build

### ISSUE THREAD

**Issue by ohelixa** [storybooks/storybook#5847]
**Describe the bug**
after building storybook components are exported as so:

`Button_Button`

Setting `Button.displayName = "Button"` will fix the visual presentation but still on build file I see wrong naming. This makes the Knob addon showing : No Knobs.

From the bundle file:

```
Button_Button=function(_ref){var disabled=_ref.disabled,tag=_ref.tag,as=_ref.as,onClick=_ref.onClick,onMouseOver=_ref.onMouseOver,onMouseOut=_ref.onMouseOut,rest=Object(objectWithoutProperties.a)(_ref,["disabled","tag","as","onClick","onMouseOver","onMouseOut"]);return react_default.a.createElement(StyledButton,Object.assign({as:!as&&tag?tag:as,disabled:disabled,onClick:onClick,onMouseOver:onMouseOver,onMouseOut:onMouseOut},rest))};Button_Button.displayName="Button",Button_Button.defaultProps={tag:"button",type:"button",variant:"standard",size:"medium",disabled:!1};__webpack_exports__.a=Button_Button;
```

devDependecies:

```
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@storybook/addon-actions": "^4.1.13",
    "@storybook/addon-info": "^4.1.13",
    "@storybook/addon-jest": "^4.1.13",
    "@storybook/addon-knobs": "^4.1.13",
    "@storybook/addon-links": "^4.1.13",
    "@storybook/addon-options": "^4.1.13",
    "@storybook/addons": "^4.1.13",
    "@storybook/react": "^4.1.13",
    "babel-cli": "^6.26.0",
    "babel-loader": "^8.0.5",
    "eslint-config-airbnb": "17.1.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.0",
    "jest-junit": "^6.3.0",
    "node-sass": "^4.11.0",
    "storybook-addon-smart-knobs": "^4.1.0"
  },
  "peerDependencies": {
    "styled-components": "^4.1.3"
  }
```

**To Reproduce**
1. Go to http://components.helixa.ai.s3-website-us-west-2.amazonaws.com
2. Click on Button -> dynamic

**Expected behavior**
Expected correct export

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react, styled components
 - Addons: jest, info, knobs
 - Version: [e.g. 4.0.0]

**Comment by Armanio** [comment]
Hi @ohelixa
Could you confirm issue if he actually. I don't can reproduce.

I see you button component, no error, correct name.
What i did wrong? 🤔

**Comment by ohelixa** [comment]
@Armanio Hi, with the v5 everything got fixed beside the fact that if you look at: "Prop Types" you will see that propType column is showing "other" as value. This is happening only on bundle.

If you go to FormItem component "No propTypes defined!" yet again only on bundle.
