### ISSUE TITLE
[5.0.0-rc.10] Switching stories results in breaking storybook 

### ISSUE THREAD

**Issue by daKmoR** [storybooks/storybook#5852]
**Describe the bug**
Switching between stories pretty fast or multiple times results in
```
Cannot read property 'nextSibling' of null
```

**To Reproduce**
```bash
git clone https://github.com/daKmoR/storybook-bug-5852.git
cd storybook-bug
yarn install
yarn storybook

# In storybook switch between stories a few times
```

**Expected behavior**
Working storybook.

**Screenshots**
![storybook-bug](https://user-images.githubusercontent.com/24378/53763963-56adec00-3ecc-11e9-917f-250a6e3e1655.gif)

**Comment by daKmoR** [comment]
apparently, it has to do with this
```js
  .add('Alternative Header asdf', () => {
    const el = document.createElement('div');
    el.innerText = 'something';
    return el;
  })
```

e.g. if you return a node and then you switch multiple times then it "breaks" with this "fatal" error and you are forced to do a hard reload.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.4 containing PR #5868 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by daKmoR** [comment]
@shilman any chance this can be released for 5.0.x? or how far away is 5.1.x?

**Comment by shilman** [comment]
Will do. 5.1 a few weeks off

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.11 containing PR #5868 that references this issue. Upgrade today to try it out!
