### ISSUE TITLE
SB5 UI: improve viewport usability

### ISSUE THREAD

**Issue by backbone87** [storybooks/storybook#5879]
It would be nice, if we could see the selected viewport right next to the viewport button.
- Always show pixel size
- show label if selected
- show L or P for orientation

**Comment by backbone87** [comment]
another thing: show a rotate button when a viewport is selected, so you dont have to open the dropdown to do it

**Comment by lucas-carl** [comment]
I would like to work on this!

**Comment by shilman** [comment]
Cc @ndelangen

**Comment by backbone87** [comment]
partially implemented in #6045

missing:

> Always show pixel size

**Comment by ndelangen** [comment]
Looks like we have this feature?

<img width="1498" alt="Screenshot 2019-04-19 at 00 05 39" src="https://user-images.githubusercontent.com/3070389/56394228-ed452b00-6236-11e9-9fb9-59f90763fdbc.png">
