### ISSUE TITLE
v5 upgrade guide, webpack modules vs module

### ISSUE THREAD

**Issue by SamKirkland** [storybooks/storybook#5883]
**Describe the bug**
Migration guide mistake. In the ["webpack config simplification"](https://github.com/storybooks/storybook/blob/next/MIGRATION.md#webpack-config-simplifcation) area, the code example uses: `config.modules.rules.push` when it should be `config.module.rules.push`
(modules should be module)
[The webpack config page](https://github.com/storybooks/storybook/blob/next/docs/src/pages/configurations/custom-webpack-config/index.md) is correct :)

**To Reproduce**
1. Open ["webpack config simplification"](https://github.com/storybooks/storybook/blob/next/MIGRATION.md#webpack-config-simplifcation) 
2. See the code example

**Expected behavior**
`module` is correct
`modules` is incorrect

**Other**
Just want to say this is one of the best libraries i've ever used. Keep up the great work.

**Comment by SamKirkland** [comment]
Resolved by PR: #5881

**Comment by tmeasday** [comment]
Thanks @SamKirkland and thanks for the kind words!
