### ISSUE TITLE
Provide React Native WS Server as Addon for React Storybook

### ISSUE THREAD

**Issue by MrLoh** [storybooks/storybook#5886]
**Describe the solution you'd like**
My company builds a shared component library between react-native and react-web projects. So I have a setup for storybook where stories are both rendered on the web with storybook/react and on native with storybook/react-native. That all works fine, but when developing, we have to manually keep the web and native views in sync. The storybook server for react-native already provides a nice way to control the native components, but it runs separate from the web stories. 

Would it be possible to use the react web storybook to not only display the same components as the native app, with react-native-web, but also send the messages via the web socket to synchronize the displayed web stories with the native stories? 

**Are you able to assist bring the feature to reality?**
I could definitely help with this, I am just not sure how the web socket server is set up, I briefly skimmed the code, but a brief introduction would be very helpful. I am not sure what the best way to set this up would be. Should this be an Addon, or a custom configuration of the web sever?

**Comment by MrLoh** [comment]
@Hypnosphi could you give me a pointer as to how I would go about building this. I understand that the react native [server](https://github.com/storybooks/storybook/tree/master/app/react-native/src/server) sets up a websocket server that forwards messages to all connected clients and that the [manager](https://github.com/storybooks/storybook/tree/master/app/react-native/src/manager) emits the story selection events. But I don't understand how I'd go about adding a web socket server to the 'standard' react storybook server and how I'd inject a similar Provider into the 'standard' react storybook server. I have a repo here that shows my current setup: https://github.com/MrLoh/universal-react-storybook

**Comment by shilman** [comment]
@MrLoh I would recommend that you wait for the next version of `@storybook/react-native` before you embark on this. Specifically there is a major refactor that's been blocked for a couple months but apparently is "very close to ready" and it's sitting in this PR: https://github.com/storybooks/storybook/pull/4942 Any work done on RN before this merge is likely to be superceded by the new code.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.12 that addresses this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
We’ve released a brand new `@storybook/react-native` with a bunch of core improvements. It’s available in the latest `5.1-alpha` on `next` and has been verified by several RN users on their existing apps. It should fix a bunch of compatibility issues, especially if you’re using the web server feature. Please give it a try and comment here if it fixes your problem. Migration instructions available here: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-native-server

@MrLoh

**Comment by shilman** [comment]
We're on `5.1.0-beta` now. Check it out!
