### ISSUE TITLE
Addons breaking App

### ISSUE THREAD

**Issue by glockjt** [storybooks/storybook#5887]
**Describe the bug**
I first started by just adding one addon and was getting this error (in screenshots below) but then I added the kitchen-sink of all the addons and still got this error.

**To Reproduce**
1. Install the latest and greatest of storybook, material-ui/core, react, react-dom, and all the addons from the kitchen-sink example
2. Setup as described in docs.
3. Add addons to `addon.js`.
4. Add `addParameters` as in the kitchen-sink
5. run `start-storybook -p 9001 -c .storybook`
6. See error

**Expected behavior**
For the app to load as if no addons were added.

**Screenshots**
![image](https://user-images.githubusercontent.com/2473335/53836989-489cb180-3f46-11e9-8d04-558ee9cd5253.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Browser: chrome
 - Framework: react
 - Addons: all official
 - Version: 5.0.0

**Comment by tmeasday** [comment]
Hi @glockjt - what was the first addon you added that saw the error?

**Comment by glockjt** [comment]
@tmeasday this is my fault.  I installed storybook the other day and installed the addons today.  So it was a version mismatch.  I was running storybook 4.* and the addons were v5.  I just updated storybook to v5 and everything is fine.  My apologies again.

**Comment by tmeasday** [comment]
No worries! Glad you figured it out! Enjoy SB5
