### ISSUE TITLE
Error on v5 upgrade

### ISSUE THREAD

**Issue by korede360** [storybooks/storybook#5888]
**Describe the bug**
After upgrading to v5, I get the error `Uncaught TypeError: Cannot read property 'Consumer' of undefined` and a blank screen.
**To Reproduce**
Upgrade a project from v4.1.4 to v5

**Expected behavior**
I expected it to work flawlessly, and see my stories.

**Screenshots**
![image](https://user-images.githubusercontent.com/15985212/53837697-8247d980-3f93-11e9-87c1-932c2149a456.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2012
 - Browser: chrome
 - Framework: react
 - Addons: none
 - Version: 5.0.0

**Additional context**
None

**Comment by tmeasday** [comment]
Hi @korede360 - can you show the contents of your `package.json`?

You could try removing `node_modules` and `yarn.lock`/`package-lock.json` and reinstalling -- it could be a messed up set of modules.

**Comment by Sycoraxya** [comment]
@tmeasday 
I had the same problem and that solution fixes it for me

**Comment by tourniquet** [comment]
@tmeasday , thank you! This solution worked for me!

**Comment by korede360** [comment]
@tmeasday Your solution works! Thanks a lot.

**Comment by tmeasday** [comment]
:/

**Comment by nkov** [comment]
I am having this issue and reinstalling modules did not help.
