### ISSUE TITLE
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by artemirq** [storybooks/storybook#5892]
**Describe the bug**

When I upgraded Storybook from `4.0.9` to `5.0.0`, by starting `start-storybook`, I give error (see screenshot below)

**Expected behavior**

Storybook works without errors

**Screenshots**

![image](https://user-images.githubusercontent.com/17342159/53846231-3447cb80-3fbd-11e9-973e-851b465e2952.png)

**System:**
 - OS: `Windows 10`
 - Framework: `React`
 - Addons: `@storybook/addon-actions@5.0.0`, `storybook-addon-material-ui@0.9.0-alpha.17`, `storybook-addon-intl@2.4.0`
 - Version: `5.0.0`

**Additional context**

This error stack doesn't give any information with which file have problem

**Comment by Razzwan** [comment]
The same error

**Comment by shilman** [comment]
Any chance you can provide a sample repo?

**Comment by artemirq** [comment]
@shilman So I found reason. When I disable `storybook-addon-material-ui`, Storybook works normally. This issue related to `storybook-addon-material-ui` repository

**Comment by artemirq** [comment]
I close this issue in [favour](https://github.com/react-theming/storybook-addon-material-ui/issues/92) at `storybook-addon-material-ui` repo
