### ISSUE TITLE
Preview doesn't load svg components correctly

### ISSUE THREAD

**Issue by yingzuo** [storybooks/storybook#5898]
**Describe the bug**
Preview doesn't render the svg files imported as a React component correctly even with the custom webpack config. It always looks for the svg file under static/media. 

**To Reproduce**
1. import the svg as a React component
```
import Logo from "../icons/logo.svg";

export function container() {
  return <div>
      <Logo />
  </div>;
}
```

2. Run "start-storybook -p 6006 -c .storybook"

3. Storybook ui is loaded with the preview of components.  Error is shown on the preview of the container component.
Failed to execute 'createElement' on 'Document': The tag name provided ('static/media/logo.717fead6.svg') is not a valid name.
Error: Failed to execute 'createElement' on 'Document': The tag name provided ('static/media/logo.717fead6.svg') is not a valid name.

**Expected behavior**
The component is rendered correctly with the svg file.

**Code snippets**
webpack.config.js
```
const path = require('path');

module.exports = {
    module: {
        rules: [
            {
                test: /\.scss$/,
                loaders: ['style-loader', 'css-loader', 'sass-loader'],
                include: path.resolve(__dirname, '../'),
            },
            {
                test: /\.(js|jsx|mjs)$/,
                loader: require.resolve('babel-loader'),
                options: {
                    cacheDirectory: true,
                },
            },
            {
                test: /\*.svg$/,
                use: [
                    {
                        loader: require.resolve("babel-loader")
                    },
                    {
                        loader: require.resolve("react-svg-loader"),
                        options: {
                            jsx: true
                        }
                    }
                ]
            }
        ],
    },
};
```

**System:**
 - OS: MacOS
 - Browser: Chrome
 - Framework: React
 - Version: 5.0.0

**Comment by shilman** [comment]
Yeah, hope to fix that today! Closing this as a duplicate to #5708
