### ISSUE TITLE
Middleware should enforce trailing / or use <base href>

### ISSUE THREAD

**Issue by ericclemmons** [storybooks/storybook#590]
Hi!  Given:

```js
const storybook = require("@kadira/storybook/dist/server/middleware").default;
app.use("/stories", storybook(".storybook"));
```

Navigating to `/stories` results in a `404` of `manager.bundle.js` because it's loaded at `/static/manager.bundle.js` instead of `/stories/static/manager.bundle.js`.

There are two solutions to this:

- Add `<base href="${req.path}/" />` or equivalent in the the HTML.
- Enforce the trailing slash in the middleware.

I can submit a PR for either depending on your preference.

**Comment by arunoda** [comment]
@mnmtanish could you co-ordinate this?

**Comment by mnmtanish** [comment]
I'll check it out

**Comment by ndelangen** [comment]
Hey @ericclemmons Sounds like enforcing a trailing slash will be easy to do! Want to make that PR?

I'm also interested in a PR describing how to inject storybook within an express app, as you're doing I believe ?

**Comment by ericclemmons** [comment]
This is what I have in our code now:

```js
import { Router as router } from "express";
import storybook from "@kadira/storybook/dist/server/middleware";


export default router()
  .use(
      // Redirect stories to stories/, due to relative URLs
    (req, res, next) => {
      if (req.originalUrl === "/stories") {
        return res.redirect("/stories/");
      }

      next();
    },
     storybook(".storybook")
   )
 ;
```

Our app has docs, tools, stories, etc. all available when in development.  (We found that no one runs stories if it's a separate process/script.  Plus, we need the API  access.)

**Comment by ndelangen** [comment]
@ericclemmons Do you think you could write a blogpost & a section in our documentation detailing this and why it's working out so well for you?
