### ISSUE TITLE
[5.0.0] Error message when removing value from number knob

### ISSUE THREAD

**Issue by web-padawan** [storybooks/storybook#5912]
**Describe the bug**
When removing the value from the "number" knob, following error appears in the console:

<details>
<summary>Full log</summary>
<pre>
Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    in input (created by Context.Consumer)
    in Input (created by NumberType)
    in NumberType (created by PropForm)
    in label (created by Context.Consumer)
    in Styled(label) (created by Field)
    in Field (created by PropForm)
    in form (created by Context.Consumer)
    in Styled(form) (created by PropForm)
    in PropForm (created by KnobPanel)
    in div (created by Context.Consumer)
    in Styled(div) (created by KnobPanel)
    in KnobPanel
    in div (created by Context.Consumer)
    in Styled(div)
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by Context.Consumer)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Panel)
    in Panel (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in Main (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout) (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ResizeDetector
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
Warning: A component is changing a controlled input of type number to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (created by Context.Consumer)
    in Input (created by NumberType)
    in NumberType (created by PropForm)
    in label (created by Context.Consumer)
    in Styled(label) (created by Field)
    in Field (created by PropForm)
    in form (created by Context.Consumer)
    in Styled(form) (created by PropForm)
    in PropForm (created by KnobPanel)
    in div (created by Context.Consumer)
    in Styled(div) (created by KnobPanel)
    in KnobPanel
    in div (created by Context.Consumer)
    in Styled(div)
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by Context.Consumer)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Panel)
    in Panel (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in Main (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout) (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ResizeDetector
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
</pre>
</details>
<br>

**To Reproduce**
1. Add number knov
2. Remove the value
3. See error in the console

**Expected behavior**
No error in the console.

**Screenshots**
![number-error](https://user-images.githubusercontent.com/10589913/53867290-33825a00-3ffc-11e9-92d1-581ec1cb3191.gif)

**System:**
 - OS: Mac OS
 - Device: Macbook Pro 2017
 - Browser:  Chrome, Safari, Firefox
 - Framework: Polymer
 - Addons: knobs
 - Version: 5.0.0

**Additional context**
Seems like the same as #2475 which was previously fixed, could be a regression.

**Comment by IshaTr** [comment]
@web-padawan @shilman Hey do you mind if I take this issue up?

**Comment by shilman** [comment]
@IshaTr Go for it! 👍

**Comment by toshi1127** [comment]
@IshaTr 
@shilman 
I'm sorry if you put your hand on
I tried to fix it.

**Comment by IshaTr** [comment]
@toshi1127 are you done with the fix?

**Comment by toshi1127** [comment]
@IshaTr 
I fixed it, so I opened PR！

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.5 containing PR #6043 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
