### ISSUE TITLE
Searching for component broken on static build

### ISSUE THREAD

**Issue by michaelfarrell76** [storybooks/storybook#5914]
**Describe the bug**
I recently upgraded to v5. I have a relatively simple storybook setup. I can run the `start-storybook` and get a functional storybook environment no problem. I can search components and everything

 But when I use `build-storybook` and host the assets using `http-server`, everything loads up fine and all of my stories show, however when I try to search, the components do not get filtered and if I peak in the console  I can see a couple errors:
```
TypeError: t.parameters.fileName.includes is not a function. (In 't.parameters.fileName.includes(e)', 't.parameters.fileName.includes' is undefined)

TypeError: e.toLocaleLowerCase is not a function. (In 'e.toLocaleLowerCase()', 'e.toLocaleLowerCase' is undefined)
``` 

**To Reproduce**
1. Create a static build: `STORYBOOK_ON=true build-storybook -c .storybook -o .storybook-dist`
2. Host the build `http-server .storybook-dist`
3. Search anything
4. Open console and see error with no search on components

**Expected behavior**
I should be able to search components by name when using a static build.

**Screenshots**
<img width="1300" alt="screen shot 2019-03-06 at 1 08 27 am" src="https://user-images.githubusercontent.com/10264973/53869440-1f633c00-3fad-11e9-9ae8-f80a3aed53e8.png">
<img width="222" alt="screen shot 2019-03-06 at 1 08 34 am" src="https://user-images.githubusercontent.com/10264973/53869442-1f633c00-3fad-11e9-9ae5-3e6983e59157.png">

**Code snippets**

My webpack:
```

const path = require('path');
const { existsSync } = require('fs');

const pkgPath = path.join(__dirname, '../../package.json');
const { theme } = existsSync(pkgPath) ? require(pkgPath) : {}; // eslint-disable-line import/no-dynamic-require

module.exports = {
  mode: 'development',

  // In production, we skip all hot-reloading stuff
  entry: [path.join(process.cwd(), 'src')],

  module: {
    rules: [
      {
        test: /\.less$/,
        use: [
          'style-loader',
          'css-loader',
          `less-loader?{"sourceMap":true,"modifyVars":${
            JSON.stringify(theme)}, "javascriptEnabled":true}`,
        ], // compiles Less to CSS
      },
    ],
  },
  plugins: [
  ],
  resolve: {
    modules: ['src', 'node_modules'],
    extensions: [
      '.ts',
      '.tsx',
      '.js',
      '.jsx',
      '.react.js',
    ],
  },
};
```

my babel.config.js
```
module.exports = {
  presets: [
    '@babel/preset-env',
    '@babel/preset-react',
  ],
  plugins: [
    '@babel/plugin-proposal-class-properties',
    'babel-plugin-styled-components',
    ['import', {
      libraryName: 'antd',
      libraryDirectory: 'lib',
      style: true,
    }],
  ],
  env: {
    test: {
      plugins: [
        'require-context-hook',
      ],
    },
  },
};
```

**System:**
 - OS: MacOs and Netlify (linux)
 - Device: Macbook Pro 2018 and Netlify
 - Browser: chrome and safari
 - Framework: react
 - Addons:
   "@storybook/addon-actions": "^5.0.0",
    "@storybook/addon-links": "^5.0.0",
    "@storybook/addon-storyshots": "^5.0.0",
    "@storybook/addons": "^5.0.0",
 - Version: 5.0.0

**Additional context**

**Comment by wuweiweiwu** [comment]
I just also recently discovered this. thanks @michaelfarrell76

**Comment by shilman** [comment]
Thanks for the report! This is duplicate to #5907 where there's also a solution PR pending. Closing for now 👍
