### ISSUE TITLE
Search doesn't search on static storybooks

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5921]
**Describe the bug**
Search doesn't search on staticly deployed Storybooks.

**To Reproduce**
1. Go to a static storybook [here](https://artsy-reaction.netlify.com/?path=/story/apps-artwork-page-components-artworkimagebrowser--artworkactions) or the [official SB](https://storybooks-official.netlify.com/?path=/story/ui-panel--default)
2. Click on the search input
3. Start typing 
4. See that it doesn't instantly filter

**Expected behavior**
It begins filtering the stories list 

**Screenshots**
A deployed SB (bad) 
![image](https://d3crtwyc2nw0fl.cloudfront.net/items/3Q001m2d042N0y033d2W/Screen%20Recording%202019-03-06%20at%2009.31%20AM.gif?v=bafdf605)

On localhost (good)
![image](https://d3crtwyc2nw0fl.cloudfront.net/items/0b2b3z2d2F3F0e2o130t/Screen%20Recording%202019-03-06%20at%2009.32%20AM.gif?v=9837e5cf)

**Comment by ehzhang** [comment]
if interested, there is a workaround identified in #5907 (and a pr to fix in #5907)

**Comment by shilman** [comment]
Closing as duplicate to #5907. Community is one step ahead @domyen 😘
