### ISSUE TITLE
Allow for styling of the addon-notes panel

### ISSUE THREAD

**Issue by vpicone** [storybooks/storybook#5923]
**Is your feature request related to a problem? Please describe.**

With the current theming options, it's very difficult to style the notes panel when needed. Using backticks for inline code results in unreadable text.

![screen shot 2019-03-06 at 9 33 12 am](https://user-images.githubusercontent.com/4078018/53892960-e64dba80-3ff2-11e9-81b9-e5f28669edb1.png)

---
**Describe the solution you'd like**
The notes addon should allow for flexible theming of the notes panel.
```
  addonNotesTheme: {
    code: {
      color: 'rebeccapurple',
    },
    h2: {
      color: 'red',
    },
  },
```

![screen shot 2019-03-06 at 9 37 50 am](https://user-images.githubusercontent.com/4078018/53893280-86a3df00-3ff3-11e9-9cd0-a1dbc9766321.png)

---

**Describe alternatives you've considered**
Instead of allowing the user to theme with any emotion rules they want, the notes addon could expose a few extra themeable variables to style things like blockquotes, inline code, etc. However, this would mean extra maintenance overhead whenever a new styling request comes along.

**Are you able to assist bring the feature to reality?**
Yes → https://github.com/storybooks/storybook/pull/5922

**Comment by anki247** [comment]
This is how the `addons/notes/README.md` looks in v5.0.0 with dark theme.
![image](https://user-images.githubusercontent.com/3366211/53957477-bda2ef00-40de-11e9-96e9-83f1f6ea1781.png)

**Comment by vpicone** [comment]
@anki247 Yes, that's why I made this issue and PR.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.11 containing PR #5922 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
