### ISSUE TITLE
Deep linking to "kinds" broken in SB5

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#5925]
H/t @NicoleGrondinAlayacare

Confirmed the old behavior in 4.x and the new (regressed) behavior in 5.x.

4.x: https://5c7e1a14bc4b210008a05f9f--storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs

5.x: https://storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs

---

~~Click on: https://storybooks-official.netlify.com/?path=/story/ui-menuitem--default~~

~~Before anything shows it will automatically re-route to: https://storybooks-official.netlify.com/?path=/story/ui-panel--default~~

~~Click on: https://storybooks-official.netlify.com/?selectedKind=UI%7CMenuItem&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel~~

~~It will (correctly) reroute to: https://storybooks-official.netlify.com/?path=/story/ui-menuitem--default~~

~~But then, before anything shows it will automatically re-route to: https://storybooks-official.netlify.com/?path=/story/ui-panel--default~~

**Comment by tmeasday** [comment]
But that's just because there is no story called "UI|MenuItem:default"?

This link works: https://storybooks-official.netlify.com/?path=/story/ui-layout-desktop-mocked--default

**Comment by tmeasday** [comment]
As does this:

https://storybooks-official.netlify.com/?selectedKind=UI%7CPanel&selectedStory=no+panels&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by tmeasday** [comment]
Not sure what's going on here 🤷‍♂️

**Comment by shilman** [comment]
Right on. This was a bad URL 👍

**Comment by NicoleGrondinAlayacare** [comment]
Hum... maybe I'm not getting it. In storybook 4, you could link to storiesOf(X) without naming a specific story and it would default to the first story available. 

Now you need to feed the name of a specific story to the url or you get an error screen:
<img width="1440" alt="screen shot 2019-03-07 at 9 29 29 am" src="https://user-images.githubusercontent.com/44609805/53963567-8f5fe800-40bb-11e9-8f35-b57809f42ea1.png">

This makes it more difficult to link to stories from outside storybook.

**Comment by shilman** [comment]
@NicoleGrondinAlayacare Confirmed the old behavior in 4.x and the new (regressed) behavior in 5.x.

4.x: https://5c7e1a14bc4b210008a05f9f--storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs

5.x: https://storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs

Updating the issue description

**Comment by tmeasday** [comment]
I reckon we can fix this but it's not trivial. Something for 5.1.0?

**Comment by tmeasday** [comment]
Some notes:
 - This link https://storybooks-official.netlify.com/?selectedKind=UI%7CPanel&selectedStory=no+panels&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel does not work reliably in *chrome* but does in *safari*

 - the order of stories in https://storybooks-official.netlify.com is different in chrome and safari (related to #5827?)

**Comment by tmeasday** [comment]
Ok.

I fixed the regression here: https://github.com/storybooks/storybook/pull/6688

I still want to look at linking to kind only.

I also worked out that the ordering difference between Safari & Chrome is due to this line: https://github.com/storybooks/storybook/blob/5925-fix-kind-deep-linking/lib/ui/src/components/sidebar/treeview/utils.js#L63

(You are supposed to return 1,0,or -1 from sort, I guess browsers differ if you return a bool).

I don't think the treeview should be sorting at all, due to reasons discussed (namely the keyboard shortcuts will be inconsistent with the treeview == much uggh). I will get rid off this and fix #5827 also

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.37 containing PR #6688 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tmeasday** [comment]
More to do

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.40 containing PR #6720 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
