### ISSUE TITLE
Viewport Addon: Border-box modifies iframe size

### ISSUE THREAD

**Issue by jcousins-ynap** [storybooks/storybook#5927]
The border of `#storybook-preview-iframe` reduces the width and height of the document by 20px thanks to `* { box-sizing: border-box; }`.

This means that a viewport is not the size it says it is.

With the following viewport defined:
```js
viewports: {
  bp1: {
    name: 'Breakpoint 1',
    styles: {
      width: '320px',
      height: '480px',
    },
  }
}
```
The iFrame document should be 320px by 460px, but instead it actually is 300px by 460px.

![image](https://user-images.githubusercontent.com/46780058/53901383-c2ac6380-4036-11e9-8b4e-15091ba93cf7.png)

![image](https://user-images.githubusercontent.com/46780058/53901339-adcfd000-4036-11e9-98e3-8c93fd58dd06.png)

**System:**
 - OS: MacOS
 - Device: Macbook Pro 13" 2017
 - Browser: Chrome
 - Framework: react
 - Addons: @storybook/addon-viewport
 - Version: ^5.0.0

**Comment by evolutionxbox** [comment]
As far as I know, this issue can only be mitigated by editing the addon source.

Using the following css fixes the issue:
```css
#storybook-preview-iframe {
  box-sizing: content-box !important;
}
```

The use of important is to override any style attributes, but if this rule can be added via emotion, or the like, that is preferable.

**Comment by shilman** [comment]
Wanna issue a PR?

**Comment by evolutionxbox** [comment]
Honestly, not really.
However, now that I have much more free time today than I thought I'll give it a go.

**Comment by evolutionxbox** [comment]
(btw, the account which posted the issue is my work github account)

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.4 containing PR #5993 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.2 containing PR #5993 that references this issue. Upgrade today to try it out!

**Comment by aalieksashyn** [comment]
@shilman  setting the boxSizing: 'content-box' on an iframe brakes some of our components. We build the components with boxSizing: 'border-box' in mind. I believe, this is the best practice. And your change overrides the border-box property that causes layout issues. Is there a way to set/override the border-box property for a storybook globally?
