### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by mt-roberto** [storybooks/storybook#5936]
**Description**
Storybook 5 fails to decode custom fonts. The console returns: `Failed to decode downloaded font: http://localhost:9001/static/media/fonts.ttf`.

The font is available when accessing that url directly: `http://localhost:9001/static/media/fonts.ttf`

**To Reproduce**
Just import the font in one of your jsx files:

`import 'custom-font/style.css';`

**Expected behavior**
Version 4 of Storybook was working correctly.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react

**Comment by shilman** [comment]
@ndelangen @tmeasday any idea what could be happening here?

**Comment by tmeasday** [comment]
No idea -- any chance of a reproduction @mt-roberto?

**Comment by mt-roberto** [comment]
I think it has to do with the webpack configuration, according to this issue on webpack: https://github.com/webpack/webpack/issues/1468

**Comment by tmeasday** [comment]
@mt-roberto are you importing the font from JS? Your code snippet imports CSS (which I assumed imported the font via CSS syntax, not webpack).

If you are importing the font directly, are you using a loader for that? You might be tripping up on the fact that SB5 adds file loader to the default configuration

**Comment by mt-roberto** [comment]
Ok, I fixed this replacing the fonts rules on Storybook webpack with my rules:

```
  let fontCssRule = config.module.rules.find(rule => rule.test.toString() === /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/.toString());

  fontCssRule = {
    test: /\.woff(\?.*$|$)/,
    loader: 'url-loader?limit=10000&mimetype=application/font-woff'
  },
    {
      test: /\.(ttf|eot|svg)(\?.*$|$)/,
      loader: 'url-loader'
    },
    {
      test: /\.(gif|png|jpe?g|svg|ico)$/i,
      use: [
        {
          loader: 'url-loader',
          options: {
            limit: 10000
          },
        },
        {
          loader: 'image-webpack-loader',
          options: {
            bypassOnDebug: true,
            mozjpeg: {
              progressive: true,
              quality: 65
            },
            // optipng.enabled: false will disable optipng
            optipng: {
              enabled: true,
            },
            pngquant: {
              quality: '65-90',
              speed: 4
            },
            gifsicle: {
              interlaced: false,
            },
            // the webp option will enable WEBP
            webp: {
              quality: 75
            }
          }
        }
      ]
    }; 
```

**Comment by churichard** [comment]
I was running into the same issue and excluding [the rule](https://github.com/storybooks/storybook/blob/4da246bbe9413510b48d1ab8b9faf4fae4656d92/lib/core/src/server/preview/base-webpack.config.js#L36) that @mt-roberto mentioned fixed it. Would doing this break anything in Storybook, or is it safe to do?

**Comment by shilman** [comment]
@churichard It should be fine, see: https://github.com/storybooks/storybook/pull/6341/files

@mt-roberto @churichard Should this be changed in the default Storybook webpack config?

**Comment by ilyaztsv** [comment]
@shilman I've checked it using storybook 5.0.3 and it works without my custom rule for fonts:

```
config.module.rules = config.module.rules.map(rule => {
  if (rule.test.toString() === /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/.toString()) {
    return configureFontLoader();
  }

  return rule;
});
```

**Comment by edgardz** [comment]
Solved here setting webpack.config.js like:

```
module.exports = async ({ config }) => {
  config.module.rules = config.module.rules.map(rule => {
    if (rule.test && rule.test.toString().includes('woff')) {
      return {
        ...rule,
        test: /\.(svg|ico|jpg|jpeg|png|gif|webp|cur|ani|pdf)(\?.*)?$/
      }
    }
    return rule
  })
  return config
```

**Comment by natterstefan** [comment]
Thank you @edgardz, worked for me as well.

**Comment by nicosampler** [comment]
@edgardz 
you man saved my day!
