### ISSUE TITLE
linkTo has incorrect behavior on call with one parameter

### ISSUE THREAD

**Issue by Armanio** [storybooks/storybook#5950]
**Describe the bug**
`linkTo` from links addon has incorrect behaviour when it calls without second parameter

**To Reproduce**
1. Go to https://storybooks-official.netlify.com/?path=/story/other-demo-welcome--to-storybook
2. Click on "stories" in description welcome component
3. App will be redirect to https://storybooks-official.netlify.com/?path=/story/Button and you see broken markup
**Expected behavior**
Welcome component has linkTo function call `linkTo('Button')` from links addon. In addon doc i found this:
"Second (optional) parameter is the story name (what you named with .add). If the second parameter is omitted, the link will point to the first story in the given kind."

**Screenshots**
<img width="1007" alt="2019-03-07 17 36 14" src="https://user-images.githubusercontent.com/3195714/53964049-9577b800-40ff-11e9-8dfa-6ab735134bec.png">

**System:**
 - OS: MacOS 10.14.3
 - Device: Macbook Pro 2017
 - Browser: Chrome 72.0.3626.119
 - Addons: link
 - Version: 5.0.0

**Additional context**
I inspect this problem. Like a problem in `selectStory` from `storybook/lib/ui/src/core/stories.js`.
If call function without second parameter app will simple redirect  to /story/{PARAM} despite PARAM is valid kind name.

**Comment by Armanio** [comment]
If i understand it right i can take this issue and fix it?

**Comment by shilman** [comment]
@Armanio Awesome!! Would love a fix for this!! 🥇

**Comment by shilman** [comment]
Related: https://github.com/storybooks/storybook/issues/5925

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.3 containing PR #5983 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.2 containing PR #5983 that references this issue. Upgrade today to try it out!
