### ISSUE TITLE
addon-knobs panel loses focus on change of value

### ISSUE THREAD

**Issue by leepowellcouk** [storybooks/storybook#5952]
**Describe the bug**
We have a React Storybook set up with the `actions` and `knobs` addons. Running version 5.0.0 of each. When changing a `knob` value, the addons panel jumps to `actions`.

**Expected behavior**
`knob` panel should remain as the primary focus until the user selects an alternative addon

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - Browser: Chrome
 - Framework: react
 - Addons: actions, knobs, a11y, jest, notes, options, viewport
 - Version: 5.0.0

**Comment by shilman** [comment]
Solved?

**Comment by leepowellcouk** [comment]
Yes I think so. I didn’t see the configuration change warnings in the console. Once I updated it seemed to solve the issue.

**Comment by yhnavein** [comment]
I am having this problem in 5.0.1 in the almost the same configuration as yours. @leepowellcouk How did you manage to fix it?

**Comment by leepowellcouk** [comment]
@yhnavein Not really sure what fixed it. I got a bunch of warnings in the console about deprecated settings. Once I resolved those it seemed to fix the issue.

**Comment by yhnavein** [comment]
For everyone interested in this issue:
The reason you see this is pretty much because you use old `@storybook/options` package. Just follow this guide: [Migration Guide](https://github.com/storybooks/storybook/blob/next/MIGRATION.md#options-addon-deprecated) and you are good to go :)
