### ISSUE TITLE
5.0.0 uses root babel.config even if custom config is provided

### ISSUE THREAD

**Issue by timhettler** [storybooks/storybook#5955]
**Describe the bug**
If a project uses a `babel.config.js` file, there is no way to provide a custom babel config to storybook.

**To Reproduce**
1. Create a `babel.config.js` file in the root directory
2. Create a `.babelrc` file with overriding behavior in `.storybook`
3. Start storybook
4. See at the configuration specified in the root `babel.config.js` is used.

**Expected behavior**
Storybook prioritizes configuration files in `.storybook`

**Code snippets**
`./babel.config.js`
```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
      },
    ],
    '@babel/preset-react',
  ],
  plugins: [['@babel/plugin-transform-runtime']],
  env: {
    test: {
      presets: ['@babel/preset-env', '@babel/preset-react'],
    },
  },
};
```

`./.storybook/.babelrc`
```json
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
}
```

**System:**
 - OS: MacOS
 - Framework: react
 - Version: 5.0.0

**Additional context**
I am working within a monorepo. The build process worked with the config file pasted above in version 4.x and without a custom babel config for Storybook. Perhaps the `rootMode` babel option was changed in version 5?

**Comment by Jessidhia** [comment]
`babel.config.js` is always considered to be _the_ authoritative babel config by default.

You need to tell babel that it's OK to trust your local babelrc by adding it to `babelrcRoots`: https://babeljs.io/docs/en/options#babelrcroots

For example, `babelrcRoots: ['.', '.storybook']`.

If that still doesn't work, then you should either merge both configs (by using, say, https://babeljs.io/docs/en/options#overrides) or rename your `babel.config.js` to `.babelrc.js` to make it non-authoritative.
