### ISSUE TITLE
Viewport styling changes

### ISSUE THREAD

**Issue by Glazy** [storybooks/storybook#5965]
**Is your feature request related to a problem? Please describe.**

Since upgrading to v5, the viewport addon adds a big 10px black border around your viewport and it doesn't look as nice as it used to.

**Describe the solution you'd like**

I think it would be good to get a way to configure this border or ideally have a way to return to the styling of V4. Putting the viewport in the center of the screen and adding the shadow around it just made more sense to me.

**Describe alternatives you've considered**

I could write some CSS to manually override the viewport styles but I would imagine there are a few people out there who would like the option to return to the previous styling/functionality so a configuration option would make more sense.

**Are you able to assist bring the feature to reality?**

Yes

**Additional context**

V5

<img width="1272" alt="screen shot 2019-03-08 at 11 25 21" src="https://user-images.githubusercontent.com/8593744/54026186-ec7b9c80-4194-11e9-9cf2-aae9be4e8c20.png">

V4

<img width="882" alt="screen shot 2019-03-08 at 11 19 00" src="https://user-images.githubusercontent.com/8593744/54026197-f69d9b00-4194-11e9-963a-bcbc62a6a55b.png">

**Comment by shilman** [comment]
Not sure who changed the border or why. @domyen @ndelangen any comments here? Is that in scope for theming in the near future?

**Comment by domyen** [comment]
I didn't change the border. The v4 appearance is more handsome imo. Would be open to changing the base UI to something like that if @Glazy wants to open a PR for it.

**Something like:**
- 1px border with box-shadow
- horizontally centered

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.3 containing PR #5979 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.2 containing PR #5979 that references this issue. Upgrade today to try it out!

**Comment by connor-baer** [comment]
There seems to have been a regression in #7385 (see [this line](https://github.com/storybookjs/storybook/pull/7385/files#diff-fe63efcdfc60bd2e76fce892c494024eR189)). I've submitted a PR to fix it again.

**Comment by sioanis** [comment]
Not sure why, but this still seems to exist for `"@storybook/vue": "^5.3.14"`, `"@storybook/addon-viewport": "^5.3.14"`. 

<img width="1472" alt="Screen Shot 2020-04-10 at 12 17 17 PM" src="https://user-images.githubusercontent.com/3586765/79005616-45023380-7b25-11ea-8ee4-c5a8d9eb136e.png">

**Comment by connor-baer** [comment]
@sioanis The PR to update the styling was merged into the v6 branch (https://github.com/storybookjs/storybook/pull/8486)

**Comment by sioanis** [comment]
Ah, I see. Thank you, @connor-baer.
