### ISSUE TITLE
Viewport addon: Missleading example in README

### ISSUE THREAD

**Issue by no23reason** [storybooks/storybook#5968]
**Describe the bug**
Following the example of setting defaultViewport per story in `@storybook/addon-viewport` README does not work and breaks the viewport configuration.

**To Reproduce**
1. Create a custom viewport configuration:
```js
import { configure, addParameters } from '@storybook/react';
import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';

const myViewports = {
    myOne: {
        name: 'MyOne',
        styles: {
            width: '1200px',
            height: '900px'
        }
    }
};

addParameters({
    viewport: {
        viewports: {
            ...INITIAL_VIEWPORTS,
            ...myViewports
        }
    }
});

const req = require.context('../stories', true, /\.tsx?$/);

function loadStories() {
    req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```
2. Create a story and try to set its default viewport following the [example](https://github.com/storybooks/storybook/tree/next/addons/viewport#configuring-per-component-or-story).

```js
addStories('Stories', module)
    .add('story', () => </>, { viewport: 'myOne' });
```

3. The viewport list does not contain MyOne and the default viewport is not set.

**Expected behavior**
The viewport list contains MyOne and it is set as a default viewport.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: Chrome, Safari
 - Framework: react
 - Addons: viewport
 - Version: 5.0.0

**Comment by shilman** [comment]
@tmeasday Didn't https://github.com/storybooks/storybook/pull/5829 try to address this?

**Comment by tmeasday** [comment]
You can set `viewport: { defaultViewport: 'myOne' }`, but cannot set the parameters object to a string (as this breaks auto-merging of parameters).

Did I not end up documenting this properly?

**Comment by tmeasday** [comment]
Hmm I see I made a typo, I'll fix it.

**Comment by tmeasday** [comment]
https://github.com/storybooks/storybook/pull/5977/files
