### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by arnaudmanaranche** [storybooks/storybook#5970]
In the section `Configuration`, the following part of code :
```js
addParameters({ viewport: options });
```
should be : 
```js
addParameters({ viewport: { viewports: newViewports } });
```
<img width="912" alt="screen shot 2019-03-08 at 17 34 05" src="https://user-images.githubusercontent.com/12219184/54041627-7bee7300-41c8-11e9-8c06-cdb981612b4e.png">

**Comment by shilman** [comment]
@arnaudmanaranche Mind putting together a small PR for this?

**Comment by tmeasday** [comment]
@arnaudmanaranche I'm not sure I agree -- the `options` can take a couple of keys, as documented directly below the snippet you posted?
