### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Jony-Y** [storybooks/storybook#6014]
Migrated to v5 from v4.1 with custom webpack, getting this issue:
![image](https://user-images.githubusercontent.com/10330531/54112017-edf3d180-43ed-11e9-81bf-575662393deb.png)

this is my console:
![image](https://user-images.githubusercontent.com/10330531/54112063-0532bf00-43ee-11e9-9319-96fdb49acbd5.png)

my stack:
```
"@storybook/addon-actions": "^5.0.1",
    "@storybook/addon-info": "^5.0.1",
    "@storybook/addon-links": "^5.0.1",
    "@storybook/react": "^5.0.1",
    "@storybook/theming": "^5.0.1",
"react": "^16.8.4",
"react-dom": "^16.8.4",

```
my webpack:

```
const path = require('path');
const appWebpack = require('../webpack.config');

module.exports = ({ config, mode }) => {
  config.module.rules.push({
    test: /\.scss$/,
    loaders: ['style-loader', 'css-loader', 'sass-loader'],
    include: path.resolve(__dirname, '../'),
  });
  return config;
}
```

my config:

```
import {jss} from 'react-jss';
import jssNested from 'jss-nested';
import './addons';
import { version } from '../package.json';
import { configure, addParameters, addDecorator } from '@storybook/react';
import { withInfo } from '@storybook/addon-info';
import TableComponent from './TableComponent';
import CodeExample from './infra/CodeExample';
import Section from './infra/Section/Section';

jss.use(jssNested);
function loadStories() {
  require('./stories');
}

addParameters(
  {
    options: {
      showAddonPanel: false,
      name: `Atomic Design v${version}`,
      url: 'https://github.com/guestyorg/atomic-design',
      sidebarAnimations: true
    }
});

addDecorator(
  withInfo({
  inline:true,
  header:false,
  source:false,
  propTablesExclude:[Section, CodeExample],
  TableComponent,
}));
configure(loadStories, module);
```
*****Edit******
And an example of a failing story: 

```
import React from 'react';
import { storiesOf } from '@storybook/react';
import { withInfo } from '@storybook/addon-info';
// eslint-disable-next-line
import AvatarExampleRaw from '!raw-loader!./AvatarExample';
import Section from '../../../../.storybook/infra/Section/Section';
import CodeExample from '../../../../.storybook/infra/CodeExample';
import { AvatarComponent } from './Avatar';
import { STORYBOOK_V2_COMPONENTS } from '../../../constants/constants';
import storyName from '../../../../.storybook/infra/storyName';
import AvatarExample from './AvatarExample';

storiesOf(STORYBOOK_V2_COMPONENTS)
  .add(
    storyName('Avatar'),
    withInfo({
      propTables: [AvatarComponent],
      propTablesExclude: [AvatarExample, Section, CodeExample],
    })(() => (
      <Section title="Avatar" description="import Avatar from '@guestyinc/atomic-design/dist/components/Avatar'">
        <CodeExample title="Avatar" className="flex-space-between-center" codeText={AvatarExampleRaw}>
          <AvatarExample />
        </CodeExample>
      </Section>)),
  );
```
I've been struggling with the migration to 5, I have a lot of issues on the way, also with svg loaders. I think this is the only one left and I cant understand whats wrong here, can someone help?

**Comment by shilman** [comment]
@Jony-Y what happens when you remove the custom `TableComponent`?

**Comment by Jony-Y** [comment]
@shilman Sorry, closed by mistake, yes, If I remove it it still happens. I'll add an example of a story that fails.

**Comment by Jony-Y** [comment]
@shilman After more research it appears to only crash on propTables which are Class Components. and in functional it does not read the description over each component

Any idea?

**Comment by shilman** [comment]
I'm overhauling this right now as part of improving the documentation features of Storybook. I'll take a closer look in the next two weeks. Thanks for your patience!

**Comment by Jony-Y** [comment]
@shilman any update on this?

**Comment by shilman** [comment]
Sorry no progress yet. Been working on other aspects of a replacement for addon-info and tons of progress there, but haven't gotten to take a pass at the info bugs yet unfortunately. On vacation this week but hopefully next week when I'm back. Thanks for your patience!

**Comment by lauriejones** [comment]
I am getting this same error on `storybook@4.1.16`.

Dropping back to `4.1.4` does not have the issue.

**Comment by Jony-Y** [comment]
Was able to fix it, in my case it was the @storybook/addon-info, I had base configs which apparently in SBv5 it just either didn't read or just had an issue with.

Ended up creating a small wrapper and removed the global configs. 

solved me issue.

```
export default function({section = STORYBOOK_V2_COMPONENTS, name, options={}, component}) {
  storiesOf(section).add(
    name,
    !isEmpty(options) ?
      withInfo(options.propTables,
      options.propTablesExclude,
      options.description)(component):
      component);
}

```

```
import { withInfo as withInfoAddon } from '@storybook/addon-info';
import TableComponent from './TableComponent';
import CodeExample from './CodeExample';
import Section from './Section/Section';
export function withInfo(propTables = [], propTablesExclude = [], description = '') {
  return withInfoAddon({
    inline: true,
    header: false,
    source: false,
    text:description,
    propTables,
    propTablesExclude: [...propTablesExclude, Section, CodeExample],
    TableComponent,
  });
}

```

**Comment by Dozalex** [comment]
In my case it was due to 
`data: PropTypes.arrayOf(PropTypes.shape())`

Solved by
`data: PropTypes.arrayOf(PropTypes.object)`

**Comment by JoaoFGuiomar** [comment]
I'm getting a similar issue when starting storybook up.

I recently upgraded to 5.2. No clue whats going on here 🤔 

```
    "@storybook/addon-a11y": "5.2.8",
    "@storybook/addon-viewport": "5.2.8",
    "@storybook/react": "5.2.8",
```


![screenshot](https://user-images.githubusercontent.com/2249046/71627712-fa028700-2beb-11ea-8a92-d9f666484fd6.png)

**Comment by randyridge** [comment]
@JoaoFGuiomar I had same issue with 5.2 as you, found this thread today.  It appears that it's a problem with addon-viewport configuration.  The addParameters({viewport: { ... }}) has changed...  I ended up just removing mine.  See [this addon-viewport issue](https://github.com/storybookjs/storybook/issues/9129).

**Comment by JoaoFGuiomar** [comment]
Yep, that was it.

Thanks 🍻
