### ISSUE TITLE
html-loader and markdown-loader not working together + wrong output

### ISSUE THREAD

**Issue by MPasadu** [storybooks/storybook#6018]
**Describe the bug**
We can't use markdown-loader together with html-loader. When I only use markdown-loader some syntax is not correct. Returns / Line feeds also only sometimes seem to be recognized.

**Expected behavior**
Correct formatting.

**Markdown**
![alt text](https://i.imgur.com/ITvaFZX.png "markdown")

**Output**
![alt text](https://i.imgur.com/BFzGDiW.png "output")

**System:**
 - OS: Windows 10
 - Device: Desktop
 - Browser: Chrome
 - Framework: react
 - Addons: storybook-readme
 - Version: 5.0.1

**Comment by shilman** [comment]
I don't understand this issue. Can you clarify what's the problem?

**Comment by MPasadu** [comment]
I am sorry. I think the issue can be put simpler: I can't seem to get markdown to work with story book. At the top screenshot you can see the markdown text (inside visual studio code). The bottom screen shows the result inside storybook. You can see the line feeds are not correct as well as the corresponding line 19 in the markdown screenshot, shows in the storybook screenshot html characters like `&quot;` or `&lt;`

**Comment by shilman** [comment]
Where is this being displayed? `addon-notes`?

**Comment by MPasadu** [comment]
Correct.
