### ISSUE TITLE
style guide generation, react-styleguidist integration?

### ISSUE THREAD

**Issue by jurgob** [storybooks/storybook#602]
Hi, is it possible to generate a style guide from the stories? 
something like react-styleguidest (https://github.com/sapegin/react-styleguidist) do?
Does it make sense to write something from scratch? or maybe it make more sense to do some tools to "generate" the react-styleguidist files?

In my project I was using both react-styleguidest and react-storybook, so I wrote a storybook generator from the styleguidest examples.  (here the code: https://gist.github.com/jurgob/58f6f46c34e991dc449effe5731dd693).

Maybe doing the opposite (from stories to markup files) it could be the fastest way?

Let me know what do you think

**Comment by jurgob** [comment]
probably a static building could solve my problems, but as far as I can see, it miss 3 feat witch are present in react-styleguidist:
1)  on-the-fly code editor. 
2) markdown description for every story
3) markdownd pages included in the generated styleguide (same format of github)

**Comment by cdaringe** [comment]
can the addons not fill this role somehow already?

**Comment by jurgob** [comment]
mmm, not sure. Btw have a longer description for the story could be a good idea?

**Comment by arunoda** [comment]
Hey, we have some solutions in Storybook land for this. Let me show you them:

* Info addon: https://github.com/storybooks/react-storybook-addon-info
* Readme Addon: https://github.com/tuchk4/storybook-readme
* [Our react-docgen integration](https://voice.kadira.io/component-metadata-react-storybook-ac0b218a2203#.qphz37cdb)

**Comment by sapegin** [comment]
Hey, React Styleguidist author is here ;-) Is anyone still interested in Storybooks and React Styleguidist integration?

**Comment by glambertmtl** [comment]
I might be yes :)

**Comment by TheSisb** [comment]
+1 for the integration

**Comment by jbovenschen** [comment]
@sapegin I'm interested in the integration with styleguidist, also I'm happy to help or make the integration, happy to hear of your still interested.

**Comment by sapegin** [comment]
@jbovenschen Hi Jaco! I’m not very familiar how Storybook works but probably we could somehow convert stories to Styleguidist Markdown format. Probably it will require some changes in Styleguidist itself. I’m happy to discuss it ;-)

**Comment by logankoester** [comment]
I'm still interested in this as well, definitely!

**Comment by cdaringe** [comment]
I will definitely follow commits on such a thing.  **very** interested!

**Comment by cdaringe** [comment]
one idea is a styleguidist loader.

in that regard, storybook doesn't even need awareness of styleguidist.  you just:

```js
.add('widget', require('styleguidist!./my-widget.md'))
```

the loader would return the root react `Component` for the styleguide and blamo, we'r' on our way!

@sapegin, thoughts?

**Comment by jbovenschen** [comment]
Currently I try to work out something where you get a link, like "Open isolated ->" in the examples generated by styleguidist.

@cdaringe Will the webpack example return the complete set of styleguidist stories? Or create new ones based on it's content, if so is it not better to create some kind of [addon](https://getstorybook.io/docs/react-storybook/addons/writing-addons)?

**Comment by cdaringe** [comment]
@jbovenschen, it would load only the content as defined by `./my-widget.md`, so just the one styleguidist story, or set of stories defined therein.  loading a full build probably wouldnt provide much value, IMHO

**Comment by sapegin** [comment]
Then what’s the difference with running Styleguidist separately if you still have to write docs in Styleguidist format?

**Comment by cdaringe** [comment]
> Then what’s the difference with running Styleguidist separately if you still have to write docs in Styleguidist format?

great point, i dont know what i was thinking. my head's on straight now!  perhaps a better approach would be an addon, providing a styleguidist wrapper thingy™:

```js
import { styleguidist } from 'storybook-styleguidist'
import Button from './path/to/button'
.add('Button', styleguidist(
  Button,  // tells which props to inject into addon pane
  () => { /* story 1 */ }, // renders normal styleguidist experience
  () => { /* story 2 */ }
)
```

maybe not ideal, because in that approach, all stories share the same viewer. instead...

```js
import { styleguidist } from 'storybook-styleguidist'
import Button from './path/to/button'
.add(styleguidist(
  Button,
  'story1', () => { /* story 1 */ },
  'story2', () => { /* story 2 */ }
)
```

^^ would load the props documentation into the story1 & story2 "styleguidist" addon panes, & the stories would be laid out per the below in the storybook:

```
├── Button
│   ├── story1
│   ├── story2
```

**Comment by UsulPro** [comment]
Hey! I like an idea to integrate them such a way that it could be possible to use Strorybook as a development tool and Styleguidist as a customizable static output.

I was looking for ways to seamlessly transfer stories data to styleguidist and now I can show the example how it's possible to create markdown from storybooks via addon. 

```js
storiesOf('Usual story', module)
    .addStyleGuide('Simple Example', () => (
      <div className="example-component">
        <Button title={text('Subtitle3', 'Knob1.SubTitle')} />
      </div>
    ), { getCode: storeCode })
```

It's possible to pass additional description to each story like in `react-storybook-addon-info` (actually it's a fork). And markdown could be devided by stories or any other way.

The big pros is that it's possible to use with other addons like `Knobs`. e.g. set all knobs and then generate a markdown with stored prop values. (I hope it'll be possible to support decorators as well)

Here're [demo](https://usulpro.github.io/storybook-styleguidist/) and  [repo](https://github.com/UsulPro/storybook-styleguidist)

In this demo you can see markdown in the addon panel after selecting single story or do it automatically to generate all of them. 
it's just an outline for now. I think if it's usefull it's possible to reduce excessive code and have something realy simple for usage and avoid ` .addStyleGuide` (keep it only if we want to add some additional docs to the description, in all other cases - just usual `.add`)

@sapegin @cdaringe @jbovenschen @jurgob  do you have any ideas is it possible to continue and how to pass this markdown (and everything else) to Styleguidist?

One of the problems could be is that do it in browser not server (now the most simple way is just save a file manually) or could we generate styleguide on a client side?

So I'll be happy if it could help with this work :)

**Comment by sapegin** [comment]
@UsulPro That’s amazing! Exactly what I was thinking (but had no idea how to implement it ;–)

> how to pass this markdown (and everything else) to Styleguidist?

That’s a good question. Generating real files is not the best way. But I don’t really know how can we connect Storybook and Styleguidist. Does Storybook have some API? Is it possible to have all Markdown snippets in Node?

**Comment by UsulPro** [comment]
Storybook has API for addons developing.

But maybe we can use this #435 ?

Asking to have Markdown snippets in Node do you mean to use this [API](https://github.com/styleguidist/react-styleguidist/blob/master/docs/API.md#buildcallback)? I'm confused that it needs to require everything from this Markdown as well.

**Comment by sapegin** [comment]
I should study Storybook API, right now I don’t understand how to connect two tools together ;-)

**Comment by pke** [comment]
I also always wondered what the difference between storybooks and styleguidist is. I think I favour the latter for its easy markdown readme and most of all, users of the guide can "write their own story", because styleguidist allows live editing of code from the (static) guide side.

**Comment by sapegin** [comment]
@pke Yeah, ability to generate a style guide with all components on the same page and different way of writing stories / examples are the main differences.

**Comment by IanVS** [comment]
This issue fits really well with this article comparing storybook and styleguidist: https://blog.hichroma.com/storybook-vs-styleguidist-2bd93d6dcc06.  The TL;DR is that they both fill different needs.  Storybook is great for developers creating components in isolation, and styleguidist is well-suited for creating documentation around them.  The author ends by saying he he wishes the two could be combined.  I agree.

To accomplish this, I think we need two pieces.  One is to be able to create rich documentation about a component, and https://github.com/tuchk4/storybook-readme seems perfect for that.  But the piece that is still missing, I think, is being able to generate a single page with all of the documentation for all of the components.  Imagine a new developer on the team looking for a particular type of component, but not knowing what it's called.  It is much easier to scroll through a single page looking for something that looks right, than it is to click through the elements in a sidebar, guessing from their names.

All that to say, does anyone think it might be possible to create a single page combining all of the stories together, using either `info-addon` or `storybook-readme`?

**Comment by pke** [comment]
I don't want to learn a new DSL for writing documentation. I still think styleguidist solves the problem at hand better and smoother.
Also by facilitating readme files in every component folder, that readme can be seen when browsing the github repo without even opening the styleguidist docu. So I can not see how both projects fill different needs, for me they do the same.

**Comment by IanVS** [comment]
I agree that being able to pull in readme docs into stories with storybook-readme is awesome for the reasons you describe.  I think the main thing still missing from storybook, is the ability to scroll down a single page and see all the components, without having to click once or twice through the scrollbar for each one.

**Comment by crash7** [comment]
I'm trying to build the same, just because I want the view-port feature that storybook has with that addon but couldn't find a way to load the stories from the readme or the other way around.

**Comment by QingLeiLi** [comment]
Any progress about this?

**Comment by IanVS** [comment]
I'm hopeful that this will give us what we are looking for: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a

**Comment by QingLeiLi** [comment]
> I'm hopeful that this will give us what we are looking for: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a

Thanks for the quick reply, I will take a look at the article. Also thanks for the hard work what you are doing on the SB.

**Comment by shilman** [comment]
@IanVS @QingLeiLi If you want to try it out, here's a more recent guide: https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

Currently in alpha, hustling to get it into beta this week 🤞

**Comment by QingLeiLi** [comment]
> @IanVS @QingLeiLi If you want to try it out, here's a more recent guide: https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing
> 
> Currently in alpha, hustling to get it into beta this week 🤞

Nine work! I will give it a try soon.
