### ISSUE TITLE
latest update breaks components built with emotion

### ISSUE THREAD

**Issue by lifeiscontent** [storybooks/storybook#6028]
**Describe the bug**
Previous version 5.0.0 works perfectly, and this latest update breaks all of my emotion components.

it has there's also an error saying I need to add `emotion-theming` in my project in order for storybook to work.

**Comment by shilman** [comment]
@lifeiscontent can you clear out your `node_modules` and `yarn.lock` and try again? I suspect this is due to a yarn bug. Probable dupe to https://github.com/storybooks/storybook/issues/5817
