### ISSUE TITLE
react-autowhatever component events

### ISSUE THREAD

**Issue by amaalej** [storybooks/storybook#603]
Hi, 
I am working on an opensource project gathering reusable pure react components. 
I tried to integrate this component [react-autowhatever](https://github.com/moroshko/react-autowhatever/) in react-storybook.

I faced a problem with the events: ('onMouseEnter', 'onMouseLeave', 'onMouseDown', 'onClick') are only attached to the 1st item. 

Here are 2 examples: 
1. [Basic Example](https://github.com/Talend/react-talend-components/blob/feat/typeahead/stories/Typeahead.js#L10) 
2. [Advanced Example](https://github.com/Talend/react-talend-components/blob/feat/typeahead/stories/Typeahead.js#L39)

The problem is that when I click on the items, only the 1st item handles the events!
Any Idea please.

**Comment by ndelangen** [comment]
@amaalej If you are still experiencing this issue with Storybook 3, please re-open and we'll take a look! 👍
