### ISSUE TITLE
Cannot install @storybook/addon-liveedit

### ISSUE THREAD

**Issue by EnixCoda** [storybooks/storybook#6039]
**Describe the bug**
Cannot find `@storybook/addon-liveedit` on npm.
```
❯ yarn add @storybook/addon-liveedit -D
yarn add v1.13.0
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@storybook%2faddon-liveedit: Not found".
info If you think this is a bug, please open a bug report with the information provided in "yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**To Reproduce**
1. run `yarn add @storybook/addon-liveedit -D` in a npm package folder.

**Expected behavior**
Install the addon successfully.

**System:**
 - OS: MacOS
 - Addons: liveedit

**Comment by shilman** [comment]
@EnixCoda AFAIK there is no such addon. Perhaps you're looking for this one?

https://github.com/vertexbz/storybook-addon-react-live-edit#readme

**Comment by EnixCoda** [comment]
Hi @shilman 

Code of `addon-liveedit` was available in this repo (under the `/addons`) when this issue was drafted. Maybe it has been removed recently (finally deprecated?).

Thank you anyway.
