### ISSUE TITLE
addon-backgrounds doesn't hide the addons panel when transparent

### ISSUE THREAD

**Issue by glitchperfect** [storybooks/storybook#6041]
**Describe the bug**
Addon-backgrounds overwrites the background color of the preview. However, if the color is "cleared" or set to transparent, then the preview panel is also transparent and will not show the default theme background color but instead reveal the underlying addons-panel that should be hidden. This is due to the fact that "Showing or Hiding the Addons Panel" does in fact not change the size of the addons panel but changes the size of the preview panel so it completely covers it.

**To Reproduce**
1. Create a new empty directory
2. Create the HTML Kitchensink with `npx -p @storybook/cli sb init --type html`
3. Add addon-backgrounds with `npm i -D @storybook/addon-backgrounds`
4. [Add import to config.js](https://github.com/storybooks/storybook/tree/master/addons/backgrounds#configuration): `import '@storybook/addon-backgrounds/register';`
5. Add backgrounds to /stories/index.stories.js:
```js
import { storiesOf } from '@storybook/html';
storiesOf('Demo', module)
  .addParameters({
    backgrounds: [
      { name: 'transparent', value: 'transparent', default: true },
      { name: 'facebook', value: '#3b5998' },
    ],
  })
  .add('heading', () => '<h1>Hello World</h1>');
```
6. Start the Storybook
7. Untick the "show Addons" in the "..." Dropdown or press hotkey `A`
**BUG: It still shows the Addons Panel**
8. Select "facebook" as background color in the background selector
9. Select "Clear Background" as background color in the background selector
**BUG: It still shows the Addons Panel**

**Expected behavior**
The Addon Panel should be hidden. Instead it still shows.

**Screenshots**
![image](https://user-images.githubusercontent.com/2488563/54193884-47760200-44bb-11e9-800a-382af81a8985.png)

**Additional context**
Although this is technically correct (transparent being transparent), it should not be transparent because the preview panel needs one fallback background color. this should be the default background theme color.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.7 containing PR #6042 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.2 containing PR #6042 that references this issue. Upgrade today to try it out!
