### ISSUE TITLE
Add option to hide info from story snapshot generated by story snaps

### ISSUE THREAD

**Issue by scottdickerson** [storybooks/storybook#6049]
**Is your feature request related to a problem? Please describe.**
Can we add an option to the story snaps configuration to exclude all the addons output from the captured storybooks snapshot?  I'm using story snaps to identify changes to my components and alert me to them, but I don't want to be alerted whenever my property definitions or comments change, only when functional changes have happened to the directly rendered component?  When the snapshot gets generated it includes all the markup added around the component by all the addons that I've enabled.

**Describe the solution you'd like**
An option when calling initStoryshots that allows me to exclude the rendered addons from the captured storybook.  For instance
```
 initStoryshots({
    test: snapshotWithOptions({
      excludeAddons: true,
    }),
  });
```

In the generated snapshot, only the rendered component would be included.

Here's a small (common) example of something included in each snapshot that I wouldn't like to show up (the show info button from the info addon):
```
  <button
      onClick={[Function]}
      style={
        Object {
          "background": "#28c",
          "border": "none",
          "borderRadius": "0 0 0 5px",
          "color": "#fff",
          "cursor": "pointer",
          "display": "block",
          "fontFamily": "sans-serif",
          "fontSize": "12px",
          "padding": "5px 15px",
          "position": "fixed",
          "right": 0,
          "top": 0,
        }
      }
      type="button"
    >
      Show Info
    </button>
```

**Describe alternatives you've considered**
I've considered mocking and disabling the storybook addons-info plugin in my testcase, but I'd need to mock and disable all the plugins, and it just seems like this must be a common enough usecase to support this as an standard option.

**Are you able to assist bring the feature to reality?**
probably not due to infamiliarity with the codebase.

**Additional context**

**Comment by shilman** [comment]
Addons that modify the preview window are an anti-pattern. We'll be updating `addon-info` to run in the addons panel in 5.1, so hopefully this won't be an issue.

**Comment by scottdickerson** [comment]
sounds perfect, thank you I can't wait!

**Comment by shilman** [comment]
Update: it's going to be 5.2 not 5.1. Full project announcement: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a
