### ISSUE TITLE
Nesting two storybook projects.

### ISSUE THREAD

**Issue by Generic35** [storybooks/storybook#6051]
**Is your feature request related to a problem? Please describe.**
We have an existing library of components that we share across teams. 
This library also has it's storybook. 
Is it possible to do storybook composition, meaging, creating new storybooks that would start off including these base components (atoms, molecules, organisms), and then add to this storybook pages specific to the current project consuming the component library?

**Describe the solution you'd like**
Would like to be able to start a storybook with an existing storybook of atoms, molecules, to which i would add pages specific to the current project, consuming a library of common components.

**Describe alternatives you've considered**
We considered having two seperate storybooks, one for the web components then another one for the pages developed by each team, put would prefer to have one storybook per team, that includes the common components, and pages specific to the project

**Comment by shilman** [comment]
I don't see why you couldn't do this. Most Storybooks have a story loader that looks like this defined in its `config.js`:

```js
import { configure } from '@storybook/react';

function loadStories() {
  let req;
  req = require.context('../lib/components', true, /\.stories\.js$/);
  req.keys().forEach(filename => req(filename));
  req = require.context('../services/webapp/screens', true, /\.stories\.js$/);
  req.keys().forEach(filename => req(filename));
  // ...
}

configure(loadStories, module);
```

Each storybook could have a different config with as many or as few of those as you wanted.

**Comment by Generic35** [comment]
yes, each storybook is using the storyloader in config.js, but is there already a function in the storybook api that allows to export and import an entire existing storybook, into another storybook other than this storyLoader, like a storybookLoader?

**Comment by shilman** [comment]
No, we don't have anything like this. Fortunately, configuration is done in Javascript so it shouldn't be hard to reuse code between your configurations.

That said, I'm sure your use case is fairly common, so we can think about adding support for something like that in a future version. What do you imagine the API would look like?

**Comment by Generic35** [comment]
A convenient api could be:

- first, having the ability to export storybook A as an npm package (maybe this already exists?)
- then being able to add this package to another project (React, Vue, Ang. etc.), that already contains a storybook config.js, and loading all stories side by side in config.js's loadStories function
