### ISSUE TITLE
Issues with withCSSContext when using vue-cli plugin defaults

### ISSUE THREAD

**Issue by CrashyBang** [storybooks/storybook#6052]
**Describe the bug**
Storybooks not loading, using default config.

**To Reproduce**
1. Create empty Vue project `vue create project-name`
2. Add storybooks plugin `vue add vue-cli-plugin-storybook `
3. Run `npm run storybook:serve`

```
Uncaught TypeError: (0 , _core.withCSSContext) is not a function at Object../node_modules/@storybook/addon-actions/dist/components/ActionLogger/index.js
```

**Expected behavior**
Storybooks to load up (according to dash it is built correctly);

**Code snippets**
`package.json`:
```json
"@storybook/addon-actions": "^4.1.0",
"@storybook/addon-knobs": "^4.1.0",
"@storybook/addon-links": "^4.1.0",
"@storybook/addon-notes": "^4.1.0",
"vue-cli-plugin-storybook": "^0.6.0",
```
Also tried installing `"@storybook/cli": "^5.0.1",` didn't make a difference.

**System:**
(Running in a docker container on Ubuntu 18.10 with `--ci` flag)
 - OS: Ubuntu 18.04
 - Device: Desktop
 - Browser: Chrome 72.0.3626.109 (Official Build) (64-bit)
 - Framework: Vue 2.6.8
 - Version: 5 (I think, assuming that is what the Vue plugin brings in).

**Additional context**
I also tried installing the dependencies mentioned in the [learnstorybook](https://www.learnstorybook.com/vue/en/simple-component/) guide (bottom of the page), but this made no difference and these seem to only be relevant when using storybooks via jest so this shouldn't matter.

**Comment by shilman** [comment]
cc @pksunkara

**Comment by pksunkara** [comment]
Will take a look at it this weekend.

**Comment by backbone87** [comment]
I guess this is a version fuck up by npm. `vue-cli-plugin-storybook` 0.6.0 is compatible with both sb4 & 5, but the addon version he installs are v4, so i guess npm did draw in a sb5 for the plugin.

Please post the output of `npm list @storybook/vue @storybook/addon-actions vue-cli-plugin-storybook`

**Comment by pksunkara** [comment]
You should update the addon versions to be the same as storybook versions.
