### ISSUE TITLE
Bootstrap import breaks background grid

### ISSUE THREAD

**Issue by rmdevos** [storybooks/storybook#6065]
**Describe the bug**
After importing Bootstrap CSS the background grid is no longer displayed.

**To Reproduce**
1. Add ```import 'bootstrap/dist/css/bootstrap.css';``` to config.js

**Expected behavior**
I expected the background grid to be present.

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
 - OS: Ubuntu
 - Device: PC
 - Browser: Chromium
 - Framework: React

**Comment by than-speedline** [comment]
The problem seems to relates to the background on the body of the iFrame being set to color other than transparent. Currently resetting the background color after importing bootstrap seem to have helped.

**Comment by nikdo** [comment]
I think this can be safely closed. Bootstrap sets body background, resetting it manually for usage in Storybook sounds like a proper solution.

The other solution is to change storybook to set a transparent `body` background using `!important`. But I'm not sure this is reasonable.

**Comment by nikdo** [comment]
.storybook/config.js:
```
import 'bootstrap/dist/css/bootstrap.css'
import './reset.css'

...
```

.storybook/reset.css:
```
body {
  background-color: transparent;
}
```
