### ISSUE TITLE
Dark theme doesn't render md files properly.

### ISSUE THREAD

**Issue by ruudyroon** [storybooks/storybook#6073]
This is light theme (everything looks great!) =>
https://ibb.co/pP4dkvx

This is how my md file looks in the dark theme => 
https://ibb.co/94X4f91

some of the text is dark in the dark theme, doesn't look right. Is there a way I can fix this? 
I'm on v5

**Comment by vpicone** [comment]
I have this PR that would allow for theming of this panel: https://github.com/storybooks/storybook/pull/5922

**Comment by vpicone** [comment]
My PR will allow for theming, however the addon-notes should be updated to be compatible with dark mode by default. It's unusable with dark mode in it's current state.

**Comment by shilman** [comment]
This was released in https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.11 so I'm closing this. Please re-open if there's more work to do here.
