### ISSUE TITLE
Expose API for how storybook slugify `selectedKind` and `selectedStory`

### ISSUE THREAD

**Issue by ryancat** [storybooks/storybook#6074]
**Is your feature request related to a problem? Please describe.**
From the migration guide https://github.com/storybooks/storybook/blob/next/MIGRATION.md#new-url-structure it is suggested to use story id instead of url queries to route to a story. We are using the old pattern with `selectedStory` and `selectedKind` in our url, and would like to convert to story id. However, there is no existing API (or I cannot find in documentation) that we can use to do that.

I found the source code is a simple string conversion https://github.com/storybooks/storybook/blob/baa9c2c760b2e706ebc992d55e05fd891fe3ff5d/lib/router/src/utils.ts#L13

**Describe the solution you'd like**
Either using a third party library to slugify (for example, [slug](https://www.npmjs.com/package/slug)), or expose an API from storybook that we can use to do the conversion

**Comment by shilman** [comment]
We've got that, tho there might be a better place for it:

```js
import { toId } from '@storybook/router/utils';
const id = toId(kind, story);
```

cc @ndelangen @tmeasday

**Comment by ryancat** [comment]
@shilman Thanks for pointing that out -- I should've tried that first as the function is exported.

However, in my usecase it's more than just using this API. I separated the storybook environment (test/demo environment) and the source code (library/app) in two repositories. The idea is storybook will provide me an environment and the library tests will just use an URL to visit that test environment. 

Hence, there is no direct dependency from the library repo to storybook. I want to make the test environment more generic (so that I can hide implementation details on which service to use to provide the test environment). Even storybook provides me this API, I cannot use it without setup dependency to storybook directly in my library repo.

I am not sure if this makes sense to you. I know that different test environment may have different assumption of URL patterns, so it's not a problem with storybook. However, it would be nice if storybook is using a more generic slugify library so that I can also use that just to composite URL in the library repo.

**Comment by tmeasday** [comment]
Unfortunately standard slugifying practices did not work for our use case (we looked around a bit)

**Comment by shilman** [comment]
@ryancat there's a possibility we would pull out a small set of utility functions like this into its own library in the future, but I wouldn't wait around for that. In the meantime, either take a dep on `@storybook/router` or copy-paste the relevant code ... or rethink your project layout which frankly sounds a little funky to me 😘
