### ISSUE TITLE
Old url pattern with "selectedKind" and "selectedStory" is not working

### ISSUE THREAD

**Issue by ryancat** [storybooks/storybook#6075]
**Describe the bug**
Using old URL pattern in storybook v5 will result in 'no preview' page, despite that the URL is correctly changed to use story id.

This is NOT happening in iframe.html pages. Using the old URL pattern works fine there.

**To Reproduce**
Go to https://storybooks-official.netlify.com/?selectedKind=ui%2FPanel&selectedStory=no%20panels, and you will see that the page is not loaded correctly

Now refresh the page, you will see the correct result.

**Expected behavior**
The correct rendering result should show on first try

**System:**
 - Version: ^5.0.0

**Comment by rieznik** [comment]
Have the same issue 😞 probably that is why I've got empty screenshots in [Chromatic](https://www.chromaticqa.com)

**Comment by tmeasday** [comment]
Oddly enough it actually *does* work in Safari, not in Chrome (reliably). I am going to close this and deal with it as part of #5925 -- see https://github.com/storybooks/storybook/issues/5925#issuecomment-485762342
