### ISSUE TITLE
Image loading not working in Storybook v5

### ISSUE THREAD

**Issue by elie222** [storybooks/storybook#6076]
**Describe the bug**
Unable to import media assets by importing (or requiring) them.

**To Reproduce**
1. Create a story with the following code:

```
import * as React from "react"
import { storiesOf } from "@storybook/react"

import imageFile from './header-background.png'

const image = {
  src: imageFile,
  alt: 'my image',
};

storiesOf("Header", module)
  .add('with an image', () => (
    <img src={image.src} alt={image.alt} />
  ))
```

2. Run Storybook

**Expected behavior**
I expect SB to load and show the image.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2015
 - Framework: react
 - Version: "@storybook/react": "^5.0.1"

**Other info:**
I am using Gatsby.

**Comment by shilman** [comment]
Closing this as a dupe to #5941
