### ISSUE TITLE
[addon-knobs] boolean could be a reserved word

### ISSUE THREAD

**Issue by leoyli** [storybooks/storybook#6090]
Hi, my colleague bug me when I write the code as the following:

```js
import { boolean } from '@storybook/addon-knobs';
         wwwwwww
```

He said, `boolean` is a reserved words.  I've know this as a reserved word in Java, but for the sake of the history, people generally try to avoid name a variable like this.  Similarly, `select` is also being suggested not to used.  The full list goes [W3Schools](https://www.w3schools.com/js/js_reserved.asp) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords).

Interestingly, upon the latest [ECMAScript specification](https://www.ecma-international.org/ecma-262/#sec-keywords), only `enum` is a future reserved words.

My question is, should we be more careful on these variable names?! Maybe renamed it to `bool` as in the react PropType?! (but it would be a breaking change though...

**Comment by shilman** [comment]
@leoyli sorry i missed this. i probably would've named it `booleanKnob`. i don't think we should fix it unless it's breaking for people. if you don't want that in your code you can always rename it at import time:

```js
import { boolean as bool } from '@storybook/addon-knobs'
```

**Comment by leoyli** [comment]
Yeah, that is what I did actually.  Not a big issue though since it would be a breaking change and need some extra deprecation warning.  But this maybe looks a bit strange for TypeScript people?! Although not necessary change the typing of `boolean` but it can be quite confused...

**Comment by shilman** [comment]
@leoyli I'd be up for making this change:
1) In a major release of SB
2) Alongside some other major changes to knobs
