### ISSUE TITLE
Custom fonts are not encoding correctly

### ISSUE THREAD

**Issue by mgimenez** [storybooks/storybook#6092]
Tried with Lato Google Font, the files are downloaded but there is an encoding issue.
I tried a lot of forman and just it worked in BASE64.
Is there a way to use TTF files?

![image](https://user-images.githubusercontent.com/2190656/54384023-1986ee00-4672-11e9-9e85-a802e955b206.png)

Thanks.

**Comment by shilman** [comment]
what version of storybook? any custom webpack config?

**Comment by ndelangen** [comment]
Is it that the mime-types are incorrect?

Can you please provide more information and possible provide a reproduction?
