### ISSUE TITLE
Unable to create React storybook

### ISSUE THREAD

**Issue by plug-n-play** [storybooks/storybook#6102]
The command given at https://storybook.js.org/docs/guides/guide-react/, 

npx -p @storybook/cli sb init --type react

is failing with following error:

![image](https://user-images.githubusercontent.com/6245927/54402337-a9b84800-46f1-11e9-85ca-b14835b9a324.png)

**Comment by shilman** [comment]
What kind of project are you installing into?

**Comment by shilman** [comment]
Duplicate to https://github.com/storybooks/storybook/issues/6002
