### ISSUE TITLE
The addon-viewport tab does not show in storybook

### ISSUE THREAD

**Issue by lestrato** [storybooks/storybook#6109]
**Describe the bug**
Addon-viewport tab does not show in storybook
There are no issues in starting up storybook.
Is there something I'm missing in configuration?

**To Reproduce**
1. `npm install --save-dev @storybook/addon-viewport`
2. `import '@storybook/addon-viewport/register';` inside **addons.js**

**Expected behaviour**
The Viewports tab is expected to show up in Storybook

**Screenshots**
![image](https://user-images.githubusercontent.com/21113702/54435391-c317bf00-4706-11e9-99b8-5eeced7a2b03.png)

**Code snippets**
This is my **config.js**
```
import { configure } from '@storybook/react';
import { addParameters } from '@storybook/react';
import {
  configureViewport,
  INITIAL_VIEWPORTS
} from '@storybook/addon-viewport';

import 'Styles/index.scss';


// automatically import all files ending in *stories.js
const req = require.context('Components', true, /stories\.js$/);
const loadStories = () => {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);

const newViewports = {
  mobile: {
    name: 'Mobile',
    styles: {
      width: '320px',
      height: '568px'
    }
  },
  tablet: {
    name: 'Tablet',
    styles: {
      width: '768px',
      height: '1024px'
    }
  },
  laptop: {
    name: 'Laptop',
    styles: {
      width: '1200px',
      height: '1024px'
    }
  },
  desktop: {
    name: 'Desktop',
    styles: {
      width: '1366px',
      height: '1024px'
    }
  },
  wide: {
    name: 'Wide',
    styles: {
      width: '1920px',
      height: '1080px'
    }
  }
};

configureViewport({
  viewports: newViewports,
  defaultViewport: 'Mobile'
});
```
---
this is my *addons.js*
```
import '@storybook/addon-viewport/register';
import '@storybook/addon-actions/register';
import '@storybook/addon-knobs/register';
```

**System:**
 - OS: [Ubuntu 16.04 LTS]
 - Device: [Lenovo-B50-+]
 - Browser: [chrome]
 - Framework: [react]
 - Addons: ["@storybook/addon-viewport]
 - Version: [e.g. ^5.0.1]

**Comment by shilman** [comment]
It's now in the toolbar at the top of the screen, furthest icon on the right. Do you need it to show up in a tab?

**Comment by lestrato** [comment]
Ah! It was in a tab in previous versions, next to Knobs tab so I was confused why it wasn't here.
https://github.com/storybooks/storybook/blob/master/addons/viewport/docs/viewport.png

**Comment by lhguerra** [comment]
I don't think this issue should be closed since the Readme is still wrong and causing confusion.

**Comment by shilman** [comment]
@lhguerra Mind taking a pass at updating the README and create a small PR?

**Comment by lhguerra** [comment]
@shilman not at all. Will do it tonight.

**Comment by mkchx** [comment]
@shilman Is it still possible to have it as a tab? instead of an icon with drop-down options

**Comment by shilman** [comment]
@mkchx Not AFAIK. @ndelangen any plan on making addon UI more portable? Seems like people want to move stuff around
