### ISSUE TITLE
Resizing window vertically can put addons panel under preview panel and get stuck thee 

### ISSUE THREAD

**Issue by mohsen1** [storybooks/storybook#6115]
if resize window vertically to small enough hight, it's possible to put the header of addons panel under preview header and make it impossible to grab the splitter handler to make addons panel smaller:

<img width="871" alt="Screen Shot 2019-03-15 at 1 14 26 PM" src="https://user-images.githubusercontent.com/543633/54449442-72af5a00-4724-11e9-8c17-d142d74fac42.png">

Resizing the window back will **not** make the addons panel smaller:
<img width="865" alt="Screen Shot 2019-03-15 at 1 15 55 PM" src="https://user-images.githubusercontent.com/543633/54449456-82c73980-4724-11e9-9b11-58c2f39cca4f.png">

**System:**
 - OS: MacOS Mojave
 - Device: Macbook Pro
 - Browser: Chrome 73
 - Framework: React
 - Addons: knob, actions and link
 - Version: 5.0.1

**Additional context**
Sometimes the panel header is completely hidden. This is why I filed https://github.com/storybooks/storybook/issues/6087 assuming enabling addons will make preview disappear

**Comment by shilman** [comment]
Cc @kroeder
