### ISSUE TITLE
[addon-notes] inaccurate documentation for imported markdown

### ISSUE THREAD

**Issue by jjspace** [storybooks/storybook#6117]
**Describe the bug**
In the `README` for the notes addon it shows this code to load markdown:

```javascript
import notes from './someMarkdownText.md';

storiesOf('Component', module)
  .add('With Markdown', () => <Component />, { notes });
```

However this does not actually work to include a markdown file and does not seem to even be the supported method in SB v5 as you can see in the code from the official [Storybook Example/addon-notes](https://storybooks-official.netlify.com/?path=/story/addons-notes--addon-notes-rendering-imported-markdown)

**To Reproduce**
1. Create any new story and a markdown file with some content
2. Import the markdown file as it shows in the README
3. Include the notes in the story parameters

**The Fix**
Import like this instead:

```javascript
import markdownNotes from './notes/notes.md';

storiesOf('Addons|Notes', module)
  .add('addon notes rendering imported markdown', baseStory, {
    notes: { markdown: markdownNotes },
  });
```

**Comment by MarcoDeJong** [comment]
I've been searching for days. This fix is validated and working.

**Comment by shilman** [comment]
Thanks for this correction. Is there any chance you can create a small PR for this?

**Comment by MightyRevenge** [comment]
I noticed this as well! Thanks for the correction too!

**Comment by madrus** [comment]
The fix of __jjspace__ above alas did not work for me with Typescript. Import was complaining that my Markdown file was not found (it was expecting a module). So, my workaround was to convert my markdown file `notes.md` to a Javascript file `notes.md.js`:
``` js
module.exports = `
# Storybook Notes
This is an example of Storybook Notes in __Markdown__
`
```
After that I could import it like this:
``` js
import markdownNotes from '../notes/notes.md'
```
and use it like this:
``` js
storiesOf('addons|notes', module)
  .add('With Markdown', 
    () => <Component />,
    {
      notes: { markdown: markdownNotes }
    }
  )
```
