### ISSUE TITLE
Storybook hangs with 100% CPU load due to unnecessary use of react-docgen

### ISSUE THREAD

**Issue by ilyabo** [storybooks/storybook#612]
There is an open issue in react-docgen which causes react-storybook to stay in an infinite loop while parsing the source code of the stories when a specific pattern is used in code: https://github.com/reactjs/react-docgen/issues/136

I attached a minimal project with storybook to reproduce the issue: [storybook-high-cpu-load.zip](https://github.com/storybooks/react-storybook/files/583189/storybook-high-cpu-load.zip)

Commenting out this line in babel_config.js to disable babel-plugin-react-docgen resolves the issue with react-storybook:

<img width="1368" alt="upload" src="https://cloud.githubusercontent.com/assets/351828/20174519/6fb837c8-a73e-11e6-886d-27e0ea8ae817.png">

I realize that the root of the problem is not an issue of react-storybook, but of react-docgen. However, if I understand correctly, react-docgen is only needed for specific plugins (e.g. which display component properties). Therefore, I think, the react-docgen part shouldn't be always added by default, especially, since it is expensive and can also cause such serious issues.

**Comment by arunoda** [comment]
You've made a good point.
I'll think about a way to deal with this.

**Comment by onelson** [comment]
Ran into this today - thought I was losing my mind when storybook just stopped responding with every logged click.

Using callbacks which console.log() out the arguments seems to be the workaround I'm left with, but makes our storybook usage inconsistent from story to story. :(

**Comment by thenewvu** [comment]
I faced this issue today, I overwrote webpack config with `devServer.lazy = true`, webpack only rebuilds when I reload the storybook. I know this is inconvenience, but my CPU temperature raises too high (around 65 degrees), my hands smelt like a fried steak.

**Comment by shilman** [comment]
@dburles does this match the issue you were seeing yesterday?

**Comment by dburles** [comment]
@shilman looks very much like it is

**Comment by felizuno** [comment]
Sorry if this is ignorant, I'm new here ;-)

This was an ongoing issue with what seems to be the boilerplate used to build the app (at startup I see `=> Using default webpack setup based on "Create React App".`). 

Issue discussion: https://github.com/facebookincubator/create-react-app/issues/293https://github.com/facebookincubator/create-react-app/issues/293

Is there a policy here WRT staying up to date with that source repo?

**Comment by felizuno** [comment]
Also FWIW after downgrading to the 6.11.2 LTS release of Node I no longer experience this issue
