### ISSUE TITLE
After an error fix, it'll load the first story

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybook#614]
If there's a syntax error, it should show the webpack error overlay.
After that, it should reload the preview and load the current story.

But now, it'll load the first story in the storybook instead.

### Reason

After an error, it'll reload the page. Then it'll load the very first story since that is hard coded on the iframe URL. We need to change it and reload.

**Comment by tmeasday** [comment]
This one is really annoying me right now. Will take a look.

**Comment by tmeasday** [comment]
Does anyone have a reproduction for this? I can't make it happen RN

**Comment by tmeasday** [comment]
This is actually easy to reproduce. Follow these steps carefully (tested on current `release/3.3`):

1. Load the `cra-kitchen-sink` storybook
2. Browse to http://localhost:9010/ (that exact path).
3. Browse to a different story (not the welcome story).
  - Notice that the main URL will change
  - Also notice the iframe URL will *not* change.
4. Add `throw new Error("foo");` somewhere in some story file at the top level, allow HMR
  - Notice the error show in a red box in the preview iframe
5. Remove the error, allow HMR
  - Notice the welcome story is rendered in the iframe, even though the main URL is still the URL for the other story.
6. Hit refresh
  - Notice the correct story now loads in the iframe
  - Also notice the iframe URL is now in sync with the main URL.

Note if you are going to continue you have to start again at step 1, not continue on from step 6, as the iframe URL will have changed.

**Comment by tmeasday** [comment]
See https://github.com/storybooks/storybook/pull/2349

**Comment by tmeasday** [comment]
This was fixed in 3.3.0
