### ISSUE TITLE
Accessing user theme config in addon?

### ISSUE THREAD

**Issue by leepowellcouk** [storybooks/storybook#6146]
When writing a custom addon, is it possible to access the users theme settings that were set via `addParameters`.

Consider the following:

```
// config.js
addParameters({
  options: {
    theme: themes.dark,
  }
}
```

In my addon I want to access this so I can load in the relevant css for my panel at the point of registration.

**Comment by yjcxy12** [comment]
From source code of addon-backgrounds, you can use the `api.getCurrentStoryData()` to access all parameters for the story.

For reference

https://github.com/storybooks/storybook/blob/next/addons/backgrounds/src/register.tsx#L12

https://github.com/storybooks/storybook/blob/next/addons/backgrounds/src/containers/BackgroundSelector.tsx#L59

**Comment by shilman** [comment]
This has been updated in 5.1 and @ndelangen is working on an add-on guide to document this
