### ISSUE TITLE
Static build is not loading story when refresh or in a shared link

### ISSUE THREAD

**Issue by leoyli** [storybooks/storybook#6156]
**Describe the bug**
Unlike dev mode, the static build storybook is not loading story, leading a **No Preview** page.

**To Reproduce**
1. Build the storybook app statically, using `npx serve .\${BUILD}` script to sever static file locally
2. See the first story
3. Refresh or share the link to others
4. See **No Preview** and no story loading

**Expected behavior**
Static build should work the same a in the dev mode

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
 - OS: MacOS Mojave
 - Device: Macbook Air 2013-mid
 - Browser: Chrome 72
 - Framework: React
 - Addons: N/A
 - Version: 5.0.3

**Additional context**
N/A

**Comment by emjaksa** [comment]
I am experiencing the same issue. @leoyli do you have showPanel set to false?
I only experience the issue after setting showPanel to false.

**Comment by leoyli** [comment]
This is really weird... It seems like this was actually happened when you open it directly in the local file system?! Anyway, I think I will close this issue for the moment since SB is happy and normal when we deployed the static build internally.

**Comment by natterstefan** [comment]
Hi @leoyli, I have the same issue right now. We are also using `serve` for the static bundled build of our stories. Can you tell me what you mean with "when you open it directly in the local file system"?

**Comment by leoyli** [comment]
> Can you tell me what you mean with "when you open it directly in the local file system"?

Just open the file directly from the OS folder instead of have a local server serving files from localhost.

I'm not really sure what was going on but I can not always reproduce this problem... If @natterstefan have a reproducible steps then it may worth to reopen this issue.

**Comment by shilman** [comment]
@leoyli you mean `file://` URLs?

**Comment by leoyli** [comment]
@shilman, yes.

**Comment by natterstefan** [comment]
Hi @leoyli,

Interesting, I did not open it with `file://`.

All I do is building the storybook with this command: `"build-storybook": "rimraf dist && build-storybook -c .storybook -o dist/storybook && copyfiles static/**/* dist/storybook",` _inside_ a Dockerfile. It is then later served in the docker image with `serve dist/storybook -p 9001` ([serve module](https://www.npmjs.com/package/serve)).

I'll try to create reproducible steps and maybe an example, but will not be able to open-source(show) the repo I am experiencing the issue (due to company/project restrictions).

**Comment by shilman** [comment]
@natterstefan Have you tried `cd`ing into the folder and serving from there? It shouldn't make any difference, but just throwing it out there...

**Comment by natterstefan** [comment]
Hi @shilman, good idea. I just tried it

```sh
yarn build-storybook
cd dist/storybook
serve -p 9001
```

and it did not work. :/ I'll later try it with an nginx inside the image instead. Let's see what happens then.
