### ISSUE TITLE
Regression in 5.0.2 (loader for svg)

### ISSUE THREAD

**Issue by KhodeN** [storybooks/storybook#6178]
**Describe the bug**
Lots of errors after update from 5.0.1 to 5.0.2. Mostly they are about wrong loader for SVG. I use stock create-react-application 2 project.

Downgrade to 5.0.1 solves the problem, but I want to be on bleeding edge. In 5.0.3 the problem still presents.

**Screenshots**
```
ERROR in ./src/modules/toasts/icons/times-black.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Browser: -
 - Framework: react (CRA2)
 - Addons: -
 - Version: 5.0.2

**Comment by shilman** [comment]
Are you using any webpack customizations? We changed the webpack config in 5.0.2 to fix a regression that got introduced from 4.x to 5.0: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#from-version-501-to-502

It's very likely your change in behavior came from this. Can you paste your `webpack.config.js` and also the story in question including your import?

**Comment by KhodeN** [comment]
Thank you, I miss that guide. Fixed.

**Comment by shilman** [comment]
Sorry about the confusion. It was technically a breaking change, but it was a breaking change to fix a bug, so I released it as a patch knowing that it would probably cause a few headaches. Glad this one was relatively easy to fix! 😄
