### ISSUE TITLE
Regex in config.js is not correct

### ISSUE THREAD

**Issue by Means88** [storybooks/storybook#6179]
**Describe the bug**
Files other than `*.stories.js` are imported by storybook.

**To Reproduce**
1. Create file named `build-stories.js` in <project>/stories
2. Add `import fs from 'fs'` in it
3. `yarn storybook`

```
ERROR in ./stories/build-stories.js
Module not found: Error: Can't resolve 'fs' in '<project>/stories'
 @ ./stories/build-stories.js 24:0-20
 @ ./stories sync .stories.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```

**Expected behavior**
`build-stories.js` not imported by storybook.

**Screenshots**
![image](https://user-images.githubusercontent.com/5810331/54597928-6c95e200-4a72-11e9-8333-3f5ed03a0306.png)

**System:**
 - OS: macOS
 - Browser: Chrome
 - Framework: React
 - Version: 5.0.2

**Additional context**
PR: #6180

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.12 containing PR #6180 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.4 containing PR #6180 that references this issue. Upgrade today to try it out!
