### ISSUE TITLE
Grouping / headings?

### ISSUE THREAD

**Issue by TheKnarf** [storybooks/storybook#6187]
On the frontpage of Storybooks webpage you can find the following video:
https://storybook.js.org/videos/storybook-hero-video-optimized.mp4

It shows two groupings: `LIBRARY` and `WEB APP`, how do I setup that kind of grouping? I can't find the documentation for it anywhere.

**Comment by shilman** [comment]
See `hierarchyRootSeparator`:

https://github.com/storybooks/storybook/blob/next/MIGRATION.md#story-hierarchy-defaults

We probably need to document this better in the docs

**Comment by TheKnarf** [comment]
Thanks, that solved it for me.

**Comment by shilman** [comment]
It's also documented here, but maybe not explicit enough:

https://storybook.js.org/docs/configurations/options-parameter/

https://github.com/storybooks/storybook/blob/next/docs/src/pages/configurations/options-parameter/index.md

If anybody wants to take a cut at improving the docs for this specific feature--to make it more clear and discoverable, that would be really great. You're not the first person to ask about it @TheKnarf
