### ISSUE TITLE
Use commitizen & semantic-release to make releases more transparent

### ISSUE THREAD

**Issue by joscha** [storybooks/storybook#619]
I think storybooks could greatly benefit from https://github.com/semantic-release/semantic-release and https://github.com/commitizen/cz-cli as it would mean versioning is cleanly controlled and the changelog on github will get automatically populated. Currently unless following specific issues it is really hard to determine when what got fixed and what a new version changes/entails.

**Comment by arunoda** [comment]
I think we could improve the workflow with Semantic Release.

But we always follow semvar and maintain a [decent Changelog](https://github.com/storybooks/react-storybook/blob/master/CHANGELOG.md).

So, I don't think this is correct.
> Currently unless following specific issues it is really hard to determine when what got fixed and what a new version changes/entails.

Unless, I missed something else.

**Comment by joscha** [comment]
Sorry, I didn't mean to say you use semver incorrectly, I am merely saying that it currently is not obvious what a new release entails. For example if I hadn't followed #555 because of #606 I wouldn't know that the fix is part of `v2.30.1`. So for anyone other than people finding the problem beforehand or searching for it, there is no way to see what an update means.
If you compare https://github.com/semantic-release/semantic-release/releases (auto-generated from the commit messages) with https://github.com/storybooks/react-storybook/releases (empty) you see what I mean.
