### ISSUE TITLE
File access broken since v5

### ISSUE THREAD

**Issue by ColCh** [storybooks/storybook#6191]
**Describe the bug**

Updated storybook to v5, got bug :)

**To Reproduce**
1. Build storybook
2. open `index.hmtl` with `file:///` path

**Expected behavior**

there is no error

**Screenshots**

![image](https://user-images.githubusercontent.com/599439/54646329-c7016380-4aaf-11e9-9b07-6c26175e2827.png)

**Code snippets**

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLIFrameElement.n (vendors~main.a7641db39c9f16a9b895.bundle.js:66)
```

not applicable

**System:**
 - OS: [e.g. iOS, Windows10, MacOS] Mac OS Mojave
 - Device: [e.g. iPhoneX, Macbook Pro 2018] MBP 2015 '15
 - Browser: [e.g. chrome, safari] chrome
 - Framework: [e.g. react, vue, angular] react
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0] 5.0.3

**Additional context**

debugged for you

![image](https://user-images.githubusercontent.com/599439/54646514-53ac2180-4ab0-11e9-9312-a5f085490ace.png)

**Comment by Armanio** [comment]
Seems like fixed in https://github.com/storybooks/storybook/pull/6238
Could you update you sb version and proof it?

**Comment by ColCh** [comment]
@Armanio yes, this is fixed. Thank you!
