### ISSUE TITLE
Passing a custom parameter from the conifg.js into a story?

### ISSUE THREAD

**Issue by Ziv-Barber** [storybooks/storybook#6192]
**Is your feature request related to a problem? Please describe.**
It'll be nice if storybook will support global custom parameters.

**Describe the solution you'd like**
For example, let's say that I have one or more themes in my app and I'm writing components that I want to re-use in other apps (using bit.dev for example).
So what I want to do is to place the list of themes available in each app inside the storybook configuration and then to have additional component that I'll use only in storybook that it'll use the configuration to detect what themes available and to offer selecting a theme + a fallback if no theme defined (in this case it'll just use the default theme).
Also I can add another storybook only component to show example colors, typography, common controls, etc. With global custom configuration parameters I can have customize what controls to show in the theme example story.

**Describe alternatives you've considered**
I guess that I can be doing it by saving data in global but it's ugly and mutable.
I'll try now my workaround with the global - but it's ugly.

**Are you able to assist bring the feature to reality?**
maybe

**Additional context**
No

**Comment by shilman** [comment]
Is this kind of like a global addon-knobs?
