### ISSUE TITLE
What addon is used to separate stories into subsections here?

### ISSUE THREAD

**Issue by sergiotapia** [storybooks/storybook#6198]
https://storybooks-official.netlify.com/?path=/story/basics-badge--all-badges

Addons, App, Core, etc. Notice how the stories are separated by sections.

What addon is this?

Thank you!

**Comment by tomspeak** [comment]
I do not believe this is an add on, you can see in their code they are using:

```
storiesOf('Basics|Spaced', module)
```

Using the `|`, creates a separation, in the same way `/` allows you to nest stories.

https://storybook.js.org/docs/basics/writing-stories/#generating-nesting-path-based-on-__dirname

It is not explicitly stated in the docs, but it is there.

**Comment by tomspeak** [comment]
Tell a lie, it is here: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#story-hierarchy-defaults 

Maybe not as prominent as it could be! I'm sure they'd be up for a PR to improve the docs @sergiotapia.

**Comment by sergiotapia** [comment]
Thanks much appreciated, hopefully this Github issue helps people find the right info.

**Comment by shilman** [comment]
It's also documented here, but maybe not explicit enough:

https://storybook.js.org/docs/configurations/options-parameter/

https://github.com/storybooks/storybook/blob/next/docs/src/pages/configurations/options-parameter/index.md

If anybody wants to take a cut at improving the docs for this specific feature--to make it more clear and discoverable, that would be really great. You're not the first person to ask about it.
