### ISSUE TITLE
Display StorybookUI in your app in React Native

### ISSUE THREAD

**Issue by amed** [storybooks/storybook#6214]
The App that we are currently developing is migrated to latest versions of react native and storybook.  (React-Native 0.59 with Storybook 5)

**previous situation**: Storybook4, running via `$ react-native start --projectRoot storybook`
**current situation**: Running `StorybookUI` via replacing `projectRoot` is not working anymore. (previous approach is not working)

Also as it is documentation describes:
[Storybook for React Native](https://storybook.js.org/docs/guides/guide-react-native/#manual-setup) in "Display StorybookUI in your app" section, this `StorybookUI` should be exported as the default component. Another idea is to use it somewhere inside the app which seems to me like an odd behaviour. The production bundle will have all unnecessary components and add-ons (possibly).

Is there a better way integrate Storybook in React Native?

**Comment by shilman** [comment]
@amed Pretty sure that suggestion is just for development mode. Nobody wants extra stuff in their production app? cc @benoitdion @Gongreg

**Comment by oblador** [comment]
It was a [regression in the RN CLI](https://github.com/react-native-community/react-native-cli/pull/259), installing latest via `yarn add @react-native-community/cli --dev` should fix the issue.
