### ISSUE TITLE
[addons] - Cannot read property '__STORYBOOK_ADDONS' of undefined

### ISSUE THREAD

**Issue by CodeByAlex** [storybooks/storybook#6233]
**Describe the bug**
When I run yarn dev, after pulling down the project, running yarn install and yarn bootstrap --reset --core, I get errors stating:
- Could not find a declaration file for module 'telejson' (shows up on other addons)
- Could not find a declaration file for module 'react-inspector' (shows up on other addons)
- Property 'warn' does not exist on type 'typeof import(".../lib/client-logger/dist/index")

When I try to fix those by correctly importing warn and adding the types to the typings, I get this error when yarn linking to another project:
Cannot read property '__STORYBOOK_ADDONS' of undefined at getAddonsStore (index.ts:97) at Object.../storybook/lib/addons/dist/index.ts

After that error comes up, none of the components are listed in the side panel nor are they rendered in the iframe. I can't do any local development on Storybook until this is resolved.

**To Reproduce**
1. Pull down a brand new copy of the project
2. Run yarn install
3. run yarn bootstrap --reset --core
4. run yarn dev
5. see errors

**Expected behavior**
Errors shouldn't appear during yarn dev run, and if resolved, I should be able to link an addon to another project and see the components being rendered as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/29763590/54814716-a9c2c580-4c66-11e9-9d12-d943f1e38cc8.png)
![image](https://user-images.githubusercontent.com/29763590/54814809-d4ad1980-4c66-11e9-9388-bacc0d5d3d04.png)
![image](https://user-images.githubusercontent.com/29763590/54814849-ed1d3400-4c66-11e9-8b9e-e048265cb512.png)

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [chrome, firefox]
 - Framework used in external project using link to local: [Angular]
 - Version: [NEXT - first seen as of local merge on 3-20 (but hadn't merged in since 3-15 when working on a feature). Continuing to see as of 3-22-19]
 - External project using the yarn link is using version: 5.1.0-alpha.12

**Comment by CodeByAlex** [comment]
@ndelangen @shilman could this have to do with the API changes that went in?

**Comment by ndelangen** [comment]
Why is `lib/addons/dist/index.ts` being loaded instead of `lib/addons/dist.index.js`

I think this is part of the problem.

**Comment by CodeByAlex** [comment]
I am not quite sure and I'm trying to figure out where to start with this one. Fixing the errors in the addon didnt solve the issue. Im using 5.1.0-alpha.12 in the external project and linking in the next version of storybook. Has an important change with the way addons work not been released that could be in next as of 3-15-19?

What I've shown is a clean slate project so it should be able to be replicated. Many other addons are having similar issues locally. Is anyone else able to see this issue when pulling down and running the commands?

**Comment by CodeByAlex** [comment]
@shilman, still not sure what is causing this problem but I am able to continue development without linking using the cra-kitchen-sink. I should be good for now.

**Comment by shilman** [comment]
@CodeByAlex I suggest using `official-storybook` since it uses the `--no-dll` flag and therefore works with `yarn dev`.
