### ISSUE TITLE
Vulnerability Concern

### ISSUE THREAD

**Issue by Mbarak-Mbigo** [storybooks/storybook#6234]
**Describe the bug**
One of the dependencies `"jest-specific-snapshot": "^1.0.0",`, has a dependency to a package that has a vulnerability, and it's being flagged by `npm audit`

**To Reproduce**
1. install @storybook/addon-storyshots v5.0.3
2. run npm audit

**Expected behavior**
npm audit warning on braces used by jest-message-util used by jest-snapshot used by jest-specific-snapshot used by @storybook/addon-storyshots...

**Screenshots**
![image](https://user-images.githubusercontent.com/25595450/54821265-b2d98400-4cb2-11e9-9af7-12a984cb45f4.png)

**Comment by arturopie** [comment]
This seems to be a duplicate of #6110

**Comment by shilman** [comment]
Good call @arturopie , closing as dupe
