### ISSUE TITLE
Is there a way to add <script> tags to the end of the story iframe?

### ISSUE THREAD

**Issue by Jonathan0wh** [storybooks/storybook#6247]
I followed the guide in [Add Custom Head Tags](https://storybook.js.org/docs/configurations/add-custom-head-tags/) section and created the ```preview-head.html``` inside my ```.storybook``` folder, which allowed me to add custom tags such as ```<link rel="stylesheet" />``` and ```<script src="js/jquery.min.js"></script>``` to the head tag inside the iframe.

But when I tried to find a way to add some footer scripts such as ```<script src="js/custom-flex.js"></script>``` to the footer inside the iframe, I had difficulty because it seems that there was no such ```preview-footer.html```. These js files would take much time to be integrated inside React, therefore I just put them at the end of ```public/index.html```. But I could hardly do the same for stories in Storybook.

Essentially, I just want to load these javascript files at the end of the iframe document. I tried to use ```$(document).ready(() => {$.getScript("js/custom-flex.js")})``` in ```preview-head.html``` but it did not work. I also tried to use ```$(document).ready(() => {$(document).append("<script src="js/custom-flex.js"></script>")})``` in ```preview-head.html```, but it just added this ```<script>``` tag to the end of the iframe document without running the js inside. Is there a way to resolve or work around this problem? Any help would be appreciated. Thanks!

**Comment by JonathanLefebvreV** [comment]
I have the same problem and am experimenting for weeks to find a way without success.
 Did you find a solution @Jonathan0wh ?
