### ISSUE TITLE
CSS added by backgrounds addons should use "!important"

### ISSUE THREAD

**Issue by nemaniarjun** [storybooks/storybook#6250]
**Describe the bug**
I am importing a CSS file, which is meant to be used in other applications across our organization, thus I don't want to make changes to it.
The CSS added by the backgrounds addons should have preference over imported CSS file.

**To Reproduce**
1. Create a new repo using cra
2. Init storybook and backgrounds addons
3. Import CSS file with 
```
...
body {
 background-color: white;
}
...
```
4. Backgrounds doesn't work anymore.

**Expected behavior**
The CSS added by the backgrounds addons should have preference over imported CSS file.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - Version: 5.0.3

Link to static hosted storybook: http://ui-storybook.aicrowd.com

**Comment by Armanio** [comment]
Hmm, interesting. Just to add `!important` will not help in this case. Background div - it's a wrapper around the preview iframe. If you add `background` property to the body in the iframe then you will overwrite selected background from bg addon. 
I can propose a simple solution: don't use bg in your main.css

Otherway: we can rethink the bg addon work. Eg set the background to the iframe>body directly. It needs a little time.
What do you think, @ndelangen?

**Comment by nemaniarjun** [comment]
I will use the simple solution for now, but as I said, in cases where one want a single CSS for use across apps in an organization. Editing that css for the storybook is something one might not want to do.

**Comment by ndelangen** [comment]
@Armanio we can set the background to the body of the iframe, but..

Why does a component set a background on the body?

Should storybook try to fight for dominance inside the preview for styling?

Will we win the fight without causing other issues?

---

I humbly think if a user is setting a background as part of their base styles, he/she is better off explicitly removing that style via `preview-head.html`. And by doing so making the iframe transparent.
