### ISSUE TITLE
api.on is not a function

### ISSUE THREAD

**Issue by devarashetty** [storybooks/storybook#6258]
**Describe the bug**
Tried to implement the `jest addon`. the moment I add the addon it's giving me the above error in console

**To Reproduce**
1. Go to  `.storybook/addons.js` 
   and add `import '@storybook/addon-jest/register'`

**Comment by devarashetty** [comment]
@ndelangen  Please check the above issue .Thanks

**Comment by shilman** [comment]
What version?

**Comment by devarashetty** [comment]
@storybook/react - 4.0.12

**Comment by shilman** [comment]
What version of `addon-jest`?

**Comment by devarashetty** [comment]
@storybook/addon-jest - 5.0.5

**Comment by shilman** [comment]
There you go... 😉

**Comment by devarashetty** [comment]
please let me know

**Comment by shilman** [comment]
They should be the same version
