### ISSUE TITLE
vue this.$refs.xx.function is not a function

### ISSUE THREAD

**Issue by ayiaq1** [storybooks/storybook#6288]
1. vue-cli3 create
2. npm install @storybook/vue --save-dev
3. npm install vue-loader vue-template-compiler @babel/core babel-loader babel-preset-vue --save-dev 
4. App.vue has children components A.vue

**Code snippets**

`
<div>
        <A ref="A"></A>
    </div>

    mounted() {
        this.$nextTick(() => {
            console.log(this.$refs.A); // is find A
            this.$refs.A.func();
        });
    }
`
    

5. npm run storybook
6. Error!  _this.$refs.A.func()  is not a function

**Comment by backbone87** [comment]
more context needed: in which component do you use the mounted listener? which component sets the ref?

**Comment by ayiaq1** [comment]
![1](https://user-images.githubusercontent.com/3860498/55043655-26dca900-5072-11e9-8cf8-3681408e2936.jpg)
App.vue mounted A.vue

**Comment by backbone87** [comment]
do you use vue-cli-plugin-storybook?

**Comment by ayiaq1** [comment]
Oh my god, I didn't see this in the API documentation? Do you have a link address

**Comment by backbone87** [comment]
come on: http://lmgtfy.com/?q=vue-cli-plugin-storybook

**Comment by ayiaq1** [comment]
good! 3Q
