### ISSUE TITLE
storybook 5.0.5 upgrade broken on load svg and png

### ISSUE THREAD

**Issue by RyanZhu1024** [storybooks/storybook#6306]
**Describe the bug**
```shell

ERROR in ./icon/sortIcon/images/sort_asc.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.

ERROR in ./icon/viewFileIcon/view-Active.svg 1:0
Module parse failed: Unexpected token (1:0)
```

**Expected behavior**
Everything is fine before upgrading to 5.0.5. It was 5.0.1

**System:**
 - OS: [MacOS]
 - Device: [ Macbook Pro 2015]
 - Framework: [react]
 - Version: [5.0.5]

**Comment by RyanZhu1024** [comment]
I'm going to downgrade back to 5.0.1. Now all are back to normal

**Comment by shilman** [comment]
There was a bugfix in `5.0.2` and I'm guessing you're using `extend-mode` webpack configuration. If you convert to `full-control` it should work. More info:

https://github.com/storybooks/storybook/blob/next/MIGRATION.md#deprecate-webpack-extend-mode

**Comment by RyanZhu1024** [comment]
@shilman thank you! Problem solved!!
