### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by VladimirHumeniuk** [storybooks/storybook#6311]
I have this errors in console, when i run Storybook (tried 5.0.5 and 5.0.3). Does anyone faced with this?

```
Uncaught TypeError: Object(...) is not a function
    at Function.div (vendors~main.cbfa0565136f7756886e.bundle.js:2795)
    at Object.../../../node_modules/@storybook/components/dist/Badge/Badge.js (vendors~main.cbfa0565136f7756886e.bundle.js:15399)
    at __webpack_require__ (runtime~main.7861100cd90c77ea6569.bundle.js:84)
    at Object.../../../node_modules/@storybook/components/dist/index.js (vendors~main.cbfa0565136f7756886e.bundle.js:16902)
    at __webpack_require__ (runtime~main.7861100cd90c77ea6569.bundle.js:84)
    at Object.../../../node_modules/@storybook/addon-knobs/dist/components/Panel.js (vendors~main.cbfa0565136f7756886e.bundle.js:10776)
    at __webpack_require__ (runtime~main.7861100cd90c77ea6569.bundle.js:84)
    at Object.../../../node_modules/@storybook/addon-knobs/dist/register.js (vendors~main.cbfa0565136f7756886e.bundle.js:13304)
    at __webpack_require__ (runtime~main.7861100cd90c77ea6569.bundle.js:84)
    at Object.../../../node_modules/@storybook/addon-knobs/register.js (vendors~main.cbfa0565136f7756886e.bundle.js:13372)
```

**Comment by shilman** [comment]
This looks a bit like the React version error: https://github.com/storybooks/storybook/issues/4796

But it doesn't make sense in 5.0, so I'm not sure what's going on...

**Comment by VladimirHumeniuk** [comment]
@shilman  exactly, because I already tried on 16.8.0 and 16.3.0

**Comment by shilman** [comment]
@VladimirHumeniuk did you figure it out?

**Comment by VladimirHumeniuk** [comment]
@shilman no, we just abandoned the idea of using the 5.*.* versions.

**Comment by shilman** [comment]
That's a shame. Can you paste your package.json deps?

**Comment by VladimirHumeniuk** [comment]
@shilman 

```
    "@emotion/core": "^0.x.x",
    "@storybook/addon-a11y": "^5.0.5",
    "@storybook/addon-actions": "^5.0.5",
    "@storybook/addon-backgrounds": "^5.0.5",
    "@storybook/addon-knobs": "^5.0.5",
    "@storybook/addon-viewport": "^5.0.5",
    "@storybook/react": "^5.0.5",
    "babel-loader": "^8.0.4",
    "eslint": "^5.9.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-plugin-flowtype": "^3.2.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1",
    "file-loader": "^2.0.0",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "reset-css": "^4.0.1",
    "storybook-addon-jsx": "^6.0.0",
    "storybook-readme": "^5.0.0"
```

**Comment by ryanrombough** [comment]
I had this same issue. It was because I was still trying to import `action` from `@storybook/react`. It is now imported from `@storybook/addon-actions`. So I had to update:

```
import { storiesOf, action } from '@storybook/react';
```

to 

```
import { storiesOf } from '@storybook/react';
import { actions } from '@storybook/addon-actions';
```

in all of my `.stories.js` files

**Comment by VladimirHumeniuk** [comment]
@ryanrombough will try to do this, thanks in advance

**Comment by VladimirHumeniuk** [comment]
Tried everything from the scratch on 5.0.6, same errors::
![image](https://user-images.githubusercontent.com/20288162/55388792-2e99c300-5534-11e9-899f-d98eb4cdb1a8.png)

**Comment by shilman** [comment]
@VladimirHumeniuk Do you happen to have a reproduction I can look at?

**Comment by Lelith** [comment]
i also experience the same issue after trying to upgrade from 4 to 5 but i already use `@storybook/addon-actions` so  no solution for me 
![image](https://user-images.githubusercontent.com/1789174/55467889-7be46600-5602-11e9-83d6-a48c592f44e4.png)

**Comment by shilman** [comment]
@Lelith Try removing "addon-info"?

**Comment by Lelith** [comment]
@shilman its a quite big component library with many stories and all of them using this addon :/ so will stop migration for now but will update once i tried out eliminating this addon / other addons.

**Comment by ericsoco** [comment]
I also ran into this issue. Turned out it was due to the order of exports in my library -- one component was importing a `styled-components` theme from another module, and accessing it within a `styled.div`. However, the `theme` object was exporting after the component in my `index.js`. Rather than throw an NPE, I saw `Uncaught TypeError: Object(...) is not a function`.

**Comment by smykes** [comment]
The weird part for me is it runs fine locally, but throws this error when deployed too Netlify.

**Comment by wlblanchette** [comment]
I ran into this issue as well and it was related to importing from "@storybook/theming": "5.0.11"

**Comment by JDansercoer** [comment]
@smykes Try to check your repo for circular dependencies. I had the exact same problem as you, where running it locally worked as it should, where building (and deploying it) gave me this error.
After removing the circular dependency, it all worked again!

**Comment by divyeshjethwa** [comment]
If you're facing this problem with angular then in my case:

I solved it by importing moduleMetadata from '@storybook/angular' instead of '@storybook/angular/dist/client/preview/types'

**Comment by slawomir-marek** [comment]
@divyeshjethwa thanks! You're my savior!
