### ISSUE TITLE
Can't apply custom theme in official example

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#6321]
**To Reproduce**
In `examples/official/storybook/config.js`:

```
addParameters({
  ...
  options: {
    ...
    theme: create({
      base: 'light',
      appBg: 'orangered',
    }),
  },
  ...
}
```

`yarn start`, see no effect on UI theme. Reloading page, restarting storybook, and even `yarn bootstrap --reset` don't help

**Comment by shilman** [comment]
@ndelangen Why don't we have a custom theme in the official example? And was there not a pull request for this change?

**Comment by Hypnosphi** [comment]
Seems fixed with current alpha
