### ISSUE TITLE
How do I write multiple types in vue props 

### ISSUE THREAD

**Issue by ayiaq1** [storybooks/storybook#6330]
storiesOf('multiple', module)
  .addDecorator(withKnobs)
  .add('props', () => ({
    template: `
        <el-select v-model="selected">
            <el-option
            v-for="item in options"
            :key="item.value"
            :label="item.label"
            :value="item.value">
            </el-option>
        </el-select>
    `,
    props: {
      selected: {
        type: [String, Array]
        default: //  to do  ??
      }
    }
  }));

selected may be String OR Array ,so How to white  selected default ?

**Comment by shilman** [comment]
cc @backbone87

**Comment by backbone87** [comment]
single element array is treated the same way as a string by element-ui, so just use an array knob
https://github.com/storybooks/storybook/tree/master/addons/knobs#array

for support questions please use discord (see https://storybook.js.org/support/) or standard support networks like stackoverflow
