### ISSUE TITLE
Setting a custom document title in React

### ISSUE THREAD

**Issue by robbertolierook** [storybooks/storybook#6339]
I'm not able to set a custom title. Even the workaround in the `manager-view.html` file doesn't work anymore (well it works for about 0.5 second):

`<script>
   document.title = 'custom title';
</script>`

I'm guessing this has to do with the implementation of #866. Setting a custom title shouldn't be this hard, an addParameter option for it would be awesome.

This has been asked a lot, so sorry if I'm missing something, but I could only find outdated answers to this question.

**Comment by shilman** [comment]
@robbertolierook What version of Storybook?

**Comment by robbertolierook** [comment]
It's storybook 5.0.5

**Comment by spiltcoffee** [comment]
@robbertolierook: Here's a workaround I found for this for now
* Put this into your `manager-head.html` file:
```html
<script>
  var observer = new MutationObserver(function(mutations) {
    if (document.title.match(/Storybook$/)) {
      document.title = "custom title";
    }
  }).observe(document.querySelector("title"), {
    childList: true,
    subtree: true,
    characterData: true
  });
</script>
```

(MutationObservers have pretty good browser support, so this should work fairly well: https://caniuse.com/#search=mutationobserver)

**Comment by jmlivingston** [comment]
@spiltcoffee - Nice tip! For others, I had to add this before the "var observer...", since it was looking for changes. A shame there isn't a less hacky way to do this.

```document.title = "custom title";```

**Comment by jmlivingston** [comment]
After trying several solutions, I finally found a clean solution for this. I'm a bit surprised this isn't documented anywhere as this seems like a very common use case.

Create a file called TitleAddon.js with the following content:
```
import addons from '@storybook/addons'
import { STORY_RENDERED } from '@storybook/core-events'
import packageJson from '../package.json'

addons.register('TitleAddon', api => {
  api.on(STORY_RENDERED, story => {
    const storyData = api.getCurrentStoryData()
    document.title = `${storyData.name} - ${packageJson.name}`
  })
})
```

Add a reference addons.js
```
import './TitleAddon'
```

Note: I'm using my package.json name as a suffix in the title, but this can be changed to anything. You can also add the storyData.kind if you're looking for the parent name as well.

**Comment by claudio-moya** [comment]
Hi @shilman I'm using v5.1.9 and this feature is not working with the new `addParameters` function, actually there is no 'title' option listed in the docs as well.

https://storybook.js.org/docs/configurations/options-parameter/

I checked the previous releases and this feature should be fixed on v5.0.0-alpha.7  but it still broken (https://github.com/storybookjs/storybook/issues/866).

Can you checked again please?
Thanx in advance.

**Comment by herman-rogers** [comment]
This is broken in v5.2.1 still. I set the document title and it's immediately overwrittend with 'Storybook'. This should definitely be something easy to set and should have to require such a hack to get working.

**Comment by chvin** [comment]
'overwritten by Storybook' solution:

``` js
// .storybook/manager.js
import './titleAddon';
```

``` js
// .storybook/titleAddon.js
import addons from '@storybook/addons'
import { STORY_RENDERED } from '@storybook/core-events'

addons.register('TitleAddon', api => {
  const cunstomTitle = 'abc'; // Define your customTitle title
  let interval = null;
  const setTitle = () => {
    clearTimeout(interval);
    let storyData = null;
    try {
        storyData = api.getCurrentStoryData(); // Some time get error
    } catch(e) {}
    let title;
    if (!storyData) {
        title = cunstomTitle;
    } else {
        title = `${storyData.kind} - ${storyData.name} ⋅ ${cunstomTitle}`
    }
    if (document.title !== title) { // As few dom operations as possible
        document.title = title;
    }
    interval = setTimeout(setTitle, 100);
  };
  setTitle();
  api.on(STORY_RENDERED, story => {
    setTitle();
  })
});
```

**Comment by chadlavi-casebook** [comment]
Anyone have a solution for this that's compatible with storybook 6.x? The the suggestion by @chvin doesn't have any effect now.

**Comment by rwieruch** [comment]
I tried overriding the title in the manage-head.html, but then I end up with two title elements. Isn't there a option to define a custom title oneself?

**Comment by artursopelnik** [comment]
In Storybook 8, you need to use `storyData.title` instead of `storyData.kind` and manually add spaces around `/`.

The STORY_RENDERED event is only triggered for stories and not for documentation pages (MDX), which do it completely unnecessary. Additionally, the alternative setTimeout is render-blocking and therefore not an ideal option.

As a solution, I use MutationObserver to monitor changes to the <title> tag. Here is my implementation:

```ts
// .storybook/manager.js
import './titleAddon';
```
```ts
addons.register('TitleAddon', (api) => {
  const PAGE_TITLE = 'abc'

  const setTitle = () => {
    let storyData = null
    try {
      storyData = api.getCurrentStoryData()
    } catch (e) {}
    document.title =
      storyData !== null && storyData.title
        ? `${storyData.title.replace(/\//g, ' / ')} - ${storyData.name} ⋅ ${PAGE_TITLE}`
        : PAGE_TITLE
  }

  return new MutationObserver(() => {
    if (document.title.endsWith('Storybook')) {
      setTitle();
    }
  }).observe(document.querySelector('title'), {
    childList: true,
    subtree: true,
    characterData: true,
  });
})

```

**Comment by yashsway** [comment]
@artursopelnik  This works! Thank you
