### ISSUE TITLE
Resizing the browser to a small height breaks the UI permanently 

### ISSUE THREAD

**Issue by kroeder** [storybooks/storybook#6343]
**Describe the bug**
Resizing the browser to a small height so the addons-area toolbar moves behind the preview toolbar destroys the UI permanently. The only way I found to get rid of this is to remove the preview toolbar manually in the DOM and then resize the addons-area back to a normal state

**To Reproduce**
1. Go to https://storybooks-official.netlify.com/?path=/story/ui-panel--default
2. Resize your browser until the addons-area moves behind your preview-area
3. See the result

**Expected behavior**
The UI should fix itself after resizing back to a normal size

**Screenshots**

![](https://cdn.discordapp.com/attachments/489892645087215636/560796924656222209/storybook-ui-broken.gif)

**System:**
 - OS: Windows 10
 - Device: Desktop PC
 - Browser: Chrome 
 - Version: v5.0.0

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.40 containing PR #6696 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-beta.1 containing PR #6696 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
