### ISSUE TITLE
date knob returns a number, not a string

### ISSUE THREAD

**Issue by maciejmyslinski** [storybooks/storybook#6351]
**Describe the bug**
The documentation states:
> The date knob returns the selected date as **stringified** Unix timestamp

Yet, when I pass its value to react component, I see this warning in the console

> Failed prop type: Invalid prop `date` of type `number` supplied to `Component`, expected `string`.

**To Reproduce**
1. Create a react component that takes a string prop.
2. Use `prop-types` to ensure a string type
3. Use `date` knob like this:
```jsx
<Component date={date('date', new Date('09.02.2019'))} />
```

**Expected behavior**
I expect a value returned from `date` knob to be as documented: a string.

**System:**
 - `@storybook/react`: 5.0.3
 - `@storybook/addon-knobs`: 5.0.3

**Comment by Armanio** [comment]
Hmm, I think it's the error in docs: unixtime should be a number.
What you think about it? Maybe just fix docs?
