### ISSUE TITLE
Can't find addons

### ISSUE THREAD

**Issue by viridia** [storybooks/storybook#6356]
**Describe the bug**

I've gone through the basic instructions for setting up a Storybook app with TypeScript and React, and registered the "actions" addon as described. However, when I go the the page, the addons panel says "nothing found". I've tried this with several addons and I get the same result.

You can see a live demo of my site here: https://viridia.github.io/skyhook/storybook/index.html

My ```config.ts``` file looks like this:

```typescript
import { configure, addDecorator } from '@storybook/react';
import '@storybook/addon-actions/register';

// automatically import all files ending in *.stories.tsx
const req = require.context('../stories', true, /.stories.tsx$/);

function loadStories() {
  req.keys().forEach(req);
}

configure(loadStories, module);
```

**Expected behavior**
The addons panel should display the currently installed addons.

**System:**
 - OS: [Ubuntu 18]
 - Device: [Dell XPS]
 - Browser: [Chrome]
 - Framework: [React]
 - Addons: [actions]
 - Version: [e.g. 5.0.5]

**Additional context**

GitHub for the project is located here: https://github.com/viridia/skyhook

**Comment by rafael-anachoreta** [comment]
I'm having the exact same problem and it is driving me crazy 😵.

What is more - I actually do get some logging output on the console for the knobs plugin, and my components work correct, which makes me think this is more of a UI problem.

![image](https://user-images.githubusercontent.com/10238432/55655515-ba417700-57f4-11e9-8338-8575e2df2844.png)

**Comment by shilman** [comment]
@viridia This line should be moved to `.storybook/addons.js`:

```
import '@storybook/addon-actions/register';
```
