### ISSUE TITLE
Cryptic runtime error when used with NEXT.JS

### ISSUE THREAD

**Issue by majames** [storybooks/storybook#6358]
**Describe the bug**

A receive a runtime error and see the empty storybook state when attempting to use it with NEXT.JS. The `addItem` function in the vendor bundle is exceeding the call stack (some sort of inifinite loop?)

**To Reproduce**
1. Clone scaffold repo - https://github.com/majames/whatamidoing
2. `yarn` to install deps
3. `yarn storybook` to spin up storybook
4. Visit URL in browser and note the runtime error

**Expected behavior**

Storybook to work with no runtime errors

**Screenshots**

<img width="1792" alt="empty-state" src="https://user-images.githubusercontent.com/7553458/55296247-9aace780-53cb-11e9-8c56-bda0f8274b47.png">

**Code snippets**

```
vendors~main.a9a4ae66b574313b92ed.bundle.js:4212 RangeError: Maximum call stack size exceeded
    at Object.toString (<anonymous>)
    at addItem (vendors~main.a9a4ae66b574313b92ed.bundle.js:16295)
    at vendors~main.a9a4ae66b574313b92ed.bundle.js:16302
    at Array.forEach (<anonymous>)
    at addItem (vendors~main.a9a4ae66b574313b92ed.bundle.js:16301)
    at vendors~main.a9a4ae66b574313b92ed.bundle.js:16302
    at Array.forEach (<anonymous>)
    at addItem (vendors~main.a9a4ae66b574313b92ed.bundle.js:16301)
    at vendors~main.a9a4ae66b574313b92ed.bundle.js:16302
    at Array.forEach (<anonymous>)
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Addons: NA
 - Version: `5.0.5`

**Additional context**

For what it's worth I'm also using typescript and firebase (although from what i've seen they aren't related to the cause of the problem)

**Comment by shilman** [comment]
Dupe to https://github.com/storybooks/storybook/issues/6128

Your repo works when I change `<Card/>` to `Card` in your stories.

**Comment by majames** [comment]
Oh my bad 🤦‍♂️ ... thanks @shilman!

**Comment by shilman** [comment]
@majames No worries - we need a better fix on our side! I'm just glad it wasn't a new bug 😆
