### ISSUE TITLE
[Angular] Knobs do not update preview for class-specified components when changeDetectionStrategy is set to OnPush

### ISSUE THREAD

**Issue by MaximSagan** [storybooks/storybook#6359]
**Describe the bug**
When a component is class-specified, and that component has its change detection strategy set to OnPush (see "additional context" below), the user is unable to manipulate the component's inputs using the knobs add-on.

(I believe this issue is almost certainly due to angular/angular#14087, but I think there are ways we can work around it, such as manually triggering change detection when a knob is changed.)

_[Clarification: By 'class-specified', I mean that the component is specified in the story definition using `component: MyComponent` (referencing the component's class directly) rather than `template: <my-component></my-component>` (referencing the component in a template via its selector).]_

**To Reproduce**
1. Find any story for a class-specified component that uses knobs ([here's one in the examples in this repo](https://github.com/storybooks/storybook/blob/next/examples/angular-cli/src/stories/custom-pipes.stories.ts))
2. Goto its component definition ([here's the one referred to in the above example](https://github.com/storybooks/storybook/blob/next/examples/angular-cli/src/stories/moduleMetadata/name.component.ts))
3. In its @Component decorator, add the following the the component metadata object: `changeDetection: ChangeDetectionStrategy.OnPush`
4. Run or refresh Storybook
5. Try to manipulate the input for the above story, and notice that the component is unresponsive.

**Expected behavior**
I expect that the component should preview should be updated using knobs, even when the component's change detection strategy is set to OnPush.

**Additional context**
"OnPush" change detection one of two change detection strategies used in Angular (the other being ("Default"), ensuring that change detection is essentially only run when the inputs are changed, which can be a major benefit for performance. (Read more about it [here](https://netbasal.com/a-comprehensive-guide-to-angular-onpush-change-detection-strategy-5bac493074a4) if you're interested.)

**Comment by MaximSagan** [comment]
Solved by #6360

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.21 containing PR #6360 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
