### ISSUE TITLE
An error ocurred while installing dependencies

### ISSUE THREAD

**Issue by eugenio4** [storybooks/storybook#6362]
**Describe the bug**
The following error occurred when install Storybook for angular. 

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/plugin-proposal-unicode-property-regex@^7.4.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/preset-env'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eugenio/.npm/_logs/2019-04-01T08_39_51_357Z-debug.log

**To Reproduce**
npm install @storybook/angular --save-dev

**System:**
 - OS: MacOS
 - node: nodeJs 10.14.2

**Comment by shilman** [comment]
This looks like an NPM issue. Can you try again?

```
$ npm info @babel/plugin-proposal-unicode-property-regex

@babel/plugin-proposal-unicode-property-regex@7.4.0 | MIT | deps: 3 | versions: 36
...
```

**Comment by eugenio4** [comment]
Sorry, is a problem of my internal registry.

This issue can be closed.

Thanks
