### ISSUE TITLE
Error "Maximum call stack size exceeded" with circular objects in actions

### ISSUE THREAD

**Issue by tyler-johnson** [storybooks/storybook#6365]
**Describe the bug**
When an action is fired (using addon-action) that contains a circular object (ie an object that refers to itself), an error is logged which comes from the dependency `fast-deep-equal`. This results in the action never being logged.

Error in Chrome: `RangeError: Maximum call stack size exceeded`
Error in Firefox: `InternalError: "too much recursion"`

**To Reproduce**
Run the code snippet below.

**Expected behavior**
For this error to not happen and for the action to log with circular data.

**Screenshots**
N/A

**Code snippets**
```js
import React from "react";
import { storiesOf } from "@storybook/react";
import { action } from "@storybook/addon-actions";

const stories = storiesOf("CircularTest", module);

function TestComponent({ data, onClick, children }) {
  return <div
    onClick={(e) => {
      e.preventDefault();
      onClick(data);
    }}
  >
    {children}
  </div>;
}

const circularData = {};
circularData.data = circularData;

stories.add("Test", () => (
  <TestComponent data={circularData} onClick={action("onClick")}>
    Hello
  </TestComponent>
));
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2016
 - Browser: Chrome and Firefox
 - Framework: React
 - Addons: actions
 - Version: 5.0.5

**Additional context**
N/A

**Comment by Armanio** [comment]
Hi, Tyler!
Just update you SB to [5.0.6](https://github.com/storybooks/storybook/releases/tag/v5.0.6). It already fixed.
Let me know if your problem still remains.

**Comment by tyler-johnson** [comment]
Wow, I'm sorry for wasting your time. I saw the notification that a new version was available after I submitted this issue and I thought to myself, "oh maybe it was fixed". And what do you know it is.

Thank you!
