### ISSUE TITLE
v5.1.x change breaks Boolean knob

### ISSUE THREAD

**Issue by metasean** [storybooks/storybook#6366]
**Describe the bug**
[Changing `value` to `value: value || ''` in addons/knobs/src/components/PropForm.js](https://github.com/storybooks/storybook/commit/c1f8ec90d804be765a4450313136ff803fe4006e#diff-8ec888992c85289adbfe8de770998b3c) (introduced with bug fix #6043 😞 ) causes boolean knobs to return an empty string when toggled from `true`, which itself causes the error:
```
Warning: Failed prop type: Invalid prop `knob.value` of type `string` supplied to `BooleanType`, expected `boolean`.
```

**To Reproduce**
1. Go an existing project with a Boolean knob
2. in `node_modules/@storybook/addon-knobs/dist/components/PropForm.js` around line 76 change `value: value || ''` to just `value` (broken to fixed) or vice versa.
3. Restart the server (e.g. `yarn storybook`)
4. With console log open, toggle a boolean knob

**Expected behavior**
Toggling a boolean from `true` should not result in an error about an empty string.

**Screenshots**

## Bad === `value: value || ''`
![PropForm-Bad](https://user-images.githubusercontent.com/7552754/55357930-71ec2700-548b-11e9-805a-45606aa917e9.gif)

## Good === `value` === `value: value,`
![PropForm-Good](https://user-images.githubusercontent.com/7552754/55357941-77497180-548b-11e9-879a-19c43d4a02b9.gif)

**Code snippets**
```
  _createClass(PropForm, [{
    key: "makeChangeHandler",
    value: function makeChangeHandler(name, type) {
      var onFieldChange = this.props.onFieldChange;
      return function (value) {
        var change = {
          name: name,
          type: type,
          // value,            // <-- GOOD in v5.0.6
          value: value || '',  // <-- BROKEN in v5.1.x
        };
        onFieldChange(change);
      };
    }
  }, {
```
[i.e. the opposite of bugfix #6043](https://github.com/storybooks/storybook/commit/c1f8ec90d804be765a4450313136ff803fe4006e#diff-8ec888992c85289adbfe8de770998b3c)

**Additional context**
This boolean bug was introduced in a fix for changing a number value to an empty value (#6043).  Fixes should account for both scenarios.

**Comment by metasean** [comment]
Using the following instead addresses the _known situations_, however I haven't tested it against all knob types, and _ideally_ there will be tests in any pull request for this fix.

_possible fix_: `value: value === true ? false : value || '',`

**Comment by leoyli** [comment]
I think I can fix this when in the upcoming weekend :)

**Comment by leoyli** [comment]
Sorry for this easy bug I committed to fix lately, I get many things pile up unfortunately 😂...  I think this commit should logically fixing the bug since it allow `false` (and potentially `0`) to be correctly passed in.

**Comment by leoyli** [comment]
@metasean,

Hey, thank you for pointing me a good direction to fix the bug, although I did not take you suggested bugfix approach.  I would also encourage you to submit PR and invite people to review it next time :).

The fact is `value` could be `0`, `null`, `undefined`, `''`, `false`, `NAN` that triggers this bug, and I believe the intention was to ensure the value can be typed against `undefined`, the true intention need more investigation though.

The PR should be included in the next release, by then, feel free to file another issue if you have other concerns. 👍

**Comment by metasean** [comment]
@leoyli - No sweat from my end.  If my pile hadn't been so high (and remained so high) I would have submitted a PR instead of a just a bug report.  So at this point, **_I'm just happy you've submitted a fix!_**  Thank you! 🙇‍♂️

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-rc.0 containing PR #6830 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
