### ISSUE TITLE
When running storybook in static model - main page nested inside itself

### ISSUE THREAD

**Issue by jmcpeak** [storybooks/storybook#6386]
**Describe the bug**
When I just run storybook, it runs just fine:
start-storybook -s public -p 9009

When I build storybook as a static app:
build-storybook -s public
serve -s storybook-static -p 4000

I get no errors, it works - but each entry is nested inside itself. (See attached image.)

**To Reproduce**
(See above)

**Expected behavior**
build-storybook works the same as start-storybook

**Screenshots**
<img width="1589" alt="Screen Shot 2019-04-02 at 1 04 03 PM" src="https://user-images.githubusercontent.com/5578955/55422487-bfc76480-5549-11e9-9381-9bf007dc3316.png">

**Code snippets**
N/A

**System:**
 - OS: [e.g. iOS, Windows10, MacOS]
MacOS
 - Device: [e.g. iPhoneX, Macbook Pro 2018]
Macbook Pro 2018
 - Browser: [e.g. chrome, safari]
Chrome
 - Framework: [e.g. react, vue, angular]
CRA 2.1.8 - React, Material-UI 3.9.2
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0]
3.x, 4.x, 5.0.6

**Additional context**
Any ideas?

**Comment by jmcpeak** [comment]
I'm an idiot

**Comment by shilman** [comment]
Inception! What was the fix?

**Comment by jmcpeak** [comment]
For my npm script command to run the storybook server I had:

"storybook-serve": "serve -s storybook-static -p 4000"

The "-s" arg got accidentally copied over from the "-s" option to specify the public folder for "build-storybook -s public"

The "-s" option for serve is "Rewrite all not-found requests to `index.html`"

Hence the "inception"...

**Comment by shilman** [comment]
One of the cooler bugs I've seen 👌

**Comment by palerdot** [comment]
@shilman I'm getting this same bug for `vue` storybook.  It works fine in dev mode. But production build just mirrors iteself with no contents.

Any fix?

**Comment by shilman** [comment]
@palerdot This was a user bug AFAIK, not a problem with Storybook per se.

**Comment by palerdot** [comment]
@shilman Yes. `serve -s` is for some reason showing nested storybooks. Not an issue with storybook.
