### ISSUE TITLE
Viewport addon not working as expected

### ISSUE THREAD

**Issue by lhguerra** [storybooks/storybook#6392]
**Describe the bug**
After registering the addon it's icon shows up in the storybook window but the behavior is odd. Whenever I try to chose a viewport I end up with the same thing.

**To Reproduce**
1. Install the addon `yarn add -D @storybook/addon-viewport`
2. Register it in `addons.js`
```
import '@storybook/addon-viewport/register';
```
3. Create a story:
```
import React from 'react';
import { storiesOf } from '@storybook/react';

import ActionDialog from './index';

storiesOf('ActionDialog', module).add('default', () => (
  <ActionDialog>Dialog Content</ActionDialog>
));
```
4. Run storybook

**Expected behavior**
The viewport setting resizes the viewport as shown in the print in the Readme.

**Actual behavior**
With no breakpoints selected (this is correct)
![Screenshot from 2019-04-02 18-14-13](https://user-images.githubusercontent.com/4529663/55436896-e13d4600-5573-11e9-8d70-b37a6c331dc5.png)

With any breakpoint selected (in this case, iphone6)
![Screenshot from 2019-04-02 18-14-23](https://user-images.githubusercontent.com/4529663/55436912-eb5f4480-5573-11e9-9d34-b3cb686cbf27.png)

Notice that it changes the size of the viewport (see scrollbar on the right) but not to the expected size.

**System:**
 - OS: Ubuntu 16.04
 - Device: Desktop
 - Browser: chrome
 - Framework: react
 - Addons: breakpoint
 - Version: 5.0.6

**Comment by shilman** [comment]
Have you taken a look at our example? Does this work as expected on your machine/browser?

https://storybooks-official.netlify.com/?path=/story/ui-panel--default

**Comment by lhguerra** [comment]
Yes it does. I cloned the repo and will test the example to see if I find any difference between my setup and what the example does.

**Comment by CodeByAlex** [comment]
@shilman, I'm definitely seeing an issue similar to this in next. Example can be found here: https://next--storybooks-vue.netlify.com/?path=/story/welcome--welcome
![image](https://user-images.githubusercontent.com/29763590/55486291-0d9ba580-55fa-11e9-88ef-6edae749373c.png)

**Comment by shilman** [comment]
It looks like this is a problem in `next` but not `master`. Perhaps it was introduced in https://github.com/storybooks/storybook/pull/6045

@lucas-carl mind taking a look at this?

**Comment by lucas-carl** [comment]
@shilman I looked into the _next_ version right after my PR but can't seem to find any bugs.

**Comment by ioanlucut** [comment]
Having the same issue.

**Comment by callmephilip** [comment]
Seeing this issue with `@next`

**Comment by mick-feller** [comment]
Same here, broken on @next

**Comment by shilman** [comment]
@lucas-carl Indeed, I checked and the problem got introduced in `alpha.15`, probably by this PR: https://github.com/storybooks/storybook/pull/6126

@Armanio mind looking into this?

**Comment by Armanio** [comment]
I check it today. Give me a few hours. 👍

**Comment by Armanio** [comment]
Guys, I apologize: it's my mistake, I fixed zoom and broke background addon.
I create PR to fix my past mistakes. 🔝

**Comment by lhguerra** [comment]
Just tested and it is working just fine. Thank you guys :)

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.26 containing PR #6502 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
