### ISSUE TITLE
Ability to link from one (Markdown) note to another

### ISSUE THREAD

**Issue by gka** [storybooks/storybook#6394]
**Is your feature request related to a problem? Please describe.**
I am using the [notes addon](https://github.com/storybooks/storybook/tree/next/addons/notes) and I would like to be able to link from one note to another, without having to refresh the entire storybook.
 
**Describe the solution you'd like**
I think it would be nice if I could just use Markdown links, maybe with a special syntax like `[SomeStoryNotes](sb:notes/path/to/TheStory)`. Clicking the link should then change to the other story's notes, just as if I had clicked the link in the sidebar.

**Describe alternatives you've considered**
The alternative solution I am using at the moment is to use the `?path=/info/path--to--the-story` links, which is fine, but the experience of browsing around isn't great because the entire Storybook will reload everytime I use a `?path` link.

**Are you able to assist bring the feature to reality?**
No, sorry, I've never written a line of React code.

**Comment by shilman** [comment]
Docs will supercede Notes and will support cross-linking, coming in 5.2 though: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.35 containing PR #6398 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
