### ISSUE TITLE
PropsTable console warning after update to 5.0.6

### ISSUE THREAD

**Issue by andreeasimona** [storybooks/storybook#6396]
**Describe the bug**
After an update from storybook 4.0.7 to 5.0.6, an error appears in the console. I followed the migration instruction from [here](https://github.com/storybooks/storybook/blob/next/MIGRATION.md). Everything works well and the error does not seem to affect anything in the stories and the adds-on. 

**Screenshots**
<img width="593" alt="Screenshot 2019-04-03 at 10 21 44" src="https://user-images.githubusercontent.com/6817073/55465225-f5795580-55fc-11e9-8aad-b4d1be2eb119.png">

**Code snippets**
The dependency in package.json
![Screenshot 2019-04-03 at 10 34 16](https://user-images.githubusercontent.com/6817073/55465269-0aee7f80-55fd-11e9-9e56-51f06e283034.png)

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Framework: [react]
 - Version: [5.0.6]

**Comment by shilman** [comment]
I think this might be a `storybook-addon-react-docgen` issue. We also have a `PropTable` in `@storybook/addon-info`, but it doesn't look like you're using that.
