### ISSUE TITLE
Addons compilation configuration

### ISSUE THREAD

**Issue by JulienPradet** [storybooks/storybook#6399]
Hi! First of all, thanks for the awesome work you are doing y'all!

**Is your feature request related to a problem?**
I've stumbled into two issues while creating custom addons for our Storybook:
- There are several webpack aliases and a custom webpack resolver plugin in our webpack configuration but they are not applied to the custom addons
- Once my project is used as a npm dependency, JSX transformations are no longer applied to my custom addons. This is because we send source files and want those to be compiled by using custom `includes` in webpack's rules.

Although I managed to find workarounds, I think that it would be great if these use cases could be supported by Storybook.

**Describe the solution you'd like**
I didn't actually check how it works in Storybook, but my guess is that the custom webpack configurations applied to the stories are not applied to the addons. However, I'm not familiar at all with Storybook's codebase, so I don't know if that's wanted or if that would make sense.

**Describe alternatives you've considered**
If it's too risky to directly apply `webpack.config.js` transforms because it is meant to be used for stories only, it would be great to add a `webpack.storybook.config.js` or something that would make sense for the UI around stories.

**Are you able to assist bring the feature to reality?**
Yes. If one could point me to where the addons compilation is handled, I'd be happy to give a hand in fixing this issue. But since I'm not even sure that you'd like to support such use cases, I didn't dive into it just yet. :)

Sorry if it was already mentioned in an existing issue, but I didn't manage to find it :)

:wave:

**Comment by shilman** [comment]
Hi @JulienPradet, this is the issue you're looking for and there's a workaround described there:

https://github.com/storybooks/storybook/issues/4995

@ndelangen is working on a cleaner way of doing things for a future version of Storybook (5.2?) but in the meantime the workaround is fully supported.

Closing this as a dupe, please comment there if you have any problems getting things working 👍
