### ISSUE TITLE
Question - 'all' equivalent

### ISSUE THREAD

**Issue by jenko3000** [storybooks/storybook#6400]
I used the 'All' panel as a way to see and play around with all the states at once (it was my go-to view in fact) but it seems it's been removed or replaced. 

AFAIK knobs can only be in one group at a time, so how can I access more than one knob group at the same time now?

**Comment by shilman** [comment]
There was a panel called "all" that showed the ungrouped knobs, so I changed the name to "other" to reflect that. Did it used to show all the knobs in an older version of Storybook?

**Comment by jenko3000** [comment]
> There was a panel called "all" that showed the ungrouped knobs, so I changed the name to "other" to reflect that. Did it used to show all the knobs in an older version of Storybook?

Yes, it did. All of them (both ungrouped and grouped) together...

**Comment by shilman** [comment]
I see. In that case, perhaps I merely covered over a 5.0 bug. 😢 

I'm open to PRs to restore the "all" tab in 5.1

**Comment by jenko3000** [comment]
> I see. In that case, perhaps I merely covered over a 5.0 bug. 
> 
> I'm open to PRs to restore the "all" tab in 5.1

As it was called 'All' and it showed all, it's definitely one of those feature not a bug cases ;-)
