### ISSUE TITLE
URL - in v5 old url structure is not working

### ISSUE THREAD

**Issue by mortal94** [storybooks/storybook#6402]
**Describe the bug**
When using the old URL structure of storybook v4 in storybook v5 it'll select the story in the sidebar (stories tree) and also will change the url to the new structure of v5, but the story view will not show the selected story and will show an error of "No preview".

**To Reproduce**
1. Go to the link below (offical storybook site with old structured URL) 
https://storybooks-official.netlify.com/?selectedKind=addons-knobs-withknobs&selectedStory=tweaks-static-values
2. See that the story is selected and also the URL have changed to the new URL structure but the story view shows "No preview" error.
3. Refresh the page and it'll load the page with the new url (because it was replaced) and the story view will load.

**Expected behavior**
For now as the documentation and code reference that the old URL structure is still being supported, so the expected behavior is that the story view will also load the selected story according to the old structure URL.

**Screenshots**
![Screen Shot 2019-04-03 at 17 09 49](https://user-images.githubusercontent.com/17675995/55486676-69cfeb00-5635-11e9-90ef-6c6466275c09.png)

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react - but any framework?
 - Version: 5.0.x and 5.1.x

**Comment by shilman** [comment]
Sorry for the delay @mortal94 somehow this didn't show up in my notifications.

Closing as a dupe to https://github.com/storybooks/storybook/issues/6075
