### ISSUE TITLE
Addon Actions should be able to use options: depth

### ISSUE THREAD

**Issue by snowystinger** [storybooks/storybook#6409]
**Describe the bug**
When using `action('click')` and passing an actual event object through, the JSON stringify takes about 200ms. `action` claims to take an object that includes `depth` that should limit how far down the object is stringified. Instead, it is always ignored and 15 is used. This is making our storybook representations of our components appear very sluggish.
https://www.npmjs.com/package/@storybook/addon-actions?activeTab=readme#available-options

**To Reproduce**
1. Edit cra-kitchensink button story to use `action('click', {depth: 1})`
1. Go to cra-kitchensink button story
1. Open chrome profiler and begin recording
1. Click on the button in the story
1. Stop recording
1. Narrow down window to the click event handling
1. See that at the bottomish of call stack, stringify is taking ~200ms
1. Also note that the entire event object has been logged to the action addon

**Expected behavior**
The event object logged to the action addon should only have a top level set of attributes. It also shouldn't take that long to stringify, it shouldn't even be noticeable.

**Screenshots**

**Code snippets**
To make it more obvious, just pile up a couple actions:
```
.add('with text', () => (
    <Button onClick={(event) => {
      action('clicked', {depth: 1})(event);
      action('clicked2', {depth: 1})(event);
    }}>
      Hello Button
    </Button>
  ), {
    options: { selectedPanel: 'storybook/actions/panel' },
  })
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Addons: actions
 - Version: 5.1.0-alpha20

**Comment by shilman** [comment]
Released in https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.22

**Comment by snowystinger** [comment]
wow, that was fast, thanks!
