### ISSUE TITLE
Progressively Slowed Builds with react-docgen-typescript

### ISSUE THREAD

**Issue by clintandrewhall** [storybooks/storybook#6430]
**Describe the bug**

The [documentation](https://storybook.js.org/docs/configurations/typescript-config/#using-typescript-with-the-tsdocgen-addon) for Typescript offers TSDocgen as an option for parsing and providing `props` tables for stories.  In my recent experience, and as noted in an [recent issue](https://github.com/styleguidist/react-docgen-typescript/issues/112) in `react-docgen-typescript`, each `tsx` story is individually parsed and visibly pauses the Storybook build.  With each TS story that is added, the build gets slower and slower.  With only 10 stories, our build time is ~1.5 minutes... HMR is also impaired.

**To Reproduce**

1. Enable `react-docgen-typescript-loader` for `.tsx?` files, as recommended.
2. Enable the `TSDocgenPlugin`, as recommended.
3. Have a repo with 10+ stories.
4. See slow build time.

![Screen Shot 2019-04-04 at 8 25 44 PM](https://user-images.githubusercontent.com/297604/55598345-d7ecde80-5717-11e9-9a21-b48c92de7cc2.png)

Commenting out both [1](https://github.com/elastic/kibana/blob/master/x-pack/plugins/canvas/.storybook/webpack.config.js#L60) and [2](https://github.com/elastic/kibana/blob/master/x-pack/plugins/canvas/.storybook/webpack.config.js#L65) in our setup results in ~4s builds:

![Screen Shot 2019-04-04 at 8 33 41 PM](https://user-images.githubusercontent.com/297604/55598562-f56e7800-5718-11e9-843b-d24b39e5fe50.png)

**Screenshots**

![Apr-04-2019 20-24-22](https://user-images.githubusercontent.com/297604/55598337-cc011c80-5717-11e9-82ad-0feb9cce1739.gif)
**Code snippets**

You can view our current Storybook config [here](https://github.com/elastic/kibana/tree/master/x-pack/plugins/canvas/.storybook) on Github.  I'm currently working on a PR to reduce our payload sizes with a DLL, so this config will change in the coming days/

**System:**
 - OS: MacOS
 - Device: Macbook Pro 13", latest
 - Browser: Chrome
 - Framework: React
 - Version: 5.0.5

**Additional context**
I've been discussing this in the Discord channel, under support.  It was suggested I log this bug.

**Comment by strothj** [comment]
The documentation needs to be updated to reflect that `react-docgen-typescript-webpack-plugin` should be replaced with [react-docgen-typescript-loader](https://github.com/strothj/react-docgen-typescript-loader). The Webpack plugin was the initial implementation which was later replaced with a loader.

https://github.com/strothj/react-docgen-typescript-loader/pull/40 was just merged in and published as `v3.1.0` which should improve the performance. We were creating a TypeScript program instance for each parsed file. The pull request changes this to reuse the same instance.

Can you report what performance you're getting with only the loader installed and with the new version?

**Comment by clintandrewhall** [comment]
@strothj Absolutely.  I'll test it and get back to you...!

**Comment by clintandrewhall** [comment]
@strothj BRAVO!  Those two changes-- removing the plugin and updating the package-- dropped build time to ~9s.

![Screen Shot 2019-04-05 at 8 40 56 AM](https://user-images.githubusercontent.com/297604/55631861-9e9b8980-577e-11e9-9875-91aaa1e80192.png)

@shilman I would recommend updating the documentation for `5.0.5`+, depending of course on your own tests.

**Comment by shilman** [comment]
@clintandrewhall Mind submitting a small PR for that?

**Comment by strothj** [comment]
Credit where it's due. @denieler submitted the pull request which fixed that. :)
