### ISSUE TITLE
npx -p @storybook/cli sb init --type react_native fails

### ISSUE THREAD

**Issue by majirosstefan** [storybooks/storybook#6478]
**Describe the bug**
npx -p @storybook/cli sb init --type react_native results in npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/react-native@^5.0.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'indie_proto'
npm ERR! notarget 

**To Reproduce**
npx -p @storybook/cli sb init --type react_native

**Expected behavior**
not failing

**Comment by shilman** [comment]
Dupe to https://github.com/storybooks/storybook/issues/5893
