### ISSUE TITLE
Integration between addon-info and addon-viewport

### ISSUE THREAD

**Issue by CPedrini** [storybooks/storybook#6485]
**Describe the bug**
If you switch the viewport and then open the info then the information is displayed in the modified viewport.

**To Reproduce**
1. Create a new storybook with both viewport and  info addons.
2. Create a new story for a component.
3. Switch viewport and see the error.

**Expected behavior**
Ideally it should reset the viewport or use a new panel (like addon-notes does).

**Screenshots**
How it looks like:

![Screenshot_1](https://user-images.githubusercontent.com/9299430/55915130-41a93480-5bbf-11e9-8438-b0ecb24f7f2c.png)
![Screenshot_2](https://user-images.githubusercontent.com/9299430/55915126-41109e00-5bbf-11e9-9005-db4d6d4d8625.png)

How I think that it should reset to:

![Screenshot_3](https://user-images.githubusercontent.com/9299430/55915129-41a93480-5bbf-11e9-9a42-62a222d324e0.png)

**Comment by shilman** [comment]
Closing this as a dupe to https://github.com/storybooks/storybook/issues/1147

This issue has been around for a long time but it's finally being worked on. More here very soon.
