### ISSUE TITLE
vulnerability in @storybook/addon-info > marksy > marked

### ISSUE THREAD

**Issue by mhauens** [storybooks/storybook#6488]
npm audit security report                   
===================================================
Moderate:  Regular Expression Denial of Service                   
Package:  marked
Patched in:  >=0.6.2 
Dependency of: @storybook/addon-info [dev]
Path: @storybook/addon-info > marksy > marked
More info:  https://npmjs.com/advisories/812 

found 1 moderate severity vulnerability in 1002488 scanned packages
  1 vulnerability requires manual review. See the full report for details.

In version @storybook/addon-info -> 5.0.6

**Comment by fabb** [comment]
It was fixed in `@storybook@5.1.0-alpha.36`: https://github.com/storybooks/storybook/commit/d739347ee9f10e6679a0ccbf399a4dd72ba6cf96

**Comment by kunalnagar** [comment]
@fabb ran `npm audit fix` to fix the `@storybook/addon-info` vulnerability and it broke the `build-storybook` command. Here is some more info you might need, any help would be appreciated!

```
// package.json dependencies

"@storybook/addon-actions": "^5.0.11",
"@storybook/addon-info": "^5.1.3",
"@storybook/addon-links": "^5.0.11",
"@storybook/addons": "^5.0.11",
"@storybook/react": "^5.0.11",
```

<details>
  <summary>Logs</summary>

```
=> npm run build-storybook

> react-base-components@1.0.0 build-storybook /Users/kunalnagar/Documents/Code/react-twitter
> build-storybook -c .storybook -o docs

info @storybook/react v5.0.11
info
info clean outputDir..
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Loading custom addons config.
info => Compiling manager..
info => manager built (13 s)
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets:
WARN   vendors~main.3474211a6f58bf285ffa.bundle.js (1.23 MiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (1.23 MiB)
WARN       runtime~main.6ac4c33d73ae9704bbb9.bundle.js
WARN       vendors~main.3474211a6f58bf285ffa.bundle.js
WARN       main.2368a53986c1c4fab009.bundle.js
WARN
WARN webpack performance recommendations:
WARN You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
WARN For more info visit https://webpack.js.org/guides/code-splitting/
info => Building preview..
info => Loading preview config..
info => Loading presets
info => Using default webpack setup.
info => Using base config because react-scripts is not installed.
info => Compiling preview..
 70% building 93/100 modules 7 active ...e_modules/core-js/modules/_set-proto.jsERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve 'core-js/modules/es.object.assign' in '/Users/kunalnagar/Documents/Code/react-twitter/node_modules/@storybook/addon-info/dist'
(node:85078) UnhandledPromiseRejectionWarning: ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/modules/es.object.assign' in '/Users/kunalnagar/Documents/Code/react-twitter/node_modules/@storybook/addon-info/dist'
    at factory.create (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/kunalnagar/Documents/Code/react-twitter/node_modules/neo-async/async.js:2825:7
    at /Users/kunalnagar/Documents/Code/react-twitter/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/kunalnagar/Documents/Code/react-twitter/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
(node:85078) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:85078) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 70% building 628/628 modules 0 activenpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-base-components@1.0.0 build-storybook: `build-storybook -c .storybook -o docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-base-components@1.0.0 build-storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalnagar/.npm/_logs/2019-06-08T15_03_15_762Z-debug.log
```
</details>

**Comment by stearruda** [comment]
I have the same question regarding that. If you upgrade only the `@storybook/addon-info` and not the entire storybook is it gonna break? This was one of main reasons I didn't do it since I read problems on building.
I'm currently using the `5.0.11` version.
Did you find any solution @kunalnagar ?

**Comment by shilman** [comment]
@stearruda Generally you should be using the same version of `@storybook/*` if you can. In practice you can probably use 5.0.x and 5.1.x packages together since they are the same major semver version. But we don't officially support that and if you can possibly upgrade all your `@storybook/*` packages together, I'd highly recommend it.

**Comment by kunalnagar** [comment]
@stearruda nope, still stuck. Looks like I'll have to give @shilman's solution a shot where we need to update all the packages together.

**Comment by stearruda** [comment]
Tks @shilman and @kunalnagar for the replies!
I've updated the same packages as @kunalnagar (plus the `@storybook/addon-knobs`) to `5.1.9` and it worked like a charm!

**Comment by eacarras** [comment]
I still have audit problem using`5.1.11`version

**Comment by bgarrett-rt** [comment]
I'm still seeing this issue with all storybook packages at ^5.2.1

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s been released in Storybook 5.2, and doesn't have this problem. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by splomax** [comment]
> FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s been released in Storybook 5.2, and doesn't have this problem. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@shilman Is there a way in the new `addon-docs` to customize what actually shows up in the DocsPage?  Something I really like about `addon-info` is that I can write a markdown file for custom documentation but `addon-docs` seems to be a one-size-fits all as far as I can tell, unless there's some other documentation I'm missing.

I realize `addon-docs` supports MDX but I'm talking about configuring exactly _which_ stories show up in the DocsPage, what source code to show, etc.  Thanks!

**Comment by shilman** [comment]
@splomax there's a lot of documentation linked off of here: https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md

For example, to disable stories in docs (in 5.3 only): https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#docspage

Docs is actually more configurable than `addon-info` AFAIK. It contains a set of "slots" that can be completely overridden as needed, with sensible defaults. Needs more documentation, but here's what we have so far: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#docspage-slots

**Comment by splomax** [comment]
@shilman That looks super promising, thank you!  Not sure how I missed the stuff about configuring slots but I'm super grateful you shared it with me.  Playing with it now :)

**Comment by splomax** [comment]
@shilman I realize this is out of scope for this topic but I've been trying to figure out how to override each of those slots.  For example:

> The value for each slot is computed from a SlotContext context, and the function that's used to compute the value can be overridden if you need to customize the page.

I understand that the SlotContext interface has properties for the different slots, but it's not entirely clear to me where I'm supposed to be overriding it.  I'm currently using CSF for my story definitions, if that makes a difference.  Thank you for any help!

**Comment by shilman** [comment]
@splomax here's a simple example if that helps?

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/config.js#L64

I'll see if I can spend some time documenting it better later this week

**Comment by mramadhanr** [comment]
Still having this problem in 5.2.4 ^

here's my package.json

```
{
  "name": "content_editor",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^4.5.1",
    "@material-ui/styles": "^4.5.0",
    "@mdx-js/loader": "^1.5.1",
    "@storybook/addon-actions": "^5.2.4",
    "@storybook/addon-docs": "^5.2.4",
    "@storybook/addon-info": "^5.2.4",
    "@storybook/addon-links": "^5.2.4",
    "@storybook/addons": "^5.2.4",
    "@storybook/react": "^5.2.4",
    "@zeit/next-css": "^1.0.1",
    "antd": "^3.24.2",
    "css-loader": "^3.2.0",
    "dotenv": "^8.1.0",
    "marked": "^0.7.0",
    "next": "^9.1.1",
    "next-compose-plugins": "^2.2.0",
    "next-fonts": "^0.17.0",
    "next-images": "^1.1.2",
    "next-progressbar": "^1.0.0",
    "path": "^0.12.7",
    "prop-types": "^15.7.2",
    "rc-tree": "^2.1.3",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-icons": "^3.7.0",
    "react-scripts": "3.2.0",
    "styled-components": "^4.4.0",
    "webpack": "^4.41.0"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "lint": "eslint --ext .jsx --ext .js src/ pages/",
    "storybook": "start-storybook  -s ./ -p 6006",
    "build-storybook": "build-storybook"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "babel-loader": "^8.0.6",
    "eslint": "^6.1.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.4.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
    "eslint-plugin-sonarjs": "^0.4.0",
    "prettier": "^1.18.2"
  }
}
```

Thanks in advance
