### ISSUE TITLE
React Native - Stories aren't displaying in browser (5.1.0-alpha.24)

### ISSUE THREAD

**Issue by NemanjaManot** [storybooks/storybook#6489]
**Describe the bug**
My stories don't appear in browser. 
On (android) simulator i can see the stories, but action logger doesn't work.

**Expected behavior**
To see my stories / action loggers on Web Browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/18553180/55963794-c81f4e00-5c73-11e9-843f-d9d7808aa479.png)
![image](https://user-images.githubusercontent.com/18553180/55963853-dcfbe180-5c73-11e9-8029-51aab60a2222.png)

**package.json**
![image](https://user-images.githubusercontent.com/18553180/55964039-3bc15b00-5c74-11e9-98bb-76d18fb9e1fc.png)

**Code snippets**
Storie:

```
storiesOf('Button', module)
    .add('default', () => (
        <Button onPress={ action('tapped-default') }>Press Me</Button>
    ))


```
**System:**
 - Ubuntu 18.04.2. LTS
 - Device: Android simulator
 - Browser: Chrome
 - Framework: react-native
- react-native init
- npm version: 6.4.1

**Comment by shilman** [comment]
Did you run `adb reverse tcp:7007 tcp:7007`? Sometimes this is necessary to get android devices to talk to the server

https://github.com/storybooks/storybook/issues/6469

**Comment by NemanjaManot** [comment]
> Did you run `adb reverse tcp:7007 tcp:7007`? Sometimes this is necessary to get android devices to talk to the server
> 
> #6469

Yes, but nothing is changed..
