### ISSUE TITLE
Error around workaround

### ISSUE THREAD

**Issue by BinaryCry** [storybooks/storybook#6498]
I wanna use Storybook with my project but components in there predominantly was making with Lit-Element.
Regarding a workaround described [here](https://github.com/storybooks/storybook/issues/4958#issue-389191229) I got an error after I created webpack.config.js in .storybook dir and put there next config:
```
module.exports = (baseConfig, env, config) => {
  config.module.rules[0].exclude = /node_modules\/(?!(@webcomponents\/shadycss|lit-html|@polymer|@vaadin|@lit)\/).*/;
  return config;
};
```
**### ERR! TypeError: Cannot read property 'module' of undefined**

**Comment by shilman** [comment]
What version of storybook? That's a 4.x config and if you're using 5.x you need to migrate it:

https://github.com/storybooks/storybook/blob/next/MIGRATION.md#from-version-41x-to-50x

**Comment by BinaryCry** [comment]
Oh, you are right!
Now it works. Thank you so much :)
