### ISSUE TITLE
[Security] Vulnerability in `marked` (addon-info)

### ISSUE THREAD

**Issue by aralroca** [storybooks/storybook#6501]
See: https://nodesecurity.io/advisories/812  

![image](https://user-images.githubusercontent.com/13313058/56053416-51a64d00-5d54-11e9-9740-755848b2fcfd.png)

**Comment by joeycozza** [comment]
Duplicate of https://github.com/storybooks/storybook/issues/6488

**Comment by shilman** [comment]
Closing as dupe!
