### ISSUE TITLE
react native setup fails to load after 5.1.0-alpha.25 (24 works)

### ISSUE THREAD

**Issue by bitfrost** [storybooks/storybook#6512]
**Describe the bug**
My react native setup fails to load after 5.1.0-alpha.25 (24 works) with following error:
undefined is not an object (evaluating '_global.document.location')
This is happening on device via metro:
getQueryParams
    queryparams.js:19:47
<unknown>
    KnobManager.js:72:39
loadModuleImplementation
    require.js:331:6
<unknown>
    registerKnobs.js:19:49
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:66:28
loadModuleImplementation
    require.js:331:6
<unknown>
    panel.js:46:25
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:14:43
loadModuleImplementation
    require.js:331:6
<unknown>
    register.js:1:7
loadModuleImplementation
    require.js:331:6
<unknown>
    rn-addons.js:1
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:4
loadModuleImplementation
    require.js:331:6
<unknown>
    <unknown file>:0
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code
    <unknown file>:0

**To Reproduce**
import { withKnobs } from '@storybook/addon-knobs';
import { addDecorator } from '@storybook/react-native';
addDecorator(withKnobs);

**Expected behavior**
App loads

**Screenshots**
<img width="364" alt="iPhone_X_—_12_2" src="https://user-images.githubusercontent.com/290755/56100067-c9a27d80-5ee2-11e9-859d-4b47d2ad88a0.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS :MacOS
 - Device: andriod, ios
 - Framework: react-native
 - Addons: knobs +  ondevice-knobs
 - Version: 5.1.0-alpha.25 +

**Additional context**

**Comment by benoitdion** [comment]
@ndelangen https://github.com/storybooks/storybook/commit/3870bd1707d1f391c0ae31772a8d3df24b27b00c looks like this might be related. I can take a look unless you think you have more context on this one.

**Comment by benoitdion** [comment]
fixed with 59fa00cf78ddd4d0d2c37fbde3a4b6ebb185148e and 632eabd37cf5dff236ae7c4df38dea3f845fa023

**Comment by bitfrost** [comment]
The above error is cleared after the above, now getting 
TypeError: Cannot read property 'storyFn' of null

This error is located at:
    in StoryView (created by StorybookRoot)
    in StorybookRoot (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

StoryView._this.renderListening
    index.js:94:32
StoryView.render
    index.js:147:20
finishClassComponent
    ReactNativeRenderer-dev.js:11581:30
updateClassComponent
    ReactNativeRenderer-dev.js:11508:23
beginWork
    ReactNativeRenderer-dev.js:12874:13
performUnitOfWork
    ReactNativeRenderer-dev.js:17276:11
workLoop
    ReactNativeRenderer-dev.js:17316:23
renderRoot
    ReactNativeRenderer-dev.js:17417:6
performWorkOnRoot
    ReactNativeRenderer-dev.js:18423:6
performWork
    ReactNativeRenderer-dev.js:18324:6
This project works in the .24 release.

**Comment by bitfrost** [comment]
It is connecting and initializing the web ui..

**Comment by bitfrost** [comment]
works when   onDeviceUI: true.

Getting the above   onDeviceUI: false.  I will create a new issue.

**Comment by shilman** [comment]
@bitfrost did you try the latest alpha that contains @benoitdion 's fixes?
