### ISSUE TITLE
Can't Get Storybook to work for components with external dependencies. 

### ISSUE THREAD

**Issue by deepaksslibra** [storybooks/storybook#6516]
Hello guys, 

Sorry this is my first issue raised ever hence I don't know the proper way to do it. 

The problem i'm facing is with this repo :-

https://github.com/deepaksslibra/ever

I'm trying to setup storybook in that and it works for components which don't have external dependencies.

It works for SwitcherComponent but not for ModalsComponent for example. 

Sorry, I have no experience customizing the webpack config. 

I get this error:-

![image](https://user-images.githubusercontent.com/20175578/56384090-27173100-6239-11e9-9b53-6b8aeb416688.png)

**Steps to Reproduce :-** 

1.  git clone   -c core.symlinks=true --recursive https://github.com/deepaksslibra/ever.git
2.  git checkout develop
3.  yarn bootstrap
4.   cd admin/website-angular
5.  yarn storybook

**Comment by deepaksslibra** [comment]
The code is in the 'develop' branch of the repository.

**Comment by deepaksslibra** [comment]
@igor-dv @shilman Guys any update please ? Sorry for being nosey but I'm in urgent need of help

**Comment by kroeder** [comment]
@deepaksslibra https://github.com/deepaksslibra/ever/blob/develop/admin/website-angular/src/tsconfig.app.json why do you include files from node_modules directly? 

in `.storybook/tsconfig.json` storybook uses `../src/tsconfig.app.json` - it might be misconfigured. You should not need any custom webpack config for your setup as far as I can see

I immediately got permission errors (locally) after using your checkout command and doing `git checkout develop` 🤔  

Can you create a fresh angular app + `sb init` and compare your configuration with the fresh installation?

**Comment by deepaksslibra** [comment]
> @deepaksslibra https://github.com/deepaksslibra/ever/blob/develop/admin/website-angular/src/tsconfig.app.json why do you include files from node_modules directly?
> 
> in `.storybook/tsconfig.json` storybook uses `../src/tsconfig.app.json` - it might be misconfigured. You should not need any custom webpack config for your setup as far as I can see
> 
> I immediately got permission errors (locally) after using your checkout command and doing `git checkout develop` 
> 
> Can you create a fresh angular app + `sb init` and compare your configuration with the fresh installation?

Hello @kroeder.. I can't understand why If I load storybook for SwitcherComponent for example, it works perfectly fine. 
I would also like to add that I haven't been working on this project from the start and have no idea why the tsconfig files are structured that way. I've been asked to implement Storybook into this existing codebase.

What is the most surprising factor for me is that the app itself runs without no issue i.e. if you do
yar run:admin the angular cli doesn't break or throw an error. It just runs. 

I don't know how to work around the config files and how do they import modules and stuff. That's why I'm asking for help.
