### ISSUE TITLE
onDeviceUI: false fails with 5.1.0.alpha.28  (React Native stopped working post alpha.24 until .28)

### ISSUE THREAD

**Issue by bitfrost** [storybooks/storybook#6545]
**Describe the bug**
onDeviceUI: false causing build issues RN > 5.1.0-alpha.24

**To Reproduce**
in a react native project set onDeviceUI:false in call to getStorybookUI

**Expected behavior**
on deviceUI:false works

**Screenshots**
![iPhone_X_—_12_2_and_index_js_—_falcon_and_react_native_setup_fails_to_load_after_5_1_0-alpha_25__24_works__·_Issue__6512_·_storybooks_storybook](https://user-images.githubusercontent.com/290755/56261358-ba6d2c80-60a8-11e9-9961-f09267401179.png)

**System:**
 - OS: [MacOS]
 - Device: [All]
 - Version: [5.1.0-alpha.28]

**Comment by benoitdion** [comment]
thanks for catching this @bitfrost. #6549 should fix the issue. Thank you for your patience as storybook react-native test coverage is still lagging behind the new features.

**Comment by bitfrost** [comment]
Thank you for the quick fixes!  I am happy to serve as canary until test coverage catches up.

**Comment by shilman** [comment]
@benoitdion if you use the `Issue: #xxx` format for the PRs from the template, issues like this will get closed when the PR is released with a comment to let people know to check out the release
