### ISSUE TITLE
Storyshots: how to use webpack-built assets

### ISSUE THREAD

**Issue by gswirrl** [storybooks/storybook#6592]
Storyshots errors if it depends on assets built by webpack.

Im not sure if this is a design/conceptual bug or just a mismatch between my expectations and real life 😄 

DESCRIPTION OF ISSUE

I have storybook set up with a simple custom webpack config that runs an imported css file through postcss.

ie in `.storybook/config.js`

```
import '../src/css/needs-postcss.css';
```

This works perfectly in storybook, but fails in jest presumably because the assets aren't going through webpack.

```
...
    SyntaxError: Invalid or unexpected token
| import '../src/css/needs-postcss.css';

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transfor
m/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptT
ransformer.js:513:25)

```

Is there a way to achieve this?

I know that i can mock the css file, but if i want to use image snapshots, that defeats the object of the exercise afaict. thanks.

**Comment by gswirrl** [comment]
ahhh. am stupid. mocking the css is fine because ignored by webpack for the running storybook. sorry!

**Comment by schrapel** [comment]
@gswirrl @shilman Is there a way to use postcss with storyshots? I am encountering the same issue. I am using Tailwindcss and need the classes to produce an accurate screenshot. I get the same error above
