### ISSUE TITLE
Having no default value for color knob breaks

### ISSUE THREAD

**Issue by binomialstew** [storybooks/storybook#6597]
**Describe the bug**
When there is no default value for a color knob, there is a fatal error of:
`TypeError: Cannot read property 'toUpperCase' of undefined`

Here is the source of this error:
https://github.com/storybooks/storybook/blob/c6d704225eec98c20a729242f14987852071ddb1/addons/knobs/src/components/types/Color.js#L94

**To Reproduce**
1. In a story, create a color knob with no default value:
```
.add('Overview', () => {
    const iconColor = color('Icon Color')
    return <Component iconColor={iconColor} />
  })
```
2. Navigate to this story

**Expected behavior**
The color knob should not require a default value. (This didn't break prior to be822727e10893d4853639b2e0bdb4abaef815f2)

This is important because some components may have a color prop that is only used when non-falsy.

**Possible Solution**
Check if `knob.value` exists before using `toUpperCase()`.

**Comment by binomialstew** [comment]
PR [here](https://github.com/storybooks/storybook/pull/6598)

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.34 containing PR #6598 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.11 containing PR #6598 that references this issue. Upgrade today to try it out!

**Comment by MarkAPhillips** [comment]
This works but in typescript I get an error that the type expected is a string - can the types be updated to make this arg optional?

**Comment by shilman** [comment]
@MarkAPhillips PRs welcome!
