### ISSUE TITLE
Add URL queries for controlling contexts in the SB full iFrame mode

### ISSUE THREAD

**Issue by leoyli** [storybooks/storybook#6602]
**Is your feature request related to a problem? Please describe.**
For snapshot testing and story sharing purposes, it would be nice to have the URL query parameters to determine which contextual environment should be applied in the SB full iFrame mode.

**Describe the solution you'd like**
The same approach done in `addon-contexts`.

**Describe alternatives you've considered**
N/A

**Are you able to assist bring the feature to reality?**
Yes, done.

**Additional context**
N/A

**Comment by leoyli** [comment]
Related to #6601.

**Comment by shilman** [comment]
Deployed in https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.34

@leoyli if the PR had referenced this issue on the first line, this comment would have been generated and issue would have been closed automagically 😉 I updated the comment just now, but it needs to be correct before I run the publish script

**Comment by leoyli** [comment]
Oh I see, sorry about that 😞
