### ISSUE TITLE
`@storybook/addon-a11y`'s `withA11y` slowing down the storybook that results in browser hanging

### ISSUE THREAD

**Issue by MansoorBashaBellary** [storybooks/storybook#6612]
**Describe the bug**
Usage of `withA11y` of `@storybook/addon-a11y` is slowing down the storybooks and resulting in browser hanging

**To Reproduce**
1. Clone the repository: https://github.com/MansoorBashaBellary/vue-cli-storybook
2. Do `yarn && yarn start` on the cloned repo
3. Click on the `Changelog` story of `Welcome` and observe that browser gets hung for sometime and slows down the storybooks

`Changelog` story has Changelog of across 1500 lines. And it is happening due to the inclusion of `withA11y` decorator in `config.js`.

On removing below 2 lines from `config.js` fixes the issue:

import { withA11y } from '@storybook/addon-a11y';
addDecorator(withA11y);

This issue was not happening in SB 4.0, it started happening in SB 5.0

**Expected behavior**
Browser should not get hung on using withA11y decorator

**Code snippets**
Reproduction URL attached above

**System:**
 - OS: All
 - Device: All
 - Browser: All
 - Framework: All
 - Addons: A11y
 - Version: 5.0.0

**Comment by MansoorBashaBellary** [comment]
@CodeByAlex  @jsomsanith @Armanio 

Could you please help me on this issue

**Comment by Hypnosphi** [comment]
Looks like it's even worse in `5.1.0-alpha`. I observe a lot of inperformant background activity on https://next--storybooks-official.netlify.com


![Kapture 2019-04-25 at 17 20 45](https://user-images.githubusercontent.com/6651625/56747720-c6c74880-677e-11e9-88e4-959ec1718fbb.gif)

**Comment by MansoorBashaBellary** [comment]
I feel this is due `addon-a11y`, because on removing `withA11y` decorator, storybooks are more performant and they are fast

**Comment by jsomsanith** [comment]
@MansoorBashaBellary I haven't tried your repo yet, but the description seems to match this issue : https://github.com/storybooks/storybook/issues/5973

I fixed it and scheduled for 5.1.
Can you try the 5.1 alpha.6+ please ?

**Comment by MansoorBashaBellary** [comment]
Thanks @jsomsanith. Using the above version specified fixes the issue. Closing this issue
