### ISSUE TITLE
Force rerender with storybook/html

### ISSUE THREAD

**Issue by hsablonniere** [storybooks/storybook#6623]
Hey wonderful team of storybook :smile:

I'm trying to force rerender my stories when a knob is changed with storybook/html but it does nothing when story is an HTML element.

I looked at the code, knob changes trigger a rerender so it should be OK but when the code execution arrives in `renderMain` if it sees `forceRender === true` it does nothing :cry:

I'm probably missing the point here but reading this, I expected a force render to clear `rootElement` and reattach the node. The opposite of what it does right know.

https://github.com/storybooks/storybook/blob/master/app/html/src/client/preview/render.js#L20-L25

* Can someone tell me more about this? @Atekon 
* Maybe I'm the only one expecting this since I use custom elements and a detach/reattach would trigger a rerender of my component.

**Comment by JohnMunsch** [comment]
I think I'm seeing the same thing when my object knob supplies new data to create a Redux model and assigns that to my LitElement component. I can see it go through the story, create a new model, create a new component, assign the model to the component, and then return the component. However, the rendered component shown in Storybook is still the previous one.

**Comment by Hypnosphi** [comment]
@igor-dv @Atekon looks like #4822 broke knobs for "HTML element" stories

**Comment by hsablonniere** [comment]
Thanks very much!!! :tada:
