### ISSUE TITLE
react-native storybook 5.1.0-alpha-34 missing /bin/storybook script

### ISSUE THREAD

**Issue by FrederickEngelhardt** [storybooks/storybook#6643]
**Describe the bug**
Use the following storybook addons
"@storybook/addon-knobs": "5.1.0-alpha.34",
 "@storybook/addon-ondevice-knobs": "5.1.0-alpha.34",
 "@storybook/react-native": "5.1.0-alpha.34",

Simply try and run storybook and you will get the error.
```
$ storybook start -p 7007 --h 127.0.0.1
/bin/sh: storybook: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
1. install
```
"@storybook/addon-knobs": "5.1.0-alpha.34",
 "@storybook/addon-ondevice-knobs": "5.1.0-alpha.34",
 "@storybook/react-native": "5.1.0-alpha.34",
```
2. Go into `node_modules/.bin/`
3. Notice that the storybook script is missing.

**Expected behavior**
Expected to be able to run the storybook server script `npm run storybook`

**Comment by nabati** [comment]
Also bumped into this issue.

**Comment by shilman** [comment]
Please read the migration instructions: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-native-server

We still need to get this information back into the main docs, but are busy getting the functionality wrapped up for 5.1.

**Comment by nabati** [comment]
Thanks, and awesome to have the info here at least. 💪

**Comment by benoitdion** [comment]
@nabati is this issue resolved?

**Comment by nabati** [comment]
Yes!
