### ISSUE TITLE
Dependencies added using sb init are not inserted alphabetically

### ISSUE THREAD

**Issue by ghengeveld** [storybooks/storybook#6651]
**Describe the bug**
When adding Storybook to an existing project using `npx -p @storybook/cli sb init` it installs a set of packages. These are appended to the list of devDependencies in package.json. The yarn and npm clients usually insert new dependencies in alphabetical order, so Storybook breaks that.

**To Reproduce**
Use `sb init` to setup a new Storybook in an existing project with dependencies. See https://github.com/ghengeveld/react-async/commit/0e80fcb3597fed44ae7cdf785ac9d031ef1f8dd6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 for example.

**Expected behavior**
I expect dependencies in package.json to always be ordered alphabetically.

**Comment by shilman** [comment]
I think this will be fixed by #6629

**Comment by shilman** [comment]
Closing. Please comment if this is still broken after #6629
