### ISSUE TITLE
"EDIT THIS PAGE" links not working

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/storybook#6657]
E.g. https://storybook.js.org/docs/guides/guide-html/ links to https://github.com/storybooks/storybook/blob/master/docs/src/pages/undefined/guide-html/index.md

**Comment by mickaelzhang** [comment]
@shilman I think this can be closed or do you guys wait until the doc's fix is deployed before closing an issue ?

**Comment by shilman** [comment]
Closing! Will finish deploy in a bit
