### ISSUE TITLE
Addon-contexts: Have no cancel option in UI if the context have no param

### ISSUE THREAD

**Issue by leoyli** [storybooks/storybook#6668]
**Describe the bug**
Have no cancel option in UI if the context have no param even `option.cancelable` set to `true`.

**To Reproduce**
As been described.

**Expected behavior**
N/A

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
N/A

**Additional context**
N/A

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.37 containing PR #6669 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.
