### ISSUE TITLE
Upgrade to @babel/preset-env 7.4.4 with core-js@3.x is breaking build

### ISSUE THREAD

**Issue by sPaCeMoNk3yIam** [storybooks/storybook#6671]
**Describe the bug**
With @babel/preset-env v7.4.3 and using `core-js` 3.x explicitly in babel config building storybook worked fine. After upgrading @babel/preset-env to the latest release (being 7.4.4) an error is shown when `core-js` modules are used.

**To Reproduce**
1. Create a babel config with `corejs: { version: 3, proposals: true }`
2. Use latest @babel/preset-env v7.4.4
3. build and start storybook
4. See errors like
`Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator' in ...`
`Module not found: Error: Can't resolve 'core-js/modules/es.array.concat' in ...`

**Expected behavior**
A storybook build should not fail with latest babel, when doing a bugfix version bump.

**System:**
 - OS: MacOS 10.14.4 (18E226)
 - Framework: react
 - Version: 5.0.11

**Additional context**
May be this is also related to https://github.com/storybooks/storybook/issues/6204 but the workaround is not working and wasn't needed with @babel/preset-env v7.4.3.

**Comment by Zyzle** [comment]
@sPaCeMoNk3yIam Have you been able to come up with a workaround for this issue? I've come up against what looks like the same problem but haven't been able to resolve it.

**Comment by csvan** [comment]
We currently work around this by adding a hard resolve (in Yarn) to core-js 2.6.5, but that is untenable in the long run. Would be great to see full support for core-js 3, which is also the path Babel is headed.

**Comment by shilman** [comment]
@csvan Have you tried `5.1.0-beta.0`? I believe it contains the full upgrade

**Comment by Zyzle** [comment]
@shilman @csvan  Can confirm upgrading to `5.1.0-beta.0` resolved the issue for us.

**Comment by shilman** [comment]
Awesome @Zyzle thanks for the confirmation. I'm going to close this issue, but can re-open if it's still a problem for people.

**Comment by mrmartineau** [comment]
Thanks @shilman, updating all my `@storybook` dependencies to `@5.1.0-beta.1` fixed the build issues for me.

**Comment by rpearce** [comment]
This is fixed for me, as well. Thanks!

**Comment by ndelangen** [comment]
Awesome!

**Comment by yairEO** [comment]
Sadly manually installing latest `npm i core-js -D` helped. Shame... 
It's not good to manually install a dependency or a 3rd-party library such as Storybook. it should properly manage such issues internally
