### ISSUE TITLE
Knob "select" does not work on nested story

### ISSUE THREAD

**Issue by oluckyman** [storybooks/storybook#6703]
**Describe the bug**
When I use `select` knob in a nested story:
```
storiesOf('Chart / series', module)
  .add('nested story', ...)
```
it throws an error in the console
![image](https://user-images.githubusercontent.com/642673/57015778-dd561f80-6c16-11e9-809e-2f7576f4d183.png)
if I go to root story first, reload the page and then go to the nested story. It does not throw the error, but the `select` knob does not work: when I change the selection, it does not update the component and returns the selection to the initial value in a half of a second or so.

**To Reproduce**
on Vue project:
```
storiesOf('Chart', module)
  .add('root story with select works', ...)
storiesOf('Chart / series', module)
  .add('nested story with select does not work', ...)
```
**Expected behavior**
Should work both on root and nested stories and do not throw `emit` error in the console

**Screenshots**
`this._channel` is undefined
![image](https://user-images.githubusercontent.com/642673/57015923-96b4f500-6c17-11e9-9273-027d3b87fa1f.png)

**System:**
 - OS: MacOs
 - Device: Macbook Pro 
 - Browser: chrome
 - Framework: vue
 - Addons: knobs
 - Version: 
"@storybook/addon-knobs": "^5.0.11",
"@storybook/vue": "^5.0.11

**Comment by shilman** [comment]
I'm not sure that's valid nesting. Does it work if you try `storiesOf('Chart/standard', ...).add(...)` and `storiesOf('Chart/series', ...).add(...)`?

**Comment by oluckyman** [comment]
Just tried this:
```
storiesOf('Chart / standard', ...).add('knob', ...)
storiesOf('Chart / series', ...).add('knob', ...)
```
It works for 'standard' section and does not work for 'series'.

---

And just before sending this comment I realized that the first section has `addDecorator` and all the rest don't 🤦‍♂️
```
storiesOf('Chart / standard', ...)
  .addDecorator(withKnobs)
```

Sorry! with `addDecorator` directive it all works as expected.
