### ISSUE TITLE
Can't resolve fs when running npm run storybook

### ISSUE THREAD

**Issue by npattarone** [storybooks/storybook#6711]
**Describe the bug**
Out of the blue, the command `npm run storybook` started to throw this error. Didn't change anything in between, besides changes of some stories of mine.

**Expected behavior**
Not throw errors of any kind and start the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/19308167/57146121-fdaee700-6d9a-11e9-9565-c0f65145d5da.png)

![image](https://user-images.githubusercontent.com/19308167/57146290-61391480-6d9b-11e9-95de-6e04949655c2.png)

**System:**
 - OS: Windows10
 - Device: ASUS
 - Browser: chrome
 - Framework: react
 - Version: "@storybook/react": "^5.0.10"

**Comment by npattarone** [comment]
Sorry, was a local mistake in other file

**Comment by Waseemrajashaik** [comment]
@npattarone what was the mistake you made ?

**Comment by jasonwr** [comment]
> Sorry, was a local mistake in other file

How did you resolve this?

**Comment by adelin-b** [comment]
The pain of finding the same resolved issue im facing but without the resolution 

For `fs `  !

**Comment by shilman** [comment]
Importing a node-specific library in your components or stories perhaps?

**Comment by vishal213** [comment]
The problem was entirely elsewhere. My IDE mistakenly added one of the import statements from some library and that caused the problem. Removed that and the actual error cropped up: was also using an undeclared variable in that file only.
