### ISSUE TITLE
v3 & v4 docs?

### ISSUE THREAD

**Issue by njradford** [storybooks/storybook#6715]
In the push for v5, were the docs for v3 and v4 deprecated? Do they exist somewhere or should we consider the docs for v5 to be a drop in replacement?

**Comment by shilman** [comment]
v4 https://release-4-1--storybooks.netlify.com/
v3 https://release-3-4--storybooks.netlify.com/

**Comment by njradford** [comment]
Thank you for the response

**Comment by peterp** [comment]
@shilman Just a heads up that the link to v4 docs are no longer working.

**Comment by shilman** [comment]
@peterp thanks for the heads up. we'll be doing a docs overhaul as soon as 6.0 is out the door and will fix the versioning issue as part of that. in the meantime, your best bet is to look at the repo:

- https://github.com/storybookjs/storybook/tree/release/3.4
- https://github.com/storybookjs/storybook/tree/release/4.x
