### ISSUE TITLE
Storybook with previous versions of react

### ISSUE THREAD

**Issue by yaoksankoo** [storybooks/storybook#673]
How can I use Storybook with, for example, React 13?

**Comment by ndelangen** [comment]
I am interested why not upgrade to React 15?

To answer your question: If you try to use an other version then what's in our package.json you'll get a PeerDependency not met.
I may still work, but likely it will not.

On our side; We can try allowing any react version, but I find this a bit dangerous. I would possibly require us to do more maintenance to support some odd old react versions.
