### ISSUE TITLE
Deep Linking: put path of component>story in the URL

### ISSUE THREAD

**Issue by dptoot** [storybooks/storybook#674]
Forgive me if I am missing the obvious.

I see that deep linking has been available since #6 but  I can't seem to find any documentation on how it is actually achieved.

I can see the generated query string but unless it is re-used in its entirety then the app just falls back to the first story.  I would have thought ```?selectedKind=Button``` would at least bring me to the Button section.

is there any way to currently achieve deep linking within react-storybook?

**Comment by marc-rutkowski** [comment]
@dptoot Maybe this is what you are looking for? https://github.com/storybooks/storybook-addon-links

**Comment by dptoot** [comment]
Thanks Marc, but what I am looking for is external links into react-storybook.  My hope would be that ```http://localhost:9001/?selectedKind=Button``` would bring me to the initial story of button component but in actuality it will render the first story of the first component in the list.

**Comment by marc-rutkowski** [comment]
Sorry, didn't understand your question correctly.

Seems you need to provide at least the `selectedStory` parameter along with `selectedKind` to have it to work.
Is it a problem for your use case?

If so maybe we can submit a PR for this?
I think [this test](https://github.com/storybooks/react-storybook/blob/c46a341556c61ac2e99bb70ccee951368b1d75f5/src/client/preview/story_store.js#L55) can be changed to return the first story of a kind if the `selectedStory` is missing or if the specified story is not found.

@arunoda any advice with this?

**Comment by dptoot** [comment]
@marc-rutkowski 

Thanks!  That actually does work for my use case as I have a standard naming convention for the initial story for each component story set.  I would posit that that can't be relied on for everyuser though. I lucked out.  Humbly, and without looking too much into the source code,  I would say the expectation would be that only selectedKind be required to link into the storybook and the default selectedStory would fall back back to the first story in the story array,  if not supplied.  I would be happy to help out on a PR if @arunoda thinks this is the direction he would like to take things.

**Comment by tmeasday** [comment]
This seems like a reasonable feature. See also https://github.com/storybooks/react-storybook/issues/614.

**Comment by tmeasday** [comment]
See linked PR (https://github.com/storybooks/storybook-ui/pull/78)

**Comment by tmeasday** [comment]
This is merged and will be released w/ version 3.0

**Comment by NicoleGrondinAlayacare** [comment]
This seems to have regressed with version 5.0.0. Are there any plans to fix this?

**Comment by shilman** [comment]
Thanks for the bug @NicoleGrondinAlayacare -- tracking it here: https://github.com/storybooks/storybook/issues/5925
