### ISSUE TITLE
Storybook Hub isn't properly building the project

### ISSUE THREAD

**Issue by colbycheeze** [storybooks/storybook#675]
![screen shot 2017-01-22 at 11 20 17 am](https://cloud.githubusercontent.com/assets/8884298/22184318/ddad62fa-e094-11e6-80f1-0c27973808e4.png)

When I run `build-storybook` locally and serve it with a simple static node server everything works perfect.

What would be causing storybook to not transpile the code? Do you guys not use the provided webpack config, or do you have a different .babelrc perhaps?

Here is my config: https://gist.github.com/0db7e8f78f08088cca5af87c1c629251
The command is from the docs `"build-storybook": "build-storybook -o ./.out",`

**Comment by shilman** [comment]
Sorry for the trouble. Storybook hub is not currently being maintained by the storybook community. We are currently figuring out next steps here and will follow up directly once we've figured something out. Please feel free to contact me directly, but I'll close this issue for now.
