### ISSUE TITLE
Clicking Shortcuts Button Opens Blank Screen

### ISSUE THREAD

**Issue by scottleblang** [storybooks/storybook#6756]
**Describe the bug**
When clicking the Storybook 3-dot shortcuts button in the left panel, rather than open a menu of options for Storybook, the page refreshes to a blank screen . This same behavior also occurs if I press the 'Change the size of the preview' button along the top header panel.

**Expected behavior**
A menu should open next to the Shortcuts button showing selectable options -see attached screenshot of expected behavior.

**Error Message**
Uncaught Error: Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation.
    at parseToRgb (vendors~main.270ffce4b0377143551d.bundle.js:8469)
    at parseToHsl (vendors~main.270ffce4b0377143551d.bundle.js:8550)
    at lighten (vendors~main.270ffce4b0377143551d.bundle.js:9085)
    at fn (vendors~main.270ffce4b0377143551d.bundle.js:8796)
    at vendors~main.270ffce4b0377143551d.bundle.js:132612
    at handleInterpolation (vendors~main.270ffce4b0377143551d.bundle.js:897)
    at serializeStyles (vendors~main.270ffce4b0377143551d.bundle.js:989)
    at vendors~main.270ffce4b0377143551d.bundle.js:1294
    at updateContextConsumer (vendors~main.270ffce4b0377143551d.bundle.js:26277)
    at beginWork (vendors~main.270ffce4b0377143551d.bundle.js:26465);
The above error occurred in the <Context.Consumer> component:
    in Styled(div) (created by Tooltip)
    in Tooltip (created by Tooltip)
    in Tooltip (created by InnerPopper)
    in InnerPopper (created by Context.Consumer)
    in Popper (created by TooltipTrigger)
    in Manager (created by TooltipTrigger)
    in TooltipTrigger (created by WithTooltipPure)
    in WithTooltipPure (created by lifecycle(WithTooltipPure))
    in lifecycle(WithTooltipPure)
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown (created by withState(Component))
    in withState(Component) (created by Context.Consumer)
    in Styled(withState(Component)) (created by Sidebar)
    in nav (created by Context.Consumer)
    in Styled(nav) (created by Sidebar)
    in Sidebar (created by Context.Consumer)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Nav)
    in Nav (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout) (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ResizeDetector
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root

**Screenshots**
![Screen Shot 2019-05-09 at 9 14 33 AM](https://user-images.githubusercontent.com/47985245/57469233-03914600-723b-11e9-9e9e-a3cee26376a7.png)

**System:**
 - OS: MacOS High Sierra - 10.13.6
 - Browser: All major browsers
 - Framework: React
 - Addons:  '@storybook/addon-knobs/register'; '@storybook/addon-links/register'; '@storybook/addon-viewport/register';
 - Version: 5.0.11

**Additional context**

**Comment by scottleblang** [comment]
Issue resolved as invalid entry in theme

**Comment by robbertolierook** [comment]
I have the same issue but I can't figure out what the invalid entry in my theme is. What should I pay attention to?

**Comment by scottleblang** [comment]
> I have the same issue but I can't figure out what the invalid entry in my theme is. What should I pay attention to?

I was passing in a color with the hash tag - i.e. #white. As you can imagine that broke it.

**Comment by robbertolierook** [comment]
hmm.. I don't. I think to me it might be either the gradient or using variables. Either way, I think my code should work:

```import { create } from '@storybook/theming';

const black = '#434343';
const blue = '#0063ba';
const grey = '#e6e6e6';
const white = '#ffffff';

export default create({
  base: 'light',

  colorPrimary: blue,
  colorSecondary: blue,

  // UI
  appBg: `linear-gradient(to bottom, ${grey}, ${white})`,
  appContentBg: white,
  appBorderColor: blue,
  appBorderRadius: 0,

  // Typography
  fontBase: '"Open Sans", sans-serif',
  fontCode: 'monospace',

  // Text colors
  textColor: black,
  textInverseColor: white,

  // Toolbar default and active colors
  barTextColor: white,
  barSelectedColor: white,
  barBg: blue,

  // Form colors
  inputBg: white,
  inputBorder: grey,
  inputTextColor: black,
  inputBorderRadius: 0,
```

**Comment by scottleblang** [comment]
Looks correct on the surface. Was it working at one point?

**Comment by robbertolierook** [comment]
Nope never had. Weird right?

**Comment by scottleblang** [comment]
What if you remove your custom theme and just use the default SB theme?

**Comment by robbertolierook** [comment]
Then it does work

**Comment by scottleblang** [comment]
So, it looks like it doesn't like something in your theme.

Is there an extra quote here before Open:
`fontBase: '"Open Sans", sans-serif',`

**Comment by robbertolierook** [comment]
That is supposed to be there. It turns out it was the gradient. Which is too bad because I liked the gradient background. I'm opening another issue
