### ISSUE TITLE
Webpack's DevServer not work as expected

### ISSUE THREAD

**Issue by oMaten** [storybooks/storybook#6773]
**Describe the bug**
I set the `webpack.config.js` as follow, but it's not work.
Then, I found here https://github.com/storybooks/storybook/blob/next/lib/core/src/server/dev-server.js#L109
It's wrong for assigning the `devServer` options to `webpack-dev-middleware`, cause the most of options only affect the behavior of `webpack-dev-server`.
Is it possible to support the webpack's `devServer` options?

```js
module.exports = async ({ config }) => {
  config.devServer = {
    before: app => {
       MyCustomMiddleware(app);
    }
  }
}
```

**To Reproduce**
1. Set Webpack's config 
```js
module.exports = async ({ config }) => {
  config.devServer = {
    before: app => {
       MyCustomMiddleware(app);
    }
  }
}
```
2. Run script "start-storybook"

**Expected behavior**
`devServer` options like `before ` & `after` work as expected

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2016]
 - Browser: [chrome]
 - Framework: [react]
 - Version: [5.0.0]

**Comment by oMaten** [comment]
I found `./storybook/middleware.js` could solve my problem. But it's not mentioned on document.

**Comment by shilman** [comment]
@oMaten In my opinion it's not an officially supported API. We've kept it around because it's a useful escape hatch for doing just about anything. We also don't have any plans to remove it, and if we did it would only be in a major version update. Does that help clarify?

**Comment by oMaten** [comment]
@shilman Sure, thanks for reply
