### ISSUE TITLE
Failed to use DllReferencePlugin

### ISSUE THREAD

**Issue by serut** [storybooks/storybook#678]
Hello,

I would like to use the webpack Dll feature, which divides by 10 the duration of the compilatio of the  storybook but with no success.
I tried to setup an heal.html, but the content of that file is inserted into the iframe and not the main body, so it doesn't help. 

My `webpack.config` config file: 
```
  plugins: [
    new webpack.DllReferencePlugin({
      // The path to the manifest file which maps between
      // modules included in a bundle and the internal IDs
      // within that bundle
      manifest: require(`${__dirname}/build/core-manifest.json`),
      context: __dirname
    }),
  ]
```

The main script inside the html file is : 
`<script src="static/manager.bundle.js"></script>`
And it crashes because the DLL of my app is not included before that script.

Someone succeed to use storybook and Dll ?

**Comment by serut** [comment]
We are still using Storybook but our 6 months codebase, without any DDL, takes too much time to reload...
```
webpack built d9f77a1e478e823de48d in 46943ms
```

A solution would be to be able to edit the index.html with something like that: 
```
<!-- core.bundle.js is our project webpack DLL -->
<script src="/core.bundle.js"></script>
<!-- manager.bundle.js is the storybook webpack compiled javascript file -->
<script src="static/manager.bundle.js"></script>
```

**Comment by ndelangen** [comment]
I hear you!, we will look into improving things for larger codebases.

Sounds like your codebase would be an excellent test-subject, would it be possible for me to get access to it? @serut

**Comment by serut** [comment]
Our project will be open source on github in few months ! 

Moreover I updated webpack from version 1 to 2 and storybook is not working anymore from now.

**Comment by ndelangen** [comment]
That's on my radar! But can't make promises on how fast that compatibility comes.

**Comment by ndelangen** [comment]
@serut If you'd like to alpha-test the version in the mono-repo? It has webpack 2!

**Comment by serut** [comment]
Ok I will try to find out the migration tutorial and will come back to you. It just concern webpack 2 and not Dll usage right ?  
If you need any other info, please ask !

**Comment by ConneXNL** [comment]
Any updates on this?

**Comment by ndelangen** [comment]
The merged PR should allow you to inject any scripts you want! Both in the preview and manager.
