### ISSUE TITLE
v5.0.11 is not in NPM

### ISSUE THREAD

**Issue by lucasff** [storybooks/storybook#6792]
No 5.x "stable" version exists in NPM which break any installation

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/react-native@^5.0.11
```

**System:**
 - OS: macOS Mojave
 - Framework: react-native
 - Addons: typescript

**Comment by shilman** [comment]
There is no 5.0 release of RN. See https://github.com/storybooks/storybook/issues/5893 deets
