### ISSUE TITLE
Values changed using knobs don't update in a new tab view

### ISSUE THREAD

**Issue by jblaut** [storybooks/storybook#6800]
**Describe the bug**
We use knobs a lot to check how components look with different translations/lengths of headlines, etc. which are then tested by UX. They prefer using the new tab view, without Storybook UI, however in that view, all options changed via knobs disappear and go back to the default view.

**To Reproduce**
1. Go to a story in Storybook
2. Change properties using knobs
3. Click on `Open canvas in new tab` ![image](https://user-images.githubusercontent.com/13763899/57853215-0e208200-77dd-11e9-8482-12b01e3bcbcf.png)
4. Component loads in a new tab with default values

**Expected behavior**
The expected behaviour is to see the component on its own, without Storybook UI, with properties changed according to knobs

**System:**
 - OS: MacOS
 - Browser: Firefox 66, Chrome 74
 - Framework: React
 - Version: 5.0.11

**Comment by shilman** [comment]
This is a little tricky without special-casing the eject button to know about knobs. However, I think it's a nice feature and should be possible.

@ndelangen is there an easy way for knobs to override that button?

**Comment by ndelangen** [comment]
This may be already fixed in the 5.1 beta?

I'll check tomorrow

**Comment by ndelangen** [comment]
I found that if the values are copied from the 'copy button' and then the user presses the `eject iframe window` button it works.

But updating the knobs doesn't work. So I'll try and fix this today.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-rc.1 containing PR #6817 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
