### ISSUE TITLE
Strange behavior with babel-plugin-flow-react-proptypes

### ISSUE THREAD

**Issue by renatorib** [storybooks/storybook#683]
I'm experiencing a strange bahavior when I try to use this babel plugins: `syntax-flow` with `flow-react-proptypes`

I've firstly related on `flow-react-proptypes` issues: https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/67

But, as you can see here https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/67#issuecomment-277346384 it's working perfectly when I use outside of Storybook.

But when I use inside Storybook, It don't tranforms with `propTypes` or `__docgenInfo`.

**Comment by tmeasday** [comment]
Hi @renatorib--do you have an idea of why storybooks is going wrong here? It's hard to understand exactly what is wrong in the issue you linked to above. Can you create a simple reproduction of the problem?

**Comment by ndelangen** [comment]
Please re-open if you are still experiencing this issue 👍
