### ISSUE TITLE
Webpack 2

### ISSUE THREAD

**Issue by tomitrescak** [storybooks/storybook#690]
Hi, is there any guideline how can we move storybook to webpack 2?
Thanks!

**Comment by joscha** [comment]
refs #637

**Comment by ndelangen** [comment]
**Note to self:**
This fork seems to have done pretty much the same things I have also done, could be interesting to compare at some point.

**Comment by eatrocks** [comment]
@ndelangen Is this the proper issue to watch for progress on webpack 2 support in storybook?

**Comment by ndelangen** [comment]
We'll be releasing an 3.0.0.alpha.01 soonish, which will have webpack 2 support.

We'll probably have to write some good migration guides before the real release.

Webpack 2 support is already in master, so you could already give it a try manually by either `npm link` or local file dependencies.

**Comment by ndelangen** [comment]
We're real close to a 3.0.0-alpha.01 release people!

I think after this: https://github.com/storybooks/storybook/issues/773#issuecomment-297679733 I will be publishing!

**Comment by delijah** [comment]
Any updates on this?

**Comment by andrewcashmore** [comment]
I second this...any update?

**Comment by ndelangen** [comment]
I'm working on it as much as I can 👍

**Comment by ajhyndman** [comment]
It looks like #773 was unblocked today.  Is there anything still holding up a 3.0.0-alpha release?  :smile:

**Comment by ndelangen** [comment]
Not too much, 🔬 details I think and then 🚢

**Comment by ndelangen** [comment]
I'm going to releasing `3.0.0-alpha.0` in a short while, so this can be closed.
