### ISSUE TITLE
Block page navigations and make them as actions

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybook#7]
When clicked on a  HREF we need to prevent any page navigation. Instead we need to fire an action.

**Comment by smeijer** [comment]
Is there already a workaround available for this?

**Comment by smeijer** [comment]
Anybody?

**Comment by ndelangen** [comment]
I don't really agree, this should be default storybook behavior.

If a component has a `<a href...` that's what the component is and does.
Overriding this without explicit configuration to do so, would be super unexpected.

I'm guessing it's rather easy to write an addon that will `preventDefault()` any click within it, and log an action. But I haven't seen such an addon yet, so I'm really wondering if this is something we should write.

If you want this comment below or make a PR :)
