### ISSUE TITLE
Unusable with React 16 alpha

### ISSUE THREAD

**Issue by jaredpalmer** [storybooks/storybook#724]
I tried to use with React 16 alpha. However I can't even get you the error message because Chrome literally crashes when I try to open storybook.

**Comment by rogeliog** [comment]
I'm having the same problem 😄

**Comment by ndelangen** [comment]
Ouch that's nasty! 
How fast does chrome crash? any option to do some debugging to see what's causing the crash?

**Comment by ndelangen** [comment]
@xavcz has been working on experimenting with react versions I think

**Comment by xavcz** [comment]
I got it working with a one simple story book but still having lots of warning because of many different instances of React present. We are on our way to have it working with React 15.5 (latest stable), we'll see then how we can make it work well with 16 :)

**Comment by ndelangen** [comment]
Any updates on react 16 @xavcz ? Did you manage to get it to work maybe? 🙏

**Comment by xavcz** [comment]
Ow yeah! It's stalled at the moment but I'll definitely remove the dust! I keep you posted ⚛️🤸

**Comment by danielduan** [comment]
storybook react and react-native should be compatible after https://github.com/storybooks/storybook/pull/1674 and https://github.com/storybooks/storybook/pull/1673
