### ISSUE TITLE
Call to community: submit your project for future compatibility testing

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#732]
I'm looking for projects using storybook so I can do some analysis on what's being used, and also do some future compatibility testing.

I'm going to work on upgrading/updating to webpack 2, but as you may imagine, this could break a lot of projects. I'd love to be able to do it in a backwards compatible way.

Also for future releases, it'd be great if we could get a feel for what external things may break.

So if you could share your project using storybook, that'd be great! Especially if you're using add-ons, or have configured storybook in an interesting way.

**Comment by UsulPro** [comment]
### [Storybook Boilerplate Project](https://github.com/sm-react/react-theming#storybook-boilerplate-project)
Contains a set of pre-installed common storybook addons, scripts for publishing, deploying and so on

**Comment by xDae** [comment]
I have a super simple Yeoman generator for create react components, and it includes a storybook playground by default

https://github.com/xDae/generator-create-react-component

**Comment by StorytellerCZ** [comment]
Don't forget Mantra architecture and related `mantra-cli` which gives an option to generate with storybooks.

https://www.npmjs.com/package/mantra-cli

**Comment by vgpena** [comment]
@ndelangen I'm using Storybook but I can't make the project available -- what info can I provide that will be useful? Addons and general config options that I'm using?

**Comment by nutgaard** [comment]
I'm in the process of creating an addon for a storybook we're using internally (hopefully we'll be able to opensource the whole thing soon), but for now I can help with testing the addon part at least. 

https://github.com/nutgaard/react-storybook-addon-sections

**Comment by hadfieldn** [comment]
The major challenge with Storybook for us has been managing stories for a large number of components within a single project. I created an alternative loader for Storybook that uses [storybook-chapters](https://github.com/sm-react/storybook-chapters) to organize stories in a hierarchical navigation tree that mirrors the location of story files in the filesystem. This makes it easy for us to find & organize stories and to develop them inline with our components.

https://github.com/hadfieldn/storybook-filepath-chapters

**Comment by jrhicks** [comment]
https://github.com/mashmatrix/react-lightning-design-system

**Comment by jasonLaster** [comment]
https://github.com/devtools-html/debugger.html/tree/master/src/components/stories

**Comment by ndelangen** [comment]
@jrhicks Thanks, your code helped me find a fix a bug!

I've tested your project on this branch: https://github.com/storybooks/storybook/pull/1008 and it works as far as I can tell!

**Comment by ndelangen** [comment]
@vgpena if you could share your .storybook folder's contents that would give us an insight into what addons you're combining together.
