### ISSUE TITLE
Migrate Storybook to monorepo

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#742]
Creating this issue to track the work you're doing on moving Storybook to a mono-repo (and the associated bookkeeping).

**Comment by shilman** [comment]
@ndelangen I took a look at migrating issues to the mono-repo. Here's what I found:

1. https://github.com/IQAndreas/github-issues-import - robust issue import script (see below)
2. https://gist.github.com/jonmagic/5282384165e0f86ef105 - an experimental github API that's incrementally better (see below)
3. https://github.com/google/github-issue-mover - the top search result, but only migrates individual issues so not useful

Tested out `github-issues-import` and it creates issues like this: https://github.com/shilman/import-issues-spike/issues/1

This is better than nothing, but updates the issue/comment author and timestamp. It also requires disabling two-factor authentication temporarily.  I have not tested more complex features like migrating milestones/labels/etc. which are also supported.

The experimental API is incrementally better than this, because it preserves the timestamp. However, it does not preserve the author information, closed-at, etc. and requires modifying the issue importer.

**Comment by ndelangen** [comment]
from github support email:
> Note that this API doesn't currently allow you create issues as authored by other users, since that would be a security concern. It's something we're considering adding in the future by allowing users to opt-in to such imports, but I can't say when that will happen. For now, you could add that information in a short header/footer in the content you create (e.g., at the bottom of each issue and comment).

So in whatever way we move issues over, the issues will never retain the original author.

**Comment by shilman** [comment]
@ndelangen In that case, I think the `github-issues-import` is our best option. If we are going to put the mono repo in `storybooks/react-storybook` then the number of issues from the constellation repos should be relatively small. I'm happy to take care of that when the time comes.

**Comment by ndelangen** [comment]
DONE!

**Comment by eddiemonge** [comment]
More than a year in and this still makes me sad. Monorepos might make dev easier but definitely make support harder.

**Comment by ndelangen** [comment]
How so?

**Comment by eddiemonge** [comment]
Searching issues is almost impossible for specific add-ons now. Unless every single issue is tagged with the add-on then knowing what applies to what is hard to do. Even if it is tagged, searching will still most likely pull non-related things in.

**Comment by ndelangen** [comment]
I see, that's a valid point. We try to label things as much and accurate as possible.

Do you have any suggestions what we could do to improve things?
