### ISSUE TITLE
Ignore specific story from appearing in the side menu

### ISSUE THREAD

**Issue by nahumzs** [storybooks/storybook#743]
Do you know how to prevent a specific story from appearing in Storybook side menu? I would like to access a specific story from the iframe url, but preventing the story from appearing in the side menu, it this possible?

**Comment by ndelangen** [comment]
Thanks for the suggestion! This is currently not a feature we have, I guess the metadata introduced for stories here could be used to build such a feature: https://github.com/storybooks/react-storybook/pull/705 (needs to be reviewed and merged though).
