### ISSUE TITLE
Improve docs & assist with automatic story loading

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#746]
`config.js` requires you to `require()` all your stories, It's very common to see users use webpack to autorequire all stories using a pattern:

```js
const regex = /.stories.js$/;
const context = require.context('../src/components', true, regex)
context.keys().map(context)
```

However this is undocumented. We should add this to the docs and possibly add a demo-project using this to refer to.

**Comment by travi** [comment]
not easy to find in the docs, but it is in there: https://getstorybook.io/docs/react-storybook/basics/writing-stories#loading-stories-dynamically

**Comment by danielduan** [comment]
The code in the docs also support nested folders too.

something like `stories/buttons/cancelButton.stories.jsx` would also work. makes organization a lot easier.

**Comment by travi** [comment]
yep, i keep my stories in nested folders, right next to the component. the details in the docs support that approach well

**Comment by ndelangen** [comment]
@travi You say it was not easy to find, do you have any suggestions how to make it easier to find?

**Comment by danielduan** [comment]
@ndelangen I feel like this should be a default that `*.stories.js(x)` be automatically included when you define a `stories` folder with an option to opt out or define custom filename regex in the config file.

**Comment by ndelangen** [comment]
yeah something to think about.

**Comment by travi** [comment]
@ndelangen good question. docs organization is never simple. the main thought i guess i have it that i would have expected these details under the "slow start guide" where it describes the config file since its more related to config than the stories themselves

**Comment by moimikey** [comment]
i would appreciate for checking `stor(ies|y)`. we use this pattern in our modules:

```
reducer.js
component.js
story.js
```

but at the same time, i don't believe storybook should do this by default. this seems more like an implementation detail.

**Comment by ndelangen** [comment]
I could see us auto-loading all `/.story.js$/` in the future.

**Comment by tmeasday** [comment]
> I could see us auto-loading all /.story.js$/ in the future.

I like this pattern because it is consistent with Jest.

**Comment by ndelangen** [comment]
I will close this and create a new issue dedicated to:

> I could see us auto-loading all /.story.js$/ in the future.
