### ISSUE TITLE
Custom webpack config ProvidePlugin issue

### ISSUE THREAD

**Issue by leondragan** [storybooks/storybook#751]
In our application, we use use the ```ProvidePlugin``` plugin from Webpack to avoid having to write the boilerplate ```import React from 'react'``` statements in our components.  This is done via ```webpack.config.js``` by using the following:

```
    plugins: [
      new webpack.ProvidePlugin({
      React: 'react'
      }),
    ]
```

Obviously when trying to display these components using storybook, React is not found since it's missing from the baseline ```webpack.config```.   I attempted to follow the docs to add the ```ProvidePlugin``` code into the custom ```webpack.config.js``` inside my ```/storybook``` folder, but have had no luck.  Here is the current content of that file.

```
var webpack = require('webpack');
// load the default config generator.
var genDefaultConfig = require('@kadira/storybook/dist/server/config/defaults/webpack.config.js');

module.exports = function(config, env) {
  var newConfig = genDefaultConfig(config, env);

  newConfig.plugins.push( new webpack.ProvidePlugin({
      React: 'react'
    }));

  return newConfig;
};
```
But it is not working.  This behavior can be easily seen in the following repo:
[storybook-issue](https://github.com/leondragan-pvt/storybook-issue)

Major thanks.

**Comment by tmeasday** [comment]
Hi @leondragan, thanks for the reproduction!

I added a storybook config + a basic storybook webpack config mirroring the above: https://github.com/tmeasday/storybook-issue and it seems to work.

Your repro didn't seem to include those files (perhaps you forgot to git add them?). I wonder what's different about your version?

**Comment by leondragan** [comment]
Hi @tmeasday, thank you for taking the look at the issue.

The missing files were my bad, and you are correct adding them does fix the issue, so I apologize for the time waste.   

However when running my other code base and yours at the same time, I spotted a difference:
My code had a custom ``.babelrc`` file in the _root_ folder of my project.  So I added  to the storybook-issue and noticed that storybook picked it up, which caused the project to longer work.

Before .babelrc
![image](https://cloud.githubusercontent.com/assets/23174752/24878410/e314f1a0-1de7-11e7-93e0-8894a027e5d4.png)

After .babelrc
![image](https://cloud.githubusercontent.com/assets/23174752/24878432/f1e29b88-1de7-11e7-804c-9ce94b1d3c74.png)

Now I was surprised by this behavior since I would only expect the custom ``.babelrc`` to come into play if it was in the ``/config`` folder.   
Latest code is here: https://github.com/leondragan/storybook-issue

**Comment by tmeasday** [comment]
Hi @leondragan - the only error I see when using that commit is something about a missing package for the `stage-1` babel preset. When I `npm install` it the issue goes away.

What error are you seeing?

**Comment by leondragan** [comment]
I am getting swamped at work so will have to park this for now. OK to close.  Thanks for the help @tmeasday .

**Comment by leondragan** [comment]
I couldn't repro this since the initial attempt.
