### ISSUE TITLE
babel config in package.json

### ISSUE THREAD

**Issue by ButuzGOL** [storybooks/storybook#754]

**Comment by ndelangen** [comment]
Please give us more information what is wrong or being requested here.

**Comment by ButuzGOL** [comment]
currently storybook takes config only from .babelrc but if i want to keep it in package.json
https://github.com/storybooks/react-storybook/blob/master/src/server/babel_config.js#L51

https://babeljs.io/docs/usage/babelrc/#use-via-package-json

**Comment by fczuardi** [comment]
@ndelangen I think this is still an issue and we should reopen this bug.

storybook does not honor babel presets and plugins defined inside package.json (the workaround is to copy that babel config to a different file, and name that file .babelrc)

I think it would be nice if storybook is able to use existing custom babel configs when they are present in the package.json, and I can try to write up a patch if this issue gets reopened.

**Comment by ndelangen** [comment]
Sure, I would be happy to get a PR on this!

Here's where the code is:
https://github.com/storybooks/storybook/blob/master/app/vue/src/server/babel_config.js

(there's similar code for `app/vue`)

**Comment by ndelangen** [comment]
@fczuardi Need help help opening a PR?

**Comment by JulianoRodrigues** [comment]
Hey guys, do you still need help with this issue?

**Comment by Hypnosphi** [comment]
Released as [`4.0.0-alpha.20`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.20)
