### ISSUE TITLE
get all stories with Addon API

### ISSUE THREAD

**Issue by ZigGreen** [storybooks/storybook#767]
Why there is no addon API to get all stories?

**Comment by UsulPro** [comment]
@ZigGreen maybe this API could help you?
https://github.com/storybooks/react-storybook/blob/master/src/client/preview/client_api.js#L85

**Comment by ZigGreen** [comment]
Yeap, this API meet my needs. But pls tell me how I can use it. Isn't it a private API?

**Comment by UsulPro** [comment]
@ZigGreen 

here is a brief example how to use it:

```js
import { storiesOf, getStorybook } from '@kadira/storybook';

storiesOf('React App', module)
  .add('Story 1', () => <Story1 />)
...

const myStories = getStorybook();
console.log(myStories);
```
You'll have an array with all you storyKind -> stories ...
