### ISSUE TITLE
Change npm organisation from kadira to storybook

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#773]
We will be publishing to the storybook organisation on npm, our code should reflect that.

- [ ] Change package names
- [ ] Change info in package.json like repository etc
- [ ] Change documentation
- [ ] Deprecate existing `@kadira` packages, or at least the addons?

**Comment by aaronmcadam** [comment]
I recently wrote a codemod for updating `import`s. Let me know and I'll raise a PR later.

**Comment by ndelangen** [comment]
I'd love for this PR to happen and would merge it in a heartbeat.
I think webpack 2 is done (need to do more regression testing) so I think we've got only this to do before doing a alpha.01 release! 🚢

**Comment by ndelangen** [comment]
Looks about right to me, did some superficial testing and it seems to preserve other dependencies. Are you going to do a PR? 🥇

**Comment by aaronmcadam** [comment]
Yeah I'll raise one soon @ndelangen

**Comment by wizardzloy** [comment]
@ndelangen is it going to be `@storybook/storybook` or just `storybook`?

**Comment by ndelangen** [comment]
Uhm good question, perhaps something I should throw into the #roadmap on slack: but i was kinda thinking about `@storybook/core`

**Comment by ndelangen** [comment]
`@storybook/storybook` it is 😆

**Comment by wizardzloy** [comment]
Got it!

**Comment by ndelangen** [comment]
Completed
