### ISSUE TITLE
How to get a list of stories during a build step?

### ISSUE THREAD

**Issue by swese44** [storybooks/storybook#775]
I am setting up Backstopjs for visual diff regression testing and want to automatically run a visual test for every Storybook story.

It looks like I can only use the client API to retrieve stories at runtime, after the app has run and stories have been added. But I need to generate the list of URLs statically in a build step. A few ideas how this could be solved:

1. Static analysis of my story files, just run a regex on the source as text. This would be brittle and would be harder to share the code with others.
2. Extend the static build to also create a .json file containing `kinds` with child `story names`.

Maybe there's something else more obvious I haven't thought of? Thoughts? Thanks!

**Comment by ndelangen** [comment]
Check out how storyshots works: 
https://github.com/storybooks/storybook/blob/master/addons/storyshots/src/index.js#L61

**Comment by IgorZh** [comment]
@swese44 , hi
did you solve your problem? If yes, could you share the way how you do it?

**Comment by JohnAlbin** [comment]
Can we re-open this ticket?

It would be a super handy if Storybook could output a list of stories into a .json file. Not just for visual regression testing, I'd imagine.

**Comment by ndelangen** [comment]
In 5.2 we've introduced CSF which is a declarative format for defining stories.

In 5.3 we'll introduce tri-config which will make it possible for defining stoy-files declaratively too.

These 2 things together will make it possible -in theory- to generate a JSON file during the bundle-phase.

So work is being done to make this possible.
