### ISSUE TITLE
Clear shortcut for addon-actions - Cmd/Ctrl + K to clear

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#777]
<a href="https://github.com/ericclemmons"><img src="https://avatars3.githubusercontent.com/u/15182?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericclemmons](https://github.com/ericclemmons)**
_Tuesday Nov 01, 2016 at 19:22 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-actions/issues/25_

----

This is a common shortcut in terminals (**and even in the Chrome DevTools!**) to clear the output.

This would be very handy.

I can submit this request upstream in https://github.com/kadirahq/react-storybook/issues/new as well, if you'd prefer.

Thanks!

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Saturday Nov 05, 2016 at 05:39 GMT_

----

We would to add a feature to support for addons to register keyboard shortcuts.
With that we could do this.

I add a task here: https://github.com/orgs/storybooks/projects/1#card-698087

**Comment by ndelangen** [comment]
Adding an api for registering shortcuts will be part of: #865 #1209 

Addon-actions would also have to be modified to take advantage of this and clear itself when the called.
