### ISSUE TITLE
Circular json can possibly hang.

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#778]
<a href="https://github.com/rhalff"><img src="https://avatars1.githubusercontent.com/u/274358?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rhalff](https://github.com/rhalff)**
_Wednesday Nov 02, 2016 at 02:55 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-actions/issues/26_

----

It can be replicated by replacing `circular` with something like `window` within:

 https://github.com/kadirahq/storybook-addon-actions/blob/master/.storybook/stories.js#L20

The click on the circular button will cause the action to never be logged.

I've tried replacing `json-stringify-safe` with `circular-json` which seems to behave better.
But even then after the 4th click `circular-json` will throw a circular reference error.

I now know how to circumvent this by just not logging something with circular references, however when this bug is encountered it's not immediately clear the hang originates from within storybook which makes one try to debug the application code itself first.

I think replacing json-stringify-safe with circular-json would already be an improvement.

**Comment by shilman** [comment]
<a href="https://github.com/leMaik"><img src="https://avatars1.githubusercontent.com/u/5544859?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [leMaik](https://github.com/leMaik)**
_Wednesday Nov 02, 2016 at 18:10 GMT_

----

Also facing this problem... Wasted hours just to find out that storybook caused this. :cry:

**Comment by shilman** [comment]
<a href="https://github.com/jonnyelliot"><img src="https://avatars1.githubusercontent.com/u/433293?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonnyelliot](https://github.com/jonnyelliot)**
_Thursday Feb 16, 2017 at 14:33 GMT_

----

Also hit this issue.

**Comment by shilman** [comment]
<a href="https://github.com/ndelangen"><img src="https://avatars1.githubusercontent.com/u/3070389?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndelangen](https://github.com/ndelangen)**
_Wednesday Apr 05, 2017 at 21:06 GMT_

----

A PR fixing this would be super welcome! Would you care to give it a go @rhalff ?

**Comment by ndelangen** [comment]
@rhalff @leMaik @jonnyelliot Any of you feel like contributing to help resolve this issue? ♥️

**Comment by leMaik** [comment]
@ndelangen I'd like to, but I have no idea how to fix this. :confused:

**Comment by jonnyelliot** [comment]
@ndelangen I can take a look at this.

**Comment by ndelangen** [comment]
@leMaik Here's why i thought it would be pretty simple:

> I think replacing json-stringify-safe with circular-json would already be an improvement.

Maybe you and @jonnyelliot can contact each other and resolve it together. If you need my help, just ask! 🥇

**Comment by ndelangen** [comment]
@jonnyelliot Is this still something you're interested in to fix?

Did you get stuck somewhere? maybe I can help!

**Comment by dangreenisrael** [comment]
Hey guys, is someone actively working on this? If not I can take a stab at it this weekend.

**Comment by rhalff** [comment]
I could have a look, no guarantees though

Btw, the link in the original post should become:
https://github.com/storybooks/storybook/blob/master/addons/actions/.storybook/stories.js#L20

The current format function only test for a 'SyntheticEvent' but there are many more cases where recursion will fail:
https://github.com/storybook-eol/storybook-addon-actions/blob/master/src/preview.js#L7

Node's build-in `util.format` could be used, storybook action stringifies to log something to the log window so precise recursion is not needed.

**Comment by ndelangen** [comment]
@dangreenisrael @rhalff a PR to fix this proper would be fantastic!

**Comment by danigulyas** [comment]
Nice catch people!

So i've hit this and (just like you) spent about an hour on this, to my salvation, moving the event to a function parameter instead of an object will solve the issue, see example:

before:
```jsx
const MyAwesomeComponent = ({ onClick }) => (
  <button 
    onClick={(event) => onClick({ event, awesome: true })} 
  />
);
```

after:
```jsx
const MyAwesomeComponent = ({ onClick }) => (
  <button 
    onClick={(event) => onClick(event, { awesome: true })} 
  />
);
```

**Comment by ndelangen** [comment]
I think this is fixed right?
