### ISSUE TITLE
Hitting the direct URL doesn't load comments.

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#782]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arunoda](https://github.com/arunoda)**
_Monday Oct 17, 2016 at 06:52 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-comments/issues/42_

----

When we load the current URL, comment addon won't load comments for the current screen.

**Comment by ndelangen** [comment]
addon-comments is something we'll completely redo at some point, good feature to implement then, but for now closing.
