### ISSUE TITLE
Print correct URL link for Github Enterprise

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#784]
<a href="https://github.com/ankurp"><img src="https://avatars2.githubusercontent.com/u/498669?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ankurp](https://github.com/ankurp)**
_Monday Mar 27, 2017 at 20:23 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-comments/issues/52_

----

When deploying to github pages on github enterprise, it prints the github.io domain URL which is wrong. It should use the same domain as the github enterprise if the repo url is not github.com

**Comment by ndelangen** [comment]
addon-comments is something we'll completely redo at some point, good feature to implement then, but for now closing.

**Comment by ptolemybarnes** [comment]
I also encountered this. The problematic code is:

```
// @storybook/storybook-deployer/src/utils.js
module.exports.getGHPagesUrl = function getGHPagesUrl(ghUrl) {
  var parsedUrl = parseGitUrl(ghUrl);
  var ghPagesUrl = 'https://' + parsedUrl.owner + '.github.io/' + parsedUrl.name + '/';
  return ghPagesUrl;
};
```
