### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#785]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arunoda](https://github.com/arunoda)**
_Monday Jun 20, 2016 at 03:04 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/11_

----

It's better to have tests for this projects. Write them.

cc @mnmtanish @roonyh

**Comment by ndelangen** [comment]
We should write unit tests for a whole truckload of addons and stuff, it's known.

This will be a forever open issue, unless we add some sort of metric / definition-of-done to it. We could.. but honestly I don't think it adds value to have this issue open at all.
