### ISSUE TITLE
Modifying state from decorator component does't work

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#787]
<a href="https://github.com/ritz078"><img src="https://avatars0.githubusercontent.com/u/5389035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ritz078](https://github.com/ritz078)**
_Friday Jun 24, 2016 at 10:18 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/18_

----

I am using a decorator `Container` that accepts the children. The children are cloned inside container so that they use the value from the container's state.

But the moment I use this plugin, it doesn't work because `Story` component comes in between `Container` and `children` and somehow children can't access the props passed by the `Container`. It just renders with the default props.

**Container.js**

``` js
export default class Container extends Component {
  constructor (props) {
    super(props);
    this.state = {
      value: props.value
    };
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange (data) {
    this.setState({
      value: data.value
    }, () => {
      this.props.action('data changed')(data);
    });
  }

  render () {
    const self = this;
    const children = React.Children.map(this.props.children, (child) => {
      return React.cloneElement(child, {
        value: self.state.value,
        onChange: self.handleChange
      });
    });

    return (
      <div className={this.props.className}>
        {children}
      </div>
    );
  }
}
```

**Story.js**

``` js
import React  from 'react';
import { storiesOf, action } from '@kadira/storybook';
import { Switch } from '../components';
import Container from './Container';

storiesOf('Switch Button')
  .addDecorator((story) => <Container action={action} value={false}>{story()}</Container>)
  .addWithInfo('Basic', 'hello',  () => (
    <Switch name='basic' />
  ))
```

Now when I click on Switch, its state doesn't change but when I replace `addWithInfo` with `add`, it works.

**Comment by ndelangen** [comment]
Will be fixed with #1147
