### ISSUE TITLE
Option to ignore components in source viewer

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#789]
<a href="https://github.com/kesne"><img src="https://avatars2.githubusercontent.com/u/498479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kesne](https://github.com/kesne)**
_Tuesday Jun 28, 2016 at 22:53 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/29_

----

Sometimes, I have a wrapper around components to help their presentation, but they aren't relevant to source inspection. Would it make sense to add either a prop or some sort of array to define components you want to ignore?

**Comment by shilman** [comment]
<a href="https://github.com/Koleok"><img src="https://avatars1.githubusercontent.com/u/10928312?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Koleok](https://github.com/Koleok)**
_Tuesday Jan 17, 2017 at 04:06 GMT_

----

I have a similar issue when using [`withProps`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withprops) from `recompose` which i do quite frequently. This actually makes the info addon sort of unusable for me, short of some heavy workaround that I find it hard to justify with deadlines pulsing in front of me haha.

However I **love** how it looks and the documentation it provides with a normal component so i would love to see a library level solution to this. If I can figure out a non-epic way to fix this I'll make a PR 💃

**Comment by shilman** [comment]
<a href="https://github.com/elisherer"><img src="https://avatars3.githubusercontent.com/u/1045347?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elisherer](https://github.com/elisherer)**
_Saturday Jan 28, 2017 at 19:43 GMT_

----

#125

**Comment by ndelangen** [comment]
Will be fixed with #1147 
We are moving the info into a panel.
