### ISSUE TITLE
Use defaultProps as input for knobs & integrate smart-knobs

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#792]
<a href="https://github.com/kevinSuttle"><img src="https://avatars0.githubusercontent.com/u/95672?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kevinSuttle](https://github.com/kevinSuttle)**
_Thursday Sep 15, 2016 at 17:20 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/30_

----

See also: 
https://github.com/kadirahq/storybook-addon-knobs/commit/2f12de4a94bee358c6676072292e1356965ad4b3

https://github.com/kadirahq/react-storybook-addon-info/issues/35

Seems a bit error-prone to write them out each time. 

Example: 

`theme={select('Theme', ['Light', 'Dark'], 'Light')}`

when this is defined as: 

``` jsx
theme: React.PropTypes.oneOf(['Light, Dark'])
...

Button.defaultProps = {
  theme: "Light"
}
```

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Friday Sep 16, 2016 at 00:34 GMT_

----

I think we can do it, but the detecting types would be a problem.
But, in the above case, if we write it like this, I hope we can fix our code to use the default props somehow.

```
theme={select('Theme', ['Light', 'Dark'])} 
```

Is that what you are referring to?

**Comment by shilman** [comment]
<a href="https://github.com/kevinSuttle"><img src="https://avatars0.githubusercontent.com/u/95672?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevinSuttle](https://github.com/kevinSuttle)**
_Friday Sep 16, 2016 at 03:31 GMT_

----

@arunoda You hit on it here. react-docgen does a lot of this and supports Flow. https://github.com/kadirahq/react-storybook-addon-info/issues/67#issuecomment-247491057

**Comment by shilman** [comment]
<a href="https://github.com/lucasconstantino"><img src="https://avatars1.githubusercontent.com/u/2688512?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lucasconstantino](https://github.com/lucasconstantino)**
_Wednesday Oct 19, 2016 at 20:20 GMT_

----

Some related work in progress: https://github.com/lucasconstantino/storybook-addon-smart-knobs

**Comment by ndelangen** [comment]
I think it's possible to get the defaultProps from the component and add them to your knob?

> Seems a bit error-prone to write them out each time.
A story is just-javascript™.. You can use variables?

**Comment by ndelangen** [comment]
I'd like to integrate the smart-knobs into the main repo at some point, maybe even add it as some sort of option to knobs. Proposals welcome!
