### ISSUE TITLE
Remove UPPERCASE text-transform from labels

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#793]
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philcockfield](https://github.com/philcockfield)**
_Tuesday Oct 04, 2016 at 08:44 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/53_

----

I understand stylistically the reason to put that transform on the property label, BUT with camelCase there is information contained with the name (the word-parts) that you are stomping out by applying this style.  It's valid and helpful information for the developer working with the knobs:

![image](https://cloud.githubusercontent.com/assets/185555/19067731/f20575c2-8a7b-11e6-9d1b-56ee2ae6e271.png)

It would be great if you reset this to display as the actual name of the property!  Digging knobs, nice work!

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Tuesday Oct 04, 2016 at 09:47 GMT_

----

I get the point. Happy to accept to a PR :)

**Comment by shilman** [comment]
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philcockfield](https://github.com/philcockfield)**
_Tuesday Oct 04, 2016 at 19:07 GMT_

----

Ha ha!  "Happy to accept to a PR :)" should be a keyboard shortcut.  I'll take a look.  

Also, want to talk about the index selector on StoryBook itself.  Is that a pluggable module - there's some improvements I'd like to make to it.  What's the feasibility of that?

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Tuesday Oct 04, 2016 at 23:10 GMT_

----

What's index selector?
If that's something new, let's discuss in a new issue.

**Comment by shilman** [comment]
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philcockfield](https://github.com/philcockfield)**
_Thursday Oct 06, 2016 at 18:45 GMT_

----

Hey @arunoda - I was referring to this when I said "index selector":

![image](https://cloud.githubusercontent.com/assets/185555/19165827/c7d10072-8c61-11e6-8558-be63d49c3222.png)

But that's not `knobs`, or even this issue, so I'll start a new issue on the `storybook` repo.  
- What do you refer to that panel as?
- What's the best repo to put that on (I think you've isolated the UI parts of StoryBook out somewhere, right?  Like this one: https://github.com/kadirahq/storybook-ui/ ?)

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Thursday Oct 06, 2016 at 22:42 GMT_

----

Yep. It's on the Storybook UI repo.
That's not pluggable yet.
But we want to customize it (To show stories only for changed snapshots).
Currently, there no plans on how we should do it.

**Comment by mthuret** [comment]
A PR fixing this was merged couple days ago.
