### ISSUE TITLE
Values Bleeding Between Stories

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#794]
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philcockfield](https://github.com/philcockfield)**
_Tuesday Oct 04, 2016 at 19:25 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/55_

----

I have two stories that load two different components that both have a `size` property.
If I have a knob for setting that size like so:

```
// For component-1
size={knobs.number('size', 60)}

// For component-2
size={knobs.number('size', 12)}
```

When I load component-2, I'm seeing the component-1 value of 60.

This is on ReactNative, not sure if that makes a difference.  Also, possibly related to this, there is a little bit of weirdness when jumping between stories with the knobs panel not re-rendering to represent the currently loaded stories knobs settings.

Thanks guys!

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Tuesday Oct 04, 2016 at 23:12 GMT_

----

@philcockfield may be that's something with RN. 
@roonyh could you check that and bring onStory knobs clear feature soon.

**Comment by shilman** [comment]
<a href="https://github.com/wordofchristian"><img src="https://avatars1.githubusercontent.com/u/555044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wordofchristian](https://github.com/wordofchristian)**
_Friday Jan 13, 2017 at 18:48 GMT_

----

I can confirm this occurs with react web as well, not just react native. The query strings seem to persist when switching between stories. It also continues to show the knobs from the previous story on the new one (even if the new story doesn't have any knobs). This creates a confusing UI experience.

Perhaps I'm experiencing a different issue than the one you're describing

**Comment by shilman** [comment]
<a href="https://github.com/ChristopherBiscardi"><img src="https://avatars2.githubusercontent.com/u/551247?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChristopherBiscardi](https://github.com/ChristopherBiscardi)**
_Monday Feb 06, 2017 at 22:03 GMT_

----

@wordofchristian I'm also seeing this (on web) due to the lack of clearing the query params

**Comment by shilman** [comment]
<a href="https://github.com/wordofchristian"><img src="https://avatars1.githubusercontent.com/u/555044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wordofchristian](https://github.com/wordofchristian)**
_Monday Feb 06, 2017 at 22:07 GMT_

----

@ChristopherBiscardi I was able to partially solve it by adding the `withKnobs` decorator to my global storybook config

```javascript
import {  addDecorator } from '@kadira/storybook';
import { withKnobs } from '@kadira/storybook-addon-knobs';
// add global knobs decorator to fix issue of persistent values between stories
addDecorator(withKnobs);
```

**Comment by shilman** [comment]
<a href="https://github.com/sbaggott"><img src="https://avatars3.githubusercontent.com/u/527856?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sbaggott](https://github.com/sbaggott)**
_Wednesday Feb 15, 2017 at 21:13 GMT_

----

This is definitely an issue with react web. We are using the withKnobs decorator in our code, but it doesn't prevent the issue with persistent values in the query strings.

**Comment by Donaldini** [comment]
I have an issue that seems related, but might not be...

I have a Button component that has a caption property in its own Story.
`<Button caption={text('Caption', 'My button')} />`

When I create a different component that implements this button I cannot override the original Knob in its Story.
```
const ButtonWithCancel = (captionProp) => (
    <Button caption={captionProp} /> or <a href="#">cancel</a>
);

<ButtonWithCancel captionProp={text('Caption', 'Save')} />
```

This last **ButtonWithCancel** will display _My Button_ and not _Save_

**Comment by Billy-** [comment]
I am also having the same issue... I've only noticed it on components which are connected though, so I though that might be something to do with it.
