### ISSUE TITLE
Can't edit Date knob by hand

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#797]
<a href="https://github.com/roonyh"><img src="https://avatars3.githubusercontent.com/u/3872221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roonyh](https://github.com/roonyh)**
_Friday Oct 21, 2016 at 05:37 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/64_

----

The date knob cannot be edited by editing the accompanying text field. The moment it becomes an invalid date string the string turns to 'Invalid Date'.

**Comment by shilman** [comment]
<a href="https://github.com/FredyC"><img src="https://avatars3.githubusercontent.com/u/1096340?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FredyC](https://github.com/FredyC)**
_Tuesday Jan 24, 2017 at 19:55 GMT_

----

Yes, found that rather annoying too, especially since calendar doesn't work for date selection either (version 1.7.1)

**Comment by ndelangen** [comment]
Please re-open with a clear reproduction or steps to reproduce 👍
