### ISSUE TITLE
date knob passes timestamp (number) instead of Date object

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#798]
<a href="https://github.com/jardakotesovec"><img src="https://avatars0.githubusercontent.com/u/1590681?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jardakotesovec](https://github.com/jardakotesovec)**
_Thursday Oct 27, 2016 at 16:19 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/68_

----

Is that intention? I would expect that inside component I will receive Date object and not timestamp.

**Comment by shilman** [comment]
<a href="https://github.com/simon360"><img src="https://avatars1.githubusercontent.com/u/816203?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [simon360](https://github.com/simon360)**
_Tuesday Feb 21, 2017 at 12:49 GMT_

----

It would be nice to have options here. I'd prefer to receive the date as an ISO8601 string, because of the way our component will be used. I'm not sure there's one correct type.

Perhaps an optional callback on `date()` which receives a `Date` as its input and returns whatever it wants, which is then passed on to the component. Could be a string, could be the `Date`, could be the timestamp. The current behaviour would remain as the default.

**Comment by ndelangen** [comment]
You should probably wrap the output of the knob in a way you find easy to deal with or your components expects. We can't please everyone, and there's too many ways to format a date.
A timestamp sounds perfectly reasonable to me.

**Comment by aerlinn13** [comment]
Well, I suppose it has to return Date object because it's called date, right? It's very easy to retrieve epoch timestamp from Date object via default getTime method, but if you want to convert epoch time in ms into Date, it would not be that easy. Current implementation is misleading and inconsistent.

**Comment by maxKimoby** [comment]
Makes no sense to return a number when type is 'Date'.
