### ISSUE TITLE
select knob seems backwards

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#799]
<a href="https://github.com/lifehackett"><img src="https://avatars0.githubusercontent.com/u/1809761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lifehackett](https://github.com/lifehackett)**
_Tuesday Nov 01, 2016 at 20:18 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/71_

----

Every time I use the `select` knob object syntax I write it incorrectly, but it also is more limiting.  IMO it makes more sense that the dropdown would show the keys and on selection pass the value.  

Additionally, the current setup restricts what can be passed as the prop value to strings or numbers because object keys are more restricted.  i.e. you can't have a function or an object in the key position, but you could in the value.

I realize this would be a breaking change.

**Comment by shilman** [comment]
<a href="https://github.com/webOS101"><img src="https://avatars0.githubusercontent.com/u/328450?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [webOS101](https://github.com/webOS101)**
_Wednesday Dec 07, 2016 at 20:48 GMT_

----

Add to this that you cannot set `null` as a key, either.  I went through some of our stories and found cases where people expected that they could use `'null': null` inside the select.  Needless to say, it doesn't work that way.

**Comment by shilman** [comment]
<a href="https://github.com/bluetidepro"><img src="https://avatars3.githubusercontent.com/u/410701?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bluetidepro](https://github.com/bluetidepro)**
_Wednesday Feb 08, 2017 at 18:49 GMT_

----

YES. Please fix this. It makes 0 sense why it was done this way. It is completely backwards.

**Comment by shilman** [comment]
<a href="https://github.com/ndbroadbent"><img src="https://avatars1.githubusercontent.com/u/139536?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndbroadbent](https://github.com/ndbroadbent)**
_Tuesday Feb 21, 2017 at 09:06 GMT_

----

Oh yeah, I was just wondering why my numbers were all getting converted to strings. I was using this:

```js
select('Size', { 4: 4, 6: 6, 9: 9 }, 4)
```

This definitely feels backwards. The main reason is because when you use this syntax, your keys must be strings, but the values can be any type.

EDIT: Actually, values are serialized in the URL so they will be strings anyway. I think I just need to use `parseInt`.

**Comment by ndelangen** [comment]
Yup solid case here, Anyone wants to contribute here? @ndbroadbent @bluetidepro @webOS101 @lifehackett

Sounds like it won't be too complex to do. Though it's likely a breaking change.

**Comment by SEAPUNK** [comment]
bump

**Comment by ndelangen** [comment]
Added a comment on the associated PR:
https://github.com/storybooks/storybook/pull/1745

**Comment by SEAPUNK** [comment]
bump

**Comment by ndelangen** [comment]
Should be merged/solved pretty quick:
https://github.com/storybooks/storybook/pull/1745#issuecomment-354765501

**Comment by lifehackett** [comment]
Awesome. Glad to be able to make use of this. I think this issue can be closed.

**Comment by ndelangen** [comment]
I'll close it when the PR is merged 👍

**Comment by Hypnosphi** [comment]
Released as `3.4.0-alpha.7`
