### ISSUE TITLE
array knob converts all types to string

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#801]
<a href="https://github.com/stefanmihoc"><img src="https://avatars0.githubusercontent.com/u/7522957?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stefanmihoc](https://github.com/stefanmihoc)**
_Wednesday Dec 21, 2016 at 13:33 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/80_

----

Hi,

Just encountered this issue. I use the knob like this:
```sampleArray = array('Sample array', [2, 3]);```
It works fine with that default value of [2, 3], but once you do a change it gets converted to e.g. this: ["2","3","4"] (if I added the 4), and my component doesn't work anymore cause it expects those to be numbers. I really really don't want to check and parseInt those strings inside my component.

Thanks!

Update: I just saw that the array knob does this: 
```
...
value={knob.value.join(knob.separator)}
onChange={(e) => onChange(e.target.value.split(knob.separator))}
...
```
so, this would be a problem with any type other than string in the array. 

Update 2: I can still do my own mapping after the knob of course, something like:
```
sampleArray = array('Sample array', [2, 3]).map(Number).filter(item => item);
```
Also, using
```
sampleArray = object('Sample array', [2, 3]);
```
seems to work just fine for my use case.

**Comment by shilman** [comment]
<a href="https://github.com/ndbroadbent"><img src="https://avatars1.githubusercontent.com/u/139536?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndbroadbent](https://github.com/ndbroadbent)**
_Tuesday Feb 21, 2017 at 10:23 GMT_

----

I think the main problem is that the values are being serialized and stored in the URL. I ran into this when trying to figure out `select`. I think doing your own mapping is the right way. You just need to do that in the story, and not the actual component.

**Comment by ndelangen** [comment]
I'll close this one as a duplicate in favour of this one: #799 

Please help by contributing a fix!

Also related:
#805 #1296
