### ISSUE TITLE
color cannot use RGBA

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#802]
<a href="https://github.com/lifeiscontent"><img src="https://avatars0.githubusercontent.com/u/180963?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lifeiscontent](https://github.com/lifeiscontent)**
_Tuesday Jan 03, 2017 at 10:32 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/82_

----

since the color picker has an option to use RGBA, it should be supported as an output value for a knob

**Comment by ndelangen** [comment]
Clearly a bug! Do you think you could create a PR? @lifeiscontent

**Comment by vgpena** [comment]
Would the rgba value ideally appear in the URL as a part of the Knobs querystring, in addition to the hex value?

**Comment by lifeiscontent** [comment]
@vgpena I'd imagine so if that's how it currently behaves. I'm unsure because I haven't written a story in several months.

**Comment by ndelangen** [comment]
@vgpena There's a hex notation for rgba, so that shouldn't be a problem.

**Comment by Hypnosphi** [comment]
Fix released as [`3.3.4`](https://github.com/storybooks/storybook/releases/tag/v3.3.4)
