### ISSUE TITLE
Add a multiselect knob

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#806]
<a href="https://github.com/benediktvaldez"><img src="https://avatars1.githubusercontent.com/u/1928103?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [benediktvaldez](https://github.com/benediktvaldez)**
_Tuesday Feb 28, 2017 at 11:39 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/89_

----

Is there any way to get a `<select multiple>` instead of just `<select>`?

Could in theory just be an option on the `select()` method

Can make a PR if there is interest?

**Comment by ndelangen** [comment]
Hey @benediktvaldez 
Sure sounds like this a perfectly fine feature for knobs! Please submit a PR!

**Comment by benediktvaldez** [comment]
Completely forgot about this – what an awesome idea haha 🤣 

I'll look into it.

**Comment by ndelangen** [comment]
Here's something you might like to use:
https://react.rocks/example/react-select-box

**Comment by ndelangen** [comment]
@benediktvaldez Still interested?

**Comment by benediktvaldez** [comment]
Actually yes, wow this one hasn't gotten a lot of love. I'll be needing this for a component I'm making right now, so I'll try to make the time to implement it ;)

Thanks for the reminder @ndelangen

**Comment by mkochendorfer** [comment]
It would obviously be great to get true support into the knob for this, but in the meantime, here is a potential work around that people could use that just uses boolean knobs to simulate a multiselect behavior:
```
/**
 * A multiselect checkbox knob that generates an array.
 *
 * An temporary approach until https://github.com/storybooks/storybook/issues/806 is done.
 * @param label
 * @param options
 * @param defaultValue
 * @returns {Array}
 */
function multiselect(label, options, defaultValue) {
  const values = [];

  // Allow for default value to be an array or a single value.
  const defaultValues = _.isArray(defaultValue) ? defaultValue : [defaultValue];

  // Create checkboxes for each value in the multiselect.
  _.forEach(options, (value, key) => {
    const checkboxLabel = _.isNumber(key) ? `${label}: ${value}` : key;

    const selected = boolean(checkboxLabel, _.includes(defaultValues, value));

    if (selected) {
      values.push(value);
    }
  });

  return values;
}
```

**Comment by danielduan** [comment]
I'm gonna go ahead and close this ticket. It's been open wayy too long.

If someone is willing to implement this, please open a new issue or PR and reference this one.

**Comment by garrettmaring** [comment]
If anyone's still looking for this, it works under the [`optionsKnob`](https://www.npmjs.com/package/@storybook/addon-knobs#options).

<img width="685" alt="Screen Shot 2019-07-26 at 12 23 37 PM" src="https://user-images.githubusercontent.com/8270120/61976288-417f4a00-afa0-11e9-8db6-44be7caceda9.png">

**Comment by jjorissen52** [comment]
The `optionsKnob` way wasn't working for me. However, [Storybook controls](https://storybook.js.org/docs/react/essentials/controls) do support a multi-select:

```javascript
export default {
  title: "Example/Button",
  component: Button,
  // More on argTypes: https://storybook.js.org/docs/react/api/argtypes
  argTypes: {
    variants: {
      options: Object.values(BUTTON_VARIANTS),
      control: { type: "multi-select" },
    },
  },
}
```

![image](https://user-images.githubusercontent.com/12461302/151224580-ca86df01-07f0-4ab3-9674-45339da01539.png)
