### ISSUE TITLE
using Preact with addon-knobs is broken

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#807]
<a href="https://github.com/amadt"><img src="https://avatars0.githubusercontent.com/u/944646?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amadt](https://github.com/amadt)**
_Wednesday Mar 01, 2017 at 22:17 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/90_

----

I switched my storybook to using preact under the hood:

```
module.exports = {
  resolve: {
    alias: {
      'react': 'preact-compat',
      'react-dom': 'preact-compat'
    }
  }
};
```
_.storybook/webpack.config_

Storybook on it's own works great, but Knobs is throwing an exception:

```
Uncaught TypeError: Cannot read property 'removeListener' of null
    at WrapStory.componentWillUnmount (WrapStory.js:70)
    at unmountComponent (preact.js:388)
    at buildComponentFromVNode (preact.js:367)
    at idiff (preact.js:180)
    at diff (preact.js:159)
    at Object.render (preact.js:411)
    at Object.render$1 [as render] (preact-compat.js:156)
    at renderException (render.js:62)
    at renderPreview (render.js:137)
    at Array.renderUI (index.js:89)
```

Any ideas?

**Comment by ndelangen** [comment]
This is where the error is from:
https://github.com/storybooks/storybook/blob/96e99a31d2ea008b4be3914b84dd576c160dfafc/addons/knobs/src/components/WrapStory.js#L33

I'm not sure why, but for a start, you could try wrapping it in a try-catch, and see what work?

**Comment by saitonakamura** [comment]
Same story using react

**Comment by ndelangen** [comment]
@saitonakamura Can you give us more information on how you're experiencing this error with React?

**Comment by saitonakamura** [comment]
Sorry, false alarm, it was v2 vs v3 incompatibility
