### ISSUE TITLE
hits history.pushState limits in Storybook 2+

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#808]
<a href="https://github.com/gmarinov"><img src="https://avatars3.githubusercontent.com/u/14101296?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gmarinov](https://github.com/gmarinov)**
_Tuesday Mar 07, 2017 at 23:48 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/91_

----

please see attached gif

![knobs](https://cloud.githubusercontent.com/assets/14101296/23683305/260d2616-0390-11e7-85c7-3a6e868ccd04.gif)

not sure if this is a storybook or knobs bug.

browser: Safari 10, OSX 10.12
expected: reasonable not to push state before mouse is released?
actual: pushes on slider input, hitting browser limit

**Comment by ndelangen** [comment]
This is fixed: 
https://github.com/storybooks/storybook/commit/50a781d4e343eb811a011e14d3d0797d36f9ae23
@Gongreg added a optional throttle.
