### ISSUE TITLE
Add throttling/batching of updates

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#809]
<a href="https://github.com/Gongreg"><img src="https://avatars2.githubusercontent.com/u/3867635?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Gongreg](https://github.com/Gongreg)**
_Thursday Mar 23, 2017 at 20:09 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/92_

----

Right now when you are typing all updates are instantly sent. It doesn't work well when we deployed the react-native storybook to server (since it uses websockets). Actually sometimes it fails to catch up even when running locally. It would be cool to have an option to enable update throttling/batching.

If nobody can work on this, maybe we will have some time to do it next week, but that is a very slim chance.

**Comment by Gongreg** [comment]
https://github.com/storybooks/storybook/pull/1039
