### ISSUE TITLE
Add support for array of objects

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#810]
<a href="https://github.com/royair"><img src="https://avatars3.githubusercontent.com/u/8818555?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [royair](https://github.com/royair)**
_Wednesday Mar 29, 2017 at 18:09 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/94_

----

**Comment by shilman** [comment]
<a href="https://github.com/UsulPro"><img src="https://avatars2.githubusercontent.com/u/14885189?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [UsulPro](https://github.com/UsulPro)**
_Wednesday Mar 29, 2017 at 18:19 GMT_

----

@royair isn't [object](https://github.com/storybooks/storybook-addon-knobs#object) what are you looking for?

**Comment by shilman** [comment]
<a href="https://github.com/royair"><img src="https://avatars3.githubusercontent.com/u/8818555?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [royair](https://github.com/royair)**
_Wednesday Mar 29, 2017 at 18:27 GMT_

----

my options param looks like this:
```
var OPTIONS = [
  {
    eventKey: "1",
    label: "Banana",
    subtext: "they are tasty"
  },
  {
    eventKey: "2",
    label: "Apple",
    subtext: "they are healthy"
  },
  {
    eventKey: "3",
    label: "Peach",
    subtext: "they are beautiful"
  }
];
```

**Comment by mcmunder** [comment]
Is anyone working on this? Seems like such an obvious feature to support?!

**Comment by ndelangen** [comment]
Related: #799 #1296 #805 

I agree this should be addressed, it would make knobs a lot more valuable!

Would you be interested in making a PR @royair @mcmunder ?

**Comment by mcmunder** [comment]
I'll give it a try!

**Comment by ndelangen** [comment]
AWESOME, let me know if there's something I can help with ♥️

**Comment by byrekt** [comment]
I think you can actually just use object to handle an array of objects:
e.g. 
`const footnotes = object('Footnotes', [{symbol: 1, content: 'sample'}]);`

seems to work for me

**Comment by ndelangen** [comment]
@byrekt I can imagine that's good for lots of cases!

**Comment by tibbus** [comment]
You can use it as @byrekt suggest, but React will complain about the types : 
`**Warning**: Failed prop type: Invalid prop **knob.value** of type **array** supplied to **ObjectType**, expected **object**`

A workaround is to create a wrapper component:

```
const optionsWrapper = {
  options: [
    {
      eventKey: '1',
      label: 'Banana',
      subtext: 'they are tasty'
    },
    {
      eventKey: '2',
      label: 'Apple',
      subtext: 'they are healthy'
    },
    {
      eventKey: '3',
      label: 'Peach',
      subtext: 'they are beautiful'
    }
  ]
};

class MyComponentWrapper extends React.Component {
  render() {
    return <Header {...{ ...this.props, options: this.props.optionsWrapper.options }} />;
  }
}

storiesOf('MyComponent', module).add('default', () => {
  return <MyComponentWrapper options={object('options', optionsWrapper)} />
});

```

**Comment by Hypnosphi** [comment]
Yeah, I think we should update the propType

**Comment by vipulbhavsar94** [comment]
@mcmunder Any updates on this, kind of critical thing for me?

**Comment by tibbus** [comment]
@vipulbhavsar94 Should not be critical, you can use my workaround until is fixed.

**Comment by illyon** [comment]
I found another way to make array of objects, don't know if it's a right way. This is an example of story for Socials component, which takes an array of objects with information about each social (name, href) and displays it as list:

```
const socials = [
    {
        name: 'twitter',
        href: 'https://twitter.com/',
    },
    {
        name: 'facebook',
        href: 'https://facebook.com/',
    }
]

const props = {
    socials: [
        object('Twitter', socials[0]),
        object('Facebook', socials[1])
    ]
}

return <Socials {...props} />
```

**Comment by Hypnosphi** [comment]
@illyon nice solution! Works good when you have a fixed set of expected objects

**Comment by Hypnosphi** [comment]
Fixed in 3.2.15

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.45 containing PR #7957 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by HoplaGeiss** [comment]
Naive question - Is this fix also implemented for @storybook/angular?

**Comment by shilman** [comment]
@HoplaGeiss yeah, it's a knob thing, so should be framework-independent
