### ISSUE TITLE
Add option to set the main document title

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#812]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mnmtanish](https://github.com/mnmtanish)**
_Friday Oct 28, 2016 at 05:39 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-options/issues/7_

----

Related issue: https://github.com/kadirahq/react-storybook/issues/581

Add an option to set the storybook-ui page title.

**Comment by shilman** [comment]
<a href="https://github.com/afc163"><img src="https://avatars2.githubusercontent.com/u/507615?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [afc163](https://github.com/afc163)**
_Monday Dec 26, 2016 at 13:15 GMT_

----

+1

**Comment by shilman** [comment]
<a href="https://github.com/TheSisb"><img src="https://avatars0.githubusercontent.com/u/1592327?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheSisb](https://github.com/TheSisb)**
_Wednesday Jan 18, 2017 at 21:43 GMT_

----

+1

**Comment by shilman** [comment]
<a href="https://github.com/bluetidepro"><img src="https://avatars3.githubusercontent.com/u/410701?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bluetidepro](https://github.com/bluetidepro)**
_Wednesday Jan 25, 2017 at 19:35 GMT_

----

+1

**Comment by shilman** [comment]
<a href="https://github.com/vgpena"><img src="https://avatars1.githubusercontent.com/u/1166226?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vgpena](https://github.com/vgpena)**
_Tuesday Jan 31, 2017 at 22:16 GMT_

----

+1

**Comment by shilman** [comment]
<a href="https://github.com/ndelangen"><img src="https://avatars1.githubusercontent.com/u/3070389?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndelangen](https://github.com/ndelangen)**
_Wednesday Apr 12, 2017 at 22:31 GMT_

----

Should be fairly simple to implement, PR welcome!

**Comment by fraedom-jmcmonagle** [comment]
+1

**Comment by philcockfield** [comment]
+1

**Comment by ndelangen** [comment]
It feels like something simple to do right? Has anyone tried to implement this?

Would any of you be interested in giving this a try? @philcockfield @fraedom-jmcmonagle @vgpena @bluetidepro @TheSisb @afc163 ?

**Comment by janmichek** [comment]
This is a simple hack for changing page title, name of the app in heading and favicon.
I know you guys working on new api and I am sorry for hacking your awsome tool, but I didn't found this simple example.

Create 'manager-head.html' in .storybook/ folder with following content:

```
<script>
    document.title = 'My Title';
</script>
<style>
    h3{
        font-size: 0!important;
    }
    h3:after{
        content: "My Styleguide";
        font-size: 12px!important;
    }
</style>
<link rel="icon" type="image/png" href="./img/my-favicon.ico">
```

**Comment by ndelangen** [comment]
no worries, we added the `manager-head.html` as an escape-hatch also.

If you're changing the name storybook, you can do this via the [addon-options](https://github.com/storybooks/storybook/tree/master/addons/options#getting-started)

**Comment by ndelangen** [comment]
#952

**Comment by ndelangen** [comment]
Strictly speaking this is fixed, we will implement #866 which I think will be what 99% of users want.

**Comment by chvin** [comment]
'overwritten by Storybook' solution:

``` js
// .storybook/manager.js
import './titleAddon';
```

``` js
// .storybook/titleAddon.js
import addons from '@storybook/addons'
import { STORY_RENDERED } from '@storybook/core-events'

addons.register('TitleAddon', api => {
  const cunstomTitle = 'abc'; // Define your customTitle title
  let interval = null;
  const setTitle = () => {
    clearTimeout(interval);
    let storyData = null;
    try {
        storyData = api.getCurrentStoryData(); // Some time get error
    } catch(e) {}
    let title;
    if (!storyData) {
        title = cunstomTitle;
    } else {
        title = `${storyData.kind} - ${storyData.name} ⋅ ${cunstomTitle}`
    }
    if (document.title !== title) { // As few dom operations as possible
        document.title = title;
    }
    interval = setTimeout(setTitle, 100);
  };
  setTitle();
  api.on(STORY_RENDERED, story => {
    setTitle();
  })
});
```

**Comment by steffchep** [comment]
#866 isn't quite what this issue is about. Also, it's still open as well. :(

**Comment by Flcwl** [comment]
why don't open title custom?

**Comment by juji** [comment]
> 'overwritten by Storybook' solution:
> 
> ```js
> // .storybook/manager.js
> import './titleAddon';
> ```
> 
> ```js
> // .storybook/titleAddon.js
> import addons from '@storybook/addons'
> import { STORY_RENDERED } from '@storybook/core-events'
> 
> addons.register('TitleAddon', api => {
>   const cunstomTitle = 'abc'; // Define your customTitle title
>   let interval = null;
>   const setTitle = () => {
>     clearTimeout(interval);
>     let storyData = null;
>     try {
>         storyData = api.getCurrentStoryData(); // Some time get error
>     } catch(e) {}
>     let title;
>     if (!storyData) {
>         title = cunstomTitle;
>     } else {
>         title = `${storyData.kind} - ${storyData.name} ⋅ ${cunstomTitle}`
>     }
>     if (document.title !== title) { // As few dom operations as possible
>         document.title = title;
>     }
>     interval = setTimeout(setTitle, 100);
>   };
>   setTitle();
>   api.on(STORY_RENDERED, story => {
>     setTitle();
>   })
> });
> ```

This is one without `seTimeout`

```javascript
import { STORY_RENDERED, STORY_CHANGED, STORY_SPECIFIED } from '@storybook/core-events'

// .storybook/titleAddon.js
addons.register('TitleAddon', api => {

  const customTitle = 'JujiDocs'; // Define your customTitle title
  
  const setTitle = () => {
  
    let storyData = null;
    
    try {
        // @ts-ignore
        storyData = api.getCurrentStoryData(); // Some time get error
    } catch(e) {}
    
    let title;
    
    if (!storyData) {
        title = customTitle;
    } else {
      // @ts-ignore
      title = `${storyData.title} ⋅ ${customTitle}`
    }
    
    if (document.title !== title) { // As few dom operations as possible
        document.title = title;
    }

  };

  setTitle();
  api.on(STORY_RENDERED, story => { 
    console.log('STORY_RENDERED')
    setTitle(); 
  })
  api.on(STORY_CHANGED, story => { 
    console.log('STORY_CHANGED')
    setTitle(); 
  })
  api.on(STORY_SPECIFIED, story => { 
    console.log('STORY_SPECIFIED')
    setTitle(); 
  })
  

});
```

Thank you @chvin for the example
