### ISSUE TITLE
React Native: Null channel with `addon-options`

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#815]
<a href="https://github.com/inyono"><img src="https://avatars2.githubusercontent.com/u/1508477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [inyono](https://github.com/inyono)**
_Tuesday Mar 28, 2017 at 16:02 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-options/issues/15_

----

I'm failing to get this to work with React Native (and create-react-native-app). After following the README, I get the error `null is not an object (evaluating 'channel.emit')` @ `setOptions`.

storybook/addons.js
```.js
import '@kadira/react-native-storybook/addons';
import '@kadira/storybook-addon-options/register';
```

storybook/index.js
```.js
import './addons';

import { NativeModules } from 'react-native';
import { getStorybookUI, configure } from '@kadira/react-native-storybook';
import url from 'url';

import { setOptions } from '@kadira/storybook-addon-options';

setOptions({
    name: 'CUSTOM-OPTIONS',
    url: 'https://github.com/kadirahq/storybook-addon-options',
    goFullScreen: false,
    showLeftPanel: false,
    showDownPanel: false,
    showSearchBox: false,
    downPanelInRight: false,
    sortStoriesByKind: false,
});

configure(
  () => {
    require('./stories');
  },
  module
);

const { hostname } = url.parse(NativeModules.SourceCode.scriptURL);

export default getStorybookUI({ port: 19001, host: hostname });
```

Any idea, what the problem might be?

**Comment by simply-innovative** [comment]
@shilman @mthuret : I am also running into the same problem, can you please help us on this. Based on README it is supported on rn storybook, not sure why we ending up with this error.

plz let us know in case you have any updates

**Comment by inyono** [comment]
Funny, I'm currently testing out Storybook 3 Alpha and run into this problem again ^^. Although, according to https://github.com/storybooks/storybook/tree/v3.0.0-alpha.5/addons/options it should work with React Native. So yeah, still a problem with `@storybook/addon-options` at version 3.0.0-alpha.0.

**Comment by shilman** [comment]
@inyono Thanks so much for testing this out! Your help is much appreciated (and great Medium post too!). If you're able to figure something out here, a PR would be much appreciated. 🥇 👍 ❤️ 

NOTE, the latest NPM-published version is `alpha.4` not `alpha.5`. it's a little confusing and i'm currently trying to rectify that 😉

**Comment by pranavrajsinghchauhan** [comment]
we are also running into the same issue, any help would be much appreciated

Stack:
- Storybook 3
- RN 0.45.0.rc-2

**Comment by shilman** [comment]
@inyono @pranavrajsinghchauhan Can you check to see if there are two instances of the `addon-options` package somewhere underneath your `node_modules` directory?

**Comment by inyono** [comment]
@shilman Doesn't seem like it:
```
find node_modules -type d -name 'addon-options'
node_modules/@storybook/addon-options
```

Reproducible example: https://github.com/serlo-org/serlo-abc/tree/addon-options

**Comment by shilman** [comment]
@inyono 👍 for the repro! I will check it out and let you know what I find. (cc @tmeasday )

**Comment by tmeasday** [comment]
Hi @inyono! Thanks for the reproduction. How do I run it? I tried `npm start` or running storybook, but it seems to not quite work correctly (I don't see any errors anyway).

**Comment by tmeasday** [comment]
@shilman does `@storybook/react-native` not depend on `addons`?:

![screenshot 2017-06-05 12 09 30](https://cloud.githubusercontent.com/assets/132554/26767992/f33d5398-49e7-11e7-95f2-91713aa2703b.png)

**Comment by tmeasday** [comment]
Hmm, maybe you can't trust `npm list` then: https://github.com/storybooks/storybook/blob/master/app/react-native/package.json#L39

Sigh 
![screenshot 2017-06-05 12 14 12](https://cloud.githubusercontent.com/assets/132554/26768065/8356d0e4-49e8-11e7-8426-cab141625778.png)

**Comment by tmeasday** [comment]
Alright, the issue wasn't anything to do with `node_modules`, that was a bit of a furphy.

**Comment by tmeasday** [comment]
Ok, this issue is more succinctly explained by https://github.com/storybooks/storybook/issues/1192. @inyono the best current workaround is a `setTimeout`, as far as we can tell.

I'm going to make a better error message for the options addon until we resolve the underlying issue (https://github.com/storybooks/storybook/issues/1191).

**Comment by ndelangen** [comment]
@tmeasday Do we need to keep this issue open then?

**Comment by tmeasday** [comment]
I guess not. It might be useful to have the issue open for people searching for it?

**Comment by ndelangen** [comment]
#1514

**Comment by tmeasday** [comment]
And #1515
