### ISSUE TITLE
Error using storyshots

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#816]
<a href="https://github.com/fdaciuk"><img src="https://avatars1.githubusercontent.com/u/487669?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fdaciuk](https://github.com/fdaciuk)**
_Thursday Apr 13, 2017 at 23:11 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-options/issues/17_

----

I'm using [storybook-readme](https://github.com/tuchk4/storybook-readme) and storyshots on my project. When I try to run `storyshots -c storybook` on terminal, I get this error:

```terminal
TypeError: Cannot read property 'emit' of null
    at setOptions (/code/my-project/node_modules/@kadira/storybook-addon-options/dist/preview/index.js:27:10)
    at evalmachine.<anonymous>:20:39
    at runWithRequireContext (/code/my-project/node_modules/@kadira/storyshots/dist/require_context.js:104:3)
    at _callee$ (/code/my-project/node_modules/@kadira/storyshots/dist/cli.js:29:43)
    at tryCatch (/code/my-project/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/code/my-project/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/code/my-project/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/code/my-project/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /code/my-project/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/code/my-project/node_modules/core-js/library/modules/_export.js:35:28)
error Command failed with exit code 1.
error Command failed with exit code 1.
```

My storybook config files (click to open):
<details>
<summary>config.js</summary>

```js
import { configure, addDecorator, setAddon } from '@kadira/storybook'
import GithubCorner from '@personare/react-storybook-decorator-github-corner'
import InfoAddon from '@kadira/react-storybook-addon-info'
import { setOptions } from '@kadira/storybook-addon-options'

addDecorator(GithubCorner)
setAddon(InfoAddon)

setOptions({ downPanelInRight: true })

const req = require.context('../src/components', true, /\.story\.js$/)

function loadStories () {
  req.keys().forEach((filename) => req(filename))
}

configure(loadStories, module)
```

</details>

<details>
<summary>addons.js</summary>

```js
import '@kadira/storybook/addons'
import '@kadira/storybook-addon-options/register'
import 'storybook-readme/register'
```

</details>

---

Any ideas?

cc @mnmtanish @arunoda

**Comment by ChrisHaPunkt** [comment]
Got the same error.
For me the issue was the upgrade from `babel-loader 6.4.1` to `babel-loader 7.0.0`.

After reverted to `6.4.1` every used addons works fine again.

**Comment by fdaciuk** [comment]
@ChrisHaPunkt I'm using `babel-loader@6.2.10`. I've tried to install `babel-loader@6.4.1` and `7.0.0`, but no success :disappointed: :thinking:

**Comment by enjoylife** [comment]
I'm running into the same issue for all addons. From what I can tell, it looks like none of the  addons `addons.register`  are being called. [For example the action addon](https://github.com/storybooks/storybook/blob/master/addons/actions/src/manager.js#L7).

...Going in further to the dist and src folder inside of the node_modules...  I see that the singleton behavior of `AddonStore` is not being respected.

What happens is that when addons.js runs the addons are added to one instance of the store. and then during the [react render](https://github.com/storybooks/storybook/blob/a9944e1533de79ce4a1a2fd8d2b25aa450998147/app/react/src/client/manager/provider.js#L37) another instance is being populated.

During addons.js -> `node_modules\@storybook\addons\dist\index.js`
During ReactProvider -> `node_modules\@storybook\addons\src\index.js`
