### ISSUE TITLE
Disable when globally

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#825]
<a href="https://github.com/lucasconstantino"><img src="https://avatars1.githubusercontent.com/u/2688512?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lucasconstantino](https://github.com/lucasconstantino)**
_Friday Nov 18, 2016 at 19:53 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-decorator-centered/issues/5_

----

Is there anyway to enable this globally but allow for disabling on a given story?

**Comment by shilman** [comment]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnmtanish](https://github.com/mnmtanish)**
_Saturday Nov 19, 2016 at 02:00 GMT_

----

Try wrapping your story with a div like this:

```
<div style={{ flex: 1 }}>
  // story
</div>
```

NOTE: I haven't this yet so maybe this will need a few tweaks to work well.

**Comment by shilman** [comment]
Closing this for now! Please re-open if this is still a problem!

**Comment by Billy-** [comment]
I would like this feature. It should be possible for any decorator...

**Comment by techieshark** [comment]
The suggested workaround from April 2017 seems to no longer work. 

Given these styles:
https://github.com/storybooks/storybook/blob/fae0ff5b53bd32e9db89d551c48638eddbf814af/addons/centered/src/styles.js

The parent sets `display: flex` but there's an inner container between that and the story, and yet "The scope of a flex formatting context is limited to a parent/child relationship." - https://stackoverflow.com/a/37844240/1024811

Thus, setting `flex: 1` on a grandchild of `display: flex` won't work.

**Comment by techieshark** [comment]
Would it be possible to disable through same mechanism as available with addon-info?

Like so:
```
storiesOf('MyComponent', module)
    .addParameters({ centered: { disable: true }, info: { disable: true }})
```

**Comment by seleckis** [comment]
Would be great to have this. E.g. I have need a wrapper with paddings for the most of components, but some of them should go without padding. Any suggestion?

**Comment by michelcve** [comment]
@shilman is it possible to reopen? The original workaround doesn't seem to work anymore, and it would be nice if the property "centered: { disable: true}" would work when it's enabled globally.

**Comment by shilman** [comment]
Seems like it's already implemented?

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/addon-centered.stories.js#L19-L25

**Comment by michelcve** [comment]
I'm using it with angular, and it doesn't seem to do anything for me when I set props "centered: { disable: true }".

But perhaps this is an angular specific bug then?

**Comment by michelcve** [comment]
I'm sorry, it does work. I actually made 2 mistakes:

1) I mistakenly added it to th 'props' section, instead of the 'parameters' section
2) It should be in the 'export default {}' and not in the 'export primary = () => {}'

**Comment by lgcantarelli** [comment]
The case where a global decorator could be overriden or disabled in a given story makes a lot of sense to me.

**Comment by shilman** [comment]
Storybook layout parameter is the recommended way to do this and can be overridden

https://storybook.js.org/docs/react/configure/story-layout
