### ISSUE TITLE
Hook on leaveing a story

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#845]
<a href="https://github.com/linonetwo"><img src="https://avatars2.githubusercontent.com/u/3746270?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [linonetwo](https://github.com/linonetwo)**
_Monday Jan 16, 2017 at 02:53 GMT_
_Originally opened as https://github.com/storybooks/react-native-storybook/issues/120_

----

Some component will change Orientation of device, so seems that we need a hook to revert the changing of Orientation on leaving a story.

**Comment by shilman** [comment]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnmtanish](https://github.com/mnmtanish)**
_Sunday Jan 22, 2017 at 15:29 GMT_

----

I think we should be able to do this with a decorator. The basic idea is to wrap the story with a component and run the hook function on `componentWillUnmount`

```js
storiesOf('Button', module)
  .addDecorator(storyHook({
    componentWillUnmount() {
      // reset screen orientation
    }
  }))
  .add('story - 1', () => (
    <pre>STORY_1</pre>
  ))
```

**Comment by shilman** [comment]
<a href="https://github.com/linonetwo"><img src="https://avatars2.githubusercontent.com/u/3746270?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [linonetwo](https://github.com/linonetwo)**
_Sunday Jan 22, 2017 at 16:00 GMT_

----

That would be much more easy to use. I'm currently having to use redux to do this clean up work for every component.

```javascript
storiesOf('LineChart', module)
  .addDecorator((getStory) => {
    const store = getNewStore();
    const token = 'e77b3f75-1daa-4ded-b52a-7bbd65f758f5';
    store.dispatch(STORYBOOK.request({ orientation: 'landscape' }));
    store.dispatch(LOGIN.request({ token, jump: false }));
    Orientation.lockToLandscape();
    Promise.delay(2000)
    .then(() => {
      store.dispatch(LOAD_LINE_CHART.request({ areaType: 'Company', jump: false }));
    });
    return (
      <Provider store={store}>
        {getStory()}
      </Provider>
    );
  })
  .add('initial', () => (
    <LineChart areaType="Company" />
  ));

```

Where ```STORYBOOK.request({ orientation: 'landscape' })``` is an action creator for informing redux to do something special for storybook. If I don't pass ```orientation: 'landscape'``` to it, it will reset the orientation.

**Comment by ndelangen** [comment]
https://github.com/storybooks/storybook/issues/845#issuecomment-294300891 sounds like an acceptable solution?

Please re-open if you still experience this problem 👍
