### ISSUE TITLE
ios device "websocket: connection error"

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#846]
<a href="https://github.com/rohit-ravikoti"><img src="https://avatars2.githubusercontent.com/u/16107563?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rohit-ravikoti](https://github.com/rohit-ravikoti)**
_Wednesday Feb 08, 2017 at 21:19 GMT_
_Originally opened as https://github.com/storybooks/react-native-storybook/issues/122_

----

Hi,
I'm not sure if this functionality is supported, but when I try to run the app on a real ios device, I get the following error:
```
2017-02-08 13:18:52.831 [error][tid:com.facebook.react.JavaScript] 'websocket: connection error', 'The operation couldn’t be completed. Connection refused'
2017-02-08 13:18:52.865 [error][tid:com.facebook.react.JavaScript] 'websocket: connection closed', undefined, undefined
```

**Comment by shilman** [comment]
<a href="https://github.com/admmasters"><img src="https://avatars0.githubusercontent.com/u/335607?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [admmasters](https://github.com/admmasters)**
_Thursday Mar 02, 2017 at 22:59 GMT_

----

E

**Comment by shilman** [comment]
<a href="https://github.com/chrismcleod"><img src="https://avatars2.githubusercontent.com/u/1134683?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrismcleod](https://github.com/chrismcleod)**
_Saturday Mar 04, 2017 at 21:20 GMT_

----

@rohit-ravikoti 
This is because react native uses "localhost" as the default port for the packager.  This doesn't work for react native storybook.  I'm guessing because it expects that the storybook server is running on the same host as the packager.  However, the storybook host is not on the ios device, it is on your development computer.  So, replace all the localhost references with your computer's internal IP address.  That can be found by going to **System Settings > Network**.

If your internal ip address is 10.0.1.16:

open your react native project with XCode and go to: 
_ProjectName_ > Libraries > RCTWebSocket.xcodeproj > RCTWebSocketExecutor.m

got to the method - (void)setUp and (toward the top) change 
`host = @"localhost"` to `host = @"10.0.1.16"`.

![image](https://cloud.githubusercontent.com/assets/1134683/23582355/f079e61e-00ed-11e7-9aa5-6746efb076d0.png)

create storybook like this:
`const StorybookUI = getStorybookUI({ port: 7007, host: "10.0.1.16" });`

start it like this:
`npm run storybook -- -h 10.0.1.16`

After making all the changes, I'd probably close all simulators, stop all packagers and close the app on the phone.

**Comment by notgiorgi** [comment]
Isn't there some more general approach? So that the whole team won't have to do that separately?

**Comment by Sonblind** [comment]
I'm on CRNA, so XCode is not an option without ejecting. It would be great to have an alternative solution

**Comment by chmaltsp** [comment]
This would be amazing to have in some kind of build step when running the packager.

**Comment by ndelangen** [comment]
Would any of you be able to open a PR for this @notgiorgi @Sonblind @chmaltsp ?

**Comment by chmaltsp** [comment]
@ndelangen I could give it a shot, but I'm unsure of how to inject into the local IP into `RCTWebSocketExecutor.m`

**Comment by devtanc** [comment]
This is still an issue. I was able to fix with the suggestions, but it's not going to work as either a long-term fix, or a fix for a team of developers.

**Comment by rdewolff** [comment]
Yeah this this issue isn't resolved, should be left open until resolved. The provided solution is an (ugly) workaround.

**Comment by hariDasu** [comment]
this issue should remain open. until this is resolved I find it impractical to use storybook in an RN application. the "speed to development" promise of storybook is greatly reduced by this arduous and time consuming process.

**Comment by shilman** [comment]
@benoitdion not sure if you've seen this...

**Comment by Gongreg** [comment]
Currently you have an option to pass host as a param to getStorybookUI. It is a lot better solution than the one recommended here. Later on we could try to implement some screen to allow user to insert custom IP, but for now it should work. I am closing this issue and opening a feature request.
