### ISSUE TITLE
RelayQL: Unexpected invocation ...

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#847]
<a href="https://github.com/slicejunk"><img src="https://avatars3.githubusercontent.com/u/5887100?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [slicejunk](https://github.com/slicejunk)**
_Wednesday Mar 15, 2017 at 15:33 GMT_
_Originally opened as https://github.com/storybooks/react-native-storybook/issues/131_

----

when use with babel-relay-plugin-loader.
this happens even when the .babelrc is copied into the storybook/ directory.

Any workaround?

**Comment by danielduan** [comment]
Old bug, not sure if it's still relevant. Please reopen if it still exists on the latest builds.
