### ISSUE TITLE
how to debug app

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#848]
<a href="https://github.com/salmon002"><img src="https://avatars1.githubusercontent.com/u/15521495?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [salmon002](https://github.com/salmon002)**
_Thursday Mar 30, 2017 at 00:55 GMT_
_Originally opened as https://github.com/storybooks/react-native-storybook/issues/133_

----

  how can i debug my app. For example, how to print debug info in browser？

**Comment by ndelangen** [comment]
You can use `debugger;` `break-points` and `console.log()` inside the `add` function or inside your components, and open the web dev tools.
