### ISSUE TITLE
Expose an API to get and set URL queryParams.

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#863]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arunoda](https://github.com/arunoda)**
_Thursday Aug 11, 2016 at 06:22 GMT_
_Originally opened as https://github.com/storybooks/storybook-ui/issues/25_

----

With that, addons can use it as a data store (or a way to save preferences).

**Comment by shilman** [comment]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnmtanish](https://github.com/mnmtanish)**
_Friday Sep 02, 2016 at 08:23 GMT_

----

I think we can close this issue

**Comment by shilman** [comment]
<a href="https://github.com/ndelangen"><img src="https://avatars1.githubusercontent.com/u/3070389?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndelangen](https://github.com/ndelangen)**
_Wednesday Mar 15, 2017 at 08:39 GMT_

----

This exists

**Comment by UsulPro** [comment]
It was added in `storybook-addons`
