### ISSUE TITLE
It's great if we can expose an API to addons to register shortcuts.

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#865]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arunoda](https://github.com/arunoda)**
_Friday Aug 12, 2016 at 12:27 GMT_
_Originally opened as https://github.com/storybooks/storybook-ui/issues/27_

----

This will be a killer feature.
But people can abuse this feature, so we need to see how Atom do this.

**Comment by bernard-lin** [comment]
What kind of shortcuts would we be looking at? Or just the availability of creating your own?

**Comment by ndelangen** [comment]
#1209 Will be part of api-v2
