### ISSUE TITLE
Improve Story Index

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#870]
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philcockfield](https://github.com/philcockfield)**
_Thursday Nov 24, 2016 at 19:53 GMT_
_Originally opened as https://github.com/storybooks/storybook-ui/issues/63_

----

I'd like to write a better index panel that can better handle larger projects and libraries, and provide more sophisticated organisation options for stories.

![image](https://cloud.githubusercontent.com/assets/185555/20609035/89ba9008-b2ec-11e6-9fc1-11d87c3ad986.png)

Is there a pluggable way to do this.  Can I write this as an external module, and have it dropped in using a known set of properties that get passed to it.  (I'd like to write it in Typescript).  Or do I have to hack it out within this repo?

Please let me know options - and how pluggable UI want to make the Storybook?  Thanks.

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Friday Nov 25, 2016 at 02:17 GMT_

----

Currently, it's not pluggable and with current state, I think it's hard to do so. Since it's a core component of storybook.

Anyway, I think there's a huge opportunity for an improvement. So, I'd like to see it lands to the core.
If that's kind a impossible, let's try to make it pluggable.

**Comment by shilman** [comment]
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philcockfield](https://github.com/philcockfield)**
_Friday Nov 25, 2016 at 05:17 GMT_

----

OK, I think I'll draw up some designs.  I have some ideas that allows for clean, nested organization of stories that would not change the `storiesOf` data structure at all.

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Friday Nov 25, 2016 at 05:24 GMT_

----

Awesome.

**Comment by shilman** [comment]
<a href="https://github.com/benediktvaldez"><img src="https://avatars1.githubusercontent.com/u/1928103?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [benediktvaldez](https://github.com/benediktvaldez)**
_Sunday Apr 02, 2017 at 01:00 GMT_

----

@philcockfield did you ever get any further with those designs? really excited to see something like this happen

**Comment by shilman** [comment]
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philcockfield](https://github.com/philcockfield)**
_Monday Apr 03, 2017 at 20:05 GMT_

----

Hey @benediktvaldez - I haven't pushed that forward yet.  What's the future of Storybook looking like (before I invest time)?

**Comment by shilman** [comment]
<a href="https://github.com/ndelangen"><img src="https://avatars1.githubusercontent.com/u/3070389?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndelangen](https://github.com/ndelangen)**
_Monday Apr 03, 2017 at 22:05 GMT_

----

Hey Phil,
I think storybooks future looks pretty bright, recently quite a few people stepped forward to maintain the packages, and we're making a lot of progress getting ready for the 3.0.0 release.
It will contain an upgrade to webpack 2, which will help a lot of people out.

We'd love to hear your ideas for designs, make people even happier?

**Comment by shilman** [comment]
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philcockfield](https://github.com/philcockfield)**
_Tuesday Apr 04, 2017 at 20:03 GMT_

----

OK, cool - that's encouraging.  I'll look to put something together ASAP.

**Comment by ndelangen** [comment]
Hey @philcockfield if you need any help or want to brainstorm your idea's you're very welcome on our slack!

**Comment by philcockfield** [comment]
@ndelangen - sweet.  I've just joined the Slack channel.  Apologies haven't had a chance to look at this yet, but am finding some time now.  Before I dive in, has there been any changes to the index for Version 3?  Or is this still in the same place?

Thanks

**Comment by UsulPro** [comment]
Hi @philcockfield!
There're PRs related to the stories panel: https://github.com/storybooks/storybook/pull/981 https://github.com/storybooks/storybook/pull/908
and some discussions about API improvement: https://github.com/storybooks/storybook/issues/993 https://github.com/storybooks/storybook/issues/151

If this work is going to include nesting/hierarchy of stories, can we discuss it (maybe on our slack)?

**Comment by ndelangen** [comment]
Considering we have multiple issues related to this, and you people are now working together on making a awesome proposal, I think we can close this one, so there's a single place where we can report progress.

🤝
