### ISSUE TITLE
Can't perform shortcut when input is focused

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#871]
<a href="https://github.com/willowcheng"><img src="https://avatars0.githubusercontent.com/u/6239076?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [willowcheng](https://github.com/willowcheng)**
_Wednesday Apr 12, 2017 at 04:15 GMT_
_Originally opened as https://github.com/storybooks/storybook-ui/issues/81_

----

In #60, it was discussed to fix the bug as `⌘ ⇧ →` and `⌘ ⇧ ←` would trigger shortcut if `<input>` is focused. Along with the fix, it would also remove part of functionality of shortcut. Check this [repo](https://github.com/willowcheng/storybook-ui/tree/demo-shortcus-for-input) for minimal reproducing with auto focused `<input>`.

The first time I got into trouble was using shortcut to toggle search box, I couldn't dismiss it until it's unfocused.

**Comment by Hypnosphi** [comment]
I think it's OK to keep disabling shortcuts when some input is focused. The issue with search box is quite annoying though. We can allow dismissing it with Esc key and/or outside click. Maybe we could use ReactModal like it's done in shortcuts_help. "Toggle Search Box" should be renamed into "Show Search Box" in that case.
