### ISSUE TITLE
Toggle Full Screen Mode shortcut for Mac doesn't work

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#872]
<a href="https://github.com/willowcheng"><img src="https://avatars0.githubusercontent.com/u/6239076?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [willowcheng](https://github.com/willowcheng)**
_Thursday Apr 13, 2017 at 02:50 GMT_
_Originally opened as https://github.com/storybooks/storybook-ui/issues/82_

----

`⌘ ⇧ F` would cause error shown in below and doesn't work, while `⌃ ⇧ F` works properly. Can be reproduced by HEAD commit of current master branch.

<img width="1276" alt="screen shot 2017-04-12 at 10 42 23 pm" src="https://cloud.githubusercontent.com/assets/6239076/24988140/05eeae32-1fd2-11e7-80bf-3cc3a7e69715.png">

**Comment by willowcheng** [comment]
Follow up with the issue, I found `⌘ ⇧ F` works now to toggle fullscreen mode, but Go FullScreen button in the example would fail as shortcut is simulated where `e.target` is not defined.

Can be reproduced by c9afedc.
