### ISSUE TITLE
Add NODE_PATH support

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#873]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arunoda](https://github.com/arunoda)**
_Tuesday Oct 04, 2016 at 14:00 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/32_

----

We added NODE_PATH support to React Storybook where you can import modules directly inside the app.

So, we should add it to storyshots too.
See: https://github.com/kadirahq/react-storybook/pull/528

**Comment by ndelangen** [comment]
Looks like this was merged?
