### ISSUE TITLE
TypeError: w.default.findDOMNode is not a function

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#876]
<a href="https://github.com/ericclemmons"><img src="https://avatars3.githubusercontent.com/u/15182?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericclemmons](https://github.com/ericclemmons)**
_Tuesday Nov 29, 2016 at 20:49 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/58_

----

When testing with , I get the following error for anything wrapped by a `@componentQueries` (which uses https://github.com/ctrlplusb/react-sizeme):

```
  TypeError: w.default.findDOMNode is not a function
      at i.m.value (/Users/Eric/Projects/HigherEducation/platform/node_modules/react-sizeme/lib/react-sizeme.js:1:3247)
      at i.m.value (/Users/Eric/Projects/HigherEducation/platform/node_modules/react-sizeme/lib/react-sizeme.js:1:2901)
      at /Users/Eric/Projects/HigherEducation/platform/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (/Users/Eric/Projects/HigherEducation/platform/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at /Users/Eric/Projects/HigherEducation/platform/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (/Users/Eric/Projects/HigherEducation/platform/node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/Eric/Projects/HigherEducation/platform/node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.TransactionImpl.closeAll (/Users/Eric/Projects/HigherEducation/platform/node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.TransactionImpl.perform (/Users/Eric/Projects/HigherEducation/platform/node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (/Users/Eric/Projects/HigherEducation/platform/node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
```

I assume that I need to mock the DOM node somehow?
> http://stackoverflow.com/questions/40852131/refs-are-null-in-jest-snapshot-tests-with-react-test-renderer/40854433#40854433
> https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing

Has anyone else had issues with testing out DOM-dependent components like this?

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Wednesday Nov 30, 2016 at 02:14 GMT_

----

cc @roonyh

**Comment by shilman** [comment]
<a href="https://github.com/jasonmorganson"><img src="https://avatars0.githubusercontent.com/u/128727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jasonmorganson](https://github.com/jasonmorganson)**
_Wednesday Dec 07, 2016 at 19:53 GMT_

----

In React@v15.4.0 `create` takes an extra argument to provide mocked refs.

This looks like the place to pass it in: https://github.com/storybooks/storyshots/blob/master/src/test_runner/snapshot_runner.js#L60

Still need a good way to pass the mock into the story though. Maybe something like:

```javascript
function createNodeMock (element) {
  if (element.type === 'p') {
    return {};
  }
  return null;
}
const options = {createNodeMock}

storiesOf('Foo', module)
  .add('default state', () => (
    <Foo />
  ), options)
```

For that to work [`react-storybook`](https://github.com/storybooks/react-storybook) will have to store the `options` on the story.

Then line 60 could pass the node mock in:
```javascript
const {createNodeMock} = story.options
const renderer = ReactTestRenderer.create(tree, createNodeMock)
```

**Comment by theinterned** [comment]
I made PR on the old storyshots repo that resolve this issue: https://github.com/storybooks/storyshots/pull/98

**Comment by tmeasday** [comment]
It's now possible to set a (admittedly global) `createNodeMock` via the storyshots [`test` option](https://github.com/storybooks/storybook/tree/master/addons/storyshots#test).

Obviously people will probably want to do it per-test, which is probably better described by the dupe issue https://github.com/storybooks/storybook/issues/881. Let's have the discussion there, closing this.

**Comment by renanvalentin** [comment]
Hey guys, I'm having the same problem but I'm stuck with the old version:

```
    "@kadira/storybook": "^2.35.3",
    "@kadira/storyshots": "^2.1.0"
```

Do you have any suggestions?

**Comment by tmeasday** [comment]
Hmm, I don't really think there's any way to get around it in the old storyshots. You could do something hacky like monkey patch `ReactTestRenderer.create`?

**Comment by renanvalentin** [comment]
@tmeasday thanks for the tip!! It seems that my problem is related to jsdom:

https://github.com/airbnb/react-dates/issues/528

**Comment by renanvalentin** [comment]
I've solved it by patching `ReactDOM` and `ReactTestRenderer`:
https://gist.github.com/renanvalentin/0472aa5ac4769ce5ec1b2f91f60e78fc
