### ISSUE TITLE
Show storyshots in UI

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#878]
<a href="https://github.com/SpaceK33z"><img src="https://avatars1.githubusercontent.com/u/533616?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SpaceK33z](https://github.com/SpaceK33z)**
_Tuesday Dec 06, 2016 at 11:12 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/60_

----

It would be great if the storyshot tests were visible in the Storybook UI, like [storybook-addon-specifications](https://github.com/mthuret/storybook-addon-specifications). At the moment the storyshots are not in the same "development flow", because you have to open your terminal each time to see the storyshots.

A next step would be to have a button you can click to update the storyshot if it failed.

I *might* be able to work on this during the holidays. Just to start of the discussion, how could I implement this (roughly)?

The current idea I have is to hook into the Storybook server (which should be possible since https://github.com/storybooks/react-storybook/pull/435) and install a WebSocket. Storyshots would use this WebSocket to push the failed / successful storyshots. On the client, there is [storybook-channel-websocket](https://github.com/storybooks/storybook-channel-websocket) to listen / push things to the WebSocket.

Or would it be cleaner to make a separate addon for this? I think all storyshots users would want this, so that's why I'm leaning towards adding it in storyshots at the moment.

**Comment by ndelangen** [comment]
Check this out, if you want to work on it:
https://github.com/mthuret/storybook-addon-specifications/commits/jest-test-files
