### ISSUE TITLE
.addDecorator is probably not working

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#879]
<a href="https://github.com/kitze"><img src="https://avatars3.githubusercontent.com/u/1160594?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kitze](https://github.com/kitze)**
_Friday Dec 23, 2016 at 23:37 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/68_

----

I'm using material-ui in my project for some of the components. The components that are not affected by material-ui and don't need muiTheme pass the tests. But the other components that need muiTheme provided by context, are failing with a warning ```Warning: Failed context type: The context `muiTheme` is marked as required in `CircularProgress`, but its value is `undefined`.```

Keep in mind that the stories in storybook are fine because I'm providing muiTheme through a decorator like this in my global .storybook/config.js file:

```
addDecorator(story => wrapWithStyles(story()));
addDecorator(story => wrapWithMui(story()));
```

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Saturday Dec 24, 2016 at 00:07 GMT_

----

@roonyh what do you think about this issue?

**Comment by shilman** [comment]
<a href="https://github.com/roonyh"><img src="https://avatars3.githubusercontent.com/u/3872221?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [roonyh](https://github.com/roonyh)**
_Tuesday Dec 27, 2016 at 05:21 GMT_

----

@kitze I am taking a look. `addDecorator` works with simple wrappers but I guess something does not work with `context`. Have you used storyshots `2.x` versions successfully with your stories?

**Comment by shilman** [comment]
<a href="https://github.com/fredantell"><img src="https://avatars0.githubusercontent.com/u/5240507?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fredantell](https://github.com/fredantell)**
_Sunday Feb 26, 2017 at 17:18 GMT_

----

I'm running into the same issue. I have a <ContextProvider /> component I specifically created for testing. I can use a global addDecorator and it works fine with storybooks. Then when I run storyshot via jest it fails trying to find functions that should have been injected via context.

If I use addDecorator on a per story level it works fine in both storybooks and storyshots.
Similarly if I just wrap each story directly in the <ContextProvider /> component that also works fine for both storybook and storyshots.

**Comment by shilman** [comment]
<a href="https://github.com/jacobk"><img src="https://avatars3.githubusercontent.com/u/497477?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jacobk](https://github.com/jacobk)**
_Friday Mar 24, 2017 at 09:46 GMT_

----

I have this issue too with storyshots `3.2.2`.

**Comment by RussMax783** [comment]
I have the same issue, Im using Styled Components and add the <ThemeProvider> to all the stories with the addDecorator. but the storyshots don't work when i use something like the withTheme component. 

Any update on this?   Using the v3

**Comment by tmeasday** [comment]
@RussMax783 can we get a reproduction of this? It sounds similar to #877, which I failed to reproduce. Would love to get a [reproduction](https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#reproductions) going!

**Comment by ktj** [comment]
Here is a reproduction:
https://github.com/ktj/storybook-rp

Run:
```yarn```
```yarn test```

**Comment by tmeasday** [comment]
Thanks @ktj that's great!

**Comment by mattleff** [comment]
I can fix the repro @ktj provided with the following [diff](https://github.com/ktj/storybook-rp/blob/master/.storybook/config.js#L6-L10):

![image](https://user-images.githubusercontent.com/120155/28251114-b2a501ca-6a33-11e7-84db-ebacb9fac7db.png)

This ensures that `addDecorator` is called before the stories are loaded.

**Comment by tmeasday** [comment]
I'm guessing just moving the `addDecorator` line above the `require.context` line should work too, no?

This seems like a documentation problem more than anything. Perhaps the global `addDecorator` should log a warning if a story has already been registered, as this is unlikely to be what you want?

**Comment by mattleff** [comment]
> I'm guessing just moving the addDecorator line above the require.context line should work too, no?

Yup, that has the same affect. I'd be game for logging a warning: it would have saved me a ton of time debugging this.

**Comment by tmeasday** [comment]
@mattleff keen to try sending a PR?

**Comment by mattleff** [comment]
@tmeasday Sure, I'll try to send one in the next couple days.

**Comment by mattleff** [comment]
@shilman Can this issue be closed now?

**Comment by tmeasday** [comment]
I'll mark it `merged` and we'll close it when it gets released (soon!)

**Comment by UsulPro** [comment]
is it really solved?

**Comment by UsulPro** [comment]
yep, we faced this here https://github.com/react-theming/storybook-addon-material-ui/issues/64
maybe we can unite our efforts to solve this

**Comment by travi** [comment]
i'm happy to provide details of what we are seeing and help potential solutions, but may not have time to dig into coming up with solutions at this point. happy to provide what help i can though.
