### ISSUE TITLE
create-react-app

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#880]
<a href="https://github.com/lifeiscontent"><img src="https://avatars0.githubusercontent.com/u/180963?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lifeiscontent](https://github.com/lifeiscontent)**
_Friday Dec 30, 2016 at 10:33 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/71_

----

When using a default create-react-app for storyshots, it seems to break.

I've got this code in `src/Storyshots.test.js`

``` es6
import initStoryshots from 'storyshots';
initStoryshots();
```

the error in the test is

``` bash
Test suite failed to run

    evalmachine.<anonymous>:1
    (function (exports, require, module, __filename, __dirname) { import { configure } from '@kadira/storybook';
                                                                  ^^^^^^
    SyntaxError: Unexpected token import
```

**Comment by shilman** [comment]
<a href="https://github.com/lifeiscontent"><img src="https://avatars0.githubusercontent.com/u/180963?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lifeiscontent](https://github.com/lifeiscontent)**
_Friday Dec 30, 2016 at 10:40 GMT_

----

figured it out, I needed a `.babelrc` that reflected the same presets as create react app

**Comment by shilman** [comment]
<a href="https://github.com/roonyh"><img src="https://avatars3.githubusercontent.com/u/3872221?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [roonyh](https://github.com/roonyh)**
_Friday Dec 30, 2016 at 11:16 GMT_

----

Glad it works! storyshots comes pre transpiled. So I think this is unrelated to storyshots. Anyway reopen if needed.

**Comment by shilman** [comment]
<a href="https://github.com/kedoska"><img src="https://avatars3.githubusercontent.com/u/11739105?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kedoska](https://github.com/kedoska)**
_Thursday Jan 12, 2017 at 20:38 GMT_

----

I have the same issue.
@lifeiscontent where did you set up the `.babelrc`?

in my `__tests__` directory i have one file, _storyshots.js_

```javascript
import initStoryshots from 'storyshots'
initStoryshots({
  suit: 'ComponentStories'
})
```

when i run `npm run test-storybook` everything works just fine
but, when i run _npm test_ or, in my case `CI=true npm test` it fails like this

![screenshot from 2017-01-12 15 35 31](https://cloud.githubusercontent.com/assets/11739105/21907240/c47a1572-d8dc-11e6-91d2-44ebc26b6f74.png)

my project was created with `create-react-app`

**Comment by shilman** [comment]
<a href="https://github.com/Fatxx"><img src="https://avatars3.githubusercontent.com/u/575479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Fatxx](https://github.com/Fatxx)**
_Thursday Feb 02, 2017 at 01:27 GMT_

----

Any solution here? Get in the same error

**Comment by shilman** [comment]
<a href="https://github.com/Fatxx"><img src="https://avatars3.githubusercontent.com/u/575479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Fatxx](https://github.com/Fatxx)**
_Thursday Feb 02, 2017 at 13:01 GMT_

----

Could this issue be related to the command `react-scripts test --env=jsdom` ? Which we use to run tests?

**Comment by shilman** [comment]
<a href="https://github.com/marc-rutkowski"><img src="https://avatars3.githubusercontent.com/u/6328742?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marc-rutkowski](https://github.com/marc-rutkowski)**
_Thursday Feb 02, 2017 at 14:35 GMT_

----

@kedoska, @Fatxx, as mentioned by @lifeiscontent, providing a basic `.babelrc` file (containing the following snippet) into the project root folder, solves the problem.

```
{
  "presets": ["es2015", "react"]
}

```

Let us know if it works for you.

**Comment by shilman** [comment]
<a href="https://github.com/irnc"><img src="https://avatars1.githubusercontent.com/u/486101?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [irnc](https://github.com/irnc)**
_Tuesday Mar 14, 2017 at 21:15 GMT_

----

Please have a look at https://github.com/storybooks/storyshots/pull/67#pullrequestreview-26933230 which added code related to babel config. The root cause for that issue seems to be in usage of `babelConfig` variable before its declaration.

**Comment by shilman** [comment]
<a href="https://github.com/baptistemanson"><img src="https://avatars1.githubusercontent.com/u/5444992?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [baptistemanson](https://github.com/baptistemanson)**
_Friday Mar 17, 2017 at 01:07 GMT_

----

We were not able to get storyshots working at the same time as storybook and create-react-app using the workaround.
:(.

**Comment by shilman** [comment]
<a href="https://github.com/irnc"><img src="https://avatars1.githubusercontent.com/u/486101?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [irnc](https://github.com/irnc)**
_Saturday Mar 18, 2017 at 19:02 GMT_

----

@baptistemanson For a workaround, you could move from ES6 to ES5 in `.storybook/config.js`, i.e. use `requite` instead of `import`, so unconfigured Babel would just pass without an error on unknown syntax.

Note, that original error is about unknown syntax in `.storybook/config.js`, not in `Storyshots.test.js`.

**Comment by ndelangen** [comment]
We currently do not support ES modules in our config files. maybe in the future we will.
