### ISSUE TITLE
Allow passing options to react-test-renderer .create() method

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#881]
<a href="https://github.com/jrdrg"><img src="https://avatars0.githubusercontent.com/u/11744407?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jrdrg](https://github.com/jrdrg)**
_Wednesday Jan 25, 2017 at 23:09 GMT_
_Originally opened as https://github.com/storybooks/storyshots/pull/76_

----

This PR adds the ability to pass options to the react-test-renderer `create` method, for example to allow mocking refs as per https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing

----

_**[jrdrg](https://github.com/jrdrg)** included the following code: https://github.com/storybooks/storyshots/pull/76/commits_

**Comment by shilman** [comment]
<a href="https://github.com/jrdrg"><img src="https://avatars0.githubusercontent.com/u/11744407?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jrdrg](https://github.com/jrdrg)**
_Tuesday Jan 31, 2017 at 15:58 GMT_

----

@arunoda @roonyh without this PR, running a snapshot test on a component that uses a ref will result in the following error:
![screen shot 2017-01-31 at 10 56 28 am](https://cloud.githubusercontent.com/assets/11744407/22472598/1f1ac064-e7a4-11e6-964f-3ee805b1c1d7.png)

**Comment by shilman** [comment]
<a href="https://github.com/STRML"><img src="https://avatars1.githubusercontent.com/u/1197375?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [STRML](https://github.com/STRML)**
_Tuesday Feb 14, 2017 at 03:40 GMT_

----

This fixes #58 - would be very useful for us to deal with components that use refs.

**Comment by shilman** [comment]
<a href="https://github.com/jrdrg"><img src="https://avatars0.githubusercontent.com/u/11744407?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jrdrg](https://github.com/jrdrg)**
_Thursday Feb 16, 2017 at 18:57 GMT_

----

@roonyh can you take a look when you get a chance?

**Comment by shilman** [comment]
<a href="https://github.com/testerez"><img src="https://avatars0.githubusercontent.com/u/815236?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [testerez](https://github.com/testerez)**
_Saturday Mar 04, 2017 at 00:26 GMT_

----

With @jasonmorganson solution we could have a per-story mock: https://github.com/storybooks/storyshots/issues/58#issuecomment-265554582
Maybe an even better solution would be to add it to `story.options.storyshots.createNodeMock`. It would be cleaner if we end up needing more configuration options...

That said, options passed to `initStoryshots` could still be usefull as a default.

**Comment by theinterned** [comment]
Hi, what's the status on this? I need this functionality and would like to do what I can to get it merged.

**Comment by theinterned** [comment]
Hi, I've made a proposal for a react component-based api for defining stories and passing arbitrary props: https://github.com/storybooks/storybook/issues/993

**Comment by tmeasday** [comment]
It's now possible to set a (admittedly global) `createNodeMock` via the storyshots [`test` option](https://github.com/storybooks/storybook/tree/master/addons/storyshots#test).

We still need a solution to doing it per-story, I suppose. See @theinterned's linked discussion issues.

**Comment by shilman** [comment]
@tmeasday can we close this now, or do we want to continue the per-story discussion here?

**Comment by tmeasday** [comment]
I think it's useful to have an open issue about this because it is something people need.
