### ISSUE TITLE
Run without snaphsots

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#884]
<a href="https://github.com/tmeasday"><img src="https://avatars2.githubusercontent.com/u/132554?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tmeasday](https://github.com/tmeasday)**
_Friday Feb 17, 2017 at 05:21 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/81_

----

Is it possible to run the storyshots w/o actually taking snapshots?

i.e. just to verify if the stories render, w/o checking for changes. 

My use case would be early on in development when things are changing a lot, and I don't want to update snapshots all the time, but I still want to pick up errors. Also using something like https://github.com/mthuret/storybook-addon-specifications would make it even more powerful.

I would imagine the API would be something like `initStoryshots({ noSnapshotTests: true })`

**Comment by ndelangen** [comment]
Why wouldn't you just disable running storyshots?
