### ISSUE TITLE
Since ReactDOM 15.4 is out, the require hijack should be removed from version 2

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#891]
<a href="https://github.com/imontiel"><img src="https://avatars2.githubusercontent.com/u/17833819?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [imontiel](https://github.com/imontiel)**
_Monday Mar 20, 2017 at 21:00 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/90_

----

Since ReactDOM 15.4.* is out, the require hijack should be removed so that stories that use overlays (such as react-bootstrap's `OverlayTrigger`) can be tested.

Currently, in [run_storyshots.js](https://github.com/storybooks/storyshots/blob/v2.1.0/bin/run_storyshots.js), the `ReactDOM` dependency is hijacked. This means any story that uses `unstable_renderSubtreeIntoContainer` or any other function provided by ReactDOM (such as any of the functionality provided [here](https://github.com/facebook/react/blob/15-stable/src/renderers/dom/ReactDOM.js#L30-L40)) cannot be tested.

I have a current work around where I invoke the cli directly:

```
NODE_ENV=test node ./node_modules/storyshots/dist/cli.js
```

I guess the easiest solution is to remove the hijack, change the ReactDOM dependency to `^15.4.0` and upversion to `3.3.0`?

**Comment by ndelangen** [comment]
Is this issue still current?

Please re-open if it's still something we need to do / fix 👍
