### ISSUE TITLE
Add regex to match the story's kind

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#892]
<a href="https://github.com/olistic"><img src="https://avatars2.githubusercontent.com/u/5600126?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [olistic](https://github.com/olistic)**
_Tuesday Mar 28, 2017 at 00:00 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/91_

----

What do you guys think about having these two config options: `storyKindRegex` and `storyNameRegex` instead of the current `storyRegex`?

`storyNameRegex` would behave just as the existing `storyRegex`, while `storyKindRegex` would match against the story's kind, giving users more flexibility.

For example, it could be used to solve #84 doing something like this:

```javascript
// SomeComponent.stories.js

// ...
storiesOf('SomeComponent', module)
    .add('foo', () => {
        // ...
    });
```

```javascript
// SomeComponent.test.js

import initStoryshots from 'storyshots';

initStoryshots({
  storyKindRegex: /^SomeComponent$/,
});
```

Which will cause storyshots (or jest actually) to output a `__snapshots__` directory colocated with the component and with just its storyshots.

If you think it is a good idea, I'm happy to submit a PR!

**Comment by shilman** [comment]
<a href="https://github.com/olistic"><img src="https://avatars2.githubusercontent.com/u/5600126?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [olistic](https://github.com/olistic)**
_Tuesday Mar 28, 2017 at 00:31 GMT_

----

I guess I'm submitting the PR anyway, it's simple enough and I need it for my projects.

**Comment by shilman** [comment]
<a href="https://github.com/alexfedoseev"><img src="https://avatars3.githubusercontent.com/u/4244251?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alexfedoseev](https://github.com/alexfedoseev)**
_Saturday Apr 08, 2017 at 03:36 GMT_

----

Why not just writing snapshots next to the stories file? W/o dummy regexp for each component.

**Comment by ndelangen** [comment]
@olistic We're interested in this PR, if you'll submit it. We've moved to a mono-repo architecture, if you need help, let us know?

**Comment by olistic** [comment]
@ndelangen @shilman I migrated the changes from the old repo and made sure the linter passes. PR is now open against the mono-repo!

**Comment by ndelangen** [comment]
I think that closes this issue?

**Comment by marcoala** [comment]
I really like this feature, when did you plan to release it?

**Comment by ndelangen** [comment]
There's no date yet, sorry. Next release will be 3.0.0.

**Comment by olistic** [comment]
@marcoala I had published a fork of the old storyshots repo in npm, which includes this feature. I'm using it in my projects until 3.0.0 is released. Just `npm i @olistic/storyshots` or `yarn add @olistic/storyshots`.

**Comment by marcoala** [comment]
@olistic Thanks!

**Comment by epicallan** [comment]
I hope this does't sound dumb, but what do you think about adding a reverse of the same option. I know you can do an inverse regex but it may not be easy for some of us.
I am suggesting something like this.

```
initStoryshots({
  storyIgnoreKindRegex: /^SomeComponent$/,
});
```
I can put together a PR

**Comment by ndelangen** [comment]
@tmeasday What do you think?

**Comment by tmeasday** [comment]
Is it possible to just write a negative regelated?

**Comment by tmeasday** [comment]
Ugh, regexp

**Comment by epicallan** [comment]
@tmeasday I was using https://regex101.com to try to create inverse regexes and they were not working for some reason and i assumed maybe they were not supported in JS or required rear regex tricks. Tried the same inverse regexes in the browser console window and they worked. 

I am guessing maybe we may not need the reverse the same although it might be convenient for people who find regexes intimidating.

**Comment by tmeasday** [comment]
Maybe we can add something to the docs? I guess I'm not sure how common
this use case is?

**Comment by epicallan** [comment]
I agree we could add something to the docs in form of an example or leave as is. I doubt its a common use case.

**Comment by tmeasday** [comment]
If you want to send a PR of what you did (I don't know how to write a negative regexp myself ;) ), that'd be super!

**Comment by epicallan** [comment]
Just sent a PR https://github.com/storybooks/storybook/pull/1317

**Comment by tirli** [comment]
@epicallan I tried to use your regexp from docs and I have a file named `tooltip.DontTest.stories.js`. But the story still not skipping :( Could you please tell me what I'm doing wrong?

**Comment by igor-dv** [comment]
@tirli 
Can you please share your regex ?

**Comment by tirli** [comment]
@igor-dv The same as in docs: `storyKindRegex: /^((?!.*?DontTest).)*$/`

**Comment by igor-dv** [comment]
storyKindRegex is for the storyKind (the first parameter you provide to the `storiesOf(...)`), but not for the story file name..  I think currently is not possible to filter stories by files..

**Comment by tirli** [comment]
@igor-dv Now it works :) Thank you

**Comment by matsumatsu233** [comment]
Hi, I'm finding a way to separate the snapshots generated by storyshot. I read the README of storyshot and found here.
```javascript
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots({
  storyKindRegex: /^MyComponent$/
});
```
> This can be useful if you want to separate the snapshots in directories next to each component. See an example [here](https://github.com/storybooks/storybook/issues/892).

This statement indicates that if I use this option, then the snapshots will be separated and be placed nearby each component's source code. I gave it a try but just found the generated snapshots are stilled merge into a big file. The regex works well.

So, do I misunderstand the documents? Or I have a wrong version (3.0.0) or this feature is not available yet? I would appreciate your help :)

**Comment by igor-dv** [comment]
@matsumatsu233 

Today the only way to do what you want is creating a storyshot.test.js for each story separately. For example having `Button.stories.js` file you can create `Button.storyshots.tests.js` and configure it to take only the kind from `Button.stories.js`. 

The limitation is from the Jest's side that do not support multiple snapshots per test file.

But we have this #1584 PR that will probably help with this requirement in the future.

**Comment by matsumatsu233** [comment]
@igor-dv Thank you very much! I will try to create test file for each component, and I'm looking forward to #1584 :)
