### ISSUE TITLE
head.html is not loaded in storyshots

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#894]
<a href="https://github.com/eric-burel"><img src="https://avatars2.githubusercontent.com/u/7983005?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eric-burel](https://github.com/eric-burel)**
_Tuesday Apr 11, 2017 at 09:47 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/96_

----

In v2.1.0, `.storybook/head.html/` does not seem to be taken into account. My issue is that its where I load jQuery, which is mandatory for bootstrap to work (I found no other solution than using `head.html` to get Bootstrap working with webpack).
Edit: same issue with 3.1.1 so far, I am trying to find a solution.

**Comment by HBCharles** [comment]
I'm also having the issue with 4.5.0. Is there any solution to this ?

**Comment by tmeasday** [comment]
Reproduced here: https://github.com/tmeasday/storybook/tree/issue-894

Note that (a) the tests fail in the `test-cra` app, but (b) the storybook runs without errors.

**Comment by shilman** [comment]
@tmeasday thanks for creating a repro. my understanding: `head.html` is loaded in the preview window's `iframe`. therefore it doesn't show up in the outer window.

Added the following `head.html` to `create-react-app/getstorybook` yields:
```
<style> body {  background: yellow; }</style>
```

<img width="493" alt="storybook" src="https://cloud.githubusercontent.com/assets/488689/26619194/7638d62e-4631-11e7-894a-3e9700760562.png">

**Comment by tmeasday** [comment]
@shilman -- correct. It's just that storyshots doesn't respect that, so the environment a story renders in in the UI (the preview window) is different from how it is rendered in the test (with a simple `renderer.create(..)`), thus the errors.

**Comment by shilman** [comment]
@tmeasday oh sorry this is a storyshots issue. my misunderstanding!

**Comment by tmeasday** [comment]
Hmm, thinking about this some more, I'm not sure there is a good solution to the problem. Does any one have any good ideas?

**Comment by zeroasterisk** [comment]
see: https://github.com/storybooks/storybook/commit/5c0eb412c27ece763e4432213bd5d6668d49dd8c

it should work with either, but it's officially renamed to `preview-head.html`

**Comment by tmeasday** [comment]
Looking at this again, I reckon the real "solution" here is to not put JS includes in `preview-head.html`. 

I wonder if the problem (needing static includes) could be solved in some other way, like a require from `.storybook/config`?

**Comment by Hypnosphi** [comment]
You always can insert scripts dynamically:

```
const script = document.createElement('script')
script.src = "..."
document.head.appendChild(script)
```

**Comment by tmeasday** [comment]
Perhaps @eric-burel or @HBCharles could confirm if the above technique, as posted by @Hypnosphi helps?

**Comment by johnend** [comment]
Did anyone find a solution to this? I want to start using StoryBook as part of our front-end development workflow on Vue projects, but having done some testing tonight I have come across this problem.

**Comment by tmeasday** [comment]
@johnend -- did @Hypnosphi's solution work for you?

**Comment by johnend** [comment]
Sorry just updated, posted too early.

**Comment by Hypnosphi** [comment]
You can try to add that code to `config.js` instead

**Comment by tmeasday** [comment]
@johnend -- the `preview-head.html` file is not evaluated for storyshots at all (storyshots only runs your JS code, so it doesn't necessarily make sense to try and evaluate HTML code -- although we could with JSDOM perhaps).

So the solution as suggested by @Hypnosphi  is to try to avoid including JS code in `preview.head` and instead put it in `.storybook/config.js` where possible.

**Comment by johnend** [comment]
Ok so having done that, I'm still getting a 404 for the script for font awesome. Tag is being included in the head and is referencing the correct folder. Just updating to let you know.

**Comment by tmeasday** [comment]
@johnend is this in storyshots or regular storybook now?

**Comment by johnend** [comment]
This is in regular storybook. Sorry I think I’ve posted my comments on the wrong issue. Didn’t realise storyshots was an add on and not just the iframe for the components.

**Comment by tmeasday** [comment]
No worries. I suspect maybe you need to use the -s option to set the static
directory?
