### ISSUE TITLE
Can't use CSS module with storyshots

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#895]
<a href="https://github.com/willowcheng"><img src="https://avatars0.githubusercontent.com/u/6239076?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [willowcheng](https://github.com/willowcheng)**
_Wednesday Apr 12, 2017 at 16:25 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/97_

----

Wish to use storyshots for snapshot feature of JEST while using CSS module. In JEST, I can use `identity-obj-proxy` to [mock CSS module](https://facebook.github.io/jest/docs/webpack.html#mocking-css-modules). BTW, might it be a good idea to bring mock functionality from JEST?

<img width="461" alt="screen shot 2017-04-12 at 12 24 59 pm" src="https://cloud.githubusercontent.com/assets/6239076/24968398/1a016cb8-1f7b-11e7-9531-a64e07cdbc89.png">

**Comment by klaemo** [comment]
We're using storyshots with css modules and it works as expected.

**Comment by ndelangen** [comment]
Please re-open with a reproduction or steps to reproduce 👍
