### ISSUE TITLE
Lerna warning: a cycle in the dependency graph

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#898]
```
➜  mono-repo git:(master) ✗ lerna bootstrap && npm run lint -- --fix
Lerna v2.0.0-beta.38
Bootstrapping 8 packages
Encountered a cycle in the dependency graph. This may cause instability!
Preinstalling packages
Installing external dependencies
...
```

There's probably a circular dependency on internal modules somewhere, likely demo inside src using addons which use src... Should be easily fixed by moving demo's out of src.

**Comment by tmeasday** [comment]
Is this still a problem @ndelangen? I haven't seen it for a while. Closing in lieu of you telling me it is.

**Comment by datapimp** [comment]
i'm experiencing this also; can you suggest some steps on how to find the culprit?

**Comment by tmeasday** [comment]
@datapimp have you tried `lerna clean` to clean up

**Comment by ndelangen** [comment]
Our repo should no longer have this problem
