### ISSUE TITLE
Automate updating a CHANGELOG in the root

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybook#905]
Should we maintain a changelog.md ?
If we are going to, we should automate this.

**Comment by aaronmcadam** [comment]
I use [`lerna`'s `conventional-commits` flag](https://github.com/lerna/lerna#--conventional-commits), which works nicely. We would have to follow [this commit message convention](https://conventionalcommits.org/) with everything.

**Comment by ndelangen** [comment]
We decided not to mess with git history and went to a pr-log based solution @shilman made.
