### ISSUE TITLE
ReferenceError: window is not defined when executing initStoryshots()

### ISSUE THREAD

**Issue by flanamacca** [storybooks/storybook#909]
When using jest to init initStoryshots (as per the guide), I am stumped with the following error.  Sadly all of the code references that used to exist for storyshots seem to go to 404 pages.

` FAIL  .\Storyshots._test_.js
  ● Test suite failed to run

    ReferenceError: window is not defined

      at evalmachine.<anonymous>:17:1
      at runWithRequireContext (node_modules\storyshots\dist\require_context.js:104:3)
      at testStorySnapshots (node_modules\storyshots\dist\index.js:72:35)
      at Object.<anonymous> (Storyshots._test_.js:2:26)
      at process._tickCallback (internal\process\next_tick.js:109:7)`

**Comment by shilman** [comment]
@flanamacca which code references are you referring to? The `storyshots` repo has moved here:

https://github.com/storybooks/storybook/tree/master/packages/storyshots

**Comment by flanamacca** [comment]
Hey @shilman This part on that pge.

import initStoryshots from 'storyshots';
initStoryshots(); <!-- when this runs with nothing but the default configuration i was getting this error.  Now i had to setup a lot of just settings to get working.

When i do the basic installation with create-react-app and run it, it doesn't work either (since it's not configured to run through any preprocessor).

PASS  src/App.test.js
 FAIL  __tests__/Storyshots.test.js
  ● Test suite failed to run

    evalmachine.<anonymous>:1
    (function (exports, require, module, __filename, __dirname) { import { configure } from '@kadira/storybook';
                                                                  ^^^^^^
    SyntaxError: Unexpected token import

**Comment by flanamacca** [comment]
Found the solution is that unlike in some other jest setups, you need to define your windows as global objects in the config file.

**Comment by beauknowssoftware** [comment]
Sorry for coming back to a closed issue, but I'm also experiencing this.  @flanamacca , do you happen to have a code sample that shows your solution?

**Comment by leojh** [comment]
This error started happening for me all out of a sudden out of nowhere :|

**Comment by OBrian16** [comment]
`    ReferenceError: error is not defined

      83 |           className={'reactSelect'}
      84 |         />
    > 85 |         {error && <strong>{error}</strong>}
         |          ^
      86 |       </div>
      87 |     })
 `
I'm getting the same error. Anyone with a solution?
