### ISSUE TITLE
Update Docs for monorepo

### ISSUE THREAD

**Issue by burabure** [storybooks/storybook#912]
The current docs here https://getstorybook.io/docs have a lot of misleading information about how to setup addons, testing and such. All links to these go to the deprecated packages repos instead of the new ones.

This was very confusing and made it difficult to get started with storybook.

**Comment by ndelangen** [comment]
Hey @burabure This is certainly true, we're sorry for the inconvenience! We're transitioning to the monorepo, and have yet to publish new releases or documentation. This is high on our issue-list!

**Comment by shilman** [comment]
@shilman is updating the doc content
@mnmtanish is updating the deployment so we can get it on `storybooks.js.org`

**Comment by shilman** [comment]
Update: we've updated the contents and added a clever way to publish by @mnmtanish. Now we're just waiting for the DNS changes to go through and it should be live on https://storybooks.js.org within 24H

**Comment by methyl** [comment]
@shilman even after updating docs there is no information on how to install addon included within monorepo, for example when you go to https://getstorybook.io/docs/react-storybook/addons/using-addons (or check out https://github.com/storybooks/storybooks.github.io/issues/1) it says

```
npm i --save '@kadira/storybook-addon-notes';
```

which will install deprecated addon. How do you use addons from monorepo?

**Comment by shilman** [comment]
@methyl the monorepo addons have not been released yet. the addon itself is not deprecated, but the repo is deprecated. we hope to release the updated addons soon and will update the docs when they are available.

**Comment by shilman** [comment]
I have deployed the updated docs temporarily to https://storybooks.github.io/

**Comment by shilman** [comment]
Site is now live at https://storybooks.js.org/
