### ISSUE TITLE
Explain the -g pattern in documentation is for generating only, not to run storybook itself

### ISSUE THREAD

**Issue by TheJaredWilcurt** [storybooks/storybook#916]
It's widely considered to be an anti-pattern to request that people globally install your Node Module. You shouldn't have to have Grunt, Bower, Webpack, Rollup, Storybook, etc, etc, etc, added to your system's global PATH.

Further, it can cause version issues. If the project I am using was written expecting an older version of `X`, but the newer, globally installed, version doesn't work with the project. Had the project just listed `X` in the `devDependencies` and accessed it via a `npm run scriptName` then when I ran `npm install` I'd have the correct version downloaded locally, and when I run it via `npm run whatever` it will use the correct version.

There should be documentation showing how to get `start-storybook`/`build-storybook` to run locally without adding anything to the PATH.

In order to run someone else's project, the expectation should be just to run `npm install` and `npm start`. If you have to globally install something, you're adding barriers of entry to getting more people to contribute.

**Comment by shilman** [comment]
Hi @TheJaredWilcurt. As far as I know, there are no global requirements for Storybook. `getstorybook` is a convenient way to add storybook to any React project, but you can also just edit by hand. The documentation is here:

https://storybooks.github.io/docs/react-storybook/basics/slow-start-guide

Please let me know if that answers your concern!

**Comment by avaly** [comment]
@shilman I think he might be referring to these instructions: 

- https://storybooks.js.org/docs/react-storybook/basics/quick-start-guide
- https://github.com/storybooks/storybook#getting-started

**Comment by shilman** [comment]
Ok @avaly @TheJaredWilcurt. Given that there is documentation that describes how to set things up by hand without any global requirement, does that address your concern? And if not, why not?

If you think it can be made better, please feel free to submit a PR to improve the docs!

**Comment by TheJaredWilcurt** [comment]
If you just added in a link to the slow guide next to the other, far easier to find, instructions that said:

"If you want instructions on using Storybook that don't require polluting your PATH, click here."

Feel free to pretty up that language, I'm no wordsmith.

**Comment by ndelangen** [comment]
We're working on better documentation, thanks for the notification we should improve on this front.

I agree, less global installs is better. 

However to get a project setup from scratch it's very common to have some sort of generator you need to install globally. This is what `getstorybook` is.

**Comment by danielduan** [comment]
done.
