### ISSUE TITLE
How do I write a story with flowtype?

### ISSUE THREAD

**Issue by lifeiscontent** [storybooks/storybook#925]
Sorry, I'm new to flow, any chance someone can help me out here?

line 5 is `storiesOf('NodeContextMenu', module).add('default', () => (`

``` jsx
import React from 'react';
import {storiesOf} from '@kadira/storybook';
import NodeContextMenu from './index';

storiesOf('NodeContextMenu', module).add('default', () => (
  <NodeContextMenu>
    <NodeContextMenu.Item icon="trashbin-18">Delete</NodeContextMenu.Item>
    <NodeContextMenu.Item icon="lock-18">Lock</NodeContextMenu.Item>
  </NodeContextMenu>
));
```

| Type | Source | File | Line | Description |
| ---- | ------ | ---- | ---- | ----------- |
|Warning|Type Coverage|src/components/NodeContextMenu/index.stories.js|5|Not covered by Flow|
|Warning|Type Coverage|src/components/NodeContextMenu/index.stories.js|5|Not covered by Flow|
|Warning|Type Coverage|src/components/NodeContextMenu/index.stories.js|5|Not covered by Flow|

**Comment by TheSisb** [comment]
We skip flow on stories.  Only on components.

**Comment by ndelangen** [comment]
You load stories in `config.js` and they are loaded through webpack.

So you have the option to add a webpack loaded with babel + flow.
