### ISSUE TITLE
Added content wrapped in decorator

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#931]
<a href="https://github.com/aray12"><img src="https://avatars1.githubusercontent.com/u/8671174?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aray12](https://github.com/aray12)**
_Friday Jul 15, 2016 at 16:41 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/40_

----

So if I want to provide some styling just to the component. The following example will center everything, including what addon-info adds

```
import React from 'react';
import { storiesOf, action } from '@kadira/storybook';

storiesOf('Button', module)
  .addDecorator(story => (<div style={{width: '100px', margin: 'auto'}}>{story()}</div>))
  .addWithInfo(
    'Standard
    `
    This should continue to be normal and not constrained by the decorator <div>
    `,
    () => (
      <button onClick={action('button clicked')}>Click Me</button>
    ),
    { inline: true, source: true, header: true }
  )
```

Thoughts?

**Comment by shilman** [comment]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnmtanish](https://github.com/mnmtanish)**
_Monday Jul 18, 2016 at 09:52 GMT_

----

Yeah, that messes things up pretty bad. I think we should let addon developers decide that. How about exposing 2 new methods `addRaw` and `decorate` in addition to `add`?

cc: @arunoda

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Wednesday Jul 20, 2016 at 04:24 GMT_

----

@mnmtanish basically we need some options to do this:
- apply decorators
- do not apply decorators

Is that? If so, I'm okay with a such an API.

May be an option to the `.add` as `byPassDecorators`.

**Comment by shilman** [comment]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnmtanish](https://github.com/mnmtanish)**
_Thursday Jul 21, 2016 at 04:20 GMT_

----

With the option users can only bypass decorators. With `addRaw` and `decorate` users can apply decorators exactly where they want. And adding an options object to the add method would make the API look terrible.

**Comment by davemcorwin** [comment]
In general, you can apply styles to the container of your story markup by providing a `styles` key in the configuration such as:
```
{
  ...
  styles: stylesheet => {
    stylesheet.children = {
    // some styles
    }
    return stylesheet
  },
}
```

However, this did not work when rendering inline (with `inline: true` in the config), so I just submmited #1431 to address this.

**Comment by ndelangen** [comment]
#1147 We will move the info into a panel.

**Comment by ndelangen** [comment]
Feel free to continue discussing or re-open if there's still an issue afterwards 👍
