### ISSUE TITLE
React native support for addon-info

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#936]
<a href="https://github.com/mlabrum"><img src="https://avatars1.githubusercontent.com/u/296106?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mlabrum](https://github.com/mlabrum)**
_Wednesday Sep 14, 2016 at 00:27 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/64_

----

Hello,

I was wondering if there is any plans to support https://github.com/kadirahq/react-native-storybook

Cheers,

**Comment by shilman** [comment]
<a href="https://github.com/linonetwo"><img src="https://avatars2.githubusercontent.com/u/3746270?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [linonetwo](https://github.com/linonetwo)**
_Sunday Dec 18, 2016 at 17:32 GMT_

----

Now it will throw ```undefined is not an object (near 'ked-xxxxx')}));)```

**Comment by shilman** [comment]
<a href="https://github.com/rohit-ravikoti"><img src="https://avatars2.githubusercontent.com/u/16107563?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rohit-ravikoti](https://github.com/rohit-ravikoti)**
_Wednesday Jan 25, 2017 at 04:03 GMT_

----

Is native support planned for this at all? It would be very useful!

**Comment by shilman** [comment]
<a href="https://github.com/jiasaichao"><img src="https://avatars2.githubusercontent.com/u/11605441?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jiasaichao](https://github.com/jiasaichao)**
_Sunday Mar 05, 2017 at 16:29 GMT_

----

Is native support planned for this at all? It would be very useful!

**Comment by robertherber** [comment]
Would love this as well. Right now I get 'Expected a component class, got [object Object]' when using this together with React Native.

**Comment by simply-innovative** [comment]
@shilman  Is native support planned for this? if yes any timelines for the same?

**Comment by ndelangen** [comment]
Is anyone here interested in opening an PR for this?

**Comment by shilman** [comment]
#1147 will fix this as soon as we get it going

**Comment by RobinLebhar** [comment]
Maybe this can help you while someone create the react-native add-on

https://github.com/RobinLebhar/with-info-doc-expo-storybook
