### ISSUE TITLE
Design suggestion: keep component alone in render area, move info to right panel

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#937]
<a href="https://github.com/kevinSuttle"><img src="https://avatars0.githubusercontent.com/u/95672?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kevinSuttle](https://github.com/kevinSuttle)**
_Thursday Sep 15, 2016 at 17:40 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/67_

----

Just an idea.

**Comment by shilman** [comment]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnmtanish](https://github.com/mnmtanish)**
_Thursday Sep 15, 2016 at 17:48 GMT_

----

Yeah totally agree with you on that. If we do that, it'll be possible to use this addon with React Native Storybook. Also check these similar addons:
- https://github.com/kadirahq/storybook-addon-notes
- https://github.com/mthuret/storybook-addon-usage

It'll be great if someone writes an addon to display component prop information

**Comment by shilman** [comment]
<a href="https://github.com/kevinSuttle"><img src="https://avatars0.githubusercontent.com/u/95672?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kevinSuttle](https://github.com/kevinSuttle)**
_Thursday Sep 15, 2016 at 18:17 GMT_

----

Do you have a guide for configuring/contributing to this addon? I know it uses the RCK.

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Friday Sep 16, 2016 at 00:29 GMT_

----

I think it'll be a new addon. Check our addon docs: https://getstorybook.io/docs/addons/writing-addons

If we are doing this, I think it's a pretty good idea to provide a way to pass [`react-docgen`](https://github.com/reactjs/react-docgen) to parse the source code and get the propType information.

**Comment by shilman** [comment]
<a href="https://github.com/marc-rutkowski"><img src="https://avatars3.githubusercontent.com/u/6328742?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marc-rutkowski](https://github.com/marc-rutkowski)**
_Monday Jan 09, 2017 at 12:35 GMT_

----

This will be a good improvement when using this addon with the [storyshots](https://github.com/storybooks/storyshots) feature.

For now, snapshots created from stories by storyshots includes all the info markup instead of only the component's markup.

**Comment by shilman** [comment]
<a href="https://github.com/marc-rutkowski"><img src="https://avatars3.githubusercontent.com/u/6328742?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marc-rutkowski](https://github.com/marc-rutkowski)**
_Monday Jan 23, 2017 at 17:18 GMT_

----

Here is an attempt to display components info (props & story) into panels
https://github.com/marc-rutkowski/storybook-addon-props

Any feedback is very welcome!

**Comment by ndelangen** [comment]
CONFIRMED! #1147 

I'm marking this as a duplicate, thanks for the suggestion! @kevinSuttle
