### ISSUE TITLE
Support flow type props validation

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#939]
<a href="https://github.com/joehua87"><img src="https://avatars0.githubusercontent.com/u/11925924?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joehua87](https://github.com/joehua87)**
_Saturday Sep 17, 2016 at 14:00 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/74_

----

Thank you for your awesome library.

Did you have any plan to support:

``` js
export default class Item extends React.Component { // eslint-disable-line
  props: {
    icon: string,
    tooltip?: string,
    onClick?: () => void,
  };

  render() {
    const { icon, tooltip, onClick } = this.props
    return (
      <span className={styles.root} onMouseDown={onClick} title={tooltip}>
        <span className="material-icons">{icon}</span>
      </span>
    )
  }
}

```

together with

``` js
  static propTypes = {
    icon: React.PropTypes.string.isRequired,
    tooltip: React.PropTypes.string,
    onClick: React.PropTypes.func,
  };
```

**Comment by shilman** [comment]
<a href="https://github.com/MoOx"><img src="https://avatars1.githubusercontent.com/u/157534?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MoOx](https://github.com/MoOx)**
_Wednesday Feb 01, 2017 at 10:38 GMT_

----

https://github.com/styleguidist/react-styleguidist handle this using react-docgen. The problem is that for now it's limited to babel5 parser... Until this is fixed https://github.com/reactjs/react-docgen/issues/125 / https://github.com/reactjs/react-docgen/pull/137 (so this https://github.com/babel/babylon/issues/278 / https://github.com/babel/babylon/pull/277)

**Comment by ndelangen** [comment]
I think we should move this issue to:
https://github.com/storybooks/babel-plugin-react-docgen

**Comment by ndelangen** [comment]
Moved: https://github.com/storybooks/babel-plugin-react-docgen/issues/29
