### ISSUE TITLE
breakIntoNewLines should be configurable

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#941]
<a href="https://github.com/Bjvanminnen"><img src="https://avatars0.githubusercontent.com/u/1767466?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Bjvanminnen](https://github.com/Bjvanminnen)**
_Friday Oct 21, 2016 at 23:55 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/115_

----

https://github.com/kadirahq/react-storybook-addon-info/blob/master/src/components/Props.js#L27

I'd like to make our components always break into new lines (regardless of number of properties). Without having spent a lot of time looking at this code, it seems like the best way to do this would be to add a prop to `Node` that gets passed through to `Props` that is either a bool `alwaysBreakIntoNewLines` or a number `breakNewLinesAfterNProps` (where n is 3 by default) that allow one to override when we break into new lines.

Thoughts?

Happy to submit a PR if either of these approaches seem palatable.

**Comment by ndelangen** [comment]
Considering we're moving the content into a panel see #1147 I guess the only behavior that makes sense it like you describe.

@shilman You're going to do that issue right?
Do you want to have this issue included, or done separately? @Bjvanminnen could possibly help you?
