### ISSUE TITLE
Broken Markdown support

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#943]
<a href="https://github.com/tomitrescak"><img src="https://avatars1.githubusercontent.com/u/2682705?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomitrescak](https://github.com/tomitrescak)**
_Tuesday Nov 01, 2016 at 04:33 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/118_

----

When I define my story as following, everything from the second line is considered to be "code" example:

```js
 .addWithInfo('Item > logged out user',
  `Shows a logged out view with possibility of preview 

* shows only the header and a description
* header link points to public exercise with url /organisation/exercise/exerciseName/practicalName/exerciseName/exerciseId/practicalId/scheduleId/
* image contains a preview icon
* clicking on the image shows a preview modal
  `, () => {
```

**Comment by ndelangen** [comment]
Yeah this is the case with meaningful indentation / whitespace... I don't like it either and **always** use fenced code-samples.

But this is markdown and it will be super odd the change it. Sorry this isn't directly fixable.

But!
It **is** preventable:
```js
const info = `
Shows a logged out view with possibility of preview 

* shows only the header and a description
* header link points to public exercise with url /organisation/exercise/exerciseName/practicalName/exerciseName/exerciseId/practicalId/scheduleId/
* image contains a preview icon
* clicking on the image shows a preview modal
`;
const stories = storiesOf()
  .addWithInfo(
    'Item > logged out user',
    info,
    () => <div />
  );
```

...by extracting the info into a variable at indentation 0.

-- or --

```js
const stories = storiesOf()
  .addWithInfo(
    'Item > logged out user',
    require('./info.md'),
    () => <div />
  );
```

...by requiring a markdown-file and using `raw-loader`
