### ISSUE TITLE
Support all propTypes (shape, arrayOf, oneOf)

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#944]
<a href="https://github.com/tuchk4"><img src="https://avatars3.githubusercontent.com/u/5140611?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tuchk4](https://github.com/tuchk4)**
_Tuesday Dec 13, 2016 at 06:07 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/123_

----

It would be great if support all propTypes:

- shape
- oneOf
- arrayOf

etc.

I know that implementation is not possible but I created related issue (feature request) at React repository. If all is OK - I will be able to make PR with this feature implementation.

https://github.com/facebook/react/issues/8310

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Thursday Dec 15, 2016 at 07:48 GMT_

----

I'm not sure this will land to React or not.
Anyway, if React does support it we are glad to have that on here.

**Comment by shilman** [comment]
<a href="https://github.com/elisherer"><img src="https://avatars3.githubusercontent.com/u/1045347?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elisherer](https://github.com/elisherer)**
_Thursday Dec 15, 2016 at 11:53 GMT_

----

You could potentially try to run all the prop type checks with several combinations of values and based on the PropTypeError object returned (like checking the message with a regex) you could determine what kind of prop type was used.

**Comment by shilman** [comment]
<a href="https://github.com/tuchk4"><img src="https://avatars3.githubusercontent.com/u/5140611?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tuchk4](https://github.com/tuchk4)**
_Thursday Dec 15, 2016 at 13:37 GMT_

----

> based on the PropTypeError object returned (like checking the message with a regex) 

yes, but this is way is like "workaround"

**Comment by shilman** [comment]
<a href="https://github.com/elisherer"><img src="https://avatars3.githubusercontent.com/u/1045347?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elisherer](https://github.com/elisherer)**
_Thursday Dec 15, 2016 at 15:17 GMT_

----

That's why I said "potentially", also it will not work in production builds (if you make your static storybook use production environment). But a nice touch for most use cases without changing React's code. could be easily changed/reverted if broken by future versions of React.

**Comment by shilman** [comment]
<a href="https://github.com/tuchk4"><img src="https://avatars3.githubusercontent.com/u/5140611?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tuchk4](https://github.com/tuchk4)**
_Wednesday Jan 04, 2017 at 18:49 GMT_

----

btw. I made PR to React so you can take part if you are interested in 

* [facebook/react/issues/8310](https://github.com/facebook/react/issues/8310)
* [facebook/react/pull/8684](https://github.com/facebook/react/pull/8684)

**Comment by ndelangen** [comment]
We get the props info from this babel plugin: https://github.com/storybooks/babel-plugin-react-docgen

Is this support still missing? Cone you please open an issue at that repo?
