### ISSUE TITLE
Display problem when installed with storybook-host

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#946]
<a href="https://github.com/HBCharles"><img src="https://avatars2.githubusercontent.com/u/9991267?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HBCharles](https://github.com/HBCharles)**
_Saturday Jan 07, 2017 at 19:54 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/129_

----

The addon-info are displaying in the host area when storybook-host is installed : 

![image](https://cloud.githubusercontent.com/assets/9991267/21744719/6c06203a-d51b-11e6-8da6-99e51d725260.png)

How can I display the component addon-info in fullscreen ?

**Comment by ndelangen** [comment]
#1147 Wil be fixed by moving info contents to a panel
