### ISSUE TITLE
Styling of the info

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#950]
<a href="https://github.com/Donaldini"><img src="https://avatars0.githubusercontent.com/u/2185680?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Donaldini](https://github.com/Donaldini)**
_Monday Mar 06, 2017 at 10:35 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/140_

----

I was looking through the issues whether there was something about styling the content generated by the add-on, but couldn't find any previous info.

I did see [this post](https://github.com/storybooks/react-storybook-addon-info/issues/8) of @mnmtanish that showed a styled version of the info.

What would be the best and contained way of styling the add-on?

**Comment by shilman** [comment]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnmtanish](https://github.com/mnmtanish)**
_Saturday Apr 08, 2017 at 11:13 GMT_

----

Related PR: https://github.com/storybooks/react-storybook-addon-info/pull/135

cc: @jbellsey

**Comment by jbellsey** [comment]
I will not be pursuing that PR any further. Feel free to take its code and/or ideas and implement as you see fit (or abandon it).
