### ISSUE TITLE
Code highlighting 

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#951]
<a href="https://github.com/ilionic"><img src="https://avatars0.githubusercontent.com/u/1027871?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ilionic](https://github.com/ilionic)**
_Thursday Mar 16, 2017 at 21:24 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/141_

----

Based on example
https://github.com/storybooks/react-storybook-addon-info/blob/master/example/story.js#L71
Is it possible to enable highlighting for inline code? ( similar to how Story Source is displayed)

**Comment by ndelangen** [comment]
Yeah, why not?! should be simple.

Want to make a PR for this @ilionic ?

**Comment by danielduan** [comment]
I'm gonna close this one.

I'm not sure what it means by inline code. If you want to insert code, you can use markdown in the notes addon or the description field of the info addon as well.
