### ISSUE TITLE
Make title configurable

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#952]
<a href="https://github.com/creeperyang"><img src="https://avatars0.githubusercontent.com/u/8046480?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [creeperyang](https://github.com/creeperyang)**
_Wednesday Mar 22, 2017 at 04:07 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/142_

----

Currently title and section's title are all hardcoded, it's great to give a way to change them.

**Comment by shilman** [comment]
<a href="https://github.com/rphuber"><img src="https://avatars3.githubusercontent.com/u/8245890?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rphuber](https://github.com/rphuber)**
_Friday Mar 31, 2017 at 17:47 GMT_

----

What titles are you referring to?  The component name at the top?

**Comment by shilman** [comment]
<a href="https://github.com/creeperyang"><img src="https://avatars0.githubusercontent.com/u/8046480?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [creeperyang](https://github.com/creeperyang)**
_Saturday Apr 01, 2017 at 03:50 GMT_

----

I means the hardcode part, such as 

```js
<h1 style={this.state.stylesheet.source.h1}>Story Source</h1>
<h1 style={this.state.stylesheet.source.h1}>Prop Types</h1>
```

**Comment by ndelangen** [comment]
To what end? what follows is always the same, so they are descriptive headers..

**Comment by ndelangen** [comment]
Marking this as duplicate of #866

**Comment by vladanyes** [comment]
You can do smth like this:
```
storiesOf('elements/Button', module)
  .addDecorator(withInfo)
  .addDecorator(story => (
    <div style={{ paddingLeft: 10 }}>
      <h5>Component additional description</h5>
      {story()}
    </div>
  ))
  .add('Component name or smth else', () => (
    <Button  onClick={action('onClick')}>
      Content
    </Button>
  ));
```
