### ISSUE TITLE
Typescript compatibility

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#953]
<a href="https://github.com/mdcorriveau"><img src="https://avatars0.githubusercontent.com/u/9082852?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mdcorriveau](https://github.com/mdcorriveau)**
_Friday Mar 31, 2017 at 19:07 GMT_
_Originally opened as https://github.com/storybooks/react-storybook-addon-info/issues/144_

----

Hi, 

I'm currently converting my react application and storybook to typescript. I currently have a bunch of error with the addWithInfo which return this error : 
TS2339:Property 'addWithInfo' does not exist on type 'Story'.

While react-storybook is already providing a storybook.d.ts file in their package, do you think it'll be a great idea to do the same with react-storybook-addon-info ?

Thanks

**Comment by shilman** [comment]
<a href="https://github.com/ndelangen"><img src="https://avatars1.githubusercontent.com/u/3070389?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndelangen](https://github.com/ndelangen)**
_Friday Mar 31, 2017 at 19:35 GMT_

----

Hey @mdcorriveau, thank you for reporting! Sounds you know a thing or 2 about typescript, would you be able to help us out by creating a PR?

**Comment by shilman** [comment]
<a href="https://github.com/mnmtanish"><img src="https://avatars2.githubusercontent.com/u/136691?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnmtanish](https://github.com/mnmtanish)**
_Saturday Apr 01, 2017 at 10:45 GMT_

----

I've never done this before but perhaps we can add a type definition file to this repo which will add the method to the story type. I found [this page](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) in typescript documentation about merging type declarations. I'll check it out and comment here.

**Comment by mdcorriveau** [comment]
Sorry i've just seen your message, i'll try to give you some info tomorrow !

**Comment by ndelangen** [comment]
The custom `.addBlahBlah()` stuff is a bad idea, and we need to provide better ways to add addon-data to stories.

That will make this problem go away too.

Ideas and solution are welcome, but I'm not going to fix this, because long term this is not how we want to do things.

Related #1209

**Comment by mucsi96** [comment]
I created a PR containing a new example for React + TypeScript https://github.com/storybooks/storybook/pull/5011
