### ISSUE TITLE
Mocking in storyshots

### ISSUE THREAD

**Issue by tehandyb** [storybooks/storybook#962]
Is it possible to Mock components when using storyshots? I can't see any documentation to do it.

**Comment by evenchange4** [comment]
Yes, it is possible. I mock several components for storyshots with Jest config:

```json
"setupFiles": [
  "<rootDir>/.storybook/storyshots-setup.js"
],
```

```js
// .storybook/storyshots-setup.js"
jest.mock('react-motion-ui-pack');
...
```

Reference: https://github.com/MCS-Lite/mcs-lite/blob/master/packages/mcs-lite-ui/package.json#L30

**Comment by tehandyb** [comment]
Awesome, thanks!

**Comment by horacio10x** [comment]
If you want to mock for the storyshots only you can put your mock above initStoryshots()

```
jest.mock('../someMock', () =>
  () => `mock`
);
initStoryshots();
```
