### ISSUE TITLE
https://storybooks.js.org is not indexed by Google

### ISSUE THREAD

**Issue by brikou** [storybooks/storybook#963]
It is not possible to use Google to search for documentation, only homepage is indexed by Google. 

![image](https://cloud.githubusercontent.com/assets/383212/25474055/11d845b2-2b32-11e7-945b-a7ba9dc1cebd.png)

**Comment by shilman** [comment]
This is a known issue and a duplicate to this one: https://github.com/storybooks/storybooks.github.io/issues/5

Currently the way we are getting direct links in the old site to work on static github pages is to use a temporary 404 redirect hack. Thus the site is not getting indexed properly ☹️ . The proper fix is to redo the documentation site in something like gatsby and that's what I plan to do next.

Closing this to resume progress in the other issue.
