### ISSUE TITLE
Story.js not present in addons-info after prepublish

### ISSUE THREAD

**Issue by subpopular** [storybooks/storybook#968]
Clone repo, generated the dist dir for `addons-info` and got webpack error about missing Story.js. Seems its being ignored without case-sensitivity in prepublish.sh
```js
'--ignore tests,__tests__,test.js,stories/,story.jsx,story.js', 
```
Removing story.js and rebuilding seemed to fix it.

**Comment by subpopular** [comment]
https://github.com/storybooks/storybook/pull/973

**Comment by UsulPro** [comment]
done!
