### ISSUE TITLE
Consolidate examples from packages into top level `/examples` folder

### ISSUE THREAD

**Issue by theinterned** [storybooks/storybook#976]
There are examples of how to use the packages spread throughout the repo. This causes issues with circular dependencies as well as code quality issues due to repeated code in the example apps.

It would be great to consolidate all the examples into one or more example storybooks in the root-level [/examples](https://github.com/storybooks/storybook/tree/master/examples) directory.

These examples could then be deployed and made publicly accessible by linking from the readme and the https://storybooks.js.org/ website.

**Comment by tmeasday** [comment]
See also https://github.com/storybooks/storybook/issues/1012

**Comment by ndelangen** [comment]
I'm going to mark this as done.. There are some remains, and we'll remove them over time. Path is clear: add things to the example/kitchen-sink.
