### ISSUE TITLE
CSS Modules & LESS

### ISSUE THREAD

**Issue by eduardoinnorway** [storybooks/storybook#978]
Did anyone got this working? Tried all suggestions given, and no luck at all.

**Comment by agustif** [comment]
Yeah, but it's easier if you already have the node_modules in your project I think... 

I'm not really sure how I got it working, but I forked a elixir phoenix react stylus webpack2 and made my own, getting rid of stylus but keeping react and adding semantic-ui-react and semantic-ui-less and building those assets with webpack.

Anyway, here's proof, it's beautiful that even .less has HMR, I mean I never had this kind of setup before, and react semantic ui is superb for frontend, me thinks.

In case you are interested, you can check out the repo https://github.com/agustif/webpacker-semantic-ui-less, or if you do prefer stylus and are not interested in semantic, check the repo I forked from: https://github.com/odiumediae/webpacker

![screenshot 2017-04-29 02 13 06](https://cloud.githubusercontent.com/assets/6601142/25553738/66357ab2-2c81-11e7-8de1-97154c2ee22e.png)

**Comment by ndelangen** [comment]
What suggestions have you followed?

You need to modify the webpack config and add a `style-loader`, `css-loader`, `less-loader` for `.less` files.

**Comment by thatjsguy** [comment]
Not that the `webpack.config.js` belongs in `.storybook` and that the Webpack supported version is currently 1.x NOT 2.x (big structural differences there). This is using `sass-resources-loader`, which I highly suggest. 

```javascript
const path = require('path');
const combineLoaders = require('webpack-combine-loaders');

module.exports = {
  sassResources: [
    path.resolve(__dirname, '../sass/scaffold.scss'),
  ],
  module: {
    loaders: [
      {
        test: /\.(s)?css$/,
        exclude: /node_modules/,
        include: [
          path.resolve(__dirname, '../components'),
          path.resolve(__dirname, '../sass')
        ],
        loader: combineLoaders([
          "style-loader",
          {
            loader: "css-loader",
            query: {
              allowMultiple: true,
              modules: true,
              localIdentName: "[name]__[local]___[hash:base64:5]",
              importLoaders: 1,
              sourceMap: true
            }
          },
          {
            loader: "sass-loader",
            query: {
              sourceMap: true
            }
          },
          "sass-resources-loader"
        ])
      }
    ]
  }
};
```
