### ISSUE TITLE
Webpack Deprecation Warning from latest master

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#984]
I get this warning every time I run storybook npm linked from the latest master.

```
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

Does something in the default webpack config need to be updated?

**Comment by ndelangen** [comment]
Thanks for giving master a try!

I've seen this message too! thanks for reporting it! There's some old webpack config still around, though everything seems operational for now.

I'm trying to track down where this is caused.

**Comment by ronderksen** [comment]
@ndelangen Put `process.traceDeprecation = true` in your webpack config to find out which loader is causing the issue.

**Comment by ndelangen** [comment]
Woot! thanks for the suggestion @ronderksen !

**Comment by ndelangen** [comment]
I think I might have fixed it, but I'm not sure: https://github.com/storybooks/storybook/pull/1008

**Comment by danielduan** [comment]
@ndelangen confirmed the deprecation warnings are gone
