### ISSUE TITLE
Slack-in appears to be down

### ISSUE THREAD

**Issue by dburles** [storybooks/storybook#994]
https://storybooks-slackin.herokuapp.com/ 😞

**Comment by ndelangen** [comment]
I can confirm, I do not have access to the code nor deployment of this.

@arunoda can you help? Anything you need, or I can do to help with this?

**Comment by ndelangen** [comment]
I fixed it!

**Comment by apipemc** [comment]
@ndelangen Slack-in continue to be down.

**Comment by ndelangen** [comment]
It's up here:
https://now-examples-slackin-nqnzoygycp.now.sh/

Heroku decided to disable the old url, and I cannot get it back.
