### ISSUE TITLE
Unexpected token, expected , 

### ISSUE THREAD

**Issue by natdm** [storybooks/storybook#999]
Running freshly installed storybook with `yarn run storybook` in my Create React App based application yields...

```js
ERROR in ./src/stories/index.js
Module build failed: SyntaxError: Unexpected token, expected , (8:13)

   6 | storiesOf('Welcome', module)
   7 |   .add('to Storybook', () => (
>  8 |     <Welcome showApp={linkTo('Button')}/>
     |              ^
   9 |   ));
  10 |
  11 | storiesOf('Button', module)

 @ ./.storybook/config.js 4:2-27

```

**Comment by UsulPro** [comment]
@natdm could you specify your OS and which way you installed Storybook (via `getstorybook` or manually)?

**Comment by natdm** [comment]
Apologies. macOS and yes, getstorybook.

**Comment by UsulPro** [comment]
Do you have any custom `.babelrc` or `webpack.config.js` in your project?
 Is it a fresh install of CRA + getstorybook or you installed it to an existing project?
In this case, could you try [this steps](https://github.com/storybooks/storybook/blob/master/CONTRIBUTING.md#reproductions) to check is it reproducible with default config?

**Comment by natdm** [comment]
To update, I blew out storybook, re-installed it after upgrading everything and it seems to work fine now.

**Comment by shilman** [comment]
Glad you sorted it out! Closing now, but feel free to re-open if you need to revisit.
